### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#3558] opened 2019-04-29 15:57 UTC
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.23.0-insiders`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/reds/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment] 2019-04-29 21:22
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/3213. Expected to be fixed in our next update.

**Closed as completed by sean-mcmanus** 2019-04-29 21:22 UTC
Labels: duplicate
