### ISSUE TITLE
How to refresh compile_commands.json

### ISSUE THREAD

**Issue by a5066987** [microsoft/vscode-cpptools#5937] opened 2020-08-08 08:43 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win10 10.0.19042.423
- VS Code Version: 1.48.0-insider
- C/C++ Extension Version: 0.29.0

I have a generated compile_commands.json file, and I configured it in c_cpp_properties.json. But every time I add some new files and re-generate compile_commands.json, the Intellisense shows a warning saying that there is no entry in the compile_commands.json for the new file. Sometimes I have to restart vscode to refresh it. 

Is it possible to manually make Intellisense refresh the compile_commands.json?

**Comment by michelleangela** [comment] 2020-08-10 23:59
Can you try running the command `C/C++: Rescan Workspace`? This will force to shut down and restart any IntelliSense process. To verify if the updated compile_commands.json is sent to the IntelliSense process, run `C/C++: Log Diagnostics`.

**Comment by Colengms** [comment] 2020-08-11 01:31
Hi @a5066987 .  The C/C++ extension should be monitoring your `compile_commands.json` file for changes.  I'm not able to repro an issue with this in a simple case.

Could you enable debug logging using `"C_Cpp.loggingLevel": "Debug"`, repo the issue, and check the C/C++ output for: `cpptools/didChangeCompileCommands: <file>` ?

If you are not seeing that output, it may be that we're failing to receive notification that the file has changed.  If you are receiving that output, there may be an issue with our parsing of the file.

Can you tell us more about how you have this set up?  Is `compile_commands.json` under your workspace folder, or outside of it?  Does the issue occur if the file is already open in the editor, or when opening the file after having added it?

**Comment by a5066987** [comment] 2020-08-11 04:05
@Colengms Basically I use [XMake](https://github.com/xmake-io/xmake) to generate compiler_commands.json and put it in .vscode. : https://xmake.io/#/plugin/builtin_plugins?id=generate-compiler_commands

The log is a little weird to me:
![image](https://user-images.githubusercontent.com/13390857/89855976-d5409b80-db4c-11ea-9804-760422bd7873.png)
147.insertion-sort-list.cpp is the new file.

@michelleangela I tried  running the command C/C++: Rescan Workspace as well as Reset Intellisense Database, no difference

**Comment by jeremyong** [comment] 2020-09-18 00:17
Perennial problem for me on Windows as well. With clang, no matter where I put the compile_commands.json file (workspace root, build folder etc) or however much I rescan or reset the intellisense database, the extension doesn't seem to find the file (compile definitions specified there are never picked up, resulting in a number of erroneous red squiggles). I don't have a minimal reproduction case, but it happens sporadically even for smaller projects.

![image](https://user-images.githubusercontent.com/250149/93540908-53dde500-f912-11ea-9e78-c4e277712b78.png)

Here for example, RP_WINDOWS is defined, there's a `-DRP_WINDOWS` compile flag in pretty much every compile command and as a sanity check, I ensured the cmake provider is used, the compile_commands.json file I literally copied everywhere just to rule out any problem with discovering it, reset the universe, rebuilt, latest vscode, latest extensions, I've even gone as far as doing a fresh install. Would love for VSCode to support C++ work, but I have no idea how people are able to use it right now unless there's something I'm missing. It certainly doesn't seem "turnkey."

**Comment by sean-mcmanus** [comment] 2020-09-18 00:22
@jeremyong Is your compileCommands property set somewhere? This bug is with updating compile commands, but your issue sounds like it's not working at all. If you have the configurationProvider set then compileCommands won't be used -- the configuration provider should provide the configuration info.

**Comment by jeremyong** [comment] 2020-09-18 00:23
I've tried changing the compile commands setting, but also removed the configuration provider, but also tried the built in cmake one (with setting the location to the workspace root).

**Comment by jeremyong** [comment] 2020-09-18 00:26
If you don't mind, I really think the extension needs to be smarter. The configuration space is far too large, and when researching this, there are a ton of settings that don't even apply depending on other settings in a some opaque "action at a distance" manner. This makes the documentation unclear and troubleshooting pretty much impossible. Even simple things like an indicator at the bottom saying where the extension is deriving its data from ("using compile_commands.json found at ...") or whatever would be useful.

**Comment by sean-mcmanus** [comment] 2020-09-18 00:28
We have a C/C++: Log Diagnostics command that can be used for diagnostics and you can set the C_Cpp.loggingLevel to "Debug" to get more logs in the C/C++ pane.

It sounds like the CMake Tools extension has an issue and isn't sending us the proper configuration info in your case. The logs mentioned above could be used to verify that.

**Comment by sean-mcmanus** [comment] 2020-09-18 00:33
But if you disabled the configuration provider, then the compileCommands not picking up the defines would be our bug -- we'd need to look at the logs mentioned previously.

**Comment by Colengms** [comment] 2020-09-18 00:51
@a5066987 Sorry for the delay.  I see that we received a notification that the file has changed (`cpptools/fileChanged`), but I do not see a `cpptools/didChangeCompileCommands` message indicating that we tried to parse it.  Could you attach the entire output from the C/C++ channel, as text rather than an image?  Also, could you post the contents of your `c_cpp_properties.json` file, so we can see how things are configured?

@jeremyong Are you using `compileCommands` in `c_cpp_properties.json` to specify the location of `compile_commands.json`? 
 That is how to enable its use and indicate exactly where it is.  (We don't scan for it to auto-detect it.)  If so, and you are seeing a similar issue as a5066987 with us not always handling changes to the file, could you please provide the same information requested?  (Content of `c_cpp_properties.json`, debug level output of C/C++ channel).  As you noted, configuration is very complex, mainly because we're trying to provide language services independently of build system.  So, knowing how things were configured and what was logged would help us understand what's happening.  `compileCommands` _should_ be an easy mode, as it tells us about every source file and exactly how to configure each one.

**Comment by jeremyong** [comment] 2020-09-18 01:02
I enabled debug logging and what I got is very strange. The correct define is actually sent in the source file that uses the header (so I know the compile_commands.json is being resolved properly):

```
sending compilation args for -SNIP-
  -SNIP-
  define: RP_WINDOWS
  -SNIP-
```

It then says `Shutting down IntelliSense server: -SNIP-` for that translation unit.

Immediately afterwards, it processes the header with essentially empty compile args.

```
sending compilation args for -SNIP-
  include: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include
  include: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\atlmfc\include
  include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um
  include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt
  include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared
  include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt
  include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt
  other: --header_only_fallback
  stdver: ms_c++17
  intelliSenseMode: msvc-x64
```

meaning the header is being analyzed independently of the source file that includes it. The source file, has red-squigglies everywhere despite the engine reporting no compilation issues with it. Furthermore, it later tries to post `Attempting to get defaults from compiler found on the machine: '/usr/bin/gcc'` ...

Note: I've tried changing compilers, windows, linux, fresh reinstall of visual studio 2019 on top of vs code. I'm not sure if I should be expecting this to work or not?

**Comment by a5066987** [comment] 2020-09-18 19:51
> @a5066987 Sorry for the delay. I see that we received a notification that the file has changed (`cpptools/fileChanged`), but I do not see a `cpptools/didChangeCompileCommands` message indicating that we tried to parse it. Could you attach the entire output from the C/C++ channel, as text rather than an image? Also, could you post the contents of your `c_cpp_properties.json` file, so we can see how things are configured?

@sean-mcmanus It's basically an infinite loop indicating the file has changed. But anyway I'll find time to get a complete output for you.

**Comment by sean-mcmanus** [comment] 2020-10-08 23:58
This might be the same issue as https://github.com/microsoft/vscode-cpptools/issues/6285 .

**Comment by michelleangela** [comment] 2020-12-09 19:00
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue.

**Closed as completed by michelleangela** 2020-12-09 19:00 UTC
Labels: question, Language Service, more info needed, Feature: Configuration, Feature: Compile Commands
