### ISSUE TITLE
High CPU usage on MacOS

### ISSUE THREAD

**Issue by davinci26** [microsoft/vscode-cpptools#6238] opened 2020-10-01 17:23 UTC
Type: General

The extension is consuming a lot of CPU on macOS Mojave

**Describe the bug**
- OS and Version: macOS Mojave 10.14.6
- VS Code Version: 1.49.0
- C/C++ Extension Version: v1.0.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

The CPU usage of cpptols process according to activity monitor is 99%.

**To Reproduce**
*Please include code sample and `task.json` files.*

Not sure how to repro

**Expected behavior**

Normal CPU usage.

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by davinci26** [comment] 2020-10-01 17:24
I understand that the bug might not be actionable with the current description but let me know how I can collect logs, memory dumps to make it actionable.

**Comment by michelleangela** [comment] 2020-10-01 23:29
@davinci26 

We have instructions on how to collect CPU analysis logs at https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues. Please follow the instructions for macOS.

It will also be helpful if you could provide a sample project in which this issue consistently reproduces, as well as any specific repro steps. For example, does this consistently reproduce only at the start of opening a project or were any operations done after opening a project?

**Comment by davinci26** [comment] 2020-10-08 18:34
[instrumentscli0.trace.zip](https://github.com/microsoft/vscode-cpptools/files/5350666/instrumentscli0.trace.zip) here is the request trace file

It happens when I work on https://github.com/envoyproxy/envoy

**Comment by davinci26** [comment] 2020-10-08 18:36
Just want to point out that this issues not only makes extension unusable but regrades the entire developer machine.

**Comment by michelleangela** [comment] 2020-10-09 23:01
@davinci26 
I cloned the project https://github.com/envoyproxy/envoy and saw that at initial open of a file in the project, the CPU usage was high and CPU work was from tag parsing include files. After the extension completed tag parsing the include files, the CPU usage dropped. The tag parsing only lasted a few seconds from when I opened the project and then opened file under the "source" subfolder. However, IntelliSense was not able to resolve the path of some include files as the IntelliSense configuration was not setup (or perhaps these missing include files are generated ones?).

The provided CPU trace also showed tag parsing work. What operation was done when the CPU trace was taken? Was it during initial open of the project? Does the CPU usage drop after tag parsing is done? You can enable the [language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) to see the logs of tag parsing. After tag parsing is done, there should be a log on "database safe to open".

**Comment by davinci26** [comment] 2020-10-13 17:38
@michelleangela the trace was not collected at startup but it was collected while I had the repository open (no particular operation was taking place). From the moment the extension gets loaded the CPU spikes and never drops.

Could it be something specific to bazel? I saw another issue that caused high cpu (#6149) and it is active.

**Comment by michelleangela** [comment] 2020-10-16 17:35
@davinci26 
There could be many factors to performance issues. Perhaps logs from the language server may give clues as to what files are being parsed that could be causing the issues. Could you also provide the following logs:

1. Log output from enabling the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server). This logging will show what files are getting parsed and show other work the language server is doing.
2. Log output from running the command `C/C++: Log Diagnostics` This logging will show the IntelliSense configuration for your folder. This will also help us replicate any custom configuration that needs to be applied when trying to reproduce the issue on our machine.

**Comment by michelleangela** [comment] 2020-10-16 17:38
Also, have you tried resetting the browse path database with the command `C/C++: Reset IntelliSense database` and see if that makes any difference?

**Comment by TylerADavis** [comment] 2021-02-22 19:32
I noticed the fans were running on my MacBook, and I opened Activity Monitor to see that cpptools was using 98% CPU. I've had VS Code closed on my Mac since last night (when I opened approx 50 different cpp files), so I am not sure why cpptools would be running and using so much CPU right now.

Please let me know if there is a better place for me to report this bug, or if there are some logs I could collect and provide. I am running macOS Big Sur, and my C/C++ for VS Code is 1.2.2-insiders2.

![image](https://user-images.githubusercontent.com/16804460/108759567-5ec02580-7501-11eb-853c-be80b7413f38.png)

**Comment by michelleangela** [comment] 2021-02-22 19:42
@TylerADavis 
Since there are different factors that could contribute to a performance issue, could you create a a new issue and provide the following logs:

1. Log output from [enabling the language server.](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) This logging will show what files are getting parsed and show other work the language server is doing.
2. Performance analysis logs (see https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues#macos)

**Comment by michelleangela** [comment] 2021-02-22 19:50
@TylerADavis do you also have a sample code or project that we could reproduce the issue with?

**Comment by PaperPrototype** [comment] 2021-02-25 01:06
I am having the same issue. for future readers how can I get this to turn off?

**Comment by sean-mcmanus** [comment] 2021-02-26 01:28
Is this issue fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2 ? That releases fixes a known infinite loop issue with certain code constructs.

**Comment by jayteemo** [comment] 2021-03-08 18:28
i am also seeing this issue with 1.2.2 of cpp tools.

```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by sean-mcmanus** [comment] 2021-03-09 01:13
@jayteemo High CPU usage is a general symptom which could have many causes -- can you create a new issue with more repro details to help us identify the cause of the CPU usage? See https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues

**Comment by dolphineye** [comment] 2021-03-16 17:43
I confirm I'm also having this issue on a regular basis, hence freezing the entire editor window. I personally have not any repro steps in mind, but if I were to find any, I will you guys let you know about this.

Thanks

**Comment by sean-mcmanus** [comment] 2021-03-16 21:17
@dolphineye If you don't have repro steps, it could also help to get a call stack (or perf trace) of the process that appears to be causing the issue. Also, what exactly do you mean by freezing of the editor window, do you mean:
1. The entire OS UI is frozen.
2. Just VS Code's UI entirely frozen (other apps are fine).
3. Just the VS Code editor window (other VS windows are not frozen).
And any info on why you believe the C/C++ extension is the cause of the freezing would help.

**Comment by dolphineye** [comment] 2021-03-17 09:48
Hi @sean-mcmanus ,

> it could also help to get a call stack (or perf trace) of the process that appears to be causing the issue. 

Any hints on getting that call stack / perf trace for you (I'm using the homebrew version of vscode).

> And any info on why you believe the C/C++ extension is the cause of the freezing would help.

I'm not exactly sure of what extensions are possibly causing the issue, but when the freezing occurs, I usually notice that a few vscode processes are eating the whole CPU time (mostly: either cpp-tools or sometimes the vscode renderer). 

So far, the only C/C++ that are enabled are:

* C/C++ IntelliSense, debugging, and code browsing.
* CMake langage support for Visual Studio Code

> Also, what exactly do you mean by freezing of the editor window, do you mean:

By frozen I mean that the entire vscode instance will stop responding for a short while (from a couple of seconds to tens of seconds) while the rest of the macOS apps and the system will continue working normally. Usually, that happens when I'm typing some code, then vscode will just stop responding for a while.

Ultimately, if that helps: we use Git in our project, with a few CMake dependencies.

Let me know how I can help to track down this issue.

Thanks

**Comment by sean-mcmanus** [comment] 2021-03-17 18:25
@dolphineye We have some instructions on how to get a call stack at https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv and how to get perf logs at https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues . However, since our extension runs out of process from the VS Code renderer, it is not expected that our extension would be the cause of a UI hang, particularly after just typing some code. This suggests the issue is caused by VS Code itself and there are guidelines for reporting VS Code performance issues at https://github.com/microsoft/vscode/wiki/Performance-Issues .

**Comment by dolphineye** [comment] 2021-03-20 01:55
Hi Sean,

As a matter of facts, it seems that disabling GPU acceleration solved my freeze issues so far.

Hope it will help anyone else, eventually.

Thanks for your help!

**Closed as completed** 2021-08-08 11:16 UTC
Labels: Language Service, more info needed, performance, investigate: repro
