### ISSUE TITLE
how to get the include path or define for c++ config 

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#8440] opened 2021-11-24 07:21 UTC
Type: Feature Request

https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference#_supported-variables we can get configName

and how can  I get the defines and other like include path for my task.json

**Comment by bobbrow** [comment] 2021-11-24 21:37
I believe this is a duplicate of #5038

**Closed as completed by bobbrow** 2021-11-24 21:37 UTC
Labels: duplicate, Language Service, Feature Request, Feature: Extension API
