### ISSUE TITLE
Macro definitions are not obtained from compiler when using `compilerPath` with `Tag Parser`

### ISSUE THREAD

**Issue by dodheim** [microsoft/vscode-cpptools#1771] opened 2018-04-01 10:19 UTC
My macro definitions are being set correctly when setting `compilerPath` in conjunction with the `Default` `intelliSenseEngine` setting, but for the handful of projects that demand `Tag Parser` they do not. I suspect that invoking the compiler may be bypassed with this engine since the include paths aren't needed, but the macro definitions still very much are. If this is by design it should be mentioned in the documentation. :-]

As an aside, why can't the browse paths be populated from the compiler's reported include paths, at least by default?

**Comment by sean-mcmanus** [comment] 2018-04-02 09:30
Yes, the tag parser engine won't pick up the defines or compilerPath defines. It's by design.

We have an internal work item to somehow get the browse.path to update based on the compilerPath. We could use this issue to track that.

**Comment by dodheim** [comment] 2018-04-02 09:31
Looking forward to it – thank you, Sean.

**Comment by bobbrow** [comment] 2018-04-19 23:17
I am actually doing the work to get browse.path to update based on compilerPath as part of #1338.  Shall I close this as a duplicate?

**Comment by sean-mcmanus** [comment] 2018-04-19 23:29
It doesn't matter to me.

**Comment by bobbrow** [comment] 2018-04-24 21:09
A preview of this is available in the [insiders build](https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.0-insiders) if you would like to try it out and provide feedback.

**Comment by bobbrow** [comment] 2018-05-08 17:43
This is fixed in 0.17.0.

**Closed as completed by bobbrow** 2018-05-08 17:43 UTC
Labels: Language Service, Feature Request, fixed
