### ISSUE TITLE
Switching the language from C to C++ doesn't have any effect on IntelliSense

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2764] opened 2018-11-02 20:56 UTC
...when using the language name in the status bar. Not sure if anyone cares about this. The workaround is to rename the file from .c to .cpp.

**Comment by bobbrow** [comment] 2020-11-12 22:52
Looks like a dupe of #2557

**Closed as completed by bobbrow** 2020-11-12 22:52 UTC
Labels: bug, Language Service
