### ISSUE TITLE
Child process creation (i.e. IntelliSense) can fail with 1.10.6

### ISSUE THREAD

**Issue by Scott169** [microsoft/vscode-cpptools#9431] opened 2022-06-11 02:37 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version:  Windows 10  19043.1741
- VS Code Version: 1.68.0
- C/C++ Extension Version: 1.10.5
- Other extensions you installed:
C/C++ Extension pack, Code Runner, Material Icon Theme, Remote - Containers, Remote - SSH, Remote - WSL, Tiny Light

- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

After updating to the latest version of C/C++ extension, the extension stuck at searching libs.

**Steps to reproduce**

1. Update to the latest version (1.10.5) of this extension
2. Restart vscode and open the same project or source file to use this newly installed extension
3. You can see that the info "searching IncludePath" does not disappear.

**Expected behavior**
After a while, the searching of includePath should complete.

**Screenshots**
Problem (in version 1.10.5):
![image](https://user-images.githubusercontent.com/38151815/173169011-f8de8f47-df82-4846-81d7-a8623c4f3347.png)

Expected (in version 1.9.8):
![image](https://user-images.githubusercontent.com/38151815/173169389-2924f28e-ae33-49aa-abb6-5eb6b39074aa.png)

**Comment by aillear** [comment] 2022-06-12 15:12
![图片](https://user-images.githubusercontent.com/91419191/173239444-ce92ad9b-1007-4fa6-a470-f774cb79dffb.png)
My version is 1.10.5,too. I had a allied problem, and it will show "Include file not found in browse.path.". My solution is to temporarily go back to the previous version.  But the werid thing is that this problem does not occur on my classmate's computer.

**Comment by sean-mcmanus** [comment] 2022-06-13 19:09
Unfortunately, we're not able to repro the issue, and I'm not sure what change could have caused this. Is the cpptools process using CPU while it is in this state? If so, can you attach a debugger to get a call stack? https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv . When you set C_Cpp.loggingLevel to "Debug" do you see any errors in the "C/C++" logging output? You could potentially try installing one of the older vsix's at https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools, such as 1.10.1 to see if that also repros the issue or not.

**Comment by sean-mcmanus** [comment] 2022-06-13 19:10
You could also try running the C/C++: Reset IntelliSense Database command.

**Comment by Scott169** [comment] 2022-06-14 15:29
I tried installing 1.10.1 and this problem also appeared. It seems that this bug was introduced in an early preview version of 1.10.

![圖片](https://user-images.githubusercontent.com/38151815/173616152-ea9a174f-632a-45cc-8045-75ff9370d881.png)

**Comment by Colengms** [comment] 2022-06-14 20:55
Hi @Scott169 .  I'm not able to repro this easily.  Could you enable `"C_Cpp.loggingLevel": "Debug"`, reload VS Code, repro the issue, then provide the output from the C/C++ Output channel?  Could you also provide the contents of your `c_cpp_properties.json` (if any) and any `C_Cpp.*` related settings set?

The `Searching include path...` string is related to tag parsing.  It's possible that if parsing doesn't complete it could prevent IntelliSense from starting up.  

After this has repro'ed, do other features of the extension work?  (Such as tools tips on hover, or formatting?)

Also, what compiler are you using (which would be providing the `iostream` header).  It's possible there could be a bug with parsing a specific system header.

**Comment by ilharp** [comment] 2022-06-15 01:11
I'm using [PlatformIO](https://github.com/platformio/platformio-vscode-ide) on Windows and found several bugs similar to this issue.

### 1. `C/C++ Configuration Warning` output prints errs when loading project:

![image](https://user-images.githubusercontent.com/20179549/173714014-52a057d1-f252-40b3-a99b-79503540edb1.png)

And here's `C/C++` output with debug level:

![image](https://user-images.githubusercontent.com/20179549/173715198-d943baba-55ff-46c1-89f8-c2aa972d39be.png)

It seems like `vscode-cpptools` can't get output from child process.

But in `v1.9.8` this works normally (although `vscode-cpptools` doesn't know what's `avr`):

![image](https://user-images.githubusercontent.com/20179549/173714743-6a2c09ac-f5bf-473d-8caf-acf3c9463cb6.png)

### 2. `C/C++` output prints errs when hovering any code (debug level):

![image](https://user-images.githubusercontent.com/20179549/173714185-187b7949-5ffc-4503-8242-cdc11b1369b0.png)

### 3. Try to format document using `clang-format` also cause errs:

![image](https://user-images.githubusercontent.com/20179549/173714301-ceba2d25-b2df-4b02-8895-86149873d7b2.png)

---

Downgrade to `v1.9.8` fixes all 3 errors above.

Downgrading to `v1.9.8` fixed all 3 errors above, which leads me believing that all errors are caused by some kind of one single bug, most likely which failed to read the `stdout` of child processes.

**Comment by sean-mcmanus** [comment] 2022-06-15 01:16
@ilharp Your PlatformIO issue is most likely https://github.com/microsoft/vscode-cpptools/issues/9434, which we will ship a fix for in the next hour or so.

**Comment by sean-mcmanus** [comment] 2022-06-15 01:17
@ilharp Umm...but it looks like you may be hitting this process creation issue as well, which is not fixed.

**Comment by sean-mcmanus** [comment] 2022-06-15 01:18
@ilharp Oh, https://github.com/microsoft/vscode-cpptools/issues/9434 is Linux/Mac-only, so it's unrelated to your issue on Windows.

**Comment by ilharp** [comment] 2022-06-15 01:21
![image](https://user-images.githubusercontent.com/20179549/173716031-1463300d-ac5f-4e24-b418-d6d918b61171.png)

![image](https://user-images.githubusercontent.com/20179549/173716135-82e2bfcb-845b-4904-977e-fecb8553b997.png)

Yep and I just create a new fresh folder, `Failed to spawn IntelliSense process:` still exists

**Comment by sean-mcmanus** [comment] 2022-06-15 17:37
We've identified a PR that fixed a CreateProcess bug on Windows (we thought may be Windows 7 only, but maybe other scenarios, possibly if there's a space in the username or something like that) that accidentally didn't make it into the release which possibly could fix the issue. We're planning to ship the fixes in 1.11.0 (pre-release) and if that fixes the issue we can backport it to 1.10.7.

**Comment by sean-mcmanus** [comment] 2022-06-15 18:18
Actually, we're now planning to ship 1.10.7 with the potential fix (later today). We know it fixes at least 2 CreateProcess-related bugs, we're just not 100% sure yet if it fixes this one.

**Comment by sean-mcmanus** [comment] 2022-06-15 19:46
I have reproed the bug and verified our pending 1.10.7 binaries fixes the issue (in which process creation fails...if there are issues not caused by process creation failing those would be different).

**Comment by sean-mcmanus** [comment] 2022-06-16 00:07
This is fixed with 1.10.7 -- if anyone is still experiencing other bugs, you should create a new issue.

**Closed as completed by sean-mcmanus** 2022-06-16 00:07 UTC
Labels: bug, Language Service, fixed, not reproing, regression
