### ISSUE TITLE
IntelliSense process crash with get_expr_rescan_info

### ISSUE THREAD

**Issue by energygreek** [microsoft/vscode-cpptools#4798] opened 2019-12-30 08:37 UTC
Type: General

 [ 2928.062584] Microsoft.VSCod[10232]: segfault at 3c ip 000000000075a793 sp 00007f7df17f6038 error 4 in Microsoft.VSCode.CPP.IntelliSense.Msvc.linux[400000+7d5000]
[ 2928.062592] Code: c6 86 48 01 00 00 04 48 89 8e 4c 01 00 00 c7 86 54 01 00 00 00 00 00 00 48 89 8e 58 01 00 00 48 c7 86 60 01 00 00 00 00 00 00 <48> 8b 48 3c 48 89 4e 3c 48 8b 48 44 48 89 4e 44 8a 80 48 01 00 00
[ 2928.062630] audit: type=1701 audit(1577694796.203:78): auid=1000 uid=1000 gid=985 ses=1 pid=10219 comm="Microsoft.VSCod" exe="/home/jimery/.vscode/extensions/ms-vscode.cpptools-0.26.3-insiders2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux" sig=11 res=1
[ 2928.071280] audit: type=1130 audit(1577694796.213:79): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@11-10245-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2931.225874] audit: type=1131 audit(1577694799.366:80): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@11-10245-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2936.475895] Microsoft.VSCod[10262]: segfault at 3c ip 000000000075a793 sp 00007fba72ff9038 error 4 in Microsoft.VSCode.CPP.IntelliSense.Msvc.linux[400000+7d5000]
[ 2936.475902] Code: c6 86 48 01 00 00 04 48 89 8e 4c 01 00 00 c7 86 54 01 00 00 00 00 00 00 48 89 8e 58 01 00 00 48 c7 86 60 01 00 00 00 00 00 00 <48> 8b 48 3c 48 89 4e 3c 48 8b 48 44 48 89 4e 44 8a 80 48 01 00 00
[ 2936.475969] audit: type=1701 audit(1577694804.616:81): auid=1000 uid=1000 gid=985 ses=1 pid=10250 comm="Microsoft.VSCod" exe="/home/jimery/.vscode/extensions/ms-vscode.cpptools-0.26.3-insiders2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux" sig=11 res=1
[ 2936.483003] audit: type=1130 audit(1577694804.623:82): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@12-10287-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2939.547584] audit: type=1131 audit(1577694807.690:83): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@12-10287-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2968.146904] Microsoft.VSCod[10361]: segfault at 3c ip 000000000075a793 sp 00007f8acd4cd038 error 4 in Microsoft.VSCode.CPP.IntelliSense.Msvc.linux[400000+7d5000]
[ 2968.146911] Code: c6 86 48 01 00 00 04 48 89 8e 4c 01 00 00 c7 86 54 01 00 00 00 00 00 00 48 89 8e 58 01 00 00 48 c7 86 60 01 00 00 00 00 00 00 <48> 8b 48 3c 48 89 4e 3c 48 8b 48 44 48 89 4e 44 8a 80 48 01 00 00
[ 2968.146974] audit: type=1701 audit(1577694836.290:84): auid=1000 uid=1000 gid=985 ses=1 pid=10349 comm="Microsoft.VSCod" exe="/home/jimery/.vscode/extensions/ms-vscode.cpptools-0.26.3-insiders2/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux" sig=11 res=1
[ 2968.154485] audit: type=1130 audit(1577694836.296:85): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@13-10374-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2970.940427] audit: type=1131 audit(1577694839.083:86): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@13-10374-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

**Describe the bug**
- OS and Version:  Arch Linux  5.4.6-arch3-1
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.3-insiders2 
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*
1. click pick definition of a virtual function

**Additional context**
i just use it for coding and view

**Comment by sean-mcmanus** [comment] 2019-12-30 21:22
Are you able to get a crash call stack? Does it repro with 0.26.2?

**Comment by sean-mcmanus** [comment] 2019-12-30 21:23
Or can you provide a code sample that causes the crash and details on what compilerPath is being used? (Using -E to generate a single file without any #include references would be the most useful).

**Comment by energygreek** [comment] 2019-12-31 12:00
```
Core was generated by `/home/jimery/.vscode/extensions/ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000073f033 in get_expr_rescan_info ()
[Current thread is 1 (Thread 0x7fd999ffb700 (LWP 51961))]
(gdb) thread apply all bt

Thread 12 (Thread 0x7fd99affd700 (LWP 51957)):
#0  0x00007fd9b339df7a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000093200e in neosmart::UnlockedWaitForEvent(neosmart::neosmart_event_t_*, unsigned long) ()
#2  0x0000000000932086 in neosmart::WaitForEvent(neosmart::neosmart_event_t_*, unsigned long) ()
#3  0x000000000092d409 in msvc::alertable_event::wait(unsigned int) ()
#4  0x000000000091d03a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<msvc::thread_pool::thread_pool()::$_0> > >::_M_run() ()
#5  0x00000000009822ef in execute_native_thread_routine ()
#6  0x00007fd9b33974cf in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007fd9b32c62d3 in clone () from /usr/lib/libc.so.6

Thread 11 (Thread 0x7fd9b0992700 (LWP 51954)):
#0  0x00007fd9b339dc45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00000000009ad6bc in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#2  0x0000000000574d96 in edge::an_edge_translation_unit_impl::compile_declaration(snapshot_session_id, a_canonicalized_file_name, wchar_t const*, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, a_declaration_context const&, a_tracked_region_kind, a_region_scope_info const&, bool, bool, bool, bool*, edge::query_action_data&) ()
#3  0x00000000005683bb in edge::scoped_query_manager::check_and_compile(edge::file_position const&, edge::file_position const&, edge::file_position const&, bool, bool) ()
#4  0x0000000000567c70 in edge::scoped_query_manager::update_fragment(edge::file_position const&, edge::file_position const&, edge::file_position const&, bool, bool, bool) ()
#5  0x000000000057cb06 in edge::an_edge_translation_unit_impl::update_range(edge::allocator*, snapshot_session_id, edge::file_position, edge::file_position, edge::update_range_options const&, edge::file_position, unsigned long*, unsigned long*, an_array_list<edge::update_range_action*, std::allocator<edge::update_range_action*> > const&, edge::query_action_data&) ()
#6  0x000000000057dfc6 in edge::translation_unit::update_range(edge::allocator*, snapshot_session_id, edge::file_position, edge::file_position, edge::update_range_options const&, edge::file_position, unsigned long*, unsigned long*, an_array_list<edge::update_range_action*, std::allocator<edge::update_range_action*> > const&, edge::query_action_data&) ()
#7  0x0000000000544c00 in edge_intellisense_server_impl::update_range(char const*, bool, bool, bool) ()
#8  0x000000000052cead in edge_intellisense_server_impl::handle_update_intellisense(microsoft::cpp::intellisense::UpdateIntelliSenseRequest const&) ()
#9  0x0000000000555a6d in work_queue::worker_proc() ()
#10 0x000000000091d0a2 in std::_Function_handler<void (), msvc::thread_pool::enqueue(std::function<void ()>, std::future<void>*)::$_2>::_M_invoke(std::_Any_data const&) ()
#11 0x000000000091bd04 in msvc::thread_pool::do_work(unsigned long) ()
#12 0x00000000009822ef in execute_native_thread_routine ()
#13 0x00007fd9b33974cf in start_thread () from /usr/lib/libpthread.so.0
#14 0x00007fd9b32c62d3 in clone () from /usr/lib/libc.so.6

Thread 10 (Thread 0x7fd9b3197700 (LWP 51949)):
#0  0x00007fd9b339dc45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000093262c in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x000000000092d56b in msvc::alertable_event::wait_for_multiple(msvc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x000000000091bc12 in msvc::thread_pool::do_work(unsigned long) ()
#4  0x00000000009822ef in execute_native_thread_routine ()
#5  0x00007fd9b33974cf in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007fd9b32c62d3 in clone () from /usr/lib/libc.so.6

Thread 9 (Thread 0x7fd99bfff700 (LWP 51955)):
#0  0x00007fd9b339dc45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#1  0x000000000093262c in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x000000000092d56b in msvc::alertable_event::wait_for_multiple(msvc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x000000000091bc12 in msvc::thread_pool::do_work(unsigned long) ()
#4  0x00000000009822ef in execute_native_thread_routine ()
#5  0x00007fd9b33974cf in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007fd9b32c62d3 in clone () from /usr/lib/libc.so.6

Thread 8 (Thread 0x7fd99a7fc700 (LWP 51958)):
#0  0x00007fd9b33a168c in read () from /usr/lib/libpthread.so.0
#1  0x000000000092d915 in async_pipe_nix::read_sync_impl(std::string&) ()
#2  0x000000000092dac8 in async_pipe_nix::read_thread_proc() ()
#3  0x00000000009822ef in execute_native_thread_routine ()
#4  0x00007fd9b33974cf in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fd9b32c62d3 in clone () from /usr/lib/libc.so.6

Thread 7 (Thread 0x7fd9b3198740 (LWP 51947)):
#0  0x00007fd9b339dc45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000093262c in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x000000000092d56b in msvc::alertable_event::wait_for_multiple(msvc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x0000000000919a40 in comm_server::wait_for_requests() ()
#4  0x0000000000551e8e in main ()

Thread 6 (Thread 0x7fd9b2996700 (LWP 51950)):
#0  0x00007fd9b339dc45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000093262c in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x000000000092d56b in msvc::alertable_event::wait_for_multiple(msvc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x000000000091bc12 in msvc::thread_pool::do_work(unsigned long) ()
#4  0x00000000009822ef in execute_native_thread_routine ()
#5  0x00007fd9b33974cf in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007fd9b32c62d3 in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7fd9b1994700 (LWP 51952)):
#0  0x00007fd9b339dc45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000093262c in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x000000000092d56b in msvc::alertable_event::wait_for_multiple(msvc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x000000000091bc12 in msvc::thread_pool::do_work(unsigned long) ()
#4  0x00000000009822ef in execute_native_thread_routine ()
#5  0x00007fd9b33974cf in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007fd9b32c62d3 in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7fd9b2195700 (LWP 51951)):
#0  0x00007fd9b339dc45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000093262c in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x000000000092d56b in msvc::alertable_event::wait_for_multiple(msvc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x000000000091bc12 in msvc::thread_pool::do_work(unsigned long) ()
#4  0x00000000009822ef in execute_native_thread_routine ()
#5  0x00007fd9b33974cf in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007fd9b32c62d3 in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7fd99b7fe700 (LWP 51956)):
#0  0x00007fd9b339dc45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000093262c in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x000000000092d56b in msvc::alertable_event::wait_for_multiple(msvc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x000000000091bc12 in msvc::thread_pool::do_work(unsigned long) ()
#4  0x00000000009822ef in execute_native_thread_routine ()
#5  0x00007fd9b33974cf in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007fd9b32c62d3 in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7fd9b1193700 (LWP 51953)):
#0  0x00007fd9b339dc45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000093262c in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x000000000092d56b in msvc::alertable_event::wait_for_multiple(msvc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x000000000091bc12 in msvc::thread_pool::do_work(unsigned long) ()
#4  0x00000000009822ef in execute_native_thread_routine ()
#5  0x00007fd9b33974cf in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007fd9b32c62d3 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7fd999ffb700 (LWP 51961)):
#0  0x000000000073f033 in get_expr_rescan_info ()
#1  0x0000000000710289 in rescan_expr_with_substitution_internal ()
#2  0x000000000072af0d in rescan_expr_with_substitution ()
#3  0x0000000000789624 in copy_template_param_expr ()
#4  0x000000000078d925 in copy_template_param_con_with_substitution ()
#5  0x00000000008b2199 in substitute_template_argument ()
#6  0x00000000008b181f in copy_template_arg_list_with_substitution ()
#7  0x00000000008b2c0f in copy_template_class_reference_with_substitution ()
#8  0x00000000008ae1c4 in copy_type_with_substitution ()
#9  0x00000000008b25b5 in copy_parent_type_with_substitution ()
#10 0x00000000008ada80 in copy_type_with_substitution ()
#11 0x00000000008b1fe8 in substitute_template_argument ()
#12 0x00000000008b45a0 in all_templ_params_have_values ()
#13 0x00000000008a5566 in wrapup_template_argument_deduction ()
#14 0x00000000008a5346 in wrapup_function_template_argument_deduction ()
#15 0x0000000000860318 in determine_function_viability ()
#16 0x0000000000842ff2 in try_overloaded_function_match ()
#17 0x0000000000841ead in conversion_to_class_possible ()
#18 0x00000000008538a8 in user_defined_conversion_possible ()
#19 0x0000000000854f56 in conversion_possible ()
#20 0x0000000000854b65 in prep_elision_initializer_operand ()
#21 0x000000000070e545 in scan_return_expression ()
#22 0x00000000008828c3 in statement ()
#23 0x000000000087e2e9 in compound_statement_full ()
#24 0x000000000087fde2 in statement ()
#25 0x00000000008826be in statement ()
#26 0x000000000087e1b9 in compound_statement_full ()
#27 0x0000000000771ac0 in scan_function_body ()
#28 0x0000000000774919 in function_definition ()
#29 0x00000000006c0420 in scan_nonmember_declaration ()
#30 0x00000000006c482b in namespace_declaration ()
#31 0x00000000006bcb65 in scan_nonmember_declaration ()
#32 0x00000000006c257a in declaration ()
#33 0x00000000005b2afa in compile_fragment((anonymous namespace)::a_fragment_buffer const&, a_canonicalized_file_name, unsigned long, unsigned long, unsigned long, bool, a_declaration_context const&, a_region_scope_info const&, std::vector<std::string, std::allocator<std::string> > const&, bool, bool, bool, bool*) ()
#34 0x00000000005b052d in before_tu_wrapup ()
#35 0x00000000008e40fa in process_translation_unit ()
#36 0x0000000000626ba7 in cfe_main ()
#37 0x0000000000903c06 in cfe_main_exception_handler ()
#38 0x0000000000626cb6 in edg_main ()
#39 0x00000000008ff06a in edge_compiler_main(int, char const**) ()
#40 0x00000000005b0afd in preparse(int, char const**, a_scout_store*, edge::translation_unit*) ()
#41 0x000000000057d2b6 in a_compiler_thread::compiler_thread_routine(a_compiler_thread*) ()
#42 0x00000000009822ef in execute_native_thread_routine ()
#43 0x00007fd9b33974cf in start_thread () from /usr/lib/libpthread.so.0
#44 0x00007fd9b32c62d3 in clone () from /usr/lib/libc.so.6

```

**Comment by energygreek** [comment] 2019-12-31 12:01
ms-vscode.cpptools-0.26.2 and ms-vscode.cpptools-0.26.3 both have this problem.

**Comment by sean-mcmanus** [comment] 2019-12-31 20:49
Thanks a lot for bringing this to our attention. It looks like one of our top crashes, also repros with VS, and not a recent regression. An isolated repro of a code sample that causes the crash would be helpful.

UPDATE: Looks like we need to somehow find a code sample that repros this crash in order to fix it.

**Comment by sean-mcmanus** [comment] 2020-03-04 03:11
Fixed in our latest Insiders release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders.

**Closed as completed** 2020-06-03 02:11 UTC
Labels: bug, Language Service, fixed, reliability, Visual Studio
