### ISSUE TITLE
Intellisense database residing on remote-ssh host is recreated at times

### ISSUE THREAD

**Issue by kartikeyshetty** [microsoft/vscode-cpptools#4969] opened 2020-02-14 07:58 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS 10.15.3 & RHEL 7 on remote-ssh extension
- VS Code Version: 1.42.0
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them): ms-vscode-remote.remote-ssh-edit version 0.49.0

I use the "remote-ssh" plugin to connect to a RHEL 7 machine hosting a large C codebase ( around 10 GB). I use the C++ extension for code completion and have seen the Intellisense database grow to about 4GB in size. But i have noticed, atleast twice, when reconnecting to the same workspace the Intellisense database shrinks in size and seems to index all over again. A look at the C/C++ logs revealed these two lines:

`Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)`

I do not know what a database safety check entails. So how do i decipher these lines ? How can i prevent the recreation of the DB ?

Thanks

**Comment by sean-mcmanus** [comment] 2020-02-14 19:55
If you set C_Cpp.loggingLevel to "Debug" and view the C/C++ panel and look for text "Database safe to open" and no further "tag parsing file" messages appear, then it's safe to exit. If the process crashes, then it's possible the safety check won't be written. If you edit a file and then do a Reload Window or close VS Code before the safety check is written (after 5 seconds) then the database safety check will fail (if our normal process exit code isn't run) -- not sure yet if that is fixable or not, i.e. VS Code may be abnormally terminating our processes before we can safely shutdown our database.

**Comment by sean-mcmanus** [comment] 2020-02-14 20:17
Actually, it looks like under normal exit conditions we are writing the safety check. Let us know if you find a repro where we aren't -- i.e. if we're unable to cleanly shutdown before VS Code kills our process.

**Comment by kartikeyshetty** [comment] 2020-02-19 10:03
Unfortunately i still haven't found a way to reproduce this consistently. But i see a case ( which may or may not be related to this particular issue) where the database is being cleaned and re-parsed.

We have a particularly large C codebase. When a user pulls this code from git and adds it as a workspace it takes 4-5 hours for the extension to index it completely . To get away with this substantial indexing time i make a copy of the aforementioned database and tweak the 'files' table to point to the right path and then add the workspace. I have assumed the rest of the database need no changes. 

But in this case too, the modified database is re-parsed from start. Whats interesting is that the log suggests the safety check is fine and the files are processed but the extension still goes on to tag parsing them all over again

`Discovering files...
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /workspace/copied
  Discovering files: **41012 file(s) processed**
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...`

I initially believed the re-parsing was because of the safety check failures; but it appears to be not so.

**Comment by sean-mcmanus** [comment] 2020-02-19 21:22
Your logging doesn't show tag parsing. It just shows that 41k files were found in the search phase. Are you saying the tag parsing occurs afterwards?

If you set your C_Cpp.loggingLevel to the hidden value of "7" (and maybe Reload Window) you should be able to see logs related to why a file needs to be re-tag parsed, such as the timestamp being different.

**Comment by michelleangela** [comment] 2020-12-09 18:50
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 18:50 UTC
Labels: bug, Language Service, more info needed, not reproing
