### ISSUE TITLE
${workspaceFolder}/** is auto-added when default.includePath is set and no c_cpp_properties.json exists

### ISSUE THREAD

**Issue by maxim-babenko** [microsoft/vscode-cpptools#5621] opened 2020-06-07 08:05 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version:
MacOS 10.15.4

- VS Code Version:
1.45.1

- C/C++ Extension Version:
0.28.2

- Other extensions you installed (and if the issue persists after disabling them):
Remote -- SSH 

- Does this issue involve using SSH remote to run the extension on a remote machine?:
Yes

- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

After VSCode is being used a while (say, couple of hours) Goto Symbol in Editor could take tens of seconds to show the list of symbols in the current file. Closing VSCode and killing all vscode-related processes on the remote machine, and then restarting everything back solves the issue... for some time.

Is there anything I could do to help diagnosing this? E.g. should I collect the logs when this feature becomes laggy?

Thanks in advance.

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment] 2020-06-08 22:14
You could set the C_Cpp.loggingLevel to "Debug", but my guess is that the logigng wouldn't show anything useful if the process is internal to the symbol processing thread.

Could you attach a debugger to cpptools when it's taking a long time and then break and look for a call stack that appears to have a lot of work/frames (i.e. not one of the many shallow thread call stacks that aren't really doing any work)?

**Comment by maxim-babenko** [comment] 2020-06-08 22:17
Thanks for the suggestion, I'll try to do that (and perhaps try to collect some perf tops).

**Comment by maxim-babenko** [comment] 2020-06-09 06:28
OK, here's what I've got after spending some time with top, perf and strace.

To give some initial context: our company stores most of its codebase in a huge monorepo. Its working copies are accessible via a fuse-powered filesystem.

It seems that my problems (or at least some of them) are not CPU-related. When goto symbol becomes laggy, I see (via strace) a huge number of FS-related syscalls, in particular stat, fstat, open, fcntl, read etc. Being backed by fuse, this is not likely to be fast.

Are there any caches in VS code that could help here? Currently it seems that each time I strike "goto symbol", VS code traverses the whole source tree starting from the current file.

Another strange thing I see is that "node" with "--type=watcherService" arguments keeps calling "inotify_add_watch" for files that are in explicitly blacklisted via files.watcherExclude directories. There are literally millions of them and this just can't scale properly.

**Comment by maxim-babenko** [comment] 2020-06-09 06:38
Also this watcher node process constantly gets kills due to OOM:
https://gist.github.com/maxim-babenko/9b3e608ba7ff96b99aaf5b897c5f2c33

Could it be possible that without watcher being available we fallback to direct FS scan?

**Comment by maxim-babenko** [comment] 2020-06-09 08:15
Changing watcherExclude to absolute paths seems to have helped me.
This oddity was also mentioned here:
https://github.com/microsoft/vscode/issues/29594

**Comment by sean-mcmanus** [comment] 2020-06-09 17:33
Go to symbol is supposed to use our database. Are you able to tell if the FS-related calls are to our database or other files? If it's to other files, then it seems likely the FS-related calls could be due to existing operations unrelated to the go to symbol that are just blocking the go to symbol, i.e. due to active parsing that is occurring. Our logging should probably have info on what existing operations are occurring.

It's possible the database is getting too large, although that implies that it's starting off smaller and growing (it should stay about the same size after the initial workspace parsing, unless something causes it to reset).

**Comment by maxim-babenko** [comment] 2020-07-29 10:30
I have upgraded to 0.29.0 but still suffer from this problem.

To me it seems related to the fact that cpptools is traversing files it should definitely not be touching at all.

Here's my code-workspace file:
https://gist.github.com/maxim-babenko/28326adad81b70b1a199b49f6a438b59

I'm seeing tons of newfstatat calls to files outside of the supposed indexing range.

Also here are some results of ls /proc/<pid>/fd I've obtained while cpptools was rebuilding its indexes.

$ ls -lht /proc/13378/fd
total 0
lrwx------ 1 babenko 64 Jul 29 13:18 0 -> socket:[814952859]
lrwx------ 1 babenko 64 Jul 29 13:18 1 -> socket:[814952861]
lr-x------ 1 babenko 64 Jul 29 13:18 10 -> /yt/nvme1/babenko/arc/store/.arc/objects/
lr-x------ 1 babenko 64 Jul 29 13:18 11 -> /yt/nvme1/babenko/arc/store/.arc/objects/37/



$ ls -lht /proc/13378/fd
total 0
lr-x------ 1 babenko 64 Jul 29 13:19 12 -> /yt/nvme1/babenko/arc/arcadia/alice/paskills/dialogovo/src/
lr-x------ 1 babenko 64 Jul 29 13:19 13 -> /yt/nvme1/babenko/arc/arcadia/alice/paskills/dialogovo/src/main/
lr-x------ 1 babenko 64 Jul 29 13:19 14 -> /yt/nvme1/babenko/arc/arcadia/alice/paskills/dialogovo/src/main/java/
lr-x------ 1 babenko 64 Jul 29 13:19 15 -> /yt/nvme1/babenko/arc/arcadia/alice/paskills/dialogovo/src/main/java/ru/
lr-x------ 1 babenko 64 Jul 29 13:19 16 -> /yt/nvme1/babenko/arc/arcadia/alice/paskills/dialogovo/src/main/java/ru/yandex/
lr-x------ 1 babenko 64 Jul 29 13:19 17 -> /yt/nvme1/babenko/arc/arcadia/alice/paskills/dialogovo/src/main/java/ru/yandex/alice/
lr-x------ 1 babenko 64 Jul 29 13:19 18 -> /yt/nvme1/babenko/arc/arcadia/alice/paskills/dialogovo/src/main/java/ru/yandex/alice/paskill/
lr-x------ 1 babenko 64 Jul 29 13:19 19 -> /yt/nvme1/babenko/arc/arcadia/alice/paskills/dialogovo/src/main/java/ru/yandex/alice/paskill/dialogovo/
lr-x------ 1 babenko 64 Jul 29 13:19 20 -> /yt/nvme1/babenko/arc/arcadia/alice/paskills/dialogovo/src/main/java/ru/yandex/alice/paskill/dialogovo/domain/

I see two big issues here:
1)  /yt/nvme1/babenko/arc/store/.arc/objects/ -- why cpptools is ever reaching this directory? The workspace folder is /yt/nvme1/babenko/arc/arcadia; cpptools should never be leaving it
2) /yt/nvme1/babenko/arc/arcadia/alice is explicitly blacklisted in files.exclude but cpptool is traversing it

**Comment by bobbrow** [comment] 2020-07-29 17:19
1. Do you have any symlinks that could be sending our indexer here?
2. We may traverse some paths but we won't parse the actual files in those paths if they are excluded.

If you enable "C_Cpp.loggingLevel": "Debug", our extension will print out the files that it is actually parsing in the Output Window (you have to select the "C/C++" log channel from the drop down box to see it).

**Comment by maxim-babenko** [comment] 2020-07-29 17:30
1. Not likely.
2. Our monorepo is pretty big, some millions of files in total. Like I mentioned before, we use FUSE for accessing it. So even traversing the whole source tree (via FUSE, again) could take quite a while; and it is not needed, in fact I expect vscode not to touch the directories listed in the exclusion list.

I have "C_Cpp.loggingLevel": "Debug" in my settings.json

**Comment by maxim-babenko** [comment] 2020-07-29 17:48
A complete log is here:
https://gist.github.com/maxim-babenko/13b66261e7e1309364432f16df3e9e1f

**Comment by maxim-babenko** [comment] 2020-07-29 18:02
OK, 1) above is more interesting; indeed there's a link
$ stat /home/babenko/arc/arcadia/.arc
  File: '/home/babenko/arc/arcadia/.arc' -> '/yt/nvme1/babenko/arc/store/.arc'

But .arc is in files.exclude, so why does vscode follow it?

**Comment by maxim-babenko** [comment] 2020-07-30 19:01
@bobbrow any ideas on this?

Is there any documentation on how C++ indexer handles project folders/includes directories/exclusion lists?

Ultimately, I need to limit the directories the indexer is allowed to visit to a certain subset; are there any best practices here?

**Comment by bobbrow** [comment] 2020-07-30 19:07
We currently have some issues with symlinks which we plan to address in an upcoming release.  Unfortunately, I don't have a workaround for you right now.  To reduce the traversal, I think the extension would need to change its policy around cataloging files.

**Comment by maxim-babenko** [comment] 2020-07-30 19:13
Thank you for the response!

OK, I think I can live with the indexer always following the symlinks; anyway, the destination is a relatively small (in terms of the number of files) directory our VCS uses internally.

Another problem is that I'm seeing cpptools traversing parts of the project folder that are explicitly excluded; and this is not likely to be symlink-related. Is there any way to figure out why this is happening?

**Comment by bobbrow** [comment] 2020-07-30 19:38
Is the extension actually parsing those excluded files, or is it just doing a `stat` on them?  It's currently expected that it does `stat` on files under the paths you provide in `includePath` or `browse.path`.  The exclusion settings apply to all remaining operations like parsing, symbol search, etc.  To stop the extension from `stat`ing these files requires the policy change I was referring to earlier.

**Comment by maxim-babenko** [comment] 2020-07-30 19:51
Oh, I see. I'm not seeing any reads in strace, just stat-related calls. Hence it seems that the behavior is as expected. Still it takes _a lot_ of time for this traversal to finish so I'm looking forward to the improvements you mentioned. Are there any issues I could subscribe to not to miss the relevant release?

**Comment by bobbrow** [comment] 2020-07-30 22:53
I'm renaming this issue to cover the policy change.  If you want to subscribe to any of the symlink bugs, you can search for issues with the "symlink" label on them.

**Comment by maxim-babenko** [comment] 2020-08-01 13:58
Is there any ETA for this task?

**Comment by bobbrow** [comment] 2020-08-03 17:39
Sorry, no.  We do not set ETAs on tasks until they are selected into a release milestone.

**Comment by maxim-babenko** [comment] 2020-08-03 21:03
Just to make sure we're on the same page:
* currently there's no way to avoid cpptools traversing the whole project folder
* C_Cpp.exclusionPolicy=checkFolders makes no difference here

Did I get everything correct?

Is there any way to figure out the exact list of files that were _indexed_ by cpptools (just to verify that nothing redundant was actually processed)?

**Comment by bobbrow** [comment] 2020-08-03 23:43
> Just to make sure we're on the same page:
> * currently there's no way to avoid cpptools traversing the whole project folder
> * C_Cpp.exclusionPolicy=checkFolders makes no difference here

You can avoid traversing the whole project folder by picking specific subfolders to parse in the `browse.path` property in `c_cpp_properties.json` instead of `${workspaceFolder}`.  You can avoid traversing sub folders by placing an asterisk at the end of any path in that array.  For example:
```jsonc
  "browse": {
    "path": [
      "${workspaceFolder}/folderA/*",          <-- only the contents of folderA are looked at and not any of its subfolders
      "${workspaceFolder}/folderA/subfolder1"  <-- subfolder1 and all of its subfolders are traversed
      "${workspaceFolder}/folderB"             <-- folderB and all of its subfolders are traversed
    ]
  }
```
The exclusion policy setting only applies to file parsing, not indexing.

If you set the `C_Cpp.loggingLevel` to the hidden value of `"7"` (make sure it's a string), and reset the database, we will print a message for every file we add to the database.  It starts with the text: "update_file_if_needed".  There will be a lot of text to sift through though.

Another option is to open the database file in a SQLite viewer of some kind and look at the "Files" table.  Anything with a timestamp of 0 was indexed, but not parsed.

**Comment by maxim-babenko** [comment] 2020-08-04 07:25
Thanks for the pointers!

Will vscode still be traversing folders listed in C_Cpp.default.includePath?

**Comment by maxim-babenko** [comment] 2020-08-04 07:34
I tried listing the relevant directories in browse.path and now it's for the first time that VSCode is able to complete the indexing process (I see no HDD icon in the status bar).

However now I'm getting no intellisense in many files and "Updating intellisense" flame icon is ON forever.

C++ debug logs contain the phases

IntelliSense client not available, using Tag Parser for go to definition.
IntelliSense client not available, using Tag Parser for quick info.
using Tag Parser for quick info

Could you please help in diagnosing the issue?

**Comment by maxim-babenko** [comment] 2020-08-04 07:58
After 10 mins of background activity I see the following in the log:
Update IntelliSense time (sec): 683.689

Hopefully it's a one-time scenario.

**Comment by sean-mcmanus** [comment] 2020-08-04 20:37
I haven't followed this entire discussion, but it sounds like this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/3123 . Our initial file enumeration code doesn't check files.exclude until later on.

**Comment by bobbrow** [comment] 2020-08-05 20:49
> Will vscode still be traversing folders listed in C_Cpp.default.includePath?

`C_Cpp.default.includePath` is included in the search only in cases where `browse.path` is not set.  The other requirement is that `includePath` is not set or `includePath` contains the string "${default}".

> After 10 mins of background activity I see the following in the log:
> Update IntelliSense time (sec): 683.689
> 
> Hopefully it's a one-time scenario.

Wow, that's impossibly slow!  Please let us know if you continue to see that.  If so, please share the steps you followed to make it happen so we can debug it.

**Comment by bobbrow** [comment] 2020-08-05 20:59
@maxim-babenko, if #3123 looks like the same issue to you, we will close this one and track the issue there.

**Comment by maxim-babenko** [comment] 2020-08-06 13:34
I don't think #3123 is the duplicate. It is certainly related as I do not want cpptools to follow the links blindly, but it's not the only issue here.

I still struggle to avoid cpptools traversing the irrelevant parts of my codebase.

My current workplace settings are
https://gist.github.com/maxim-babenko/4b76d78ec91f5c489c59113ae14dd579

As per your advice, I listed the relevant paths in C_Cpp.default.browse.path, please see the gist above.
But I definitely notice cpptools process traversing folders that are outside of the list, e.g.

lr-x------ 1 babenko dpt_yandex_infra_tech_ytdev 64 Aug  6 16:30 3 -> /yt/nvme1/babenko/arc/arcadia/mobile
lr-x------ 1 babenko dpt_yandex_infra_tech_ytdev 64 Aug  6 16:30 4 -> /yt/nvme1/babenko/arc/arcadia/mobile/weather
lr-x------ 1 babenko dpt_yandex_infra_tech_ytdev 64 Aug  6 16:30 5 -> /yt/nvme1/babenko/arc/arcadia/mobile/weather/android
lr-x------ 1 babenko dpt_yandex_infra_tech_ytdev 64 Aug  6 16:30 6 -> /yt/nvme1/babenko/arc/arcadia/mobile/weather/android/weather-app
lr-x------ 1 babenko dpt_yandex_infra_tech_ytdev 64 Aug  6 16:30 7 -> /yt/nvme1/babenko/arc/arcadia/mobile/weather/android/weather-app/app
lr-x------ 1 babenko dpt_yandex_infra_tech_ytdev 64 Aug  6 16:30 8 -> /yt/nvme1/babenko/arc/arcadia/mobile/weather/android/weather-app/app/src
lr-x------ 1 babenko dpt_yandex_infra_tech_ytdev 64 Aug  6 16:30 9 -> /yt/nvme1/babenko/arc/arcadia/mobile/weather/android/weather-app/app/src/main

Why is it even going to  /yt/nvme1/babenko/arc/arcadia/mobile? The latter is _not_ in browse.path and there are no symlinks there.

**Comment by bobbrow** [comment] 2020-08-06 20:32
Did you delete your `c_cpp_properties.json` or replace the contents of `browse.path` with `["${default}"]`?  `C_Cpp.default.browse.path` won't be used if it is overridden by some other value in `c_cpp_properties.json`

**Comment by maxim-babenko** [comment] 2020-08-08 16:06
I don't have c_cpp_properties.json.
C_Cpp.default.browse.path is set in my workspace file.

I don't believe VSCode just ignores browse.path since I see exactly these paths listed in "Folder ... will be indexed" and "Processing folder (recursive)" messages.

Still during Intellisense update (flame icon) strace + procfs clearly show that cpptools is touching "unwanted" folders, e.g.
lr-x------ 1 babenko 64 Aug 8 19:03 13 -> /yt/nvme1/babenko/arc/arcadia/junk/mesteno/
lr-x------ 1 babenko 64 Aug 8 19:03 14 -> /yt/nvme1/babenko/arc/arcadia/junk/mesteno/xurma_deploy/

I tried attaching gdb to cpptools, here's the backtrace of the thread doing that traversal:
https://gist.github.com/maxim-babenko/68846c5d5bf7b8e750cd79c9218ed15a

**Comment by maxim-babenko** [comment] 2020-08-11 12:32
@bobbrow Any ideas on this could be happening? Should I attach some more diagnostics?

**Comment by sean-mcmanus** [comment] 2020-08-12 18:05
The root cause is the same as https://github.com/microsoft/vscode-cpptools/issues/3123 . The call stack at https://gist.github.com/maxim-babenko/68846c5d5bf7b8e750cd79c9218ed15a shows "recursive_directory_iterator_utf8" which generates a vector with all the files (include excluded ones), and that vector is only checked against files.exclude later in "parse_includes". The files are not read or processed, but if there are a huge number of files in excluded directories it can still take a long time to process.

**Comment by bobbrow** [comment] 2020-08-12 18:06
The callstack you shared shows that our recursive include processing thinks that one of your `#include` dependencies is in those folders.  Are you using `**` in any of your `includePath`s in `c_cpp_properties.json`?

When using this feature we will look up file names in the database that were collected by the indexer and if we find a valid path (i.e. the path starts with the `**` path from `includePath` and ends with the path part of the `#include` statement), then we will parse that file for its dependencies (other `#include` statements) and continue until we find all the dependencies for the source file you are editing.

**Comment by maxim-babenko** [comment] 2020-08-12 20:13
I'm not using ** in includePaths. My workspace settings are here:
https://gist.github.com/maxim-babenko/4b76d78ec91f5c489c59113ae14dd579

I have "${workspaceFolder}" in my include paths but it's not **recursive**, right? 

It is possible to find out (by means of some logging) the exact include path that vscode regards as being recursive?

**Comment by sean-mcmanus** [comment] 2020-08-12 23:41
If you run the C/C++: Log Diagnotics, you'll see that we are auto-adding "${workspaceFolder}/**". It appears to be a regression from https://github.com/microsoft/vscode-cpptools/pull/5413

**Comment by maxim-babenko** [comment] 2020-08-13 06:58
For me, the problem seems to vanish if I move browse and include paths from workspace defaults to c_cpp_properties.json. After this C/C++: log diagnostics starts showing some sane paths (exactly, mine, in fact).

**Comment by bobbrow** [comment] 2020-08-13 16:52
@sean-mcmanus can you open a new issue to track the regression?  We're using this issue to track implementation of files.exclude for scanning paths.

**Comment by sean-mcmanus** [comment] 2020-08-13 18:20
@maxim-babenko Yes, the "${workspaceFolder}/**" only gets auto-added if no c_cpp_properties.json exists.

@bobbrow Sure, I could do that, but I don't understand what "implementation of files.exclude for scanning paths" means...it sounds like you're saying there's an additional bug? Or is it the same as https://github.com/microsoft/vscode-cpptools/issues/3123 (that issue title mentions symlinks but the description says "The root problem is that we're not checking folder exclusions when we generate our initial list of directory entries"...maybe we could rename the title).

**Comment by bobbrow** [comment] 2020-08-13 20:24
If #3123 is the same thing, then can you fix the title of #3123 and then change the title of this one to deal with the regression issue?

**Comment by sean-mcmanus** [comment] 2020-08-13 21:24
@bobbrow Done.

**Comment by bobbrow** [comment] 2020-08-18 00:00
@elahehrashedi, PR #5413 added ${workspaceFolder}/** to the `includePath` when C_Cpp.default.includePath is set.
> `configuration.includePath = [rootFolder].concat(this.vcpkgIncludes).concat([defaultFolder]);`

We probably should have just set `configuration.includePath = defaultFolder` instead.

**Closed as completed** 2020-08-21 19:29 UTC
Labels: Language Service, Feature Request, fixed, performance, regression
