### ISSUE TITLE
Data breakpoints support please!

### ISSUE THREAD

**Issue by Ben136KBC** [microsoft/vscode-cpptools#11180] opened 2023-07-11 16:12 UTC
### Feature Request

Visual Studio Code supports data breakpoints, but this key basic awesome essential extension sadly still does not support this basic debugging feature available in nearly every other debugger.

In many debugging situations data breakpoints are simply essential, and for this reason we usually use tools other than Visual Studio Code. If data breakpoints were available, we would use Visual Studio Code more.

So many usability improvements are implemented for Visual Studio Code, yet this basic essential functionality is still missing.

Running under Windows developing for Windows.

PLEASE with sugar on top!

**Comment by WardenGnaw** [comment] 2023-07-11 20:00
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/8343

**Closed as not planned by WardenGnaw** 2023-07-11 20:00 UTC
