### ISSUE TITLE
0.26.0-insidersX freezes my laptop

### ISSUE THREAD

**Issue by DelphianOracle** [microsoft/vscode-cpptools#4400] opened 2019-10-08 07:07 UTC
Now I 'm use 0.25.1 and it works fine, but after update to 0.26.0-insidesX version, Microsoft.VSCode process which uses cpp extension, consumes all available resources, even the mouse cursor stops moving (12gb ram and CPU i5-4200U).

PS:
cat /etc/issue
Ubuntu 18.04.3 LTS \n \l

**Comment by vlkv** [comment] 2019-10-08 10:08
Me too. Please fix this ASAP.
![vscode_eats_all_memory](https://user-images.githubusercontent.com/146375/66387269-4f077600-e9cc-11e9-809a-b6346539fc5b.png)

C/C++ for Visual Studio Code Change Log
Version 0.26.0-insiders2: October 3, 2019

Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-29-generic

**Comment by vlkv** [comment] 2019-10-08 10:25
Oh, this issue is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4386

**Comment by bobbrow** [comment] 2019-10-08 16:39
Yes, we plan to release an update today with the fix.  We're sorry for the inconvenience!

**Closed as completed** 2019-10-08 20:17 UTC
Labels: bug, duplicate, Language Service, insiders

**Comment by sean-mcmanus** [comment] 2019-10-09 19:19
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0-insiders3 .
