### ISSUE TITLE
Linux launch.json errors/hangs

### ISSUE THREAD

**Issue by lzyang2000** [microsoft/vscode-cpptools#2816] opened 2018-11-13 07:17 UTC
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Debian GNU/Linux 9 (stretch)
- VS Code Version: 1.29.0 x64
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): Code Runner; Java Extension Pack; Python.  The issue still persists after disabling them.
- A clear and concise description of what the bug is.
  The debugger would hang there doing nothing though the program is built successfully with the output file. Can access gdb in the built-in terminal.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Use launch.json
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.o",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "logging": {
                "engineLogging": true,
                "trace": true,
                "traceResponse": true
            },
            //"externalConsole": true,
            "MIMode": "gdb",
            "windows": {
                "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
                "miDebuggerPath": "C:/Program Files/mingw-w64/mingw64/bin/gdb.exe"
            },
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "Build",
        }
    ]
}`
build.json
`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "command": "g++",
            "args": [
                "-g",
                "-Wall",
                "-std=c++11",
                "-lm",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}.o"
            ],
            "windows": {
                "args": [
                    "-g",
                    "-Wall",
                    "-std=c++11",
                    "-lm",
                    "${file}",
                    "-o",
                    "${fileDirname}/${fileBasenameNoExtension}.exe"
                ]
            },
            "presentation": {
                "reveal": "always",
                "echo": false,
                "focus": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": "absolute",
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Run",
            "type": "shell",
            "dependsOn": "Build",
            "command": "${fileDirname}/${fileBasenameNoExtension}.o",
            "windows": {
                "command": "${fileDirname}/${fileBasenameNoExtension}.exe"
            },
            "args": [],
            "presentation": {
                "reveal": "always",
                "focus": true
            },
            "problemMatcher": [],
            "group": {
                "kind": "test",
                "isDefault": true
            }
        }
    ]
}`
2. Start dubugger
3. It outputs: launch.json:1: syntax error, without trace it hangs there.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by lzyang2000** [comment] 2018-11-13 07:42
To clear up the mess of code above I used a newer version of .json configurations. They are uploaded in txt format.

I am able to build with this, but the debugger would hang there.

[launch.txt](https://github.com/Microsoft/vscode-cpptools/files/2575090/launch.txt)
[tasks.txt](https://github.com/Microsoft/vscode-cpptools/files/2575091/tasks.txt)

**Comment by lzyang2000** [comment] 2018-11-13 20:14
[https://github.com/Microsoft/vscode-cpptools/issues/1527#issuecomment-364613612](https://github.com/Microsoft/vscode-cpptools/issues/1527#issuecomment-364613612)

The fix is confirmed working. Could someone please merge it into the next release?
[cpptools.zip](https://github.com/Microsoft/vscode-cpptools/files/2577886/cpptools.zip)

**Comment by pieandcakes** [comment] 2018-11-14 19:00
@lzyang2000 The overall problem is not fixed by that change. The problem is that it is sending a BOM and we are not expecting it. We have attempted to disable the sending of BOM by Windows but .NET framework doesn't seem to be allowing it. Our current workaround is to ask users to disable this Beta feature for now.

I don't know why that change would fix it for Linux though.

**Comment by lzyang2000** [comment] 2018-11-15 00:20
I don't know either... But now I could debug. For single files anyway.

**Comment by eegt** [comment] 2018-11-30 23:06
@pieandcakes I am running in Linux, saw the same symptoms, and the patch fixed mine as well. 
VSCode 1.29.1, commit ...37088e.
CentOS Linux release 7.5.1804 (Core)

**Comment by dcourtois** [comment] 2018-12-21 09:47
Hi, I'd like to report that I also have the same bug.

I'm on CentOS 7, using VSCode 1.30.0, and cpptools 0.20.1
I'm not using Linux very often so I don't know when this problem started to happen though (it worked fine until I recently updated VSCode and the extensions)

I can't launch anything using "cppdbg". It hangs forever. Enabling logging show the following output on the Debug Console:

```
1: (134) LaunchOptions  MIDebuggerPath='/home/dcourtois/Development/Tools/gdb-8.1/bin/gdb'
--> E (output): {"event":"output","body":{"category":"console","output":"1: (134) LaunchOptions  WaitDynamicLibLoad='false'\n"},"seq":14,"type":"event"}
1: (134) LaunchOptions  WaitDynamicLibLoad='false'
--> E (output): {"event":"output","body":{"category":"console","output":"1: (134) LaunchOptions  ExternalConsole='true'\n"},"seq":16,"type":"event"}
1: (134) LaunchOptions  ExternalConsole='true'
--> E (output): {"event":"output","body":{"category":"console","output":"1: (135) LaunchOptions>\n"},"seq":18,"type":"event"}
1: (135) LaunchOptions>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (135) LaunchOptions    <SetupCommands>\n"},"seq":20,"type":"event"}
1: (135) LaunchOptions    <SetupCommands>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (135) LaunchOptions        <Command IgnoreFailures='true' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command>\n"},"seq":22,"type":"event"}
1: (135) LaunchOptions        <Command IgnoreFailures='true' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (135) LaunchOptions    </SetupCommands>\n"},"seq":24,"type":"event"}
1: (135) LaunchOptions    </SetupCommands>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (136) LaunchOptions    <Environment>\n"},"seq":26,"type":"event"}
1: (136) LaunchOptions    <Environment>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (136) LaunchOptions        <EnvironmentEntry Name='LD_LIBRARY_PATH' Value='/home/dcourtois/Development/Tools/gcc-8.1.0/lib64:$LD_LIBRARY_PATH' />\n"},"seq":28,"type":"event"}
1: (136) LaunchOptions        <EnvironmentEntry Name='LD_LIBRARY_PATH' Value='/home/dcourtois/Development/Tools/gcc-8.1.0/lib64:$LD_LIBRARY_PATH' />
--> E (output): {"event":"output","body":{"category":"console","output":"1: (136) LaunchOptions    </Environment>\n"},"seq":30,"type":"event"}
1: (136) LaunchOptions    </Environment>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (136) LaunchOptions</LocalLaunchOptions>\n"},"seq":32,"type":"event"}
1: (136) LaunchOptions</LocalLaunchOptions>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) DbgCmd:echo $$ > /tmp/Microsoft-MIEngine-Pid-gwdzxnjv.ti3 ; cd /home/dcourtois/Development/Misc/RayTracing/Output/vscode ; DbgTerm=`tty` ; set -o monitor ; trap 'rm /tmp/Microsoft-MIEngine-In-pabgbv1h.uc7 /tmp/Microsoft-MIEngine-Out-6igwe9ot.l3k /tmp/Microsoft-MIEngine-Pid-gwdzxnjv.ti3 /tmp/Microsoft-MIEngine-Cmd-9nqk507a.xzp' EXIT ; /home/dcourtois/Development/Tools/gdb-8.1/bin/gdb --interpreter=mi --tty=$DbgTerm < /tmp/Microsoft-MIEngine-In-pabgbv1h.uc7 > /tmp/Microsoft-MIEngine-Out-6igwe9ot.l3k & clear; pid=$! ; echo $pid > /tmp/Microsoft-MIEngine-Pid-gwdzxnjv.ti3 ; wait $pid; \n"},"seq":34,"type":"event"}
1: (229) DbgCmd:echo $$ > /tmp/Microsoft-MIEngine-Pid-gwdzxnjv.ti3 ; cd /home/dcourtois/Development/Misc/RayTracing/Output/vscode ; DbgTerm=`tty` ; set -o monitor ; trap 'rm /tmp/Microsoft-MIEngine-In-pabgbv1h.uc7 /tmp/Microsoft-MIEngine-Out-6igwe9ot.l3k /tmp/Microsoft-MIEngine-Pid-gwdzxnjv.ti3 /tmp/Microsoft-MIEngine-Cmd-9nqk507a.xzp' EXIT ; /home/dcourtois/Development/Tools/gdb-8.1/bin/gdb --interpreter=mi --tty=$DbgTerm < /tmp/Microsoft-MIEngine-In-pabgbv1h.uc7 > /tmp/Microsoft-MIEngine-Out-6igwe9ot.l3k & clear; pid=$! ; echo $pid > /tmp/Microsoft-MIEngine-Pid-gwdzxnjv.ti3 ; wait $pid; 
--> C (runInTerminal-36): {"command":"runInTerminal","arguments":{"kind":"external","title":"cppdbg: RayTracing","cwd":"","args":["sh","/tmp/Microsoft-MIEngine-Cmd-9nqk507a.xzp"],"env":{"LD_LIBRARY_PATH":"/home/dcourtois/Development/Tools/gcc-8.1.0/lib64:$LD_LIBRARY_PATH"}},"seq":36,"type":"request"}
--> E (output): {"event":"output","body":{"category":"console","output":"1: (243) Wait for connection completion.\n"},"seq":38,"type":"event"}
1: (243) Wait for connection completion.
```

Note that [the fix mentioned by lzyang2000](https://github.com/Microsoft/vscode-cpptools/issues/1527#issuecomment-364613612) also fixes the issue.
Is there a way the aforementioned "potential fix" could be merged ? It doesn't seem to fix the original issue it was posted on, but apparently it fixes this one :)

**Comment by IOOOTAlan** [comment] 2019-02-07 16:42
Have this issue too on vs code 1.30.1 on Linux_x64.

The fix reported by @lzyang2000 solves the issue for me too: I now see an xterm window pop up when gdb is starting, then all seems to works ok.

**Comment by pieandcakes** [comment] 2019-02-15 23:13
I've commited the change and it will be in a future release. Thanks

**Closed as completed** 2019-02-15 23:13 UTC
Labels: debugger, investigate: repro
