### ISSUE TITLE
Inspect Tokens and Scopes infinite loading

### ISSUE THREAD

**Issue by jacobghunter** [microsoft/vscode-cpptools#9914] opened 2022-09-24 20:58 UTC
Type: <b>Bug</b>

This extention causes Developer: Inspect editor Tokens and Scopes to show "loading" infinitely.

Extension version: 1.13.0
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.86GB (18.48GB free)|
|Process Argv|\\\\wsl$\\Ubuntu\\root\\cs 302\\Homework\\homework2-jacobghunter --crash-reporter-id 563cd297-a8da-49d0-9c4c-3b91fd28e498|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30573243

```

</details>

**Comment by sean-mcmanus** [comment] 2022-09-26 19:02
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/9835 . See that issue for a workaround and you can add any more repro info to that if you want.

**Closed as not planned by sean-mcmanus** 2022-09-26 19:02 UTC
Labels: duplicate
