### ISSUE TITLE
Hover Tips can't handle GBK encoded characters correctly. 

### ISSUE THREAD

**Issue by HaujetZhao** [microsoft/vscode-cpptools#10222] opened 2022-12-04 02:40 UTC
### Environment

- OS and Version: Windows11 21H2
- VS Code Version: 1.73.1 (system setup)
- C/C++ Extension Version: v1.12.4
- Other extensions you installed (and if the issue persists after disabling them):  None, I disabled all of other extensions. 

### Bug Summary and Steps to Reproduce

Bug Summary:

In a single C file (encoded in GBK), while the VSCode UserSetting set  `"files.encoding": "gbk"`, the hover tooltip of a string contains Chinese can't show correctly. 

Seems to be a long fixed issue #414 , but it still exists. 

Steps to reproduce:

1. Open a folder in VS Code
2. In user setting, set `"files.encoding": "gbk",`
3. create a file `test.c`, which should be encoded in `gbk`
4. Type in these (copy paste suggested):

```c
#include <stdio.h>

int main()
{
    char str = "中文字符串 with gbk";
}
```

5. Hover mouse over the string, you can see nonsense characters in tooltip. Just like the pic below. 

### Expected behavior

Correct character shown in tooltip

### Code sample and Logs

```c
#include <stdio.h>

int main()
{
    char str = "中文字符串 with gbk";
}
```

logs: 

```log
Database safe to open
cpptools/getCodeActions: D:\Users\hauje\Desktop\csapp_test\test.c (id: 69)
textDocument/didOpen: D:\Users\hauje\Desktop\csapp_test\test.c
Checking for syntax errors: D:\Users\hauje\Desktop\csapp_test\test.c
Queueing IntelliSense update for files in translation unit of: D:\Users\hauje\Desktop\csapp_test\test.c
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: D:\Users\hauje\Desktop\csapp_test\test.c (id: 70)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
cpptools/getSemanticTokens: D:\Users\hauje\Desktop\csapp_test\test.c (id: 71)
cpptools/activeDocumentChange: D:\Users\hauje\Desktop\csapp_test\test.c
cpptools/getInlayHints: D:\Users\hauje\Desktop\csapp_test\test.c (id: 72)
cpptools/getFoldingRanges: D:\Users\hauje\Desktop\csapp_test\test.c (id: 73)
cpptools/getCodeActions: D:\Users\hauje\Desktop\csapp_test\test.c (id: 74)
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.271
cpptools/getFoldingRanges: D:\Users\hauje\Desktop\csapp_test\test.c (id: 75)
textDocument/hover: D:\Users\hauje\Desktop\csapp_test\test.c (id: 76)
```

### Screenshots

![image](https://user-images.githubusercontent.com/19181833/205471029-f22ac245-7603-47db-a8d9-8138194dc97f.png)

**Comment by Colengms** [comment] 2022-12-06 19:21
Hi @HaujetZhao .  I believe what you're seeing is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/8846

>The C/C++ extension does not currently attempt to interpret UTF-8 encoded sequences in char arrays as UTF-8 text, as not all char arrays in C/C++ can be assumed to contain UTF-8 encoded text. Instead, it's reflecting exactly what is in each character of that char array. While this does not match what printf will display after parsing the UTF-8 content, it's an accurate reflection of the contents of the array.

>However, when hovering over a string literal (not a char array), it does seem reasonable that we should display the same text as would be displayed by the current character encoding of that file. I'd like to use this issue to track that.

Consider up-voting that issue.  Closing this one as a duplicate.

**Closed as not planned by Colengms** 2022-12-06 19:21 UTC
