### ISSUE TITLE
Error message about 2 operator overloads where one is for const and the other is for not const

### ISSUE THREAD

**Issue by JackTimothy** [microsoft/vscode-cpptools#10450] opened 2023-02-01 19:04 UTC
### Environment

- OS and Version: Windows_NT x64 10.0.19042
- VS Code Version: 1.74.3
- C/C++ Extension Version: v1.13.9
- If using SSH remote, specify OS of remote machine: Linux Centos 7

### Bug Summary and Steps to Reproduce

Bug Summary: Error squiggle on using a C++ template class's `[]` operator overload complains that there are multiple operators matching the operands. There are two operators matching the operands, but one is defined as a const overloader and the other is not.

Steps to reproduce:
1. Write the following function:
```
#define FORMAT_TO_BUF(fmt_buf, fmt_str, ...) fmt::format_to(std::back_inserter(fmt_buf), FMT_COMPILE(fmt_str), ##__VA_ARGS__)

inline void end_json_object(fmt::memory_buffer &fmt_buf) 
{
    if (fmt_buf[fmt_buf.size() - 1] == ',') fmt_buf.resize(fmt_buf.size() - 1);
    FORMAT_TO_BUF(fmt_buf, "{}", "},");
}
```
2. See error:
`more than one operator "[]" matches these operands`

Expected behavior:
Because `fmt_buf` is not defined as a const reference, I would expect the non-const operator overload to be used and VS Code to not complain.

### Configuration and Logs

```shell
c_cpp_properties.json:

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/bin/gcc",
            "cStandard": "c89",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}
```
```


### Other Extensions

_No response_

### Additional context

_No response_

**Comment by Colengms** [comment] 2023-02-03 19:06
Hi @jtimothy-flexgen .  Could you provide a self-contained example that we can use to reproduce the problem, so we can investigate further?  I tried the following, but was not able to repro an issue:

```
class A
{
public:
    int operator[](int i);
    int operator[](int i) const;
};

void foo(A& a)
{
    if (a[0] == 1)
        ;
}
```

**Comment by jtimothy-flexgen** [comment] 2023-02-03 22:36
Here is a more focused example:
```
template <typename T> class buffer {
private:
    T* ptr_;
public:
    template <typename I> constexpr auto operator[](I index) -> T& {
        return ptr_[index];
    }
    template <typename I> constexpr auto operator[](I index) const -> const T& {
        return ptr_[index];
    }
};

class example {
    const buffer<char> buff_;
    auto c_str() const -> const char* { return &buff_[0]; }
};
```

I do not have much experience using operator overloading so it's entirely possible that this is just a misunderstanding on my part. But based on Googling, my expectation would be that since the `buff_` member variable of `example` is declared `const`, the second overload should be used. I get the same error message when I remove `const` from line 14 and am not as sure about what I would expect, but thinking since it is a non-const `buffer` then the first overload should be chosen.

So based on that understanding, it seems like figuring out which overload will be used can be determined by looking at the `const` versus non-`const` nature of the instance variable.

![image](https://user-images.githubusercontent.com/51306958/216724127-fbb4a84a-67cd-4b37-a96d-b7e6d38cd001.png)

**Comment by sean-mcmanus** [comment] 2023-02-08 00:28
@jtimothy-flexgen I'm not able to repro the bug for some reason -- can you provide your C/C++: Log Diagnostics output? In particular, I'm looking for what IntelliSense Mode and C++ standard are getting used.

**Comment by jtimothy-flexgen** [comment] 2023-02-08 01:14
Here are is my C/C++: Log Diagnostics output:
```
-------- Diagnostics - 2/7/2023, 8:13:41 PM
Version: 1.13.9
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/bin/gcc",
    "cStandard": "c89",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-gcc-x64",
    "configurationProvider": "ms-vscode.makefile-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": []
}
Translation Unit Mappings:
[ /home/vagrant/git/site_controller/src/example.cpp ]:
    /home/vagrant/git/site_controller/src/example.cpp
Translation Unit Configurations:
[ /home/vagrant/git/site_controller/src/example.cpp ]:
    Process ID: 26199
    Memory Usage: 90 MB
    Compiler Path: /bin/gcc
    Includes:
        /usr/include/c++/4.8.2
        /usr/include/c++/4.8.2/x86_64-redhat-linux
        /usr/include/c++/4.8.2/backward
        /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include
        /usr/local/include
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=40805
Total Memory Usage: 90 MB
```

**Comment by sean-mcmanus** [comment] 2023-02-08 03:10
Can you update your gcc to a newer version or is there a reason you need to use the older version? It looks like this bug may only rpero with older versions of gcc that we may not support as well.

**Comment by sean-mcmanus** [comment] 2023-02-08 03:12
That version of gcc doesn't have full support for c++14 and the code you're using doesn't compile with c++11 (which is the version it fully supports). If you want to use c++14 or newer, I'd recommend upgrading your compiler. What -std are you passing to gcc to get it to compile?

**Comment by sean-mcmanus** [comment] 2023-02-08 03:14
Ah, I see the newer version supported with that old gcc is -std=c++1y, which is not full c++14 and it doesn't compile with the code sample you're using, so in that case the errors from IntelliSense are sort of undefined.

**Comment by jtimothy-flexgen** [comment] 2023-02-08 19:05
My code is able to compile but I believe this code snippet lives in the `SPDLOG_COMPILED_LIB` so I think we're getting away with using it since it comes already compiled. When I changed my `cppStandard` from `c++14` to `c++11` in my `c_cpp_properties.json` the red squiggles went away. So it seems like this was an incompatibility with the version of C++ I had declared in my settings and the gcc version I was using, as you said.

Sometimes I find that `c_cpp_properties.json` will be automatically reverted back to `c++14` without me doing anything which is odd, but it doesn't happen often so isn't a huge deal. And I will look into upgrading my compiler to a more recent version so that I do not have to worry about it losing support

**Comment by sean-mcmanus** [comment] 2023-02-13 21:52
Do you mean changing your cppStandard to c++14 fixed the issue? I get the issue with c++11 because the code doesn't compile with c++11. I don't believe we have any code that would modify the cppStandard in c_cpp_properties.json (it's possible another extension could be doing that).

It sounds like the issue is resolved so I'll close it.

**Closed as not planned by sean-mcmanus** 2023-02-13 21:52 UTC
Labels: Language Service, by design

**Comment by jtimothy-flexgen** [comment] 2023-02-14 01:07
No, changing my cppStandard to c++11 fixed the issue.

Yeah, the issue is now resolved. Thank you for your help!
