### ISSUE TITLE
Code analysis reports issue with macro __has_include__ even though g++/clang++ don't complain

### ISSUE THREAD

**Issue by nicsav** [microsoft/vscode-cpptools#9575] opened 2022-07-13 05:10 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 11
- VS Code Version: 1.69.1
- C/C++ Extension Version: 1.10.8
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. open project in attached file
2. open has_include,cpp
3. press ctrl+shift+p
4. select 'C/C++: run analysis on active file'
5. see error reported:
[{
	"resource": "/home/nick/has_include/has_include.cpp",
	"owner": "clang-tidy",
	"code": "clang-diagnostic-error",
	"severity": 8,
	"message": "function-like macro '__has_include__' is not defined",
	"source": "C/C++",
	"startLineNumber": 3,
	"startColumn": 5,
	"endLineNumber": 3,
	"endColumn": 18
}]

**Expected behavior**

The code analysis should not report this as the code compiles cleanly with g++/clang++.

**Code sample and logs**

- Code sample

See attached .tar.gz for project containing source and settings to repro. It's run on WSL Ubuntu 20.04.

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

I've attached a screenshot showing the error.

**Additional context**

![has_include](https://user-images.githubusercontent.com/80062537/178655253-4383f17b-a4a3-44d1-9433-f500b4a08b31.png)
[has_include.tar.gz](https://github.com/microsoft/vscode-cpptools/files/9099059/has_include.tar.gz)

**Comment by nicsav** [comment] 2022-07-13 05:17
[language logs.txt](https://github.com/microsoft/vscode-cpptools/files/9099106/language.logs.txt)

**Comment by nicsav** [comment] 2022-07-13 05:18
[c++ logs.txt](https://github.com/microsoft/vscode-cpptools/files/9099113/c%2B%2B.logs.txt)

**Comment by nicsav** [comment] 2022-07-13 05:18
The project does not appear to have a c_cpp_properties.json

**Comment by channingxiao** [comment] 2022-07-15 06:39
got same issues with 
vscode 1.69.1, cpptooles  v1.10.8
at every single class definion cpp file, the file line to include it's header file,  it complained "
Error while processing C/C++(clang-diagnostic-error)[Ln1,Col1]
statx.h[Ln30,Col 6]: function-line macro' __has_include__' is not defined

"
![Uploading image.png…]()

**Comment by sean-mcmanus** [comment] 2022-07-15 23:02
The issue repros with gcc 9, but not 10. It's caused by the macro `-D__has_include(STR)=__has_include__(STR)` which clang (or gcc 10+) isn't able to process, but gcc 9 is. We can fix it by filtering that out.

**Comment by sean-mcmanus** [comment] 2022-07-20 02:11
Fixed with 1.11.3 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.11.3

**Closed as completed** 2022-07-22 02:05 UTC
Labels: bug, Language Service, fixed, quick fix, verified, Feature: Code Analysis
