### ISSUE TITLE
Remote SSH Syntax Coloring is not applied

### ISSUE THREAD

**Issue by grasshopper47** [microsoft/vscode-cpptools#5666] opened 2020-06-19 15:40 UTC
VScode **1.46.1** (1day ago) on Win 10

Extensions:
- C/C++&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**0.28.3**
- Remote-SSH **0.51.0**

Connecting via remote SSH to a Linux VM I get the following behavior of syntax coloring, which is incorrect (in a few cases), and is commented upon in the image below

![Untitled](https://user-images.githubusercontent.com/49437873/85150162-7ba9a800-b252-11ea-92a3-10ddbe4d3ce4.png)

I see this issue is tracked -- kind of -- https://github.com/microsoft/vscode-cpptools/issues/3942 and it refers to WSL containers, but the issues I describe in the attached photo apply to when connecting via SSH to a _Linux_ host, that is why I created this ticket.

If need be, I can copy/paste the theme file in a reply for reference.

**Comment by Colengms** [comment] 2020-06-22 19:49
Closing as a dupe of: https://github.com/microsoft/vscode-cpptools/issues/3942
The issue with remoting is the same, regardless of whether you are connecting to WSL or another Linux host.  This issue has actually been addressed, but the fix (to move to the VS Code's new Semantic Tokens API) is pending some blocking issues we have open with VS Code.  We expect this to ship soon.

**Closed as completed by Colengms** 2020-06-22 19:49 UTC

**Comment by sean-mcmanus** [comment] 2020-07-16 20:15
Fixed with 0.29.0.
