### ISSUE TITLE
IntelliSense data is lost after closing a file

### ISSUE THREAD

**Issue by rdxroman** [microsoft/vscode-cpptools#1356] opened 2017-12-17 06:24 UTC
Every time I open a file, the IntelliSense is not ready, it shows "Loading..." if I request for autocomplete suggestions. This happens even if the file was closed a few seconds ago.

This makes it a pain to use because every new file I open is not ready and needs to be rescanned before I can work with it. I would prefer to have a mode where all the project files would be loaded into the IntelliSense DB in the background so that every file would be "ready" to use IntelliSense-wise.

Is anything wrong with my configuration?

OS: macOS 10.13.1
VS Code Version: 1.19.0
C/C++ extension version: 0.14.4

**Comment by sean-mcmanus** [comment] 2017-12-18 08:27
Is this a problem with the red flame in the bottom right taking to long to finish? That's the IntelliSense compilation, which is kept in memory and we don't have a database related to it yet (we just have a symbol database). It sounds like what you're describing is currently "by design".

**Comment by rdxroman** [comment] 2017-12-21 08:03
Let me clarify the flow:

1. Open file foo.cpp.
2. Let the IntelliSense update finish (red flame disappears)
3. Now IntelliSense works.
4. Close viewer tab of foo.cpp and open it again.
5. The IntelliSense is not available because it's being updated - the red flame appears. This is where my problem is: why IntelliSense is not ready for a file it already compiled in the past only because I closed the file.

Is there a way to tell IntelliSense to compile all the files in the project folder?

**Comment by sean-mcmanus** [comment] 2017-12-21 22:08
The short answer is that we are aware of the problem and will look into ways to improve the experience.

This is the long answer: We could change it so that closing a file keeps the IntelliSense client alive (issue#1); however, that would only hide the fact that we have a logical processor limit or and a 1 GB memory limit that will close the client behind the scenes, exactly as if the user closed the file, except we don't show the red flame when the client is re-create (which I believe is a bug, issue#2) -- you can observe this hidden behavior by opening/hovering in multiple files until the limit is reached and observing the CPU usage of the IntelliSense process. We could solve this resource limit issue by adding settings for how many cores and memory usage the clients can use (issue#3). However, the bigger underlying issue is that the IntelliSense process is using too much memory (issue#4). Storing the results to disk would also help (issue#5). Also, it seems like a bug that we don't launch the IntelliSense updating after a new file becomes active, because otherwise, it's just delayed until a hover occurs and gets stuck showing "Loading" (issue#6). Compiling all the files in a project folder is not feasible until we manage to reduce the memory usage.

**Comment by michelleangela** [comment] 2019-08-20 22:27
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.

**Closed as completed by michelleangela** 2019-08-20 22:27 UTC
Labels: bug, Language Service
