### ISSUE TITLE
Outline does not follow cursor

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode-cpptools#3679] opened 2019-05-22 07:56 UTC
The outline in C++ files does not follow the cursor (the option is enabled) unless the cursor is explicitly placed on the Symbol.

If my cursor is in the body of a function, the outline does not follow:
<img width="527" alt="VS_1" src="https://user-images.githubusercontent.com/9846892/58156903-7c4ec400-7c77-11e9-8c71-fb7bf2c26757.png">

Even if the cursor is on the same line but not ON the symbol, cursor still doesn't follow:
<img width="508" alt="VS_2" src="https://user-images.githubusercontent.com/9846892/58156930-896bb300-7c77-11e9-883f-b1c93684c17c.png">

Only when I placing the cursor on the symbol makes the outline follow:
<img width="491" alt="VS_3" src="https://user-images.githubusercontent.com/9846892/58156937-8d97d080-7c77-11e9-9e3e-7688e04f11e8.png">

It works as expected with C# files and the C# extension.

**Comment by bobbrow** [comment] 2019-05-22 18:03
Thank you for your feedback.  This looks like a duplicate of #2230.  Can you please go add your +1 to that issue?

The extension does update the status bar with the current function and you can also navigate to functions that way.  VS Code created the Outline view later, but we haven't updated our implementation to go through that route yet.  It's on our backlog.

**Closed as completed by bobbrow** 2019-05-22 18:03 UTC
Labels: duplicate, Language Service, Feature Request
