### ISSUE TITLE
Incompatible language mode error for c files not accounted for in CMakeLists.txt.

### ISSUE THREAD

**Issue by tmsrise** [microsoft/vscode-cpptools#12124] opened 2024-03-20 02:13 UTC
### Environment

- OS and Version: Windows 11 (WSL2 Ubuntu)
- VS Code Version: 1.87.0
- C/C++ Extension Version: 1.19.8
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:

When `"C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools"` is applied and a .c file is not accounted for in CMakeLists.txt, VsCode supplies the following error at the start of the c file:

```
command-line error: language modes specified are incompatible
``` 

Removing the configuration provider setting solves the issue, but then VsCode does not recognize include directories set by my CMakeLists.

A workaround to this is to create a dummy target in CMakeLists.txt that isn't actually used:

```cmake
add_custom_target(DummyTarget SOURCES 
testing/test_sources/test1.c 
testing/test_sources/test2.c
examples/an_example/example.c
...
)
```
Another potential untested workaround is to remove the configuration provider setting and recreate the configuration in vscode settings.json.

Both workarounds cause confusion and multiple touch points whenever relevant changes are introduced. 

Steps to reproduce:
1. New Empty Folder / Workspace
2. CMake Quick Start -> Unspecified -> "test_name" -> cpp project -> library
3. create dummy_file.c
4. Change Configure Provider -> CMake Tools
5. Error

Reproduction Notes: 
- When reproducing I noticed that only c files are affected, regardless if c or cpp project is chosen. Thus renaming our c files to cpp is another workaround. For my purposes unfortunately, the c files in question need to be .c not .cpp.

Expected behavior:

- File exists without issue, even if it's never used or built in CMake.

### Configuration and Logs

```shell
settings.json
{
    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools"
}

C/C++ Log Diagnostics
{
  "os": "linux",
  "vscodeVersion": "1.87.2",
  "cmtVersion": "1.17.17",
  "configurations": [
    {
      "folder": "/home/marcus/projects/test",
      "cmakeVersion": "3.22.1",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/cc"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      "file:///home/marcus/projects/test/dummy.c",
      "file:///home/marcus/projects/test/dummy.cpp"
    ],
    "responses": [],
    "partialMatches": [],
    "targetCount": 29,
    "executablesCount": 0,
    "librariesCount": 1,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

**Comment by Colengms** [comment] 2024-03-21 23:07
Hi @tmsrise .  Thanks for reporting this.  This is a known issue, with a potential (eventual) solution being tracked by: https://github.com/microsoft/vscode-cpptools-api/issues/42 .  The issue is that the C/C++ Extension is currently falling back to a singular 'browse configuration' provided to by the configuration provider, to configure IntelliSense for any files the provider does not explicitly provide a configuration for.  That likely results in the right behavior for most users who are working with files that aren't explicitly specified in their CMakeLists.txt.  But that API lacks a separate standard field for C vs C++, hence the issue you're seeing. We can keep this issue open to track this.

**Comment by sean-mcmanus** [comment] 2024-03-26 21:36
The fix for https://github.com/microsoft/vscode-cpptools/issues/12144 should also enable this to be fixed since it'll fall back to using the c_cpp_properties.json configuration.

**Comment by bobbrow** [comment] 2024-12-31 17:43
This appears to be fixed in the latest version of the extension.

**Closed as completed by bobbrow** 2024-12-31 17:43 UTC
Labels: bug, Language Service, Feature: Configuration Provider
