### ISSUE TITLE
GCC nested functions aren't recognized

### ISSUE THREAD

**Issue by ArmoredPony** [microsoft/vscode-cpptools#9687] opened 2022-08-04 20:03 UTC
### Environment

- OS and Version: Windows 10 Home
- VS Code Version: 1.69.2
- C/C++ Extension Version: 1.11.4
- GCC version: 12.1.0

### Bug Summary and Steps to Reproduce

Bug Summary:
When a function inside another function is defined, the curly brace under the internal function is squiggled with red line with an `expected a ';'` error. In "c_cpp_properties.json" I added `"cStandard": "gnu17"` and `"intelliSenseMode": "windows-gcc-x64"` lines but it had no effect. Since gcc related options exist, I suppose, gcc features should be supported.

Steps to reproduce:
1. Create a file with .c extension.
2. Past the code sample inside.
3. The error appears.

### Expected behavior

No such error should appear.

### Code sample and Logs

```shell
int foo(int x)
{
    int bar(int x)
    {
        return x * 2;
    }
    return bar(x) + 1;
}
```

### Screenshots

![2048](https://user-images.githubusercontent.com/61470425/182941938-c02ac5ce-6c9a-4587-b7c7-36f963977524.png)

**Comment by sean-mcmanus** [comment] 2022-08-04 20:59
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/1035.

**Closed as not planned by sean-mcmanus** 2022-08-04 20:59 UTC
Labels: duplicate

**Comment by ArmoredPony** [comment] 2022-08-05 10:14
Any chance it will be fixed?..
