### ISSUE TITLE
struct tags only specially highlighted i .h files, not .c files

### ISSUE THREAD

**Issue by RobinTD** [microsoft/vscode-cpptools#3031] opened 2019-01-13 22:59 UTC
In `struct test`, "test" is specially and prominently highlighted in header files, but in source files it is shown as a plain identifier. It is also highlighted correctly in the tool tip when hovered in the source file. For readability, the header behavior should apply in source files.

Visual Studio Code version: 1.30.2
C/C++ extension version: 0.20.1
Platform: Linux

**Comment by sean-mcmanus** [comment] 2019-01-15 04:55
Our C/C++ extensions doesn't implement the colorization. It's implemented by VS Code using atom/language-c with textmate -- they need to fix this by switching to tree sitter. See a similar issue at https://github.com/atom/language-c/issues/207 .

**Comment by bobbrow** [comment] 2019-06-24 23:24
If you install the latest insiders version of the extension (set the "C_Cpp: Update Channel" setting to "Insiders"`) and then turn on the "Enhanced Colorization" setting, you can try out our improved colorization feature.  I will mark this as a duplicate of #230.

**Closed as completed by bobbrow** 2019-06-24 23:24 UTC
Labels: duplicate, Feature Request, Feature: Colorization
