### ISSUE TITLE
Rename Symbol doesn't work on #define

### ISSUE THREAD

**Issue by beauxq** [microsoft/vscode-cpptools#9050] opened 2022-03-18 19:25 UTC
Issue Type: <b>Bug</b>

```
#define THIS 5
const int x = THIS;
```

I right click THIS, choose "Rename Symbol", type THAT.

2nd line changes to THAT, but 1st line stays THIS.

Extension version: 1.9.5
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.13.0-27-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.65GB (0.27GB free)|
|Process Argv|--unity-launch --crash-reporter-id 282f5459-03d5-4146-a5c1-5cf222b3f089|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvidc:30447482
vscaac:30438847
pynewfile477cf:30450039

```

</details>

**Comment by michelleangela** [comment] 2022-03-18 19:53
Since the feature "Rename Symbol" uses "Find all references" to find all the refences to rename, this is a duplicate of the issue https://github.com/microsoft/vscode-cpptools/issues/4075.

**Closed as completed** 2022-03-18 19:55 UTC
Labels: bug, duplicate, Language Service, Feature: Find All References
