### ISSUE TITLE
"-isystem" paths in compile_commands.json-parsing ignored

### ISSUE THREAD

**Issue by decimad** [microsoft/vscode-cpptools#1279] opened 2017-11-23 11:07 UTC
Like the Header says, c_cpp_tools compile commands parsing seems to ignore isystem paths (that seems to be a gcc-only Feature?). It would be great if those could be parsed as well.

**Comment by bobbrow** [comment] 2017-11-27 18:29
Thanks for the feedback.  This looks like a duplicate of #1156

**Closed as completed by bobbrow** 2017-11-27 18:29 UTC
Labels: duplicate, Language Service
