### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by auysh** [microsoft/vscode-cpptools#3342] opened 2019-03-22 14:55 UTC
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\hp\ms-vscode.cpptools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bobbrow** [comment] 2019-03-22 15:55
Thanks for the report.  This looks like a duplicate of #3213

**Closed as completed by bobbrow** 2019-03-22 15:55 UTC
