### ISSUE TITLE
intelliSenseEngine set to "Disabled" in settings.json isn't reflected properly in Settings UI

### ISSUE THREAD

**Issue by tdashroy** [microsoft/vscode-cpptools#10428] opened 2023-01-28 01:06 UTC
### Environment

- OS and Version: Pop!_OS 22.04 LTS, Linux x64 6.0.12-76060006-generic
- VS Code Version: 1.73.0
- C/C++ Extension Version: v1.13.9

### Bug Summary and Steps to Reproduce

Bug Summary:
The Settings UI shows `C_Cpp: Intelli Sense Engine` as being the value `default`. 
The `.vscode/settings.json` has the following `"C_Cpp.intelliSenseEngine": "Disabled"`. 

When I use the editor in this way, Intellisense is disabled, which is confusing b/c checking on it in the Settings UI shows that it's `default` (which is enabled). 

Changing the `.vscode/settings.json` to be `"C_Cpp.intelliSenseEngine": "disabled"` and reloading the workspace causes the proper value to show up in the UI. And Intellisense is disabled as expected.

Changing the `.vscode/settings.json` to be a random alternative value, like `C_Cpp.intelliSenseEngine": "foo"`, causes the Settings UI to show `default` and causes Intellisense to be enabled as expected.

Steps to reproduce:
1. In `.vscode/settings.json` create or change the key `"C_Cpp.intelliSenseEngine"` to `"Disabled"`. 
2. Reload the workspace
3. Check the `Intelli Sense Engine` setting in the Settings UI to see that it says `default`.
4. Try to use Intellisense (like go to Definition) in the projects code, notice that it doesn't work.

Expected behavior:
Either:
  1. That a value of `"C_Cpp.intelliSenseEngine": "Disabled"` in `.vscode/settings.json` is reflected as `disabled` in the Settings UI or
  2. That a value of `"C_Cpp.intelliSenseEngine": "Disabled"` in `.vscode/settings.json` does not actually disable Intellisense.

### Configuration and Logs

```shell
`c_cpp_properties.json`:

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/**"
            ],
            "defines": [
                "HAS_CXX11_ATOMIC=1"
            ],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

`.vscode/settings.json`:
```
{
    "C_Cpp.autocomplete": "Disabled",
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.intelliSenseEngine": "Disabled",
    "clangd.arguments": [
        "--compile-commands-dir=build"
    ],
}
```
```


### Other Extensions

_No response_

### Additional context

_No response_

**Comment by browntarik** [comment] 2023-01-30 19:13
Thank you for submitting this issue! We are currently looking into a fix.

**Comment by browntarik** [comment] 2023-01-30 19:17
This is due to a change in setting behavior. We currently expect these values to be all lowercase, hence "Disabled" will not update the setting in the UI but "disabled" will. As a temporary fix, please only use lowecase letters. There should be an internal conversion to lowercase but it seems like it is not happening in this case.

**Comment by browntarik** [comment] 2023-01-30 19:26
Upon further investigation, due to updating our setting values internally to all lowercase VS Code does not recognize the uppercase version of the setting value. VS Code owns that and it's by design.  VS Code doesn't know that we'll accept values that aren't in the schema defined in package.json. For now, this is intended behavior, but we will keep this in mind for the future and close this issue.

**Closed as not planned by browntarik** 2023-01-30 19:26 UTC
Labels: bug, duplicate, Language Service, external, Visual Studio Code

**Comment by tdashroy** [comment] 2023-01-30 20:57
For some further context as to how this affected me (and thus could affect others):

Our repo has the `.vscode/settings.json` file checked in. When I opened the project and noticed Intellisense wasn't working I went to look at the Settings UI. I saw that the value was set to what it should be in order to have Intellisense turned on (aka `default`), so I assumed there was something else wrong and went searching around the web. When nothing else I came across seemed to be the reason it wasn't working, I was confused and asked a coworker. They were confused at first as well. However, eventually while poking around, they happened to open the `.vscode/settings.json`, which is when they saw the value was set to `"Disabled"` there. At which point is was pretty obvious as to what might be going on and how to fix it.

That is to say, while this issue is trivial to work around once you know what the issue is, it doesn't seem obvious (to me at least) how one would go about discovering that the Settings UI and the `.vscode/settings.json` file don't agree. The UI and the .json haven't shown different values in the past.

As a separate bit of context, the `.vscode/settings.json` was checked into our repo 7 months ago. I actually looked around a bit before filing this bug and found https://github.com/microsoft/vscode-cpptools/commit/65fcb15c092f650cd7397ffc31d64aa631de0f55, which looks like `"Disabled"` used to be the proper value, back when our `settings.json` was committed. 

All that being said, if you don't have a way to tell VS Code that you ignore case for these values, then it sounds like in order to change this behavior you'd probably have to only accept lowercase. And you might not want to make a change like that.

**Comment by bobbrow** [comment] 2023-01-30 23:42
Renaming settings in VS Code is particularly painful precisely because of these UI issues.  It is the reason we haven't done broader renames in the past despite the many inconsistencies in our settings names/values.  We had a meeting with the VS Code team about it a few years ago and we didn't get the features we asked for that would help mitigate issues like this.  We're sorry for the inconvenience this caused, but unfortunately we don't have a better solution that also allows us to make improvements in the consistency of the extension's settings aside from the "nuclear" option where we rename everything and attempt to migrate it all on startup for you... which we almost did for version 1.0.

**Comment by sean-mcmanus** [comment] 2023-02-07 02:35
Yeah, this is already being tracked in https://github.com/microsoft/vscode/issues/162596, which I opened back in October.
