### ISSUE TITLE
Supports format the code without already saving to a file.

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/vscode-cpptools#10351] opened 2023-01-04 06:49 UTC
### Feature Request

Now, if you create a new file (not saved) in VSCode, and paste some C/C++ code in it for formatting, it will show you "no cpp formatter installed". If you save the file to disk, then retry again, it works well.

**Comment by sean-mcmanus** [comment] 2023-01-04 19:15
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/4143 (you can upvote that issue).

**Closed as not planned by sean-mcmanus** 2023-01-04 19:15 UTC
Labels: duplicate
