### ISSUE TITLE
VSCode unresponsive while generating very large tooltip while editing C file

### ISSUE THREAD

**Issue by vgf89** [microsoft/vscode-cpptools#7577] opened 2021-05-22 14:00 UTC
Bug type: General

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.3.1
- Other extensions you installed (and if the issue persists after disabling them): Only the C/C++ plugin is necessary to reproduce. Every other plugin can be uninstalled
- A clear and concise description of what the bug is.

I have a particularly large array of structs that I instantiate and that the C/C++ plugin has trouble with. Open https://github.com/vgf89/gbemu/blob/579fbcee1693456c66374bace0940c637062a837/cpu.c and hover over any of the "{" or "}" in the instructions struct array (starts on line 19), and observe how VSCode freezes for multiple seconds.

If you don't move the mouse, a very very long tooltip of all of the list values appears when the lag ends. I'm not sure why the C/C++ plugin tries to generate this tooltip, and I especially don't like that it completely freezes the UI for multiple seconds while doing so.

**To Reproduce**
*Please include code sample and `task.json` files.*
1. open https://github.com/vgf89/gbemu/blob/579fbcee1693456c66374bace0940c637062a837/cpu.c  in VSCode
2. hover the mouse over the "{" bracket at the end of line 19, or any of the "{" or" }" brackets inside of the list.
3. Observe how VSCode freezes for ~5 seconds, and watch VSCode CPU usage spike in Task Manager.

**Expected behavior**

VSCode shouldn't freeze when mousing over value instantiation list brackets in my c file. The tooltip it generates while doing so is also of dubious usefulness.

**Screenshots**

**Additional context**

This happens on both my laptop and much more powerful desktop, and even happens with NO other plugins installed besides the C/C++ plugin.

Here's a profile of the freeze captured from the debugger:
https://gist.github.com/vgf89/4719a0d13ebdfd1d8cdd76bf0c6ad259

**Comment by sean-mcmanus** [comment] 2021-05-24 17:53
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/7334 and fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders2

**Comment by vgf89** [comment] 2021-05-25 07:25
I just installed the 1.4.0-insiders2 plugin version. The freezes are only about a second now. That's a massive improvement, but it's still just a little bit disruptive. I guess worst case I can switch the language mode to plain text when editing that part of my file.

**Comment by vgf89** [comment] 2021-05-26 13:33
My main gripe is that it still freezes the UI. AFAIK most suggestion, auto complete, and styling operations don't do that (though I could be wrong about that, for all I know those all run in a UI thread but are fast enough to not cause noticeable hitches). If the tooltip took an extra second to appear but left the rest of the UI responsive, I'd be very happy, but admittedly I don't know at all how VSCode or its plugin API work so I have no idea how hard that is to do. (Also if the lag is from VSCode trying to render that tooltip, maybe the primary performance issue lies upstream? Idk, just spitballing)

I will say that the 1 second lags I get when working in the literals list are very much bearable compared to the 5 second lags I had previously, so I thank you for that.

**Comment by sean-mcmanus** [comment] 2021-05-26 21:05
Yeah, I'm not able to repro any UI freeze at all and I believe the root issue is VS Code's rendering.

**Comment by sean-mcmanus** [comment] 2021-05-26 21:07
Ah, there's no lag with local Windows, but I see the UI freeze when remoting to Linux. Should be easy to fix...

**Comment by sean-mcmanus** [comment] 2021-05-28 00:12
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0

**Closed as completed by sean-mcmanus** 2021-05-28 00:12 UTC
Labels: bug, Language Service, fixed, quick fix, performance
