### ISSUE TITLE
IntelliSense engine generating false errors

### ISSUE THREAD

**Issue by cenomla** [microsoft/vscode-cpptools#739] opened 2017-05-19 21:16 UTC
After I upgraded to 0.11.1 just about every symbol in my project is generating a problem. I tried adding all my project directories to the browse/path setting in the c_cpp_properties.json file but that made no difference. If I use the tag parser instead of the intellisense engine it works as expected. I am using linux.

**Comment by sean-mcmanus** [comment] 2017-05-19 21:19
The IntelliSense engine needs the includePath and defines set to what the code compiles with. The includePath is not recursive. The features currently controlled by the IntelliSense engine are only hover and errorSquiggles.

**Comment by cenomla** [comment] 2017-05-19 21:25
I also have all the include paths in the appropriate place. The only thing in defines is "_DEBUG". Even symbols like fwrite and size_t and showing up as errors.

**Comment by sean-mcmanus** [comment] 2017-05-19 21:37
I'm reproing the problem with size_t (we had problems with size_t previously, but I thought they were fixed). Does it say that fwrite is undefined when you #include <cstdio>? I'm reproing that with libc++4.0. IntelliSense isn't working with libc++4.0 currently (it works with 3.8-3.9).

**Comment by cenomla** [comment] 2017-05-19 21:46
The actual include statements are not showing up as errors, I am using g++ 6.3.1 as my compiler. Every symbol that is not defined in the current file is showing up as an undefined symbol as if the intellisense engine is not parsing any header files at all.

**Comment by sean-mcmanus** [comment] 2017-05-19 21:52
Yeah, this seems like https://github.com/Microsoft/vscode-cpptools/issues/728 . Unfortunately, we've only been testing with g++ 4.8.5 to 6.2 and it looks like 6.3 broke us (the headers are a lot different). You should probably change the IntelliSenseEngine setting to "Tag Parser" until we make the IntelliSenseEngine work with the newer g++ version.

**Comment by cenomla** [comment] 2017-05-19 22:00
It appears that the intellisense engine is only parsing the first header included in the file. If I include "cstddef" first then the engine recognizes size_t however if I define it second then it does not, same with all other symbols.

**Comment by bobbrow** [comment] 2017-07-26 16:12
Are you still having this problem?
Can you share your config from **c_cpp_properties.json** so we can validate the auto-generated include paths?

We shipped a fix for the auto-generated include paths in 0.11.3, but if you already have a c_cpp_properties.json file in your workspace, we don't overwrite the contents, so you might want to let the extension generate a new one to see what the auto-generated include paths would be.

**Comment by cenomla** [comment] 2017-07-27 01:52
I recently regenerated my c_cpp_properties.json file and the default includes are:
"/usr/include/c++/7.1.1",
"/usr/include/c++/7.1.1/x86_64-pc-linux-gnu",
"/usr/local/include",
"/usr/lib/clang/4.0.1/include",
"/usr/include",
"${workspaceRoot}"
I am no longer having the problems with include directories, however the intellisense engine is still somewhat unstable (frequent hangs, restarting vs code doesn't help).

**Comment by bobbrow** [comment] 2017-07-27 04:24
Ok, thanks for confirming.  I'll close this issue since it sounds like the squiggles are working for you now.  

If you can help us identify the cause of your hangs, please open a new issue and we'll be happy to investigate more.

**Closed as completed by bobbrow** 2017-07-27 04:24 UTC
Labels: bug, Language Service
