### ISSUE TITLE
C/C++ "the task provider for the task accidentally provided the" shell"

### ISSUE THREAD

**Issue by a318219151** [microsoft/vscode-cpptools#5450] opened 2020-05-10 03:22 UTC
所需的数据太大，无法直接发送。我们已经将
Issue Type: <b>Bug</b>

#include<iostream>
const int Max = 5;
int fill_array(double arr[],int limit);
void show_array(const double arr[],int n);
void revalue(double r,double arr[],int n);

int main()
{
    using namespace std;
    double properties[Max];
    
    int size = fill_array(properties,Max);
    show_array(properties,size);
    if (size >0)
    {
        cout << "Enter revaluation factor: ";
        double factor;
        while (!(cin >> factor))
        {
            cin.clear();
            while (cin.get() != '\n')
                continue;
            cout << "Bad input ;Please enter a number: ";
        }
        revalue(factor,properties,size);
        show_array(properties,size);
    }
    cout << "Done.\n";
    cin.get();
    cin.get();
    return 0;
}
int fill_array(double arr[],int limit)
{
    using namespace std;
    double temp;
    int i;
    for (i = 0;i<limit;i++)
    {
        cout << "Enter value #" << (i + 1) << ":";
        cin >>temp;
        if (!cin)
        {
            cin.clear();
            while (cin.get() != '\n')
                continue;
            cout << "Bad input;input process terminated.\n";
            break;
        }
        else if(temp < 0)
            break;
        arr[i] = temp;
    }
    return i;
}
void show_array(const double arr[],int n)
{
    using namespace std;
    for (int i = 0;i < n;i++)
    {
        cout << "property #" << (i + 1) << ": $";
        cout << arr[i] << endl;
    }
}
void revalue(double r,double arr[],int n)
{
    for (int i = 0;i <n;i++)
        arr[i] *= r;
}

**Comment by ericbrownz** [comment] 2020-05-11 12:50
> We have a fix with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders3 . We plan to release 0.28.0 on Monday (or maybe Tuesday).

0.28.3prelease修复了 过几天正式版

**Comment by a318219151** [comment] 2020-05-11 12:51
Thank you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"EricBrown"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 晚上8:50
收件人:&nbsp;"microsoft/vscode-cpptools"<vscode-cpptools@noreply.github.com&gt;;
抄送:&nbsp;"珞珈"<318219151@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode-cpptools] C/C++ "the task provider for the task accidentally provided the" shell" (#5450)





  
We have a fix with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders3 . We plan to release 0.28.0 on Monday (or maybe Tuesday).
  
0.28.2版本修复了 过几天正式版

**Comment by michelleangela** [comment] 2020-05-11 16:32
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/5388

**Closed as completed by michelleangela** 2020-05-11 16:32 UTC
Labels: bug, duplicate, tasks/build/debug
