### ISSUE TITLE
The identifiers which I define cannot be colorized in IntelliSense

### ISSUE THREAD

**Issue by warzone-oier** [microsoft/vscode-cpptools#7167] opened 2021-03-14 14:14 UTC
**Type: LanguageService**
**Describe the bug**
- OS and Version: Ubuntu 16.04
- VS Code Version: 1.54.2
- C/C++ Extension Version: 1.2.2
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Extension Pack

- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace：  
  just as what I described in title, and the workspace is a small single project, less than 10 KB

**Steps to reproduce**  

<img src="https://cdn.luogu.com.cn/upload/image_hosting/laqpdhk7.png">

**Comment by sean-mcmanus** [comment] 2021-03-15 20:01
It sounds like you're referring to C_Cpp.enhancedColorization not working in the hover UI. This is "by design". VS Code has closed the issue as "out of scope": https://github.com/microsoft/vscode/issues/105892.

**Closed as completed by sean-mcmanus** 2021-03-15 20:01 UTC
Labels: external, by design
