### ISSUE TITLE
[Deubgger] Can this extension contribute breakpoints for the rust language?

### ISSUE THREAD

**Issue by chuckries** [microsoft/vscode-cpptools#8017] opened 2021-08-20 03:06 UTC
Can cpptools add the "rust" language to the contributes.breakpoints portion of the package.json? AFAIK this is the de-facto VS Code debugger for rust (since rust is just native), but with this installed you can still not set breakpoints in .rs files out of the box. 

Seems like a small way to fix a pain point for rust developers using this tool.

**Comment by chuckries** [comment] 2021-08-20 03:07
cc @WardenGnaw

**Comment by chuckries** [comment] 2021-08-20 03:10
It appears the rust extension contributes the "rust" language, so if this extension provides rust for breakpoints, I believe it should "just work".

https://github.com/rust-lang/vscode-rust/blob/b1ae67b06640ffab6e1ebb72e07364b4477dfbf1/package.json#L75

**Comment by WardenGnaw** [comment] 2021-08-20 17:08
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/8017

**Closed as completed by WardenGnaw** 2021-08-20 17:08 UTC
Labels: duplicate, debugger

**Comment by escape0707** [comment] 2021-09-14 12:17
> Duplicate of #75

Duplicate of a 5 years old bug.
