### ISSUE TITLE
Multi-line comment display incorrectly in c/c++ header file

### ISSUE THREAD

**Issue by cppkeyboardman** [microsoft/vscode-cpptools#5600] opened 2020-06-02 09:54 UTC
Issue Type: <b>Bug</b>

Step 1. Create a c/c++ header file.
Step 2. Define a macro in the header file.
Step 3. Give a multi-line comment after the macro.

Extension version: 0.28.2
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.1.7601
Remote OS version: Linux x64 5.3.7-1.el7.elrepo.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (10.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH:|
|OS|Linux x64 5.3.7-1.el7.elrepo.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz (1 x 2499)|
|Memory (System)|1.94GB (0.32GB free)|
|VM|100%|
</details>

**Comment by sean-mcmanus** [comment] 2020-06-02 18:27
Our extension doesn't contribute lexical colors. I believe this is a duplicate of https://github.com/jeff-hykin/cpp-textmate-grammar/issues/404#issuecomment-625977840 .

**Closed as completed** 2020-08-20 21:48 UTC
Labels: Language Service, external
