### ISSUE TITLE
[Error - 18:49:18] Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by Merange** [microsoft/vscode-cpptools#6172] opened 2020-09-19 16:52 UTC
Issue Type: <b>Bug</b>

I compile with Arduino exytension and I recieve very often this error message

[Error - 18:49:18] Connection to server got closed. Server will not be restarted.

and a new cpptools output is opened

Extension version: 1.0.0
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (2.29GB free)|
|Process Argv|--crash-reporter-id acf1d9fe-f24b-4365-87aa-163496313aa8|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by t0maszduda** [comment] 2020-09-20 07:10
the same issue: https://github.com/microsoft/vscode-cpptools/issues/6126

**Comment by sean-mcmanus** [comment] 2020-09-21 17:52
@Merange 
Can you attach a debugger to the cpptools process to get a crash call stack? (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv).

Or provide more repro steps?

**Comment by michelleangela** [comment] 2020-12-09 18:39
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 18:39 UTC
Labels: bug, Language Service, more info needed, reliability, investigate: repro
