### ISSUE TITLE
c_cpp_properties - "env" properties with array value, error squiggles in "includePath"

### ISSUE THREAD

**Issue by polyclash** [microsoft/vscode-cpptools#3962] opened 2019-07-22 21:57 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Home
- VS Code Version: Version: 1.37.0-insider (system setup)
Commit: 81ed55af79f01e9e64c3438558d2c2233e382a5a
OS: Windows_NT x64 10.0.17134
- C/C++ Extension Version: 0.24.1
- Other extensions you installed (and if the issue persists after disabling them): No
- "env" properties with array value, error squiggles when used in other properties.

**To Reproduce**

I used this screenshot as an example to show the issue.

**Screenshots**

![image](https://user-images.githubusercontent.com/40276897/61668229-6348aa80-acdc-11e9-88d3-6f7f046e0f44.png)

**Additional context**

**Comment by michelleangela** [comment] 2019-07-22 22:05
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/3912

**Closed as completed** 2019-07-24 20:36 UTC
Labels: duplicate, Language Service
