### ISSUE TITLE
Enhanced colorization uses memberOperatorOverload for both definition and usage

### ISSUE THREAD

**Issue by mmatrosov** [microsoft/vscode-cpptools#6972] opened 2021-02-15 16:23 UTC
I have the following config:

```
  "editor.semanticTokenColorCustomizations": {
    "rules": {
      // ...
      "memberOperatorOverload": "#fd952c"  // Orange
    }
  },
```

And the following code:

```
struct A {
  bool operator==(const A&) { return true; }
};

void foo() {
  A a, b;
  a == b;
}
```

Here is how VS Code colorizes it:

![image](https://user-images.githubusercontent.com/3617951/107970837-b53dd900-6fc2-11eb-94cc-b63a07644e63.png)

As you can see, both operator declaration at line 2 and operator usage at line 7 have orange color, specified in `memberOperatorOverload`. But I want them to have different colors. Namely, I want the usage of `==` to have regular grey color. How do I do it?

**Comment by Colengms** [comment] 2021-02-16 21:06
Hi @mmatrosov .  The semantic colorization algorithm we are using is shared with VS, and does not differentiate between use and declaration.  We are currently tracking this with: https://github.com/microsoft/vscode-cpptools/issues/6013

This issue is also open against VS, if you want to up-vote it there: https://developercommunity.visualstudio.com/idea/1160898/request-that-vc-provide-different-semantic-token-c.html

Closing this issue as a dupe of: https://github.com/microsoft/vscode-cpptools/issues/6013

**Closed as completed by Colengms** 2021-02-16 21:06 UTC
