### ISSUE TITLE
Enhance the Outline view for C++

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#2404] opened 2018-08-15 01:00 UTC
Type: LanguageService
The C++ class (or struct) can't be folded on the Outline view, but the enum can be. It looks uncomfortable, and I hope it can be improved.

**Comment by bobbrow** [comment] 2018-08-15 05:36
Thanks for the feedback.  This is a duplicate of #2230.  Please go upvote it so we can track the priority.

**Closed as completed by bobbrow** 2018-08-15 05:36 UTC
Labels: duplicate, Language Service
