### ISSUE TITLE
support show  local variable of Function in outline

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#8364] opened 2021-11-03 16:11 UTC
Type: Feature Request

just like typescript, please support  local variable in outline
![image](https://user-images.githubusercontent.com/1876302/140098747-48bafb0d-8799-46f8-9a10-69dbd576f32f.png)

**Comment by sean-mcmanus** [comment] 2021-11-05 23:27
We're unlikely to support local variables in the outline view, since VS itself doesn't support that and the system that provides the non-local symbols for a file doesn't parse the contents inside of functions. This is also probably a duplicate of a previously filed issue.

**Comment by heartacker** [comment] 2021-11-06 11:39
@sean-mcmanus  thanks for you clarify

and what is the due day of 1.8.0 . I can't wait for new experience since its Significant performance improvements

**Comment by sean-mcmanus** [comment] 2021-11-09 18:28
I'm not sure when 1.8.0 will be released. We've been fixing bugs with it. Hopefully within the next 2 weeks.

**Closed as completed** 2022-03-20 11:43 UTC
Labels: Language Service, Feature Request, Visual Studio, more votes needed, Feature: Document Symbol
