### ISSUE TITLE
How to format case label automatically

### ISSUE THREAD

**Issue by mkitby** [microsoft/vscode-cpptools#4782] opened 2019-12-22 03:47 UTC
Hello,

I want to format case label automatically after input, How can I make it?

There is a .clang-format file in the folder. format on type is true.
`"editor.formatOnType": true,`

![switch_case](https://user-images.githubusercontent.com/15389150/71316741-5826c000-24b0-11ea-99c6-a72afffb15d2.gif)

**Comment by sean-mcmanus** [comment] 2019-12-23 20:48
Our format on type code is only invoked when the `;` is typed, so in your example, typing the `:` at the end doesn't work, but `:;` would work. A related issue is https://github.com/microsoft/vscode-cpptools/issues/1419 . We had problems getting clang-format to format a single line after Enter was used.

**Comment by bobbrow** [comment] 2020-01-09 22:28
@sean-mcmanus was there a reason we didn't add `:` to the list of symbols for formatOnType?

**Comment by sean-mcmanus** [comment] 2020-01-09 23:13
Yes, because it causes bad results when ":" is not used at the end of the line, e.g. one line `?:` expressions or the start of a `::` operator.

**Comment by bobbrow** [comment] 2020-11-05 22:38
Closing as duplicate of #1419

**Closed as completed by bobbrow** 2020-11-05 22:38 UTC
Labels: duplicate, Language Service, Feature Request, Feature: Code Formatting
