### ISSUE TITLE
Calls to placement operator new can't be resolved correctly by IntelliSense

### ISSUE THREAD

**Issue by PaperCube** [microsoft/vscode-cpptools#5457] opened 2020-05-11 03:59 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1909 18363.778
- VS Code Version: 1.45.0
- C/C++ Extension Version: 0.27.1
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
- This issue persists after disabling all plugins other than cpptools
- g++ version: g++ (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

Create a cpp file with content below:

```cpp
#include <cstddef>

using namespace std;

int main() {
    int *ptr = (int *)operator new(sizeof(int));
    new ((void *)ptr) int; // This line fails
}
```
There's a error squiggle under `new` which says "Unable to call function 'operator new' with given parameters -- parameter types are (unsigned long long, void *)", while this code compiles with my g++ without warning with flags `-Wextra, -Wall` enabled and works.

And overload for `operator new` reports an error as well, as in issue #5452. 
```cpp
#include <new>
#include <cstddef>
using namespace std;
// The line below says the first parameter must be size_t type but it's already size_t.
void *operator new(size_t, void *); 
```

These two code fragments worked before.

![批注 2020-05-11 121619](https://user-images.githubusercontent.com/7395735/81523720-4ff8ef80-9381-11ea-819f-f5a6b6420a0e.png)
![批注 2020-05-11 121544](https://user-images.githubusercontent.com/7395735/81523725-538c7680-9381-11ea-9170-31442084590c.png)

**Steps to reproduce**
Type the code described above in a cpp file and then the error is shown.

**Expected Behavior**
No error should be raised.
<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 2020/5/11 上午11:49:16
Version: 0.27.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "cStandard": "c11",
    "compilerPath": "C:\\ProgramData\\mingw-w64\\bin",
    "compilerArgs": [],
    "cppStandard": "c++14",
    "intelliSenseMode": "gcc-x64",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\*** HIDDEN ***\test2.cpp ]:
    C:\Users\*** HIDDEN ***\test2.cpp
Translation Unit Configurations:
[ C:\Users\*** HIDDEN ***\test2.cpp ]:
    Process ID: 20224
    Memory Usage: 12 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        C:\Users\***** USER NAME *****\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7
        C:\Users\***** USER NAME *****\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\x86_64-linux-gnu\c++\7
        C:\Users\***** USER NAME *****\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7\backward
        C:\Users\***** USER NAME *****\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc\x86_64-linux-gnu\7\include
        C:\Users\***** USER NAME *****\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\usr\local\include
        C:\Users\***** USER NAME *****\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc\x86_64-linux-gnu\7\include-fixed
        C:\Users\***** USER NAME *****\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\x86_64-linux-gnu
        C:\Users\***** USER NAME *****\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++14
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=70400
Total Memory Usage: 12 MB
```
</details>

**Comment by Colengms** [comment] 2020-05-11 21:42
Hi @PaperCube .  Regarding the very first bit of code you provided:

```
#include <cstddef>

using namespace std;

int main() {
    int *ptr = (int *)operator new(sizeof(int));
    new ((void *)ptr) int; // This line fails
}
```

I can repro the error.  However, I also repo the error when attempting to compile, so the error seems correct.  If I add `#include <new>` , to pick up the declaration, that resolves the issue for me - both the squiggle and compilation.


However, I believe your other issue may be due to the TU being incorrectly configured.  The diagnostics log contained the following:

```
    "compilerPath": "C:\\ProgramData\\mingw-w64\\bin",
```
```
    Compiler Path: /usr/bin/gcc
```

It would appear that we failed to query a compiler at the path: `C:\\ProgramData\\mingw-w64\\bin`, and fell back to gcc via WSL, as it was the first installed compiler we detected.

Could you try correcting compilerPath to contain the executable name as well, and let us know if that clears up the other issues?

**Comment by PaperCube** [comment] 2020-05-12 02:41
@Colengms Thank you, 
The error squiggles have gone after correcting the compiler path by adding the executable name to path.

But I'm still a bit confused. In some cases, I may want to compile the code manually in WSL from command line and I would like it to resolve headers provided by gcc in WSL. Do I have to use Remote-WSL if `"compilerPath"` is set to `/usr/bin/g++` when I only wanted code completion and grammar check?

**Comment by sean-mcmanus** [comment] 2020-05-12 21:26
I get the same error squiggles with WSL+gcc on Windows with WSL paths, with WSL remote, with mingw, and when using gcc via https://gcc.godbolt.org/ . 

The squiggles may be going away temporarily after changing the compilerPath due to bug https://github.com/microsoft/vscode-cpptools/issues/5474 .

**Comment by PaperCube** [comment] 2020-05-13 00:28
@sean-mcmanus I closed and reopened the workspace several times, restarted vscode several times and waited for several minutes and the squiggles didn't show up. I assume the squiggles didn't disappear temporarily.

My compiler was downloaded from [here](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z)

**Comment by sean-mcmanus** [comment] 2020-05-13 00:44
If the squiggles don't appear with the mingw you're using that compiles correctly, but appears when we fall back to WSL compilers, then that appears to be "by design", correct behavior. Let me know if I'm misunderstanding the issue.

**Comment by PaperCube** [comment] 2020-05-13 01:21
@sean-mcmanus When we fall back to WSL compilers, after correcting the code by adding `#include <new>`, the error squiggles are still there but the code really compiles with g++ via WSL. 

I'm afraid I don't quite understand why it reports error after correcting configuration and code, given that the configured compiler compiles successfully, and the error message seems irrelevant. 

Could you explain a little further about what is done by design and how to get rid of it if I'm still doing something wrong?

**Comment by sean-mcmanus** [comment] 2020-05-13 02:01
Fixed with 0.28.0: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0

Let us know if you're still reproing the issue with the new release.

**Comment by PaperCube** [comment] 2020-05-13 02:54
Still reporting errors. But what's different is that this time OK with my WSL compilers and errors reported with my mingw-w64. Exactly the same error msg.

In summary:
0.27.1: WSL: error, mingw-w64: ok
0.28: WSL: ok, mingw-w64: error

Code:
```
#include <cstddef>
#include <new>
#include <memory>

using namespace std;

void *operator new(size_t, void *);

int main() {
    int *ptr = (int *)operator new(sizeof(int));
    new ((void *)ptr) int;
}
```

<details>
<summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 2020/5/13 上午10:34:23
Version: 0.28.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "cStandard": "gnu11",
    "compilerPath": "C:\\ProgramData\\mingw-w64\\bin\\g++.exe",
    "compilerArgs": [],
    "cppStandard": "c++14",
    "intelliSenseMode": "gcc-x64",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\===PATH===\test2.cpp ]:
    C:\USERS\===PATH===\TEST2.CPP
Translation Unit Configurations:
[ C:\Users\===PATH===\test2.cpp ]:
    Process ID: 21600
    Memory Usage: 23 MB
    Compiler Path: C:\ProgramData\mingw-w64\bin\g++.exe
    Includes:
        C:\PROGRAMDATA\MINGW-W64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++
        C:\PROGRAMDATA\MINGW-W64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\X86_64-W64-MINGW32
        C:\PROGRAMDATA\MINGW-W64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\BACKWARD
        C:\PROGRAMDATA\MINGW-W64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE
        C:\PROGRAMDATA\MINGW-W64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE-FIXED
        C:\PROGRAMDATA\MINGW-W64\X86_64-W64-MINGW32\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++14
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=80100
Total Memory Usage: 23 MB
```
</details>

<details>
<summary><strong>Cpp related settings in settings.json</strong></summary>

```
{
    // "C_Cpp.intelliSenseEngineFallback": "Disabled",
    // "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.clang_format_fallbackStyle": "{ BasedOnStyle: LLVM, IndentWidth: 4 }",
    "C_Cpp.intelliSenseCacheSize": 100,
    // "C_Cpp.default.compilerPath": "/usr/bin/g++",
    "C_Cpp.default.compilerPath": "C:\\ProgramData\\mingw-w64\\bin\\g++.exe",
    "C_Cpp.default.cppStandard": "c++14",
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
}
```
</details>

**Comment by sean-mcmanus** [comment] 2020-05-13 03:06
That is odd. I'm not reproing it and your config settings look correct.
@Colengms @michelleangela Are you able to repro this?

My mingw is at `C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\g++.exe`

**Comment by sean-mcmanus** [comment] 2020-05-13 03:10
Oh, you're using mingw32...can you try changing your intelliSenseMode to gcc-x86?

Otherwise, it sounds like we need to try out that particular mingw version.

**Comment by PaperCube** [comment] 2020-05-13 03:15
Well, I believe I'm using exactly the same version as yours. I just renamed the path. It's not mingw32.

First line of `g++ --version` output:
```
g++ (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
```

But I tried changing the IntelliSense mode to gcc-x86 and mysteriously it **works**. But I think my compiler is really 64-bit.

**Comment by sean-mcmanus** [comment] 2020-05-13 03:33
Are you sure the g++ on your path is the same one as your compilerPath?

@michelleangela Could we have a bug with 32-bit versus 64-bit IntelliSense? I see code that is treating "long" as 8 bytes with gcc mode, even on Windows+mingw where it might still be 4 bytes, which would explain why changing the intellisenseMode to x86 fixes the issue. Maybe this is a reason to switch to doing what VS does with "windows-gcc-x64" style IntelliSense modes?

Still, it's strange why I'm not able to repro it. @michelleangela @Colengms Is anyone else able to get a repro?

**Comment by PaperCube** [comment] 2020-05-13 03:40
Yes. I copied the path from `where g++` and there's no other compiler on my computer.

**Comment by Colengms** [comment] 2020-05-13 23:22
After installing a handful of different versions (and bitnesses) of MinGW, I'm able to repro this issue only with the X86_64-8.1.0 variation of MinGW-w64.  The Log Diagnostics output from 0.27.1 and 0.28.0 are identical and look correct.  The params we're passing to the IntelliSense process look correct.  The issue would seem to be regression in the IntelliSense parser in 0.28.0.  Perhaps its getting confused by something it's failing to parse in a header - We have a similar issue with clang 10 headers.

**Comment by sean-mcmanus** [comment] 2020-05-14 00:58
Yeah, I repro it too now. The IntelliSense params are correct but in gcc mode on Windows we're treating sizeof(long) as 8 instead of 4.

**Comment by sean-mcmanus** [comment] 2021-04-05 17:54
I think this issue is already being tracked by https://github.com/microsoft/vscode-cpptools/issues/6246

**Comment by michelleangela** [comment] 2021-04-08 18:32
Closing as duplicate of  #6246

**Closed as completed by michelleangela** 2021-04-08 18:32 UTC
Labels: duplicate, Language Service, regression, investigate: repro, Feature: Configuration
