### ISSUE TITLE
when pasting code that doesn't end with a semicolon, code in the next line is concatenated to the current line

### ISSUE THREAD

**Issue by bombs-kim** [microsoft/vscode-cpptools#3208] opened 2019-02-23 12:24 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: OSX 10.13 High Sierra
- VS Code Version:
1.31.1
1b8e8302e405050205e69b59abb3559592bb9e60
x64
- C/C++ Extension Version:  0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

when pasting code that doesn't end with a semicolon, current line's newline character gets removed and the code in the next line is concatenated to the current line

**To Reproduce**

before copy
![image](https://user-images.githubusercontent.com/11001573/53286354-9419c780-37b0-11e9-9545-4ff0af7228ed.png)

after copy
![image](https://user-images.githubusercontent.com/11001573/53286358-a5fb6a80-37b0-11e9-9edf-0cd987f269c0.png)

**Expected behavior**

**Screenshots**

**Additional context**

To reproduce, the file should exist for the current buffer.

**Comment by sean-mcmanus** [comment] 2019-02-25 20:07
I'm not reproducing the issue. Does this repro with the C/C++ extension disabled? What are your format-related and editor.* settings?

**Comment by bombs-kim** [comment] 2019-02-26 07:12
@sean-mcmanus  Thank you for having a look on this issue. It doesn't happen if I disable C/C++ extension, so I guess it's caused by this extension. Here is my editor settings.

```
{
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "editor.hover": false,
    "editor.hover.delay": 3000000,
    "editor.rulers": [79, 119],
    "C_Cpp.intelliSenseEngineFallback": "Disabled",
    "workbench.editor.enablePreview": false,
    ...
}
```

Note that this problem can be reproduced only when the current buffer(tab) had been saved as a file somewhere. i.e., You cannot reproduce it in a Untitled tab.

**Comment by sean-mcmanus** [comment] 2019-02-26 20:08
I got a repro via enabling "editor.formatOnPaste" (although a manual format also works after the paste occurs). This is caused by clang-format (as can be seen via [enabling logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md):
```
Formatting raw output:
int iwilpaste;

int main() {
    iwilpaste return sub_h;
}
```

It's possible this could be configured via some clang-format setting, but I don't know which: https://clang.llvm.org/docs/ClangFormatStyleOptions.html .

Can you file a bug with clang at https://bugs.llvm.org/ ?

**Comment by bobbrow** [comment] 2019-05-16 17:12
Closing external issue not caused by our extension.

**Closed as completed by bobbrow** 2019-05-16 17:12 UTC
Labels: bug, external
