### ISSUE TITLE
functions and symbols reference  feature needed

### ISSUE THREAD

**Issue by mdzyduan** [microsoft/vscode-cpptools#83] opened 2016-06-26 00:22 UTC
functions and symbols reference not support now, if you  using vscode read a large project , you will find it is not  convenient .

**Comment by kinreven** [comment] 2016-06-27 06:05
agree

**Comment by sridmad** [comment] 2016-06-28 20:14
Duplicate of #15

**Closed as completed by sridmad** 2016-06-28 20:15 UTC

**Comment by sean-mcmanus** [comment] 2019-08-09 03:22
Find All References is available in 0.25.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders , but you'll need to set the C_Cpp.experimentalFeatures setting to "Enabled".
