### ISSUE TITLE
can not run a program without debugging

### ISSUE THREAD

**Issue by hananawi** [microsoft/vscode-cpptools#4373] opened 2019-10-02 05:43 UTC
Type: Debugger

**Describe the bug**
- OS and Version: centos 8
- VS Code Version:
- C/C++ Extension Version: 0.25.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}

int main(){
    int a = 0;
    int b = a;   //this line has a breakpoint
    cout<<a<<endl;
    return 0;
}

1. Go to ctrl F5
2. still stop on the breakpoint

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by pieandcakes** [comment] 2019-10-15 17:50
Duplicate of #1201. Please upvote that issue

**Closed as completed by pieandcakes** 2019-10-15 17:50 UTC
