### ISSUE TITLE
i have this problem in vs code can any help me ? #include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\user\Desktop\Marlin-2.0.x\Marlin\src\MarlinCore.cpp).

### ISSUE THREAD

**Issue by ammarfarsi** [microsoft/vscode-cpptools#6165] opened 2020-09-18 06:05 UTC
i have this problem in vs code can any help me ?
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\user\Desktop\Marlin-2.0.x\Marlin\src\MarlinCore.cpp).

**Comment by bobbrow** [comment] 2020-09-18 16:29
Hover the mouse over the error and it should tell you which header it was unable to find.  When it does, you can update the `includePath` to help the extension locate that file by using the "Edit Configurations (UI)" command.

**Comment by ammarfarsi** [comment] 2020-09-19 04:40
can you explain for me step by step, because I don't use vs code more. this is the problem in the picture. I don't know how I solve it
![image](https://user-images.githubusercontent.com/70930795/93659153-74fa1f00-fa53-11ea-9f22-55b415b8eb97.png)

**Comment by sean-mcmanus** [comment] 2020-09-21 18:36
If you open MarlinCore.cpp you should be able to see more info on which headers can't be found. You can also run C/C++: Log Diagnostics to see which include paths are being used by IntelliSense.

**Comment by michelleangela** [comment] 2020-12-09 18:39
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 18:39 UTC
Labels: question, Language Service, more info needed, Feature: Configuration
