### ISSUE TITLE
Breakpoints hit in files with identical file names

### ISSUE THREAD

**Issue by fpanjevic** [microsoft/vscode-cpptools#4266] opened 2019-09-18 13:14 UTC
Type: Debugger

**Describe the bug**
- OS and Version: Linux x64 4.15.0-60-generic
- VS Code Version: 1.38.1
- C/C++ Extension Version: 0.25.1

Breakpoints placed in one file will be hit in all files within the source tree as long as they have the identical file name as the file containing the breakpoint (but not the same dir path).

**To Reproduce**
1. Create a source tree with two files with identical names in different directories, like so:
/main.cpp
/first/code.cpp
/second/code.cpp
Contents of the source files can be arbitrary, as long as they compile and execute.

2. Place a breakpoint somewhere in /first/code.cpp
3. During execution of /second/code.cpp, a breakpoint will be hit on the same line as the breakpoint from step #2, even though it wasn't specified by the user.

**Comment by pieandcakes** [comment] 2019-09-24 17:11
This is a duplicate of #977

**Closed as completed by pieandcakes** 2019-09-24 17:11 UTC
Labels: duplicate, debugger
