### ISSUE TITLE
g++-10 contents of <concepts> are all greyed out

### ISSUE THREAD

**Issue by cleoold** [microsoft/vscode-cpptools#5553] opened 2020-05-22 05:57 UTC
**Type: LanguageService**
Running remote-ssh with wsl, all the contents in the header \<concepts\> below the line `#if __cplusplus > 201703L && __cpp_concepts >= 201907L` are all disabled by intellisense. and so any attempts to write c++20 new things like `std::views` will give an error in the editor because they are "not defined".

PS: same thing happens to <ranges\> and <coroutine\>

**Describe the bug**
- OS and Version: Windows 10 and WSL1
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.1

**Steps to reproduce**
1. set the compiler path to the path to g++-10 and set the standard to c++20
2. create cpp file and include <concepts\>

**Expected behavior**
the <concepts> header's contents are available

**Comment by TerensTare** [comment] 2020-05-22 17:23
I have the same problem with `msvc-x64` Intellisense mode. 
![image](https://user-images.githubusercontent.com/37905314/82693240-75c7a380-9c61-11ea-8051-ebc2cf2342f4.png)

This image is taken from the v0.28.0 changelog of the extensions. As you can see, `__cpp_concepts` isn't defined (that's why it is grayed out). The macro isn't defined because apparently, concepts aren't fully supported by the extension.

**Comment by michelleangela** [comment] 2020-05-22 17:50
Closing as a duplicate of issue https://github.com/microsoft/vscode-cpptools/issues/5444.

**Closed as completed by michelleangela** 2020-05-22 17:50 UTC
Labels: bug, Language Service, Visual Studio
