### ISSUE TITLE
Using std::move with an std::optional reports an error that will disapear after a few seconds

### ISSUE THREAD

**Issue by dortamiguel** [microsoft/vscode-cpptools#11478] opened 2023-09-28 12:13 UTC
### Environment

- OS and Version: Ventura 13.6
- VS Code Version: 1.82.2
- C/C++ Extension Version: 1.17.5

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
Write this code
```c++
 std::optional<std::function<void(void)>> on_press;
 if (on_press) {
    std::move (*on_press)();
}
```
Wait for a few seconds, then this error will appear
```
template instantiation resulted in unexpected function type of "std::__1::function<void ()> &&(std::__1::function<void ()> &__t) noexcept" (the meaning of a name may have changed since the template declaration -- the type of the template is "std::__1::__libcpp_remove_reference_t<_Tp> &&(_Tp &&__t) noexcept")
```
Now wait for a few seconds and the error will disapear, if the error stays there try making an edit anywhere in the source file like comment and uncomment any line.

Expected behavior:
I don't see this error

### Configuration and Logs

```shell
-------- Diagnostics - 28/09/2023, 21:11:06
Version: 1.17.5
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "/Users/miguel/prototype/lib/macos/include",
        "/Users/miguel/prototype/include",
        "/Users/miguel/prototype"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c17",
    "intelliSenseMode": "macos-clang-arm64",
    "compilerPathInCppPropertiesJson": "/usr/bin/clang",
    "forcedInclude": [
        "/Users/miguel/prototype/src/pch.hpp"
    ],
    "cppStandard": "c++20",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": true,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "/Users/miguel/prototype/lib/macos/include",
            "/Users/miguel/prototype/include",
            "/Users/miguel/prototype",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.17.5.0
Translation Unit Mappings:
[ /Users/miguel/prototype/src/main.cpp ]:
    /Users/miguel/prototype/src/main.cpp
Translation Unit Configurations:
[ /Users/miguel/prototype/src/main.cpp ]:
    Process ID: 40341
    Memory Usage: 450 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /Users/miguel/prototype/lib/macos/include
        /Users/miguel/prototype/include
        /Users/miguel/prototype
        /usr/local/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include/c++/v1
        /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include
        /Library/Developer/CommandLineTools/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/System/Library/Frameworks
    Forced Includes:
        /Users/miguel/prototype/src/pch.hpp
    Standard Version: c++20
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=160000
Total Memory Usage: 450 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 10751
```

**Comment by michelleangela** [comment] 2023-09-28 17:50
@dortamiguel 
Thank you for reporting this issue. It is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/11448 and https://github.com/microsoft/vscode-cpptools/issues/11463.

**Closed as completed by michelleangela** 2023-09-28 17:50 UTC
Labels: bug, duplicate, Language Service, Visual Studio

**Comment by dortamiguel** [comment] 2023-09-29 00:44
@michelleangela ah! sorry about that
