### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by infalmo** [microsoft/vscode-cpptools#3557] opened 2019-04-29 14:22 UTC
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.23.0-insiders`
- OS Version: `Linux x64 4.15.0-48-generic`
- VSCode version: `1.33.1`

> /home/******/ms-vscode.cpptools-unresponsive.cpuprofile.txt
[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/3127755/ms-vscode.cpptools-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment] 2019-04-29 21:35
Duplicate of #3213. Expected to be fixed in our next update.

**Closed as completed by sean-mcmanus** 2019-04-29 21:35 UTC
Labels: duplicate
