### ISSUE TITLE
Customizable Doxygen tags for Quick Info

### ISSUE THREAD

**Issue by emaschas** [microsoft/vscode-cpptools#8525] opened 2021-12-11 17:34 UTC
Type: Feature Request

Could you please implement @details and eventually also @note and @warning in quick info.
If it cannot be a separate section, at least show the text after that of @brief.

Another suggestion : implement @n to force line break

Many thanks.

**Comment by michelleangela** [comment] 2021-12-13 19:31
@emaschas 

Just to clarify, is this a request to add those additional Doxygen tags to the simplified view of structured comments in the quick info tooltip? Otherwise, all Doxygen tags can be viewed by setting `C_Cpp.simplifyStructuredComments` to `false`.

![image](https://user-images.githubusercontent.com/38734287/145875804-373f9150-def2-403b-ab23-6be44c9edce8.png)

**Comment by emaschas** [comment] 2021-12-14 18:13
The request is to add one or two more tags that would be displayed in the quick info with the same aspect as the "simplified" option.
Something like that 
![image](https://user-images.githubusercontent.com/30336575/146055664-4ac2cafc-cf4e-41ea-a1cd-c3de34e318d5.png)

Maybe I should have done a separate issue for the other request concerning the implementation of @n to force line break (like <br/> in HTML).

**Comment by emaschas** [comment] 2021-12-15 11:03
I realize that my issue somehow similar to #7705

**Comment by TomasVaner** [comment] 2022-07-27 22:31
> @emaschas
> 
> Just to clarify, is this a request to add those additional Doxygen tags to the simplified view of structured comments in the quick info tooltip? Otherwise, all Doxygen tags can be viewed by setting `C_Cpp.simplifyStructuredComments` to `false`.
> 
> ![image](https://user-images.githubusercontent.com/38734287/145875804-373f9150-def2-403b-ab23-6be44c9edce8.png)

The problem is that with this setting being off comments become almost plain text, and tags are visible as tags with @ and all. So yeah, adding some tag being parsed would be great

**Comment by emaschas** [comment] 2022-08-22 11:22
> > @emaschas
> > Just to clarify, is this a request to add those additional Doxygen tags to the simplified view of structured comments in the quick info tooltip? Otherwise, all Doxygen tags can be viewed by setting `C_Cpp.simplifyStructuredComments` to `false`.
> > ![image](https://user-images.githubusercontent.com/38734287/145875804-373f9150-def2-403b-ab23-6be44c9edce8.png)
> 
> The problem is that with this setting being off comments become almost plain text, and tags are visible as tags with @ and all. So yeah, adding some tag being parsed would be great
> 
> Also, maybe add an option to parse known tags and just add the unknown ones as a non-simplified version?

The request was to add some of the Doxygen tags in order to enhance the quick info tooltip, not the full set. 
The use case is not for Doxygen implementation, but just the quick info.
The implementation of @n to force line breaks would be really nice too.

**Comment by sean-mcmanus** [comment] 2022-08-23 18:14
@bobbrow Can/should you update the Milestone/Project?

**Comment by bobbrow** [comment] 2022-08-23 18:19
@sean-mcmanus we will when we start working on it.

**Comment by cjr163** [comment] 2022-08-31 09:15
![g11](https://user-images.githubusercontent.com/41551741/187643592-2e07c8ef-c921-45af-a51c-2e3fe71d9c17.png)
I need ...

**Comment by sean-mcmanus** [comment] 2022-09-01 17:45
@cjr163 Could you clarify your screenshot/comment? What do you need?

**Comment by kisielk** [comment] 2022-09-14 04:46
Since this was closed as a duplicate of #7705 I'd just like to add that I think even if the brief display can be customized, `@warning` should be in the defaults

**Comment by michelleangela** [comment] 2022-10-10 21:26
TODO: add image and ID of new setting here.

**Comment by sean-mcmanus** [comment] 2022-10-26 22:47
The fix is available with 1.13.3 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.3

**Closed as completed** 2022-12-07 18:44 UTC
Labels: Language Service, Feature Request, fixed, Visual Studio, Feature: Doc comments
