### ISSUE TITLE
Unable to search for files when this plugin is active

### ISSUE THREAD

**Issue by rteja** [microsoft/vscode-cpptools#1516] opened 2018-02-02 09:06 UTC
Operating System : Windows 10
VSCode Version: 1.19.3
C/C++ Extension Version : 0.14.6
C_Cpp includes have about 30 include folders
This is happening on a project having relatively large number of source files.

Steps to reproduce:
Open the workspace
Ctrl + P to open the file search dropdown.
Search for a file in the workspace.

Without this plugin active I get almost instantaneous results for search queries. But when active search fails almost always, and when successful takes a very long time.

**Comment by sean-mcmanus** [comment] 2018-02-02 20:01
Our code doesn't get called on Ctrl + P "file search", only workspace/file symbol search. I don't see how we could be affecting this. I'm not able to repro any problem. Is there a database or flame icon in the bottom right?

**Comment by rteja** [comment] 2018-02-03 04:37
Oh, but I can see this happening consistently. When I disable the plugin I see that search is fast again.

**Comment by sean-mcmanus** [comment] 2018-02-06 01:59
Is one of our extension processes hogging the CPU while you try to do the file search? Which process is using CPU during the file search?

**Comment by rteja** [comment] 2018-02-06 06:30
Microsoft C/C++ plugin takes about 25% of CPU all the time when I open the project. I dont notice any other process so actively using CPU other than this.

**Comment by sean-mcmanus** [comment] 2018-02-06 10:29
Yes, that's our workspace symbol parsing thread. Can you click on the database icon in the bottom right and select "Pause Parsing"? The CPU usage should go to 0%. Then can you do the file search operation and see if anything is using CPU? You could also hover over the database icon to track the progress and wait till it finishes (under normal conditions the discovering files phase should be fast and the 2nd parsing phase should have less files to parse).

**Comment by rteja** [comment] 2018-02-06 19:23
No, even if I select "Pause Parsing" CPU activity does not go to 0. Its as before and I do not notice any difference in search as well.

**Comment by sean-mcmanus** [comment] 2018-02-06 19:38
What does it say in the tooltip when you hover over the database icon? It sounds like it could be stuck enumerating files, which can occur if your browse.path has an extremely large number of folders (of if there's some other bug causing an infinite loop in that code).

**Comment by rteja** [comment] 2018-02-13 08:19
I do not see this issue after VScode update 1.20.0 .

**Comment by rteja** [comment] 2018-02-13 08:32
Closed it by mistake. 

When I hover over database icon, it is enumerating files. I see that this never ends. Yes, there are extremely large number of folders and files.

**Comment by sean-mcmanus** [comment] 2018-02-13 19:30
The root cause is https://github.com/Microsoft/vscode-cpptools/issues/1481 , which we're not planning to fix. The workaround is to remove "${workspaceRoot}" or whatever large path from your browse.path setting (use Edit Configuration to access the setting). Is that workaround acceptable?

**Comment by michelleangela** [comment] 2019-06-12 21:34
Closing this issue as the last response is more than a year old.

**Closed as completed by michelleangela** 2019-06-12 21:34 UTC
Labels: more info needed, performance
