### ISSUE TITLE
Named initialization of Structs in C is not recognized

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode-cpptools#10871] opened 2023-04-24 16:51 UTC
### Environment

- OS and Version: Win10
- VS Code Version: 1.77.3
- C/C++ Extension Version: 1.14.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:

this works since C99, but is linted as error
```
typedef struct { int v1; } sc2;
int main () {
	sc2 g1 = {
		.v1 = 1		// error: `expected an expression`
	};
	return 1;
};
```

### Configuration and Logs

```shell
-
```

**Comment by sean-mcmanus** [comment] 2023-04-24 17:17
This should work if you're properly configured for C. Can you run C/C++: Log Diagnostics from the command palette and look to verify that the C language is being used and what the C standard is?

**Comment by irvnriir** [comment] 2023-04-24 17:20
@sean-mcmanus this works if i set the file extension to .c , but not if i manually change the language for opened file .

**Comment by sean-mcmanus** [comment] 2023-04-24 17:28
So what does the C/C++: Log Diagnostics say? What are the repro steps?

This sounds like it's a duplicate of https://github.com/microsoft/vscode-cpptools/issues/10494 .

**Closed as completed** 2023-04-25 03:19 UTC
Labels: Language Service, more info needed, not reproing, Feature: Configuration
