### ISSUE TITLE
25 GB cpptools memory usage with a workspace with one of the projects symlinked to another disk

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7925] opened 2021-08-05 19:23 UTC
I experience it with 1.5.1. Had a workspace with one of the projects symlinked to another disk, and cpptoolls memory usage went through the roof (like, 25G), up to a point when processes started getting killed. Removed it, and memory usage dropped.

_Originally posted by @antonsavin in https://github.com/microsoft/vscode-cpptools/issues/7218#issuecomment-893123504_

**Comment by sean-mcmanus** [comment] 2021-08-05 19:24
@Colengms Can you follow up to get more info?

**Comment by Colengms** [comment] 2021-08-05 19:52
Hi @antonsavin .  We sometimes see issues such as this when there is a symlink circular reference.  The tag parser will continue to parse indefinitely, as it repeatedly follows the same symlink.  Can you confirm if that may be happening in your repro?

**Comment by sean-mcmanus** [comment] 2021-08-06 21:19
@antonsavin We had some symlink bugs like that, but I believe they should be fixed, so if you can provide some sort of repro we could investigate. Or if you could attach a call stack to the cpptools process while memory is increasing the fast and get a call stack (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv).

**Comment by jinguTech** [comment] 2021-08-11 15:45
Version: 1.51
System: Arch Linux
Linux kernel: 5.13.8-arch1-1
It consumes 7G of memory space.
The following is the stack information.
Don't know if it helps
I will try to reproduce this problem later.
[stack.log](https://github.com/microsoft/vscode-cpptools/files/6969687/stack.log)

**Comment by sean-mcmanus** [comment] 2021-08-13 20:37
@jinguTech Your stacks show all the threads waiting and not doing any work -- a call stack would only be potentially helpful if it was captured while the memory is increasing at the fastest rate and not after it's already finished accumulating. Does the memory go to 7 GB and then stop growing?

**Comment by sean-mcmanus** [comment] 2021-10-13 23:31
@chenhaowen01 Your call stack seems to indicate it's a bug with populate_filename_cache. Did this repro with 1.6.0 as well? There could be some symlink that is causing too many files to be added. We may need to find/construct an example repro project in order to fix it.

**Comment by chenhaowen01** [comment] 2021-10-15 12:38
@sean-mcmanus I can only install the 1.7.0 version in VS Code (I don't know how to install a lower version), and it can repro with v1.7.0. 

How do I known if symlink cause this? I can be sure that there are not any symlink file in my project directory, expect those in .git folder.

And I found that the problem can only repro when I open a *.cpp file not in compdb (I use a compile_commands.json to config the project), or open a *.h file directly (not jump from a *.cpp file).

This issue I only meet in one project. And the project lead to the problem is proprietary, so I can't share it here. However, I am pleasure to provide  help to fix it within my capacity.

**Comment by sean-mcmanus** [comment] 2021-10-29 22:20
@chenhaowen01 You can install older versions of the extension from the Extension view, gear icon, Install Another Version menu option, and you might need to set extensions.autoUpdate to "None". If you temporarily set the C_Cpp.loggingLevel to the hidden value of 7 you could potentially see more logging in regards to the file iteration that is occurring, potentially through a symlink.

**Comment by einarjon** [comment] 2021-11-18 08:06
2 discoveries here: 
1. A lot of this seems to be caused by ripgrep search indexing. Setting the `"search.followSymlinks": false` made my CPU load/disk use drop to acceptable levels. Maybe ripgrep needs a feature to detect and not follow circular symlinks.
2. For those using remote-SSH, a [PR was merged](https://github.com/microsoft/vscode-remote-release/issues/472#issuecomment-972142006) yesterday to move the server folder to any location. It should be in the current [remote SSH nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-nightly)

**Closed as completed** 2022-04-07 11:21 UTC
Labels: Language Service, more info needed
