### ISSUE TITLE
New lines not preserved in documentation popup with Doxygen tag

### ISSUE THREAD

**Issue by UwUSnek** [microsoft/vscode-cpptools#6652] opened 2020-12-11 16:26 UTC
**Type: LanguageService**

**Documentation popup window puts description all in the same line when using any @ tag**
- OS and Version: Fedora 32 Workstation 5.9.11-100.fc32.x86_64
- VS Code Version: 1.51.1 e5a624b788d92b8d34d1392e4c4d9789406efe8f
- C/C++ Extension Version: 1.1.3

![2](https://user-images.githubusercontent.com/47669437/101925954-cccba080-3bd2-11eb-9750-b0245e6b9c29.png)
![1](https://user-images.githubusercontent.com/47669437/101925951-cc330a00-3bd2-11eb-8843-c3ea88c72a52.png)
![3](https://user-images.githubusercontent.com/47669437/101925956-cd643700-3bd2-11eb-9437-02c6b575dcc3.png)

**Comment by michelleangela** [comment] 2020-12-11 19:36
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/5741

**Closed as completed by michelleangela** 2020-12-11 19:36 UTC
Labels: duplicate, Language Service, Feature: Doc comments
