### ISSUE TITLE
Cannot debug a c++ program: "Program received signal SIGSEGV, Segmentation fault."

### ISSUE THREAD

**Issue by tomatac** [microsoft/vscode-cpptools#7414] opened 2021-04-23 07:55 UTC
Bug type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.55.2
- C/C++ Extension Version: 1.3.1
- Other extensions you installed (and if the issue persists after disabling them): none
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. run the debugger to the first line of code of the main program (cout << "Hello World\n";)
2. get a multiple faults in a loop: Program received signal SIGSEGV, Segmentation fault. __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
3. it happens for multiple programs that used to work
4. if I run gdb, from the terminal, inside vs code, debugging is normal

Do you have any suggestions to troubleshoot this issue?

**Additional context**
![image](https://user-images.githubusercontent.com/15964070/115837915-f5a84180-a3cd-11eb-8162-b7fbe99e442d.png)

![image](https://user-images.githubusercontent.com/15964070/115838267-58014200-a3ce-11eb-8542-4ff124e15f92.png)

Running within a container. See also: 
https://github.com/microsoft/vscode-dev-containers/issues/827

**Comment by sean-mcmanus** [comment] 2021-04-23 21:47
This doesn't seem like an issue with our extension. I assume it would crash when you run the app from the command line, right? It seems like some issue with your compiler, libraries, or runtime.

**Comment by Chuxel** [comment] 2021-04-23 22:15
@sean-mcmanus The strange thing is that it appears to run fine from the terminal based on this comment:

> if I run gdb, from the terminal, inside vs code, debugging is normal

This was originally raised as microsoft/vscode-dev-containers#827 where it happened from inside a development container that should give a consistent content toolchain.

**Comment by tomatac** [comment] 2021-04-24 05:19
I think it is an issue with the interface between the VS Code and gdb that is particular to this project (folder in VS Code).
The gdb works fine from a terminal inside the VS Code.
If not debugged the program runs fine from VS Code.
It does not seam to be related to the container as I stripped down the container to the basics and it is still happening.
The same container configuration in a different project works fine.
Debugging used to work in this project. It looks like something got corrupted and it stooped working. 

It is interesting that when I choose the debug option I can see some Launch options from my old configuration, when my launch.json has only one configuration "Build Main" copied from the vscode-remote-try-cpp".

![image](https://user-images.githubusercontent.com/15964070/115948065-ac64fa00-a480-11eb-84ee-4eb19175160b.png)

Is VS Code cashing some data that can affect debugging?

Is there a way to troubleshoot the VS Code debugger?

**Comment by tomatac** [comment] 2021-04-24 05:36
I uninstalled VS Code and it is still not working.

**Comment by tomatac** [comment] 2021-04-24 08:01
Deleting all files and sub-folders from this folder solved the issue: ~/.config/Code
Obviously I lost my configuration settings

**Comment by tomatac** [comment] 2021-04-24 08:30
The same issue appeared again as I was just stepping through the program using the VS Code debugger.
Some UI clues when that happens:

![image](https://user-images.githubusercontent.com/15964070/115952712-6f0e6580-a49c-11eb-8303-fbe8e2e7f1b2.png)

![image](https://user-images.githubusercontent.com/15964070/115952714-75044680-a49c-11eb-931b-7d9b3dbd2627.png)

![image](https://user-images.githubusercontent.com/15964070/115952716-7a619100-a49c-11eb-9e03-a480264fc35a.png)

**Comment by sean-mcmanus** [comment] 2021-04-26 17:23
@tomatac Do you have expressions in the watch Window that when evaluated could cause your program to crash when evaluated?

@WardenGnaw Do you think this could be a C/C++ debugger bug?

**Comment by tomatac** [comment] 2021-04-27 05:32
I am not sure if i had anything in the watch window. If it was any variable, it was something simple (not an expression). 
It looks like when the crash appear, to recover and be able to debug again, the fix is to erase all VS Code settings.
I could try to erase just part of the settings and see what setting makes the debugger crash.
Do you know what settings (files, folder, ...) could be linked to the debugger?

**Comment by sean-mcmanus** [comment] 2021-04-27 18:48
I don't know of any debugger settings that could affect this, other than launch.json. @WardenGnaw might.

**Comment by tomatac** [comment] 2021-04-27 20:16
Deleting all files and sub-folders from this folder solved the issue: ~/.config/Code
Typically the launch.json is typically stored with the project and that did not seam to have an influence on this specific issue.

**Comment by sean-mcmanus** [comment] 2021-04-27 20:46
Yeah, I'm not aware of any debugger extension data that is cached at ~/.config/Code by our extension, so I'm guessing maybe VS Code itself might have stored something there that caused the issue?

**Comment by WardenGnaw** [comment] 2021-04-28 00:33
The only customizations I am aware of are gdb init file or customizations to launch the debugger in launch.json with `setupCommands`.

**Comment by WardenGnaw** [comment] 2021-05-13 00:13
Closing due to it being cause by external folders.

**Closed as completed by WardenGnaw** 2021-05-13 00:13 UTC
Labels: debugger, external

**Comment by cffjob** [comment] 2022-10-25 08:56
> I encountered the same problem. There is a variable in the watch window, the problem disappears after I deleting the variable in the watch window.
Thanks.

**Comment by cffjob** [comment] 2022-10-25 08:57
> @tomatac Do you have expressions in the watch Window that when evaluated could cause your program to crash when evaluated?
> 
> @WardenGnaw Do you think this could be a C/C++ debugger bug?

I encountered the same problem. There is a variable in the watch window, the problem disappears after I deleting the variable in the watch window.
Thanks.

**Comment by Orbitoly** [comment] 2022-11-14 18:00
Encountered the same, solved by removing all breakpoints.

**Comment by larsbs** [comment] 2022-11-22 11:04
> > @tomatac Do you have expressions in the watch Window that when evaluated could cause your program to crash when evaluated?
> > @WardenGnaw Do you think this could be a C/C++ debugger bug?
> 
> I encountered the same problem. There is a variable in the watch window, the problem disappears after I deleting the variable in the watch window. Thanks.

I can confirm I had a variable in the watch window that I hadn't added there, and deleting it fixed the issue.

**Comment by heddxh** [comment] 2024-05-13 02:17
> I can confirm I had a variable in the watch window that I hadn't added there, and deleting it fixed the issue.

Same here. Should it be re opened? Watching an  non-exist variable should not lead to segmentation fault and interruprt the debugger.

**Comment by programmer-04** [comment] 2024-09-02 17:43
> > I can confirm I had a variable in the watch window that I hadn't added there, and deleting it fixed the issue.
> 
> Same here. Should it be re opened? Watching an non-exist variable should not lead to segmentation fault and interruprt the debugger.

I agree that it should be reopened. I spent a long time trying to find what's wrong.
