### ISSUE TITLE
Error getting stack trace

### ISSUE THREAD

**Issue by alanbirtles** [microsoft/vscode-cpptools#1339] opened 2017-12-12 11:24 UTC
When trying to get the stack trace after stopping at a breakpoint or exception visual studio code is throwing a NullReferenceException.
I'm running cpptools 0.14.4 on Centos 7 in vs code 1.18.1
stack trace of error:
[stacktrace.txt](https://github.com/Microsoft/vscode-cpptools/files/1551357/stacktrace.txt)

**Comment by nzjony** [comment] 2017-12-12 15:11
I also started having a similar problem starting today, please see image:

![stack_trace_error](https://user-images.githubusercontent.com/2533428/33891651-e39596a8-df56-11e7-9279-8c3237689f3c.png)

I'm running also running cpptools 0.14.4, Ubuntu 16.04 with code 1.18.1

**Comment by pieandcakes** [comment] 2017-12-12 19:32
Can either of you tell me if this is 100% reproducible and what the steps are to hit this?

**Comment by pieandcakes** [comment] 2017-12-12 20:34
I have CentOS 7 with 0.14.4 installed with a multithreaded C++ app. I have set breakpoints and also hit pause to try and replicate this and i'm not able to.

**Comment by sean-mcmanus** [comment] 2017-12-12 20:52
I also am not able to repro this on Mint/Ubuntu 16.04. Do you have a breakpoint in some file "special" file or is there anything else unusual about your scenario? What is your debugger type? gdb?

**Comment by alanbirtles** [comment] 2017-12-12 21:18
I don't know how to reproduce it but I was unable to hit these breakpoints all day, this was with gdb

**Comment by pieandcakes** [comment] 2017-12-12 21:27
Ok. I think I might have figured out what the problem is. The log file helped out immensely. I'm going to see if I can make a fix.

**Comment by pieandcakes** [comment] 2017-12-13 00:48
@alanbirtles @nzjony Can either of you try [this release](https://github.com/Microsoft/vscode-cpptools/releases/download/v0.14.5-insiders/cpptools.vsix) and see if it fixes the problem?
Steps:
1. Download the file.
2. Uninstall the existing extension.
3. Go to Extensions -> `...` -> Install from VSIX and choose the file that was downloaded.

It should prompt you to reload. Then try debugging.

Please let me know.

Thanks

**Comment by pieandcakes** [comment] 2017-12-14 01:01
Can anyone confirm if this fixes their issue? I would like to know if I need to investigate more. Thanks!

**Comment by ytimenkov** [comment] 2017-12-14 07:06
@pieandcakes I've had similar issue when debugging remote target on CentOS 7.4 (debugger just failed to show any call stack and execute any command when execution stopped at breakpoint).

With 0.14.5-insiders release the problem is gone and debugger started working again.
Thanks for quick fix!

**Comment by alanbirtles** [comment] 2017-12-14 10:26
seems to work for me too

**Comment by alexbaden** [comment] 2017-12-14 20:45
Resolved here, Arch w/ code 1.18.1.

**Comment by josesimoes** [comment] 2017-12-15 15:57
I stumbled on this today too. Installed the fix from @pieandcakes and it's gone.
If this is relevant I'm using VS Code on a Windows 10 64bits setup.

**Comment by pieandcakes** [comment] 2017-12-15 19:01
We're probably releasing this fix next week with a few other bugfixes.

**Comment by sean-mcmanus** [comment] 2017-12-19 11:12
Fixed with 0.14.5.

**Closed as completed by sean-mcmanus** 2017-12-19 11:12 UTC
Labels: bug, debugger, fixed
