### ISSUE TITLE
Parsing not working - log filled with database errors

### ISSUE THREAD

**Issue by etcetc** [microsoft/vscode-cpptools#2296] opened 2018-07-20 00:09 UTC
Type: LanguageService
**----- Input information below -----**

Running version 0.17.7.  Upon startup, I see that the log is filled with errors for every file.

Unable to add file to database, error = 0x8064000a

Additionally, it tries to parse /usr/local/include, /usr/include, /use/local/Cellar, etc. even though I don't include any of these in my c_cpp_properties.json file because the project is for an embedded system that uses a cross-compiler.  E.g. I see:

Unable to add file to database, error = 0x8064000a: /usr/include/netinet/in_pcb.h
Unable to add file to database, error = 0x8064000a: /usr/include/netinet/in_systm.h
Unable to add file to database, error = 0x8064000a: /usr/include/netinet/in_var.h
Unable to add file to database, error = 0x8064000a: /usr/include/netinet/ip.h

It seems to even want to add .o and .d files to the database, which seems strange:

   Unable to add file to database, error = 0x8064000a: 
   /Users/ff/build/bootloader/bootloader_support/src/bootloader_random.o

Because I don't use any Mac frameworks or include files, I have removed references from my browse and include paths.

**Describe the bug**
- OS and Version: MacOS 10.12.6
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.7
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Provide a code sample including configuration files such as c_cpp_properties.json*

Note sure it is easily reproducible because intellisense seems to work in a simple C++ program.  This used to work pretty well until I updated a couple days ago.

**Expected behavior**

Would be nice to have Parsing and IntelliSense work.

**Screenshots**

**Additional context**
*Call Stacks: For bugs like crashes, deadlocks, infinite loops, etc. that we are not able to repro and for which the call stack may be useful, please attach a debugger and/or create a dmp and provide the call stacks. Starting with 0.17.3, Windows binaries have symbols available in VS Code by setting your "symbolSearchPath" to "http://msdl.microsoft.com/download/symbols".*
Add any other context about the problem here including log messages in your Output window ("C_Cpp.loggingLevel": "Debug" in settings.json).

Here is the salient part of the c_cpp_properties.json:

    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceRoot}/main/include",
                "${workspaceRoot}/main/include/devices",
                "${workspaceRoot}/main/include/ArduinoJson",
                "${workspaceRoot}/main/include/neopixel",
                "${workspaceRoot}/main/include/OneWire",
                "${workspaceRoot}/main/include/utils",
                "${workspaceRoot}",
                "${workspaceRoot}/../../xtensa-esp32-elf/include",
                "${workspaceRoot}/../../xtensa-esp32-elf/xtensa-esp32-elf/include",
                "${workspaceRoot}/../../xtensa-esp32-elf/xtensa-esp32-elf/sysroot/usr/include",
                "${workspaceRoot}/../../xtensa-esp32-elf/lib/gcc/xtensa-esp32-elf/5.2.0/include",
                "${workspaceRoot}/../../xtensa-esp32-elf/lib/gcc/xtensa-esp32-elf/5.2.0/include-fixed",
                "${workspaceRoot}/components/esp-request/include",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/newlib",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/config",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/log",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/driver",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/esp32",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/esp32/rom",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/esp32/xtensa",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/soc",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/freertos",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/fatfs",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/expat",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/ethernet",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/openssl",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/spi_flash",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/spiffs",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/heap",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/nvs_flash",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/json",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/jsmn",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/lwip",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/app_update",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/tcpip_adapter",
                "${workspaceRoot}/components/arduino-esp32/tools/sdk/include/vfs",
                "${workspaceRoot}/components/arduino-esp32/libraries/Wire/src",
                "${workspaceRoot}/components/arduino-esp32/libraries/FS/src",
                "${workspaceRoot}/components/arduino-esp32/libraries/WiFi/src",
                "${workspaceRoot}/components/arduino-esp32/libraries/Preferences/src",
                "${workspaceRoot}/components/arduino-esp32/libraries/HttpClient/src",
                "${workspaceRoot}/components/arduino-esp32/cores/esp32",
                "${workspaceRoot}/components/arduino-esp32/variants/esp32",
                "${workspaceRoot}/components/arduino-esp32/variants/esp32/pins_arduino.h"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "${workspaceRoot}/../esp-idf"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17"
        },

**Comment by sean-mcmanus** [comment] 2018-07-20 00:26
This is caused by dangling processes (from the old, buggy version of the extension) maintaining a lock on the database. Fix this via killing the dangling Microsoft.VSCode.CPP.Extension processes. It was bug https://github.com/Microsoft/vscode-cpptools/issues/2169 . You can also fix it by changing your `databaseFilename` to something like `${workspaceFolder}/.vscode/vc.db`.

We thought of adding code to auto-kill the old dangling processes it finds...but our hope is that 0.17.7 won't dangle processes so this won't be an issue any more...we may need to reconsider that later if it continues to be a problem.

Let us know if you're not able to get this resolved.

**Comment by etcetc** [comment] 2018-07-20 01:07
Seems it fixed it - thanks!  There were about 9 processes dangling.

Regarding other part of question - why does it add all the files in /usr/local to the database even though I have not explicitly asked that they be included?  The /usr/local/Cellar files seem irrelevant, for example.

**Comment by sean-mcmanus** [comment] 2018-07-20 01:25
Those files are added because the /usr/include and /usr/local/include are added from querying your compilerPath (/usr/bin/clang), and it appears some symlink recursively points to those files. Only the names/paths of the files are added to the database and they aren't open/parsed unless another file #includes them (with Debug logging you'll see "tag parsed" for the files that are opened/parsed). Setting the compilerPath to "" would remove those files, but that would break most of the IntelliSense features due to missing system headers/defines.

You can also add those particular folders to the files.exclude setting to make them not be added to the database at all.

**Comment by etcetc** [comment] 2018-07-20 03:22
Got it!  Your prompt responses are much appreciated.

**Comment by bobbrow** [comment] 2018-07-20 03:25
It would be better if you set `compilerPath` to the path to your extensa-esp32-elf compiler and removed the `"${workspaceRoot}/../../xtensa-esp32-elf/...` includePaths (assuming this compiler is a GCC variant and can be queried similar to GCC and CLang)

**Comment by Colengms** [comment] 2019-10-14 20:48
This issue appears to have been addressed.  Closing.  If there is still an issue here, please let us know.

**Closed as completed by Colengms** 2019-10-14 20:48 UTC
Labels: Language Service
