### ISSUE TITLE
Debugging: Attaching to a process results in a Error.

### ISSUE THREAD

**Issue by iyyappam** [microsoft/vscode-cpptools#1022] opened 2017-09-08 18:53 UTC
OS: xubuntu 16.04
VSCode: 1.15.1
C++ Extension : 0.12.3

I'm trying to attach to pid 5225.

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "somename.exe",
            "cwd": "${workspaceRoot}",
            "environment": [],
            "processId":"5225"
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

Issue: VSCode pops up with a message "Unable to open 'syscall-template.S': File not found (/build/glibc-bfm8X4/glibc-2.23/sysdeps/unix/syscall-tempalte.S. (CreateFile or Close)

Even if I close the message, it pops up repeatedly.

Another issue: Process picker didn't work.

**Comment by pieandcakes** [comment] 2017-09-08 20:12
@iyyappam When you say Process picker doesn't work, what about it is not working? 

The error that you get about syscall-template.S is expected because it is stopping on a library code file. can you verify if you can see items in the call stack window? When you get the VSCode error, is debugging paused?

**Comment by pieandcakes** [comment] 2017-09-08 20:19
Looks like the process picker issue is a duplicate of #1016

**Closed as completed** 2017-10-07 01:03 UTC
Labels: debugger, more info needed
