### ISSUE TITLE
Add support for embedded-SQL C code

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8069] opened 2021-08-27 18:13 UTC
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/8054

<div type='discussions-op-text'>

<sup>Originally posted by **pbderr** August 25, 2021</sup>
My project has lots of C code with embedded SQL processed by the Oracle Pro*C precompiler. (https://en.wikipedia.org/wiki/Pro*C)
The SQL code is prefixed by "exec sql" (case insensitive) and terminated by a semi-colon (;), possibly multiple lines.

For example:
    exec sql select count(*)
               into :PayerCnt
               from t_re_pat_liab
              where sak_recip = :sakRecip;

How can I configure the VScode C/C++ extension to not consider this to be an error?

My SQL-C source files are named \*.sc and in settings.json I can make them be recognized as C code like this:
  "files.associations": {
        "*.sc": "c"
}</div>

**Comment by bobbrow** [comment] 2021-09-07 22:16
This is a duplicate of #3688 which was closed with insufficient upvotes.  We should use that as the main issue tracking community interest in this feature.

**Closed as completed** 2021-09-07 22:16 UTC
Labels: duplicate, Language Service, Feature Request, parser, Visual Studio
