### ISSUE TITLE
code folding issue

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-cpptools#2116] opened 2018-06-11 15:13 UTC
_From @cctry on June 11, 2018 10:59_

- VSCode Version: 1.23.1
- OS Version: Windows10

Steps to Reproduce:

When writing C/C++ code with conditional compilation preprocessor instructions like \#ifdef, the code folding feature works abnormally.
It cannot fold a function correctly with a pair of preprocessor instructions inside. The code between the start of the function and \#ifdef will be folded but rest of the code not.
The code should be folded as a whole function including everything between the braces.

# Example:
![expand](https://user-images.githubusercontent.com/17473714/41227709-5a1d9ac0-6da8-11e8-8623-b570d4f2ac05.PNG)
after folded
![folded](https://user-images.githubusercontent.com/17473714/41227909-0e3e9b44-6da9-11e8-86ad-2cd1dc1b7aa4.PNG)

The 'return' statement remains unfolded.

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#51604_

**Comment by aeschli** [comment] 2018-06-11 15:13
_From @vscodebot[bot] on June 11, 2018 10:59_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [\[folding\] language-aware folding (#3422)](https://www.github.com/Microsoft/vscode/issues/3422) 
- [how to comment the folded code? (#48985)](https://www.github.com/Microsoft/vscode/issues/48985) 
- [Fold All working only on some lines (#47409)](https://www.github.com/Microsoft/vscode/issues/47409) 
- [Code folding no longer works by indentation (#47404)](https://www.github.com/Microsoft/vscode/issues/47404)

**Comment by aeschli** [comment] 2018-06-11 15:13
There's a new 'folding provider' API where language extension can contribute language aware foldig ranges.

Moving to the CPP extension for consideration.

**Comment by bobbrow** [comment] 2018-06-11 16:09
Thank you for the feature request.  This is a duplicate of #407.  I recommend you go upvote that feature so we can know where it fits on our priority list.

**Closed as completed by bobbrow** 2018-06-11 16:09 UTC
