### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AnomSanjaya** [microsoft/vscode-cpptools#3348] opened 2019-03-23 12:52 UTC
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.1`
- OS Version: `Windows_NT ia32 10.0.17763`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: 
[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/2999353/ms-vscode.cpptools-unresponsive.cpuprofile.txt)
` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bobbrow** [comment] 2019-03-23 17:16
Thank you for your issue report.  This looks like a duplicate of #3213.

**Closed as completed by bobbrow** 2019-03-23 17:16 UTC
Labels: duplicate, Language Service
