### ISSUE TITLE
C/C+ extension IntelliSence arm64

### ISSUE THREAD

**Issue by joolzg** [microsoft/vscode-cpptools#4848] opened 2020-01-14 11:53 UTC
Type: General

**Describe the bug**
- ubuntu 18.04 LTS
Version: 1.42.0 (user setup)
Commit: 22e4d75bd07b1ec7362c69da9dda7667eae95374
Date: 2020-01-13T06:29:20.418Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux arm64 4.9.140-tegra

- C/C++ IntelliSence:

On starting i get asked to install c++ intellisence as i the project is a c++ project. If i say yes the program tries to install but pops up an error saying "Architecture arm64 is not supported."

**Comment by pieandcakes** [comment] 2020-01-14 16:51
Hi @joolzg. This looks like a duplicate of #2506. Please comment or upvote that issue

**Closed as completed** 2020-01-14 16:51 UTC
Labels: duplicate, Language Service

**Comment by sean-mcmanus** [comment] 2020-09-14 21:31
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.0.0
