### ISSUE TITLE
Intellisense (C++ Go To Definition, formatter, switch source/header file) stops working

### ISSUE THREAD

**Issue by mark-yacoub** [microsoft/vscode-cpptools#1689] opened 2018-03-15 06:11 UTC
### Issue Type
Bug

### Description

After a lot of code copy-pasting around, checking out git branches that are different, or jumpa  lot through the code, VSCode suddenly stop working, so I can't go to definition, formatter doesn't work, can't Alt+O to header file.
It's fixed by restarting vscode though, which was embarrasing when I was showing off vscode to a co-worker.
It's been happening for a while, since i started using it last year, but it became more frequent recently.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.4.0-109-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 1696)|
|Load (avg)|0, 0, 0|
|Memory (System)|62.81GB (0.65GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.8
code-gnu-global|aus|0.2.2
python|ms-|2018.1.0
cpptools|ms-|0.14.6
debug|web|0.21.2

</details>
Reproduces only with extensions

**Comment by aanguss** [comment] 2018-03-15 15:35
I'm having a similar issue as of yesterday - seemingly after updating to the latest VSCode.  I tried uninstalling/reinstalling the extension as well as VSCode (per other suggestions found online), but neither helped.

**Comment by sean-mcmanus** [comment] 2018-03-15 20:54
@mark-yacoub We haven't seen a repro of this yet (and it's not something we've received many complaints about). Is there a red flame or database icon in the bottom right? What are the Microsoft.VSCode.CPP processes doing? Are you able to get a call stack for the Microsoft.VSCode.CPP.Extension.linux process when it's stuck? Our latest version is 0.15.0 (which fixed some crashes with 0.14.6) and we have an 0.16.0-insiders at https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders . Another user reported an issue with failures after pasting, but we're not able to get a repro yet ( https://github.com/Microsoft/vscode-cpptools/issues/1662 ). Is your intelliSenseEngine set to "Default" or "Tag Parser"?

@aanguss Can you provide more repro details? Your issue might be different.

**Comment by dllerena** [comment] 2018-03-15 21:39
I have exactly the same issue as aanguss.
I'm using for ANSI C and using VSC 1.21.1

**Comment by sean-mcmanus** [comment] 2018-03-15 23:01
@dllerena What version of the C/C++ extension are you using? I don't understand what the issue is. Can you provide more details? Our extension hasn't released an update for several weeks, so I don't know what has changed. It could be another extension that is causing the failure or VS Code itself.

**Comment by dllerena** [comment] 2018-03-15 23:17
@sean-mcmanus Im using cpptools 0.15.0
When I click on "Peek definition" it doesn't work. I tried it with several variables.
I haven't install any extension lately. I was only updating VSCode.
I had to downgrade VSCode to version 1.19.3 in order to use the extension.
I'm using these extensions:
vcterminal|esp|1.0.28
cpptools|ms-|0.15.0
vscode-icons|rob|7.21.0
partial-diff|ryu|0.5.1

The most important for me is cpptools due I'm a C developer.
I think its something related with VSCode latest updates.

**Comment by sean-mcmanus** [comment] 2018-03-15 23:23
@dllerena That is very strange. What OS are you using? I'm using VS Code 1.21 and 1.22-insiders and I'm not seeing any issue on Linux or Windows. Have you tried uninstalling our extension and reinstalling it?

**Comment by sean-mcmanus** [comment] 2018-03-15 23:25
Another thing to check for is to make sure there are no dangling Microsoft.VSCode.Extension processes -- if so they should be killed. We had an issue where a dangling process could block new processes, but that should have been fixed though.

**Comment by dllerena** [comment] 2018-03-15 23:27
Done and working. Updated VSCode and extension reinstalled. :) thanks!

**Comment by sean-mcmanus** [comment] 2018-03-15 23:32
@dllerena Oh, so it's fixed? It sounds like there might be a real bug with VS Code updating causing our extension to be in a corrupted installation state...not sure how to get that resolved yet.

**Comment by dllerena** [comment] 2018-03-15 23:34
@sean-mcmanus  yes. Before that, I was just enabling and disabling it, not reinstalling it. I just Update VSCode and reinstall the extension. That's it.

**Comment by aabuelenin** [comment] 2018-03-16 02:16
@sean-mcmanus I'd the same issue, the intellisense server was crashing very often, sometimes by just opening vscode, after installing cpp tools 0.16 I stopped having that issue (at least for the last hour).

**Comment by aanguss** [comment] 2018-03-16 17:52
I'm using VS Code 1.21.1 with C/C++ 0.15.0.  

I went back to attempt to try more troubleshooting after @dllerena got his working, and I noticed my Output tab gives the below error.  I previously had a proxy setup for VS Code, but perhaps it was reset after the VSCode update.  Either way, adding the proxy back fixed my error, so I'm back to using VS Code again. 👍 

```
Updating C/C++ dependencies...
Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying...Waiting 32 seconds...
Failed at stage: downloadPackages
Error: read ECONNRESET
	at exports._errnoException (util.js:1050:11)
	at TLSWrap.onread (net.js:581:26)
```

**Comment by gregcoombe** [comment] 2018-04-04 22:08
I've noticed the same issues with bazel (also fixed by restarting). VS Code 1.21.1 with C/C++ 0.16.1

You mentioned dangling processes, I appear to have a bunch
`$ ps -A | grep IntelliSense | wc -l
      75
`

Pure speculation: one of the culprits might be that bazel manages a lot of files behind the scenes as soft-links. For third-party precompiled packages that are downloaded and unpacked, these files can disappear and re-appear frequently (depending on build dependencies). Some of these files are headers that are pointed to in my includePath config (in c_cpp_properties.json). So I often (1-2x per day) get the warning to fix my include paths, likely based on which bazel targets I've recently built.

**Comment by bobbrow** [comment] 2019-11-07 22:51
We don't have enough information to address this issue and since there hasn't been any activity on this issue in a very long time, we're inclined to think that the issue has been resolved.  If you continue to experience this problem, please let us know and help us get the information we need to investigate it.

**Closed as completed by bobbrow** 2019-11-07 22:51 UTC
Labels: Language Service, not reproing
