### ISSUE TITLE
CUDA C++: #include error squiggles on CUDA system include files, limited IntelliSense with deviceQuery sample project

### ISSUE THREAD

**Issue by ackalker** [microsoft/vscode-cpptools#11454] opened 2023-09-21 21:56 UTC
Type: <b>Bug</b>

1. Install latest CUDA Toolkit in WSL, add `/usr/local/cuda/bin` to PATH, verify version is `V12.2.140` by running `nvcc --version`.
2. Clone the CUDA Samples project from GitHub: https://github.com/NVIDIA/cuda-samples
3. Connect VSCode to WSL, make sure the C/C++ and Makefile Tools extensions are installed and enabled in WSL.
4. In the cloned repository, open the folder `Samples/1_Utilities/deviceQuery` in VSCode.
5. Open the file `deviceQuery.cpp` from the Explorer.

Extension version: 1.17.5
VS Code version: Code - Insiders 1.83.0-insider (11bfd76a61a299156a9f3138ecfad70937af3527, 2023-09-21T05:34:38.227Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400F (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (5.57GB free)|
|Process Argv|--crash-reporter-id 78c6d751-e4b0-4959-a782-10106e5f6b9d|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400F (12 x 2496)|
|Memory (System)|7.65GB (6.07GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
asynctok:30821568
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttype:30823781
pythonmypyww:30841056
pythonmpsinfo:30815194
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiag:30842812
pythonmypyd1:30841190

```

</details>

**Comment by ackalker** [comment] 2023-09-21 22:02
Here is the log output of C/C++ extension with loglevel `debug` after opening the workspace but before opening the `deviceQuery.cpp` file:
 
[cpptools-devicequery-debug-1.log](https://github.com/microsoft/vscode-cpptools/files/12693699/cpptools-devicequery-debug-1.log)

Here is the log output after opening the `deviceQuery.cpp` file:
[cpptools-devicequery-debug-2.log](https://github.com/microsoft/vscode-cpptools/files/12693708/cpptools-devicequery-debug-2.log)

**Comment by ackalker** [comment] 2023-09-21 22:09
I can build a working `deviceQuery` binary without errors by running `make` at a shell prompt, the output of doing that is:

```shell
$ make
/usr/local/cuda/bin/nvcc -ccbin g++ -I../../../Common -m64 --threads 0 --std=c++11 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_89,code=sm_89 -gencode arch=compute_90,code=sm_90 -gencode arch=compute_90,code=compute_90 -o deviceQuery.o -c deviceQuery.cpp
/usr/local/cuda/bin/nvcc -ccbin g++ -m64 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_89,code=sm_89 -gencode arch=compute_90,code=sm_90 -gencode arch=compute_90,code=compute_90 -o deviceQuery deviceQuery.o
mkdir -p ../../../bin/x86_64/linux/release
cp deviceQuery ../../../bin/x86_64/linux/release
$ 
```

**Comment by ackalker** [comment] 2023-09-21 22:15
From the logs, it seems to me that the C/C++ extension has difficulty getting the compiler configuration from `nvcc`. This seems strange to me, when I run `nvcc --dryrun -v -c` with a nonexistent file, I get lots of easy to parse output and no errors:

```bash
$ /usr/local/cuda/bin/nvcc --dryrun -v -c dummy.cpp
#$ _NVVM_BRANCH_=nvvm
#$ _SPACE_=
#$ _CUDART_=cudart
#$ _HERE_=/usr/local/cuda/bin
#$ _THERE_=/usr/local/cuda/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_DIR_=targets/x86_64-linux
#$ TOP=/usr/local/cuda/bin/..
#$ NVVMIR_LIBRARY_DIR=/usr/local/cuda/bin/../nvvm/libdevice
#$ LD_LIBRARY_PATH=/usr/local/cuda/bin/../lib:
#$ PATH=/usr/local/cuda/bin/../nvvm/bin:/usr/local/cuda/bin:/home/miki/.vscode-server-insiders/bin/11bfd76a61a299156a9f3138ecfad70937af3527/bin/remote-cli:/usr/local/cuda/bin::/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2/bin:/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2/libnvvp:/mnt/c/Program Files/openxr-explorer/bin:/mnt/c/Program Files/Oculus/Support/oculus-runtime:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/NVIDIA Corporation/Nsight Compute 2023.2.2/:/mnt/c/Users/ackal/scoop/apps/nodejs/current/bin:/mnt/c/Users/ackal/scoop/apps/nodejs/current:/mnt/c/Users/ackal/scoop/apps/python/current/Scripts:/mnt/c/Users/ackal/scoop/apps/python/current:/mnt/c/Users/ackal/scoop/shims:/mnt/c/Users/ackal/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/ackal/AppData/Local/Programs/Microsoft VS Code Insiders/bin:/snap/bin
#$ INCLUDES="-I/usr/local/cuda/bin/../targets/x86_64-linux/include"
#$ LIBRARIES=  "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib/stubs" "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib"
#$ CUDAFE_FLAGS=
#$ PTXAS_FLAGS=
#$ gcc -D__CUDA_ARCH_LIST__=520 -c -x c++ -D__NVCC__  "-I/usr/local/cuda/bin/../targets/x86_64-linux/include"    -D__CUDACC_VER_MAJOR__=12 -D__CUDACC_VER_MINOR__=2 -D__CUDACC_VER_BUILD__=140 -D__CUDA_API_VER_MAJOR__=12 -D__CUDA_API_VER_MINOR__=2 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -m64 "dummy.cpp" -o "dummy.o"
$
```

Sure, there may need to be added some other options which are important to VSCode, but they are easy enough to add (I tried a few with good results).

**Comment by Colengms** [comment] 2023-09-22 18:13
Hi @ackalker .  Could you enable `"C_Cpp.loggingLevel": "Debug"` and provide the output from the C/C++ output channel, from launch and leading up to the repro?

There is a step that interrogates nvcc and attempts to solicit the actual command line nvcc will use.  The args you are seeing (`-x c++ -E -dM /dev/null`) are not part of that query, and would suggest that a prior step has failed.  There should be more information about that in Debug output to the C/C++ output channel.  It's possible that a recent release of the CUDA SDK has altered something we depend on to do the proper query.

**Comment by sanannavyaa** [comment] 2023-09-22 19:41
I have also been investigating this issue (since it was also reported https://github.com/NVIDIA/nsight-vscode-edition/issues/39) and an additional note - I could only reproduce it on WSL. Let me know if I can help with anything else.

**Comment by ackalker** [comment] 2023-09-22 20:21
> Hi @ackalker .  Could you enable `"C_Cpp.loggingLevel": "Debug"` and provide the output from the C/C++ output channel, from launch and leading up to the repro?

@Colengms I have uploaded what I believe are the logs you are asking for in comment https://github.com/microsoft/vscode-cpptools/issues/11454#issuecomment-1730357635
If they don't contain the information you require, please let me know.

**Comment by Colengms** [comment] 2023-09-22 22:19
I was able to identify a few new CUDA issues that repro'ed with that sample.  I have a fix in progress.  These should be addressed by the next release of the C/C++ Extension (1.18.0).

**Comment by ackalker** [comment] 2023-09-22 23:32
@Colengms @sanannavyaa Thank you very much for looking into this, I'm looking forward to the new release.

**Comment by sean-mcmanus** [comment] 2023-10-10 21:44
@sanannavyaa 1.18.0 will be our "insiders" or pre-release, see https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.0 for a past example. The final release will be 1.18.2+ later on.

**Comment by sean-mcmanus** [comment] 2023-10-13 17:11
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.18.0

**Comment by sanannavyaa** [comment] 2023-10-13 18:05
Can confirm that it resolves the bug on my end. Thanks!

**Closed as completed** 2023-11-16 23:29 UTC
Labels: bug, Language Service, fixed, Feature: CUDA
