### ISSUE TITLE
substitution: ${env.XXX} not supported in c_cpp_properties.json

### ISSUE THREAD

**Issue by wsw0108** [microsoft/vscode-cpptools#773] opened 2017-05-26 03:10 UTC
Not like in [tasks.json](https://code.visualstudio.com/docs/editor/tasks#_variable-substitution)

**Comment by sean-mcmanus** [comment] 2017-05-26 15:25
`${ENV}` is supported with includePath and browse.path. Is that okay, or did you want the `${env.ENV}` syntax to work or for environment variables to work on other properties.

**Comment by wsw0108** [comment] 2017-05-26 16:05
## Environment
os: Windows 10
vscode version: 1.12.2
extension version: 0.11.2

## Case
file a.cpp:
```
#include <jni.h>
...
```
c_cpp_properties.json
```
        {
            "name": "Win32",
            "includePath": [
                "${env.JAVA_HOME}/include",
                "${env.JAVA_HOME}/include/win32"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "",
                "path": [
                    "${env.JAVA_HOME}/include",
                    "${env.JAVA_HOME}/include/win32"
                ]
            }
```

## Result
- `Go To Definition` works fine just now when cursor on line `#include <jni.h>`
- But there was a red line under source line with tip says 'cannot open source file "jni.h"'

**Comment by wsw0108** [comment] 2017-05-26 16:08
If replace `${env.JAVA_HOME}` with absolute path like `"C:/Program Files/Java/jdk1.8.0_77`, red line gone.

**Comment by sean-mcmanus** [comment] 2017-05-26 16:09
Can you try `${JAVA_HOME}?`

**Comment by wsw0108** [comment] 2017-05-28 00:46
`${JAVA_HOME}` has no problem. 
Maybe the document need update.

**Comment by sean-mcmanus** [comment] 2017-05-30 15:47
The docs are from the VS Code team. Our extension supports the different syntax...maybe we should change it to use the ${env.} syntax instead to avoid confusion and conflict with other special variables like ${workspaceRoot}.

**Comment by sean-mcmanus** [comment] 2017-07-26 19:42
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/697 .

**Closed as completed by sean-mcmanus** 2017-07-26 19:42 UTC
Labels: duplicate, Language Service
