### ISSUE TITLE
Highlight bug when using macros, reproducible inside

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#12519] opened 2024-07-26 02:39 UTC
Not important but I'm sure this affects a few people

### Environment

- OS and Version:  Linux but I seen it on mac as well
- VS Code Version: 1.91 and I seen it on older

### Bug Summary and Steps to Reproduce

Bug Summary:

When I defined my own assert macro, the first three letters are always highlighted incorrectly. When you move your cursor on the word it'll glow incorrectly as well. It has to do with the inner macro name length because if I make it a letter longer 4 letters are incorrectly highlighted

Steps to reproduce:
1. Copy paste source below into a cpp file, save.
2. Observe "assert(tes" highlighted, which is incorrect
3. Change SMM to SMMM on line 2 and 3
4. Observe "assert(test" highlighted, which is incorrect, you see it's now 4 letters off

Source

	#define SMM_INTERNAL_ASSERT(X)				(X)
	#define SMM_ASSERT(cond)					SMM_INTERNAL_ASSERT(cond)
	#define assert SMM_ASSERT
	int main() {
		int tester=1;
		assert(tester);
	}

Expected behavior:
Only 'assert' should have the macro color

### Configuration and Logs

```shell
No need
```

### Other Extensions

Doubt this is required

**Comment by Colengms** [comment] 2024-07-31 01:13
Hi @LevoDeLellis .  I believe this issue is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/12408 and has already been fixed in 1.21.4.  I can repro with 1.20.5, with the code you provided, but can no longer repro with 1.21.4.

Closing this issue as a dupe (and fixed).

**Closed as not planned by Colengms** 2024-07-31 01:13 UTC
