### ISSUE TITLE
Wrong bitness for xtensa-esp32-elf-gcc

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#7034] opened 2021-02-23 20:50 UTC
I'm also having the same issue with GCC 8 and Xtensa (ESP32):

![Screenshot_20210217_105622](https://user-images.githubusercontent.com/424549/108187455-c85dbf80-710e-11eb-816d-f7605fef862d.png)

This is obviously wrong, given that size_t IS unsigned int, and IntelliSense known that:

![Screenshot_20210217_105715](https://user-images.githubusercontent.com/424549/108187588-e9261500-710e-11eb-9d33-3efa78a08a74.png)

Everything else works fine, except standard literals for strings (like `s` and `sv`), which are broken in the same way.

Needless to say, this code compiles fine with GCC 8.4, triple is xtensa-esp32-elf, `sizeof(int) == 4`. The C/C++ extension I'm using is version 1.2.1.

_Originally posted by @mcilloni in https://github.com/microsoft/vscode-cpptools/issues/6573#issuecomment-780442797_

**Comment by Colengms** [comment] 2021-02-23 20:50
It does look like CMake Tools is providing the wrong bitness.  However, cpptools should be correcting the bitness, and is getting it wrong also.  It doesn't look like we're correctly detecting the bitness of this compiler.  Since it's not x86 or x64, we would be relying on the `--target` passed in, or falling back to the default target returned by the compiler when passed `-dumpmachine`.  However, this compiler returns `xtensa-esp32-elf-gcc` for `-dumpmachine`, which we are not handling.  We could possibly handle this by considering any occurrences of `32` and `64` within the target string instead of giving up.

**Comment by Colengms** [comment] 2021-04-14 01:02
Starting in 1.3.0, the extension should switch to 32-bit IntelliSense when we see a target that contains "esp32".

**Comment by mcilloni** [comment] 2021-04-19 13:54
Negative, it still does not work for me:

![Screenshot_20210419_154533](https://user-images.githubusercontent.com/424549/115246567-4ac22a00-a126-11eb-9640-39be8920988a.png)

The logs still report intellsenseMode as being "linux-gcc-x64" or "linux-clang-x64" with cpptools 1.3.0. Setting `"C_Cpp.default.intelliSenseMode": "gcc-x86"` in settings.json makes no difference, because it keeps reverting to "gcc-x64".
The detected compiler path is "/home/marco/.local/bin/xtensa-esp32-elf-gcc".

**Comment by mcilloni** [comment] 2021-04-20 14:58
I also tried changing configurations.compilerPath in c_cpp_properties.json, to no avail. In the log I still see this:

```
Querying compiler's default target using command line: "/home/marco/Workspace/p501_esp32/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc" -dumpmachine
Compiler returned default target value: xtensa-esp32-elf

Compiler does not support 32-bit. Falling back to 64-bit intelliSenseMode.
Failed to query compiler. Falling back to no bitness.
Compiler does not support 32-bit. Falling back to 64-bit intelliSenseMode.
Failed to query compiler. Falling back to no bitness.
```
(`/home/marco/.local/bin/xtensa-esp32-elf-gcc` and `/home/marco/Workspace/p501_esp32/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc` are the same compiler, the version in .local is just a symlink that happens to be in $PATH)

**Comment by sean-mcmanus** [comment] 2021-05-26 00:54
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders3

**Comment by mcilloni** [comment] 2021-05-26 08:38
Thanks a lot @sean-mcmanus, I can confirm IntelliSense finally works perfectly with 1.4.0-insiders3:

![Screenshot_20210526_103741](https://user-images.githubusercontent.com/424549/119629583-706ddd80-be0e-11eb-8966-bd4b9b68b013.png)

Great job to everyone involved, and again thanks you all for the time and effort you've put into this.

**Closed as completed** 2021-05-28 00:11 UTC
Labels: bug, Language Service, fixed, quick fix, Feature: Configuration
