### ISSUE TITLE
breakpoint stopped at same name file but in different directory

### ISSUE THREAD

**Issue by WZG3661** [microsoft/vscode-cpptools#7913] opened 2021-08-04 06:50 UTC
Bug type: Debugger

**Describe the bug**
- Version: 1.43.2
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Linux x64 5.4.0-80-generic
- C/C++ Extension Version: 0.28.3

Steps to Reproduce:
1. same name file in different directory
2. set a breakpoint in onefile, but stopped at another same name file in same line.
3. Note: another file's function must be called first.

**Comment by WardenGnaw** [comment] 2021-08-09 18:13
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/977#issuecomment-726325642

**Closed as completed by WardenGnaw** 2021-08-09 18:13 UTC
Labels: duplicate, debugger
