### ISSUE TITLE
This extension does not work in the latest VS Code in macOS

### ISSUE THREAD

**Issue by AwenChen** [microsoft/vscode-cpptools#4116] opened 2019-08-21 02:19 UTC
**Type: LanguageService**

**Describe the bug**
- VS Code Version: 1.37.1
- Extension Version: 0.25.0-insiders2: August 15, 2019
- Commit ID: f06011ac164ae4dc8e753a3fe7f9549844d15e35
- Date: 2019-08-15T16:16:34.800Z
- Electron: 4.2.7
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- The extension does not work any more, and if I uninstall it, then reinstall it, it would work ok.
- The detailed information is:
```
dyld: Symbol not found: __ZTISt18bad_variant_access
  Referenced from: /Users/zhengwen.chen/.vscode/extensions/ms-vscode.cpptools-0.25.0-insiders2/bin/Microsoft.VSCode.CPP.Extension.darwin
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/zhengwen.chen/.vscode/extensions/ms-vscode.cpptools-0.25.0-insiders2/bin/Microsoft.VSCode.CPP.Extension.darwin
[Error - 上午10:15:38] Connection to server got closed. Server will not be restarted.
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by michelleangela** [comment] 2019-08-21 16:27
Duplicate of #4096.

**Closed as completed by michelleangela** 2019-08-21 16:27 UTC
Labels: duplicate, Language Service
