### ISSUE TITLE
Add a way to use clang-format without enabling IntelliSense.

### ISSUE THREAD

**Issue by Yosh31207** [microsoft/vscode-cpptools#10129] opened 2022-11-10 02:19 UTC
### Feature Request

I want a way to use clang-format without enabling IntelliSense.

I am disabling IntelliSence (`"C_Cpp.intelliSenseEngine": "Disabled"`) because it spends much memory and sometime crashes, but doing this seems to disable all features of the extension.

My question is: Does Clang-format feature depend on IntelliSense engine? If not, it would be nice to add a way to use it without IntelliSence. Likewise, if there are other features that are not dependent on IntelliSense, would you consider enabling them when IntelliSense engine is disabled.

**Comment by browntarik** [comment] 2022-11-10 17:38
Thank you for your feature request. Unfortunately, this issue has been brought up within the past (reference https://github.com/microsoft/vscode-cpptools/issues/7083). Currently, when we disable the intellisense engine, we disable the extension altogether. Since this issue isn't common among our users, we decided to not to change its behavior. If this issue does get enough attention, we will reconsider in the future.

**Comment by browntarik** [comment] 2022-11-10 17:58
Since this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/7083, I will be closing this issue in favor of that one.

**Closed as completed by browntarik** 2022-11-10 17:58 UTC
Labels: duplicate, Language Service
