### ISSUE TITLE
Request textDocument/codeAction failed.   Message: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#8387] opened 2021-11-11 15:06 UTC
I am getting a bunch of these and it is quite annoying as the UI switches to the error:

> Request textDocument/codeAction failed.
  Message: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code

**Describe the bug**
- OS and Version: macOS 12 Monterey
- VS Code Version: 1.62.1
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them): C/C++ extension pack
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Build a CMake project
2. Open PROBLEMS section
3. Try to select a row - the UI switches to OUTPUT and displays this: 

> E[17:02:20.897] Failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
I[17:02:20.897] --> reply:textDocument/codeAction(322) 0 ms, error: -32602: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
[Error - 5:02:20 PM] Request textDocument/codeAction failed.
  Message: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
  Code: -32602 
I[17:02:21.049] <-- textDocument/codeAction(323)
E[17:02:21.049] Failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
I[17:02:21.049] --> reply:textDocument/codeAction(323) 0 ms, error: -32602: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
[Error - 5:02:21 PM] Request textDocument/codeAction failed.
  Message: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
  Code: -32602 
I[17:02:23.254] <-- textDocument/codeAction(324)
E[17:02:23.254] Failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
I[17:02:23.254] --> reply:textDocument/codeAction(324) 0 ms, error: -32602: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
[Error - 5:02:23 PM] Request textDocument/codeAction failed.
  Message: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
  Code: -32602 
I[17:02:25.454] <-- textDocument/codeAction(325)
E[17:02:25.454] Failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
I[17:02:25.454] --> reply:textDocument/codeAction(325) 0 ms, error: -32602: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
[Error - 5:02:25 PM] Request textDocument/codeAction failed.
  Message: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
  Code: -32602 
I[17:02:28.852] <-- textDocument/codeAction(326)
E[17:02:28.852] Failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
I[17:02:28.852] --> reply:textDocument/codeAction(326) 0 ms, error: -32602: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code
[Error - 5:02:28 PM] Request textDocument/codeAction failed.
  Message: failed to decode textDocument/codeAction request: expected string at (root).context.diagnostics[0].code

**Comment by Colengms** [comment] 2021-11-11 17:12
Hi @H-G-Hristov .  What is the currently selected Output channel when you see these errors?  Does this happen with the C/C++ extension disabled?  The C/C++ extension does not use the `textDocument/codeAction` language service message.  It provides CodeActions to VS Code using a CodeActionProvider.

Could you provide an image of what you are selecting in the Problems panel when the error occurs?

Could you try setting `"C_Cpp.loggingLevel": "Debug"`, and providing the output of the C/C++ output channel leading up to the issue?  If the issue is related to the C/C++ extension, I would expect that to include some indication of what happened.

**Comment by Zingam** [comment] 2021-11-12 03:51
I'll try to provide more information when I am back on the mac on Monday.
From memory:

I have installed everything from the C++ extension pack, python, test mate and gtest extensions, cmake tools, github extensions for pull requests, lens, tree, docker. I have disabled some of the extensions live share, etc.

The project I build is of mid size. It uses CMake and conan including CMake presets to setup the IDE. It has alot of cmake targets.

After I build the project I get hundreds of warnings: mostly compiler but also I assume intellisense ones inaccessible system headers, which is odd as I can navigate to them.

I have for example a warning about "memset". I want to copy the message of the warning in the PROBLEMs tab. When I move the message over the line with the memset. The channel (I assume) switches from CMake/Build to Language server and from PROBLEMS to Output.

Maybe I am also getting these errors when I move the mouse over the edit area.  I have difficulties following exactly what's going on.

**Comment by Zingam** [comment] 2021-11-27 09:15
@Colengms I followed your advise and went on and disabled some extensions. Then I observed the behavior for a while. Most probably the issue was caused by the Swift language server. So we can close this issue. Sorry for the trouble and thank you very much for the help.  (I guess I need to use my work account to be able to close the issue myself)

**Closed as completed** 2021-11-30 01:25 UTC
Labels: Language Service, more info needed
