### ISSUE TITLE
Language Server Crashed

### ISSUE THREAD

**Issue by ajwentzel** [microsoft/vscode-cpptools#10598] opened 2023-02-27 19:43 UTC
### Environment

- OS and Version: Windows 10 21H2
- VS Code Version: 1.75.1
- C/C++ Extension Version: 1.14.3
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:
Tried using the RP2040 Feather from Adafruit (https://www.adafruit.com/product/4884), following the setup guide here (https://learn.adafruit.com/adafruit-feather-rp2040-pico/arduino-ide-setup). Everything works fine on the Arduino IDE, but when I switch to VS Code, I get the following error:

[Error - 9:24:01 AM] Sending request cpptools/getInlayHints failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:24:01 AM] Sending request cpptools/getSemanticTokens failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:24:01 AM] The language server crashed 5 times in the last 3 minutes. It will not be restarted.

The code is a very simple .ino file with blank setup() and loop() functions. If I switch to a different board, the code compiles with no problem, so it seems like it's specific to the RP2040. I've attached both the c_cpp_properties.json and the language server logs.
[c_cpp_properties.txt](https://github.com/microsoft/vscode-cpptools/files/10843405/c_cpp_properties.txt)
[CCpp Language Server Logging.txt](https://github.com/microsoft/vscode-cpptools/files/10843406/CCpp.Language.Server.Logging.txt)

### Configuration and Logs

```shell
See attached logs
```

### Other Extensions

Other Extensions:
Arduino v0.5.0
Serial Monitor v0.8.0 
Both C/++ and Serial Monitor are required for using the Arduino extension.

### Additional context

I tried attaching the debugger following the guides here (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv), but there is no option for 'cpptools' when I try to attach it.

**Comment by Colengms** [comment] 2023-02-27 20:17
Hi @ajwentzel .  Thanks for reporting this.  Based on your logs, it looks like the extension works for some time before crashing.  Would you be able to attach the debugger to `cpptools.exe` before it crashes, and provide the resulting stack?  That would help immensely.

https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

**Comment by ajwentzel** [comment] 2023-02-27 20:23
@Colengms Thanks for the quick reply. As I mentioned above the cpptools.exe does not show up as an attach option when following those steps. Same result as the person in this issue (https://github.com/microsoft/vscode-cpptools/issues/10385#issuecomment-1397338360), but it looks like that issue was closed so I'm not sure what other steps to take.

**Comment by Colengms** [comment] 2023-02-27 20:36
@ajwentzel . There are a couple possible causes that come to mind.  The extension does that start up until it's activated, such as by opening a `.cpp` file.  Can you confirm the extension has activated before you try to attach to it?  Or, perhaps by the time you're trying to attach to it, the process has already crashed?  Could you confirm that by checking the C/C++ log output?  Also, could you try using a workspace folder the crash does not occur with, and check whether you are able to attach to `cpptools.exe` in that scenario?  I'm curious if the issue is that the process is not running, or if it's being filtered out for some reason.  You might also check the task manager, to see if `cpptools.exe` is listed at the time.  Note that there will be 2 instances of the process running, and you'd want to attach to the more sizable one.

**Comment by ajwentzel** [comment] 2023-02-27 21:13
I switched the board to one that I knew worked (Feather M0), added a couple basic files called Test.h and Test.cpp and restarted VS Code. I was then able to attach the debugger to cpptools since nothing crashed. Then I switched the board back to the Feather RP2040. Attached the call stacks from that. 
[cpptools call stack.txt](https://github.com/microsoft/vscode-cpptools/files/10844327/cpptools.call.stack.txt)
[lsp_manager thread call stack.txt](https://github.com/microsoft/vscode-cpptools/files/10844328/lsp_manager.thread.call.stack.txt)

Something I noticed while going through this process.
1 - Start with the Feather M0 selected
2 - Compile
3 - Switch to the Feather RP2040
4 - VS Code will recognize the board change and auto compile. At this point the language server crashes.
5 - Switch back to the Feather M0. 
6 - VS Code will recognize the board change and auto compile. I let it finish compiling.
7 - Restart VS Code with no issues.

- If instead at step 6, I close VS Code before it has a chance to compile with the M0.
- Restart VS Code. The language server will crash here because even though the Feather M0 is selected, it hasn't had a chance to compile with it (possibly from something in the c_cpp_properties.json file it generates?)

Not sure if this is useful to you, just something I noticed.

**Comment by sean-mcmanus** [comment] 2023-02-27 21:21
We have a previous issue at https://github.com/microsoft/vscode-cpptools/issues/10486 for that same crash call stack, but this issue has more repro details.

**Comment by Colengms** [comment] 2023-02-27 21:26
Hi @ajwentzel .  Thanks.  This will help us a lot.

The code involved in the crash is related to placing squiggles within a source file, possibly a particular source file, and relates to some squiggle locations that may be outside of the bounds of the file.  Is there a specific file that's open when this occurs that may be involved in the repro?

**Comment by ajwentzel** [comment] 2023-02-27 21:31
The only file I have explicitly open is Testing.ino. 
![image](https://user-images.githubusercontent.com/5388377/221690186-d8118340-6534-44e2-9025-4e9e71271036.png)

Is there somewhere else that something could be open?

**Comment by Colengms** [comment] 2023-02-27 21:39
Hi @ajwentzel .  The IntelliSense results being processed when the crash occurs appear to be related to that file.  Would you be able to provide the contents of that file?  That might help us repro and test a fix.

That file may be included by a source file, and cpptools may be choosing the source file to generate IntelliSense for the header.  That source file, and other headers that are included, may be part of the repro as well.  Is this something simple enough that you could zip up and share, that we could use to repro?

**Comment by ajwentzel** [comment] 2023-02-27 21:43
It's honestly just a blank arduino sketch, but I zipped the whole folder for you. You can ignore the .txt files since those are just places I copied logs for attaching here. 


[Testing.zip](https://github.com/microsoft/vscode-cpptools/files/10844590/Testing.zip)

**Comment by Colengms** [comment] 2023-02-27 22:17
Hi @ajwentzel .  One more question; I see that you're using `packages\\rp2040`.  But, when I use the Arduino extension (or Arduino IDE), the RP2040 boards I install do not get stored in that location.  Can you clarify how/where to install those support files?

**Comment by ajwentzel** [comment] 2023-02-27 22:27
I added this line: "https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json"
 to the Additional Boards Manager URLs in the Arduino IDE preferences.

**Comment by ajwentzel** [comment] 2023-02-27 22:41
Also, in case it matters, the Arduino IDE version is 1.8.15.

**Comment by sean-mcmanus** [comment] 2023-03-01 02:10
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.4

**Closed as completed by sean-mcmanus** 2023-03-01 02:10 UTC
Labels: bug, Language Service, fixed
