### ISSUE TITLE
cpptools-1.7.0-insiders version GLIBC_2.27 not found

### ISSUE THREAD

**Issue by qydpkcgcdwfwozk** [microsoft/vscode-cpptools#8200] opened 2021-09-29 00:30 UTC
Bug type: CppTools

**Describe the bug**

- OS and Version: CentOS Linux release 7.9.2009 (Core)
- VS Code Version: Version: 1.60.2
        Commit: 7f6ab5485bbc008386c4386d08766667e155244e
        Date: 2021-09-22T11:59:08.826Z (6 days ago)
        Electron: 13.1.8
        Chrome: 91.0.4472.164
        Node.js: 14.16.0
        V8: 9.1.269.39-electron.0
        OS: Darwin arm64 20.6.0

- C/C++ Extension Version: `ms-vscode.cpptools-1.7.0-insiders`
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

The GUI shows the following message:
```
The language server crashed 5 times in the last 3 minutes. It will not  be restarted.
```
Upon further investigation, this version requires GLIBC_2.27 which is not present in my system.
```
${HOME}/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/bin/cpptools: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ${HOME}/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/bin/cpptools)
```

**To Reproduce**

1. Install Remote SSH v0.65.8 plugin (from Microsoft)
2. Install C++ plugin v1.7.0-insiders (from Microsoft)
3. Remote login to a CentOS 7 host
4. Start a C++ project such as a simple hello_world.cpp basic file.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.
![Screen Shot 2021-09-28 at 7 27 23 PM](https://user-images.githubusercontent.com/10732930/135183024-43218527-16a2-4408-861b-ae5afefc1bde.png)
![Screen Shot 2021-09-28 at 7 28 31 PM](https://user-images.githubusercontent.com/10732930/135183148-026b06ce-0003-4650-8799-6e928d85888b.png)

**Comment by michelleangela** [comment] 2021-09-29 00:42
@qydpkcgcdwfwozk 
Thank you for reporting this. It is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/8192.

**Closed as completed by michelleangela** 2021-09-29 00:42 UTC
Labels: bug, duplicate, external

**Comment by michelleangela** [comment] 2021-10-01 00:54
1.7.0-insiders2 is now available with a fix for this issue. https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
