### ISSUE TITLE
Go To Definition goes to the wrong macro definition in gcc IntelliSense mode

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#8577] opened 2021-12-16 02:45 UTC
QUESTION 2 is:
the define is in line 711
![image](https://user-images.githubusercontent.com/1876302/145512268-81c47ccb-3791-40f8-be53-d2da54212961.png)

but we press F12 
![image](https://user-images.githubusercontent.com/1876302/145512309-48fd7829-8505-47f6-a2d1-4d375ba373e5.png)

it goes to line 351, that is wrong position
![](https://user-images.githubusercontent.com/1876302/145398893-911a0de3-e806-4778-ae1c-bf27ff4d9332.gif)

_Originally posted by @heartacker in https://github.com/microsoft/vscode-cpptools/issues/8508#issuecomment-990577469_

**Comment by Colengms** [comment] 2021-12-16 20:20
Hi @heartacker .  If I interpret the screen recording you posted correctly, you are seeing the issue with using F12 on the definition itself?  This should result in a `Go To Reference` operation.  And, it's going to a line that is not a reference?  If I'm not interpreting the screen recording correctly, could you please explain what is happening?

 Does this issue repro if you run `C/C++: Reset IntelliSense Database` and allow tag parsing to complete again?  It seems like an incorrect offset has been stored to the database.

I'm not able to easily reproduce the issue.  Can you reproduce the issue in a reduced example that we could use to investigate further?

**Comment by heartacker** [comment] 2021-12-16 21:48
- frist，the intelligence mode is  Windows_msvc_arm, and it work correctly 
- change  the intelligent mode into windows_gcc_arm，  It works incorrectly.
- reset C plus plus database， reload or   re scan the whole work  space， It still works incorrectly.
-  Now we change the Intelligence mode back to windows_msvc_arm,  It works correctly  Immediately.
-  So I don't believe that is the database issue.

**Comment by heartacker** [comment] 2021-12-16 21:50
I have test with my workmates' pc 
All of them have the same problem.  And we all could reproduce the issue.

**Comment by Colengms** [comment] 2021-12-16 22:00
> All of them have the same problem. And we all could reproduce the issue.

Hi @heartacker .  Is that because you are sharing the same code?  I believe you that there is an issue here.  In order to find out what that issue is, we need to be able to reproduce the issue ourselves to investigate further.  Is the code you are repro'ing with something you can share?  So far, I've not been able to make this issue occur with code I've typed in based on the images you posted.

**Comment by heartacker** [comment] 2021-12-16 22:05
Sorry, I can not share the code，  But I will try to make a minimal simple code for you，wait for  me 😅

**Comment by heartacker** [comment] 2021-12-16 22:25
[cpp_code.zip](https://github.com/microsoft/vscode-cpptools/files/7730768/cpp_code.zip)

here  you are, we could repro with this code

**Comment by Colengms** [comment] 2021-12-17 02:55
Thanks @heartacker .  I was able to repro with that example.  I've confirmed that the issue also repro's in VS.  (The C/C++ extension for VS Code shares the IntelliSense implementation with VS).  I've opened a bug against VS internally.

**Comment by nunojsa** [comment] 2022-01-10 12:33
Hi all,

I'm not sure if this is related but I think it is... So, take the next code as an example:

```
#define DIV_2(x)    ((x) / 2)
#define DIV_4(x)    DIV_2((x) / 2)


#define FOO DIV_4(16);
static int foo_2 =  DIV_4(32);

int main(void)
{
    printf("Hello world %d!\n", DIV_4(8));
    
    return 0;
}
```

I can see that "go to definition" on DIV_4 leads me to DIV_2. This looks like an issue on defines/macros that use another defines/macros.

On top of this, I can say that downgrading to the latest stable version, 1.7.1 (disabling the insiders channel) is a workaround as things work as expected in that version

**Comment by sean-mcmanus** [comment] 2022-01-10 20:18
@nunojsa Yes, that appears to be the same issue.

**Comment by rodrigobrochado** [comment] 2022-02-15 13:45
Not sure if it was expected, but tested with 1.8.2, 1.8.4 (latest), 1.9.0 (pre-release) and the issue is still there.

**Comment by sean-mcmanus** [comment] 2022-02-15 20:25
@rodrigobrochado That is expected -- the issue hasn't been fixed yet -- if it's fixed in a release, it would be assigned to a release milestone in which the fix is available.

**Comment by nunojsa** [comment] 2022-02-16 07:53
> That is expected -- the issue hasn't been fixed yet -- if it's fixed in a release, it would be assigned to a release milestone in which the fix is available.

That said, is there any idea already when it might be fixed? This issue is keeping me from update to a newer version....

**Comment by sean-mcmanus** [comment] 2022-02-16 19:00
@nunojsa I don't know yet -- I pinged the person it's assigned to...

**Comment by sean-mcmanus** [comment] 2022-02-16 19:23
@nunojsa It's scheduled to be fixed within the next 3 weeks -- not sure how reliable that scheduling is though.

**Comment by cc-caixf** [comment] 2022-02-17 01:43
@sean-mcmanus  here also have a problem : 
![image](https://user-images.githubusercontent.com/19278194/154387983-0c59d03b-75ba-4b44-b102-8f94aa072765.png)
`xa_lock` is  a member of `xa`, but be identified as macro.

**Comment by MaJerle** [comment] 2022-03-29 10:41
@sean-mcmanus do you have an ETA for the update? It still seems to not be fixed - I do not exclude a problem only on my side tho.

**Comment by sean-mcmanus** [comment] 2022-03-29 18:04
@MaJerle Yeah, it's supposed to be fixed in our next insiders build.

**Comment by qiuyuhang** [comment] 2022-04-24 10:45
Is it released? I still got the same problem.
Latest release version v1.9.8.

**Comment by nunojsa** [comment] 2022-04-25 07:54
Apparently it is fixed if you move to the pre-release version...

**Comment by MaJerle** [comment] 2022-04-25 07:59
> Apparently it is fixed if you move to the pre-release version...

I cannot find option to select pre-release version for this plugin?

**Comment by nunojsa** [comment] 2022-04-25 08:02
![image](https://user-images.githubusercontent.com/28741857/165045849-08b1a370-fbbb-41cc-a914-3d357fef256b.png)

It is here... You can see that I already made the switch so for me the option is to go back. If you can't see the option, then you'll need help from the devs

**Comment by Colengms** [comment] 2022-04-27 01:00
Closing as fixed.

**Closed as completed by Colengms** 2022-04-27 01:00 UTC
Labels: bug, Language Service, fixed, regression, Visual Studio, Feature: Go to Definition

**Comment by Spongman** [comment] 2022-05-18 17:19
I had the same issue: f12 went to different symbol than the (correct one) shown in the tooltip. updating to v1.10.2 fixed it.
