### ISSUE TITLE
It takes a long time to start the analysis after opening an project。

### ISSUE THREAD

**Issue by suzukajiang** [microsoft/vscode-cpptools#1429] opened 2018-01-10 01:37 UTC
Description:	windows 7 64bit

Version 1.19.1
Architecture x64

C/C++ extension 0.14.6-insider

I think the plugin should start to parse file immediately ofter open an project。

**Comment by sean-mcmanus** [comment] 2018-01-10 01:46
It's by design. Our extension doesn't activate until you open a C++ file or you use a C++ command, unless it was activated on the previous launch (i.e. if you opened a C++ previously, we'll activate even with no C++ file open the next time). Does that correspond to what you observe or are you experiencing some other buggy delay in parsing? I usually always have at least one C++ file open in my workspace.

Starting our extension immediately isn't a good idea, because it would be launched for people doing things like type script debugging, since we also launch on debugging in general, only ~50% of users with the C++ extension actually use C++ in a month or so.

Also, this behavior is the same as 0.14.5.

**Comment by suzukajiang** [comment] 2018-01-10 02:16
It also happened when there are several C files opened. 
there are same problem when I reload the windows, and it takes at least 20 seconds to start parse。

**Comment by suzukajiang** [comment] 2018-01-10 02:20
![image](https://user-images.githubusercontent.com/34700091/34752861-c01bb298-f5ef-11e7-892d-6c946dff0c3a.png)

when I reload the project, the plugin isn't starting immediately.

**Comment by sean-mcmanus** [comment] 2018-01-10 03:33
@suzukajiang Okay, you seem to be hitting some other strange issue that we are not able to repro. The language service is supposed to start in a 2-3 seconds or so (e.g. you should see icons appear in the bottom right and the config "Win32"). Is this a regression from 0.14.5? Our typescript code, which is running at this point, is at https://github.com/Microsoft/vscode-cpptools so if you're feeling ambitious you should be able to break into the debugger to see what is going on or maybe the Toggle Developer Tools might show something. It's possible another installed extension is loading beforehand and blocking our activation from occurring. Can you tell if C++ debugging works during this period of time or do you get a wait for loading message? If not, it would mean that our main extension is not being activated fast enough (i.e. a Vs Code issue).

**Comment by sean-mcmanus** [comment] 2018-01-10 04:31
I just thought of one thing that could cause this -- we try to download a cpptools.json file for on the fly configuration at startup -- it's possible this could be causing a delay and we just never noticed because of our fast internet connections. You can work around this by opening `"C:\Users\user\.vscode\extensions\ms-vscode.cpptools-<version>\out\src\main.js"`

and changing
`    return downloadCpptoolsJson("https://go.microsoft.com/fwlink/?linkid=852750"){`

to `    return downloadCpptoolsJson("")`.

It's possible we might have regressed this via making the operation sync instead of async. I'll investigate.

**Comment by suzukajiang** [comment] 2018-01-10 08:31
I has tryed, it works.

**Comment by sean-mcmanus** [comment] 2018-01-10 08:37
Cool. Thanks a lot for trying the insider release and reporting this issue. We should have it fixed in our pending release.

**Comment by sean-mcmanus** [comment] 2018-01-17 23:40
Fixed https://github.com/Microsoft/vscode-cpptools/releases/latest

**Closed as completed by sean-mcmanus** 2018-01-17 23:40 UTC
Labels: bug, Language Service, fixed, performance
