### ISSUE TITLE
Fetching build tasks never completes

### ISSUE THREAD

**Issue by mikepelley** [microsoft/vscode-cpptools#4638] opened 2019-11-19 20:49 UTC
I am developing a small library in C on a remote Ubuntu machine which I connect to using Remote SSH from my Windows laptop. I have a build task configured in tasks.json and it was working fine for a while. Now though it gets stuck saying "Fetching build tasks..." and after a moment I get a pop-up that says "The C/C++ task provider is slow. The extension...".

**Comment by sean-mcmanus** [comment] 2019-11-19 21:48
Is this a bug with our C/C++ extension? Does it repro with our extension disabled? Or is this a VS Code or remote SSH bug?

**Comment by alex-vas** [comment] 2019-12-10 23:19
I have the same problem on macOS, not running C++ extension (I believe).


CPUs | Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 3, 3, 3
Memory (System) | 40.00GB (16.42GB free)
Process Argv |  
Screen Reader | no
VM | 0%


Extension | Author (truncated) | Version
-- | -- | --
cross-highlighter | cro | 0.0.4
xml | Dot | 2.5.0
vscode-docker | ms- | 0.9.0
vscode-kubernetes-tools | ms- | 1.0.9
java | red | 0.54.2
vscode-yaml | red | 0.6.1
sass-indented | rob | 1.5.1
vscodeintellicode | Vis | 1.2.0
vscode-java-debug | vsc | 0.23.0
vscode-java-dependency | vsc | 0.6.0
vscode-java-pack | vsc | 0.8.1
vscode-java-test | vsc | 0.21.0
vscode-maven | vsc | 0.20.0

**Comment by alex-vas** [comment] 2019-12-10 23:23
I ran with all extensions disabled, and the problem seems to gone away...

**Comment by onepick** [comment] 2020-03-31 14:12
I meet the same issue with running remote-ssh extension, when i disable C/C++ extension on server.  task can build

**Comment by PhillipVoyle** [comment] 2020-04-30 22:12
I get this error when trying to fetch the build tasks.
```
[2020-05-01 10:11:01.143] [renderer1] [error] spawn /home/phillipv/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/node_modules/vscode-ripgrep/bin/rg ENOENT: Error: spawn /home/phillipv/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/node_modules/vscode-ripgrep/bin/rg ENOENT
    at Object.t.deserializeSearchError (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4334:786)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4377:134
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by barabaka** [comment] 2020-12-02 17:44
Same issue on Windows. It started after installing 'Git Lens' plugin. I removed the plugin but the issue was still there. For me the problem was in *.code-workspace file. Git Lens adds the following line there but then fails to clear it when uninstalled:
`"uri": "gitlens://319c334/........" `
It also adjusts the "name" to include Git revision. I removed the URI line and adjusted the name, now the issue is gone.

**Comment by birgersp** [comment] 2020-12-04 15:08
I have this exact same problem for any project that has a task of type "gulp"

**Comment by shwetaIAF** [comment] 2021-01-15 13:33
In my case! I was directly opening the .c file in via search and didn't opened the folder.
Open your folder file in visual studio code would work...

**Comment by sean-mcmanus** [comment] 2021-01-15 21:07
@shwetaIAF Yeah, you're right. I repreod this a few days ago as part of https://github.com/microsoft/vscode-cpptools/issues/6764 .

**Comment by sean-mcmanus** [comment] 2021-01-27 22:25
This should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders3 .

**Closed as completed** 2021-02-03 00:37 UTC
Labels: fixed, regression, tasks/build/debug

**Comment by birgersp** [comment] 2021-02-12 12:06
I was having the same problem where the "Fetching build tasks" would never complete, (though it was not when using this extension).

For anyone trying to figure out why this happens (like I did) I would like to point you here: https://github.com/microsoft/vscode/issues/112207

**Comment by psommerfeld** [comment] 2021-03-18 00:25
I am getting this often using the rust-analyzer extension
