### ISSUE TITLE
#include auto-complete bug

### ISSUE THREAD

**Issue by lh123** [microsoft/vscode-cpptools#1970] opened 2018-05-09 06:53 UTC
* Operating System and version: Win10 64Bit
* VS Code version: 1.23.0
* C/C++ extension version: 0.17.0

# 1. First Problem
> * step-by-step instructions to reproduce the issue
1. trigger #include auto-complete.
![image](https://user-images.githubusercontent.com/10697249/39800100-4ec6df02-5399-11e8-9496-01ad75c8097b.png)
2. press `Esc` to cancel auto-complete.
3. press `Ctrl` + `Space` to trigger auto-complete again.
![image](https://user-images.githubusercontent.com/10697249/39802896-e3a709fa-53a1-11e8-9872-8f6c3a6795b2.png)
4. press `Enter` to accept auto-complete.
## Actual behavior
![image](https://user-images.githubusercontent.com/10697249/39800160-7e8dfbda-5399-11e8-9026-bb22638e9313.png)
## Expected behavior
`#include "ui/Config.h"`
# 2. Second Problem
* New header file needs to restart VSCode to get #include auto-completion.

**Comment by bobbrow** [comment] 2018-05-11 15:57
First problem is the same root cause as #1959.  I committed a fix for that and it will be in 0.17.1.
Second problem still needs to be addressed.

**Comment by sean-mcmanus** [comment] 2018-05-14 23:28
@bobbrow Problem #2 appears to have been fixed in our pending update (i.e. we clear the include cache on file creation).

**Comment by sean-mcmanus** [comment] 2018-05-18 00:52
These #include completion bugs should be fixed now with 0.17.1.

**Closed as completed by sean-mcmanus** 2018-05-18 00:52 UTC
Labels: bug, Language Service, fixed
