### ISSUE TITLE
identifier “cout“ is undefined (vscode + MingW) 

### ISSUE THREAD

**Issue by HeisensOppings** [microsoft/vscode-cpptools#9203] opened 2022-04-19 09:29 UTC
### Environment

- OS and version: Win10
- VS Code: 1.66.2.0
- C/C++ extension:  v1.9.7

### Bug Summary and Steps to Reproduce

Bug Summary:

1. In this environment and configs...(imgs)
![163528815-12ecffeb-5653-4924-93b9-2df28b367808](https://user-images.githubusercontent.com/73877739/163973337-0c3dc209-41da-43f8-a9ed-0b3b082133c7.png)
![163528823-363aecf6-1f93-43c2-a196-1ec32c1336dd](https://user-images.githubusercontent.com/73877739/163973341-ab79c957-5d17-4d04-a68d-495e51a197fb.png)
![163528831-f14392df-fb04-4289-8591-209db70b87f3](https://user-images.githubusercontent.com/73877739/163973349-ab792718-3328-40e6-a33d-5f3ed29aedb3.png)
4. Get Start to C++ Coding...
5. See error that there is no definition, but I can jump, tried many methods, reinstalled the c++ extension, added the library file path, etc. but dose't work. but if I add "C_Cpp.intelliSenseEngine": "Tag Parser", it will not report an error , but the important function error prompts are gone, wavy lines, etc.

![163528827-7b6abbd6-28c8-441b-910f-4230775ba1e6](https://user-images.githubusercontent.com/73877739/163973344-21dad0fe-eb9d-46d7-9bde-15dc951b4e84.png)
![163528829-bf91ef65-264d-4a71-acdc-c1c401ac7262](https://user-images.githubusercontent.com/73877739/163973345-c20a6961-6fe8-4fbe-8ec1-06849828b22b.png)

### Other Extensions

![Snipaste_2022-04-19_17-28-30](https://user-images.githubusercontent.com/73877739/163973932-c4f01e29-4934-49ef-80fa-e2b5a4c7478a.png)

**Comment by michelleangela** [comment] 2022-04-20 23:25
If `C_Cpp.intelliSenseEngine` is set to `Tag Parser` it is by design the error squiggles are disabled because `Tag Parser` is does not use the IntelliSense engine that knows the context of a code.

In order for IntelliSense features to work, such as auto-complete and find all references, `C_Cpp.intelliSenseEngine` should be set to `Default`. `Default` value means the IntelliSense engine is enabled.

**Comment by HeisensOppings** [comment] 2022-04-21 03:16
> Thanks, now it works

**Comment by michelleangela** [comment] 2022-04-21 17:13
Closing as resovled.

**Closed as completed by michelleangela** 2022-04-21 17:13 UTC
Labels: Language Service, Feature: Configuration
