### ISSUE TITLE
Call Hierarchy can show invalid results with inactive code

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10913] opened 2023-05-03 00:58 UTC
Use c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "Win32-ONE",
            "defines": [
                "ONE"
            ]
        },
        {
            "name": "Win32-TWO",
            "defines": [
                "TWO"
            ]
        }
    ],
    "version": 4
}
```

test1.cpp
```cpp
#ifdef ONE
void func1()
{
}

void func2()
{
    func1();
}
#endif
```

test2.cpp
```cpp
#ifdef TWO
void func1()
{
}

void func2()
{
    func1();
}
#endif
```

1. Switch the config to Win32-TWO
2. Do Call Hierarchy Calls From on func2 in test2.cpp

Bug: The Call Hierarchy results are incorrectly given for test1.cpp.

![image](https://user-images.githubusercontent.com/19859882/235813700-eb33bcee-3ee0-4665-9c5f-07749ac8b116.png)

The issue becomes fixed after test1.cpp is closed and then a Reset IntelliSense Database is done, but BOTH have to be done, not just one of those steps.

**Comment by michelleangela** [comment] 2023-05-17 03:48
Making this a duplicate of https://github.com/microsoft/vscode-cpptools/issues/10923 as it has the same root cause.

**Closed as completed by michelleangela** 2023-05-17 03:48 UTC
Labels: bug, duplicate, Language Service, insiders, Feature: Call Hierarchy
