### ISSUE TITLE
When the comment contains \0, the prompt in the floating box will be truncated

### ISSUE THREAD

**Issue by a16su** [microsoft/vscode-cpptools#6341] opened 2020-10-17 12:04 UTC
**Type: UI Bug**

**Describe the bug**
- OS and Version: **_Windows_NT x64 10.0.19042_**
- VS Code Version: **_1.50.1_**
- C/C++ Extension Version: **_v1.1.0-insiders2_**
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:  **_No_**
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![Snipaste_2020-10-17_19-46-30](https://user-images.githubusercontent.com/33782391/96336322-7d289700-10b1-11eb-90fa-6aff34574743.jpg)

**Additional context**

**Comment by michelleangela** [comment] 2020-10-18 19:20
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6084

**Closed as completed by michelleangela** 2020-10-18 19:20 UTC
Labels: duplicate, Visual Studio, Feature: Doc comments
