### ISSUE TITLE
Extension causes high cpu load calling which.sync('clang-format')

### ISSUE THREAD

**Issue by dragonchen035** [microsoft/vscode-cpptools#6630] opened 2020-12-07 01:52 UTC
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `1.1.3`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ADMINI~1\AppData\Local\Temp\ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment] 2020-12-07 20:29
Can you attach the profiler text?

**Comment by dragonchen035** [comment] 2020-12-08 10:24
> Can you attach the profiler text?

[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cpptools/files/5658600/ms-vscode.cpptools-unresponsive.cpuprofile.txt)

**Comment by sean-mcmanus** [comment] 2020-12-08 19:10
Thanks for the info. Looks like it's caused by https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/settings.ts#L77 , from PR https://github.com/microsoft/vscode-cpptools/pull/4855

**Comment by Colengms** [comment] 2021-01-21 23:32
I believe this has been partially addressed by the linked PR.  I suspect this is no longer an issue, so closing.  If you are still seeing an issue with the latest version, please let us know.

**Comment by sean-mcmanus** [comment] 2021-01-21 23:57
The fix is in https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2 (not 1.1.3).

**Closed as completed** 2021-02-03 00:38 UTC
Labels: Language Service, fixed, performance, Feature: Code Formatting
