### ISSUE TITLE
Text after Doxygen \ref and \f$ commands in a documentation item is ignored

### ISSUE THREAD

**Issue by mjacobse** [microsoft/vscode-cpptools#6136] opened 2020-09-14 21:49 UTC
**Type: LanguageService**

- OS and Version: Manjaro Linux and Windows 10 1909
- VS Code Version: 1.49.0
- C/C++ Extension Version: 1.0.0

**Screenshots of examples**

![example_ref](https://user-images.githubusercontent.com/44684927/93140736-3e36a880-f6e3-11ea-8004-4e690a653dba.png)
![example_formula](https://user-images.githubusercontent.com/44684927/93140987-abe2d480-f6e3-11ea-8c47-8a19fb758e9a.png)

It seems like any description that follows commands like `\ref` and `\f$` is completely omitted in the tooltip. These commands `\ref` and `\f$` can be used within Doxygen documentation as described [here](https://www.doxygen.nl/manual/commands.html#cmdref) and [here](https://www.doxygen.nl/manual/commands.html#cmdfdollar).

**Expected behavior**

- Expected tooltip in screenshot 1 to say "Related to `test1` is this second test function"
- Expected tooltip in screenshot 2 to say "Computes `E = m c^2` for the given mass."

**Comment by michelleangela** [comment] 2020-09-15 19:34
The Doxygen parser is shared code between Visual Studio and C++ extension.

Created a feedback ticket on Visual Studio
https://developercommunity.visualstudio.com/content/problem/1185851/text-after-doxygen-ref-and-f-commands-in-a-documen.html

**Comment by michelleangela** [comment] 2020-09-17 20:18
This might also be related to https://github.com/microsoft/vscode-cpptools/issues/6084

**Comment by michelleangela** [comment] 2020-09-18 17:34
Determined this is a duplicate of #6084

**Closed as completed by michelleangela** 2020-09-18 17:34 UTC
Labels: bug, duplicate, Visual Studio, Feature: Doc comments

**Comment by michelleangela** [comment] 2022-03-11 18:49
Correction: this issue is not a duplicate of #6084. A mistake was made when evaluating this issue.
