### ISSUE TITLE
[Cpptools]Uninstall cpptools extension pop up an error message

### ISSUE THREAD

**Issue by qian6** [microsoft/vscode-cpptools#1166] opened 2017-10-25 01:27 UTC
## Environment data

 dotnet --info  output:
 Runtime Environment:
 OS Name: Windows
 OS Version: 10.0.15063
 OS Platform: Windows
 RID: win10-x64
 Base Path: C:\Program Files\dotnet\sdk\2.0.2
 VS Code version: 1.17.2
 C# Extension version: 20171023.2
 MinGW32: c:\mingw\mingw32\bin\gdb.exe

## Steps to reproduce
1.Open vscode as administrator and Install extensionas following:
![capturqqe](https://user-images.githubusercontent.com/20922638/31975744-e611ca58-b965-11e7-97da-3b457904ca9d.PNG)
2.It pop up a message and click Reload now as following:
![captuffre](https://user-images.githubusercontent.com/20922638/31975755-ef096ada-b965-11e7-9191-5da674ae8dbf.PNG)
3.It pop up a message and click Reload as following:
![captcccccure](https://user-images.githubusercontent.com/20922638/31975757-f3a7ba88-b965-11e7-9d61-f74eae0dc543.PNG)
4.Open test folder in attachments directly.
[test.zip](https://github.com/Microsoft/vscode-cpptools/files/1412950/test.zip)
5.Click uninstall button.
![captggggggggure](https://user-images.githubusercontent.com/20922638/31975763-fd6345b0-b965-11e7-8101-3213752a775a.PNG)

## Expected behavior

#1 It can uninstall extension and no error message.

#2
 In the step2, successfully option info should be pop up after complete installion

## Actual behavior

It pop up an error message as following:
![error](https://user-images.githubusercontent.com/20922638/31975806-38e306f2-b966-11e7-8b43-81c9f455d2b6.PNG)

## Investigation:
1.I found extension has been uninstalled when open vs again.
2. It hasn't error message When don't open folder.

**Comment by sean-mcmanus** [comment] 2017-10-25 01:54
Yes, we are aware of this. You can workaround this by closing the current workspace/folder before uninstalling the extension. The problem is that we have processes running when VS Code tries to uninstall them and VS Code isn't telling our processes to shutdown. We're still investigating how to fix this -- I'm not sure yet if it's a VS Code bug or something we can fix ourselves.

**Comment by qian6** [comment] 2017-10-25 02:08
Got it! Thanks for your message!

**Comment by sean-mcmanus** [comment] 2017-10-25 22:59
I filed a bug with VS Code about this 5 months ago. It looks like other extensions have the same problem: https://github.com/Microsoft/vscode/issues/26828 . So I don't think we're able to provide a fix ourselves, but I'll still double check later.

**Comment by michelleangela** [comment] 2019-06-12 21:32
Closing this issue as the last response is more than a year old.

**Closed as completed by michelleangela** 2019-06-12 21:32 UTC
Labels: bug, external
