### ISSUE TITLE
some time comments are showed as messy code

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#7136] opened 2021-03-09 05:39 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: win 7、win10
- VS Code Version:1.54.1
- C/C++ Extension Version:1.2.2
- 
**Steps to reproduce**

some time it show mesy code
![image](https://user-images.githubusercontent.com/1876302/110423694-7cce7e00-80dc-11eb-91d4-b885a2298ecb.png)

![image](https://user-images.githubusercontent.com/1876302/110423698-80620500-80dc-11eb-975a-ea2cf86ebef7.png)
![image](https://user-images.githubusercontent.com/1876302/110423731-8ce65d80-80dc-11eb-828f-289c2adaf64a.png)

BTW: file-coding IS `GB2322`
**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment] 2021-03-09 18:22
We don't currently support the files.autoGuessEncoding setting (https://github.com/microsoft/vscode-cpptools/issues/4753) so you'll need to set your files.encoding setting. It's possible you may need to do a Reload Window. Does your issue still repro after doing that?

**Comment by bobbrow** [comment] 2021-03-11 22:51
We believe this is a duplicate of #4753.  You should be able to workaround this for the time being by setting `"files.encoding"` to `"gb2312"` in your settings.

**Closed as completed by bobbrow** 2021-03-11 22:51 UTC
Labels: duplicate, Language Service, world ready
