### ISSUE TITLE
Duplicate Intellisense Hints

### ISSUE THREAD

**Issue by AzureVauban** [microsoft/vscode-cpptools#12400] opened 2024-06-20 23:31 UTC
Type: <b>Bug</b>

Just type something, shows duplicate hints. For example, my linked list class has a method called push_back, I'll see it twice in the hints popup minimenu. Extension at fault via the extension bisect feature

Extension version: 1.20.5
VS Code version: Code 1.90.2 (Universal) (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:37:41.291Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|24.00GB (9.47GB free)|
|Process Argv|--crash-reporter-id d0cccd77-08a2-4a3d-b776-df8d85585ec7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31077528

```

</details>

**Comment by browntarik** [comment] 2024-06-21 19:23
Could provide a screenshot of the bug you are seeing?

**Comment by AzureVauban** [comment] 2024-06-21 19:56
Here is the screenshot:

<img width="806" alt="Screenshot 2024-06-21 at 2 51 15 PM" src="https://github.com/microsoft/vscode-cpptools/assets/106707615/b1445b63-8d1d-44fe-bf42-1b9b0ff3929e">

**Comment by browntarik** [comment] 2024-06-24 13:26
Does this error reproduce when you disable all other VS Code Extensions except for the C/C++ one?

**Comment by AzureVauban** [comment] 2024-06-24 19:53
this issue is not reproduced when all extensions are disabled. I first tried with the just the extension itself and then the c/c++ extension pack. The issue was not reproduced with the extension pack.

**Comment by AzureVauban** [comment] 2024-06-24 20:00
after your message I went an disabled each extension one by one and I think the issue is caused by C/C++ Clang Command Adapter" by Yasuaki MITANI. Whenever this extension is enabled I see duplicate suggestions.

**Comment by browntarik** [comment] 2024-06-24 22:08
Given your feedback, it looks like this issue is not caused by our extension and I will now close this issue. Please let me know if you have any further concerns.

**Closed as not planned by browntarik** 2024-06-24 22:08 UTC
Labels: Language Service, more info needed
