### ISSUE TITLE
[WSL2] Debugging with gdb gets stuck

### ISSUE THREAD

**Issue by SashaOv** [microsoft/vscode-cpptools#4571] opened 2019-11-08 02:48 UTC
Type: Debugger

**Describe the bug**
- OS and Version: 
    Microsoft Windows [Version 10.0.19013.1102]
    WSL 2
    Ubuntu 18.04
   
- VS Code Version: 1.40.0 (Also happens with recent Code Insiders)
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

I am working through the C++ tutorial at https://code.visualstudio.com/docs/languages/cpp .
Building and running program works.
When I try to start debugging via F5, the debugger prints stuff on the console and gets stuck

**To Reproduce**
Clone this project: https://github.com/SashaOv/vc-repro-1

*Please include a code sample and `launch.json` configuration.*
1. Clone `https://github.com/SashaOv/vc-repro-1`
2. Build using Ctrl-Shift-B
3. Start debugging session using F5

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
The log trace is in the README: https://github.com/SashaOv/vc-repro-1

It could be gdb version problem; I have similar problem with VS Code Insiders and possibly with Visual Studio Community Edition

**Comment by pieandcakes** [comment] 2019-11-09 00:12
This sounds like it is a WSL2 issue where it never hits a breakpoint or stops.

**Comment by pieandcakes** [comment] 2019-11-09 00:41
@SashaOv Our speculation is its an issue in WSL2 since if you switch back to WSL1's filesystem it works (per internal testing). We need to investigate what the problem is and communicate it to the WSL2 team.

**Comment by SashaOv** [comment] 2019-11-11 01:39
Hi @pieandcakes thanks for your reply. When I invoke gdb manually, it stops on breakpoint no problem:
```
(gdb) b hello.cpp:8
Breakpoint 1 at 0x8f1: file hello.cpp, line 8.
(gdb) r
Starting program: /home/me/learn/c1/hello.out 
Hello

Breakpoint 1, main (argv=1, argc=0x7fffffffe6a8) at hello.cpp:8
8           return 0;
(gdb) 
```

Do you still think it's a WSL 2 issue? Could be more of a gdb version issue, like you guys cannot parse the output of this version:

```
me@L19:~/learn/c1$ gdb --version
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
me@L19:~/learn/c1$ 
```

**Comment by pieandcakes** [comment] 2019-11-11 20:47
@SashaOv in looking at the log you provided, `gdb` never stops. This tells me that its either a WSL2 issue or an issue with the gdb that is being provided in WSL2. Either way, it isn't something that the extension can fix. I'm working with another team that is doing some investigation for the issue so we can send information to the WSL2 team. 

I think the difference in this scenario is that its being invoked through the WSL.exe (or bash.exe) when we call it and for some reason, that remoting is causing a problem.

**Comment by pieandcakes** [comment] 2019-11-19 22:13
@SashaOv We determined that there is an issue in WSL2 that the WSL2 team has a fix for. We don't know which insiders release it will be part of though. 

I'll let you know more when I have more to share.

**Comment by SashaOv** [comment] 2019-11-19 22:18
> @SashaOv We determined that there is an issue in WSL2 that the WSL2 team has a fix for. We don't know which insiders release it will be part of though.
> 
> I'll let you know more when I have more to share.

Thanks Pierson, looking forward.

**Comment by pieandcakes** [comment] 2019-12-16 18:38
This should be fixed if you can update your Windows Insiders Fast Ring build to the latest.

**Closed as completed by pieandcakes** 2019-12-16 18:38 UTC
Labels: debugger, external
