### ISSUE TITLE
Can not hit a breakpoint/stopAtEntry when debugging In Mac OS High Sierra 10.15Beta(19A546d)

### ISSUE THREAD

**Issue by Sofabulous** [microsoft/vscode-cpptools#4179] opened 2019-08-31 18:59 UTC
Type: Debugger

Unable to start debugging

OS and Version: Mac OS High Sierra 10.15Beta(19A546d)
VS Code Version: 1.37.1
C/C++ Extension Version: 0.25.1

Other extensions you installed (and if the issue persists after disabling them):
I'm new to programming and I'm trying to learn how to debug my program. Whenever I try to, I can't stop breakpoint in my .cpp file new created.
debugger console show me:
...
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
..

I don't know it is because of my fault of configuration or beta system.

Here is the launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.out",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false, // if true then stop at the main entry (function)
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb",
            "logging": {
                "trace": true,
                "traceResponse": true,
                "engineLogging": true
            },
            "preLaunchTask": "build" 
        }
    ]
}

I'm sorry if this is only a beta system issue, but I do want to know if it is my fault. Pls help!

**Comment by Sofabulous** [comment] 2019-08-31 19:17
Both "Stop At Entry" as well as breakpoints don't work (neither breakpoints set before the debugging session starts, nor breakpoints set during the debugging session).

Using the CodeLLDB extension still works fine.

Debug log from the C/CPP Extension Debugger:

--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (208) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'\n"},"seq":2}
1: (208) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (225) LaunchOptions  ExePath='/Users/maru/Desktop/Learning c++/main.out'\n"},"seq":4}
1: (225) LaunchOptions  ExePath='/Users/maru/Desktop/Learning c++/main.out'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (226) LaunchOptions  WorkingDirectory='/Users/maru/Desktop/Learning c++'\n"},"seq":6}
1: (226) LaunchOptions  WorkingDirectory='/Users/maru/Desktop/Learning c++'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (226) LaunchOptions  ExeArguments=''\n"},"seq":8}
1: (226) LaunchOptions  ExeArguments=''
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (226) LaunchOptions  MIMode='lldb'\n"},"seq":10}
1: (226) LaunchOptions  MIMode='lldb'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (227) LaunchOptions  MIDebuggerPath='/Users/maru/.vscode/extensions/ms-vscode.cpptools-0.25.1/debugAdapters/lldb/bin/lldb-mi'\n"},"seq":12}
1: (227) LaunchOptions  MIDebuggerPath='/Users/maru/.vscode/extensions/ms-vscode.cpptools-0.25.1/debugAdapters/lldb/bin/lldb-mi'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (227) LaunchOptions  WaitDynamicLibLoad='false'\n"},"seq":14}
1: (227) LaunchOptions  WaitDynamicLibLoad='false'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (227) LaunchOptions  ExternalConsole='true'\n"},"seq":16}
1: (227) LaunchOptions  ExternalConsole='true'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (228) LaunchOptions>\n"},"seq":18}
1: (228) LaunchOptions>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (228) LaunchOptions</LocalLaunchOptions>\n"},"seq":20}
1: (228) LaunchOptions</LocalLaunchOptions>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (371) Starting: \"/Users/maru/.vscode/extensions/ms-vscode.cpptools-0.25.1/debugAdapters/lldb/bin/lldb-mi\" --interpreter=mi\n"},"seq":22}
1: (371) Starting: "/Users/maru/.vscode/extensions/ms-vscode.cpptools-0.25.1/debugAdapters/lldb/bin/lldb-mi" --interpreter=mi
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (408) DebuggerPid=52089\n"},"seq":24}
1: (408) DebuggerPid=52089
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (668) ->(gdb)\n"},"seq":26}
1: (668) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (684) <-1001-gdb-set auto-solib-add on\n"},"seq":28}
1: (684) <-1001-gdb-set auto-solib-add on
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (684) ->1001^done\n"},"seq":30}
1: (684) ->1001^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (685) ->(gdb)\n"},"seq":32}
1: (685) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (687) 1001: elapsed time 4\n"},"seq":34}
1: (687) 1001: elapsed time 4
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (688) <-1002-gdb-set solib-search-path \"/Users/maru/Desktop/Learning c++:\"\n"},"seq":36}
1: (688) <-1002-gdb-set solib-search-path "/Users/maru/Desktop/Learning c++:"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (688) ->1002^done\n"},"seq":38}
1: (688) ->1002^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (689) 1002: elapsed time 0\n"},"seq":40}
1: (689) 1002: elapsed time 0
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (689) <-1003-environment-cd \"/Users/maru/Desktop/Learning c++\"\n"},"seq":42}
1: (689) <-1003-environment-cd "/Users/maru/Desktop/Learning c++"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (689) ->(gdb)\n"},"seq":44}
1: (689) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (689) ->1003^done,path=\"/Users/maru/Desktop/Learning c++\"\n"},"seq":46}
1: (689) ->1003^done,path="/Users/maru/Desktop/Learning c++"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (690) ->(gdb)\n"},"seq":48}
1: (690) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (693) 1003: elapsed time 4\n"},"seq":50}
1: (693) 1003: elapsed time 4
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (693) <-1004-gdb-set new-console on\n"},"seq":52}
1: (693) <-1004-gdb-set new-console on
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (693) ->1004^done\n"},"seq":54}
1: (693) ->1004^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (694) ->(gdb)\n"},"seq":56}
1: (694) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (694) 1004: elapsed time 0\n"},"seq":58}
1: (694) 1004: elapsed time 0
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (694) <-1005-file-exec-and-symbols \"/Users/maru/Desktop/Learning c++/main.out\"\n"},"seq":60}
1: (694) <-1005-file-exec-and-symbols "/Users/maru/Desktop/Learning c++/main.out"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (865) ->1005^done\n"},"seq":62}
1: (865) ->1005^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (865) ->(gdb)\n"},"seq":64}
1: (865) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (865) 1005: elapsed time 171\n"},"seq":66}
1: (865) 1005: elapsed time 171
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (866) ->=library-loaded,id=\"/Users/maru/Desktop/Learning c++/main.out\",target-name=\"/Users/maru/Desktop/Learning c++/main.out\",host-name=\"/Users/maru/Desktop/Learning c++/main.out\",symbols-loaded=\"1\",symbols-path=\"/System/Volumes/Data/Users/maru/Desktop/Learning c++/main.out.dSYM/Contents/Resources/DWARF/main.out\",loaded_addr=\"-\",size=\"8192\"\n"},"seq":68}
1: (866) ->=library-loaded,id="/Users/maru/Desktop/Learning c++/main.out",target-name="/Users/maru/Desktop/Learning c++/main.out",host-name="/Users/maru/Desktop/Learning c++/main.out",symbols-loaded="1",symbols-path="/System/Volumes/Data/Users/maru/Desktop/Learning c++/main.out.dSYM/Contents/Resources/DWARF/main.out",loaded_addr="-",size="8192"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (868) <-1006-interpreter-exec console \"platform status\"\n"},"seq":70}
1: (868) <-1006-interpreter-exec console "platform status"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (869) ->  Platform: host\n"},"seq":72}
1: (869) ->  Platform: host
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (869) ->    Triple: x86_64h-apple-macosx\n"},"seq":74}
1: (869) ->    Triple: x86_64h-apple-macosx
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (869) ->OS Version: 10.15 (19A546d)\n"},"seq":76}
1: (869) ->OS Version: 10.15 (19A546d)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (869) ->    Kernel: Darwin Kernel Version 19.0.0: Sun Aug 18 23:37:31 PDT 2019; root:xnu-6153.0.166~17/RELEASE_X86_64\n"},"seq":78}
1: (869) ->    Kernel: Darwin Kernel Version 19.0.0: Sun Aug 18 23:37:31 PDT 2019; root:xnu-6153.0.166~17/RELEASE_X86_64
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (870) ->  Hostname: 127.0.0.1\n"},"seq":80}
1: (870) ->  Hostname: 127.0.0.1
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (870) ->WorkingDir: /Users/maru/Desktop/Learning c++\n"},"seq":82}
1: (870) ->WorkingDir: /Users/maru/Desktop/Learning c++
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (870) ->1006^done\n"},"seq":84}
1: (870) ->1006^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (870) ->(gdb)\n"},"seq":86}
1: (870) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (872) 1006: elapsed time 4\n"},"seq":88}
1: (872) 1006: elapsed time 4
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (874) <-1007-break-insert -f on main\n"},"seq":90}
1: (874) <-1007-break-insert -f on main
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (877) ->1007^done,bkpt={number=\"1\",type=\"breakpoint\",disp=\"keep\",enabled=\"y\",addr=\"0x0000000100000f7d\",func=\"main\",file=\"main.cpp\",fullname=\"/Users/maru/Desktop/Learning c++/main.cpp\",line=\"6\",pending=[\"main\"],times=\"0\",original-location=\"main\"}\n"},"seq":92}
1: (877) ->1007^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x0000000100000f7d",func="main",file="main.cpp",fullname="/Users/maru/Desktop/Learning c++/main.cpp",line="6",pending=["main"],times="0",original-location="main"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (878) ->(gdb)\n"},"seq":94}
1: (878) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (881) 1007: elapsed time 7\n"},"seq":96}
1: (881) 1007: elapsed time 7
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (881) ->=breakpoint-modified,bkpt={number=\"1\",type=\"breakpoint\",disp=\"keep\",enabled=\"y\",addr=\"0x0000000100000f7d\",func=\"main\",file=\"main.cpp\",fullname=\"/Users/maru/Desktop/Learning c++/main.cpp\",line=\"6\",pending=[\"main\"],times=\"0\",original-location=\"main\"}\n"},"seq":98}
1: (881) ->=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x0000000100000f7d",func="main",file="main.cpp",fullname="/Users/maru/Desktop/Learning c++/main.cpp",line="6",pending=["main"],times="0",original-location="main"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (881) ->(gdb)\n"},"seq":100}
1: (881) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (890) Send Event AD7EngineCreateEvent\n"},"seq":102}
1: (890) Send Event AD7EngineCreateEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (894) Send Event AD7ProgramCreateEvent\n"},"seq":104}
1: (894) Send Event AD7ProgramCreateEvent
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.60828.1","VS.Diagnostics.Debugger.HostVersion":"14.0.60828.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.Duration":772,"VS.Diagnostics.Debugger.Launch.IsCoreDump":false,"VS.Diagnostics.Debugger.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.SourceFileMappings":0,"VS.Diagnostics.Debugger.MIMode":null}},"seq":106}
--> R (launch-2): {"type":"response","request_seq":2,"success":true,"command":"launch","body":{},"seq":108}
--> E (initialized): {"type":"event","event":"initialized","body":{},"seq":110}
<--   C (setBreakpoints-3): {"command":"setBreakpoints","arguments":{"source":{"name":"main.cpp","path":"/Users/maru/Desktop/Learning c++/main.cpp"},"lines":[7],"breakpoints":[{"line":7}],"sourceModified":false},"type":"request","seq":3}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (951) <-1008-break-insert -f on main.cpp:7\n"},"seq":113}
1: (951) <-1008-break-insert -f on main.cpp:7
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (953) ->1008^done,bkpt={number=\"2\",type=\"breakpoint\",disp=\"keep\",enabled=\"y\",addr=\"0x0000000100000fa2\",func=\"main\",file=\"main.cpp\",fullname=\"/Users/maru/Desktop/Learning c++/main.cpp\",line=\"7\",pending=[\"main.cpp:7\"],times=\"0\",original-location=\"main.cpp:7\"}\n"},"seq":115}
1: (953) ->1008^done,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x0000000100000fa2",func="main",file="main.cpp",fullname="/Users/maru/Desktop/Learning c++/main.cpp",line="7",pending=["main.cpp:7"],times="0",original-location="main.cpp:7"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (953) ->(gdb)\n"},"seq":117}
1: (953) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (954) ->=breakpoint-modified,bkpt={number=\"2\",type=\"breakpoint\",disp=\"keep\",enabled=\"y\",addr=\"0x0000000100000fa2\",func=\"main\",file=\"main.cpp\",fullname=\"/Users/maru/Desktop/Learning c++/main.cpp\",line=\"7\",pending=[\"main.cpp:7\"],times=\"0\",original-location=\"main.cpp:7\"}\n"},"seq":119}
1: (954) ->=breakpoint-modified,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x0000000100000fa2",func="main",file="main.cpp",fullname="/Users/maru/Desktop/Learning c++/main.cpp",line="7",pending=["main.cpp:7"],times="0",original-location="main.cpp:7"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (955) ->(gdb)\n"},"seq":121}
1: (955) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (954) 1008: elapsed time 2\n"},"seq":123}
1: (954) 1008: elapsed time 2
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (968) Send Event AD7BreakpointBoundEvent\n"},"seq":125}
1: (968) Send Event AD7BreakpointBoundEvent
--> R (setBreakpoints-3): {"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"id":1,"verified":true,"line":7}]},"seq":127}
--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":true,"line":7}},"seq":129}
<--   C (setFunctionBreakpoints-4): {"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":4}
--> R (setFunctionBreakpoints-4): {"type":"response","request_seq":4,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]},"seq":132}
<--   C (setExceptionBreakpoints-5): {"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":5}
--> R (setExceptionBreakpoints-5): {"type":"response","request_seq":5,"success":true,"command":"setExceptionBreakpoints","body":{},"seq":135}
<--   C (configurationDone-6): {"command":"configurationDone","type":"request","seq":6}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1071) Send Event AD7LoadCompleteEvent\n"},"seq":139}
1: (1071) Send Event AD7LoadCompleteEvent
--> R (configurationDone-6): {"type":"response","request_seq":6,"success":true,"command":"configurationDone","body":{},"seq":138}
<--   C (threads-7): {"command":"threads","type":"request","seq":7}
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"Warning: Debuggee TargetArchitecture not detected, assuming x86_64.\n"},"seq":143}
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1078) <-1009-exec-run\n"},"seq":146}
1: (1078) <-1009-exec-run
--> R (threads-7): {"type":"response","request_seq":7,"success":true,"command":"threads","body":{"threads":[]},"seq":145}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2073) ->1009^running\n"},"seq":149}
1: (2073) ->1009^running
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2073) ->=thread-group-started,id=\"i1\",pid=\"52117\"\n"},"seq":151}
1: (2073) ->=thread-group-started,id="i1",pid="52117"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2073) 1009: elapsed time 995\n"},"seq":153}
1: (2073) 1009: elapsed time 995
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2075) ->(gdb)\n"},"seq":155}
1: (2075) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2075) ->=thread-created,id=\"1\",group-id=\"i1\"\n"},"seq":157}
1: (2075) ->=thread-created,id="1",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2075) ->=thread-selected,id=\"1\"\n"},"seq":159}
1: (2075) ->=thread-selected,id="1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2075) ->(gdb)\n"},"seq":161}
1: (2075) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2075) ->*running,thread-id=\"all\"\n"},"seq":163}
1: (2075) ->*running,thread-id="all"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2075) ->(gdb)\n"},"seq":165}
1: (2075) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2081) <-1010-thread-info 1\n"},"seq":167}
1: (2081) <-1010-thread-info 1
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"=thread-selected,id=\"1\"\n"},"seq":169}
=thread-selected,id="1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2085) ->(gdb)\n"},"seq":171}
1: (2085) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2085) ->=thread-exited,id=\"1\",group-id=\"i1\"\n"},"seq":173}
1: (2085) ->=thread-exited,id="1",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2086) ->=thread-group-exited,id=\"i1\",exit-code=\"0\"\n"},"seq":175}
1: (2086) ->=thread-group-exited,id="i1",exit-code="0"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2088) ->*stopped,reason=\"exited-normally\"\n"},"seq":177}
1: (2088) ->*stopped,reason="exited-normally"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2089) ->(gdb)\n"},"seq":179}
1: (2089) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2089) ->1010^done,threads=[{id=\"1\",target-id=\"Thread 1\",frame={level=\"0\",addr=\"0xffffffffffffffff\",func=\"??\",args=[],file=\"??\",fullname=\"??\",line=\"0\"},state=\"running\"}]\n"},"seq":181}
1: (2089) ->1010^done,threads=[{id="1",target-id="Thread 1",frame={level="0",addr="0xffffffffffffffff",func="??",args=[],file="??",fullname="??",line="0"},state="running"}]
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2090) ->(gdb)\n"},"seq":183}
1: (2090) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2094) 1010: elapsed time 13\n"},"seq":185}
1: (2094) 1010: elapsed time 13
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2097) Send Event AD7ProcessInfoUpdatedEvent\n"},"seq":187}
1: (2097) Send Event AD7ProcessInfoUpdatedEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2098) Send Event AD7ThreadCreateEvent\n"},"seq":189}
1: (2098) Send Event AD7ThreadCreateEvent
--> E (thread): {"type":"event","event":"thread","body":{"reason":"started","threadId":1},"seq":191}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2106) <--gdb-exit\n"},"seq":193}
1: (2106) <--gdb-exit
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2106) ->^exit\n"},"seq":195}
1: (2106) ->^exit
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2107) ->=thread-group-exited,id=\"i1\"\n"},"seq":197}
1: (2107) ->=thread-group-exited,id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2107) ->(gdb)\n"},"seq":199}
1: (2107) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2116) ->\n"},"seq":201}
1: (2116) ->
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2117) ->\n"},"seq":203}
1: (2117) ->
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2118) <-logout\n"},"seq":205}
1: (2118) <-logout
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2124) \"/Users/maru/.vscode/extensions/ms-vscode.cpptools-0.25.1/debugAdapters/lldb/bin/lldb-mi\" exited with code 0 (0x0).\n"},"seq":207}
1: (2124) "/Users/maru/.vscode/extensions/ms-vscode.cpptools-0.25.1/debugAdapters/lldb/bin/lldb-mi" exited with code 0 (0x0).
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2129) Send Event AD7ProgramDestroyEvent\n"},"seq":209}
1: (2129) Send Event AD7ProgramDestroyEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"The program '/Users/maru/Desktop/Learning c++/main.out' has exited with code 0 (0x00000000).\r\n\n"},"seq":211}
The program '/Users/maru/Desktop/Learning c++/main.out' has exited with code 0 (0x00000000).
--> E (exited): {"type":"event","event":"exited","body":{"exitCode":0},"seq":213}
--> E (terminated): {"type":"event","event":"terminated","body":{},"seq":215}
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.60828.1","VS.Diagnostics.Debugger.HostVersion":"14.0.60828.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":0}},"seq":217}
<--   C (disconnect-8): {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":8}
--> R (disconnect-8): {"type":"response","request_seq":8,"success":true,"command":"disconnect","body":{},"seq":220}

**Comment by pieandcakes** [comment] 2019-09-04 19:52
I see 
```
->=library-loaded,id="/Users/maru/Desktop/Learning c++/main.out",target-name="/Users/maru/Desktop/Learning c++/main.out",host-name="/Users/maru/Desktop/Learning c++/main.out",symbols-loaded="1",symbols-path="/System/Volumes/Data/Users/maru/Desktop/Learning c++/main.out.dSYM/Contents/Resources/DWARF/main.out",loaded_addr="-",size="8192"
``` 
which I would expect to see a `loaded_addr` value. 

When we requested `thread-info` value, we're receiving:
```
1010^done,threads=[{id="1",target-id="Thread 1",frame={level="0",addr="0xffffffffffffffff",func="??",args=[],file="??",fullname="??",line="0"},state="running"}]\n"},"seq":181}
```

I don't know what the problem is though. Do you know what version of LLDB the other debugger is using?

**Comment by fangkyi03** [comment] 2020-01-18 03:03
mac 10.15.2 
I have the same problem

Issues an error:
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=thread-selected,id="1"

**Comment by fangkyi03** [comment] 2020-01-18 03:06
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1016) ->\n"},"seq":213}
1: (1016) ->
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1020) <-logout\n"},"seq":215}
1: (1020) <-logout
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1024) Send Event AD7ProgramDestroyEvent\n"},"seq":217}
1: (1024) Send Event AD7ProgramDestroyEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"The program '/Users/mac/Desktop/QuickJS/a.out' has exited with code 0 (0x00000000).\r\n\n"},"seq":219}
The program '/Users/mac/Desktop/QuickJS/a.out' has exited with code 0 (0x00000000).

--> E (exited): {"type":"event","event":"exited","body":{"exitCode":0},"seq":221}
--> E (terminated): {"type":"event","event":"terminated","body":{},"seq":223}
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.61023.1","VS.Diagnostics.Debugger.HostVersion":"14.0.61023.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":0}},"seq":225}
<--   C (disconnect-8): {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":8}
--> R (disconnect-8): {"type":"response","request_seq":8,"success":true,"command":"disconnect","body":{},"seq":228}
vscode:
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0

c/c++ 0.26.3-insiders3

x64

**Comment by fangkyi03** [comment] 2020-01-18 03:10
1: (1044) ->1010^done,threads=[{id="1",target-id="Thread 1",frame={level="0",addr="0xffffffffffffffff",func="??",args=[],file="??",fullname="??",line="0"},state="running"}]
1: (1044) ->(gdb)
=thread-selected,id="1"
@"123"
1: (1049) 1010: elapsed time 5
1: (1051) Send Event AD7ProcessInfoUpdatedEvent
1: (1052) Send Event AD7ThreadCreateEvent
1: (1058) <--gdb-exit
1: (1058) ->^exit
1: (1058) ->=thread-group-exited,id="i1"
1: (1058) ->(gdb)
1: (1059) ->
1: (1059) ->
1: (1063) <-logout
1: (1065) "/Users/mac/.vscode/extensions/ms-vscode.cpptools-0.26.3-insiders3/debugAdapters/lldb/bin/lldb-mi" exited with code 0 (0x0).
1: (1068) Send Event AD7ProgramDestroyEvent
The program '/Users/mac/Desktop/QuickJS/a.out' has exited with code 0 (0x00000000).

**Comment by fangkyi03** [comment] 2020-01-18 03:11
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.61023.1","VS.Diagnostics.Debugger.HostVersion":"14.0.61023.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.Duration":457,"VS.Diagnostics.Debugger.Launch.IsCoreDump":false,"VS.Diagnostics.Debugger.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.SourceFileMappings":0,"VS.Diagnostics.Debugger.MIMode":null}},"seq":2}
--> R (launch-2): {"type":"response","request_seq":2,"success":true,"command":"launch","body":{},"seq":4}
--> E (initialized): {"type":"event","event":"initialized","body":{},"seq":6}
<--   C (setBreakpoints-3): {"command":"setBreakpoints","arguments":{"source":{"name":"a.cpp","path":"/Users/mac/Desktop/QuickJS/a.cpp"},"lines":[9,10],"breakpoints":[{"line":9},{"line":10}],"sourceModified":false},"type":"request","seq":3}
--> R (setBreakpoints-3): {"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"id":1,"verified":true,"line":9},{"id":2,"verified":true,"line":10}]},"seq":9}
--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":true,"line":9}},"seq":11}
--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":2,"verified":true,"line":10}},"seq":13}
<--   C (setFunctionBreakpoints-4): {"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":4}
--> R (setFunctionBreakpoints-4): {"type":"response","request_seq":4,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]},"seq":16}

**Comment by fangkyi03** [comment] 2020-01-18 03:11
<--   C (setBreakpoints-3): {"command":"setBreakpoints","arguments":{"source":{"name":"a.cpp","path":"/Users/mac/Desktop/QuickJS/a.cpp"},"lines":[9,10],"breakpoints":[{"line":9},{"line":10}],"sourceModified":false},"type":"request","seq":3}
<--   C (setFunctionBreakpoints-4): {"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":4}
<--   C (setExceptionBreakpoints-5): {"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":5}
<--   C (configurationDone-6): {"command":"configurationDone","type":"request","seq":6}
<--   C (threads-7): {"command":"threads","type":"request","seq":7}
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=thread-selected,id="1"
@"123"
The program '/Users/mac/Desktop/QuickJS/a.out' has exited with code 0 (0x00000000).

<--   C (disconnect-8): {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":8}

**Comment by pieandcakes** [comment] 2020-01-22 19:23
@fangkyi03 Yours is related to the Catalina issue #3829

**Comment by pieandcakes** [comment] 2020-01-22 19:25
I'm assigning this to #3829 now since it will be worked as the same issue.

**Closed as completed by pieandcakes** 2020-01-22 19:25 UTC
Labels: debugger
