### ISSUE TITLE
C_Cpp.commentContinuationPatterns don't work when IntelliSense engine is Disabled

### ISSUE THREAD

**Issue by bdwiel** [microsoft/vscode-cpptools#3417] opened 2019-04-05 12:37 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS 10.14.4
- VS Code Version: 1.32.3
- C/C++ Extension Version: 1.32.3
- Other extensions you installed (and if the issue persists after disabling them): Vim, cycles, CodeLLDB, ScopeBar
- A clear and concise description of what the bug is.

When inside a single-line comment and 'Enter' is pressed, the newline no longer beings with the single-line comment marker ('//'). The behavior used to work as expected but stopped recently (1-2 weeks).

In my settings.json, I have this:

"C_Cpp.updateChannel": "Insiders",
    "C_Cpp.default.intelliSenseMode": "clang-x64",
    "C_Cpp.default.cppStandard": "c++14",
    "C_Cpp.default.cStandard": "c11",
    "C_Cpp.intelliSenseEngineFallback": "Disabled",
    "C_Cpp.commentContinuationPatterns": [
        "// ",
        "/**"
    ],
    "C_Cpp.loggingLevel": "Information",
    // "C_Cpp.loggingLevel": "Debug",
    "C_Cpp.default.systemIncludePath": [

      "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include",
        "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1"
    ],
    "C_Cpp.autocomplete": "Disabled",
    "C_Cpp.formatting": "Disabled",
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.intelliSenseEngine": "Disabled",

**And my c_cpp_properties.json**
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "${workspaceFolder}/compile_commands.json"
        }
    ],
    "version": 4
}

**To Reproduce**
Edit a C++ file. Enter this on a blank line.
    // comment
Then press Enter. The cursor moves to a new line but does not insert the comment pattern.

**Expected behavior**
The comment pattern to be inserted before the cursor on the new line after hitting Enter.

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment] 2019-04-09 22:11
Hmm, it's working for me. We didn't change area of code at all recently so a regression is unlikely unless VS Code broke something.

Does it still repro with the latest VS Code 1.33?

**Comment by bdwiel** [comment] 2019-04-10 12:52
I narrowed it down to this line in my settings.json

```json
"C_Cpp.intelliSenseEngine": "Disabled"
```

I guess the comment continuation is part of intelliSense. I'd be happy to hear any workarounds that might exist, but I don't expect there to be any fixes for this issue.

**Comment by sean-mcmanus** [comment] 2019-04-10 16:36
Okay, that makes sense. It's not really part of "IntelliSense", but our IntelliSense disabling code occurs too early. It's possible this is fixable in our open source TypeScript if anyone wants to investigate. I think we'll be too busy with other stuff until our April release ships.

**Comment by Georacer** [comment] 2019-06-13 17:03
I'd like to report this as well.
Having 
```
    "C_Cpp.commentContinuationPatterns": [
        "//",
        "/*"
    ],
```
in my `settings.json` has no effect when IntellisenseEngine is enabled;
While creating comment blocks with the Doxygen documentation generator extension, an extra `*/` is appended below the autogenerated `*/` closing comment.

**Comment by kinyubi** [comment] 2019-07-25 15:40
I stumbled on a solution. If you change "doxdocgen.c.triggerSequence": from "/\*\*" to "\*\*\*" the intellisense engine no longer preempts the doxygen generator. After making the change, just type *** and doxygen does its thing even changing *** to the expected /**.  Hope this helps someone.

**Comment by bobbrow** [comment] 2020-04-09 21:51
Unfortunately, this is not something we plan to fix at this time.  If we see more upvotes, we can revisit the decision.

**Closed as completed by bobbrow** 2020-04-09 21:51 UTC
Labels: bug, Language Service, help wanted, more votes needed

**Comment by fezho** [comment] 2021-07-02 07:11
I just fix this issue by uninstalling doxdocgen, thanks @kkm000

**Comment by jiudianren** [comment] 2022-07-12 03:39
C_Cpp.commentContiniutionPatterns  how to define  comment like this

/*
*  a=0;
*  b=0;
*/

every line has a "*"  at the start ,for comment  code block.
Thanks.

**Comment by sean-mcmanus** [comment] 2022-07-12 17:00
@jiudianren I don't know. That may not be supported currently, i.e. the closest thing that works is the default of `/**`.

**Comment by JasonPhone** [comment] 2023-10-21 12:21
Same issue in 1.83.1. Took the workaround using `kevinkyang.auto-comment-blocks`.

Setting `"C_Cpp.intelliSenseEngine": "default",` with

```json
"C_Cpp.commentContinuationPatterns": [
  {
    "begin": "///",
    "continue": "/// ",
  },
],
```

works *perfectly* also, event with other extensions. But for me clangd requires the intellisense of cpptools to be disabled. Pity.

I think it's a strange dependence between intellisense and comment continuation (since they are both from cpptools), which requires an explicit hint. ~I prefer decoupling them and make the continuation work even alone.~
