### ISSUE TITLE
Indexing / parsing fails due to code that is removed by preprocessor.

### ISSUE THREAD

**Issue by vliedel** [microsoft/vscode-cpptools#12509] opened 2024-07-25 07:58 UTC
### Environment

- OS and Version: Windows 11
- VS Code Version: 1.91.1
- C/C++ Extension Version: 1.21.3

### Bug Summary and Steps to Reproduce

Have some code like this:
```
int foo(int arg) {
#ifdef FOO
   if (arg == 1) {
#else
   if (arg == 2) {
#endif
      return arg;
   }
   return 0;
}
```

Now the parser or indexer will think the last `}` closes `if (arg == 1) {`, and will be totally wrong.

![2024-07-25 10_47_58-test c - test (Workspace) - Visual Studio Code](https://github.com/user-attachments/assets/742dec11-1808-4fb0-854c-ec783ec4cb62)

### Configuration and Logs

```shell
No idea where to find the config file, I don't think i changed the defaults.
```

**Comment by sean-mcmanus** [comment] 2024-07-25 19:12
@vliedel Duplicate of https://github.com/microsoft/vscode-cpptools/issues/3681

**Closed as not planned by sean-mcmanus** 2024-07-25 19:12 UTC
Labels: duplicate
