### ISSUE TITLE
tag parser freeze on parsing large define

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode-cpptools#9076] opened 2022-03-23 14:44 UTC
Issue Type: <b>Bug</b>

In attachment - simple project.
tag parser freezes when try to parse test.h file

Extension version: 1.8.4
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.4.0-100-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3923)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|31.25GB (0.75GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by dibalavs** [comment] 2022-03-23 14:44
[vscode_bug.tar.gz](https://github.com/microsoft/vscode-cpptools/files/8333962/vscode_bug.tar.gz)

**Comment by sean-mcmanus** [comment] 2022-03-23 19:44
Does that test.h have a lot of defines? If so, it's bug https://github.com/microsoft/vscode-cpptools/issues/6454 .

**Comment by dibalavs** [comment] 2022-03-24 06:30
@sean-mcmanus , No. It has only 1 define. but very large.

**Comment by sean-mcmanus** [comment] 2022-03-24 18:38
Are you able to paste the contents of the define inline? I can't seem to download https://github.com/microsoft/vscode-cpptools/files/8333962/vscode_bug.tar.gz .

**Comment by dibalavs** [comment] 2022-03-24 18:47
strange. I will re-attach file
[vscode_bug.tar.gz](https://github.com/microsoft/vscode-cpptools/files/8344506/vscode_bug.tar.gz)

**Comment by dibalavs** [comment] 2022-03-24 18:48
@sean-mcmanus  Please check attachment again.

**Comment by sean-mcmanus** [comment] 2022-03-24 21:41
Okay, I repro the issue. Do you know if it ever finishes? Our parser is "stuck" processing the define. Not sure if it's just slow or permanently stuck. As a workaround you can add that folder that file belongs to to the C_Cpp.files.exclude setting or the file if you change the C_Cpp.exclusionPolicy to work for files.

**Comment by sean-mcmanus** [comment] 2022-03-24 21:44
Also, the issue is different from https://github.com/microsoft/vscode-cpptools/issues/6454 .

**Comment by sean-mcmanus** [comment] 2022-03-25 04:19
I get a crash after about an hour. I've filed a bug on VS at https://developercommunity.visualstudio.com/t/c-tag-parser-gets-stuck-parsing-for-an-hour-and-th/1702811 -- that issue might not be publicly viewable though.

**Comment by sean-mcmanus** [comment] 2022-05-24 00:16
This is fixed with 1.10.3 (pre-release).

**Closed as completed** 2022-06-08 22:06 UTC
Labels: bug, Language Service, fixed, performance, Visual Studio, verified
