### ISSUE TITLE
tag parser stuck on specific file

### ISSUE THREAD

**Issue by kaix-huang** [microsoft/vscode-cpptools#8331] opened 2021-10-27 05:51 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10(host), Ubuntu 16.04(SSH remote)
- VS Code Version: 1.61.2 (user setup)
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: Ubuntu 16.04
- **tag parser always stuck on a `reg.h` file, which contains > 1M lines of #define macros. (Sorry, I can't show the file for it's an internal project)**
- **Call stacks are attached in comments below.**

**Detailed infomation**
I set `C_Cpp.loggingLevel` to `Debug`, the log runs normally at beginning. Then it hangs at "tag parsing file: xxx/reg.h" for hours.
CPU usage of cpptools process is always 100%. I tried to attach gdb to it and call stacks are in the comments.

**Comment by sean-mcmanus** [comment] 2021-11-01 17:19
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6454 and https://developercommunity.visualstudio.com/t/updating-cc-intellisense-and-browsing-information-1/1263948

**Closed as completed by sean-mcmanus** 2021-11-01 17:19 UTC
Labels: Language Service, parser

**Comment by sean-mcmanus** [comment] 2022-07-08 20:56
This fix is available with 1.11.2 (pre-release): https://github.com/microsoft/vscode-cpptools/releases
