### ISSUE TITLE
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\M1058538\Desktop\test.cpp).

### ISSUE THREAD

**Issue by mallesh116** [microsoft/vscode-cpptools#5664] opened 2020-06-19 04:20 UTC
Type: Debugger

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment] 2020-06-20 03:27
Can you provide more repro info? Such as from the C/C++: Log Diagnostics command?

**Comment by FazeelUsmani** [comment] 2020-09-13 18:32
![image](https://user-images.githubusercontent.com/8823157/93025684-96a37280-f61d-11ea-888f-8754ead59d26.png)

Even I'm facing the same issue

**Comment by sean-mcmanus** [comment] 2020-09-14 19:51
@FazeelUsmani Make sure your includePath doesn't contain any system headers and your compilerPath is set correct and then run C/C++: Log Diagnostics and see if the output appears correct or not. Does that help?

**Comment by FazeelUsmani** [comment] 2020-10-11 11:02
Thank you for the help, @sean-mcmanus. It''s working now.

**Comment by michelleangela** [comment] 2020-12-09 18:41
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 18:41 UTC
Labels: Language Service, more info needed
