### ISSUE TITLE
C++11 'alignof' keyword not recognized

### ISSUE THREAD

**Issue by Leedehai** [microsoft/vscode-cpptools#938] opened 2017-08-02 03:15 UTC
<img width="220" alt="screen shot 2017-08-01 at 20 15 36" src="https://user-images.githubusercontent.com/18319900/28856161-32c6c40a-76f6-11e7-883f-183eb5df35b9.png">
I know I could've tweak with the language setting file but updates can overwrite my modification...

**Comment by sean-mcmanus** [comment] 2017-08-02 17:36
It's a bug with the VS Code's default Dark theme. If you switch your theme to something like Monokai, you should see it as keyword colored. I remember a bug was filed on VS Code about this, but I haven't found it yet.

**Comment by Leedehai** [comment] 2017-08-02 22:17
@sean-mcmanus This is the [pull request](https://github.com/Microsoft/vscode/pull/2649) last year, but it is still not in production yet.

**Comment by sean-mcmanus** [comment] 2017-08-02 22:26
@Leedehai No, the pull request last year is out. The problem is with the theme coloring you're using, which colors the alignof white instead of blue. The Monokai theme colors "alignof" correctly as a keyword.

However, there does appear to be another bug in that "alignof(" with a parenthesis is not being colored correctly. I've filed bug https://github.com/atom/language-c/issues/246 for that.

**Comment by sean-mcmanus** [comment] 2017-08-02 22:34
The previous theming bug we filed got fixed for sizeof (see https://github.com/Microsoft/vscode/issues/22419 ), but it looks like there's an additional issue with alignof. I added a comment to that bug and will open a new bug if necessary.

**Comment by DenisYaroshevskiy** [comment] 2018-07-11 06:34
Hi! Just a ping in case this would boost the ticket's priority)

**Comment by sean-mcmanus** [comment] 2018-07-11 19:02
@DenisYaroshevskiy This is bug https://github.com/atom/language-c/issues/246, so it needs to be fixed there, so maybe you could upvote that issue? A fix was made in a forked repo of atom/language-c, but not the official repo, so someone could also to porting that fix.

**Comment by jeff-hykin** [comment] 2019-02-10 10:18
I went ahead and made a fix for this (as well as several other issues) and put them in an extension. https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax#overview

**Comment by Colengms** [comment] 2019-10-11 01:04
This issue is external to cpptools.  The TextMate grammar for C++ (in VS Code) is correctly identifying the token as `keyword.operator.alignof.cpp`.  It's up to the theme to apply a color to it.

https://github.com/microsoft/vscode/issues/80783 is tracking adding some C/C++ specific tokens to the default themes in VS Code.  I commented there about alignof, specifically.

Closing this issue.  If someone feels strongly that this should also be tracked in cpptools, let us know.

**Closed as completed by Colengms** 2019-10-11 01:04 UTC
Labels: Language Service, external
