### ISSUE TITLE
The language server pretends to be clang, but it isn't clang.

### ISSUE THREAD

**Issue by smoofra** [microsoft/vscode-cpptools#4246] opened 2019-09-13 20:07 UTC
**Type: LanguageService**
- OS and Version: Mac OS 10.15
- VS Code Version: Version: 1.38.1
- C/C++ Extension Version: 0.25.1

**Description**

The C/C++ language server can define preprocessor variable `__clang__` for parsing, but it is not clang and it is not fully compatible with clang.

This is a problem because it defeats `ifdef` conditionals that are there specifically to  enable clang specific compiler features.      For example, this class from llvm is using `enable_if` in a way that the Microsoft C++ parser does not support.   This should not be a problem because it has preprocessor conditionals to only do so when the compiler is clang.   But because the Microsoft parser defines `__clang__` anyway, it produces errors.

```
  class StringLiteral : public StringRef {
  private:
    constexpr StringLiteral(const char *Str, size_t N) : StringRef(Str, N) {
    }

  public:
    template <size_t N>
    constexpr StringLiteral(const char (&Str)[N])
#if defined(__clang__) && __has_attribute(enable_if)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"
        __attribute((enable_if(__builtin_strlen(Str) == N - 1,
                               "invalid string literal")))
#pragma clang diagnostic pop
#endif
        : StringRef(Str, N - 1) {
    }

    // Explicit construction for strings like "foo\0bar".
    template <size_t N>
    static constexpr StringLiteral withInnerNUL(const char (&Str)[N]) {
      return StringLiteral(Str, N - 1);
    }
  };
```

This produces the error:

```
{
	"resource": "/Volumes/data/src/llvm-project/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "'enable_if' attributes with conditions that are not constant values are not currently supported -- attribute was declared here",
	"startLineNumber": 1026,
	"startColumn": 14,
	"endLineNumber": 1026,
	"endColumn": 18
}
```

**To Reproduce**

1.  Setup a workspace with clang.

```
"compilerPath": "/usr/bin/clang",
"intelliSenseMode": "clang-x64",
```

2. Use `#ifdef __clang__` in your code 

3. The clang specific code ought to be be greyed out and should not be able to produce compiler errors — but it isn't.

**Further info**

It appears the language server is invoking clang like this to get a  list of system defines.

```
clang -std=c11 -Wp,-v -E -xc -dD -x c /dev/null
clang -std=c++2a -Wp,-v -E -xc -dD -x c++ /dev/null
```

**Comment by sean-mcmanus** [comment] 2019-09-13 20:42
The Microsoft compiler is "cl.exe", but the IntelliSense compiler is based on the EDG compiler which emulates cl.exe or clang based on different settings we use, i.e. it's supposed to work (we have one known bug with __has_include that hasn't had the fix shipped yet https://github.com/microsoft/vscode-cpptools/issues/4193 ).

I'm not reproing the error (I tried on Mac too and it works after I remove the StringRef undefined code and add `#include <cstddef>`).  Can you use C/C++: Log Diagnostics and let us know what flags/settings are being used?

**Comment by smoofra** [comment] 2019-09-13 20:46
I don't see a setting called "Log Diagnostics" under C/C++...   How do I turn that on?

**Comment by sean-mcmanus** [comment] 2019-09-13 20:46
It's a command (from the command prompt, Ctrl+Shift+P).

**Comment by smoofra** [comment] 2019-09-13 20:47
```
-------- Diagnostics - 9/13/2019, 1:47:10 PM
Version: 0.25.1
Current Configuration:
{
    "defines": [
        "VSCODE=1"
    ],
    "macFrameworkPath": [
        "/Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks"
    ],
    "includePath": [
        "/Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include",
        "/Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
        "/Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include"
    ],
    "name": "Mac",
    "compilerPath": "/Users/lawrence_danna/bin.local/wclang",
    "intelliSenseMode": "clang-x64",
    "compileCommands": "/Users/lawrence_danna/build/lldb/compile_commands.json",
    "compilerArgs": [],
    "browse": {
        "path": [
            "/Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include",
            "/Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
            "/Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Volumes/data/src/llvm-project/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp ]:
    /Volumes/data/src/llvm-project/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp
    /Volumes/data/src/llvm-project/llvm/include/llvm/ADT/StringRef.h
[ /Volumes/data/src/llvm-project/lldb/source/Plugins/ScriptInterpreter/Python/PythonExceptionState.cpp ]:
    /Volumes/data/src/llvm-project/lldb/source/Plugins/ScriptInterpreter/Python/PythonExceptionState.cpp
    /Volumes/data/src/llvm-project/llvm/include/llvm/ADT/StringRef.h
Translation Unit Configurations:
[ /Volumes/data/src/llvm-project/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp ]:
    Process ID: 73033
    Memory Usage: 319 MB
    Compiler Path: /Users/lawrence_danna/bin.local/wclang
    Includes:
        /Volumes/data/build/lldb/tools/lldb/source/Plugins/ScriptInterpreter/Python
        /Volumes/data/src/llvm-project/lldb/source/Plugins/ScriptInterpreter/Python
        /Volumes/data/build/lldb/tools/lldb/source
        /Volumes/data/src/llvm-project/lldb/include
        /Volumes/data/build/lldb/tools/lldb/include
        /Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libxml2
        /Volumes/data/build/lldb/include
        /Volumes/data/src/llvm-project/llvm/include
        /Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
        /Volumes/data/src/llvm-project/clang/include
        /Volumes/data/build/lldb/tools/clang/include
        /Volumes/data/src/llvm-project/lldb/source
        /usr/local/include
        /Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
    Frameworks:
        /Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks
    Defines:
        VSCODE=1
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110000
[ /Volumes/data/src/llvm-project/lldb/source/Plugins/ScriptInterpreter/Python/PythonExceptionState.cpp ]:
    Process ID: 73044
    Memory Usage: 243 MB
    Compiler Path: /Users/lawrence_danna/bin.local/wclang
    Includes:
        /Volumes/data/build/lldb/tools/lldb/source/Plugins/ScriptInterpreter/Python
        /Volumes/data/src/llvm-project/lldb/source/Plugins/ScriptInterpreter/Python
        /Volumes/data/build/lldb/tools/lldb/source
        /Volumes/data/src/llvm-project/lldb/include
        /Volumes/data/build/lldb/tools/lldb/include
        /Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libxml2
        /Volumes/data/build/lldb/include
        /Volumes/data/src/llvm-project/llvm/include
        /Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
        /Volumes/data/src/llvm-project/clang/include
        /Volumes/data/build/lldb/tools/clang/include
        /Volumes/data/src/llvm-project/lldb/source
        /usr/local/include
        /Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
    Frameworks:
        /Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks
    Defines:
        VSCODE=1
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 562 MB

```

**Comment by sean-mcmanus** [comment] 2019-09-13 20:55
I'm using clang version 100001 -- we haven't tested with 110000 yet, so that might be the difference. I'll see...

Does your code file have any includes? I had to add `#include <cstddef>` to get size_t to be defined. Also, do you have the definition for StringRef? I had to remove that for the repro...but it seems like it shouldn't be necessary since it seems like the enable_if code is getting compiled correctly...actually, the base class might be causing the issue.

**Comment by smoofra** [comment] 2019-09-13 21:15
The full source code for the file I'm looking at is [here: StringRef.h](https://github.com/llvm/llvm-project/blob/master/llvm/include/llvm/ADT/StringRef.h)

That's a header, the cpp file for the translation unit that I first saw the problem in is [here: PythonDataObjects.cpp](https://github.com/llvm/llvm-project/blob/master/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp)

I just downloaded the llvm sources and used cmake to generate `compile_commands.json`

My `c_cpp_properties.json` looks like this:

```
{
    "configurations": [
        {
            "macFrameworkPath": [
                "/Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks"
            ],
            "includePath": [
                "/Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include",
                "/Volumes/data/xcode-os.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                "/Volumes/data/xcode-os.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include"
            ],
            "name": "Mac",
            "compilerPath": "/usr/bin/clang",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "/Users/lawrence_danna/build/lldb/compile_commands.json"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment] 2019-09-17 02:26
We'll try to investigate (might take a few day since we're trying to get a 0.26.0-insiders out)…

I see a bug fix "in the pipeline" involving enable_if, so that might fix this (not sure yet).

**Comment by bobbrow** [comment] 2019-10-10 18:18
I don't see any errors with StringRef.h with 0.25.1 or 0.26.0-insiders3 on my MacBook.  I was on the llvm subfolder though since I didn't find instructions to get CMake configured for the lldb project.

**Comment by bobbrow** [comment] 2020-02-28 18:40
This is a duplicate of #3683.

**Closed as completed by bobbrow** 2020-02-28 18:40 UTC
Labels: bug, duplicate, Language Service
