### ISSUE TITLE
F2: rename static variable is very slowwwwwww.

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode-cpptools#6547] opened 2020-11-19 12:22 UTC
**Type: LanguageService**
I try to rename static global variable.
I pressed F2, entered new name and pressed Enter.
VSCode is doing something for 5 more minues. and found 1900 files where need to rename.
But this is **static**  variable. it does not exists out of this (.c) file.
I think refactoring feature for renaming static identifiers can be improved.
![image](https://user-images.githubusercontent.com/801951/99665577-def66b00-2a7a-11eb-9e15-22e6350c6771.png)

------------------------------
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
C/C++ extension: 1.1.2

**Comment by sean-mcmanus** [comment] 2020-11-19 20:24
Looks like around 9893 files have the text "thread" and we return lexical results like string/comment references which could be in other files (although we could add some setting to change that behavior).

Also, the static variable could be accessible by other files that are in the same TU, although our search isn't limited to files in the TU.

After the search phase, the confirming phase has an issue in which it'll still try to confirm references in different TUs, which is the same as the VS issue https://developercommunity.visualstudio.com/content/problem/1014321/c-intellisense-find-all-references-confirms-refere.html (that repro description uses namespace {} for file local variables).

**Comment by mreale** [comment] 2020-11-25 00:11
F2 refactoring in VSCode the most dangerous thing I ever used in a IDE.

**Comment by sean-mcmanus** [comment] 2020-11-25 02:10
@mreale Can you explain what was dangerous about it? Was it just the speed or did it rename incorrect code?

**Comment by mreale** [comment] 2020-11-25 15:38
I use platformIO extension and sometimes the refactoring process freezes and after that I got an half-refactored (and messed) source code.  Also I had to double check the refactoring preview to ensure that only the intended source in my project will be affected since I (rarely) got files out of my source tree (mcu and framework libraries) marked to refactoring.  I had no time to investigate the conditions to reproduce this behavior and I feel unconfortable every time I hit f2.  Maybe an issue with PIO, though.

![refactor](https://user-images.githubusercontent.com/6580046/100247853-8a8b3980-2f19-11eb-9099-356021b688cd.png)

**Comment by sean-mcmanus** [comment] 2020-11-26 04:19
@mreale Half-refactoring can occur if some references are incorrectly not marked as confirmed/selected. One such bug we just fixed is https://github.com/microsoft/vscode-cpptools/issues/4249 . But our rename/FAR accuracy is still not 100%, so it is recommended that you look at the preview and then compile your code after the change. There are some complicated scenarios related to overloads, templates, inherited members, and file-local variables that can cause errors or or ambiguity in regards to which symbols should be included in the rename by default. So in that respect, I would agree in the rename being potentially dangerous.

**Comment by mreale** [comment] 2020-11-26 14:44
I agree that's a very complicated business specially with non dynamic languages, like C/C++ and it's hard to address every possible scenario.  

Thanks for your time!

**Comment by pflannery** [comment] 2020-12-24 13:11
@mreale 
>  Also I had to double check the refactoring preview to ensure that only the intended source in my project will be affected since I (rarely) got files out of my source tree (mcu and framework libraries) marked to refactoring

I was having a similar issue with arduino projects (I dont use platform.io though).

I discovered that I had references like ```#include "Arduino.h"``` in the files I was refactoring and thus it was including files outside my project in the rename list. 

Once I changed the external references to ```#include <Arduino.h>``` the files outside of my project were no longer appearing in the rename symbol list.

**Comment by pflannery** [comment] 2020-12-24 13:29
Another thing I find is that entries in the "includePath" of the c_cpp_properties.json file will also get included.

Maybe we could have an "externalIncludePath" that gets ignored by refactoring?

**Comment by sean-mcmanus** [comment] 2020-12-28 20:03
@pflannery Your request is being tracked by https://github.com/microsoft/vscode-cpptools/issues/4102 .

**Closed as completed** 2021-04-22 11:45 UTC
Labels: Language Service, performance, more votes needed, Feature: Find All References, Feature: Rename, enhancement
