### ISSUE TITLE
Not working left part

### ISSUE THREAD

**Issue by Jenny0316** [microsoft/vscode-cpptools#6291] opened 2020-10-10 02:24 UTC
Type: Debugger

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.19041
- VS Code Version:1.50.0
- C/C++ Extension Version: v1.0.1
- Other extensions you installed (and if the issue persists after disabling them):mingw
- A clear and concise description of what the bug is.
When I degugging the code, the left part did not show up for example variables and call stack things.
I runned very easy code

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

#include<stdio.h>

int main(){
    int a=10;
    int b=20;
    int c;

    c=a+b;

    printf("%d + %d = %d\n",a,b,c);

    printf("hello1\n");
    printf("hello2\n");
    printf("hello3\n");
    printf("hello4\n");
 

    return 0;
}--------------------------------------------------------------------------------------------------------

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe - 활성 파일 빌드 및 디버그",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "gdb에 자동 서식 지정 사용",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++.exe build active file"
        }
    ]
}
[bandicam 2020-10-09 14-26-09-822.zip](https://github.com/microsoft/vscode-cpptools/files/5358314/bandicam.2020-10-09.14-26-09-822.zip)

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment] 2020-10-13 01:12
Please provide the exact error messages you are seeing.

**Comment by Jenny0316** [comment] 2020-10-13 01:47
I already attached the video in the zip file on Github but I will attach it
here again for you
and the sentence the bottom blue line means
g++.exe-활성 파일 빌드 및 디버그(vscoding)   ->   g++.exe-Build and debug active
files (vscoding)
I translated it for you except that you can read all word in the video

2020년 10월 12일 (월) 오후 6:13, Sean McManus <notifications@github.com>님이 작성:

**Comment by jihyeon316** [comment] 2020-10-15 02:35
> Please provide the exact error messages you are seeing.
[error.zip](https://github.com/microsoft/vscode-cpptools/files/5382104/error.zip)

**Comment by Jenny0316** [comment] 2020-10-15 02:37
> Please provide the exact error messages you are seeing.

[error.zip](https://github.com/microsoft/vscode-cpptools/files/5382109/error.zip)

**Comment by sean-mcmanus** [comment] 2020-10-15 22:06
I don't see any error in the video or when trying the repro.

![image](https://user-images.githubusercontent.com/19859882/96190945-f5e3f380-0ef7-11eb-92c0-069db535dca5.png)

**Comment by Jenny0316** [comment] 2020-10-15 22:14
I mean the console window disappeared very quickly and I can't see any
things on variables part. You can see it in the video

2020년 10월 15일 목요일, Sean McManus <notifications@github.com>님이 작성:

**Comment by sean-mcmanus** [comment] 2020-10-15 22:50
That is "by design". Your program is exiting, causing the console window to close. You can set a breakpoint on the final return of main to prevent the console from closing.

@WardenGnaw might have more info.

**Closed as completed** 2020-10-28 21:03 UTC
Labels: Language Service, by design
