### ISSUE TITLE
Debugger doesn't show the content of string, map

### ISSUE THREAD

**Issue by ftrofin** [microsoft/vscode-cpptools#1881] opened 2018-04-26 06:46 UTC
OS: macOS Sierra (10.12.6)
Visual Studio Code Version 1.22.2
ms-vscode.cpptools 0.16.1
Xcode 9.2 installed
My launch configuration specified lldb as the debugger.
I also tried this with "Native Debug" extension version  0.22.0 and got the same behavior.

The launch configuration looks like:

    {
        "name": "(lldb) Launch MyApp",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceFolder}/Targets/MyApp/Mac/Debug/64/MyApp.app/Contents/MacOS/MyApp",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": true,
        "MIMode": "lldb"
    },

I can't see the content of most classes but I can see the value of basic types (like int). For example, a basic_string looks like this:

![image](https://user-images.githubusercontent.com/8718388/39289634-cadff73a-48e1-11e8-91bc-a262132a69a1.png)

The interesting thing is that it recognizes it correctly and I can expand it to a point but just when I would get to see the value it gives up.

Another example:
![image](https://user-images.githubusercontent.com/8718388/39289699-0ca767f2-48e2-11e8-9ae1-8dcffa40260e.png)

This class contains a mutex and two std::unordered_map members. I can see only the size of the maps, not their elements.

Is there a way to fix this? Does Visual Studio Code honor lldb configuration files? I have a ~/.lldbinit and a ~/lldbsummaries.py that I was using with Xcode as custom data formatters for my classes.
Please let me know if you need more information.
I am very excited by VSC and I'm looking forward to be using it as a permanent replacement to Xcode.
Thanks!

Florin

**Comment by WardenGnaw** [comment] 2018-04-26 20:38
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/1768

**Closed as completed by WardenGnaw** 2018-04-26 20:38 UTC

**Comment by WardenGnaw** [comment] 2018-04-26 20:39
You may be able to use the ```setupCommands``` in your launch.json to configure lldb.
