### ISSUE TITLE
LLVM/Clang no longer contains lldb-mi.exe

### ISSUE THREAD

**Issue by fxzxmic** [microsoft/vscode-cpptools#10097] opened 2022-11-01 08:22 UTC
### Feature Request

So is there any alternative feature to use lldb?

**Comment by H-G-Hristov** [comment] 2022-11-01 09:19
CodeLLDB

**Comment by WardenGnaw** [comment] 2022-11-02 20:51
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/6617

**Closed as completed by WardenGnaw** 2022-11-02 20:52 UTC
