### ISSUE TITLE
Tokenization Error on symlinks files

### ISSUE THREAD

**Issue by alealv** [microsoft/vscode-cpptools#5986] opened 2020-08-19 15:07 UTC
**Type: LanguageService**

**Describe the bug**
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:40:55.768Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.9-050709-generic
C/C++ Extension Version:  0.30.0-insiders2

I have an example project and It seems when opening files from symlink locations the Tokenizer doesn't work.

![Screenshot from 2020-08-19 17-06-20](https://user-images.githubusercontent.com/9395091/90652440-5f1ff100-e23e-11ea-945d-138c92774ab4.png)

**Comment by sean-mcmanus** [comment] 2020-08-19 18:08
Yeah, I see the enhancedColorization feature not working when opening a folder that is a symlink (created from `ln -s source link`) on Linux. @Colengms

**Comment by alealv** [comment] 2020-08-19 21:05
I don't know if it's just enhancedColorization because when running **Developer: Inspect Editor Tokens and Scopes** it does not load.
![Screenshot from 2020-08-19 23-04-08](https://user-images.githubusercontent.com/9395091/90689404-52b48c00-e270-11ea-9e71-3d116dbb8598.png)

**Comment by sean-mcmanus** [comment] 2020-08-19 22:35
The root problem is that our IntelliSense engine is returning squiggles for the resolves symlink target instead of the original symlink path -- you can observe this by the fact that squiggles do not appear in the document, and in the problems window it shows the errors for the non-opened file (symlink target URI).

The "Loading" from Inspect Scopes appears to be because the semantic token results for the file never get returned.

**Comment by sean-mcmanus** [comment] 2020-08-19 22:46
Ah, looks like we're tracking this issue with https://github.com/microsoft/vscode-cpptools/issues/4573 .

I'm closing this as a duplicate of that issue.

**Closed as completed by sean-mcmanus** 2020-08-19 22:46 UTC
Labels: bug, duplicate, Language Service, verified, Feature: Colorization
