### ISSUE TITLE
Playbutton not building correctly on Mac (dependency on std version)

### ISSUE THREAD

**Issue by AlexandraKemperMS** [microsoft/vscode-cpptools#11292] opened 2023-08-04 22:35 UTC
### Environment

- OS and Version: macOS on 12.6.2 (monterey)
- VS Code Version: 1.80.1
- C/C++ Extension Version: 1.16.3
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
in the walkthrough on a mac, when you try to run the hello world code from our docs, the play button does not build correctly - it needs to append the -std=c++17

Steps to reproduce:
1. Go to our walkthrough
2. Install clang, configure clang++ as the compiler
3. Create a file and add the code from the C++ docs for hello world
4. Click on the play button in "run" mode - the code will not build correctly.
5. Manually run the code with the -std=c++17 flag and it will build correctly.

Expected behavior: run/build correctly using the correct version of std library

### Configuration and Logs

```shell
Does not exist yet because you are in a single file in the walkthrough.
```

**Comment by AlexandraKemperMS** [comment] 2023-08-04 22:36
I have replicated this on my mac (not through SSH), if more info is needed let me know

**Comment by sean-mcmanus** [comment] 2023-08-04 22:49
This is the same issue as https://github.com/microsoft/vscode-cpptools/issues/9600 . It's currently "by design". The C++ docs for hello world should mention that `-std=c++17` may need to be added if their compiler defaults to an older standard version. I seem to recall reading that a future Apple clang version would be increasing the default standard version.

**Comment by AlexandraKemperMS** [comment] 2023-08-04 23:08
It's also a duplicated issue from [#11062](https://github.com/microsoft/vscode-cpptools/issues/11062). While it is by design, it creates a terrible walkthrough experience - you click the play button and it does not work. We can add it to the C++ docs, but that does not help users in the walkthrough. We should increase the default standard version on Mac.

**Comment by sean-mcmanus** [comment] 2023-08-04 23:20
The walkthrough doesn't mention using code that is C++ 17 specific, does it?

**Comment by AlexandraKemperMS** [comment] 2023-08-07 16:20
Using C++20 or C++23 would not be a problem - just using something before C++17. If you do use the built in one on mac, Intellisense starts showing errors in your code that do not exist. For example, that there is a missing semicolon at the end of your line when there clearly is one. This was the error I had shown to you and Michelle in office about the walkthrough (where Intellisense was showing incorrect suggestions) that we were unable to repro at the time.

**Comment by sean-mcmanus** [comment] 2023-08-07 17:19
@AlexandraKemperMS Can we just update the sample code to not use C++17 features?

**Comment by bobbrow** [comment] 2023-08-07 20:32
@sean-mcmanus that doesn't solve the problem.  As soon as the customer uses a C++11 feature, the build breaks.

**Comment by sean-mcmanus** [comment] 2023-08-07 20:51
@bobbrow You mean C++17 or newer. You could make the same argument if a customer adds C++20 or C++23 code, but then the user could add code that compiles with C++17 but fails with C++20 or C++23.

But I'm not saying that this shouldn't be fixed...I'm not entirely clear on what the design philosophy is for the play button feature.

**Comment by bobbrow** [comment] 2023-08-07 22:01
I meant C++11 because it looked like the Apple Clang compiler was defaulting to c++98 or some old standard like that.

Ideally we'd surface the standard version that we pick for IntelliSense to the TypeScript side so we can pick that one, but in this case we were hoping for something quick that would be mostly reliable until we get all of the compiler querying stuff over into TypeScript.  Once those changes are in, it should be relatively easy to know what version the compiler supports and pick that.

**Comment by bobbrow** [comment] 2023-08-07 22:24
I was thinking about just hardcoding c++14 for the task for 1.17 and then we can get the full fix in 1.18.

**Comment by michelleangela** [comment] 2023-08-10 00:57
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.1.

**Comment by michelleangela** [comment] 2023-08-15 00:03
Fixed in release version https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.2.

**Closed as completed by michelleangela** 2023-08-15 00:03 UTC
Labels: bug, Language Service, fixed, tasks/build/debug
