### ISSUE TITLE
include pathes provided by isystem are ignored by compile commands parser

### ISSUE THREAD

**Issue by wcscmp** [microsoft/vscode-cpptools#1156] opened 2017-10-23 10:25 UTC

**Comment by sean-mcmanus** [comment] 2017-10-23 14:34
What is `isystem`? When your compileCommands is set, the includePath setting is intentionally ignored.

**Comment by wcscmp** [comment] 2017-10-23 16:50
https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html
-isystem is used for include from which we want to ignore warnings.
For example for third party libraries which we would not modify.

**Comment by sean-mcmanus** [comment] 2017-10-23 17:33
How are you generating the compile_commands.json? Is this a bug with how we're processing that file or how it's generated by another tool? Are we not reading a particular field in the json?

**Comment by wcscmp** [comment] 2017-10-24 07:33
I'm generating it using cmake with a -DCMAKE_EXPORT_COMPILE_COMMANDS=ON parameter provided.
In a cmake file target_include_directories is called with SYSTEM specified.
https://cmake.org/cmake/help/v2.8.12/cmake.html#command:target_include_directories
In a compile_commands.json include directories are provided in a "-isystem <directory path>" format instead of "-I<directory path>".
Headers from those directories cannot be found by cpptools.
I'm replacing "-isystem " with "-I" in compile_commands.json which resolves my issue.  This is a manual step thought which is not nice.

**Comment by bobbrow** [comment] 2017-10-24 15:44
We can fix this.  Thanks for letting us know about the issue.

**Comment by mbodmer** [comment] 2017-11-21 14:14
Hi, I have the same issue here. I think you could just treat -isystem paths the same as normal -I include paths but do not warn if it is not possible to resolve any further includes from the referenced system header.

**Comment by bobbrow** [comment] 2017-12-12 04:36
This should be fixed in 0.14.4

**Closed as completed by bobbrow** 2017-12-12 04:36 UTC
Labels: bug, Language Service, fixed

**Comment by niosHD** [comment] 2017-12-12 13:22
Sorry to rain on your parade, but the problem is (at least for cmake generated compilation databases) unfortunately not fixed in 0.14.4.

I put together a [minimal working example](https://github.com/niosHD/mwe-vscode-cpp-code-completion) which shows the problem. In summary, it seems to be that `-isystem` is now handled exactly like `-I` meaning that the parser is expecting arguments like `-I/path/to/directory` and `-isystem/path/to/directory`. For `-I` that works since cmake generates the arguments in this form. However, for `-isystem`, cmake is generating the entries in the compilation database as `-isystem /path/to/directory` (note the space between `-isystem` and the path) which is not understood by the cpptools.

The result is that all `-isystem` paths with space are still ignored which puts us into exactly the same space before. I think it would in general be a good idea to support both forms (with and without space between the flag and the path) for `-I` and `-isystem` since gcc and clang also accept them.

**Comment by sean-mcmanus** [comment] 2017-12-12 21:43
@niosHD Thanks for reporting this. We'll track this bug with https://github.com/Microsoft/vscode-cpptools/issues/1343 . I'm not sure how @bobbrow tested this change if -isystem always has the space after it...oh, looks like our test uses a hand-generated compile_commands.json without the space.

**Comment by bobbrow** [comment] 2017-12-13 19:01
I implemented the change based on my reading of the [Clang documentation](https://clang.llvm.org/docs/ClangCommandLineReference.html) which shows no space after `-isystem`.  We can support both forms though.

**Comment by sean-mcmanus** [comment] 2017-12-19 11:14
@niosHD 0.14.5 should work with -isystem now (with a space). Let us know if you hit any other issues (preferably by filing a new bug).

**Comment by niosHD** [comment] 2017-12-19 11:41
Perfect, I can confirm that the [minimal working example](https://github.com/niosHD/mwe-vscode-cpp-code-completion) works with 0.14.5 as expected. A quick test on a more complex project setup also looks promising.

@sean-mcmanus @bobbrow Thank you for the prompt fix!
