### ISSUE TITLE
IntelliSense reports problems with Windows SDK identifiers

### ISSUE THREAD

**Issue by junglie85** [microsoft/vscode-cpptools#9034] opened 2022-03-16 14:33 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 Home 21H2 Build 19044.1288
- VS Code Version:
```
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```
- C/C++ Extension Version: 1.8.4 & Extension Pack 1.1.0
- IntelliSense shows identifiers defined in the Windows SDK as having problems. `ctrl-`clicking can navigate to the relevant definition. Code compiles and runs without problem.

**Expected behavior**

Identifiers/symbols should be found and no problems reported.

**Code sample and logs**

- Configurations in `c_cpp_properties.json`

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}\\**"
            ],
            "defines": [
                "WINDOWS",
                "_DEBUG"
            ],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 16/03/2022, 14:18:43
Version: 1.8.4
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}\\**"
    ],
    "defines": [
        "WINDOWS",
        "_DEBUG"
    ],
    "compilerPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\Hostx64\\x64\\cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "windowsSdkVersion": "10.0.20348.0",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}\\**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\file.cpp ]:
    D:\file.cpp
Translation Unit Configurations:
[ D:\file.cpp ]:
    Process ID: 12408
    Memory Usage: 143 MB
    Compiler Path: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\Hostx64\x64\cl.exe
    Includes:
        C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\VC\TOOLS\MSVC\14.31.31103\INCLUDE
        C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\VC\TOOLS\MSVC\14.31.31103\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\CPPWINRT
    Defines:
        WINDOWS
        _DEBUG
        HANDMADE_WIN32=1
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 143 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 4940
```

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
```
loggingLevel: Debug
cpptools/didChangeCppProperties
Attempting to get defaults from C compiler in "compilerPath" property: 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\Hostx64\x64\cl.exe'
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\Hostx64\x64\cl.exe'
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.20348.0/CPPWINRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.20348.0/SHARED/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.20348.0/UCRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.20348.0/UM/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.20348.0/WINRT/ will be indexed
  Folder: C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2022/COMMUNITY/VC/TOOLS/MSVC/14.31.31103/ATLMFC/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2022/COMMUNITY/VC/TOOLS/MSVC/14.31.31103/INCLUDE/* will be indexed
  Folder: D:/ will be indexed
cpptools/didChangeSettings
Discovering files...
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled.
Autocomplete is enabled.
textDocument/didOpen: D:\file.cpp
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: D:\file.cpp
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.20348.0/CPPWINRT/
cpptools/getCodeActions: D:\file.cpp (id: 2)
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.20348.0/SHARED/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.20348.0/UCRT/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.20348.0/UM/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.20348.0/WINRT/
  Processing folder (non-recursive): C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2022/COMMUNITY/VC/TOOLS/MSVC/14.31.31103/ATLMFC/INCLUDE
  Processing folder (non-recursive): C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2022/COMMUNITY/VC/TOOLS/MSVC/14.31.31103/INCLUDE
  Processing folder (recursive): D:/
  Discovering files: 4940 file(s) processed
  1 file(s) removed from database
Done discovering files.
Populating include completion cache.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Checking for syntax errors: D:\file.cpp
cpptools/didChangeSettings
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled.
Autocomplete is enabled.
$/setTraceNotification
cpptools/getFoldingRanges: D:\file.cpp (id: 3)
cpptools/getSemanticTokens: D:\file.cpp (id: 4)
  tag parsing file: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\CodeAnalysis\sourceannotations.h
sending compilation args for D:\file.cpp
  include: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\VC\TOOLS\MSVC\14.31.31103\INCLUDE
  include: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\VC\TOOLS\MSVC\14.31.31103\ATLMFC\INCLUDE
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\UM
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\UCRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\SHARED
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\WINRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\CPPWINRT
  define: WINDOWS
  define: _DEBUG
  stdver: ms_c++17
  intelliSenseMode: windows-msvc-x64
Checking for syntax errors: D:\file.cpp
Queueing IntelliSense update for files in translation unit of: D:\file.cpp
cpptools/getCodeActions: D:\file.cpp (id: 5)
cpptools/getDocumentSymbols: D:\file.cpp (id: 6)
cpptools/getDocumentSymbols
cpptools/finishUpdateSquiggles
Error squiggle count: 96
Update IntelliSense time (sec): 2.044
cpptools/getFoldingRanges: D:\file.cpp (id: 7)
cpptools/getCodeActions: D:\file.cpp (id: 8)
```

**Screenshots**

![Capture](https://user-images.githubusercontent.com/17502031/158613048-bab1bc70-0863-4fce-be86-6a3750d03f0c.PNG)
![Annotation 2022-03-16 142832](https://user-images.githubusercontent.com/17502031/158613055-9e3ba648-2795-4b7e-99e9-9fbb89cf68a1.png)

**Comment by sean-mcmanus** [comment] 2022-03-16 17:47
Your source file uses `#include <Windows.h>`?

Can you try with pre-release version 1.9.3? That has some potential fixes.

**Comment by junglie85** [comment] 2022-03-16 19:45
Hi @sean-mcmanus , yes, I `#include <windows.h>`.

The pre-release version seems to have fixed. I'll give it 24 hours and if it continues to remain fixed will mark as resolved.

**Comment by sean-mcmanus** [comment] 2022-03-16 20:52
Does setting `C_Cpp.intelliSenseCacheSize` to 0 fix/workaround the issue? It sounds like macros are getting undefined for some reason. Are you able to create a simple repro case and/or can you identify what is triggering the repro?

**Comment by sean-mcmanus** [comment] 2022-03-16 20:55
This could be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6580 -- do you have any conditionally included headers?

**Comment by junglie85** [comment] 2022-03-16 21:12
I'll give that a try and will look at a repro tomorrow if it doesn't fix it.

**Comment by junglie85** [comment] 2022-03-17 10:36
I can't get a sufficiently small repro to exhibit the problem.

Setting the cache size to 0 seems to have resolved. I do get a recurrence of the problem every so often, then all the warnings disappear again. What's the implication of setting the cache size to zero permanently?

I think this might be a duplicate of #6525.

**Comment by sean-mcmanus** [comment] 2022-03-18 00:18
Setting the cache file to 0 just causes us to not generate .ipch files that have the headers parsed already -- the performance benefit of that varies. The change in performance may not even be noticeable.

I'm not sure about #6525, but another potential issue is https://github.com/microsoft/vscode-cpptools/issues/8610

**Closed as completed** 2022-05-17 11:16 UTC
Labels: Language Service, more info needed, not reproing, Feature: Configuration
