### ISSUE TITLE
Local variable Problem

### ISSUE THREAD

**Issue by Jackie-Yang** [microsoft/vscode-cpptools#420] opened 2016-12-24 09:01 UTC
Can not Hint/Go to Definition/Peek the local variable.
<img width="360" alt="2016-12-24 5 00 30" src="https://cloud.githubusercontent.com/assets/18381153/21466180/9f0256ec-c9fa-11e6-9d20-34454f7a3bd1.png">
<img width="544" alt="2016-12-24 5 00 49" src="https://cloud.githubusercontent.com/assets/18381153/21466181/a03bd90c-c9fa-11e6-9f7e-890e051cf6c1.png">

**Comment by sean-mcmanus** [comment] 2016-12-27 15:29
Yes, it's a known "by design" limitation of the current implementation that is planned to be fixed once full IntelliSense is added.

**Closed as completed by sean-mcmanus** 2016-12-27 15:29 UTC
