### ISSUE TITLE
debug line was disappeared(caused by chinese characters)

### ISSUE THREAD

**Issue by dzj0821** [microsoft/vscode-cpptools#3254] opened 2019-03-05 17:11 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Enterprise Edition
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them): none
When i use gdb to debug a program, the path which include chinese characters was displayed unknown characters. And the debug line was disappeared.

**To Reproduce**

1. Create a cpp file in a path which include chinese characters.
2. Enter some codes and create a breakpoint
3. Use MinGW to compile it and use gdb to debug the exe (i'm already prepare tasks.json and launch.json)
4. When the program running at breakpoint, a dialog was showed which text is "Can't open file "�����.cpp": Can't find file(file:///d:/����/���/�����.cpp)"
5. When i press F10 to debug it, I can't see the debug line, but the variable‘s value was already changed. (Every time i press F10, the dialog which text is can't find file will be display)

↓This is my cpp file
[中文.zip](https://github.com/Microsoft/vscode-cpptools/files/2931940/default.zip)

**Expected behavior**

show the debug line normally

**Screenshots**

![pic](https://user-images.githubusercontent.com/36768960/53823002-d068d700-3fab-11e9-976e-0be4dd70a609.jpg)
in the picture the debug line was disappeared.
**Additional context**

**Comment by WardenGnaw** [comment] 2019-03-05 19:47
This is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/602

**Closed as completed by WardenGnaw** 2019-03-05 19:47 UTC
Labels: duplicate, debugger
