### ISSUE TITLE
Auto-Complete doesn't work after struct keyword

### ISSUE THREAD

**Issue by lh123** [microsoft/vscode-cpptools#3080] opened 2019-01-24 07:40 UTC
**Type: LanguageService**
- C/C++ Extension Version: 0.21.0

```c
struct test {};

int main(void) {
    struct tes // auto complete doesn't work.
}

```

**Comment by sean-mcmanus** [comment] 2019-01-24 22:13
This is currently "by design" and how Visual Studio behaves. This changed as of 0.21.0 due to the fix for https://github.com/Microsoft/vscode-cpptools/issues/2734 . The reason is that when "struct " is used it could be a new struct declaration/definition and not a variable declaration of an existing type, so completion interferes with inputting the new type name when it completes to an existing type when Enter is used.

Would showing completion when Ctrl+Space is used (manual invoking completion) be a sufficient workaround, or did you want a setting to alter this behavior to what it was previously?

**Comment by lh123** [comment] 2019-01-25 05:13
But Ctrl + Space is only valid after struct keywork.
```c
struct test {};

int main(void) {
    struct tes^ //  Ctrl+Space invoking completion doesn't work at '^'.
    struct ^ //  Ctrl+Space invoking completion works at '^'.
}
```

**Comment by sean-mcmanus** [comment] 2019-01-25 19:56
I meant that we can fix/change it so that struct t^ would auto-complete when forced via Ctrl+Space.

**Comment by sean-mcmanus** [comment] 2019-02-07 02:20
Manually invoking completion after `"struct <text>"` works with 0.22.0-insiders. You can get it via setting the C_Cpp.updateChannel setting to "Insiders", or downloading it manually from https://github.com/Microsoft/vscode-cpptools/releases .

However, I just found a bug with it -- if there are >1000 results in your list (i.e. the list is "incomplete"), then the list will disappear with "No suggestions" after typing more. We'll try to fix that in our next update.

UPDATE: The bug when results are incomplete has been fixed for our next release.

UPDATE: That bug was fixed with the latest insiders: Should be fixed with the latest insiders: https://github.com/Microsoft/vscode-cpptools/releases .

**Closed as completed** 2019-03-21 02:40 UTC
Labels: Language Service, Feature Request, fixed, quick fix, regression
