### ISSUE TITLE
Debugger get lost on C++ source files when they have the same name but different paths (shows breakpoint set on one file as if they were set on another file) 

### ISSUE THREAD

**Issue by leogcorrea** [microsoft/vscode-cpptools#1853] opened 2018-04-19 20:52 UTC
Issue Type: <b>Bug</b>

Create a project with 2 C++ source files with the same name and extension but in different paths. I'm using the GDB as the debugger. A breakpoint set in one of the source files (/src/file.cpp) when triggered shows the breakpoint on the other one (/otherpath/src/file.cpp) as if the breakpoint was set in this second file instead of on the first one.

Extension version: 0.16.1
VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (4 x 3766)|
|Load (avg)|0, 1, 0|
|Memory (System)|15.61GB (4.31GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by WardenGnaw** [comment] 2018-04-20 23:50
If you enable engine logging via
```
"logging": {
   "engineLogging": true
}
```
Can you see if the breakpoint is being attached to /src/file.cpp or if it is being attached to /otherpath/src/file.cpp?

**Comment by ZobyTwo** [comment] 2018-05-08 09:25
I think that this is a duplicate of #977.

**Comment by pieandcakes** [comment] 2019-12-09 20:56
Duplicate of #977

**Closed as completed by pieandcakes** 2019-12-09 20:56 UTC
Labels: debugger
