### ISSUE TITLE
IntelliSense reports include-error in workspaceFolder

### ISSUE THREAD

**Issue by thecky** [microsoft/vscode-cpptools#7756] opened 2021-06-30 13:23 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version:    Linux - Arch
- VS Code Version:  1.56.2
- C/C++ Extension Version: error occours in extension version higher than 1.2.2
- Other extensions you installed (and if the issue persists after disabling them): German Language Pack for Visual Studio Code (1.56.2), PlatformIO IDE (2.3.2)

With the C/C++ Extension version 1.2.2 everything works as expected and no include errors are reported.
Changing to a newer version (1.3.0 and higher and even 1.5.0-insiders2) reports include-errors inside the workspace.
A diff for c_cpp_properties.json, launch.json, extensions.json shows no difference between the version and the include/browse paths are the same.

Maybe is it an "user-problem" - but this occours after the update and then I rollback to the extension version 1.2.2 everything is fine.

**Steps to reproduce**
Assuming this structure:

```
Folder
 |
 + include
 |       |- main.h
 |
 + src
     |- main.c
```

In main.c is a #include "main.h". Since Version 1.3.0 the include is now reported as error (error 1696 - include error, update your includepath...).
In the screenshot-sections are some images taken from 1.2.2 and 1.3.0

**Expected behavior**
No Include-Errors reports (error 1696) inside the workspaceFolder when in path

**Code sample and logs**
c_cpp_properties.json:
```
//
// !!! WARNING !!! AUTO-GENERATED FILE!
// PLEASE DO NOT MODIFY IT AND USE "platformio.ini":
// https://docs.platformio.org/page/projectconf/section_env_build.html#build-flags
//
{
    "configurations": [
        {
            "name": "PlatformIO",
            "includePath": [
                "/Daten/Projekte/IoT/Test/Test/include",
                "/Daten/Projekte/IoT/Test/Test/src",
                "/Daten/Projekte/IoT/Test/Test/.pio/build/esp32dev/config",
                <snipped - many includes from platformio>
                ""
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "path": [
                    "/Daten/Projekte/IoT/Test/Test/include",
                    "/Daten/Projekte/IoT/Test/Test/src",
                    "/Daten/Projekte/IoT/Test/Test/.pio/build/esp32dev/config",
                    <snipped - many includes from platformio>
                    ""
                ]
            },
            "defines": [
                "_GNU_SOURCE",
                "IDF_VER=\"3.40200.210118\"",
                "ESP_PLATFORM",
                "PLATFORMIO=50101",
                "ARDUINO_ESP32_DEV",
                ""
            ],
            "cStandard": "c99",
            "cppStandard": "c++11",
            "compilerPath": "/<homedir>/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc",
            "compilerArgs": [
                "-mlongcalls",
                ""
            ]
        }
    ],
    "version": 4
}
```
The platformio-includes are removed (not necessary).
As mentioned before, the json aren't changed between the versions.

**Screenshots**
This is only a simple stupid code, nothing real - only to show the difference.
As you can see in 1.2.2 there is no error and 1.3.0 (and higher) reports an error for the include outside the own folder (and the folders are in the c_cpp_properties.json).

Version 1.2.2:
![Screenshot_main_1 2 2](https://user-images.githubusercontent.com/13124415/123966585-d9b8b180-d9b5-11eb-8978-6da47bce2ed1.png)
![Screenshot_main_h_1 2 2](https://user-images.githubusercontent.com/13124415/123966748-fce36100-d9b5-11eb-9660-dd9d7399332e.png)

Version 1.3.0:
![Screenshot_main_1 3 0](https://user-images.githubusercontent.com/13124415/123966685-ef2ddb80-d9b5-11eb-9ee0-759ae38f6172.png)
![Screenshot_main_h_1 3 0](https://user-images.githubusercontent.com/13124415/123966713-f523bc80-d9b5-11eb-995a-45975b797598.png)

**Comment by thecky** [comment] 2021-06-30 14:04
After more searching the issues, it seems similar to #7701 (expect that I haven't different mountpoints) - so it's maybe a duplicate issue. In that case, please excuse.

**Comment by sean-mcmanus** [comment] 2021-06-30 18:08
Are you referencing files on a different disks or are there symlinks on the paths? If not, then it may not be a duplicate, but I'm not able to repro the issue:

![image](https://user-images.githubusercontent.com/19859882/124010162-571efa80-d993-11eb-8aee-2f7416d48b42.png)

Can you run the C/C++: Log Diagnostics command after opening main.c and make sure the "Includes" section has the "include" folder?

**Comment by thecky** [comment] 2021-07-01 08:46
Hi, thanks for your response.

No, there aren't any symlinks or different volumes.
For the 1.2.2 and 1.3.0 I ran the C/C++ Diagnostics, see below. I can see some differences between the files - for better pointing out, I created a diff.
For better reading I removed the platformio path (saves > 300 lines).
My "workspacefolder" is /Daten/Projekte/IoT/Test/Test, which ist in the sections (well, as far as I can see it).

**Version 1.2.2 (working - all fine):**
```
-------- Diagnostics - 1.7.2021, 09:18:55
Version: 1.2.2
Current Configuration:
{
    "name": "PlatformIO",
    "includePath": [
        "/Daten/Projekte/IoT/Test/Test/include",
        "/Daten/Projekte/IoT/Test/Test/src",
        "/Daten/Projekte/IoT/Test/Test/.pio/build/esp32dev/config",
        <snipped out platformio includes under ~/.platformio/packages for better reading>
    ],
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "/Daten/Projekte/IoT/Test/Test/include",
            "/Daten/Projekte/IoT/Test/Test/src",
            "/Daten/Projekte/IoT/Test/Test/.pio/build/esp32dev/config",
            <snipped out platformio includes under ~/.platformio/packages for better reading>
        ]
    },
    "defines": [
        "_GNU_SOURCE",
        "IDF_VER=\"3.40200.210118\"",
        "ESP_PLATFORM",
        "PLATFORMIO=50101",
        "ARDUINO_ESP32_DEV"
    ],
    "cStandard": "c99",
    "cppStandard": "c++11",
    "compilerPath": "/<homedir>/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc",
    "compilerArgs": [
        "-mlongcalls"
    ],
    "intelliSenseMode": "linux-gcc-arm64",
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true
}
Translation Unit Mappings:
[ /Daten/Projekte/IoT/Test/Test/src/main.c ]:
    /Daten/Projekte/IoT/Test/Test/src/main.c
Translation Unit Configurations:
[ /Daten/Projekte/IoT/Test/Test/src/main.c ]:
    Process ID: 594924
    Memory Usage: 10 MB
    Compiler Path: /<homedir>/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc
    Includes:
        /Daten/Projekte/IoT/Test/Test/include
        /Daten/Projekte/IoT/Test/Test/src
        /Daten/Projekte/IoT/Test/Test/.pio/build/esp32dev/config
        <snipped out platformio includes under ~/.platformio/packages for better reading>
    Defines:
        _GNU_SOURCE
        IDF_VER="3.40200.210118"
        ESP_PLATFORM
        PLATFORMIO=50101
        ARDUINO_ESP32_DEV
    Standard Version: c99
    IntelliSense Mode: linux-gcc-arm64
    Other Flags:
        --gcc
        --gnu_version=80400
Total Memory Usage: 10 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 3173
Number of files discovered (not excluded): 2965
```

**Version 1.3.0 ("not working"):**
```
-------- Diagnostics - 1.7.2021, 09:03:14
Version: 1.3.0
Current Configuration:
{
    "name": "PlatformIO",
    "includePath": [
        "/Daten/Projekte/IoT/Test/Test/include",
        "/Daten/Projekte/IoT/Test/Test/src",
        "/Daten/Projekte/IoT/Test/Test/.pio/build/esp32dev/config",
        <snipped out platformio includes under ~/.platformio/packages for better reading>
    ],
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "/Daten/Projekte/IoT/Test/Test/include",
            "/Daten/Projekte/IoT/Test/Test/src",
            "/Daten/Projekte/IoT/Test/Test/.pio/build/esp32dev/config",
            <snipped out platformio includes under ~/.platformio/packages for better reading>
        ]
    },
    "defines": [
        "_GNU_SOURCE",
        "IDF_VER=\"3.40200.210118\"",
        "ESP_PLATFORM",
        "PLATFORMIO=50101",
        "ARDUINO_ESP32_DEV"
    ],
    "cStandard": "c99",
    "cppStandard": "c++11",
    "compilerPath": "/<homedir>/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc",
    "compilerArgs": [
        "-mlongcalls"
    ],
    "intelliSenseMode": "linux-gcc-arm64",
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true
}
Translation Unit Mappings:
[ /Daten/Projekte/IoT/Test/Test/include/main.h ]:
    /Daten/Projekte/IoT/Test/Test/include/main.h
    /Daten/Projekte/IoT/Test/Test/include/test_inc.h
[ /Daten/Projekte/IoT/Test/Test/src/main.c ]:
    /Daten/Projekte/IoT/Test/Test/src/main.c
Translation Unit Configurations:
[ /Daten/Projekte/IoT/Test/Test/include/main.h ]:
    Process ID: 293832
    Memory Usage: 15 MB
    Compiler Path: /<homedir>/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc
    Includes:
        /Daten/Projekte/IoT/Test/Test/include
        /Daten/Projekte/IoT/Test/Test/src
        /Daten/Projekte/IoT/Test/Test/.pio/build/esp32dev/config
        <snipped out platformio includes under ~/.platformio/packages for better reading>
    Defines:
        _GNU_SOURCE
        IDF_VER="3.40200.210118"
        ESP_PLATFORM
        PLATFORMIO=50101
        ARDUINO_ESP32_DEV
    Standard Version: c++11
    IntelliSense Mode: linux-gcc-arm64
    Other Flags:
        --g++
        --gnu_version=80400
        --header_only_fallback
[ /Daten/Projekte/IoT/Test/Test/src/main.c ]:
    Process ID: 294030
    Memory Usage: 11 MB
    Compiler Path: /<homedir>/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc
    Includes:
        /Daten/Projekte/IoT/Test/Test/include
        /Daten/Projekte/IoT/Test/Test/src
        /Daten/Projekte/IoT/Test/Test/.pio/build/esp32dev/config
        <snipped out platformio includes under ~/.platformio/packages for better reading>
    Defines:
        _GNU_SOURCE
        IDF_VER="3.40200.210118"
        ESP_PLATFORM
        PLATFORMIO=50101
        ARDUINO_ESP32_DEV
    Standard Version: c99
    IntelliSense Mode: linux-gcc-arm64
    Other Flags:
        --gcc
        --gnu_version=80400
Total Memory Usage: 26 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 2965
```

**The diff between this two files:**
The maindifference that I see, is the "Translation Unit Mappings" section.

```
--- Diagnostics_1.2.2	2021-07-01 09:26:34.351983762 +0200
+++ Diagnostics_1.3.0	2021-07-01 09:16:49.925770287 +0200
@@ -1,5 +1,5 @@
--------- Diagnostics - 1.7.2021, 09:18:55
-Version: 1.2.2
+-------- Diagnostics - 1.7.2021, 09:03:14
+Version: 1.3.0
 Current Configuration:
 {
     "name": "PlatformIO",
@@ -38,12 +38,36 @@
     "compilerPathIsExplicit": true
 }
 Translation Unit Mappings:
+[ /Daten/Projekte/IoT/Test/Test/include/main.h ]:
+    /Daten/Projekte/IoT/Test/Test/include/main.h
+    /Daten/Projekte/IoT/Test/Test/include/test_inc.h
 [ /Daten/Projekte/IoT/Test/Test/src/main.c ]:
     /Daten/Projekte/IoT/Test/Test/src/main.c
 Translation Unit Configurations:
+[ /Daten/Projekte/IoT/Test/Test/include/main.h ]:
+    Process ID: 293832
+    Memory Usage: 15 MB
+    Compiler Path: /<homedir>/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc
+    Includes:
+        /Daten/Projekte/IoT/Test/Test/include
+        /Daten/Projekte/IoT/Test/Test/src
+        /Daten/Projekte/IoT/Test/Test/.pio/build/esp32dev/config
+        <snipped out platformio includes under ~/.platformio/packages for better reading>
+    Defines:
+        _GNU_SOURCE
+        IDF_VER="3.40200.210118"
+        ESP_PLATFORM
+        PLATFORMIO=50101
+        ARDUINO_ESP32_DEV
+    Standard Version: c++11
+    IntelliSense Mode: linux-gcc-arm64
+    Other Flags:
+        --g++
+        --gnu_version=80400
+        --header_only_fallback
 [ /Daten/Projekte/IoT/Test/Test/src/main.c ]:
-    Process ID: 594924
-    Memory Usage: 10 MB
+    Process ID: 294030
+    Memory Usage: 11 MB
     Compiler Path: /<homedir>/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc
     Includes:
         /Daten/Projekte/IoT/Test/Test/include
@@ -61,8 +85,7 @@
     Other Flags:
         --gcc
         --gnu_version=80400
-Total Memory Usage: 10 MB
+Total Memory Usage: 26 MB
 
 ------- Workspace parsing diagnostics -------
-Number of folders and files enumerated: 3173
 Number of files discovered (not excluded): 2965
```

**Comment by sean-mcmanus** [comment] 2021-07-01 20:36
@Colengms Any ideas? Seems like the same symptom as https://github.com/microsoft/vscode-cpptools/issues/7701 but without the 2 disks.

**Comment by Colengms** [comment] 2021-07-02 05:23
This looks like a dupe of #7701 .  It's related to the path starting with "/D" and being misrecognized as a define.  Closing as a dupe.

**Closed as completed by Colengms** 2021-07-02 05:23 UTC
Labels: bug, duplicate, Language Service, regression
