### ISSUE TITLE
no stderr with pipeTransport

### ISSUE THREAD

**Issue by hi0t** [microsoft/vscode-cpptools#7784] opened 2021-07-05 15:32 UTC
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 10 21H1 + WSL
- VS Code Version: 1.57.1 (user setup)
- C/C++ Extension Version: 1.4.1
- Other extensions you installed (and if the issue persists after disabling them): none

I am debugging my application in docker via pipeTransport. But in the debug console I see only output from the stdout. stderr is omitted.
Configuration in launch.json:
```JSON
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Debug",
			"type": "cppdbg",
			"request": "launch",
			"program": "/app",
			"cwd": "/",
			"MIMode": "gdb",
			"preLaunchTask": "prepare",
			"pipeTransport": {
				"pipeProgram": "docker",
				"pipeArgs": [
					"exec",
					"-i",
					"app",
					"bash",
					"-c"
				],
				"debuggerPath": "/usr/bin/gdb"
			},
			"setupCommands": [
				{
					"description": "Enable pretty-printing for gdb",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				}
			]
		}
	]
}
```
I found workaround, use "debuggerPath": "/usr/bin/gdb --tty /dev/pts/1". But the solution doesn't look good.
Is this a bug? Are there any other ways to redirect the stderr?

**Comment by WardenGnaw** [comment] 2021-07-06 18:52
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/7784

**Closed as completed by WardenGnaw** 2021-07-06 18:52 UTC
Labels: duplicate, debugger

**Comment by hi0t** [comment] 2021-07-06 20:36
Sorry for the duplicate. Perhaps you meant https://github.com/microsoft/vscode-cpptools/issues/5358

**Comment by WardenGnaw** [comment] 2021-07-06 21:08
@hi0t Thank you for pointing to the correct issue.
