### ISSUE TITLE
Wildcard directory name searches

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode-cpptools#849] opened 2017-06-28 00:53 UTC
The `includePath` doesn't seem to work with NuGet packages since the directory name includes the version. For example, if we use package rapidjson 1.0.2 and later upgrade, we'd have to update references to "packages/rapidjson.1.0.2/build/native/include" in this file - in additional to any packages.config files. It would be nice if we could use wildcards in directory specifiers or some other means of not having to maintain the same information in two different places.

**Comment by sean-mcmanus** [comment] 2017-06-28 05:12
I also hit this every time my VC tools version updates.

UPDATE: We added a WindowsSDKVersion setting to c_cpp_properties.json and also use the matching includes for cl.exe when set in compilerPath for a particular VC toolset. But a wildcard in general hasn't been added yet.

**Comment by anatoli26** [comment] 2019-04-08 06:13
Hi, any update on this?

**Comment by sean-mcmanus** [comment] 2019-04-09 01:53
I think Bob started a branch with a fix at https://github.com/Microsoft/vscode-cpptools/commit/37f87e7d950953c74f2dc84d5d84290194e35ddb, but there was some problem with it I think.

**Comment by bobbrow** [comment] 2019-10-17 21:56
This is a duplicate of #723

**Closed as completed by bobbrow** 2019-10-17 21:56 UTC
Labels: duplicate, Language Service, Feature Request
