### ISSUE TITLE
Include graph lookup should occur for source files as well as header files, when determining primary TU source file

### ISSUE THREAD

**Issue by Sochsenfeld** [microsoft/vscode-cpptools#12036] opened 2024-02-29 10:51 UTC
### Environment

- OS and Version: Windows_NT x64 10.0.19045
- VS Code Version: Version: 1.87.0 (user setup)
- C/C++ Extension Version: v1.19.4
- If using SSH remote, specify OS of remote machine:

### Bug Summary and Steps to Reproduce

Bug Summary: My project consists of multiple .cpp files that are all included in the main.cpp for clarity. All the libraries are also included in the main.cpp. Normally IntelliSense recognizes that the .cpp files are included in the main and then also sees the libraries. So for example IntelliSense recognized std::cout in the non main files. This suddenly stopped working once quite some time ago. I reinstalled VSC and it worked for a while but stopped working few days ago again. 
Now all the non-main.cpp files are full of IntelliSense errors even though the code compiles and runs normally. This happens also with variable declarations done in one file and used in another. 

I have written a small example code to reproduce the error:
1. Create main.cpp, file1.cpp, file2.cpp
2. Include `#include <iostream>` in main.cpp
3. Include `#include "file1.cpp"`  and then `#include "file2.cpp"` in main.cpp
4. Define `double variable=1.0;` in file1.cpp
5. Use `variable` in file2.cpp and see that IntelliSense does not recognize it
6. Use `std::cout` in file2.cpp and see that IntelliSense does not recognize it
7. Use function from file2.cpp in main.cpp and see that IntelliSense does work
8. Code compiles just fine

Expected behavior:
`variable` and `std::cout` should be recognized by Intellisense in file2.cpp because `<iostream>` is included in main.cpp.

Appended see screenshots of the testing code with errors 
![bugtest1](https://github.com/microsoft/vscode-cpptools/assets/97513607/744b921b-5046-48a4-912f-ea54d06992f2)
![bugtest2](https://github.com/microsoft/vscode-cpptools/assets/97513607/908c8f1a-e340-4a3a-ae28-6df75f8ef4d1)
![bugtest3](https://github.com/microsoft/vscode-cpptools/assets/97513607/bd42c5ae-b963-4e5b-90a9-232afb6010a7)
![bugtest4](https://github.com/microsoft/vscode-cpptools/assets/97513607/4e2f7454-8760-4fb6-a4ab-c526daa3404c)
![bugtest5](https://github.com/microsoft/vscode-cpptools/assets/97513607/e7fe4eb5-b958-4b86-bd01-2dfee2c3251f)

Additional Info: Im running C/C++ on WSL Ubuntu. But the first time this error ocurred was when I used VSC without WSL.

The `C/C++ Log Diagnostics` seems to contain info about my actual project and not the test one.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}

log diagnostics:
-------- Diagnostics - 2/28/2024, 9:26:09 PM
Version: 1.19.4
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/steoc/projects/**",
        "/usr/include/"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c17",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "/usr/bin/gcc",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "/home/steoc/projects/**",
            "/usr/include/",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.19.4.0
Translation Unit Mappings:
[ /home/steoc/projects/bugreport/src/file1.cpp - source TU]:
[ /home/steoc/projects/bugreport/src/file2.cpp - source TU]:
[ /home/steoc/projects/bugreport/src/main.cpp - source TU]:
Translation Unit Configurations:
[ /home/steoc/projects/bugreport/src/file1.cpp ]:
    Process ID: 26550
    Memory Usage: 10 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/11
        /usr/include/x86_64-linux-gnu/c++/11
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110400
[ /home/steoc/projects/bugreport/src/file2.cpp ]:
    Process ID: 26572
    Memory Usage: 11 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/11
        /usr/include/x86_64-linux-gnu/c++/11
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110400
[ /home/steoc/projects/bugreport/src/main.cpp ]:
    Process ID: 26509
    Memory Usage: 51 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/11
        /usr/include/x86_64-linux-gnu/c++/11
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110400
Total Memory Usage: 73 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 18632



language server logging:
loggingLevel: Debug
loggingLevel has changed to: Debug
LSP: (invoked) cpptools/didChangeCppProperties (id: 32)
LSP: Sending response (id: 32)
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: (received) cpptools/getCodeActions: file:///home/steoc/projects/bugreport/src/main.cpp (id: 33)
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/getCodeActions: file:///home/steoc/projects/bugreport/src/main.cpp (id: 33)
LSP: Sending response (id: 33)
LSP: (invoked) cpptools/didChangeVisibleTextEditors
Intellisense update pending for: file:///home/steoc/projects/bugreport/src/main.cpp
LSP: (received) cpptools/didChangeActiveEditor: file:///home/steoc/projects/bugreport/src/main.cpp
LSP: (received) cpptools/didChangeTextEditorSelection
LSP: (invoked) cpptools/didChangeActiveEditor: file:///home/steoc/projects/bugreport/src/main.cpp
LSP: (invoked) cpptools/didChangeTextEditorSelection
IntelliSense update scheduled and TU acquisition started for: file:///home/steoc/projects/bugreport/src/main.cpp
Update IntelliSense time (sec): 0.007
LSP: (received) cpptools/getCodeActions: file:///home/steoc/projects/bugreport/src/main.cpp (id: 34)
LSP: (invoked) cpptools/getCodeActions: file:///home/steoc/projects/bugreport/src/main.cpp (id: 34)
LSP: Sending response (id: 34)
LSP: (received) cpptools/getFoldingRanges: file:///home/steoc/projects/bugreport/src/main.cpp (id: 35)
LSP: (invoked) cpptools/getFoldingRanges: file:///home/steoc/projects/bugreport/src/main.cpp (id: 35)
LSP: Sending response (id: 35)
LSP: (received) cpptools/didChangeTextEditorSelection
LSP: (invoked) cpptools/didChangeTextEditorSelection
LSP: (received) cpptools/getCodeActions: file:///home/steoc/projects/bugreport/src/main.cpp (id: 36)
LSP: (invoked) cpptools/getCodeActions: file:///home/steoc/projects/bugreport/src/main.cpp (id: 36)
LSP: Sending response (id: 36)
LSP: (received) cpptools/getDiagnostics (id: 37)
LSP: (invoked) cpptools/getDiagnostics (id: 37)
LSP: Sending response (id: 37)
LSP: (received) cpptools/didChangeActiveEditor: file:///home/steoc/projects/bugreport/src/main.cpp
LSP: (invoked) cpptools/didChangeActiveEditor: file:///home/steoc/projects/bugreport/src/main.cpp
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: (received) cpptools/didChangeActiveEditor: file:///home/steoc/projects/bugreport/src/main.cpp
LSP: (invoked) cpptools/didChangeActiveEditor: file:///home/steoc/projects/bugreport/src/main.cpp
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
```

### Other Extensions

The C/C++ Extension package and disabling all other extensions did not resolve the error.

**Comment by sean-mcmanus** [comment] 2024-02-29 18:42
It's creating a new TU for the `#include`d .cpp files instead of using main.cpp's TU. @Colengms Do you know anything about this?

**Comment by Colengms** [comment] 2024-02-29 19:20
This is because the C/C++ Extension will currently assume that a file with a source extension such as `.cpp` can be interpreted independently, not as a header of another source file.  We could improve this for your scenario by always performing a (costly) lookup to detect this scenario, when opening any file instead of just those with header extensions.  We can use this issue to track implementing that.

**Comment by sean-mcmanus** [comment] 2024-02-29 19:54
@Colengms This is a 1.19.4 regression, i.e. it works correctly with 1.18.5. @Sochsenfeld You should be able to downgrade to 1.18.5 and it should work.

**Comment by Sochsenfeld** [comment] 2024-02-29 20:05
Amazing, thank you! That works for now!

**Comment by FrankHB** [comment] 2024-03-01 08:59
> @Colengms This is a 1.19.4 regression, i.e. it works correctly with 1.18.5. @Sochsenfeld You should be able to downgrade to 1.18.5 and it should work.

This also affects `#include MACRO_NAME` forms when the a file is included in the source (or the header file) designated by `MACRO_NAME` indirectly after macro expansion. However in this case the downgrade also does not work. The behavior is a slightly different: 1.18.5 would still generate further diagnostics about the failure on subsequent multiple `#include MACRO_NAME` lines, while 1.19.4 would only complains at the first line. Perhaps better a separate issue?

**Comment by sean-mcmanus** [comment] 2024-03-05 00:01
@Sochsenfeld @FrankHB Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.19.5

**Closed as completed by sean-mcmanus** 2024-03-05 00:01 UTC
Labels: bug, Language Service, fixed, regression, Feature: Configuration, verified, Works in VS
