### ISSUE TITLE
Windows Remote Debugger similar to standard Visual Studio.

### ISSUE THREAD

**Issue by pmaciejew** [microsoft/vscode-cpptools#10254] opened 2022-12-08 19:31 UTC
### Feature Request

It seems that remote debugging does not work with "cppvsdbg" on Windows.

With standard Visual Studio, the user is able to build binaries locally, deploy them on remote machine and debug them remotely.

VS Code is able to perform remote developing, but it always required to copy source code to target machine, which is not always desired, for example target platform can be only used for test

**Comment by WardenGnaw** [comment] 2022-12-08 19:38
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/1098

**Closed as completed by WardenGnaw** 2022-12-08 19:38 UTC
