### ISSUE TITLE
excess CPU usage

### ISSUE THREAD

**Issue by HankB** [microsoft/vscode-cpptools#822] opened 2017-06-13 13:15 UTC
VS Code 1.13.0
Linux Debian 9 (4.9.0-3-amd64 #1 SMP Debian 4.9.30-1 (2017-06-04) x86_64 GNU/Linux)
C/C++ 0.11.4 
(Other extensions installed and presently disabled.)

Open VS code and CPU shows 100% on one or two threads including /home/hbarta/.vscode/extensions/ms-vscode.cpptools-0.11.4/bin/Microsoft.VSCode.CPP.Extension.linux. After several minutes the CPU load decreases to what would be expected as normal. If VS code is exited and restarted the same problem occurs.

To provoke the problem, it is only necessary to open a C file (Hello world will do) in VS code. No other actions are required.

A bug is also filed against VS code itself for excess CPU usage (https://github.com/Microsoft/vscode/issues/28406)

**Comment by bobbrow** [comment] 2017-06-13 14:27
Thank you for reporting the issue.  The 100% you are seeing should only be for a single core and it is temporary while the extension is parsing your workspace folder and sub-folders.  There is currently a bug in the extension where much of this processing is being repeated unnecessarily on subsequent relaunches, but we have a fix in the pipeline to address that.

**Comment by HankB** [comment] 2017-06-14 11:35
It consumes one core for about 24 minutes. 
It must be doing a *lot* of parsing. This is on a laptop with an I7 processor and SATA SSD.
Due to the use of CPPunit test framework it references headers outside the directory tree. Is that causing a problem?
By comparison, a project builds and runs test cases in 2 seconds:
hbarta@yggdrasil:~/Documents/C/c-txtutil/cpputest-starter-project$ make clean
Making clean
hbarta@yggdrasil:~/Documents/C/c-txtutil/cpputest-starter-project$ time make
compiling io_CppUMockTest.cpp
compiling io_CppUMock.cpp
compiling example-explodingfakes.c
compiling AllTests.cpp
compiling ExampleTest.cpp
compiling TestDump.cpp
compiling TestLog.cpp
compiling MyFirstTest.cpp
compiling io.c
compiling dump.c
compiling logmsg.c
compiling Example.c
Building archive test-lib/libexample.a
a - test-obj/example-platform/io.o
a - test-obj/../dump.o
a - test-obj/../logmsg.o
a - test-obj/example-src/Example.o
Linking example_tests
Running example_tests
.........
OK (9 tests, 9 ran, 297 checks, 0 ignored, 0 filtered out, 1 ms)


real	0m2.003s
user	0m1.572s
sys	0m0.192s

Project can be cloned from https://github.com/HankB/c-txtutil if you wish to test with the code that provokes the issue.

**Comment by HankB** [comment] 2017-06-14 12:44
I have just found that the same version of VS code and CPP extension does not exhibit excessive CPU usage in a resource constrained environment. Please see https://github.com/Microsoft/vscode/issues/28406#issuecomment-308418966 for additional details. (If you prefer, I will copy the entire comment here.)

**Comment by HankB** [comment] 2017-06-14 15:07
On another PC Desktop) with a faster I7, more RAM and RAIDed SSDs I do not experience the excessive CPU issue so I am leaning toward the first possible cause in the previous comment (on the other issue. e.g. some residue in a file where VS code saves state that is causing a problem.)

Edit: Red herring - CPU usage on this other PC is high as well.

**Comment by bobbrow** [comment] 2017-06-29 17:14
I cloned your repo and edited the text, and I don't see any excessive CPU usage.  The folder parses in about a second for me on Windows and on Mint 18.1.  My machines have non-RAID'ed SSDs and are otherwise average.

I think I have all the sources you've referenced in your post.  Does this include path look about right?  It doesn't resolve all of the headers in all of your test folders, but it should be pulling in the most important ones.  I tried using both the "Tag Parser" and "Default" `intelliSenseEngine`s

```
            "includePath": [
                "${workspaceRoot}",
                "${workspaceRoot}/../cpputest/include",
                <system includes omitted for brevity>,

            "browse": {
                "path": [
                    "${workspaceRoot}/../cpputest/include",
                    <system includes omitted for brevity>,
```

I'm not sure what else might be going on with your machine, but I'm not seeing anything awry with the C++ extension. :/

**Comment by HankB** [comment] 2017-06-30 19:53
Hi Bob,
Thank you for trying to duplicate the problem.
I haven't bothered to set the paths inside Code since I build from the command line but what you have looks correct. Perhaps that is something I should sort out.
I think the next thing would be for me to try to debug it on my system. It looks like there is sufficient information in the project documentation to get me started.

thanks,
hank

**Comment by bobbrow** [comment] 2017-07-06 04:23
Let us know if you need any further help.  I'm going to close this issue for now since it doesn't look like there is anything else I can help you with at the moment.

**Closed as completed by bobbrow** 2017-07-06 04:23 UTC
Labels: Language Service

**Comment by ogrisel** [comment] 2017-11-17 14:15
I think I have a similar issue:

VS Code 1.18.0
Ubuntu 16.04
C/C++ 0.14.2

To reproduce, just clone https://github.com/python/cpython , open vscode in the top level folder of the repo and open a `.c` file in a tab, e.g.: `Modules/_pickle.c`.

I get a process named `Microsoft.VSCode.CPP.IntelliSense.Msvc.linux` running 100% CPU seemingly forever (and I have to kill it manually when I close the vscode window).

**Comment by ogrisel** [comment] 2017-11-17 14:18
I deleted all my user settings and the `.vscode` folder in my project to get the default configuration of vscode and the c/c++ extension and I still get the 100% CPU usage issue whenever I edit a file like `cpython/Modules/_pickle.c` in vscode under Linux.

**Comment by bobbrow** [comment] 2017-11-17 17:06
@ogrisel, can you please create a new issue for your case and we will gladly look into it?  Your issue looks different than @HankB's issue.

**Comment by ogrisel** [comment] 2017-11-29 15:14
@bobbrow done here: #1294

**Comment by nico87** [comment] 2017-12-13 21:40
I'm having the same problem here, but the suggested solution did not work.
