### ISSUE TITLE
Comment continuation pattern of '/*` and '*' doesn't work after the 2nd line

### ISSUE THREAD

**Issue by jiudianren** [microsoft/vscode-cpptools#9577] opened 2022-07-13 08:44 UTC
### Feature Request

C_Cpp.commentContiniutionPatterns how to define comment like this
```
/*
*  a=0;
*  b=0;
*/
```
every line has a "*" at the start ,for comment code block.
i  think this a little product demand。

**Comment by Colengms** [comment] 2022-07-13 19:02
Hi @jiudianren .  Thanks for providing this feature request.  It's actually unclear to me why a simple "/*" is not supported, or why the space added on the new line is not configurable.

**Comment by jiudianren** [comment] 2022-07-14 01:28
Are there any instructions on configuring this requirement? Tks

**Comment by sean-mcmanus** [comment] 2022-07-14 21:02
It's supposed to work via:
```json
"C_Cpp.commentContinuationPatterns": [
    {
        "begin": "/*",
        "continue": " *"
    }
]
```
but it's buggy and stop working after the 2nd line.

The code is at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/languageConfig.ts if anyone wants to try to debug/fix it.

**Comment by sean-mcmanus** [comment] 2022-07-14 21:09
Actually, this is a duplicate of the existing issue: https://github.com/microsoft/vscode-cpptools/issues/8998

**Closed as not planned by sean-mcmanus** 2022-07-14 21:09 UTC
Labels: bug, Language Service, help wanted
