### ISSUE TITLE
"Activating extension ms-vscode.cpptools failed due to an error"

### ISSUE THREAD

**Issue by janhaa** [microsoft/vscode-cpptools#6209] opened 2020-09-25 08:19 UTC
Type: General

Hi,
since version 1.0 the extension does not function for me properly anymore.
!!! **Downgrading to 0.29.0 fixes it** !!!

**Describe the bug**
- OS and Version: Windows 10 Pro
- VS Code Version: 1.49.2
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them): ESLint, Vetur, Arduino - yes issue persists
- A clear and concise description of what the bug is: Extension not loading.

**To Reproduce**
1. Install "ms-vscode.cpptools" extension
2. Notice that it won't load

**Expected behavior**
The extension to load.

**Additional context**
Log of extension host:
```
[2020-09-25 10:08:31.848] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/.vscode/extensions/ms-vscode.cpptools-1.0.1/dist/main
[2020-09-25 10:08:31.849] [exthost] [error] Activating extension ms-vscode.cpptools failed due to an error:
[2020-09-25 10:08:31.850] [exthost] [error] Error: Cannot find module 'c:\Users\xxx\.vscode\extensions\ms-vscode.cpptools-1.0.1\dist\main'
```

Trying to build manually (Node 12.18.4):
```
$ npm run compile

> cpptools@1.0.1 compile C:\Users\xxx\.vscode\extensions\ms-vscode.cpptools-1.0.1
> node ./tools/prepublish.js && gulp generate-native-strings && gulp translations-generate && webpack --mode production --vscode-nls

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\xxx\.vscode\extensions\ms-vscode.cpptools-1.0.1\tools\prepublish.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cpptools@1.0.1 compile: `node ./tools/prepublish.js && gulp generate-native-strings && gulp translations-generate && webpack --mode production --vscode-nls`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cpptools@1.0.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-09-25T08_09_50_503Z-debug.log
```

**Comment by michelleangela** [comment] 2020-09-25 18:56
@janhaa 
Could you tell us more on how you installed version 1.0 of the extension? Was it through automatic update or manual install of offline package? Have you tried a complete uninstall and re-install?

**Comment by janhaa** [comment] 2020-09-28 08:32
@michelleangela I tried all the ways. The initial update was through automatic update though I think.

**Comment by sean-mcmanus** [comment] 2020-09-29 00:18
Unfortunately, we don't know how to repro this and we don't know what could be causing it. If you want to try debugging it yourself to get more info, you could do a `git clone https://github.com/microsoft/vscode-cpptools.git`, "checkout release", open the vscode-cpptools\Extension folder and do Start Debugging with the "Launch Extension (development)" config.

**Comment by janhaa** [comment] 2020-09-29 09:36
@sean-mcmanus I will come back to you once I'm back in office.

**Comment by michelleangela** [comment] 2020-12-09 19:22
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide any new information.

**Closed as completed by michelleangela** 2020-12-09 19:22 UTC
Labels: more info needed
