### ISSUE TITLE
C_Cpp.clang_format_fallbackStyle in WSL not using windows config

### ISSUE THREAD

**Issue by Emergency1999** [microsoft/vscode-cpptools#6771] opened 2021-01-13 14:22 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu WSL on Windows10
- VS Code Version: 1.52.1
- C/C++ Extension Version: v1.1.3
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: WSL
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I have my formatterstyle set to "{ BasedOnStyle: Google, IndentWidth: 4, ColumnLimit: 0}",
which works fine when I'm working with local files, but when I connect to my Ubuntu WSL, the default style formatter is used.
![image](https://user-images.githubusercontent.com/37804385/104460595-98227e80-55ae-11eb-9a1c-2902035a8527.png)
When I am connected to WSL, this is displayed in settings.json

**Workaround**

open remote settings for WSL and configure C_Cpp.clang_format_fallbackStyle again
or configure it using the directory .vscode/settings.json.

**Steps to reproduce**

1. install Ubuntu WSL and vscode on windows
2. install and configure "C/C++" and "Remote - WSL" extension.
3. connect to WSL and install "C/C++" in WSL as well
4. try to format a document, it will use the default and not the one specified in the local settings.json

**Expected behavior**

It should just use the style I have configured in Windows.

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment] 2021-01-14 00:41
That is "by design". It's a machine local setting. You need to set those formatting settings in your remote, workspace, or workspace folder settings. Does that fix your issue?

**Comment by Emergency1999** [comment] 2021-01-19 01:20
As I said: I found this "Fix" already and wonder why this is the default setting?

**Comment by sean-mcmanus** [comment] 2021-01-20 22:58
The reason is because the local and remote machines may have different versions of clang-format and one version may not support the same style values, which would cause clang-format to fail. It's sort of a design trade off. It's possible we could reconsider/change that later. We haven't gotten much feedback yet.

**Comment by Colengms** [comment] 2021-01-21 23:35
Closing issue as 'by design'.

**Closed as completed by Colengms** 2021-01-21 23:35 UTC
Labels: Language Service, by design, Feature: Code Formatting
