### ISSUE TITLE
Debug stopped: Unexpected token { in JSON at position 8. Stopping the debug adapter.

### ISSUE THREAD

**Issue by stanf0rd** [microsoft/vscode-cpptools#1681] opened 2018-03-13 12:28 UTC
- Extension Name: cpptools
- Extension Version: 0.15.0
- OS Version: Linux x64 4.15.0-10-generic (Ubuntu 18.04-beta)
- VSCode version: 1.20.0, 1.21.0, 1.22.0-beta

Steps to Reproduce:

1. Install VSC
2. Install ms-vscode.cpptools
3. Create launch.json
4. Compile your program (no matter how)
5. Press F5

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 870)|
|Load (avg)|0, 0, 1|
|Memory (System)|15.55GB (9.89GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0

</details>

<details>
<summary>debug activation log</summary>

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 121,
		"activateCallTime": 9,
		"activateResolvedTime": 775,
		"activationEvent": "onLanguage:cpp"
	}
}
``` 

</details>

**Comment by pieandcakes** [comment] 2018-03-14 18:31
Thank you for reporting the issue. This is a duplicate of #1348. We are still trying to get a repro in-house so we can debug and figure out what is happening.

**Closed as completed** 2018-03-14 18:31 UTC
Labels: duplicate, debugger

**Comment by stanf0rd** [comment] 2018-03-15 21:15
@pieandcakes I receive this error every time I try to run debug, even after reinstalling vscode, gdb and g++. If I could help somehow, just write me. I'm really interested in this being fixed.
