### ISSUE TITLE
cpp_tool can not show the expand-macro correctly

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#8508] opened 2021-12-09 12:49 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: win10
- VS Code Version: 1.63/1.64-insider
- C/C++ Extension Version: 1.8.0-insider2

1. cpp-tools can not show the expend-macro
![image](https://user-images.githubusercontent.com/1876302/145399092-6c748cfd-b631-4315-892d-fcd1cf936ba1.png)

2. cpp goto wrong position(goto define)(right position is line 711)

![c++_bug](https://user-images.githubusercontent.com/1876302/145398893-911a0de3-e806-4778-ae1c-bf27ff4d9332.gif)

（it works before I reset cpp database of workspace）
![image](https://user-images.githubusercontent.com/1876302/145399153-d46d5206-3ada-4750-ac5e-4f2caa22f8b8.png)

**Steps to reproduce**

1. reset cpp tool database of workspace

**Expected behavior**

**Comment by Colengms** [comment] 2021-12-09 20:41
Hi @heartacker .  I'm having a difficult time understanding the scenario and what the expected result is.  Can you extract just the macros involved in the repro into a code example that we might use to investigate further?

**Comment by heartacker** [comment] 2021-12-10 03:20
@Colengms sorry
and what I mean is:
1. hover information do not show the origin value
e.g.
```c
#define _A 0
#define _B 1

#define AB  _A, _B
```
what we need in hover is that we should see: `AB` expand to `0, 1` but cpp_tool just show me that   `AB` expand to `_A, _B`

**Comment by heartacker** [comment] 2021-12-10 03:25
QUESTION 2 is:
the define is in line 711
but we press F12 
it goes to line 351, that is wrong position
![](https://user-images.githubusercontent.com/1876302/145398893-911a0de3-e806-4778-ae1c-bf27ff4d9332.gif)

**Comment by heartacker** [comment] 2021-12-10 03:47
I found that the intelligence mode will impact the hover information

![image](https://user-images.githubusercontent.com/1876302/145513957-2ce756b5-783e-4704-a48e-841d663d03e2.png)

![image](https://user-images.githubusercontent.com/1876302/145513972-f94bf7a4-b806-4745-970b-87d82dfcef1a.png)

**Comment by sean-mcmanus** [comment] 2021-12-13 17:07
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4970 . The reason it works for msvc mode is that the preprocessor used in that is a non-conformant to the C++ standard (it fails again if /Zc:preprocessor is used with msvc mode).

**Closed by sean-mcmanus** 2021-12-13 17:07 UTC
Labels: Language Service, more info needed

**Comment by heartacker** [comment] 2021-12-14 14:53
> QUESTION 2 is: the define is in line 711 
>![image](https://user-images.githubusercontent.com/1876302/145512268-81c47ccb-3791-40f8-be53-d2da54212961.png)
> 
> but we press F12
> ![image](https://user-images.githubusercontent.com/1876302/145512309-48fd7829-8505-47f6-a2d1-4d375ba373e5.png)
> 
> it goes to line 351, that is wrong position
> ![](https://user-images.githubusercontent.com/1876302/145398893-911a0de3-e806-4778-ae1c-bf27ff4d9332.gif)

@sean-mcmanus  is this same root cause?

**Comment by sean-mcmanus** [comment] 2021-12-14 17:35
The Go to Definition issue is a different issue -- do you have any more repro info?

**Comment by heartacker** [comment] 2021-12-15 02:28
> The Go to Definition issue is a different issue -- do you have any more repro info?

I found that the intelligence mode will ALSO impact the `Go to Definition` maybe that is same cause

**Comment by sean-mcmanus** [comment] 2023-02-03 02:53
The recursive macro expansion issue is fixed with 1.14.1 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.1
