### ISSUE TITLE
Macro autocomplete from local variable in header

### ISSUE THREAD

**Issue by omerbguclu** [microsoft/vscode-cpptools#4662] opened 2019-11-26 10:15 UTC
Hey,

As I say in title, auto completion at macros does not work.
![a](https://user-images.githubusercontent.com/28712312/69620393-5fdc7b80-104e-11ea-917c-8fc7c373237b.png)
![b](https://user-images.githubusercontent.com/28712312/69620396-623ed580-104e-11ea-8165-2a82b55ca752.png)
![c](https://user-images.githubusercontent.com/28712312/69620414-6834b680-104e-11ea-8982-36448889e1d9.png)
![d](https://user-images.githubusercontent.com/28712312/69620420-6965e380-104e-11ea-87c3-06355d017293.png)

But it works at everywhere except macros. Is this is a bug or expected behavior ?

**Comment by sean-mcmanus** [comment] 2019-11-26 19:28
This is somewhat "by design" or an oversight in design. VS doesn't auto-invoke completion in the `#define` case because it's likely the user is defining something new, but allows manual invoking of completion, which our extension doesn't implement. So we'll track this as a feature request.

**Comment by YalandHong** [comment] 2020-09-11 02:00
I think it is (at least partial) duplicate of #3927

**Comment by sean-mcmanus** [comment] 2022-05-18 21:20
This should be fixed with 1.10.2 (pre-release).

**Closed as completed** 2022-06-08 21:57 UTC
Labels: bug, Language Service, fixed, quick fix, Feature: Auto-complete, Works in VS
