### ISSUE TITLE
cpptools not showing in extensions manager

### ISSUE THREAD

**Issue by riri** [microsoft/vscode-cpptools#7365] opened 2021-04-15 12:20 UTC
Bug type: General

**Describe the bug**
- OS and Version: Archlinux (Linux 5.11.13-arch1-1)
- VS Code Version:1.54.3
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):

I make a fresh install of VScode and want to add C/C++ extension (I had it before I clean up everything).
All my common extensions are visible (git graph, gitlens, golang-pls, etc...) but not C/C++.

![extension not showing](https://i.imgur.com/CT1uNG9.png)

**Comment by michelleangela** [comment] 2021-04-15 16:55
@riri 
The view from the screenshot looks like the search result of the **Extensions Marketplace**. What does the view look like when the search box is empty?

If the search box for searching the Extensions Marketplace is empty, it should show a view of which extensions are installed under the "INSTALLED" collapsible list.
![image](https://user-images.githubusercontent.com/38734287/114907729-39002000-9dd0-11eb-89d5-fd9e73cb0766.png)

Also, was the extension disabled somehow per User or Workspace scope?

**Comment by riri** [comment] 2021-04-15 18:05
@michelleangela 
Yes that's that case

![searchbox empty](https://i.imgur.com/l9zbIEl.png)

And no, the extension was not disabled (I am on a fresh install), and anyway it would show up as disabled in the installed list.

**Comment by michelleangela** [comment] 2021-04-15 18:47
That is strange. Could you check the extension's install path`~/.vscode/extensions` and see if there is a folder for the C++ extension? The extension's folder name should be something like `ms-vscode.cpptools-1.3.0` for version 1.3.0. If it's not installed, could you try installing it manually using one of our VSIX (https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0) compatible for your platform, then see if it shows up under the Extensions Manger panel?

Also, I see your VS Code version is 1.54.3. Could you try updating it the latest 1.55.2 as well?

**Comment by riri** [comment] 2021-04-15 19:12
I checked the folder already, and it contained only the 3 extensions I loaded.

I downloaded the release manually and used the vsix command, it worked. The extension installed correctly.

For vscode itself, I install from the Archlinux packages repository, and 1.54.3 is not packaged yet. It's more convenient for me.
So, the extension is installed, but that does not explain why it did not show up in the extension manager :)

**Comment by michelleangela** [comment] 2021-04-15 19:40
>I checked the folder already, and it contained only the 3 extensions I loaded.

The Extensions Manger will only show extensions under "installed" list if they're found under folder `~/.vscode/extensions`. After you manually installed C++ extension, when you say "it worked" do you mean it showed up under the "installed" list on Extensions Manger after it was manually installed? 

>So, the extension is installed, but that does not explain why it did not show up in the extension manager :)

Just to clarify my understanding:
- First issue is, the extension didn't show up under "installed" when it wasn't installed, but it showed up under "installed" after it was installed?
- Second issue is, the extension didn't show up under the search results of Extension Marketplace when "c++" search word was used? There could be a platform dependency here. @sean-mcmanus do you have any insights to this?

**Comment by sean-mcmanus** [comment] 2021-04-15 21:15
Yeah, our C/C++ extension isn't published in https://open-vsx.org/ . We are only licensed to be run in VS Code and not other distros. This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6388 .

**Closed as completed by sean-mcmanus** 2021-04-15 21:15 UTC
Labels: duplicate, more info needed
