### ISSUE TITLE
Integrated terminal is sh instead of gnome-terminal (Linux Mint)

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-cpptools#1553] opened 2018-02-13 22:48 UTC
_From @zbendefy on February 13, 2018 11:15_

Hi!
I use Linux Mint 18.3 (64bit cinnamon), and I Updated from 1.19 to 1.20.0.
Previously the integrated terminal used the gnome-terminal, but now since 1.20 it uses the sh terminal.

This causes C++ debugging to be unavailable since the debugger cannot start with the sh terminal (I get the error message: **Unable to start debugging. No terminal is available to launch the debugger. Please install Gnome Terminal or XTerm)**

_Copied from original issue: Microsoft/vscode#43578_

**Comment by weinand** [comment] 2018-02-13 22:48
_From @Tyriar on February 13, 2018 14:28_

@zbendefy did you used to get gnome-terminal pop up in another window when you started debugging?

**Comment by weinand** [comment] 2018-02-13 22:48
_From @zbendefy on February 13, 2018 15:50_

No, it did not pop up, only the error message. Previously (on 1.19) it popped up though. 
Also if I run "gnome-terminal" in my regular linux terminal, then it works, and a new terminal window opens.

**Comment by bobbrow** [comment] 2018-02-13 23:14
duplicate of #1550

**Closed as completed by bobbrow** 2018-02-13 23:14 UTC
