### ISSUE TITLE
change "." to "->" automatically

### ISSUE THREAD

**Issue by nxyd** [microsoft/vscode-cpptools#3105] opened 2019-01-27 13:53 UTC
When i type a variable that is a pointer, then i type ".", and is it possible to change to "->" automatically?

**Comment by starkblitz** [comment] 2019-01-28 07:09
I would definitely want this feature!

**Comment by sean-mcmanus** [comment] 2019-01-28 20:15
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/862 . Please upvote that issue.

**Closed as completed by sean-mcmanus** 2019-01-28 20:15 UTC
Labels: duplicate, Language Service, Feature Request

**Comment by sean-mcmanus** [comment] 2020-07-16 20:05
Fixed with 0.29.0.
