### ISSUE TITLE
Autosave & Formatter cause resource busy or locked hang

### ISSUE THREAD

**Issue by sleutho** [microsoft/vscode-cpptools#1224] opened 2017-11-09 12:09 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
matlab|Gim|0.7.1
cpptools|ms-|0.14.0
vscode-icons|rob|7.17.0
tcl|sle|0.2.0
perforce|sle|2.2.2
---

Steps to Reproduce:

1. "files.autoSave": "onFocusChange",
    "editor.formatOnSave": true,
    "C_Cpp.clang_format_style": "file",
    "C_Cpp.formatting": "Default",
    "C_Cpp.clang_format_sortIncludes": true,
    "C_Cpp.intelliSenseEngine": "Default",
2. Edit the file and cause an autoformat+save via focuschange or delay
3. The file wont save, and I see an EBUSY error. 
4. The file will not save anymore forever.
5. I have to kill Microsoft.VSCode.CPP.IntelliSense.Msvc.exe in my taskmanager and the file will save again. I do that umpteen times a day. Recently it started to happen with almost every file. A month ago it happened once a week.

![2017-11-09](https://user-images.githubusercontent.com/1581639/32604796-f14828b4-c51c-11e7-91e6-9984d2ede2e1.png)

**Comment by bobbrow** [comment] 2017-11-09 16:44
We have a fix for this coming out today if our CDN will cooperate.  (duplicate of #1040)

**Closed as completed by bobbrow** 2017-11-09 16:44 UTC
Labels: duplicate, Language Service
