### ISSUE TITLE
Update extension to insider version in remote SSH

### ISSUE THREAD

**Issue by nxyd** [microsoft/vscode-cpptools#4053] opened 2019-08-09 06:02 UTC
Set the update channel to Insider in remote settings is useless.

**Comment by yamcenutzer** [comment] 2019-08-09 12:28
same here.
using mostly remote ssh to linux machines.
the update channel setting seems to be ignored.

Interestingly, the native vscode version installed on these linux machines do update and the extension is actually doing something when used locally.

**Comment by bobbrow** [comment] 2019-08-09 15:04
Thank you for reporting this issue.  This is actually a duplicate of #3833.  If you could go add a 👍 to that issue, it helps us track the most impactful bugs.

**Closed as completed by bobbrow** 2019-08-09 15:04 UTC
Labels: bug, duplicate, Language Service
