### ISSUE TITLE
Syntax highlighting issue when explicitly specifying return type for C++ lambda function.

### ISSUE THREAD

**Issue by JorgeIba** [microsoft/vscode-cpptools#11137] opened 2023-06-27 23:34 UTC
### Environment

- OS and Version: Windows 11
- VS Code Version: 1.79.2 (user setup)
- C/C++ Extension Version: v1.16.3

### Bug Summary and Steps to Reproduce

Bug Summary:
I am experiencing a syntax highlighting issue when explicitly specifying the return type for a C++ lambda function. When I include the return type in my lambda function, the colors of the words in my code editor change to a default color scheme. However, if I remove the return type and leave it as an auto-deduced return type, the words are colored correctly. It compiles correctly, is only a highlighting issue.

I wrote the example code:

```cpp
#include<iostream>

using namespace std;

int main () {

    auto fun = [](int param_1, int param_2)->bool{
        int sum = param_1 + param_2;

        if(sum > 10){
            sum -= 10;
        }

        return sum == 0;
    };

    cout << fun(5, 5) << endl;

	return 0;
}
```

Behavior when return type is explicitly specified:

![image](https://github.com/microsoft/vscode-cpptools/assets/39895741/c8fbe0f8-3dc4-4276-9819-153832a70004)

Behavior when is not specified:

![image](https://github.com/microsoft/vscode-cpptools/assets/39895741/73bf8974-4b2d-402e-900a-5bf9221e48bb)

### Configuration and Logs

```shell
-------- Diagnostics - 6/27/2023, 5:33:11 PM
Version: 1.16.3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:\\c++64kit\\bin\\gcc.exe",
    "cStandard": "c17",
    "intelliSenseMode": "windows-gcc-x64",
    "compilerPathInCppPropertiesJson": "C:\\c++64kit\\bin\\gcc.exe",
    "cppStandard": "c++17",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": true,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.16.3.0
Translation Unit Mappings:
[ C:\Users\jorge\OneDrive\Escritorio\test.cpp ]:
    C:\Users\jorge\OneDrive\Escritorio\test.cpp
Translation Unit Configurations:
[ C:\Users\jorge\OneDrive\Escritorio\test.cpp ]:
    Process ID: 16888
    Memory Usage: 111 MB
    Compiler Path: C:\c++64kit\bin\gcc.exe
    Includes:
        C:\c++64kit\lib\gcc\x86_64-w64-mingw32\11.2.0\include\c++
        C:\c++64kit\lib\gcc\x86_64-w64-mingw32\11.2.0\include\c++\x86_64-w64-mingw32
        C:\c++64kit\lib\gcc\x86_64-w64-mingw32\11.2.0\include\c++\backward
        C:\c++64kit\lib\gcc\x86_64-w64-mingw32\11.2.0\include
        C:\c++64kit\lib\gcc\x86_64-w64-mingw32\11.2.0\include-fixed
        C:\c++64kit\x86_64-w64-mingw32\include
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++17
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110200
Total Memory Usage: 111 MB

------- Workspace parsing diagnostics -------
```
```


### Other Extensions

_No response_

### Additional context

_No response_

**Comment by sean-mcmanus** [comment] 2023-06-28 00:11
This is a duplicate of https://github.com/jeff-hykin/better-cpp-syntax/issues/405 (which is where VS gets its syntax highlighting from, not our extension).

**Closed as not planned by sean-mcmanus** 2023-06-28 00:11 UTC
Labels: duplicate, Language Service, external, Feature: Colorization
