### ISSUE TITLE
User snippets suggestions on variable declaration

### ISSUE THREAD

**Issue by nunojsa** [microsoft/vscode-cpptools#4626] opened 2019-11-18 09:25 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux (Arch and Ubuntu)
- VS Code Version: 1.40.0
- C/C++ Extension Version: 0.26.2-insiders
- Other extensions you installed (and if the issue persists after disabling them): Still happens when disabled

  * CMake

  - Docker

  - Devicetree

  - Indent to bracket

  - Markdown

**To Reproduce**

1. Define a user snippet
2. Define a variable with the same prefix as the snippet

**Expected behavior**
No snippet suggestion on variable declaration

After defining my user snippets I'm receiving suggestion for it on variable declarations that start with the same letter of the snippet prefix which can be annoying. This also makes unusable the `ctrl  + space` binding for manually sugestions (which is useful for `structs`). I can say that this does  not happen with the official extension snippets so it can be a problem with my definitions. Here they are:

```
        "For": {
		"prefix": ["for"],
		"body": ["for (int ${idx} = 0; ${idx} < ${size}; ${idx}++) {",
			"\t$0",
			"}"
		],
		"description": "For loop template"
	},
	"If": {
		"prefix": ["if"],
		"body": ["if (${expr}) {",
			"\t$0",
			"}"
		],
		"description": "if clause template"
	},
	"Else": {
		"prefix": ["else"],
		"body": ["else {",
			"\t$0",
			"}"
		],
		"description": "else clause template"
	},
	"ElseIf": {
		"prefix": ["else if"],
		"body": ["else if (${expr}) {",
			"\t$0",
			"}"
		],
		"description": "else if clause template"
	},
	"while": {
		"prefix": ["while"],
		"body": ["while (${expr}) {",
			"\t$0",
			"}"
		],
		"description": "while loop template"
	},
	"do": {
		"prefix": ["do"],
		"body": ["do {",
			"\t$0",
			"} while (${expr});"
		],
		"description": "do while loop template"
	},
	"switch": {
		"prefix": ["switch"],
		"body": ["switch (${expr}) {",
			"case ${case_1}:",
			"\t",
			"default:",
			"\t$0return ${error};",
			"}"
		],
		"description": "switch case template"
	},
```
I can also say that I tried some other extensions defining their own snippets and the problem still occurred. As a workaround, I just disabled my snippets for now

Honestly I'm not sure if this the right place to submit the issue (and not directly on code) so I apologize if it's not. Any help would be appreciated!

Thanks!

**Screenshots**

![image](https://user-images.githubusercontent.com/28741857/69040001-566b6780-09ed-11ea-882c-3c4a739ea481.png)

**Comment by sean-mcmanus** [comment] 2019-11-18 22:21
Our internal snippets has access to our lexer so it can use that info to avoid showing snippets in invalid cases such as in variable declarations. The base VS Code snippet functionality doesn't have access to this language info. I believe once we expose a way for users to edit/modify the snippets we expose then this would fix your issue: see https://github.com/microsoft/vscode-cpptools/issues/3556 .

**Comment by nunojsa** [comment] 2019-11-19 08:26
I see.

> I believe once we expose a way for users to edit/modify the snippets we expose then this would fix your issue

Definitely. That was my first approach before writing my own snippets, since I just want do slight variations of what the internal snippets are doing already. Hopefully, this comes soon to the extension...

Thanks for your reply!

**Comment by bobbrow** [comment] 2020-02-06 22:48
Closing issue as duplicate of #3556

**Closed as completed by bobbrow** 2020-02-06 22:48 UTC
Labels: duplicate, Language Service, Feature: Auto-complete
