### ISSUE TITLE
Autocomplete does not work properly after the operator in the 'C' file.

### ISSUE THREAD

**Issue by lh123** [microsoft/vscode-cpptools#2923] opened 2018-12-13 14:23 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Archlinux

**To Reproduce**
```c
struct test {
    int a;
};

int main(void) {
    struct test t1, t2;
    int a = t1.a + t2. // After typing "t2.", Intellisense does not list the members of test.
}

```

**Comment by sean-mcmanus** [comment] 2018-12-13 22:03
This is a duplicate of bug https://github.com/Microsoft/vscode-cpptools/issues/2184 .

Please upvote the issue at https://developercommunity.visualstudio.com/content/problem/407956/cc-intellisense-no-member-list-appears-after-typin.html if you want them to fix this. We had filed a bug with them internally 5 months ago, but they've been too busy to investigate it.

**Closed as completed** 2018-12-27 21:38 UTC
Labels: bug, duplicate, Language Service, parser

**Comment by sean-mcmanus** [comment] 2020-09-02 00:58
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 .
