### ISSUE TITLE
IntelliSense not working (declaration peeks, etc) and other poor experiences

### ISSUE THREAD

**Issue by GabeAl** [microsoft/vscode-cpptools#1043] opened 2017-09-18 17:28 UTC
Linux x64 CentOS 7.4. Code v1.16.1. C/C++ 0.12.4

Bunch of issues here. 
1. The install instructions don't work. They must be out of date, because the Microsoft C/C++ extension does not show up with Ctrl+P and "ext install cpptools". 
2. Finally got it working by loading a C file and waiting for the context bar at the top to suggest an install, which I performed, then restarted. Why the need to restart twice (since the second time it had to pull in more stuff)?
3. Auto-complete of words I already typed works, but the program is completely unaware of what a function is, etc, and shows no knowledge of the api, parameters expected, etc. My files are properly syntax highlighted and end in the .c extension. 
4. Library functions are not recognized. "malloc(" shows no tool-tips as it does in Notepad++. Double-clicking and trying to "peek" does nothing -- no error, no message, nothing. Silent failure is not a good thing. 

I understand that this is a very early beta release, but it would be good to address these user experience aspects, as I can't get one of the "big features" working.

**Comment by GabeAl** [comment] 2017-09-18 17:45
I see 3 and 4 may be related to another bug. #19 

It's immediately shocking and suspicious that RHEL, CentOS, Scientific Linux, Ubuntu 12.04, etc are not supported. What sort of Linux industry/school environment is this software applicable to, then? Microsoft of all folks should know a thing or two about traditional large institutions' tendencies to prefer "vintage" software stacks... And upgrading is often not an option even if you do have control over your software stack. The Xeon Phi coprocessor, for instance, requires RHEL/CentOS/other distros with glibc <= 2.17. 

The other rough edges still apply to this ticket, but without support of huge major Linux distros, they pale in comparison.

**Comment by bobbrow** [comment] 2017-09-19 21:16
1. Which instructions are you referring to?  I seem to recall seeing `ext install cpptools` on the marketplace page at one point, but I don't see it anymore.  That command seems to invoke a search now rather than installing a specific extension.  VS Code must have changed something on us.  If you can share the URL of the instructions you found, we can get this updated.
2. The first reload is required by VS Code and the second one is from the extension since we need to modify some elements of the package after VS Code loads our extension. We are looking for ways to remove the extra reload requirement, but haven't found a way out of it yet.

You are correct about 3 and 4.  We plan to support additional distros in the future, but the relative lack of interest in our extension from the distros you cite means that the priority of that backlog item has been low relative to other bugs and features impacting more users.  We'd love to make everything work for everyone today, but we're a small team and have to make hard decisions about what we can and cannot support in the near future.

**Comment by yamcenutzer** [comment] 2017-09-21 17:45
how did vscode itself manage to overcome the glibc issue then?
IIRC the editor itself satrted out with the similar requirement of glibc >=2.18, but that got resolved quite some time ago.

..and Redhat/Centos 7.3 are the currently upto date versions, and not exactly uncommon.

At least mention the requirements somewhere on the top page so that everyone knows to save time trying to get this to run on those OSes

**Comment by sean-mcmanus** [comment] 2017-09-21 18:04
@yamcenutzer I think they build on RHEL7. They have a lower 2.15 requirement. Yeah, updating our docs about the supported OS's would be good.

**Comment by GabeAl** [comment] 2017-09-28 21:41
![image](https://user-images.githubusercontent.com/8050438/30991588-3ccb2930-a46b-11e7-8294-b68d08e3a143.png)
Have you tried going to the main link on Linux? ;-) (A jerk thing of me to say, but to appreciate the irony in a post about Linux support...)

2 cents about the "lack of interest" -- judging lack of interest by the app's telemetry itself is flawed when users (like me, actually) are told by friends and co-workers and classes that "it doesn't work on our machines, don't try it." or simply "It's Microsoft, how could you expect it to talk to Linux?" and other decisive-sounding shoot-downs. The app can't capture that. :) Only the rambunctious non-conformists (ahem!) would even try it after hearing that. :) 

If folks were instead simply told without bias or warning by their friends and peers "here are some neat apps, try them" and had to find out for themselves each and every time that it didn't work, sure, that'd be reflected in the telemetry, but the social component of demand otherwise remains uncaptured. After all, you'd have to be a pretty poor friend to refer someone to something you know doesn't work right. (Right?)

**Comment by bobbrow** [comment] 2017-09-28 22:05
That's fair.

**Comment by sean-mcmanus** [comment] 2017-09-28 22:08
What is the "main link on Linux"? I agree that telemetry will scew the unsupported platforms lower. However, we already have a large number of users on Linux with the other distros of Linux, and the amount of complaints on this GitHub page about lack of support for those OS's matches the 3-4% we're seeing in telemetry. We decided to primarily focus on improving the experience for the 94% of users who are on supported platforms.

As I mentioned in another issue, our code won't compile without glibc 2.18 because we use thread_local with objects with non-trivial destructors so we have to re-write the code, possibly using some pthread APIs (not sure if other changes would be needed as well). I think we do intend to eventually fix this...just not sure when yet.

**Comment by GabeAl** [comment] 2017-09-28 22:37
As shown in the image above, it's the standard marketplace page all the others link to: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools 

Of course the number of failure reports would match the telemetry! How could folks write a bug report if they didn't try it? The point was, most folks (and institutions like schools to their CS students) tell others to stay away from software that doesn't work on their system, so telemetry has no way of picking up on this. People are less likely to try a piece of software if it isn't recommended to them...and much less likely when it is explicitly billed as "not working." It's obvious given this that all the people avoiding it aren't going to go posting issues on GitHub. I was warned but came anyway -- I'm the _exception_, not the rule. :)

As for the code dependencies, is statically compiling/linking the necessary glibc objects not an option? I make almost all my linux binaries *completely* static so they work everywhere, but here I'm just talking about statically linking the one big crutch, glibc.

**Comment by sean-mcmanus** [comment] 2017-09-29 01:14
@GabeAl If you could point us to any source of data that shows significantly greater usage by unsupported OS's that would help us give this more priority. We haven't figured out how to get glibc to be statically linked. We've tried using the static flags, but it just keeps adding the dynamic flags and we get various errors that suggests our external dependencies require dynamic linking. Our build system is complicated and involves multiple cmake projects.

**Comment by sean-mcmanus** [comment] 2017-11-28 02:59
This issue appears to a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/19 , and the language service processes should run on CentOS (and other 64-bit OS's) in our next 0.14.4 update. Let us know if there was some other issue that is still not addressed.

**Closed as completed by sean-mcmanus** 2017-11-28 02:59 UTC
Labels: Language Service, Feature Request, fixed, docs

**Comment by sean-mcmanus** [comment] 2017-12-12 01:29
Fixed with 0.14.4.
