### ISSUE TITLE
c/c++ extension eating CPU , os x 

### ISSUE THREAD

**Issue by chauvoluuhuong** [microsoft/vscode-cpptools#1288] opened 2017-11-27 01:13 UTC
Hi !, 
i using Mac OS (HIGH SIERRA version)
why it consumption too many CPU ? .When i trace through activity tool, it using 99% CPU all most time .How can i de-sersion it ???
Thanks

**Comment by bobbrow** [comment] 2017-11-27 16:48
If you hover over this icon, do you see any progress being made?

![image](https://user-images.githubusercontent.com/12818240/33278128-6c503f34-d34f-11e7-9529-9afb9433ee84.png)

It is expected that we use one core to index your workspace so that code navigation works.  This should be a finite operation.  If it continues for too long we would like to know more about your workspace.

You also have the option to pause the indexing thread by clicking on the icon above and choosing to "Pause Parsing" .

**Comment by jyavenard** [comment] 2017-12-07 12:52
I experience the issue.

 Microsoft.VSCode.CPP.Extension.darwin	99.9	18:59.76	25	0	87155	jyavenard	64 bit	0 bytes	0 bytes	0	0	0 bytes	0 bytes		0 bytes	0 bytes	0 bytes		-	No	0 bytes	0 bytes	No	No		0 bytes	No	No	

Project is made of 235696 files, I guess it could be restarting everytime some changes is made on the tree.

It has been like this for quite a while (which rarely bother me as this work machine has lots of cores)

**Comment by sean-mcmanus** [comment] 2017-12-07 22:20
@jyavenard You should be able to track the progress via hovering over the database icon in the bottom right. It'll reparse individual files that are changed, but it shouldn't restart the scan unless there's a dependent config/setting change.

**Comment by techwiz2100** [comment] 2017-12-12 21:17
I'm also having this issue on Windows 10... the progress resets every time I perform a search against the whole project so whatever indexing process is happening never finishes. Pretty annoying that 30-50% of my CPU is being consumed at any given point while Code is running. That being said, my project is fairly large, Code detects 65k files and the repo is 3GB+ in size. Also, it would seem that hitting "Pause Parsing" does nothing, the process continues chewing CPU cycles.

If there's anything I can do to help debug the issue, I'd be glad to help.

**Comment by sean-mcmanus** [comment] 2017-12-12 21:50
@techwiz2100 Can you check if the database is being reset in size? We rescan on workspace loading to look for changes, but only reparse if the database is corrupted or there's a changing requiring a reparse. Pausing parsing works for me. If it's not working, it probably means the main thread is stuck and is not receiving the command, or you're in a multi-root workspace and are switching files that belong to different workspaces, causing unpausing.

**Comment by techwiz2100** [comment] 2017-12-13 12:45
@sean-mcmanus I absolutely can, where does Code put the database? I don't see anything in the .vscode dir in my workspace. I only have the one top-level folder in my workspace so I don't think it's the multi-root issue, however my workspace *is* on a different disk than my Code installation. Also, should Code be re-indexing my workspace every time it starts up? It's almost like my Code workspace has no concept of persistence.

**Comment by techwiz2100** [comment] 2017-12-13 16:16
Just an update, I set out to leave Code alone to do it's thing when I made my last comment and 3 hours later, it has just finished parsing/indexing.

I think I found the databases at %APPDATA%\Code\User\ and I think both the DB-shm and DB-wal files get nuked on shutdown. The .DB file doesn't get nuked, but I still see Code re-indexing/parsing on startup. DB is about 800MB and the search function doesn't seem to make any use of it what-so-ever. Code will still use ripgrep to manually grep all the files, which is both slow and kinda dumb.

On the upside, restarting Code made the pause parsing function work again... so that's pretty nice.

**Comment by sean-mcmanus** [comment] 2017-12-13 21:04
Yes, you located the workspace storage location (default database location). The DB-shm and DB-wal files are temporary and are supposed to go away. If the database file itself is not reset to a 0 size, then it's behaving as intended. We re-scan the browse.path on startup to look for any files with a newer timestamp, but there should not be any parsing being done (the status message of "Parsing files:" is misleading, and we intend to refactor the code so it only shows that when there's actual parsing work being done). The scanning should finish a lot faster than the when the database needs to be rebuilt. There are known changes we intend to make to make the scanning faster. We're also open to other ideas to improve the experience, such as not scanning as much, or adding a setting to make it only "on demand".

**Comment by techwiz2100** [comment] 2017-12-13 21:33
@sean-mcmanus Thanks for the update, however Code was still chewing on my CPU and was definitely not just "looking for any files with newer timestamps," so I think there may be a bug there. Surely it wouldn't take hours to perform such a simple task. I didn't let it finish, but it was progressing at roughly the same rate as the original build.

**Comment by sean-mcmanus** [comment] 2017-12-13 23:46
@techwiz2100 Yes, I'm seeing a performance problem that we need to investigate (speed using the database only increases by 50%), so it's a slow rate of 75 files per second, but for a project with tens of thousands of files, this is only a matter of minutes to process and not hours. Do you have >100k files?

**Comment by techwiz2100** [comment] 2017-12-14 19:10
@sean-mcmanus ~50k files according to windows explorer and it does take hours, not minutes. If there's anything I can do to help debug, I'm all ears.

Also another thing to consider, do symlinks and/or junctions have an impact on the parsing and indexing process?

**Comment by sean-mcmanus** [comment] 2017-12-14 23:46
@techwiz2100 50k files should probably be taking 11 minutes or so to scan (still too long). Symlinks might be causing an issue. You can temporarily set your C_Cpp.loggingLevel to "6" which will output all the files that are being scanned to see if it's doing unnecessary work (in the C/C++ output window). Do you see any bugs in that output? But be sure to get rid of the setting when you're done, because it slows stuff down.

**Comment by techwiz2100** [comment] 2017-12-15 20:05
@sean-mcmanus Wow, you weren't kidding... turning on logging crushed Code. I don't see anything odd in the logs but it just seems to be taking a very long time to compare all the timestamps of the files. So, here's a suggestion... Windows Explorer allows searching for files based on date modified timestamp. Maybe there's an API that could be leveraged here to find all files in the workspace that have been modified since the last time the project was opened. We can easily and safely assume that a file that was not touched/modified since the last time the project was opened has not changed. I expect Linux and OS X have similar facilities that could be leveraged to enhance performance on those platforms as well.

https://msdn.microsoft.com/en-us/library/windows/desktop/aa965362(v=vs.85).aspx
https://stackoverflow.com/questions/16085958/scripts-find-the-files-have-been-changed-in-last-24-hours
https://www.howtogeek.com/219157/how-to-easily-view-recently-modified-files-in-windows/

**Comment by sean-mcmanus** [comment] 2017-12-23 02:00
Our 0.13.1 update introduced a huge performance regression as a result of a bug fix. The performance issue will be fixed in our next update early January. I'm seeing performance gains of 3 times faster with no database and 12 times faster with a database existing, e.g. 30 seconds instead of 6 minutes (potentially higher for projects with a large complicated include graph). I'm investigating further potential performance improvements as well.

**Comment by sean-mcmanus** [comment] 2018-01-09 22:59
We have a pre-release with the fix if you want to try it out (https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.14.6-insiders) and let us know if there are any fixes we should make before our release next week.

You should notice that the database icon says "Discovering files" and it should run a little faster, but now the Parsing phase should be completely eliminated if the database has already been built so it should be an order of magnitude faster; otherwise, it'll parse files at 50% CPU usage by default, but the status number is actually accurate now (the max number of files to parse will increase as it search #include for more files to parse) -- you can change that to 100% if you don't mind or 25% if that's still too much by changing the workspaceParsingPriority. Parsing of open files still happens at 100% CPU so that symbols are available, so the background parsing is mostly for finding lower priority workspace symbols. We made major changes to the code, so be on the look out for any regressions related to missing symbols.

**Comment by techwiz2100** [comment] 2018-01-11 22:31
Sorry, been a bit busy as of late. I'll take a look tomorrow and let you know if this resolves my indexing issues.
Thanks.

**Comment by techwiz2100** [comment] 2018-01-12 15:20
Finally got around to playing with the new updates and man, the improvements are night and day. I'm not using 0.14.6, but Code did update itself to 1.19.2 and the C/C++ extension to 0.14.5. As long as 0.14.6 is as performant as .5, I'm happy. Kudos to the team working on this.

**Comment by sean-mcmanus** [comment] 2018-01-12 20:17
@techwiz2100 Oh, that's odd. Maybe you were hitting a different issue caused by VS Code then, or your previous VS Code was older than 1.17, since our latest extension version requires that. Usually the VS Code version doesn't impact our extension's performance.

**Comment by techwiz2100** [comment] 2018-01-13 00:14
I had just installed VS Code not too long before first commenting on this bug, which was about early December. I think that puts it at version 1.19 according to this page (https://code.visualstudio.com/updates/v1_19).

Code still chews on the CPU, but it stays under 35% now and finishes up it's tasks within an hour. I think there's still some room for improvement... How do I install the pre-release? Is there an option within code?

**Comment by sean-mcmanus** [comment] 2018-01-13 00:36
@techwiz2100 Just download the Windows vsix at https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.14.6-insiders (the offline or online one) and do an Install Extension from VSIX command in VS. But before doing that, you'll want to do a Close Folder, and then uninstall the existing extension version. Ideally, VS Code would have a better way to do this, but they're still working on adding betas to the marketplace.

**Comment by sean-mcmanus** [comment] 2018-01-17 23:17
Should be fixed in our latest release: https://github.com/Microsoft/vscode-cpptools/releases/latest . If your database already exists, the CPU usage should drop to 0% within seconds, i.e. the database icon should disappear, but the red flame (intellisense parsing of the open file) might take longer. The parsing status in the bottom right when hovering should be accurate now too. You can reduce the CPU usage of this background processing via changing the C_Cpp.workspaceParsingPriority.

**Closed as completed by sean-mcmanus** 2018-01-17 23:17 UTC
Labels: bug, Language Service, fixed
