### ISSUE TITLE
Issues with WSL and Intellisense highlighting (0.29)

### ISSUE THREAD

**Issue by poltamtamis** [microsoft/vscode-cpptools#5724] opened 2020-07-03 13:01 UTC
Hello, I'm crossposting this from the VSCode GitHub Repo, I had posted about this issue a while ago and I was told that on 0.29 it should be fixed. This is the issue https://github.com/microsoft/vscode/issues/98531#issue-624402155

I'm currently on 0.29 Insiders but the highlighting still doesn't properly work on VScode. Without Remote Host and running VScode normally the highlighting seems to work fine still, but the WSL Behavior is the same as before.

**Comment by Colengms** [comment] 2020-07-06 18:08
This is a dupe of https://github.com/microsoft/vscode-cpptools/issues/3942 .  We expect the next insiders (0.29.0-insiders2) will contain the fix, which is to switch from our own custom semantic highlighting solution to using VS Code's new Semantic Tokens API.

**Closed as completed by Colengms** 2020-07-06 18:08 UTC
Labels: duplicate, Language Service, Feature: Colorization
