### ISSUE TITLE
Active file is reset with no custom configuration when reconfigured by `updateCustomConfigurations`

### ISSUE THREAD

**Issue by stroan** [microsoft/vscode-cpptools#8974] opened 2022-03-05 02:39 UTC
Bug type: Language Service

- OS and Version: Windows 10 or 11 host w/ Ubuntu 20.04 in local devcontainer
- VS Code Version: 1.65.0
- C/C++ Extension Version: 1.8.4
- Other extensions you installed (and if the issue persists after disabling them): ms-vscode.cmake-tools
- OS of remote machine: Ubuntu 20.04 in devcontainer

I am having an issue where after using cmake-tools for a short period (changing target, regenerating build files, running and debugging, closing and opening the dev environment), vscode starts reporting the following on a random file:

```
#include errors detected based on information provided by the configurationProvider setting. Squiggles are disabled for this translation unit 
cannot open source file "X.h"
```

This was also reported here I think: https://github.com/microsoft/vscode-cmake-tools/issues/1621, but I believe the bug lies in cpptools. I've attached the extension debug logs from the point where the bug starts: [c_cpp.log.txt](https://github.com/microsoft/vscode-cpptools/files/8189639/c_cpp.log.txt)

Changing cmake settings triggers `updateCustomConfigurations` in the language server client, which calls `provideCustomConfiguration` for all tracked files. The logs show the custom configurations received for all the opened files, except one. Having debugged the ms-vscode.cmake-tools side the request never arrives for the configuration for the broken file. On the cpptools side, all the tracked files do have `provideCustomConfiguration` invoked against them. The file that's broken ends up erroring out on this case: https://github.com/microsoft/vscode-cpptools/blob/5f888eef3062dd2f0c053ab27067b154abd89394/Extension/src/LanguageServer/client.ts#L1974. The QueryTranslationUnitSourceResult reports no candidates, and so it never requests the custom configuration from the provider. I haven't found any series of actions that gets the editor out of this state.

**Steps to reproduce**
1. Launch the following in a devcontainer: https://github.com/stroan/cpptoolsbug
2. Open a few of the source files.
3. Cause updateCustomConfigurations to be triggered by cmake-tools a bunch. Build, regenerate cmake files. switch build target, switch variant, run the tests with the ctest button. disconnect from the container and reconnect. I've had this repro on multiple machines everytime, after a few minutes of poking.
4. Observe that one of the files starts reporting an error on the first include.

**Expected behavior**
It doesn't break

**Code sample and logs**
Code sample: https://github.com/stroan/cpptoolsbug
Logs: [c_cpp.log.txt](https://github.com/microsoft/vscode-cpptools/files/8189639/c_cpp.log.txt)
Diagnostics: 
[c_cpp_diagnostics.txt](https://github.com/microsoft/vscode-cpptools/files/8189835/c_cpp_diagnostics.txt)

**Comment by Colengms** [comment] 2022-03-07 23:17
Hi @stroan .  I think you're encoutering a race condition related to re-opening a file that had been open previously (successfully associated with a custom configuration), while CMake Tools is in the process of reconfiguring the project and has cleared out cached custom configurations.

The only time QueryTranslationUnitSource returns an empty result is when a custom configuration has already been received for that file, and no new configuration needs to be requested.  However, after that check and before the opening of that file could be completely processed, it appears that CMake Tools had started to reconfigure the project.  That process involves first clearing all cached custom configurations previously received from CMake Tools.  Due to the async nature of these operations, the events can potentially occur in the following order:

 - The file being opened is seen to already have a cache custom configuration.
 - Cached custom configurations are cleared.
 - The file being opened is passed off to the native process, where the custom configuration is no longer found, so the file is configured based on the base-configuration in `c_cpp_properties.json`.

I suspect this scenario is pretty rare, as the timing needs to be just right (er, wrong).  It would be possible to correct the issue by closing the file, waiting several seconds for its TU to expire, and re-opening the file.  Or, the issue could be avoided by waiting to open files until CMake Tools is has completed its configuration process.

We can use this issue to track prevent the race condition.  That would seem to require deferring processing of `updateCustomConfigurations()` between the check for a custom configuration for the file and queuing up a didOpen for that file to the native process.  I suspect the reconfiguration is currently slipping through between those calls, due to use of async.

**Comment by stroan** [comment] 2022-03-07 23:26
Cheers for the quick response. That explaination makes sense. To hopefully add some weight to your theory, after reproing again here I closed the erroring file, waited a bit, and reopened the file, and the error had resolved.

Thanks for the workaround for now :)

**Comment by stroan** [comment] 2022-03-07 23:31
Though, reading a bit more closely. The files have been open for a decent period (at least 10s of seconds) when this repros, so unless the race is between re-opening the file for processing by an open editor (?), it may be a race between updateCustomConfigurations and something else.

**Comment by Colengms** [comment] 2022-03-08 00:31
Hi @stroan .  I think you're right, there is more going on here.  In the log you provided, I see the following sequence of events:

>cpptools/clearCustomConfigurations
>Shutting down IntelliSense server: /opt/workspace/examples/basic/basic.cpp
>...
>sending compilation args for /opt/workspace/examples/basic/basic.cpp
>...
>cpptools/queryTranslationUnitSource: /opt/workspace/examples/basic/basic.cpp (id: 33)

QueryTranslationUnitSource will also return no candidates if there is already a TU existing for that file.  In this case, it looks like we're clearing the TU's, then creating a TU for basic.cpp before queryTranslationUnitSource occurs for some reason.

**Comment by Colengms** [comment] 2022-03-08 01:00
Now I think this issue is because: when `updateCustomConfigurations` clears configurations, that triggers a reset of the TU for the 'active' file.  Unlike when opening a new file, that TU reset does not trigger a new request for its custom configuration.  When `updateCustomConfigurations` then tries to update that file's custom configuration, the result of `QueryTranslationUnitSource` implies that a custom configuration is unnecessary (as there is already a TU for that file).  This only happens when the TU reset completes more quickly than its new custom configuration can be pushed.

Thanks for helping us uncover this.  It seems to have been this way for a while.

**Comment by stroan** [comment] 2022-03-08 01:08
That definitely sounds closer to the mark, since it also explains why I only ever see a single file manifest the error.

Thanks for taking the time to look in to the report, hopefully the info can help get the issue resolved :)

**Comment by Colengms** [comment] 2022-03-10 00:22
Hi @stroan .  Could you confirm whether this issue was successfully resolved with 1.9.3?

**Closed as completed** 2022-03-10 01:39 UTC
Labels: bug, Language Service, fixed, Feature: Configuration

**Comment by stroan** [comment] 2022-03-10 01:42
Ah, the debugger is attaching, but it's unable to set breakpoints

**Comment by sean-mcmanus** [comment] 2022-03-10 01:42
@stroan That is not expected (and it sounds like a serious regression)...not sure if it's a known issue or not @WardenGnaw might know.

**Comment by sean-mcmanus** [comment] 2022-03-10 01:43
@stroan 1.9.3 has an updated debugger (other previous 1.9.x versions had updated debuggers as well).

**Comment by sean-mcmanus** [comment] 2022-03-10 01:55
@stroan I'm not able to repro the issue on Windows with vsdbg or Linux with cppdbg, so if you can file a bug with more repro info that would be good. See the comment at https://github.com/microsoft/vscode-cpptools/issues/8959#issuecomment-1057366036

**Comment by Colengms** [comment] 2022-03-10 02:05
@stroan @sean-mcmanus Using the provided 'cpptoolsbug' repro (with Dev Container), I was also unable to easily repro the issue with 1.9.3.  I put a breakpoint in `/opt/workspace/examples/basic/basic.cpp`, and it was hit when launched.  I was able to add and remove breakpoints with running as well.

**Comment by stroan** [comment] 2022-03-10 02:17
Looks like a false alarm. I deleted my user state in %USERPROFILE%/AppData/Roaming/Code, recreated the container, and breakpoints are working happily again. It definitely did reproduce locally for me consistently, even through a container rebuild, so I must have had some local user state that was tripping it up.
