### ISSUE TITLE
autopopulated search for "cppdbg" has no results on the extensions marketplace

### ISSUE THREAD

**Issue by briaguya0** [microsoft/vscode-cpptools#8798] opened 2022-02-07 21:24 UTC
Bug type: General

**Describe the bug**
- OS and Version: debian sid,
- VS Code Version: 1.64.0 (snap)
- A clear and concise description of what the bug is
  - autopopulated search for "cppdbg" has no results on the extensions marketplace

**To Reproduce**
1. Do *not* have [vscode-cpptools](https://github.com/Microsoft/vscode-cpptools) installed
2. Open a project with a launch.json that includes a configuration of type "cppdbg"
3. Try running/debugging
4. See this message `Configured debug type 'cppdbg' is not supported`
![Screenshot from 2022-02-05 08-26-06](https://user-images.githubusercontent.com/70942617/152644356-13256556-6276-4480-bf24-df36622329fb.png)
5. Click the "Install cppdbg Extension" button
![Screenshot from 2022-02-05 08-27-08](https://user-images.githubusercontent.com/70942617/152644374-76c92be2-91a4-421b-8240-3f82d5efbd18.png)
6. see no results
![Screenshot from 2022-02-05 08-27-38](https://user-images.githubusercontent.com/70942617/152644419-70625672-e82a-41ea-960b-ac539363ec31.png)

**Expected behavior**
this extension shows up in the marketplace search results

originally created as https://github.com/microsoft/vscode/issues/142279

**Comment by sean-mcmanus** [comment] 2022-02-07 21:41
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/8023 -- see that issue for more info.

**Closed as completed by sean-mcmanus** 2022-02-07 21:41 UTC
Labels: duplicate
