### ISSUE TITLE
breadcrumbs does not show symbol path when cursor is in function body

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode-cpptools#2401] opened 2018-08-14 05:02 UTC
Type: LanguageService

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.26
- C/C++ Extension Version: 0.17.7
- A clear and concise description of what the bug is.

VSCode 1.26 adds a nice feature called `breadcrumbs` which shows the file and symbol paths in the editor. However, for C++ source files, the symbol path is only shown when the cursor is on the line of function definition. If the cursor is moved inside a function body, the symbol path disappears while the function names shown in the bottom status bar is correct.

![image](https://user-images.githubusercontent.com/4662568/44072543-0604d0b0-9fc2-11e8-83f1-2f8b96a38c8e.png)

![image](https://user-images.githubusercontent.com/4662568/44072557-1c7d0d80-9fc2-11e8-9e59-ce0ff712efd5.png)

**Comment by sean-mcmanus** [comment] 2018-08-14 13:43
Hmm...our extension doesn't do any special handling of breadcrumbs. This is related to the Outline features -- we don't handle the new Symbol API that associates symbols with a scope (i.e. we don't return DocumentSymbols described at https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md , we just return the SymbolInformation, without a range).

**Comment by sean-mcmanus** [comment] 2018-08-15 11:58
I'm closing this as a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/2230 . When we add support for returning the DocumentSymbols we'll make sure the breadcrumbs also work correctly.

**Closed as completed by sean-mcmanus** 2018-08-15 11:58 UTC
Labels: duplicate, Language Service, Feature Request
