### ISSUE TITLE
想要一个跟virtual stdio IDE 的热键 'Alt+6'呼出的内存窗口的功能.

### ISSUE THREAD

**Issue by legal-username** [microsoft/vscode-cpptools#6744] opened 2021-01-06 11:45 UTC
Type: Debugger
功能: 查看指定内存地址数据的窗口

之前我都是使用 -exec p/x *addr@count 或者 -exec x/120xb addr, 但是使用起来不方便, 想要一个virtual stdio IDE  'Alt+6'热键呼出的内存窗口

**Comment by WardenGnaw** [comment] 2021-01-06 19:19
Translated:
> Type: Debugger
Function: View the window of the specified memory address data

> I used -exec p/x *addr@count or -exec x/120xb addr before, but it is not convenient to use, I want a virtual stdio IDE'Alt+6' hotkey to call out the memory window


Duplicate of: https://github.com/microsoft/vscode-cpptools/issues/509

**Closed as completed by WardenGnaw** 2021-01-06 19:19 UTC
Labels: duplicate, debugger
