### ISSUE TITLE
CPPTools fails to query clang++ (ndk)

### ISSUE THREAD

**Issue by thunderstorm010** [microsoft/vscode-cpptools#7519] opened 2021-05-13 18:35 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 20H2 (19042)
- VS Code Version: 1.56.1
- C/C++ Extension Version: 1.3.1
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
IntelliSense fails to query the clang++ compiler from NDK. This results on IntelliSense falling back to win32 and cl.exe. I've also opened an [issue](https://github.com/microsoft/vscode-cmake-tools/issues/1851) in CMake Tools Repo.
Because of this, there are squiggles under android system includes.

**Expected behavior**
No red squiggles under android system includes.

**Logs**
https://gist.github.com/thunderstorm010/fcf90394f7da1c3feb18b11d4ca671b7
https://gist.github.com/thunderstorm010/a25ed5e3a49935d685ef90385e5716bf

**Comment by Colengms** [comment] 2021-05-13 19:01
Hi @thunderstorm010 .  I'm seeing the following in your log output:

```
clang++: error: unsupported option '-fPIC' for target 'x86_64-w64-windows-gnu'
```

The command line it was attempting to run at the time was:

```
"q:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe" -g -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wformat -Werror=format-security -O0 -fno-limit-debug-info -fPIC -std=gnu++20 -g -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wformat -Werror=format-security -O0 -fno-limit-debug-info -fPIC --sysroot=Q:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -Wp,-v -E -dD -x c++  -fno-blocks nul
```

Since we do not add -`fPIC` when querying the compiler, the issue would seem to be due either to this being an invalid arg, or because another arg needs to be included (that was perhaps omitted from the command line by the C/C++ extension) which modifies how other args are interpreted.  Or, perhaps due to the order of those args.

Could you confirm that you're able to build despite using this arg?  If so, could you compare the command line above with the command line generated by your build, and let us know the differences?  (` -Wp,-v -E -dD -x c++  -fno-blocks nul` is being added by us).

**Comment by thunderstorm010** [comment] 2021-05-13 19:16
I can build the project as usual with no errors using Ninja.

**Comment by Colengms** [comment] 2021-05-13 19:29
@thunderstorm010 I assume because your project targets android that you are not intending to compile for `x86_64-w64-windows-gnu`.  Could you enable verbose output for CMake and provide one of your compile command lines?  A compile command line from `compile_commands.json` would also work.  Perhaps an arg that controls the target used by the compiler is being omitted by the compiler query.  Seeing a working compile command line for your project should clarify.

**Comment by searingarrows** [comment] 2021-05-14 07:37
I had the same issue and temporally fixed it by removing all "-Wa,--noexecstack" options in my compile_commands.json.

The logs are as follows (I don't know how to make it in English).

```
cpptools/didChangeCppProperties
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
正在使用命令行查询默认 C++ 语言标准的编译器: "C:\\LLVM\\bin\\gcc.exe" -x c++ -E -dM nul
检测到的语言标准版本: gnu++14
正在使用命令行查询默认 C 语言标准的编译器: "C:\\LLVM\\bin\\gcc.exe" -x c -E -dM nul
检测到的语言标准版本: gnu11
正在使用命令行查询编译器的目标:“C:\LLVM\bin\gcc.exe”-dumpmachine
编译器返回的默认目标值: x86_64-w64-mingw32

编译器查询命令行: "C:\\LLVM\\bin\\gcc.exe" -std=c99 -Wp,-v -E -dD -x c -m64  nul
已初始化代码浏览服务
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
编译器查询命令行: "C:\\LLVM\\bin\\gcc.exe" -std=c++17 -Wp,-v -E -dD -x c++ -m64  nul
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在使用命令行查询默认 C++ 语言标准的编译器: "D:\\Setup\\AndroidSDK\\ndk\\20.0.5594570\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" -x c++ -E -dM nul
检测到的语言标准版本: c++14
正在使用命令行查询默认 C 语言标准的编译器: "D:\\Setup\\AndroidSDK\\ndk\\20.0.5594570\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" -x c -E -dM nul
检测到的语言标准版本: c11
正在使用命令行查询编译器的目标:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”-dumpmachine
编译器返回的默认目标值: x86_64-w64-windows-gnu

编译器查询命令行: "D:\\Setup\\AndroidSDK\\ndk\\20.0.5594570\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" --target=armv7-none-linux-androideabi24 --gcc-toolchain=D:/Setup/AndroidSDK/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/Setup/AndroidSDK/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -Wall -g -Werror -fvisibility=hidden -fvisibility-inlines-hidden -O2 -std=c++17 -Oz -fPIC  -Wp,-v -E -dD -x c++  -fno-blocks nul
clang++: error: argument unused during compilation: '-Wa,--noexecstack' [-Werror,-Wunused-command-line-argument]

正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
编译器查询命令行: "C:\\LLVM\\bin\\gcc.exe" --target=armv7-none-linux-androideabi24 --gcc-toolchain=D:/Setup/AndroidSDK/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/Setup/AndroidSDK/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -Wall -g -Werror -fvisibility=hidden -fvisibility-inlines-hidden -O2 -std=c++17 -Oz -fPIC  -Wp,-v -E -dD -x c++   nul
gcc.exe: error: unrecognized command line option '--target=armv7-none-linux-androideabi24'
gcc.exe: error: unrecognized command line option '--gcc-toolchain=D:/Setup/AndroidSDK/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64'
gcc.exe: error: unrecognized command line option '-fno-addrsig'; did you mean '-Wno-address'?
gcc.exe: error: unrecognized command line option '-mthumb'; did you mean '-mtbm'?

未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
正在尝试从 compile_commands.json 文件中的 C++ 编译器获取默认值:“D:\Setup\AndroidSDK\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe”
正在尝试从计算机上找到的编译器获取默认值:“C:\LLVM\bin\gcc.exe”
未找到合适的编译器。请在 c_cpp_properties.json 中设置 "compilerPath"。
  文件夹 C:/LLVM/LIB/GCC/X86_64-W64-MINGW32/7.3.0/INCLUDE/ 将编入索引
  文件夹 C:/LLVM/LIB/GCC/X86_64-W64-MINGW32/7.3.0/INCLUDE-FIXED/ 将编入索引
  文件夹 C:/LLVM/X86_64-W64-MINGW32/INCLUDE/ 将编入索引
  文件夹 D:/WORKSET/IRIS/OUT/RELEASE/SDK/C/INCLUDE/ 将编入索引
  文件夹 D:/WORKSET/IRIS/SDK/UNITY/UNITYCUSTOMSURFACE/PLUGIN/SRC/MAIN/NATIVE/ 将编入索引
textDocument/didOpen: file:///d%3A/WorkSet/iris/sdk/unity/UnityCustomSurface/plugin/src/main/native/unity/provider/display/SinglePassRenderer.cpp
填充包含完成缓存。
正在发现文件...
cpptools/activeDocumentChange: file:///d%3A/WorkSet/iris/sdk/unity/UnityCustomSurface/plugin/src/main/native/unity/provider/display/SinglePassRenderer.cpp
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///d%3A/WorkSet/iris/sdk/unity/UnityCustomSurface/plugin/src/main/native/unity/provider/display/SinglePassRenderer.cpp (id: 2)
cpptools/getCodeActions: file:///d%3A/WorkSet/iris/sdk/unity/UnityCustomSurface/plugin/src/main/native/unity/provider/display/SinglePassRenderer.cpp (id: 3)
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: file:///d%3A/WorkSet/iris/sdk/unity/UnityCustomSurface/plugin/src/main/native/unity/provider/display/SinglePassRenderer.cpp (id: 4)
cpptools/getSemanticTokens: file:///d%3A/WorkSet/iris/sdk/unity/UnityCustomSurface/plugin/src/main/native/unity/provider/display/SinglePassRenderer.cpp (id: 5)
  正在处理文件夹(递归): C:/LLVM/LIB/GCC/X86_64-W64-MINGW32/7.3.0/INCLUDE/
正在为 D:\WORKSET\IRIS\SDK\UNITY\UNITYCUSTOMSURFACE\PLUGIN\SRC\MAIN\NATIVE\UNITY\PROVIDER\DISPLAY\SINGLEPASSRENDERER.CPP 发送编译参数
  包括: D:\WORKSET\IRIS\OUT\RELEASE\SDK\C\INCLUDE
  包括: D:\WORKSET\IRIS\SDK\UNITY\UNITYCUSTOMSURFACE\PLUGIN\SRC\MAIN\NATIVE\UNITY\INCLUDE
  定义: XRWindowNativeLibrary_EXPORTS
  定义: ANDROID
  定义: NDEBUG
  其他: --clang
  其他: --clang_version=100000
  stdver: c++17
  intelliSenseMode: windows-clang-x64
正在检查语法错误: file:///d%3A/WorkSet/iris/sdk/unity/UnityCustomSurface/plugin/src/main/native/unity/provider/display/SinglePassRenderer.cpp
  正在处理文件夹(递归): C:/LLVM/LIB/GCC/X86_64-W64-MINGW32/7.3.0/INCLUDE-FIXED/
正在为以下项的翻译单元中文件的 IntelliSense 更新进行排队: D:\WORKSET\IRIS\SDK\UNITY\UNITYCUSTOMSURFACE\PLUGIN\SRC\MAIN\NATIVE\UNITY\PROVIDER\DISPLAY\SINGLEPASSRENDERER.CPP
  正在处理文件夹(递归): C:/LLVM/X86_64-W64-MINGW32/INCLUDE/
  正在处理文件夹(递归): D:/WORKSET/IRIS/OUT/RELEASE/SDK/C/INCLUDE/
  正在处理文件夹(递归): D:/WORKSET/IRIS/SDK/UNITY/UNITYCUSTOMSURFACE/PLUGIN/SRC/MAIN/NATIVE/
  正在发现文件: 已处理 2502 个文件
  已从数据库中删除 0 个文件
“发现文件”操作已完成。
正在分析打开的文件...
正在分析剩余的文件...
  正在分析: 已处理 0 个文件
“分析剩余文件”操作已完成。
空闲环路: 重新分析活动文档
“分析打开的文件”操作已完成。
正在检查语法错误: file:///d%3A/WorkSet/iris/sdk/unity/UnityCustomSurface/plugin/src/main/native/unity/provider/display/SinglePassRenderer.cpp
正在为以下项的翻译单元中文件的 IntelliSense 更新进行排队: D:\WORKSET\IRIS\SDK\UNITY\UNITYCUSTOMSURFACE\PLUGIN\SRC\MAIN\NATIVE\UNITY\PROVIDER\DISPLAY\SINGLEPASSRENDERER.CPP
cpptools/finishUpdateSquiggles
错误波形曲线计数: 28
将在以下项中禁用错误波形曲线: file:///d%3A/WorkSet/iris/sdk/unity/UnityCustomSurface/plugin/src/main/native/unity/provider/display/SinglePassRenderer.cpp
更新 IntelliSense 时间(秒): 0.674
cpptools/getFoldingRanges: file:///d%3A/WorkSet/iris/sdk/unity/UnityCustomSurface/plugin/src/main/native/unity/provider/display/SinglePassRenderer.cpp (id: 6)
cpptools/getCodeActions: file:///d%3A/WorkSet/iris/sdk/unity/UnityCustomSurface/plugin/src/main/native/unity/provider/display/SinglePassRenderer.cpp (id: 7)

```

**Comment by sean-mcmanus** [comment] 2021-05-14 18:25
@searingarrows I believe your issue is fixed in 1.4.0-insiders (same issue as https://github.com/microsoft/vscode-cpptools/issues/7388 ).

@thunderstorm010 Have you tried 1.4.0-insiders? It's possible your issue may also be caused by the -Werror, but the logging doesn't directly indicate that.

**Comment by searingarrows** [comment] 2021-05-15 03:10
@sean-mcmanus 1.4.0-insiders works, thanks

**Comment by thunderstorm010** [comment] 2021-05-18 10:34
> @thunderstorm010 I assume because your project targets android that you are not intending to compile for `x86_64-w64-windows-gnu`. Could you enable verbose output for CMake and provide one of your compile command lines? A compile command line from `compile_commands.json` would also work. Perhaps an arg that controls the target used by the compiler is being omitted by the compiler query. Seeing a working compile command line for your project should clarify.

How can I do that? I'm using CMake and I can't see the compile_commands.json file.

**Comment by sean-mcmanus** [comment] 2021-05-19 22:47
@thunderstorm010 You can set the CMAKE_EXPORT_COMPILE_COMMANDS CMake variable to have CMake generate a compile_commands.json file. In VS Code there's a CMake.LoggingLevel setting (not sure if that's what Colen meant by the "enable verbose output").

**Comment by thunderstorm010** [comment] 2021-05-20 20:30
My compile_commands.json file:
```
[
{
  "directory": "C:/Users/crypto/Desktop/New folder/MonoLoader/build/Quest",
  "command": "Q:\\android-ndk-r22b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe --target=aarch64-none-linux-android24 --gcc-toolchain=Q:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=Q:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DID=\\\"monoloader\\\" -DVERSION=\\\"0.1.0\\\" -Dmonoloader_EXPORTS -I../../extern -I../../shared -I../../include -I../.././extern/libil2cpp/il2cpp/libil2cpp -isystem ../../extern/beatsaber-hook/shared -isystem ../../extern/modloader -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -std=gnu++20 -o CMakeFiles\\monoloader.dir\\src\\main.cpp.o -c \"C:\\Users\\crypto\\Desktop\\New folder\\MonoLoader\\src\\main.cpp\"",
  "file": "C:/Users/crypto/Desktop/New folder/MonoLoader/src/main.cpp"
},
{
  "directory": "C:/Users/crypto/Desktop/New folder/MonoLoader/build/Quest",
  "command": "Q:\\android-ndk-r22b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe --target=aarch64-none-linux-android24 --gcc-toolchain=Q:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=Q:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DID=\\\"monoloader\\\" -DVERSION=\\\"0.1.0\\\" -Dmonoloader_EXPORTS -I../../extern -I../../shared -I../../include -I../.././extern/libil2cpp/il2cpp/libil2cpp -isystem ../../extern/beatsaber-hook/shared -isystem ../../extern/modloader -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -std=gnu++20 -o CMakeFiles\\monoloader.dir\\extern\\beatsaber-hook\\src\\inline-hook\\And64InlineHook.cpp.o -c \"C:\\Users\\crypto\\Desktop\\New folder\\MonoLoader\\extern\\beatsaber-hook\\src\\inline-hook\\And64InlineHook.cpp\"",
  "file": "C:/Users/crypto/Desktop/New folder/MonoLoader/extern/beatsaber-hook/src/inline-hook/And64InlineHook.cpp"
},
{
  "directory": "C:/Users/crypto/Desktop/New folder/MonoLoader/build/Quest",
  "command": "Q:\\android-ndk-r22b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang.exe --target=aarch64-none-linux-android24 --gcc-toolchain=Q:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=Q:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DID=\\\"monoloader\\\" -DVERSION=\\\"0.1.0\\\" -Dmonoloader_EXPORTS -I../../extern -I../../shared -I../../include -I../.././extern/libil2cpp/il2cpp/libil2cpp -isystem ../../extern/beatsaber-hook/shared -isystem ../../extern/modloader -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIC -o CMakeFiles\\monoloader.dir\\extern\\beatsaber-hook\\src\\inline-hook\\inlineHook.c.o -c \"C:\\Users\\crypto\\Desktop\\New folder\\MonoLoader\\extern\\beatsaber-hook\\src\\inline-hook\\inlineHook.c\"",
  "file": "C:/Users/crypto/Desktop/New folder/MonoLoader/extern/beatsaber-hook/src/inline-hook/inlineHook.c"
},
{
  "directory": "C:/Users/crypto/Desktop/New folder/MonoLoader/build/Quest",
  "command": "Q:\\android-ndk-r22b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang.exe --target=aarch64-none-linux-android24 --gcc-toolchain=Q:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=Q:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DID=\\\"monoloader\\\" -DVERSION=\\\"0.1.0\\\" -Dmonoloader_EXPORTS -I../../extern -I../../shared -I../../include -I../.././extern/libil2cpp/il2cpp/libil2cpp -isystem ../../extern/beatsaber-hook/shared -isystem ../../extern/modloader -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIC -o CMakeFiles\\monoloader.dir\\extern\\beatsaber-hook\\src\\inline-hook\\relocate.c.o -c \"C:\\Users\\crypto\\Desktop\\New folder\\MonoLoader\\extern\\beatsaber-hook\\src\\inline-hook\\relocate.c\"",
  "file": "C:/Users/crypto/Desktop/New folder/MonoLoader/extern/beatsaber-hook/src/inline-hook/relocate.c"
}
]
```

**Comment by Colengms** [comment] 2021-05-20 23:33
Hi @thunderstorm010 .  If you remove `"configurationProvider": "ms-vscode.cmake-tools"` from your `c_cpp_properties.json`, and instead set `"compileCommands": "<path to your compile_commands.json file>"`, does the issue still occur?

The command lines in your `compile_commands.json` file include `--target` args, but I am not seeing any `--target` args in the custom configuration data received from CMake Tools.  If that `compile_commands.json` was generated using the same CMake configuration that you were using with CMake Tools in the logs you posted, the issue would seem to be that CMake Tools is not passing the `--target` arg along to the C/C++ Extension for some reason.

**Comment by sean-mcmanus** [comment] 2021-05-20 23:51
i.e. if CMake Tools isn't sending the --target you could file an issue with CMake Tools or we could transfer this issue there.

**Comment by thunderstorm010** [comment] 2021-05-21 08:04
Yep, I've set the c_cpp_properties.json file to ```
{
    "version": 4,
    "configurations": [
        {
            "name": "Quest",
            "intelliSenseMode": "linux-clang-arm64",
            "compileCommands": "C:/Users/crypto/Desktop/New folder/MonoLoader/build/Quest/compile_commands.json"
        }
    ]
}
```
and I've no squiggles under includes. It'll be nice if you can move this issue to /vscode-cmake-tools.

**Comment by Colengms** [comment] 2021-05-24 18:03
Closing as external, in favor of the issue in the CMake Tools repo. https://github.com/microsoft/vscode-cmake-tools/issues/1896

**Closed as completed by Colengms** 2021-05-24 18:03 UTC
Labels: Language Service, external, Feature: Configuration

**Comment by andreeis** [comment] 2021-06-09 07:03
@thunderstorm010, can you try the CMake Tools vsix from [here](https://github.com/microsoft/vscode-cmake-tools/actions/runs/920800165) and confirm if it solves anything for you?
