### ISSUE TITLE
C/C++ extension not working on vs code insiders for m1 Macs

### ISSUE THREAD

**Issue by prasoonrajpoot** [microsoft/vscode-cpptools#6901] opened 2021-02-04 06:18 UTC
To be frank to you guys I am a student and don't have much knowledge..
when I try to install C/C++ extension as I have to use C language for college purposes. it shows my architecture is not supported...
Please can anybody guide me in simple language in steps how can I fix that ??? 
I will highly obiliged to your support.....👏🏽

**Comment by michelleangela** [comment] 2021-02-04 22:49
@betusingh890 

Version 1.2.0 of the C++ extension should be able to run on the x64 emulator of Apple Silicon ARM64 machine regardless whether VS Code is insiders or not.

There is a separate issue that is tracking to for C++ extension to run natively on Apple Silicon ARM64 (see https://github.com/microsoft/vscode-cpptools/issues/6595).

This is also a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6839

**Closed as completed by michelleangela** 2021-02-04 22:49 UTC
Labels: duplicate
