### ISSUE TITLE
Format on Save setting enabled withmodifications is formatting the whole file

### ISSUE THREAD

**Issue by fergald** [microsoft/vscode-cpptools#10391] opened 2023-01-17 12:09 UTC
### Environment

- OS and Version: Debian GNU/Linux (Google internal)
- VS Code Version:

```
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:57:40.428Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.11-1rodete1-amd64
Sandboxed: No

```

- C/C++ Extension Version: 1.13.9
- If using SSH remote, specify OS of remote machine:  same as local

I was able to reproduce this running locally too but now I can only repro over ssh (I am getting a stack trace about "Illegal value for `line`" when trying to repro locally, I will file another issue for that).

### Bug Summary and Steps to Reproduce

Copied from https://github.com/microsoft/vscode/issues/170936

I'm running into this while working on chromium. Repro steps below are for a chromium checkout ([multiple chrome devs are seeing this](https://crbug.com/1402278)). I tried to repro in a simple clean repository but couldn't repro steps are (from a checkout of chrome).

1. run the following script on a chromium checkout
  ```sh
  #! /bin/bash -ex
  
  git checkout -b b1 main
  perl -i -pe 'if (/^ / && !$f) {$_="// $_";  $f=1}' content/browser/renderer_host/render_frame_host_impl.cc
  git commit -a -m//
  
  git checkout -b b2 main
  perl -i -pe 'if (/^ / && !$f) {$_="//// $_";  $f=1}' content/browser/renderer_host/render_frame_host_impl.cc
  git commit -a -m////
  
  git rebase b1
  ```
2. Note that line 9565 is before saving
  ```
    if (!IsRenderFrameLive())
      return;
  ```
3. Resolve the conflict in vscode (just delete it all)
4. Save
5 `git diff`

You'll get a ~3000 line diff with lots of reformatted `if` statements.

This might not be a recent problem, however chrome recently changed it's clang-format to add braces to all `if`s so it is now very noticeable, as every file has `if`s that get reformatted.

### Configuration and Logs

```shell
$@ cat .vscode/c_cpp_properties.json 

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "${workspaceFolder}/compile_commands.json"
        }
    ],
    "version": 4
```

I tried `C/C++: Log Diagnostics` but I saw no output when saving the file (is it because this is remote?)
```


### Other Extensions

I have a bunch of other extension but I couldn't find a way to get a copy/pasteable list of them.

I did find that disabling clangd extension stopped this from happening (and stopped all code formatting)

### Additional context

_No response_

**Comment by Colengms** [comment] 2023-01-18 03:34
Hi @fergald .  

> Resolve the conflict in vscode (just delete it all)

Can you clarify what you are doing to resolve the conflict?  Are you simply editing text, or is there some other UI involved that may be incurring unintended edits?

In this scenario, an extension does not decide which ranges should be formatted.  The range are passed to it by VS Code.  If 'resolving the conflicts' involved multiple edits, it's possible either the issue is with VS Code identifying the ranges to be formatted, or perhaps VS Code is coalescing those ranges into a single range, gathering up everything in between.  Since `provideDocumentRangeFormattingEdits` accepts only a single range, I assume VS Code should either be invoking it separately for each modified range (unlikely), or the ranges are getting coalesced (more likely), resulting in formatting of code between those modifications as well.

The C/C++ extension leverages clang-format, by default.  Another possible cause is that clang-format does sometimes format more than the range provided to it, usually when a change on that line impacts code immediately around it.  You might try manually invoking clang-format to format only a range that should be impacted and see if perhaps that is resulting in formatting a much larger range.

Since the C/C++ extension is just marshalling ranges that were provided to us, I suspect this issue is either with VS Code itself, or possibly clang-format.

**Comment by fergald** [comment] 2023-01-18 03:45
In the example, the conflict is a single line. I'm directly editing. Whether I just delete the whole block or accept one of the edits, saving reformats the whole file. Here's a snippet of the diff

```
diff --cc content/browser/renderer_host/render_frame_host_impl.cc
index bf99ad721d313,7d56eafcc25cb..0000000000000
--- a/content/browser/renderer_host/render_frame_host_impl.cc
+++ b/content/browser/renderer_host/render_frame_host_impl.cc
@@@ -296,9 -296,9 +296,10 @@@
  #endif
  
  namespace features {
--BASE_FEATURE(kDisableFrameNameUpdateOnNonCurrentRenderFrameHost,
- //              "DisableFrameNameUpdateOnNonCurrentRenderFrameHost",
 -////              "DisableFrameNameUpdateOnNonCurrentRenderFrameHost",
--             base::FEATURE_ENABLED_BY_DEFAULT);
++BASE_FEATURE(
++    kDisableFrameNameUpdateOnNonCurrentRenderFrameHost,
++    //              "DisableFrameNameUpdateOnNonCurrentRenderFrameHost",
++    base::FEATURE_ENABLED_BY_DEFAULT);
  
  // Evict when accessibility events occur while in back/forward cache. Remove
  // once the https://crbug.com/1341507 is resolved. This crash started to happen
@@@ -549,8 -549,8 +550,9 @@@ void GrantFileAccess(int child_id
        ChildProcessSecurityPolicyImpl::GetInstance();
  
    for (const auto& file : file_paths) {
--    if (!policy->CanReadFile(child_id, file))
++    if (!policy->CanReadFile(child_id, file)) {
        policy->GrantReadFile(child_id, file);
++    }
    }
  }
```

As you can see the first `if` that gets reformatted is hundreds of lines away from the conflict.

This only seems to happen with conflicts. Other edits respect the modifications-only setting.

Is there a way to see what's being sent to clang-format? I guess I could write a wrapper that logs everything...

**Comment by fergald** [comment] 2023-01-18 04:23
I have set my `C_Cpp: Clang_format_path` setting to `/usr/local/google/home/fergal/chromium/src/clang-format-wrapper.sh` in both workspace and Remote (it not present in User) which logs the arguments. It is not being executed.

When I disable the clangd extension, I lose format-on-save. That makes me think that the C++ extn is not actually the one doing the formatting.

Setting `editor.defaultFormatter` to C/C++ in all 3 settings means I lose formatting on save, it seems.

**Comment by fergald** [comment] 2023-01-18 04:29
Further confirmation. When I save, I see this in the clangd output

```
I[04:24:32.142] <-- textDocument/rangeFormatting(186)
I[04:24:33.244] --> reply:textDocument/rangeFormatting(186) 1102 ms
```

When I switch any of my settings away from default to `"editor.defaultFormatter": "ms-vscode.cpptools"` I get no formatting on save.

**Comment by fergald** [comment] 2023-01-19 04:42
So my question now is why is C/C++ *not* doing my formatting? That's why the tracing indicated in the original bug and when I disable the clang extension entirely, I get no formatting at all.

**Comment by Colengms** [comment] 2023-01-19 19:52
Hi @fergald .  We're not tracking a general issue with formatting not working at all.  That would seem to suggest there is something going on specific to your config or environment.

Could you set `"C_Cpp.loggingLevel": "Debug"`, and post the output from the C/C++ channel from a repro?  It should log details about which formatting engine it's using, and any errors related to formatting attempts.

**Closed as not planned** 2023-03-21 11:15 UTC
Labels: Language Service, more info needed, Feature: Code Formatting
