### ISSUE TITLE
C++ autocomplete not working for private functions/methods

### ISSUE THREAD

**Issue by enelson1001** [microsoft/vscode-cpptools#2539] opened 2018-09-21 19:19 UTC
**Type: LanguageService**

**Describe the bug**
When using autocomplete to add a private member function/method to the class the drop-down list of suggested functions/methods only contains public functions/methods.

- OS and Version: Linux Mint 18.3
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

1. Create header file that contains both public and private methods
2. Create class
3. Add a function/method to class; after entering :: a drop-down list appears of suggested functions/methods but only public functions/methods are listed.
4. See screen shot below.  The header file is shown on right side and has both public and private functions/methods
5. Even typing "private" nothing after :: does not bring any suggestions up

**Expected behavior**

Would expect to see all functions listed for class

**Screenshots**

![helloworld2a](https://user-images.githubusercontent.com/43481343/45901488-4bdd2000-bda0-11e8-8ca8-b0078ed0ba9e.png)

**Additional context**

**Comment by sean-mcmanus** [comment] 2018-09-21 19:27
This is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/1955. A workaround is to invoke completion (e.g. Ctrl+Space) a 2nd time with the cursor on the same location (you need to use Esc, or cursor left/right to get rid of the 1st completion popup though, since VS Code doesn't allow the 2nd Ctrl+Space while the 1st popup is visible).

**Closed as completed by sean-mcmanus** 2018-09-21 19:27 UTC
Labels: bug, duplicate, Language Service
