### ISSUE TITLE
no member named 'thread' in namespace 'std'

### ISSUE THREAD

**Issue by Laur1nMartins** [microsoft/vscode-cpptools#1748] opened 2018-03-28 10:33 UTC
I created a task to compile the main.cpp.
compiling with the following code snippet seems to be fine but i still get error markings on "std::thread"

![screenshot from 2018-03-28 10-58-18](https://user-images.githubusercontent.com/26897824/38024059-2e54cd8c-3284-11e8-95d1-08233d98bc91.png)

compile task: 
"command": "g++ -Wall -g -std=c++17 -pthread main.cpp -o CANToolLinux"

clang:  
clang version 4.0.1-6 (tags/RELEASE_401/final) 
Target: x86_64-pc-linux-gnu 
Thread model: posix

Another stupid thing that has nothing to do with this problem i guess is that after some time my c_cpp_properties.json forgets all include paths i typed in. But that happend yesterday.Today the file seems fine.

my c_cpp_properties.json:

    
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/include/c++/7",
                    "/usr/include/x86_64-linux-gnu/c++/7",
                    "/usr/include/c++/7/backward",
                    "/usr/lib/gcc/x86_64-linux-gnu/7/include",
                    "/usr/local/include",
                    "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed",
                    "/usr/include/x86_64-linux-gnu",
			        "/usr/include",
                    "/usr/src/linux-headers-4.13.0-37"
                    ],
            "defines": [],
            "browse": {
                "path": [
                    "/usr/include/c++/7",
                    "/usr/include/x86_64-linux-gnu/c++/7",
                    "/usr/include/c++/7/backward",
                    "/usr/lib/gcc/x86_64-linux-gnu/7/include",
                    "/usr/local/include",
                    "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed",
                    "/usr/include/x86_64-linux-gnu",
			        "/usr/include",
                    "/usr/src/linux-headers-4.13.0-37"
		        ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 3
    
Mirror from : https://stackoverflow.com/questions/49530148/vs-code-c-thread-not-in-namespace-std

**Comment by sean-mcmanus** [comment] 2018-03-28 18:52
This is most likely due to missing defines required by your thread library. Our pending 0.16.0 release fixes this by querying the compiler's defines, and enabling your to set the compilerPath property for when we default to the wrong one: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders2 .

What do you mean by "forgets all include paths"? Do you mean it becomes blank?

**Comment by Laur1nMartins** [comment] 2018-03-28 19:04
Yes the paths just became blank for both includes. But this has not happend to me today.

**Comment by sean-mcmanus** [comment] 2018-03-28 19:23
cmake-tools-helper has been known to reset the includes (https://github.com/Microsoft/vscode-cpptools/issues/1569 ), but I'm not aware of any scenario in which our extension does that (the code is at https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/configurations.ts ).

**Comment by Laur1nMartins** [comment] 2018-03-28 19:31
like i said happened yesterday. i tried even tried to edit and save it from with an external application but after a while all changes just disappeared. Today i could not reproduce that error.
im using git. can this be a reason for this issue ? I was not actively doing something with that git though.

**Comment by sean-mcmanus** [comment] 2018-03-28 20:02
It seems unlikely git could be the cause, unless you had c_cpp_properties.json checked into git and somehow switched to a branch that had the includes blank.

**Comment by bobbrow** [comment] 2018-03-29 16:19
Version 0.16.0 has been released.  Can you try again?  You can add "compilerPath" to your "Linux" configuration and we will query your compiler for its defaults before we try to parse the source file.

**Closed as completed** 2018-04-24 20:46 UTC
Labels: bug, Language Service, fixed
