### ISSUE TITLE
2 uncaught errors

### ISSUE THREAD

**Issue by areee** [microsoft/vscode-cpptools#2613] opened 2018-10-05 18:16 UTC
- Extension Name: cpptools
- Extension Version: 0.19.0
- OS Version: Darwin x64 18.0.0
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 6582,
		"activateCallTime": 120,
		"activateResolvedTime": 479,
		"activationEvent": "onLanguage:cpp"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'fsPath' of null"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'fsPath' of null"
		}
	]
}
```

**Comment by sean-mcmanus** [comment] 2018-10-05 19:03
Thanks for reporting this. Yeah, I'm seeing this error when opening a file without a workspace folder. You could use Open Folder instead of open file to avoid this error. Looks like a regression from https://github.com/Microsoft/vscode-cpptools/pull/2552 .

**Comment by sean-mcmanus** [comment] 2018-10-09 21:15
Fixed with https://github.com/Microsoft/vscode-cpptools/releases/download/0.19.1-insiders/cpptools-osx.vsix .

**Comment by rsthn** [comment] 2018-10-14 04:10
I can confirm it happens on Windows as well, please add a fix to it.

    Extension Name: cpptools
    Extension Version: 0.19.0
    OS Version: Microsoft Windows [Version 10.0.17134.228]
    VSCode version: 1.28.1

**Closed as completed** 2018-10-30 23:42 UTC
Labels: bug, fixed, quick fix, regression
