### ISSUE TITLE
Ignore library files during debugging

### ISSUE THREAD

**Issue by Y7n05h** [microsoft/vscode-cpptools#6593] opened 2020-11-30 11:31 UTC
Type: Debugger

In the debugging function, vscode failed to follow the configuration of gdb to skip some files.

**Describe the bug**
- OS and Version:`Arch Linux`  `Linux x64 5.9.10-arch1-1`
- VS Code Version:
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
```

- C/C++ Extension Version:`v1.1.2`

**To Reproduce**

```c++
#include <iostream>
using namespace std;
int main(void)
{
    string test = "Bug Report Test";
    auto a = test.begin();//Line 6
    cout << *a << endl;
}
```

When I add a breakpoint on line 6 and perform single-step debugging, I will enter the library file, but I want the debugger to skip all library files.I just want the debugging tool to step through my own code.

In order to solve the problem, I added 
```
skip -gfi /usr/include/c++/
skip -gfi /build/gcc/src/
```
in the gdb configuration file  in `~/.gdbinit`

In the debug console of vscode, gdb read the option, but failed to execute it correctly.

>launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "gdb-g++",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "internalConsoleOptions": "neverOpen",
            "MIMode": "gdb",
            "miDebuggerPath": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": false
                }
            ],
            "preLaunchTask": "Compile_CPP"
        }
    ]
}
```

**Comment by WardenGnaw** [comment] 2020-11-30 19:10
Duplicate of: https://github.com/microsoft/vscode-cpptools/issues/811#issuecomment-613912937

**Closed as completed by WardenGnaw** 2020-11-30 19:10 UTC
Labels: duplicate, debugger
