### ISSUE TITLE
Exclude System Included symbols/variables from autocomplete

### ISSUE THREAD

**Issue by Richhoef** [microsoft/vscode-cpptools#5867] opened 2020-07-30 18:12 UTC
**Type: LanguageService**

Is it possible to exclude the symbols/variables/etc which are found by the `systemIncludePath` from the auto complete? 
I only want symbols/variables which are found in the files under the `includePath` and/or the `browse.path` to be suggested to me when I type. Now, the first things that are suggested are always many many variables which I have never used and probably will never use. Only when I type more characters, the list will become relevant. 
I can get the desired behaviour by setting the `C_Cpp.default.systemIncludePath` to `"C_Cpp.default.systemIncludePath": [""],` (and not including those path's as `includePath` in the c_cpp_properties.json), but this has the, logical, (side) effect of intellisense not being able to find some of the files that are being included. If a variable found by the 'systemIncludePath' is used somewhere in the file, it obviously is being used and would be allowed to be suggested. This would make typing so much faster and nicer! 

Reading [customize default settings cpp #system-includes](https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp#_system-includes) I thought the desired behaviour described above would already (supposed to) be the case, but I do not get it to work. Help is very much appreciated.

If more informating is needed, I would be happy to provide it!

Besides the above, it would also be nice to have variables that are used recently at/near the top of the list (depending on how often they are used recently). This would also speed up typing a lot.

**Version info**
- OS and Version: Microsoft Windows [Version 10.0.18363.959]
- VS Code Version: 1.47.3
- C/C++ Extension Version: 0.29.0

**Comment by sean-mcmanus** [comment] 2020-08-04 19:55
Yeah, we'd have to add completion filtering based on the file path, possibly checking files.exclude or some other new setting.

**Comment by bobbrow** [comment] 2020-08-06 00:31
This feels like too big of a hammer to solve the problem.  I think that #1798/#4939 would address the root cause of the issue (too much info) and make the completion list more manageable.  I wouldn't think that you'd really want to remove completions for all STL types (which is what I assume are the types of files pointed to by your `systemIncludePath`.

(And as an aside, if it is the standard C/C++ headers you're specifying in `systemIncludePath`, consider using `compilerPath` instead. You will get better IntelliSense.)

**Comment by bobbrow** [comment] 2020-08-13 21:11
We'll close this as a duplicate of 1798 and 4939.

**Closed as completed by bobbrow** 2020-08-13 21:11 UTC
Labels: duplicate, Language Service, Feature Request, Feature: Auto-complete
