### ISSUE TITLE
Operator placement new renders intellisense error

### ISSUE THREAD

**Issue by selassje** [microsoft/vscode-cpptools#7098] opened 2021-03-03 13:32 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win10
- VS Code Version: 1.53.2
- C/C++ Extension Version: v1.2.2
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

My gcc compiler has no problem with it.

![image](https://user-images.githubusercontent.com/42682959/109812303-32588780-7c2c-11eb-97b2-86839dca4e10.png)

intellisense compiler args:
            "compilerArgs": [
                "-O3",
                "-fstrength-reduce",
                "-fno-builtin",
                "-x",
                "c++",
                "-ansi",
                "-fno-zero-initialized-in-bss",
                "-Wno-write-strings",
                "-MD",
                "-MP",
                "-std=c++11",
                "-mlongcall",
                "-fsigned-char"
            ]
my compiler flags : 
-O3 -fstrength-reduce -fno-builtin -x c++ -ansi -fno-zero-initialized-in-bss -Wno-write-strings -MD -MP -std=c++11 -mlongcall -fsigned-char

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment] 2021-03-03 18:06
This appears to be a duplicate of #6246 , which is tracking https://developercommunity.visualstudio.com/content/problem/1207998/cc-intellisense-gives-errors-regarding-size-t-and.html .

**Closed as completed by sean-mcmanus** 2021-03-03 18:06 UTC
Labels: duplicate
