### ISSUE TITLE
command 'C_Cpp.ConfigurationEditJSON' not found

### ISSUE THREAD

**Issue by misha-antonenko** [microsoft/vscode-cpptools#9109] opened 2022-03-29 12:50 UTC
Issue Type: <b>Bug</b>

Reinstalling does not help

Extension version: 1.9.7
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No
Remote OS version: Linux x64 4.19.183-42.2mofed

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|14, 19, 16|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id de7537ee-b7ff-4aa6-9ac1-40d3f0a20bb2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sdc-dev-container|
|OS|Linux x64 4.19.183-42.2mofed|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (65 x 2095)|
|Memory (System)|156.42GB (0.64GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrc:30451274
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477:30450038

```

</details>

**Comment by michelleangela** [comment] 2022-03-29 16:04
This issue should have been fixed in 1.9.x https://github.com/microsoft/vscode-cpptools/issues/8785. 

Though sometimes this could occur if installation was incomplete. Could you try uninstalling/reinstalling the C/C++ extension? Maybe restarting VS Code in between or making sure the extension directory is deleted on the remote machine in case VS Code did not delete it when uninstalling.

**Comment by misha-antonenko** [comment] 2022-03-29 16:30
Does not work

**Comment by michelleangela** [comment] 2022-03-29 19:52
There is a current issue https://github.com/microsoft/vscode-cpptools/issues/9083 where the extension will not activate if `C_Cpp.intelliSenseEngine` is set to disabled. Is your `C_Cpp.intelliSenseEngine` disabled by any chance? Are there any other `C_Cpp.*` settings configured?

Also, could you provide logs from the "Log (Extension Host)" output to check what is happening during extension activation?
![image](https://user-images.githubusercontent.com/38734287/160695543-e9ac4fa5-23a0-4079-8323-ca2faf8e9304.png)

**Comment by misha-antonenko** [comment] 2022-03-30 03:42
Right, it was indeed disabled. Thank you for clarifying!

**Comment by michelleangela** [comment] 2022-03-30 16:27
Closing as duplicate of #9083

**Closed as completed by michelleangela** 2022-03-30 16:27 UTC
Labels: duplicate, Language Service
