### ISSUE TITLE
Autosuggestion provided by VS code is not working after this tool enabled

### ISSUE THREAD

**Issue by zkostree** [microsoft/vscode-cpptools#574] opened 2017-03-16 09:44 UTC
Hi, I found that the autosuggestion provided by VS code is not working after I installed and enabled this C/C++ extension. (Only c or cpp files have this problem)
I have changed the config "C_Cpp.autocomplete"  from "Default" to "Disable", but it still didn't work.

Without vscode-cpptools extension :
![success](http://i.imgur.com/5KqAbE8.gif)

With vscode-cpptools extension : 
No Matter "C_Cpp.autocomplete" is Default or Disable
![failed](http://i.imgur.com/w2lPrfF.gif)

I have found a similar issue : #189 
But his autosuggestion works properly, though it seems like there is no IntelliSense. 

Thanks!

Platform : Windows 7
VS Code Version : 1.11.0
Cpptools Version : 0.10.4

**Comment by sean-mcmanus** [comment] 2017-03-16 13:27
This is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/572 . Changing your user setting to [cpp]: { "editor.quickSuggestions": true } should fix the issue.

**Closed as completed by sean-mcmanus** 2017-03-16 13:27 UTC
Labels: duplicate

**Comment by zkostree** [comment] 2017-03-17 01:00
It works! Thank you!

**Comment by zkostree** [comment] 2017-03-17 01:00
It works! Thank you!

**Comment by amit13091992** [comment] 2020-02-21 04:46
> This is a duplicate of #572 . Changing your user setting to [cpp]: { "editor.quickSuggestions": true } should fix the issue.

@sean-mcmanus 
Can you please tell me for JS as well. For my React project this issue is happening.

**Comment by sean-mcmanus** [comment] 2020-02-21 20:15
@amit13091992 Does using [js]: { "editor.quickSuggestions": true } not work? Our extensions should not be affecting JavaScript quickSuggestions. Have you tried asking the VS Code team about your issue?

**Comment by amit13091992** [comment] 2020-02-22 05:08
> @amit13091992 Does using [js]: { "editor.quickSuggestions": true } not work? Our extensions should not be affecting JavaScript quickSuggestions. Have you tried asking the VS Code team about your issue?

No @sean-mcmanus It did not work, any suggestions for how can i resolve it.

**Comment by sean-mcmanus** [comment] 2020-02-24 21:25
@amit13091992 I don't know. Can you ask someone on the VS Code team?

**Comment by amit13091992** [comment] 2020-02-25 04:11
> @amit13091992 I don't know. Can you ask someone on the VS Code team?

Sure thank you for the reply.
