### ISSUE TITLE
No auto suggestions via pointer available

### ISSUE THREAD

**Issue by MarcTCruz** [microsoft/vscode-cpptools#8412] opened 2021-11-17 14:57 UTC
Duplicate of (closed) #5228
Bug type: Language Service

Visual Studio Code

Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z (5 days ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

- C/C++ Extension Version:
C/C++ v1.7.1

![image](https://user-images.githubusercontent.com/58499846/142223401-52bfa1c7-b0fe-49c4-b895-75d9c55bc7ad.png)

```
#include <iostream>
template <class T>
class Simple_Templated_Class
{
    struct Node
    {
        int value = 15;
    };

public:
    void print_value()
    {
        Node *new_node = new Node;
        //new_node->
        std::cout << new_node->value;
    }
};

int main()
{
    Simple_Templated_Class<int> stc_instance;

    stc_instance.print_value();

    return 0;
}
```

**Comment by Colengms** [comment] 2021-11-17 19:27
Hi @MarcTCruz .  Thanks for reporting this.  The root cause appears to be that IntelliSense is assuming a type must be known for the template arg before it can provide completion for member types.  (https://github.com/microsoft/vscode-cpptools/issues/1946 is tracking providing a way for users to provide types for template args).  However, in your case, the type failing to provide completion has no dependency on the template arg.

I've opened a bug against VS internally.  (We share the IntelliSense implementation with VS).

**Comment by sean-mcmanus** [comment] 2022-01-28 17:01
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.1

**Closed as completed** 2022-02-01 20:37 UTC
Labels: Language Service, fixed, Visual Studio
