### ISSUE TITLE
IntelliSense error for enum variables with matching type and variable names

### ISSUE THREAD

**Issue by tambry** [microsoft/vscode-cpptools#4783] opened 2019-12-23 11:43 UTC
**Type: LanguageService**
**Describe the bug**
- OS and Version: Windows 1909 18363.535
- VS Code Version: 1.42.0-insider
- C/C++ Extension Version: 0.26.3-insiders2
- Enum variables with matching type and variable names give incorrect error "variable "x" is not a type name"

**To Reproduce**
Paste the following code in a .cpp file:
```
enum class colour
{
};

colour colour;
```

**Expected behavior**
No error and the type `colour` for variable `colour` is correctly detected. The code compiles fine (if you add `int main() {}`).

**Screenshots**
![image](https://user-images.githubusercontent.com/1827708/71356184-136f5780-258a-11ea-8aa8-98f3523f2cc2.png)

**Comment by sean-mcmanus** [comment] 2019-12-23 22:25
Thanks for reporting this. I've filed a bug on VS at https://developercommunity.visualstudio.com/content/problem/866015/cc-intellisense-incorrectly-reports-errors-for-glo.html .

**Comment by sean-mcmanus** [comment] 2019-12-27 20:13
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4251 (forgot about that).

**Closed as completed by sean-mcmanus** 2019-12-27 20:13 UTC
Labels: bug, duplicate, Language Service, Visual Studio
