### ISSUE TITLE
Load symbols for outline/intellisense gets stuck in v 1.2.0

### ISSUE THREAD

**Issue by olofkallander** [microsoft/vscode-cpptools#6958] opened 2021-02-12 10:49 UTC
**Type: LanguageService**
When I select a source file in the left pane, it creates an outline of the functions and classes in that file. I noticed that it suddenly could not load the symbols for a specific file in my list. I have encountered this problem once before and the workaround was to either rename the file and then rename it back, or go into ..Library../ipch folder and delete the cached intellisense symbols. But this time, that did not help. Reverting back to v 1.1.3 did help. I notice the problem a few days agp so it does seem to match the upgrade to 1.2.0 of the extension. It takes some time to recreate the symbols after the cache was cleared but it does not get stuck.
I think the child-process/thread is stuck since it cannot perform other tasks like switching between .h and .cpp file. Editing, open, save files works though.

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
Try it on a fairly big C++ project. 
Perhaps clear the symbol cache to have it reproduce outline symbols for each file you select in the left pane.
Click around on the files in the left pane. It seems that if you wait for the symbol load to complete it has a greater chance of surviving. If click on 3-4 files in sequence, it seems to get stuck easier.

If you cannot reproduce this in a project with multiple files containing at least 2000 lines, I guess it is specific to my project content in combination with version 1.2.0. 

**Expected behavior**
Symbol generation to not getting stuck. Swapping between .h and .cpp file to work.

Logs looks normal and just stop logging at the file it gets stuck parsing.
**Screenshots**
Left pane looks as it usually does when loading symbols. It just does not complete.

**Comment by sean-mcmanus** [comment] 2021-02-12 18:18
Symbols/outline not working usually means the database is unusable, usually from a dangling process locking the database file. Can you try killing any dangling cpptools processes (restarting also works), or changing the C_Cpp.default.browse.databaseFilename setting to something like `"${workspaceFolder}/.vscode/vc.db"`?

If that doesn't work, can you attach a debugger to cpptools and provide the call stack for any thread that appears to be doing work? See https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv .

**Comment by sean-mcmanus** [comment] 2021-02-12 18:50
I think it's an issue specific to one of your code files. Also, can you set C_Cpp.loggingLevel to "Debug" and look for what file is being "tag parsed" when it gets stuck? Then you place that file in an isolated workspace folder and verify that is also gets stuck? If so, are you able to determine which code in the file is triggering the problem?

**Comment by andrewmcdonald-oxb** [comment] 2021-02-15 17:33
Wanted to note that myself and several colleagues have started encountering a similar issue. Everything was fine until the most recent upgrade in the last week+. Now the Intellisense flame often gets stuck on and you can't use go to definition etc.

Exiting VS Code leaves a `cpptools` and `cpptools-srv` process each behind. Killing `cpptools` clears the other one too, and then relaunching VS Code seems to get things back into a working state, which persists for a while but within a short time the problem is back again.

I don't really have specific repro steps for this beyond the above - does it sound like the linked issue which has been fixed in the upcoming release?

In my case I'm using VS Code 1.53.2 on mac OS Catalina 10.15.6 with C/C++ extension 1.2.0. Anecdotally some colleagues have reported that downgrading to 1.52 fixed it, but I'm not sure whether that included an extension downgrade too.

**Comment by ChiSaw** [comment] 2021-02-15 21:16
I can confirm that IntelliSense gets stuck ever since the recent days.

I have  C_Cpp.loggingLevel set to "Debug". Sometimes it get stuck at "tag parsing" an arbitrary file or but also when "Checking for syntax errors". The IntelliSense flame won't disappear keeps saying "Updating IntelliSense". I have tried to disable C_Cpp: Intelli Sense Engine Fallback to check if tag parser itself seems to be the problem, but no difference. Only restarting vscode seems to help.

Weirdly, it seems to occur "after a while" too. For me its usually 5-10 minutes working in a fairly big project. I tried to disable all other extensions as well, no luck so far.

I am running vscode 1.53.1 on macos 11.2.1 (20D74) and C/C++ 1.2.0. I am no colleague of andrewmcdonald-oxb, but interestingly this happens to my colleagues too (only know from those who work on macos as well).

**Comment by sean-mcmanus** [comment] 2021-02-17 19:05
Is it better with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.1 ? We fixed some regressions.

Everyone seems to be describing different symptoms. The original poster described no symbols loading in the outline view, which would be a database issue.

@andrewmcdonald-oxb is describing what could be a deadlock -- attaching a debugger to cpptools to get the call stacks for threads that appear to have work on them could help fix that. He's also describing dangling processes, which could cause the database to be inaccessible by other VS Code instances.

@ChiSaw may also be describing a deadlock but doesn't mention dangling processes.

There is one known crash new to 1.2.0 that didn't get fixed with 1.2.1 (but will be in 1.3.0-insiders), but I don't know how that crash could lead to the symptoms described, so I'm guessing they're unrelated.

**Comment by ChiSaw** [comment] 2021-02-17 22:47
Thanks @sean-mcmanus, unfortunately no luck with 1.2.1 either. Stopped working and got stuck after ~15 minutes. I'd like to attach a debugger to it, unfortunately the pause button of the debugger does not work/cannot pause the process, hence I cannot post the stack at the time when it gets stuck. However, I do have a dangling cpptools process as well then.

The debug output from cpptools looks like the following for me, however its not always getting stuck at "tag parsing file", sometimes at other operations. Sounds reasonable that it is related to interprocess communication issues, so I am looking forward to 1.2.2-insiders!

```log
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///Users/christian/some_path/file1.h (id: 1571)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///Users/christian/some_path/file1.h (id: 1572)
textDocument/didChange: file:///Users/christian/some_path/file1.h
cpptools/abortRequest
cpptools/textEditorSelectionChange
textDocument/definition: file:///Users/christian/some_path/file1.h (id: 1573)
cpptools/getFoldingRanges: file:///Users/christian/some_path/file1.h (id: 1574)
cpptools/textEditorSelectionChange
textDocument/didChange: file:///Users/christian/some_path/file1.h
cpptools/abortRequest
cpptools/textEditorSelectionChange
cpptools/getSemanticTokens: file:///Users/christian/some_path/file2.cpp (id: 1575)
cpptools/getSemanticTokens: file:///Users/christian/some_path/file3.h (id: 1576)
cpptools/getSemanticTokens: file:///Users/christian/some_path/file2.h (id: 1577)
cpptools/getSemanticTokens: file:///Users/christian/some_path/file4.h (id: 1578)
cpptools/getCodeActions: file:///Users/christian/some_path/file1.h (id: 1579)
idle loop: reparsing the active document
cpptools/getFoldingRanges: file:///Users/christian/some_path/file1.h (id: 1580)
textDocument/hover: file:///Users/christian/some_path/file1.h (id: 1581)
sending 1 changes to server
sending 1 changes to server
Checking for syntax errors: file:///Users/christian/some_path/file1.h
  tag parsing file: /Users/christian/some_path/file1.h
```

**Comment by sean-mcmanus** [comment] 2021-02-18 01:27
Can you check if https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2-insiders fixes this issue?

**Comment by ChiSaw** [comment] 2021-02-18 11:00
Looks good after working with 1.2.2-insiders for some hours, did not get stuck at any point, thanks a lot @sean-mcmanus !

**Comment by andrewmcdonald-oxb** [comment] 2021-02-18 18:20
FWIW, I've been using 1.2.1 for a day or two now, and haven't yet encountered the problem I had earlier in the week. However, I haven't necessarily been working in the same files, so might not currently be exercising that case.

Today however a colleague has reported `cpptools` getting stuck using a full core, and he's on 1.2.1. I'm not sure whether this is related to these other issues, and/or is what might be fixed in 1.2.2.

**Comment by sean-mcmanus** [comment] 2021-02-18 21:50
@andrewmcdonald-oxb Multiple issues could cause high CPU usage. The best way for us to know what is going on is get a call stack via attaching a debugger or running a profiling tool (https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues). I don't think the issue we fixed with 1.2.2 would lead to high CPU usage.

**Comment by sean-mcmanus** [comment] 2021-02-19 18:40
@andrewmcdonald-oxb You're using 1.2.1? Can you try https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2-insiders2 ? We fixed some issues that could be causing what you're seeing. For the CPU usage issue, we would need more info.

**Comment by HCl-10** [comment] 2021-02-20 12:38
No need fairly big C++ project.
A 60-line single C++ source code can also stuck it.

**Comment by sean-mcmanus** [comment] 2021-02-22 18:42
@HCl-10 Are you using https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2-insiders2 ? Are you able to provide a repro?

**Comment by HCl-10** [comment] 2021-02-23 00:27
> @HCl-10 Are you using https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2-insiders2 ? Are you able to provide a repro?

I was using 1.2.1 that time, and now I changed to 1.2.2 insiders 2 and it's ok.

**Closed as completed** 2021-02-26 00:24 UTC
Labels: bug, fixed, parser, regression

**Comment by sean-mcmanus** [comment] 2021-02-26 01:22
We believe this is fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2 .

If others are hitting a similar symptom, it's probably best to open a new issue with more repro details.
