### ISSUE TITLE
Reference to functions called from macro not found

### ISSUE THREAD

**Issue by jenuc78** [microsoft/vscode-cpptools#6767] opened 2021-01-12 21:13 UTC
**Type: LanguageService**

Go To Refernce does not find functions called via macros

**Describe the bug**
- OS and Version: WSL2 Windows 10
- VS Code Version: 1.53.0-insiders
- C/C++ Extension Version: v1.1.3
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. #define my_macro cfg_pointers_update()
void cfg_pointers_update()
{}
G To Reference does not find the row where cfg_pointers_update is called via macro definition

**Expected behavior**

To list also row where function is called in macro definition

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/76923885/104375223-b1361b80-552b-11eb-94a6-e61f9ffe23c7.png)

**Additional context**

**Comment by sean-mcmanus** [comment] 2021-01-12 22:18
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4075 .

**Closed as completed by sean-mcmanus** 2021-01-12 22:18 UTC
Labels: duplicate
