### ISSUE TITLE
Exception when run my extension with other extension

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-cpptools#4] opened 2016-04-10 21:43 UTC
_From @iHuahua on March 31, 2016 12:31_
- VSCode Version:0.10.11
- OS Version:Windows 7

Steps to Reproduce:
1. ext install cpptools
2. yo code 
3. F5

it will stop on :
path.js:line 8
throw new TypeError('Path must be a string. Received ' + util.inspect(path));

_Copied from original issue: Microsoft/vscode#4823_

**Comment by egamma** [comment] 2016-04-10 21:43
_From @jrieken on April 1, 2016 14:17_

@iHuahua What do mean by `yo code`? do you create a new extension that you want to run? What is the _full_ reading of the console?

**Comment by egamma** [comment] 2016-04-10 21:43
_From @iHuahua on April 5, 2016 2:12_

@jrieken yeah, i want to create a new extension, everything is right until i run the new extension by F5. Than i had installed the "cpptools" before. 

![qq 20160405101023](https://cloud.githubusercontent.com/assets/2878674/14269404/e265a4ce-fb16-11e5-87d1-bd660740193d.jpg)

**Comment by egamma** [comment] 2016-04-10 21:43
_From @jrieken on April 5, 2016 10:38_

this is an node-internal module. what's it the call stack from your code that leads to this?

**Comment by egamma** [comment] 2016-04-10 21:43
_From @iHuahua on April 5, 2016 11:18_

@jrieken i had removed the extension `cpptools`. can you try it by yourself?

1.In vscode, `Press F1`, `ext install cpptools`.
2.In cmd, `yo code` to create a new extension, and open it with vscode
3.In vscode, `Press F5`

**Comment by egamma** [comment] 2016-04-10 21:43
_From @jrieken on April 5, 2016 14:42_

`yo code` should not install anything related to cpp. Please report the top of the stack as I believe this is something with the `cpp tools`

**Comment by egamma** [comment] 2016-04-10 21:43
_From @iHuahua on April 6, 2016 3:46_

I am sorry to later for reply.
I am a cpp developer, so I had install extension `cpptools` before. I have not modify anything about .vscode.

![stack](https://cloud.githubusercontent.com/assets/2878674/14305264/241b8fb0-fbed-11e5-93ce-62af4ff1feb7.jpg)
![setting](https://cloud.githubusercontent.com/assets/2878674/14305265/242e2c60-fbed-11e5-80b2-11dbffa7316f.jpg)

**Comment by egamma** [comment] 2016-04-10 21:43
_From @iHuahua on April 6, 2016 3:47_

@jrieken If I have not reply in time, please email to me, ihuahua#live.com, # => @

**Comment by egamma** [comment] 2016-04-10 21:43
_From @jrieken on April 6, 2016 7:15_

Thanks, that's helpful. @delmyers Can you help? This seems to be an issue with the cpp-extension.

**Comment by egamma** [comment] 2016-04-10 21:43
_From @delmyers on April 8, 2016 19:4_

This looks like an exception in the language service for the extension. I'll get someone to look at it.

**Comment by egamma** [comment] 2016-04-10 21:43
_From @delmyers on April 8, 2016 19:20_

I am having trouble with the GitHub issue mover @egamma, can you help? I keep getting an exception: Cannot call "ez" on null.

**Comment by sridmad** [comment] 2016-04-11 16:45
This is a dupe of #2

**Closed as completed by sridmad** 2016-04-11 16:45 UTC
Labels: bug, duplicate
