### ISSUE TITLE
Identifier renamer breaks when identifier contains "$" (dollar sign)

### ISSUE THREAD

**Issue by Nufflee** [microsoft/vscode-cpptools#5832] opened 2020-07-24 14:53 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 v1903
- VS Code Version: 1.48.0-insiders
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): N/A
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
When I try to rename an identifier that contains `$`, the rename box only shows the part of the identifier before or after the `$` (depending on where the cursor was when rename was invoked) but renames the whole symbol in the end.

**Steps to reproduce**

1. Create an identifier containing a `$`
2. Try to rename it using the shortcut (<kbd>F2</kbd>)
3. Observe

Gif: ![3oA6vJNidy](https://user-images.githubusercontent.com/19150550/88403992-93ce9300-cdcd-11ea-9ab6-ea6e259fb2d2.gif)

**Expected behavior**

The whole identifier should be shown in the rename box.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 7/24/2020, 4:51:15 PM
Version: 0.29.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/src",
        "${workspaceFolder}/src/libc"
    ],
    "defines": [
        "__i386__"
    ],
    "compilerPath": "/usr/bin/i686-linux-gnu-gcc",
    "cStandard": "c11",
    "intelliSenseMode": "gcc-x86",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "${workspaceFolder}/src",
            "${workspaceFolder}/src/libc"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ H:\PROJECTS\Active\epic\epic\src\userland\echo.c ]:
    H:\PROJECTS\Active\epic\epic\src\userland\echo.c
[ H:\PROJECTS\Active\epic\epic\src\kernel\kmalloc.c ]:
    H:\PROJECTS\Active\epic\epic\src\kernel\kmalloc.c
[ H:\PROJECTS\Active\epic\epic\src\kernel\syscall.c ]:
    H:\PROJECTS\Active\epic\epic\src\kernel\syscall.c
    H:\PROJECTS\Active\epic\epic\src\kernel\syscall.h
Translation Unit Configurations:
[ H:\PROJECTS\Active\epic\epic\src\userland\echo.c ]:
    Process ID: 2108
    Memory Usage: 10 MB
    Compiler Path: /usr/bin/i686-linux-gnu-gcc
    Includes:
        H:\PROJECTS\Active\epic\epic\src
        H:\PROJECTS\Active\epic\epic\src\libc
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc-cross\i686-linux-gnu\7\include
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc-cross\i686-linux-gnu\7\include-fixed
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\i686-linux-gnu\include
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include
    Defines:
        __i386__
    Standard Version: c11
    IntelliSense Mode: gcc-x86
    Other Flags:
        --gcc
        --gnu_version=70500
[ H:\PROJECTS\Active\epic\epic\src\kernel\kmalloc.c ]: not ready
    Process ID: 21508
    Memory Usage: 7 MB
    Compiler Path: /usr/bin/i686-linux-gnu-gcc
    Includes:
        H:\PROJECTS\Active\epic\epic\src
        H:\PROJECTS\Active\epic\epic\src\libc
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc-cross\i686-linux-gnu\7\include
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc-cross\i686-linux-gnu\7\include-fixed
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\i686-linux-gnu\include
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include
    Defines:
        __i386__
    Standard Version: c11
    IntelliSense Mode: gcc-x86
    Other Flags:
        --gcc
        --gnu_version=70500
[ H:\PROJECTS\Active\epic\epic\src\kernel\syscall.c ]:
    Process ID: 17728
    Memory Usage: 14 MB
    Compiler Path: /usr/bin/i686-linux-gnu-gcc
    Includes:
        H:\PROJECTS\Active\epic\epic\src
        H:\PROJECTS\Active\epic\epic\src\libc
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc-cross\i686-linux-gnu\7\include
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc-cross\i686-linux-gnu\7\include-fixed
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\i686-linux-gnu\include
        C:\Users\Nuff\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include
    Defines:
        __i386__
    Standard Version: c11
    IntelliSense Mode: gcc-x86
    Other Flags:
        --gcc
        --gnu_version=70500
Total Memory Usage: 31 MB
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/19150550/88403589-0d19b600-cdcd-11ea-97f5-32d65b23b8e4.png)
![image](https://user-images.githubusercontent.com/19150550/88403626-1440c400-cdcd-11ea-893c-e52592031cfd.png)

**Comment by Colengms** [comment] 2020-07-24 18:24
Hi @Nufflee .  This looks similar to this issue: https://github.com/Microsoft/vscode/issues/51084

There does appear to be a way for the C/C++ Extension to correct the string.  However, I'd suggest also opening a bug against VS Code, in case they would prefer to address this in their default cpp language support, by updating the pattern they use for `wordPattern` in `cpp\language-configuration.json`.

Related: https://code.visualstudio.com/api/language-extensions/language-configuration-guide

**Comment by Colengms** [comment] 2021-04-15 02:45
This looks like a VS Code issue.  I've opened a new issue for it here: https://github.com/microsoft/vscode/issues/121343  Closing this one as a dupe of the VS Code issue.

**Closed as completed by Colengms** 2021-04-15 02:45 UTC
Labels: Language Service, Feature: Rename
