### ISSUE TITLE
VS Code doesn't show predefined launch.json files

### ISSUE THREAD

**Issue by DanielNikoofar** [microsoft/vscode-cpptools#9184] opened 2022-04-13 21:12 UTC
### Environment

- OS and version: Windows 10 19044.1586
- VS Code: 1.66.2
- C/C++ extension: v1.9.7

### Bug Summary and Steps to Reproduce

I installed mingw64 successfully.

I go to Run -> Add Configuration then choose C++(GDB/LLDB), dropdown for predefined debugging configurations doesn't show anything, and create launch.json empty.

Unfortunately, launch.json is empty.

I can build and create exe file and see the result. But I cannot debug and create launch.json.

My main problem with launch.json and it will be empty. tasks.json isn't empty and works fine.

### Additional Information

I saw another person has the same problem:
https://stackoverflow.com/questions/71705670/vs-code-doesnt-show-predefined-launch-json-fileswho

**Comment by michelleangela** [comment] 2022-04-13 21:25
@DanielNikoofar 
Thank you for reporting this issue. It is actually a duplicate of https://github.com/microsoft/vscode-cpptools/issues/9100 which we are working on to fix. Please refer to https://github.com/microsoft/vscode-cpptools/issues/9100 for further updates about the issue.

**Closed as completed by michelleangela** 2022-04-13 21:25 UTC
Labels: bug, duplicate, Language Service, tasks/build/debug
