### ISSUE TITLE
Need help with an error: "Connection to server got closed. Server will not be restarted"

### ISSUE THREAD

**Issue by jeffrey0407** [microsoft/vscode-cpptools#5831] opened 2020-07-24 06:33 UTC
**Type: LanguageService**
With Visual Studio Code I'm having the issue: Connection to server got closed. Server will not be restarted.

**Describe the bug**
- OS and Version: Windows 10 x64
- VS Code Version:1.47.2
- C/C++ Extension Version:0.29.0
-Issue: The first time I installed VSCode and C/C++ I'm getting an error that says ** Connection to server got closed. Server will not be restarted.** I'm new to vscode and coding in general, I have tried some solutions but it doesn't work for me, I reinstalled VSCode and C/C++ extensions many times but it seem doesnt work it keeps sending me this error and I dont know what to do.

**Expected behavior**

I enabled logging cpp for the language server and it says in the c/c++ log:
```
cpptools/didChangeCppProperties
Attempting to get defaults from compiler in "compilerPath" property: 'C:\TDM-GCC-64\bin\gcc.exe'
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: 'C:\TDM-GCC-64\bin\gcc.exe'
  Folder: C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE/ will be indexed
  Folder: C:/TDM-GCC-64/INCLUDE/ will be indexed
  Folder: C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE-FIXED/ will be indexed
  Folder: C:/TDM-GCC-64/X86_64-W64-MINGW32/INCLUDE/ will be indexed
  Folder: D:/CODING/ will be indexed
Populate include completion cache.
textDocument/didOpen: file:///d%3A/Coding/chao.c
Discovering files...
cpptools/activeDocumentChange: file:///d%3A/Coding/chao.c
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///d%3A/Coding/chao.c (id: 2)
cpptools/getCodeActions: file:///d%3A/Coding/chao.c (id: 3)
cpptools/getFoldingRanges: file:///d%3A/Coding/chao.c (id: 4)
cpptools/getSemanticTokens: file:///d%3A/Coding/chao.c (id: 5)
cpptools/getDocumentSymbols
  tag parsing file: D:\CODING\CHAO.C
  Processing folder (recursive): C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE/
cpptools/didChangeCppProperties
Attempting to get defaults from compiler in "compilerPath" property: 'C:\TDM-GCC-64\bin\gcc.exe'
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: 'C:\TDM-GCC-64\bin\gcc.exe'
  Folder: C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE/ will be indexed
  Folder: C:/TDM-GCC-64/INCLUDE/ will be indexed
  Folder: C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE-FIXED/ will be indexed
  Folder: C:/TDM-GCC-64/X86_64-W64-MINGW32/INCLUDE/ will be indexed
  Folder: D:/CODING/ will be indexed
cpptools/didChangeSettings
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/*.code-search
Search exclude: **/.vscode
textDocument/didOpen: file:///d%3A/Coding/chao.c
Populate include completion cache.
Discovering files...
cpptools/activeDocumentChange: file:///d%3A/Coding/chao.c
cpptools/didChangeCppProperties
cpptools/didChangeSettings
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
textDocument/didOpen: file:///d%3A/Coding/chao.c
cpptools/activeDocumentChange: file:///d%3A/Coding/chao.c
textDocument/didOpen: file:///d%3A/Coding/chao.c
cpptools/activeDocumentChange: file:///d%3A/Coding/chao.c
  Processing folder (recursive): C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE/
  tag parsing file: D:\CODING\CHAO.C
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///d%3A/Coding/chao.c (id: 2)
cpptools/getDocumentSymbols
cpptools/getCodeActions: file:///d%3A/Coding/chao.c (id: 3)
cpptools/getFoldingRanges: file:///d%3A/Coding/chao.c (id: 4)
cpptools/didChangeCppProperties
Attempting to get defaults from compiler in "compilerPath" property: 'C:\TDM-GCC-64\bin\gcc.exe'
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: 'C:\TDM-GCC-64\bin\gcc.exe'
  Folder: C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE/ will be indexed
  Folder: C:/TDM-GCC-64/INCLUDE/ will be indexed
  Folder: C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE-FIXED/ will be indexed
  Folder: C:/TDM-GCC-64/X86_64-W64-MINGW32/INCLUDE/ will be indexed
  Folder: D:/CODING/ will be indexed
cpptools/didChangeSettings
Populate include completion cache.
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/*.code-search
Search exclude: **/.vscode
textDocument/didOpen: file:///d%3A/Coding/chao.c
cpptools/activeDocumentChange: file:///d%3A/Coding/chao.c
Populate include completion cache.
cpptools/didChangeCppProperties
cpptools/didChangeSettings
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
textDocument/didOpen: file:///d%3A/Coding/chao.c
Discovering files...
cpptools/activeDocumentChange: file:///d%3A/Coding/chao.c
textDocument/didOpen: file:///d%3A/Coding/chao.c
cpptools/activeDocumentChange: file:///d%3A/Coding/chao.c
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///d%3A/Coding/chao.c (id: 2)
cpptools/getCodeActions: file:///d%3A/Coding/chao.c (id: 3)
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: file:///d%3A/Coding/chao.c (id: 4)
  Processing folder (recursive): C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE/
  tag parsing file: D:\CODING\CHAO.C
cpptools/abortRequest
cpptools/didChangeCppProperties
Attempting to get defaults from compiler in "compilerPath" property: 'C:\TDM-GCC-64\bin\gcc.exe'
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: 'C:\TDM-GCC-64\bin\gcc.exe'
  Folder: C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE/ will be indexed
  Folder: C:/TDM-GCC-64/INCLUDE/ will be indexed
  Folder: C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE-FIXED/ will be indexed
  Folder: C:/TDM-GCC-64/X86_64-W64-MINGW32/INCLUDE/ will be indexed
  Folder: D:/CODING/ will be indexed
cpptools/didChangeSettings
Populate include completion cache.
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/*.code-search
Search exclude: **/.vscode
textDocument/didOpen: file:///d%3A/Coding/chao.c
cpptools/activeDocumentChange: file:///d%3A/Coding/chao.c
Populate include completion cache.
cpptools/didChangeCppProperties
cpptools/didChangeSettings
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
textDocument/didOpen: file:///d%3A/Coding/chao.c
cpptools/activeDocumentChange: file:///d%3A/Coding/chao.c
textDocument/didOpen: file:///d%3A/Coding/chao.c
textDocument/didClose: file:///d%3A/Coding/chao.c
Discovering files...
textDocument/didOpen: file:///d%3A/Coding/hello.c
cpptools/activeDocumentChange: file:///d%3A/Coding/hello.c
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///d%3A/Coding/hello.c (id: 2)
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: file:///d%3A/Coding/hello.c (id: 3)
  Processing folder (recursive): C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE/
  tag parsing file: D:\CODING\CHAO.C
cpptools/didChangeCppProperties
Attempting to get defaults from compiler in "compilerPath" property: 'C:\TDM-GCC-64\bin\gcc.exe'
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: 'C:\TDM-GCC-64\bin\gcc.exe'
  Folder: C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE/ will be indexed
  Folder: C:/TDM-GCC-64/INCLUDE/ will be indexed
  Folder: C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE-FIXED/ will be indexed
  Folder: C:/TDM-GCC-64/X86_64-W64-MINGW32/INCLUDE/ will be indexed
  Folder: D:/CODING/ will be indexed
cpptools/didChangeSettings
Populate include completion cache.
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/*.code-search
Search exclude: **/.vscode
textDocument/didOpen: file:///d%3A/Coding/hello.c
cpptools/activeDocumentChange: file:///d%3A/Coding/hello.c
Populate include completion cache.
cpptools/didChangeCppProperties
cpptools/didChangeSettings
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
textDocument/didOpen: file:///d%3A/Coding/hello.c
Discovering files...
cpptools/activeDocumentChange: file:///d%3A/Coding/hello.c
textDocument/didOpen: file:///d%3A/Coding/hello.c
cpptools/activeDocumentChange: file:///d%3A/Coding/hello.c
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///d%3A/Coding/hello.c (id: 2)
cpptools/getFoldingRanges: file:///d%3A/Coding/hello.c (id: 3)
cpptools/getDocumentSymbols: file:///d%3A/Coding/hello.c (id: 4)
cpptools/getDocumentSymbols
  Processing folder (recursive): C:/TDM-GCC-64/LIB/GCC/X86_64-W64-MINGW32/9.2.0/INCLUDE/
  tag parsing file: D:\CODING\HELLO.C
```

**Screenshot**
![image](https://user-images.githubusercontent.com/68680222/88365830-6ecc2700-cdb1-11ea-8eec-679cfb4225a7.png)

**Additional context**
I have this problem everytime i opened vscode please help me. 
Thanks for reading my post!

**Comment by Colengms** [comment] 2020-07-24 20:45
Hi @jeffrey0407 .  I noticed the following in your log:

```
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
```

The extension appears to crash as it starts parsing files (which writes to the database).  Normally, you could reset the database using the `C/C++: Reset IntelliSense database` command, but that would require the extension to be running at the time.  You may need to delete the database directly.  If you have not modified the setting for `C_Cpp.default.browse.databaseFilename`, it should be here on Windows: `C:\Users\<username>\AppData\Roaming\Code\User\workspaceStorage\<random name>\ms-vscode.cpptools\.browse.VC.db`

You might also want to confirm that the drive the database is stored on is not out of storage space.

If that deleting the database does not address the issue, could you post the contents of your `c_cpp_properties.json`?

**Comment by tripjam** [comment] 2020-09-15 13:14
@Colengms I experience the same error as @jeffrey0407 and my debug log is almost exactly the same as his.

I've tried your suggestion to delete the database, as well as removing the extension completely according to #5806 , but the issue still persists.

May I know where is c_cpp_properties.json located?

**Comment by sean-mcmanus** [comment] 2020-09-16 01:18
c_cpp_properties.json should be under the ${workspaceFolder}/.vscode folder.

**Comment by tripjam** [comment] 2020-09-17 14:55
> c_cpp_properties.json should be under the ${workspaceFolder}/.vscode folder.

@sean-mcmanus The folder only has settings.json inside. Any further suggestions?

**Comment by sean-mcmanus** [comment] 2020-09-17 21:05
You don't have a c_cpp_properties.json, which means it's just using the defaults.

Can you attach a debugger to cpptools before it crashes? See https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv .

Or do you know how we can reproduce the crash?

**Comment by Veoramid** [comment] 2020-09-19 19:55
If I downgrade C / C ++ to 0.25 the error goes away. Since version 0.26 - the error appears
![image](https://user-images.githubusercontent.com/16515589/93687974-fb9e1300-faca-11ea-8e60-6eadbe02b1c7.png)
![image](https://user-images.githubusercontent.com/16515589/93687998-32742900-facb-11ea-9ed3-15758129e921.png)

**Comment by tripjam** [comment] 2020-09-20 08:42
I've tested from my end and the outcome is exactly the same as @Veoramid - since v0.26 the error starts to appear.

**Comment by sean-mcmanus** [comment] 2020-09-24 17:13
The "Connection to server got closed." is a generic symptom of a cpptools crash, but if started with 0.26.0, that could imply it's the same crash, but we need either repro steps or a crash call stack.

**Comment by michelleangela** [comment] 2020-12-09 18:42
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 18:42 UTC
Labels: Language Service, more info needed
