### ISSUE TITLE
Intellisense reports types and symbols as not defined even though it clearly knows them

### ISSUE THREAD

**Issue by mcilloni** [microsoft/vscode-cpptools#5480] opened 2020-05-13 09:34 UTC
**Type: LanguageService**

Every once in a while, only with certain C++ files, Intellisense starts throwing definition errors , such as:
- putting wiggly lines under a type it is clearly aware of (i.e. doing CTRL+click correctly opens the right definition, or hover shows the correct symbol)

- failing to correctly match the right symbol (i.e. mixing up members and variables from unrelated structures or namespaces), with ctrl-click showing multiple possible definitions (even though some are clearly wrong)

**Describe the bug**
- OS and Version: Arch Linux 
- VS Code Version: 1.45.0
- C/C++ Extension Version: 0.28.0
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Screenshots**

![example](https://i.imgur.com/52h7LM7.png)

**Additional context**
GCC correctly compiles and accepts the code. I cannot give out code samples because I'm under NDA, but the project uses the ESP32 toolchain (GCC 8.2) and it's quite large (lots of quite complex C++17, with type traits, inference, constexpr and SFINAE)

**Comment by michelleangela** [comment] 2020-05-13 17:50
@mcilloni , could you provide the following 2 logs:

1. Log output from the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
2. Log output from running the command `C/C++: Log Diagnostics`

And did these issues occur in 0.27.1 or are they a regression in 0.28.0 for your project?

**Comment by mcilloni** [comment] 2020-05-14 08:17
Here you are:

1. [dbglog.txt](https://github.com/microsoft/vscode-cpptools/files/4626859/dbglog.txt)
2. [diagnostics.txt](https://github.com/microsoft/vscode-cpptools/files/4626860/diagnostics.txt)

I had to `sed` away a few names for the aforementioned reasons.

I've also tested with the same codebase under Windows (same version of vscode, same version of cpptools, same version of libraries and code, and the Windows build of the same version of xtensa-esp32-elf-gcc) and it has the same issues. Downgrading to 0.27.1 doesn't change anything.

**Comment by mcilloni** [comment] 2020-05-14 09:51
Update: I let vscode use a `compile_commands.json` file when asked, and it seems like the issue  immediately stopped showing. If I delete the file, it starts happening again. The main issue I'm having right now is that a few scripts I use delete the build directory quite often, and if I keep it set without recreating it with CMake, Visual Studio Code starts complaining a lot; I also don't get why Intellsense breaks if I choose to not use compile_commands.json.

**Comment by sean-mcmanus** [comment] 2020-05-15 02:13
The compile_commands.json might have better configuration info in it. If you run C/C++: Log Diagnostics with and without compileCommands set you can compare how the includes/defines are different. Maybe you could modify your scripts to copy the compile_commands.json to a location that doesn't get deleted (or restore it after the folder is deleted).

FYI, we have a known high hitting IntelliSense regression crash with 0.28.0 which may cause some of the symptoms you describe: https://github.com/microsoft/vscode-cpptools/issues/5486 .

**Comment by mcilloni** [comment] 2020-05-15 10:12
> FYI, we have a known high hitting IntelliSense regression crash with 0.28.0 which may cause some of the symptoms you describe: #5486 .

I've tried downgrading to 0.27.1 but it hasn't really changed anything, the behaviour I see does not change from what I get from 0.28.0

**Comment by sean-mcmanus** [comment] 2020-05-15 19:11
It looks like your intelliSenseMode should be "gcc-x86" and not "gcc-x64" since your compiler output indicates it's targetting 32-bit.

Without compile_commands.json, the include paths you're using may have the incorrect order, because you're using "${workspaceFolder}/**" which generates includes recursively in a non-deterministic order.

Does it complain about missing headers?

If you get squiggles that mean the IntelliSense parsing hit problems (from full parsing of the TU), but things like Go to Def and hover may still work via using the global symbols that are parsed in a different manner (which does a "fuzzy" parsing that can succeed without resolving headers or macros).

**Comment by mcilloni** [comment] 2020-05-19 14:57
Yes, it does indeed complain about missing headers every once in a while. I've tried changing the `intelliSenseMode` to `gcc-x86` and I've been having no issues so far. I also installed the CMake extension and I discovered it can be used as a `configurationProvider`, thus solving the compile commands deletion issue, which is nice.

**Closed as completed** 2021-01-21 21:33 UTC
Labels: Language Service, more info needed
