### ISSUE TITLE
More than one instance of overloaded function "std::move" matches the argument list

### ISSUE THREAD

**Issue by hakula139** [microsoft/vscode-cpptools#11448] opened 2023-09-20 07:34 UTC
### Environment

- OS and Version: macOS Ventura 13.5.2 (22G91)
- VS Code Version: 1.82.2
- C/C++ Extension Version: v1.17.5
- If using SSH remote, specify OS of remote machine: No

### Bug Summary and Steps to Reproduce

Bug Summary:

After upgrading to Xcode SDK 15, I start getting the following error when using `std::move`:

MRE:

```cpp
#include <string>
#include <utility>
#include <vector>

int main() {
  std::vector<std::string> v;
  std::string s = "a";
  v.emplace_back(std::move(s));
  return 0;
}
```

See intellisense error:

<img width="1483" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/9496568/cdcab701-da1e-451c-a390-f0e62e3b6dc4">

```text
more than one instance of overloaded function "std::move" matches the argument list:
function template "std::__1::__libcpp_remove_reference_t<_Tp> &&std::__1::move(_Tp &&__t) noexcept" (declared at line 27 of "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/move.h")
function template "std::__1::__libcpp_remove_reference_t<_Tp> &&std::__1::move(_Tp &&__t) noexcept" (declared at line 27 of "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/move.h")
function template "std::__1::__libcpp_remove_reference_t<_Tp> &&std::__1::move(_Tp &&__t) noexcept" (declared at line 27 of "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/move.h")
argument types are: (std::__1::string)
```

While compiling this code with Apple clang++ is just fine with no errors.

<img width="836" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/9496568/188f534a-d8c1-4c6a-8a8b-65e5c346465c">

Expected behavior:

There should be no error in this code.

### Configuration and Logs

- Configurations in `c_cpp_properties.json`

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "intelliSenseMode": "macos-clang-arm64",
            "compilerPath": "/usr/bin/clang++",
            "cStandard": "c17",
            "cppStandard": "c++20"
        }
    ],
    "version": 4
}
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

```text
-------- Diagnostics - 9/20/2023, 3:25:35 PM
Version: 1.17.5
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "/Users/hakula/GitHub/Online-Judge-Solutions/C++/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "intelliSenseMode": "macos-clang-arm64",
    "compilerPath": "/usr/bin/clang++",
    "cStandard": "c17",
    "cppStandard": "c++20",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "/usr/bin/clang++",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "/Users/hakula/GitHub/Online-Judge-Solutions/C++/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.17.5.0
Translation Unit Mappings:
[ /Users/hakula/GitHub/Online-Judge-Solutions/C++/LeetCode/0.cpp ]:
    /Users/hakula/GitHub/Online-Judge-Solutions/C++/LeetCode/0.cpp
Translation Unit Configurations:
[ /Users/hakula/GitHub/Online-Judge-Solutions/C++/LeetCode/0.cpp ]:
    Process ID: 42472
    Memory Usage: 216 MB
    Compiler Path: /usr/bin/clang++
    Includes:
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++20
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=160000
Total Memory Usage: 216 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 9723
```

- Logs from the language server logging

[language_server.log](https://github.com/microsoft/vscode-cpptools/files/12670090/language_server.log)

**Comment by michelleangela** [comment] 2023-09-26 02:08
Determined that this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/11463 when the move templates are reduced.

**Closed as completed** 2023-09-26 02:08 UTC
Labels: bug, duplicate, Language Service, Visual Studio, verified
