### ISSUE TITLE
Intellisense update takes forever with ranges-v3 (with high CPU usage).

### ISSUE THREAD

**Issue by greblus** [microsoft/vscode-cpptools#4414] opened 2019-10-10 11:12 UTC
After installation of ranges-v3 headers for my C++ project updating of Intellisense takes forever
with a very high CPU usage. I tried it on Linux and Windows, both with VS Code version 1.39.0, cpptools 0.26.0-insiders3.

My only workaround for now to keep VS Code somewhat usable is to remove ranges-v3 from include path and compile the project by hand with -I compiler flag pointing to ranges headers placed in some optional location.

**Comment by bobbrow** [comment] 2019-10-10 16:28
Ranges v3 has definitely caused IntelliSense some trouble in the past (see: https://developercommunity.visualstudio.com/content/problem/396030/vs2017-v1593-c-intellisense-is-very-slow.html).  We use the same engine as Visual Studio 2019, so I expected most of the performance issues to be fixed. 

One of the suggestions is to use the [range-v3-vs2015](https://github.com/microsoft/Range-V3-VS2015) fork of the library.

**Comment by ytimenkov** [comment] 2019-10-25 13:55
It's unclear whether this is fixed or not? Because cpptools 0.26.0 can't ~couple~ cope (on-screen keyboard :|) with ranges 0.9.1...

**Comment by sean-mcmanus** [comment] 2019-10-26 02:42
"can't couple"? Do you mean you get squiggle errors?

**Comment by ytimenkov** [comment] 2019-10-26 05:51
It works like a charm in general, but I've added a simple call to views::trabsform and when I open the file this happens:
1. IntelliSense process takes 100% cpu
2. Hovering on things just shows "loading"
3. Autoformatting does nothing.

I think at first I got squiggles under `view::` and `|` complaining "no candidate for some brace-initialized thing" and symptoms above. Then I killed LS process and tried to restart code but then it looked totally disfunctional.

Maybe some kind of regression? I could try to make a single preprocessed file to reproduce...

For now I have to give up on ranges because it doesn't increase productivity as Code 🙂

**Comment by sean-mcmanus** [comment] 2019-10-28 22:26
Yeah, if you could provide a preprocessed repro file that would help us.

**Comment by sean-mcmanus** [comment] 2020-01-22 22:11
Some performance improvement work was done for range-v3 with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3 , but there is still room for better performance...not sure if it's sufficient to close this issue or not.

**Comment by greblus** [comment] 2020-01-23 22:38
I confirm - It works great now, thank you! :)

**Closed as completed** 2020-01-24 22:49 UTC
Labels: Language Service, fixed, performance, parser, Visual Studio
