### ISSUE TITLE
How to change the default code snippet style?

### ISSUE THREAD

**Issue by pCandKa** [microsoft/vscode-cpptools#12514] opened 2024-07-25 15:57 UTC
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/12513

<div type='discussions-op-text'>

<sup>Originally posted by **pCandKa** July 25, 2024</sup>
![image](https://github.com/user-attachments/assets/ea2a712e-ec6c-4dfe-b505-287c9594df54)
I want the effect of the top half of the image.</div>

**Comment by sean-mcmanus** [comment] 2024-07-25 19:05
@pCandKa There isn't a way to change the snippet style currently, other than running a formatter afterwards. This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/5538 .

**Closed as not planned by sean-mcmanus** 2024-07-25 19:05 UTC
Labels: duplicate
