### ISSUE TITLE
cpptools generates file with special characters

### ISSUE THREAD

**Issue by monzool** [microsoft/vscode-cpptools#217] opened 2016-09-09 06:50 UTC
When launching vscode with the c/c++ plugin, it generates a file with special characters: `?{ER@?҂@`

To reproduce:

``` bash
./tmp ❯❯❯ ll
drwxrwxr-x 2 skv skv 4096 Sep  9 08:11 ./
drwxrwxr-x 3 skv skv 4096 Sep  9 08:11 ../
./tmp ❯❯❯ code --list-extensions
./tmp ❯❯❯ code
./tmp ❯❯❯ ll
drwxrwxr-x 2 skv skv 4096 Sep  9 08:11 ./
drwxrwxr-x 3 skv skv 4096 Sep  9 08:11 ../
./tmp ❯❯❯ code --install-extension ms-vscode.cpptools
Found 'ms-vscode.cpptools' in the marketplace.
Installing...
Extension 'ms-vscode.cpptools' v0.9.1 was successfully installed!
./tmp ❯❯❯ code
./tmp ❯❯❯ ll
drwxrwxr-x 2 skv skv 4096 Sep  9 08:13 ./
drwxrwxr-x 3 skv skv 4096 Sep  9 08:11 ../
-rw-rw-r-- 1 skv skv    0 Sep  9 08:13 ?{ER@?҂@8
```

Not a big problem per say, if it was not so that it breaks svn :-(

``` bash
./tmp ❯❯❯ svn st
svn: E000022: Error converting entry in directory './tmp' to UTF-8
svn: E000022: Valid UTF-8 data
(hex: 01 7b 45 52 40)
followed by invalid UTF-8 sequence
(hex: b8 d2 82 40)
```

rm also barf on the filename, so I have to delete by inode number

OS: Kubuntu 16.04.1 LTS (Xenial Xerus)

``` bash
❯❯❯ uname -srvpo
Linux 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:00:59 UTC 2016 i686 GNU/Linux
```

Code ver: 

``` bash
❯❯❯ code --version
1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877)
```

(same result with code ver 1.4)

**Comment by pieandcakes** [comment] 2016-09-12 22:47
@sean-mcmanus @sridmad Can one of you take a look and see if the language service is generating this file? I see it on my machine too but its before debugging.

**Comment by sean-mcmanus** [comment] 2016-09-13 20:44
I'm not able to repro this bug on Ubuntu 14.

**Comment by jgoshi** [comment] 2016-09-13 20:53
I'm not able to repro this either (Ubuntu 16).

**Comment by sridmad** [comment] 2016-09-14 20:23
What is the full path of the root folder? I suspect there may be a bug in handling some Unicode characters

**Comment by monzool** [comment] 2016-09-29 09:59
My home directory is `/home/skv` and I am running a US language Kubuntu with no directories using any unicode characters 

``` bash
❯❯❯ echo ${HOME}
/home/skv
```

My locale is mostly non-US though:

``` bash
/tmp ❯❯❯ localectl
   System Locale: LANG=en_US.UTF-8
                  LANGUAGE=en_US:en
                  LC_NUMERIC=da_DK.UTF-8
                  LC_TIME=da_DK.UTF-8
                  LC_MONETARY=da_DK.UTF-8
                  LC_PAPER=da_DK.UTF-8
                  LC_NAME=da_DK.UTF-8
                  LC_ADDRESS=da_DK.UTF-8
                  LC_TELEPHONE=da_DK.UTF-8
                  LC_MEASUREMENT=da_DK.UTF-8
       VC Keymap: n/a
      X11 Layout: dk
       X11 Model: pc105
```

``` bash
/tmp ❯❯❯ code --version
1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27)
```

**Comment by sean-mcmanus** [comment] 2017-03-16 13:46
@monzool Did you repro the bug with 32-bit Linux?

**Comment by sungb** [comment] 2017-03-17 03:43
@sean-mcmanus thank you for follwing up.

VM Ware Fusion 8.5.3 hosted on macOS 10.12.3

VM Guest OS info below. Always reproducible.

```
 ~/tmp/test$ file /sbin/init
/sbin/init: ELF 32-bit LSB  shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=c394677bccc720a3bb4f4c42a48e008ff33e39b1, stripped

 ~/tmp/test$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

 ~/tmp/test$ localectl
   System Locale: LANG=en_US.UTF-8
       VC Keymap: n/a
      X11 Layout: n/a
       X11 Model: SKIP

 ~/tmp/test$ code --version
1.10.2
8076a19fdcab7e1fc1707952d652f0bb6c6db331
```

**Comment by pegomes** [comment] 2017-03-17 03:55
I get this same problem. I am running a VirtualBox VM hosted on macOS 10.12.3.
VirtualBox version 5.0.32 r112930
VM OS is Ubuntu 14.04.5 LTS
VS Code is v 1.10.2

**Comment by managedata** [comment] 2017-03-17 06:58
I have the same problem. Configuration:

Host: Windows 7 Professional SP 1
VMWare Workstation 11.1.4 build- 3848939
Guest: Debian 8 (jessie)
VSCode 1.8.1

localectl output on Debian:
System Locale: LANG=de_DE.UTF-8
       VC Keymap: n/a
      X11 Layout: de
       X11 Model: pc105

**Comment by monzool** [comment] 2017-03-17 07:48
@sean-mcmanus Sorry, it seems that I am no longer able to reproduce this issue. 

Have not tried since my followup on the ticket but, of the top of my head, the "only" things changed are:
1) updated to vscode-1.10.1
2) an update to vmware 12.5.2 build-4638234
3) whatever `apt upgrade` brought me

**Comment by sungb** [comment] 2017-03-17 08:46
BTW, with the newest 0.10.4 cpp-tools, the name of the empty garbage file is shortened to one char.  It used to be longer.

**Comment by sean-mcmanus** [comment] 2017-03-17 16:21
This bug is really strange and I don't see any place in our code where we could be writing a bogus file. It seems like the file is being created by some external library/process/OS in response to some unknown event. If you guys are really reproing this bug with a 32-bit OS (and not a 64-bit OS) then it means the bug is in our javascript code. We're still trying to find a repro machine setup, but if you're interested in trying to diagnose/fix this yourself, you could look at and modify the javascript to try to find/remove the code that is causing the file to be generated, at ~\.vscode\extensions\ms-vscode.cpptools-0.10.4\out\src . I'm using Ubuntu 14/64-bit on a VM and it's not reproing.

**Comment by sungb** [comment] 2017-10-17 04:50
@sean-mcmanus , looks like this bug has been fixed somewhere along the version because it is no longer reproduced on the system which showed the problem, and it works well with the latest vscode version below, with cpptools (v0.13.1) enabled.

Hello, @managedata  , @pegomes how is it on your system with the latest vscode?

Version 1.17.1
Commit 1e9d36539b0ae51ac09b9d4673ebea4e447e5353
Date 2017-10-10T14:21:23.673Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

**Comment by sungb** [comment] 2017-10-26 09:09
The issue re-appeared with the cpptools 0.14.0

**Comment by sean-mcmanus** [comment] 2017-10-26 17:52
@sungb 0.14.0 caused a database reset, so the bogus file might be created when the database is initialized. We are unable to repro this. If you know of any Linux tools that can track down which process is creating that file that might help.

**Comment by sungb** [comment] 2017-10-27 07:58
@sean-mcmanus sorry not sure 
https://groups.google.com/forum/#!topic/comp.unix.programmer/e7UkhzU7R1I

**Comment by sungb** [comment] 2017-11-23 05:37
This issue is fixed in Version 0.14.2 
CC: @sean-mcmanus  @bobbrow

**Comment by sean-mcmanus** [comment] 2017-11-27 19:34
@sungb Okay, let us know if it repros again and we can reopen this.

**Closed as completed by sean-mcmanus** 2017-11-27 19:34 UTC
Labels: bug, Language Service

**Comment by MaxXor** [comment] 2017-12-10 17:00
I just installed vscode-cpptools and saw a strange file being created in my workspace. Stumbled upon this issue here. Using latest version of the extension and vscode itself on Debian 9 32bit in VMware.

**Comment by sean-mcmanus** [comment] 2017-12-11 18:43
@MaxXor We don't support 32-bit Linux yet, but we will in our pending 0.14.4 we plan to release later today (or later, if we hit any last minute delays), so you should try that. I've seen the bogus file get generated on VMs, but I wasn't able to get a repro with our latest bits, but I'll need to investigate more to figure out the exact repro.

**Comment by sungb** [comment] 2017-12-13 07:59
@MaxXor 0.14.4 seems good in my xubuntu 32bit in VMWare environment.  

The issue came back in the 0.14.3.   But the latest 0.14.4 seems good.
Hope the issue doesn't come back...
CC: @sean-mcmanus
