### ISSUE TITLE
IntelliSense doesn't work (crashes)

### ISSUE THREAD

**Issue by Samega7Cattac** [microsoft/vscode-cpptools#10636] opened 2023-03-06 12:14 UTC
### Environment

- OS and Version: Arch Linux
- VS Code Version: 1.76.0
- C/C++ Extension Version: 1.14
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:
There's dozens of "cpptools" on the output tab, every single one with dozens of errors.
An example of one of them:
```
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/didChangeCppProperties failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/queryTranslationUnitSource failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/getInlayHints failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/getInlayHints failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/getFoldingRanges failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/getFoldingRanges failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/getSemanticTokens failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/getSemanticTokens failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/getDocumentSymbols failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending request cpptools/getDocumentSymbols failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] The language server crashed. Restarting...
[Error - 12:12:00 PM] Sending document notification textDocument/didOpen failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:12:00 PM] Sending document notification textDocument/didOpen failed
  Message: Client is not running
  Code: -32096 
```
With time they increase rapidly.

In the tab of the Configuration Warnings:
```
[3/6/2023, 12:08:05 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:08:05 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:08:08 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:08:08 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:08:08 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:08:08 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:08:08 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:08:08 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:08:08 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:08:08 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:08:08 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:08:08 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:08:08 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:08:08 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:01 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:01 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:01 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:01 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:01 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:01 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:01 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:01 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:01 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:01 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:01 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:01 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:01 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:01 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:01 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:01 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:01 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:01 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:01 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:01 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:01 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:01 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:02 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:02 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:02 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:02 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:12:02 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:12:02 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
[3/6/2023, 12:16:03 PM] For C++ source files, the cppStandard was changed from "gnu++20" to "".
[3/6/2023, 12:16:03 PM] For C source files, the cStandard was changed from "gnu17" to "".
```

Steps to reproduce:
1. Open workspace with several projects
2. Open a .cpp file
3. IntelliSense doesn't work

Expected behavior:
IntelliSense to show something on hover or autocomplete

### Configuration and Logs

```shell
c_cpp_properties.json:
(this is an example of one of the projects config, they dont diff much)

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "${env:PROJECT_INSTALL_PATH}/include/",
                "/usr/include/glibmm-2.68/",
                "/usr/lib/glibmm-2.68/include",
                "/usr/include/glib-2.0/",
                "/usr/lib/glib-2.0/include",
                "/usr/include/gtkmm-4.0",
                "/usr/lib/gtkmm-4.0/include",
                "/usr/include/sigc++-3.0",
                "/usr/lib/sigc++-3.0/include",
                "/usr/lib/pangomm-2.48/include",
                "/usr/include/pangomm-2.48",
                "/usr/include/pango-1.0",
                "/usr/include/harfbuzz",
                "/usr/include/giomm-2.68",
                "/usr/lib/giomm-2.68/include",
                "/usr/include/cairomm-1.16",
                "/usr/lib/cairomm-1.16/include",
                "/usr/include/cairo",
                "/usr/include/freetype2",
                "/usr/include/gtk-4.0",
                "/usr/include/gdk-pixbuf-2.0",
                "/usr/include/graphene-1.0",
                "/usr/lib/graphene-1.0/include",
                "/usr/include/botan-2"
            ],
            "cStandard": "gnu17",
            "cppStandard": "gnu++20",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

C/C++ logs:
[cpptools_logs.txt](https://github.com/microsoft/vscode-cpptools/files/10898033/cpptools_logs.txt)
```


### Other Extensions

_No response_

### Additional context

_No response_

**Comment by alexvorndran** [comment] 2023-03-06 18:54
I can confirm that downgrading to `1.14.3` fixed the issue for me (Ubuntu 18.04).

VS Code Version information:

```
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:25:16.105Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.4.0-109-generic
Sandboxed: No
```

**Comment by Colengms** [comment] 2023-03-06 20:58
Hi @Samega7Cattac .  Your log seems a bit unusual to me.  Am I correct to infer that you reproduced this issue with a multi-root workspace containing 10 workspace folders?  I see a _lot_ of occurrences of `Custom browse configuration received`, indicating that the configuration provider(s) are flooding the C/C++ extension with these messages.  Did this issue arise with a specific version of the C/C++ Extension or CMake Tools?  If so, can you let us know which specific version(s) incurred the issue?

Hi @KagaJiankui .  Based on your description, I'm not sure if you're seeing the same crash as this issue was opened to track.  The stack you provided seems to point to an extension named `draivin.hsnips-0.2.8`.  If the issue does not occur with the C/C++ Extension installed, can you confirm whether the issue occurs with `draivin.hsnips` removed instead?  That extension does not appear to be intended to interact with the C/C++ Extension, so it's unclear how these are are related.  Is there any other information you can provide, such as the C/C++ extension log output (with `"C_Cpp.loggingLevel": "Debug"` set) leading up to the failure?  (Also, as this issue seems different, could you open a new issue?)

Hi @alexvorndran .  Can you confirm whether you're experiencing the same issue as Samega7Cattac or KagaJiankui?  As there could be multiple root causes for crashes, consider opening a new issue with additional information.

**Comment by Samega7Cattac** [comment] 2023-03-06 22:03
> Am I correct to infer that you reproduced this issue with a multi-root workspace containing 10 workspace folders?

Yes there's several projects in that workspace and each one has a c_cpp config file.

> Did this issue arise with a specific version of the C/C++ Extension or CMake Tools? If so, can you let us know which specific version(s) incurred the issue?

I don't remember when it started happening but max a weeks or week and half ago, sometimes I hold off some updates while I have unfinished work so I can't tell u accurately when it started.

**Comment by KagaJiankui** [comment] 2023-03-08 05:16
> The stack you provided seems to point to an extension named `draivin.hsnips-0.2.8`. If the issue does not occur with the C/C++ Extension installed, can you confirm whether the issue occurs with `draivin.hsnips` removed instead?

After uninstalling and re-installing the `draivin.hsnips-0.2.8` extension on my Windows 11 laptop, Ubuntu 22.04 WSL hosted on Win11 laptio and a native Ubuntu 22.04 laptop, the stack I posted seems to be only related to the `draivin.hsnips-0.2.8` extension rather than the C/C++ extension, and the working status of the C/C++ extension has no relationship to the status of the `draivin.hsnips-0.2.8` extension.

Additionally, the `1.14.4` version of C/C++ extension working fine on the native Ubuntu 22.04 laptop, but the extension crashes on Win11 laptop and no logging message emitted even with `"C_Cpp.loggingLevel": "Debug"` set.

**Comment by alexvorndran** [comment] 2023-03-09 07:39
Hi @Colengms! Thanks for looking into this.

> [...] Can you confirm whether you're experiencing the same issue as Samega7Cattac or KagaJiankui? As there could be multiple root causes for crashes, consider opening a new issue with additional information.

The description of Samega7Cattac seems to fit what I saw. I too have a multi-root workspace (6 related project folders). I don't have the original logs at hand and I'm a bit hesitant to switch back to `1.14.4` at the moment, but searching for `Pending response rejected since connection got disposed` in Google originally lead me to this issue and I remember that the log looked something like the one in the opening post.

**Comment by rajasrijan** [comment] 2023-03-11 15:36
I see this issue too. I too have multi-root workspace. Both 1.14.3 and 1.14.4 are not working for me.
This started happening after updating vscode itself, not sure if extension got updated.

**Comment by rdlaner** [comment] 2023-03-13 21:11
I'm having the same issue as well. The only difference I can see is that the C/C++ Output logs have a lot of these errors:
```
tag parsing error (this can be ignored unless symbols can't be found):
    line 497 (col. 50): error: expected a ')'
    
tag parsing error (this can be ignored unless symbols can't be found):
    line 15 (col. 1): error: expected a file name
```

And the cpptools Output logs show a lot of these errors:
```
[Error - 1:34:55 PM] Sending request cpptools/getSemanticTokens failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getInlayHints failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getInlayHints failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getInlayHints failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getInlayHints failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request textDocument/documentHighlight failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request textDocument/definition failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request textDocument/hover failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getDocumentSymbols failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getInlayHints failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getInlayHints failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getInlayHints failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request textDocument/hover failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request textDocument/documentHighlight failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getInlayHints failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getFoldingRanges failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] Sending request cpptools/getCodeActions failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:34:55 PM] The language server crashed. Restarting...
```

**Comment by Jasonlhy** [comment] 2023-03-16 08:46
I have the same problem too using multiple root workspace

**Comment by Samega7Cattac** [comment] 2023-03-16 16:09
I have noticed that most of the errors appears when I try to compile the projects, second to opening files and saving

**Comment by sfariaNG** [comment] 2023-03-16 17:34
I can confirm that downgrading to 1.14.3 also fixed it for me. I had many cpptools entries in the dropdown with the same errors listed above and this is also a multi-root workspace.

**Comment by sean-mcmanus** [comment] 2023-03-16 17:39
Has anyone tried 1.15.0? Is anyone able to attach a call stack to get a crash or determine what the repro requirement is? We've tested with multi-root projects and haven't hit the crash yet. It also sounds like there might be multiple issues.

**Comment by sfariaNG** [comment] 2023-03-16 19:17
@sean-mcmanus After reverting to 1.14.3, cleaning and rebuilding everything Intellisense works again. It also continues to work after updating to 1.15.0 and 1.14.4 without a clean and rebuild. Unfortunately I don't have the time to do another clean and rebuild at this point, but will report back if I do. I did try resetting the Intellisense database on 1.14.4, but it still worked afterward.

**Comment by EmbeddedBacon** [comment] 2023-03-16 22:47
I see this issue also us v1.14.4.  I assume 1.15.0 is pre-release?   @sean-mcmanus , how do I get the call stack info for you?

**Comment by sean-mcmanus** [comment] 2023-03-16 22:56
1.15.0 is pre-release.

I have found a crash repro in the multi-root scenario. I don't know for certain which users are hitting that one or not. The crash call stack would determine if it's the same crash I'm working on fixing, but it may not be necessary.

If you can attach a debugger to the cpptools process under some condition in which it doesn't crash and then trigger the crash you may be able to get a crash call stack: https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

**Comment by Samega7Cattac** [comment] 2023-03-17 12:54
@sean-mcmanus updating to 1.15 and clean rebuild solved the issue here too.

**Comment by EmbeddedBacon** [comment] 2023-03-20 18:20
Using the debug session provided by @sean-mcmanus , I attached the debugger and waited for cpp to crash and it did.  Unfortunately, the debugger detached and I was unable to get the call stack.


Program terminated with signal SIGKILL, Killed.
The program no longer exists.
Debugger has disconnected from the program '/users/mrhicks/.vscode-server/extensions/ms-vscode.cpptools-1.14.4/bin/cpptools'.

**Comment by sean-mcmanus** [comment] 2023-03-20 18:33
@EmbeddedBacon Is that on Mac or Linux?

**Comment by EmbeddedBacon** [comment] 2023-03-20 18:38
@sean-mcmanus, sorry, I am using a Windows 10 Enterprise remoting (i.e., ssh) into a Linux system (Fedora release 34).  After I remoted in, I attached the debugger then just let the tools parse the project.  Nothing special really.

**Comment by EmbeddedBacon** [comment] 2023-03-20 22:33
Okay, but this happens all the time.  My project has auto generated hardware header files that can be several hundred megs.   So, is there a way to increase the timeout?  I often see the parsing stuck.  How can I find out where it is getting stuck to help it along?

**Comment by sean-mcmanus** [comment] 2023-03-20 23:16
@EmbeddedBacon The process killing we do should only occur if the message from the TypeScript side in 4 minutes, which seems very unlikely. You could bypass that by modifying the installed package.json "version" field by adding a "-main" to the end of the number, like at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/package.json#L5 . If you're still getting the issue after that, then some external process might be killing the cpptools process. You might also want to try 1.15.0, since that has a bunch of bug fixes.

**Comment by EmbeddedBacon** [comment] 2023-03-21 22:16
@sean-mcmanus, I upgraded to 1.15.0 Pre-Release and I am still seeing these error messages

[Error - 3:11:10 PM] Sending request cpptools/getDocumentSymbols failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:11:10 PM] Sending request textDocument/completion failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:11:10 PM] Sending request cpptools/getDocumentSymbols failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:11:10 PM] The language server crashed. Restarting...

**Comment by sean-mcmanus** [comment] 2023-03-23 00:12
We fixed some crashes and a deadlock with multiroot workspaces with 1.15.1 (https://github.com/microsoft/vscode-cpptools/releases/tag/v1.15.1), but it's possible you may be hitting a different crash, in which case it would be helpful to open a separate issue to track that, preferably with a call stack or other repro details so we can identify where it's crashing.

**Comment by EmbeddedBacon** [comment] 2023-03-24 01:38
Saw this today.  When checking the hints each output show the server crashed

![image](https://user-images.githubusercontent.com/42427056/227402391-56dc074e-9784-480d-9ea2-b36cef4c455f.png)

**Comment by sean-mcmanus** [comment] 2023-03-24 01:48
@EmbeddedBacon With what version? 1.15.1? Are you able to get a call stack or are you just seeing the SIGKILL still?

We have 1 known crash with recursive environment variables at https://github.com/microsoft/vscode-cpptools/issues/10704 .

**Comment by EmbeddedBacon** [comment] 2023-03-24 01:56
@sean-mcmanus , I didn't have the debugger attached since most messages I had seen in the past were the sigkill.  I am using the most recent version, 1.15.1.  This is on a Fedora system using remote ssh.  We had rather larger hardware header files which are several hundred megs.   I always feel the header files are too large for the cpptools to handle, at least that is my gut feeling

**Comment by sean-mcmanus** [comment] 2023-03-24 18:26
@EmbeddedBacon You may be hitting the C_Cpp.intelliSenseMemoryLimit, so you could try increasing that. Another thing to try is setting C_Cpp.intelliSenseCacheSize to 0 (in case the issue is related to the cache).

![image](https://user-images.githubusercontent.com/19859882/227609156-a4165da7-3528-4e7a-96a9-30da11e0ea4d.png)

**Comment by EmbeddedBacon** [comment] 2023-03-29 22:44
Mr. @sean-mcmanus , sorry for the delay, but I don't see either of those options either in the main Settings interface

![image](https://user-images.githubusercontent.com/42427056/228684424-b0262e27-a0dc-456c-8c05-0526e587ce4a.png)

or within the json file.

![image](https://user-images.githubusercontent.com/42427056/228684315-1a8873b6-526a-4703-acba-e6ad353bb237.png)

What am I doing wrong?

**Comment by sean-mcmanus** [comment] 2023-04-03 23:31
@EmbeddedBacon You need to change the setting in the "remote" section instead of the "user" section.

**Comment by EmbeddedBacon** [comment] 2023-04-05 20:51
Mr. @sean-mcmanus , I am still seeing the issue after setting the configuration to the following

![image](https://user-images.githubusercontent.com/42427056/230208539-78e1b707-8829-4fe0-bb9a-924c8ecd2d94.png)

Is there another method of me debugging and seeing what is going on?

**Comment by sean-mcmanus** [comment] 2023-04-05 21:33
@EmbeddedBacon Have you ran something like "top" to see the CPU/memory usage of the cpptools-srv process over time?

**Comment by EmbeddedBacon** [comment] 2023-04-05 22:08
Yes, I have looked at it in the past.  It is always running high

![image](https://user-images.githubusercontent.com/42427056/230222691-a3a54fa0-69ae-44c1-8703-0bca4d783c2e.png)

**Comment by sean-mcmanus** [comment] 2023-04-05 22:47
@EmbeddedBacon That is cpptools. I was wondering about cpptools-srv (the one that is crashing or exiting out for some unknown reason). I didn't think there was an issue with cpptools.

**Comment by EmbeddedBacon** [comment] 2023-04-06 00:36
Mr. @sean-mcmanus , okay, perhaps I captured the data correctly this time.  Here is the htop view 

![image](https://user-images.githubusercontent.com/42427056/230243567-ad11f135-2522-48e2-bd7b-f164cb39b92a.png)

I used psrecord to capture cpu and memory using `psrecord 167317 --log cpp-srv.log --interval 1 --plot cpp-srv-167317.png`

This is the graph of the captured data

![image](https://user-images.githubusercontent.com/42427056/230243674-fad45ccf-aeae-48de-aaeb-b294b4ce5d2c.png)

**Comment by sean-mcmanus** [comment] 2023-04-06 00:57
@EmbeddedBacon Your OS an x64 Linux and not 32-bit arm, right? The memory and CPU usage looks "normal" and doesn't appear to indicate a crash or out of memory. 2.5 GB is above normal, but doesn't necessarily indicate an error if the TU is big enough. Where in the time graph do you get the crash logging?

**Comment by EmbeddedBacon** [comment] 2023-04-06 21:31
Mr. @sean-mcmanus , yes, the distro is Fedora release 34 (Thirty Four).  Psrecord was attached to the process until it closed so the graph represents the entire time line (or as quick as I could find the pid of the process and launch the command).

**Comment by EmbeddedBacon** [comment] 2023-04-28 23:31
@sean-mcmanus , is there something else I can collect or some other information/data I can collect for this?

**Comment by sean-mcmanus** [comment] 2023-04-29 00:02
Have you tried setting the C_Cpp.intelliSenseMaxMemory (your previous screenshot just show C_Cpp.intelliSenseMemoryLimit set, which has a different effect)? The sigkill could be due the memory limit across all TUs getting hit, i.e. if you have multiple files open.

**Comment by EmbeddedBacon** [comment] 2023-04-29 01:03
@sean-mcmanus , I don't think C_Cpp.intelliSenseMaxMemory was mentioned previously, but I did increase it to 16384.  If I still see that same issue, what is the max values I can set C_Cpp.intelliSenseMaxMemory and  C_Cpp.intelliSenseMemoryLimit,?  Right now both are set to 16K.

**Comment by sean-mcmanus** [comment] 2023-04-29 01:08
C_Cpp.intelliSenseMaxMemory has a higher limit of 65536. You have C_Cpp.intelliSenseMemoryLimit set to the max.

**Comment by sean-mcmanus** [comment] 2023-05-01 23:49
We're closing this as fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.15.4 . For any remaining issues, we or you could move them to new issues to track.

**Closed as completed by sean-mcmanus** 2023-05-01 23:49 UTC
Labels: bug, Language Service, fixed, quick fix, reliability
