### ISSUE TITLE
#6855 regressed on 1.11.0

### ISSUE THREAD

**Issue by flplv** [microsoft/vscode-cpptools#9530] opened 2022-07-01 14:25 UTC
### Environment

- OS and version: Linux, ubuntu 20.04
- VS Code: 1.68.1
- C/C++ extension: 1.11.0
- OS and version of remote machine (if applicable): ubuntu 18.04, 

### Bug Summary and Steps to Reproduce

The bug reported at  #6855 seems to have been regressed.  I can use the exact same steps to reproduce and have the issue showing in my setup.

**Comment by sean-mcmanus** [comment] 2022-07-01 17:29
Is there a symlink on the path to the workspace folder? That is currently unsupported and tracked by https://github.com/microsoft/vscode-cpptools/issues/4573 . Otherwise, what is the repro setup and types of symlinks involved?

**Comment by flplv** [comment] 2022-07-01 17:36
Hello sean;
In the vscode project there is a folder called “src” that contains multiple subfolders that are actually symlinks to folders outside the vscode project tree. 

To reproduce all you need is to open a source file within those symlinked folders and run the header/source toggle command. The IDE will open duplication of the already open file, using off project fullpath instead the in-project path. Exactly as described in #6855

**Comment by sean-mcmanus** [comment] 2022-07-01 20:24
Where are the header and source files located relative to each other, i.e. are they in the same folder?

**Comment by flplv** [comment] 2022-07-01 21:49
They are in different folders, but both behind the same link, i.e:

`vs_code_root/src/X/src/a.cpp`
`vs_code_root/src/X/include/a.h`
where X is the symlink

**Comment by sean-mcmanus** [comment] 2022-07-01 22:13
I repro the issue. As described in comment https://github.com/microsoft/vscode-cpptools/issues/6855#issuecomment-769399202 -- that case wasn't fixed. The root issue is being tracked by https://github.com/microsoft/vscode-cpptools/issues/4573 .

The recommended workaround is to add the target of the symlink as a 2nd workspace folder.

The problem is that our extension is incorrectly resolving symlinks to their targets and storing those in our database.

This is not a recent regression.

**Closed as not planned by sean-mcmanus** 2022-07-01 22:13 UTC
Labels: bug, duplicate, Language Service

**Comment by flplv** [comment] 2022-07-01 22:16
Roger, thanks for the explanation and analysis
