### ISSUE TITLE
Outline for C is wrong.

### ISSUE THREAD

**Issue by XuanofXXX** [microsoft/vscode-cpptools#12254] opened 2024-04-25 15:09 UTC
### Environment

- OS and Version: macOS 14.4.1 (23E224)
- VS Code Version: 1.88.1
- C/C++ Extension Version: 1.19.9
- If using SSH remote, specify OS of remote machine: Ubuntu 22.04.4 LTS (Jammy Jellyfish

### Bug Summary and Steps to Reproduce

Bug Summary:
When I click `mm_free` function, it jumps to `find_fit` function, with a wrong function tag above.
![overview](https://github.com/microsoft/vscode-cpptools/assets/116292569/20124590-f235-4dd6-85cf-2c4e0b22d4c6)
![wrong_function_tag_above](https://github.com/microsoft/vscode-cpptools/assets/116292569/d46d4fc7-0fe2-4137-90dc-7ebc7c66f29f)

### Configuration and Logs

```shell
no c_cpp_properties.json
```

### Other Extensions

These are the extensions I enabled:
![image](https://github.com/microsoft/vscode-cpptools/assets/116292569/4d906686-0e94-4e5c-ab82-54d777ab81a3)
![image](https://github.com/microsoft/vscode-cpptools/assets/116292569/814cdd03-3e2c-45eb-8128-38b487d538c3)

**Comment by sean-mcmanus** [comment] 2024-04-25 19:30
@XuanofXXX Can you provide a screenshot of the code the defines mm_free? The source of the problem could be there.

**Comment by XuanofXXX** [comment] 2024-04-26 01:06
Not only does the mm_free function exhibit this bug, but almost all functions are experiencing incorrect jumps.
Here is the screenshot of the `mm_free`:
<img width="1800" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/116292569/73fe81b1-6671-4243-aef2-bfe56ceb0576">

**Comment by sean-mcmanus** [comment] 2024-04-26 01:19
@XuanofXXX If you set C_Cpp.loggingLevel to "Debug", what do you see in you make an edit to mm.c, such as renaming mm_free to mm_free2? Do you see a "tag parsing" message? Are there any error messages? Does the Outline update with the new name, and is the position still wrong?

Otherwise, does doing a Reset IntelliSense Database fix the issue?

It seems like the database has wrong positions for the symbols for some reason.

**Comment by XuanofXXX** [comment] 2024-04-26 01:33
After resetting the IntelliSense database, the issue was resolved. Renaming mm_free also helped, but there's still a 3-second delay. Is it normal?

**Comment by sean-mcmanus** [comment] 2024-04-26 02:10
@XuanofXXX Yeah, your database must have been either outdated or "corrupt" -- it's possible the cause of the corruption might have been fixed in 1.20.2. A 3-second symbol update delay is normal.

**Closed as completed by sean-mcmanus** 2024-04-26 02:10 UTC
Labels: bug, Language Service, Feature: Document Symbol
