### ISSUE TITLE
Unable to get correct formatting code if  chinese characters exist.

### ISSUE THREAD

**Issue by ZhUyU1997** [microsoft/vscode-cpptools#5939] opened 2020-08-08 19:54 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win 10 1903
- VS Code Version: 1.47.3
- C/C++ Extension Version:  0.30-0-insiders
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes
- If chinese characters exist in code, after format, unable to get correct code, which even causes a compile error.

**Steps to reproduce**

1. Open c source file
2. Input below code
```c
//保
	return 0;
```
3. Right-click and click to format code
4. See an error,  the code will be below
```c
//保
	rturn 0;
```
**Screenshots**

![GIF 2020-8-9 3-52-52](https://user-images.githubusercontent.com/18410894/89718730-d4e0bd00-d9f3-11ea-8b96-59e9b77752ba.gif)

**Comment by github-yxb** [comment] 2020-08-10 07:23
昨天升级后遇到同样的问题

**Comment by michelleangela** [comment] 2020-08-10 23:13
> 昨天升级后遇到同样的问题

@github-yxb  Could you translate this comment to English?

**Comment by michelleangela** [comment] 2020-08-10 23:22
@Colengms This issue may be the same as https://github.com/microsoft/vscode-cpptools/issues/5929, where formatting breaks when there are non-ASCII characters in the comment. Formatting works when the comment in the sample code uses ASCII characters.

**Comment by michelleangela** [comment] 2020-08-11 00:11
This is duplicate of https://github.com/microsoft/vscode-cpptools/issues/5914

**Closed as completed by michelleangela** 2020-08-11 00:11 UTC
Labels: duplicate, Language Service, verified, Feature: Code Formatting

**Comment by sean-mcmanus** [comment] 2020-08-12 01:15
This is fixed with 0.30.0-insiders2: https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders2 .
