### ISSUE TITLE
intelliSense fails after reloading window

### ISSUE THREAD

**Issue by qiuhaha** [microsoft/vscode-cpptools#3996] opened 2019-07-29 07:40 UTC
**Type: LanguageService**
**Describe the bug**
- OS and Version: Windows 10 64bit
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1
- Other extensions you installed (and if the issue persists after disabling them): twxs.cmake
- Description:  
I am working on project within a within a rather large codebase. Sometimes after reloading the window (close vscode and reopen it from the taskbar, for example) intelliSense will crash for some open files. And the extension outputs something like:
> Done parsing remaining files.
Checking for syntax errors: file:///c%3A/Users/admin/Documents/bigAggron/serialize.h
Checking for syntax errors: file:///c%3A/Users/admin/Documents/bigAggron/serialize.h
Checking for syntax errors: file:///c%3A/Users/admin/Documents/bigAggron/serialize.h
Quick info operation failed: Error: Failed to find translation unit. Try opening a source file that includes this header, then re-open this header.

The file serialize.h dosen't contain any detected problems. I re-open the file, and it works again.  

Sorry I could't reproduce it outside my codebase. Just re-opening the header can fix the problem, but then I reload the window it will fail again. I wonder why am I getting this error?

**Comment by sean-mcmanus** [comment] 2019-07-30 19:09
Your errors don't show a crash. It sounds like some bug when VS Code is first started and there's an existing file open. Let us know if you find any more repro info.

**Comment by sean-mcmanus** [comment] 2019-07-30 19:10
If you do a C/C++: Log Diagnostic command you may be able to see what inputs to IntelliSense are causing it to fail.

**Comment by bobbrow** [comment] 2020-03-19 21:28
I believe we released a fix for this last year. It was caused by assigning the wrong source file as the translation unit for a header that it didn't actually include.

**Closed as completed by bobbrow** 2020-03-19 21:28 UTC
Labels: bug, Language Service, reliability, not reproing
