### ISSUE TITLE
Can't start debugger in ubuntu 18.04 using gdb 8.1

### ISSUE THREAD

**Issue by dsowa-w1** [microsoft/vscode-cpptools#1972] opened 2018-05-09 15:16 UTC
Using Ubuntu 18.04 on an Intel platform using the default gdb 8.1.  When I start my project in the debugger I get an error box that says "Unable to start debugging. An Item with the same key has already been added." 
I created a simple c++ test app project with a couple of modules and can successfully debug that on this same machine so the debugging process isn't totally broken.
This same machine and project can run in the debugger successfully under ubuntu 17.10 and gdb 8.01.

Now to what I think is the issue.
The project I'm working on has a task class that uses a local function called main() to describe the thread function wrapped by the class (whether this is a good idea is not my call), I've turned on the logging through launch.json and what I see is the response to the line "1010-break-insert main' is returned with 21 entries and I believe that is confusing the GDB control code.  I'm not really sure why this is happening at all since I have "stopAtEntry": false set in launch.json

the GDB 8.1 change log has the following entry
* Breakpoints on C++ functions are now set on all scopes by default

  By default, breakpoints on functions/methods are now interpreted as
  specifying all functions with the given name ignoring missing
  leading scopes (namespaces and classes).

  For example, assuming a C++ program with symbols named:

    A::B::func()
    B::func()

  both commands "break func()" and "break B::func()" set a breakpoint
  on both symbols.

  You can use the new flag "-qualified" to override this.  This makes
  GDB interpret the specified function name as a complete
  fully-qualified name instead.  For example, using the same C++
  program, the "break -q B::func" command sets a breakpoint on
  "B::func", only.  A parameter has been added to the Python
  gdb.Breakpoint constructor to achieve the same result when creating
  a breakpoint from Python.

So instead of getting one breakpoint set in the past now any function called main() gets a breakpoint set and that seems to be interfering with the VSC starting up gdb

**Comment by dsowa-w1** [comment] 2018-05-16 20:06
I resolved this for myself be renaming all of the things in my codebase called main() except the real main() and that lets me debug again.  I still consider this a bug but is no longer in my way. It could probably be resolved by passing the '-qualified' parameter for the setting of the initial breakpoint unless that is something that gdb does automatically.

**Comment by pieandcakes** [comment] 2018-06-15 06:19
Hi @dsowa-w1,

We have a fix if you want to try it. It is listed [here](https://github.com/Microsoft/vscode-cpptools/issues/2056#issuecomment-396757668).

**Comment by pieandcakes** [comment] 2018-06-15 06:20
Marking this as a duplicate of #2056.

**Closed as completed** 2018-06-15 06:21 UTC
Labels: duplicate, debugger, fixed
