### ISSUE TITLE
[Regression] The 'Learn how to install a library for this header with vcpkg' option has disappeared

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode-cpptools#12413] opened 2024-06-25 05:53 UTC
### Environment

- OS and Version: Windows/Linux/Mac OS
- VS Code Version: 1.85.0
- C/C++ Extension Version: 1.20.5

### Bug Summary and Steps to Reproduce

Bug Summary: The 'Learn how to install a library for this header with vcpkg' option has disappeared

**Steps to reproduce:**
1. Create a Test folder with .cpp file.
2. Open Test folder with VS Code.
3. Type error code in .cpp file, such as: **#include"xxxxx.h"** 
4. Hover over error squiggle and Click on 'Quick Fix'

**Expected behavior:** 'Learn how to install a library for this header with vcpkg' option appear
![image](https://github.com/microsoft/vscode-cpptools/assets/78774400/51e45fd0-58fb-46c6-bd64-ba5aad241309)

**Actual behavior:** 'Learn how to install a library for this header with vcpkg' option has disappeared from C/C++ extension 1.17.2

Latest C/C++ extension version: 1.20.5
![image](https://github.com/microsoft/vscode-cpptools/assets/78774400/26c2d252-7050-4712-8bde-85d1a08f5540)

C/C++ extension 1.17.2:
![image](https://github.com/microsoft/vscode-cpptools/assets/78774400/ad797a97-bb8d-47a9-9626-934f9f1cad51)

### Configuration and Logs

```shell
/
```

### Other Extensions

/

**Comment by browntarik** [comment] 2024-06-26 20:00
Thank you for reporting this issue. This behavior is actually by design as we only want to suggest this code action for headers that are supported by vcpkg. This does however bring to light a bug where this code action is not appearing even for such headers like `#include <zlib.h>`. 

It looks like we were incorrectly parsing our vcpkg header database. Please keep tracking this issue to be notified when a fix is checked in.

**Comment by sean-mcmanus** [comment] 2024-07-16 00:15
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.21.1

**Closed as completed by sean-mcmanus** 2024-07-16 00:15 UTC
Labels: bug, Language Service, fixed, regression

**Comment by v-ericawu** [comment] 2024-07-16 10:07
@sean-mcmanus Verified on C/C++ 1.21.1(pre-release) still repro this issue, so could you help to re-confirm it?
![image](https://github.com/user-attachments/assets/88c41da3-cfc4-4b21-bf2e-46b5d3740c54)

**Comment by Colengms** [comment] 2024-07-16 23:07
Hi @v-ericawu .  To clarify, you wouldn't get that option for "xxxxx.h".  The feature applies only if the header is from a library supported by vcpkg.  Try `geos.h`:

![image](https://github.com/user-attachments/assets/290282e0-89a5-4f5e-b159-5838bdb834d0)

**Comment by v-ericawu** [comment] 2024-07-17 02:10
@Colengms @sean-mcmanus Thanks for your confirmation! using ''geos.h'' will bring up the 'Learn how to install a library for this header with vcpkg' option:
![image](https://github.com/user-attachments/assets/168a9dc6-6f91-433c-aff5-fe23876ab8c6)
