### ISSUE TITLE
Can not avoid incompatible-pointer-types IntelliSense triggering

### ISSUE THREAD

**Issue by ltWolfik** [microsoft/vscode-cpptools#4702] opened 2019-12-04 16:57 UTC
I have type, defined like this:
```c
union prefixconstptr {
    const struct prefix *p;
    const struct prefix_ipv4 *p4;
    // ...
} __attribute__((transparent_union));
```
And function:
```c
int prefix_same(union prefixconstptr, union prefixconstptr);
```
Everywhere *prefix_same* is called, IntelliSense triggers for arguments error:
> argument of type "struct prefix *" is incompatible with parameter of type "union prefixconstptr"

From console the project is built without problems (with autotools). 

I tried to add the following to *c_cpp_properties.json*:
```json
"compilerArgs": ["-Wno-incompatible-pointer-types"]
```
But, IntelliSense still triggers the error.

Is it possible to avoid triggering this error?

It's used cross-compiler for arm:
```json
"compilerPath": "${_BIN}/arm-oe-linux-musleabi-gcc",
```
**VS Code**
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.12.14-lp151.28.32-default
C/C++ Extension: 0.26.2

**Comment by Colengms** [comment] 2019-12-04 18:30
Hi @ltWolfik .  Can you provide a complete code example that repro's the issue?  I tried the following, and did not get any squiggles:

```
union prefixconstptr {
    const struct prefix *p;
    const struct prefix_ipv4 *p4;
    // ...
} __attribute__((transparent_union));

int prefix_same(union prefixconstptr, union prefixconstptr);

void foo()
{
    prefixconstptr p;
    prefix_same(p, p);
}
```

Based on the error, it sounds like you are trying to pass a `struct prefix *` as a prefixconstptr argument.  If so, the error would seem to be correct.  If I add the following code:

```
void foo2()
{
    const struct prefix *p;
    prefix_same(p, p);
}
```

With gcc (7), I get the following error:

`error: could not convert ‘p’ from ‘const prefix*’ to ‘prefixconstptr’`

(and similar errors with cl.exe, or clang)

If `arm-oe-linux-musleabi-gcc` accepts this, it would seem to be non-standard, or perhaps a bug.  The IntelliSense parser is essentially a C++ compiler front-end.  Although it can be configured to follow rules for msvc, gcc, or clang (using the `IntelliSenseMode` setting), it does not leverage your actual compiler directly.

**Comment by ltWolfik** [comment] 2019-12-05 10:33
Originally the problem from [FRRouting project](https://github.com/FRRouting/frr/blob/master/lib/prefix.h#L306)

I just make the following example:
```c
#include <stdint.h>
#include <netinet/in.h>
#include <net/ethernet.h>

struct prefix {
	uint8_t family;
	uint16_t prefixlen;
	union {
		uint8_t prefix;
		struct in_addr prefix4;
		struct in6_addr prefix6;
		struct {
			struct in_addr id;
			struct in_addr adv_router;
		} lp;
		uint8_t val[16];
		uint32_t val32[4];
		uintptr_t ptr;
	} u __attribute__((aligned(8)));
};

struct prefix_ipv4 {
	uint8_t family;
	uint16_t prefixlen;
	struct in_addr prefix __attribute__((aligned(8)));
};

struct prefix_ipv6 {
	uint8_t family;
	uint16_t prefixlen;
	struct in6_addr prefix __attribute__((aligned(8)));
};


#define prefixtype(uname, typename, fieldname) \
	typename *fieldname;

union prefixconstptr {
	prefixtype(prefixconstptr, const struct prefix,      p)
	prefixtype(prefixconstptr, const struct prefix_ipv4, p4)
	prefixtype(prefixconstptr, const struct prefix_ipv6, p6)
} __attribute__((transparent_union));

int prefix_same(union prefixconstptr up1, union prefixconstptr up2)
{
        return 0;
}

int main(int argc, char const *argv[])
{
        struct prefix range = {0};
        struct prefix lr = {0};

        prefix_same(&range, &lr); // <-- Squiggles here
        return 0;
}
```
IntelliSense triggers the errors on arguments:
> argument of type "struct prefix *" is incompatible with parameter of type "union prefixconstptr"


But *make* from console do not produce any errors:
```shell
Making all in src
make[1]: Entering directory '/home/alexander/projects/trash/tests/.build-arm/src'
arm-oe-linux-musleabi-gcc  -march=armv7ve -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 -mmusl --sysroot=/usr/sdk/sysroots/cortexa7hf-neon-oe-linux-musleabi -DPACKAGE_NAME=\"tests\" -DPACKAGE_TARNAME=\"tests\" -DPACKAGE_VERSION=\"1.0.0\" -DPACKAGE_STRING=\"tests\ 1.0.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tests\" -DVERSION=\"1.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -I/home/alexander/projects/trash/tests/src    -Wall -O2 -pipe -g -feliminate-unused-debug-types  -MT intelli_sense_test-intelli-sense-test.o -MD -MP -MF .deps/intelli_sense_test-intelli-sense-test.Tpo -c -o intelli_sense_test-intelli-sense-test.o `test -f 'intelli-sense-test.c' || echo '/home/alexander/projects/trash/tests/src/'`intelli-sense-test.c
mv -f .deps/intelli_sense_test-intelli-sense-test.Tpo .deps/intelli_sense_test-intelli-sense-test.Po
../arm-oe-linux-musleabi-libtool  --tag=CC   --mode=link arm-oe-linux-musleabi-gcc  -march=armv7ve -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 -mmusl --sysroot=/usr/sdk/sysroots/cortexa7hf-neon-oe-linux-musleabi -Wall -O2 -pipe -g -feliminate-unused-debug-types   -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -o intelli-sense-test intelli_sense_test-intelli-sense-test.o
arm-oe-linux-musleabi-libtool: link: arm-oe-linux-musleabi-gcc -march=armv7ve -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 -mmusl --sysroot=/usr/sdk/sysroots/cortexa7hf-neon-oe-linux-musleabi -Wall -O2 -pipe -g -feliminate-unused-debug-types -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -o intelli-sense-test intelli_sense_test-intelli-sense-test.o
make[1]: Leaving directory '/home/alexander/projects/trash/tests/.build-arm/src'
make[1]: Entering directory '/home/alexander/projects/trash/tests/.build-arm'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/alexander/projects/trash/tests/.build-arm'
```

**Comment by Colengms** [comment] 2019-12-05 19:23
Hi @ltWolfik .  It looks like the detail I was missing was that this is in C, not C++.  It does compile in C.

This issue repro's in VS.  (The C/C++ Extension shares common code with VS for IntelliSense).  I've opened an issue against VS, [here](https://developercommunity.visualstudio.com/content/problem/846049/intellisense-squiggles-valid-code-related-to-trans.html), if you'd like to up-vote it.

**Comment by Colengms** [comment] 2021-09-24 22:43
I'm no longer able to reproduce this issue with recent builds of the C/C++ Extension.  Closing this as fixed.

**Closed as completed by Colengms** 2021-09-24 22:43 UTC
Labels: Language Service, Visual Studio
