### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SeanMichaelJoy** [microsoft/vscode-cpptools#3337] opened 2019-03-21 16:52 UTC
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

**Comment by michelleangela** [comment] 2019-03-21 17:40
Are you seeing this high cpu load on the Microsoft.VSCode.CPP.Extension.exe or Microsoft.VSCode.CPP.IntelliSense.Msvc.exe process?

Can you try disabling the new IntelliSense caching feature and run the same load scenario and report the results? You can disable the IntelliSense caching by setting the `C_Cpp.intelliSenseCacheSize` setting to 0.

**Comment by bobbrow** [comment] 2019-03-21 18:14
Thanks for reporting this issue. This looks like a duplicate of #3213.

**Closed as completed by bobbrow** 2019-03-21 18:14 UTC
Labels: duplicate, Language Service

**Comment by SeanMichaelJoy** [comment] 2019-03-22 16:59
Thank You
