### ISSUE TITLE
.clang-format file isn't used

### ISSUE THREAD

**Issue by viveksjain** [microsoft/vscode-cpptools#604] opened 2017-03-31 05:33 UTC
Running on Ubuntu 14.04, VSCode 1.10.2 and C++ extension 0.10.5. I seem to be having a similar issue to #196 - the flags passed to clang-format are
`-style={ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 2, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0 } -fallback-style=LLVM`
which means my actual .clang-format file is not used (should be `-style=file`). Where is this other style coming from and how can I fix it?

**Comment by viveksjain** [comment] 2017-03-31 05:35
Just found #536 which is tangentially (but not exactly) related. It also says that issue is supposed to be fixed in 0.10.4, but my later version is still having this issue.

**Comment by viveksjain** [comment] 2017-03-31 05:41
Manually specifying the dict for C_Cpp.clang_format_style works, but setting it to "file" doesn't work.

**Comment by sean-mcmanus** [comment] 2017-03-31 12:01
It's https://github.com/Microsoft/vscode-cpptools/issues/571 , but I think we'll use this bug to track the issue, since the other bug mostly discusses another issue that I couldn't repro.

**Comment by Binero** [comment] 2017-04-06 13:42
Can confirm this. Just running clang-format from the terminal works fine, VSC ignores it and always uses the fallback.

**Comment by rooomaa** [comment] 2017-04-08 06:21
same on ubuntu-16.04 & rhel-7.3 + vscode 1.11.1

**Comment by sean-mcmanus** [comment] 2017-04-26 16:45
The workaround is to change your clang_format_fallbackStyle to one of the non-"Visual Studio" presets, such as LLVM. But hopefully this will get fixed soon anyway.

**Comment by spencersutton** [comment] 2017-04-27 18:01
> The workaround is to change your clang_format_fallbackStyle to one of the non-"Visual Studio" presets, such as LLVM. But hopefully this will get fixed soon anyway.

That doesn't work for me but setting C_Cpp.clang_format_path to my system version of clang-format fixes it on macOS.

**Comment by sean-mcmanus** [comment] 2017-04-27 18:39
@spencersutton Ah, that's probably because your .clang-format has newer fields that aren't supported by the 3.8 version we ship, i.e. different root cause from the Linux/Mac-only issue.

**Comment by spencersutton** [comment] 2017-04-27 18:50
@sean-mcmanus You're right, I generated my .clang-format with clang-format --dump-config using my system clang-format.  I found the version installed by vscode and ran it and got an error. There's no feedback in vscode if there's an error though.

It does work with default settings if I take the new option out.

**Comment by sean-mcmanus** [comment] 2017-04-27 19:14
@spencersutton I agree. We have a work item for exposing the clang-format error messages, but it's not expected to be fixed soon.

**Comment by sean-mcmanus** [comment] 2017-05-05 23:24
The .clang-format not being detected when the Visual Studio fallback is used will be fixed in the next update. I'm not sure if we'll update the downloaded clang-format version. And we won't be exposing clang-format errors yet.

**Comment by xgalaxy** [comment] 2017-05-17 00:48
I'm having this problem on Windows. The strange thing is I swear it was working earlier.
This is my clang format file:
https://gist.github.com/xgalaxy/e36910ba723849da146f705347a8adad

**Comment by sean-mcmanus** [comment] 2017-05-17 01:30
@xgalaxy Yeah, we should output the clang-format stderr somewhere. But as a workaround you can just run clang-format via the command line. In your example, TabWidth needs a colon, and FixNamespaceComments was added in clang-format 5.0 and we only ship 3.8-3.9, soon changing to 4.0, but you can change the C_Cpp.clang_format_path to your manually downloaded clang-format 5.0 if you want it to work.

**Comment by xgalaxy** [comment] 2017-05-17 01:55
Crap totally missed the colon. Thank you.
And yea, I already point at a locally installed clang.

**Comment by bobbrow** [comment] 2017-05-23 23:40
This was fixed in version 0.11.1. Please reopen if you continue to have this issue.

**Closed as completed by bobbrow** 2017-05-23 23:40 UTC
Labels: bug, Language Service, fixed
