### ISSUE TITLE
Renaming macros

### ISSUE THREAD

**Issue by ilobilo** [microsoft/vscode-cpptools#9021] opened 2022-03-14 13:30 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Ubuntu 21.04
- VS Code Version: 1.65.0
- C/C++ Extension Version: 1.9.3
- Other extensions you installed (and if the issue persists after disabling them): yes
- If using SSH remote, specify OS of remote machine: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

When renaming C/C++ macro with F2, all the uses of that macro gets renamed but not original definition:

**Steps to reproduce**

1. Create a macro and rename it eith F2
Before:
```c
#define MYMACRO(x, y) ((x) + (y))
printf("%d", MYMACRO(1, 2));
```
Select MYMACRO, click F2, type new name e.g ADD
After:
```c
#define MYMACRO(x, y) ((x) + (y))
printf("%d", ADD(1, 2));
```

**Expected behavior**

Macro gets renamed too

**Comment by sean-mcmanus** [comment] 2022-03-14 17:51
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4075. You can upvote that issue.

**Closed as completed by sean-mcmanus** 2022-03-14 17:51 UTC
Labels: duplicate
