### ISSUE TITLE
Support tracepoint actions (Linux)

### ISSUE THREAD

**Issue by aparks5** [microsoft/vscode-cpptools#3120] opened 2019-01-31 18:26 UTC
it's pretty simple, vscode 1.30.2

launch gdb, try:

-exec trace source.cxx:line
-exec actions 

(no response)

works fine when i launch gdb from the terminal

**Comment by pieandcakes** [comment] 2019-01-31 20:55
We don't currently support tracepoints.

@aparks5 what are you expecting to happen? I tried your scenarion and I get a response of *not available* back from gdb.

**Comment by aparks5** [comment] 2019-01-31 22:13
I was expecting to be able to do anything in the Debug Console that I could do in gdb. Even if it gets written out to the file system and is not reflected in the Debug window.

**Comment by WardenGnaw** [comment] 2023-03-02 19:27
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/2591

**Closed as not planned by WardenGnaw** 2023-03-02 19:27 UTC
Labels: debugger, Feature Request
