### ISSUE TITLE
Suggestion: Pre-Processor Directives Improvement

### ISSUE THREAD

**Issue by xidianzhangjun** [microsoft/vscode-cpptools#3316] opened 2019-03-19 03:20 UTC
**Type: LanguageService**

Hi,
Like the code below, 
#if AMACRO
      do_something_A();
#else
      do_something_B();
#endif
If I click on the #if Directive, it would be better to enhance the display (e.g. color) of the matching #else and #endif.

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment] 2019-03-19 20:43
It sounds like this is for highlighting the matching preprocessor directives (if/else/endif/etc.).

**Comment by xidianzhangjun** [comment] 2019-03-20 02:20
> It sounds like this is for highlighting the matching preprocessor directives (if/else/endif/etc.).

Yes! :-)
When there are too many lines of codes between #if and its matching #endif or when there are multi-level  preprocessor directives, , it is not very easy to read the codes.
Thanks.

**Comment by Colengms** [comment] 2021-04-12 21:10
This is being added in 1.3.0, and is currently available in 1.3.0-insiders5.  Closing this one as a dupe of https://github.com/microsoft/vscode-cpptools/issues/2565 .

**Closed as completed by Colengms** 2021-04-12 21:10 UTC
Labels: Language Service, Feature Request, Works in VS
