### ISSUE TITLE
modify "the External: Osx Exec" not work when debug C files 

### ISSUE THREAD

**Issue by Zhoucheng133** [microsoft/vscode-cpptools#9563] opened 2022-07-10 08:39 UTC
### Environment

- OS and version: macOS 12.4
- VS Code: 1.69.0
- C/C++ extension: 1.10.8
- GDB / LLDB version:  clang version 13.0.0

### Bug Summary and Steps to Reproduce

Bug Summary:
modify vs code setting : "the External: Osx Exec" not work when debug C files even if I set the "externalConsole" to "true"

Steps to reproduce:
1. modify "the External: Osx Exec" to iTerm.app
2. modify "externalConsole" to true in launch.json
3. using F5 to debug the file (single c++ file)

The program can run but the program run in default terminal not the terminal I set
![178112256-6ccb4111-bb79-49f9-a8b3-0d578c7a386e](https://user-images.githubusercontent.com/54197427/178137690-5ed66c2a-e00a-4c98-a756-73a86075344e.png)

### Debugger Configurations

```shell
tasks.json:
{
    "type": "cppbuild",
    "label": "CppBuild",
    "command": "/usr/bin/clang++",
    "args": [
        "-fdiagnostics-color=always",
        "-g",
        "${file}",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}"
    ],
    "options": {
        "cwd": "${fileDirname}"
    },
    "problemMatcher": [
        "$gcc"
    ],
    "group": "build",
    "detail": "调试器生成的任务。"
}

launch.json:
{
    "name": "C/C++: clang++ 生成和调试活动文件",
    "type": "cppdbg",
    "request": "launch",
    "program": "${fileDirname}/${fileBasenameNoExtension}",
    "args": [],
    "stopAtEntry": false,
    "cwd": "${fileDirname}",
    "environment": [],
    "externalConsole": true,
    "MIMode": "lldb",
    "preLaunchTask": "CppBuild"
}
```

### Debugger Logs

```shell
Loaded '/usr/lib/system/libsystem_platform.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_pthread.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_symptoms.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_trace.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libunwind.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libxpc.dylib'. Symbols loaded.
Loaded '/usr/lib/libobjc.A.dylib'. Symbols loaded.
Loaded '/usr/lib/liboah.dylib'. Symbols loaded.
The program '/Users/zhoucheng/Desktop/Demo/helloworld' has exited with code 0 (0x00000000).
```

### Additional Information

The program runs correctly on the default terminal, but i want it to run on the terminal I set in vscode setting.
If the extension is not affected by the vs code setting, I want to give me a setting to modify default terminal.

**Comment by WardenGnaw** [comment] 2022-07-11 19:32
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/390

Reason: This is because our version of lldb includes a module that was part of original lldb called darwin-debug that itself spawns the macOS terminal application.

**Closed as not planned by WardenGnaw** 2022-07-11 19:32 UTC
