### ISSUE TITLE
'Visual Studio' pseudo-style / macro-style is not usable as a base for clang formatter formatting options

### ISSUE THREAD

**Issue by merely-present** [microsoft/vscode-cpptools#11405] opened 2023-09-05 09:30 UTC
Type: <b>Bug</b>

It appears any attempt at changes to the 'Visual Studio' pseudo style, via the GUI, .clang-format file or JSON settings option "C_Cpp.clang_format_fallbackStyle" (EX. `"C_Cpp.clang_format_fallbackStyle": "{ BasedOnStyle: Visual Studio }"` will result in "Formatting failed".

Searching for workarounds, I found this post:

> Internally, the Visual Studio style setting we use is similar to `"{ BasedOnStyle: LLVM, UseTab: Always, IndentWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, TabWidth: 4 }"`, so you could set the clang_format_style to something like that with modifications. In the pending 0.11.0 update, you can also use a custom clang_format_fallbackStyle. What formatting feature of Visual Studio are you not able to replicate with clang-format? Later clang-format versions have added more options.

_Originally posted by @sean-mcmanus in https://github.com/microsoft/vscode-cpptools/issues/657#issuecomment-297061547_

That lead me to the conclusion that 'Visual Studio' is not a real style but instead is a macro that is being converted somewhere between your VSCode settings (JSON or GUI) and clang-format. The issue then, would be that it seems to only function as a Pseudo style while not being used as a base. When used as a base, whatever macro functionality exists to convert it into its true `{ BasedOnStyle: LLVM...` form, fails to recognize it is being used in a base, [resulting in a failed call to clang-format with a style option it is not familiar with.](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options)

To fix this, whatever mechanism converts 'Visual Studio' into `{ BasedOnStyle: LLVM...` would need to also do so while it was used as a base (situations like `"C_Cpp.clang_format_fallbackStyle": "{ BasedOnStyle: Visual Studio, ColumnLimit: 80 }"`).

Alternatively, as this seems to be a rather niche issue, I suppose it could also just be documented as a quirk so that the UI more accurately represented the possibilities of configuration.

# Workaround
Use the equivalent given in the UI Hint in your settings.json or clang formatting file.

Extension version: 1.17.5
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (6.74GB free)|
|Process Argv|--crash-reporter-id 00f1fbea-93e1-4a68-9e0a-faf5d8fb943d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
962ge761:30823813
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015cf:30823818

```

</details>

**Comment by Colengms** [comment] 2023-09-06 00:02
Hi @CS-Account .  This is by design.  `Visual Studio` is not a style value recognized by `clang-format`.  The documentation you referred to for that value refers to the equivalent you could use if you want to replicate the style and make your own further changes to it.  The block of values referred to (`{ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -4, NamespaceIndentation: All, FixNamespaceComments: false }`) can be passed directly to `clang-format` itself, via command line.  As such, we would not be able to add `Visual Studio` as a value for `BasedOnStyle`, without modifying `clang-format` itself.

Note that a `.clang-format` file is only utilized if the `C_Cpp.clang_format_style` is set to `file` (the default).  And, if so, the `C_Cpp.clang_format_fallbackStyle` setting is only used if no such `.clang-format` file is located.

I'm going to go ahead and close this as by-design.  Let me know if this information doesn't resolve the issue for you.

**Closed as not planned by Colengms** 2023-09-06 00:02 UTC
