### ISSUE TITLE
Wrong semantic colorization when using lambda expression

### ISSUE THREAD

**Issue by warzone-oier** [microsoft/vscode-cpptools#11421] opened 2023-09-09 10:54 UTC
### Environment

- OS and Version: Ubuntu 20.04
- VS Code Version: 1.81.1
- C/C++ Extension Version: v1.17.5
- If using SSH remote, specify OS of remote machine: no SSH

### Bug Summary and Steps to Reproduce

Semantic colorization is wrong when using lambda expression like these below:
![2023-09-09 18-13-19 的屏幕截图](https://github.com/microsoft/vscode-cpptools/assets/74630986/8ecc22e9-88d1-46e0-9303-6d9b2dc901ef)
![2023-09-09 18-15-03 的屏幕截图](https://github.com/microsoft/vscode-cpptools/assets/74630986/7522065a-5f52-445c-8a7f-723977468f6d)
![2023-09-09 18-15-23 的屏幕截图](https://github.com/microsoft/vscode-cpptools/assets/74630986/ca319a98-475c-4d11-9f3b-a055b7697571)

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

### Other Extensions

The problem has nothing to do with any language pack.

**Comment by Colengms** [comment] 2023-09-11 18:54
Closing as a duplicate of: https://github.com/microsoft/vscode-cpptools/issues/11406
(which is external.  The colorization involved here is syntactic/lexical, not semantic, and is handled by VS Code itself, using textmate grammar contributed by another repo).

**Closed as not planned by Colengms** 2023-09-11 18:54 UTC
