### ISSUE TITLE
showing an irrelevant error

### ISSUE THREAD

**Issue by mohit-uniyal** [microsoft/vscode-cpptools#8602] opened 2021-12-24 14:22 UTC
Issue Type: <b>Bug</b>

int n;
    printf("enter the size of array: ");
    scanf("%d", &n);
    int arr[n];

it is showing error for line 4 that it should be a constant value but it is valid and working perfectly well. The error is false.

Extension version: 1.8.0-insiders2
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.45GB free)|
|Process Argv|--crash-reporter-id 2eb17b2b-3bba-494e-8036-8a0af333a941|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710:30416614
vscexrecpromp3c:30407761

```

</details>

**Comment by sean-mcmanus** [comment] 2021-12-27 19:50
It's a bug with our parser when -fms-extensions is used (internal bug 1455111). It should be "fixed" with our next 1.8.0-insiders3 release (via not setting that flag by default), and the equivalent workaround is to add "-fno-ms-extensions" in the compilerArgs.

**Comment by sean-mcmanus** [comment] 2021-12-27 23:26
Also, this was a duplicate of https://github.com/microsoft/vscode-cpptools/issues/8581

**Comment by michelleangela** [comment] 2022-01-05 20:31
Closing issue as duplicate.

**Closed as completed by michelleangela** 2022-01-05 20:31 UTC
Labels: bug, duplicate, Language Service, fixed, regression

**Comment by sean-mcmanus** [comment] 2022-01-19 19:37
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).

Unless you're explicitly adding -fms-extensions, in which case that bug fix is still pending (https://github.com/microsoft/vscode-cpptools/issues/8353 ).
