### ISSUE TITLE
compilerPath setting of c_cpp_properties.json no longer supports batch files

### ISSUE THREAD

**Issue by smhc** [microsoft/vscode-cpptools#3428] opened 2019-04-07 11:29 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version:  1.33.0
- C/C++ Extension Version: 0.22.1

compilerPath setting of c_cpp_properties.json no longer supports batch files (.bat). Earlier versions did support these. Using "cmd /C call xx.bat" works, however it is not possible to pass "${workspaceFolder}" as an argument.

Using a batch file results in the misleading error:
Failed to spawn process. Error: 2 (The system cannot find the file specified.)

**To Reproduce**

Use a c_cpp_properties.json file with a setting of:

```
"compilerPath":  "${workspaceFolder}\\test.bat"
```

or:
```
"compilerPath": "C:\\Windows\\System32\\cmd.exe /C echo ${workspaceFolder} >> %TEMP%\\cmd.log"
```

**Expected behavior**

Either the batch file can be launched directly, or at least make it possible to pass the 'workspaceFolder' as an argument to cmd to launch a batch file.

**Additional context**

The reason I wish to launch a batch file from the workspace folder is I want to have a 'dummy compiler' included as part of the project. This dummy compiler just returns the include paths and defines etc as gcc/g++ would. I use this technique for remote development from windows to linux with 'correct' intellisense.
However recent versions of vscode/cpptools have blocked this ability.

**Comment by sean-mcmanus** [comment] 2019-04-08 23:01
Sorry about that -- we had a bunch of bugs in this scenario. It should be fixed for our next release, but it probably won't make the soon to be released 0.22.2-insiders.

**Comment by smhc** [comment] 2019-04-08 23:16
Could you elaborate on which fix was implemented:

- compilerPath now supports batch files
- compilerPath now supports multiple replacements of ${workspaceFolder} in the arg list

Cheers.

**Comment by sean-mcmanus** [comment] 2019-04-09 02:27
We fixed it so that .cmd/.bat files works in the command line, as well as cmd.exe with args that are paths surrounded by quotes (which was also buggy, which I assume is why your cmd.exe workaround didn't work).

We didn't fix the `${workspaceFolder}` issue, i.e. we only resolve that variable when it's at the start of the compilerPath and not as an argument. If that will still be an issue for you, can you file a new bug for that?

**Comment by smhc** [comment] 2019-04-09 02:34
Ok thanks.
The 'cmd /C call' workaround did work ok, It's just that I couldn't use the workspaceFolder as part of the args. e.g

```
cmd /C call ${workspaceFolder}\\dummy_compiler.bat
```

But being able to run a batch file directly is sufficient. Using:
```
${workspaceFolder}\\dummy_compiler.bat
```

Once can simply use the CWD within the batch file to use it how you like. Thanks.

**Comment by sean-mcmanus** [comment] 2019-04-09 02:43
Yeah, using cmd should work as a workaround for now, assuming there are no spaces or double quotes (bug fix pending) or `${workspaceFolder}` in your path (no bug fix pending currently, semi "by design")

**Comment by smhc** [comment] 2019-04-09 10:11
While I don't specifically need multiple substitution of ${workspaceFolder} - I did read a similar request on another issue. I am adding the link here for prosperity:

 https://github.com/Microsoft/vscode-cpptools/issues/1982#issuecomment-401980572

I imagine the ability to invoke a batch file and use CWD would be a workaround for most scenarios.

**Comment by sean-mcmanus** [comment] 2019-04-09 20:49
Thanks for letting me know about that other user's report -- the restriction on `${workspaceFolder}` to be only be resolved at the beginning was an oversight that was trivial to fix as well (https://github.com/Microsoft/vscode-cpptools/issues/3440 ).

**Comment by sean-mcmanus** [comment] 2019-04-24 02:19
The .bat file should work on 0.23.0-insiders now, but we didn't check in the fix for ${workspaceFolder} in the compilerPath yet (should be in 0.23.1-insiders).

**Closed as completed** 2019-05-08 01:30 UTC
Labels: bug, Language Service, fixed, quick fix, regression
