### ISSUE TITLE
Intellisense doesn't work for symlink

### ISSUE THREAD

**Issue by hsupu** [microsoft/vscode-cpptools#3456] opened 2019-04-12 01:49 UTC
**Type: LanguageService**

- OS and Version: Linux x64 4.15.0-47-generic
- VS Code Version: 1.33.0
- C/C++ Extension Version: 0dd516dd

My source dir has too many files, so I `ln -s` some subdir to another dir \(my workdir\) for work. Then I can exclude the source dir for file-watching. But thing goes wrong for workdir.

My dir tree likes this:
```
src/
    include/
    subdir/
        file.c
workdir/
    link/ => ../src/subdir/
        file.c
```

My cpptools includePath is configured correctly:

```
"includePath": [ "${workspaceFolder}/src/include" ],
```

Open the file.c under src is fine, everything works; open the file.c symlink under workdir is bad, no error hint, no suppress macro block, only symbol tip shows when hovering.

It may be a bug, Thanks for your attention.

**Comment by sean-mcmanus** [comment] 2019-04-12 02:42
Yeah, I believe that is a known bug, same as https://github.com/Microsoft/vscode-cpptools/issues/3288 . We are working a related fix when path has 2 different casings, but it might not fix this issue.

**Comment by dev-guy** [comment] 2019-12-30 17:45
Same issue on OSX. This bugs renders this extension useless with projects that use Bazel.

**Comment by bobbrow** [comment] 2020-04-09 21:41
Closing as duplicate of #3288

**Closed as completed by bobbrow** 2020-04-09 21:41 UTC
Labels: bug, duplicate, Language Service, symlinks
