### ISSUE TITLE
Debug session crashing - Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by princehektor** [microsoft/vscode-cpptools#2996] opened 2019-01-03 18:49 UTC
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

OS and Version: Ubuntu 18, 64bit
VS Code Version: 1.30.1
C/C++ Extension Version: 0.20.1

- A clear and concise description of what the bug is.

After launching the debugger, the debug console shows this error message

Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object

This is my launch.json

    {
        "name": "(gdb) my-debug",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceFolder}/myproj,
        "args": [],
        "stopAtEntry": true,
        "cwd": "${workspaceFolder}/myproj",
        "externalConsole": true,
        "MIMode": "gdb",
        "miDebuggerPath": "/usr/bin/sgdb",
        "setupCommands": [
            {
                "description": "Enable pretty-printing for gdb",
                "text": "-enable-pretty-printing",
                "ignoreFailures": true
            },
            {
                "description": "Have gdb ignore SIGUSR1",
                "text": "handle SIGUSR1 nostop noprint",
                "ignoreFailures": true
            },
            {
                "description": "Have gdb ignore SIGUSR2",
                "text": "handle SIGUSR2 nostop noprint",
                "ignoreFailures": true
            }
        ]
    },
sgdb is simply a script which opens gdb using sudo.

Note : This only happens when "externalConsole" set to true. With it to set to false (using integrated terminal), there are no issues.

**Comment by princehektor** [comment] 2019-01-03 18:50
@pieandcakes : Not sure what changed from the last time i submitted an issue. This is the link for it

https://github.com/Microsoft/vscode-cpptools/issues/2753

I also see a similar issue logged for the insiders version (https://github.com/Microsoft/vscode-cpptools/issues/2858)

But it looks like the problem happens with the non-insiders version too.

**Comment by WardenGnaw** [comment] 2019-01-03 19:12
Please update the cpptools extension to the [latest insiders](https://github.com/Microsoft/vscode-cpptools/releases/tag/0.21.0-insiders2) and let me know if you are still experiencing this issue.

**Comment by princehektor** [comment] 2019-01-03 19:40
@WardenGnaw : I havent used the insiders version before. Could you point me to the instructions on how to install the insiders version instead of the non-insiders version?

Also, once the fix is propagated to the non-insiders version, how do i switch back from the insiders version to the non-insiders version ?

**Comment by pieandcakes** [comment] 2019-01-03 20:38
>I also see a similar issue logged for the insiders version (#2858)
But it looks like the problem happens with the non-insiders version too.

@princehektor the issue was in VS Code and we made a fix that we haven't released yet. VS Code released an update that had the issue that they also then fixed, but it is in their insiders track.

You can fix the issue by either installing the insiders version of the extension or the insiders version of VS Code. 

To install the insiders version of the extension, download the file that @WardenGnaw linked above and then uninstall the extension in your current version of VS Code and manually install the extension following [these](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) instructions.

**Comment by princehektor** [comment] 2019-01-03 22:23
@pieandcakes and @WardenGnaw : I can confirm that the latest insiders version works fine. So i will use this for now. 

Will the fix be eventually propagated to the non-insiders version as well ? 

In general, is it recommended to use the insiders or non-insiders version of the plugin ?

**Comment by sean-mcmanus** [comment] 2019-01-03 22:30
@princehektor Yes, the change will get propogated to our next non-insiders (hopefully next week).

I would recommend all users who are comfortable reporting issues on GitHub to use the Insiders versions unless there's something breaking with that -- i.e. our pending 0.20.1-insiders3 has 50 or so fixes. Using the C_Cpp.updateChannel "Insiders" is the easiest way.

**Comment by psla** [comment] 2019-01-15 17:33
I installed 0.20.1-insiders3, and now GDB starts :) But it crashes on a breakpoint:
Stopping due to fatal error: NotImplementedException: No handler implemented for request type 'SourceRequest'!

**Comment by psla** [comment] 2019-01-15 17:35
After I changed the working directory it stopped crashing :-)
("cwd": "${workspaceRoot}/foo/bar",)

Maybe the error should be different, but it works now for me.

**Comment by pieandcakes** [comment] 2019-01-23 21:24
Duplicate of #2922

**Closed as completed by pieandcakes** 2019-01-23 21:24 UTC
Labels: bug, duplicate, debugger

**Comment by crioux** [comment] 2019-05-14 22:39
This is still broken on latest Insiders, as of today. It's totally not the same bug as #2922. I can reproduce it reliably.

Here's the debug configuration :

```
    {
      "name": "Debug",
      "type": "cppdbg",
      "request": "launch",
      "program": "${env:HOME}/foo/artifacts/bar",
      "miDebuggerServerAddress": "172.17.0.2:9091",
      "cwd": "${env:HOME}/foo",
      "linux": {
        "MIMode": "gdb"
      },
      "osx": {
        "MIMode": "gdb"
      },
      "windows": {
        "MIMode": "gdb"
      },
      "sourceFileMap": {
        "/root/src": "${homedir}/foo"
      }
    },
```

This is happening with local source code available in ${homedir}/foo, connecting to a remote gdbserver with no special options.

Click on an item in the call stack list to open the source file and this is what you get:

```
Thread 1 "bar" received signal SIGPIPE, Broken pipe.
0x00007ffff7fb5b87 in write () from target:/lib/x86_64-linux-gnu/libpthread.so.0
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
Stopping due to fatal error: NotImplementedException: No handler implemented for request type 'SourceRequest'!```
