### ISSUE TITLE
Suggestions of variables failed after opening the c/c++ extension

### ISSUE THREAD

**Issue by Jason-WT** [microsoft/vscode-cpptools#7780] opened 2021-07-04 07:52 UTC
Bug type: Debugger

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version: 1.5.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
suggestions of variable failed after opening the c/c++ extension

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
![image](https://user-images.githubusercontent.com/26076677/124377689-c6705380-dcdf-11eb-9e71-5e7c8e95ef51.png)

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment] 2021-07-06 18:27
This is currently "by design" because with C/C++ the word based suggestions causes a bug in which undesirable completions occur when Enter is used https://github.com/microsoft/vscode-cpptools/issues/2943. Set
```
    "[cpp]": {
        "editor.wordBasedSuggestions": true
    },
    "[c]": {
        "editor.wordBasedSuggestions": true
    }
```
to re-enable wordBasedSuggestion for C/C++.

And/or file an issue on VS Code (if it doesn't already exist) to somehow stop completion on Enter or in cases where the language service believes it shouldn't occur so we could potentially re-enable it by default.

**Comment by Jason-WT** [comment] 2021-07-07 02:16
> This is currently "by design" because with C/C++ the word based suggestions causes a bug in which undesirable completions occur when Enter is used #2943. Set
> 
> ```
>     "[cpp]": {
>         "editor.wordBasedSuggestions": true
>     },
>     "[c]": {
>         "editor.wordBasedSuggestions": true
>     }
> ```
> 
> to re-enable wordBasedSuggestion for C/C++.
> 
> And/or file an issue on VS Code (if it doesn't already exist) to somehow stop completion on Enter or in cases where the language service believes it shouldn't occur so we could potentially re-enable it by default.

sorry, I tried this solution but it doesn't work for me. Is there any other solutions for this problem? After I disable the c/c++ extension, the completion works. But I don't know which setting conflicts.

**Comment by sean-mcmanus** [comment] 2021-07-07 17:29
It works for me. Can you provide more repro info? i.e. do you get the same results as in the screenshot below? If so, what example doesn't work?

![image](https://user-images.githubusercontent.com/19859882/124803604-2ba98c00-df0e-11eb-9e72-c8d50d7ae8e1.png)

**Comment by Jason-WT** [comment] 2021-07-09 09:47
It works in a new cpp file. But it fails when working in my exsited file.
![image](https://user-images.githubusercontent.com/26076677/125059055-7fb69b00-e0dd-11eb-94d8-3da35795a765.png)
![image](https://user-images.githubusercontent.com/26076677/125059132-94932e80-e0dd-11eb-889b-d3f64a73cee9.png)

**Comment by sean-mcmanus** [comment] 2021-07-09 10:09
Hmm...your existing file might have some corrupted database entry, which could possibly get fixed by cut/pasting/saving the file contents or running the C/C++: Reset IntelliSense Database command. Or the other contents of the file could be breaking our parser.

However, your 2nd screenshot shows it's getting normal completion results and not the word based completions. If you want the word based completions only, then you should set C_Cpp.autocomplete to "Disabled". The word base completions normally only appear when our extension isn't able to provide its own completions, such as after the keyword "struct" or "class".

**Comment by Jason-WT** [comment] 2021-07-10 03:27
I tried: Reset IntelliSense Database command. But it just work for the first several seconds and then failed again. Maybe the workspace has some conflicts but I don't know why.

**Comment by Colengms** [comment] 2021-07-12 18:19
Hi @Jason-WT .  Is this something you could reduce into a stand-alone repro that we could use to investigate further?

It's possible that something prior to the edit you are making is not being successfully parsed.  If no problems are detected for the file, it's possible there could be an issue in a header that is not being reported.  You may be able to determine that by preprocessing the file (i.e. with the `-E` arg, if using gcc or clang).

Also, could you enable logging using `"C_Cpp.loggingLevel": "Debug"` and provide the output of the C/C++ output channel leading up to the repro?

**Comment by v-ericawu** [comment] 2021-07-13 03:01
Sorry, we cannot reproduce the issue, can you provide us with your existing .cpp file?
![image](https://user-images.githubusercontent.com/78774400/125382709-bf74cf80-e3c8-11eb-85bb-1d04effdb175.png)

**Comment by v-ericawu** [comment] 2021-07-13 03:02
@Jason-WT Sorry, we cannot reproduce the issue, can you provide us with your existing .cpp file?
![image](https://user-images.githubusercontent.com/78774400/125383304-cd772000-e3c9-11eb-88a0-f71431aff459.png)

**Closed as completed** 2021-10-02 06:57 UTC
Labels: Language Service, more info needed, Not Repro - Internal
