### ISSUE TITLE
#else is confused with the C++ else keyword

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode-cpptools#3690] opened 2019-05-24 18:39 UTC
Issue Type: <b>Bug</b>

Type #else and watch the suggestions list

![else_snippet_bug](https://user-images.githubusercontent.com/13824553/58349619-9e337c80-7e18-11e9-93b5-49976efe50f2.PNG)

Extension version: 0.23.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

**Comment by sean-mcmanus** [comment] 2019-05-24 20:32
How do you repro that? It isn't reproing for me.
![image](https://user-images.githubusercontent.com/19859882/58355161-4ef54800-7e28-11e9-8990-be2984741a5f.png)

**Comment by sean-mcmanus** [comment] 2019-05-24 20:33
Oh -- I got it to repro after invoking the completion after the entire word is typed. This might be semi-"by design".

**Comment by sean-mcmanus** [comment] 2019-05-24 20:34
Are you able to repro the issue when actually typing "#else"? If I paste "else" I repro it...might be timing dependent if your initial typing isn't processed fast enough.

**Comment by tlemo** [comment] 2019-05-24 20:37
@sean-mcmanus : the auto completion happens after typing the whole #else as you observed. To make things worse, if statement snippets are enabled VS Code will insist on inserting { }

**Comment by tlemo** [comment] 2019-05-24 20:39
(and yes, it repros while typing, no pasting required)

**Comment by sean-mcmanus** [comment] 2019-05-24 21:15
Thanks for reporting this. It repros 100% if the previous preprocessor is a "#if 0" (which can unintentionally invoke the "else" snippet when enter is pressed). It should be fixed in our next update unless we hit some issue after further testing. Similar bugs would occur for other preprocessor keywords (not just "else"), which have been fixed as well.

**Comment by tlemo** [comment] 2019-05-24 21:28
Great, thanks!

**Comment by sean-mcmanus** [comment] 2019-06-14 23:19
Fixed with 0.24.0-insiders (available by setting "C_Cpp.updateChannel" to "Insiders").

**Closed as completed** 2019-07-04 02:23 UTC
Labels: bug, Language Service, fixed, quick fix, Feature: Auto-complete
