### ISSUE TITLE
Add "Jump to cursor" debugging functionality

### ISSUE THREAD

**Issue by daravi** [microsoft/vscode-cpptools#3936] opened 2019-07-17 20:39 UTC
Type: Debugger
**Feature Request**

As per the new stable release (1.36), VSCode now supports debugging extensions' ability to add a "Jump to cursor" functionality to the context menu and/or the command palette. 

This will let the debugger to skip code and [jump to a specific line](https://sourceware.org/gdb/onlinedocs/gdb/Jumping.html) to continue the execution.
[
This is already implemented in the C# extension](https://github.com/OmniSharp/omnisharp-vscode/issues/3117). It would be great if the C++ extension also implements the feature.

**Comment by WardenGnaw** [comment] 2019-07-18 02:35
This feature will need to do a couple things:

- Implement `-exec-jump` in [MIEngine](https://github.com/microsoft/MIEngine/blob/master/src/MICore/CommandFactories/gdb.cs).

<details>
<summary>The -exec-jump Command</summary>
<p>

**Synopsis**
```-exec-jump location```
Resumes execution of the inferior program at the location specified by parameter. See Specify Location, for a description of the different forms of location.

**GDB Command**
The corresponding GDB command is ‘jump’.

Example
```
-exec-jump foo.c:10
*running,thread-id="all"
^running
```
From https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Program-Execution.html
</p>
</details>

- Update protocol in [OpenDebugAD7](https://github.com/microsoft/MIEngine/tree/master/src/OpenDebugAD7)

**Comment by pieandcakes** [comment] 2019-07-18 18:26
This is a duplicate of the work to do in #1025. Please go vote on that issue.

**Closed as completed** 2019-07-18 18:26 UTC
Labels: duplicate, debugger, Feature Request
