### ISSUE TITLE
Unable to Step next or hit breakpoints

### ISSUE THREAD

**Issue by articulatesnail** [microsoft/vscode-cpptools#1659] opened 2018-03-09 13:15 UTC
OS: Windows 10
 VS Code version: 1.20.1
 C/C++ version:  0.15.0
When I start debugging I'm able to enter my inputs in the terminal window, and I don't appear to hit any breakpoints in the GUI. When I attempt to step over, into, or out, I get an error saying:

"Unable to step next. Operation failed with error code 0x80004004."

In the debug console it states:
`ERROR: Unexpected GDB output from command "-exec-next". Cannot find bounds of current function
`
Below is my launch.json file:
`{

    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/1_26.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "c:\\mingw\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}`

**Comment by WardenGnaw** [comment] 2018-03-09 22:42
@articulatesnail Did you compile with ```-g```? 

If you did, can you also copy what appears in the output window when you enable logging. You can do this by adding the following to you launch.json.
```
"logging": {
   "engineLogging": "true"
}
```

**Comment by articulatesnail** [comment] 2018-03-10 03:57
Sorry, what does it mean to "compile with -g"? What setting specifies what I compile with?

**Comment by sean-mcmanus** [comment] 2018-03-11 01:55
You pass -g to your compiler on the command line (or the "args" for your build task).

**Comment by articulatesnail** [comment] 2018-03-17 11:09
Sorry for the delay, here's what I see in the output window.

`1: (27787) <-1021-thread-select 2
1: (27793) ->1021^done,new-thread-id="2",frame={level="0",addr="0x774a041c",func="??",args=[]}
1: (27793) ->(gdb)
1: (27793) 1021: elapsed time 6
1: (27793) ->&"\n"
1: (27793) ->^done
1: (27793) ->(gdb)
1: (27795) <-1022-exec-next
1: (27804) ->1022^error,msg="Cannot find bounds of current function"
1: (27804) ->(gdb)
1: (27804) 1022: elapsed time 8
1: (27804) ->&"\n"
1: (27804) ->^done
1: (27804) ->(gdb)
ERROR: Unexpected GDB output from command "-exec-next". Cannot find bounds of current function
`

**Comment by WardenGnaw** [comment] 2018-03-19 20:45
@articulatesnail Can you provide more information on how you are building your project? Are you linking to a library with optimized code and attempting to hit a breakpoint there?

**Comment by articulatesnail** [comment] 2018-03-20 05:20
Problem solved!  I reconfigured my tasks.json and launch.json to the following:
```

// tasks.json
   // See https://go.microsoft.com/fwlink/?LinkId=733558
   // for the documentation about the tasks.json format
   "version": "2.0.0",
   "tasks": [
      {
         "label": "echo",
         "type": "shell",
         "command": "g++ -g kthSorting5_13.c -o kthSorting5_13",
         "args": [],
         "group": {
            "kind": "build",
            "isDefault": true
         }
      }
   ]



//launch.json
   "version": "0.2.0",
   "configurations": [
      {
         "name": "(gdb) Launch",
         "type": "cppdbg",
         "request": "launch",
         "program": "${workspaceFolder}/kthSorting5_13.exe",
         "args": [],
         "stopAtEntry": false,
         "cwd": "${workspaceFolder}",
         "environment": [],
         "externalConsole": true,
         "MIMode": "gdb",
         "miDebuggerPath": "C:\\mingw\\bin\\gdb.exe",
         "preLaunchTask": "echo",
         "setupCommands": [
            {
               "description": "Enable pretty-printing for gdb",
               "text": "-enable-pretty-printing",
               "ignoreFailures": true
            }
         ],
         "logging": {
            "engineLogging": true,
         }
      }
   ]

```

**Comment by Mishurin** [comment] 2018-03-26 14:15
Any news regarding this?
I am using similar configuration but with visual code, gcc and cygwin.
![1_range_of_types c - kernighan-ritchie - visual studio code 2018-03-26 16 14 44](https://user-images.githubusercontent.com/5419132/37911637-e7b6d0b0-3110-11e8-8044-f3d30bcad19f.png)

My launcher has:
{
        "version": "0.2.0",
        "configurations": [
            {
                "name": "(gdb) Launch",
                "type": "cppdbg",
                "request": "launch",
                "program": "${workspaceFolder}/a.exe",
                "args": [],
                "stopAtEntry": false,
                "cwd": "${workspaceFolder}",
                "environment": [],
                "externalConsole": true,
                "MIMode": "gdb",
                "miDebuggerPath": "C:/cygwin64/bin/gdb.exe",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ],
                "logging": {
                    "engineLogging": true
                }
            }
        ]
    }

My build task:
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "C build",
            "type": "shell",
            "command": "gcc",
            "args": [
                "-g", "${workspaceFolder}/2/1_range_of_types.c"
            ],
            "problemMatcher": [
                "$gcc"
            ]
        }
    ]
}

**Comment by WardenGnaw** [comment] 2018-03-26 21:28
@Mishurin What version of GDB are you using?

**Comment by Mishurin** [comment] 2018-03-27 12:08
Prompt shows me that I use GNU gdb (GDB) (Cygwin 7.10.1-1) 7.10.1

**Comment by Mishurin** [comment] 2018-03-27 12:09
Maybe it makes sense to distribute requirements for using the plugin?

**Comment by WardenGnaw** [comment] 2018-03-27 20:44
@Mishurin There should be no requirements for versions. I was only asking to see if I could reproduce the error. 

I have tested it with:
* gcc version 6.4.0 (GCC)
* GNU gdb (GDB) (Cygwin 7.10.1-1) 7.10.1
and can not reproduce the error with your given code snippet.

**Comment by Mishurin** [comment] 2018-03-28 08:40
@WardenGnaw, thank you for quick responses. I am using currently gcc version 5.4.0 (GCC). I will try to configure it with the version as you do and will report.

**Comment by Mishurin** [comment] 2018-03-28 09:06
I run cygwin installer again and found gcc compilers collection. And it worked 👍 
![cygwin setup - select packages 2018-03-28 11 02 34](https://user-images.githubusercontent.com/5419132/38019482-f75f5a38-3277-11e8-9e4c-5123105f9c41.png)

**Comment by WardenGnaw** [comment] 2018-03-28 22:05
Closing since @articulatesnail and @Mishurin have resolved their issues.

**Closed as completed by WardenGnaw** 2018-03-28 22:05 UTC
