### ISSUE TITLE
Syntax highlighting confuses parameter type in a function declaration for paramter identifier if no identifier is specified.

### ISSUE THREAD

**Issue by sbeve72** [microsoft/vscode-cpptools#8510] opened 2021-12-09 16:38 UTC
Issue Type: <b>Bug</b>

I made an issue on VCS official repository where I was told this problem is related to this extension (which I doubt because even after disabling/uninstalling) the extension, the issue persists but I am going to describe the issue here anyway

In the below function declaration:

```c
void somefun(unsigned int);
```

VSC incorrectly colors the `int` keyword with light blue (when it should be dark blue like all keywords) and thinks it is an identifier and treats it as such. Upon adding an idenitifer to the function declaration, it works as expected. So, the code below is color coded correctly:

```c
void somfun(unsigned int someparam);
```

It's a very common practice to declare functions before defining them at the top of source files without parameter names so this is quite annoying when syntax highlighting doesn't get it right.

Extension version: 1.7.1
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.11.0-41-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8300 CPU @ 3.70GHz (4 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.50GB (0.17GB free)|
|Process Argv|--unity-launch --disable-features=SendMouseLeaveEvents --crash-reporter-id e295b45c-908c-41c9-a5f0-92489d35bfb2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30408636
vscop804:30404766
vs360cf:30404996
vsrem710:30405998
vscexrecpromp3t3:30407764

```

</details>

**Comment by sbeve72** [comment] 2021-12-09 16:40
The issue can be seen with function declarations like the one below as well:

```c
double atof2(int size, const char[]);
```

where VSC confuses `char` for the identifier of the parameter and highlights it with light blue (instead of dark blue which is the color used for all keywords throughout my code elsewhere). As you can see, Github gets this right but VSC/Extension doesn't.

**Comment by Colengms** [comment] 2021-12-09 20:20
Hi @sbeve72 .  I believe you are correct that this issue is not related to the C/C++ extension.  The C/C++ extension provide semantic tokens.  Colorization of syntactic/lexical tokens come from VS Code itself and the TextMate grammar that it uses.  (The TextMate grammar for C/C++ is contributed to VS Code from this repo: https://github.com/jeff-hykin/better-cpp-syntax )

One way to be sure is to run the `Developer: Inspect Editor Tokens and Scopes` command, then click on a token to inspect.  If no info is displayed regarding "semantic tokens", the issue is not related to the C/C++ extension.

That said, I'm unable to reproduce the issue, using VS Code 1.63.0.  Is it possible you have another extension installed that might be injecting an alternative set of TextMate grammar rules into VS Code?  (I assume you are working with C and C++ source files).

You might consider installing the Better C++ Syntax extension.  That is published by the author of the TextMate grammar that is contributed to VS Code, and sometimes contains recent changes.

**Comment by Colengms** [comment] 2021-12-09 20:26
Aha.  I'm able to reproduce it, but only in a `.c` file, not a `.cpp` file.  I can confirm that the issue continues even if the C/C++ extension is not installed.  I'd suggest opening an issue here, if there isn't one already: https://github.com/jeff-hykin/better-cpp-syntax

**Comment by sbeve72** [comment] 2021-12-10 04:45
Thank you, I will open an issue on that repo. This would be my third issue for this problem but I guess that's okay.

**Comment by sbeve72** [comment] 2021-12-10 05:01
https://github.com/jeff-hykin/better-cpp-syntax/issues/580
I made an issue on that repo in case you want to add on to what I said there.

**Comment by Colengms** [comment] 2021-12-10 19:43
Closing this issue as external.

**Closed by Colengms** 2021-12-10 19:43 UTC
Labels: Language Service, more info needed, Feature: Colorization
