### ISSUE TITLE
Formater does works in one folder while does not in another

### ISSUE THREAD

**Issue by moojek** [microsoft/vscode-cpptools#4494] opened 2019-10-25 21:29 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Manjaro Linux, kernel: 5.0.1-MANJARO 
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.0
- Other extensions you installed (and if the issue persists after disabling them): Bracket Pair Colorizer, Discord Presence, HTML Preview, LaTeX Workshop, Material Icon Theme, Noctis, Power Mode, Todo Tree, vscode-pdf
- A clear and concise description of what the bug is.

**To Reproduce**

1. Open file
2. Try to format document with either Ctrl+Shift+I or Ctrl+Shift+P -> Format document
3. Not working in one folder and in second it does

**Expected behavior**

The code should get formatted
**Screenshots**

**Additional context**
 
C/C++ output in this folder does not output anything related to formatting.
Running the binary file clang-format as suggested in other issues works (outputs correctly formatted code to terminal)

**Comment by sean-mcmanus** [comment] 2019-10-25 22:20
Are you using a multi-root workspace? If so, I believe this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/2107 and will get fixed after we re-write our extension to have a single language server per-workspace with one format provider and document handler.

**Comment by moojek** [comment] 2019-10-26 15:58
Do you mean one workspace with few folders? Yes, I am. Sorry for dupliacte, I couldn't found the issue anywhere. When could it possibly work again?

**Comment by sean-mcmanus** [comment] 2019-10-28 22:27
We're planning to have it fixed for 0.26.2.

**Comment by michelleangela** [comment] 2020-05-21 18:49
Closing as duplicate.

**Closed as completed by michelleangela** 2020-05-21 18:49 UTC
Labels: bug, duplicate, Language Service, more info needed, Feature: Code Formatting
