### ISSUE TITLE
Call Hierarchy should show function as parameter

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode-cpptools#11146] opened 2023-06-30 05:51 UTC
This is a feature request I've already post yesterday, But one of your team, @michelleangela, falsely think the feature need to be determined until so-called "RUNTIME". I don't think your team, as a Microsoft team, should've made such a mistake on a naive C/C++ concept.

This is @michelleangela 's original post:
--- 
Thank you for submitting this feature. However, it is by design that call hierarchy does not find references to functions used as a parameter. This is because a function as a parameter is not a function call, but is being used as a parameter or a function pointer. A function pointer is a variable that stores the memory address of a function. When the function pointer is called, it will execute the function whose address it holds. Therefore, the actual function of the example `void(*func)(void)` in `void g(void(*func)(void))` is not determined until runtime.

_Originally posted by @michelleangela in https://github.com/microsoft/vscode-cpptools/issues/11142#issuecomment-1613627070_
            
---
And this is what I reply:
---
What? I don't think a Microsoft guy should have made such mistakes.
```c
// Following is two DECLARATIONS, not some runtime code or what!
void f(void);
void g(void(*func)(void));
...
// This is where the `Call Hierarchy` should figure out, I DON'T think this need to be located in RUNTIME
void whatever_the_name() {
    g(f);
}
```
BTW, there's no RUNTIME concept in C/C++, there're only compile or link.

**Comment by bobbrow** [comment] 2023-06-30 17:28
Closing as a duplicate of #11142.  When an issue is closed and you disagree with the decision, the discussion should continue on that issue instead of opening duplicates.  Thank you.

**Closed as not planned by bobbrow** 2023-06-30 17:28 UTC
Labels: duplicate
