### ISSUE TITLE
Crosscompilation and custom sysroot option

### ISSUE THREAD

**Issue by icegood** [microsoft/vscode-cpptools#6611] opened 2020-12-02 12:47 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux ice-ubuntu 5.8.0-31-generic #33-Ubuntu SMP Mon Nov 23 18:44:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- VS Code Version: 
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.0-31-generic

- C/C++ Extension Version:  v1.1.2
Preconditions:
1) Custom configuration in c_cpp_properties.json  is created.
compilerPath is "path/to/compiler --sysroot=/path/to/sysroot"
**Steps to reproduce**

Expected result:

1) All functions should be found within headers in custom sysroot.
2) Moreover if integration with cmake-tools done then only pathes from target_include_libraries should be added
3) 

Actual result:
1) no headers are parsed. Instead, system headers are found instead of custom ones in sysroot.

**Comment by Colengms** [comment] 2020-12-02 20:30
Hi @icegood .  Thanks for reporting this.  We've recently implemented parsing of sysroot args, so this should be addressed by our next full release (1.2).  We used https://github.com/microsoft/vscode-cpptools/issues/1575 to track that fix, so closing this as a dupe.

**Closed as completed by Colengms** 2020-12-02 20:30 UTC
Labels: duplicate, Language Service, Feature: Configuration

**Comment by sean-mcmanus** [comment] 2020-12-04 20:57
We're also tracking a similar issue at https://github.com/microsoft/vscode-cpptools/issues/1083 for 1.2 or 1.3.

**Comment by icegood** [comment] 2020-12-07 10:48
When 1.2 is expected to be released?

**Comment by sean-mcmanus** [comment] 2020-12-07 21:20
We're still working on fixing regressions with 1.2.0-insiders, so it might not be available till January (due to holiday vacations).

**Comment by sean-mcmanus** [comment] 2021-01-21 07:48
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
