### ISSUE TITLE
 'debug Adapters' causes an encoding problem on Windows.

### ISSUE THREAD

**Issue by thefatwhale** [microsoft/vscode-cpptools#7516] opened 2021-05-12 17:29 UTC
Bug type: Debugger
#  'debug Adapters' causes an encoding problem on Windows.
> ".vscode\extensions\ms-vscode.cpptools-1.3.1\debugAdapters\bin\WindowsDebugLauncher.exe"

#### So this cause a encoding problem. (use 2 kind of encoding on 1 program).

**So I suggest give back the choice of console's encoding to users**
**give their a choice of console encoding**
> It may be possible to refer to the java extension solution
use a batch (.bat) file to change the Active Code Page(chcp 65001)
Instead of to change Active Code Page in a Exe file.
In this way user can cancel this feature by comment (REM) this command line.
Or using other method to solve this bug(Graphical controls Setting)
(This screenshot is Java Debugger Extension's solution):
[![g0t780.png](https://z3.ax1x.com/2021/05/13/g0t780.png)](https://imgtu.com/i/g0t780)

**Describe the bug**
- OS and Version: Microsoft Windows 7 x64
- VS Code Version: 1.56.1
- C/C++ Extension Version: 1.3.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Go to C source file
2. Run it
3. Encoding problem

> Manual compilation and runs successfully
[![g0tz5R.png](https://z3.ax1x.com/2021/05/13/g0tz5R.png)](https://imgtu.com/i/g0tz5R)

> Use Extension to compilation and run
[![g0NFKO.png](https://z3.ax1x.com/2021/05/13/g0NFKO.png)](https://imgtu.com/i/g0NFKO)

**Please Fix This**

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment] 2021-05-12 18:11
Duplicate of: https://github.com/microsoft/MIEngine/issues/1120

**Closed as completed by WardenGnaw** 2021-05-12 18:11 UTC
Labels: duplicate, debugger

**Comment by thefatwhale** [comment] 2021-05-14 06:27
https://github.com/microsoft/MIEngine/pull/1025
👆 This PR can solve this problem. I tried on my Simplified Chinese Version Windows. Please fix
this bug
