### ISSUE TITLE
Formatter cannot be run on new files until they have been saved 

### ISSUE THREAD

**Issue by abyrd-phx** [microsoft/vscode-cpptools#9295] opened 2022-05-11 21:01 UTC
Bug type: Language Service

I thought this was an issue with VS Code itself due to this issue
https://github.com/microsoft/vscode-cpptools/issues/8230

But looks like it's an issue with the C++ extension specifically
https://github.com/microsoft/vscode/issues/149215

**Describe the bug**
VS Code version: Code 1.67.0
OS version: Windows_NT x64 10.0.19044
C/C++ Extension Version: v1.9.8

**Steps to reproduce**
* Create a new file, set its language to C++
* Open the command palette and type "Format"
* Notice most of the formatting options are missing (Format Modified Lines, Format Selection, Format Document With...)
* Select Format Document
* Notice the error message: There is no formatter for 'cpp' files installed.

**Comment by sean-mcmanus** [comment] 2022-05-11 22:25
Duplicate of #4143

**Closed as not planned by sean-mcmanus** 2022-05-11 22:25 UTC
