### ISSUE TITLE
C/C++ shows error type for templated variables

### ISSUE THREAD

**Issue by PythonCoderAS** [microsoft/vscode-cpptools#10260] opened 2022-12-11 00:16 UTC
Type: <b>Bug</b>

Have a templated map or set type, such as:

```c++
#include <map>

template <class T>
bool val_in_map(std::map<T, char>& x, T val){
    std::map<T, char>::iterator it = x.find(val);
    return it != x.end();
}
```

The variable `it` will be `<error-type>`.

Extension version: 1.13.7
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:37:54.581Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 2b0708f4-d206-4f56-bb5c-21ca647cc418|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by browntarik** [comment] 2022-12-12 18:18
Thank you for submitting your issue! We will look into this bug as soon as possible.

**Comment by sean-mcmanus** [comment] 2022-12-20 23:59
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/1946

i.e. it gives the same error in VS, but becomes fixed after the UI used to assign a type to T:
![image](https://user-images.githubusercontent.com/19859882/208789394-d432716e-ce0b-4761-8c8d-ca19f9445a63.png)

**Closed as not planned by sean-mcmanus** 2022-12-20 23:59 UTC
Labels: bug, duplicate, Language Service

**Comment by PythonCoderAS** [comment] 2022-12-21 03:32
@sean-mcmanus This is similar but not identical. For example, the iterator autocomplete should be available regardless of what the actual types are.

**Comment by sean-mcmanus** [comment] 2022-12-27 23:38
Our IntelliSense engine can provide autocomplete for the iterator if it isn't able to resolve it for an actual type. Are you referring to something for which IntelliSense has the type?

**Comment by PythonCoderAS** [comment] 2022-12-28 00:27
Oh no, I was referring about unknown type. I didn't know it wouldn't work with unknown types, like a vector of unknown type.
