### ISSUE TITLE
Alt+O doesn't honor files.exclude

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode-cpptools#485] opened 2017-02-10 15:18 UTC
When swithching to matching header file, which is in another folder, all goes well. But switching back picks another matching source file (same folder as header file). Despite excluding all .c files in that folder. 

E.g having src/file.c open and hitting Alt+O.
```
src/file.c
obj/file.c (should be exluded by files.exclude rule)
obj/file.h
```

Rule: `"**/obj/*.c": true`

**Comment by sean-mcmanus** [comment] 2017-02-10 18:21
Yes, you are right, The current header switching doesn't use the browse database and just creates its own isolated data structure and search which doesn't look at any of the exclude settings (in addition to other problems). We've implemented header switching using the browse database so this should be fixed in the next update, assuming we don't find some problem with the new implementation that causes us to revert the change.

**Comment by bobbrow** [comment] 2017-03-02 00:52
This should be fixed in 0.10.2.  Please reopen if you continue to see the issue.

**Closed as completed by bobbrow** 2017-03-02 00:52 UTC
Labels: bug, Language Service, fixed

**Comment by csholmq** [comment] 2017-03-21 12:46
@bobbrow  Still present in 0.10.4. :(

**Comment by sean-mcmanus** [comment] 2017-03-21 12:48
We changed the behavior to always look in the same folder first, but it doesn't look at the files.excludes in that case...is that what is happening? As in, was this fixed in 0.10.3?

**Comment by csholmq** [comment] 2017-03-21 12:54
Correct. When switching to the .h it jumps to obj/out (since my .h files are auto generated there). When I then try to switch back it doesn't look at files.exclude and instead selects another, copied, .c file in the same folder (out/obj).

**Comment by sean-mcmanus** [comment] 2017-03-21 14:12
Okay, it's been fixed, and there was another "bug" in which the files.exclude would be parsed after it was manually opened. We might be able to release that in today's update.

**Comment by sean-mcmanus** [comment] 2017-03-23 01:29
With 0.10.5, it no longer switches to excluded files as long as the excluded file stays out of the browse database. Unfortunately, we found scenarios right before shipping that can cause the excluded files to enter the database and then file switching to happen. We intend to fix these in the next update.

**Comment by csholmq** [comment] 2017-03-23 06:17
Sounds solid. Will test later today.

In future releases, will modifying files.exclude also remove files from database? Not very intuitive having to purge the database each time you make an edit.

**Comment by sean-mcmanus** [comment] 2017-03-23 14:02
Modifying the files.excludes removes files from the database right now...the problem is that it will freeze the main thread while it searches for all the files to remove.

**Comment by csholmq** [comment] 2017-03-23 18:22
Confirmed to work!

So editing my settings.json would trigger that behaviour or do I have to actually add or remove an entry in the files.exclude?

**Comment by sean-mcmanus** [comment] 2017-03-23 19:28
Only modifying the files.exclude setting should trigger the potential freeze as it tries to remove all the excluded files on the main thread.

**Comment by csholmq** [comment] 2017-03-23 19:28
Oh, ok. Good to know. Well, better than no action!
