### ISSUE TITLE
When "Goto Define" is in another file, it will given a warning if the file is not opened.

### ISSUE THREAD

**Issue by JasonLeeCn** [microsoft/vscode-cpptools#3803] opened 2019-06-20 07:18 UTC
Issue Type: <b>Bug</b>

Example: Test_FuncB is in file TestB.c, and be using in TestA.c. The TestB.c file is not open.

If using "Go to Define" for jump to Test_FuncB in TestA.c file, it will given a warning as follow:

This file (d:\xxx\TestB.c) is already opened in the editor but with a different casing. IntelliSense features will be disabled on this copy of the file.

But if the TestB.c file is opened in editor, no this problem.

Extension version: 0.24.0-insiders
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.66GB (3.86GB free)|
|Process Argv|D:\VS BugTest|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by michelleangela** [comment] 2019-06-20 19:44
Thank you for reporting the issue.

This is a duplicate of #3786

**Closed as completed by michelleangela** 2019-06-20 19:44 UTC
Labels: duplicate, Language Service

**Comment by sean-mcmanus** [comment] 2019-06-26 02:12
Fixed with 0.24.0-insiders2. Set the "C_Cpp.updateChannel" setting to "Insiders" to auto-install it.
