### ISSUE TITLE
Disassembly view is blank on linux

### ISSUE THREAD

**Issue by abrahammurciano** [microsoft/vscode-cpptools#7960] opened 2021-08-11 16:19 UTC
Bug type: Debugger

**Describe the bug**
- OS and Version: Arch Linux 5.13.9-arch1-1
- VS Code Version: 1.59.0
- C/C++ Extension Version: 1.5.1
- Desassembly view is blank for C or C++ on linux.

**To Reproduce**

launch.json
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "gcc - Build and debug active file",
			"type": "cppdbg",
			"request": "launch",
			"program": "${fileDirname}/${fileBasenameNoExtension}",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${fileDirname}",
			"environment": [],
			"externalConsole": false,
			"MIMode": "gdb",
			"setupCommands": [
				{
					"description": "Enable pretty-printing for gdb",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				}
			],
			"preLaunchTask": "C/C++: gcc build active file",
			"miDebuggerPath": "/usr/bin/gdb"
		}
	]
}
```

tasks.json
```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc build active file",
            "command": "/usr/bin/gcc",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

My c code
```c
#include <stdio.h>

int main() {
	int counter = 1;
	while (counter <= 5) {
		printf("%d\n", counter);
		++counter;
	}
	return 0;
}
```

1. Open any C or C++ file.
2. Add a breakpoint.
3. Start the debugger.
4. Right click anywhere in the code and click Open Disassembly View.
5. An empty tab opens up instead of displaying the assembly code. (see screenshot)

![image](https://user-images.githubusercontent.com/25041135/129065802-479c6c0a-94f8-4e6f-9888-07c14e73a950.png)

**Comment by DenverCoder1** [comment] 2021-08-11 17:06
Having the same issue. My configuration is similar (Arch Linux 5.13.8-arch1-1, VS Code 1.59.0)

It should be working in 1.59.0 according to [this blog post](https://devblogs.microsoft.com/cppblog/visual-studio-code-c-july-2021-update-disassembly-view-macro-expansion-and-windows-arm64-debugging/).

Gif reproduction, disassembly tab does not show any output:

![Peek 2021-08-11 20-02](https://user-images.githubusercontent.com/20955511/129071963-0278f1f1-bf38-4a3e-8c94-955fb10798d6.gif)

**Comment by Colengms** [comment] 2021-08-12 23:54
This should be addressed in 1.6.0-insiders.

**Closed as completed by Colengms** 2021-08-12 23:54 UTC
Labels: debugger, fixed

**Comment by freyjadomville** [comment] 2021-08-30 15:32
Can this issue be reopened? I seem to be running 1.6.0 and I am still experiencing this issue. System details in the about dialog of the screenshot.

![image](https://user-images.githubusercontent.com/45965242/131364575-03e569a0-c620-4eef-b07e-f10d28adcca7.png)

**Comment by freyjadomville** [comment] 2021-08-30 15:33
Please let me know if I'm missing an executable that the extension relies on for disassembly.

**Comment by freyjadomville** [comment] 2021-08-30 15:41
I can get the disassembly when there's library code, but it seems to not want to show anything in user-facing code, on Linux. Is that a new issue?

**Comment by freyjadomville** [comment] 2021-08-30 15:48
Ah, never mind, seems to be a mistake on my part as a result of optimisations. removing `-O2` from my project gets the debuginfo to be found again, even if the `-g` flag is emitted. Is that expected?

**Comment by yuehuang010** [comment] 2021-08-30 16:17
It uses the stackframe to locate the current address.  Without debug information, perhaps, it couldn't resolve the stackframe.  
Do you have "-fno-omit-frame-pointer" or similar flag?  This optimization, implied from -O1, will decrease the chance of debugger from locating stackframe.

**Comment by freyjadomville** [comment] 2021-08-31 07:33
ahhh, OK, good to know, thanks.
