### ISSUE TITLE
C/C++ Intellisense taking too long to start up even with small workspaces

### ISSUE THREAD

**Issue by sagnik-t** [microsoft/vscode-cpptools#12337] opened 2024-05-28 10:44 UTC
### Environment

- OS and Version: Windows 11, Zorin 17 (based on Ubuntu 22.04)
- VS Code Version: 1.89.1
- C/C++ Extension Version: 1.20.5
- If using SSH remote, specify OS of remote machine: N/A

#### Bug Summary:
The C/C++ intellisense takes about 4-5 minutes to function properly. During this time, proper linting also doesn't work for certain classes such as `vector`.

#### Steps to reproduce:
1. Simply open VS code
2. Write some C/C++ code, preferably using STL

#### Expected behavior:
Intellisense shouldn't take this long since the workspace is not very large.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

### Other Extensions

The issue persists even all other extensions are disabled.

**Comment by sean-mcmanus** [comment] 2024-05-28 17:52
@sagnik-t That doesn't sound expected. Which process is using cpu during this time? With C_Cpp.loggingLevel set to "Debug" what is being output or what is the last output?

**Comment by sean-mcmanus** [comment] 2024-07-03 17:47
@sagnik-t I think this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/12292 . We added more stuff to the database so it takes longer to populate.

**Closed as not planned** 2024-09-02 12:15 UTC
Labels: duplicate, Language Service, performance
