### ISSUE TITLE
IntelliSense results for a source file should include any error discovered in its headers

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#11779] opened 2023-12-13 21:34 UTC
Opening this issue to track reporting errors for unopen headers.  In the IntelliSense results for a source file, VS will report errors encountered in header.  Cpptools is not currently reporting these.  Doing so will require some work to manage merging/deduping of header results from multiple TUs, and to properly clear out header results when all associated source files have been closed.

**Comment by starball5** [comment] 2024-02-26 01:33
even those found as system headers when using a compile commands database?

**Comment by bobbrow** [comment] 2024-12-31 19:33
This is a duplicate of #3873

**Closed as duplicate by bobbrow** 2024-12-31 19:33 UTC
Labels: Language Service, Feature Request, Works in VS
