### ISSUE TITLE
program will crash in libpng when debugging via vscode. it will not crash if run or debugged from terminal. 

### ISSUE THREAD

**Issue by arnoldemu** [microsoft/vscode-cpptools#3369] opened 2019-03-27 08:33 UTC
Hello,
I am seeing a crash when debugging my program within vscode. The crash doesn't happen if debugging outside of vscode or run from the terminal directly.

I am running the 'snap' vscode under Ubuntu 18.10 with default "unity" look window manager.

To reproduce this you will need the "cmake-tools-helper" extension installed because the build uses cmake. I have cmake 3.12.1 installed. I don't believe the issue I am seeing is with the extensions I am using because I can build the program executable with vscode using these extensions and then run that same program outside of vscode without a problem.

You will need to install wxwidgets development libraries because the program uses wxwidgets. Note that wxwidgets libraries are also linked against libpng.

Pre-requisites:

Install wxwidgets and cmake from terminal:

sudo apt-get install g++
sudo apt-get install cmake
sudo apt-get install libwxgtk3.0-dev

[minexp.zip](https://github.com/Microsoft/vscode-cpptools/files/3012224/minexp.zip)

Steps to reproduce:

    Run vscode from terminal. I am running as a normal user which can be elevated with "sudo" to install packages.
    Inside vscode use "open folder" and choose the folder where the CMakeLists.txt file is located for the program. See attached "minexp.zip"
    Click on the cmake triangle icon on the bar on the left to access the cmake tools.
    Click on the configure button/cmake smaller triangle at the top of the cmake tool window. Use gcc 6.5.0 if prompted. I tried clang with the same results. You need a compiler that can build programs. The cmake tools will fail to configure if you don't have one of those.
    Check configuration is successful in the output window.
    Click on the hammer button at the top of the cmake tool window. The code will build.
    Check build is successful.
    Check "export" program executable has been built inside the build folder which is located within the source directory.
    "Start Debugging" in vscode to debug the executable. I see gdb outputting logging. If it breaks at the start of the program "go" to make it run. You will see a dialog appear with a title and a menu. This is the program running.
    Click on the window and attempt to use the file menu.
    You will get see a crash in memcpy-sse3. In the callstack libpng is mentioned. It is not possible to skip this and continue.
    In a terminal go to the executable's location and run it and do the same as before. NOTE: It will not crash.
    In a terminal go to the executable's location run it via gdb and do the same as before. (gdb export, run). NOTE: it will not crash.

My expectation is that I can use the debugger in vscode and that it is consistent with running from the terminal or via gdb in the terminal in that the operation is the same, currently vscode is inconsistent with the other methods to run it.

I checked that the paths that the gdb launched from the terminal and the gdb launched by vscode were using for the shared libraries that were loaded. I saw they were the same. However, what I did see is that the gdb vscode is using is loading more libraries than the gdb run from the terminal. This may be part of the problem.

Thank you for your help.

Kevin

vscode information:

Version: 1.32.3
Commit: a3db5be
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-16-generic

CPUs | Intel(R) Xeon(R) CPU X5472 @ 3.00GHz (4 x 2556)
-- | --
GPU Status | 2d_canvas: disabled_softwarechecker_imaging: disabled_offflash_3d:  disabled_softwareflash_stage3d: disabled_softwareflash_stage3d_baseline:  disabled_softwaregpu_compositing:  disabled_softwaremultiple_raster_threads:  disabled_offnative_gpu_memory_buffers: disabled_softwarerasterization:  disabled_softwaresurface_synchronization: disabled_offvideo_decode:  disabled_softwarewebgl: disabled_offwebgl2: disabled_off
Load (avg) | 3, 2, 1

CPUs | Intel(R) Xeon(R) CPU X5472 @ 3.00GHz (4 x 2556)
-- | --
GPU Status | 2d_canvas: disabled_softwarechecker_imaging: disabled_offflash_3d:  disabled_softwareflash_stage3d: disabled_softwareflash_stage3d_baseline:  disabled_softwaregpu_compositing:  disabled_softwaremultiple_raster_threads:  disabled_offnative_gpu_memory_buffers: disabled_softwarerasterization:  disabled_softwaresurface_synchronization: disabled_offvideo_decode:  disabled_softwarewebgl: disabled_offwebgl2: disabled_off
Load (avg) | 3, 2, 1
Memory (System) | 3.85GB (1.50GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Memory (System) | 3.85GB (1.50GB free)
Process Argv |  
Screen Reader | no
VM | 0%

CPUs | Intel(R) Xeon(R) CPU X5472 @ 3.00GHz (4 x 2556)
-- | --
GPU Status | 2d_canvas: disabled_softwarechecker_imaging: disabled_offflash_3d:  disabled_softwareflash_stage3d: disabled_softwareflash_stage3d_baseline:  disabled_softwaregpu_compositing:  disabled_softwaremultiple_raster_threads:  disabled_offnative_gpu_memory_buffers: disabled_softwarerasterization:  disabled_softwaresurface_synchronization: disabled_offvideo_decode:  disabled_softwarewebgl: disabled_offwebgl2: disabled_off
Load (avg) | 3, 2, 1
Memory (System) | 3.85GB (1.50GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by leso-kn** [comment] 2019-05-16 14:24
I'm facing the same issue. Loading a GdkPixbuf from png files will fail when debugging from vscode.

I didn't yet figure out why this is happening either or how to work arround it (except for debugging via the terminal). In fact it took quite some time unitl i noticed this is actually related to the vscode debugger. I was assuming theres an issue within my code.

My specs:

**Platform** Ubuntu 19.04 amd64
**Code** vscode 1.33.1 (snap)
**Memory** 16gb DDR4
**Processor** Intel® Core™ i7-8650U CPU @ 1.90GHz × 8
**Graphics** Intel® UHD Graphics 620 (Kabylake GT2)

**Comment by fguilleme** [comment] 2019-10-06 09:48
Basically the same when I try to debug darktable

**Comment by arnoldemu** [comment] 2020-12-12 11:53
Adding a comment to keep this open.
Has this issue been fixed yet?

**Comment by sean-mcmanus** [comment] 2020-12-12 12:05
It hasn't been fixed as far as I know. Let us know if you see it fixed.

**Comment by zachs18** [comment] 2022-04-06 20:15
I am encountering this issue on amd64, VSCode 1.66.0, cpptools 1.9.7, Ubuntu 20.04, libpng16-16 1.6.37-2.

**Comment by zachs18** [comment] 2022-04-06 20:20
I have determined that the problem is that VSCode's GTK/GDK environment variables from snap are not being removed when running the debugged program, causing it to try to use the VSCode snap's version of GTK/GDK libraries, which will not work.

Fix: Clear `GDK_BACKEND`, `GDK_PIXBUF_MODULEDIR`, and `GDK_PIXBUF_MODULE_FILE` (maybe others?) environment variables before running the program. This works when running the program in the vscode terminal, but I do not know how to fix this while ddebugging.

**Comment by leso-kn** [comment] 2022-04-07 10:32
That's very interesting news! Perhaps a fix could be, to clean these variables in vscode-cpptools if not explicitly overwritten by the user?

**Comment by leso-kn** [comment] 2022-04-07 10:37
@zachs18 Could you try launching your GTK program with the following VScode debug configuration?

`[project]/.vscode/launch.json`:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/program",
            "MIMode": "gdb",
            "environment": [
                { "name": "GDK_PIXBUF_MODULEDIR", "value": "" },
                { "name": "GDK_PIXBUF_MODULE_FILE", "value": "" }
            ],
        }
    ],
    "compounds": []
}
```

**Comment by zachs18** [comment] 2022-04-11 01:55
Hacky workaround: add ```
	unsetenv("GDK_PIXBUF_MODULEDIR");
	unsetenv("GDK_PIXBUF_MODULE_FILE");
``` as the first line of `main()` before I do anything with gtk/gdk.

**Comment by leso-kn** [comment] 2022-04-12 09:02
Great workaround! I've been tinkering a bit meanwhile and found [this commit](https://github.com/microsoft/vscode/commit/96d03d1ecc393a047d549dc8bd13c74dc174f20a) from the official vscode repository (Oct. 2020). According to this commit, the issue should not occure in recent verisons of vscode.

I also checked out the `vscode-cpptools` extension and added some code to remove the environment variables, but the tests show that these variables in fact seem to be unset in the first place, even when launching vscode explicitly by:

```bash
> export GDK_PIXBUF_MODULEDIR="still set"
> export GDK_PIXBUF_MODULE_FILE="still set"
> code

# In vscode terminal:
> env | grep GDK
GDK_BACKEND=x11 # variables are gone
```

@zachs18 Did you debug your program using the latest version of vscode? If the version you're using was released after October 2020, the variables should be unset by [this line](https://github.com/microsoft/vscode/commit/96d03d1ecc393a047d549dc8bd13c74dc174f20a#diff-203836ac437fb3e21d1b59c98b79cc6108b7a32153cd673f9553b6c5f562685bR349) of code.

**Comment by leso-kn** [comment] 2022-06-03 09:50
Hey! Sorry for the late reply, the previous month has been quite busy.

That is very strange indeed. I'm not quite familiar with the debugging extension code (also this bug made me switch to the apt version of vscode).

According to your findings, it seems like the issue could be resolved by (re-)setting the SNAP variable when launching a task or debugging session (inside its subprocess, or the aparent dedicated environment of some kind).

Could we maybe escallate this to the extension developers, to determine the critical place in the code, where this would need to be adjusted?

Since this is not yet fixed, I'd propose to re-open the issue @sean-mcmanus

**Comment by sean-mcmanus** [comment] 2022-06-03 17:50
@WardenGnaw FYI

**Comment by lszl84** [comment] 2022-12-01 11:36
How do you determine the priority of an issue? It is a high priority for me, for example, and I guess for others developing with wxWidgets on Linux.

**Comment by sean-mcmanus** [comment] 2022-12-08 01:56
More upvotes might help.

**Closed as not planned** 2023-06-06 11:12 UTC
Labels: debugger, investigate: repro
