### ISSUE TITLE
C/C++ Extension 1.0.0 some feature Not working When using in Remote-SSH remote development

### ISSUE THREAD

**Issue by lemonchann** [microsoft/vscode-cpptools#6176] opened 2020-09-21 07:58 UTC
Type: General

**Describe the bug**
First of ALL: I use `Remote-SSH` Extension to connect to the Linux Centos remote server through the Host win10 for remote development.

When C/C++ Extension automatically upgraded from 0.29.0 to version 1.0.0, feature related to `Find reference`  doesn't work, but other features works well.  when Press `Shift+F12` the error log was output: `FE:'Compiler exited with error-No IL available'`

So i roll back the C/C++ Extension version to 0.29.0, it can works well. I wonder if there is a problem with this latest Extension ?

**Expect**: Features of  `find reference`  expected to work correctly.
**Actual**:
- `Find reference` not work
- `Find All references` not work
- error log `FE:'Compiler exited with error-No IL available'`

**System and version info**
- OS and Version: Host(Win10 64bit 18363.1082) Remote(centos x86_64)
- VS Code Version:1.49.1
- C/C++ Extension Version:1.0.0

**Comment by sean-mcmanus** [comment] 2020-09-21 17:49
This is most likely a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6114 (fix available with 1.0.1-insiders) or https://github.com/microsoft/vscode-cpptools/issues/6147 (fix should be available with 1.0.1 later today).

**Comment by sean-mcmanus** [comment] 2020-09-22 00:28
Can you update to 1.0.1 to see if this is fixed?

**Comment by lemonchann** [comment] 2020-09-22 06:46
1.0.1 version works well Thanks for figuring it out!

**Closed as completed** 2020-09-22 09:18 UTC
Labels: bug, duplicate, Language Service, more info needed
