### ISSUE TITLE
"Expands to" and "overloads" hover strings are not translated

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5340] opened 2020-04-21 19:15 UTC
See the screenshot at https://github.com/microsoft/vscode-cpptools/issues/5337 .

There are other error strings in the same location that may also need to be localized.

It looks unusual because the other IntelliSense error messages in the same hover are translated.

**Comment by Colengms** [comment] 2020-04-28 20:54
Similar to #5370 :
Since these aren't log messages, we're either going to need a new request/response so the native code can ask the TypeScript side to provide a localized string, or we'll need to reroute completion through the equivalent TypeScript provider class to allow the TypeScript side an opportunity to do localized string replacement before returning the results.

In this case, either we'd need a new req/resp, or hover would need to be rerouted through the equivialent TypeScript provider class.  Duping this to https://github.com/microsoft/vscode-cpptools/issues/5370

**Comment by Colengms** [comment] 2020-04-28 20:55
Closing a dupe of #5370

**Closed as completed by Colengms** 2020-04-28 20:55 UTC
Labels: bug, Language Service, world ready
