### ISSUE TITLE
Very slow debugger attachment

### ISSUE THREAD

**Issue by eguskov** [microsoft/vscode-cpptools#6943] opened 2021-02-10 12:22 UTC
I've faced an issue with the debugger since 1.2.0 update (On 1.1.3 everything works fine).
The debugger is so slow now.
I get a 1min+ time gap between hit `Run` and an application's window showing up.

The debugger gets to `"seq":759` very fast and then it waits for something about 1 min or more.

Here is the log output.
[vscode-cpptools.log](https://github.com/microsoft/vscode-cpptools/files/5958099/vscode-cpptools.log)

**Comment by eguskov** [comment] 2021-02-10 12:25
I've just rolled back to 1.1.3 because of that issue.

**Comment by WardenGnaw** [comment] 2021-02-11 22:17
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/6913

**Closed as completed by WardenGnaw** 2021-02-11 22:17 UTC
Labels: duplicate, debugger, performance
