### ISSUE TITLE
Different include paths for IntelliSenseMode `clang-x64` and `macos-clang-x64`

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#7448] opened 2021-04-30 21:56 UTC
For anyone else seeing this, I ran into a similar problem, and all I had to do was change in `c_cpp_properties.json`:

`"intelliSenseMode": "macos-clang-x64"`  to  `"intelliSenseMode": "clang-x64"`

For some reason, the `macos-clang-x64` include paths have most of the standard C/C++ includes, but not `stdarg.h`.
You can confirm this by looking at the differences between the following platform/toolchain include paths included with Xcode.

Here is the location of the `macos` includes, and have most header files, like `stddef.h`, but not `stdarg.h` for whatever reason:
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include`

Here is where the clang builtin includes are located, and has very similar files as the above, and *does* have `stdarg.h` to support variadic functions:
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/include`

It's a strange discrepancy.  If you query the `/usr/bin/clang` tool itself, using:  `clang++ -E -x c++ - -v < /dev/null`
You'll see that it includes both of the above directories in its system include path.
The C/C++ Extension for VSCode must have some special macOS setup for "macos-clang-x64" that avoids the clang toolchain directory above, and that's why `stdarg.h` of all files is causing the issue that surfaces in the error.

Hope this helps someone avoid some frustration...  :)

_Originally posted by @carter-thaxton in https://github.com/microsoft/vscode-cpptools/issues/5349#issuecomment-830320516_

**Comment by michelleangela** [comment] 2021-04-30 22:02
@sean-mcmanus It's correct that `clang-x64` on macOS and `macos-clang-x64` should be equivalent. An IntelliSenseMode without a platform variant are automatically changed to a mode with a platform that matches the host machine's platform.

 @carter-thaxton could you send the logs from running `C/C++: Log Diagnostics` from the VS Code command palette?

**Comment by Colengms** [comment] 2021-09-22 19:40
Bug type: Language Service

**Describe the bug**
- OS and Version: MacOS 11.6 BigSur
- VS Code Version: 1.60.1
- C/C++ Extension Version: 1.6.0

Ran into https://github.com/microsoft/vscode-cpptools/issues/7448 and here are requested diagnostics:

stdarg.h is found if I use `"intelliSenseMode": "clang-x64",` and not found if I use `"intelliSenseMode": "gcc-x64",`. See teh original bug for details.

C/C++ diagnostics from working setup:

```
-------- Diagnostics - 9/21/2021, 5:49:10 PM
Version: 1.6.0
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [],
    "compilerPath": "/usr/bin/g++",
    "cStandard": "c11",
    "intelliSenseMode": "clang-x64",
    "cppStandard": "c++14",
    "compilerArgs": [
        "-I /usr/local/include/SDL2",
        "-I include"
    ],
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/jussiku/dev/learn/metal/minity/src/main.cpp ]:
    /usr/local/Cellar/sdl2/2.0.16/include/SDL2/SDL.h
    /Users/jussiku/dev/learn/metal/minity/src/sdlHelpers.h
Translation Unit Configurations:
[ /Users/jussiku/dev/learn/metal/minity/src/main.cpp ]:
    Process ID: 21194
    Memory Usage: 196 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /usr/local/Cellar/sdl2/2.0.16/include/SDL2
        /Users/jussiku/dev/learn/metal/minity/include
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /usr/local/Cellar/sdl2/2.0.16/include/SDL2
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++14
    IntelliSense Mode: macos-clang-x64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 196 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 34523
Number of files parsed: 1846

```

C/C++ diagnostics from non-working setup:

```
-------- Diagnostics - 9/21/2021, 5:50:24 PM
Version: 1.6.0
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [],
    "compilerPath": "/usr/bin/g++",
    "cStandard": "c11",
    "intelliSenseMode": "gcc-x64",
    "cppStandard": "c++14",
    "compilerArgs": [
        "-I /usr/local/include/SDL2",
        "-I include"
    ],
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/jussiku/dev/learn/metal/minity/src/main.cpp ]:
    /Users/jussiku/dev/learn/metal/minity/src/sdlHelpers.h
Translation Unit Configurations:
[ /Users/jussiku/dev/learn/metal/minity/src/main.cpp ]:
    Process ID: 21243
    Memory Usage: 164 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /usr/local/Cellar/sdl2/2.0.16/include/SDL2
        /Users/jussiku/dev/learn/metal/minity/include
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Users/jussiku/dev/learn/metal/minity/src
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++14
    IntelliSense Mode: macos-clang-x64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 164 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 34347

```

_Originally posted by @jussikuosa in https://github.com/microsoft/vscode-cpptools/issues/8177#issue-1002656643_

**Comment by Colengms** [comment] 2021-09-22 19:56
Hi @jussikuosa .  I'm not able to easily reproduce this issue on my Mac.

Those system paths should be returned by the compiler when queried.  It would seem that the missing path was not returned by the compiler for some reason.  That may have something to do with different args passed to the compiler when queried.  Could you enable debug logging using `"C_Cpp.loggingLevel": "Debug"`, and provide the log output from the C/C++ channel from both scenarios?  That should include the args passed to the compiler.

**Comment by jussikuosa** [comment] 2021-09-23 09:12
Hello @Colengms, I updated vsc this morning and now I cannot reproduce the problem. I tried all `gcc-x64` / `clang-x64` and `g++` / `clang++` combinations with the debug level logging but every time the headers are found just fine 👍  I attached the c/c++ debug log just in case still if you want to take a peek... Feel free to close this case again from my part.

```
Version: 1.60.2
[c_cpp_debug_output.log](https://github.com/microsoft/vscode-cpptools/files/7216274/c_cpp_debug_output.log)

Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

**Closed as completed** 2021-09-23 18:20 UTC
Labels: Language Service, more info needed, Feature: Configuration
