### ISSUE TITLE
Autocomplete problem for variables declared as auto

### ISSUE THREAD

**Issue by hellmannx** [microsoft/vscode-cpptools#8209] opened 2021-09-30 16:39 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: macOS Big Sur 11.6
- VS Code Version: 1.60.2
- C/C++ Extension Version: v1.7.0-insiders
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: Docker, Cmake, Go
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

The workspace is a single-project workspace. Headers and libraries are located in a custom location and cpp_properties.json is configured accordingly. C++11/14/17 auto keyword seems to be not properly deduced based on the real type. That creates problems when autocomplete feature is needed for types like structs and classes with member functions.

**Expected behavior**

The autocompletion feature should automatically deduce type of auto variable and provide correct suggestions.

**Code sample and logs**

- Code sample

```
.message = [](auto *ws, std::string_view message, uWS::OpCode opCode){
       ws->publish("", message);
},
```

- Configurations in `c_cpp_properties.json`

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${default}",
                "~/.conan/data**"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-clang-arm64",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/9071530/135496607-8e4726d2-dd47-4b5f-adb9-7f373dbd5a09.png)

**Additional context**

**Comment by Colengms** [comment] 2021-10-01 22:48
Hi @byzeagle .  An auto arg to a lambda is the equivalent of a template arg.    In the context of the definition of the lambda in your example (where you are trying to use auto-complete), the type `ws` points to is not yet determined.  That would seem to be 'by-design', as it's not possible to deduce the type there.  Let me know if there is something I am missing.  Do you have other examples of this issue in scenarios where it should be possible to deduce the auto type?

**Comment by Colengms** [comment] 2021-11-05 21:54
Closing this issue, as it appears to be by-design.

**Closed as completed by Colengms** 2021-11-05 21:54 UTC
Labels: duplicate, Language Service, more info needed

**Comment by glingy** [comment] 2021-11-21 01:37
I was actually working with this same library and was looking for autocomplete for the auto keyword as well. That clip above is misleading because `auto * ws` is determined at that point by the template arguments of the enclosing call to `.ws(...)`. https://github.com/uNetworking/uWebSockets/blob/e8b870c7bae2d7d97193abd4ed0bd13b86bc50a1/examples/EchoServer.cpp#L35 gives the snippet in context. The compiler is perfectly happy to tell me the type of the `auto * ws` parameter if I purposefully try to call a method on it that doesn't exist and look at the compilation error:

```
main.cpp: In instantiation of ‘init()::<lambda()>::<lambda(auto:31*, std::string_view, uWS::OpCode)> [with auto:31 = uWS::WebSocket<false, true, unsigned int>; std::string_view = std::basic_string_view<char>]’:
/usr/include/c++/10/type_traits:2506:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = init()::<lambda()>::<lambda(auto:31*, std::string_view, uWS::OpCode)>&; _Args = {uWS::WebSocket<false, true, unsigned int>*, std::basic_string_view<char, std::char_traits<char> >, uWS::OpCode}]’
/usr/include/c++/10/type_traits:2517:55:   required from ‘struct std::__result_of_impl<false, false, init()::<lambda()>::<lambda(auto:31*, std::string_view, uWS::OpCode)>&, uWS::WebSocket<false, true, unsigned int>*, std::basic_string_view<char, std::char_traits<char> >, uWS::OpCode>’
/usr/include/c++/10/type_traits:138:12:   recursively required by substitution of ‘template<class _Result, class _Ret> struct std::__is_nt_invocable_impl<_Result, _Ret, std::__void_t<typename _CTp::type> > [with _Result = std::__invoke_result<init()::<lambda()>::<lambda(auto:31*, std::string_view, uWS::OpCode)>&, uWS::WebSocket<false, true, unsigned int>*, std::basic_string_view<char, std::char_traits<char> >, uWS::OpCode>; _Ret = void]’
/usr/include/c++/10/type_traits:138:12:   required from ‘struct std::__and_<std::__is_nt_invocable_impl<std::__invoke_result<init()::<lambda()>::<lambda(auto:31*, std::string_view, uWS::OpCode)>&, uWS::WebSocket<false, true, unsigned int>*, std::basic_string_view<char, std::char_traits<char> >, uWS::OpCode>, void, void>, std::__call_is_nothrow<std::__invoke_result<init()::<lambda()>::<lambda(auto:31*, std::string_view, uWS::OpCode)>&, uWS::WebSocket<false, true, unsigned int>*, std::basic_string_view<char, std::char_traits<char> >, uWS::OpCode>, init()::<lambda()>::<lambda(auto:31*, std::string_view, uWS::OpCode)>&, uWS::WebSocket<false, true, unsigned int>*, std::basic_string_view<char, std::char_traits<char> >, uWS::OpCode> >’
/usr/include/c++/10/type_traits:2999:12:   required from ‘struct std::is_nothrow_invocable_r<void, init()::<lambda()>::<lambda(auto:31*, std::string_view, uWS::OpCode)>&, uWS::WebSocket<false, true, unsigned int>*, std::basic_string_view<char, std::char_traits<char> >, uWS::OpCode>’
/usr/include/c++/10/type_traits:3021:54:   required from ‘constexpr const bool std::is_nothrow_invocable_r_v<void, init()::<lambda()>::<lambda(auto:31*, std::string_view, uWS::OpCode)>&, uWS::WebSocket<false, true, unsigned int>*, std::basic_string_view<char, std::char_traits<char> >, uWS::OpCode>’
/home/gregory/Telem/telem/new/lib/uWebSockets/src/MoveOnlyFunction.h:281:31:   required by substitution of ‘template<class F, class> ofats::any_invocable<void(uWS::WebSocket<false, true, unsigned int>*, std::basic_string_view<char>, uWS::OpCode)>::any_invocable(F&&) [with F = init()::<lambda()>::<lambda(auto:31*, std::string_view, uWS::OpCode)>; <template-parameter-1-2> = <missing>]’
main.cpp:52:7:   required from here
main.cpp:46:15: error: ‘struct uWS::WebSocket<false, true, unsigned int>’ has no member named ‘foo’
   46 |           ws->foo();
   ```
   Specifically, the last error line where it says that `auto * ws` was a `struct uWS::WebSocket<false, true, unsigned int> * ws`. If the compiler knows what it is, I'd expect autocomplete to be able to figure it out as well. I'm finding myself often changing `auto *` to that `struct uWS::WebSocket<false, true, unsigned int> *` to get autocomplete to work.

**Comment by glingy** [comment] 2021-11-21 01:41
Using that library above, https://github.com/uNetworking/uWebSockets, here's a simplified example which should have autocomplete, but does not:
```
#include <App.h>

int main() {
  // res is a uWS::HttpResponse<false> and req is a uWS::HttpRequest, but no autocopmlete for either.
  uWS::App().get("/", [](auto * res, auto * req) {
    res->send("OK");
  });
}
```

**Comment by sean-mcmanus** [comment] 2021-11-22 21:23
I believe this issue is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/5039 .
