### ISSUE TITLE
Declare before use problems not detected in C++

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-cpptools#4901] opened 2020-01-27 14:32 UTC
**Type: LanguageService**

**Describe the bug**
Version: 1.42.0-insider (system setup)
Commit: f3dbcea32a6b52ce819dc863e778fb8517357f61
Date: 2020-01-24T05:38:14.538Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
C/C++ Extension Version: 0.26.3

If I have a declare before use error, there are no errors shown. 
Expected, where I've deleted `doSomeCounting`
![image](https://user-images.githubusercontent.com/38270282/73182761-eb8b8a80-4119-11ea-9511-de543340e50b.png)
But if I include `doSomeCounting` below `main`, there is no error:
![image](https://user-images.githubusercontent.com/38270282/73182832-0d850d00-411a-11ea-9272-e3634fb85796.png)

Sample code:
```c++
#include <iostream>

int main()
{
    std::cout << "Hello, Remote World!"
              << "\n";
    doSomeCounting(3);
    return 0;
}

int doSomeCounting(int startAt)
{
    for (int i = startAt; i < 10; i++)
    {
        std::cout << i
                  << "\n";
    }
}
```

Since this is a compile error and it is detected when `doSomeCounting` is entirely missing, I expected it to be detected when it is declared too late.

**Comment by Colengms** [comment] 2020-01-27 18:56
Hi @alexr00 .  Thanks for letting us know.  This also repro's in VS, so I've opened a bug there also.  https://developercommunity.visualstudio.com/content/problem/897827/c-intellisense-does-not-detect-issue-with-use-befo.html

**Comment by bobbrow** [comment] 2024-09-20 22:51
This issue still repros, but the Developer Community link is no longer valid and it would have been closed as "lower priority" by now anyway.

I actually just had a discussion about this quirk with another developer. The issue is known and has to do with how the IntelliSense compiler first collects an outline of the classes/functions in the translation unit and only parses function bodies after that. It does not currently keep track of that fact that the declaration of `doSomeCounting` (which it knows about because of the outline) is below the function body where it is used.  I'll kick off another conversation with the IntelliSense team about it, but I'm closing this in the meantime.

**Closed as not planned by bobbrow** 2024-09-20 22:51 UTC
Labels: bug, Language Service, Visual Studio
