### ISSUE TITLE
Formatter uses Tabs for alignment

### ISSUE THREAD

**Issue by nkdmSum** [microsoft/vscode-cpptools#6127] opened 2020-09-13 12:27 UTC
(I'm using tabs for indentation)

Tabs should be used for indentation, but never for alignment!
Sadly, that's what the formatter does.

1: Enter the following code:
```
#include <iostream>

void main()
{
	std::cout << "Hello, " << "world!";
}
```
2: Press SHIFT+OPTION+F (or whatever shortcut you have for formatting).
3: You get the following code:
```
#include <iostream>

void main()
{
	std::cout << "Hello, "
			  << "world!";
}
```
Github (at least for me) uses 8 spaces for a tab, but I had set 4 spaces in vscode, so it formatted it accordingly.
As you can see, this results in the `<<`s not being aligned properly.
The formatter should use spaces for alignment:
```
#include <iostream>

void main()
{
	std::cout << "Hello, "
	          << "world!";
}
```
And, other than the question whether you should use tabs vs spaces for indentation, everyone can agree that using tabs for alignment is a bad idea.

If there is a setting to set alignment to spaces, please tell me so(although such a setting shouldn't exist in the first place).

Formatted with tabs=4 : 
<img width="313" alt="Снимок экрана 2020-09-13 в 14 21 45" src="https://user-images.githubusercontent.com/51021475/93018008-266d0080-f5cd-11ea-85c4-33f80470c426.png">
Looked at with tabs=2 : 
<img width="295" alt="Снимок экрана 2020-09-13 в 14 23 09" src="https://user-images.githubusercontent.com/51021475/93018010-3258c280-f5cd-11ea-9504-3207b15202fc.png">

**Comment by sean-mcmanus** [comment] 2020-09-14 21:10
I'm not reproing this. Can you provide your VS Code format related settings? Such as editor.tabSize, detectIndentation, insertSpaces, and C_Cpp.formatting? Also, is there a .clang-format file in your folder hierarchy?

**Comment by michelleangela** [comment] 2020-12-09 18:35
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 18:35 UTC
Labels: Language Service, more info needed, not reproing, Feature: Code Formatting
