### ISSUE TITLE
Intellisense and tags doesnt work in Windows 7

### ISSUE THREAD

**Issue by rajesh-gali** [microsoft/vscode-cpptools#10] opened 2016-04-16 00:39 UTC
Hi, 
I have installed cpptools but Intellisense and symbols view is not working at all. Search for symbols command always displays "No Symbols Matching " message. I was wondering are there any dependencies to make it work for Windows? 

Thank you,
Regards,
Raj

**Comment by sridmad** [comment] 2016-04-16 19:00
Dupe of issue #9

**Closed as completed by sridmad** 2016-04-16 19:00 UTC
Labels: bug, duplicate
