### ISSUE TITLE
std::optional - qualified name is not allowed - GCC 7.2.1

### ISSUE THREAD

**Issue by agauniyal** [microsoft/vscode-cpptools#1350] opened 2017-12-15 02:48 UTC
```
#include <optional>

std::optional<int> func() { return 5; } 
// ^ error here

int main() {
  
}
```

**Comment by sean-mcmanus** [comment] 2017-12-15 04:35
What OS? What library are you using for optional (i.e. the path)? What's the error? It works for me on Linux with /usr/include/c++/6/experimental and on Windows with MSVC 14.13.26009. My best guess is that your library doesn't include optional as part of the std namespace, since it's a new C++17 feature (i.e. trying std::experimental or std::tr1 might work for you).

**Comment by agauniyal** [comment] 2017-12-15 05:03
@sean-mcmanus arch linux. `#include <optional>`. Code compiles with `clan/ g++ -std=c++17 ...`.
```
g++ --version
g++ (GCC) 7.2.1 20171128
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

I've not added any path, just installed extension and reopened vscode.

**Comment by sean-mcmanus** [comment] 2017-12-15 05:16
What is the error you are seeeing? std::optional works for me using clang 5.0 headers (under c++/v1). You can try doing an Edit Configuration to generate the default includePath options that are being used. We try to query clang or gcc for defaults, but maybe we messed up. You can also try opening the header file (assuming it can be found via the browse.path setting), and see if there are any define's that are expected in the header.

**Comment by agauniyal** [comment] 2017-12-15 06:17
Error is the same as issue name. I generated Edit Configuration -
```
{
            "name": "Linux",
            "includePath": [
                "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../include/c++/7.2.1",
                "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../include/c++/7.2.1/x86_64-pc-linux-gnu",
                "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../include/c++/7.2.1/backward",
                "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/include",
                "/usr/local/include",
                "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/include-fixed",
                "/usr/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../include/c++/7.2.1",
                    "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../include/c++/7.2.1/x86_64-pc-linux-gnu",
                    "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../include/c++/7.2.1/backward",
                    "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/include",
                    "/usr/local/include",
                    "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/include-fixed",
                    "/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
```

These path seems like - `/usr/include/c++/7.2.1/` where there is a `optional` file along with all other c++ headers.

```
$ cd /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../include/c++/7.2.1
$ ls

algorithm           cstdalign     initializer_list  set
any                 cstdarg       iomanip           shared_mutex
....
....

climits             deque         optional          typeinfo
clocale             exception     ostream           type_traits
```

**Comment by agauniyal** [comment] 2017-12-15 06:24
![rsz_2017-12-15-115509_1366x768_scrot](https://user-images.githubusercontent.com/7630575/34029438-a5dc0272-e18e-11e7-9c3f-d6d010bc4719.png)

**Comment by agauniyal** [comment] 2017-12-15 10:07
I think c++17 constructs are not being recognized by cpptools plugin. I was using `string_view` and it again gave error `identifier string_view is undefined`.

**Comment by sean-mcmanus** [comment] 2017-12-15 12:02
Yeah, our IntelliSense parser is not 100% C++17 complaint yet. I believe this will be improved in the January update (or February if there's a delay), but I haven't checked to what extent. But the error with std::optional appears to only repro with the 7.2 gcc stdc++ libraries (something in that header is breaking our parser).

**Comment by adtennant** [comment] 2018-03-04 21:23
This is also occurring with the 7.3 gcc stdc++ libraries on OSX.

**Comment by tristan957** [comment] 2018-03-13 01:05
I hope this is not seen as only a +1 comment. I just want to also confirm that this is also a problem on Solus. The goto definition works, but squiggles still appear. Excited for the upcoming update nonetheless

**Comment by tristan957** [comment] 2018-03-13 01:07
I can confirm this is fixed in the v16 preview. Thanks devs. Should this issue be closed?

**Comment by sean-mcmanus** [comment] 2018-03-13 01:15
@tristan957 Thanks for letting us know the insider build fixed the issue for you.

@agauniyal @adtennant Let us know if you guys are still having problems with https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders (or our final release which is expected in a week or so). You may need to set your compilerPath setting if we don't guess it correctly.

**Closed as completed** 2018-04-02 23:19 UTC
Labels: bug, Language Service, fixed, parser
