### ISSUE TITLE
Header capital not found

### ISSUE THREAD

**Issue by dngo10** [microsoft/vscode-cpptools#3744] opened 2019-06-08 07:19 UTC
Hi, the problem is cpp tools seems to find the folder, but it only shows headers with lower ".h" extension, but with not capital ".H"

Not sure how to fix.

![Screenshot from 2019-06-08 00-12-39](https://user-images.githubusercontent.com/34533770/59143761-ff179480-8982-11e9-8ee7-2ba3e929473c.png)

![Folder](https://user-images.githubusercontent.com/34533770/59143764-0474df00-8983-11e9-876f-28b902bc1cb2.png)

Please help. Thanks.

**Comment by sean-mcmanus** [comment] 2019-06-10 19:08
It's a bug (doesn't repro on Windows). I'm surprised it took so long for anyone to report this.

https://github.com/microsoft/vscode-cpptools/issues/3048 probably has the same root cause.

UPDATE: #3048 isn't fixed (different root cause).

**Comment by sean-mcmanus** [comment] 2019-08-22 01:13
Fixed with 0.25.0. The switch header/source case will be fixed in our next Insider release (https://github.com/microsoft/vscode-cpptools/issues/3048).

**Closed as completed by sean-mcmanus** 2019-08-22 01:13 UTC
Labels: bug, Language Service, fixed, quick fix, verified, Feature: Auto-complete
