### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by noizfactory** [microsoft/vscode-cpptools#3507] opened 2019-04-23 03:35 UTC
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.1`
- OS Version: `Linux x64 3.10.0-862.14.4.el7.x86_64`
[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/3105660/ms-vscode.cpptools-unresponsive.cpuprofile.txt)

- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/sshrestha/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bobbrow** [comment] 2019-04-23 15:07
Thank you for the feedback.  This looks like a duplicate of #3213

**Closed as completed by bobbrow** 2019-04-23 15:07 UTC
Labels: duplicate, Language Service
