### ISSUE TITLE
Please help me how to run c programm in visual studio 

### ISSUE THREAD

**Issue by reddi2** [microsoft/vscode-cpptools#6543] opened 2020-11-18 10:56 UTC
Issue Type: <b>Bug</b>

GCC and G++ commands are not working here in  windows 
please do help me 
how to run c program in vs

Extension version: 1.1.2
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by eathtespagheti** [comment] 2020-11-18 16:23
Duplicate of #6542, please close this

**Comment by WardenGnaw** [comment] 2020-11-18 18:19
If the difference between this question and #6542 is how to use C/C++ in Visual Studio, then this is not the correct place for this question. This GitHub repo is for VS Code's C/C++ extension. 

However, you can use this reference for Visual Studio: https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-in-visual-studio?view=msvc-160

**Closed as completed by WardenGnaw** 2020-11-18 18:19 UTC
