### ISSUE TITLE
Support for Darwin arm64 (Apple Silicon) in VS Code - Insiders

### ISSUE THREAD

**Issue by EmperorYP7** [microsoft/vscode-cpptools#6839] opened 2021-01-23 16:22 UTC
Type: General

With reference to #6595, this is a feature request for adding support for Darwin arm64 specifically for **VS Code - Insiders edition**.

**Screenshots**

<img width="447" alt="Screenshot 2021-01-23 at 9 33 54 PM" src="https://user-images.githubusercontent.com/62606998/105607091-e6135f80-5dc2-11eb-9752-3fce19efeece.png">

**Software versions**
- OS and Version: Darwin arm64 20.2.0 (macOS Big Sur 11.1)
- VS Code Version: 1.53.0-insider
- C/C++ Extension Version: v1.1.3

**Comment by sean-mcmanus** [comment] 2021-01-26 00:20
This is already fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2 . That page has instructions on how to get it.

This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6713 .

We're tracking native (and debugger) support at https://github.com/microsoft/vscode-cpptools/issues/6595.

**Closed as completed by sean-mcmanus** 2021-01-26 00:20 UTC
Labels: duplicate, fixed
