### ISSUE TITLE
Configuration provider Insiders regression -- includes not found

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5906] opened 2020-08-05 19:08 UTC
This issue seems to have re-surfaced with the new version update v0.30.0-insiders. Things are working perfectly with v0.29.0. Please assit this. I have tested it with previous versions to claim this. (I am using VSC on a Ubuntu Server via SSH connect.

With latest version
![image](https://user-images.githubusercontent.com/43124192/89375235-9c5d8c80-d730-11ea-8bbb-da7e549e6fd7.png)

With older version:
![image](https://user-images.githubusercontent.com/43124192/89375633-65d44180-d731-11ea-8b1f-b858a1c3dcc6.png)

_Originally posted by @srijanc in https://github.com/microsoft/vscode-cpptools/issues/2630#issuecomment-668988956_

**Comment by sean-mcmanus** [comment] 2020-08-05 19:11
You're using the CMake Tools configuration provider, right? Can you provide info from C/C++: Log Diagnostics?

@Colengms Could this be related to your recent configuration provider changes?

**Comment by srijanc** [comment] 2020-08-06 02:28
Yes, I am using the CMake Tool configuration provider.
I am not very sure what exactly you mean by saying "C/C++: Log Diagnostics"?
I am attaching 2 logs, one is extension log and another is debug log for C/C++.
Please let me know how to extract that specific log (the one you have requested).
[C_C++_Debug.log](https://github.com/microsoft/vscode-cpptools/files/5032192/C_C%2B%2B_Debug.log)
[exthost.log](https://github.com/microsoft/vscode-cpptools/files/5032193/exthost.log)

**Comment by sean-mcmanus** [comment] 2020-08-06 18:29
View->Command Palette->C/C++ Log Diagnostics.
![image](https://user-images.githubusercontent.com/19859882/89568222-d5047100-d7d7-11ea-9e30-caecfb3df549.png)
And view the output window:
![image](https://user-images.githubusercontent.com/19859882/89568289-f1a0a900-d7d7-11ea-8cbc-b40b1f84266c.png)

**Comment by srijanc** [comment] 2020-08-06 23:38
As requested.....here is it. I have added both for v29 and v30.
[C_C++_LogDiagnostic_V29.log](https://github.com/microsoft/vscode-cpptools/files/5038550/C_C%2B%2B_LogDiagnostic_V29.log)
[C_C++_LogDiagnostic_v30.log](https://github.com/microsoft/vscode-cpptools/files/5038551/C_C%2B%2B_LogDiagnostic_v30.log)

**Comment by Colengms** [comment] 2020-08-07 00:41
Hi @srijanc .  Could you enable debugging logging, using the following setting?  `"C_Cpp.loggingLevel": "Debug"`

That should result in more verbose output to the C/C++ output channel, including the information we receive from the custom config provider, and possibly other clues.

Note that when using the `configurationProvider` field in `c_cpp_properties.json`, it overrides all other fields of that configuration.  I suspect you are seeing the result of a 'fix' in which we stopped falling back to the other values in that configuration when unable to receive a custom configuration from the provider.  In that scenario, it should now be properly falling back to a default set of compiler information also specified by the config provider.  Since you are using CMake Tools, could you try issuing a `CMake: Delete Cache and Reconfigure` command?  Or, perhaps the issue is that CMake Tools is not installed or is disabled, preventing us from receiving any information from it at all?  If this is the issue, we could consider restoring the original behavior.  Though, the new behavior seems to better surface that the configuration is not occuring as expected.  Perhaps we should issue a warning when unable to get any information from a config provider, before falling back to other fields in the configuration.

**Comment by srijanc** [comment] 2020-08-07 01:44
@Colengms I followed all the steps as suggest by you.
To summarise:
1. The logs I provided earlier were at the Debug level. `"C_Cpp.loggingLevel": "Debug"` is already set in my `settings.json` when I provided the logs previously.
2. I understand about `configurationProvider` and did a `CMake: Delete Cache and Reconfigure` but the issue remains the same.
3. As per my knowledge, CMake tool is correctly installed and work fine, because I have build another CPP projects using the same and there was no issue.
4. I am not very sure if I explained myself very clear, that this issue is only with the new plugin update for C++ intellisense that came in probably 2-3 days before. My project is working all good with v0.29.
5. I also did try to set `"cmake.configureOnOpen": false` in `settings.json` file and the issue remains the same even after reloading the window.

**Comment by Colengms** [comment] 2020-08-07 02:37
Hi @srijanc .  The output you provided from the C/C++ output channel looks to be incomplete.  It contains 22 lines, and we should be seeing several hundred.  It doesn't capture a file being processed by the extension, for which we should see a `textDocument/didOpen` message (even if already open on launch).  I don't see an initial browse path received from the configuration provider when registered (which should happen even with `"cmake.configureOnOpen": false`).  I don't see probing of a detected default compiler.  Something seems amiss.

Could you try generating that output again, from launch up until it logs `cpptools/finishUpdateSquiggles`, indicating it has completed an initial IntelliSense pass?

Also, could you also provide the contents of your `c_cpp_properties.json` file, and any `C_Cpp` settings?  Hopefully, that should give us all the clues we need.

I can repro a similar issue to what you describe if I try to use a workspace in which a custom configuration provider is specified, but which we have never received anything from.  To confirm that is not the scenario you are seeing, I'd like to see if the C/C++ output channel shows receipt of a custom configuration.  For that, I'm looking for the following in the log: `Custom browse configuration received` and `Custom configurations received`.

**Comment by srijanc** [comment] 2020-08-07 03:56
Ok, I understand. The browse path is displayed empty in the debug. I have attached all the logs along with cpp_properties file.

[c_cpp_properties.txt](https://github.com/microsoft/vscode-cpptools/files/5039228/c_cpp_properties.txt)
[C_C++_LogDiagnostic_v30.log](https://github.com/microsoft/vscode-cpptools/files/5039230/C_C%2B%2B_LogDiagnostic_v30.log)
[C_C++_LogDiagnostic_V29.log](https://github.com/microsoft/vscode-cpptools/files/5039231/C_C%2B%2B_LogDiagnostic_V29.log)

**Comment by Colengms** [comment] 2020-08-07 18:52
Hi @srijanc .  Indeed, something seems to be wrong with the custom configuration provider (CMake Tools).  As you noted, your log contains a `Custom browse configuration received` section, but it's empty.  Normally, it should contain browse paths, a standard version, a compiler path, compiler args, etc..  And, there is no file-specific custom configuration received for the file you opened, which should be in a `Custom configurations received` section.  This problem was also present for you in 0.29.0, but was masked by the fact that we were falling back to the other fields present in c_cpp_properties.json.  We could restore the behavior to fall back to those values, but the real issue here is that you are not getting the configuration you should be (and are probably expecting) from CMake Tools.  Can you confirm that you are using the latest version of CMake Tools, and that there are no errors reported when you use `CMake: Delete Cache and Reconfigure`, or other errors logged to the CMake Tools output channel?  There could perhaps be an issue with CMake on the target machine, perhaps an old version?  Also, do you have any `C_Cpp.default.*` settings set in `settings.json` that could be relevant?

**Comment by srijanc** [comment] 2020-08-09 05:23
I couldn't find any such issues. I have attached a screenshot of the version of the cmake along with a log file in which I have attached the output of the `CMake: Delete Cache and Reconfigure` and the content of my `settings.json`. There is no `C_Cpp.default*` in my `settings.json` file.

![image](https://user-images.githubusercontent.com/43124192/89725562-3173c480-da54-11ea-9a36-c945282bb1db.png)
[requested_details.log](https://github.com/microsoft/vscode-cpptools/files/5046784/requested_details.log)

**Comment by srijanc** [comment] 2020-08-10 03:16
To clarify my doubts I created a new C++ project with default settings which are instructed by MS in this [link](https://code.visualstudio.com/docs/cpp/config-linux).
The errors remains same.

Note: I am not using cmake here. It is just a simple helloworld code.

**Comment by Colengms** [comment] 2020-08-10 22:01
Hi @srijanc .  Regarding your original repro: The fact that the log contained an empty custom browse path and did not contain any receipt of a custom configuration, clearly indicates that the C/C++ extension was not being configured by the config provider.  This would explain why no includes were listed in the `Log Diagnostics` output in that scenario, and why things started failing in v0.30.0, as we no longer fall back to the base configuration when there is no configuration available from the custom config provider.  This is something we can drill into further.  When you issue a `CMake: Delete Cache and Reconfigure` command, is there corresponding output in the C/C++ output channel indicating that we received a custom configuration?  (i.e. `Custom configurations received`?)  If not, I'd like to try to figure out why.  We may need to open an issue in the CMake Tools repo for this.

Regarding your new repro: Many users are able to configure simple hello world projects.  To understand why this is not working for you, we need to understand what is different about your environment.

You mentioned, "The errors remains same.".  The error you previously reported appears to be: `#include errors detected based on information provided by the configurationProvider setting.`.  Is that right?  If you're not using a custom config provider in your new repro, the error should be different.  Can you clarify what error you are now seeing?  Does it indicate a specific #include file that cannot be found?

Since you have a new repro, could you provide updated copies of the following.  I believe this is everything relevant:

* Contents of the project's `c_cpp_properties.json`
* Output of the `C/C++: Log Diagnostics` command, after the file that repro's the issue is opened and the initial intellisense pass has completed.  (If the log output mentions "not ready", an intelliSense pass has not completed)
* With debug logging enabled (`"C_Cpp.loggingLevel": "Debug"`), the output of the `C/C++` output channel, from launch up until output has settled after repro'ing the issue.
* The contents of the `settings.json` file in the `.vscode` folder of the project, as well as the global `settings.json` which can be opened using `Preferences: Open Settings (JSON)`.  (I'm looking only for settings that start with `C_Cpp`, which refer to the C/C++ Extension).

**Comment by srijanc** [comment] 2020-08-13 01:07
Hi @Colengms , my response accordingly:

1. On initiating the command `CMake: Delete Cache and Reconfigure` below is the screenshot of the first few lines, where I don't receive any `custom configuration`.
![image](https://user-images.githubusercontent.com/43124192/90081935-e3abd480-dd51-11ea-9479-71906f71a549.png)

2. About the errors received on the newly created project, I couldn't re-create it as the plug-in has automatically updated to version `v0.30.0-insiders2` and now I am not getting any include errors.

3. Below are the requested files from the newly created project:

- [c_cpp_properties.txt](https://github.com/microsoft/vscode-cpptools/files/5066582/c_cpp_properties.txt)

- [C_C++_LogDiagnostic.txt](https://github.com/microsoft/vscode-cpptools/files/5066603/C_C%2B%2B_LogDiagnostic.txt)

- [CPP_DebugLoggingStart.txt](https://github.com/microsoft/vscode-cpptools/files/5066615/CPP_DebugLoggingStart.txt)

- [Setting_JSON_vscode.txt](https://github.com/microsoft/vscode-cpptools/files/5066624/Setting_JSON_vscode.txt)

- [Preferences_OpenSetting.txt](https://github.com/microsoft/vscode-cpptools/files/5066627/Preferences_OpenSetting.txt)

**Comment by Colengms** [comment] 2020-08-13 20:42
Hi @srijanc .

In v0.30.0-insiders2, we restored the original behavior of falling back to the base configuration if not able to receive one from the custom configuration provider.  You may still have an issue with not receiving a custom configuration from the provider.

It should be possible to make that problem more obvious by removing the base configuration, and using a configuration containing only:

```
        {
            "name": "Linux",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
```

When using a custom configuration provider, those should be the only fields necessary.

If you are still seeing a failure to receive a custom configuration, I have some suggestions:

* Could you create a github repo, or zip a folder containing a project that we might use to reproduce the problem ourselves?  So far, I'm not able to repro the issues you are describing, and that would help us to investigate.

* Make sure you are using the latest version of CMake Tools (1.4.1).

* Try updating CMake to a more recent version.  I believe the latest is 3.18.  There were some significant API changes starting in 3.15.

* Could you open an issue against [CMake Tools](https://github.com/microsoft/vscode-cmake-tools) to investigate the apparent failure to deliver a custom configuration?

> About the errors received on the newly created project, I couldn't re-create it as the plug-in has automatically updated to version v0.30.0-insiders2 and now I am not getting any include errors.

If your hello world project did not use CMake Tools, then I don't believe the behavior should have changed with 0.30.insiders2 .  But, if you're no longer seeing any issues with that project, that is good news.  Perhaps you were seeing another issue we've since addressed.

**Comment by srijanc** [comment] 2020-08-14 04:32
Hi @Colengms I did create a fresh [repository](https://github.com/srijanc/VSC_Test) and made 3 commits for each stage. Details are mentioned in the Readme file.

It is strange and surprising that I couldn't re-create the error that I was getting previously.

VSC - CMake Tools (1.4.1)
CMake (3.10.2)

I have raised a new issue against CMake Tools [here](https://github.com/microsoft/vscode-cmake-tools/issues/1409).

**Comment by Colengms** [comment] 2020-08-14 20:41
Hi @srijanc .  The [repository](https://github.com/srijanc/VSC_Test) you linked does not include a `CMakeLists.txt`.  One is necessary to configure CMake, and CMake needs to be configured in order for CMake Tools to provide configurations based on it.  Was this file accidentally omitted?   If a `CMakeLists.txt` is not present, that would explain the issue in which you do not receive a configuration from CMake Tools.

**Comment by srijanc** [comment] 2020-08-18 06:40
Oh....I see. I cross verified and found that the CMakeLists.txt file was accidently removed. This happened to my main project too. I will re-create the same and see if I am still facing similar issue. Thanks heaps for pointing it out.

**Comment by Colengms** [comment] 2020-08-18 18:45
Hi @srijanc .  Assuming that is the issue, I'm going to close this.  If you are still seeing a problem, we can re-open this.

**Closed as completed by Colengms** 2020-08-18 18:45 UTC
Labels: Language Service, more info needed, not reproing, regression, Feature: Configuration

**Comment by srijanc** [comment] 2020-08-27 04:42
Hi @Colengms The issue has now been resolved and it seems to be an issue with the CMake version as you suggested previously. I updated the CMake to the latest version 3.18.2 and now the config is picking up all the details and working as expected. Thanks for all your support.
