### ISSUE TITLE
Condition breakpoint for string

### ISSUE THREAD

**Issue by alekseibutiaev** [microsoft/vscode-cpptools#8684] opened 2022-01-18 14:27 UTC
Bug type: Debugger

C/C++ v1.8.0-insiders2

Can not set condition break point for string 

v.compare("test") == 0 
void bp_string(const std::string& v) {
  std::cout << v << std::endl;
  return;
}
![Untitled](https://user-images.githubusercontent.com/28618106/149955058-d1de645d-b823-4f3d-8b48-6edc5b854826.png)
![Untitled1](https://user-images.githubusercontent.com/28618106/149955067-0f68f888-a878-4929-aa9f-5637e6aa04c4.png)
in gdb is working
![Untitled2](https://user-images.githubusercontent.com/28618106/149956089-68410e35-e463-4c0c-bbc6-d1db4f975b39.png)

**Comment by WardenGnaw** [comment] 2022-01-18 18:00
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/8515

**Closed as completed by WardenGnaw** 2022-01-18 18:00 UTC
