### ISSUE TITLE
Working with MSVC include files is problematic in Linux 

### ISSUE THREAD

**Issue by OnikenX** [microsoft/vscode-cpptools#5366] opened 2020-04-27 03:28 UTC
Issue Type: <b>Bug</b>

I'm trying to make a win32 program in linux with wine, there is no problem compiling and running the programs that i create, being that i only use the terminal. The problem comes when i try to use a code editor.

I'm trying to use C/C++ extension from microsoft but even including the source files from my vm it doesn't work well with them.

To recreate make a cpp file, include mscv and win32 header files and it will have problem finding those files.

In windows it finds the files without problem but in linux even giving it the header files there are problems.

This is my c/c++ config: 
https://github.com/OnikenX/MSVC-in-Linux/blob/master/c_cpp_properties.json

Extension version: 0.27.0
VS Code version: Code - OSS 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-23T19:32:05.786Z)
OS version: Linux x64 5.6.6-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1775)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|7.69GB (0.16GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment] 2020-04-27 20:34
I don't think targeting Windows from Linux is currently support with IntelliSense (except via using one of the remote extensions). We have another issue tracking targeting Linux from Mac at https://github.com/microsoft/vscode-cpptools/issues/1083, so the root issue may be the same.

**Comment by bobbrow** [comment] 2020-05-14 21:29
Closing as duplicate of #1083

**Closed as completed** 2020-05-14 21:38 UTC
Labels: duplicate, Language Service, Feature Request, Feature: Configuration
