### ISSUE TITLE
The non-standard interface identifier breaks intellisense

### ISSUE THREAD

**Issue by graphitemaster** [microsoft/vscode-cpptools#3771] opened 2019-06-14 08:04 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux x64 5.1.3-arch1-1-ARCH
- VS Code Version:
Version: 1.35.0
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-05T22:12:50.056Z
Electron: 4.1.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.30-electron.0
OS: Linux x64 5.1.3-arch1-1-ARCH
- C/C++ Extension Version: 0.23.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
Naming anything in C/C++ with `interface` triggers Microsoft specific COM interface extensions and results in `__interface <namespace>::__unnamed_interface_<hash>` names everywhere in the symbol list and breaks goto definition.

As a simple example
```cpp
namespace foo {
  struct interface {
    void bar(); // implemented in some other file.cpp
  };
}
```

Will produce a symbol name of `__interface foo::__unnamed_interface_c0f4_1` and using **F12** (goto definition) on `foo::interface::bar` will not go to the relevant function in `file.cpp`

**Expected behavior**
These are specific extensions that don't pertain to standard C nor C++ and should not pollute the global namespace unless one includes something like `<windows.h>`. Or alternatively a way to disable them would work too. The `interface` identifier should be usable.

**Things tried to work around the issue**
Tried using a `cpp.hint` to `#undef` and also `#define` `interface` with no real luck.
Tried several other versions and looking for documentation on how to disable Microsoft extensions, couldn't find anything that worked.

**Comment by sean-mcmanus** [comment] 2019-06-14 20:49
I believe it's caused by our "tag parser" being run with Microsoft C++/CLI and C++/CX mode enabled. It doesn't affect the IntelliSense results if IntelliSense is used for things like hover, but it does affect the symbols/outline view. VS has the same bug so I filed it at: https://developercommunity.visualstudio.com/content/problem/608651/cc-intellisense-struct-interface-is-incorrectly-pa.html . You could upvote that if you have a Microsoft account.

**Comment by sean-mcmanus** [comment] 2019-06-21 01:22
VS closed it as "low priority" so either this issue or that one needs more upvogtes. I thought it was be a simple fix, but it looks like it is not.

**Comment by graphitemaster** [comment] 2019-06-24 11:43
That's a shame. I have tons of classes named `interface` (38 of them to be exact) where they only differ by namespace and not having working intellisense, goto definition, etc is really dishearting. I can't think of a better name for them either to work around it without violating consistency in coding style anyways.

**Comment by sean-mcmanus** [comment] 2019-06-24 20:54
Maybe you could use "abstract" or "abstract_class" or "abstract_interface" instead, since "abstract" doesn't have this problem. In standard C++, "interfaces" are implemented using "abstract classes" anyway.

**Comment by graphitemaster** [comment] 2019-06-27 18:14
They're not interfaces in that way. They're not virtual and inherit + implement them. They're just static interfaces to components of a larger system. Almost singletons.

**Comment by bobbrow** [comment] 2024-11-27 18:49
The linked Visual Studio bug was closed as lower priority. Unfortunately, this means that we won't be getting a fix for VS Code either. We should have closed this issue earlier.

**Closed as not planned by bobbrow** 2024-11-27 18:49 UTC
Labels: bug, Language Service, Visual Studio, more votes needed
