### ISSUE TITLE
Outline for c/cpp files: "No symbols found"

### ISSUE THREAD

**Issue by liyanshao2** [microsoft/vscode-cpptools#3908] opened 2019-07-10 06:16 UTC
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Windows 10 Enterprise/Windows_NT x64 10.0.16299
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

The bug reported in #2477 and fixed in release 0.19.0 seems appear again.
microsoft/vscode-cpptools#2477

There are no such problems while opening the python or yml/json files.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

1. File->Open Folder to load a project folder
2. open a c/cc file, in the outline it says "No symbols found in document"
3. when I begin to edit the file, the symbol start to show up in the outline view.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment] 2019-07-10 19:14
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/3877 .

We plan to fix this with 0.24.1-insiders next week. Reverting back to 0.23.1 is another option.

**Closed as completed by sean-mcmanus** 2019-07-10 19:14 UTC
Labels: duplicate

**Comment by liyanshao2** [comment] 2019-07-13 15:04
Thanks.

**Comment by sean-mcmanus** [comment] 2019-07-22 19:43
This should be fixed now with 0.24.1.
