### ISSUE TITLE
Error with std::move with Clang + libc++

### ISSUE THREAD

**Issue by quyykk** [microsoft/vscode-cpptools#11463] opened 2023-09-24 14:51 UTC
### Environment

- Arch Linux (up-to-date)
- VSCode 1.82.2
- C/C++ v1.17.5
- Clang 16

### Bug Summary and Steps to Reproduce

IntelliSense produces an invalid error for the following code which clang compiles without problems:

```c++
#include <memory>

int main()
{
    std::shared_ptr<int> a;
    auto b = std::move(a); // <-- error here
}
```

Error:

```
template instantiation resulted in unexpected function type of "std::__1::shared_ptr<int> &&(std::__1::shared_ptr<int> &__t) noexcept" (the meaning of a name may have changed since the template declaration -- the type of the template is "std::__1::__libcpp_remove_reference_t<_Tp> &&(_Tp &&__t) noexcept")C/C++(871)
test.cpp(6, 26): detected during instantiation of "std::__1::move" based on template argument <std::__1::shared_ptr<int> &> at line 6
```

Steps to reproduce:
1. Set the extension to use clang++ and `-stdlib=libc++`
2. Add a file with the source above
3. Wait

Expected behavior:

No error should be produced, this is perfectly valid code.

### Configuration and Logs

```shell
{
    "C_Cpp.default.compilerArgs": [
        "-stdlib=libc++"
    ],
    "C_Cpp.default.compilerPath": "/usr/bin/clang++"
}
```

**Comment by Colengms** [comment] 2023-09-25 20:24
Hi @quyykk .  I'm not easily able to reproduce this issue with clang-16 on Ubuntu.  I set up an Arch Linux instance in WSL, and did not see any issue without the `-stdlib=libc++` arg present (which should actually be unnecessary for IntelliSense to be configured correctly).  However, with that arg, I'm seeing an issue with the result of our command line to query the compiler:

```
/usr/bin/clang++ -std=c++17 -m64 -Wp,-v -fno-blocks -E -dM -x c++ -stdlib=libc++ /dev/null
```

Results in:
```
clang -cc1 version 16.0.6 based upon LLVM 16.0.6 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../x86_64-pc-linux-gnu/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/clang/16/include
 /usr/local/include
 /usr/include
...
```

I assume this is simply due to the right header package not being present on my system.  It may be related to this thread: https://www.reddit.com/r/archlinux/comments/113fbnk/clang_llvm_picks_wrong_gcc_installation_folder/

If you can tell me more about how exactly you've installed clang 16, header packages, etc., on your Arch Linux system, I'd be happy to try to investigate further.

**Comment by quyykk** [comment] 2023-09-25 20:34
Hey,

> (which should actually be unnecessary for IntelliSense to be configured correctly)

In my project the extension uses this flag because it is in my compile_commands.json.

>If you can tell me more about how exactly you've installed clang 16, header packages, etc., on your Arch Linux system, I'd be happy to try to investigate further.

Did you install the libc++ and libc++abi package? In Arch it is packaged separately.

**Comment by Colengms** [comment] 2023-09-26 01:00
Hi @quyykk .  Thanks for reporting this.  I was able to get those headers installed and reproduce the issue.  It does appear to be an IntelliSense bug, related to parsing that particular implementation of `std::move`.  I've isolated the repro, and it also repro's in VS, which shares the same core IntelliSense implementation.  I've opened a bug internally against VS.  (1891914)

Self contained repro:
```
static_assert(__has_builtin(__remove_reference_t));

// Repros slightly differently if this definition is in a header file.
template <class _Tp>
[[nodiscard]] inline __attribute__((__visibility__("hidden"))) __attribute__((__always_inline__)) __attribute__((__abi_tag__("v160006")))
 constexpr __remove_reference_t(_Tp)&&
mytest( _Tp&& __t) noexcept {
  typedef __remove_reference_t(_Tp) _Up;
  return static_cast<_Up&&>(__t);
}

class A { };

int main()
{
    A a;
    auto c = mytest(a); // <-- error here
}
```

**Comment by sean-mcmanus** [comment] 2023-11-14 00:10
@lazan @quyykk This should (may?) be fixed with 1.18.2/1.18.3 (the reduced bug was fixed, but it's possible there could be another issue)

**Comment by lazan** [comment] 2023-11-14 08:55
> @lazan @quyykk This should (may?) be fixed with 1.18.2/1.18.3 (the reduced bug was fixed, but it's possible there could be another issue)

I'm running 1.8.3 and to me, the problem is still there.

**Comment by lazan** [comment] 2023-11-28 10:42
Seems to be working in 1.19.1

**Comment by sean-mcmanus** [comment] 2023-11-28 21:01
@lazan That is good news. Yes, 1.19.1 does have a bunch of updates/fixes to our IntelliSense parser.

**Closed as completed** 2024-02-22 03:30 UTC
Labels: bug, Language Service, fixed, Visual Studio
