### ISSUE TITLE
Database fails to get created at the default location (or fallback to another location) on some remote Linux machines

### ISSUE THREAD

**Issue by windless0530** [microsoft/vscode-cpptools#4654] opened 2019-11-22 12:47 UTC
Type: General

**Describe the bug**
- OS and Version: MacOS 10.15.1
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
1. Add the following folders to both 'C_Cpp.default.includePath' in settings.json and 'configurations.includePath' in c_cpp_properties.json
`[
    "${workspaceFolder}/**",
    "${workspaceFolder}/.build/pb/c++/**",
    "${workspaceFolder}/pub/src/**",
    "${workspaceFolder}/third_party/**",
    "${workspaceFolder}/pub/src/third_party/**",
    "/usr/java/jdk1.8.0_191-amd64/include/**"
]`
2. At first, everything works well, no error tooltip on my includes in the code.
3. Today I suddenly found **ALL** the includes based on my workspace root in my code underlined by error wavy lines, and shows error tooltip "can not open source file ..." when I hover my mouse on them.

The screen shot can show the detail. In fact, all the included header files are written in the form of relative path to the my ${workspaceFolder}.

And the error persists even after I restarted my Code.

**Screenshots**
![image](https://user-images.githubusercontent.com/4645959/69426812-13045680-0d69-11ea-99d5-ab84286d11c6.png)
![image](https://user-images.githubusercontent.com/4645959/69426969-6aa2c200-0d69-11ea-8c86-ff2d13827dc6.png)
![image](https://user-images.githubusercontent.com/4645959/69426982-72fafd00-0d69-11ea-927d-eab7a7457410.png)

**Comment by justiceamoh** [comment] 2019-11-22 16:25
Same thing happened to me. I think something in the latest release (0.26.2) broke this. I'm also on macOS 10.15.

**Comment by michelleangela** [comment] 2019-11-22 17:21
@windless0530 and @justiceamoh, can you share [logs from the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)? @justiceamoh, does the issue only repro for you on 0.26.2 and not 0.26.1?

**Comment by justiceamoh** [comment] 2019-11-22 21:40
@michelleangela , find below my logs -- it's very brief.

```
Finished installing dependencies

Can't create IntelliSense client for /Users/Justice/artemis/src/main.c
```
And yes, I only see this issue on 0.26.2-insiders2, and not on 0.26.1

**Comment by justiceamoh** [comment] 2019-11-22 21:54
And here's a longer log  just after I install 0.26.2-insiders2

```
initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
Autocomplete is enabled.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Attempting to get defaults from compiler found on the machine: '/usr/local/bin/gcc-8'
terminating child process: 32651
cpptools/queryCompilerDefaults: 1
Attempting to get defaults from compiler found on the machine: '/usr/local/bin/gcc-8'
terminating child process: 32654
cpptools/didChangeFolderSettings
Attempting to get defaults from compiler in "compilerPath" property: '/usr/local/bin/arm-none-eabi-gcc'
arm-none-eabi-gcc: error: unrecognized command line option '-m64'

terminating child process: 32661
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: '/usr/local/bin/arm-none-eabi-gcc'
arm-none-eabi-gcc: error: unrecognized command line option '-m64'

terminating child process: 32663
  /Users/Justice/artemis/** is not a directory
  /Users/Justice/artemis/EmbedNN is not a directory
  Unable to retrieve file system information for /Users/Justice/artemis/EmbedNN. error = -1
  Folder: /usr/local/include/ will be indexed
  Folder: /Users/Justice/artemis/ will be indexed
  Folder: /Users/Justice/AmbiqSDK/ will be indexed
  Folder: /Library/Frameworks/OSXFUSE.framework/Versions/A/Headers/ will be indexed
Populate include completion cache.
cpptools/clearCustomConfigurations
Discovering files...
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /Users/Justice/artemis/
  Processing folder (recursive): /Users/Justice/AmbiqSDK/
  Processing folder (recursive): /Library/Frameworks/OSXFUSE.framework/Versions/A/Headers/
  Discovering files: 22786 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
```

**Comment by michelleangela** [comment] 2019-11-22 22:00
@justiceamoh, the log shows it's failing to query the compiler, so it fails to get the system include paths. In 0.26.2-insiders2, the compiler options -m32 and -m64 were introduced (to fix the issue https://github.com/microsoft/vscode-cpptools/issues/4635). We are currently trying to fix this for compilers that do not have those options (see issue https://github.com/microsoft/vscode-cpptools/issues/4653)

**Comment by windless0530** [comment] 2019-11-25 09:57
> @windless0530 and @justiceamoh, can you share [logs from the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)? @justiceamoh, does the issue only repro for you on 0.26.2 and not 0.26.1?


Here is the c/c++ output after I switched the logging level to 'DEBUG':

[cpp.log](https://github.com/microsoft/vscode-cpptools/files/3885946/cpp.log)

In this section, I can not find the include paths that I configured:
![image](https://user-images.githubusercontent.com/4645959/69530458-02dcb900-0fad-11ea-9e15-41c3ccccc46c.png)

**Comment by sean-mcmanus** [comment] 2019-11-26 00:29
@windless0530 With recursive includes (i.e. "**" at the end) it will only send the includes from the compiler or non-recursive includes unless the recursive includes are actually used. If you add a `#include` that is under a recursive included path, then you should see the path added.

The "Timed out waiting for tag parser initialization." is likely to cause failures for you.

Also, to reference C_Cpp.default.includePath with existing includes you need to add "${default}.

If you're using 0.26.1, it hasn't been changed in a month -- do you know what else changed? You could try doing a Reset IntelliSense Database command.

**Comment by sean-mcmanus** [comment] 2019-11-26 02:16
@justiceamoh Can you try 0.26.2-insiders3? The compiler querying issue should be fixed with that.

**Comment by windless0530** [comment] 2019-11-26 03:20
> @windless0530 With recursive includes (i.e. "**" at the end) it will only send the includes from the compiler or non-recursive includes unless the recursive includes are actually used. If you add a `#include` that is under a recursive included path, then you should see the path added.
> 
> The "Timed out waiting for tag parser initialization." is likely to cause failures for you.
> 
> Also, to reference C_Cpp.default.includePath with existing includes you need to add "${default}.
> 
> If you're using 0.26.1, it hasn't been changed in a month -- do you know what else changed? You could try doing a Reset IntelliSense Database command.

All of the following headers are really included, under the root path of configuration:
''${workspaceFolder}/**"
![image](https://user-images.githubusercontent.com/4645959/69596774-af1ab000-103e-11ea-9d46-6c9af67544bd.png)

And as for this cause, is there anything I can do?
> The "Timed out waiting for tag parser initialization." is likely to cause failures for you.

I have run "Reset IntelliSense Database", and restarted my Code, while the error squiggle is still there.

**Comment by sean-mcmanus** [comment] 2019-11-26 03:41
It sounds like the recursive includes feature isn't working for some reason, potentially due to the problems with creating the database. If you change it to "${workspaceFolder}" does it find the headers that are rooted there?

**Comment by windless0530** [comment] 2019-11-26 10:22
> It sounds like the recursive includes feature isn't working for some reason, potentially due to the problems with creating the database. If you change it to "${workspaceFolder}" does it find the headers that are rooted there?

Yes. In this way, it can.

However, there are some sub folders under the root of my workspace I need to include, which made recursive configuration quite necessary.

Meanwhile, my project uses [BLADE](https://github.com/chen3feng/blade-build) as building tool. If there is a solution like parsing the BLADE project structure file (the 'BUILD' file) and retrieves the depended source file locations, recursive includes feature is perhaps no longer needed.

**Comment by windless0530** [comment] 2019-11-26 11:04
BTW, my project is quite large, with 40000+ header files and 10000+ source files.

**Comment by windless0530** [comment] 2019-11-26 11:16
OK, I managed to search and add a dozen of include paths, without recursive features, one by one to my configuration.

Now the error squiggle disappeared. However, 'Go to definition' can not work still, even if the definition itself is within the SAME source file ...
![image](https://user-images.githubusercontent.com/4645959/69625211-15282700-1081-11ea-82af-b21281026e86.png)

All of the above problems occurred just recently. I guess they are related to something changed in recent releases.

**Comment by justiceamoh** [comment] 2019-11-26 14:00
@sean-mcmanus , just tried 0.26.2-insiders3 and that solved it for me. thanks!

**Comment by sean-mcmanus** [comment] 2019-11-26 20:12
@windless0530 Go to Def is most likely failing because your database is not able to get created (potentially the same reason for the recursive includes is failing). The "Timed out waiting for Tag Parser initilization" message I saw earlier could cause that. Can you do a "C/C++: Reset IntelliSense Database" command, or if that doesn't work, set the "browse.databaseFilename" to something like "${workspaceFolder}/.vscode/vc.db" and verify that it populates (i.e. grows in MB)? It's possible your OS isn't allowing access to the database at its existing location from some reason (permissions issue, locked by another process, etc.).

**Comment by sean-mcmanus** [comment] 2019-11-26 20:15
@windless0530 Also, https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders3 is our release candidate for 0.26.2 that we plan to release next week (if we don't find any high priority bugs) so you may want to try that. Or if you could use the "Install Another Version" feature and change the extensions.autoUpdate to false to use 0.25.1 that would help us see if it's a regression...you said "the problems occurred recently", but 0.26.1 was release 1 month ago, so something external may have changed on your machine (i.e. Mac Catalina update?...we haven't received other reports from Catalina users like this though).

**Comment by windless0530** [comment] 2019-11-27 02:25
> @windless0530 Also, https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders3 is our release candidate for 0.26.2 that we plan to release next week (if we don't find any high priority bugs) so you may want to try that. Or if you could use the "Install Another Version" feature and change the extensions.autoUpdate to false to use 0.25.1 that would help us see if it's a regression...you said "the problems occurred recently", but 0.26.1 was release 1 month ago, so something external may have changed on your machine (i.e. Mac Catalina update?...we haven't received other reports from Catalina users like this though).

Yes, I updated to Catalina a few days ago, which roughly matches in time.

CLARIFICATION: I remembered that I am Remote SSH ing to some linux machine to develop. So now it seems that there is NOTHING TO DO with Catalina.

**Comment by windless0530** [comment] 2019-11-27 02:33
> @windless0530 Go to Def is most likely failing because your database is not able to get created (potentially the same reason for the recursive includes is failing). The "Timed out waiting for Tag Parser initilization" message I saw earlier could cause that. Can you do a "C/C++: Reset IntelliSense Database" command, or if that doesn't work, set the "browse.databaseFilename" to something like "${workspaceFolder}/.vscode/vc.db" and verify that it populates (i.e. grows in MB)? It's possible your OS isn't allowing access to the database at its existing location from some reason (permissions issue, locked by another process, etc.).

Thanks @sean-mcmanus !

After reseting the IntelliSense database path, now it seems that **EVERYTHING WORKS WELL** now, not only the error squiggle, but also the 'Go To Definition', as well as recursive include path, and even "Command + Left Click -> go to the header file" which did not work either.

![image](https://user-images.githubusercontent.com/4645959/69688424-fa959280-1100-11ea-820d-16a19d355752.png)

What's more, now I can see the following prompt if I run "C/C++: Reset IntelliSense Database", which is not seen when I run the command without IntelliSense database path specified:
![image](https://user-images.githubusercontent.com/4645959/69688283-92df4780-1100-11ea-8cb0-fe636a7a087f.png)

**Comment by sean-mcmanus** [comment] 2019-11-27 02:42
@windless0530 Thanks for the info.

@bobbrow @Colengms Could all users on Catalina be unable to use the database at the default location? It seems odd that we wouldn't have gotten more complaints about this. We should probably verify if we can repro this on a Catalina machine.

The other explanation is a dangling process was preventing the database access, but that also means our database fallback mechanism is broken and should be fixed.

**Comment by sean-mcmanus** [comment] 2019-11-27 02:52
@windless0530 FYI, you can also change the C_Cpp.default.browse.databaseFilename in the VS Code user settings.json to have that the database be created locally for all workspaces.

**Comment by windless0530** [comment] 2019-11-27 03:37
> @windless0530 Thanks for the info.
> 
> @bobbrow @Colengms Could all users on Catalina be unable to use the database at the default location? It seems odd that we wouldn't have gotten more complaints about this. We should probably verify if we can repro this on a Catalina machine.
> 
> The other explanation is a dangling process was preventing the database access, but that also means our database fallback mechanism is broken and should be fixed.

I am sorry for the misleading, but I just remembered that I am **Remote SSH ing** to some linux machine to develop. So now it seems that there is NOTHING TO DO with Catalina. Maybe it was because of some authentication restriction amends by the administrator.

So for remote working environments, maybe it is a better idea to place the default IntelliSense database path under the workspace folder, for it can always be assumed that the code workspace folder is writable.

**Comment by Colengms** [comment] 2020-01-07 02:12
In 0.26.2 (Dec 2, 2019) we changed the default database path to leverage XDG_CACHE_HOME on Linux, or fall back to ~/.cache/vscode-cpptools/ .  Are you still able to repro the issue with the latest version of the extension?

**Comment by windless0530** [comment] 2020-01-14 04:31
> In 0.26.2 (Dec 2, 2019) we changed the default database path to leverage XDG_CACHE_HOME on Linux, or fall back to ~/.cache/vscode-cpptools/ . Are you still able to repro the issue with the latest version of the extension?

I am not sure of it because I had already customized my database path to my workspace folder to avoid the issue.

**Comment by bobbrow** [comment] 2020-07-16 21:44
This should have been addressed by the change to use XDG_CACHE_HOME on linux.  If anyone else is still having a problem with this, please open a new issue.  Thank you!

**Closed as completed by bobbrow** 2020-07-16 21:44 UTC
Labels: bug, Language Service, investigate: repro, Feature: Configuration
