### ISSUE TITLE
1.1.0-insiders3: Setup commands do not work when attaching

### ISSUE THREAD

**Issue by ryanpholt** [microsoft/vscode-cpptools#6417] opened 2020-10-30 16:41 UTC
See launch config:

```
    "configurations": [
        {
            "name": "attach to main",
            "type": "cppdbg",
            "processId":"${command:pickProcess}",
            "request": "attach",
            "program": "${workspaceFolder}/main",
            "MIMode": "gdb",
            "logging": {
                "engineLogging": true
            },
            "setupCommands": [
                {
                    "description": "add dir",
                    "text": "directory /home/ryanholt/debug_test/add_this_folder",
                    "ignoreFailures": true
                }
            ],
            "miDebuggerPath": "/usr/bin/gdb"
        }

    ]
```

In 1.1.0-insiders3, the "setupCommands" do not execute (only when attaching?). However, in previous versions they do. In 1.0.1, for example, if I enable engineLogging, I see:

```
1: (2525) <-1002-interpreter-exec console "directory /home/ryanholt/debug_test/add_this_folder"
1: (2526) ->~"Source directories searched: /home/ryanholt/debug_test/add_this_folder:$cdir:$cwd\n"
``` 

However, in 1.1.0-insiders3, I do not see this in the logs. Running `-exec show directories` confirms that the setup command did not run.

This is a problem for me because we build with `-fdebug-prefix-map` which means I need to manually set the source path directory.

This repros on any project. However, I attached my very small [repro](https://github.com/microsoft/vscode-cpptools/files/5466411/debug_test.zip). Use the debug config above and observe that the setupCommands do not work.

**Comment by WardenGnaw** [comment] 2020-10-30 18:12
Looks like in JSON we only set it for the launch case.
https://github.com/microsoft/MIEngine/blob/1b5b5e87d767e1feacebf690ad3bd6fefd2924ae/src/MICore/LaunchOptions.cs#L1889

However this is a common option between launch and attach.

@ryan-holt-1 Thank you for using insiders and filing this issue!

To workaround this issue, you can install VS Code Cpptools 1.0.1
![image](https://user-images.githubusercontent.com/3953714/97742385-72063b80-1aa1-11eb-8b1d-8ad455f92b58.png)

**Comment by weisun76** [comment] 2020-11-02 19:40
Hi WardenGnaw,

I met the same issue. When I tried to downgrade C/C++ to 1.01, it always automatically upgrade it after reloading. Anyway, hope you can fix this issue soon.

Regards,
Wei


> Looks like in JSON we only set it for the launch case.
> https://github.com/microsoft/MIEngine/blob/1b5b5e87d767e1feacebf690ad3bd6fefd2924ae/src/MICore/LaunchOptions.cs#L1889
> 
> However this is a common option between launch and attach.
> 
> @ryan-holt-1 Thank you for using insiders and filing this issue!
> 
> To workaround this issue, you can install VS Code Cpptools 1.0.1
> ![image](https://user-images.githubusercontent.com/3953714/97742385-72063b80-1aa1-11eb-8b1d-8ad455f92b58.png)

**Comment by sean-mcmanus** [comment] 2020-11-02 20:59
You need to set the extensions.autoUpdate to false or C_Cpp.updateChannel to "Default".

**Comment by sean-mcmanus** [comment] 2020-11-04 02:29
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.0-insiders4

**Closed as completed by sean-mcmanus** 2020-11-04 02:29 UTC
Labels: bug, debugger

**Comment by weisun76** [comment] 2020-11-05 03:01
Hi Sean,

Thank you so much!

I tested and confirmed it works. VSCode is really a great software and it
helps us a lot.

Best regards,
Wei
