### ISSUE TITLE
The language server is crashing with larger projects - macos

### ISSUE THREAD

**Issue by rganascim** [microsoft/vscode-cpptools#11674] opened 2023-11-14 00:59 UTC
### Environment

OS and version: macOS 14.1.1 23B81 arm64
VS Code: 1.84.2
C/C++ extension: v1.18.2

###  Issue description:
With larger projects, the language server continuously crashes. It's crashing too fast, that I need an external script to collect the lldb info while the cpptools still executes.

Errors suddenly appeared 2 days ago when I open VSCode. I was using in the same project without any problems. I already did the intellisense cache clear, and even tried to unistall all extensions, reinstall visual studio, change the cpptools versions. But I'm always getting this crash.

[crash_stack_cpptools_macos.txt](https://github.com/microsoft/vscode-cpptools/files/13326233/crash_stack_cpptools_macos.txt)

_Originally posted by @rganascim in https://github.com/microsoft/vscode-cpptools/issues/10651#issuecomment-1806888378_

**Comment by sean-mcmanus** [comment] 2023-11-14 01:20
I don't think that area of code has changed recently -- can you confirm it also repros with 1.17.5? We haven't seen this crash before. That code is processing the recursive includes so it's possible it may be caused by some unexpected condition in your file system or includePaths. Removing the "**" may be a workaround, although you'd have to replace it with an equivalent set of paths.

**Comment by rganascim** [comment] 2023-11-14 12:41
The same issue using 1.17.5 version + removing the ** from the end of the includePath too.

[crash_stack_cpptools_1_17_5_macos.txt](https://github.com/microsoft/vscode-cpptools/files/13348799/crash_stack_cpptools_1_17_5_macos.txt)

**Comment by sean-mcmanus** [comment] 2023-11-15 02:53
@rganascim We figured out a fix via reviewing the code from the call stack you provided. It should be in 1.19.0, which we're working on releasing, possibly by Thursday.

**Comment by sean-mcmanus** [comment] 2023-11-17 10:35
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.19.0 (pre-release)

**Comment by rganascim** [comment] 2023-11-20 18:59
I've switched to pre-release version and the language server isn't crashing anymore. Thanks!!

**Closed as completed** 2024-02-22 03:29 UTC
Labels: bug, Language Service, fixed, quick fix, reliability
