### ISSUE TITLE
Switch header / source often leads to open duplicate files in multiple editor groups

### ISSUE THREAD

**Issue by windless0530** [microsoft/vscode-cpptools#4192] opened 2019-09-05 03:00 UTC
**Type: LanguageService**
Switch header / source often leads to open duplicate files in multiple editor groups

**Describe the bug**
- OS and Version: macOS Mojave 10.14.6
- VS Code Version: 1.37.1
- C/C++ Extension Version: 0.25.1
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is.

Switch header / source often leads to open duplicate files in multiple editor groups

**To Reproduce**
1. Set the keyboard shortcut of "C/C++: Switch Header/Source" to "Ctrl + ;"
2. Set the keyboard shortcut of "View: Move Editor to Previous Group" to "Command + Left"
3. Set the keyboard shortcut of "View: Move Editor to Next Group" to "Command + Right"
4. Split the editors into 2 groups, left and right
5. Open a.cc in the right group
6. Press "Ctrl + ;" to open a.h in the right group
7. Press "Command + Left" to move a.h to the left group
8. Do some other operations, without changing the editor group for a.h / a.cc

> If the actual operation of the above step 8 is "focus on another doc in the left group, this issue can always be reproduced.

9. Focus on a.cc in right group and press "Ctrl + ;" again
10. **Sometimes**, though not always, a new a.h is opened in the right group, causing duplicate a.h's in both editor groups.

**Expected behavior**
Always focus on the existing a.h in the left group

**Screenshots**
None

**Additional context**
When this occurs, I can press "Command + Left" again to **_move_** the newly opened a.h to left again, which actually results in focusing the a.h in the left group and right one closed. I just wonder if I could avoid such uncertain redundant operation.

**Comment by sean-mcmanus** [comment] 2019-09-05 19:16
Yeah, I also hit this on Mac last week -- it didn't repro on Linux/Windows. I was hoping my Mac was just configured in some unusual way since we haven't heard any other complaints until now.

I'm not sure yet if it's a VS Code issue (i.e. https://github.com/microsoft/vscode/issues/12448 ) or something we can fix in our extension.

**Comment by sean-mcmanus** [comment] 2019-09-05 19:37
Ooops, your repro steps are different from what I was hitting. I get the same results on Windows when step 8 involves switching focus to a different doc -- is that what you're hitting or do you repro the issue when both a.h and a.cc are visible. We have a TODO in our code that says "Handle non-visibleTextEditor..not sure how yet" -- i.e. there doesn't appear to be a VS Code API for checking if a document is in a different column but not visible.

**Comment by ssoher** [comment] 2019-11-04 19:21
> 
> 
> We have a TODO in our code that says "Handle non-visibleTextEditor..not sure how yet" -- i.e. there doesn't appear to be a VS Code API for checking if a document is in a different column but not visible.

I came here to report this issue, this seems to be *my* problem on Windows.

**Comment by windless0530** [comment] 2019-11-13 07:02
> Ooops, your repro steps are different from what I was hitting. I get the same results on Windows when step 8 involves switching focus to a different doc -- is that what you're hitting or do you repro the issue when both a.h and a.cc are visible. We have a TODO in our code that says "Handle non-visibleTextEditor..not sure how yet" -- i.e. there doesn't appear to be a VS Code API for checking if a document is in a different column but not visible.

Thanks.

And yes, now I can 100% reproduce the issue by this way:
1. make a.h in the left group and a.cc in the right group.
2. focus on another doc in the left group.
3. focus on a.cc in the right group.
4. press key shortcut, trying to switch to a.h

Sounds that the lack of API you mentioned can explain.

**Comment by windless0530** [comment] 2020-01-19 09:35
Are there any updates about the solution to this issue? Thanks.

**Comment by sean-mcmanus** [comment] 2020-01-21 20:10
Sorry, no update.

**Comment by bobbrow** [comment] 2020-11-12 22:36
This appears to be a duplicate of #2667. We'll track it with that one.

**Closed as completed by bobbrow** 2020-11-12 22:36 UTC
Labels: bug, Language Service, Feature: Switch Header/Source

**Comment by sean-mcmanus** [comment] 2021-01-21 07:58
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2 , but you need to change the setting workbench.editor.revealIfOpen to true.
