### ISSUE TITLE
Incorrect GDB breakpoints on ambiguous filenames while debugging

### ISSUE THREAD

**Issue by Omnomios** [microsoft/vscode-cpptools#4698] opened 2019-12-04 05:04 UTC
I have two files with the same name in different namespaces and folders.
`src/first/Section.cpp`
`src/second/Section.cpp`

If I set a breakpoint in VScode at `src/second/Section.cpp` on line 66, the program will pause on the same line in `src/first/Section.cpp`. The wrong file.

I think when the breakpoints are being set in GDB only the filename is being used. Paths should be used when setting the breakpoints to avoid ambiguous names like this.

I tested it in GDB and the behavior was as expected.
`break Section.cpp:66` recreated the problem, using `break second/Section.cpp:66` created the correct breakpoint.

**OS:** Windows 10
**VScode:** 1.40.2
**vscode-cpptools:** 0.26.2
**GDB:** 8.3

**Comment by pieandcakes** [comment] 2019-12-06 17:51
This is a duplicate of #977.

**Closed as completed by pieandcakes** 2019-12-06 17:51 UTC
Labels: duplicate, debugger
