### ISSUE TITLE
language server crashes on 0.30.0-insiders

### ISSUE THREAD

**Issue by gracicot** [microsoft/vscode-cpptools#5915] opened 2020-08-06 13:26 UTC
Type: General

**Describe the bug**
- OS and Version: Arch (rolling)
- VS Code Version: Code - OSS 1.47.3 (from the arch repo)
- C/C++ Extension Version: 0.30.0-insiders
- Other extensions you installed (and if the issue persists after disabling them): CMake-tool, gitlens, CMake test-exporer
- The extension fails to load correctly. It did worked with the non-insider version and I don't know how to get back to it.

**To Reproduce**
1. Install the insider version of the C++ extension
2. Load a VSCode window

**Expected behavior**
The C++ extension is expected to load correctly

**Screenshots**
![Screenshot_20200806_092335](https://user-images.githubusercontent.com/2906673/89536894-84384c80-d7c6-11ea-929e-a48d32f432c4.png)

**Additional context**
The log window contains

>     Failed to read response from server: 2
>     Failed to read response from server: 2

The issue persist after rebooting the machine, upgrading the OS to its latest version and reinstalling the extension.

**Comment by sean-mcmanus** [comment] 2020-08-06 17:49
Our extension is detected missing files. How are you getting the Insider build? Are you manually installing https://github.com/microsoft/vscode-cpptools/releases/download/0.30.0-insiders/cpptools-linux.vsix or using the updateChannel mechanism?

You can get the non-Insiders by setting the C_Cpp.updateChannel to "Default". You may also need to uninstall 0.30.0-insiders and install 0.29.0.

**Comment by gracicot** [comment] 2020-08-06 17:57
@sean-mcmanus Thank you for the instruction to roll back. Strangely enough, after a few restarts and reload, it started working again. Maybe because I tried building it and suddenly it got the files it needed? It also worth noting that I forgot my laptop running a ssh session on the computer I was getting the error.

The console output now reads:
```
Finished installing dependencies

Failed to read response from server: 22
```

I would have liked to provide more info, but I can't seem to reproduce the error, sorry.

**Comment by sean-mcmanus** [comment] 2020-08-06 18:36
So it gives the "Failed to read response from server: 22" but it doesn't give the "failed to install successfully" message?

What is the OSS of the target machine that you're SSHing to? x64 Linux?

The "Failed to read response" means our cpptools-srv process is crashing. Does it crash with a simple .cpp file with just "int i;"? That would indicate that the process is missing or not runnable on your machine. Are you able to run ~/.vscode-server/extensions/ms-vscode.cpptools-0.30.0-insiders/bin/cpptools-srv on the target machine?

**Comment by sean-mcmanus** [comment] 2020-08-06 18:38
Also, does 0.29.0 not gives errors and 0.30.0-insiders gives errors?

**Comment by gracicot** [comment] 2020-08-06 19:54
@sean-mcmanus It was from a MacOS machine, but the extension worked fine on that workstation. The Arch Linux machine had the non working extension, which kind of work right now.

I have some highlighting being displayed and auto completion, but I get multiple `Failed to read response from server` with many different numbers. This happens on both machines.

After some use time I got this in the console too, but I doubt it's related to the issue I had:

    Quick info operation failed: Error: Failed to find translation unit. Try opening a source file that includes this header, then re-open this header.

Running `~/.vscode-server/extensions/ms-vscode.cpptools-0.30.0-insiders/bin/cpptools-srv` returns the code `255` in the console without any output.

I get no error running the old extension. I use C++20 and my project use some dependency I installed with Conan and CMake's FetchContent module.

**Comment by sean-mcmanus** [comment] 2020-08-06 20:26
We have a known high hitting crash regression with 0.30.0-insiders with "open_primary_source_file(int)" on the call stack, so my guess is that is what you are hitting. Are you able to get a call stack for the crash, such as via attaching a debugger before it crash, using some Linxu core dump logger, or checking ~/Library/Logs/DiagnosticReports crash logging on Mac?

We do not yet have a repro yet, so if you're able to provide any sample code that repros the crash that would help us get a fix (compiling the file with -E to generate a preprocessed file might help too if the repro requires certain system headers that might not match the ones we're using).

**Comment by sean-mcmanus** [comment] 2020-08-06 22:24
Setting your C_Cpp.intelliSenseCacheSize to 0 maybe be a workaround for this crash until we're able to fix the root issue (let us know if that workaround isn't working for you).

**Comment by gracicot** [comment] 2020-08-09 22:33
I don't see anything in `~/Library/Logs/DiagnosticReports` on my mac machine, even though I see the `Failed to read response from server`. I'll try to see what is happening on my linux machine.

**Comment by michelleangela** [comment] 2020-08-11 22:58
Updating tags until we get more information, such as a call stack of the the cpptools-srv process crashing.

**Comment by sean-mcmanus** [comment] 2020-08-12 20:37
We fixed the top hitting regression crash with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders2 . Let us know if this crash is still occurring with that.

Yeah, on some Mac OS's the ~/Library/Logs/Diagnostics don't contain our crash log -- we don't know why yet.

**Comment by michelleangela** [comment] 2020-12-09 18:30
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed.

**Closed as completed by michelleangela** 2020-12-09 18:30 UTC
Labels: Language Service, more info needed

**Comment by gracicot** [comment] 2020-12-09 20:00
Yes I haven't seen a crash with the new version yet. Thanks!
