### ISSUE TITLE
Auto-Completion (experimental)

### ISSUE THREAD

**Issue by zhhwss** [microsoft/vscode-cpptools#606] opened 2017-04-04 04:43 UTC
There are no automatic code hints for variables that have already appeared in the current file。

**Comment by bobbrow** [comment] 2017-04-04 15:32
Our extension currently disables `editor.quickSuggestions` when the `C_Cpp.autocomplete` setting is enabled (which is the default).  You should be getting automatic suggestions when you type certain operators (".", "->", "::") but our suggestion list is currently incomplete and caused users to have to 'escape' the suggestions to type keywords, so we disabled it temporarily for the case you mention.

**Comment by rdlaner** [comment] 2017-04-26 06:07
I just started using this extension and also noticed that intellisense does not automatically give suggestions when I start typing. I either have to use "ctrl+space" or encounter one of the specified operations (".", "->",...).
Is there any plan to support auto suggestions that trigger when typing?

**Comment by bobbrow** [comment] 2017-04-26 15:31
As I mentioned above, yes, we do plan to remove the temporary disabling of this setting.  soon.

**Comment by fxliang** [comment] 2017-04-28 13:50
is it possible to disable the completion triggered by . :: ->，when it's not OK to suggest the correct members of those, I used ycmd to make that work. if it's possible to disable completion triggered by those characters, it would be much better for me .

**Comment by sean-mcmanus** [comment] 2017-04-28 15:50
@fxliang The only way to disable the . :: -> autocomplete is to change the C_Cpp.autocomplete setting to "Disabled". Are you asking for an additional setting that enables our autocomplete when Ctrl+Space is used, but disables the popup at . :: ->?

**Comment by fxliang** [comment] 2017-04-28 16:13
@sean-mcmanus 
with editor.quickSuggestions it completes words in current file only , when cpptools helps to complete words in directory. However cpptools couldn't complete members in structure etc at .::->when with only ycmd(no cpptools) it does well. What I want to know is if it's possible to used cpptools complete words when not at .::->, at .::-> let ycmd do that art of completions.

Sorry for my chinglish :(

**Comment by fxliang** [comment] 2017-04-28 16:17
@sean-mcmanus yes， disable  the popup at .::->.

**Comment by sean-mcmanus** [comment] 2017-04-28 16:33
@fxliang We could enable disabling of the popup, but I don't know if the other autocomplete provider would kick in, because we're still registered as a general completion provider (such as when Ctrl+Space is used). How do you use ycmd? From the you-complete-me extension? If our tool is missing results when . :: -> are used then that is a bug we should fix (we have some known bugs), and we're also working on IntelliSense engine autocomplete which will give better results.

**Comment by fxliang** [comment] 2017-04-28 16:54
@sean-mcmanus yes , I am using  you-complete-me.

**Comment by sean-mcmanus** [comment] 2017-05-09 21:19
@fxliang We're working to add more accurate IntelliSense-based autocomplete when trigger characters are used, so we don't believe a setting to disable it will be needed. For the next update, we're just removing the automatic setting of quickSuggestions to false (the original issue).

**Comment by Srekel** [comment] 2017-05-19 14:31
Will these issues be resolved when the new C++ extension release is... released? :)
https://github.com/Microsoft/vscode/issues/26938
https://github.com/Microsoft/vscode/issues/26939

Plus, I would really like to be able to disable all of the suggestions for functions and types in the Windows SDK (and more). I'm very un-interested in them for this project.

Direct gif of buggy behaviour:

![autocompletebug](https://cloud.githubusercontent.com/assets/1578924/26251317/275e55ac-3cad-11e7-8835-31dd66ae0d9d.gif)

**Comment by bobbrow** [comment] 2017-05-19 15:32
@Srekel, the behavior you demonstrate in the gif is currently the expected behavior.  The tag parser does not scan local variables or collapse duplicates into a single item in the suggestion list.  The issues you list will be addressed when autocomplete suggestions are provided by the new IntelliSense engine.

**Comment by Srekel** [comment] 2017-05-19 17:11
New intellisense engine - is that something that's coming in VS Code or an upcoming feature in this extension?

Regarding my request to disable suggestions coming from "outside" the project, is that on the roadmap? Or is it something I can already do?

Thanks for the reply!

**Comment by bobbrow** [comment] 2017-05-19 17:41
The new IntelliSense engine is a feature of this extension.  It currently replaces the tag parser for quick info tooltips but is being updated to provide more features, such as autocomplete.

The Windows SDK is included by default on Windows.  If you open the command palette (CTL+SHIFT+P) and select "C/Cpp: Edit Configurations" a file called c_cpp_properties.json will be created and you can remove the paths you don't want to have included in your project.

You may need to delete the old DB to remove the extra symbols - I don't think we've published a fix for that issue yet.  On Windows, the DB should be under `%appdata%\Code\User\workspaceStorage\<hash>\ms-vscode.cpptools`.  Or you can just change the `browse.databaseFilename` property in the c_cpp_properties.json file to create a new one.

**Comment by bobbrow** [comment] 2017-05-23 23:39
This was fixed in version 0.11.1. Please reopen if you continue to have this issue.

**Closed as completed by bobbrow** 2017-05-23 23:39 UTC
Labels: Language Service, fixed
