### ISSUE TITLE
gdb breakpoint set to wrong source file

### ISSUE THREAD

**Issue by huili80** [microsoft/vscode-cpptools#7207] opened 2021-03-21 14:33 UTC
Type: Debugger

Say if there are 2 files of the same filename (identical basename i.e.) in different directories in the project, and when i try to set a breakpoint in one of those file, sometimes gdb would stop as if the breakpoint was set in the other file on the same line number. This problem has been there since i first stared using vscode+cpptools several years ago and never seemed to have been addressed. Does the cpptools not use the absolute path of the file when setting breakpoints on a line??

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by huili80** [comment] 2021-03-21 15:18
i do have a workaround for this. i have to insert the right amount of new lines in the first source file (one where i wanted the breakpoint) so that the breakpoint lands on a particular line number, such that the same line number in the second file happens to be outside of any function scope.

**Comment by WardenGnaw** [comment] 2021-03-22 17:48
Duplicate of #6754.

Solution: https://github.com/microsoft/vscode-cpptools/issues/6754#issuecomment-756964069

**Closed as completed by WardenGnaw** 2021-03-22 17:48 UTC
Labels: duplicate, debugger
