### ISSUE TITLE
Debbuger throws error when I issue a "Step into"

### ISSUE THREAD

**Issue by frenchiveruti** [microsoft/vscode-cpptools#6472] opened 2020-11-08 22:00 UTC
- VSCode Version: 1.51.0
- OS Version: Windows 10 / Linux 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 GNU/Linux

I'm using this: https://code.visualstudio.com/docs/cpp/config-wsl
I'm running Debian WSL, I run VSCode using "code ." on a debian terminal.
When I try to use the debugger and DO A SINGLE STEP (the ↓ arrow on the top options) y get this error:
![imagen](https://user-images.githubusercontent.com/1095997/98485238-b4432180-21f3-11eb-81d2-d627ee8bc1c6.png)
Which is, for me, as if I was reading Chinese, no idea what it means.

Interestingly, it **does** print stuff on screen, the function on top called "ingreseVarInt" has a printf and it can clearly be seen printed on the console below.  
It's when I try to do step by step that fails.

Steps to Reproduce:

1. Run VS Code under a WSL using "code ." in a WSL console/terminal
2. Code some C code.
3. Try to run a single step with the debugging tools included on VSC.
4. Error is thrown.

Here's my simple code:
```c
#include <stdio.h>
#include <stdlib.h>

int ingreseVarInt(char nombre)
{
   int variable;
   printf("Ingrese valor de variable %c:\n", nombre);
   scanf("%d", &variable);
   return variable;
}

int main (void){
    int x = ingreseVarInt('x');
    int y = ingreseVarInt('y');

    printf("%d es el mínimo", (x + y + abs(x - y)) / 2);
    
    
    return 0;
}
```

**Comment by WardenGnaw** [comment] 2020-11-09 00:42
This is GDB providing you the file when you step into the printf function but since you did not build the standard library, the file path it provides is unavaliabe.

Duplicate of https://github.com/microsoft/vscode-cpptools/issues/811

**Closed as completed by WardenGnaw** 2020-11-09 00:42 UTC
Labels: duplicate, debugger

**Comment by frenchiveruti** [comment] 2020-11-09 00:57
And... can I solve it? I have deadlines due to college. And I can't see if anything works.  
Thanks

**Comment by WardenGnaw** [comment] 2020-11-09 01:05
The debugger is currently stopped at `libc.so.6!_printf(const char * format)` which is in `printf.c`. 

If you are looking to look at the source code for printf, you can download the sources at https://www.gnu.org/software/libc/sources.html and use `sourceFileMap` to remap to file to a local path.

**Comment by frenchiveruti** [comment] 2020-11-09 01:06
Okay sorry but too much technical jargon, I have no idea what you're talking about.  
Pity.

**Comment by sean-mcmanus** [comment] 2020-11-11 01:04
Are you trying to debug printf? You probably should not need to do that. You may need to add a call fflush (see https://stackoverflow.com/questions/1716296/why-does-printf-not-flush-after-the-call-unless-a-newline-is-in-the-format-strin ).

What technical jargon did you not understand?
