### ISSUE TITLE
Intellisense doesn't recognize the Microsoft #import directive for importing type libraries or DLLs

### ISSUE THREAD

**Issue by wormspeed** [microsoft/vscode-cpptools#9223] opened 2022-04-22 11:11 UTC
### Environment

- OS and version: Windows x64 10.0.19042
- VS Code: 1.66.2
- C/C++ extension: C++17
- OS and version of remote machine (if applicable): N/A
- GDB / LLDB version: Don't know

### Bug Summary and Steps to Reproduce

Bug Summary:
I've got VS Code building with MSBuild and running, and debugging works fine. I've updated my include path and all of my #include statements for header files work fine, with code navigation and everything. The only thing Intellisense doesn't like is the #import statements for binary files, such as for the following macros:
```
#import <msxml3.dll>
#import "DmRender.tlb" 
#import "DmFile.tlb"
```
All these files are in the same directory as my headers. Intellisense gives me red squiggles under the # and says "Cannot open source file [filename]".

### Debugger Configurations

```shell
{
      "label": "build debug",
      "type": "shell",
      "command": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MsBuild.exe",
      "args": [
        "/p:Configuration=v140Debug",
        "/p:Platform=x64",
        "C:/Repos/LibInTouch/LibInTouch.sln"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "problemMatcher": "$msCompile"
    }

Build config:
"configurations": [
      {
        "name": "Run Studio RM debug",
        "type": "cppvsdbg",
        "request": "launch",
        "program": "C:/Repos/StudioRM/Application/SetupFiles/StudioRM/Binx64/StudioRMD.exe",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": false
      }
    ]
```

### Debugger Logs

```shell
N/A
```

### Other Extensions

N/A

**Comment by Colengms** [comment] 2022-04-22 17:12
Hi @Quenton4 .  Thanks for reporting this.  I believe this issue is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/2703 .  There is a workaround suggested in that issue.  Closing this one as a duplicate.

**Closed as completed by Colengms** 2022-04-22 17:12 UTC
