### ISSUE TITLE
Debugger not stopping on breakpoints on macOS Catalina

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#4357] opened 2019-09-29 22:29 UTC
**Info**

- OS and Version: macOS Catalina 10.15 Beta (19A573a)
- VS Code Version: `1.38.1`
- C/C++ Extension Version: `0.25.1`
- Other extensions: `vscodevim.vim`, unlikely to be related

**Bug**

The debugger won't break at any of my breakpoints or at the start of `main`. The program runs through and exits successfully. My breakpoints all look normal, not greyed out or anything:

<kbd><img width="300" src='https://user-images.githubusercontent.com/40591975/65840402-935c8d00-e2cd-11e9-8ee3-06cce446e59b.png'></kbd>

**Reproduce**

main.cpp:

```cpp
#include <stdio.h>

int main(int argc, char **argv) {
  printf("hello world!\n");
  return 0;
}
```

tasks.json (what I'm using to build):

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "build",
      "type": "shell",
      "command": "clang++",
      "args": [
        "-g",
        "main.cpp",
      ],
    }
  ]
}
```

launch.json:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(lldb) Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/a.out",
      "stopAtEntry": true,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "lldb",
      "logging": {
        "engineLogging": true,
        "traceResponse": true,
      }
    }
  ]
}
```

Debug console (with `engineLogging` and `traceResponse` turned on):
https://gist.github.com/brhsiao/b29e3e4191612dcee7a29cfe59487e11

I also ran the debugger manually from the command line and confirmed that breakpoints don't get set:

```
$ /Users/brandonhsiao/.vscode/extensions/ms-vscode.cpptools-0.25.1/debugAdapters/lldb/bin/lldb-mi ./ide
(gdb)
-file-exec-and-symbols "./ide"
^done
(gdb)
=library-loaded,id="./ide",target-name="./ide",host-name="./ide",symbols-loaded="1",symbols-path="/System/Volumes/Data/Users/brandonhsiao/monorepo/ide.dSYM/Contents/Resources/DWARF/ide",loaded_addr="-",size="552960"
breakpoint set -f main.cpp -l 4
Breakpoint 1: where = ide`main + 15 at main.cpp:4, address = 0x0000000100000e9f
^done
(gdb)
=breakpoint-created,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x0000000100000e9f",func="main",file="main.cpp",fullname="/Users/brandonhsiao/monorepo/main.cpp",line="4",times="0",original-location="main.cpp:4"}
(gdb)
run
Process 2509 launched: './ide' (x86_64)
^done
(gdb)
=thread-created,id="1",group-id="i1"
=thread-selected,id="1"
(gdb)
*running,thread-id="all"
(gdb)
@"hello world!\r\n"
(gdb)
=thread-exited,id="1",group-id="i1"
=thread-group-exited,id="i1",exit-code="0"
*stopped,reason="exited-normally"
(gdb)
```

**Comment by WardenGnaw** [comment] 2019-10-08 22:53
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/3829

**Closed as completed by WardenGnaw** 2019-10-08 22:53 UTC
Labels: bug, debugger

**Comment by sarad26** [comment] 2020-06-03 03:27
Hi, This is I am using Macbook pro I am working testing I can able start breakpoint in my system, If any one want Clearly, Then I can explain.Thanks #5292
