### ISSUE TITLE
.h header files automatically detected as C++

### ISSUE THREAD

**Issue by Andrej123456789** [microsoft/vscode-cpptools#9872] opened 2022-09-11 09:43 UTC
### Environment

- OS and Version: `Arch Linux, Kernel version: 5.19.7-arch1-1`
- VS Code Version: `1.70.0`
- C/C++ Extension Version: `v1.12.4`
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
`When you create string.h or any other C header file it is automatically detected as C++ even if code is empty and no C++ file exist in entire project`

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. Open 'explorer'
2. Click on 'New file'
3. Create new file with ends on '.h' in project where no C++ file exist

### Expected behavior

File to be automatically detected as C in C project

### Code sample and Logs

```shell
-------- Diagnostics - 9/11/2022, 11:42:59 AM
Version: 1.12.4
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c17",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-clang-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/vangu/Vesta/src/kernel/kernel.c ]:
    /home/vangu/Vesta/src/kernel/kernel.c
    /home/vangu/Vesta/src/kernel/keyboard/keyboard.h *
[ /home/vangu/Vesta/src/kernel/keyboard/keyboard.c ]:
    /home/vangu/Vesta/src/kernel/keyboard/keyboard.c
    /home/vangu/Vesta/src/kernel/keyboard/keyboard.h
[ /home/vangu/Vesta/src/kernel/gui/gui.c ]:
    /home/vangu/Vesta/src/kernel/gui/gui.c
[ /home/vangu/Vesta/src/kernel/libc/string.h ]:
    /home/vangu/Vesta/src/kernel/libc/string.h
Translation Unit Configurations:
[ /home/vangu/Vesta/src/kernel/kernel.c ]:
    Process ID: 8272
    Memory Usage: 312 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/lib/clang/14.0.6/include
        /usr/local/include
        /include
        /usr/include
        /home/vangu/Vesta/src/limine
    Standard Version: c17
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=140006
[ /home/vangu/Vesta/src/kernel/keyboard/keyboard.c ]:
    Process ID: 13386
    Memory Usage: 312 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/lib/clang/14.0.6/include
        /usr/local/include
        /include
        /usr/include
    Standard Version: c17
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=140006
[ /home/vangu/Vesta/src/kernel/gui/gui.c ]:
    Process ID: 15994
    Memory Usage: 312 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/lib/clang/14.0.6/include
        /usr/local/include
        /include
        /usr/include
    Standard Version: c17
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=140006
[ /home/vangu/Vesta/src/kernel/libc/string.h ]:
    Process ID: 17636
    Memory Usage: 312 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/12.2.0
        /usr/include/c++/12.2.0/x86_64-pc-linux-gnu
        /usr/include/c++/12.2.0/backward
        /usr/lib/clang/14.0.6/include
        /usr/local/include
        /include
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=140006
        --header_only_fallback
Total Memory Usage: 1248 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 37312
Number of files parsed: 5009
```
```


### Screenshots

_No response_

### Additional context

_No response_

**Comment by Colengms** [comment] 2022-09-12 18:13
Hi @Andrej123456789 .  This is currently 'by design'.  When a header file is opened, it's ambiguous whether or not it might intended to be compiled in C or C++.  The C/C++ Extension will try to locate a source file that includes the header.  If found, the language of that source file is used.  If no source file is found that includes the header, it's considered C++ by default.

The diagnostic logs you provided indicate `string.h` was not successfully associated with any existing source file, so was considered C++ by default.

Would you like to use this issue as a feature request to add a setting for the default language disposition of header files when no associated source file can be found?

**Comment by Andrej123456789** [comment] 2022-09-12 18:40
Well, I would like to use this issue as feature request to add a setting for the default language disposition, also it could search project and if there is no C++ file, it can set setting to C

**Comment by MangoDev1** [comment] 2022-09-14 00:06
Maybe add a config setting that assumes `*.h` files are C headers and `*.hpp` are C++ headers, or a config for what languages to assume for specific file types (.h, .hpp, .hh, .hxx, etc.)?

**Comment by Colengms** [comment] 2022-09-14 00:22
@Andrej123456789 @MangoDev1 

Actually, it occurs to me that it should already be possible to change the default association of .h files, using file association settings:

```
    "files.associations": {
        "*.h": "c"
    }
```

Since there is a simple solution for this, I'll close the issue.

**Closed as not planned by Colengms** 2022-09-14 00:22 UTC
Labels: Language Service, Feature: Configuration, enhancement

**Comment by sean-mcmanus** [comment] 2022-09-14 05:29
@Colengms Would it be worth keeping this issue open in order to auto-add the files.associations for the .h if the workspace only has C files?

**Comment by Andrej123456789** [comment] 2022-09-14 13:14
> @Andrej123456789 @MangoDev1
> 
> Actually, it occurs to me that it should already be possible to change the default association of .h files, using file association settings:
> 
> ```
>     "files.associations": {
>         "*.h": "c"
>     }
> ```
> 
> Since there is a simple solution for this, I'll close the issue.

Thanks
