### ISSUE TITLE
Annoying and useless popup suggestions if no workspace folder is set

### ISSUE THREAD

**Issue by manuel-tiedtke** [microsoft/vscode-cpptools#2691] opened 2018-10-18 16:21 UTC
Hi,

if a C file is created in a VSC instance without a Workspace folder set, some really annoying suggestions pop up at the end of include statements, once the closing angular bracket is typed. That way it is not possible to enter the next line with the Return key, but instead the first alphabetical IntelliSense (?) autosuggestion is appended to the include statement. (I want to keep the acceptSuggestionOnEnter setting, as I like it's behavior, when a Workspace folder is set.)

In the accompanying GIF, the behavior is visible. First a Workspace folder is set, which is subsequently removed to demonstrate the problem. Also no helpful suggestions are provided unless a Workspace folder is set.

Is this intended behavior, enforced by a property of the C language or is it a bug?

Cheers, Manuel.

PS: I have not overwritten any user settings regarding this behavior. It is the same in a default installation.

![vsc_c_cpp_autocompletion_workspace_folder_annoying_behaviour](https://user-images.githubusercontent.com/17552155/47168348-f2193880-d300-11e8-85d6-695cdc001c3b.gif)

**Comment by sean-mcmanus** [comment] 2018-10-18 18:45
This has already been fixed with 0.19.1-insiders2: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders2 . Can you try that? The bug was caused by https://github.com/Microsoft/vscode-cpptools/issues/2613 .

**Comment by manuel-tiedtke** [comment] 2018-10-18 21:48
Indeed version 0.19.1-insiders2 fixes that bug. Thank you very much.

**Closed as completed** 2018-10-30 23:43 UTC
Labels: bug, duplicate, Language Service, fixed
