### ISSUE TITLE
Intellisense database for default engine doesn't seem to be persistent

### ISSUE THREAD

**Issue by mdzahidh** [microsoft/vscode-cpptools#3311] opened 2019-03-18 22:40 UTC
**Type: LanguageService**

- OS and Version: Linux
- VS Code Version: 1.32.2
- C/C++ Extension Version: 0.21

I am using the following c_cpp_properties.json

```
{
    "configurations": [
        {
            "name": "Linux",
            "compileCommands": "${workspaceFolder}/compile_commands.json",
            "defines": [],
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}

```
I am also using the following settings:

```
"C_Cpp.intelliSenseEngine": "Default",
"C_Cpp.intelliSenseEngineFallback": "Disabled",

```

It works fine on the large codebase that I am working on, but I noticed that every time I restart vscode, cpptools seems to forget about the file indexing is has done in the previous session and intellisense doesn't seem to work until I open the .cpp files again one by one. Is the index database not persistent ? 

**Expected behavior**
Indexing completed in the past should be persistent.

**Comment by sean-mcmanus** [comment] 2019-03-18 22:50
This is a known issue. You need to manually set your `browse.path` if you are using compileCommands.

UPDATE: See https://github.com/Microsoft/vscode-cpptools/issues/1163.

**Comment by mdzahidh** [comment] 2019-03-19 00:07
Thanks ! I think that certainly fixes it for now.

**Comment by bobbrow** [comment] 2019-05-16 16:56
Closing as duplicate of #1163

**Closed as completed by bobbrow** 2019-05-16 16:56 UTC
Labels: bug, duplicate, Language Service
