### ISSUE TITLE
Task command line arguments are sometimes being wrapped with single quotes which breaks functionality

### ISSUE THREAD

**Issue by marcinols** [microsoft/vscode-cpptools#12027] opened 2024-02-27 09:25 UTC
### Environment

- OS and Version: OracleLinux 8
- VS Code Version: 1.86.2
- C/C++ Extension Version: 1.19.4
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
Latest update to cpptools, probably a bugfix for issue  https://github.com/microsoft/vscode-cpptools/issues/11422, breaks command line argument  passing  to make.

Steps to reproduce:
1. Create a task that runs make command
2. Add a parameter: "-j\`nproc\`"
3. Run the task and observe that the parameter is now wrapped with single quotes:
    '-j\`nproc\`' 
 which causes make to fail.
5. 
Expected behavior:
Older versions used to pass arguments directly, which would cause the shell to run nproc and substitute the right value before launching make.

### Configuration and Logs

```shell
{
    "env": {
        "compilerName": "gcc-10.2.0",
        "miscellaneous": "(private local Path)",
        "thirdParty": "(private local Path)",
        "vendor": "(private local path)",
        "vendorThirdParty": "(private local path)"
                                                  
    },
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/src",
                (other private include paths)
            ],
            "compilerPath": "${miscellaneous}/${compilerName}/bin/gcc",
            "defines": [
                (private defines)
            ],
            "cStandard": "c17",
            "cppStandard": "c++20",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by SteuxJMHelha** [comment] 2024-02-27 13:25
I have the kind same issue due to the added quotes. It appears suddenly on all computers in my school, breaking all compilation procedures. We now have to manuall specify all files in a folder, which is incompatible and very painful.
Note that an issue was written on VSC but closed because it was detected that the extension causes the problem: [tasks.json surrounds argument with single quotes when including asterisk](https://github.com/microsoft/vscode/issues/204947)

Here is the tasks.json that is not working anymore:

```
{
    "version": "2.0.0",
    "tasks": [
         {
            "type": "cppbuild",
            "label": "Compiler les tests",
            "command": "/usr/bin/gcc",
            "args": [
                "-g",
                "${workspaceFolder}/Sources/*.c",
                "${workspaceFolder}/Unity/*.c",
                "${workspaceFolder}/Tests/*.c",
                "-I",
                "/usr/include/mariadb",
                "-I",
                "/usr/include/mariadb/mysql",
                "-o",
                "${workspaceFolder}/Tests/tests",
                "-L",
                "/usr/lib/x86_64-linux-gnu/",
                "-l",
                "mariadb",
                "-l",
                "ncurses"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

```

**Comment by spotter1006** [comment] 2024-02-27 14:56
I have the same problem

**Comment by bobbrow** [comment] 2024-02-27 17:53
The case in the original post may be expected if using "args" to specify "-j nproc".  You should use "-j" and "nproc" as separate arguments because each of the args is treated as a single argument and quotes will be added when spaces are detected.

The responses about getting incorrect escaping when using a `*` is a duplicate of #12001 which we are in the process of fixing.  #12026 should address it.  We're sorry for the inconvenience. If you need an immediate resolution we recommend rolling back to version 1.18.5 until we publish 1.19.5.

**Closed as not planned by bobbrow** 2024-02-27 17:53 UTC
Labels: bug, duplicate, tasks/build/debug

**Comment by marcinols** [comment] 2024-02-27 19:01
There are NO spaces:
"<dash>j<backtick>nproc<backtick>"
 and yet it is being wrapped wirh single quotes.
It works fine with older version.


wt., 27 lut 2024, 18:54 użytkownik Bob Brown ***@***.***>
napisał:

**Comment by bobbrow** [comment] 2024-02-27 19:48
I see.  Looks like Markdown messed up your message.  I'll fix it.  The existence of backtick in the argument puts that arg in the same category as `*`, so your issue is a duplicate of #12001 as well.
