### ISSUE TITLE
IntelliSense of errors in C++ auto parameters

### ISSUE THREAD

**Issue by Haceau-Zoac** [microsoft/vscode-cpptools#6934] opened 2021-02-09 11:24 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 7 Service Pack 1
- VS Code Version: 1.53.0 (user setup)
- C/C++ Extension Version: 1.2.0
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
-- workspace: some temporary files, include a temp.c file, a temp.cpp file, a temp.html file, a .net project, etc.
-- bug: IntelliSense of errors in C++ auto parameters
-- code:
```c++
#include <iostream>

auto add(auto left, auto right)
{
  return left + right;
}

int main()
{
  std::cout << add(1, 2);

  return 0;
}
```
-- compiler: Clang++ 11.0.0
-- compiler target: i686-pc-windows-msvc
-- compiler thread model: POSIX
-- installed dir: F:\Visual Studio 2019 Preview\Visual Studio IDE\VC\Tools\Llvm\bin
-- run extension: Code Runner 0.11.2
-- code runner configure of c++: cd $dir && chcp 65001 && clang++ *.cpp -Werror -o $fileNameWithoutExt.exe -Wall -std=c++20 && $dir$fileNameWithoutExt
-- C_Cpp.default.cppStandard: c++20
-- output: 3
-- IntelliSense error: 有多个 重载函数 "add" 实例与参数列表匹配: -- 函数模板 "auto add(auto left, auto right)" (已声明 所在行数:3) -- 函数模板 "int add(auto left, auto right)" (已声明 所在行数:3) -- 参数类型为:  (int, int)"

**Steps to reproduce**
1. Write a source code as above C++ file
2. See error

**Expected behavior**
Fix it so that it doesn't report errors to auto parameters

<details>
  <summary><strong>Logs</strong></summary>

```
文件排除: **/.git
文件排除: **/.svn
文件排除: **/.hg
文件排除: **/CVS
文件排除: **/.DS_Store
文件排除: **/.vscode
搜索排除: **/node_modules
搜索排除: **/bower_components
搜索排除: **/*.code-search
搜索排除: **/.vscode
填充包含完成缓存。
正在发现文件...
```
</details>

**Screenshots**

![workspace](https://user-images.githubusercontent.com/61569726/107356652-07d34d00-6b0c-11eb-89d1-6ec68971197e.png)

**Additional context**

**Comment by michelleangela** [comment] 2021-02-09 23:58
Verified issue on Windows 10 with cl.exe and C++20.

**IntelliSense error:**
>more than one instance of overloaded function "add" matches the argument list: -- function template "auto add(auto left, auto right)" (declared at line 3) -- function template "int add(auto left, auto right)" (declared at line 3) -- argument types are: (int, int)

![image](https://user-images.githubusercontent.com/38734287/107444395-5a524080-6aef-11eb-8a6d-f811d55b8980.png)

**c_cpp_properties.json**
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/mainint/VC/Tools/MSVC/14.28.29331/bin/Hostx64/x64/cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++20",
            "intelliSenseMode": "windows-msvc-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment] 2021-02-11 01:28
@michelleangela Were you going to file a bug on VS?

**Comment by michelleangela** [comment] 2021-02-11 01:54
> @michelleangela Were you going to file a bug on VS?

I forgot to add that this works on Visual Studio.

**Comment by sean-mcmanus** [comment] 2021-02-11 03:48
It repros in VS -- the repro is just trickier -- you have to make various edits and it'll randomly appear (i.e. I couldn't find edits that would repro 100%). @Colengms This would be a good candidate to get an isense_driver repro.

![image](https://user-images.githubusercontent.com/19859882/107600206-e475d400-6bd7-11eb-8e54-9c4ba4f5a98d.png)

**Comment by sean-mcmanus** [comment] 2021-02-11 03:49
I assigned it to Milestone 1.3 for getting a isense_driver repro, not getting a fix.

**Comment by michelleangela** [comment] 2021-02-11 18:08
@sean-mcmanus  Thanks for find a repro on Visual Studio. I'll file a feedback ticket for it.

**Comment by michelleangela** [comment] 2021-02-11 18:45
Reported this issue on Visual Studio. Feedback ticket https://developercommunity2.visualstudio.com/t/unexpected-intellisense-error-for-c-auto-type-para/1337431.

When the issue is resolved for Visual Studio, the C++ extension will be able to port over the fix.

**Comment by michelleangela** [comment] 2021-02-18 07:22
We discovered that this is the same issue as https://github.com/microsoft/vscode-cpptools/issues/6714. Closing this and duplicating it to that issue.

**Closed as completed by michelleangela** 2021-02-18 07:22 UTC
Labels: bug, duplicate, Language Service, Visual Studio, verified
