### ISSUE TITLE
Suggestions about the break/continue snippets

### ISSUE THREAD

**Issue by Wakotu** [microsoft/vscode-cpptools#9267] opened 2022-05-04 06:12 UTC
### Feature Request

I hope you can revise the `break;` and `continue;` snippet to 'break' and `continue`. For example, when I type `c = a / b;` and press the `enter` key, it would turn to `c = a / break;` . This snippet may be not convenient to me.

**Comment by bobbrow** [comment] 2022-05-04 19:34
Thanks for reporting this issue.  We determined this is a duplicate of #9115. We fixed it for version 1.10, but it's still in pre-release.  If you would like to get the fix now, you can switch to the pre-release version of the extension.

**Closed as completed by bobbrow** 2022-05-04 19:34 UTC
Labels: bug, duplicate, Language Service, Feature: Auto-complete
