### ISSUE TITLE
intellisense doesnot work

### ISSUE THREAD

**Issue by daheibuhei** [microsoft/vscode-cpptools#7639] opened 2021-06-02 07:16 UTC
Bug type: Debugger

**Describe the bug**
- OS and Version:ubuntu20.04
- VS Code Version:1.56.2
- C/C++ Extension Version:1.4.0
- Other extensions you installed (and if the issue persists after disabling them):chinese language
- A clear and concise description of what the bug is.
my ubuntu20 is installed in  vmware,i edit cpp file on window10 by ntfs file system via vmware shared directory.
Then intellisense doesnot work anymore.i have tried changing the file encoding to utf8 LF,but it does noting.
just like this
![image](https://user-images.githubusercontent.com/46115753/120439593-450e6400-c3b5-11eb-952f-3d923b872ccc.png)
But,if i copy this file into ubuntu and open it,it will be like this
![image](https://user-images.githubusercontent.com/46115753/120439747-72f3a880-c3b5-11eb-928d-38049cdebf7a.png)

**Comment by sean-mcmanus** [comment] 2021-06-02 19:09
I don't understand. Are both screenshots using the VS Code in Ubuntu? What do you see when you run C/C++: Log Diagnostics.

**Comment by daheibuhei** [comment] 2021-06-03 01:05
sorry,my english is so poor. yes,both pics are using vscode in ubuntu20,just the locations of the cpp file are diffrent. one is in ubuntu20 directly, while another is in window10 and be opened via vmware shared folders.do u know vmware shared folders?
i got screenshots.
![image](https://user-images.githubusercontent.com/46115753/120569820-46896c00-c449-11eb-9e16-34ad1d199582.png)
![image](https://user-images.githubusercontent.com/46115753/120569589-c7943380-c448-11eb-8fdb-ce49b727d75f.png)
![image](https://user-images.githubusercontent.com/46115753/120569752-25c11680-c449-11eb-86c9-008e65b22871.png)
by this way,in ubuntu, i can easily,directly edit files which are placed in windows.
for the second question,i donot know that, but for this problem, it is not necessary to run my app,is there still some log?

**Comment by daheibuhei** [comment] 2021-06-03 01:09
sorry,my english is so poor. yes,both pics are using vscode in ubuntu20,just the locations of the cpp files are diffrent. one is in ubuntu20 directly, while another is in window10 and be opened via vmware shared folders.do u know vmware shared folders?
i got screenshots.
![image](https://user-images.githubusercontent.com/46115753/120569820-46896c00-c449-11eb-9e16-34ad1d199582.png)
![image](https://user-images.githubusercontent.com/46115753/120569589-c7943380-c448-11eb-8fdb-ce49b727d75f.png)
![image](https://user-images.githubusercontent.com/46115753/120569752-25c11680-c449-11eb-86c9-008e65b22871.png)
by this way,in ubuntu, i can easily,directly edit files which are placed in windows.
for the second question,i donot know that, but for this problem, it is not necessary to run my app,is there still some log?

**Comment by sean-mcmanus** [comment] 2021-06-03 19:29
When you set C_Cpp.loggingLevel to "Debug" do you see any errors in the C/C++ panel? What do you get when you run the C/C++: Log Diagnostics command from the View->Command Palette?

**Comment by sean-mcmanus** [comment] 2021-06-03 19:31
Also, are you opening a folder on the /mnt/ location?

And does your Outline view populate after opening a file?

**Comment by daheibuhei** [comment] 2021-06-05 08:17
so stupid i am, i think this is what you want.
![image](https://user-images.githubusercontent.com/46115753/120884767-bfd6b980-c617-11eb-88ef-b48624a80b89.png)
![image](https://user-images.githubusercontent.com/46115753/120884743-961d9280-c617-11eb-8a96-dc61cee77901.png)
![image](https://user-images.githubusercontent.com/46115753/120884983-f82ac780-c618-11eb-9620-eb3ba470b171.png)
![image](https://user-images.githubusercontent.com/46115753/120885061-64a5c680-c619-11eb-9603-dc17753f4b03.png)

yes,the folder is on /mnt,you can see it below.And outline view works very well
and i ran the C/C++: Log Diagnostics command,the output is:

-------- Diagnostics - 2021/6/5下午3:55:32
Version: 1.4.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /mnt/hgfs/myWork/CPBasic/CPBasic.cpp ]:
    /mnt/hgfs/myWork/CPBasic/CPBasic.cpp
Translation Unit Configurations:
[ /mnt/hgfs/myWork/CPBasic/CPBasic.cpp ]:
    Process ID: 2570
    Memory Usage: 92 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/9
        /usr/include/x86_64-linux-gnu/c++/9
        /usr/include/c++/9/backward
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=90300
Total Memory Usage: 92 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 2813

**Comment by sean-mcmanus** [comment] 2021-06-07 19:00
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4573 . A potential workaround is to open the folder via the resolved path instead of the path with the symlink.

**Closed as completed by sean-mcmanus** 2021-06-07 19:00 UTC
Labels: duplicate, Language Service

**Comment by daheibuhei** [comment] 2021-06-08 00:41
No symlink? that's unnormal. Is this a problem that can't be solved?

**Comment by sean-mcmanus** [comment] 2021-06-08 01:02
It can be solved, we just haven't done it yet. We have to re-write our implementation of file canonicalization for Linux/Mac to not call realpath.

**Comment by daheibuhei** [comment] 2021-06-08 01:06
ok.i am looking forword to that day you solve it.thanks for the answer
