### ISSUE TITLE
Some lines of the Non-English file is copyed and pasted to the end line when press "Format Code" constantly.

### ISSUE THREAD

**Issue by xiaoyao11** [microsoft/vscode-cpptools#209] opened 2016-09-08 02:59 UTC
OS version: win 10  1511
VS Code version: 1.4
Cpptools version: 0.9.0
1.Open a Non-English file as below screenshot:
![1](https://cloud.githubusercontent.com/assets/21498631/18335194/0ffec9ec-75b0-11e6-8c92-889061cb46d2.PNG)
2.Then right click and click Format Code, the code is formatted as below screenshot:
![2](https://cloud.githubusercontent.com/assets/21498631/18335536/8bfb9168-75b2-11e6-8609-6d0df65c68d0.PNG)
3.Repeat the step 2, the code is again formatted as below screenshot:
![3](https://cloud.githubusercontent.com/assets/21498631/18335312/14e409a8-75b1-11e6-8833-69779d4c05b3.PNG)
4.Repeat the step 2, the code is again formatted as below screenshot:
![4](https://cloud.githubusercontent.com/assets/21498631/18335347/4b3cab4a-75b1-11e6-9436-ee0a12213691.PNG)
When repeat step 2, some lines of the Non-English file is copyed and pasted to the end line.

**Comment by sean-mcmanus** [comment] 2016-09-12 16:58
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/176 .

**Closed as completed by sean-mcmanus** 2016-09-12 16:58 UTC
Labels: duplicate, fixed

**Comment by sean-mcmanus** [comment] 2016-09-23 23:44
Fixed in 0.9.2.
