### ISSUE TITLE
Running on ubuntu 12.04

### ISSUE THREAD

**Issue by jstys** [microsoft/vscode-cpptools#229] opened 2016-09-15 20:03 UTC
On startup of vscode 1.5.2 in ubuntu 12.04 x64 with cpptools 1.5.2, I am receiving an error that seems to be indicating that the language server is failing for c++.  Below is the error message in the developer console that is coming from the cpptools extension

> "{"0":"TypeError: Cannot read property 'forEach' of null\n    at LanguageClient.cleanUp (/home/jim.stys/.vscode/extensions/ms-vscode.cpptools-0.9.1/node_modules/vscode-languageclient/lib/main.js:471:24)\n    at LanguageClient.stop (/home/jim.stys/.vscode/extensions/ms-vscode.cpptools-0.9.1/node_modules/vscode-languageclient/lib/main.js:454:14)\n    at LanguageClient.handleConnectionError (/home/jim.stys/.vscode/extensions/ms-vscode.cpptools-0.9.1/node_modules/vscode-languageclient/lib/main.js:684:18)\n    at errorHandler (/home/jim.stys/.vscode/extensions/ms-vscode.cpptools-0.9.1/node_modules/vscode-languageclient/lib/main.js:559:19)\n    at /home/jim.stys/.vscode/extensions/ms-vscode.cpptools-0.9.1/node_modules/vscode-languageclient/lib/main.js:45:42\n    at CallbackList.invoke (/home/jim.stys/.vscode/extensions/ms-vscode.cpptools-0.9.1/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:103:39)\n    at Emitter.fire (/home/jim.stys/.vscode/extensions/ms-vscode.cpptools-0.9.1/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:167:36)\n    at writeErrorHandler (/home/jim.stys/.vscode/extensions/ms-vscode.cpptools-0.9.1/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:92:22)\n    at CallbackList.invoke (/home/jim.stys/.vscode/extensions/ms-vscode.cpptools-0.9.1/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:103:39)\n    at Emitter.fire (/home/jim.stys/.vscode/extensions/ms-vscode.cpptools-0.9.1/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:167:36)"}"

Additionally, I'm not sure if this is any indication of the problem, but running ~/.vscode/extensions/ms-vscode.cpptools-0.9.1/bin/Microsoft.VSCode.CPP.Extension.linux returns the following errors on my console.

> ./Microsoft.VSCode.CPP.Extension.linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.18' not found (required by ./Microsoft.VSCode.CPP.Extension.linux)
> ./Microsoft.VSCode.CPP.Extension.linux: /lib/x86_64-linux-gnu/libc.so.6: version`GLIBC_2.17' not found (required by ./Microsoft.VSCode.CPP.Extension.linux)

**Comment by pieandcakes** [comment] 2016-09-16 18:11
This is probably because the language service is compiled with glibc version 2.18. @sridmad is there a workaround for this?

**Comment by delmyers** [comment] 2016-09-16 19:19
Looks like it si probably a duplicate of #19. @sridmad, @greazer, you might want to take a closer look at these issues as they are hitting more customers.

**Comment by sridmad** [comment] 2016-09-16 19:59
At this point we support Ubuntu 14.04 and later. Something we can look into for Oct update of the extension

**Comment by bobbrow** [comment] 2017-04-24 17:51
This is being tracked by issue #19.

**Closed as completed by bobbrow** 2017-04-24 17:51 UTC
Labels: Language Service, fixed

**Comment by sean-mcmanus** [comment] 2017-12-12 00:43
Should be fixed with 0.14.4.
