### ISSUE TITLE
cpptools.exe keeps tag parsing every single file in a folder, 99.9% of which are not even used

### ISSUE THREAD

**Issue by Leopard20** [microsoft/vscode-cpptools#8588] opened 2021-12-20 06:27 UTC
It seems to me that this extension is active 99% of the time, and is always using my disk and CPU, which is bad.

How can I make it stop? There's only a `Workspace Parsing Priority` option, but it doesn't allow me to stop this completely.

In comparison, VS2019 takes like 5-6 seconds to parse my project and then it's idle. Like literally 0 CPU and disk usage. It seems to me this extension is getting stuck in a loop.

This is after over 10 minutes (I haven't touched my project at all):
![image](https://user-images.githubusercontent.com/16115820/146721559-12816348-8d3f-4586-9b30-0aab7fcb8ce5.png)

So yeah, pretty sure it's stuck in an infinite loop somewhere.

VSCode version (latest):
```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```
cpptools version (latest): `1.7.1`
I use `ms-vscode.cmake-tools` as the configuration provider

**Comment by Leopard20** [comment] 2021-12-20 06:40
Or this: 
I have literally nothing open. For several minutes. What is it doing?!
![image](https://user-images.githubusercontent.com/16115820/146723041-3e4e4947-48de-45d8-808a-2d20eb8dc7e8.png)

**Comment by Leopard20** [comment] 2021-12-20 07:14
looks like it keeps writing non-stop to this file. `.BROWSE.VC.DB`

**Comment by Leopard20** [comment] 2021-12-20 07:49
in addition I keep seeing this when I attach debugger to `cpptools`: (it loops)
```
Exception thrown at 0x770EA8B2 in cpptools.exe: Microsoft C++ exception: antlr::NoViableAltException at memory location 0x07B0DB6C.
Exception thrown at 0x770EA8B2 in cpptools.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x770EA8B2 in cpptools.exe: Microsoft C++ exception: antlr::NoViableAltException at memory location 0x07B0D208.
Exception thrown at 0x770EA8B2 in cpptools.exe: Microsoft C++ exception: antlr::NoViableAltException at memory location 0x07B0DB6C.
Exception thrown at 0x770EA8B2 in cpptools.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x770EA8B2 in cpptools.exe: Microsoft C++ exception: antlr::NoViableAltException at memory location 0x07B0D208.
Exception thrown at 0x770EA8B2 in cpptools.exe: Microsoft C++ exception: antlr::NoViableAltException at memory location 0x07B0DB6C.
```

**Comment by Leopard20** [comment] 2021-12-20 08:12
So after looking at the previous issues, it seems that this extension has lots of problems with symlinks. So I guess it's safe to say this is another similar bug (this time on Windows; as far as I could see previous ones were for macOs and Linux)
Also I don't symlink to another drive like those issues mentioned. It's structured like this:
```
root
|__repo1
|  |__...(repo1 has no symlink to any other file or folder)
|__repo2
   |__external
      |__symlink to repo1
```

**Comment by sean-mcmanus** [comment] 2021-12-20 22:15
I don't recall any known bugs with symlinks on Windows. I'm not able to repro the issue with
![image](https://user-images.githubusercontent.com/19859882/146839652-98ea7d2b-14ac-48a9-858d-3373f189a1a3.png)

Do you know what is different with your repro?

Do you get any useful logging with C_Cpp.loggingLevel set to "Debug"? If not, can you temporarily set it to the hidden value of "7"?

Another way to tell what is going on is to attach a debugger and break (see https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) and ignore the threads with a shallow callstack.

**Comment by sean-mcmanus** [comment] 2021-12-20 22:18
Also, the "cpptools.exe: Microsoft C++ exception" are "by design" -- they are from normal exception handling that our tag parser causes.

Also, one potentially work around is to add any offending paths/symlinks to "C_Cpp.files.exclude" since our directory iterator will check that.

**Comment by sean-mcmanus** [comment] 2021-12-20 22:22
If the database is increasing in size, it could be "normal behavior" from parsing the boost library (i.e. adding the path to C_Cpp.files.exclude should fix it).

Or this could be https://github.com/microsoft/vscode-cpptools/issues/8459 -- which is fixed with 1.8.0-insiders2, so you might want to try that.

**Comment by Leopard20** [comment] 2021-12-21 03:56
@sean-mcmanus 
It appears it wasn't an infinite loop. It is just taking a very long time to "tag parse" the files. (whatever that means)
The problem, however, is that I don't use 99.9% of these files. Why does it even waste so much time (and disk space) on that?
e.g. from boost, I probably use at most 50 files, not 50000 files.
Also it redoes this every time I reopen the repository (`.BROWSE.VC.DB` resets). It's a huge waste of computer resources, especially for someone like me who codes on a laptop, not a super computer.
I closed VSCode after like 5 minutes. This is what the log had before I exited:
[log.txt](https://github.com/microsoft/vscode-cpptools/files/7749396/log.txt)

**Comment by sean-mcmanus** [comment] 2021-12-21 18:56
You should make sure your C_Cpp.default.browse.limitSymbolsToIncludedHeaders setting is set to true (or the equivalent in c_cpp_properties.json), if that that's the case, then the entire boost folder shouldn't be tag parsed, only the headers that match names of files that are `#included` by files in your workspace, which should be relatively fast.

The database will reset if the process exits before 5 seconds after a database write to prevent against a potentially corrupted database being used.

Also, there is a Pause Workspace parsing command you can use after clicking the database icon.

I don't believe that CMake Tools has a list of all the external headers that are included when building, which would require a full build of the code -- you could try filing an issue with CMake Tools if you want, although the configuration provider API would also need to updated https://github.com/microsoft/vscode-cpptools-api to enable that info to be provided.

Tag parsing is used to provide global symbols (across translation units) for go to definition, find symbols, find all references, etc.

**Comment by Leopard20** [comment] 2021-12-22 04:02
> C_Cpp.default.browse.limitSymbolsToIncludedHeaders setting is set to true

It is. Does it mean it could be a bug?

> I don't believe that CMake Tools has a list of all the external headers that are included when building, which would require a full build of the code

That's not what I meant though. That would probably cause the same issue all over again.
I mean for tag parsing, this would be a better process in my opinion:
1. Retrieve the project source files (those that are linked to the build target, e.g. via `add_executable` in CMake)
2. Scan the source files and find the `#include`d headers.
3. Recursively tag parse the headers.

**Comment by sean-mcmanus** [comment] 2021-12-27 18:02
We already do something very similar to the steps 1-3 that you describe. However, scanning in the `#include` doesn't always use the full includePath so it may include some additional files that didn't that match based on just the name, but that usually shouldn't take significantly more processing.

Are you able to provide any additional repro info? It sounds like you may be experiencing a bug.

**Closed as completed** 2022-02-26 11:16 UTC
Labels: bug, Language Service, more info needed, not reproing
