### ISSUE TITLE
symbol search doesn't work

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode-cpptools#1060] opened 2017-09-23 09:48 UTC
Some lib I don't download, so don't add to include path and browse path, but I don't understand why I can't find symbol in the file.

    * Operating System and version
       macos 10.12.6 
    * VS Code version and if you are using the Insiders build
       1.16.1
    * C/C++ extension version
       0.12.4
    * Other extensions you installed and if the issue persists after disabling them
      no
    * step-by-step instructions to reproduce the issue
    * A small code sample, zipped up project, or open source repo we can use to verify the bug
    * Relevant settings from your settings.json, c_cpp_properties.json, and/or launch.json files
{
    "files.autoGuessEncoding": true,
    "files.autoSave": "onFocusChange",
    "files.exclude": {
        ".*": true,
        "**/CVS": true,
        "**.a": true,
        "**/.DS_Store": true,
        "**/.git": true,
        "**/.hg": true,
        "**.o": true,
        "**.so": true,
        "**/.svn": true
    },
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "editor.fontSize": 12.5,
    "editor.formatOnType": true,
    "editor.formatOnSave": true,
    "editor.minimap.enabled": false,
    "editor.renderWhitespace": "all",
    "editor.useTabStops": false,
    "terminal.external.osxExec": "iTerm.app",
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.fontFamily": "menlo",
    "window.openFilesInNewWindow": "off",
    "workbench.colorTheme": "Monokai",
    "workbench.startupEditor": "newUntitledFile",
    "window.zoomLevel": 0,
    "workbench.iconTheme": "vscode-icons",
    // golang
    "go.buildOnSave": "workspace",
    "go.buildFlags": [],
    "go.coverOnSave": false,
    "go.formatOnSave": true,
    "go.formatTool": "goreturns",
    "go.goroot": "/usr/local/go",
    "go.gopath": "/Users/kurt/project/go",
    "go.lintFlags": [],
    "go.lintOnSave": "workspace",
    "go.vetFlags": [],
    "go.vetOnSave": "workspace",
    "go.useCodeSnippetsOnFunctionSuggest": false,
    // c++
    "C_Cpp.addWorkspaceRootToIncludePath": true,
    "C_Cpp.autocomplete": "Default",
    "C_Cpp.errorSquiggles": "Enabled",
    "C_Cpp.intelliSenseEngine": "Default",
    // "C_Cpp.intelliSenseEngine": "Tag Parser",
    "C_Cpp.intelliSenseEngineFallback": "Enabled",
    "C_Cpp.formatting": "Default",
    "C_Cpp.clang_format_formatOnSave": true,
    "C_Cpp.clang_format_sortIncludes": true,
    "C_Cpp.clang_format_fallbackStyle": "{{BasedOnStyle: Google, IndentWidth: 4}}",
    "C_Cpp.clang_format_style": "{BasedOnStyle: Google, IndentWidth: 4}",
    "C_Cpp.navigation.length": 100,
    //setting sync
    // align
    "alignment.operatorPadding": "right"
}

{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include/c++/4.2.1",
                "/usr/include/c++/4.2.1/tr1",
                "/usr/local/include",
                "/usr/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include/c++/4.2.1",
                    "/usr/include/c++/4.2.1/tr1",
                    "/usr/local/include",
                    "/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include",
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
![image](https://user-images.githubusercontent.com/7554917/30772064-45968f64-a01a-11e7-8bdf-1b3ffb473dc1.png)
![image](https://user-images.githubusercontent.com/7554917/30772073-5aeb5c8c-a01a-11e7-8337-fadc3dba48d1.png)

**Comment by sean-mcmanus** [comment] 2017-09-25 13:25
For the Mac configuration, can you change your browse.databaseFilename property to something like `"${workspaceRoot}/.vscode/vc.db"` and see what it's size is? You can also try closing all your VS Code instances, then kill all the Microsoft.VSCode.CPP.* processes (dangling ones accessing the same database can cause failures). Does Go to Definition or hover work for any global variables?

**Comment by Kurt-Shiwz** [comment] 2017-09-25 14:05
vc.db is 18M, it take 15 minutes to get it. after that i also can't find symbol. i just want find symbol in the current file,  how could it happen.... @sean-mcmanus

**Comment by sean-mcmanus** [comment] 2017-09-25 15:46
@Kurt-Shiwz What happens if you create a new file and add some uniquely named variable (int) and do a Go to Symbol in File (@)?

**Comment by Kurt-Shiwz** [comment] 2017-09-26 06:11
Effective, but it take a long ting to tip. when i empty browse.databaseFilename it faster.
And, when I open a new project or file it will take sometime to tip, slower than sublime text. 
I also find when browse.databaseFilename is set,  vc.db will allways clear and rebuild when i reopen the project, even the includepath/browsepath don't change and don't add new files. it take a long time. @sean-mcmanus

**Comment by sean-mcmanus** [comment] 2017-09-26 18:43
What do you mean by "tip"?

@Kurt-Shiwz Thanks a lot for reporting the that the database is clearing -- it's a regression (I suspect with 0.13.0). We should fix that soon. Also, the clearing is occurring even when the databaseFilename is left unchanged (it's just clearing in the default workspaceStorage location).

**Comment by Kurt-Shiwz** [comment] 2017-09-27 13:28
![image](https://user-images.githubusercontent.com/7554917/30915851-9b64085e-a35d-11e7-8f3f-bef4f4b32107.png)
![image](https://user-images.githubusercontent.com/7554917/30915901-b613de40-a35d-11e7-9ab5-c75ed2066b18.png)

it take 2 seconds to show, slower than sublime text

**Comment by sean-mcmanus** [comment] 2017-09-27 18:27
@Kurt-Shiwz Yes, I've noticed that the symbol searching is slow (I've seen a lot longer than 2 seconds). We haven't investigated making that scenario faster yet. The database emptying is primarily due to a VS Code bug that is killing our process before we're able to mark the database as safe to use: https://github.com/Microsoft/vscode/issues/35196 . If you wait for >5 seconds after a database is modified, then the database clearing should not occur (unless we have additional bugs).

**Comment by bobbrow** [comment] 2017-10-05 21:49
A fix for DB clearing has been released in 0.13.1.

**Closed as completed by bobbrow** 2017-10-05 21:49 UTC
Labels: bug, Language Service, fixed
