### ISSUE TITLE
C language 'Go to Definition' recognition function error

### ISSUE THREAD

**Issue by JasonLeeCn** [microsoft/vscode-cpptools#3609] opened 2019-05-08 05:58 UTC
Issue Type: <b>Bug</b>

If the function without parameter, but the function declaration with 'void' in header file.  In other file (not the function entity file) call the function. Using F12 (Go to Definition), the editor will just jump to the header file, not the function entify '*.c' file.

Eg.: 
file1: testA.c
void test_a()
{
    /* function entity*/
}

file2: testA.h
extern void test_a(void);

file3: testB.c
#include "testA.h"

void test_b(void)
{
    test_a();
}

When 'Go to Definition' to test_a();  the editor will jump to testA.h file not testA.c file. But if testA.c is 
void test_a(void)
{
    /* function entity */
}
It can jump to the testA.c file.

Extension version: 0.23.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.66GB (3.48GB free)|
|Process Argv|D:\Workspace\Projects\EB_QL_02\03_Software_Design\Trunk\EB_PMSM|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment] 2019-05-09 02:29
Thanks a lot for reporting this -- we fixed a similar bug a 6 months ago, but we missed this case. It's caused by "void" being missing in the param list of the definition. It should be fixed in our next release.

This particularly issues only repros with .c files (not .cpp).

**Closed as completed** 2019-05-22 07:48 UTC
Labels: bug, Language Service, fixed, quick fix, Feature: Go to Definition

**Comment by sean-mcmanus** [comment] 2019-06-14 23:14
Fixed with 0.24.0-insiders (available by setting "C_Cpp.updateChannel" to "Insiders").
