### ISSUE TITLE
Format macro expansion code

### ISSUE THREAD

**Issue by LasseRosenow** [microsoft/vscode-cpptools#10580] opened 2023-02-23 12:49 UTC
### Feature Request

When hovering a `macro` it gets expanded.
But this expansion is not formatted and thus often very difficult to read.

It would be great, if the resulting code of the macro expansion could be presented in a formatted way on hover.

**Comment by sean-mcmanus** [comment] 2023-02-24 17:06
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/9537 . Please upvote that issue.

![image](https://user-images.githubusercontent.com/19859882/221242281-913b83f6-73bd-49f6-8c5d-0aff1da55915.png)

**Closed as not planned by sean-mcmanus** 2023-02-24 17:06 UTC
Labels: duplicate
