### ISSUE TITLE
[FR] C++ Modules: Support `cppm` files

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cpptools#11369] opened 2023-08-26 21:25 UTC
### Feature Request

`ixx` files seem to be supported but not `cppm`, which are now standard for other compilers.

What files do you actually support?

- `ixx` ?
- `cppp` ?

**Comment by Zingam** [comment] 2023-08-27 05:30
What files do you actually support?

- `ixx` ?
- `cppp` ?

**Comment by H-G-Hristov** [comment] 2023-08-28 13:20
Update: https://cmake.org/cmake/help/v3.27/release/3.27.html#languages

> The CXX language now treats source file extensions .ccm, .cxxm, and .c++m as C++.

**Comment by bobbrow** [comment] 2023-08-28 18:56
We don't officially support modules yet.  #6302 tracks the implementation.  Some features happen to work if you manually build 
and pass the right flags because we inherit the support from VS.  Some of these workarounds are documented in that issue.

I'm going to close this as a duplicate of the main issue though.

**Closed as not planned by bobbrow** 2023-08-28 18:56 UTC
Labels: duplicate, Language Service, modules

**Comment by bobbrow** [comment] 2023-08-30 20:42
If this is just about syntax highlighting, I believe you should be able to get support with the `files.associations` setting.

```jsonc
  "files.associations": {
    "*.cppm": "cpp",
    "*.ccm": "cpp",
    // ...
  }
```

**Comment by Zingam** [comment] 2023-09-02 06:55
> If this is just about syntax highlighting, I believe you should be able to get support with the `files.associations` setting.
> 
> ```js
>   "files.associations": {
>     "*.cppm": "cpp",
>     "*.ccm": "cpp",
>     // ...
>   }
> ```

That's what I do right now.

**Comment by bobbrow** [comment] 2023-09-05 16:35
Perfect.  So if you're just asking for .cppm, etc to be added to the list of supported extensions so that you don't need to explicitly add the files.associations yourself, then I still consider this to be a duplicate feature ask as we will be doing that as part of the modules implementation.
