### ISSUE TITLE
CppDbg Debugger broken ( Version 1.6.0-insiders: August 12, 2021 )

### ISSUE THREAD

**Issue by gokunik** [microsoft/vscode-cpptools#7971] opened 2021-08-13 15:07 UTC
Bug-type: Debugger

**Describe the bug**
- OS and Version: Windows 10 Home
- VS Code Version: 1.59.0
- C/C++ Extension Version:  1.6.0-insiders: August 12, 2021 
- Other extensions you installed (and if the issue persists after disabling them):
  Disabled all other extensions except C/C++ Extension but still the issue persists.
  tried enabling disabling extension but didn't work.

### Bug Details
-- Debugging feature seems to have broken in the recent update. When the debugging process is started, it shows up only for a few seconds and then ends. The program builds successfully but seems like the debugger never starts, the process ends right there, and no output in the debugging console. I even rolled back to the previous version of my code which is working during debugging process in the previous version but still, the same problem persists.  I also tried changing my configs, disabling, and enabling extension but nothing seems to work but if rollback to the previous version of the extension then everything works as expected.

Refer to the below video 👇

https://user-images.githubusercontent.com/57342034/129374367-187c6444-5122-42c5-96b6-840054966f91.mov

**To Reproduce**
- Install the C/C++ Extension Version 1.6.0-insiders: August 12, 2021, to reproduce the issue.
- Start the debugging process

<details>
    <summary> Launch.json file </summary>
        <div> 
            <pre>
                <code>
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": false
                }
            ],
            "preLaunchTask": "C/C++: g++.exe build active file"
        }
    ]
}
                </code>
             </pre>
        </div>
</details>

1.  Recent update must be installed
2.  Starts the debugging process
2.  Terminal fires up and build the file
- Nothing happens after 2 steps, debugging stops. No output in the debugging console and no error.

**Additional context**
- Issue only shows up in the recent update
- Upon re-installing the previous version of the extension, the issue resolves without changing anything else.

**Comment by aayush749** [comment] 2021-08-13 16:05
Yes, I also faced the same issue. It seems there is a problem with the new update.

**Comment by asherhe** [comment] 2021-08-13 16:10
Switching to the last version seemed to fix the problem for me

**Comment by sean-mcmanus** [comment] 2021-08-13 17:32
It's working for me. Is your OS 32-bit or 64-bit?

@aayush749 Are you also using Windows 10?

1.6.0-insiders was changed to run with .NET 5: https://github.com/microsoft/vscode-cpptools/pull/7858

When you run regedit.exe and go to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedhost do you see version 5.0.9? Does updating your .NET version fix it? https://devblogs.microsoft.com/dotnet/net-august-2021/

![image](https://user-images.githubusercontent.com/19859882/129397337-ffb3db0b-2d12-4f83-b6db-9a73e5481915.png)

**Comment by sean-mcmanus** [comment] 2021-08-13 17:40
Ah, it's mingw debugging -- I repro the issue now.

**Comment by WardenGnaw** [comment] 2021-08-13 18:32
The error is:
```
Failed to load the dll from [%USER%\.vscode\extension\debugAdapters\bin\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from %USER%\.vscode\extension\debugAdapters\bin\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
```

This is due to the insiders version of cpptools-win32 shipping the Windows 7 debugger is being used for Windows 10 users.

To resolve this issue for Win 10 users, delete the following files:
1. %USERPROFILE%\.vscode\extensions\ms-vscode.cpptools-1.6.0-insiders\install.lock
2. %USERPROFILE%\.vscode\extensions\ms-vscode.cpptools-1.6.0-insiders\debugAdapters

Then relaunch VS Code and have the extension activate again. 

It will download the correct debugger:
![image](https://user-images.githubusercontent.com/3953714/129403468-1122617c-55e1-4133-b5bd-90ce10ad0295.png)

**Comment by sean-mcmanus** [comment] 2021-08-13 19:02
You could also manually install https://github.com/microsoft/vscode-cpptools/releases/download/1.6.0-insiders/cpptools-win64.vsix (the updateChannel mechanism won't automatically pick that up though until we make a change to that code), and that will also use the 64-bit language service binaries (which we haven't officially released yet).

**Comment by kvelezgh** [comment] 2021-08-13 19:39
Deleting the 
%USERPROFILE%\.vscode\extensions\ms-vscode.cpptools-1.6.0-insiders\install.lock
%USERPROFILE%\.vscode\extensions\ms-vscode.cpptools-1.6.0-insiders\debugAdapters
worked for me. Windows 10

**Comment by TTimo** [comment] 2021-08-13 21:19
@sean-mcmanus when I try to install that .vsix above I get the following error: https://gist.github.com/TTimo/470d2350e0e2cd813f640397fead80c3

**Comment by sean-mcmanus** [comment] 2021-08-13 21:39
@TTimo Common mistake -- you double-clicked the vsix, causing VS to try to install the vsix instead of VS Code. 

The full releases page has the install instructions (https://github.com/microsoft/vscode-cpptools/releases/tag/1.6.0-insiders), i.e. run the "Install from VSIX" command in VS Code.

**Comment by leondhay** [comment] 2021-08-13 22:06
Deleting the
%USERPROFILE%.vscode\extensions\ms-vscode.cpptools-1.6.0-insiders\install.lock
%USERPROFILE%.vscode\extensions\ms-vscode.cpptools-1.6.0-insiders\debugAdapters
worked for me. Windows 10

**Comment by BetterYimi** [comment] 2021-08-14 01:40
me too🤣

**Comment by BetterYimi** [comment] 2021-08-14 01:41
I also encountered the same problem

**Comment by ishanfdo18098** [comment] 2021-08-14 02:13
I also encountered the same problem

**Comment by gokunik** [comment] 2021-08-14 06:11
Ok, the issue is resolved after deleting the mentioned files. 
I am new to reporting the issues. Should I close the issue as my problem is solved? Or it will be closed by the moderators when the issue is fixed?

**Comment by SJ2050cn** [comment] 2021-08-14 07:04
Same problem. I didn't realize my update strategy is insider. Finally I changed my update strategy to default and came back to version 1.5.1. Now, everything works well.

**Comment by gokunik** [comment] 2021-08-14 07:35
> Same problem. I didn't realize my update strategy is insider. Finally I changed my update strategy to default and came back to version 1.5.1. Now, everything works well.

Rollback is one of the options, also the recent insider update works well when the mentioned files are deleted.

**Comment by LetMeFly666** [comment] 2021-08-14 08:02
My friends and I both encountered the problem.

By the way, how to came back to version 1.5.1?

Could anyone help me? Thank you very much!

**Comment by Navjot-13** [comment] 2021-08-14 08:11
> My friends and I both encountered the problem.
> 
> By the way, how to came back to version 1.5.1?
> 
> Could anyone help me? Thank you very much!

Just right click on the extension and click on "Install Another Version".

**Comment by Tisfy** [comment] 2021-08-14 08:15
> My friends and I both encountered the problem.
> 
> By the way, how to came back to version 1.5.1?
> 
> Could anyone help me? Thank you very much!

Same bro. I also want to know how to install a history version.

**Comment by LetMeFly666** [comment] 2021-08-14 08:23
> > My friends and I both encountered the problem.
> > By the way, how to came back to version 1.5.1?
> > Could anyone help me? Thank you very much!
> 
> Just right click on the extension and click on "Install Another Version".

Thank you so much, but I can not find the "Install Another Version".

Is it here? 
![pic](https://user-images.githubusercontent.com/56995506/129439909-5c82b1d3-008b-47ba-af92-c54f9e4d3f99.jpg)

**Comment by ishanfdo18098** [comment] 2021-08-14 08:29
> > > My friends and I both encountered the problem.
> > > By the way, how to came back to version 1.5.1?
> > > Could anyone help me? Thank you very much!
> > 
> > 
> > Just right click on the extension and click on "Install Another Version".
> 
> Thank you so much, but I can not find the "Install Another Version".
> 
> Is it here?
> ![pic](https://user-images.githubusercontent.com/56995506/129439909-5c82b1d3-008b-47ba-af92-c54f9e4d3f99.jpg)

![image](https://user-images.githubusercontent.com/73381996/129440050-15cafed2-a5fa-4136-9d94-0afa316a6915.png)
To change update channel to default:
![image](https://user-images.githubusercontent.com/73381996/129440064-46aa588a-3fd9-4539-bbad-ba8e270e8f7c.png)

**Comment by SJ2050cn** [comment] 2021-08-14 08:39
> > > > My friends and I both encountered the problem.
> > > > By the way, how to came back to version 1.5.1?
> > > > Could anyone help me? Thank you very much!
> > > 
> > > 
> > > Just right click on the extension and click on "Install Another Version".
> > 
> > 
> > Thank you so much, but I can not find the "Install Another Version".
> > Is it here?
> > ![pic](https://user-images.githubusercontent.com/56995506/129439909-5c82b1d3-008b-47ba-af92-c54f9e4d3f99.jpg)
> 
> ![image](https://user-images.githubusercontent.com/73381996/129440050-15cafed2-a5fa-4136-9d94-0afa316a6915.png)
> To change update channel to default:
> ![image](https://user-images.githubusercontent.com/73381996/129440064-46aa588a-3fd9-4539-bbad-ba8e270e8f7c.png)

Try to open c/c++ extension settings and search "update" keyword. Then, turn "Update Channel" to "default", and vscode will roll back to version 1.15.1 automatically(because latest stable vesion is 1.15.1).

![](https://pic.baixiongz.com/uploads/2021/08/14/f2ffe74740885.png)

**Comment by LetMeFly666** [comment] 2021-08-14 08:45
> > > > > My friends and I both encountered the problem.
> > > > > By the way, how to came back to version 1.5.1?
> > > > > Could anyone help me? Thank you very much!
> > > > 
> > > > 
> > > > Just right click on the extension and click on "Install Another Version".
> > > 
> > > 
> > > Thank you so much, but I can not find the "Install Another Version".
> > > Is it here?
> > > ![pic](https://user-images.githubusercontent.com/56995506/129439909-5c82b1d3-008b-47ba-af92-c54f9e4d3f99.jpg)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/73381996/129440050-15cafed2-a5fa-4136-9d94-0afa316a6915.png)
> > To change update channel to default:
> > ![image](https://user-images.githubusercontent.com/73381996/129440064-46aa588a-3fd9-4539-bbad-ba8e270e8f7c.png)
> 
> Try to open c/c++ extension settings and search "update" keyword. Then, turn "Update Channel" to "default", and vscode will roll back to version 1.15.1 automatically(because latest stable vesion is 1.15.1).
> 
> ![](https://camo.githubusercontent.com/9cf730ebbf5004737747f653ece134dee7eceacf49a231e6a6a099610c9570cd/68747470733a2f2f7069632e62616978696f6e677a2e636f6d2f75706c6f6164732f323032312f30382f31342f663266666537343734303838352e706e67)

Thank both of you so much! @ishanfdo18098 @SJ2050cn 
You two let me feel the enthusiasm from all over the world.

**Comment by josedev9** [comment] 2021-08-14 10:48
> The error is:
> 
> ```
> Failed to load the dll from [%USER%\.vscode\extension\debugAdapters\bin\hostfxr.dll], HRESULT: 0x800700C1
> The library hostfxr.dll was found, but loading it from %USER%\.vscode\extension\debugAdapters\bin\hostfxr.dll failed
>   - Installing .NET prerequisites might help resolve this problem.
>      https://go.microsoft.com/fwlink/?linkid=798306
> ```
> 
> This is due to the insiders version of cpptools-win32 shipping the Windows 7 debugger for Windows 10 users.
> 
> To resolve this issue for Win 10 users, delete the following files:
> 
> 1. %USERPROFILE%\.vscode\extensions\ms-vscode.cpptools-1.6.0-insiders\install.lock
> 2. %USERPROFILE%\.vscode\extensions\ms-vscode.cpptools-1.6.0-insiders\debugAdapters
> 
> Then relaunch VS Code and have the extension activate again.
> 
> It will download the correct debugger:
> ![image](https://user-images.githubusercontent.com/3953714/129403468-1122617c-55e1-4133-b5bd-90ce10ad0295.png)

This solution worked perfectly fine with my W10 pc. Thank you so much for the brief answer, was getting kind of annoying to try to come up with the cause of the bug by myself

**Comment by sean-mcmanus** [comment] 2021-08-16 17:13
@gokunik We'll usually close it when a fix is released.

**Comment by Riaz-404** [comment] 2021-08-16 20:22
> The error is:
> 
> ```
> Failed to load the dll from [%USER%\.vscode\extension\debugAdapters\bin\hostfxr.dll], HRESULT: 0x800700C1
> The library hostfxr.dll was found, but loading it from %USER%\.vscode\extension\debugAdapters\bin\hostfxr.dll failed
>   - Installing .NET prerequisites might help resolve this problem.
>      https://go.microsoft.com/fwlink/?linkid=798306
> ```
> 
> This is due to the insiders version of cpptools-win32 shipping the Windows 7 debugger for Windows 10 users.
> 
> To resolve this issue for Win 10 users, delete the following files:
> 
> 1. %USERPROFILE%\.vscode\extensions\ms-vscode.cpptools-1.6.0-insiders\install.lock
> 2. %USERPROFILE%\.vscode\extensions\ms-vscode.cpptools-1.6.0-insiders\debugAdapters
> 
> Then relaunch VS Code and have the extension activate again.
> 
> It will download the correct debugger:
> ![image](https://user-images.githubusercontent.com/3953714/129403468-1122617c-55e1-4133-b5bd-90ce10ad0295.png)

This solves debugging issues. But after completing debug, there creates a file `crtexe.c` file. Is there any way to stop opening it?

**Closed as completed** 2021-08-16 20:28 UTC
Labels: bug, debugger

**Comment by abhi-k9** [comment] 2023-05-23 03:21
I have the same thing happening as the original post by OP.
## VSCode details:
> Version: 1.78.2 (user setup)
> Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
> Date: 2023-05-10T14:39:26.248Z
> Electron: 22.5.2
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.19044
> Sandboxed: N

## launch.json:
```
"configurations": [
        {
            "name": "Debug",
            "type": "cppdbg",
            "request": "launch",
            "externalConsole": false,
            "program": "/home/linux/code/bin/myexe",
            "cwd": "/home/linux/code/bin",
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
            "stopAtEntry": true,
            "environment": [
                { "name": "LD_LIBRARY_PATH", "value": "/home/linux/code/bin" },
                { "name": "PATH", "value": "${env:LD_LIBRARY_PATH}:${env:PATH}" },
                { "name": "DISPLAY", "value": "localhost:10.0" },
            ],
        }
```
## Extension:
C/C++ for Visual Studio Code - Version 1.15.4: May 1, 2023


I'm ssh'ing into a Linux machine. On the integrated terminal, I am able to manually start the debugger on the exe successfully but not via the VSCode task. The next-step-restart-stop bar at the top (see OP's video) pops up for few seconds before vanishing. No output in any of the windows.

I have tried deleting
1. %USERPROFILE%.vscode\extensions\ms-vscode.cpptools-*\install.lock
2. %USERPROFILE%.vscode\extensions\ms-vscode.cpptools-*\debugAdapters
from both the Windows host machine and the Linux machine but that didn't work. Tried using older versions of the extensions too.

Any help would be appreciated. I have no idea where to begin since logs are not being generated.
