### ISSUE TITLE
Intellisense can interpret macro meanwhile displays squiggle saying "identifier undefined"

### ISSUE THREAD

**Issue by rj-leichen** [microsoft/vscode-cpptools#3795] opened 2019-06-18 09:25 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1809
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.24.0-insiders
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Intellisense suddenly displayed squiggles under previously correct macros. When mouse hover on macro, it could display correct value, and clicking would jump to the definition. Reloading the database, renaming the files, deleting .vscode then reset workspace, all wouldn't help. 

**To Reproduce**

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "D:/Documents/header/org_wlan",
                "D:/Documents/header/linux",
                "C:/cygwin64/usr/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "__USE_MISC",
                "CLOCK_MONOTONIC"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Expected behavior**

**Screenshots**
![20190618162119](https://user-images.githubusercontent.com/4439197/59669296-89b28c00-91ec-11e9-92ad-f632235fa7ad.png)

**Additional context**

After editing the files and at save there is error log in OUTPUT:
```
[Error - 下午5:31:56] Connection to server got closed. Server will not be restarted.
[Error - 下午5:31:56] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:2556:25)
	at Object.dispose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:3313:35)
	at LanguageClient.handleConnectionClosed (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:5395:42)
	at LanguageClient.handleConnectionClosed (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:11804:15)
	at closeHandler (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:5382:18)
	at CallbackList.invoke (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7515:39)
	at Emitter.fire (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7573:36)
	at closeHandler (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:1906:26)
	at CallbackList.invoke (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7515:39)
	at Emitter.fire (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7573:36)
	at StreamMessageWriter.fireClose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:10015:27)
	at Socket.module.exports.constructor.writable.on (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:10034:46)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 下午5:31:56] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:2556:25)
	at Object.dispose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:3313:35)
	at LanguageClient.handleConnectionClosed (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:5395:42)
	at LanguageClient.handleConnectionClosed (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:11804:15)
	at closeHandler (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:5382:18)
	at CallbackList.invoke (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7515:39)
	at Emitter.fire (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7573:36)
	at closeHandler (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:1906:26)
	at CallbackList.invoke (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7515:39)
	at Emitter.fire (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7573:36)
	at StreamMessageWriter.fireClose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:10015:27)
	at Socket.module.exports.constructor.writable.on (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:10034:46)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 下午5:31:56] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:2556:25)
	at Object.dispose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:3313:35)
	at LanguageClient.handleConnectionClosed (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:5395:42)
	at LanguageClient.handleConnectionClosed (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:11804:15)
	at closeHandler (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:5382:18)
	at CallbackList.invoke (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7515:39)
	at Emitter.fire (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7573:36)
	at closeHandler (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:1906:26)
	at CallbackList.invoke (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7515:39)
	at Emitter.fire (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7573:36)
	at StreamMessageWriter.fireClose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:10015:27)
	at Socket.module.exports.constructor.writable.on (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:10034:46)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 下午5:31:56] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:2556:25)
	at Object.dispose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:3313:35)
	at LanguageClient.handleConnectionClosed (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:5395:42)
	at LanguageClient.handleConnectionClosed (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:11804:15)
	at closeHandler (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:5382:18)
	at CallbackList.invoke (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7515:39)
	at Emitter.fire (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7573:36)
	at closeHandler (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:1906:26)
	at CallbackList.invoke (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7515:39)
	at Emitter.fire (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:7573:36)
	at StreamMessageWriter.fireClose (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:10015:27)
	at Socket.module.exports.constructor.writable.on (C:\Users\xxxxxx\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:10034:46)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
```
And there is a notification:
```
This file (\\192.168.56.101\share\gerrit\xxxxxx.c) is already opened in the editor but with a different casing. IntelliSense features will be disabled on this copy of the file.
```
However, I'm sure there is only one file opened. The file is within a linux virtual machine and is accessable in Windows via samba, if that helps.

**Comment by sean-mcmanus** [comment] 2019-06-18 18:43
The squiggle is coming from a different system (IntelliSense parsing) than the hover (tag parser), and the systems can use different search paths. Can you run the C/C++: Log Diagnostics command and verify that the info (i.e. include path) shown is sufficient to find the WAIT_TIME_DEF? Is this squiggle issue a regression from 0.23.1?

We're tracking the hover crash with https://github.com/microsoft/vscode-cpptools/issues/3792 . Our current theory is there is some unexpected invalid UTF-8 characters causing the crash.

We're tracking another "already opened" issue with https://github.com/microsoft/vscode-cpptools/issues/3786, but your specific repro sounds like it may be different, i.e. with Windows/Samba (but the file is within a Linux VM, so it could be fixed when we disable that code path for Linux).

Your best immediate workaround for the known Insiders regressions is to switch to C_Cpp.updateChannel "Default" instead of "Insiders" until we're able to release a fix.

**Comment by manas42** [comment] 2019-06-19 03:32
Downgrading to 0.23.1 solved the problem yesterday. I have upgraded to 0.24.0-insiders again but the problem has not been reproduced. Will upload more log if it occurs again.

**Comment by sean-mcmanus** [comment] 2019-06-26 02:18
Crashes and related issue should be fixed with 0.24.0-insiders2. Set the "C_Cpp.updateChannel" setting to "Insiders" to auto-install it. Let us know if you're still having issues.

**Comment by sebirdman** [comment] 2019-06-28 18:40
@sean-mcmanus  i'm still seeing this on 0.24.0-insiders3

```
[Error - 11:37:29 AM] Connection to server got closed. Server will not be restarted.
[Error - 11:37:29 AM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:2556:25)
	at Object.dispose (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:3320:35)
	at LanguageClient.handleConnectionClosed (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:5402:42)
	at LanguageClient.handleConnectionClosed (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:11811:15)
	at closeHandler (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:5389:18)
	at CallbackList.invoke (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:7522:39)
	at Emitter.fire (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:7580:36)
	at closeHandler (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:1906:26)
	at CallbackList.invoke (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:7522:39)
	at Emitter.fire (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:7580:36)
	at StreamMessageReader.fireClose (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:9862:27)
	at Socket.module.exports.listen.readable.on (/home/bird/.vscode-oss/extensions/ms-vscode.cpptools-0.24.0-insiders3/dist/main.js:9902:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
```

**Comment by sean-mcmanus** [comment] 2019-06-28 21:33
0.24.0-insiders3 does appear to have fixed the all the "major" crash regression compared to 0.23.1, so it sounds like you're hitting a different issue. Are you able to get a crash call stack, such as via attaching to the Microsoft.VSCode.Cpp.Extension.linux process? Are you able to identify what action causes the crash (the Connection to server got closed.) or if you can repro it without any files getting opened?

**Comment by michelleangela** [comment] 2020-05-21 18:43
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.

**Closed as completed by michelleangela** 2020-05-21 18:43 UTC
Labels: bug, Language Service, more info needed
