### ISSUE TITLE
C++ syntax highlighting not working properly when constructor initializer list has multiple lines

### ISSUE THREAD

**Issue by veerajskhokale** [microsoft/vscode-cpptools#529] opened 2017-03-04 07:11 UTC
VSCode Version: Code 1.10.1 (653f873, 2017-03-02T00:47:58.633Z)
OS Version: Linux x64 4.4.0-64-generic
Extensions:
Extension	Author	Version
githistory	donjayamanne	0.1.5
vscode-clang	mitaki28	0.2.1
cpptools	ms-vscode	0.10.2
vscode-icons	robertohuertasm	7.3.0
Material-theme	zhuangtongfa	2.1.3
Steps to Reproduce:

Syntax highlighting for keywords like noexcept and delete is not working as shown in the screenshot with the following code:

#include

class Myclass
{
public:
Myclass()
: x(), y(),
z()
{
}

Myclass(const Myclass&) noexcept = delete;
void print() { std::cout << 1 << std::endl; }
private:
int x;
int y;
int z;
};

It is observed that this issue occurs when the constructor initializer list is spread over more than a line.
Issue exists for all themes and when all extensions are disabled as well
Code works and tested with g++
screenshot at 2017-03-03 21 16 41
![image](https://cloud.githubusercontent.com/assets/20010212/23576932/df53de1e-00d7-11e7-90b3-b35d50856566.png)

**Comment by sean-mcmanus** [comment] 2017-03-06 14:30
This is a bug with atom/language-c, which is used to implement all the C/C++ syntax highlighting in VS Code (the C++ extension doesn't implement any colorization). It seems like the root cause is the same as in https://github.com/atom/language-c/issues/101 .

**Comment by Colengms** [comment] 2019-07-03 20:57
This appears to be fixed in VS Code.

**Closed as completed by Colengms** 2019-07-03 20:57 UTC
Labels: bug, Language Service, external
