### ISSUE TITLE
editor.suggest.insertMode = insert partially broken

### ISSUE THREAD

**Issue by Neonit** [microsoft/vscode-cpptools#11101] opened 2023-06-16 08:16 UTC
### Environment

- OS and Version: Windows 10 Pro 22H2 (Windows_NT x64 10.0.19045)
- VS Code Version: 1.79.2
- C/C++ Extension Version: v1.15.4
- If using SSH remote, specify OS of remote machine: –

### Bug Summary and Steps to Reproduce

Bug Summary:
C/C++ seems to ignore the value `insert` for the `editor.suggest.insertMode` setting for some insertions.

Steps to reproduce:
1. Configure `editor.suggest.insertMode` to `insert`. Globally, this is the default. CPP changes the default to `replace`. I set it to `insert` both at user and workspace scope.
2. Create a C++ file, e.g. `foo.cpp`:
	```cpp
	#include <string>

	namespace foo_is_very_long_name {};

	int main()
	{
		std::string banana;
		return 0;
	}
	```
3. Position the cursor e.g. right befor `std`.
4. Type in `foo`, then let suggestions auto-complete to `foo_is_very_long_name `.
5. `std` (or the word you placed the cursor before) gets replaced.

Expected behavior:
`foo_is_very_long_name` gets inserted before `std`. (It works when I disable the C/C++ extension.)

Oddly, it works when I e.g. type `std::`, then insert something from the suggestions. In that case it does not replace, but insert as expected.

### Configuration and Logs

```shell
No `c_cpp_properties.json` present.

C/C++ Log Diagnostics:

-------- Diagnostics - 6/16/2023, 10:09:57 AM
Version: 1.15.4
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "c:\\Users\\Neonit\\Desktop\\insert_mode_bug/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "compilerPath": "cl.exe",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerPathInCppPropertiesJson": "cl.exe",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\Neonit\Desktop\insert_mode_bug\foo.cpp ]:
    C:\Users\Neonit\Desktop\insert_mode_bug\foo.cpp
Translation Unit Configurations:
[ C:\Users\Neonit\Desktop\insert_mode_bug\foo.cpp ]:
    Process ID: 16452
    Memory Usage: 97 MB
    Compiler Path: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe
    Includes:
        C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 97 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 4884
```

**Comment by sean-mcmanus** [comment] 2023-06-16 18:59
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/10613 . You can upvote that issue.

**Closed as not planned by sean-mcmanus** 2023-06-16 18:59 UTC
Labels: duplicate, Feature: Auto-complete

**Comment by Neonit** [comment] 2023-06-17 12:39
Oh man, next time I know to search for closed issues as well. Would've saved everyone some time. It's a bit weird that you break with common vocabulary, just to prevent comments (or what for?).

**Comment by sean-mcmanus** [comment] 2023-06-19 23:08
@Neonit What do you mean by "It's a bit weird that you break with common vocabulary, just to prevent comments"? What "common vocabulary" are you referring to? What comments are being prevented?

**Comment by Neonit** [comment] 2023-06-20 15:30
I assumed comments were disabled on closed issues, but right now I'm learning they are not. I would interpret *closed* as *done* and not *todo* or *not yet taken care of* and got that meaning from common sense.

Now that it's not about the comments, why did you close that issue? It prevens users like me to find it with the default filter enabled, while at the same time you're encouraging users to search first before opening a new issue.

**Comment by bobbrow** [comment] 2023-06-20 16:50
Closed issues do not get locked for comments immediately.  Our bot will lock them after about 6 weeks to provide ample time for rebuttal in case an issue was closed prematurely.  Our bot will also close feature requests that do not have broad community interest.  Our threshold is 3 👍 reactions which is much less than VS Code's threshold of 20.  If a closed issue gets more 👍 our bot will reopen it.

Why do we have our bots enforce this policy?  It's because we have over 1k issues open right now and not nearly enough full-time employees available to work on them all.  Keeping everything open makes it harder for us to filter out the less urgent issues from the more urgent issues (based on community interest).

There is no need to stress about opening a duplicate issue. If we detect it, we'll just point you back to the main one so you can add a 👍 to it.  Searching helps reduce this, but it's not required.  FWIW, GitHub does also show the number of closed issues related to a topic by default when you search, so those results are just a click away.
![image](https://github.com/microsoft/vscode-cpptools/assets/12818240/70fa46ce-e314-41ad-b688-03e494bcbc81)
