### ISSUE TITLE
Rank existence of a configuration higher than filename similarity and path proximity, when choosing a TU source for a header

### ISSUE THREAD

**Issue by 4wrxb** [microsoft/vscode-cpptools#7396] opened 2021-04-20 22:06 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: VSCode Windows on Windows 10
- VS Code Version: 1.55
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: remote-ssh to SLES12
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc). Single folder workspace with compile_commands.json from cmake (run externally)

**Steps to reproduce**
1. In header_a.h include header_a.h
2. In active_file.cpp include header_b.h
3. Include header_a in header_a_test.cpp 
4. Set compile target to compile_commands.json which excludes header_b_test.cpp
5. Open header_a.h

**Expected behavior**
On first open, header_a.h include errors are flagged back to header_a_test.cpp and error squiggles are disabled. Sometimes, after opening active_file.cpp (and sometimes needing to "go to definition" of header_b.h) does Intellisense recognize the path to compile header_a.h and offer error squiggles, but this does not always resolve the issue. This becomes particularly cumbersome when working with header-only libraries that don't have an obviously active cpp file (in our case they're also the most common applications for *test.cpp files).

**Code sample and logs**
- Configurations in `c_cpp_properties.json **attached**

- Code sample and other logging are not straight-forward to provide due to the nature of the project. If this description is unclear I can attempt to reproduce.

**Additional Note**
This workspace is rather large and contains 3 separate build targets under a single /src directory (defines, included libraries/directories, etc. are managed by CMAKE). Having an option to disable/ignore files not covered by compile_commands.json would likely help streamline a lot of other aspects of using c/c++ with our code base. Unfortunately, ignore folders etc. are not helpful here since the ignore set changes depending on the compile target under development.

**Comment by sean-mcmanus** [comment] 2021-04-21 01:07
@Colengms Can you respond to this issue, i.e. is there enough info?

**Comment by Colengms** [comment] 2021-04-21 03:10
Hi @4wrxb .  It's currently 'by design` that a header is resolved to a source file that includes it, and that source is used for processing IntelliSense for that file.  A source file that is already open is preferred.  Depending on what files are open, or the order they were opened in, you may see a header interpreted differently.

The current priority order is:
* Prefer a source file (that includes the header) that is already open.
* Prefer a source file with a name that is similar to the header, if any.  (i.e. For `test.h` it would choose `test.cpp`, if it exists in the workspace).
* Prefer a source file nearer in proximity to the header file than one further away.  That is, if there are sources with more parent directories in common with the header, they are preferred over sources with fewer parent directories in common.
* Prefer a file a custom configuration has been received for (if using a custom configuration provider).
* Prefer a file there is compile commands entry for.
* Use the first source file from a sorted set of sources that include the header.

Can you suggest changes to this approach that might improve the source chosen in your usage scenario?

There's an existing request for a way to choose which source file a header is associated with: https://github.com/microsoft/vscode-cpptools/issues/3960

**Comment by 4wrxb** [comment] 2021-04-21 17:25
Thanks for the response!

So going by your list (I'm reading highest to lowest priority top to bottom) I think this explains why sometimes it works to open an active (in compile_commands) cpp. When the header isn't directly included it usually requires we open a few headers to "walk back" to the header and get the right cpp recognized (which might be by design or due to the size of the project).

For the other items, it looks like we're getting tripped up in a few places.

1) Some of our infrastructure header files are only directly included in one (test) cpp file while "real" use is included through other infrastructure.*
2) This is usually named <header_name>_test.cpp so depending on how loose the name matching is that may apply.
3) These inactive test files also tend to be the only cpp file in the header-only directories so they definitely "win" by proximity
4) Due to the fact that our actual build flow has cmake wrapped in a few other tools we have not managed to enable the cmake tools extension as a custom configuration provider, but since this is lower on the list I'm not sure it would help us.

*These are only used in our google test based compile (which is one of the 3 compiles mentioned).

As to what could resolve this

* The most direct way for our use would be an option to skip/ignore files which are not in compile_commands.json so that <header_name>_test.cpp files aren't candidates.
* Barring that having a per-configuration exclude glob would allow us to set some patterns and handle the most obvious scenarios.^
* An option to select a translation unit would at least make the manual process single-step, as opposed to opening files and hoping the right cpp is recognized.

^I've had some minor success with exclude globs in the config and commenting/uncommenting the json for whichever target is active, but that's not really a work-able solution for most. It's also much trickier with our other two compiles because unlike the <header_file>_test.cpp pattern what is/isn't include is target-needs based and that is really only reliably defined in whether the directory is included in CMakeLists.txt.

**Comment by Colengms** [comment] 2021-04-21 19:56
>The most direct way for our use would be an option to skip/ignore files which are not in compile_commands.json so that <header_name>_test.cpp files aren't candidates.

Perhaps our priority order should be adjusted to rank existence of a configuration (from a provider or compile commands) above name similarity and file proximity.  If you think that should address what you're seeing, we could use this issue to track making that change.

**Comment by Colengms** [comment] 2021-07-09 01:07
I don't think a proper fix for this would be a quick fix.  The current logic is based on custom configs that have already been provided.  It does not attempt to check if a custom config is potentially available, but has not yet been provided.  It would be extremely inefficient to request configs for all source files.  For Unification, we plan to update the custom config provider API to provide all available custom configurations proactively (as EdgeSystem depends on configs being present for operations such as building the include graph).  Without that change, the user would have to open the source file first before we would choose it.  Also, once Unification is done, we will have a different include graph and would likely be able to leverage the same logic that VS uses to choose a source for a header.

**Comment by Colengms** [comment] 2021-08-12 23:49
This should be addressed in 1.6.0-insiders.

**Closed as completed by Colengms** 2021-08-12 23:49 UTC
Labels: bug, Language Service, fixed, Feature: Configuration

**Comment by 4wrxb** [comment] 2021-08-24 19:20
Thanks @Colengms ! I'm talking this for a spin in 1.6.0-insiders3 now and see a big reduction in the time it takes .h files to find its TU (and a lot fewer error squiggles).

I do see issues occasionally, but I can't find a log what translation unit is being used (I have enabled debug logging and am looking at the C/C++ output). Is there somewhere to see this information?

**Comment by sean-mcmanus** [comment] 2021-08-24 19:27
@4wrxb Use the C/C++: Log Diagnostics command (after opening the file and waiting for IntelliSense to finish) to view the TU info. The C/C++ might also have what you're looking for if you search for "sending compilation args".

**Comment by 4wrxb** [comment] 2021-08-24 19:33
Ohh, was not aware of that. Thanks!

It looks like the reason I wasn't seeing the TU in the log (and the source of my unexpected include squiggles) was that it was stuck on an old TU. Changing the configuration caused it to re-evaluate and it quickly picked the right TU after it processed the config.
