### ISSUE TITLE
"Switch Header/Source" action doesn't work correctly in 2 column layout

### ISSUE THREAD

**Issue by ssoher** [microsoft/vscode-cpptools#6492] opened 2020-11-10 21:50 UTC
Issue Type: <b>Bug</b>

In 2 column layout, open the source in one column and it's header in the other column. Make sure the target group has another file open at the time of invoking the action (It works fine if both the source and the header are current open files instead of just tabs in the group). Upon invoking action `Switch Header/Source`, I expect it to focus on the editor in the other column but instead it opens the accompanying header/source in the same editor as a new instance.

1) Works fine if the header/source is open in the other editor
2) Creates new instance in current group if accompanying header/source is not focused in the other editor

This was a general problem with peek reference in VSCode that was fixed last year. https://github.com/microsoft/vscode/issues/85075

Extension version: 1.1.1
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Colengms** [comment] 2020-11-11 23:32
Hi @ssoher .  Thanks for reporting this.  I believe this is a dupe of https://github.com/microsoft/vscode-cpptools/issues/4192 , so closing this as a duplicate.  Please let me know if I'm mistaken.

**Closed as completed** 2020-11-11 23:32 UTC
Labels: duplicate, Language Service, Feature: Switch Header/Source

**Comment by sean-mcmanus** [comment] 2021-01-21 07:58
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2 , but you need to change the setting workbench.editor.revealIfOpen to true.
