### ISSUE TITLE
change "C_Cpp: Clang_format_fallback Style" is fail!

### ISSUE THREAD

**Issue by jsxzhub** [microsoft/vscode-cpptools#5477] opened 2020-05-13 02:50 UTC
version : 0.28.0 
os : windows 10
option of “C_Cpp: Clang_format_fallback Style” can not change.

**Comment by sean-mcmanus** [comment] 2020-05-13 02:55
Can you clarify what you mean?

**Comment by sean-mcmanus** [comment] 2020-05-13 02:59
If you're using a remote session, it should be changeable in the Remote or Workspace or Workspace Folder settings.

![image](https://user-images.githubusercontent.com/19859882/81766476-114f5c00-948b-11ea-8290-581275fab3a9.png)

This is intentional, because your remote machine's instance of clang_format may not accept the same fallbackStyle that your local machine is able to use.

**Comment by sean-mcmanus** [comment] 2020-05-13 03:16
1. Copy your existing settings that are greyed out.
2. File->Preferences->Settings->Remote.
3. Click the Open Settings icon in the top right.
4. Paste the settings.

Are you saying you want a setting that applies to all the different remote machines you use? For that, I recommend filing a feature request at https://github.com/Microsoft/vscode-remote-release/issues .

The change we may was based on recommendations from https://github.com/microsoft/vscode/issues/73985 .

I'm not sure how we would know if the remote settings are acceptable or not.

**Comment by Colengms** [comment] 2020-07-28 02:01
Currently, this is by design.  We changed it due to feedback we received from the VS Code team at #3774 .  Closing this issue.

**Closed as completed by Colengms** 2020-07-28 02:01 UTC
Labels: Language Service, by design, Visual Studio Code, Feature: Code Formatting
