### ISSUE TITLE
Autocompletion does not show detailed document as appear in the official introduction page on Mac M1

### ISSUE THREAD

**Issue by Fred-Wu** [microsoft/vscode-cpptools#9097] opened 2022-03-27 12:18 UTC
The official introduction page of [Clang on macOS](https://code.visualstudio.com/docs/cpp/config-clang-mac) describes that IntelliSense is able to show detailed document of a member function

![image](https://user-images.githubusercontent.com/4111978/160280851-b2ff7a97-ea7f-43fa-96e6-7d3922acf1d1.png)

However, I only can see minimal information

<img width="927" alt="image" src="https://user-images.githubusercontent.com/4111978/160280876-7ee4dfbc-b123-4679-8d4c-d4bcc5e3eacb.png">

I have tried various options in the configuration file, but none of them appears to work. 

Is this a known issue for M1?

**Comment by sean-mcmanus** [comment] 2022-03-28 18:39
Yes, this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/9063 -- it's caused by the Mac M1 clang compiler having a seemingly incorrect default -std version set to C++97 -- you should be able to workaround it by explicitly setting the cppStandard to a higher value.

**Closed as completed** 2022-03-29 16:07 UTC
Labels: duplicate
