### ISSUE TITLE
Struct sigaction (signal.h) and DT_REG/DT_DIR/DT_LNK (dirent.h) not recognized by C/C++ extension

### ISSUE THREAD

**Issue by kiko-g** [microsoft/vscode-cpptools#5262] opened 2020-04-07 19:32 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: **Ubuntu 19.04** (Plasma KDE)
- VS Code Version: **1.43.2**
- C/C++ Extension Version: **0.27.0**
- Other extensions you installed (and if the issue persists after disabling them): 

![image](https://user-images.githubusercontent.com/40745490/78697030-1b17f980-78f8-11ea-9e8e-d85da0b7b686.png)

- Does this issue involve using SSH remote to run the extension on a remote machine?: **No**
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc):

**Screenshots**:

**Sigaction**:
![image](https://user-images.githubusercontent.com/40745490/78692462-dd17d700-78f1-11ea-81d3-c5e23344ed23.png)

**DT Flags**:
![image](https://user-images.githubusercontent.com/40745490/78704836-6e904480-7904-11ea-9a0e-4a8464ccff37.png)

**Expected behavior**

I simply expect these types and identifiers to be recognized by VS Code. Struct sigaction is defined in signal.h and DT_DIR (and others) is defined in dirent.h

<details>
  <summary><strong>Logs</strong></summary>

```
identifier "DT_REG" is undefined
incomplete type is not allowed
```
</details>

**Comment by sean-mcmanus** [comment] 2020-04-07 20:40
This is caused by our lack of support for gnu std values (https://github.com/microsoft/vscode-cpptools/issues/2782 ). You should be able to workaround it via setting `_GNU_SOURCE` in your defines. See the previous thread at https://github.com/microsoft/vscode-cpptools/issues/2903 .

**Comment by bobbrow** [comment] 2020-04-09 21:11
Closing as duplicate.

**Closed as completed by bobbrow** 2020-04-09 21:11 UTC
Labels: bug, duplicate, Language Service
