### ISSUE TITLE
Order of the include would affect the result of intellisense.

### ISSUE THREAD

**Issue by caacyzp** [microsoft/vscode-cpptools#8633] opened 2022-01-05 05:56 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Win11 Version	10.0.22000 Build 22000
- VS Code Version: 1.63.2
- C/C++ Extension Version: v1.8.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): 
1. Better C++ Syntax. 2. CMAKE 3. CMAKE Tools 4. Docker 5. Hex Editor 6. Jupter 7. Jupter Keymap 8. Jupter Notebook Renderers 9. Pylance 10. Python 11. Syntax Hightlighting Theme. (Issue persists after only left C/C++ extention enabled)
- If using SSH remote, specify OS of remote machine: No

The order of writing header including statement would make intellisense report non-exist error. 

I have two .h files and two .cpp files in the same project folder like following：
-XpCppClient
  -drefdecoder.h
  -drefdecoder.cpp
  -xpclient.h
  -xpclient.cpp

among those, the drefdecoder.h is included in the xpclient.h, while, I found out that if I don't include the drefdecoder.h as the first include statement within the xpclient.h, this would result the intellisense report error within the drefdecoder.h. Even the build and run works smooth, the error is annoying.

**Expected behavior**
No error should be reported?

<img width="650" alt="2022-01-05 (4)" src="https://user-images.githubusercontent.com/60253671/148166588-19962085-75c6-43e8-9e69-e06639a9c0da.png">
Include the drefdeocder.h at the fifth line of the xpclient.h will result drefdecoder.h report namespace nlohmann as no memeber json like below (Go to definition works fine).
<img width="643" alt="2022-01-05 (7)" src="https://user-images.githubusercontent.com/60253671/148166591-10a8347a-d37a-46cc-820a-6135987add45.png">

if i then move the "#include drefdecoder.h" as the first include stament. All error then removed
<img width="659" alt="2022-01-05 (10)" src="https://user-images.githubusercontent.com/60253671/148167322-3dbd60d3-1171-4034-b540-c97d7b7c9597.png">

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
--------- Diagnostics - 1/5/2022, 1:47:20 PM
Version: 1.8.0-insiders2
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "cStandard": "c17",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "cppStandard": "c++11",
    "intelliSenseMode": "gcc-x64",
    "mergeConfigurations": true,
    "compilerPath": "C:\\msys64\\mingw64\\bin\\g++.exe",
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "${workspaceFolder}"
        ]
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "c:/users/zepu.yan/desktop/xplaneconnectcpp"
    ],
    "compilerPath": "c:/msys64/mingw64/bin/x86_64-w64-mingw32-g++.exe",
    "compilerArgs": [
        "-g"
    ]
}
Custom configurations:
[ C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.cpp ]
{
    "defines": [
        "FMT_LOCALE",
        "SPDLOG_COMPILED_LIB",
        "SPDLOG_FMT_EXTERNAL",
        "SPDLOG_SHARED_LIB",
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "includePath": [
        "c:/users/zepu.yan/desktop/xplaneconnectcpp",
        "${workspaceFolder}/**",
        "${workspaceFolder}"
    ],
    "compilerPath": "c:/msys64/mingw64/bin/x86_64-w64-mingw32-g++.exe",
    "compilerArgs": [
        "-g"
    ],
    "forcedInclude": []
}
Translation Unit Mappings:
[ C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.cpp ]:
    C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h *
    C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\drefdecoder.h *
    C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.cpp
Translation Unit Configurations:
[ C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.cpp ]:
    Process ID: 1884
    Memory Usage: 224 MB
    Compiler Path: c:/msys64/mingw64/bin/x86_64-w64-mingw32-g++.exe
    Includes:
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP
        C:\MSYS64\MINGW64\INCLUDE\C++\10.3.0
        C:\MSYS64\MINGW64\INCLUDE\C++\10.3.0\X86_64-W64-MINGW32
        C:\MSYS64\MINGW64\INCLUDE\C++\10.3.0\BACKWARD
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.3.0\INCLUDE
        C:\MSYS64\MINGW64\INCLUDE
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.3.0\INCLUDE-FIXED
        C:\MSYS64\MINGW64\X86_64-W64-MINGW32\INCLUDE
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD\CMAKEFILES
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\CMAKE-BUILD-DEBUG
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\CMAKE-BUILD-DEBUG\.CMAKE
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\CMAKE-BUILD-DEBUG\.CMAKE\API
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\CMAKE-BUILD-DEBUG\.CMAKE\API\V1
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\CMAKE-BUILD-DEBUG\.CMAKE\API\V1\QUERY
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD\.CMAKE\API\V1\REPLY
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD\.CMAKE\API\V1
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD\.CMAKE\API
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD\.CMAKE
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD\CMAKEFILES\PROGRESS
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD\CMAKEFILES\XPCLIENT.DIR
    Defines:
        FMT_LOCALE
        SPDLOG_COMPILED_LIB
        SPDLOG_FMT_EXTERNAL
        SPDLOG_SHARED_LIB
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++14
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=100300
        --ms_extensions
Total Memory Usage: 224 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 22194

- Logs from [the language server logging]loggingLevel: Debug
loggingLevel has changed to: Debug
cpptools/didChangeCppProperties
$/setTraceNotification
cpptools/getCodeActions: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\drefdecoder.h (id: 1391)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\drefdecoder.h (id: 1392)
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\drefdecoder.h
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\drefdecoder.h (id: 1393)
textDocument/hover: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\drefdecoder.h (id: 1394)
textDocument/hover: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\drefdecoder.h (id: 1395)
cpptools/getCodeActions: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1396)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1397)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
cpptools/activeDocumentChange: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
cpptools/getFoldingRanges: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1398)
cpptools/getCodeActions: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1399)
idle loop: reparsing the active document
Checking for syntax errors: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
Queueing IntelliSense update for files in translation unit of: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Error squiggle count: 0
Error squiggle count: 0
Update IntelliSense time (sec): 0.283
cpptools/getFoldingRanges: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1400)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1401)
textDocument/didChange: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1402)
cpptools/getCodeActions: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1403)
cpptools/getSemanticTokens: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1404)
cpptools/getDocumentSymbols: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1405)
cpptools/getDocumentSymbols
Checking for syntax errors: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
  tag parsing file: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
Queueing IntelliSense update for files in translation unit of: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.cpp
textDocument/hover: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1406)
sending 1 changes to server
cpptools/textEditorSelectionChange
cpptools/getCodeActions: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1407)
textDocument/didChange: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1408)
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Error squiggle count: 0
textDocument/didChange: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
Queueing IntelliSense update for files in translation unit of: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.cpp
cpptools/getFoldingRanges: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1409)
willSaveWaitUntil: 0ms
textDocument/didSave: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
cpptools/fileChanged: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
cpptools/getDocumentSymbols: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1411)
cpptools/getDocumentSymbols
sending 1 changes to server
sending 1 changes to server
  tag parsing file: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
idle loop: reparsing the active document
Checking for syntax errors: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h
Queueing IntelliSense update for files in translation unit of: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 1
Error squiggle count: 2
Error squiggle count: 12
Update IntelliSense time (sec): 3.416
cpptools/getSemanticTokens: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1412)
cpptools/getFoldingRanges: C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\xpclient.h (id: 1413)

**Screenshots**

**Comment by caacyzp** [comment] 2022-01-05 08:59
Looks roll the extentions back to V1.7.1 fixed the issue.
-------- Diagnostics - 1/5/2022, 4:58:51 PM
Version: 1.7.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "cStandard": "c11",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "cppStandard": "c++11",
    "intelliSenseMode": "windows-gcc-x64",
    "mergeConfigurations": true,
    "compilerPath": "C:\\msys64\\mingw64\\bin\\g++.exe",
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "${workspaceFolder}"
        ]
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "c:/users/zepu.yan/desktop/xplaneconnectcpp"
    ],
    "standard": "gnu++11",
    "compilerPath": "c:/msys64/mingw64/bin/x86_64-w64-mingw32-g++.exe",
    "compilerArgs": [
        "-g",
        "-std=gnu++11"
    ]
}
Custom configurations:
[ C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\main.cpp ]
{
    "defines": [
        "FMT_LOCALE",
        "SPDLOG_COMPILED_LIB",
        "SPDLOG_FMT_EXTERNAL",
        "SPDLOG_SHARED_LIB",
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "standard": "gnu++11",
    "includePath": [
        "c:/users/zepu.yan/desktop/xplaneconnectcpp",
        "${workspaceFolder}/**",
        "${workspaceFolder}"
    ],
    "compilerPath": "c:/msys64/mingw64/bin/x86_64-w64-mingw32-g++.exe",
    "compilerArgs": [
        "-g",
        "-std=gnu++11"
    ],
    "forcedInclude": []
}
Translation Unit Mappings:
[ C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\main.cpp ]:
    C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\MAIN.CPP
    C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\XPCLIENT.H
    C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\DREFDECODER.H
Translation Unit Configurations:
[ C:\Users\Zepu.Yan\Desktop\XplaneConnectCpp\main.cpp ]:
    Process ID: 4472
    Memory Usage: 212 MB
    Compiler Path: c:/msys64/mingw64/bin/x86_64-w64-mingw32-g++.exe
    Includes:
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP
        C:\MSYS64\MINGW64\INCLUDE\C++\10.3.0
        C:\MSYS64\MINGW64\INCLUDE\C++\10.3.0\X86_64-W64-MINGW32
        C:\MSYS64\MINGW64\INCLUDE\C++\10.3.0\BACKWARD
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.3.0\INCLUDE
        C:\MSYS64\MINGW64\INCLUDE
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.3.0\INCLUDE-FIXED
        C:\MSYS64\MINGW64\X86_64-W64-MINGW32\INCLUDE
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD\CMAKEFILES
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\CMAKE-BUILD-DEBUG
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\CMAKE-BUILD-DEBUG\.CMAKE
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\CMAKE-BUILD-DEBUG\.CMAKE\API
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\CMAKE-BUILD-DEBUG\.CMAKE\API\V1
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\CMAKE-BUILD-DEBUG\.CMAKE\API\V1\QUERY
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD\CMAKEFILES\PROGRESS
        C:\USERS\ZEPU.YAN\DESKTOP\XPLANECONNECTCPP\BUILD\CMAKEFILES\XPCLIENT.DIR
    Defines:
        FMT_LOCALE
        SPDLOG_COMPILED_LIB
        SPDLOG_FMT_EXTERNAL
        SPDLOG_SHARED_LIB
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++11
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=100300
Total Memory Usage: 212 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 22206

**Comment by bobbrow** [comment] 2022-01-05 15:54
If rolling back to 1.7.1 fixes the issue, I believe this is a duplicate of #8581 which will be fixed in 1.8.0-insiders3.

**Closed as completed by bobbrow** 2022-01-05 15:54 UTC
Labels: bug, duplicate, Language Service, fixed

**Comment by sean-mcmanus** [comment] 2022-01-05 20:08
Well, it's a duplicate of https://github.com/microsoft/vscode-cpptools/issues/8487, but the root cause is the same issue with -fms-extensions that got added.

**Comment by sean-mcmanus** [comment] 2022-01-19 19:33
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).

Unless you're explicitly adding -fms-extensions, in which case that bug fix is still pending (https://github.com/microsoft/vscode-cpptools/issues/8353 ).
