### ISSUE TITLE
Intellisense showing error on an empty define

### ISSUE THREAD

**Issue by selassje** [microsoft/vscode-cpptools#7057] opened 2021-02-26 13:19 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Wind10
- VS Code Version: 1.53.2
- C/C++ Extension Version: v1.2.2
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Intellisense complaining about an empty define:

![image](https://user-images.githubusercontent.com/42682959/109305156-9a2e5d00-783d-11eb-8104-58630390b01c.png)

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment] 2021-02-26 18:20
It doesn't repro for me. Do you repro it with a simple example or do you know what is triggering it?

![image](https://user-images.githubusercontent.com/19859882/109339009-dd77d400-781b-11eb-96aa-165a994021a1.png)

Does the definition exist in other headers or is there an `#undef` in one of the header files?

**Comment by selassje** [comment] 2021-02-27 03:06
I have a rather hefty number of headers included in this translation unit. The definition does exist as I can jump to it via F12.  It seems "Problems" output got somehow desynced with the rest of the IntelliSense for this particular definition, 
The number of headers makes an impact as reducing it solves the issue.

**Comment by sean-mcmanus** [comment] 2021-02-27 04:29
Using F12 may be locating the definition via our tag parser (which parses symbols differently). It is most likely a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6580 . Another alternative to investigate further is to process your TU to a single file via something like `<compiler> -Wp,-v -E -std=<version> <other compiler args> /dev/null > test.out.cpp` and seeing if you see squiggle errors in the headers that could breaking our IntelliSense parsing before it gets to the definition.

**Closed as completed** 2021-04-28 11:18 UTC
Labels: Language Service, more info needed, not reproing
