### ISSUE TITLE
IntelliSense doesn't define _DEBUG when /MDd or /MTd is used

### ISSUE THREAD

**Issue by Toizi** [microsoft/vscode-cpptools#6690] opened 2020-12-20 21:43 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version: 1.52.1
- C/C++ Extension Version: v1.1.3
- `_DEBUG` is not defined for Intellisense even though the `compile_commands.json` specifies `/MDd` and list of defines contains `_DEBUG`

**Steps to reproduce**

0. Make sure you have Ninja and CMake installed
1. Download and extract [compile_commands_cpp_config.zip](https://github.com/microsoft/vscode-cpptools/files/5721556/compile_commands_cpp_config.zip)
2. From the directory of the sample, call `build.bat` from a developer command prompt. This will create a `cmake_compile_commands.json` in the `build` directory and run the executable that has been created with the output `_DEBUG = 0`
3. Open `test.cpp` to see that the `#ifdef _DEBUG` branch is faded out to signal that it is inactive

**Expected behavior**

`_DEBUG` should be defined since the command line specified in the `compile_commands.json` contains `/MDd` as per [documentation][1].

Additionally, it raises the question of how `defines` specified in `c_cpp_properties.json` should be handled whenever a `compile_commands.json` is specified as well. As it is right now, it seems that `defines` are not taken into account since the sample `defines` list also contains `_DEBUG`

**Screenshots**

![_DEBUG_issue](https://user-images.githubusercontent.com/3457016/102724826-bdef9700-4312-11eb-9858-b2620ea43416.png)

[1]: https://docs.microsoft.com/en-us/cpp/c-runtime-library/debug?view=msvc-160

**Comment by sean-mcmanus** [comment] 2020-12-21 23:44
This is "by design" -- /MDd doesn't define _DEBUG and when you're using compileCommands it ignores the "defines" section. Can you add a /D_DEBUG to the compile_commands?

**Comment by Toizi** [comment] 2020-12-22 07:48
Alright, good to know that the this is the expected behavior regarding the `defines` being ignored for `compile_command.json`.

I am not sure what you mean by "/MDd doesn't define _DEBUG" though when the sample demonstrates the opposite and the link to the documentation I provided as well:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/debug?view=msvc-160

To test this for yourself, try compiling and running the following code
```
#include <iostream>

int main(int argc, char const *argv[])
{
    std::cout << "_DEBUG "
#ifdef _DEBUG
        << "is defined"
#else
        << "is not defined"
#endif
        << std::endl;
    return 0;
}
```
Once with just `cl.exe /MD test.cpp` and once with `cl.exe /MDd test.cpp`. I also tested this with `clang-cl` and it behaves like the msvc compiler in this regard.

When explicitly adding `/D_DEBUG` it works as expected but I don't feel like modifying compiler flags to get documented behavior is the correct solution.

**Comment by sean-mcmanus** [comment] 2020-12-22 16:56
Ah, okay -- our extension doesn't currently process the /MDd compiler arg, so IntelliSense won't have the _DEBUG defined. Thanks for reporting this.

**Comment by sean-mcmanus** [comment] 2021-01-21 08:34
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2

**Closed as completed** 2021-02-03 00:45 UTC
Labels: bug, Language Service, fixed, quick fix, Feature: Configuration
