### ISSUE TITLE
cpptools does not ask the configuration provider for the configuration of headers files

### ISSUE THREAD

**Issue by Mossop** [microsoft/vscode-cpptools#3985] opened 2019-07-26 18:21 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: OSX 10.14.5
- VS Code Version: 1.37.0-insider Commit: 6d82826e990407364d5c829b73602a19ecdf7d00

- C/C++ Extension Version: 0.24.1
- Other extensions you installed (and if the issue persists after disabling them): https://github.com/FractalBrew/vscode-mozillacpp
- A clear and concise description of what the bug is.

I have registered a custom configuration and it is correctly servicing requests for the configuration for .cpp files. However when I have a header file open I see no requests for the configuration for the header file and then the notification appears:

```
'Mozilla' is unable to provide IntelliSense configuration information for '/Users/dave/mozilla/source/trunk/dom/events/KeyEventHandler.h'. Settings from the 'Mac' configuration will be used instead.
```

**To Reproduce**

1. Have a source tree for Firefox built (sorry)
2. Install the referenced extension and select it as the configuration provider.
3. Set the extension's log level to "always" in settings.
4. Open a header file.
5. See error notification

**Expected behavior**
Expected to see the configuration provider called to ask for configuration for the header file.

**Screenshots**

**Additional context**

**Comment by bobbrow** [comment] 2019-07-26 20:40
Since many providers were unable to provide configs for headers, we decided to try to find the matching .cpp file and query your provider for that instead.  If your extension is capable of providing configs for headers, we could consider adding an API to disable this logic in cpptools.

I'm not exactly sure whether this is just a bug and a bad error message though. My suspicion is that cpptools **thinks** that some foo.cpp includes KeyEventHandler.h and when it asks you for the config for foo.cpp, your extension says it doesn't have a config for that.

**Comment by Mossop** [comment] 2019-07-26 20:52
Ah ok. I think what is actually going on is that cpptools is failing to find a cpp file for the header.

If I open vscode, clear the intellisense database and then open KeyEventHandler.h then the error notification is immediately shown, my configuration provider receives no request for configuration for any files.

If I open vscode, clear the intellisense database, open KeyEventHandler.cpp and let it finish parsing that then when I open KeyEventHandler.h then no error is shown and intellisense seems to work. Perhaps worth noting that my configuration provider doesn't receive any additional request for configuration for any files after the initial one for KeyEventHandler.cpp, presumably because it is cached at this point.

**Comment by bobbrow** [comment] 2019-08-08 17:42
> If I open vscode, clear the intellisense database and then open KeyEventHandler.h then the error notification is immediately shown, my configuration provider receives no request for configuration for any files.

In this case, are you able to see which cpp file cpptools is selecting for IntelliSense?  [Enabling Logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp) will help answer this question.  Is the cpp we select a reasonable choice, or does that cpp not actually include the header in question? We plan to spend some more time on this logic in the future, including adding a better ranking system, because right now there are cases where files with the same name (even though they seem like the most obvious choice) might not be selected.

> If I open vscode, clear the intellisense database, open KeyEventHandler.cpp and let it finish parsing that then when I open KeyEventHandler.h then no error is shown and intellisense seems to work. Perhaps worth noting that my configuration provider doesn't receive any additional request for configuration for any files after the initial one for KeyEventHandler.cpp, presumably because it is cached at this point.

Correct. This is the expected behavior.  If a cpp file includes an h file, we share the language server between the two files when both are open in the editor. And once your provider gives us the configuration we assume that it doesn't change unless you call `didChangeCustomConfiguration`, so we cache the result for the rest of the session.

**Comment by Mossop** [comment] 2019-08-09 02:12
> > If I open vscode, clear the intellisense database and then open KeyEventHandler.h then the error notification is immediately shown, my configuration provider receives no request for configuration for any files.
> 
> In this case, are you able to see which cpp file cpptools is selecting for IntelliSense? [Enabling Logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp) will help answer this question.

I don't see it selecting any cpp file and as I said my configuration provider is never asked for any configuration so even if it is selecting a cpp file it cannot be using the correct configuration for it.

Here are the C++ output log and the LSP logs: https://gist.github.com/Mossop/4ce5bdbb056468dd4aa7f5472c01cbb9

**Comment by bobbrow** [comment] 2019-08-09 04:05
Interesting.  It's not picking a cpp file for some reason.  It could be because the file indexing is incomplete.  I saw a lot of "tag parsing file" messages in your log so we might not have identified a cpp file that includes it yet.  But I would have expected cpptools to ask your extension for the configuration in that case.  In the log it looks like some sort of configuration was provided though.  Do you have an `includePath` set in your `c_cpp_properties.json` file?  Cpptools will resort to that if the custom config provider does not provide a configuration.

I had a clone of mozilla on my MacBook at one point while investigating another issue, but it seems to have been deleted at some point and I'll need to start over.  Is there a specific folder you're opening?

**Comment by Mossop** [comment] 2019-08-12 18:08
Ah ok, looks like this is only an issue when tag parsing is not yet complete. It picks a reasonable cpp file in this case. I wonder if it should just not return any results until tag parsing is complete and the correct configuration is returned.

**Comment by bobbrow** [comment] 2019-08-12 18:23
We can't wait until tag parsing is complete because in many cases this can take a really long time.  It feels like there is a bug here though if your extension is not being asked to provide a configuration for the header file in the case where we didn't discover a cpp file that includes it yet.

**Comment by sean-mcmanus** [comment] 2019-08-22 01:45
@bobbrow Any status on this? Did it get fixed for 0.25.0 with the V3 API? Should it be moved to 0.26.0 or On Deck?

**Comment by bobbrow** [comment] 2019-08-22 16:22
I haven't had a chance to set up a repro for this yet.  I may ask @Colengms to take a look when he spends some more time on the header/source matching logic.

**Comment by Colengms** [comment] 2019-09-24 20:47
I think the issue here is that we're not waiting for the initial custom configuration from the config provider.  Currently, we kick off tag parsing, etc., right away, and need to restart them when the custom configuration becomes available.  If a header is opened before getting the configuration, and is outside of (default, non-custom config) browse paths, we consider it a system include.  We don't ask for configurations for system includes.

I think the right solution would be to wait for the custom configuration provider, initially.  There was concern that the config may never be delivered, and we might fail to start up.  I propose we do wait, but display an error message after a timeout indicating which custom configuration provider is not responding.

Sean mentioned seeing some issues with Find All References due to the initial tag parsing without the custom config, as that writes potentially incorrect data to the DB.  Waiting for the initial config should address that as well.

**Comment by sean-mcmanus** [comment] 2019-09-24 21:32
Yeah, that sounds good.

**Comment by Colengms** [comment] 2019-12-03 19:16
I believe this has been addressed by: https://github.com/microsoft/vscode-cpptools/pull/4671  (Moreso a corresponding change in the native process).  This issue is that when a file is already opened at launch, and we create a TU for it before the config provider is registered, we fail to update that TU when the provider becomes available.  We were also failing to reconfigured TU properly after a custom configuration provider sent us an updated configuration for a file we had already created a TU for.

**Comment by Mossop** [comment] 2019-12-04 15:59
Great, this sounds like it may have fixed some other oddities I was seeing. When might this release be available for testing?

**Comment by sean-mcmanus** [comment] 2019-12-06 01:46
We're hoping to release 0.26.3-insiders some day next week (maybe Thursday evening?). 0.26.3 non-insiders won't be till some time in January.

**Comment by Mossop** [comment] 2020-01-03 22:50
This looks fixed to me, thanks!

**Closed as completed** 2020-01-22 22:22 UTC
Labels: Language Service, Feature Request, fixed, Feature: Extension API
