### ISSUE TITLE
Can't compile cpp file with clang

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/vscode-cpptools#10533] opened 2023-02-16 09:00 UTC
### Environment

- OS and version: Windows 10 21H2
- VS Code: 1.75.1
- C/C++ extension: v1.14.3
- llvm version: 15.0.7

### Bug Summary and Steps to Reproduce

Bug Summary:

I can't run cpp file with clang++
this is my code:
```c
#include<iostream>
#include<string>

using namespace std;

int main(void) {

    cout<<"hello!"<<endl;

    return 0;
}
```
![image](https://user-images.githubusercontent.com/82581024/219316789-8394a391-bd93-4018-8068-5d864c888caa.png)

vscode will waiting for a very long time, and don't have any response.

### Debugger Configurations

```shell
// tasks.json:
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: clang++.exe 生成活动文件",
            "command": "D:\\Program Files\\LLVM\\bin\\clang++.exe",
            "args": [
                "-fcolor-diagnostics",
                "-fansi-escape-codes",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "调试器生成的任务。"
        }
    ],
    "version": "2.0.0"
}
```

### Debugger Logs

```shell
// Don't have log.
```

**Comment by sean-mcmanus** [comment] 2023-02-16 20:53
It's compiling, but it looks like C:\\Program Files\\LLVM\\bin\\lldb.exe is getting stuck for some reason.

**Comment by WardenGnaw** [comment] 2023-02-16 21:34
Duplicate of #10491

**Closed as not planned by WardenGnaw** 2023-02-16 21:34 UTC
Labels: bug, debugger, verified
