### ISSUE TITLE
Incorrect exit code reported in debug console for C program

### ISSUE THREAD

**Issue by thierryseegers** [microsoft/vscode-cpptools#6663] opened 2020-12-14 16:22 UTC
Issue Type: <b>Bug</b>

When debugging a C or C++ program, should the program return a non-zero exit code (e.g. `EXIT_FAILURE`), I expected that that code be reported at the end of execution in the debug console. It appears that it always reports `0` regardless of the actual exit code returned. Like so : 

```
The program '/[redacted]/a.out' has exited with code 0 (0x00000000).
```
Here is the contents of the `configurations` element in `launch.json` :

```
"configurations": [
        {
            "name": "test",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "cwd": "${workspaceFolder}",
            "environment": [],
            "stopAtEntry": true,
            "logging": {
                "moduleLoad": false
            },
            "osx": {
                "MIMode": "lldb",
            },
            "miDebuggerArgs": "--quiet",
            "targetArchitecture": "x64",
            "preLaunchTask": "compilation"
        }
    ]
```

Note that `Xcode` is not installed, only its command line tools.

(If I had to take stab in the dark, I would guess that that error code is that of the actual debugger program (i.e. `lldb`) rather than the program being debugged.)

Extension version: 1.1.3
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|. --crash-reporter-id fc13e4db-e56f-444c-9148-edc01d0f1514|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
vsjup459cf:30229594

```

</details>

**Comment by WardenGnaw** [comment] 2020-12-14 20:12
Thank you for reporting this issue. This is a duplicate of: https://github.com/microsoft/vscode-cpptools/issues/487

Additional notes: 
This is an issue specifically when debugging using lldb as the miDebugger.

**Closed as completed by WardenGnaw** 2020-12-14 20:12 UTC
Labels: duplicate, debugger
