### ISSUE TITLE
Debugger: Cannot be hit after modifying conditional breakpoint

### ISSUE THREAD

**Issue by GraceDong** [microsoft/vscode-cpptools#2672] opened 2018-10-15 07:39 UTC
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Ubuntu 16.04
- VS Code Version: 1.28.0
- C/C++ Extension Version: 0.19.1-master
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Add the following code to the source file
```
#include "iostream"
using namespace std;

int FuncTest(int i)
{
    int j=0;   //set breakpoint
    if(i==0)
    {
        return 0;
    }
    else
    {
        return FuncTest(i-1);
    }
}

int main()
{
    FuncTest(100);
    return 0;
}
```

2. Add condition breakpoint at line of 6, such as "i==50" 
3. F5 (gdb launch) and wait for break mode
4. Modify the conditional expression to "i==40" and continue

**Expect behaver**
Conditional breakpoint should be hit.

**Actual behaver**
Didn't hit the conditional breakpoint and the program exited.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.
[Launch.txt](https://github.com/Microsoft/vscode-cpptools/files/2477790/Launch.txt)
[main.cpp.txt](https://github.com/Microsoft/vscode-cpptools/files/2477792/main.cpp.txt)
[log.txt](https://github.com/Microsoft/vscode-cpptools/files/2477774/log.txt)

**Comment by zhangmn799** [comment] 2018-10-15 09:09
This issue also repro in Mac machine.

**Environment data**
VS Code version:1.28.0
C++ Extension version: 0.19.1-master
Debugger: lldb
OS: macOS Sierra/10.12.6

**Comment by pieandcakes** [comment] 2018-10-16 17:36
@zhangmn799 @GraceDong Thank you for reporting this. This isn't an issue with the changes but it is an issue with how VS Code changed breakpoint updating.

**Comment by pieandcakes** [comment] 2018-10-16 17:37
Duplicate of #2297

**Closed as completed by pieandcakes** 2018-10-16 17:37 UTC
Labels: duplicate, debugger
