### ISSUE TITLE
C/C++ invalid macro definitions with V1.9.7 and newer

### ISSUE THREAD

**Issue by JulianMaV** [microsoft/vscode-cpptools#9435] opened 2022-06-13 08:30 UTC
Bug Summary: 
I use a self-created microcontroller board based on a Renesas controller and the IAR development environment. With the IAR extension for VS Code, it is possible that Intellisense can properly connect all paths, defines, types, etc. and everything works nicely. As of extention version 1.9.7 of C/C++, a command line error is always displayed that a macro definition is invalid, although this is not the case! If you jump back to version 1.8.4 everything is ok.

Steps to reproduce: 
- Install the latest extension c/c++ and the latest IAR For Visual Studio Code from pluyckx.iar-vsc
- Download the attached file [bug_on_vs_code.zip](https://github.com/microsoft/vscode-cpptools/files/8889335/bug_on_vs_code.zip)

- Unpack the files an open the VSC-WS file in the .vscode folder
- browse in VS Code to the file: r_bsp_config_reference and then you get the command line error. this is just one example of this behavior from the C/C++ extension.
- If you now downgrade the c/c++ version to 1.8.4 and restart vs code, the error disappear

VS Code Version: 
![2022-06-13 10_13_47-Visual Studio Code](https://user-images.githubusercontent.com/107396328/173311636-e617f239-b6c6-4d3f-908c-c002216af8d2.png)

Example of macro definition error: 
![image](https://user-images.githubusercontent.com/107396328/173311824-d483c5da-dc4b-47a6-8d4a-cd96b88c7c67.png)

**Comment by sean-mcmanus** [comment] 2022-06-13 23:09
That project seems to be configured with another configuration provider. Are you able to create a repro that doesn't use that configuration provider? If you run C/C++: Log Diagnostics, does the output appear to show correct data being provided by the configuration provider?

What does that error say in English? It sounds like it's saying the __STDC_VERSION__ version is invalid?

**Comment by JulianMaV** [comment] 2022-06-14 08:54
Hi @sean-mcmanus your guess is correct. The configuration provider is the extension "IAR For Visual Studio Code"(iar-vsc) from pluyckx. Without this it is actually not possible for me to create a working setup.

The Error Massage in English: Command line error: Invalid macro definition: __STDC_VERSION__=199901L 
However, this definition is not changed and therefore can't be invalid when the versions of c/c++ are changed. 

And here is the log file from C/C++: Log Diagnostics (Version 1.10.5): [V1.10.5.txt](https://github.com/microsoft/vscode-cpptools/files/8898112/V1.10.5.txt)

**Comment by JulianMaV** [comment] 2022-06-14 09:32
later I completely deleted the defines for testing and looked at the error reactions of the different C/C++ versions with active IAR extension of pluyckx. 

**C/C++ Version 1.8.4:** 
![V1 8 4_without_errors](https://user-images.githubusercontent.com/107396328/173542130-0651e912-1876-4d17-8ddd-336d2bebc3c5.png)

**C/C++: Log Diagnostics:** 

-------- Diagnostics - 14.6.2022, 10:48:43
Version: 1.8.4
Current Configuration:
{
    "name": "IAR",
    "defines": [],
    "includePath": [],
    "forcedInclude": [],
    "cStandard": "c99",
    "cppStandard": "c++14",
    "compilerPath": "",
    "intelliSenseMode": "msvc-x64",
    "configurationProvider": "pluyckx.iar-vsc",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom configurations:
[ C:\Users\JulianVeith\Desktop\bug_on_vs_code\r_bsp_config_reference.h ]
{
    "compilerPath": "",
    "defines": [
        "_Pragma(x)=",
        "__eeprom=",
        "__flash=",
        "__no_init=",
        "__root="
    ],
    "includePath": [],
    "forcedInclude": [],
    "intelliSenseMode": "msvc-x64",
    "standard": "c99"
}
Translation Unit Mappings:
[ C:\Users\JulianVeith\Desktop\bug_on_vs_code\r_bsp_config_reference.h ]:
    C:\Users\JulianVeith\Desktop\bug_on_vs_code\r_bsp_config_reference.h
Translation Unit Configurations:
[ C:\Users\JulianVeith\Desktop\bug_on_vs_code\r_bsp_config_reference.h ]:
    Process ID: 29984
    Memory Usage: 15 MB
    Defines:
        _Pragma(x)=
        __eeprom=
        __flash=
        __no_init=
        __root=
    Standard Version: ms_c17
    IntelliSense Mode: windows-msvc-x64
    Other Flags:
        --header_only_fallback
Total Memory Usage: 15 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 14
Number of files parsed: 1

**C/C++ Version 1.10.5:** 
![V1 10 5_with_error](https://user-images.githubusercontent.com/107396328/173542445-213fc93b-481f-4699-9634-d86a20deb0e0.png)

Error in English: Command line error: Invalid macro definition: _Pragma(x)=

**C/C++: Log Diagnostics:** 

-------- Diagnostics - 14.6.2022, 10:47:08
Version: 1.10.5
Current Configuration:
{
    "name": "IAR",
    "defines": [],
    "includePath": [],
    "forcedInclude": [],
    "cStandard": "c99",
    "cppStandard": "c++14",
    "compilerPath": "",
    "intelliSenseMode": "msvc-x64",
    "configurationProvider": "pluyckx.iar-vsc",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom configurations:
[ C:\Users\JulianVeith\Desktop\bug_on_vs_code\r_bsp_config_reference.h ]
{
    "compilerPath": "",
    "defines": [
        "_Pragma(x)=",
        "__eeprom=",
        "__flash=",
        "__no_init=",
        "__root="
    ],
    "includePath": [],
    "forcedInclude": [],
    "intelliSenseMode": "msvc-x64",
    "standard": "c99"
}
Translation Unit Mappings:
[ C:\Users\JulianVeith\Desktop\bug_on_vs_code\r_bsp_config_reference.h ]:
    C:\Users\JulianVeith\Desktop\bug_on_vs_code\r_bsp_config_reference.h
Translation Unit Configurations:
[ C:\Users\JulianVeith\Desktop\bug_on_vs_code\r_bsp_config_reference.h ]:
    Process ID: 26680
    Memory Usage: 12 MB
    Defines:
        _Pragma(x)=
        __eeprom=
        __flash=
        __no_init=
        __root=
    Standard Version: ms_c17
    IntelliSense Mode: windows-msvc-x64
    Other Flags:
        --header_only_fallback
Total Memory Usage: 12 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 14


**Test summary:**
In the logs, the default defines stand out, from where I still do not know why they were inserted. But what is striking here is that in the latest version of C/C++ the first define is marked as error, although this is not used at all in the r_bsp_config_reference.h file. 

Does anyone have a guess where this error could come from?

**Comment by Colengms** [comment] 2022-06-15 00:37
Curiously, the issue only repros when using an `msvc` intelliSense mode.  That configuration provider is returning:

```
"intelliSenseMode": "msvc-x64",
```

The defines returned by the compiler do not indicate that the compiler supports MSC extensions.  If your environment is not intended to compiler MSVC or Windows headers, you might want to contact the author of `pluyckx.iar-vsc` and suggest they provide a non-msvc `IntelliSenseMode` instead.

**Comment by Colengms** [comment] 2022-06-23 19:43
Hi @HampusAdolfsson .  I noticed that your custom configuration extension is providing the `msvc-x64` IntelliSense mode.  That mode is specific to the MSVC `cl.exe` compiler.  Unfortunately, cpptools does not currently have a [compiler agnostic intellisense mode](https://github.com/microsoft/vscode-cpptools/issues/4653), which might be the ideal solution for compilers that aren't directly supported.

Could you check if you get acceptable IntelliSense behavior if your extension provides `gcc-x64` as the IntelliSense mode instead?  I believe the 'invalid macro' errors are only reported if using an MSVC IntelliSense mode, so changing it to `gcc-x64` may address this issue entirely.

The 'invalid macro' errors are actually ignorable, and do not interfere with IntelliSense.  The values you are providing should indeed be used.  (The error is actually originating in code tries to specify values for these defines, and fails because they were already explicitly set by the configuration.)

Another potential issue here is that the `standard` your extension is providing does not appear to be used.  This may be due to using an MSVC IntelliSense mode, as `cl.exe` does not support specifying `c99` as the standard and defaults to `c17`.  If this issue persists when specifying a non-MSVC IntelliSense mode, we can likely address it.  Unfortunately, setting the value of `__STDC_VERSION__` is not sufficient to configure IntelliSense to match that version of the standard.

**Comment by JulianMaV** [comment] 2022-06-24 07:32
Hello each other,

What can I do now to make these errors disappear until there is a solution? Is there an ignore list for errors, because working with constant error messages and red marks can be a bit annoying? 

How else can I help you to solve this error case?

**Comment by HampusAdolfsson** [comment] 2022-06-27 08:36
Hi @Colengms. 
Sorry, I wasn't being very clear. Our extension (`iarsystems.iar-build`) [uses clang-arm](https://github.com/IARSystems/iar-vsc-build/blob/master/src/extension/cpptools/configurationprovider.ts#L139). `pluyckx.iar-vsc` uses `msvc-x64`, but it will be deprecated soon.

I get this error regardless of the intellisenseMode, including with `gcc-x64`. When I wrote my first comment, the `gcc` and `clang` modes defined `__EDG_VERSION__=602`, which is the same as the latest IAR compilers, and which I believe is why they didn't give this error. However, now they all seem to use `603` (i.e. a different value from IAR compilers), so all intelliseSense modes now give this error.

Even if the EDG version used by IAR compilers is upgraded, it is quite common for our users to use older compilers, so we cannot expect the compiler's EDG version to match what the intellisenseMode wants to define.

>Another potential issue here is that the standard your extension is providing does not appear to be used.

`iarsystems.iar-build` has been improved so that it sets both the `standard` and `__STDC_VERSION__` to the correct (and equivalent) value. I hope this (and using `clang-arm`) would address the issue?

**Comment by Colengms** [comment] 2022-07-13 18:56
> I get this error regardless of the intellisenseMode, including with gcc-x64

Hi @HampusAdolfsson .  To clarify, this warning should not occur with a non-MSVC IntelliSenseMode.  Could you please check again?  Looking at the code, there is a flag that imposes a requirement on these defines, and that flag is specific to the MSVC mode, specific to the version of MSVC we are emulating, and specific to how we conform to C11 and C17.  If not an MSVC mode, the flag that triggers this warning should not be set, and I am unable to repro the error message with non-MSVC IntelliSense modes.  My suggestion would be to ensure you are not providing `msvc-x64` as the IntelliSenseMode in a custom configuration for any non-MSVC compiler.  If you can reproduce an issue in which this error message still occurs despite providing a non-MSVC IntelliSense mode, please provide a self-contained repro that we could use to investigate further.  Based on an inspection of the code, I don't see how use of a non-MSVC IntelliSense mode could trigger that error message.

**Comment by HampusAdolfsson** [comment] 2022-07-15 11:44
@Colengms
I am on vacation until mid-august, but I will re-check the error when I get back, and send you a repro if I can in fact produce the error with non-msvc modes.

**Comment by HampusAdolfsson** [comment] 2022-08-18 10:16
@Colengms 

I've created a minimal example here, with a [very simple provider](https://github.com/HampusAdolfsson/Cpptools-9435-repro/blob/7aed24c3cc26d53a55c0ea1529de2a63faee94f8/src/extension.ts#L47):
https://github.com/HampusAdolfsson/Cpptools-9435-repro
You should be able to `npm install`, launch the extension and then open any C file to see the error.

**Comment by Colengms** [comment] 2022-09-30 00:27
Hi @HampusAdolfsson .  The problem is that IntelliSense is itself is an EDG front-end.  EDG can be configured to emulate GCC, Clang and CL, and emulate the differences between certain versions of GCC and Clang, but it continues to represent itself as EDG (via system defines) and does not provide a way to emulate different versions of EDG itself.  It also disallows redefinition of the compiler defines that it uses internally.  That is what you are seeing.

The error is reported because the defines we are providing EDG take precedence over its own values.  It's reporting the error as it tries to assign its own values and discovers that values are already present.  So, your changes are being applied, which you can confirm by hovering over a `__EDG_VERSION__` in your repro.  However, this can lead to incorrect behavior.  EDG does not (fully) configure itself based on incoming defines.  Setting defines without also specifying an equivalent IntelliSense mode (which we translate into the appropriate args to EDG, such as `--clang`, `--clang_version=`, `--gcc`, `--g++`, `--gnu_version=`, and various other feature-specific args) can cause some mismatches that result in IntelliSense errors.

For now, we could suppress the error from being reported if the define was part of a custom configuration.  But that would not prevent other aspects of IntelliSense from failing due to internally inconsistent state in EDG.  The ideal fix would be for us to determine the proper internal args to configure EDG with to most closely match the compiler, address features gaps needed to support that compiler, and provide an IntelliSense mode for it.  (Does [this issue](https://github.com/microsoft/vscode-cpptools/issues/7653) properly track that for your compiler? )

**Comment by sean-mcmanus** [comment] 2022-10-04 14:03
@HampusAdolfsson We're tracking adding support for IAR compilers at https://github.com/microsoft/vscode-cpptools/issues/7653 . The VS team worked with NVIDIA to add NVCC compiler support -- I'm looking into if there's someone you can contact about that...

**Closed as completed** 2022-12-07 18:48 UTC
Labels: bug, Language Service, fixed, regression, Feature: Configuration
