### ISSUE TITLE
None of the available cpptools functions work over Remote SSH to Centos 7.9.2009 machine

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#7558] opened 2021-05-20 15:48 UTC
**Bug type**: Language Service

**Describe the bug**
- **OS and Version**: Win10 Pro
- **VS Code Version**: 1.56.2
- **C/C++ Extension Version**: 1.3.1
- **Other extensions you installed (and if the issue persists after disabling them)**: Remote-SSH
- **If using SSH remote, specify OS of remote machine**: CentOS Linux release 7.9.2009
- **A clear and concise description of what the bug is, including information about the workspace**:

None of the available cpptools functions work (meaning intellisense, autocomplete, references, ctrl-click functionality, outline, ...). For example, hovering over variables or functions just keeps loading. Nothing happens, not even after a while.
It's a simple project consisting of several .cc and .h files (4 directories consisting of 6 to 8 files/directory). The .h files relate to the .cc files and are in the same directory. 

**Steps to reproduce**

1. Go to any .cc or .h file and open it.
2. Hovering over any function keeps showing _Loading..._
3. Outline window says it's loading document symbols. 
4. There is no real error shown, however with `"C_Cpp.loggingLevel": "Debug"` it shows the following output (nothing else after, even when opening additional files):
```
cpptools/didChangeCppProperties
Attempting to get defaults from C compiler in "compilerPath" property: '/usr/bin/g++'
Querying compiler for default C++ language standard using command line: "/usr/bin/g++" -x c++ -E -dM /dev/null
terminating child process: 16528
Detected language standard version: gnu++98
Querying compiler for default C language standard using command line: "/usr/bin/g++" -x c -E -dM /dev/null
terminating child process: 16530
Querying compiler's default target using command line: "/usr/bin/g++" -dumpmachine
Compiler returned default target value: x86_64-redhat-linux

terminating child process: 16533
Compiler query command line: "/usr/bin/g++" -std=c99 -Wp,-v -E -dD -x c -m64  /dev/null
terminating child process: 16534

```

**Expected behavior**

I expect the outline to show the functions in my file at least. And references to be set so I can navigate the code by ctrl-clicking variables or functions.

**Configuration and logs**
- **Configurations in `settings.json`**:
```
{
    "C_Cpp.files.exclude": {
        "**/.vscode": true
    },
    "C_Cpp.loggingLevel": "Debug",
    "C_Cpp.default.browse.path": [
        "${workspaceFolder}"
    ],
    "C_Cpp.default.compilerPath": "/usr/bin/g++",
    "C_Cpp.intelliSenseEngineFallback": "Enabled",
    "C_Cpp.default.cppStandard": "gnu++98",
    "C_Cpp.default.cStandard": "c99",
    "C_Cpp.default.includePath": [
        "${workspaceFolder}"
    ],
    "C_Cpp.default.intelliSenseMode": "linux-gcc-x64",
    "C_Cpp.default.systemIncludePath": [
        "/usr/include"
    ],
    "C_Cpp.experimentalFeatures": "Enabled",
    "C_Cpp.formatting": "Default",
    "C_Cpp.workspaceSymbols": "All"
}
```

- **Configurations in `c_cpp_properties.json`**: Does not exist.

- **Logs from running `C/C++: Log Diagnostics` from the VS Code command palette**: Does nothing.

- **Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)**: See _Steps to reproduce_ above.

**Comment by sean-mcmanus** [comment] 2021-05-20 21:47
Normally, you should see output like
```
Code browsing service initialized
Attempting to get defaults from C++ compiler in "/usr/bin/g++" -std=gnu++98 -Wp,-v -E -dD -x c++ -m64  /dev/null
```
so I'm guessing it got stuck creating your browse database.

Can you set your C_Cpp.default.browse.databaseFilename setting to something like `${workspaceFolder}/.vscode/vc.db` and see if the file is created successfully? I'm guess something is causing the database creation to get stuck when the default path is used.

**Comment by magdyabdel** [comment] 2021-05-20 22:07
> Normally, you should see output like
> 
> ```
> Code browsing service initialized
> Attempting to get defaults from C++ compiler in "/usr/bin/g++" -std=gnu++98 -Wp,-v -E -dD -x c++ -m64  /dev/null
> ```
> 
> so I'm guessing it got stuck creating your browse database.
> 
> Can you set your C_Cpp.default.browse.databaseFilename setting (in the remote/workspace/folder scope, not user) to something like `${workspaceFolder}/.vscode/vc.db` and see if the file is created successfully? I'm guess something is causing the database creation to get stuck when the default path is used.

Thank you for your response.
Hmm, I tried that and it makes an empty `vc.db`. Nothing else happens.

**Comment by sean-mcmanus** [comment] 2021-05-20 22:20
We've never encountered reports of an empty vc.db so I'm not sure what that means yet. Can you attach a debugger to the cpptools process and provide the call stack for the thread that appears to be doing work and then became stuck (ignore the shallow threads)? See https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv .

**Comment by magdyabdel** [comment] 2021-05-21 08:50
Is there a different way to attach the debugger? Currently cpptools seems to get stuck before I get to start the debugger (or I am too slow 😄). So attaching the debugger as specified in the link shows empty windows (variables, watch, call stack, breakpoints), see the image below. The `launch.json` is pasted below as well.

![image](https://user-images.githubusercontent.com/5099378/119109677-aa5f6e00-ba21-11eb-9f21-798482a7aac8.png)

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "program": "/home/magdy.abdel/.vscode-server/extensions/ms-vscode.cpptools-1.3.1/bin/cpptools",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

**Comment by sean-mcmanus** [comment] 2021-05-21 20:08
That is strange. @WardenGnaw Have you seen that before?

@magdyabdel  Do you see any errors in the Debug Console? May be set
```
 "logging": {
                "engineLogging": true
            },
```
You could try running gdb directly (I don't know the commands though).

**Comment by WardenGnaw** [comment] 2021-05-21 21:29
Yes, the windows have not been populated because the process is running and has not been stopped.

**Comment by magdyabdel** [comment] 2021-05-25 13:54
> @magdyabdel Do you see any errors in the Debug Console? May be set

I see no errors, just messages saying `[New LWP 2xxxx]`

> You could try running gdb directly (I don't know the commands though).

Gives the same messages as in VS Code

> Are you able to hit the Pause button to break into the process?

I can click it, but nothing happens. No errors or messages pop-up either.
![image](https://user-images.githubusercontent.com/5099378/119509612-1408b080-bd71-11eb-915d-00b99488baf2.png)

> Maybe the process has crashed and is in some zombie state?

Checking the processes shows no zombie state. It's really strange, I had no problems with other plugins before (I used Python and its linting tools without problems). 

If I can provide you with any further information to get closer to a solution let me know.

**Comment by magdyabdel** [comment] 2021-06-09 12:19
Any idea on what else I can try so I can figure out what in my setup is preventing the use of cpptools ?

**Comment by sean-mcmanus** [comment] 2021-06-09 17:42
@Colengms ?

**Comment by Colengms** [comment] 2021-06-09 21:55
I set up a VM running `centos-release-7-9.2009.0.el7.centos.x86_64`, and so far have not been able to repro an issue with a remote folder on it.

@magdyabdel Do you repro with the latest version of the extension?  (Currently 1.4.1)  Does a simple example work properly for you, with no additional configuration (so none of your `C_Cpp`)?  If so, could you try adding those settings one at a time, to see which one introduces the issue?  If this only repros with a complex project, there could be some code (perhaps in a header) that is confusing our parser(s).

**Comment by magdyabdel** [comment] 2021-06-10 09:41
I installed the latest version (1.4.1) and created a simple example (C++) and made sure that everything started from fresh. I have set no settings inside this example. I tried this before since I was suspecting the project as well to be the reason. But as you can see in the screenshot below, I have exactly the same issue. 

This makes me think that it might be related to my gcc/g++ environment? But I have no clue what it could be. Are there any permissions required for particular tools used in cpptools?

![image](https://user-images.githubusercontent.com/5099378/121502324-5a504780-c9e0-11eb-8a4a-fb036f3eba5a.png)
The "Loading..." was my mouse hovering over `std::endl`.

**Comment by Colengms** [comment] 2021-06-10 19:38
Hi @magdyabdel .  I'm assuming that compiler query command line is the last thing that ever gets logged (other than terminating child process).  Is that correct?  If so, things would seem to be getting stuck rather than failing, which is unusual.  Does that command line work for you when executed manually in a shell/terminal, using the same account?

The possibility of a permission issue is a good theory.  If the account you are using is not also an admin, would it be possible to try to repro using an admin account?  If that succeeds, that would seem to confirm there is a permission issue.

**Comment by magdyabdel** [comment] 2021-06-11 14:25
Hey @Colengms , that's correct it's the last thing that gets logged. I ran the command as myself in a terminal and here is the output I get:
<details>
<summary>Output</summary>

```
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../x86_64-redhat-linux/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include
 /usr/local/include
 /usr/include
End of search list.
# 1 "/dev/null"
# 1 "<built-in>"
#define __STDC__ 1
#define __STDC_HOSTED__ 1
#define __GNUC__ 4
#define __GNUC_MINOR__ 8
#define __GNUC_PATCHLEVEL__ 5
#define __VERSION__ "4.8.5 20150623 (Red Hat 4.8.5-44)"
#define __GNUC_RH_RELEASE__ 44
#define __ATOMIC_RELAXED 0
#define __ATOMIC_SEQ_CST 5
#define __ATOMIC_ACQUIRE 2
#define __ATOMIC_RELEASE 3
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_CONSUME 1
#define __FINITE_MATH_ONLY__ 0
#define _LP64 1
#define __LP64__ 1
#define __SIZEOF_INT__ 4
#define __SIZEOF_LONG__ 8
#define __SIZEOF_LONG_LONG__ 8
#define __SIZEOF_SHORT__ 2
#define __SIZEOF_FLOAT__ 4
#define __SIZEOF_DOUBLE__ 8
#define __SIZEOF_LONG_DOUBLE__ 16
#define __SIZEOF_SIZE_T__ 8
#define __CHAR_BIT__ 8
#define __BIGGEST_ALIGNMENT__ 16
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_PDP_ENDIAN__ 3412
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __SIZEOF_POINTER__ 8
#define __SIZE_TYPE__ long unsigned int
#define __PTRDIFF_TYPE__ long int
#define __WCHAR_TYPE__ int
#define __WINT_TYPE__ unsigned int
#define __INTMAX_TYPE__ long int
#define __UINTMAX_TYPE__ long unsigned int
#define __CHAR16_TYPE__ short unsigned int
#define __CHAR32_TYPE__ unsigned int
#define __SIG_ATOMIC_TYPE__ int
#define __INT8_TYPE__ signed char
#define __INT16_TYPE__ short int
#define __INT32_TYPE__ int
#define __INT64_TYPE__ long int
#define __UINT8_TYPE__ unsigned char
#define __UINT16_TYPE__ short unsigned int
#define __UINT32_TYPE__ unsigned int
#define __UINT64_TYPE__ long unsigned int
#define __INT_LEAST8_TYPE__ signed char
#define __INT_LEAST16_TYPE__ short int
#define __INT_LEAST32_TYPE__ int
#define __INT_LEAST64_TYPE__ long int
#define __UINT_LEAST8_TYPE__ unsigned char
#define __UINT_LEAST16_TYPE__ short unsigned int
#define __UINT_LEAST32_TYPE__ unsigned int
#define __UINT_LEAST64_TYPE__ long unsigned int
#define __INT_FAST8_TYPE__ signed char
#define __INT_FAST16_TYPE__ long int
#define __INT_FAST32_TYPE__ long int
#define __INT_FAST64_TYPE__ long int
#define __UINT_FAST8_TYPE__ unsigned char
#define __UINT_FAST16_TYPE__ long unsigned int
#define __UINT_FAST32_TYPE__ long unsigned int
#define __UINT_FAST64_TYPE__ long unsigned int
#define __INTPTR_TYPE__ long int
#define __UINTPTR_TYPE__ long unsigned int
#define __GXX_ABI_VERSION 1002
#define __SCHAR_MAX__ 127
#define __SHRT_MAX__ 32767
#define __INT_MAX__ 2147483647
#define __LONG_MAX__ 9223372036854775807L
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __WCHAR_MAX__ 2147483647
#define __WCHAR_MIN__ (-__WCHAR_MAX__ - 1)
#define __WINT_MAX__ 4294967295U
#define __WINT_MIN__ 0U
#define __PTRDIFF_MAX__ 9223372036854775807L
#define __SIZE_MAX__ 18446744073709551615UL
#define __INTMAX_MAX__ 9223372036854775807L
#define __INTMAX_C(c) c ## L
#define __UINTMAX_MAX__ 18446744073709551615UL
#define __UINTMAX_C(c) c ## UL
#define __SIG_ATOMIC_MAX__ 2147483647
#define __SIG_ATOMIC_MIN__ (-__SIG_ATOMIC_MAX__ - 1)
#define __INT8_MAX__ 127
#define __INT16_MAX__ 32767
#define __INT32_MAX__ 2147483647
#define __INT64_MAX__ 9223372036854775807L
#define __UINT8_MAX__ 255
#define __UINT16_MAX__ 65535
#define __UINT32_MAX__ 4294967295U
#define __UINT64_MAX__ 18446744073709551615UL
#define __INT_LEAST8_MAX__ 127
#define __INT8_C(c) c
#define __INT_LEAST16_MAX__ 32767
#define __INT16_C(c) c
#define __INT_LEAST32_MAX__ 2147483647
#define __INT32_C(c) c
#define __INT_LEAST64_MAX__ 9223372036854775807L
#define __INT64_C(c) c ## L
#define __UINT_LEAST8_MAX__ 255
#define __UINT8_C(c) c
#define __UINT_LEAST16_MAX__ 65535
#define __UINT16_C(c) c
#define __UINT_LEAST32_MAX__ 4294967295U
#define __UINT32_C(c) c ## U
#define __UINT_LEAST64_MAX__ 18446744073709551615UL
#define __UINT64_C(c) c ## UL
#define __INT_FAST8_MAX__ 127
#define __INT_FAST16_MAX__ 9223372036854775807L
#define __INT_FAST32_MAX__ 9223372036854775807L
#define __INT_FAST64_MAX__ 9223372036854775807L
#define __UINT_FAST8_MAX__ 255
#define __UINT_FAST16_MAX__ 18446744073709551615UL
#define __UINT_FAST32_MAX__ 18446744073709551615UL
#define __UINT_FAST64_MAX__ 18446744073709551615UL
#define __INTPTR_MAX__ 9223372036854775807L
#define __UINTPTR_MAX__ 18446744073709551615UL
#define __FLT_EVAL_METHOD__ 0
#define __DEC_EVAL_METHOD__ 2
#define __FLT_RADIX__ 2
#define __FLT_MANT_DIG__ 24
#define __FLT_DIG__ 6
#define __FLT_MIN_EXP__ (-125)
#define __FLT_MIN_10_EXP__ (-37)
#define __FLT_MAX_EXP__ 128
#define __FLT_MAX_10_EXP__ 38
#define __FLT_DECIMAL_DIG__ 9
#define __FLT_MAX__ 3.40282346638528859812e+38F
#define __FLT_MIN__ 1.17549435082228750797e-38F
#define __FLT_EPSILON__ 1.19209289550781250000e-7F
#define __FLT_DENORM_MIN__ 1.40129846432481707092e-45F
#define __FLT_HAS_DENORM__ 1
#define __FLT_HAS_INFINITY__ 1
#define __FLT_HAS_QUIET_NAN__ 1
#define __DBL_MANT_DIG__ 53
#define __DBL_DIG__ 15
#define __DBL_MIN_EXP__ (-1021)
#define __DBL_MIN_10_EXP__ (-307)
#define __DBL_MAX_EXP__ 1024
#define __DBL_MAX_10_EXP__ 308
#define __DBL_DECIMAL_DIG__ 17
#define __DBL_MAX__ ((double)1.79769313486231570815e+308L)
#define __DBL_MIN__ ((double)2.22507385850720138309e-308L)
#define __DBL_EPSILON__ ((double)2.22044604925031308085e-16L)
#define __DBL_DENORM_MIN__ ((double)4.94065645841246544177e-324L)
#define __DBL_HAS_DENORM__ 1
#define __DBL_HAS_INFINITY__ 1
#define __DBL_HAS_QUIET_NAN__ 1
#define __LDBL_MANT_DIG__ 64
#define __LDBL_DIG__ 18
#define __LDBL_MIN_EXP__ (-16381)
#define __LDBL_MIN_10_EXP__ (-4931)
#define __LDBL_MAX_EXP__ 16384
#define __LDBL_MAX_10_EXP__ 4932
#define __DECIMAL_DIG__ 21
#define __LDBL_MAX__ 1.18973149535723176502e+4932L
#define __LDBL_MIN__ 3.36210314311209350626e-4932L
#define __LDBL_EPSILON__ 1.08420217248550443401e-19L
#define __LDBL_DENORM_MIN__ 3.64519953188247460253e-4951L
#define __LDBL_HAS_DENORM__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __DEC32_MANT_DIG__ 7
#define __DEC32_MIN_EXP__ (-94)
#define __DEC32_MAX_EXP__ 97
#define __DEC32_MIN__ 1E-95DF
#define __DEC32_MAX__ 9.999999E96DF
#define __DEC32_EPSILON__ 1E-6DF
#define __DEC32_SUBNORMAL_MIN__ 0.000001E-95DF
#define __DEC64_MANT_DIG__ 16
#define __DEC64_MIN_EXP__ (-382)
#define __DEC64_MAX_EXP__ 385
#define __DEC64_MIN__ 1E-383DD
#define __DEC64_MAX__ 9.999999999999999E384DD
#define __DEC64_EPSILON__ 1E-15DD
#define __DEC64_SUBNORMAL_MIN__ 0.000000000000001E-383DD
#define __DEC128_MANT_DIG__ 34
#define __DEC128_MIN_EXP__ (-6142)
#define __DEC128_MAX_EXP__ 6145
#define __DEC128_MIN__ 1E-6143DL
#define __DEC128_MAX__ 9.999999999999999999999999999999999E6144DL
#define __DEC128_EPSILON__ 1E-33DL
#define __DEC128_SUBNORMAL_MIN__ 0.000000000000000000000000000000001E-6143DL
#define __REGISTER_PREFIX__
#define __USER_LABEL_PREFIX__
#define __GNUC_GNU_INLINE__ 1
#define __NO_INLINE__ 1
#define __STRICT_ANSI__ 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 1
#define __GCC_ATOMIC_BOOL_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __GCC_ATOMIC_SHORT_LOCK_FREE 2
#define __GCC_ATOMIC_INT_LOCK_FREE 2
#define __GCC_ATOMIC_LONG_LOCK_FREE 2
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2
#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
#define __GCC_ATOMIC_POINTER_LOCK_FREE 2
#define __GCC_HAVE_DWARF2_CFI_ASM 1
#define __PRAGMA_REDEFINE_EXTNAME 1
#define __SIZEOF_INT128__ 16
#define __SIZEOF_WCHAR_T__ 4
#define __SIZEOF_WINT_T__ 4
#define __SIZEOF_PTRDIFF_T__ 8
#define __amd64 1
#define __amd64__ 1
#define __x86_64 1
#define __x86_64__ 1
#define __ATOMIC_HLE_ACQUIRE 65536
#define __ATOMIC_HLE_RELEASE 131072
#define __k8 1
#define __k8__ 1
#define __code_model_small__ 1
#define __MMX__ 1
#define __SSE__ 1
#define __SSE2__ 1
#define __FXSR__ 1
#define __SSE_MATH__ 1
#define __SSE2_MATH__ 1
#define __gnu_linux__ 1
#define __linux 1
#define __linux__ 1
#define __unix 1
#define __unix__ 1
#define __ELF__ 1
#define __DECIMAL_BID_FORMAT__ 1
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 19 "/usr/include/stdc-predef.h" 3 4
#define _STDC_PREDEF_H 1
# 30 "/usr/include/stdc-predef.h" 3 4
#define __STDC_IEC_559__ 1
#define __STDC_IEC_559_COMPLEX__ 1



#define __STDC_ISO_10646__ 201103L


#define __STDC_NO_THREADS__ 1
# 1 "<command-line>" 2
# 1 "/dev/null"

```
</details>

BUT, as we speculated it seems we were right..
I just tried as user **root** opening the simple example from my previous comment and it seems to work like this. However, I do not like the thought of working as **root** in a working environment for "simple" development.

Any thoughts on which permissions might be the root (pun not intended 😄) problem here?

**Comment by sean-mcmanus** [comment] 2021-06-12 00:40
I don't know.

**Comment by Colengms** [comment] 2021-06-12 01:07
Hi @magdyabdel .  I tried to repro using a new account that is not an admin.  But, that doesn't appear to be sufficient.  The very next output I see in my log is `Code browsing service initialized`, which Sean mentioned.  That is logged immediately after we open (or create) a database to store code browsing information.  By default, that file is created in `~/.vscode-server/data/User/workspaceStorage/<unique_value>/ms-vscode.cpptools`.  Is it possible that path cannot be written to by your account, for some reason?  Since I'm not reproing with a simple example on a fresh install of that build of CentOS, I guess we're looking for what might be different about your system.  Are you using any settings that might refer to folders that the account doesn't have permission to, such as `C_Cpp.default.browse.databaseFilename` ?

**Comment by magdyabdel** [comment] 2021-06-14 11:08
Thank you for the response @Colengms.
So, I tried in my simplified environment (_no custom settings_) as my usual user. And I can see that the file is generated in the folder you specified (`~/.vscode-server/data/User/workspaceStorage/<unique_value>/ms-vscode.cpptools`) and the permissions look as follows:
```
-rw-r--r--. 1 magdy.abdel domain-users  0 Jun 14 13:00 .browse.VC.db
```
The file is definitely created with myself as owner and `rw` permissions, but it's empty. Is the file being written as the user? Because as you can see, there are no write permissions for other users/groups.

**Comment by sean-mcmanus** [comment] 2021-06-14 18:50
@magdyabdel It shows user write permissions. Is your VS Code not running under your user account?

**Comment by magdyabdel** [comment] 2021-06-14 20:18
It actually is. That's why I find it a bit confusing.

**Comment by Colengms** [comment] 2021-06-15 22:33
@magdyabdel What happens if you create and use a new user account (without admin permissions) ?  If that works, there may be an issue specific to the repro'ing account.

After the repro has occurred, can you determine if the cpptools process is still running?  If so, and the symptom is a hang instead of a crash, perhaps you can connect a debugger and get stacks from it?

**Comment by magdyabdel** [comment] 2021-07-02 15:24
@Colengms It seems to work with a new local user (without any `sudo` permissions). What I could have mentioned earlier is that the users we usually work with exist locally but have an NFS mounted home directory. Not sure if this rings any bells for you or might impact behavior?

**Comment by sean-mcmanus** [comment] 2021-07-02 17:06
Might be related to https://github.com/microsoft/vscode-cpptools/issues/4573 .

**Comment by magdyabdel** [comment] 2021-07-02 17:17
Yes, but with purely local users cpptools works in the same folder that is
mounted. So not sure.

**Comment by sean-mcmanus** [comment] 2021-07-02 17:39
Actually, the symptom sounds the same as https://github.com/microsoft/vscode-cpptools/issues/7412 . Can you attach a debugger to cpptools to get a call stack? https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv . It's also possible https://github.com/microsoft/vscode-cpptools/issues/7701 could be the cause if your paths have /D or /I in them (although I think the symptom would be different).

**Comment by magdyabdel** [comment] 2021-07-06 07:46
I am still unable to get a call stack. It's like one of my previous comments. 
I am out of ideas to try, I tried reinstalling the vscode remote ssh server multiple times as well. I have a feeling it might have to do with remote ssh and the nfs mounted home directories. But only for the users that are linked to them.

**Comment by sean-mcmanus** [comment] 2021-07-08 23:44
We have a new 1.5.0 release (https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.0), but we're not sure if it fixes your issue or not.

**Comment by magdyabdel** [comment] 2021-07-09 12:25
Unfortunately the update did not resolve the issue.

**Comment by magdyabdel** [comment] 2021-07-09 12:35
Btw, just like in #7412 I also have multiple cpptools still running after closing vscode. I have to manually kill them, otherwise they just stay there forever. However killing them does not help.

It is briefly mentioned in [this](https://github.com/microsoft/vscode-cpptools/issues/7412#issuecomment-870154285) comment.

**Comment by sean-mcmanus** [comment] 2021-07-09 17:43
@magdyabdel We have code that will shutdown the cpptools process if it dangles for more than 5 minutes. By "still running after closing vscode" do you know if it's still running after 5 minutes?

I don't know of any paths that rely on to be default.

**Comment by Colengms** [comment] 2021-07-09 22:35
> Edit: I think it's getting stuck somewhere for the mounted homedir users. Are there paths that cpptools expects to be default? Like it should be /home/user/.vscode_server/... or something?

Hi @magdyabdel .  

Are you saying the NFS mounted home directories are not mounted under /home/user ?  If so, what does the `HOME` environment variable resolve to for one of those users?  We use [`uv_os_homedir` in `libuv`](https://github.com/libuv/libuv/blob/6b0051d14decb22cab1ae7ee0adf0da99620cafe/src/unix/core.c#L1067) to find the user's home directory.  We may also use the `XDG_CACHE_HOME` environment variable, if set, or will default to creating a cache directory under `~/.cache`.  Do you see a directory titled `vscode-cpptools` under either of those paths, on the repro'ing account?

Are the NFS mounted home directories remote, or does the same host provide them as well?   If you create a new user with the only non-default detail being that it uses an NFS mounted home directory, is that sufficient to repro the issue?   If you can point me to the steps necessary to set that up as you have, I could try it out to see if I can repro.

**Comment by magdyabdel** [comment] 2021-07-13 07:55
Hi @sean-mcmanus @Colengms 
Thanks for your messages. I investigated a bit further on your questions.

> do you know if it's still running after 5 minutes?

Yes, it never closes by itself. Not even after 5 minutes. The only way (I know of) to close them is by issuing the `kill` command. 

> Are you saying the NFS mounted home directories are not mounted under /home/user ? If so, what does the `HOME `environment variable resolve to for one of those users?

The machine I develop on has the mounted home directories mounted to `/mnt/SRVFILMOUNTS/homedirs/home/magdy` which is what `$HOME` resolves to. However, these home directories are sometimes also mounted to `/home/magdy` on other machines in our environment, on which I tested as well, without any luck.

> We may also use the `XDG_CACHE_HOME` environment variable, if set, or will default to creating a cache directory under `~/.cache`. Do you see a directory titled `vscode-cpptools` under either of those paths, on the repro'ing account?

`$XDG_CACHE_HOME` is not set, so the default would be `~/.cache`, right? For the repro'ing account there is no `vscode-cpptools` under this path. And to be sure that it was being generated for the local users (e.g. root or new local user) I checked in their home folders as well, and for those accounts `vscode-cpptools` exists under `~/.cache`. 

> Are the NFS mounted home directories remote, or does the same host provide them as well?

They are hosted on a remote machine separated from the machines they are mounted to.

> If you create a new user with the only non-default detail being that it uses an NFS mounted home directory, is that sufficient to repro the issue? If you can point me to the steps necessary to set that up as you have, I could try it out to see if I can repro.

I will have to see with the IT department to try this. 
As for the setup, as far as I know it's an NFS hosted on a remote machine within the same network environment. These NFS home directories are linked to users within the network (i.e. Windows user) and we mount it on the machine we're developing on.
But I can ask for more details so you can reproduce the issue if you would like.

**Comment by magdyabdel** [comment] 2021-07-23 13:12
Any idea on the `~/.cache` part yet? If you require any more information, let me know.

**Comment by magdyabdel** [comment] 2021-07-30 09:50
After another look, I suspect the users to be the problem. 
They come from an Active directory (hence why it's linked to my Windows login), meaning they do not exist within `/etc/passwd`. This might be related to why `vscode-cpptools` under `~/.cache` does not generate. 
I tried as well making a local user with a large _uid_ and _gid_ to see whether there was some id size issue going on. but that's not the case as this user was still able to use cpptools without any problems.

**Comment by magdyabdel** [comment] 2021-08-10 15:14
@Colengms Any idea ?

**Comment by Colengms** [comment] 2021-08-13 20:24
Hi @magdyabdel .  As a work-around, does it work if you specify values for the following, to point to paths not under the user directory?

(in `c_cpp_properties.json`)
```
"browse.databaseFilename": "<path>",
```

(in `settings.json`, in case a similar issue may occur with IntelliSense PCH files)
```
"C_Cpp.intelliSenseCachePath": "<path>"
```

What confuses me is the lack of any errors reported from our file system calls.  Do you see any additional logging related to the issue using the 1.6.0-insiders version of the extension?

Otherwise, next steps would be for us to set up a similar scenario with remotely mounted NFS home directories, and debug into the issue.

**Comment by jhsterling** [comment] 2021-08-30 14:38
We use a setup similar to the original poster's.  In fact I would think it is almost identical.  I have been looking for the magic bullet that will make this work for a few years.  I have never pursued this my self because I just didn't have time.  I do check the github issues from time to time thinking that some one will figure it out.   After reading this I deleted .vscode-server from my home directory,  created a .vscode-server dir on a disk local to the centos machine, created a symbolic link from my home directory on the nfs mount to the .vscode-server dir on the local disk and reloaded the server.   Bam! It seems to be functioning correctly.

**Comment by jhsterling** [comment] 2021-08-30 20:47
Ok.  It worked for about an hour.  Now it is back to not working.

**Comment by sean-mcmanus** [comment] 2021-08-30 20:52
@Colengms Do you understand what @jhsterling is referring to?

@jhsterling Can you explain more about your setup? I'm familiar with a setup in which the remote machine has a .vscode-server folder and that's the only one, so I don't understand how you have multiple .vscode-server folders or where the nfs mount is involved, i.e. what machine do our database/cache files exist on normally versus after the workaround?

It failing to work after an hour is unusual, and implies that it's caused by some change -- one thing to check for would be a dangling cpptools process that has a lock on the database.

**Comment by jhsterling** [comment] 2021-08-31 13:59
@sean-mcmanus  
We have a server on the network that provides nfs volumes.
Our development systems mount the server:/homedirs/username as /home/username
From my laptop I start vscode and connect to the development system via ssh
a directory, .vscode-server, is created in /home/username 

Yesterday I deleted .vscode-server from my home directory, created a .vscode-server directory on a disk that is local to the development machine.   Then I created a symbolic link from my home directory to the .vscode-server directory on the local disk.  Doing this improves access time to the .vscode-server directory.   After reading the above I thought that perhaps the latency involved in nfs accesses was causing an issue.   It did work for a while.    I tried deleting the contents of .vscode-server and re-installing it but it still does not function.

When I start vscode now and watch the output it shows "tag parsing file ...." for quite a few files but then always stops at a specific file.  "tag parsing file: /users/jsterling ......". Just seems to hang there.

**Comment by jhsterling** [comment] 2021-08-31 14:03
There is one process that is pegged at 100% cpu
![image](https://user-images.githubusercontent.com/8131192/131516229-e8fa4d1d-35e8-412a-9388-ab561a48af00.png)

**Comment by sean-mcmanus** [comment] 2021-08-31 21:19
Our tag parser is getting stuck on that file. You should add the path to C_Cpp.files.exclude. It sounds like you might be hitting https://github.com/microsoft/vscode-cpptools/issues/6454 . Or it could just be due to the size of the file.

**Comment by jhsterling** [comment] 2021-09-02 12:52
@sean-mcmanus  Excluding the directories with huge header files improved the parsing situation.  Now most things work most of the time.   Sometimes when you hover over a symbol nothing shows up.  Not even "Loading...".  Then you can move up or down a few lines and hover over a different symbol and it functions correctly.  All of the right click menu items seem to work ok.  Once in a while I have a symbol that when I select "Go to Definition"  I end up at another reference instead of the definition.

**Comment by sean-mcmanus** [comment] 2021-09-02 17:50
When you hover over a symbol and nothing shows up, can you check the C/C++ log for a "crash" message? Are you able to provide any repro example? Go to Definition could be failing due to some detail of the symbol that isn't handled correctly, so we'd probably need some sample code that illustrates the problem.

**Comment by magdyabdel** [comment] 2021-09-03 09:23
@Colengms Apparently, when I try a path (for `browse.databaseFilename`) outside the home directory like you suggested, it works. Does this help together with jhsterling's solution to identify the problem regarding NFS mounted home directories?

**Closed as completed** 2022-01-23 11:16 UTC
Labels: Language Service, more info needed
