### ISSUE TITLE
"C++ (Windows)" option is shown on non-Windows platforms

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#6912] opened 2021-02-05 22:47 UTC
Using `create a launch.json file` on Mac OS results in a `Select Environment` menu that includes `C++ (Windows)`.  We should not be offering this option on non-Windows platforms.  This only happens when no source file is open.  When a source file is not open, this menu instead includes `Chrome (preview)`, `Edge: Launch`, `Node.js (legacy)` and `Node.js (preview)` options.  Shouldn't this list of options be the same regardless of whether a source file is open?

The same issue repro's with Codespaces, which is Linux-hosted and browser based.

**Comment by michelleangela** [comment] 2021-02-05 22:49
Is this a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6862?

**Closed as completed** 2021-02-05 22:54 UTC
Labels: bug, duplicate, Language Service, tasks/build/debug
