### ISSUE TITLE
Don't support to Chinese path when C++ debug with some breakpoints, like blew

### ISSUE THREAD

**Issue by ai-chen2050** [microsoft/vscode-cpptools#1981] opened 2018-05-11 16:20 UTC
Issue Type: <b>Bug</b>

1、path contain chinese 
2、Cpp file has some breakppint 
3 、debug F5 , ## Can't find this path that contain chinese some name 

![11](https://user-images.githubusercontent.com/27693952/39935024-3db378a0-557a-11e8-819a-9b10bc13ae63.PNG)

Extension version: 0.17.0
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.57GB (3.56GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|57%|

</details>

**Comment by WardenGnaw** [comment] 2018-05-14 19:54
This is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/602

**Closed as completed by WardenGnaw** 2018-05-14 19:54 UTC
Labels: duplicate, debugger
