### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by imatyukin** [microsoft/vscode-cpptools#3590] opened 2019-05-06 22:07 UTC
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.1`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/igor/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment] 2019-05-06 22:17
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/3213 . Our next release is expected to fix this.

**Closed as completed by sean-mcmanus** 2019-05-06 22:17 UTC
Labels: duplicate
