### ISSUE TITLE
Add the support of Data Breakpoints in C++ debugger extension

### ISSUE THREAD

**Issue by zarathosss** [microsoft/vscode-cpptools#7107] opened 2021-03-04 15:32 UTC
From release 1.38, VSCode added the support of Data Breakpoints. Seems this is not supported on C++ langage yet. Is there a plan to add the support of Data Breakpoints in C++ debugger extension ?

**Comment by WardenGnaw** [comment] 2021-03-04 18:08
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/1410

**Closed as completed by WardenGnaw** 2021-03-04 18:08 UTC
Labels: duplicate, debugger
