### ISSUE TITLE
IntelliSense sometimes missing inner class definitions

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-cpptools#4622] opened 2019-11-16 16:40 UTC
The following code is displayed fine whenever C++ file is just opened:

```
class OuterClass
{
public:
    class InnerClass{
    };
    InnerClass returnInner();
};
OuterClass::InnerClass OuterClass::returnInner() {
}
```
If i edit the return type to be wrong, we (predictably) get errors about incorrect type, and about declaration/definition mismatch:

![2019-11-16_16-37-36](https://user-images.githubusercontent.com/37181601/68996260-800e7c80-088f-11ea-933d-b4462424fad4.png)

However, if i then edit the definition back, the error about the type goes away, but the declaration/definition mismatch error stays:

![2019-11-16_16-39-20](https://user-images.githubusercontent.com/37181601/68996278-b0561b00-088f-11ea-8d10-cada779667c2.png)

This problem only happens with inner classes. Using latest Insiders edition.

**Comment by Colengms** [comment] 2019-11-18 18:59
Hi @anatolyburakov .  Thanks for reporting this.

This looks similar to https://github.com/microsoft/vscode-cpptools/issues/3883 .  It looks like a fragment parsing issue, as editing the file at global scope (to trigger a full reparse) clears up the squiggle.

**Comment by bobbrow** [comment] 2020-02-06 22:51
Closing as duplicate of #3883

**Closed as completed by bobbrow** 2020-02-06 22:51 UTC
Labels: bug, duplicate, Language Service
