### ISSUE TITLE
Variable colourisation stopping part way through a variable

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode-cpptools#3901] opened 2019-07-09 08:37 UTC
**Type: LanguageService**

Variable colour highlighting stops part way through a variable. For example, if I enter:
int Class::VariableName[];
I get
![image](https://user-images.githubusercontent.com/17859340/60872556-c6dace80-a22c-11e9-9762-842e4eda2944.png)

With the extension disabled, I get
![image](https://user-images.githubusercontent.com/17859340/60872753-2c2ebf80-a22d-11e9-87f3-13c3bcf444a4.png)

Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

- C/C++ Extension Version:
Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 0.24.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
Put the following code in a C++ file:
class Class
{

}

int Class::VariableName[];

**Expected behaviour**
The whole of "VariableName" should be coloured.

**Comment by jason-watkins** [comment] 2019-07-09 14:52
I haven't observed the above, but I'm having all kinds of colorization issues with C++ right now that I assume must stem from the same source.

As another data point, the extension currently seems to be unable to correctly tokenize (some?) user-defined types. The screenshot below shows that the entire line of the function body up to the `=` is a single TextMate token.

![tokenize_fail](https://user-images.githubusercontent.com/1038224/60898784-3dbc9b00-a21e-11e9-9857-88c71ea49203.png)

Here's one more that I'm unable to reproduce in a discrete test file. Note that `std` is tokenized correctly and the TM scope inspector reports a foreground of `#F0F0F0` (which is correct), but the token is not actually that color.

![image](https://user-images.githubusercontent.com/1038224/60899801-f505e180-a21f-11e9-9836-f70c242af14e.png)

**Comment by Colengms** [comment] 2019-07-09 17:47
@BillDenton , This repros in VS, so appears to be an issue with VS IntelliSense.  I've opened an issue against VS.  https://developercommunity.visualstudio.com/content/problem/638776/incorrectincomplete-colorization-for-c-global-vari.html  Feel free to up-vote it.

@jason-watkins , I'm not able to repro these issue, per se.  Rather, I think they are working as expected.  With C_Cpp.enhancedColorization enabled, semantic tokens are colored based on IntelliSense, not the Text Mate grammar (whereas the TM scope inspector would show the color that would be chosen based on the grammar).  I think you are seeing these correctly colored as semantic tokens (Type and Namespace: https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/colorization.md ), and your theme is resolving them to different colors than you are expecting.  You could customize colors for semantic tokens.  Disabling enhancedColorization would restore the original behavior.

**Comment by BillDenton** [comment] 2019-07-09 17:54
@Colengms I can't access the link, so can't up vote. I'm not using VS for editing (am using command line compiler and debugger from VS). Does VS and VS Code share use of some Microsoft internal code? Any idea how and when this will get fixed? It is only a minor irritation.

**Comment by Colengms** [comment] 2019-07-09 18:00
@BillDenton , Yes, the C/C++ Extension for VS Code leverages VC++ IntelliSense which is code shared with VS.  Generally, if the issue repros in VS, we route it to the VS team.

The feedback system seems to be a bit sluggish today.  You might try the link again after several minutes.

**Comment by jason-watkins** [comment] 2019-07-09 18:03
@Colengms You appear to be correct. Was that option just added? I just encountered this behavior this morning.

You mention that it's possible to customize colors for semantic tokens. Where are those settings located/documented? I'm not seeing it in the extension settings.

**Comment by Colengms** [comment] 2019-07-09 18:17
@jason-watkins This feature was newly added in our latest release, 0.24.0, which went out last week.  It's been available in insider builds of the extension for a few weeks.

enhancedColorization leverages the existing system for theming and color customization.  We've associated arbitrary TM scopes with the semantic tokens.  A good starting point is here: https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/colorization.md

Documentation on theming and overriding colors via settings, is here: https://code.visualstudio.com/docs/getstarted/themes

**Comment by sean-mcmanus** [comment] 2019-07-09 21:09
@BillDenton @Colengms The issue was filed as "Microsoft Internal" -- I've moved it to be public so it should be upvotable now if you have a Microsoft account.

**Comment by BillDenton** [comment] 2019-07-10 07:42
@sean-mcmanus  @Colengms I've upvoted it now.

**Comment by BillDenton** [comment] 2021-03-17 09:34
Any updates on this issue?
Testing:
Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.17763

Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 1.2.2
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

Name: C/C++ Themes
Id: ms-vscode.cpptools-themes
Description: UI Themes for C/C++ extension.
Version: 1.0.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-themes

Name: Better C++ Syntax
Id: jeff-hykin.better-cpp-syntax
Description: The bleeding edge of C-like syntaxes
Version: 1.15.5
Publisher: Jeff Hykin
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax

Colour theme: Dark+ (default dark)

Text
class Class
{

}

int Class::VariableName[];

At the end of a ".cpp" file (lots of other code further up the file):
![image](https://user-images.githubusercontent.com/17859340/111445796-a6eaf600-8703-11eb-8e55-0d52acce70c6.png)

At the end of a ".hpp" file (lots of other code further up the file):
![image](https://user-images.githubusercontent.com/17859340/111445705-9470bc80-8703-11eb-8b52-fbe1484ca33c.png)

So colourisation stops partway through the variable in ".hpp" and doesn't happen at all in ".cpp". Also in ".hpp" the "class" (type) part isn't coloured correctly.

**Comment by sean-mcmanus** [comment] 2021-03-17 18:15
@BillDenton It's considered low priority because (1) it's an "old" bug, (2) low upvotes, and (3) the code is invalid and presumed to be a temporary issue that gets fixed after more user edits. If you can find a case where the code is valid/non-temporary that might increase the priority.

**Comment by BillDenton** [comment] 2021-03-17 18:18
@sean-mcmanus I saw the issue in our product code. Then I simplified it and removed the details so I could share it.

**Comment by sean-mcmanus** [comment] 2021-03-17 18:41
@BillDenton Yeah, if you can add some dummy code such that it is still compileable that could help. The repro case provided is referencing a variable in a class that doesn't exist in that class yet. It's possible your scenario could have a different root cause for the same symptom (i.e. some parsing error that is causing our parser to think the variable is not defined).

**Comment by bobbrow** [comment] 2024-11-27 18:57
I don't see any partial colorization in the latest versions of the extension. I do see a red squiggle under the token instead. Is the example expected to compile? It didn't look like any of the main 3 compilers supported that. https://godbolt.org/z/d16Yjb4Go

**Closed as not planned by bobbrow** 2024-11-27 18:57 UTC
Labels: bug, Language Service, external, Visual Studio, Feature: Colorization

**Comment by BillDenton** [comment] 2024-11-28 16:41
@bobbrow Thanks. I've rechecked and can't reproduce the original problem. If I see a similar issue I'll re-open the ticket.
