### ISSUE TITLE
syntax check incorrect for some C++ library

### ISSUE THREAD

**Issue by yuanyangwangTJ** [microsoft/vscode-cpptools#8487] opened 2021-12-05 02:59 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: win10
- VS Code Version: latest
- C/C++ Extension Version: v1.8.0
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
   I use a C++ `json` library -- `nlohmann/json`, which is written by modern C++, and I install it by `msys2` on win. But when I use it, vscode can't find all member function of this library, just part of it. Actually, my code can be compiled and run. It's terrible to see errors that do not exist in code. May it's my fault for `intelliSense` configuration? It's worth mentioning that when I open my code by vim editor with a autocomplete plugin `YouCompleteMe`, there is no error. So where is the problem?   

**Expected behavior**

Vscode with C++ extension can find correct API and member function of library.

**Code sample and logs**

- Code sample
```C++
#include <iostream>
#include <nlohmann/json.hpp>

using json = nlohmann::json;

int main()
{
    json j;
    j.push_back("foo");
    return 0;
}
```

- Configurations in `c_cpp_properties.json`
```json
{
    "name": "MSYS2",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "C:/msys64/mingw64/bin/g++.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-gcc-x64",
    "mergeConfigurations": false
}
```
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
class "nlohmann::basic_json<std::map, std::vector, std::string, bool, int64_t, uint64_t, double, std::allocator, nlohmann::adl_serializer, std::vector<uint8_t, std::allocator<uint8_t>>>" has no member "push_back"
```

**Screenshots**

![image-20211205105759926](https://raw.githubusercontent.com/yuanyangwangTJ/Picture/master/img/20211205105807.png)

**Additional context**

**Comment by sean-mcmanus** [comment] 2021-12-06 23:38
The bug doesn't repro with 1.7.1.

This is most likely a duplicate of https://github.com/microsoft/vscode-cpptools/issues/8475 .

**Comment by yuanyangwangTJ** [comment] 2021-12-07 02:18
> The bug doesn't repro with 1.7.1 -- a workaround is to change C_Cpp.updateChannel to "Default" instead of "Insiders" to downgrade to 1.7.1.
> 
> This is most likely a duplicate of #8475 .

Thanks, v1.7.1 is ok. Hope this extension can support more C++ feature in v1.8 !

**Comment by sean-mcmanus** [comment] 2021-12-13 16:03
@yuanyangwangTJ FYI, you can add "-fno-ms-extensions" to compilerArgs with 1.8.0-insiders2 to work around this bug, which was "triggered" by a 1.8.0-insiders bug fix that added -fms-extensions (which is the default for mingw gcc).

**Closed as completed** 2021-12-19 06:42 UTC
Labels: bug, Language Service, fixed, regression

**Comment by sean-mcmanus** [comment] 2022-01-19 19:33
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).

Unless you're explicitly adding -fms-extensions, in which case that bug fix is still pending (https://github.com/microsoft/vscode-cpptools/issues/8353 ).

**Comment by sean-mcmanus** [comment] 2022-01-28 17:03
The underlying issue is now fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.1 , i.e. you can add back -fms-extensions -- however you may still hit other bugs when -fms-extensions are used (https://github.com/microsoft/vscode-cpptools/issues/8353).
