### ISSUE TITLE
Intellisense does not seem to correctly resolve private inheritance.

### ISSUE THREAD

**Issue by mxdh** [microsoft/vscode-cpptools#3168] opened 2019-02-14 03:30 UTC
Issue Type: <b>Bug</b>

Sorry,my English is not good.
```
"intelliSenseMode": "gcc-x64",
"cStandard": "c99",
"cppStandard": "c++98"
```

```
class MonotoneQueue : private deque<pair<int, int> >
{
  public:
	MonotoneQueue(bool (*_cmp)(int, int)) : cmp(_cmp) {}
	void push(int k, int num)
	{
		while (!cmp(back().second, num)) pop_back();
		push_back(make_pair(k, num));
	}
	void pop(int l)
	{
		update(l);
		pop_front();
	}
	int top(int l)
	{
		update(l);
		return front().second;
	}

  private:
	bool (*cmp)(int, int);

	void update(int l)
	{
		while (front().first < l) pop_front();
	}
} q;
```

Enter "q.", the IntelliSense prompt contains "push_back", but "deque" is a private inheritance.

Extension version: 0.21.0
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

**Comment by sean-mcmanus** [comment] 2019-02-14 03:42
This is Visual Studio bug https://developercommunity.visualstudio.com/content/problem/203146/intellisense-doesnt-honour-private-inheritance.html . Unfortunately, they closed it as "low priority". I can see if I can reopen it, so more upvotes can occur.

**Comment by sean-mcmanus** [comment] 2019-02-14 04:07
I've re-activated the bug -- please upvote it so they can give it higher priority.

**Comment by mxdh** [comment] 2019-02-15 02:10
It seems that all problems about vscode-cpptools that caused by Visual Studio are closed as low priority.
The issues with "Visual Studio" tag are all open on GitHub.

**Comment by sean-mcmanus** [comment] 2019-02-15 02:43
I got it to be re-activated (they had closed it 5 hours after I reactivated it, but I got it re-reactivated again). If you see other issues tagged "Visual Studio" that the linked issues are closed and you want to upvote them, then I could get them re-activated so upvoting is possible. I think I remember seeing just 2 issues currently closed as "low priority" when I reviewed them yesterday -- the VS team closed around 17 old bugs I had reported, but most of the bugs I didn't care about anymore anyway (they were not VS Code related).

**Comment by sean-mcmanus** [comment] 2019-02-15 03:54
@mxdh Also, VS has fix a lot of bugs for us, but previously we were marking them as "parser", but there were some parser bugs caused by us so I created the new "Visual Studio" label to make it easier to find those (I didn't re-tag the Closed issues): See https://github.com/Microsoft/vscode-cpptools/issues?q=label%3Aparser+is%3Aclosed .

**Comment by mxdh** [comment] 2019-02-15 04:23
I'm sorry, I got it wrong.
Thank you very much.

**Comment by sean-mcmanus** [comment] 2019-04-10 08:48
The IntelliSense error is fixed with the latest Insiders: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.22.2-insiders .

**Closed as completed** 2019-05-08 01:02 UTC
Labels: bug, Language Service, fixed, Visual Studio
