### ISSUE TITLE
Incorrect linting in certain cases with explicitly typed lambdas.

### ISSUE THREAD

**Issue by overrule** [microsoft/vscode-cpptools#10234] opened 2022-12-06 23:48 UTC
### Environment

- OS and Version: Windows 10, 10.0.19Build 19044
- VS Code Version: 1.73.1
- C/C++ Extension Version: 1.12.4

When a lambda has an explicit return parameter with no space in between the type and opening curly bracket, It colors commas, semicolons, operators and constants as primitive types instead of the actual expression.

An example would be
```
#include <functional>
#include<string>
int main() {
    using namespace std;
    [&]() -> void{
        int x = 0;
        int y = 1;
        if(x == y){}
        std::plus<int>()(x, y);
        std::string s = "hi";
    };
}
```
The following does not contain the bug
```
#include <functional>
#include<string>
int main() {
    using namespace std;
    [&]() -> void {
        int x = 0;
        int y = 1;
        if(x == y){}
        std::plus<int>()(x, y);
        std::string s = "hi";
    };
}
```
The only change is in the `-> void {` expression.

### Bug Summary and Steps to Reproduce

Bug Summary: Incorrect Linting on certain codes

Steps to reproduce:
1. Create a cpp file
2. Use a lambda with an explicit return type. Do not put a space between the return type and opening bracket.
3. Write some functionality inside the lambda, such as `2 + 3`.

### Expected behavior

The constants and other operators should be linted as usual.

### Code sample and Logs

```cpp
#include <functional>
#include<string>
int main() {
    using namespace std;
    [&]() -> void{
        int x = 0;
        int y = 1;
        if(x == y){}
        std::plus<int>()(x, y);
        std::string s = "hi";

    };
}
```
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "intelliSenseMode": "windows-gcc-x86",
            "compilerPath": "C:/Programs/gcc11-64-winlibs/bin/g++.exe",
            "cppStandard": "c++20"
        }
    ],
    "version": 4
}
```
```
-------- Diagnostics - 12/6/2022, 5:38:37 PM
Version: 1.12.4
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "intelliSenseMode": "windows-gcc-x86",
    "compilerPath": "C:/Programs/gcc11-64-winlibs/bin/g++.exe",
    "cppStandard": "c++20",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "cStandard": "c17",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\Aditya Jain\My codes\Atcoder\AGC059\B.cpp ]:
    C:\Users\Aditya Jain\My codes\Atcoder\AGC059\B.cpp
[ C:\Users\Aditya Jain\My codes\Atcoder\AGC059\bug.cpp ]:
    C:\Users\Aditya Jain\My codes\Atcoder\AGC059\bug.cpp
Translation Unit Configurations:
[ C:\Users\Aditya Jain\My codes\Atcoder\AGC059\B.cpp ]:
    Process ID: 22948
    Memory Usage: 332 MB
    Compiler Path: C:/Programs/gcc11-64-winlibs/bin/g++.exe
    Includes:
        C:\PROGRAMS\GCC11-64-WINLIBS\INCLUDE\C++\11.2.0
        C:\PROGRAMS\GCC11-64-WINLIBS\INCLUDE\C++\11.2.0\X86_64-W64-MINGW32
        C:\PROGRAMS\GCC11-64-WINLIBS\INCLUDE\C++\11.2.0\BACKWARD
        C:\PROGRAMS\GCC11-64-WINLIBS\LIB\GCC\X86_64-W64-MINGW32\11.2.0\INCLUDE
        C:\PROGRAMS\GCC11-64-WINLIBS\INCLUDE
        C:\PROGRAMS\GCC11-64-WINLIBS\LIB\GCC\X86_64-W64-MINGW32\11.2.0\INCLUDE-FIXED
        C:\PROGRAMS\GCC11-64-WINLIBS\X86_64-W64-MINGW32\INCLUDE
        C:\MINGW\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++20
    IntelliSense Mode: windows-gcc-x86
    Other Flags:
        --g++
        --gnu_version=110200
[ C:\Users\Aditya Jain\My codes\Atcoder\AGC059\bug.cpp ]:
    Process ID: 7148
    Memory Usage: 126 MB
    Compiler Path: C:/Programs/gcc11-64-winlibs/bin/g++.exe
    Includes:
        C:\PROGRAMS\GCC11-64-WINLIBS\INCLUDE\C++\11.2.0
        C:\PROGRAMS\GCC11-64-WINLIBS\INCLUDE\C++\11.2.0\X86_64-W64-MINGW32
        C:\PROGRAMS\GCC11-64-WINLIBS\INCLUDE\C++\11.2.0\BACKWARD
        C:\PROGRAMS\GCC11-64-WINLIBS\LIB\GCC\X86_64-W64-MINGW32\11.2.0\INCLUDE
        C:\PROGRAMS\GCC11-64-WINLIBS\INCLUDE
        C:\PROGRAMS\GCC11-64-WINLIBS\LIB\GCC\X86_64-W64-MINGW32\11.2.0\INCLUDE-FIXED
        C:\PROGRAMS\GCC11-64-WINLIBS\X86_64-W64-MINGW32\INCLUDE
        C:\MINGW\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++20
    IntelliSense Mode: windows-gcc-x86
    Other Flags:
        --g++
        --gnu_version=110200
Total Memory Usage: 458 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 3141
```

### Screenshots

![image](https://user-images.githubusercontent.com/42273932/206050031-bb02e711-0f39-4829-a8a3-04a7de773a23.png)
![image](https://user-images.githubusercontent.com/42273932/206050083-80383506-f059-453b-b97f-70931e3fb673.png)

**Comment by sean-mcmanus** [comment] 2022-12-08 00:55
This bug repros with our extension disabled. You should report a bug at https://github.com/jeff-hykin/better-cpp-syntax/issues which is where the syntactic colorization comes from. It may be a duplicate of https://github.com/jeff-hykin/better-cpp-syntax/issues/405

**Closed as not planned by sean-mcmanus** 2022-12-08 00:55 UTC
Labels: external
