### ISSUE TITLE
Unable to open throw.cpp

### ISSUE THREAD

**Issue by rbyshko** [microsoft/vscode-cpptools#5637] opened 2020-06-12 14:30 UTC
Type: Debugger

When running an executable in Debug mode I get the following error:

`Unable to read file 'd:\agent\_work\4\s\src\vctools\crt\vcruntime\src\eh\throw.cpp' (Unknown (FileSystemError): Error: Unknown system error -214427238: Unknown system error -214427238, stat 'd:\agent\_work\4\s\src\vctools\crt\vcruntime\src\eh\throw.cpp').`

- OS and Version: Windows 10 Enterprise, Version 1909
- VS Code Version: 1.46.0
- C/C++ Extension Version: 0.28.3
- cl.exe 1: ...\2019\Enterprise\VC\Tools\MSVC\14.26.28801\bin\Hostx86\x86\cl.exe
- cl.exe 2: ...\2019\Enterprise\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe

**To Reproduce**
`example.cpp`
```
#include <stdexcept>

int main(void)
{
     throw std::invalid_argument("Your agruments were invalid.");
}
```
`launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "cl.exe - Build and debug active file",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "preLaunchTask": "C/C++: cl.exe build active file",
        }
    ]
}
```
See als screenshot of the vscode window as error appears.
![image](https://user-images.githubusercontent.com/35375029/84513103-42f55600-acc9-11ea-950d-717e3eeef1a2.png)

**Comment by WardenGnaw** [comment] 2020-06-12 23:12
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/811

**Comment by rbyshko** [comment] 2020-06-12 23:17
@WardenGnaw Are you sure? #811 is gcc/gdb related. This one is msvc related.

**Comment by WardenGnaw** [comment] 2020-06-12 23:27
Ah sorry, its a bit of both #811 and #5516

There can be a list of files to reduce the emphasis of "Unable to show file" and skip MSVC Standard C++ files.

**Comment by rbyshko** [comment] 2020-06-14 09:39
How about fixing the strange and wrong path to a correct one, so I can actually step through library sources? Is that possible?

**Comment by WardenGnaw** [comment] 2020-06-15 19:28
If you have the sources downloaded, you can redirect the path using `sourceFileMap` in your `launch.json`

E.g.
```
"sourceFileMap": {
   "d:\agent\_work\4\s\src\vctools\crt\runtime\src": "C:\MyPath\To\VCRuntime\src"
}
```

**Comment by evakili** [comment] 2020-07-08 07:22
Could we have an option to open the file in such scenarios (as in VS)? There is a **Create File** button that IMO is useless.

**Closed as not planned** 2024-07-11 16:58 UTC
Labels: duplicate, debugger

**Comment by TejasPersonal** [comment] 2025-02-19 13:10
Same issue help
