### ISSUE TITLE
c++ relative include error on macos 10.13.6

### ISSUE THREAD

**Issue by idealvin** [microsoft/vscode-cpptools#2544] opened 2018-09-22 12:28 UTC
In my `log.cc`
```cpp
#include "../flag/flag.h"
```

Then go to definition of `"../flag/flag.h"`, resulting in multiple definitions:

<img width="247" alt="3" src="https://user-images.githubusercontent.com/12691466/46239030-53667f80-c3c5-11e8-9b30-91cd3eab475c.png">
<img width="396" alt="1" src="https://user-images.githubusercontent.com/12691466/46239027-4f3a6200-c3c5-11e8-9c8f-1509fe5b7eff.png">
<img width="910" alt="2" src="https://user-images.githubusercontent.com/12691466/46239028-51042580-c3c5-11e8-8b5f-a7c4d9a6efff.png">

**Comment by bobbrow** [comment] 2019-10-18 21:51
This looks like a duplicate of #2564

**Closed as completed by bobbrow** 2019-10-18 21:51 UTC
Labels: bug, Language Service

**Comment by sean-mcmanus** [comment] 2020-04-29 03:42
We believe this is fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders -- let us know if it's not.
