### ISSUE TITLE
Header-only fallback occurs instead of using compileCommands configuration

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6163] opened 2020-09-18 02:17 UTC
I enabled debug logging and what I got is very strange. The correct define is actually sent in the source file that uses the header (so I know the compile_commands.json is being resolved properly):

```
sending compilation args for -SNIP-
  -SNIP-
  define: RP_WINDOWS
  -SNIP-
```

It then says `Shutting down IntelliSense server: -SNIP-` for that translation unit.

Immediately afterwards, it processes the header with essentially empty compile args.

```
sending compilation args for -SNIP-
  include: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include
  include: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\atlmfc\include
  include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um
  include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt
  include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared
  include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt
  include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt
  other: --header_only_fallback
  stdver: ms_c++17
  intelliSenseMode: msvc-x64
```

meaning the header is being analyzed independently of the source file that includes it. The source file, has red-squigglies everywhere despite the engine reporting no compilation issues with it. Furthermore, it later tries to post `Attempting to get defaults from compiler found on the machine: '/usr/bin/gcc'` ...

Note: I've tried changing compilers, windows, linux, fresh reinstall of visual studio 2019 on top of vs code. I'm not sure if I should be expecting this to work or not?

_Originally posted by @jeremyong in https://github.com/microsoft/vscode-cpptools/issues/5937#issuecomment-694585703_

**Comment by sean-mcmanus** [comment] 2020-09-18 02:18
@jeremyong Are you opening a source file or a header file? Does IntelliSense work for a source file?

It sounds like there's some error associating the header file with a source file. One thing worth trying is the C/C++: Reset IntelliSense Database command, because source/header associations are stored there.

**Comment by jeremyong** [comment] 2020-09-18 02:23
@sean-mcmanus The errors persist on the source file despite the log output indicating that the define was found with the correct compile command (so the error is on both source and header).

I've tried resetting the database, rescanning, reloading the whole thing, clean reconfigure, and combinations of the above.

**Comment by sean-mcmanus** [comment] 2020-09-18 02:34
Can you provide some of the output of C/C++: Log Diagnostics? That will show how the TU is being constructed.

**Comment by Colengms** [comment] 2020-10-28 21:44
@jeremyong Are you still seeing this issue?

What you describe (the shutting down of a source file TU and use of a header-only TU) is the behavior we would expect if we discovered that the source file we selected does not actually include the header file, after defines have been resolved.

Are you seeing that `RP_WINDOWS` is not defined when opening that source file as well, or is that issue only within the header file?  If only within the header file, are there other defines gating the inclusion of that header file by the source file?

You might also try first opening a source file that definitely does include that header, then opening the header.  It should use that already-open source as the TU for the header.  You might also try adding an entry for the header in your `compile_commands.json`.

If that does not help resolve the issue, could you provide all of the following information?  That would help us better understand what is actually happening on your system:

 * The content of your `c_cpp_properties.json` file.
 * The output of the `Log Diagnostics` command, after the repro, having both the source file and the header file involved open.
 * The output of your C/C++ output channel, with `"C_Cpp.loggingLevel": "Debug"` set, leading up to the repro.
 * The entry in your `compile_commands.json` for the source file.
 * Any `C_Cpp` settings that might be related.

**Comment by michelleangela** [comment] 2020-12-09 18:43
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 18:43 UTC
Labels: bug, Language Service, more info needed, not reproing, Feature: Compile Commands
