### ISSUE TITLE
gdb error: Unrecognized format of field "id" in result

### ISSUE THREAD

**Issue by huili80** [microsoft/vscode-cpptools#2502] opened 2018-09-10 17:17 UTC
trace logging output as follows (sorry for posting this again as a new issue, but the original issue #2244 is not getting any response ever since it was marked as more info needed).

E output: {"category":"stderr","output":"ERROR: Error while trying to enter break state. Debugging will now stop. Unrecognized format of field "id" in result: result-class: done\r\nthreads: [{id=1,target-id=Thread 0x7f1f2a213740 (LWP 34914),name=...,frame={level=0,addr=0x00000000009e9b70,func=...,args=[{name=this,value=0x7fff0324a3c0},{name=m,value=... = {...}}],file=...,fullname=...,line=127},state=stopped,core=8}]\r\ncurrent-thread-id: 1\r\n\n","data":null,"type":"output"}
ERROR: Error while trying to enter break state. Debugging will now stop. Unrecognized format of field "id" in result: result-class: done
threads: [{id=1,target-id=Thread 0x7f1f2a213740 (LWP 34914),name=...,frame={level=0,addr=0x00000000009e9b70,func=...,args=[{name=this,value=0x7fff0324a3c0},{name=m,value=... = {...}}],file=...,fullname=...,line=127},state=stopped,core=8}]
current-thread-id: 1
E output: {"category":"console","output":"Debugger has disconnected from the program ''.\n","data":null,"type":"output"}
Debugger has disconnected from the program ''.
E exited: {"exitCode":0,"type":"exited"}
E terminated: {"type":"terminated"}
E output: {"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.50719.1","VS.Diagnostics.Debugger.HostVersion":"14.0.50719.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":0},"type":"output"}
C disconnect: {"restart":false}
R: {"success":true,"message":null,"request_seq":8,"command":"disconnect","body":null,"running":false,"refs":null,"seq":0,"type":"response"}

**Comment by pieandcakes** [comment] 2018-09-11 22:27
@huili80 Its marked need more info because we need a solid repro so that we can try fixes on it. If you have a solid repro that I can use to fix the problem, then please post it there.

**Comment by pieandcakes** [comment] 2018-09-11 22:27
Duplicate of #2244

**Closed as completed by pieandcakes** 2018-09-11 22:27 UTC
Labels: duplicate, debugger
