### ISSUE TITLE
Step before in debugging mode

### ISSUE THREAD

**Issue by amiralisalimi** [microsoft/vscode-cpptools#3913] opened 2019-07-11 11:48 UTC
It would be awesome if your extension provided the feature `Step Before` in debugging mode, which would take back the current line (colored in yellow) to the last line (Actually opposite of `Step Over`).

I first opened this issue [here](https://github.com/microsoft/vscode/issues/77185), and they said the problem is the extension you use to debug, and that vscode already provides this feature for the extensions that support it.

**Comment by pieandcakes** [comment] 2019-07-11 17:57
This is a duplicate of #2130 to support reverse debugging.

**Closed as completed** 2019-07-11 17:57 UTC
Labels: duplicate, debugger
