### ISSUE TITLE
C++17 template argument deduction and structured binding type deduction

### ISSUE THREAD

**Issue by narutse** [microsoft/vscode-cpptools#2101] opened 2018-06-08 00:29 UTC
Type: LanguageService

I encountered two intellisense issues that seem to be in conflict with the C++17 standards:

The first one is that the C++ extension considers class template argument deduction an error (http://en.cppreference.com/w/cpp/language/class_template_argument_deduction) with red squiggles. Below is the screenshot:
![template argument](https://user-images.githubusercontent.com/15129634/41132679-0a0af21c-6a88-11e8-90c9-07758ae26e93.png)
This code compiles in major compilers with c++17 standards. I'm pretty sure I have the c++17 standard on for intellisense, as it is on by default in the cpp properties file, and structured bindings work.

The second issue is the type deduction in the auto [..., ...] structured bindings. Below is the screenshot:
![structured binding](https://user-images.githubusercontent.com/15129634/41132793-9ff71b5c-6a88-11e8-9191-10d8c9ac154a.png)
Variable a here should be of type int instead of int&. I checked with gcc and clang by tricking them to print out the type through template compiler errors.

- OS and Version: Manjaro Linux
- VS Code Version: 1.24.0
- C/C++ Extension Version: 0.17.4

**Comment by sean-mcmanus** [comment] 2018-06-08 01:38
Thanks for reporting this. I'm able to repro the problems.

**Comment by sean-mcmanus** [comment] 2018-07-12 00:40
The bogus error will be fixed in our pending 0.17.7-Insiders update, but the "int &" bug still repros (even with VS 2017), so I created a new bug for that: https://github.com/Microsoft/vscode-cpptools/issues/2256 .

**Closed as completed** 2018-07-19 21:55 UTC
Labels: bug, Language Service, fixed, parser

**Comment by sean-mcmanus** [comment] 2018-07-23 23:48
@narutse The int& got resolved as "by design" -- see https://github.com/Microsoft/vscode-cpptools/issues/2256 and https://developercommunity.visualstudio.com/content/problem/229224/intellisense-displays-wrong-type-for-structed-bind.html .
