### ISSUE TITLE
"Go To Symbol" opens local cache file instead of remote file when using ssh remote extension

### ISSUE THREAD

**Issue by JohnRThomas** [microsoft/vscode-cpptools#7940] opened 2021-08-09 21:03 UTC
Bug type: General

**Describe the bug**
- OS and Version: OS: Darwin x64 20.5.0
- VS Code Version: Version: 1.59.0 (Universal)
- C/C++ Extension Version:v 1.5.1
- Other extensions you installed (and if the issue persists after disabling them): Remote SSH

When using Remote SSH to access my remote C++ project, Cmd+clicking a symbol opens the wrong file.

For example, I have two files `src/foo/bar.hpp` and `src/foo/bar.cpp`:

.hpp File:
```
class Bar {
   Bar::Bar();
}
```
.cpp File:
```
Bar::Bar() {}
```

When used within bar.hpp, I would expect the "Go To Symbol" feature to open the file `src/foo/bar.cpp`, however, it opens `/local/home/<user>/remote_project/src/foo/bar.cpp`.

This happens even if src/foo/bar.cpp is in an open editor and results in BOTH files being opened.

**Expected behavior**
Open `src/foo/bar.cpp`, not `/local/home/<user>/remote_project/src/foo/bar.cpp`

**Comment by michelleangela** [comment] 2021-08-10 20:04
@johnkemnetz 

Could you provide the OS of the remote machine? Can you also provide logs from the language server when the issue occurs? See instructions https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server.

**Comment by v-ericawu** [comment] 2021-08-11 10:00
@JohnRThomas When I select "Go To Symbol in Workspace", "src/foo/bar.cpp" is opened:
![issue](https://user-images.githubusercontent.com/78774400/129009375-ceb5f4b3-7472-482d-8a20-7672858a3f09.gif)
![image](https://user-images.githubusercontent.com/78774400/129009983-82b128f3-de97-4b98-900d-69c2a061b290.png)
If my steps are incorrect, Could you provide us with your demo project and specific repro steps?

**Comment by JohnRThomas** [comment] 2021-08-16 19:46
Remote OS: RHEL x64

https://user-images.githubusercontent.com/2058899/129620418-a3d6c265-3bf6-43f2-9f6b-97cd6252ff6b.mov

I would expect it to open ./foo.hpp, but it opens /local/home/thomasjr/vs-test/foo.hpp which is not on the remote machine.

I see IntelliSense scanning both files:
```
Queueing IntelliSense update for files in translation unit of: /local/home/thomasjrmasjv/vs-test/foo.cpp
Error squiggle count: 2
Update IntelliSense time (sec): 0.293
Checking for syntax errors: file:///local/home/thomasjr/vs-test/foo.cpp
Queueing IntelliSense update for files in translation unit of: /local/home/thomasjr/vs-test/foo.cpp
Error squiggle count: 2
terminating child process: 63014
Update IntelliSense time (sec): 0.263
idle loop: reparsing the active document
Checking for syntax errors: file:///home/thomasjr/vs-test/foo.cpp
Queueing IntelliSense update for files in translation unit of: /local/home/thomasjr/vs-test/foo.cpp
Error squiggle count: 3
Update IntelliSense time (sec): 0.253
idle loop: reparsing the active document
Checking for syntax errors: file:///home/thomasjr/vs-test/foo.cpp
Queueing IntelliSense update for files in translation unit of: /local/home/thomasjr/vs-test/foo.cpp
Error squiggle count: 2
Update IntelliSense time (sec): 0.254
idle loop: reparsing the active document
Checking for syntax errors: file:///home/thomasjr/vs-test/foo.hpp
Queueing IntelliSense update for files in translation unit of: /local/home/thomasjr/vs-test/foo.hpp
sending 1 changes to server
Error squiggle count: 0
  tag parsing file: /local/home/thomasjr/vs-test/foo.hpp
Checking for syntax errors: file:///home/thomasjr/vs-test/foo.hpp
Queueing IntelliSense update for files in translation unit of: /local/home/thomasjr/vs-test/foo.hpp
Error squiggle count: 0
idle loop: reparsing the active document
Checking for syntax errors: file:///home/thomasjr/vs-test/foo.cpp
Queueing IntelliSense update for files in translation unit of: /local/home/thomasjr/vs-test/foo.cpp
Checking for syntax errors: file:///home/thomasjr/vs-test/foo.hpp
Queueing IntelliSense update for files in translation unit of: /local/home/thomasjr/vs-test/foo.hpp
sending 1 changes to server
```
I did a bit more digging on my remote system, and it looks like `/home/thomasjr/` is actually a symlink to `/local/home/thomasjr/`
 
I can fix this on my side by changing vs-code to point at the symlink target instead of the link itself, but this looks to me like a mixed usage of different path structures within the vs-code that is causing some places to use the symlink and some to use the target of the link.

**Comment by sean-mcmanus** [comment] 2021-08-17 23:01
Seems like a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4573 (same root cause).

**Closed as completed** 2021-08-24 19:46 UTC
Labels: Language Service, more info needed, Feature: Go to Definition, remote, Verifying - Internal
