### ISSUE TITLE
How to input EOF

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#1820] opened 2018-04-12 12:50 UTC
my program has a sentence "while(cin >> variable)", but when i input CTRL+D(EOF), the whole program exits.

**Comment by pieandcakes** [comment] 2018-04-13 19:58
Does this do the same without the extension? You may want to try and use file input.

**Comment by WardenGnaw** [comment] 2018-04-16 23:36
@amerysong I just tested this and could not reproduce the whole program exiting on the ```while (cin >> variable)```

With the code snippet below, if you input EOF. It will continue on with the program, you will see "Read EOF in cin" in the output and then exit.
```
#include <iostream>

using namespace std;
int main(void) {
   int variable;
   while (cin >> variable) {}
   if (cin.eof()) {
      cout << "Read EOF in cin" << endl;
   }
   return 0;
}
```

**Comment by WardenGnaw** [comment] 2018-04-27 23:05
Closing. Please re-open if you are encountering the same issue and have more information about it.

Thank you.

**Closed as completed by WardenGnaw** 2018-04-27 23:05 UTC
Labels: debugger
