### ISSUE TITLE
[FR] smarter enum value suggestion

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/vscode-cpptools#12432] opened 2024-07-03 13:37 UTC
Type: <b>Feature Request</b>

When I try to assign to an enum variable the suggestion hint doesn't pririatioze the actual enum values first.

```
typedef enum
{
  BOOT_REAS_PWR,
  BOOT_REAS_SLP
} tBootReas;

static tBootReas bootCause;

//I start typing this
bootCause=    
```

but the hints it shows are irrelevant:
![image](https://github.com/microsoft/vscode-cpptools/assets/4163396/e5873cf7-116c-4ae0-9957-87cb5f9f2d2f)

Might be true for other limited value variables too.

Extension version: 1.17.5
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes: Unsupported
Sandboxed: No

**Comment by browntarik** [comment] 2024-07-08 21:50
Thank you for your suggestion. We will let you know when we begin work on this. Things like getting more upvotes on this request may increase its priority.

**Comment by bobbrow** [comment] 2024-07-10 18:04
I believe this issue is a duplicate of #5798. Can you please click the 👍 in that issue to add your vote for it?

**Closed as not planned by bobbrow** 2024-07-10 18:04 UTC
Labels: Language Service, Feature: Auto-complete, more votes needed, enhancement
