### ISSUE TITLE
IntelliSense Updating and Parsing Workspace speed is much slower after 1.18.5

### ISSUE THREAD

**Issue by LittleFatHero** [microsoft/vscode-cpptools#12292] opened 2024-05-09 07:12 UTC
### Environment

- OS and Version: windows 10
- VS Code Version: 1.89.0
- C/C++ Extension Version: 1.20.5
- If using SSH remote, specify OS of remote machine: ubuntu 20.04

### Bug Summary and Steps to Reproduce

Bug Summary:
My vscode is running in windows 10 and I connected to remote machine ubuntu 20.04 which has installed vscode server and cpptools using the ssh remote-SSH extensions. when I open a C source file and go to definition of a function， it could not jump to the definition because cpptools is Updating IntelliSense  and Parsing Workspace. So I wait for cpptools to finish the job, but I found that it Parsing Workspace is extremely slower than previous version. My workSpace has about 100000 C source files.
1. Why cpptools 1.20.5 verison feels slow than previous version?
2. what is strategy of when Updating IntelliSense  and Parsing Workspace? will it updating of the file on the workspace or only update the and parse the open file?
3. Would it be possible to add a setting that allows the user to specify number of thread to use for parsing?

Steps to reproduce:
1. Open the workspce which has about 100000 C source Files using vscode 1.89.0 and cpptools 1.20.5
3. Count the time it takes to finish update Intellisense and Parsing workspace.
4. compare the time with privous version of vscode and cpptools

Expected behavior:
update Intellisense and Parsing workspace faster

### Configuration and Logs

```shell
default config
```

**Comment by Colengms** [comment] 2024-05-10 18:30
Hi @LittleFatHero .  Would you be able to try out the various versions (including prerelease versions) between 1.89 and 1.20.5, to isolate which version seems to introduce the performance regression?

**Comment by LittleFatHero** [comment] 2024-05-16 11:47
> Hi @LittleFatHero . Would you be able to try out the various versions (including prerelease versions) between 1.89 and 1.20.5, to isolate which version seems to introduce the performance regression?

ok,  I will try it  as soon as possible

**Comment by LittleFatHero** [comment] 2024-07-01 02:55
> Hi @LittleFatHero . Would you be able to try out the various versions (including prerelease versions) between 1.89 and 1.20.5, to isolate which version seems to introduce the performance regression?

Hi @Colengms ,  I'm sorry, I have been busy doing other thing and has no time to do this action. When the cpptools release a new   version , is there any performance test about parse and intellisense? if not , maybe the team can do this when a new version is going to release. When there is a performance regression, the new version should not release?

**Comment by sean-mcmanus** [comment] 2024-07-03 17:44
@Colengms @LittleFatHero The performance issue started with 1.19.x -- it looks like it may be "by design" due to the workspace symbol search changes. I'm seeing roughly it take roughly twice the amount of time to parse/update the database and the database is roughly 50% bigger. We'll look into whether that can be improved.

**Comment by sean-mcmanus** [comment] 2024-07-16 00:11
@LittleFatHero Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.21.1

**Closed as completed** 2024-07-22 22:14 UTC
Labels: Language Service, fixed, performance, regression
