### ISSUE TITLE
Crash in cpptools.exe!browse_engine::ensure_file

### ISSUE THREAD

**Issue by RedCookieLP** [microsoft/vscode-cpptools#8055] opened 2021-08-25 21:57 UTC
- Bug type: General
- OS: Windows 10 Pro, Version 21H1
- VS Code Version: 1.59.1
- C/C++ Extension Version: 1.6.0

I just updated from 1.5.1 to 1.6.0 and after restarting VSC the extension doesn't work anymore. It just returns **_"[Error - (my Time at startup)] Connection to server got closed. Server will not be restarted."_**

I expected it to work just fine out of the box, seems not to be the case.
I even tried reinstalling it, twice, once over the marketplace and once with the offline VSIX file, both of them don't work.

Here is a screenshot of the console... not much, only the error message...
![Unbenannt](https://user-images.githubusercontent.com/45202005/130869694-b940f93a-e65e-42a1-bc65-9462e12871d9.PNG)
I even went as far as updating my Version of VS for the .NET Runtime **AND** installing it seperately, still nothing.

If nothing works. I will just downgrade again to 1.5.1...

**Comment by garrettseepersad** [comment] 2021-09-06 04:26
+1

**Comment by Colengms** [comment] 2021-09-07 23:35
Hi @RedCookieLP @paulelsner @garrettseepersad .  We've seen evidence of this crash in automated crash reports, and would appreciate any information you can give us that might help us repro and investigate it.  The issue appears to be a failure to open the browse database with write permissions.

If you move the project to a different computer, does the issue also repro there?  If not, can you identify any specific differences between those systems?

I'm curious if the issue might have something to do with the location the browse database had been stored.  Could you try redirecting the browse database to a new location, using the following:

.. within the active configuration in `c_cpp_properties.json`:
```
            "browse": {
                "databaseFilename": "${workspaceFolder}\\.vscode\\database.db"
            }
```

or, as a default setting:
```
"C_Cpp.default.browse.databaseFilename": "${workspaceFolder}\\.vscode\\database.db"
```

... This would cause the database to be rebuilt at the new location, so might address the issue if due to database corruption.  

Could you also set the `"C_Cpp.loggingLevel": "Debug"` setting, and provide the output of the `C/C++` output channel leading up to the repro?  There may be some clues in that log that might help us.  Since the issue appears to be a failure to access the database with write permissions, I'm curious if it shows failures of other database write operations.  Does the issue repro even while log output actively indicates that the database is being successfully populated?

@paulelsner @garrettseepersad Are you also using 'multi-root' workspaces?

**Comment by Colengms** [comment] 2021-09-24 01:03
Although we have a fix for this crash in a pending insiders build, the issue is not fully understood.  We can prevent a crash by exiting the particular code path gracefully when an unexpected error is encountered, but we suspect there may still be other issues related to this.

**Comment by sean-mcmanus** [comment] 2021-09-28 20:07
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders, but see the comment above: https://github.com/microsoft/vscode-cpptools/issues/8055#issuecomment-926269170

**Closed as completed** 2021-10-15 20:25 UTC
Labels: bug, Language Service, fixed, more info needed, regression

**Comment by bruno-kakele** [comment] 2021-10-19 23:52
Same issue for me. Downgrading to 1.5.1 works. 1.7.0 is not working!!

**Comment by bruno-kakele** [comment] 2021-10-20 00:59
Hi, I have replied here: https://github.com/microsoft/vscode-cpptools/issues/8080 Sorry for the duplication
