### ISSUE TITLE
Doesn't show STL container (vector<string>) accurately on Variables window while debugging

### ISSUE THREAD

**Issue by ismailhkose** [microsoft/vscode-cpptools#3004] opened 2019-01-05 23:49 UTC
Type: C++ Debugger (GDB)
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: MacOS High Sierra (10.13.6)
- VS Code Version: 1.30.1
- C/C++ Extension Version: 10.13.6 (ms-vscode.cpptools)
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Write the code in the screenshot
2. Enter debugging mode
3. Check wordDict size. It's zero eventhough two strings were added.

**First Issue;**
It doesn't show STL container accurately on the variable window.
For example, I added two strings to vector and it stills show "size: 0" in the variables window as seen in the following screenshot.

![image](https://user-images.githubusercontent.com/353824/50730339-f551e280-10ff-11e9-9ceb-439aa140b237.png)

Example code used in the experiment.
```c++
#include <iostream>
#include <string>
#include <vector>
#include <unordered_set>
using namespace std;


int main()
{
    string s = "example_string";
    vector<string> wordDict;
    wordDict.push_back("apple");
    wordDict.push_back("pen");

    cout << "size: " << wordDict.size() << endl;
    cout << "Testing" << endl;
    return 0;
}
```

Here is from my launch.json file.
```json
        {
            "name": "(gdb) Launch",
            "preLaunchTask": "build",
            "type": "cppdbg",
            "request": "launch",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                { "text": "handle SIGPIPE nostop noprint pass",
                  "description": "ignore SIGPIPE",
                  "ignoreFailures": true } 
            ],
            "logging": {
                "engineLogging": false,
                "trace": false
            },
            "windows": {
                "program": "${workspaceRoot}/${fileBasenameNoExtension}.exe",
                "MIMode": "gdb",
                "miDebuggerPath": "<Path/To/GDB>" // Path to gdb on windows
            },
            "linux": {
                "program": "${workspaceRoot}/${fileBasenameNoExtension}.out",
                "MIMode": "gdb"
            },
            "osx": {
                "program": "${workspaceRoot}/${fileBasenameNoExtension}.out",
                "MIMode": "lldb"
            }
        }
```

**Second issue;**
This is not directly related with the first issue. If there is a quick comment to address, it would be appreciated.
While debugging, how can I prevent debugger to jump STL container's implementation? 

![image](https://user-images.githubusercontent.com/353824/50730368-82953700-1100-11e9-977c-cece6b32e411.png)

I don't want the debugger to jump inside "string" header with "Step Into". How can I disable it?

**Comment by lmglmg** [comment] 2019-01-08 09:50
It seems that this is a duplicate of issue https://github.com/Microsoft/vscode-cpptools/issues/1768

**Closed as completed** 2019-06-24 23:44 UTC
Labels: duplicate, debugger
