### ISSUE TITLE
user settings C_Cpp > Default: Compiler Path behavior from setting empty string vs undefined

### ISSUE THREAD

**Issue by snehara99** [microsoft/vscode-cpptools#10795] opened 2023-04-10 18:59 UTC
Hi, so I noticed a possible bug or unexpected behavior regarding the compiler path settings while trying to repro a user issue on vscode-cmake-tools ([3096](https://github.com/microsoft/vscode-cmake-tools/issues/3096)):

If I remove the default `compilerPath` from my user `settings.json` completely (set undefined), `compilerPathIsExplicit` depends only on the `compilerPath` setting in `c_cpp_properties.json`. However, if the default `compilerPath` in user settings is set to an empty string rather than being undefined, `compilerPathIsExplicit` is always `true`. 

I think this difference in behavior between the default compiler path in user settings being an empty string vs being undefined can be confusing, but I also understand this may be expected behavior. I just wanted to point it out.

However, I think a larger issue is when changing the default user settings via the UI rather than the `settings.json` file, an empty string versus undefined is indistinguishable. Erasing the default compiler path results in the default compiler path to be set to an empty string in the user `settings.json` file rather than undefined. I think this could cause unanticipated problems for users using the UI rather than the `settings.json` file.

I'm not sure if this is a bug, but I think it would help if some warning was given in the UI at least. Let me know if you'd like any clarification, thanks!

**Comment by browntarik** [comment] 2023-04-10 19:11
This is by design but displaying a notification in the language status UI may be helpful.

**Comment by browntarik** [comment] 2023-04-10 19:34
Since we need the VS Code UI to distinguish between an undefined or blank string for the optimal fix, we decided to keep this as known issue. This is a regression from an older fix we had for this issue so we may take a look at this as well.

**Comment by Colengms** [comment] 2023-04-12 00:49
https://github.com/microsoft/vscode-cpptools/pull/10797 somewhat addresses the issue in VS Code's settings UI, but does not address the same issue in `C/C++: Edit Configuration (UI)`.

**Comment by sean-mcmanus** [comment] 2023-04-13 20:35
The settings UI issue is fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.15.2 . I'm not sure if we need another issue to track the Edit Configuration (UI) case or not (feel free to open a new issue if you want).

**Closed as completed** 2023-05-01 23:50 UTC
Labels: bug, Language Service, fixed, regression
