### ISSUE TITLE
c/c++ server unable to start showing spawn unknown system error-86 on m1 MacBook 

### ISSUE THREAD

**Issue by Aq-shay** [microsoft/vscode-cpptools#7286] opened 2021-04-03 03:29 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS Big Sur 11.2.3
- VS Code Version:1.55(global)
- C/C++ Extension Version:1.2.2
- Other extensions you installed (and if the issue persists after disabling them):none
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
 I install vscode universal for first time my M1 Macbook air for c/c++
and then install c/c++ extension by Microsoft . As soon I name gave name to file (for example "hello.cpp") or write edit configuration in command palette and the press enter
output shows

[Error - 10:26:19 AM] Starting client failed

Error: spawn Unknown system error -86

at ChildProcess.spawn (internal/child_process.js:407:11)
at Object.spawn (child_process.js:557:9)
at /Users/akshay/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:15519:40

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

when I name file and press enter
![](https://i.stack.imgur.com/paCW2.jpg)

when I open command palette and write edit configuration and press enter

<img width="1440" alt="Screenshot 2021-04-03 at 8 53 04 AM" src="https://user-images.githubusercontent.com/76761595/113466507-17ab4580-945a-11eb-82bd-1ebce0a235d6.png">

**Additional context**
please help me to resolve this as I didn't know much about .js file and new to vscode

**Comment by sean-mcmanus** [comment] 2021-04-05 17:17
@michelleangela Any ideas about this? Maybe the ARM64 build will fix this?

**Comment by Colengms** [comment] 2021-04-05 19:15
It's possible an error occurred when installing/upgrading the extension. I had opened this issue against VS Code for previous occurrences: microsoft/vscode#100537

Could you take a look at that issue, and set aside the vsix they are asking for? Then, could you try deleting the entire ms-vscode.cpptools-x.x.x folder from the extensions folder and reinstalling the extension? If the newly installed version works, perhaps we could get VS Code to revisit that issue.

**Comment by sean-mcmanus** [comment] 2021-04-05 19:20
@Colengms This issue seems different? Seems like cpptools is failing to run.

**Comment by Colengms** [comment] 2021-04-05 19:35
One of the symptoms of the install/update issue is missing or corrupted files.

**Comment by michelleangela** [comment] 2021-04-05 20:34
I couldn't repro this on Apple Silicon with VS Code (universal) and installing C++ extension v1.2.2 from VS Code market place.

As suggested, this could be an installation issue.

**Comment by Aq-shay** [comment] 2021-04-06 01:04
@Colengms i also download VS Code for silicon chips too after completely uninstalling VS Code universal but same problem occurred.(not ones but quite few times both universal and one for silicon chip)

After installing C/C++ extension from market place and seeing it showing error , i deleted ".vscode" folder which has a folder of "extension" in it ,
i again install from market place(showing same error) and also download "cpptools" from github (which also showing same error)

i can also share video my mac screen recording showing all  the process ,if you want .

**Comment by Aq-shay** [comment] 2021-04-06 01:07
@michelleangela @sean-mcmanus 
not only me but 2 of my friend brought m1 macs with me also facing same problem

i can also share video my mac screen recording showing all the process ,if you want .

**Comment by Colengms** [comment] 2021-04-06 01:26
Hi @Aq-shay .  I just tried freshly installing the 1.55.0 (Universal) build of VS Code, and the C/C++ Extension 1.2.2 from the marketplace from within VS Code, on my Mac M1, and wasn't able to repro an issue.  Is there anything in addition to what I just described that you might be involved in your repro?  My Mac does not have any pending updates.

When the error occurs, is there a crash report added to the "Console" app?

Note that immediately after installing the C/C++ Extension, you should see a notification pop up and multiple progress bars, as native dependencies are downloaded.  If you were to terminate VS Code before that is done, it could results in those files being missing or corrupted due to being only partially downloaded.

**Comment by Aq-shay** [comment] 2021-04-06 02:19
@michelleangela 
every time i use only single extension

here is the the short 3 min fresh video of  the installation process (before installing I completely uninstalled previous vs code)
https://youtu.be/4es45ARmnO4

**Comment by Aq-shay** [comment] 2021-04-06 02:19
@Colengms 
here is the the short 3 min fresh video of the installation process (before installing I completely uninstalled previous vs code)
https://youtu.be/4es45ARmnO4

**Comment by Colengms** [comment] 2021-04-06 05:13
@Aq-shay .  That's very odd.  Following the same steps, I don't repro the issue.

1.2.2 is not native ARM64.  It's x64, so should run emulated.  Maybe some runtime dependency needed for our x64 binary is not present on your system for some reason.  The TypeScript portion of the extension appears to run fine, but the native process fails to start.

We're looking at releasing 1.3.0-insiders4, imminently.  It uses native ARM64 Mac binaries.  If the issue is due to some missing runtime dependency for x64, insiders4 may address the issue.

Did you see anything in the "Console" app?  There should be logs there with more detail.  Also, if you use Help -> Toggle Developer Tools -> Console, after the repro, there may be some useful output there, as it's VS Code that is launching our native process directly.

I noticed the icon indicating that you have app updates that are not yet installed.  It's a long shot, but could you ensure app updates are all installed, and launch XCode (assuming you also have that installed) to ensure it has updated it's tools and libs (which often require launch XCode to update).

**Comment by Colengms** [comment] 2021-04-06 18:36
@Aq-shay , Perhaps this is due to Apple disabling Rosetta 2?  https://9to5mac.com/2021/03/02/apple-may-disable-rosetta-2-on-m1-macs-in-some-regions-macos-11-3-code-suggests/

**Comment by michelleangela** [comment] 2021-04-07 04:06
@Aq-shay 

The issue may be because the Rosetta emulator for x64 programs is disabled or not installed on your machine; therefore our language service binaries that are built for x64 chips cannot execute on Silicon Mac ARM64 chip ARM64.

We just release an insiders version 1.3.0-insiders4 version which has language service ARM64 binaries for Silicon Mac. The VSIX package is **cpptools-osx-arm64.vsix** which can be downloaded at https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders4. Could you try this insiders version and see if this resolves the issue?

Note: if you want to use versions prior to 1.3.0-insiders4, then you would need to install the Rosetta emulator so that x64 programs can run on the Silicon Mac chip.

**Comment by Aq-shay** [comment] 2021-04-07 06:31
@michelleangela @Colengms 

After downloading version 1.3.0-insider4 intellisense started to work.
Heartly thank you so much to both of you for giving your time to my problem and helping me out.

I will also try to land in Microsoft as SE and say thank you in person.

**Comment by michelleangela** [comment] 2021-04-07 17:26
@Aq-shay You're welcome! I'll close this issue as resolved.

**Closed as completed by michelleangela** 2021-04-07 17:26 UTC
Labels: Language Service
