### ISSUE TITLE
#include errors when adding multiple projects (multiroot)

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#4731] opened 2019-12-11 19:20 UTC
Hello @michelleangela 
I have now created a new workspace and added only one project, source code and lib in the include folder are copied from the old project.

When starting with main.cpp still open, no error is displayed anymore, so I don't think the debug output is needed and probably didn't output anything else than before?

Too many projects have accumulated in my old workspace over the years, so I wanted to clean it up anyway. ;-) So I will add more projects to the workspace and test the behavior. If there are already problems with a few projects, I will temporarily change to version 0.26.1, but I'm happy to be available for further tests.

The result, from how many projects it comes to the error, I write later still.

Thanks for your support so far!

**Update!**

If I create a new workspace and integrate my projects in small steps (5 each) (add folders to workspace, not as new projects) and restart VSC, there is no error with all 22 projects. However, if I remove all the folders and insert the 22 project folders at once, the include error will occur the next time VSC restarts.

**2nd update...**

The solution only works if the project with the include error is inserted first. For example, if 1 or more project(s) are added without the error and the problematic project is added to Wordplace after that, the include error will reappear when restarting with main.cpp open.

Very strange and I can't explain it...

_Originally posted by @wapjoe in https://github.com/microsoft/vscode-cpptools/issues/4718#issuecomment-564535413_

**Comment by sean-mcmanus** [comment] 2019-12-13 22:42
@wapjoe We are re-writing our multi-root implementation so this might get resolved by that.

**Comment by wapjoe** [comment] 2019-12-14 07:50
@sean-mcmanus If I should or can test something, I am gladly available.

**Comment by otoomey** [comment] 2019-12-16 18:44
Managed to reproduce on my system. I have a nodejs add-on project setup, and the error was occurring in only one of the files in my workspace (for an include referenced from multiple files). Switching to a single project workspace fixed the issue.

**Comment by kkaja123** [comment] 2020-01-13 22:21
Leaving my repro notes here in case it helps:
It appears that the extension exclusively uses the settings file from the **first** folder added to a multi-root workspace, instead of using the settings file of the folder that the open file is from. From what I can tell, the settings files from subsequent folders are completely ignored.

Since the settings files are ignored, the include paths won't be pointing to what the folder expects the include paths to point to, hence the include error squiggles.

**Comment by sean-mcmanus** [comment] 2020-03-04 03:15
Our latest Insiders release has a new multi-root implementation (which fixes this bug): https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders. Please let us know if you find any multi-root-related bugs or regressions so we can prioritize fixing those for 0.27.0.

**Closed as completed** 2020-03-31 00:11 UTC
Labels: bug, Language Service, fixed, Feature: Multi-root
