### ISSUE TITLE
Intellisense for std::span

### ISSUE THREAD

**Issue by nm-bls** [microsoft/vscode-cpptools#6372] opened 2020-10-22 09:20 UTC
Issue Type: <b>Bug</b>

When converting a std::vector to std::span, Intellisense reports a problem:

> no suitable user-defined conversion from "std::vector<float, std::allocator<float>>" to "std::span<float,  18446744073709551615UL>" exists

Compilation using c++20 works fine.

Extension version: 1.1.0-insiders2
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.8.15-201.fc32.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx (8 x 1737)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|13.60GB (5.21GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 5f61d911-3c5c-4d40-b8a3-115e315ed58a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by sean-mcmanus** [comment] 2020-10-22 17:19
Can you provide a code sample? And what compiler is being used?

**Comment by sean-mcmanus** [comment] 2020-10-22 17:48
In particular, I'm hitting this crash: https://developercommunity.visualstudio.com/content/problem/1209658/c-intellisense-process-crashes-when-using-span-wit.html

**Comment by nm-bls** [comment] 2020-10-23 10:54
Contrary to the original issue, this does not seem to pop up in all cases:

```
#include <iostream>
#include <span>
#include <vector>

void fn(std::span<int> s) 
{
    std::cout << s.size();
}

int main() 
{
    std::vector vec{1, 2, 42};
    std::span sWorking{vec};                // this works
    std::span sWorking2 = vec;              // this works
    std::span sError = (std::span<int>)vec; // this doesn't
    fn(vec);                                // this doesn't
    return 0;
}
```

I did not experience any crashes on Fedora with gcc. The code compiles and runs fine, however code completion on the span objects doesn't work either.

**Comment by sean-mcmanus** [comment] 2020-10-28 00:01
Okay, thanks for the repro details. I repro the issue now. It might share the same root cause as the previous span issues. Investigating...

**Comment by sean-mcmanus** [comment] 2020-10-31 01:37
I've filed a new VS bug for this issue at https://developercommunity.visualstudio.com/content/problem/1240036/c-intellisense-for-c20-linux-gcc-mode-gives-no-sui.html .

**Comment by Colengms** [comment] 2021-11-12 20:00
Hi @nm-bls .  I'm no longer able to reproduce this issue with 1.7.1.  I'm going to close this as fixed.  But, if you are still able to repro this, please let me know, and I will reopen it.

**Closed as completed by Colengms** 2021-11-12 20:00 UTC
Labels: bug, Language Service, fixed, parser, Visual Studio
