### ISSUE TITLE
[CppVsDbg] Crash when visualizing local variables for Microsoft Edge (msedge.exe)

### ISSUE THREAD

**Issue by dylank** [microsoft/vscode-cpptools#8738] opened 2022-01-28 23:09 UTC
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows
- VS Code Version: 1.63.2
- C/C++ Extension Version: v.1.8.1
- vsdbg will crash when debugging large programs, for example, msedge or associated test binaries,. There's an email thread discussing the issue.

**Comment by sean-mcmanus** [comment] 2022-01-28 23:19
@dylank @WardenGnaw Is this a regression? Is this https://github.com/microsoft/vscode-cpptools/issues/8690 ?

**Comment by dylank** [comment] 2022-01-28 23:22
we just had a meeting on this, and Xinyu asked me to open a new issue:

[2:42 PM] Xinyu Sui
Can you open a new bug for cpptools on github?

**Comment by dylank** [comment] 2022-01-28 23:24
I think that #8690 is the same as Bug 1340722: [CppVsDbg] Debugging does not work for Microsoft Edge

After manually updating msdia.dll we hit a new issue, Andrew said it was the same as:
Bug 1327692: [CppVsDbg] Crash when visualizing local variables for Microsoft Edge

However, Xinyu wanted me to make a new issue for this.

**Comment by sean-mcmanus** [comment] 2022-01-28 23:48
@WardenGnaw So is this a regression? What's the severity? Should it delay the 1.8.2 release?

**Comment by bobbrow** [comment] 2022-01-28 23:53
No, this does not delay 1.8.  The Edge team has been stuck on v1.1.3 of cpptools for a long time because of bugs in the debugger.  We're trying to make progress on it.

**Comment by dylank** [comment] 2022-01-29 00:14
Yeah, looks like we got forced to upgrade for the 4GB issue.

**Comment by sean-mcmanus** [comment] 2022-03-23 21:52
This was fixed in 1.9.1 -- the current release is https://github.com/microsoft/vscode-cpptools/releases/tag/v1.9.7

**Closed as completed by sean-mcmanus** 2022-03-23 21:52 UTC
Labels: fixed
