### ISSUE TITLE
Frequent spurious errors (squiggles) on correct code

### ISSUE THREAD

**Issue by bsekura** [microsoft/vscode-cpptools#5066] opened 2020-03-06 01:13 UTC
Version: 0.27.0-insiders2

Language service frequently gets confused and reports spurious errors (red squiggles) when the code is actually compiling correctly. Reloading the window fixes the problem, but it's extremely tedious.

**Comment by sean-mcmanus** [comment] 2020-03-06 01:20
What OS are you on? If you're on Mac, do you see any crash logs related to the cpptools-srv process under ~/Library/Logs/DiagnosticReports .

Do you know if this is a regression compared to 0.26.3?

Are you using a multi-root workspace?

Are you using a workspace that has a symlink on the path?

Are you using a custom configuration provider?

**Comment by sean-mcmanus** [comment] 2020-03-06 03:05
Also, does setting your C_Cpp.intelliSenseCacheSize to 0 fix it?

**Comment by bsekura** [comment] 2020-03-06 09:38
OS: Windows 10 Pro 1909 18363.639
The workspace is not multi-root, but does have symlinks on include paths.
It has been happening for several versions now, I'm sorry I cannot tell which version it started happening.

I will try the setting you mentioned.
Thank you

**Comment by michelleangela** [comment] 2020-12-09 18:45
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide any new information.

**Closed as completed by michelleangela** 2020-12-09 18:45 UTC
Labels: bug, Language Service, more info needed
