### ISSUE TITLE
IntelliSense not finding include directories with lower case

### ISSUE THREAD

**Issue by J-Vernay** [microsoft/vscode-cpptools#2467] opened 2018-08-30 09:14 UTC
**Type: LanguageService**

I was trying to use wxWidgets (built from source) when I discovered the headers are not found by IntelliSense. After trying to fix it, I found that directories containing at least one lower case character are not found.

A gif is available at the end of this post.

After trying some names, what I found : `Test`, `test` are not found, but `TEST` is found. As shown in the gif, `SDL2` is found, but not `Box2D`.

**Describe the bug**
- OS and Version: Windows 10 Education 10.0.17134
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed : French Language Pack
- A clear and concise description of what the bug is : IntelliSense not find include directories containing lower case characters.

**To Reproduce**
1. Create a new workspace
2. Add in c_cpp_properties.json, in "includePath", a directory where there are the headers
3. Test autocompletion on all upper case directories, and others

**Expected behavior**
There should be no discrimination about the case of the include directory.

**Screenshots**
![vscode_upper_include](https://user-images.githubusercontent.com/23388205/44842223-935f0900-ac45-11e8-9f55-f02a32772619.gif)

**Comment by bobbrow** [comment] 2018-08-30 15:45
There isn't generally a discrimination about file path casing on Windows, but I suspect this is related to #2466 which you also commented on.  This sounds like a duplicate of that issue.  Is this the behavior you see when you open a folder created by a WSL `mkdir` command?

**Comment by J-Vernay** [comment] 2018-08-30 15:53
No, I tested this with a folder created with the Windows File Explorer.

**Comment by meiskam** [comment] 2019-04-15 23:03
I'm having the same issue, intellisense is looking for all caps directories and is thus not finding my includes.  I'm not using WSL at all, terminal is cmd, mode is MSVC.

**Comment by Colengms** [comment] 2020-05-05 23:56
Could this be due to the (new as of April 2018) Windows 10 support for enabling case-sensitivity on NTFS directories?  https://github.com/microsoft/vscode-cpptools/issues/5414 is now tracking that.  Closing this as a likely dupe.  If there is still an issue here and it's not due to NTFS case-sensitivity support, please add a comment here and we can reopen this issue.

**Closed as completed** 2020-05-05 23:56 UTC
Labels: duplicate, Language Service
