### ISSUE TITLE
always updating intellisense after building 

### ISSUE THREAD

**Issue by lgnq** [microsoft/vscode-cpptools#2066] opened 2018-05-31 06:55 UTC
Issue Type: <b>Bug</b>

build the makefile project with C/C++ IntelliSense 0.17.3 enabled, the updating IntelliSense ... will hung up, and if I disable this extension, it works fine.
VScode verison:1.23.1

Extension version: 0.17.3
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

**Comment by bobbrow** [comment] 2018-05-31 15:41
This sounds like a duplicate of #2043.  Can you try the workaround in that issue and let us know if that resolves your issue?

**Comment by bobbrow** [comment] 2018-06-01 03:16
We released 0.17.4 with a fix for the livelock, so this issue should be resolved now. There are still some performance issues with recursive includes that we are working on, so you might still see some high CPU usage when opening files, but it should eventually catch up. We are going to track performance problems with recursive includes using issue #2068.

**Closed as completed by bobbrow** 2018-06-01 03:16 UTC
Labels: bug, duplicate, Language Service
