### ISSUE TITLE
Unmatched template parameter type as refer the type defined in unrefered namespace

### ISSUE THREAD

**Issue by monstertango** [microsoft/vscode-cpptools#9507] opened 2022-06-25 10:31 UTC
Bug type: Language Service
**Describe the bug**
- OS and Version: Fedora 35
- VS Code Version: 1.68.1
- C/C++ Extension Version: v1.8.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): NO
- If using SSH remote, specify OS of remote machine: NO

Hover Tooltip refers unmatched template parameter type when the type is defined by typedef in other namespace and a function use the same template class using the type is already defined, then even if the namespace is not refered.

**Expected behavior**

Them should refer correct built in type like this
![image](https://user-images.githubusercontent.com/38209036/175769504-10262a31-148a-4975-aece-d96c24cdfc62.png)

Wrong result
![image](https://user-images.githubusercontent.com/38209036/175769621-093e8205-2e7f-48ad-994f-f6c6d091e64b.png)

**Code sample and logs**

- Code sample
//helloworld.h
#include < vector >
namespace Ns
{
class AAA 
{
    public:
    typedef uint32_t MyUnsigned; // it's same in unsigned instead of uint32_t 
     std::vector< MyUnsigned > f() { std::vector< MyUnsigned > v;
     return v;}  // this cause issue 'cause f use vector<MyUnsigned> 
    MyUnsigned n1;
};
}

// helloworld.cpp
#include < string >
#include < vector >
#include "helloworld.h"
namespace Ns2 {
    // namespace ns = Ns;
    // using namespace Ns;

struct Type {
    std::vector<unsigned> b;
};
}

int main(int argc, const char** argv)
{
    return 0;
}

**Screenshots**

**Comment by sean-mcmanus** [comment] 2022-06-27 17:23
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/7778 .

**Closed as not planned by sean-mcmanus** 2022-06-27 17:23 UTC
