### ISSUE TITLE
 memory viewer in debug

### ISSUE THREAD

**Issue by ghamelin** [microsoft/vscode-cpptools#1289] opened 2017-11-27 08:25 UTC
Since there has been an update to the vscode ( https://code.visualstudio.com/updates/v1_15#_loaded-scripts-explorer ) is there a way to view memory usage in debug mode?

**Comment by pieandcakes** [comment] 2017-11-27 23:23
@redhedgh12 This looks to be implemented by the VS Code team in VS Code. I don't think they added extensibility for UI so if you want to have memory usage in debug mode as part of the UI you probably need to ask them [here](https://github.com/microsoft/vscode/issues).

**Comment by pieandcakes** [comment] 2017-11-30 00:12
Duplicate of #509

**Closed as completed by pieandcakes** 2017-11-30 00:12 UTC
Labels: duplicate, Feature Request, external
