### ISSUE TITLE
lsp ignore `"` in compile_commands.json

### ISSUE THREAD

**Issue by codehz** [microsoft/vscode-cpptools#4781] opened 2019-12-22 03:28 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: ArchLinux (x64)
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.3-insiders2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

lsp ignore `"` in compile_commands.json

**To Reproduce**
test.c:
```c
char text[] = __sth__;
```
c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64",
            "compileCommands": "${workspaceFolder}/compile_commands.json"
        }
    ],
    "version": 4
}
```
compile_commands.json:
```json
[
    {
        "file": "test.c",
        "directory": "<your directory>",
        "arguments": [
            "/usr/bin/gcc",
            "-c",
            "-D__sth__=\"test\"",
            "test.c"
        ]
    }
]
```

**Expected behavior**

no error report

**Screenshots**

![image](https://user-images.githubusercontent.com/13158903/71316657-244a9b00-24ae-11ea-9f90-203a0d91baa9.png)

**Additional context**

```
正在为 /home/codehz/Projects/code/test.c 发送编译参数
  包括: /usr/include/c++/9.2.0
  包括: /usr/include/c++/9.2.0/x86_64-pc-linux-gnu
  包括: /usr/local/include
  包括: /usr/lib/clang/9.0.0/include
  包括: /usr/include
  定义: __sth__=test
  其他: --gcc
  其他: --gnu_version=80100
  stdver: c11
  intelliSenseMode: gcc-x64
```

**Comment by sean-mcmanus** [comment] 2019-12-23 20:31
This appears to be "by design" according to the thread at https://github.com/Microsoft/vscode-cpptools/issues/2305 . We expect `\\\"` to be used instead of `\"` to get the result you desire. Are you able to change the compile_command.json to use that?

**Comment by codehz** [comment] 2019-12-24 03:43
@sean-mcmanus BUT my compile_commands is passed from JSON ARRAY insteads of single STRING
it is pointless to use `\\\"`

`["gcc", "-D_X_=\"test\""]` vs `"gcc -D_X_=\\\"test\\\""`

**Comment by sean-mcmanus** [comment] 2019-12-27 20:05
Okay, looks like https://github.com/microsoft/vscode-cpptools/issues/2305 applies to the "command" and not the "arguments". The fix seems trivial (remove the code that erases the `\"`).

**Comment by antoche** [comment] 2020-07-31 04:28
This affects me too. Keen to hear about a fix.

**Comment by Colengms** [comment] 2020-07-31 21:17
Hi @antoche .  The parsing of args from `compile_commands.json` has changed significantly since this issue was opened.  If you're seeing an problem now, it may be new.  I'd suggest opening a new issue.

Note that `compile_commands.json` is a json file, so must include escaping of both slash and quote, if both are intended to be passed on the command line.

Note that the following results in defining a macro without quotes, despite their use on the command line:

```
clang  -Wp,-v -E -dM -DTEST="TEST" -x c++ nul
```

This outputs the following, in which TEST is defined without quotes.

```
#define TEST TEST
```

This is compiler behavior, not C/C++ Extension behavior, and is likely to allow multi-word defines to be provided via command line.  If you want quotes to be included in a #define, the command line needs to contain escaped quotes:

```
clang  -Wp,-v -E -dM -DTEST=\"TEST\" -x c++ nul
```

The above outputs:

```
#define TEST "TEST"
```

Because `compile_command.json` is a JSON file, the string requires additional escaping.  So, the above argument needs to be specified as:

```
-DTEST=\\\"TEST\\\"
```

I'm going to close this issue, as I believe our current behavior is correct.  If you can find a case which we are handling incorrectly, please open a new issue with repro details.

**Closed as completed by Colengms** 2020-07-31 21:17 UTC
Labels: bug, Language Service, quick fix, verified, Feature: Compile Commands

**Comment by antoche** [comment] 2020-08-03 02:44
Hi,

I think the issue is you are assuming that the arguments in compile_commands.json will be parsed by a command-line interpreter. If that is so, then yes the user needs to add extra escaping for the shell parser. But I believe it is the wrong approach.

I'm using a python-based build system (waf) which at no point relies on command-line interpreting. Here is a minimal example reproducing what the build system is doing:

Source:

```
#include <stdio.h>

int main(int, char**)
{
    printf("TEST is %s", TEST);
    return 0;
}
```

Build:

```
#!/usr/bin/env python
import os
import subprocess
import json

args = ['-DTEST="FOOBAR"', '-x', 'c++']
path = 'test.cc'
command = ['clang'] + args + [path]

print(subprocess.check_output(command))

assert '#define TEST "FOOBAR"' in subprocess.check_output(command + ['-Wp,-v', '-E', '-dM'])
assert 'TEST is FOOBAR' in subprocess.check_output(['./a.out'])

compile_commands = [{
    'directory': os.getcwd(),
    'arguments': args,
    'file': path
}]
with open('compile_commands.json', 'w') as f:
    json.dump(compile_commands, f)
```

JSON output:

```
[{"directory": "/tmp/vscode_compile_commands", "arguments": ["-DTEST=\"FOOBAR\"", "-x", "c++"], "file": "test.cc"}]
```

As you can see, calling clang via `popen` doesn't require any escaping, because no shell parsing takes place. The double quotes in the json output only require a single escape character, because that's all that is required to encode quotes in JSON strings. 

This is not exclusive to a python build system, the same would be true if the compiler was called from, say a C program calling the compiler with `popen` or `execv`. Basically, any build system that is not executing the compiler through a shell. It seems like the wrong approach to me that build systems that don't rely on a shell interpreter should have to add extra escaping characters to conform to other build systems that do. If certain build systems require additional escaping due to the interpreter they are using, they should not pollute the JSON representation with it.

In addition, looking at the docs on the compilation database, it clearly shows an example with quotes requiring only a single escape character: https://clang.llvm.org/docs/JSONCompilationDatabase.html

**Comment by Colengms** [comment] 2020-08-03 22:52
Hi @antoche .  I think I understand what you're saying.  I can see an argument for not considering shell parsing in `arguments` values.  But, I believe a 'command line' form would imply shell parsing.

On the page you referenced, it shows this example:

```
"command": "/usr/bin/clang++ -Irelative -DSOMEDEF=\"With spaces, quotes and \\-es.\" -c -o file.o file.cc",
```

Although the content of the define refers to quotes, I don't believe there is enough info here to infer that this use of quotes is expected to result in quotes within the define itself at compile time, as that is not indicated in the spec.

That page also indicates:

> **command**: The compile command executed. After JSON unescaping, this must be a valid command to rerun the exact compilation step for the translation unit in the environment the build system uses. ***Parameters use shell quoting and shell escaping of quotes, with ‘"’ and ‘\’ being the only special characters***. Shell expansion is not supported.

The portion I've highlighted in bold+italic appears to indicate that shell escaping for quotes and backslashes is required for `command` fields in `compile_commands.json`.  This makes sense, as the command line form implies use of a shell, to which the args are being passed on that same line as the executable.

Note that using CMake (3.18.1) and Ninja, and using a CMakeLists.txt such as the following:

```
cmake_minimum_required(VERSION 3.15)
set(EXECUTABLE_NAME "Test")
project (${EXECUTABLE_NAME} C CXX)
add_executable(${EXECUTABLE_NAME})

set(CMAKE_EXPORT_COMPILE_COMMANDS on)

target_compile_definitions(${EXECUTABLE_NAME} PUBLIC -DTEST="TEST")

target_sources(${EXECUTABLE_NAME} PUBLIC
  test.cpp
)
```

... results in the following in `compile_commands.json`, in a `command` field: `-DTEST=\\\"TEST\\\"`

Although it's unclear to me if this is the proper behavior for CMake (as it's unclear how to define a macro containing spaces and not quotes, based on this behavior), it would appear that CMake is including the expected shell escaping to ensure the quotes are included as part of macro.  This behavior would not make sense if shell escaping was not required here.

We're willing to update our implementation to adhere to the specification of `compile_commands.json`.  Shell escaping appears to be required for `command` fields, but it's unclear to me if `arguments` should be handled differently, as I do not see that called out explicitly.  

With lack of concise information to the contrary, it would appear that all args in `compile_commands.json` should include shell escaping.  Consider following up with an issue against WAF to add handling for shell escaping, or with LLVM to clarify the ambiguity of their `compile_commands.json` spec page.  If it turns out that the behavior you expect is the correct behavior, we may need to open an issue against CMake or Ninja as well.
