### ISSUE TITLE
[WSL] GCC system headers redirection is not parsed

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/vscode-cpptools#2223] opened 2018-07-03 14:37 UTC
Type: LanguageService

**Describe the bug**
- OS and Version: 10.0.17134.112
- VS Code Version: 1.24.1
- C/C++ Extension Version: 0.17.6
- Other extensions you installed (and if the issue persists after disabling them): N/A

`vscode-cpptools` does not handle redirected header files.

**To Reproduce**

1. Fresh installed WSL with gcc and libpng (`sudo apt install libpng-dev`)
2. create new `*.c` file, use `#include <png.h>`
3. try to use `png_bytep` identifier from system header.
4. See error: error squiggles are present, `identifier "png_bytep" is undefined`

**Expected behavior**
The `vscode-cpptools` should handle the redirected header.

Here is the content of the system header file (redirector one), verbatim:
<start_of_file>
`libpng16/png.h`
<end_of_file>

**Workaround**
One could get around this by using absolute system path, e.g.:
* instead of `#include <png.h>`
* use `#include <libpng16/png.h>`

**Comment by bobbrow** [comment] 2018-07-03 17:46
I believe this is the same root cause as #2140

**Comment by sean-mcmanus** [comment] 2018-07-03 19:23
I think #2140 was just about #include completion not treating symlinks as directories.

I have never seen redirection via using just using the path like "libpng16/png.h" before -- maybe it's some gcc extension?

**Comment by bobbrow** [comment] 2018-07-03 19:36
What I mean is that we don't work with symlinks at all on Windows.  You're right though that we should treat this separately since #2140 is about the `#include` autocompletion, and the fix for this would be in the IntelliSense server's file provider (I believe).

**Comment by sean-mcmanus** [comment] 2018-07-03 19:39
Oh...you mean the "png.h" file with "libpng16/png.h" is a symlink? Ok, I guess that could count as a duplicate then.

**Comment by michelleangela** [comment] 2019-08-21 16:59
Closing as duplicate.

**Closed as completed by michelleangela** 2019-08-21 16:59 UTC
Labels: bug, duplicate, Language Service
