### ISSUE TITLE
Can I enable only debugging component of this plugin?

### ISSUE THREAD

**Issue by summivox** [microsoft/vscode-cpptools#1316] opened 2017-12-06 23:04 UTC
I am using [CQuery](https://github.com/jacobdufault/cquery) to provide language service (auto-complete, hover tooltip, jump to definition, etc). I want to use the debugging support from this plugin, but the language service part of it conflicts with CQuery. Is there a way to enable only debugging support?

**Comment by sean-mcmanus** [comment] 2017-12-06 23:17
This is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/785 . Can you "upvote" that issue?

**Closed as completed by sean-mcmanus** 2017-12-06 23:17 UTC
Labels: duplicate, Language Service, Feature Request

**Comment by sean-mcmanus** [comment] 2017-12-06 23:28
You could also modify file `.vscode/extensions/ms-vscode.cpptools-0.14.3/out/src/main.js` by removing line 120 `LanguageServer.activate(delayedCommandsToExecute);`, but you'd have to reapply the change after every update, and that fix might not fix all the issues because we add some stuff via our package.json and via global object construction (e.g. the ui class that creates the config status bar item in the bottom right).

**Comment by summivox** [comment] 2017-12-06 23:52
Actually I figured out that a while ago.
For the time being I'm sticking with this.
