### ISSUE TITLE
Set Program field in launch.json gdb attach setting as non-required when process ID (PID) in use

### ISSUE THREAD

**Issue by hsiaolun-syn** [microsoft/vscode-cpptools#11225] opened 2023-07-20 08:20 UTC
### Feature Request

When debug with gdb attach, we will provide PID as the process for gdb to attach to. In this case, the program binary path is longer necessary as binary path can be automatically detected with PID. This is more similar to the gdb we use in Unix terminal. Hope the Program field can be set as non-required, and no errors report when we only use PID number.

**Comment by WardenGnaw** [comment] 2023-07-21 00:58
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/1272

**Closed as not planned by WardenGnaw** 2023-07-21 00:58 UTC
