### ISSUE TITLE
[Feature request] Add console configuration in launch.json

### ISSUE THREAD

**Issue by Lancern** [microsoft/vscode-cpptools#1743] opened 2018-03-28 01:51 UTC
To make the experience more fluent, users may prefer integrated terminal when executing the program. Up to now, users can only launch the external terminal for their programs. So maybe there could be an option to let users choose which kind of terminal environment ( external terminal or integrated terminal of VSCode ) they would like to use.

**Comment by pieandcakes** [comment] 2018-04-05 00:49
This is a duplicate of #35. Please upvote that issue.

**Closed as completed by pieandcakes** 2018-04-05 00:49 UTC
Labels: duplicate, debugger, Feature Request
