### ISSUE TITLE
Automatic addition of "${default}" to the default includePath is not working

### ISSUE THREAD

**Issue by derLalla** [microsoft/vscode-cpptools#8903] opened 2022-02-22 16:06 UTC
Bug type: Debugger

**Describe the bug**
- OS and Version: macOS Big Sur 11.6
- VS Code Version: 1.64.2
- C/C++ Extension Version: 1.8.4
- Other extensions you installed (and if the issue persists after disabling them): 
- A clear and concise description of what the bug is.

In ".vscode/settings.json" I have added the following: 
```
C_Cpp.default.includePath": [
        "${workspaceFolder}/lib/device/src/easy_file_system"
    ],
```
After restarting VS Code the c_cpp_properties.json gets new created but without the "${default}" appended to the includePath. 
But according to this Issue https://github.com/microsoft/vscode-cpptools/issues/3733 it should work.

**Comment by Colengms** [comment] 2022-02-24 02:48
Hi @derLalla .  I'm not easily able to reproduce this issue.  If I have no `c_cpp_properties.json`, I set `C_pp.default.includePath` as you described (in the `settings.json` for the workspace folder, or globally), then trigger creation of `c_cpp_properties.json` using a command such as `C/C++: Edit Configurations (JSON)` or `C/C++: Edit Configurations (UI)`, I see that `c_cpp_properties.json` is created and includes the following:

```
"includePath": [
     "${default}"
],
```

Are there more details to your repro?

**Comment by derLalla** [comment] 2022-02-25 09:24
Thanks for your answer, if I'm using your command, it is working as you described. But I need more settings.
I forgot to mention that I am using Platformio, which creates the c_cpp_properties.json file upon the start of VS Code. 
The file looks like that: 

```
//
// !!! WARNING !!! AUTO-GENERATED FILE!
// PLEASE DO NOT MODIFY IT AND USE "platformio.ini":
// https://docs.platformio.org/page/projectconf/section_env_build.html#build-flags
//
{
    "configurations": [
        {
            "name": "PlatformIO",
            "includePath": [
                "/Users/{my-username}/workspace/include",
                "",
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "path": [
                    "/Users/{my-username}/workspace/include",
                    "/Users/{my-username}/.platformio/packages/tool-unity",
                    ""
                ]
            },
            "defines": [
                "PLATFORMIO=50205",
                "NATIVE_ENV",
                "DEBUG",
                "__PLATFORMIO_BUILD_DEBUG__",
                ""
            ],
            "cppStandard": "c++17",
            "compilerPath": "/usr/bin/gcc",
            "compilerArgs": [
                ""
            ]
```

Everytime when I restart VS Code, it gets autogenerated and overwrites any manually added settings. And of course I don't want to add the "{default}" manually everytime upon start (as we also have several Developers).

Any help here is really appreciated :)

**Comment by sean-mcmanus** [comment] 2022-02-25 23:25
@derLalla This seems to be a PlatformIO issue since they're generating the c_cpp_properties.json without the ${default} in the includePath. Maybe you can file an issue for them to add it?

**Comment by Colengms** [comment] 2022-03-02 23:58
Closing this as an external issue.

**Closed as completed by Colengms** 2022-03-02 23:58 UTC
Labels: Language Service, external, Feature: Configuration
