### ISSUE TITLE
No warning about missing #include

### ISSUE THREAD

**Issue by mirao** [microsoft/vscode-cpptools#3386] opened 2019-03-30 13:54 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Uubuntu 18.10
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.22.1
- GCC: 8.2.0

**To Reproduce**

Have "my.c":
```c
int main(void)
{
    printf("Hello world\n");
    return 0;
}
```
This is an output of gcc:
```bash
$ gcc my.c
my.c: In function ‘main’:
my.c:3:5: warning: implicit declaration of function ‘printf’ [-Wimplicit-function-declaration]
     printf("Hello world\n");
     ^~~~~~
my.c:3:5: warning: incompatible implicit declaration of built-in function ‘printf’
my.c:3:5: note: include ‘<stdio.h>’ or provide a declaration of ‘printf’
my.c:1:1:
+#include <stdio.h>
 int main(void)
my.c:3:5:
     printf("Hello world\n");
     ^~~~~~
```
settings:
```json
{
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.clang_format_fallbackStyle": "{ BasedOnStyle: Google, IndentWidth: 4 }",
}
```
**Expected behavior**

- `printf` in editor should be underlined
- a warning/suggestion in gcc/clang style is shown, e.g: _include ‘<stdio.h>’ or provide a declaration of ‘printf’_
- the "Quick Fix" action should enable inserting of <stdio.h>. That would be great.

**Actual result**
- no warning

**Comment by sean-mcmanus** [comment] 2019-04-02 00:48
This is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/828 . We added warnings support but it got "postponed" because we didn't want to ship it without having the ability to disable specific warnings (https://github.com/Microsoft/vscode-cpptools/issues/2345) and we've had higher priority issues to work on.

**Closed as completed by sean-mcmanus** 2019-04-02 00:48 UTC
Labels: duplicate
