### ISSUE TITLE
Find references doesn't find struct member initializers

### ISSUE THREAD

**Issue by smoofra** [microsoft/vscode-cpptools#4173] opened 2019-08-30 20:48 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version:  Mac OS Catalina
- VS Code Version: 1.37.1
- C/C++ Extension Version: 0.25.1

**To Reproduce**
```
struct foo { 
    int some_field;
};

void bar() { 
    struct foo x = {
        .some_field = 1
    };
    x.some_field = 2;
}
```

1. Invoke "Find All References" on `some_field` in line 2 
2. It will find the assignment (line 9), but not the initializer (line 7)

**Expected behavior**
Find references should have found both references to `some_field`

It should also be able to find
```
struct foo x = {1};
```

**Comment by sean-mcmanus** [comment] 2019-08-30 21:10
The bug is inherited from VS. I've filed bug https://developercommunity.visualstudio.com/content/problem/718983/cc-designated-initializers-dont-appear-as-confirme.html .

The reference is reported as "Not A Reference" in the Output pane.

I'm not sure if "struct foo x = {1};" counts as a reference though.

**Comment by smoofra** [comment] 2019-08-30 21:13
In my opinion `= {1}` should also count, because it's initializing that specific field.    I don't think that `= {}` should count though.

**Comment by taihangg** [comment] 2021-01-19 09:09
excuse me !
how can i get the struct's member's references, such like "some_field"? 
I'm newer, i have tried some ways, but not work.

**Comment by sean-mcmanus** [comment] 2021-01-20 23:25
@taihangg Just do a Find All References:
![image](https://user-images.githubusercontent.com/19859882/105253122-ac78f500-5b33-11eb-9a25-a5544c3be545.png)

This issue is on the fact that the initializer is reported as "Not a Reference".

**Comment by sparr** [comment] 2024-10-04 12:04
I wasn't able to reproduce with a test case so I'm not filing a new bug, but this is probably related:

The reference to `emulate` on this line: https://github.com/dsalt/devilspie2/blob/760df8ce0db8f51c75acbb27ab0e420174cb8352/src/devilspie2.c#L321 also triggers the "NOT A REFERENCE" behavior when doing "Find All References" on another reference to `emulate`.

My example and this whole bug may also be related to #4083

**Comment by bobbrow** [comment] 2024-11-27 23:53
The original problem reported in this issue appears to be fixed in the latest version of the extension.

@sparr I tried something similar to what that file you referenced is doing since I'm not set up for IntelliSense for that project. With my trimmed down version, the reference was correctly reported, but if this is still a bug for you, please open a new issue.

**Closed as completed by bobbrow** 2024-11-27 23:53 UTC
Labels: bug, Language Service, Visual Studio, Feature: Find All References
