### ISSUE TITLE
includePath should support recursive globbing of "intermediate" paths

### ISSUE THREAD

**Issue by Wetmelon** [microsoft/vscode-cpptools#3317] opened 2019-03-19 09:57 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version:  Windows 10
- VS Code Version: Version: 1.32.3 (user setup)
- C/C++ Extension Version: 0.21.0

**Expected behavior**

I have a directory structure that looks something like:

    (${workspaceFolder})
        common
            _inc
                common.h
            _src
                common.cpp
        module1
            _inc
                module1.h
            _src
                module1.cpp
        module2
            _inc
                module2.h
            _src
                module2.cpp
        module3
            ...
        moduleN
            ...

I would like to include all `_inc` folders without having to recursively parse the entire directory tree (slow).  In other words, I would expect the following to work and ONLY look in `_inc` directories:

```
            "includePath": [
                "${workspaceFolder}/**/_inc"
            ],
```

Workspace Intellisense Settings:
```
    "C_Cpp.intelliSenseEngine": "Default",
    "C_Cpp.intelliSenseEngineFallback": "Disabled"
```

**Comment by bobbrow** [comment] 2019-03-19 16:02
Thank you for your feedback.  This looks like a duplicate of #723.  Can you please go add a +1 to that issue to vote for it?

**Closed as completed by bobbrow** 2019-03-19 16:02 UTC
