### ISSUE TITLE
Incorrect autocomplete

### ISSUE THREAD

**Issue by yurriy** [microsoft/vscode-cpptools#813] opened 2017-06-10 00:36 UTC
If I write "i++;", end type Enter, I get the line
i++;____FILE_defined
instead of just "i++;"
Every time I use "++" operator, the extension proposes definitions from headers, which start from __

**Comment by sean-mcmanus** [comment] 2017-06-10 00:40
I'm not able to repro this. Does it repro with the cpptools extension disabled? What OS are you on? What VS Code version do you have? The completion popup isn't supposed to appear after a semicolon is entered.

**Comment by yurriy** [comment] 2017-06-10 00:42
@sean-mcmanus No, it doesn't repro with cpptools disabled. I'm under Ubuntu 16.04. I've just updated VS Code

**Comment by sean-mcmanus** [comment] 2017-06-10 00:49
I'm still not reproing the issue on Linux. It sounds like a bug with VS Code invoking quick suggestions when it shouldn't (i.e. ctrl+space). Our extension does not invoke completion on `;`. It sounds like you're getting a completion popup after entering the `;`?

**Comment by yurriy** [comment] 2017-06-10 00:51
@sean-mcmanus in this case the popup doesn't disappear, maybe c_cpp_properties.json will help https://gist.github.com/yurriy/46cb29de802c902d7eedd4bb7a72240e
But if I type, for instance, "print", and then semicolon, then indeed, the popup will disappear.

**Comment by yurriy** [comment] 2017-06-10 00:54
@sean-mcmanus the popup screenshot: https://www.dropbox.com/s/xezqz2noymhgg80/

**Comment by yurriy** [comment] 2017-06-10 01:00
@sean-mcmanus it seems like it's an issue with VS Code, I added 
"editor.quickSuggestions":{"other": false, "comments": false, "strings": false}
in settings, and now it works fine.

**Comment by sean-mcmanus** [comment] 2017-06-10 01:02
Could you file an issue with VS Code? This bug appears to be theirs. https://github.com/Microsoft/vscode/issues . VS Code just asks us for the list of completion items and we get to them the list and the fact that we want suggestions on `.`, `->`, `::`, and `#`, not `;`...so our extension is probably not the cause of the bug (i.e. other extensions that provide completions would probably get the same results). I don't know why I'm not able to repro it though. I have quickSuggestions set to true too.

**Comment by yurriy** [comment] 2017-06-10 01:05
Ok, I will write an inssue in VS Code repo, thanks.

**Comment by bobbrow** [comment] 2017-07-06 04:04
This is the same issue as #818 which has been fixed by the VS Code team.

**Closed as completed by bobbrow** 2017-07-06 04:04 UTC
Labels: bug, Language Service, more info needed
