### ISSUE TITLE
Ctrl+T (Go to Symbol in Workspace...) does not support fuzzy search

### ISSUE THREAD

**Issue by Jamwe** [microsoft/vscode-cpptools#10715] opened 2023-03-21 12:33 UTC
Type: <b>Bug</b>

Ctrl+T (Go to Symbol in Workspace...) does not support fuzzy search.
But Ctrl+Shift+O (Go to Symbol in Editor...) partly support it.
Here is the same issue [VSCode #156865](https://github.com/microsoft/vscode/issues/156865) reported to VSCode which they didn't approve.

Extension version: 1.14.4
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-110-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Ubuntu-18|
|OS|Linux x64 5.4.0-110-generic|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (4 x 1689)|
|Memory (System)|3.84GB (2.31GB free)|
|VM|100%|
</details>

**Comment by Colengms** [comment] 2023-03-22 23:15
Hi @Jamwe .  I believe this a duplicate of: https://github.com/microsoft/vscode-cpptools/issues/2751

Could you up-vote that issue?

**Closed as not planned by Colengms** 2023-03-22 23:15 UTC

**Comment by Jamwe** [comment] 2023-03-23 03:53
@Colengms TKS, That's it. vote both that issue and feature request on VS.
