### ISSUE TITLE
Add possibility to refactor/move

### ISSUE THREAD

**Issue by wisepotato** [microsoft/vscode-cpptools#6270] opened 2020-10-07 16:32 UTC
So currently, if i move a file from `x/my_lovely_header.h` to `y/my_lovely_header.h` i have to redo my global and local includes. I'd like that to be done automatically as it makes my refactoring life easier. 

I searched the issues, but couldn't find anything similar, and I think refactoring is a large reason why people use this kind of extension. (it's great btw)

Also wouldn't mind tackling this when i have time, but that's currently hard to come by.

**Comment by bobbrow** [comment] 2020-10-08 21:57
This looks like a duplicate of #4823 which was actually just closed due to insufficient upvotes.  If you can go upvote that issue, our bot will reopen it and we'll track the request using that issue.  Thank you!

**Closed as completed by bobbrow** 2020-10-08 21:57 UTC
Labels: duplicate, Language Service, Feature Request, Feature: Refactoring

**Comment by wisepotato** [comment] 2020-10-09 12:29
thanks for your comment, i could not find that.
