### ISSUE TITLE
Automatically load counterpart files in a separate pane, like Xcode Assistant Editor

### ISSUE THREAD

**Issue by csnover** [microsoft/vscode-cpptools#10532] opened 2023-02-16 04:30 UTC
### Feature Request

This may be the same request as #10346; the description in that ticket was not totally clear. Hopefully this one is clear enough to be actionable. Please feel free to close/merge it into that ticket if they are the same thing.

Xcode has a feature called Assistant Editor which creates a split view where the pane on the right automatically loads the counterpart file for whatever is loaded in the main editor on the left. So, for example, if you load a .c file in the main editor, Xcode will automatically load the corresponding .h file in the assistant editor (or vice-versa). This request is to add this feature to vscode-cpptools.

For implementation, the built-in markdown-language-features extension seems like a good place to start since its “Open Preview” commands work exactly the way this feature should be implemented (in particular, “Open Preview to the Side”), except that here the ‘preview’ would be another editor for the counterpart file. (For clarity: both Xcode Assistant Editor and the VSCode Markdown Preview use one tab and change the content automatically based on to what other tab is currently active, rather than opening new tabs for each source file.)

If this sounds like something that would be accepted as a new feature, I may try implementing it myself, depending on free time. If this already exists, my apologies and let me know where it is.

Thanks,

**Comment by sean-mcmanus** [comment] 2023-02-16 20:06
Yeah, this sounds like a duplicate of https://github.com/microsoft/vscode-cpptools/issues/10346, but I agree with you that issue is hard to understand, so I'll close the other issue as a duplicate of this one.

**Comment by cjwijtmans** [comment] 2023-02-17 04:11
How i envisioned it was not a pane but being able to set regex rules on a editor group. Which would make it a vscode feature not a cpptools feature.

**Comment by sean-mcmanus** [comment] 2023-02-17 18:48
@cjwijtmans Sure, can you file a feature request at https://github.com/microsoft/vscode/issues ?

**Comment by csnover** [comment] 2023-02-17 21:33
Editor group by regular expression has an upstream ticket already and was closed due to lack of community upvotes: https://github.com/microsoft/vscode/issues/136162

**Comment by cjwijtmans** [comment] 2023-02-18 20:04
> Editor group by regular expression has an upstream ticket already and was closed due to lack of community upvotes: [microsoft/vscode#136162](https://github.com/microsoft/vscode/issues/136162)

I do not see anything about regex there. But sad to see it rejected. I guess we will need cpptools panel then.

**Closed as not planned** 2023-04-24 11:53 UTC
Labels: Language Service, Feature Request, more votes needed
