### ISSUE TITLE
Inspect Editor Tokens and Scopes always shows "loading" with this extension enabled

### ISSUE THREAD

**Issue by xianpul** [microsoft/vscode-cpptools#11049] opened 2023-06-06 01:51 UTC
Type: <b>Bug</b>

Select a symbol, for example, enumMember or function, then open "Inspect Editor Tokens and Scopes", "loading" is showing constantly.

Extension version: 1.15.4
VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin arm64 22.5.0
Modes:
Sandboxed: No
Connection to 'ssh-remote+cloud-desktop' could not be established

**Comment by Colengms** [comment] 2023-06-06 18:08
Hi @xianpul .  The UI for "Inspect Editor Tokens and Scopes" is part of VS Code itself.  There shouldn't be any way for the C/C++ Extension to directly cause it to fail to load.  This would seem to be a VS Code issue. Consider opening an issue in [the VS Code repo](https://github.com/microsoft/vscode/issues).

> Connection to 'ssh-remote+cloud-desktop' could not be established

If you're also seeing an error connecting to your remote, that would also be a VS Code feature.

Closing this as external.

**Closed as not planned by Colengms** 2023-06-06 18:08 UTC

**Comment by sean-mcmanus** [comment] 2023-06-06 20:48
I think this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/9835, which has a workaround discussed.
