### ISSUE TITLE
IntelliSense-based Go to Definition doesn't filter by the IntelliSense info when a new TU is first opened

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2735] opened 2018-10-29 23:30 UTC
1. Open a new .cpp file and then use Go to Definition before the red flame disappears -- use it on something with multiple symbols with conflicting names like begin()/end().

Bug: Instead of waiting for the IntelliSense-info to filter the results, it uses the incorrect unfiltered data which includes lots of undesirable symbols (i.e. the old behavior).

Up-vote this if you think it's important to fix. VS Code doesn't have a way to give progressively better results over time, asynchronously.

**Comment by bobbrow** [comment] 2020-11-12 22:47
Closing. There wasn't enough interest in working through this further.  The current behavior is by design.

**Closed as completed by bobbrow** 2020-11-12 22:47 UTC
Labels: Language Service, Feature Request, by design, more votes needed
