### ISSUE TITLE
Add support for -nostdinc to the indexer

### ISSUE THREAD

**Issue by nlieb** [microsoft/vscode-cpptools#5936] opened 2020-08-08 03:18 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.47.3
- C/C++ Extension Version: 0.30-insider
- Other extensions you installed (and if the issue persists after disabling them): "Native Debug", "Open in Github", "vscode-proto3", and yes, it persists.
- Does this issue involve using SSH remote to run the extension on a remote machine?: I am using SSH remote, but I don't think this issue is related

**Steps to reproduce**
Have a project which uses the `-nostdinc` I expect the indexer to not parse `/usr/include`, and `/usr/local/include`:

```
clang -v -E -x c++ -nostdinc - /dev/null
clang version 10.0.0 
[...]
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0
 /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/x86_64-linux-gnu/c++/7.4.0
```

vs.

```
clang -v -E -x c++ - /dev/null
clang version 10.0.0 
[...]
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0
 /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/x86_64-linux-gnu/c++/7.4.0
 /usr/local/include
 /home/nliebrecht/.cache/bazel/_bazel_nliebrecht/86d38ffcd030d83e5af990aa909a9db7/external/clang/lib/clang/10.0.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
```

However when checking the language server logs we can see that these folders are indexed:

```
  Folder: /usr/local/include/ will be indexed
  [...]
  Folder: /usr/include/ will be indexed
```

`c_cpp_properties.json`:

```
{
    "configurations": [
        {
            "name": "Linux",
            "defines": [],
            "cStandard": "c11",
            "cppStandard": "c++20",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "${workspaceRoot}/build/bin/compile_commands.json",
            "browse": {
                "limitSymbolsToIncludedHeaders": true
            },
            "compilerArgs": [
                "-nostdinc"
            ]
        }
    ],
    "version": 4
}
```

**Expected behavior**

I expect the parser to skip `/usr/...` if `-nostdinc` is passed. Hopefully this will speed up indexing which is currently very slow. Unfortunately I cannot provide detailed logs and diagnostics because of the proprietary nature of the project.

Thank you.

**Comment by sean-mcmanus** [comment] 2020-08-10 23:05
The workaround is to set compilerPath and compilerArgs.

One bug is that our special browse.path handling for compileCommands isn't handling the -stdinc in the compile_commands.json. Another bug is that that the compileArgs in c_cpp_properties.json isn't used if compilerPath isn't set if compileCommands is set.

**Comment by Colengms** [comment] 2020-10-29 01:44
I believe the issue with not processing the args from a `compile_commands.json`, has been addressed.  It should now pass that argument along when probing the compiler, preventing the compiler from returning system paths.  It's currently by design that the `compilerArgs` in the base config are not merged with the compiler args in a `compile_commands.json`.  Specifying a `compilerPath` in the base config overrides the compiler specified in `compile_commands.json`, and also leverages the `compilerArgs` in the base config.  In that case, the args in `compile_commands.json` are not leveraged for the compiler probe, only `compilerArgs`.  But, any includes and defines specified in args in `compile_commands.json` are still added to the browse path.

**Closed as completed** 2020-10-29 01:44 UTC
Labels: bug, Language Service, Feature: Configuration, verified, Feature: Compile Commands, has workaround
