### ISSUE TITLE
" incomplete type is not allowed " when I use pcl::PointXYZ

### ISSUE THREAD

**Issue by OptSolution** [microsoft/vscode-cpptools#1430] opened 2018-01-10 05:40 UTC
ubuntu 16.04
VS Code 1.19.1
C/C++ 0.14.5

When I use `pcl::PointXYZ  point;` ; it will say _incomplete type is not allowed_
When I use `pcl::PointCloud<pcl::PointXYZ>  pointCloud`; it will say nothing

you can try tutor of PCL , like this http://pointclouds.org/documentation/tutorials/moment_of_inertia.php#moment-of-inertia

**Comment by sean-mcmanus** [comment] 2018-01-10 05:55
Thanks for reporting this. I'll let you know what I find...

**Comment by sean-mcmanus** [comment] 2018-01-10 06:33
Yikes, that project has a lot of dependencies to setup. On Windows, IntelliSense has major failure problems (crashes/stalls/stuck flame) without even getting all the paths resolved. On Linux, I still haven't gotten all the dependencies. Is there an easy way to get the pcl_config.h without building?

**Comment by OptSolution** [comment] 2018-01-10 06:44
maybe you can use the DEB file in this blog 
https://larrylisky.com/2016/11/03/point-cloud-library-on-ubuntu-16-04-lts/

**Comment by sean-mcmanus** [comment] 2018-01-10 06:48
Are you able to get all your #include's resolved in the Problems window? I can generate the incomplete type message when `struct EIGEN_ALIGN16 PointXYZ
{};` is used without EIGEN_ALIGN16 being defined, so that could be related.

**Comment by sean-mcmanus** [comment] 2018-01-10 06:57
I don't have the dependencies required to run the DEB (it complains about a lot):
`dpkg: dependency problems prevent configuration of pcl:
 pcl depends on freeglut3; however:
  Package freeglut3 is not installed.
 pcl depends on libboost-date-time1.58.0; however:
  Package libboost-date-time1.58.0 is not installed.
 pcl depends on libboost-filesystem1.58.0; however:
  Package libboost-filesystem1.58.0 is not installed.
 pcl depends on libboost-iostreams1.58.0; however:
  Package libboost-iostreams1.58.0 is not installed.
 pcl depends on libboost-system1.58.0; however:
  Package libboost-system1.58.0 is not installed.
 pcl depends on libboost-thread1.58.0; however:
  Package libboost-thread1.58.0 is not installed.
 pcl depends on libqhull7; however:
  Package libqhull7 is not installed.
 pcl depends on libvtk6.2; however:
  Package libvtk6.2 is not installed.
 pcl depends on libvtk6.2-qt; however:
  Package libvtk6.2-qt is not installed.`

**Comment by sean-mcmanus** [comment] 2018-01-10 07:03
If you're able to build the pcl using cmake, you might try getting a compile_commands.json created and using the path for the "compileCommands" field in c_cpp_properties.json if you're having problems getting the includePath and defines correct.

**Comment by OptSolution** [comment] 2018-01-10 07:03
I think I get all my #include's resolved, my code can work well, and this my config
{
            "name": "Linux",
            "includePath": [
                "/usr/include/c++/5",
                "/usr/include/x86_64-linux-gnu/c++/5",
                "/usr/include/c++/5/backward",
                "/usr/lib/gcc/x86_64-linux-gnu/5/include",
                "/usr/local/include",
                "/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include",
                "${workspaceRoot}",
                "/usr/include/eigen3",
                "/usr/local/include/pcl-1.8",
                "/usr/include/vtk-6.2",
                "/usr/include/suitesparse/csparse"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include/c++/5",
                    "/usr/include/x86_64-linux-gnu/c++/5",
                    "/usr/include/c++/5/backward",
                    "/usr/lib/gcc/x86_64-linux-gnu/5/include",
                    "/usr/local/include",
                    "/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                    "/usr/include/x86_64-linux-gnu",
                    "/usr/include",
                    "${workspaceRoot}",
                    "/usr/include/eigen3"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },

emm..... pcl really required many dependencies...

**Comment by sean-mcmanus** [comment] 2018-01-10 07:11
So you don't see any "cannot find source file" message in the Problems window? Your include paths do not appear to be correct from what I can tell. The includePath property is not recursive, so you'd need to at least add some pcl-1.8 subdirectories I would think. If you add the root of libraries to the browse.path (e.g. /usr/local/include/pcl-1.8), the files will be recursively located and available via the code action lightbulb. As I mentioned earlier, exporting a compile_commands.json might be the best way to get IntelliSense working: https://stackoverflow.com/questions/20059670/how-to-use-cmake-export-compile-commands .

**Comment by OptSolution** [comment] 2018-01-10 07:25
Yes, VS Code don't say that. I tried add /usr/local/include/pcl-1.8 to  browse.path , but nothing changed. I will try other subdirectories

**Comment by sean-mcmanus** [comment] 2018-01-10 07:38
What is the smallest file that repros the problem? Like this?
`#include <pcl/point_types.h>
pcl::PointXYZ point;`
I'm seeing point_types.h defined at /pcl-master/common/include/pcl/point_types.h, which isn't in the include path you posted.

**Comment by OptSolution** [comment] 2018-01-10 07:53
I get the compile_commands.json  and add all the paths into the c_cpp_properties.json, that also doesn't work.
After I install PCL, the path of the file is /usr/local/include/pcl-1.8/pcl/point_types.h and VS Code find the file

**Comment by sean-mcmanus** [comment] 2018-01-10 07:56
With compile_commands.json, the includePath setting is ignored and the json file is used directly. You just set the path via the compileCommands property: https://blogs.msdn.microsoft.com/vcblog/2017/10/20/visual-studio-code-cc-extension-october-2017-update/ .

**Comment by sean-mcmanus** [comment] 2018-01-10 07:59
Oh, looks like I was using the PCL source instead of the installed library.

**Comment by sean-mcmanus** [comment] 2018-01-10 08:09
After installing the pcl library at /usr/local/include and adding the include paths. I have IntelliSense working and no errors with a simple file:
`#include <pcl/point_types.h>
pcl::PointXYZ point;`.

Does the repro require more?

**Comment by sean-mcmanus** [comment] 2018-01-10 08:14
And the cmake I was referring to was the one used by the source of pcl used to generate the library. User code doesn't require cmake. If your own project uses cmake then you could still use the compile_commands, but it might not be necessary if you have a simple include structure.

**Comment by OptSolution** [comment] 2018-01-10 08:18
I think it doesn't require, I'm trying to use the compile_commands

**Comment by ksemianov** [comment] 2018-03-12 12:59
I have a similar issue. Here is the code to reproduce:
```
#include <pcl/point_types.h>
#include <pcl/point_cloud.h>

void main() {
    pcl::PointXYZ point; // incomplete type is not allowed
    pcl::PointCloud<pcl::PointXYZ> cloud; // no error message
    cloud.points[0].x; // incomplete type is not allowed
}
```

I guess IntelliSense doesn't parse properly these macros in `pcl/point_cloud.h` defined in `pcl/register_point_struct.h`:
```
POINT_CLOUD_REGISTER_POINT_STRUCT (pcl::_PointXYZ,
    (float, x, x)
    (float, y, y)
    (float, z, z)
)
POINT_CLOUD_REGISTER_POINT_WRAPPER(pcl::PointXYZ, pcl::_PointXYZ)
```

**Comment by sean-mcmanus** [comment] 2018-03-12 19:39
@ksemianov I was able to use pcl::PointXYX with no "incomplete type" message. Can you give more repro details, such as your OS and some of your c_cpp_properties.json settings? The macros in point_cloud.h should be parsed correctly.

**Comment by ksemianov** [comment] 2018-03-12 19:54
macOS High Sierra 10.13.3
VS Code 1.20.0
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/Library/Developer/CommandLineTools/usr/include/c++/v1",
                "/usr/local/include",
                "/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/include",
                "/Library/Developer/CommandLineTools/usr/include",
                "/usr/include",
                "/usr/local/Cellar/eigen/3.3.4/include/eigen3/",
                "/usr/local/Cellar/pcl/1.8.1_2/include/pcl-1.8/",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/Library/Developer/CommandLineTools/usr/include/c++/v1",
                    "/usr/local/include",
                    "/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/include",
                    "/Library/Developer/CommandLineTools/usr/include",
                    "/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        }
    ],
    "version": 3
}
```

**Comment by sean-mcmanus** [comment] 2018-03-12 20:08
@ksemianov Okay, I haven't tried that project on Mac yet. One thing that might work is using our insiders build and setting your compilerPath to your clang, which will automatically setup the correct system include paths and defines: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders .

**Comment by ksemianov** [comment] 2018-03-12 22:30
Insiders build works as expected. Thank you!

**Closed as completed** 2018-07-12 01:58 UTC
Labels: Language Service, fixed, parser
