### ISSUE TITLE
cpptools in WSL2 only use one cpu core when parsing workspace files

### ISSUE THREAD

**Issue by Cosss7** [microsoft/vscode-cpptools#10198] opened 2022-11-29 10:24 UTC
### Environment

- OS and Version: win11 22H1
- VS Code Version:1.73.1
- C/C++ Extension Version:1.13.5
- Other extensions you installed (and if the issue persists after disabling them):  
- If using SSH remote, specify OS of remote machine:  WSL2
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

### Bug Summary and Steps to Reproduce

Bug Summary:

cpptools in WSL2 only use one cpu core when parsing workspace files.
So very slow when opening large code base.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/12772673/204501642-ef206bbe-ec2f-436d-9fcd-8d61238a47b2.png">

<img width="560" alt="image" src="https://user-images.githubusercontent.com/12772673/204501882-5df88052-5501-48e5-96c4-f40e308e4903.png">

Steps to reproduce:
1. just open some c project, and mine is linux kernel code.

### Expected behavior

Maybe more than 100 cpu usage.

### Code sample and Logs

```shell
-
```

### Additional context

Let me know if need any other infomation.

**Comment by sean-mcmanus** [comment] 2022-11-29 19:10
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/2083 .

**Closed as not planned by sean-mcmanus** 2022-11-29 19:10 UTC
Labels: duplicate
