### ISSUE TITLE
user-defined literal operator not found

### ISSUE THREAD

**Issue by yaroslavsadin** [microsoft/vscode-cpptools#4635] opened 2019-11-19 15:45 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 7
- VS Code Version: 1.40.1
- C/C++ Extension Version: 0.26.2-insiders
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Error squiggle appears while trying to use string literals.

**To Reproduce**

Simply copy paste code from: https://en.cppreference.com/w/cpp/string/basic_string/operator%22%22s

**Comment by sean-mcmanus** [comment] 2019-11-19 21:26
The root cause is https://developercommunity.visualstudio.com/content/problem/797098/cc-intellisense-with-gccclang-mode-reports-incorre.html and https://github.com/microsoft/vscode-cpptools/issues/2460 .

The issue doesn't repro on Linux.

However, on closer examination it looks like our code path might be different from VS in this case it might be an issue we want to investigate fix on our end first.

**Comment by sean-mcmanus** [comment] 2019-11-19 21:30
Also, what is your intelliSenseMode? I did the repro on Win10 with WSL with gcc-x64 mode, not msvc-x64 mode.

**Comment by sean-mcmanus** [comment] 2019-11-19 21:38
Oh, I see from your other bug report you're using Cygwin.

**Comment by sean-mcmanus** [comment] 2019-11-19 22:26
@Colengms Can you check if https://developercommunity.visualstudio.com/content/problem/797098/cc-intellisense-with-gccclang-mode-reports-incorre.html is actually the root cause ?

**Comment by Colengms** [comment] 2019-11-20 00:56
It does appear to be an issue with size_t.  In the repro case, I see a squiggle on the definition of the user-defined literal operator, complaining about a mismatch with size_t.  The symptom is reversed between Windows and Linux.  On Windows (x64), I see the squiggle with `gcc-x64`.  On Linux (x86_64), I see the squiggle with `gcc-x86`.

**Comment by sean-mcmanus** [comment] 2019-11-20 01:58
We figured out the cause. A workaround is to add -m32 to the compilerArgs setting (or at the end of the compilerPath) for gcc-x86 mode or add -m64 for gcc-x64 mode.

If you're targeting x86 though, you'll need to make sure you have the i386 gcc installed or you'll get include errors.

**Comment by Colengms** [comment] 2019-11-21 20:37
This should be addressed by https://github.com/microsoft/vscode-cpptools/pull/4644 (and a change to the native process, which is not in this repo).

**Closed as completed** 2019-12-03 01:00 UTC
Labels: bug, Language Service, fixed

**Comment by yaroslavsadin** [comment] 2020-04-20 19:07
I still don't see this fix.

**Comment by kosiu** [comment] 2020-05-24 12:31
the same for me, still the same problem

**Comment by sean-mcmanus** [comment] 2020-05-28 01:27
Can you provide more repro details? Such as from running C/C++: Log Diagnostics from the Command Palette?

**Comment by Guyutongxue** [comment] 2020-08-21 02:44
> Can you provide more repro details? Such as from running C/C++: Log Diagnostics from the Command Palette?


I ran into this problem too. My "Log Diagnostics" is:
```
-------- Diagnostics - 2020/8/21 上午10:42:00
Version: 0.29.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:\\mingw64\\bin\\gcc.exe",
    "cStandard": "c11",
    "compilerArgs": [],
    "cppStandard": "c++20",
    "intelliSenseMode": "gcc-x64",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\Code\Cpp\Misc\test.cpp ]:
    D:\CODE\CPP\MISC\TEST.CPP
[ D:\Code\Cpp\Misc\temp.cpp ]:
    D:\CODE\CPP\MISC\TEMP.CPP
Translation Unit Configurations:
[ D:\Code\Cpp\Misc\test.cpp ]:
    Process ID: 37644
    Memory Usage: 15 MB
    Compiler Path: C:\mingw64\bin\gcc.exe
    Includes:
        C:\MINGW64\INCLUDE\C++\10.1.0
        C:\MINGW64\INCLUDE\C++\10.1.0\X86_64-W64-MINGW32
        C:\MINGW64\INCLUDE\C++\10.1.0\BACKWARD
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.1.0\INCLUDE
        C:\MINGW64\INCLUDE
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.1.0\INCLUDE-FIXED
        C:\MINGW64\X86_64-W64-MINGW32\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++20
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100100
[ D:\Code\Cpp\Misc\temp.cpp ]:
    Process ID: 32324
    Memory Usage: 35 MB
    Compiler Path: C:\mingw64\bin\gcc.exe
    Includes:
        C:\MINGW64\INCLUDE\C++\10.1.0
        C:\MINGW64\INCLUDE\C++\10.1.0\X86_64-W64-MINGW32
        C:\MINGW64\INCLUDE\C++\10.1.0\BACKWARD
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.1.0\INCLUDE
        C:\MINGW64\INCLUDE
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.1.0\INCLUDE-FIXED
        C:\MINGW64\X86_64-W64-MINGW32\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++20
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100100
Total Memory Usage: 50 MB

```

**Comment by guyutongxue** [comment] 2020-08-21 03:10
I ran into the same problem. The `size_t` in `<string_view>` is squiggled. Here is the Log Diagnostics:

<details><summary>Log Diagnostics</summary>

```
-------- Diagnostics - 2020/8/21 上午11:09:09
Version: 0.29.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:\\mingw64\\bin\\gcc.exe",
    "cStandard": "c11",
    "compilerArgs": [
        "-m64"
    ],
    "cppStandard": "c++20",
    "intelliSenseMode": "gcc-x64",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\Code\Cpp\Misc\temp.cpp ]:
    D:\CODE\CPP\MISC\TEMP.CPP
[ D:\Code\Cpp\Misc\test.cpp ]:
    D:\CODE\CPP\MISC\TEST.CPP
Translation Unit Configurations:
[ D:\Code\Cpp\Misc\temp.cpp ]:
    Process ID: 42212
    Memory Usage: 64 MB
    Compiler Path: C:\mingw64\bin\gcc.exe
    Includes:
        C:\MINGW64\INCLUDE\C++\10.1.0
        C:\MINGW64\INCLUDE\C++\10.1.0\X86_64-W64-MINGW32
        C:\MINGW64\INCLUDE\C++\10.1.0\BACKWARD
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.1.0\INCLUDE
        C:\MINGW64\INCLUDE
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.1.0\INCLUDE-FIXED
        C:\MINGW64\X86_64-W64-MINGW32\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++20
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100100
[ D:\Code\Cpp\Misc\test.cpp ]:
    Process ID: 42996
    Memory Usage: 22 MB
    Compiler Path: C:\mingw64\bin\gcc.exe
    Includes:
        C:\MINGW64\INCLUDE\C++\10.1.0
        C:\MINGW64\INCLUDE\C++\10.1.0\X86_64-W64-MINGW32
        C:\MINGW64\INCLUDE\C++\10.1.0\BACKWARD
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.1.0\INCLUDE
        C:\MINGW64\INCLUDE
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\10.1.0\INCLUDE-FIXED
        C:\MINGW64\X86_64-W64-MINGW32\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++20
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100100
Total Memory Usage: 86 MB

```

</details>

By the way, adding `-m64` into `compilerArgs` doesn't fix this problem.
