### ISSUE TITLE
Documentation comments aren't working for gcc std::string (probably other cases too)

### ISSUE THREAD

**Issue by bananalemonmelon** [microsoft/vscode-cpptools#7493] opened 2021-05-08 15:59 UTC
Bug type: Language Service

- OS and Version: Windows 10 - Version 10.0.19042 Build 19042
- VS Code Version: 1.54.2 (system setup)
- C/C++ Extension Version: 1.2.2

Try to type the following code:
```
#include <string>
std::string str()
```
Hints of all available constructor should be displayed after typing the opening bracket `(`.
Try to press `Ctrl+Shift+Space` inside the bracket, nothing happens, the hints are not shown.

Now try to enter a number within the bracket followed by a comma.
```
#include <string>
std::string str(3,
```
The hints for constructor are displayed, albeit the signature is not the appropriate one (the number `3` is being recognized as `char *`).
Scrolling through all constructor override, the code comment (documentation) doesn't shown for several signature.

**Comment by VitorMouro** [comment] 2021-05-08 21:30
I'm having the same issue

- OS and Version: Windows 10 Pro - Version 10.0.19043 Build 19043
- VS Code Version: 1.57.0-insider (user setup)
- C/C++ Extension Version: 1.3.1

**Comment by sean-mcmanus** [comment] 2021-05-10 19:55
The 1st issue is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/7258. You can use `{}` as a workaround (see https://en.wikipedia.org/wiki/Most_vexing_parse).

The 3 being treated as a `char*` is "by design" since 3 is valid in regards to overload signature matching, i.e. you'll get a compile error with code
```
void func(int i) {}
void func(char* v) {}
```.

I'm reproing the issue with documentation comments with the gcc headers -- are you using gcc headers?

**Comment by pisanglemonmelon** [comment] 2021-05-10 21:30
Thanks for the reply.

> are you using gcc headers?

Yes, correct. I'm using GCC.

**Comment by sean-mcmanus** [comment] 2021-05-10 23:12
The documentation comment is failing due to the code being in a namespace, which is a duplicate of bug https://github.com/microsoft/vscode-cpptools/issues/5241 .

**Closed as completed by sean-mcmanus** 2021-05-10 23:12 UTC
Labels: bug, duplicate, Language Service, Feature: Doc comments, Works in VS
