### ISSUE TITLE
Wrong error message when using C _Generic selection

### ISSUE THREAD

**Issue by SPAstef** [microsoft/vscode-cpptools#5704] opened 2020-06-26 14:02 UTC
Hi,
whenever I use a structure as the argument of a generic selection, the intellisense engine reports error "type must be an object type" (I assume it means a scalar type?), but the code is completely legal in standard C11 and compiles and works with no problems.

![image](https://user-images.githubusercontent.com/9153046/85865572-638fd680-b7c6-11ea-803f-7dc544612524.png)

**Comment by sean-mcmanus** [comment] 2020-06-26 19:28
Please provide the definition for vec2_t or some other type that exhibits the bug. Our parser seems to be having some problem handling that.

**Comment by SPAstef** [comment] 2020-06-26 19:36
Oh, it's just:
```
typedef struct vec2
{
    float x;
    float y;
} vec2_t;
```

**Comment by sean-mcmanus** [comment] 2020-06-26 19:59
Thanks for reporting this. I've filed a bug on VS at https://developercommunity.visualstudio.com/content/problem/1093395/cc-intellisense-gives-an-error-type-must-be-an-obj.html .

**Comment by bstn-hfmn** [comment] 2021-08-08 09:05
Any update on this? having the same issue.

**Comment by sean-mcmanus** [comment] 2021-08-10 01:14
@bstn-hfmn No update -- it may need more upvotes to prioritize fixing it.

**Comment by HunterKohler** [comment] 2021-08-16 22:37
@bstn-hfmn Same, not sure why. It seems that this previously was working however.

**Comment by sean-mcmanus** [comment] 2022-01-06 20:18
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders2, but FYI if you're using gcc on Windows then -fms-extension is getting automatically added with that version, which causes some IntelliSense parsing regressions, which we plan to either fix or switch to -fno-ms-extensions by default for 1.8.0-insiders3.

**Closed as completed** 2022-02-01 20:39 UTC
Labels: bug, Language Service, fixed, Visual Studio
