### ISSUE TITLE
Default intellisense engine does not search for header files recurively in nested folders

### ISSUE THREAD

**Issue by reporter123** [microsoft/vscode-cpptools#1257] opened 2017-11-16 02:03 UTC
# I am using the fallowing c_cpp_properties.json

{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include/x86_64-linux-gnu/c++/6",
                "/usr/include/c++/6",
                "/usr/local/include",
                "/usr/lib/clang/4.0.0/include",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include/x86_64-linux-gnu/c++/6",
                    "/usr/include/c++/6",
                    "/usr/local/include",
                    "/usr/lib/clang/4.0.0/include",
                    "/usr/include/x86_64-linux-gnu",
                    "/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include",
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}

QT and KDE install headers into subfolders of "/usr/include/x86_64-linux-gnu" for 5+ or "/usr/include/x86_64-linux-gnu" for 4.x. Neither the old "Tag Parser" engine nor clang/llvm have any issue finding the fallowing:
`
#include <QApplication>
#include <QTemporaryFile>
`

However the new intellisense engine does not see them unless the exact path they are in is specified. This is impractical as QT and KDE include dozens of modules. I can understand needing an unambiguous path currently no recursion what ever is done. Unfortunately this is show stopper for me I switched back to "Tag Parser" so I don't get spammed messages about unlocatable headers ever time I open a project based on QT/KDE. Which is almost everything I work with.

**Comment by bobbrow** [comment] 2018-03-01 23:17
This is a duplicate of #897.  We're looking to implement this for April.

**Closed as completed by bobbrow** 2018-03-01 23:17 UTC
Labels: duplicate, Language Service, Feature Request
