### ISSUE TITLE
Intellisense crashes if file is open or edited in external program

### ISSUE THREAD

**Issue by schperplata** [microsoft/vscode-cpptools#2054] opened 2018-05-29 09:07 UTC
Issue Type: <b>Bug</b>
Intellisense crashes until restart if file is opened/saved/edited in external program/editor.

- Open some c file with VS Code (I am doing on some C software)
- wait for intellisense to start working (showing definitions and suggestions)
- open the same file in another external program. I am having problem with winIDEA
(https://www.isystem.com/downloads/winidea.html)
- do whatever, just open, or save or both
- back in VS Code, test if Intellisense is still working.

In my case Intellisense (or more specific, go to definition, peek definition, ...) is not working anymore.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (11.51GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\BlueBox\fitIDEA\samples\src\V850FxX\RH850_F1H_GHS_AOMTest_masterSend\master_test.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.4.0
cpptools|ms-|0.17.3

</details>

**Comment by bobbrow** [comment] 2018-05-29 21:52
When you say it's not working, do you mean that goto/peek definition takes you to the wrong locations or that the extension has actually crashed (i.e. auto-complete and other functions stop working too)?

If you are editing files outside of of VS Code, when you save them in the other editor, VS Code will send our extension an update notification when the file changes on disk, but we won't get a save notification.  The save notification is what tells us to reparse the file for code navigation, so if code navigation seems to be taking you to stale locations, that would explain it.  You can fix it by editing and saving the file in the VS Code editor or closing and reopening it.

I have an idea for a change that might allow us to do the update in this case without a save notification, but I'd like to hear confirmation from you that this is indeed what you are experiencing.

**Comment by schperplata** [comment] 2018-05-30 05:38
"crashing" in my case means, that nothing happens except blue line is keep spinning on top of the file tabs. Go to/peak definition does nothing (doesn't show anything, it also doesn't move the cursor to any other location).  
I can edit file and save it, but I can't use those features until VS Code restart. I am experiencing this even when I just compile file with some compiler - don't really need to edit/save file. Unfortunatelly, it does not happen always. Sometimes it just works, sometimes every action triggers this behaviour.

It does not happen with Notepad++.

**Comment by sean-mcmanus** [comment] 2018-05-30 18:56
@bobbrow It sounds like a deadlock. It could be the same "livelock" bug with recursive includes too: https://github.com/Microsoft/vscode-cpptools/issues/2043 .

**Comment by bobbrow** [comment] 2018-05-30 20:30
@schperplata, is there excessive CPU usage in the Microsoft.VSCode.CPP.Extension.exe process, or does it appear to be idle?  And do any of the Microsoft.VSCode.CPP.IntelliSense.Msvc.exe processes appear to be doing any work?  This could be a duplicate of either of the issues @sean-mcmanus mentioned.

**Comment by schperplata** [comment] 2018-05-31 05:57
Yes, there are two instances of Microsoft.VSCode.CPP.Extension.exe, each has 25% of CPU usage, while only few MB of RAM (one 9MB, other 35MB).  There are always two instances, even if everything works fine.  Another strange thing, my VS Code is 64x, while extension is 32x (this is shown in windows task manager).

However, I can't find Microsoft.VSCode.CPP.IntelliSense.Msvc.exe anywhere. Maybe I'm looking in the wrong place?
![overload](https://user-images.githubusercontent.com/8736111/40764155-2fa46e3a-64a8-11e8-8e90-6f4b490d44cf.PNG)

**Comment by bobbrow** [comment] 2018-05-31 15:38
Having two Extension processes means that you opened two folders in VS Code at some point (or perhaps you are using multi-root support with two folders).  The IntelliSense processes are probably not being launched because of the "livelocked" Extension processes which can't make forward progress.  Disabling recursive includes will solve this problem.  Take a look at #2043 for a workaround.

**Comment by bobbrow** [comment] 2018-06-01 03:14
We released 0.17.4 with a fix for the livelock, so this issue should be resolved now. There are still some performance issues with recursive includes that we are working on, so you might still see some high CPU usage when opening files, but it should eventually catch up. We are going to track performance problems with recursive includes using issue #2068.

**Closed as completed by bobbrow** 2018-06-01 03:14 UTC
Labels: bug, Language Service
