### ISSUE TITLE
Quick info shows on hover over comments

### ISSUE THREAD

**Issue by chaoer** [microsoft/vscode-cpptools#839] opened 2017-06-22 02:56 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|beautify|HookyQR|1.1.1|
|cpptools|ms-vscode|0.11.4|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.7|;

---

Problems:
_I have already post this to Microsoft/vscode (#28575), but they said that I should file this issue here._

When I put the cursor on a comment word (if it is just the same with the name of one function), the IDE also gives me a prompt, which I think may be not necessary.

Steps to Reproduce:

1. Put cursor on a comment word (the same with the name of one function)
2. The prompt will occur.

![20170613101407](https://user-images.githubusercontent.com/10883500/27063085-18d0fdf4-5022-11e7-908f-189e880fd3d2.jpg)

**Comment by sean-mcmanus** [comment] 2017-06-22 04:32
This is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/559 . Changing the intelliSenseEngine to Default will fix the issue, but you'll probably have to setup the includePath and defines correctly (our next update will make this easier to setup).

**Closed as completed by sean-mcmanus** 2017-06-22 04:32 UTC
Labels: bug, duplicate, Language Service, fixed

**Comment by chaoer** [comment] 2017-06-22 07:14
@sean-mcmanus  I got it. Thanks.

**Comment by sean-mcmanus** [comment] 2018-09-28 01:03
Hover should not longer return results in comments with 0.19.0.
