### ISSUE TITLE
Folders created through WSL do not work with intellisense

### ISSUE THREAD

**Issue by ptrsr** [microsoft/vscode-cpptools#2466] opened 2018-08-30 08:48 UTC
**Type: LanguageService**

Originally I was working on a c++ project through WSL. I cloned the repo with git through WSL. When opening the project and enabling the extension, nothing happens: it's like the extension isn't enabled at all. I created a new folder on my desktop with a simple main.cpp in which it did work.

With some experimenting I found out that all folders that are created with the ``mkdir`` command through WSL that contain c++ code do not work. I have a feeling that it might have to do with folder ownership or the way paths are stored between Windows and WSL.  

**Describe the bug**
- OS and Version: Windows 10 Pro : Version 1803
- WSL: Ubuntu : Version 18.04 LTS
- VS Code Version: 1.25.1
- C/C++ Extension Version: Version 0.18.1: August 17, 2018
- Other extensions you installed (and if the issue persists after disabling them): None
- Folders created through WSL do not work with intellisense

**To Reproduce**
Create any folder on ``/mnt/c/`` with ``mkdir``, create a cpp file through Windows and check if intellisense works.

**Comment by J-Vernay** [comment] 2018-08-30 08:58
I confirm the bug exists. I noticed the bug is present when the .cpp file is created either  through Windows (using Notepad++) and WSL (using nano).

I am using Windows 10 Edu 10.0.17134, with WSL Ubuntu 18.04 LTS (installed from Microsoft Store), using VS Code 1.26.1 and the version 0.18.1 of C/C++ Extension.

**Comment by bobbrow** [comment] 2018-08-30 15:40
What is the value of `compilerPath` in `c_cpp_properties.json`?

My guess would be that WSL creates the folder with the case-sensitive flags on.  The C/C++ extension doesn't support that right now unless you are also using the compiler from WSL (e.g. `"compilerPath": "/usr/bin/gcc"`)

**Comment by bobbrow** [comment] 2018-08-30 15:42
possibly duplicate of #1994

**Comment by bobbrow** [comment] 2018-10-03 16:18
Please go upvote #1994 so we can track the number of users who need case-sensitive folder support.  I'll close this as a duplicate.

**Closed as completed by bobbrow** 2018-10-03 16:18 UTC
Labels: duplicate, Language Service, Feature Request
