### ISSUE TITLE
Why is debugger loaded if I choose to run without debugging?

### ISSUE THREAD

**Issue by homandiy** [microsoft/vscode-cpptools#7130] opened 2021-03-08 18:23 UTC
I use batch file in the task.json to load the Msys64 bash to run the bash script. The file did built but the debugger is running forever. I didn't choose to run it with "Run Without Debugging". The debugger is annoying.

The Debug-Console:
=thread-group-added,id="i1"
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
[New Thread 283180.0x10190]
[New Thread 283180.0x4e08]
[New Thread 283180.0x478fc]
[Thread 283180.0x478f0 exited with code 3221225785]
[Thread 283180.0x10190 exited with code 3221225785]
[Thread 283180.0x478fc exited with code 3221225785]
ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". During startup program exited with code 0xc0000139.
The program 'd:\VC\projects\gtk_test\gst-test.exe' has exited with code 0 (0x00000000).

**Describe the bug**
Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

- C/C++ Extension Version:  v1.0.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment] 2021-03-08 18:27
Duplicate of: https://github.com/microsoft/vscode-cpptools/issues/5680

**Closed as completed by WardenGnaw** 2021-03-08 18:27 UTC
Labels: duplicate, debugger
