### ISSUE TITLE
A user defined left margin while debugging and stepping through deeply nested code

### ISSUE THREAD

**Issue by TryerGit** [microsoft/vscode-cpptools#8104] opened 2021-09-06 05:00 UTC
Type: Feature Request

At present, stepping through code while debugging (Step Into F11, Step Over F10, Continue F5) force focusses the cursor in column 1 (leftmost column of the file/display). This makes it difficult to focus on the actual line of code that has been stepped over especially with indentation and no linewrap setting when dealing with functions that are deeply nested or within multiple if conditions, amongst others. 

To illustrate graphically. The debugging sessions could begin with the screen looking so:

```
    ________________________________
    a  |  d               |e        |
    ___|                  |         |
    b  |                  |         |
    ___|x                 |         |  
    c  |__________________|_________|
    ___|____________f_______________|
```

`d` is the actual code window whose code I am stepping through. `e` is another file open in a vertical split, and `f` is the integrated terminal output. On the left are the variables, watches and call stack. `x` denotes the current breakpoint that has been hit.

Sometimes, some of the code in `d` is quite long since it could be within a deep for loop or else under multiple if conditions with indentation. I don't have word wrap on. As a result, some of the code gets cropped off like so:

     ___________________________________
     d                                  |
        {                               |
               {                        |
                    //Really Long line  |                                
                         //Another Long.|
    x                              //Lo.|  
                                        |
    ____________________________________|

I have to horizontally scroll over to the right in `d` to see what precisely is happening in the line. When then stepping over (F10), regardless of the horizontal scroll just made, the focus shifts to the very first column 1.

Is it at all possible to somehow maintain the horizontal scroll like so (i.e., maintain the left margin around, say, column # 10):

     ___________________________________
     d                                  |
                                        |
     {                                  |
        //Really Long line              |                                
             //Another Long line        |
                       //Long line      |  
     x                                  |
    ____________________________________|

even when stepping through the code? The white space to the left is  useless information in this context, but it repeatedly gets focus since stepping over forces focus at the left-most column 1.

PS: I raise this issue here and not in https://github.com/microsoft/vscode since I feel this problem is likely to be specialized for folks that use VSCode for C/C++ development as compared to those that use VSCode for other languages.

**Comment by WardenGnaw** [comment] 2021-09-07 18:06
You will want to start with https://github.com/microsoft/vscode since they will be the ones they need to scroll the horizontal bar to the given column in a stopped event source. 

The other limitation is that GDB itself only gives the breakpoint via line and we do not parse source files for debugging, but rather work with symbols.

**Comment by TryerGit** [comment] 2021-09-08 02:29
@WardenGnaw Fair enough. Time permitting, I will try to take this up with the vscode folks. Just so I understand your 2nd point: are you saying that even if a fixed horizontal scroll was implemented by vscode folks, from the point of view of gdb in c++, the focus will shift to some symbol on a line independent of the horizontal scroll?

**Comment by WardenGnaw** [comment] 2021-09-08 18:29
>  Just so I understand your 2nd point: are you saying that even if a fixed horizontal scroll was implemented by vscode folks, from the point of view of gdb in c++, the focus can at best shift to some symbol on a line independent of the horizontal scroll and the focus cannot be made to shift to a specific column?

The issue is that when we create a breakpoint, we assign it to a line. When the program is compiled, most source information is removed and its hard for the debugger to know when a source `line` begins. 
E.g.
```c++
auto text = 
    "multi \ 
line \ 
string"; 
```
If a user puts a breakpoint on the line `"multi \` the breakpoint will rebind to the line starting at `auto`.

**Closed as completed** 2021-09-09 03:01 UTC
Labels: debugger, Feature Request
