### ISSUE TITLE
refactor "Run > Add Configuration" to generate launch.json file

### ISSUE THREAD

**Issue by samival** [microsoft/vscode-cpptools#9100] opened 2022-03-28 04:33 UTC
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 10 / Linux Mint 19 / Ubuntu 20
- VS Code Version: 1.65.2
- C/C++ Extension Version: probably all version between 1.9.2 to 1.9.6 if not earlier
- Other extensions you installed (and if the issue persists after disabling them): No other extension installed.
- Compiler/Debugger: On windows: gcc and gdb using Mingw / On Linux: gcc and gdb.

- A clear and concise description of what the bug is:
Usually when you press F5 you get prompted with options for generating default tasks.json and launch.json
but with the recent updates, you no longer get launch.json file generated.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. create an empty folder
2. open folder with VSCode.
3. create a simple .c file such as:
`int main(void) { return 0; }`
(or any valid C code of your choice)
4. press F5
5. choose "C++ GDB/LLDB"  when prompted
6. choose "C/C++ gcc ..." or "C/C++ gcc.exe ..." when prompted
7. result: tasks.json is generated but launch.json is not. (sometimes you get an error and sometimes it just runs/debugs somehow without a launch.json file)

Additionally it appears generating tasks.json using ctrl+alt+b combination is also broken:
1. follow steps 1-3 above
2. press Ctrl+Alt+B
3. choose "C/C++ gcc ..." or "C/C++ gcc.exe ..." when prompted
4. no tasks.json is generated no executable file is created. terminal output is something like:
```
> Executing task: C/C++: g++ build active file <

Starting build...
C:\usr\bin\g++ -fdiagnostics-color=always -g ...\hello.c -o ...\hello.exe
spawn C:\WINDOWS\system32\cmd.exe ENOENTBuild finished with error(s).
The terminal process failed to launch (exit code: -1).

Terminal will be reused by tasks, press any key to close it.
```

I've yet to find an old version of the C/C++ extension that works. I've tested on Two different computers and two virtual machines. On my Windows machine it worked for a while so I thought it was a problem specifically with Linux but than the extension on Windows got updated and I started getting the same behavior. To make sure it wasn't a problem with cache/config/temp files I've deleted them and even tested on a  zipped version with a portable setup  (with "./data/tmp" structure inside VSCode's folder). 

** possible workarounds **
using an existing .vscode folder with existing tasks.json and launch.json seem to work correctly. it's only when you try to generate the files "from scratch" that problems start occuring.

**Comment by samival** [comment] 2022-03-28 04:42
Update: version 1.8.1 (insiders 4) from github seems to be working correctly.
https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.1

**Comment by Cube707** [comment] 2022-03-28 09:41
same Problem.
Worked fine on 1.7.1 but now borken on 1.9.7

**Comment by sean-mcmanus** [comment] 2022-03-28 18:46
@samival I would guess 1.8.4 would work too?

@elahehrashedi Is this a "by design" change?

**Comment by samival** [comment] 2022-03-28 20:09
> @samival I would guess 1.8.4 would work too?
Just checked. Yes, it seems to works fine as well.

To be frank, most versions are not available as .vsix and I hadn't bothered installing the tools necessary and trying to build from source,  but I kept backups of the extensions folder.

so it's possible to copy the  1.8.4 folder and/or deleting the folders of newer versions (probably have to delete or modify the ".obselete" file as well) this can serve as an additional temporary workaround. (don't forget to disable extension auto updates)

**Comment by jureid** [comment] 2022-03-28 20:11
Hey @samival - I'm curious, do you need to customize launch.json in order to debug successfully in VS Code? 

We changed the behavior of F5 so that it uses dynamic debug configurations on the fly, rather than creating and saving a launch.json file. This only happens if launch.json doesn't already exist. If it does exist, F5 will read from it.

The purpose of this change is to simplify the first-time run/debug experience for C++ in VS Code, as customers typically don't need to customize launch.json for the primary use case of running/debugging a single C++ file. Enabling dynamic debug configurations (and therefore removing the need for launch.json) also means that you can debug a file without opening it inside of a folder.

**Comment by samival** [comment] 2022-03-28 20:58
@jureid - I use  VS Code mainly for teaching C and C++ . Most code examples I use are indeed self contained single files, so it would be beneficial if there are less configuration my students and I have to worry about and if files could be handled by themselves without opening the folder.

But there are a good reasons for modifying it, at least as it stands for now:

1) setting program arguments with "args"

2) On Windows the "cwd" option is oftentimes set to the compiler path by default (instead of the working directory or the file directory) which can problematic (or alternatively make taksks use a makefile and make launch call the exectuable). 

3) sometimes I do work with multiple files and need the extra flexibility to modify tasks and launch to compile all the source file and run a program whose name is constant and not tied to the active file.

(I also use existing .vscode folders instead of generating them each time, but sometimes it's useful to have the students familiarize themselves with the json files so they'll know how to modify them to suit their needs)

Also I've now tested version 1.9.7 and getting a similar experience as 1.9.6 :

**Opening a single c/cpp source file (not folder):** currently doesn't seem to work correctly and trying to use Ctrl+Shift+B gives "no build task to run found", and trying to use F5  gives a "launch: program '... .exe' doesn't exist" message. 

**Opening a folder with a single source file:** Ctrl+Shift+B prompts for the compiler choice to create tasks.json but doesn't create it. Trying to use F5 prompts for compiler and debugger choice,  creates a tasks.json file but no launch.json.

I do recall getting debugging to work in some of my testings1.9.6 but I'm not sure how to reproduce this successful result. Prehaps I'm not using the the extension or VS Code correctly?

**Comment by jureid** [comment] 2022-03-29 17:03
@samival - thanks for the info! I wonder if we can come up with a more user-friendly way to pass args to the program at runtime so that students don't have to worry about JSON configuration files. Regardless, it seems like there are valid use cases where you'd want to create and customize launch.json. With this new F5 behavior, you can still create launch.json with a starter C++ configuration by following these steps:
1. Select **Run > Add configuration** (which will create an empty launch.json)
![image](https://user-images.githubusercontent.com/44306969/160665135-7cfed08c-366b-42e3-bc12-27fe2a691904.png)
2. In launch.json, select the blue **Add configuration** button on the bottom right
![image](https://user-images.githubusercontent.com/44306969/160665262-b404ea82-2637-472b-8a09-cf68661bff95.png)
3. Choose the desired C++ configuration snippet, such as **C/C++: (gdb) Launch**
![image](https://user-images.githubusercontent.com/44306969/160665349-275a8df3-175f-4613-a23f-3b3e4b640fd2.png)
4. The (gdb) Launch configuration is created, where you can update the program name and path to gdb:
![image](https://user-images.githubusercontent.com/44306969/160665455-cf931369-1547-4bc3-b644-daecfd4068ef.png)

Does that flow work for you?

Also, which compiler/debugger are you using? I want to investigate why those two scenarios you mentioned (Opening a single c/cpp source file (not folder) and Opening a folder with a single source file) aren't working properly.

**Comment by elahehrashedi** [comment] 2022-03-29 17:03
@samival 
Thanks for bringing up this discussion, the `run and debug` button and `F5` have had some design updates.

Currently, the debug button creates a tasks.json file, but not a launch.json file, and the debug configurations will be created on the fly. This design is more simple for users who don't want to customize their debug configurations.

In case the user wants to customize their debug configuration in launch.json, then the modified configs will be picked up from launch.json when debugging. There are some updates related to launch.json configs that are in progress right now #9110 .

Let me provide some clarifications regarding the scenarios you mentioned : 
1. The command `Tasks: Run Build Task` or  `Ctrl+shift+B` is not supposed to create a `tasks.json`. It asks the user about their preferred build configs, including compiler, and runs a build command on the go. If you are encountering an error when using this dynamic run build, a better option is to run `Tasks: Configure Task`, where the `tasks.json` will be created and you can customize the build configs. 

2. In the case where the user is opening a single file without a folder, no `tasks.json` or `launch.json` will be created when pressing either `F5` or `run and debug` button, so the build and the debug configs will be created on the go and not customizable. If the user wants the full experience, we recommend opening a folder, not a single mode file.

3. In the case where the user is opening a file inside the folder, as it's mentioned the command "Tasks: Run Build Task" or  "Ctrl+shift+B" is not supposed to create a tasks.json. While the "F5" or "run and debug" button will create a "tasks.json" but not a "launch.json". 


Let's investigate these two scanrios that seems you encountered an error:
1.  Run "Tasks: Configure Task", define a task, and then run "Tasks: Run Build Task". If you are still having an error when running the build, we can open a separate issue for that bug to investigate.

**Comment by samival** [comment] 2022-03-30 00:28
Okay, I think I found out why `Start Debugging` / F5 is giving me problems with a single-file mode. It's because I also have WSL installed and in some of my test I accidently selected WSL compilers while not working in WSL mode. Sorry for the confusion I've caused. further explanation below:

My setup currently includes among other things MinGW GCC  and gcc on WSL. When I get to the prompt for choosing a compiler I get offered both the MinGW compilers (gcc.exe/g++.exe) as well as the WSL compilers (/usr/bin/gcc / user/bin/g++). It appears I've been accidentally choosing the WSL version while not working in WSL mode which causes the error. (though I have to wonder why the WSL version is offered when not in WSL mode) If I pick g++.exe seems to work as you intended (no config files to compile & debug a file and when opening a folder it generates a default tasks.json and it's able to compile & debug)


@jureid:

> @samival - I wonder if we can come up with a more user-friendly way to pass args to the program at runtime so that students don't have to worry about JSON configuration files.

It would also be nice to have args list per file instead of it affecting all the files (whichever is being the active file). perhaps:
1) extend launch.json's args sturcture so it  would be possible to also specify arguments per file:
        `
        "perFileArgs" : {
             { "filename": ..., "args": [... ]},
             ...
        },
      `
2) some other json file (args.json?) that specifies arguments per file that will be used in cases where launch.json doesn't exist.
3) detect some file format such as ${fileBasenameNoExtension}.args as a text file with arguments when debugging ${filename}

> Regardless, it seems like there are valid use cases where you'd want to create and customize launch.json. With this new F5 behavior, you can still create launch.json with a starter C++ configuration by following these steps:
> 
> ...
> 
> Does that flow work for you?

Yes, this works, thanks for the explanation. However, this makes it less streamlined than how it used to work. setting up a new directory as a project used to be:
`F5->select debugger (enter) -> select compiler (enter)`
and you're mostly done since many of the fields get filled correctly.
Now it's:
`The steps you mentioned to create and populate launch.json + setting launch.json fields then setting up a tasks.json (and setting launch.json's prelaunch task to that task)`
So in situations where a launch.json is desired (setting arguments/when the filename to debug is different from the active file), it feels like it requires the user to meddle with more settings compared to how it used to work where it would mostly fill out the correct parts for you.
 

Also in step 1 ...
> 1. Select **Run > Add configuration** (which will create an empty launch.json)
... it still prompts the user for which debugger to use even though it doesn't matter since it generates an "empty" launch.json. Perhaps a leftover from how it used to work in previous versions of the extension.

> Also, which compiler/debugger are you using? I want to investigate why those two scenarios you mentioned (Opening a single c/cpp source file (not folder) and Opening a folder with a single source file) aren't working properly.

On Linux I use the default gcc version that's comes with "build-essential". On Windows I use some form of MinGW prebuilt binaries and setting PATH to MinGW's bin folder. I work with students that use either Linux or Windows (and in some cases Mac-OS), so this kind of setup allows me to make json files that are mostly portable (by changing command to just "gcc"/"g++" VS Code is able to detect it PATH which is great. and similarly I set "gdb" for "miDebuggerPath").

@elahehrashedi:

Thank you for the explanation, it helped me figure out the problem I mentioned at the top of this comment, and better understand the intended workflow with the current versions of the extension.

However:

1) As mentioned in my answer to @jureid, if the user does need a launch.json it becomes a less streamlined and requires the user to input things such as the compiler path where before it used to be filled automatically based on the user's settings/prompts and auto detection. I find it usually necessary to have a custom launch.json if I need custom arguments or if I want to compile several files into a single executable (or other similar setups where I don't want  the active file's name to dictate what file to run and  debug).

2) At least for my GCC setup on windows the "implicit" launch configuration has the same "cwd" issue as the previously generated launch.json. "cwd" is set to the compiler path which can be problematic if the program creates files since it could accidentally modify existing files relative to the compiler path. I'm not sure if it's a problem that happens just for my setup or if it happens to other users, perhaps it would be better to open a separate issue for this.

3) in some cases it would be beneficial to control the program arguments or environment variables during launch

4) Additionally for single file mode, it would be great if the flags of the implicit build task process could be configured. Perhaps they can be & I just haven't figured out how.

    a. For example it would be great to be able to set default flags such as `-W...`, `-std=...`, `-l...`, `-D...` but I've tried setting 
        either `C_Cpp.default.compilerArgs` or `C_Cpp.default.compileCommands` and they either don't seem to do anything or 
        cause errors.

    b. likewise setting `C_Cpp.default.cppStandard` and `C_Cpp.default.cStandard` don't affect the compilation by adding 
        something like `std=c++17` etc. Perhaps these options are meant for the language server and aren't supposed
        to affect the compilation process?

**Comment by samival** [comment] 2022-03-30 01:39
See attached file for an example of what json configurations I use sometimes:
[vscode.zip](https://github.com/microsoft/vscode-cpptools/files/8376100/vscode.zip)

**Comment by Cube707** [comment] 2022-04-01 11:40
Hello everybody, 
first of all, thanks for activly working on this and trying to make it easyer for beginners to get into C/C++.

I have tested the new system to adjust my workflow and would like to give some thoughts.

- Using `F5` to launch a .c file works absouloutly fine without an explicit `launch.json`. However I find it sligtly anoying to be asked for the launch enviroment and the task to run every time. (especially because there is only one option that is marked as default). However I understand that this information comes from the `launch.json` which is missing.
- No I want to generate a `launch.json`. [The way described above works absoloutly fine](https://github.com/microsoft/vscode-cpptools/issues/9100#issuecomment-1082138357), but for me the more obvious way is to go to the `Run and Debug (Ctrl+Shift+D)` sidebar from the activity bar. From here both the `create a launch.json` and the `show all automatic debug configurations` options result in an empty `launch.json` where I than have to click `Add configuration` and manually input the programm and debugger path. 

Compared to the old "press F5 than enter twice, and than F5 just magicly works" this feels much more complex and elongated.

**Comment by huiyeruzhou** [comment] 2022-04-01 14:06
I'm agree with @Cube707 , the old pattern is clearer and simpler, now I have to configure `launch.json` manually, and print the `path/to/gdb` and `the name of target file` every time when I create a new project. It is very frustrating to find the extension generate `launch.json` no more.

**Comment by rj-rl** [comment] 2022-04-04 17:47
I'd considered the new behavior a bug, until I found this page. What's really misleading is that the official guides such as [this](https://code.visualstudio.com/docs/cpp/config-linux) still describe the old behavior where `launch.json` was generated ready to use.

Another source of confusion was that:
* `Terminal > Configure tasks...` (while in empty folder containing a basic source file) lets you select from a drop-down list (such as `g++ build active file`)
* `Run > Start Debugging` or `Run > Run Without Debugging` lets you select the environment first (two options there: `C++(GDB/LLDB)` and `C++ (Windows)`) and then select the configuration, again, from a drop-down list.
* `Run > Add Configuration` or `create a launch.json file` from `Run and Debug` sidebar let you select the environment, but not the configuration. Instead, the `launch.json` file is generated immediately and it contains an empty list of configurations.

Ideally, both `Run > Add Configuration` and `create a launch.json file` would just let you select the environment and get on with it, or contain a separate option to create an empty `launch.json`, but not default to the latter.

**Comment by jureid** [comment] 2022-04-05 12:29
> Ideally, both `Run > Add Configuration` and `create a launch.json file` would just let you select the configuration and get on with it, or contain a separate option to create an empty `launch.json`, but not default to the latter.

Totally agree that this is the ideal behavior. It appears we have two regressions to investigate:
1.  `Run > Add Configuration` no longer uses the cpptools task provider ("build and debug active file") to create a sample launch configuration, and instead creates an empty launch.json
2. When the user presses F5, we're asking for the environment and build task every time, even if tasks.json exists.

Thanks everyone for your feedback and for making us aware of the regressions. We'll post updates to this thread as we improve the experience.

**Comment by kyuhyong** [comment] 2022-04-20 16:17
> @samival - thanks for the info! I wonder if we can come up with a more user-friendly way to pass args to the program at runtime so that students don't have to worry about JSON configuration files. Regardless, it seems like there are valid use cases where you'd want to create and customize launch.json. With this new F5 behavior, you can still create launch.json with a starter C++ configuration by following these steps:
> 
> 1. Select **Run > Add configuration** (which will create an empty launch.json)
>    ![image](https://user-images.githubusercontent.com/44306969/160665135-7cfed08c-366b-42e3-bc12-27fe2a691904.png)
> 2. In launch.json, select the blue **Add configuration** button on the bottom right
>    ![image](https://user-images.githubusercontent.com/44306969/160665262-b404ea82-2637-472b-8a09-cf68661bff95.png)
> 3. Choose the desired C++ configuration snippet, such as **C/C++: (gdb) Launch**
>    ![image](https://user-images.githubusercontent.com/44306969/160665349-275a8df3-175f-4613-a23f-3b3e4b640fd2.png)
> 4. The (gdb) Launch configuration is created, where you can update the program name and path to gdb:
>    ![image](https://user-images.githubusercontent.com/44306969/160665455-cf931369-1547-4bc3-b644-daecfd4068ef.png)
> 
> Does that flow work for you?
> 
> Also, which compiler/debugger are you using? I want to investigate why those two scenarios you mentioned (Opening a single c/cpp source file (not folder) and Opening a folder with a single source file) aren't working properly.

It doesn't seem to match what described in the tutorial https://code.visualstudio.com/docs/cpp/config-linux
I am running vscode on ubuntu 20.04 and installed C/C++ Extension 1.9.7 and had exact same problem.
There is no "g++ build and debug active file" when selected **Run > Add Configuration...**
![Screenshot from 2022-04-21 00-42-16](https://user-images.githubusercontent.com/22294429/164275943-70e07fb2-4c58-4dac-a156-331060288f44.png)


When I got back to 1.8.4, it works just fine.
![Screenshot from 2022-04-21 01-00-38](https://user-images.githubusercontent.com/22294429/164275904-7ef0ce8b-470a-4a31-9766-cf84560b08d7.png)

Are you changing the work flow intentionally? To me manually modifying the launch.json is somewhat counter intuitive.

**Comment by jureid** [comment] 2022-04-20 19:03
@kyuhyong - No, it's a regression and we're working on a fix! I'm sorry you ran into this issue. I'll open a PR to update our docs with a workaround.

**Comment by jureid** [comment] 2022-04-20 19:19
Updating docs to show the workaround while we work on the fix:
https://github.com/microsoft/vscode-docs/pull/5290

**Comment by DanielNikoofar** [comment] 2022-05-06 01:45
Isn't it better to publish a new update to fix it soon? It's late.

**Closed as completed** 2022-05-11 20:34 UTC
Labels: bug, Language Service, fixed, tasks/build/debug

**Comment by samival** [comment] 2022-05-12 22:59
I've been trying out version 1.10.1 but it seems to behave nearly the same as previous versions regarding this issue. I also tried to go over the C/C++ extension's settings to see if there's an option to how luanch.json is generated but couldn't find such an option. Perhaps I'm missing some configuration or perhaps I misunderstood what was considered the bug here and what got fixed as a result.

Additionally, a few relevant issues are also still present:

1) When manually generating a launch.json file, the user get asked for a debugger, but the file generated is still nearly empty regardless of choice. I think i t should either fill launch.json with relevant information for that debugger choice or not ask the user ( and they will use "add configuration" button to fill it later).

2) At least for my usual setup (MinGW on Windows), The working directory is still set for the compiler path for the implicit launch configuration (when there is no launch.json file in the project) . This means that any file my program creates is created inside my compiler's bin folder. Try to create a file in your program, i.e `std::ofstream{"oops.txt"};` and tell me where `oops.txt` gets created for you.

---

If I may reiterate, under version 1.10.1, when a custom launch.json is desired, here are the steps one would usually need to go through when creating such projects from scratch :

1) go to "run & Debug" -> "create a launch.json" -> select debugger (GDB) -> get a nearly empty json regardless of choice
2) click "add configuration"
3) choose "(gdb) launch"
4) change "program" (usually `"${fileDirname}/${fileBasenameNoExtension}"`)
5) change miDebuggerPath 
6) manually add "PrelaunchTask" and copy the label value from tasks.json.

Perhaps steps 1-3 are not too bad, but I would've expected steps 4-6 to be generated automatically from the choices made (in either step 1 or 3). Not to mention all of this used to be generated in the old behavior with just a few presses (often only pressing F5->Enter->Enter).

Although, to be fair, after creating launch.json & tasks.json for the first time, they can be easily copied for new projects.

**Comment by sean-mcmanus** [comment] 2022-05-12 23:06
You need to use the gear icon in the top right of the document near the debug button to generate the launch.json file.

**Comment by samival** [comment] 2022-05-13 00:32
Oh, neat. Thanks.

It might be worth noting that this button won't appear unless the debug shortcut button is also enabled (Setting ID: C_Cpp.debugShortcut)

![‏debug_shortcut](https://user-images.githubusercontent.com/13943961/168188140-1913c290-f064-4930-a1a5-b434c1bac9be.PNG)

**Comment by seaofbits** [comment] 2022-05-22 18:58
I agree with @samival, I don't think "adding an add-configuration gear button" really solves this problem. There is still **NO** `launch.json` auto generated after pressing F5, instead you need to generated it manually. I think there are two strange points about this solution:

1. It‘s quiet strange that the extension only creates `tasks.json` but no `launch.json` in a new folder. Why don't create them both at the same time?
2. You will get empty `launch.json` when generating it in "run and debug activity bar", which is against with common behaviour.
I created an sample project to explain:
![image](https://user-images.githubusercontent.com/38586229/169710353-ceebcce6-fd9f-4ce7-8ed2-8f642da9b526.png)
So when you hit "create launch json" and select, you got an empty launch.json.
![image](https://user-images.githubusercontent.com/38586229/169710530-d43f9685-3c6b-48f2-b111-36a98bcb45e0.png)
![image](https://user-images.githubusercontent.com/38586229/169710618-9ba49f69-73d5-4aa3-8280-6058d4dd251a.png)
Delete it, and try again on any `.ts` file or `.py` file (extention installed), you will get auto-generated `launch.json`:
![image](https://user-images.githubusercontent.com/38586229/169710769-4c86d5b7-a095-451a-93b3-c78d29a860ea.png)
So, this behaviour is against intuition.
P.S. I'm using the v1.10.2 pre-release version of C/C++ extention, on vscode v1.67.2 on windows 10.

So I really hope that the `launch.json` will be generated **automatically**, after pressing F5 in a new folder contains cpp file.

**Comment by sean-mcmanus** [comment] 2022-05-23 20:14
I was told we wanted to avoid creating launch.json because new users were confused by it and the properties in it were harder to understand than the tasks.json. @elahehrashedi Should we at least provide a setting to get the previous behavior?

I also initially hit the blank launch.json and was confused by it -- I believe the plan is to rely on the updated documentation to explain that the gear icon needs to be used: https://code.visualstudio.com/docs/cpp/config-linux#_customize-debugging-with-launchjson .

**Comment by Cube707** [comment] 2022-05-28 14:11
@sean-mcmanus this "gear" icon behauvior is higly unusuall and completely different from any other extention out there that uses `launch.json` files. 

I get that it may be confusing for beginners to have a launch-file generated when they don't need it, but I would still expect the button clearly stating "_To cutomise Run and Debug create a launch.json_" to do exacly that. This is the case for any other extention I use.

The python extention has also moved away from launch.json files a while ago, but still keeps it avalable for users that need it through that exact means. Creating a completle new button one has to scoure throug the documentation to find out about doesn't add to the userfrendlieness in my opinion.

**Comment by elahehrashedi** [comment] 2022-06-01 16:07
@Cube707 we are currently following the issue related to `Add Configuration` behavior from here: https://github.com/microsoft/vscode-cpptools/issues/9382. I recommend you to add your suggestions there, as this issue is closed. Thank you.
