### ISSUE TITLE
Alright, I think VSCode forgot how C++ works

### ISSUE THREAD

**Issue by bonkmaykr** [microsoft/vscode-cpptools#2398] opened 2018-08-14 01:35 UTC
Type: LanguageService
**----- Input information below -----**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Windows 10 (not sure which build but that wont matter)
- VS Code Version: 1.25.1
- C/C++ Extension Version: Latest (0.17.7)
- Other extensions you installed (and if the issue persists after disabling them): I have a few other Intellisense C++ extensions from third-parties that are supposed to improve upon the one built into Microsoft's own extension. This happens regardless of what extensions are enabled/disabled
- A clear and concise description of what the bug is.

**To Reproduce**

1. Not sure exactly what started this but apparently Intellisense forgot how to properly parse scripting languages like this because it wants me to place a semicolon *after* an opening bracket.

**Expected behavior**
Well, it gave me errors before telling me I forgot to put one at the end of my *closing* brackets (which I sometimes do since I'm more used to just leaving the end blank like in C# and JS). After I fixed that everything was SUPPOSED to be clean but then it tells me I need a new one before my *opening* ones too. To me it's like VSCode just smoked crack or something

**Screenshots**
![image](https://user-images.githubusercontent.com/42302831/44066807-fd5d2ba4-9f37-11e8-9e08-e0f38f140238.png)

Did I actually do something wrong or is this really happening? I went to use an online cpplint tool just incase, and found a ton of meaningless, nit-picky warnings... but no compiler errors related to those brackets. Only VSCode seems to misread this.

Explanation? Or no?

**EDIT: Nevermind, I tried a different compiler and it told me that I should move my function definition. Conclusion: The devs need a clearer error message that makes sense**

**Comment by bobbrow** [comment] 2018-08-14 04:09
If you can share the full source file, we can take a look and see why IntelliSense is confused.  I am unable to reproduce your problem on my PC:

![image](https://user-images.githubusercontent.com/12818240/44071280-16137cac-9f3d-11e8-9edb-7cede917371f.png)

**Comment by michelleangela** [comment] 2019-05-30 18:55
Closing this issue as the last response is more than a year old.

If you update to the latest version of the C/C++ extension and your issue persists, please re-open the issue and reply with additional information that can help us investigate your issue.

**Closed as completed by michelleangela** 2019-05-30 18:55 UTC
Labels: Language Service, more info needed
