### ISSUE TITLE
Fields named module create false IntelliSense errors when using c++20 language standard

### ISSUE THREAD

**Issue by Eric-Arz** [microsoft/vscode-cpptools#6789] opened 2021-01-15 09:31 UTC
C++ 20 has the new module keyword. Since it is a contextual keyword it is allowed as the name of a struct member field. However IntelliSense seems to always treat it as a keyword regardless of the context. Take this example from the Vulkan C API:
```
VkPipelineShaderStageCreateInfo stageInfo = {
	.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
	.stage = VK_SHADER_STAGE_VERTEX_BIT,
	.module = vertexModule,
	.pName = "main"
}; 
```
IntelliSense colors "module" as a keyword and underlines it as an error.  However the code compiles and runs fine.

**Comment by sean-mcmanus** [comment] 2021-01-15 10:06
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/6719 .

**Closed as completed by sean-mcmanus** 2021-01-15 10:06 UTC
Labels: duplicate

**Comment by sean-mcmanus** [comment] 2021-01-21 07:33
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
