### ISSUE TITLE
includePath set to ${workspaceFolder}/** not taking effect

### ISSUE THREAD

**Issue by JosephDeepIntelli** [microsoft/vscode-cpptools#5178] opened 2020-03-24 12:53 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.43.1
- C/C++ Extension Version:0.27.0-insiders4
- Other extensions you installed (and if the issue persists after disabling them): Remote - SSH
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

local c_cpp_properties.json 
`includePath: ["${workspaceFolder}/**"] `
not taking effect.  I got include errors detected. However, if it set to be
```
includePath: [
                "${workspaceFolder}/src/**",
                "${workspaceFolder}/install/**"
            ],
```
No include errors detected.

**Comment by sean-mcmanus** [comment] 2020-03-24 19:35
I'm not able to repro this. We need more info.

Does the bug repro with 0.26.3 (non-Insiders)? Does the issue repro with a single workspace folder? What is the difference in the "Includes" output when you run the "C/C++: Log Diagnostics" command with the includePath set to `${workspaceFolder}/**` versus `"${workspaceFolder}/src/**", "${workspaceFolder}/install/**"`?

If headers with the same name exist under "install" and "src", then putting `"src/**"` before may be required in order to have the correct includePath ordering; otherwise, "install/myFile.h" might get chosen as a header instead of "src/myFile.h" if just `"${workspaceFolder}/**"` is used, because recursive includes have a non-deterministic order.

**Comment by Darker7** [comment] 2020-09-09 07:39
I had a similar problem with recursive includes not working – or rather working inconsistently. Though it seems fairly exotic because I fixed it by rolling back to 0.28.3 but when I now rolled forward to 0.29.0 again to reproduce it, it was fixed but I'm starting rambling.  
More structured:

- Version: 0.29.0 (non-Insiders)
- Problem: `{workspace}/src/checksum.h` is not being detected with `{workspace}/**` for `{workspace}/test/test_checksum.c`
    - other files in `{workspace}/src/` are being detected
    - `{workspace}/src/checksum.h` is being detected for `{workspace}/src/checksum.c`
    - adding  `{workspace}/src/` to the includePath array fixes the problem
        - removing it reintroduces the problem
- Attempted solutions:
    - Reloading the window
    - changing the order with the only other entry in the includePath array
- Found solution:
    - change version to 0.28.3
    - changing back to 0.29.0 did not reproduce the problem.

This is quite bizarre. The only thing I can think of is that I created some exotic state because of some problems prior due to not installed OS C-libraries :Ü™

**Comment by sean-mcmanus** [comment] 2020-09-09 18:14
@Darker7 The checksum.h might be getting stored in the database as "non-existent". Doing a Reset IntelliSense Database would be a way to fix it if that's the case.

**Comment by michelleangela** [comment] 2020-12-09 18:45
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 18:45 UTC
Labels: Language Service, more info needed, not reproing, Feature: Configuration
