### ISSUE TITLE
Some functions fail to open for the "Go to definition" command

### ISSUE THREAD

**Issue by xueyunquan** [microsoft/vscode-cpptools#1479] opened 2018-01-22 09:12 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 4.13.0-25-generic (Ubuntu 17.10 running in a virtualbox VM)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
material-icon-theme|PKi|3.2.1
arm|dan|0.1.2
githistory|don|0.3.4
gitlens|eam|7.5.6
vscode-npm-script|eg2|0.3.3
LogFileHighlighter|emi|1.2.0
vscode-great-icons|emm|2.1.22
code-runner|for|0.8.7
CppSnippets|har|0.0.13
githd|hui|1.1.1
autoconf|mae|0.0.2
Kotlin|mat|1.4.0
**cpptools**|**ms-**|**0.14.6**
vscode-icons|rob|7.19.0
shader|sle|1.1.2
vscode-hexdump|sle|1.6.0
shader-toy|ste|0.4.0
ayu|tea|0.12.0
gitblame|wad|2.2.0

(22 theme extensions excluded)

---

Steps to Reproduce:

1. Install package ```libcunit1-dev``` with apt , if it's not already installed. This is to provide CUnit headers.
1. In VS code, disable the Intellisense fallback in the global user settings: ```"C_Cpp.intelliSenseEngineFallback": "Disabled"```
2. Clone the drm project with the following command: ```git clone https://anongit.freedesktop.org/git/mesa/drm.git``` into an empty folder.
3. Start VS code and open the drm code folder from the file menu.
4. Create & modify the ```c_cpp_properties.json``` config file to read like this:
```JSON
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/include/c++/7",
                "/usr/include/x86_64-linux-gnu/c++/7",
                "/usr/include/c++/7/backward",
                "/usr/lib/gcc/x86_64-linux-gnu/7/include",
                "/usr/local/include",
                "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include",
                "${workspaceRoot}",
                "${workspaceRoot}/include/drm",
                "${workspaceRoot}/tests/amdgpu",
                "${workspaceRoot}/amdgpu"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include/c++/7",
                    "/usr/include/x86_64-linux-gnu/c++/7",
                    "/usr/include/c++/7/backward",
                    "/usr/lib/gcc/x86_64-linux-gnu/7/include",
                    "/usr/local/include",
                    "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed",
                    "/usr/include/x86_64-linux-gnu",
                    "/usr/include",
                    "${workspaceRoot}",
                    "${workspaceRoot}/include/drm",
                    "${workspaceRoot}/tests/amdgpu",
                    "${workspaceRoot}/amdgpu"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ".vscode/database"
            }
        }
    ],
    "version": 3
}
```

5. Open the source file ```amdgpu_cs.c``` under the ```amdgpu``` subfolder, and navigate to the function ```amdgpu_cs_submit```.
6. After the whole project finishes parsing (should be very quick because it has only less than 270 files), in the function ```amdgpu_cs_submit``` click the code that calls the function ```amdgpu_cs_submit_one```. With cursor on the symbol  ```amdgpu_cs_submit_one``` press the F12 key or right-click and select "Go to definition" from the context menu.

On my machine this will bring up a popup message:
![1c](https://user-images.githubusercontent.com/4216222/35212462-318d0ad6-ff95-11e7-8503-96412d2b7660.png)

But by scrolling up you can actually see that the function ```amdgpu_cs_submit_one``` is just above ```amdgpu_cs_submit```. And it is even weird that when hovering the mouse pointer over ```amdgpu_cs_submit_one``` the function prototype can be shown:
![1a](https://user-images.githubusercontent.com/4216222/35212560-86f49ee4-ff95-11e7-9c4c-1af7f190a7c8.png)

However you just can't jump to it by pressing F12.

It is also worth noting that the function fails to appear in the function list when I click the ```C/C++ Navigation``` on the status bar:
![1b](https://user-images.githubusercontent.com/4216222/35212845-7b5db204-ff96-11e7-90e7-9c9788d31f15.png)

Please look into this issue. Thank you.

---

Reproduces without extensions: No

**Comment by sean-mcmanus** [comment] 2018-01-24 02:42
I'm able to repro the problem.

**Comment by sean-mcmanus** [comment] 2018-01-24 02:55
LIST_FOR_EACH_ENTRY is the cause. Our symbol parser doesn't handle macros and this breaks it. Adding a file named cpp.hint to your workspace with contents:
`
#define LIST_FOR_EACH_ENTRY(arg1, arg2, arg3)
#define LIST_FOR_EACH_ENTRY_SAFE(arg1, arg2, arg3, arg4)

`
should fix the issue. This is currently "by design", but we want to make the cpp.hint thing more accessible in the future. Is that workaround acceptable? This issue should stop reproing after we implement Go to Definition via the IntelliSense engine instead of the Tag Parser.

**Comment by xueyunquan** [comment] 2018-01-31 01:38
@sean-mcmanus : Thanks for your reply. Your workaround solves the  issue by now, but frankly speaking I don't think it a good  idea. 

For a temporary workaround, it seems vague to me about how to pinpoint the offending macro because in a large project like the linux kernel there could be too many macros. I mean if too many functions fail to parse it could be obsessed to find out the failing macro definitions and adding them to the hint file, no?

So I won't accept this as a permanent solution. And I might not even accept it as a temporary one, depending on my experience of working with it on large projects in the next few weeks.

I think a more natural way would be implementing proper macro parsing and save the users the trouble to write the workaround file.  Likewise I think the including paths in the c_cpp_properties.json for intellisense should be recursive.

Thanks.

**Comment by bobbrow** [comment] 2018-01-31 18:43
Include paths will support recursion in the future.  Visual Studio is testing out this feature now and we will port it over to our extension soon.

**Comment by xueyunquan** [comment] 2018-02-01 02:27
@bobbrow : Nice to hear about that.

**Comment by sean-mcmanus** [comment] 2018-02-01 21:13
The Tag Parser (navigation list and go to symbol features) may never support macro expansion (VS 2017 does not), but Go to Definition should be fixed when it's implemented via IntelliSense (https://github.com/Microsoft/vscode-cpptools/issues/255 ).

**Comment by xueyunquan** [comment] 2018-02-07 00:21
@sean-mcmanus : Hope it be fixed soon, thanks.

**Comment by sean-mcmanus** [comment] 2018-09-28 02:11
@xueyunquan Go to Definition on "amdgpu_cs_submit_one" should work as of 0.19.0. The navigation issue requires adding the for each macros to a cpp.hint file.

**Comment by michelleangela** [comment] 2019-08-20 22:19
Closing this issue due to long inactivity and duplicate.

**Closed as completed by michelleangela** 2019-08-20 22:19 UTC
Labels: duplicate, Language Service, fixed
