### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by VineetSY** [microsoft/vscode-cpptools#3538] opened 2019-04-26 06:51 UTC
[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/3120060/ms-vscode.cpptools-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.1`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`d:\users\F23459C\ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment] 2019-04-26 19:05
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/3213. We expect our next release to fix the issue.

**Closed as completed by sean-mcmanus** 2019-04-26 19:05 UTC
Labels: duplicate
