### ISSUE TITLE
[FEATURE REQUEST] Make support

### ISSUE THREAD

**Issue by rvanlaar** [microsoft/vscode-cpptools#5047] opened 2020-03-03 21:06 UTC
Please support `configure` and `makefiles`.

I would like for VSCode to figure out which configure options there are and have support for makefiles when creating build tasks.

As per: #4942 Making a new issues for this.

**Comment by jureid** [comment] 2020-10-01 20:06
Hi @rvanlaar - Thanks for opening this issue. I'm excited to share that we have a beta release ready for Make support. Would you be interested in giving it a try and providing feedback?

**Comment by bobbrow** [comment] 2020-10-01 20:27
I have more information about how to join the preview here: https://github.com/microsoft/vscode-cpptools/issues/1587#issuecomment-701590120

I will close this feature request as a duplicate of #1587.

**Closed as completed by bobbrow** 2020-10-01 20:27 UTC
Labels: Feature Request, Feature: Extension API, tasks/build/debug

**Comment by rvanlaar** [comment] 2020-10-01 20:30
Yes, would love that. Is it available via the regular beta channels?

**Comment by bobbrow** [comment] 2020-10-01 20:32
It doesn't have a channel yet.  It will be a separate extension for now.  I will invite you to the repository and you can download the VSIX from the Releases page.
