### ISSUE TITLE
Intellisense False Positives on Mac M1

### ISSUE THREAD

**Issue by spinicist** [microsoft/vscode-cpptools#9510] opened 2022-06-27 21:02 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Mac OS 12.4
- VS Code Version: 1.68.1
- C/C++ Extension Version: 1.10.7
- Other extensions you installed (and if the issue persists after disabling them): C++ Extension Pack, Jupyter Extension Pack
- If using SSH remote, specify OS of remote machine: N/A
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I have recently acquired an M1 MacBook Pro. On this machine, VS Code Intellisense shows many false positives. See this screenshot - every red squiggle here is a false positive, the code compiles fine:

<img width="754" alt="Screenshot 2022-06-27 at 21 51 14" src="https://user-images.githubusercontent.com/11050744/176034145-686545d1-09c2-40b4-9383-1eff53efa300.png">

These do not occur on my Intel Macs. As best I can tell, the only difference between my setups is the processor architecture. I'm very happy to provide whatever further information requested, I'm not sure what will be helpful.

**Expected behavior**

Intellisense works the same across platforms.

**Code sample and logs**

My repository at https://github.com/spinicist/riesling

- Configurations in `c_cpp_properties.json`

I don't have this file

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

```
-------- Diagnostics - 27/06/2022, 21:59:42
Version: 1.10.7
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "macos-clang-arm64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/users/tobias/code/riesling/build",
        "/users/tobias/code/riesling/src",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include/eigen3",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include/nifti",
        "/users/tobias/code/riesling/src/cmd",
        "/users/tobias/code/riesling/test",
        "/users/tobias/code/riesling/test/op",
        "/users/tobias/code/riesling/src/algo",
        "/users/tobias/code/riesling/src/fft",
        "/users/tobias/code/riesling/src/io",
        "/users/tobias/code/riesling/src/op",
        "/users/tobias/code/riesling/src/precond",
        "/users/tobias/code/riesling/src/sim"
    ],
    "compilerPath": "/library/developer/commandlinetools/usr/bin/c++",
    "compilerArgs": [],
    "compilerFragments": [
        "-mcpu=apple-m1 -Wall -Wpedantic -Wshadow -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk",
        "-std=c++20"
    ]
}
Custom configurations:
[ /Users/tobias/Code/riesling/src/sdc.cpp ]
{
    "includePath": [
        "/users/tobias/code/riesling/build",
        "/users/tobias/code/riesling/src",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include/eigen3",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include/nifti"
    ],
    "defines": [
        "EIGEN_USE_THREADS",
        "FMT_HEADER_ONLY=1",
        "SCN_HEADER_ONLY=0"
    ],
    "compilerPath": "/library/developer/commandlinetools/usr/bin/c++",
    "compilerArgs": [],
    "compilerFragments": [
        "-mcpu=apple-m1 -Wall -Wpedantic -Wshadow -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk",
        "-std=c++20"
    ]
}
[ /Users/tobias/Code/riesling/src/trajectory.cpp ]
{
    "includePath": [
        "/users/tobias/code/riesling/build",
        "/users/tobias/code/riesling/src",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include/eigen3",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include/nifti"
    ],
    "defines": [
        "EIGEN_USE_THREADS",
        "FMT_HEADER_ONLY=1",
        "SCN_HEADER_ONLY=0"
    ],
    "compilerPath": "/library/developer/commandlinetools/usr/bin/c++",
    "compilerArgs": [],
    "compilerFragments": [
        "-mcpu=apple-m1 -Wall -Wpedantic -Wshadow -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk",
        "-std=c++20"
    ]
}
Translation Unit Mappings:
[ /Users/tobias/Code/riesling/src/sdc.cpp ]:
    /Users/tobias/Code/riesling/src/op/grid.hpp *
    /Users/tobias/Code/riesling/src/trajectory.h *
    /Users/tobias/Code/riesling/src/types.h *
[ /Users/tobias/Code/riesling/src/trajectory.cpp ]:
    /Users/tobias/Code/riesling/src/trajectory.cpp
    /Users/tobias/Code/riesling/src/trajectory.h
    /Users/tobias/Code/riesling/src/types.h
Translation Unit Configurations:
[ /Users/tobias/Code/riesling/src/sdc.cpp ]:
    Process ID: 2468
    Memory Usage: 511 MB
    Compiler Path: /library/developer/commandlinetools/usr/bin/c++
    Includes:
        /Users/tobias/Code/riesling/build
        /Users/tobias/Code/riesling/src
        /Users/tobias/Code/riesling/build/vcpkg_installed/arm64-osx/include/eigen3
        /Users/tobias/Code/riesling/build/vcpkg_installed/arm64-osx/include
        /Users/tobias/Code/riesling/build/vcpkg_installed/arm64-osx/include/nifti
        /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include
        /Library/Developer/CommandLineTools/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks
    Defines:
        EIGEN_USE_THREADS
        FMT_HEADER_ONLY=1
        SCN_HEADER_ONLY=0
        NDEBUG
    Standard Version: c++20
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=110000
[ /Users/tobias/Code/riesling/src/trajectory.cpp ]:
    Process ID: 2527
    Memory Usage: 331 MB
    Compiler Path: /library/developer/commandlinetools/usr/bin/c++
    Includes:
        /Users/tobias/Code/riesling/build
        /Users/tobias/Code/riesling/src
        /Users/tobias/Code/riesling/build/vcpkg_installed/arm64-osx/include/eigen3
        /Users/tobias/Code/riesling/build/vcpkg_installed/arm64-osx/include
        /Users/tobias/Code/riesling/build/vcpkg_installed/arm64-osx/include/nifti
        /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include
        /Library/Developer/CommandLineTools/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks
    Defines:
        EIGEN_USE_THREADS
        FMT_HEADER_ONLY=1
        SCN_HEADER_ONLY=0
        NDEBUG
    Standard Version: c++20
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 843 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 4001
Number of files parsed: 1780
```

Note from looking at this there seems to be a discrepancy in the C++ standard as specified by my CMakeLists and that used by Intellisense - but I'm pretty sure this is all legal C++20 code.

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

Will provide if requested.

**Comment by sean-mcmanus** [comment] 2022-06-27 22:27
What do you mean by "discrepancy in the C++ standard"? I see c++20 consistently in your logging.

I'm not reproing the issue in general on our mac m1 test machine, but I haven't been able to fully configure that specific project yet.

**Comment by spinicist** [comment] 2022-06-28 06:11
Thanks for getting back so fast. 

If you look at the "cppStandard" towards the top of that report, it is 17, but all the compiler fragments say 20.

(I double checked and my CMakeLists does specify 20. Apologies, I thought it was 17.)

But yes my intuition is this isn't the problem. Are there any other reports/diagnostic information I can provide?

**Comment by sean-mcmanus** [comment] 2022-06-28 06:54
Yeah, the c++17 in the c_cpp_properties.json isn't used because the configuration provider is being set.

If you can provide a simpler repro that could help. Our current mac m1 test machine is missing some dependencies required to configure your project, although we may be able to fix that tomorrow.

Otherwise, your logging seems good so I'm not sure what the issue could be yet. If you compared logging with your Intel mac that might give a clue as to what is different. We have not encountered many mac arm64-only bugs yet, so it's pretty unusual for there to be a difference in behavior.

**Comment by spinicist** [comment] 2022-06-28 10:50
Here's the log from one of my Intel Macs:

```
-------- Diagnostics - 28/06/2022, 11:43:13
Version: 1.10.7
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [],
    "compilerPath": "/usr/local/bin/gcc-11",
    "cStandard": "gnu17",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "macos-gcc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/users/tobias/code/riesling/build/cmakefiles",
        "/users/tobias/code/riesling/build",
        "/users/tobias/code/riesling/src",
        "/users/tobias/code/riesling/build/vcpkg_installed/x64-osx/include/eigen3",
        "/users/tobias/code/riesling/build/vcpkg_installed/x64-osx/include",
        "/users/tobias/code/riesling/build/vcpkg_installed/x64-osx/include/nifti",
        "/users/tobias/code/riesling/src/cmd",
        "/users/tobias/code/riesling/test",
        "/users/tobias/code/riesling/test/op",
        "/users/tobias/code/riesling/src/algo",
        "/users/tobias/code/riesling/src/fft",
        "/users/tobias/code/riesling/src/io",
        "/users/tobias/code/riesling/src/op",
        "/users/tobias/code/riesling/src/precond",
        "/users/tobias/code/riesling/src/sim"
    ],
    "compilerPath": "/applications/xcode.app/contents/developer/toolchains/xcodedefault.xctoolchain/usr/bin/c++",
    "compilerArgs": [],
    "compilerFragments": [
        "-march=native -Wall -Wpedantic -Wshadow -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk",
        "-std=c++2a"
    ]
}
Custom configurations:
[ /Users/tobias/Code/riesling/src/trajectory.cpp ]
{
    "includePath": [
        "/users/tobias/code/riesling/build",
        "/users/tobias/code/riesling/src",
        "/users/tobias/code/riesling/build/vcpkg_installed/x64-osx/include/eigen3",
        "/users/tobias/code/riesling/build/vcpkg_installed/x64-osx/include",
        "/users/tobias/code/riesling/build/vcpkg_installed/x64-osx/include/nifti"
    ],
    "defines": [
        "EIGEN_USE_THREADS",
        "FMT_HEADER_ONLY=1",
        "SCN_HEADER_ONLY=0"
    ],
    "compilerPath": "/applications/xcode.app/contents/developer/toolchains/xcodedefault.xctoolchain/usr/bin/c++",
    "compilerArgs": [],
    "compilerFragments": [
        "-march=native -Wall -Wpedantic -Wshadow -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk",
        "-std=c++2a"
    ]
}
Translation Unit Mappings:
[ /Users/tobias/Code/riesling/src/log.cpp ]:
    /Users/tobias/Code/riesling/src/log.h *
[ /Users/tobias/Code/riesling/src/trajectory.cpp ]:
    /Users/tobias/Code/riesling/src/trajectory.cpp
Translation Unit Configurations:
[ /Users/tobias/Code/riesling/src/log.cpp ]:
    Process ID: 10950
    Memory Usage: 182 MB
    Compiler Path: /applications/xcode.app/contents/developer/toolchains/xcodedefault.xctoolchain/usr/bin/c++
    Includes:
        /opt/intel/compilers_and_libraries_2019.4.233/mac/mkl/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++20
    IntelliSense Mode: macos-clang-x64
    Other Flags:
        --clang
        --clang_version=110000
[ /Users/tobias/Code/riesling/src/trajectory.cpp ]: not ready
    Process ID: 10958
    Memory Usage: 630 MB
    Compiler Path: /applications/xcode.app/contents/developer/toolchains/xcodedefault.xctoolchain/usr/bin/c++
    Includes:
        /Users/tobias/Code/riesling/build
        /Users/tobias/Code/riesling/src
        /Users/tobias/Code/riesling/build/vcpkg_installed/x64-osx/include/eigen3
        /Users/tobias/Code/riesling/build/vcpkg_installed/x64-osx/include
        /Users/tobias/Code/riesling/build/vcpkg_installed/x64-osx/include/nifti
        /opt/intel/compilers_and_libraries_2019.4.233/mac/mkl/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Defines:
        EIGEN_USE_THREADS
        FMT_HEADER_ONLY=1
        SCN_HEADER_ONLY=0
        NDEBUG
    Standard Version: c++20
    IntelliSense Mode: macos-clang-x64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 813 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 4136
```

This box does also have GCC installed (via homebrew), which the "compilerPath" seems to have picked up, but if I understand the later messages it is actually calling the system Clang (which is what it should be doing, that's what the build is set to do). Other than that the log looks pretty similar to me?

Are there any other logs I should provide?

**Comment by sean-mcmanus** [comment] 2022-06-28 22:12
The m1 machine is using the command line tools and the other one is not, so that could be the difference. We've installed the dependencies on our m1 test machine so we can try to repro the issue again. The gcc in the c_cpp_properties.json is not used (overriden by the configuration provider's compilerPath).

**Comment by sean-mcmanus** [comment] 2022-06-29 03:35
@spinicist FYI, we may not be able to investigate this till Thursday/Friday. I'm OOF tomorrow and we've been trying to get 2 builds released.

**Comment by spinicist** [comment] 2022-06-29 08:13
That's no problem at all - I'm very happy with the speed of response.

**Comment by spinicist** [comment] 2022-06-30 08:48
A quick update that I removed the command-line tools from my M1 box, ran `xcode-select --reset`, reconfigured my project, and the issue persists. Here is another screenshot:

<img width="572" alt="Screenshot 2022-06-30 at 09 46 11" src="https://user-images.githubusercontent.com/11050744/176634580-a95c8ca6-d89f-4515-8ff6-18ded0fb3c4e.png">

And here is what the C/C++ log looks like now:
```
-------- Diagnostics - 30/06/2022, 09:45:47
Version: 1.10.7
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "macos-clang-arm64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/users/tobias/code/riesling/build",
        "/users/tobias/code/riesling/src",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include/eigen3",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include/nifti",
        "/users/tobias/code/riesling/src/cmd",
        "/users/tobias/code/riesling/test",
        "/users/tobias/code/riesling/test/op",
        "/users/tobias/code/riesling/src/algo",
        "/users/tobias/code/riesling/src/fft",
        "/users/tobias/code/riesling/src/io",
        "/users/tobias/code/riesling/src/op",
        "/users/tobias/code/riesling/src/precond",
        "/users/tobias/code/riesling/src/sim"
    ],
    "compilerPath": "/applications/xcode.app/contents/developer/toolchains/xcodedefault.xctoolchain/usr/bin/c++",
    "compilerArgs": [],
    "compilerFragments": [
        "-mcpu=apple-m1 -Wall -Wpedantic -Wshadow -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk",
        "-std=c++20"
    ]
}
Custom configurations:
[ /Users/tobias/Code/riesling/src/cmd/split.cpp ]
{
    "includePath": [
        "/users/tobias/code/riesling/build",
        "/users/tobias/code/riesling/src",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include/eigen3",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include",
        "/users/tobias/code/riesling/build/vcpkg_installed/arm64-osx/include/nifti"
    ],
    "defines": [
        "EIGEN_USE_THREADS",
        "FMT_HEADER_ONLY=1",
        "SCN_HEADER_ONLY=0"
    ],
    "compilerPath": "/applications/xcode.app/contents/developer/toolchains/xcodedefault.xctoolchain/usr/bin/c++",
    "compilerArgs": [],
    "compilerFragments": [
        "-mcpu=apple-m1 -Wall -Wpedantic -Wshadow -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk",
        "-std=c++20"
    ]
}
Translation Unit Mappings:
[ /Users/tobias/Code/riesling/src/cmd/split.cpp ]:
    /Users/tobias/Code/riesling/src/cmd/split.cpp
Translation Unit Configurations:
[ /Users/tobias/Code/riesling/src/cmd/split.cpp ]:
    Process ID: 21974
    Memory Usage: 475 MB
    Compiler Path: /applications/xcode.app/contents/developer/toolchains/xcodedefault.xctoolchain/usr/bin/c++
    Includes:
        /Users/tobias/Code/riesling/build
        /Users/tobias/Code/riesling/src
        /Users/tobias/Code/riesling/build/vcpkg_installed/arm64-osx/include/eigen3
        /Users/tobias/Code/riesling/build/vcpkg_installed/arm64-osx/include
        /Users/tobias/Code/riesling/build/vcpkg_installed/arm64-osx/include/nifti
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Defines:
        EIGEN_USE_THREADS
        FMT_HEADER_ONLY=1
        SCN_HEADER_ONLY=0
        NDEBUG
    Standard Version: c++20
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 475 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 4002
Number of files parsed: 1694

```

**Comment by sean-mcmanus** [comment] 2022-06-30 22:38
@spinicist The issue is caused by ARM_NEON __builtin intrinsics in the Eigen3 library that cause are IntelliSense parser to happen to trigger a cascading parse failure that would skip over various definitions such as the vector, but if those definitions were later reopened (triggering our "fragment parse") then the squiggles would go away. One potential workaround is to define EIGEN_ARM64_USE_SVE, maybe

#if __INTELLISENSE__
#define #define EIGEN_ARM64_USE_SVE
#endif

which could be put in a forcedInclude file.

I'll look into if there's some better fix on our end...

**Comment by sean-mcmanus** [comment] 2022-06-30 22:57
Oh, this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/7413 (forgot about that issue).

**Closed as not planned by sean-mcmanus** 2022-06-30 22:57 UTC
Labels: bug, Language Service, Feature: Configuration, Visual Studio

**Comment by sean-mcmanus** [comment] 2022-06-30 23:04
That linked issue has some other potential workarounds. We're still waiting for a fix from our parser, but it sounds like there might be some other fix we could do ourselves (sooner), not sure if we should or not yet.

**Comment by spinicist** [comment] 2022-07-01 09:12
Thanks so much! I used the `forcedInclude` trick from #7413 and that seems to have worked. Apologies for not finding that issue, the Github Issue search failed me.

My opinion is always for fixing things like this at source, any way I can help apply gentle pressure to get the parser fixed?

**Comment by sean-mcmanus** [comment] 2022-07-01 20:17
You could upvote https://developercommunity.visualstudio.com/t/C-IntelliSense-doesnt-work-correctly/1408223 .

**Comment by spinicist** [comment] 2022-07-01 20:42
Done! Thanks again.
