### ISSUE TITLE
Call Hierarchy doesn't work correctly for std::string::append

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10924] opened 2023-05-05 23:11 UTC
I'm not sure what is special about this case yet, i.e. simpler cases don't repro the bug. Find All References works correctly.

For call from, it appears to select an incorrect overload, and for call to, it is missing the call in user code.

**Comment by michelleangela** [comment] 2023-05-17 03:47
Making this a duplicate of https://github.com/microsoft/vscode-cpptools/issues/10923 as it has the same root cause.

**Closed as completed by michelleangela** 2023-05-17 03:47 UTC
Labels: bug, duplicate, Language Service, Feature: Call Hierarchy
