### ISSUE TITLE
Extension crashes in specific code structure

### ISSUE THREAD

**Issue by EJammy** [microsoft/vscode-cpptools#6554] opened 2020-11-20 07:15 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.19041
- VS Code Version: latest
- C/C++ Extension Version: latest
- A clear and concise description of what the bug is:

Crashes with the following code
![image](https://user-images.githubusercontent.com/27494262/99769312-17f91300-2b41-11eb-8770-023b58b38ed0.png)

Does not crash with other declarations or not assigning
![image](https://user-images.githubusercontent.com/27494262/99769657-9bb2ff80-2b41-11eb-910a-f1ac6948e4c6.png)

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 11/20/2020, 3:05:17 PM
Version: 1.1.2
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "/usr/bin/cpp",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [
        "-Wall -Wshadow -g"
    ],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\Connor\Documents\My stuff\C++\playground.cpp ]:
    C:\Users\Connor\Documents\My stuff\C++\playground.cpp
Translation Unit Configurations:
[ C:\Users\Connor\Documents\My stuff\C++\playground.cpp ]:
    Process ID: 6844
    Memory Usage: 0 MB
    Compiler Path: /usr/bin/cpp
    Includes:
        C:\Users\Connor\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7
        C:\Users\Connor\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\x86_64-linux-gnu\c++\7
        C:\Users\Connor\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7\backward
        C:\Users\Connor\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc\x86_64-linux-gnu\7\include
        C:\Users\Connor\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\local\include
        C:\Users\Connor\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc\x86_64-linux-gnu\7\include-fixed
        C:\Users\Connor\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\x86_64-linux-gnu
        C:\Users\Connor\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=70500
Total Memory Usage: 0 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 5512
Number of files discovered (not excluded): 5011
```
</details>

**Comment by sean-mcmanus** [comment] 2020-11-20 19:39
Thanks for reporting this. I've filed a bug against our shared parser with VS at https://developercommunity.visualstudio.com/content/problem/1264458/cc-intellisense-crashes-in-linux-mode-with-foo-f-f.html .

FYI, that code appears to be non-standard C++ that doesn't compile with cl.exe: error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax", so you might want to consider an alternative syntax.

Also, usage of Linux style WSL paths on Windows is a deprecated feature and may hit various bugs caused by mixing of case sensitive Linux paths and non-case sensitive Windows paths -- the recommended way to use WSL paths is to remote to WSL (preferably with WSL2 mode). However, this particular crash isn't related to that issue.

**Comment by sean-mcmanus** [comment] 2021-01-21 08:27
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2

**Closed as completed** 2021-02-03 00:45 UTC
Labels: bug, Language Service, fixed, reliability, parser, Visual Studio
