### ISSUE TITLE
Environment variable in includePath ctrl+click broken?

### ISSUE THREAD

**Issue by azydevelopment** [microsoft/vscode-cpptools#1415] opened 2018-01-06 20:20 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1

---

Not sure if I'm missing anything; but this seems to be broken again?
**Repro test project: **[test.zip](https://github.com/Microsoft/vscode-cpptools/files/1609185/test.zip)

Steps to Reproduce:

1. Add %INCLUDE% environment user environment variable with a path that has stdint.h in it. E.g.
![image](https://user-images.githubusercontent.com/29720335/34643595-a5acb3ce-f2db-11e7-810c-157069893ec1.png)
2. Unzip test project
3. Open directory with 0.h in it in VSCode
4. Notice the cpp properties file there is:
```
            "includePath": [
                "${env:INCLUDE}",
                "${workspaceRoot}/1"
            ],
```
5. Open 0.h
6. Notice ctrl+clicking <1.h> works
7. **Notice ctrl+clicking <stdint.h> does not work**
8. **Also notice that there's no green squigly under it implying that it does see the file but doesn't let you ctrl+click it**

Reproduces without extensions: Yes/No

**Comment by sean-mcmanus** [comment] 2018-01-08 09:37
That is strange. I'm not able to repro the problem, but I used a valid environment path. It looks like your environment variable path may be invalid? I see a ";" at the end.

**Comment by azydevelopment** [comment] 2018-01-08 09:46
Should be supported I believe as per this:

https://github.com/Microsoft/vscode-cpptools/issues/1115

**Comment by sean-mcmanus** [comment] 2018-01-08 10:06
@bobbrow Do you know about this? I'm not seeing any code that handles ";" in paths.
@azydevelopment I'm able to repro the bug as described now -- the ";" seems to be the cause.

**Comment by bobbrow** [comment] 2018-01-08 16:50
It still works (and the semicolons too)

@azydevelopment, please verify that your environment variable is being picked up by VS Code.  I'm seeing weirdness when launching VS Code from explorer after just setting an environment variable via explorer's UI.  When debugging the extension, I don't see the new variable in the process environment.

I recommend you open a CMD prompt, verify your INCLUDE variable is set in the environment and then launch VS Code from that command prompt.  Let me know if that fixes it for you.  I wonder if VS Code is caching the environment somehow because CMD seems to pick up the variable.

**Comment by bobbrow** [comment] 2018-01-08 16:51
BTW, I verified this works via the CMD prompt which is why I asked you to try that.  Sorry for omitting that from my original response.

**Comment by bobbrow** [comment] 2018-01-08 19:39
Sorry, I misunderstood based on the context of the original feature request.  You had originally asked for the semicolons to work for auto-complete, etc.  Browsing via CTL+Click is still done by the old IntelliSense engine, so this never worked with paths that contained semicolons.

I'll mark this as a feature request.

**Comment by bobbrow** [comment] 2018-01-08 19:41
(and for the record, code navigation is controlled by the `browse.path` variable, not `includePath`)

**Comment by azydevelopment** [comment] 2018-01-09 07:25
Nice thanks! I'll give it a go whenever it's available.

**Comment by sean-mcmanus** [comment] 2018-01-09 22:22
We have a pre-release with the fix if you want to try it out (https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.14.6-insiders) and let us know if there are any fixes we should make before our release next week.

**Comment by azydevelopment** [comment] 2018-01-13 07:59
Awesome. If there's a release next week I'll just give that a go.

**Comment by sean-mcmanus** [comment] 2018-01-17 23:38
Should be fixed now https://github.com/Microsoft/vscode-cpptools/releases/latest .

**Closed as completed by sean-mcmanus** 2018-01-17 23:38 UTC
Labels: Language Service, Feature Request, fixed, quick fix

**Comment by azydevelopment** [comment] 2018-01-17 23:49
Confirmed working with the test project attached to this bug. Thanks guys!
