### ISSUE TITLE
Multiple include errors generated when use cmake-tools as a configuration provider for cpptools

### ISSUE THREAD

**Issue by esynr3z** [microsoft/vscode-cpptools#4350] opened 2019-09-25 18:37 UTC
Trying to use CMT (cmake-tools) with a CMake simple "hello-world" project.
Project can be configured, built and debugged - no problems here. But it's quite annoying that all includes of standart headers underlined with red squiggly lines:

> #include errors detected. Please update your includePath. Squiggles are disabled for this translation unit

> cannot open source file "stddef.h" (dependency of "stdio.h")

This happens only if I choose to use cmake-tools as a configuration provider for cpptools. If "none" option is chosen - squiggly lines disappear.

Is it an expected behaviour? I am afraid that if I will chose "none" as a configuration provider, Intellisense will not find all my defines, includes and etc. placed in my CMakeLists.txt. Am I right?

Also I am not sure what is the rigth place for this issue - cpptols repo or cmake-tolls, but decided to start here.

Operating System: Linux Fedora 28
CMake Version: 3.14.4
VSCode Version: 1.38.1
CMake Tools Extension Version: 1.1.3
Cpptools: 0.25.1
Compiler/Toolchain: gcc version 8.3.1 20190223 (Red Hat 8.3.1-2) (GCC)

**Comment by astraujums** [comment] 2020-02-01 22:02
I seem to have almost exactly the opposite problem. While using CMake Tools, I get the squiggles if I have no .vscode/settings.json file besides my CMakeLists.txt. I can get rid of squiggles if I add the file and have the following in it:
```
{
    "C_Cpp.default.configurationProvider": "vector-of-bool.cmake-tools"
}
```
Attached are two tiny workspaces that show the difference. They also show a nuisance of CMake Tools trying to handle non-CMake folders in a multi-root workspace but that is another issue.

VSCode:
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

CMake Tools:
1.3.0-beta

CppTools:
0.26.3

CMake:
3.14.1

Toolchain:
Visual Studio Build Tools 2019, x64

[vscode_intellisense_ok.zip](https://github.com/microsoft/vscode-cpptools/files/4143278/vscode_intellisense_ok.zip)
[vscode_intellisense_squiggles.zip](https://github.com/microsoft/vscode-cpptools/files/4143279/vscode_intellisense_squiggles.zip)

**Comment by sean-mcmanus** [comment] 2020-02-03 20:11
@astraujums The "configurationProvider" property needs to be set in order for the CMake Tools extension to provide config data, which is "by design". Can you clarify if you still believe you are hitting a bug?

**Comment by astraujums** [comment] 2020-02-04 07:58
@sean-mcmanus I am "hitting" a solution in this case! 😄 I believe that the property was set when I clicked on "Allow" in the message that requested CMake Tools to configure IntelliSense. I did not realize initially that I need to preserve the files in the .vscode folder and not just the workspace file, which is why I was getting the squiggles back after every clean checkout.

There might be some inconsistency with when the message appears because at least once the message did not appear. Could have been because the folder with CMakeLists.txt file was not the first in the list of roots in the multi-root workspace. But this is [an issue](https://github.com/microsoft/vscode-cmake-tools/issues/1042) with CMake Tools, not Cpp Tools

**Comment by TheJCAB** [comment] 2020-07-12 20:45
I'm having an identical problem. I do have a .vscode\settings.json, which includes:

"C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools"

(no longer vector-of-bool :), but otherwise the same solution @astraujums detailed)

So this might be a completely different issue.

The project is vanilla CMake, with MSVC 2019 16.7 as the toolset. The symptom is identical. Building works great, but intellisense can't seem to find any headers outside of the project (windows.h, stdio.h, etc...)

I'm experiencing the ["version (2.1) of cmake-file-api issue"](https://github.com/microsoft/vscode-cmake-tools/issues/1341). The one [solution offered in StackOverflow](https://stackoverflow.com/questions/62445673/cmakefileapi-parser-warning-message-about-cmake-in-windows-vscode) of doctoring the codemodel-v2-blah.json file doesn't help. This is probably the reason for intellisense not working in my case, but I don't know for certain.

I see there was [a PR on CMake tools](https://github.com/microsoft/vscode-cmake-tools/pull/1343) last week to fix the issue. I'm hoping it'll be released soon...

At this point I'm commenting here for the benefit of anyone experiencing this issue and looking for information.

**Comment by pbannister** [comment] 2020-07-30 01:10
Had the same symptom, though perhaps a different cause. Now solved. 
Started with a dead-simple hello-world program, and got the error squibbles. Enabled debug cpptools logging (as suggested by @bobbrow above). One line caught my eye:
```
  Unable to retrieve file system information for /usr/include/kernel. error = -1
```
Attached the complete log: [cpptools-log.txt](https://github.com/microsoft/vscode-cpptools/files/4998182/cpptools-log.txt)

Brute force ... this is on Linux, clearly:
```
$ find ~ -type f -print0 | xargs -0 grep /usr/include/kernel
grep: /home/preston/sources/core: Permission denied
/home/preston/.config/Code/User/settings.json:        "/usr/include/kernel"
/home/preston/.config/Code/logs/20200729T172345/exthost7/output_logging_20200729T172348/5-CC++.log:  Unable to retrieve file system information for /usr/include/kernel. error = -1
/home/preston/.config/Code/logs/20200729T172345/exthost7/output_logging_20200729T172348/5-CC++.log:  Unable to retrieve file system information for /usr/include/kernel. error = -1
/home/preston/.config/Code/logs/20200729T172345/exthost7/output_logging_20200729T172348/5-CC++.log:Unable to resolve include path: /usr/include/kernel
/home/preston/.config/Code/logs/20200729T172345/exthost7/output_logging_20200729T172348/5-CC++.log:Unable to resolve include path: /usr/include/kernel
/home/preston/.config/Code/logs/20200729T172345/exthost7/output_logging_20200729T172348/5-CC++.log:Unable to resolve include path: /usr/include/kernel
/home/preston/.config/Code/logs/20200729T172345/exthost7/output_logging_20200729T172348/5-CC++.log:Unable to resolve include path: /usr/include/kernel
/home/preston/.config/Code/logs/20200729T172345/exthost7/output_logging_20200729T172348/5-CC++.log:Unable to resolve include path: /usr/include/kernel
```

Huh. So that is where vscode hides some configuration. :) What is in that **settings.json**:
```
{
    "window.zoomLevel": 2,
    "files.autoSave": "off",
    "workbench.sideBar.location": "right",
    "git.confirmSync": false,
    "cmake.configureOnOpen": true,
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.default.systemIncludePath": [
        "/usr/include/kernel"
    ]
}
```
Note that I am using vscode to browse the Linux kernel sources (works but needs work), and for a project to build a driver (Linux loadable module) which has working Intellisense (as defines and includes set correctly). Where the above bogus **systemIncludePath** came from - dunno - but deleted. Intellisense now works in the plain-vanilla CMake project.

**Comment by qt1** [comment] 2020-10-14 11:07
It seems to me that the extensions are saving caches and configurations in various locations and this seems to be both opaque and buggy.

I have uninstalled cmake tools and surprisingly the plain vanilla cmake and make just work, with some very minor settings to tasks.json and settings.json.
It even looks significantly faster to start debug..

**Comment by michelleangela** [comment] 2020-10-20 23:53
@esynr3z 
Could you try the latest insiders version of the extension and see if the issue is resolved? If the issue still reproduces, could you provide the following logs:

1. Log output from enabling the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
2. Log output from running the command `C/C++: Log Diagnostics`

**Comment by michelleangela** [comment] 2020-12-09 01:05
Closing issue because it has not had recent activity.

**Closed as completed by michelleangela** 2020-12-09 01:05 UTC
Labels: bug, Language Service, more info needed, Feature: Extension API
