### ISSUE TITLE
reference may be missing

### ISSUE THREAD

**Issue by LuckeX** [microsoft/vscode-cpptools#6320] opened 2020-10-15 06:49 UTC
Issue Type: <b>Feature Request</b>

[Warning] Some references may be missing, because workspace parsing was incomplete when Find All References was started.

Extension version: 1.0.1
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sean-mcmanus** [comment] 2020-10-15 19:18
What is the request? The warning is "by design". It means we're still scanning or potentially parsing the files in the workspace for references.

**Comment by michelleangela** [comment] 2020-12-09 18:40
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 18:40 UTC
Labels: Language Service, Feature Request, more info needed, Feature: Find All References
