### ISSUE TITLE
'C/C++:g++.exe build active file' won't complete the build

### ISSUE THREAD

**Issue by Namualii** [microsoft/vscode-cpptools#9231] opened 2022-04-23 19:17 UTC
Issue Type: <b>Bug</b>

I am trying to build the file I'm actively working on. However, when I run the build file task it never finishes. This goes for all of my .cpp files. There a pinsheel that spins showing that the task is still running, and when I try to run task again it says that an instance of the task is still in progress. Closing the broweser and repoening doens't help. Trying a different terminal doesn't help. 

Extension version: 1.10.0
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.76GB (1.94GB free)|
|Process Argv|--crash-reporter-id e8fe0db0-a5d4-43b6-aea9-a00cbe79da86|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by Colengms** [comment] 2022-04-27 01:56
This might be the same as https://github.com/microsoft/vscode-cpptools/issues/9241

**Comment by elahehrashedi** [comment] 2022-04-29 18:56
This is highly like the duplicate of https://github.com/microsoft/vscode-cpptools/issues/9241, I sent a fix for it.

**Closed as completed** 2022-05-03 16:43 UTC
Labels: duplicate, fixed, more info needed, tasks/build/debug
