### ISSUE TITLE
"go to definition" about struct member failed when "pointer to incomplete class type is not allowed" occurs

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3116] opened 2019-01-30 07:14 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**test.h**
struct pci_dev {
	int	bus;		
};

**test.c**                                                   // don't include test.h
void test(struct pci_dev *dev)                   // "pci_dev" can go to definition
{
    dev->bus = 0;  
}
//"pointer to incomplete class type is not allowed" occurs, "dev" can go to definition but "bus" can't.
//"No definition found for bus" occurs.

**Comment by sean-mcmanus** [comment] 2019-02-06 23:35
This seems like it's probably has the same root cause as the other bug you reported, i.e. we're not falling back to the non-IntelliSense-based go to definition results when an error is involved (which Visual Studio does): https://github.com/Microsoft/vscode-cpptools/issues/3071 . We'll make sure both are fixed when we fix the other one.

**Comment by sean-mcmanus** [comment] 2019-05-20 19:08
This is fixed in 0.23.1.

**Closed as completed by sean-mcmanus** 2019-05-20 19:08 UTC
Labels: bug, Language Service, fixed, regression, Feature: Go to Definition
