### ISSUE TITLE
ms-vscode.cpptools-1.21.6-linux-x64 cpptools-srv crash

### ISSUE THREAD

**Issue by WZFlik** [microsoft/vscode-cpptools#12559] opened 2024-08-12 03:55 UTC
### Environment

- OS and Version: Linux version 3.10.0-1160.119.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Jun 4 14:43:51 UTC 2024
-
- VS Code Version: 
Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.17763
- C/C++ Extension Version: 1.21.6
- If using SSH remote, specify OS of remote machine: Linux version 3.10.0-1160.119.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) )

### Bug Summary and Steps to Reproduce

Bug Summary:
I use the win system vscode to remotely connect to the vscode server of centos7 using ssh, and the cpp plugin always generates a lot of core files in a very short time.
I used the 1.8x vs version, and so did the upgrade to 1.92.1 (c/ C ++tool is still 1.21.6 without the upgrade), which did not solve the problem, and the large number of core files caused my disk to fill up.

My project just wants c++ tools hints and error correction, not to compile with it.

[root@xxx bin]# pwd
/root/.vscode-server/extensions/ms-vscode.cpptools-1.21.6-linux-x64/bin
[root@xxx bin]# ll|grep core.
-rw-------  1 root root 107958272 8月  12 11:28 core.27031
-rw-------  1 root root 107958272 8月  12 11:32 core.31567
-rw-------  1 root root 107958272 8月  12 11:32 core.31585
-rw-------  1 root root 107958272 8月  12 11:32 core.31634
-rw-------  1 root root 107958272 8月  12 11:32 core.31649
-rw-------  1 root root 107958272 8月  12 11:32 core.31668
-rw-------  1 root root 107958272 8月  12 11:32 core.31710
-rw-------  1 root root 107913216 8月  12 11:32 core.31775
-rw-------  1 root root 107958272 8月  12 11:32 core.31865
-rw-------  1 root root 107958272 8月  12 11:32 core.31952
-rw-------  1 root root 107958272 8月  12 11:32 core.31990
-rw-------  1 root root 107958272 8月  12 11:38 core.7100

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Gstore",
            "includePath": [
                "${workspaceFolder}/gstore/src/include/",
                "${workspaceFolder}/gstore/src/**",
                "${workspaceFolder}/gstore/test/**",
                "${workspaceFolder}/gstore/srcpp/Include/Grpc",
                "${workspaceFolder}/gstore/srcpp/Include/ProtoHead",
                "${workspaceFolder}/gstore/srcpp/Include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "Linux",
                "GSTORE",
                "__linux__",
                "__x86_64__",
                "_GNU_SOURCE",
                "_GRPC_ENABLED_",
                "__cplusplus"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "cStandard": "c89",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-gcc-x64"
        },
        {
            "name": "Gcm",
            "includePath": [
                "${workspaceFolder}/gstore/src/include/**",
                "${workspaceFolder}/gstore/src/**",
                "${workspaceFolder}/gstore/test/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "Linux",
                "GCM",
                "__linux__",
                "__x86_64__",
                "_GNU_SOURCE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "/opt/rh/devtoolset-7/root/usr/bin/g++",
            "cStandard": "c89",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

### Additional context

coredump:
Reading symbols from /root/.vscode-server/extensions/ms-vscode.cpptools-1.21.6-linux-x64/bin/cpptools-srv...Dwarf Error: wrong version in compilation unit header (is 5, should be 2, 3, or 4) [in module /root/.vscode-server/extensions/ms-vscode.cpptools-1.21.6-linux-x64/bin/cpptools-srv]
(no debugging symbols found)...done.
[New LWP 27037]
[New LWP 27033]
[New LWP 27032]
[New LWP 27035]
[New LWP 27034]
[New LWP 27036]
[New LWP 27031]
Dwarf Error: wrong version in compilation unit header (is 5, should be 2, 3, or 4) [in module ./libc.so]
Core was generated by `/root/.vscode-server/extensions/ms-vscode.cpptools-1.21.6-linux-x64/bin/cpptool'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f9113adf5fe in __restore_sigs () from ./libc.so
(gdb) bt
#0  0x00007f9113adf5fe in __restore_sigs () from ./libc.so
#1  0x00007f9113adf778 in raise () from ./libc.so
#2  0x0000000000cce36f in (anonymous namespace)::reraise_signal(int, crash_handler_data_t*) ()
#3  0x0000000000cce5b5 in crash_handler(int, siginfo_t*, void*) ()
#4  <signal handler called>
#5  0x0000000000ae2a92 in add_token_cache_to_string(a_token_cache*) ()
#6  0x0000000000ba9f62 in record_string_version_of_template(a_tmpl_decl_state*, a_symbol*, a_token_cache*) [clone .part.0] ()
#7  0x0000000000bdc859 in template_declaration(a_tmpl_decl_state*, int*) [clone .constprop.0] ()
#8  0x0000000000be54e3 in template_or_specialization_declaration_full(a_tmpl_decl_state*, int, a_decl_parse_state*) ()
#9  0x0000000000be5f07 in template_or_specialization_declaration(a_token_kind*, int, a_source_position*, int, a_decl_parse_state*) ()
#10 0x0000000000be7705 in template_directive_or_declaration(a_token_kind*, int, a_source_position*) ()
#11 0x00000000007c56f3 in scan_class_definition(a_type*, a_decl_parse_state*, int, int, int, int, int, int, a_template*, a_decl_pos_block*) ()
#12 0x0000000000bc8af8 in f_instantiate_template_class_full(a_type*, unsigned int*, unsigned int*, int, int*) ()
#13 0x00000000007a9403 in decl_nonstatic_data_member(a_symbol_locator*, a_class_def_state*, a_member_decl_info*, int) ()
#14 0x00000000007aae0f in scan_nonstatic_data_member(a_symbol_locator*, a_class_def_state*, a_member_decl_info*) ()
#15 0x00000000007c105a in class_member_declaration(a_class_def_state*, a_tmpl_decl_state*, an_ms_attribute*, int, int, a_template_param*, int*, a_type**, a_template_instance*, a_template*, a_decl_pos_block*) ()
#16 0x00000000007c4ed3 in scan_class_definition(a_type*, a_decl_parse_state*, int, int, int, int, int, int, a_template*, a_decl_pos_block*) ()
#17 0x000000000084fcc8 in class_specifier(a_decl_parse_state*, unsigned long, int, int, int, a_source_position, a_type**, int*, int*, a_decl_pos_block*) ()
#18 0x000000000085a1d9 in decl_specifiers(unsigned long, a_decl_parse_state*, a_decl_pos_block*) ()
#19 0x00000000007bfe91 in class_member_declaration(a_class_def_state*, a_tmpl_decl_state*, an_ms_attribute*, int, int, a_template_param*, int*, a_type**, a_template_instance*, a_template*, a_decl_pos_block*) ()
#20 0x00000000007c4ed3 in scan_class_definition(a_type*, a_decl_parse_state*, int, int, int, int, int, int, a_template*, a_decl_pos_block*) ()
#21 0x000000000084fcc8 in class_specifier(a_decl_parse_state*, unsigned long, int, int, int, a_source_position, a_type**, int*, int*, a_decl_pos_block*) ()
#22 0x000000000085a1d9 in decl_specifiers(unsigned long, a_decl_parse_state*, a_decl_pos_block*) ()
#23 0x000000000082eeb8 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
#24 0x0000000000832242 in declaration(int, int, int, int, a_param_id*, a_source_range*, a_decl_parse_state*) [clone .constprop.---Type <return> to continue, or q <return> to quit---
0] ()
#25 0x0000000000832a9f in namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) ()
#26 0x00000000008303e3 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
#27 0x0000000000832242 in declaration(int, int, int, int, a_param_id*, a_source_range*, a_decl_parse_state*) [clone .constprop.0] ()
#28 0x0000000000832a9f in namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) ()
#29 0x00000000008303e3 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
#30 0x0000000000832242 in declaration(int, int, int, int, a_param_id*, a_source_range*, a_decl_parse_state*) [clone .constprop.0] ()
#31 0x0000000000832a9f in namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) ()
#32 0x00000000008303e3 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
#33 0x0000000000832242 in declaration(int, int, int, int, a_param_id*, a_source_range*, a_decl_parse_state*) [clone .constprop.0] ()
#34 0x0000000000832a9f in namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) ()
#35 0x00000000008303e3 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
#36 0x0000000000832242 in declaration(int, int, int, int, a_param_id*, a_source_range*, a_decl_parse_state*) [clone .constprop.0] ()
#37 0x0000000000834492 in translation_unit() ()
#38 0x0000000000bfb9b5 in process_translation_unit(char const*, int, an_exported_template_file*) ()
#39 0x00000000007907a9 in cfe_main(int, char**) ()
#40 0x0000000000c3fecd in cfe_main_exception_handler(int, char**) ()
#41 0x00000000007908ad in edg_main(int, char**) ()
#42 0x0000000000c3732e in invoke_edge_compiler(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) ()
#43 0x0000000000c380e8 in edge_compiler_main(int, char const**) ()
#44 0x00000000006af8ae in a_compiler_thread::compiler_thread_routine(a_compiler_thread*) ()
#45 0x0000000000d4183c in msvc::thread_helper_t::thread_entry(void*) ()
#46 0x00007f9113aeb5ef in start () from ./libc.so
#47 0x00007f9113aedaf2 in __clone () from ./libc.so
#48 0x0000000000000000 in ?? ()
(gdb) Dwarf Error: wrong version in compilation unit header (is 5, should be 2, 3, or 4) [in module ./libc.so]
Undefined command: "Dwarf".  Try "help".
(gdb) Core was generated by `/root/.vscode-server/extensions/ms-vscode.cpptools-1.21.6-linux-x64/bin/cpptool'.
/root/.vscode-server/extensions/ms-vscode.cpptools-1.21.6-linux-x64/bin/was generated by `/root/.vscode-server/extensions/ms-vscode.cpptools-1.21.6-linux-x64/bin/cpptool'.: 没有那个文件或目录.
(gdb) Program terminated with signal 11, Segmentation fault.
Undefined command: "Program".  Try "help".
(gdb) #0  0x00007f9113adf5fe in __restore_sigs () from ./libc.so
(gdb) (gdb) bt
Undefined command: "".  Try "help".
(gdb) #0  0x00007f9113adf5fe in __restore_sigs () from ./libc.so
(gdb) #1  0x00007f9113adf778 in raise () from ./libc.so
(gdb) #2  0x0000000000cce36f in (anonymous namespace)::reraise_signal(int, crash_handler_data_t*) ()
(gdb) #3  0x0000000000cce5b5 in crash_handler(int, siginfo_t*, void*) ()
(gdb) #4  <signal handler called>
(gdb) #5  0x0000000000ae2a92 in add_token_cache_to_string(a_token_cache*) ()
(gdb) #6  0x0000000000ba9f62 in record_string_version_of_template(a_tmpl_decl_state*, a_symbol*, a_token_cache*) [clone .part.0] ()
(gdb) #7  0x0000000000bdc859 in template_declaration(a_tmpl_decl_state*, int*) [clone .constprop.0] ()
(gdb) #8  0x0000000000be54e3 in template_or_specialization_declaration_full(a_tmpl_decl_state*, int, a_decl_parse_state*) ()
(gdb) #9  0x0000000000be5f07 in template_or_specialization_declaration(a_token_kind*, int, a_source_position*, int, a_decl_parse_state*) ()
(gdb) #10 0x0000000000be7705 in template_directive_or_declaration(a_token_kind*, int, a_source_position*) ()
(gdb) #11 0x00000000007c56f3 in scan_class_definition(a_type*, a_decl_parse_state*, int, int, int, int, int, int, a_template*, a_decl_pos_block*) ()
(gdb) #12 0x0000000000bc8af8 in f_instantiate_template_class_full(a_type*, unsigned int*, unsigned int*, int, int*) ()
(gdb) #13 0x00000000007a9403 in decl_nonstatic_data_member(a_symbol_locator*, a_class_def_state*, a_member_decl_info*, int) ()
(gdb) #14 0x00000000007aae0f in scan_nonstatic_data_member(a_symbol_locator*, a_class_def_state*, a_member_decl_info*) ()
(gdb) #15 0x00000000007c105a in class_member_declaration(a_class_def_state*, a_tmpl_decl_state*, an_ms_attribute*, int, int, a_template_param*, int*, a_type**, a_template_instance*, a_template*, a_decl_pos_block*) ()
(gdb) #16 0x00000000007c4ed3 in scan_class_definition(a_type*, a_decl_parse_state*, int, int, int, int, int, int, a_template*, a_decl_pos_block*) ()
(gdb) #17 0x000000000084fcc8 in class_specifier(a_decl_parse_state*, unsigned long, int, int, int, a_source_position, a_type**, int*, int*, a_decl_pos_block*) ()
(gdb) #18 0x000000000085a1d9 in decl_specifiers(unsigned long, a_decl_parse_state*, a_decl_pos_block*) ()
(gdb) #19 0x00000000007bfe91 in class_member_declaration(a_class_def_state*, a_tmpl_decl_state*, an_ms_attribute*, int, int, a_template_param*, int*, a_type**, a_template_instance*, a_template*, a_decl_pos_block*) ()
(gdb) #20 0x00000000007c4ed3 in scan_class_definition(a_type*, a_decl_parse_state*, int, int, int, int, int, int, a_template*, a_decl_pos_block*) ()
(gdb) #21 0x000000000084fcc8 in class_specifier(a_decl_parse_state*, unsigned long, int, int, int, a_source_position, a_type**, int*, int*, a_decl_pos_block*) ()
(gdb) #22 0x000000000085a1d9 in decl_specifiers(unsigned long, a_decl_parse_state*, a_decl_pos_block*) ()
(gdb) #23 0x000000000082eeb8 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
(gdb) #24 0x0000000000832242 in declaration(int, int, int, int, a_param_id*, a_source_range*, a_decl_parse_state*) [clone .constprop.---Type <return> to continue, or q <return> to quit---
(gdb) 0] ()
Undefined command: "0".  Try "help".
(gdb) #25 0x0000000000832a9f in namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) ()
(gdb) #26 0x00000000008303e3 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
(gdb) #27 0x0000000000832242 in declaration(int, int, int, int, a_param_id*, a_source_range*, a_decl_parse_state*) [clone .constprop.0] ()
(gdb) #28 0x0000000000832a9f in namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) ()
(gdb) #29 0x00000000008303e3 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
(gdb) #30 0x0000000000832242 in declaration(int, int, int, int, a_param_id*, a_source_range*, a_decl_parse_state*) [clone .constprop.0] ()
(gdb) #31 0x0000000000832a9f in namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) ()
(gdb) #32 0x00000000008303e3 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
(gdb) #33 0x0000000000832242 in declaration(int, int, int, int, a_param_id*, a_source_range*, a_decl_parse_state*) [clone .constprop.0] ()
(gdb) #34 0x0000000000832a9f in namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) ()
(gdb) #35 0x00000000008303e3 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
(gdb) #36 0x0000000000832242 in declaration(int, int, int, int, a_param_id*, a_source_range*, a_decl_parse_state*) [clone .constprop.0] ()
(gdb) #37 0x0000000000834492 in translation_unit() ()
(gdb) #38 0x0000000000bfb9b5 in process_translation_unit(char const*, int, an_exported_template_file*) ()
(gdb) #39 0x00000000007907a9 in cfe_main(int, char**) ()
(gdb) #40 0x0000000000c3fecd in cfe_main_exception_handler(int, char**) ()
(gdb) #41 0x00000000007908ad in edg_main(int, char**) ()
(gdb) #42 0x0000000000c3732e in invoke_edge_compiler(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) ()
(gdb) #43 0x0000000000c380e8 in edge_compiler_main(int, char const**) ()
(gdb) #44 0x00000000006af8ae in a_compiler_thread::compiler_thread_routine(a_compiler_thread*) ()
(gdb) #45 0x0000000000d4183c in msvc::thread_helper_t::thread_entry(void*) ()
(gdb) #46 0x00007f9113aeb5ef in start () from ./libc.so
(gdb) #47 0x00007f9113aedaf2 in __clone () from ./libc.so
(gdb) #48 0x0000000000000000 in ?? ()
(gdb) (gdb)
Undefined command: "".  Try "help".
(gdb)

**Comment by sean-mcmanus** [comment] 2024-08-12 17:14
@WZFlik This is a duplicate of bug https://github.com/microsoft/vscode-cpptools/issues/11900, but your report was a helpful ping/reminder.

**Closed as not planned by sean-mcmanus** 2024-08-12 17:14 UTC
Labels: bug, duplicate, Language Service, reliability, parser
