### ISSUE TITLE
can't work on win7

### ISSUE THREAD

**Issue by chena1982** [microsoft/vscode-cpptools#33] opened 2016-04-27 10:20 UTC
i install the c/cpp extersion by copy the .vscode/extersions/ms-vscode.cpptools-0.5.0 folder to a pc which can't connect to internet.
this pc use win 7, after install, ctrl+shift+o show "we have no symbol information". and cannot find "go defintion" on right button menu, and the staut bar show text "undefinedwin32".

**Comment by csholmq** [comment] 2016-04-27 14:07
Sounds like a duplicate of https://github.com/Microsoft/vscppsamples/issues/9

**Comment by sridmad** [comment] 2016-04-27 21:42
Duplicate of #9

**Closed as completed by sridmad** 2016-04-27 21:42 UTC

**Comment by chena1982** [comment] 2016-04-28 02:00
yes, it works now, thanks.
