### ISSUE TITLE
"Cout is ambigous" error

### ISSUE THREAD

**Issue by aadia1234** [microsoft/vscode-cpptools#11122] opened 2023-06-23 04:35 UTC
Hi, I'm experiencing this exact issue for the first time (June 2023). Here is what I see:
![Screenshot 2023-06-23 at 12 11 05 PM](https://github.com/microsoft/vscode-cpptools/assets/22109624/d526f78b-4d35-4755-9eca-28f489f5eff7)

It seems that whenever I'm creating a new statement or modifiyng one of my previous print statements the error occurs. It goes away if I comment then uncomment `#include<iostream>` or restart vscode (but reappears soon after)

Specs:
Apple M1 Pro
macOS: 13.3.1 (a) (22E772610a)

VSCode:

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:33.551Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0

C/C++ tool version: v1.16.2

_Originally posted by @gam3boy1 in https://github.com/microsoft/vscode-cpptools/issues/9471#issuecomment-1603657211_

**Comment by ranganpal** [comment] 2023-06-23 06:27
I am also getting same error today

**Comment by TashinParvez** [comment] 2023-06-23 06:32
I am also getting same error

**Comment by bobbrow** [comment] 2023-06-23 16:59
I'm not currently reproducing the error on Windows.  Can someone run the `C/C++: Log Diagnostics` command and share it with us?  So far, I see it happening on Apple M1 Pro.  Is anyone seeing this on Windows or linux?

**Comment by gam3boy1** [comment] 2023-06-23 17:02
> I'm not currently reproducing the error on Windows. Can someone run the `C/C++: Log Diagnostics` command and share it with us? So far, I see one user reporting it happening on Apple M1 Pro. Is anyone seeing this on Windows or linux?

Here's a link to a recent post with the exact same issue on windows: https://github.com/microsoft/vscode-cpptools/issues/11123

**Comment by gam3boy1** [comment] 2023-06-23 17:05
@bobbrow I'd like to point out that the label "regression" doesn't fit because this problem has occurred in vs code previously: https://github.com/microsoft/vscode-cpptools/issues/9471#issuecomment-1603657211

**Comment by sean-mcmanus** [comment] 2023-06-23 17:27
@gam3boy1 This new issue does appear to be a 1.16.2 regression, since https://github.com/microsoft/vscode-cpptools/issues/9471 has different repro steps.

**Comment by sean-mcmanus** [comment] 2023-06-23 17:51
We've repro'd the issue -- the recommended workaround is to downgrade to 1.15.4.

![image](https://github.com/microsoft/vscode-cpptools/assets/19859882/df2e2829-2ddc-4d74-ae91-da4a3831d1e8)

Or using the vsix from 1.16.0 (pre-release) from https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ), not 1.16.1.

**Comment by michelleangela** [comment] 2023-06-24 03:23
This is now fixed in [release version 1.16.3](https://github.com/microsoft/vscode-cpptools/releases/tag/v1.16.3).

**Closed as completed by michelleangela** 2023-06-24 03:23 UTC
Labels: bug, Language Service, regression, verified
