### ISSUE TITLE
Add Header/Class File Generation

### ISSUE THREAD

**Issue by davidbitton** [microsoft/vscode-cpptools#3552] opened 2019-04-28 14:19 UTC
This is not  defect so I'm not using the template. There doesn't appear to be an extension — at all — for VSCode that will generate even a stub header/class file combo. I realize that if I want method generation, etc. that I have to use VS Studio — with some Resharper goodness — but something thi simple would be a huge add-on for C coders; especially those working on embedded devices along with PlatformIO. Thanks!

**Comment by sean-mcmanus** [comment] 2019-04-29 21:39
We're tracking that feature request with https://github.com/Microsoft/vscode-cpptools/issues/664 (you could upvote that).

**Comment by birgersp** [comment] 2019-12-14 13:34
IMO this isn't really a duplicate of #664. #664 assumes you already have a header file. I am (like OP) looking for a feature to generate C++ header and source files from a class name.

**Comment by sean-mcmanus** [comment] 2019-12-16 20:50
@birgersp Okay, thanks for pointing that out.

**Comment by bobbrow** [comment] 2020-04-02 21:55
We're using #664 to track the whole experience.  I'll update that issue to make it more clear.

**Closed as completed by bobbrow** 2020-04-02 21:55 UTC
Labels: duplicate, Language Service, Feature Request
