### ISSUE TITLE
IntelliSense resolution failing if prepending user defined type identifier with negation operator

### ISSUE THREAD

**Issue by KaeLL** [microsoft/vscode-cpptools#5865] opened 2020-07-30 15:23 UTC
**Type: LanguageService**

- OS and Version: Clear Linux 33560
- VS Code Version: 1.47.3
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): Git Graph
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

![code_bug](https://user-images.githubusercontent.com/4423144/88940143-ceb54880-d25d-11ea-871c-12a25ea54298.png)

If I prepend `test` with the `!` operator, IntelliSense resolution doesn't work. If there's no `!` operator, it works as expected.

<details>
  <summary><strong>Logs</strong></summary>

```
cpptools/didChangeCppProperties
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/clang'
terminating child process: 8628
  Folder: /usr/lib64/clang/10.0.1/include/ will be indexed
  Folder: /usr/include/ will be indexed
textDocument/didOpen: file:///home/nvmd/Documents/code_test.c
Populate include completion cache.
Discovering files...
cpptools/activeDocumentChange: file:///home/nvmd/Documents/code_test.c
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///home/nvmd/Documents/code_test.c (id: 2)
cpptools/getCodeActions: file:///home/nvmd/Documents/code_test.c (id: 3)
cpptools/getDocumentSymbols
  Processing folder (recursive): /usr/lib64/clang/10.0.1/include/
sending compilation args for /home/nvmd/Documents/code_test.c
  include: /usr/lib64/clang/10.0.1/include
  include: /usr/include
  define: __llvm__=1
  define: __clang__=1
  define: __clang_major__=10
  define: __clang_minor__=0
  define: __clang_patchlevel__=1
  define: __clang_version__="10.0.1 "
  define: __GNUC__=4
  define: __GNUC_MINOR__=2
  define: __GNUC_PATCHLEVEL__=1
  define: __GXX_ABI_VERSION=1002
  define: __ATOMIC_RELAXED=0
  define: __ATOMIC_CONSUME=1
  define: __ATOMIC_ACQUIRE=2
  define: __ATOMIC_RELEASE=3
  define: __ATOMIC_ACQ_REL=4
  define: __ATOMIC_SEQ_CST=5
  define: __OPENCL_MEMORY_SCOPE_WORK_ITEM=0
  define: __OPENCL_MEMORY_SCOPE_WORK_GROUP=1
  define: __OPENCL_MEMORY_SCOPE_DEVICE=2
  define: __OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES=3
  define: __OPENCL_MEMORY_SCOPE_SUB_GROUP=4
  define: __PRAGMA_REDEFINE_EXTNAME=1
  define: __VERSION__="Clang 10.0.1 "
  define: __STRICT_ANSI__=1
  define: __OBJC_BOOL_IS_BOOL=0
  define: __CONSTANT_CFSTRINGS__=1
  define: __ORDER_LITTLE_ENDIAN__=1234
  define: __ORDER_BIG_ENDIAN__=4321
  define: __ORDER_PDP_ENDIAN__=3412
  define: __BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __LITTLE_ENDIAN__=1
  define: _LP64=1
  define: __LP64__=1
  define: __CHAR_BIT__=8
  define: __SCHAR_MAX__=127
  define: __SHRT_MAX__=32767
  define: __INT_MAX__=2147483647
  define: __LONG_MAX__=9223372036854775807L
  define: __LONG_LONG_MAX__=9223372036854775807LL
  define: __WCHAR_MAX__=2147483647
  define: __WINT_MAX__=4294967295U
  define: __INTMAX_MAX__=9223372036854775807L
  define: __SIZE_MAX__=18446744073709551615UL
  define: __UINTMAX_MAX__=18446744073709551615UL
  define: __PTRDIFF_MAX__=9223372036854775807L
  define: __INTPTR_MAX__=9223372036854775807L
  define: __UINTPTR_MAX__=18446744073709551615UL
  define: __SIZEOF_DOUBLE__=8
  define: __SIZEOF_FLOAT__=4
  define: __SIZEOF_INT__=4
  define: __SIZEOF_LONG__=8
  define: __SIZEOF_LONG_DOUBLE__=16
  define: __SIZEOF_LONG_LONG__=8
  define: __SIZEOF_POINTER__=8
  define: __SIZEOF_SHORT__=2
  define: __SIZEOF_PTRDIFF_T__=8
  define: __SIZEOF_SIZE_T__=8
  define: __SIZEOF_WCHAR_T__=4
  define: __SIZEOF_WINT_T__=4
  define: __SIZEOF_INT128__=16
  define: __INTMAX_TYPE__=long int
  define: __INTMAX_FMTd__="ld"
  define: __INTMAX_FMTi__="li"
  define: __INTMAX_C_SUFFIX__=L
  define: __UINTMAX_TYPE__=long unsigned int
  define: __UINTMAX_FMTo__="lo"
  define: __UINTMAX_FMTu__="lu"
  define: __UINTMAX_FMTx__="lx"
  define: __UINTMAX_FMTX__="lX"
  define: __UINTMAX_C_SUFFIX__=UL
  define: __INTMAX_WIDTH__=64
  define: __PTRDIFF_TYPE__=long int
  define: __PTRDIFF_FMTd__="ld"
  define: __PTRDIFF_FMTi__="li"
  define: __PTRDIFF_WIDTH__=64
  define: __INTPTR_TYPE__=long int
  define: __INTPTR_FMTd__="ld"
  define: __INTPTR_FMTi__="li"
  define: __INTPTR_WIDTH__=64
  define: __SIZE_TYPE__=long unsigned int
  define: __SIZE_FMTo__="lo"
  define: __SIZE_FMTu__="lu"
  define: __SIZE_FMTx__="lx"
  define: __SIZE_FMTX__="lX"
  define: __SIZE_WIDTH__=64
  define: __WCHAR_TYPE__=int
  define: __WCHAR_WIDTH__=32
  define: __WINT_TYPE__=unsigned int
  define: __WINT_WIDTH__=32
  define: __SIG_ATOMIC_WIDTH__=32
  define: __SIG_ATOMIC_MAX__=2147483647
  define: __CHAR16_TYPE__=unsigned short
  define: __CHAR32_TYPE__=unsigned int
  define: __UINTMAX_WIDTH__=64
  define: __UINTPTR_TYPE__=long unsigned int
  define: __UINTPTR_FMTo__="lo"
  define: __UINTPTR_FMTu__="lu"
  define: __UINTPTR_FMTx__="lx"
  define: __UINTPTR_FMTX__="lX"
  define: __UINTPTR_WIDTH__=64
  define: __FLT_DENORM_MIN__=1.40129846e-45F
  define: __FLT_HAS_DENORM__=1
  define: __FLT_DIG__=6
  define: __FLT_DECIMAL_DIG__=9
  define: __FLT_EPSILON__=1.19209290e-7F
  define: __FLT_HAS_INFINITY__=1
  define: __FLT_HAS_QUIET_NAN__=1
  define: __FLT_MANT_DIG__=24
  define: __FLT_MAX_10_EXP__=38
  define: __FLT_MAX_EXP__=128
  define: __FLT_MAX__=3.40282347e+38F
  define: __FLT_MIN_10_EXP__=(-37)
  define: __FLT_MIN_EXP__=(-125)
  define: __FLT_MIN__=1.17549435e-38F
  define: __DBL_DENORM_MIN__=4.9406564584124654e-324
  define: __DBL_HAS_DENORM__=1
  define: __DBL_DIG__=15
  define: __DBL_DECIMAL_DIG__=17
  define: __DBL_EPSILON__=2.2204460492503131e-16
  define: __DBL_HAS_INFINITY__=1
  define: __DBL_HAS_QUIET_NAN__=1
  define: __DBL_MANT_DIG__=53
  define: __DBL_MAX_10_EXP__=308
  define: __DBL_MAX_EXP__=1024
  define: __DBL_MAX__=1.7976931348623157e+308
  define: __DBL_MIN_10_EXP__=(-307)
  define: __DBL_MIN_EXP__=(-1021)
  define: __DBL_MIN__=2.2250738585072014e-308
  define: __LDBL_DENORM_MIN__=3.64519953188247460253e-4951L
  define: __LDBL_HAS_DENORM__=1
  define: __LDBL_DIG__=18
  define: __LDBL_DECIMAL_DIG__=21
  define: __LDBL_EPSILON__=1.08420217248550443401e-19L
  define: __LDBL_HAS_INFINITY__=1
  define: __LDBL_HAS_QUIET_NAN__=1
  define: __LDBL_MANT_DIG__=64
  define: __LDBL_MAX_10_EXP__=4932
  define: __LDBL_MAX_EXP__=16384
  define: __LDBL_MAX__=1.18973149535723176502e+4932L
  define: __LDBL_MIN_10_EXP__=(-4931)
  define: __LDBL_MIN_EXP__=(-16381)
  define: __LDBL_MIN__=3.36210314311209350626e-4932L
  define: __POINTER_WIDTH__=64
  define: __BIGGEST_ALIGNMENT__=16
  define: __WINT_UNSIGNED__=1
  define: __INT8_TYPE__=signed char
  define: __INT8_FMTd__="hhd"
  define: __INT8_FMTi__="hhi"
  define: __INT8_C_SUFFIX__=
  define: __INT16_TYPE__=short
  define: __INT16_FMTd__="hd"
  define: __INT16_FMTi__="hi"
  define: __INT16_C_SUFFIX__=
  define: __INT32_TYPE__=int
  define: __INT32_FMTd__="d"
  define: __INT32_FMTi__="i"
  define: __INT32_C_SUFFIX__=
  define: __INT64_TYPE__=long int
  define: __INT64_FMTd__="ld"
  define: __INT64_FMTi__="li"
  define: __INT64_C_SUFFIX__=L
  define: __UINT8_TYPE__=unsigned char
  define: __UINT8_FMTo__="hho"
  define: __UINT8_FMTu__="hhu"
  define: __UINT8_FMTx__="hhx"
  define: __UINT8_FMTX__="hhX"
  define: __UINT8_C_SUFFIX__=
  define: __UINT8_MAX__=255
  define: __INT8_MAX__=127
  define: __UINT16_TYPE__=unsigned short
  define: __UINT16_FMTo__="ho"
  define: __UINT16_FMTu__="hu"
  define: __UINT16_FMTx__="hx"
  define: __UINT16_FMTX__="hX"
  define: __UINT16_C_SUFFIX__=
  define: __UINT16_MAX__=65535
  define: __INT16_MAX__=32767
  define: __UINT32_TYPE__=unsigned int
  define: __UINT32_FMTo__="o"
  define: __UINT32_FMTu__="u"
  define: __UINT32_FMTx__="x"
  define: __UINT32_FMTX__="X"
  define: __UINT32_C_SUFFIX__=U
  define: __UINT32_MAX__=4294967295U
  define: __INT32_MAX__=2147483647
  define: __UINT64_TYPE__=long unsigned int
  define: __UINT64_FMTo__="lo"
  define: __UINT64_FMTu__="lu"
  define: __UINT64_FMTx__="lx"
  define: __UINT64_FMTX__="lX"
  define: __UINT64_C_SUFFIX__=UL
  define: __UINT64_MAX__=18446744073709551615UL
  define: __INT64_MAX__=9223372036854775807L
  define: __INT_LEAST8_TYPE__=signed char
  define: __INT_LEAST8_MAX__=127
  define: __INT_LEAST8_FMTd__="hhd"
  define: __INT_LEAST8_FMTi__="hhi"
  define: __UINT_LEAST8_TYPE__=unsigned char
  define: __UINT_LEAST8_MAX__=255
  define: __UINT_LEAST8_FMTo__="hho"
  define: __UINT_LEAST8_FMTu__="hhu"
  define: __UINT_LEAST8_FMTx__="hhx"
  define: __UINT_LEAST8_FMTX__="hhX"
  define: __INT_LEAST16_TYPE__=short
  define: __INT_LEAST16_MAX__=32767
  define: __INT_LEAST16_FMTd__="hd"
  define: __INT_LEAST16_FMTi__="hi"
  define: __UINT_LEAST16_TYPE__=unsigned short
  define: __UINT_LEAST16_MAX__=65535
  define: __UINT_LEAST16_FMTo__="ho"
  define: __UINT_LEAST16_FMTu__="hu"
  define: __UINT_LEAST16_FMTx__="hx"
  define: __UINT_LEAST16_FMTX__="hX"
  define: __INT_LEAST32_TYPE__=int
  define: __INT_LEAST32_MAX__=2147483647
  define: __INT_LEAST32_FMTd__="d"
  define: __INT_LEAST32_FMTi__="i"
  define: __UINT_LEAST32_TYPE__=unsigned int
  define: __UINT_LEAST32_MAX__=4294967295U
  define: __UINT_LEAST32_FMTo__="o"
  define: __UINT_LEAST32_FMTu__="u"
  define: __UINT_LEAST32_FMTx__="x"
  define: __UINT_LEAST32_FMTX__="X"
  define: __INT_LEAST64_TYPE__=long int
  define: __INT_LEAST64_MAX__=9223372036854775807L
  define: __INT_LEAST64_FMTd__="ld"
  define: __INT_LEAST64_FMTi__="li"
  define: __UINT_LEAST64_TYPE__=long unsigned int
  define: __UINT_LEAST64_MAX__=18446744073709551615UL
  define: __UINT_LEAST64_FMTo__="lo"
  define: __UINT_LEAST64_FMTu__="lu"
  define: __UINT_LEAST64_FMTx__="lx"
  define: __UINT_LEAST64_FMTX__="lX"
  define: __INT_FAST8_TYPE__=signed char
  define: __INT_FAST8_MAX__=127
  define: __INT_FAST8_FMTd__="hhd"
  define: __INT_FAST8_FMTi__="hhi"
  define: __UINT_FAST8_TYPE__=unsigned char
  define: __UINT_FAST8_MAX__=255
  define: __UINT_FAST8_FMTo__="hho"
  define: __UINT_FAST8_FMTu__="hhu"
  define: __UINT_FAST8_FMTx__="hhx"
  define: __UINT_FAST8_FMTX__="hhX"
  define: __INT_FAST16_TYPE__=short
  define: __INT_FAST16_MAX__=32767
  define: __INT_FAST16_FMTd__="hd"
  define: __INT_FAST16_FMTi__="hi"
  define: __UINT_FAST16_TYPE__=unsigned short
  define: __UINT_FAST16_MAX__=65535
  define: __UINT_FAST16_FMTo__="ho"
  define: __UINT_FAST16_FMTu__="hu"
  define: __UINT_FAST16_FMTx__="hx"
  define: __UINT_FAST16_FMTX__="hX"
  define: __INT_FAST32_TYPE__=int
  define: __INT_FAST32_MAX__=2147483647
  define: __INT_FAST32_FMTd__="d"
  define: __INT_FAST32_FMTi__="i"
  define: __UINT_FAST32_TYPE__=unsigned int
  define: __UINT_FAST32_MAX__=4294967295U
  define: __UINT_FAST32_FMTo__="o"
  define: __UINT_FAST32_FMTu__="u"
  define: __UINT_FAST32_FMTx__="x"
  define: __UINT_FAST32_FMTX__="X"
  define: __INT_FAST64_TYPE__=long int
  define: __INT_FAST64_MAX__=9223372036854775807L
  define: __INT_FAST64_FMTd__="ld"
  define: __INT_FAST64_FMTi__="li"
  define: __UINT_FAST64_TYPE__=long unsigned int
  define: __UINT_FAST64_MAX__=18446744073709551615UL
  define: __UINT_FAST64_FMTo__="lo"
  define: __UINT_FAST64_FMTu__="lu"
  define: __UINT_FAST64_FMTx__="lx"
  define: __UINT_FAST64_FMTX__="lX"
  define: __USER_LABEL_PREFIX__=
  define: __FINITE_MATH_ONLY__=0
  define: __GNUC_STDC_INLINE__=1
  define: __GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1
  define: __CLANG_ATOMIC_BOOL_LOCK_FREE=2
  define: __CLANG_ATOMIC_CHAR_LOCK_FREE=2
  define: __CLANG_ATOMIC_CHAR16_T_LOCK_FREE=2
  define: __CLANG_ATOMIC_CHAR32_T_LOCK_FREE=2
  define: __CLANG_ATOMIC_WCHAR_T_LOCK_FREE=2
  define: __CLANG_ATOMIC_SHORT_LOCK_FREE=2
  define: __CLANG_ATOMIC_INT_LOCK_FREE=2
  define: __CLANG_ATOMIC_LONG_LOCK_FREE=2
  define: __CLANG_ATOMIC_LLONG_LOCK_FREE=2
  define: __CLANG_ATOMIC_POINTER_LOCK_FREE=2
  define: __GCC_ATOMIC_BOOL_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR16_T_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR32_T_LOCK_FREE=2
  define: __GCC_ATOMIC_WCHAR_T_LOCK_FREE=2
  define: __GCC_ATOMIC_SHORT_LOCK_FREE=2
  define: __GCC_ATOMIC_INT_LOCK_FREE=2
  define: __GCC_ATOMIC_LONG_LOCK_FREE=2
  define: __GCC_ATOMIC_LLONG_LOCK_FREE=2
  define: __GCC_ATOMIC_POINTER_LOCK_FREE=2
  define: __NO_INLINE__=1
  define: __FLT_EVAL_METHOD__=0
  define: __FLT_RADIX__=2
  define: __DECIMAL_DIG__=__LDBL_DECIMAL_DIG__
  define: __GCC_ASM_FLAG_OUTPUTS__=1
  define: __code_model_small_=1
  define: __amd64__=1
  define: __amd64=1
  define: __x86_64=1
  define: __x86_64__=1
  define: __SEG_GS=1
  define: __SEG_FS=1
  define: __seg_gs=__attribute__((address_space(256)))
  define: __seg_fs=__attribute__((address_space(257)))
  define: __k8=1
  define: __k8__=1
  define: __tune_k8__=1
  define: __REGISTER_PREFIX__=
  define: __NO_MATH_INLINES=1
  define: __FXSR__=1
  define: __SSE2__=1
  define: __SSE2_MATH__=1
  define: __SSE__=1
  define: __SSE_MATH__=1
  define: __MMX__=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1
  define: __SIZEOF_FLOAT128__=16
  define: __unix=1
  define: __unix__=1
  define: __linux=1
  define: __linux__=1
  define: __ELF__=1
  define: __gnu_linux__=1
  define: __FLOAT128__=1
  define: __STDC__=1
  define: __STDC_HOSTED__=1
  define: __STDC_VERSION__=201112L
  define: __STDC_UTF_16__=1
  define: __STDC_UTF_32__=1
  other: --clang
  other: --clang_version=100001
  stdver: c11
  intelliSenseMode: clang-x64
Checking for syntax errors: file:///home/nvmd/Documents/code_test.c
Queueing IntelliSense update for files in translation unit of: /home/nvmd/Documents/code_test.c
  Processing folder (recursive): /usr/include/
  Discovering files: 2919 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
idle loop: reparsing the active document
cpptools/getFoldingRanges: file:///home/nvmd/Documents/code_test.c (id: 4)
Checking for syntax errors: file:///home/nvmd/Documents/code_test.c
Queueing IntelliSense update for files in translation unit of: /home/nvmd/Documents/code_test.c
cpptools/finishUpdateSquiggles
Error squiggle count: 1
terminating child process: 8644
Update IntelliSense time (sec): 0.517
cpptools/getCodeActions: file:///home/nvmd/Documents/code_test.c (id: 5)
textDocument/hover: file:///home/nvmd/Documents/code_test.c (id: 6)
textDocument/completion: file:///home/nvmd/Documents/code_test.c (id: 7)
auto_complete::handle_completion: file:///home/nvmd/Documents/code_test.c (9:11)
Offering completion
completionItem/resolve (id: 8)
textDocument/didChange: file:///home/nvmd/Documents/code_test.c
cpptools/textEditorSelectionChange
textDocument/completion: file:///home/nvmd/Documents/code_test.c (id: 9)
auto_complete::handle_completion: file:///home/nvmd/Documents/code_test.c (9:12)
Offering completion
sending 1 changes to server
cpptools/getFoldingRanges: file:///home/nvmd/Documents/code_test.c (id: 10)
cpptools/getCodeActions: file:///home/nvmd/Documents/code_test.c (id: 11)
cpptools/getDocumentSymbols: file:///home/nvmd/Documents/code_test.c (id: 12)
cpptools/getDocumentSymbols
textDocument/completion: file:///home/nvmd/Documents/code_test.c (id: 13)
auto_complete::handle_completion: file:///home/nvmd/Documents/code_test.c (9:12)
Offering completion
Checking for syntax errors: file:///home/nvmd/Documents/code_test.c
Queueing IntelliSense update for files in translation unit of: /home/nvmd/Documents/code_test.c
  tag parsing file: /home/nvmd/Documents/code_test.c
cpptools/finishUpdateSquiggles
Error squiggle count: 1
Update IntelliSense time (sec): 0.251
Database safe to open
```
</details>

**Comment by sean-mcmanus** [comment] 2020-08-04 19:31
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/2184 (and https://github.com/microsoft/vscode-cpptools/issues/5168 ). You can upvote the VS issue at https://developercommunity.visualstudio.com/content/problem/407956/cc-intellisense-no-member-list-appears-after-typin.html (if you have a Microsoft account).

**Closed as completed by sean-mcmanus** 2020-08-04 19:31 UTC
Labels: duplicate

**Comment by sean-mcmanus** [comment] 2020-09-02 00:52
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 .
