### ISSUE TITLE
C++20 modules intellisense does not work despite using a compile_commands.json

### ISSUE THREAD

**Issue by HappyCerberus** [microsoft/vscode-cpptools#10258] opened 2022-12-09 13:10 UTC
### Environment

- OS and Version: Windows 11 (devcontainer into Ubuntu-based container)
- VS Code Version: 1.74.0
- C/C++ Extension Version: 1.13.7
- Other extensions you installed (and if the issue persists after disabling them):  Bazel, Remote Explorer, Dev Containers
- If using SSH remote, specify OS of remote machine:  devcontainer setup into a ubuntu-based container

I'm using the ll_rules with Bazel to get C++20 modules.

The rules support exporting a compile_commands.json file. This file is correct (as verified by using it to run clang-tidy), however, the plugin doesn't seem to like it and doesn't seem to like and only offers local intellisense (within the file).

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. Clone https://github.com/HappyCerberus/moderncpp-aoc-2022 (and open in the devcontainer)
2. run `bazel build //day09:compile_commands` (this will generate `bazel-bin/day09/compile_commands.json` referenced in the config), note that this builds LLVM on the first run, so it will take a while
3. open `day09/day09.cpp`
4. write `day09::` into main, this should autocomplete the namespace from the imported module, but doesn't

### Expected behavior

Intellisense should work for imported modules.

### Code sample and Logs

```shell
https://github.com/HappyCerberus/moderncpp-aoc-2022
```

**Comment by michelleangela** [comment] 2022-12-09 19:26
@HappyCerberus 

Could you also provide the following two logs to help investigate why the extension is not picking up the imported module:

1. Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
2. Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Comment by HappyCerberus** [comment] 2022-12-09 21:12
```
-------- Diagnostics - 12/9/2022, 9:08:40 PM
Version: 1.13.7
Current Configuration:
{
    "name": "Linux",
    "cppStandard": "c++20",
    "intelliSenseMode": "linux-clang-x64",
    "compilerPath": "",
    "includePath": [
        "${workspaceFolder}/**",
        "/root/.cache/bazel/**"
    ],
    "compileCommands": "/workspaces/moderncpp-aoc-2022/bazel-bin/day09/compile_commands.json",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "/root/.cache/bazel/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /workspaces/moderncpp-aoc-2022/day09/day09.cpp ]:
    /workspaces/moderncpp-aoc-2022/day09/day09.cpp
Translation Unit Configurations:
[ /workspaces/moderncpp-aoc-2022/day09/day09.cpp ]:
    Process ID: 375
    Memory Usage: 103 MB
    Includes:
        /root/.cache/bazel/_bazel_root/b2919da6c250adc1fa9230da3567e523/execroot/_main/bazel-out/k8-fastbuild/bin/external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/clang/staging
        /root/.cache/bazel/_bazel_root/b2919da6c250adc1fa9230da3567e523/external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/libcxx/include
        /root/.cache/bazel/_bazel_root/b2919da6c250adc1fa9230da3567e523/external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-raw/libcxxabi/include
        /root/.cache/bazel/_bazel_root/b2919da6c250adc1fa9230da3567e523/external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-raw/libunwind/include
    Defines:
        _LIBCPP_ENABLE_EXPERIMENTAL
        _LIBCPP_NO_ABI_TAG
    Standard Version: c++20
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=110000
    compile_commands.json entry:
        directory: /root/.cache/bazel/_bazel_root/b2919da6c250adc1fa9230da3567e523/execroot/_main
        file: day09/day09.cpp
        arguments:
            bazel-out/k8-fastbuild-ST-25002c1e1c77/bin/external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/clang/clang++
            -xc++
            day09/day09.cpp
            -o
            bazel-out/k8-fastbuild/bin/day09/day09.o
            --driver-mode=g++
            -fcolor-diagnostics
            -Wdate-time
            -no-canonical-prefixes
            -fdebug-compilation-dir=.
            -fno-coverage-mapping
            -c
            -fPIC
            -nostdlib++
            -nostdinc++
            -nostdlib
            --gcc-toolchain=NONE
            -resource-dir
            bazel-out/k8-fastbuild/bin/external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/clang/staging
            -isystem
            bazel-out/k8-fastbuild/bin/external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/clang/staging
            -isystem
            external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/libcxx/include
            -isystem
            external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/libcxxabi/include
            -isystem
            external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/libunwind/include
            -D
            _LIBCPP_ENABLE_EXPERIMENTAL
            -D
            _LIBCPP_NO_ABI_TAG
            -std=c++20
            -fmodule-file=bazel-out/k8-fastbuild/bin/day09/bridge.pcm
            --target=x86_64-unknown-linux-gnu
        output: bazel-out/k8-fastbuild/bin/day09/day09.o
Total Memory Usage: 103 MB
Browse Paths from compile_commands.json, from workspace folder: /workspaces/moderncpp-aoc-2022
    /root/.cache/bazel/_bazel_root/b2919da6c250adc1fa9230da3567e523/execroot/_main/bazel-out/k8-fastbuild/bin/external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/clang/staging
    /root/.cache/bazel/_bazel_root/b2919da6c250adc1fa9230da3567e523/execroot/_main/external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/libcxx/include
    /root/.cache/bazel/_bazel_root/b2919da6c250adc1fa9230da3567e523/execroot/_main/external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/libcxxabi/include
    /root/.cache/bazel/_bazel_root/b2919da6c250adc1fa9230da3567e523/execroot/_main/external/llvm-project-overlay~16.0.0-bcr.0~llvm_project_overlay~llvm-project/libunwind/include
    day09

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 1050
Number of files parsed: 733
```

```
loggingLevel: Debug
loggingLevel has changed to: Debug
cpptools/didChangeCppProperties
cpptools/getCodeActions: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 49)
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
cpptools/getFoldingRanges: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 50)
cpptools/getCodeActions: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 51)
cpptools/getInlayHints: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 52)
idle loop: reparsing the active document
Checking for syntax errors: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
Queueing IntelliSense update for files in translation unit of: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 47
Update IntelliSense time (sec): 0.368
cpptools/textEditorSelectionChange
cpptools/getSemanticTokens: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 53)
cpptools/getFoldingRanges: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 54)
cpptools/getCodeActions: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 55)
textDocument/didChange: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 56)
cpptools/getSemanticTokens: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 57)
cpptools/getDocumentSymbols: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 58)
cpptools/getDocumentSymbols
cpptools/getInlayHints: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 59)
textDocument/didChange: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
cpptools/textEditorSelectionChange
textDocument/completion: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 60)
auto_complete::handle_completion: file:///workspaces/moderncpp-aoc-2022/day09/day09.cpp (69:6)
Offering completion
sending 1 changes to server
sending 1 changes to server
textDocument/didChange: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
cpptools/textEditorSelectionChange
completionItem/resolve (id: 62)
textDocument/didChange: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
cpptools/textEditorSelectionChange
completionItem/resolve (id: 63)
cpptools/getFoldingRanges: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 64)
cpptools/getCodeActions: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 65)
textDocument/didChange: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
cpptools/textEditorSelectionChange
textDocument/completion: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 66)
auto_complete::handle_completion: file:///workspaces/moderncpp-aoc-2022/day09/day09.cpp (69:9)
Offering completion
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
cpptools/getFoldingRanges: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 67)
textDocument/didChange: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
cpptools/textEditorSelectionChange
textDocument/completion: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 68)
auto_complete::handle_completion: file:///workspaces/moderncpp-aoc-2022/day09/day09.cpp (69:10)
Offering completion
sending 1 changes to server
cpptools/getFoldingRanges: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 69)
cpptools/getCodeActions: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 70)
textDocument/didChange: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
cpptools/textEditorSelectionChange
textDocument/completion: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 71)
auto_complete::handle_completion: file:///workspaces/moderncpp-aoc-2022/day09/day09.cpp (69:11)
textDocument/didChange: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
cpptools/textEditorSelectionChange
textDocument/completion: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 72)
auto_complete::handle_completion: file:///workspaces/moderncpp-aoc-2022/day09/day09.cpp (69:12)
Offering completion
sending 1 changes to server
sending 1 changes to server
cpptools/getFoldingRanges: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 73)
cpptools/getCodeActions: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 74)
textDocument/completion: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 75)
auto_complete::handle_completion: file:///workspaces/moderncpp-aoc-2022/day09/day09.cpp (69:12)
Offering completion
cpptools/getDocumentSymbols: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 76)
Request canceled: 58
cpptools/getDocumentSymbols
cpptools/getInlayHints: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 77)
Checking for syntax errors: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
Queueing IntelliSense update for files in translation unit of: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
  tag parsing file: /workspaces/moderncpp-aoc-2022/day09/day09.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 49
Update IntelliSense time (sec): 5.424
cpptools/getFoldingRanges: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 78)
cpptools/getCodeActions: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 79)
cpptools/getSemanticTokens: /workspaces/moderncpp-aoc-2022/day09/day09.cpp (id: 80)
```

**Comment by sean-mcmanus** [comment] 2022-12-15 22:40
This appears to be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6302 .

**Closed as not planned by sean-mcmanus** 2022-12-15 22:40 UTC
Labels: duplicate, Language Service, Feature Request, Feature: Configuration, modules
