### ISSUE TITLE
C/C++ Code hints often disappear suddenly

### ISSUE THREAD

**Issue by fm123456** [microsoft/vscode-cpptools#5629] opened 2020-06-10 03:23 UTC
Code hints often disappear suddenly, and it will take effect only after restarting vscode. What is going on, can you help me?

**Comment by Nathaniel7687** [comment] 2020-06-10 04:17
After cpptools updated to the version 0.28.3, I cannot use all of the features about cpptools. Also, when I run vscode, the process as shown in the picture below continues and does not end.
![image](https://user-images.githubusercontent.com/2202291/84226355-82327400-ab1c-11ea-95ab-bb2fa5213954.png)

**Comment by sean-mcmanus** [comment] 2020-06-10 04:34
@fm123456 cpptools-srv might be crashing. Do you see any "failed" messages in the C/C++ Output logs?

@Nathaniel7687 The download has some issue. Can you try installing the offline vsix at https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.3 ?

**Comment by Nathaniel7687** [comment] 2020-06-10 04:47
@sean-mcmanus Even if, the vscode installed, the offline vsix cannot install the extension with the below error.

FYI, my vscode version is 1.45.1.

![image](https://user-images.githubusercontent.com/2202291/84227934-a6904f80-ab20-11ea-8a50-4d29e94faa0a.png)
[View Install Log]

>6/10/2020 1:28:03 PM - Microsoft VSIX Installer
6/10/2020 1:28:03 PM - -------------------------------------------
6/10/2020 1:28:03 PM - Initializing Install...
6/10/2020 1:28:04 PM - Extension Details...
6/10/2020 1:28:04 PM - 	Identifier      : cpptools
6/10/2020 1:28:04 PM - 	Name            : C/C++
6/10/2020 1:28:04 PM - 	Author          : ms-vscode
6/10/2020 1:28:04 PM - 	Version         : 0.28.3
6/10/2020 1:28:04 PM - 	Description     : C/C++ IntelliSense, debugging, and code browsing.
6/10/2020 1:28:04 PM - 	Locale          : en-US
6/10/2020 1:28:04 PM - 	MoreInfoURL     : 
6/10/2020 1:28:04 PM - 	InstalledByMSI  : False
6/10/2020 1:28:04 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
6/10/2020 1:28:04 PM - 
6/10/2020 1:28:04 PM - 	Supported Products : 
6/10/2020 1:28:04 PM - 		Microsoft.VisualStudio.Code
6/10/2020 1:28:04 PM - 			Version : 
6/10/2020 1:28:04 PM - 
6/10/2020 1:28:04 PM - 	References      : 
6/10/2020 1:28:04 PM - 
6/10/2020 1:28:04 PM - Searching for applicable products...
6/10/2020 1:28:04 PM - Found installed product - Microsoft Visual Studio Professional 2013
6/10/2020 1:28:04 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
6/10/2020 1:28:04 PM - Found installed product - Global Location
6/10/2020 1:28:04 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by sean-mcmanus** [comment] 2020-06-10 04:55
@Nathaniel7687 Don't double-click it -- that causes Windows to try to use the default .vsix handler of VS and not VS Code.

## Instructions
To use the "offline" .vsix (that doesn't download OS-based dependencies on extension activation), download the .vsix that matches your OS and run the "Install from VSIX" command in VS Code.

**Comment by Nathaniel7687** [comment] 2020-06-10 06:40
@sean-mcmanus Thanks for your guidance. The problem is solved.

**Comment by fm123456** [comment] 2020-06-11 08:27
> @fm123456 cpptools-srv might be crashing. Do you see any "failed" messages in the C/C++ Output logs?
> 
> @Nathaniel7687 The download has some issue. Can you try installing the offline vsix at https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.3 ?

@sean-mcmanus hi, sean-mcmanus.  How to see if cpptools-srv has crashed. the cpptools-srv is still running when code hint has uneffect 
![image](https://user-images.githubusercontent.com/10722399/84362764-54266000-ac00-11ea-8827-b1e6ca7aedf8.png)

It seems that cpptools-srv has crashed，but then restarted

**Comment by sean-mcmanus** [comment] 2020-06-11 17:16
@fm123456 Yeah, cpptools-srv will usually restart after a crash. Our next release will have some crash fixes for cpptools-srv. You could attach a debugger to cpptools-srv before the crash to get a crash call stack if you want us to identify which crash is occurring.

**Comment by fm123456** [comment] 2020-06-17 06:54
@sean-mcmanus i find some  cpptools-srv corefile, call stack are shown in the picture below
![image](https://user-images.githubusercontent.com/10722399/84865181-60039d80-b0aa-11ea-99bb-121fa09d7c64.png)
Hope it helps you~~

**Comment by sean-mcmanus** [comment] 2020-06-17 17:30
@fm123456 This crash has already been fixed in our pending 0.29.0-insiders. This is the 1st user report of the crash though.

**Comment by fm123456** [comment] 2020-06-18 02:29
@sean-mcmanus thanks

**Closed as completed** 2020-06-18 02:29 UTC
Labels: bug, Language Service, fixed, reliability

**Comment by sean-mcmanus** [comment] 2020-06-25 01:48
This crash should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.29.0-insiders .
