### ISSUE TITLE
Outline: wrong display when has '#if 0' in code

### ISSUE THREAD

**Issue by vipfrog** [microsoft/vscode-cpptools#11800] opened 2023-12-22 02:55 UTC
### Environment

- OS and Version: Win 10 Enterprise
- VS Code Version: 1.72.2
- C/C++ Extension Version: v1.91.1
- If using SSH remote, specify OS of remote machine: NO SSH

### Bug Summary and Steps to Reproduce

Bug Summary:
In my company, we allow to use '#if 0' and '#endif' to disable some codes, cause it allows to has other '#if 0...endif', '/\*...\*/', '//' in it, which means it's very convenient and flexible. So it's used very frequently. But I found when some code file has this, the outline maybe wrong. Fortunately, the hierarchy tree can still work.

Please just see the demo I've made in the picture. 
Hope for reply and fix. Apologize for poor English.

![微信图片_20231222104425](https://github.com/microsoft/vscode-cpptools/assets/115419535/6e52fde7-a48f-4890-830e-003a85fd966c)

### Configuration and Logs

```shell
not important
```

**Comment by sean-mcmanus** [comment] 2023-12-22 21:32
This is "by design" or "won't fix". Our symbol parser parses both sides of `#if` directives.

**Closed as not planned by sean-mcmanus** 2023-12-22 21:32 UTC
Labels: by design

**Comment by vipfrog** [comment] 2023-12-25 01:49
> This is "by design" or "won't fix". Our symbol parser parses both sides of `#if` directives.

Thank you for explanation! If 0/1 or true/false can be parsed only on one side, will be nicer :)
