### ISSUE TITLE
(lldb) without `-exec`?

### ISSUE THREAD

**Issue by weshardee** [microsoft/vscode-cpptools#2044] opened 2018-05-26 19:22 UTC
Is there a way to configure the launch.json to get just the (lldb) prompt in the debug console?

I see that once I've launched the debugger, I can pass commands to lldb in the debug console by prefixing them with `-exec`, but as a new user, I found this confusing at first and it's still a bit of a hassle when trying to learn and experiment with lldb commands.

**Comment by pieandcakes** [comment] 2018-05-29 22:11
@weshardee There are two reasons why that isn't possible: 
1) the Debug console was designed by VS Code to allow simple commands like evaluating variables. We added the `-exec` option so that users could also pass commands to the underlying debugger.
2) the underlying debugger is `lldb-mi` and not standard `lldb`. It allows some `lldb` commands but mainly expects [`mi`](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html) style commands inherited from `gdb`. This allows the debugger to be driven via input/output using a different command structure, so there is no `(lldb)` prompt for you to access.

**Comment by WardenGnaw** [comment] 2018-09-20 20:53
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/106

**Closed as completed by WardenGnaw** 2018-09-20 20:53 UTC
Labels: duplicate, debugger, external
