### ISSUE TITLE
Bug: Command `C/C++: Select IntelliSense Configuration... -> Use g**`

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-cpptools#12705] opened 2024-09-12 12:35 UTC
### Environment

- OS and Version: Windows 11 23H2
- VS Code Version: 1.92.2
- C/C++ Extension Version: v1.21.6
- If using SSH remote, specify OS of remote machine: wsl (Ubuntu 20.04)

### Bug Summary and Steps to Reproduce

Bug Summary:
If you select a compiler via `C/C++: Select IntelliSense Configuration... -> Use g**` one can notice that the updated `compilerPath` is not updated until the second time you select the same command again. It then changes `.vscode/c_cpp_properties.json` to the compiler you selected in the n-1 try.

https://github.com/user-attachments/assets/b91eeb61-edd3-4ef4-a0b9-d5738822dfda

Steps to reproduce:
1. Keep the `.vscode/c_cpp_properties.json` file open while changing the compiler via the command ``C/C++: Select IntelliSense Configuration....`
2. Notice how it does not select what you chose.

Expected behavior:
It should format the file and add a new line at EOF.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c99",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        },
        {
            "name": "CMake",
            "compileCommands": "${config:cmake.buildDirectory}/compile_commands.json",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

```
-------- Diagnostics - 9/4/2024, 1:10:29 PM
Version: 1.21.6
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/tobias/code/c-test/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c99",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "linux-gcc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "/usr/bin/gcc",
    "configurationProviderInCppPropertiesJson": "ms-vscode.cmake-tools",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "/home/tobias/code/c-test/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/home/tobias/code/c-test/src"
    ],
    "compilerPath": "/usr/bin/gcc",
    "compilerArgs": [],
    "compilerFragments": [
        "-g"
    ]
}
cpptools version (native): 1.21.6.0
Translation Unit Mappings:
[ /home/tobias/code/c-test/src/main.c - source TU]:
Translation Unit Configurations:
[ /home/tobias/code/c-test/src/main.c ]:
    Process ID: 30660
    Memory Usage: 15 MB
    Compiler Path: /usr/bin/gcc
    Includes:
    System Includes:
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=90400
Total Memory Usage: 15 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 4908
```

**Comment by sean-mcmanus** [comment] 2024-09-12 15:26
@thernstig I believe that's "by design". The first time Select IntelliSense Configuration is used with gcc/g++ it will set the C_Cpp.default.compilerPath setting instead of creating/modifying a c_cpp_properties.json. If both C_Cpp.default.compilerPath and compilerPath in c_cpp_properties.json are set, then it will change the compilerPath in c_cpp_properties.json.

Did you want to use this issue to track formatting the c_cpp_properties.json and/or adding an EOL at the end? Does manually formatting have an affect? I think that behavior might be controlled by a json formatter or other VS Code setttings?

**Comment by thernstig** [comment] 2024-09-13 06:13
@sean-mcmanus but this happens if I change the `C/C++: Select IntelliSense Configuration` multiple times in a row, it always changes to the n-1. Did you see the video I recorded?

**Comment by bobbrow** [comment] 2024-10-24 00:41
Thanks for the ping. I have a fix for this in PR.

**Closed as completed** 2024-10-24 20:42 UTC
Labels: bug, Language Service, fixed, Feature: Configuration

**Comment by sean-mcmanus** [comment] 2024-10-30 01:35
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.23.0
