### ISSUE TITLE
Designated initializers not working on file scope

### ISSUE THREAD

**Issue by nunojsa** [microsoft/vscode-cpptools#6316] opened 2020-10-14 11:49 UTC
**Describe the bug**

When defining a struct at file scope, the Designated initializers do not work (often). Sometimes and for some structs they actually work but for some other types they don't. However, for the structs that they do not work, they will work if we define the variable inside a function. I've created a very simple example where I could experience this issue (screenshots below).

- OS and Version: Ubuntu Mate 20.04
- VS Code Version: 1.50
- C/C++ Extension Version: 1.1.0-insiders

**Expected behavior**
Structs members to appear in the auto complete list

**Screenshots**
![image](https://user-images.githubusercontent.com/28741857/95984718-eb582a00-0e23-11eb-9fa4-c6f729494191.png)

![image](https://user-images.githubusercontent.com/28741857/95984765-fca13680-0e23-11eb-92cf-d663b14a963c.png)

**Comment by Colengms** [comment] 2020-10-15 00:28
Hi @nunojsa .  Thanks for reporting this.  I believe this is the same issue as: https://github.com/microsoft/vscode-cpptools/issues/4966

**Comment by sean-mcmanus** [comment] 2020-10-15 22:15
The bug repros with VS (i.e. due to our shared code) and has been reported at https://developercommunity.visualstudio.com/content/problem/1223052/c-intellisense-doesnt-work-for-designated-initiali.html .

**Comment by jiladahe1997** [comment] 2020-12-14 14:40
Same problem here.

**Comment by mbBRCM** [comment] 2021-04-07 16:00
I am having the same issue

**Comment by alexanderkutin** [comment] 2021-06-29 15:23
The issue is still here. However, for some structs at a global scope autocomplete might work.

**Comment by nunojsa** [comment] 2021-06-30 07:38
Well, I believe it's still not marked as fixed.. Maybe just upvote it here:

https://developercommunity.visualstudio.com/content/problem/1223052/c-intellisense-doesnt-work-for-designated-initiali.html

so that we have better chances for it being fixed soom...

**Comment by Colengms** [comment] 2021-08-12 23:48
This should be addressed in 1.6.0-insiders.

**Closed as completed by Colengms** 2021-08-12 23:48 UTC
Labels: bug, Language Service, fixed, Visual Studio, Feature: Auto-complete
