### ISSUE TITLE
Intellisense is completely not working inside a method definition outside a template class defined in a header file which is included in this file..

### ISSUE THREAD

**Issue by yvvt0379** [microsoft/vscode-cpptools#9725] opened 2022-08-12 08:10 UTC
### Environment

- OS and Version: Windows 11 21H2
- VS Code Version: 1.70.0
- C/C++ Extension Version: v1.11.5
- Other extensions you installed (and if the issue persists after disabling them):  Irrelevant, and this issue **persists** after disabling them.
- If using SSH remote, specify OS of remote machine:  none
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
Intellisense is completely not working inside a method definition outside a template class defined in a header file which is included in this file..

### Bug Summary and Steps to Reproduce

Bug Summary:
Intellisense is completely not working inside a method definition outside a class defined in a header file which is included in this file..

Steps to reproduce:
1. Create a C++ header file and define a template class with a public method declaration inside it, like this:
```cpp
template <int n>
class C
{
public:
    int f();
};
```
2. Create a C++ source file, include the header file (and a random header file), and define the method, like this:
```cpp
#include "<The filename of the header file I mentioned above>"

#include <vector>

template <int n>
int C<n>::f()
{
    std::vector<int> vec(n);
    1 +;
}
```

### Expected behavior

1. When I mouse over `vec`, should show a popup that says `std::vector<int> vec`
2. Should squiggle below `;` after `1 +`, and when I mouse over it, should show a popup that says `Expected expression`

### Code sample and Logs

```shell
- Code Sample
See above.
- Configurations in `c_cpp_properties.json`

{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "D:\\mingw\\bin\\g++.exe",
            "cStandard": "c17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "windows-gcc-x86",
            "compilerArgs": [],
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}

- Logs from running `C/C++: Log Diagnostics`
```
-------- Diagnostics - 2022/8/12 16:05:28
Version: 1.11.5
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "D:\\mingw\\bin\\g++.exe",
    "cStandard": "c17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "windows-gcc-x86",
    "compilerArgs": [],
    "configurationProvider": "ms-vscode.makefile-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": []
}
Translation Unit Mappings:
[ C:\Users\Admin\vscode\1.cpp ]:
    C:\Users\Admin\vscode\1.cpp
    C:\Users\Admin\vscode\1.hpp *
Translation Unit Configurations:
[ C:\Users\Admin\vscode\1.cpp ]:
    Process ID: 5688
    Memory Usage: 38 MB
    Compiler Path: D:\mingw\bin\g++.exe
    Includes:
        D:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE\C++
        D:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE\C++\MINGW32
        D:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE\C++\BACKWARD
        D:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE
        D:\MINGW\INCLUDE
        D:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE-FIXED
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++14
    IntelliSense Mode: windows-gcc-x86
    Other Flags:
        --g++
        --gnu_version=90200
Total Memory Usage: 38 MB
```
- Logs from the language server logging
```
cpptools/getCodeActions: C:\Users\Admin\vscode\1.hpp (id: 278)
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: C:\Users\Admin\vscode\1.hpp
cpptools/getInlayHints: C:\Users\Admin\vscode\1.hpp (id: 279)
cpptools/getFoldingRanges: C:\Users\Admin\vscode\1.hpp (id: 280)
cpptools/getCodeActions: C:\Users\Admin\vscode\1.hpp (id: 281)
空闲环路: 重新分析活动文档
正在检查语法错误: C:\Users\Admin\vscode\1.hpp
正在为以下项的翻译单元中文件的 IntelliSense 更新进行排队: C:\Users\Admin\vscode\1.cpp
cpptools/finishUpdateSquiggles
错误波形曲线计数: 0
更新 IntelliSense 时间(秒): 0.261
cpptools/getSemanticTokens: C:\Users\Admin\vscode\1.hpp (id: 282)
cpptools/getFoldingRanges: C:\Users\Admin\vscode\1.hpp (id: 283)
cpptools/getCodeActions: C:\Users\Admin\vscode\1.cpp (id: 284)
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: C:\Users\Admin\vscode\1.cpp
cpptools/getInlayHints: C:\Users\Admin\vscode\1.cpp (id: 285)
空闲环路: 重新分析活动文档
正在检查语法错误: C:\Users\Admin\vscode\1.cpp
正在为以下项的翻译单元中文件的 IntelliSense 更新进行排队: C:\Users\Admin\vscode\1.cpp
cpptools/getFoldingRanges: C:\Users\Admin\vscode\1.cpp (id: 286)
cpptools/getCodeActions: C:\Users\Admin\vscode\1.cpp (id: 287)
cpptools/finishUpdateSquiggles
错误波形曲线计数: 0
错误波形曲线计数: 0
更新 IntelliSense 时间(秒): 0.256
cpptools/getSemanticTokens: C:\Users\Admin\vscode\1.cpp (id: 288)
cpptools/getSemanticTokens: C:\Users\Admin\vscode\1.hpp (id: 289)
cpptools/getFoldingRanges: C:\Users\Admin\vscode\1.cpp (id: 290)
```
```

**Comment by sean-mcmanus** [comment] 2022-08-12 20:22
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/1946 .

You can somewhat workaround this by adding an explicit instantiation definition like
```cpp
template <>
int C<1>::f()
{}
```
![image](https://user-images.githubusercontent.com/19859882/184436673-88d38e22-b192-4e3c-a03b-8e98555e6df5.png)

However, you'd have to move the `#include <vector>` before template definition to get the hover to work or you'll hit bug https://developercommunity.visualstudio.com/t/C-template-IntelliSense-hover-doesnt/10119399

**Closed as not planned** 2022-08-15 18:02 UTC
Labels: duplicate
