### ISSUE TITLE
Cannot open source file of std headers

### ISSUE THREAD

**Issue by fexolm** [microsoft/vscode-cpptools#1520] opened 2018-02-03 18:32 UTC
* Arch linux
* VS Code OSS 1.19.3
* C/C++ extension version 0.14.6
* CMake

My settings: 
```{
    "configurations": [
        {
            "name": "null",
            "includePath": [
                "/usr/include/c++/7.2.1",
                "/usr/include/c++/7.2.1/x86_64-pc-linux-gnu",
                "/usr/include/c++/7.2.1/backward",
                "/usr/include",
                "/usr/local/include",
                "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/include-fixed",
                "/usr/include/linux",
                "${workspaceRoot}"
            ],
            "defines": [],
            "browse": {
                "path": [
                    "/usr/include/c++/7.2.1",
                    "/usr/include/c++/7.2.1/x86_64-pc-linux-gnu",
                    "/usr/include/c++/7.2.1/backward",
                    "/usr/include",
                    "/usr/local/include",
                    "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/include-fixed",
                    "/usr/include/linux",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "intelliSenseMode":     "clang-x64",
            "compileCommands": "${workspaceRoot}/compile_commands.json"
        }
    ],
    "version": 3
}
```
Go to defenition for headers finds 5 results.  

I have  read #1041 but it didn't help.

**Comment by sean-mcmanus** [comment] 2018-02-05 09:20
In your compile_commands.json what is the 1st part of the "command" -- we query the 1st part as if it's the compiler to get the defaults.

**Comment by fexolm** [comment] 2018-02-05 15:17
@sean-mcmanus, `/usr/bin/c++`.
Also, there is no such problem with project sources.

**Comment by bobbrow** [comment] 2018-02-05 17:55
Possibly a duplicate of #1350?  It seems our parser is having trouble with 7.2.1.  It could be a result of missing defines and @sean-mcmanus is working on that right now.

@fexolm can you specify which source files are failing to open?

**Comment by fexolm** [comment] 2018-02-05 19:55
@bobbrow, it doesn't look absolutely same for me. In my situation, it reproduces on every std header (I tried vector, map, iostream, unordered_map, unordered_set and some others). 
Here is some screenshots:

It says that it can't find headers
![gscreenshot_2018-02-05-224600](https://user-images.githubusercontent.com/14443401/35825361-a7420024-0ac6-11e8-9b73-cf37590415e7.png)
But it can.
![gscreenshot_2018-02-05-224737](https://user-images.githubusercontent.com/14443401/35825360-a70fc244-0ac6-11e8-8d92-649ceb80430f.png)
Also, if I go to some of that headers, problem doesn't reproduce there.
![gscreenshot_2018-02-05-224834](https://user-images.githubusercontent.com/14443401/35825359-a6c9d66c-0ac6-11e8-8eb8-d6937599d721.png)

**Comment by bobbrow** [comment] 2018-05-22 03:26
This issue should be fixed in the latest version of the extension if you add `"compilerPath": "/usr/bin/c++"` to your configurations in **c_cpp_properties.json** and remove the system includes from `includePath` and `browse.path`.  Please reopen if that doesn't work for you.

**Closed as completed by bobbrow** 2018-05-22 03:26 UTC
Labels: more info needed

**Comment by yiakwy** [comment] 2018-12-27 03:56
@fexolm @sean-mcmanus @bobbrow 

see problem https://github.com/vector-of-bool/vscode-cmake-tools/issues/618 and https://github.com/Microsoft/vscode/issues/65719.

I noticed that you are manualy include paths. This should not happen if you configure your system using CMake.

In Mac Xcode, to integrate a CMake project, one can write down scirpts

> cmake ${args} -G xcode -H"${ROOT}" -B"${ROOT}/xcode/"

Is it possible to do it in vscode ?

> cmake ${args} -G code -H"${ROOT}" -B"${ROOT}/vscode/"

Manually including paths for a cmake project is somehow ridiculous from my personal experiences.

Besides tasks provided by vscode, we take more care of files auto indexing. That always broken in vscode because vscode cannot correctly recognize makes files generated by cmake.

Could anyone help resolving the problem?
