### ISSUE TITLE
VScode reports errors when including Linux headers in Windows.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#6212] opened 2020-09-25 14:26 UTC
**Type: LanguageService**

VScode reports errors when including Linux headers in Windows.

Can VSCode be compatible with Linux headers in Windows?

![Image](https://preview.yozodcs.com/fcscloud/view/preview/AX9iK43lFaRNKddn5_HTiJMFT8Fg8FxJXOwfbnquseV1gPhgh1OcIMXxf6KGkcpfU97cc_0goBGGubcDe11fuPGAtwGAOFCC8PlDMaYpTYcm1IKnqDuie9MNqXzLHAtBo81yQRH1WrXi_Qc3WTu-UaNonQiQisQsJEVD-gUtCdWI1evGAdfsQ8JWyu9pk15paeKfLf5yK8_tc91lg8rgb_cewYv2Jy0p5NXWaPN6zt75Hca4nX7gp4XQbnFHi8o3mUVofu01uvI-UsgNvb4-hs93YtRDWsK2oYfX0jC-yEqUoSWhAmha-yakkpTlmJQaL0L2lNDnQFo=//%E6%8D%95%E8%8E%B7.files/file0001.PNG)

**Comment by michelleangela** [comment] 2020-09-25 18:48
@zrzjohn 

Could you share the error message from the extension? Also, could you provide the logs from running the command `C/C++: Log Diagnostics`?

**Comment by bobbrow** [comment] 2020-09-25 23:15
Did you copy the linux headers over to Windows?  If the files are not there, then our extension won't be able to parse them.

If you want to do linux development on Windows, we recommend using the Remote-WSL extension or Remote-SSH to connect to a live linux session.

**Comment by michelleangela** [comment] 2020-12-09 19:22
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 19:22 UTC
Labels: Language Service, more info needed
