### ISSUE TITLE
Build task never completes with terminal in editor area

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-cpptools#8183] opened 2021-09-23 16:29 UTC
Bug type: General

**Describe the bug**
- OS and Version: Windows 10 (Windows_NT x64 10.0.19043)
- VS Code Version: 1.61.0-insider (user setup)
- C/C++ Extension Version: v1.6.0
- Other extensions you installed (and if the issue persists after disabling them): Problem persists after disabling eslint and vscode-test-explorer.

**To Reproduce**
1. Clone https://github.com/rzhao271/named-pipe-sample (the code is specific to Windows).
2. In the settings editor, set `terminal.defaultLocation` to `editor`.
3. Run the configured build task.
4. :bug: The task terminal opens up in the editor area, but the task never finishes.

Note that the build task works fine when `terminal.defaultLocation` is set to `view`.

**Comment by sean-mcmanus** [comment] 2021-09-27 17:30
@Colengms @WardenGnaw @elahehrashedi @michelleangela Has anyone reproed this yet? It sounds like it may be a VS Code bug, although it could be caused by something with our cppbuild task.

**Comment by Colengms** [comment] 2021-09-28 20:03
This looks like a consequence of using `${file}` in the build task.  The terminal is opened in the editor before the `${file}` variable is resolved, resulting in:

```
  ERR Variable ${file} can not be resolved. Please open an editor.: Error: Variable ${file} can not be resolved. Please open an editor.
    at r (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1278:30795)
    at u.evaluateSingleVariable (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1278:32307)
    at vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1278:30401
    at String.replace (<anonymous>)
    at u.resolveString (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1278:30317)
    at u.recursiveResolve (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1278:30022)
    at vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1278:30084
    at Array.map (<anonymous>)
    at u.recursiveResolve (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1278:30072)
    at vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1278:30239
    at Array.forEach (<anonymous>)
    at u.recursiveResolve (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1278:30179)
    at u.resolveAnyBase (vscode-file://vscode-app/c:/Users/colen/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1278:29366)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Use of `${file}` is inherent to the feature `Build and Debug Active File`, as it identifies the active file.  Perhaps this could be addressed if VS Code were to evaluate variables in the task prior to opening the terminal in the editor.

**Comment by Colengms** [comment] 2021-10-05 22:45
Hi @rzhao271 .  This looks like an issue with this feature in VS Code.  It appears to incorrectly resolve `${file}` when using a terminal opened in the editor.  I'd suggest opening a bug in [the VS Code repo](https://github.com/microsoft/vscode/issues).  Closing this as external.

**Closed as completed by Colengms** 2021-10-05 22:45 UTC
Labels: Visual Studio Code
