### ISSUE TITLE
Formatting falied

### ISSUE THREAD

**Issue by viordash** [microsoft/vscode-cpptools#11396] opened 2023-09-01 13:15 UTC
### Environment

- OS and Version: Ubuntu 20.04 LTS 64-bit
- VS Code Version: 1.81.1
- C/C++ Extension Version: v1.17.5

### Bug Summary and Steps to Reproduce

Bug Summary: Cannot c++ code formating. The output window does not show any errors, only
```
Formatting failed:
/home/user/.vscode/extensions/ms-vscode.cpptools-1.17.5-linux-x64/bin/../LLVM/bin/clang-format -style=file -fallback-style=LLVM --Wno-error=unknown -assume-filename=/home/user/projects/tests/memset_tests.cpp
```
standalone execution of the command  `/home/user/.vscode/extensions/ms-vscode.cpptools-1.17.5-linux-x64/bin/../LLVM/bin/clang-format --style=file --fallback-style=LLVM --Wno-error=unknown --assume-filename=/home/user/projects/tests/memset_tests.cpp`
does nothing, the program freezes and does not output anything

### Configuration and Logs

```shell
-
```

### Other Extensions

-

### Additional context

-

**Comment by viordash** [comment] 2023-09-01 13:16
v1.17.5 works successfully

**Comment by rickyjames35** [comment] 2023-09-02 18:31
Can confirm. I'm having the same problem. `ms-vscode.cpptools@1.17.4` fixes it.

**Comment by rickyjames35** [comment] 2023-09-02 18:33
This looks related. https://github.com/microsoft/vscode-cpptools/issues/11384

**Comment by michelleangela** [comment] 2023-09-05 22:14
Closing as duplicate of https://github.com/microsoft/vscode-cpptools/issues/11384.

**Closed as completed by michelleangela** 2023-09-05 22:14 UTC
Labels: bug, duplicate, Language Service, Feature: Code Formatting
