### ISSUE TITLE
std::variant usage causes error squiggles

### ISSUE THREAD

**Issue by mmatrosov** [microsoft/vscode-cpptools#6910] opened 2021-02-05 12:00 UTC
**Type: LanguageService**
IntellliSense

**Describe the bug**
- OS and Version: Ubuntu 20.04 
- VS Code Version: 
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.0-38-generic snap
```
- C/C++ Extension Version: 1.2.0
- Other extensions you installed (and if the issue persists after disabling them):
![image](https://user-images.githubusercontent.com/3617951/107030106-2b6f5e00-67c1-11eb-82a7-26fca9d0c589.png)
- Does this issue involve using SSH remote to run the extension on a remote machine?: yes

**Steps to reproduce**
Use the following `c_cpp_properties.json`:
```
{
  "configurations": [
    {
      "name": "Linux",
      "compilerPath": "clang++",
      "cStandard": "c17",
      "cppStandard": "c++20",
      "intelliSenseMode": "clang-x64",
      "configurationProvider": "ms-vscode.cmake-tools",
      "compileCommands": "${workspaceFolder}/build_release/compile_commands.json"
    }
  ],
  "version": 4
}
```

Create a C++ file with this code:
```
#include <variant>

void foo() {
  std::variant<int, double> var = 100;
}
```

"100" has red squiggles under it with the following error message:

>no suitable constructor exists to convert from "int" to "std::variant<int, double>"C/C++(415)

**Expected behavior**
No errors.

<details>
  <summary><strong>Logs</strong></summary>

```
cpptools/didChangeCppProperties
$/setTraceNotification
cpptools/getCodeActions: file:///home/mmatrosov/dev/moo/src/gg/temp.cpp (id: 1555)
cpptools/activeDocumentChange: file:///home/mmatrosov/dev/moo/src/gg/temp.cpp
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///home/mmatrosov/dev/moo/src/gg/temp.cpp (id: 1556)
cpptools/getCodeActions: file:///home/mmatrosov/dev/moo/src/gg/temp.cpp (id: 1557)
idle loop: reparsing the active document
Checking for syntax errors: file:///home/mmatrosov/dev/moo/src/gg/temp.cpp
Queueing IntelliSense update for files in translation unit of: /home/mmatrosov/dev/moo/src/gg/temp.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 1
cpptools/getSemanticTokens: file:///home/mmatrosov/dev/moo/src/gg/temp.cpp (id: 1558)
cpptools/getFoldingRanges: file:///home/mmatrosov/dev/moo/src/gg/temp.cpp (id: 1559)
cpptools/getCodeActions: file:///home/mmatrosov/dev/moo/src/gg/temp.cpp (id: 1560)
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/3617951/107031194-d6344c00-67c2-11eb-9860-e358ba121c68.png)

**Additional context**
See also https://github.com/microsoft/vscode-cpptools/issues/4636

**Comment by sean-mcmanus** [comment] 2021-02-05 18:49
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6623

**Closed as completed by sean-mcmanus** 2021-02-05 18:49 UTC
Labels: duplicate

**Comment by sean-mcmanus** [comment] 2021-03-19 20:13
This is also fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders
