### ISSUE TITLE
Jump to my own already opened source file first on crash in debugger

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-cpptools#8090] opened 2021-09-02 03:18 UTC
Type: Feature Request
 
 Now when I debug the program crashes and it opens some file I' ve never touched like `/usr/src/debug/glibc-2.17-c758a686/nptl/sysdeps/unix/sysv/linux/raise.c` first. I have to open the left long call stack to scroll and select my own file to see which line I wrote might have problem (which usually is already opened inside the window before launch of program).  

Since clicking on the call stack finally could open my own source file. I guess it' s possible to make the extension work for me to iterate the crashed call stack and find the most relevent file in priority like: `Currently Opened/Viewd File > Files in user Home folder > Files in system path`. And show me the file with highest likelihood of the bug for me, which I believe would save a lot of time navigating through stack files.

**Comment by WardenGnaw** [comment] 2021-09-02 21:30
`raise.c` is the source where exceptions are actually thrown. 

This is the "Just my Code" feature. 

Duplicate of: https://github.com/microsoft/vscode-cpptools/issues/5763

**Closed as completed by WardenGnaw** 2021-09-02 21:30 UTC
Labels: duplicate, debugger
