### ISSUE TITLE
IntelliSense failing for smart pointers of template classes

### ISSUE THREAD

**Issue by Rishi-V** [microsoft/vscode-cpptools#9429] opened 2022-06-08 22:25 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Ubuntu 20.04.4 LTS (Focal)
- VS Code Version: 1.67.2
- C/C++ Extension Version: v1.9.8
- A clear and concise description of what the bug is: IntelliSense fails when using smart points of template classes. Autocomplete with `->` does not show functions that are accessible via `->` and instead only shows smart pointer functions (e.g. `get()`) which is invalid/leads to compile errors. Additionally going to function definitions does not work at all.

**To reproduce**
```
template <class T>
class ABC {
    ABC();
    void doSomething();
};

template <class T>
void aFunc() {
    ABC<T> a;
    a.{CURSOR}doSomething(); // Autocomplete works here
    a.doSomething{CtrlClickOnFunction}(); // Going to function definition works here

    ABC<T> *b = new ABC<T>();
    b->{CURSOR}doSomething(); // Autocomplete works here
    b->doSomething{CtrlClickOnFunction}(); // Going to definition works here

    //// IntelliSense fails below
    shared_ptr<ABC<T>> c;
    c->{CURSOR}doSomething(); // Autocomplete just shows options related to shared_ptr<> class 
    //                           even though those functions are for the object (c.) and not pointer (c->)
    c.get()->{CURSOR}doSomething(); // Autocomplete shows no options
    c->doSomething{CtrlClickOnFunction}(); // Going to definition fails
    c.get()->doSomething{CtrlClickOnFunction}(); // Going to definition also fails

    //// However, a specified instantiation of it works, e.g. specifying float
    shared_ptr<ABC<float>> d;
    d->{CURSOR}doSomething(); // Autocomplete works here
    d.get()->{CURSOR}doSomething(); // Autocomplete works here
    d->doSomething{CtrlClickOnFunction}(); // Going to definition works here
    d.get()->doSomething{CtrlClickOnFunction}(); // Going to definition works here
    

    // We get identical success and failure behavior if we use unique_ptr as well
}
```

**Expected behavior**
IntelliSense should be able to work with smart pointers of templates similar to the raw pointer version or the specified template version. Concretely `->` should show functions related to the argument template class (e.g. showing `doSomething()` of `ABC<T>` in the example) and not smart pointer functions. Going to function definitions should work as well.

**Additional context**
I see that [issue 5039](https://github.com/microsoft/vscode-cpptools/issues/5039) touches upon the autocomplete aspect of this issue but was not resolved due to low priority. In this case we see a more egregious error with IntelliSense actually recommending invalid functions. Failing to go to function definitions is also new in this issue.
`c_cpp_properties.json`:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cppStandard": "c++11",
            "intelliSenseMode": "linux-gcc-x64",
            "compileCommands": ""
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment] 2022-06-08 22:44
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/1946. We haven't implemented the template IntelliSense feature yet. It works in VS 2022 when that feature is used to set the T type:
![image](https://user-images.githubusercontent.com/19859882/172729694-1de94900-67c8-4262-9992-85cf8ffc0c2d.png)

**Closed as not planned by sean-mcmanus** 2022-06-08 22:44 UTC
Labels: duplicate
