### ISSUE TITLE
Compiler args not working (no warnings with -Wall -Wextra)

### ISSUE THREAD

**Issue by tholeb** [microsoft/vscode-cpptools#10662] opened 2023-03-13 09:00 UTC
### Environment

- OS and Version: Windows 11 22H2 with WSL2
- VS Code Version: 1.76.1
- C/C++ Extension Version: 1.14.4
- If using SSH remote, specify OS of remote machine: Ubuntu 22.04LTS (WSL)

### Bug Summary and Steps to Reproduce

Bug Summary:
I added some compiler args in the settings, but it seems that the result is shown. For example, if I add `-Wall` and `-Wextra` I don't see any warnings on VSCode but when I compile with `gcc` it shows some warnings.

The compiler args : 
```json
"C_Cpp.default.compilerArgs": [
    "-Wall",
    "-Wextra",
    "-pedantic"
  ],
  ```

**Steps to reproduce:**
1. Add the compiler args in the settigns
2. Edit `example.c`:
```c
#include <stdio.h>
#include <stdlib.h>

int main(void)
{
	printf("%d", "string");

	return 0;
}
```
4. Compile with gcc to the see the warning : `gcc -Wall -Wextra example.c`
```
warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘char *’ [-Wformat=]
   26 |         printf("%d", "string");
      |                 ~^   ~~~~~~~~
      |                  |   |
      |                  int char *
      |                 %s
```

5. Nothing appear on VSCode
**Expected behavior:**
VSC should show us a warning on that line.

### Configuration and Logs

settings:
```
"C_Cpp.default.compilerArgs": [
    "-Wall",
    "-Wextra",
    "-pedantic"
  ],
  "C_Cpp.default.compilerPath": "/usr/bin/gcc",
  "C_Cpp.default.cStandard": "c17",
```

---
`C/C++ Log diagnostics`:
```
-------- Diagnostics - 3/13/2023, 9:51:40 AM
Version: 1.14.4
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/**"
    ],
    "defines": [],
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerArgs": [
        "-Wall",
        "-Wextra",
        "-pedantic"
    ],
    "cStandard": "c17",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPath": "/usr/bin/gcc",
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/fork.c ]:
    /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/fork.c
[ /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c ]:
    /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
Translation Unit Configurations:
[ /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/fork.c ]:
    Process ID: 4210
    Memory Usage: 97 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=110300
[ /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c ]:
    Process ID: 4229
    Memory Usage: 97 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=110300
Total Memory Usage: 194 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 21820
```
---
`OUTPUT` section on terminal:
```
loggingLevel has changed to: Debug
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/getCodeActions: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1561)
LSP: cpptools/activeDocumentChange: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
LSP: cpptools/getInlayHints: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1562)
LSP: cpptools/getFoldingRanges: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1563)
LSP: cpptools/getCodeActions: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1564)
LSP: cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
Queueing IntelliSense update for files in translation unit of: /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
sending 1 changes to server
sending 2 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 2 changes to server
sending 1 changes to server
sending 1 changes to server
Error squiggle count: 0
Update IntelliSense time (sec): 0.257
LSP: cpptools/getSemanticTokens: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1565)
LSP: cpptools/getFoldingRanges: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1566)
LSP: textDocument/hover: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1567)
LSP: textDocument/hover: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1568)
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/getCodeActions: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1569)
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/getCodeActions: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1570)
LSP: textDocument/didChange: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/formatRange: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1571)
Formatting document: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
Formatting Engine: clangFormat
LSP: cpptools/getFoldingRanges: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1572)
LSP: cpptools/getCodeActions: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1573)
LSP: cpptools/getSemanticTokens: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1574)
LSP: cpptools/getDocumentSymbols: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1575)
  tag parsing file: /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
idle loop: reparsing the active document
Checking for syntax errors: /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
Queueing IntelliSense update for files in translation unit of: /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
sending 1 changes to server
Error squiggle count: 0
Update IntelliSense time (sec): 0.575
LSP: cpptools/getCodeActions: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1576)
LSP: cpptools/getInlayHints: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1577)
LSP: cpptools/formatDocument: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1578)
Formatting document: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
Formatting Engine: clangFormat
LSP: textDocument/willSaveWaitUntil: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1579)
willSaveWaitUntil: 0ms
LSP: cpptools/getFoldingRanges: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1580)
LSP: textDocument/didSave: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
  tag parsing file: /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
LSP: cpptools/fileChanged: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
Checking for syntax errors: /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
Queueing IntelliSense update for files in translation unit of: /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
Error squiggle count: 0
Update IntelliSense time (sec): 0.256
LSP: cpptools/getSemanticTokens: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1581)
idle loop: reparsing the active document
Checking for syntax errors: /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
Queueing IntelliSense update for files in translation unit of: /home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
LSP: cpptools/getFoldingRanges: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1582)
Error squiggle count: 0
Update IntelliSense time (sec): 0.223
LSP: cpptools/getSemanticTokens: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1583)
LSP: cpptools/getFoldingRanges: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c (id: 1584)
LSP: cpptools/getDiagnostics (id: 1585)
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/activeDocumentChange: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/activeDocumentChange: file:///home/tholeb/Polytech/info3-s6-systeme-2-architecture-logicielle-des-systemes/src/TP2/exec.c
```

### Other Extensions

- C/C++ Extension pack

### Additional context

I know the [clangd](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) extension does this if we add a `compile_flags.txt` : 

e.g.
```
-Wall
-Wextra
-std=c17
-pedantic
-Iinclude
```

(With error lens extension, only the "oui" underline is provided by clangd)
![image](https://user-images.githubusercontent.com/43311443/224657022-7a66b44b-4f8b-46f1-8205-ab92033628f9.png)

**Comment by Colengms** [comment] 2023-03-13 18:14
Hi @tholeb  .  I believe this would be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/2814 .  In the case of gcc and clang, the `compilerPath` and `compilerArgs` fields in `c_cpp_propeties.json` (and their default values in `C_Cpp.default.*`) are used to invoke your compiler to solicit information from it, such as system includes and system defines, so that infrormation may be included in the IntelliSense configuration.  The extension does not invoke the compiler to compile individual source files, which would be necessary to generate the same warnings as gcc or clang would generate.  The IntelliSense engine is capable of generating warnings.  https://github.com/microsoft/vscode-cpptools/issues/2814 is tracking enabling those warnings.

Closing this as a duplicate.

**Closed as not planned by Colengms** 2023-03-13 18:14 UTC
