### ISSUE TITLE
Incorrect error messages are displayed when using STL functions related to ranges

### ISSUE THREAD

**Issue by Yuki-At** [microsoft/vscode-cpptools#11196] opened 2023-07-15 04:54 UTC
### Environment

- Windows 10 Home 22H2
- Visual Studio Code 1.80.1 (system setup)
- C/C++ Extension v1.16.3
- using g++.exe (Rev7, Built by MSYS2 project) 13.1.0

### Bug Summary

Incorrect error messages are displayed when using STL functions related to ranges, but it can be compiled and executed normally.
I don't know when the bug started. It has been occurring for over 6 months now, but I ignored it and continued to use it.

### Steps to reproduce

Use std::ranges::for_each, std::ranges::reverse_view, std::views::reverse, etc.
e.g.)
```c++
const std::vector<int> v = { 0, 1, 2, 3 };
std::ranges::copy(v, std::ostream_iterator<int>(std::cout, ", "));
```

#### main.cc
```C++
#include <bits/stdc++.h>

int main(int argc, char ** argv) {
    const std::vector<int> v = { 0, 1, 2, 3 };

    // no operator "|" matches these operandsC/C++(349)
    for (const auto i : v | std::views::reverse) {
        std::cout << i;
    }

    // no instance of overloaded function "std::ranges::__copy_fn::operator()" matches the argument listC/C++(304)
    std::ranges::copy(v, std::ostream_iterator<int>(std::cout, ", "));

    // no instance of overloaded function "std::ranges::__copy_fn::operator()" matches the argument listC/C++(304)
    std::ranges::copy(v.begin(), v.end(), std::ostream_iterator<int>(std::cout, ", "));

    // no error
    std::copy(v.begin(), v.end(), std::ostream_iterator<int>(std::cout, ", "));

    return 0;
}
```
#### c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/include/**"
            ],
            "defines": [
                "_DEBUG",
                "_UNICODE",
                "UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "C:/msys64/mingw64/bin/g++.exe",
            "cStandard": "c17",
            "cppStandard": "c++20",
            "intelliSenseMode": "windows-gcc-x64"
        }
    ],
    "version": 4
}
```

### Things I've tried

- I lowered the version of C/C++ Extension to 1.12.4 referring to [here](https://github.com/microsoft/vscode-cpptools/issues/10252).
- I deleted all extensions and then reinstalled only C/C++ Extension.
- Removed all contents of settings.json.
- Deleted all contents of workspaceStorage.
- Removed all contents of C:/Users/%username%/.vscode.
- Also tried on VSCode Insiders.

As a result, nothing has changed in the error message. What has changed is the theme, fonts, folder icons...

### Screenshots

![Screenshot 2023-07-15 130030](https://github.com/microsoft/vscode-cpptools/assets/52321575/0d0e460b-066b-43a2-b2d3-7996d294964a)
![Screenshot 2023-07-15 130049](https://github.com/microsoft/vscode-cpptools/assets/52321575/5d6cf4de-e112-4361-848e-a2f113a5e626)

### Execution result
```bash
$ g++ --std=c++20 src/main.cc

$ ./a.exe
32100, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3,
```

### Lastly
I'm not a native speaker, so I apologize if there are any inappropriate expressions.

### P.S.
The display was corrupted and has been corrected.

**Comment by michelleangela** [comment] 2023-07-18 19:41
@Yuki-At 
Thank you for submitting this issue. We determined this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/11038 where we have other related issues with GCC 13 and have filed bugs against our IntelliSense engine code based that is shared with Visual Studio.

**Closed as completed by michelleangela** 2023-07-18 19:41 UTC
Labels: bug, duplicate, Language Service, Visual Studio, gcc 13

**Comment by michelleangela** [comment] 2023-07-27 03:59
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.0.
