### ISSUE TITLE
Unexpected error on usage of a function defined in struct

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#6272] opened 2020-10-07 22:09 UTC
**Type: LanguageService**

**Describe the bug**

<details>
  <summary><strong>Sample code</strong></summary>

```
typedef unsigned int       uint32_t;

enum class UniqueThreadId : uint32_t
{
    Invalid = 0,
    Min     = 1,
    Max     = uint32_t(-1),
};

struct ThreadInfo
{
    UniqueThreadId UniqueId;

    /*implicit*/ constexpr operator UniqueThreadId() const { return UniqueId; }

    friend constexpr bool operator==(ThreadInfo const& a, ThreadInfo const& b)
    {
        if (a.UniqueId == b.UniqueId)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    friend constexpr bool operator<(ThreadInfo const& a, ThreadInfo const& b)
    {
        return a.UniqueId < b.UniqueId;
    }

    friend constexpr bool operator!=(ThreadInfo const& a, ThreadInfo const& b) { return !operator==(a, b); }
    friend constexpr bool operator> (ThreadInfo const& a, ThreadInfo const& b) { return  operator< (b, a); }
    friend constexpr bool operator<=(ThreadInfo const& a, ThreadInfo const& b) { return !operator< (b, a); }
    friend constexpr bool operator>=(ThreadInfo const& a, ThreadInfo const& b) { return !operator< (a, b); }
};


```
</details>

**Steps to reproduce**

1. Created empty header file and copy sample code into header file.
2. Observe unexpected error on usage of `operator` functions

Error message sample:
```
more than one instance of function "operator==" matches the argument list: -- function "operator==(const ThreadInfo &a, const ThreadInfo &b)" (declared at line 16) -- function "operator==(const ThreadInfo &a, const ThreadInfo &b)" (declared at line 16) -- argument types are: (const ThreadInfo, const ThreadInfo)
```

**Expected behavior**
No error squiggles.

**Additional context**
Error message is coming from IntelliSense Engine. Does not reproduce on Visual Studio.

**Comment by sean-mcmanus** [comment] 2020-10-08 18:52
The bug repros with VS 16.7.5 -- I believe it must have gotten fixed within the past week.

**Comment by TheJCAB** [comment] 2020-10-20 16:45
Hi! I just confirmed that this is not limited to operators, but any friend functions called from friend functions. For instance:

![image](https://user-images.githubusercontent.com/22421744/96617752-d7477900-12b8-11eb-808b-86c4e2135425.png)

Same thing: ambiguity of the definition with itself, but reported differently (with the filename and without).

**Comment by sean-mcmanus** [comment] 2020-11-12 21:29
I don't repro this bug with msvc/cl.exe with 1.1.1. However, I get an "identifier "operator==" is undefined" in Linux mode: https://developercommunity.visualstudio.com/content/problem/1254622/c-intellisense-gives-an-incorrect-identifier-opera.html .

**Comment by Colengms** [comment] 2021-04-15 22:45
It looks like we picked up a fix for this from VS.  I'm no longer able to repro as of version 1.1.0.  Closing as fixed.

**Closed as completed by Colengms** 2021-04-15 22:45 UTC
Labels: bug, Language Service, Visual Studio, verified
