### ISSUE TITLE
Debugger won't start on Windows 10 setting UTF-8 locale

### ISSUE THREAD

**Issue by hodlen** [microsoft/vscode-cpptools#2127] opened 2018-06-13 13:44 UTC
Type: Debugger

In Windows 10 1803 update, there's an option to turn on UTF-8 beta feature in the locale settings (Control Panel -> Region -> Administrative -> Change system locale). When UTF-8 turned on, the debugger won't start but hanging on forever. Then I tried to turn off the UTF-8 feature, and the problem fixed. 

Similar issue: https://github.com/Microsoft/vscode-cpptools/issues/1527

**Describe the bug**
- OS and Version: Windows 10 Enterprise 1803
- VS Code Version: 1.24.0
- C/C++ Extension Version: 0.17.4
- Other extensions you installed (and if the issue persists after disabling them): C++ Intellisense, Code Runner, Atom One Dark Theme, Settings sync
- BUG DESCRIPTION
  - With all the configuration set correctly and run perfectly before I turned on the UTF-8 feature after the UTF-8 turned on, the debugger won't start after I hit the start button. 
  - No warnings and errors, but just hanging on. 
  - The buttons on the control bar (step into, step over, etc) except stop are all grey. 
  - When I hit the stop button, the gdb.exe still working on the background, and the start button won't work any longer except I kill gdb.exe. 

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Turn on the UTF-8 feature and restart the system. 
2. Run the debugger on any piece of code.
3. See error. 

**launch.json**
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "GDB Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
      "stopAtEntry": true,
      "cwd": "${workspaceFolder}",
      "externalConsole": true,
      "MIMode": "gdb",
      "miDebuggerPath": "C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/gdb.exe",
      "internalConsoleOptions": "neverOpen",
      "preLaunchTask": "Compile",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": false
        }
      ],
      "logging": {
        "engineLogging": true
      }
    }
  ]
}

**Additional Info**
I've also tested gdb.exe in cmd (with codepage of UTF-8), it worked correctly.

**Comment by pieandcakes** [comment] 2018-06-13 19:57
@Miosolo Thank you for filing an issue. As you noted, this is a duplicate of #1527. There is a workaround of disabling UTF-8 at this time until we find a solution.

**Closed as completed** 2021-11-30 03:28 UTC
Labels: duplicate, debugger
