### ISSUE TITLE
crash on macos

### ISSUE THREAD

**Issue by pokerchina** [Microsoft/vscode-cpptools#20] opened 2016-04-20 06:53 UTC
Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x0000700000000d58

VM Regions Near 0x700000000d58:
    VM_ALLOCATE            00000001028ff000-0000000102900000 [    4K] rw-/rwx SM=ALI  
--> STACK GUARD            0000700000000000-0000700000001000 [    4K] ---/rwx SM=NUL  stack guard for thread 1
    Stack                  0000700000001000-0000700000083000 [  520K] rw-/rwx SM=COW  thread 1

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff87f2cf8a __read_nocancel + 10
1   libsystem_c.dylib             	0x00007fff964ea15d _sread + 16
2   libsystem_c.dylib             	0x00007fff964e9771 __srefill1 + 24
3   libsystem_c.dylib             	0x00007fff964e988c __srget + 14
4   libsystem_c.dylib             	0x00007fff964e5532 getc + 52
5   libc++.1.dylib                	0x00007fff92386051 std::__1::__stdinbuf<char>::__getchar(bool) + 119
6   Microsoft.VSCode.CPP.Extension.darwin	0x0000000101bda449 std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char) + 169
7   Microsoft.VSCode.CPP.Extension.darwin	0x0000000101bc2487 vscode::handler_base<message_handler>::main_loop() + 311
8   Microsoft.VSCode.CPP.Extension.darwin	0x0000000101bc224c main + 1244
9   libdyld.dylib                 	0x00007fff8b88a5ad start + 1

Thread 1 Crashed:
0   Microsoft.VSCode.CPP.Extension.darwin	0x0000000102004680 scout_parser_cpp_generated::statement() + 32
1   Microsoft.VSCode.CPP.Extension.darwin	0x0000000101ff58db scout_parser_cpp_generated::statement_block(bool, a_source_point&) + 139
2   Microsoft.VSCode.CPP.Extension.darwin	0x0000000102004713 scout_parser_cpp_generated::statement() + 179
3   Microsoft.VSCode.CPP.Extension.darwin	0x0000000101ff58db scout_parser_cpp_generated::statement_block(bool, a_source_point&) + 139
4   Microsoft.VSCode.CPP.Extension.darwin	0x0000000102004713 scout_parser_cpp_generated::statement() + 179
5   Microsoft.VSCode.CPP.Extension.darwin	0x0000000101ff58db scout_parser_cpp_generated::statement_block(bool, a_source_point&) + 139
6   Microsoft.VSCode.CPP.Extension.darwin	0x0000000102004713 scout_parser_cpp_generated::statement() + 179
7   Microsoft.VSCode.CPP.Extension.darwin	0x0000000101ff58db scout_parser_cpp_generated::statement_block(bool, a_source_point&) + 139
8   Microsoft.VSCode.CPP.Extension.darwin	0x0000000102004713 scout_parser_cpp_generated::statement() + 179
9   Microsoft.VSCode.CPP.Extension.darwin	0x0000000101ff58db scout_parser_cpp_generated::statement_block(bool, a_source_point&) + 139
10  Microsoft.VSCode.CPP.Extension.darwin	0x0000000102004713 scout_parser_cpp_generated::statement() + 179
11  Microsoft.VSCode.CPP.Extension.darwin	0x0000000101ff58db scout_parser_cpp_generated::statement_block(bool, a_source_point&) + 139
12  Microsoft.VSCode.CPP.Extension.darwin	0x0000000102004713 scout_parser_cpp_generated::statement() + 179
13  Microsoft.VSCode.CPP.Extension.darwin	0x0000000101ff58db scout_parser_cpp_generated::statement_block(bool, a_source_point&) + 139
14  Microsoft.VSCode.CPP.Extension.darwin	0x0000000102004713 scout_parser_cpp_generated::statement() + 179
15  Microsoft.VSCode.CPP.Extension.darwin	0x0000000101ff58db scout_parser_cpp_generated::statement_block(bool, a_source_point&) + 139
16  Microsoft.VSCode.CPP.Extension.darwin	0x0000000102004713 scout_parser_cpp_generated::statement() + 179
17  Microsoft.VSCode.CPP.Extension.darwin	0x0000000101ff58db scout_parser_cpp_generated::statement_block(bool, a_source_point&) + 139
18  Microsoft.VSCode.CPP.Extension.darwin	0x0000000102004713 scout_parser_cpp_generated::statement() + 179
19  Microsoft.VSCode.CPP.Extension.darwin	0x0000000101ff58db scout_parser_cpp_generated::statement_block(bool, a_source_point&) + 139

**Comment by sridmad** [comment] 2016-06-28 19:58
@pokerchina , I have not been able to reproduce the crash with different versions of the extension. Do you see the crash with the latest version (0.7.1)?

Thanks

**Comment by maverickwoo** [comment] 2016-08-17 23:38
I just ran into a similar crash with the latest extension (0.8.1) and latest Code release (1.4.0). To reproduce, I ran `/usr/local/bin/code .` inside an empty folder. Once Code has started, I press Cmd-P and type "abc" *quickly*. Code will show "No results found" and the crash will happen at that instant.

Note that you have to type fast enough. If you type slowly such that Code is able to catch up and displays "No results found" after typing "a", then there will be no crash.

**Comment by jgoshi** [comment] 2016-08-31 17:17
I haven't been able to repro what @maverickwoo reported. It's also more of an edge case. I'm closing this issue because the latest version of cpptools (0.9.0) fixed a similar crash where the app didn't have write access to the database directory. If a crash still happens with 0.9.0 please reopen (or create a new issue).

**Closed by jgoshi** 2016-08-31 17:17 UTC
Labels: bug, Language Service

**Comment by maverickwoo** [comment] 2016-08-31 23:45
@jgoshi It still happened after I upgraded to cpptools 0.9.0. However, during the process of restarting vscode a few times to confirm I really can repo, haha, the problem goes away. I can no longer repo. I have to agree that it is fixed for me.

**Comment by jgoshi** [comment] 2016-09-01 00:05
That's good to hear. Thank you for the update!

**Comment by maverickwoo** [comment] 2016-09-01 21:06
As it turns out, the problem comes back today after an entire day of working without crash. At the moment when I started writing this comment, with cpptools 0.9.0 on vscode 1.4.0, if I open an empty directory in vscode and then press Cmd-P and then type gibberish quickly, the crash is very reproducible. I have attached the crash log for one of the crashes for the record.

But there is more! If in the same empty directory I `mkdir .vscode` and restart vscode, then the same sequence of actions won't cause a crash.

More interestingly, if I then remove the empty `.vscode` subdirectory (and now the directory returns to being empty) and restart vscode, the same sequence of actions won't cause a crash either and now I am "protected from the crash for a while"... though now I suspect it will come back later. :)

I have not been able to figure out how to make the crash come back. I have tried using a fresh `~/Library/Application Support/Code` and that does not remove my "protection" either. I think a logical deduction is that somehow my daily usage can leave some state in `~/Library/Application Support/Code` that will cause cpptools to crash during a search for a nonexistent file.

```
Process:         Microsoft.VSCode.CPP.Extension.darwin [19633]
Path:            /Users/USER/*/Microsoft.VSCode.CPP.Extension.darwin
Identifier:      Microsoft.VSCode.CPP.Extension.darwin
Version:         0
Code Type:       X86-64 (Native)
Parent Process:  Code Helper [19625]
Responsible:     iTerm2 [384]
User ID:         501

Date/Time:       2016-09-01 16:47:17.823 -0400
OS Version:      Mac OS X 10.9.5 (13F1911)
Report Version:  11
Anonymous UUID:  200F434C-FB38-3E1F-5A94-20427220D622

Sleep/Wake UUID: F2C0BD81-3A99-4CD3-9B13-F7DB6C1E4FEA

Crashed Thread:  1

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x000000000000042c

VM Regions Near 0x42c:
--> 
    __TEXT                 0000000104f7d000-00000001054ec000 [ 5564K] r-x/rwx SM=COW  /Users/USER/*/*.darwin

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff816788ea __read_nocancel + 10
1   libsystem_c.dylib             	0x00007fff8865c8d5 _sread + 16
2   libsystem_c.dylib             	0x00007fff8865bee7 __srefill1 + 24
3   libsystem_c.dylib             	0x00007fff8865c001 __srget + 14
4   libsystem_c.dylib             	0x00007fff886582f4 getc + 44
5   libc++.1.dylib                	0x00007fff89d66f51 std::__1::__stdinbuf<char>::__getchar(bool) + 119
6   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104faa0e9 std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char) + 153
7   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104f7f077 vscode::handler_base<message_handler>::main_loop() + 375
8   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104f7eeb6 main + 102
9   libdyld.dylib                 	0x00007fff8c48f5fd start + 1

Thread 1 Crashed:
0   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104fe4274 code_store::a_store::get_structure_version() + 4
1   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104fc2f11 browse_engine::populate_filename_cache() + 49
2   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104fc4b71 browse_engine::query_files(char const*, std::__1::vector<browse_symbol, std::__1::allocator<browse_symbol> >&) + 129
3   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104f894d6 message_handler::workspace_symbol(vscode::WorkspaceSymbolParams) + 70
4   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104f826c5 vscode::handler_base<message_handler>::dispatch(vscode::vscode_client_message&&, vscode::vscode_server_message&, bool) + 7637
5   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104f80609 vscode::handler_base<message_handler>::handle_message(vscode::vscode_client_message&&) + 57
6   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104f8054b vscode::handler_base<message_handler>::main_loop()::'lambda'()::operator()() const + 75
7   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104f804c0 void* std::__1::__thread_proxy<std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::'lambda'()> >(void*) + 96
8   libsystem_pthread.dylib       	0x00007fff8969a899 _pthread_body + 138
9   libsystem_pthread.dylib       	0x00007fff8969a72a _pthread_start + 137
10  libsystem_pthread.dylib       	0x00007fff8969efc9 thread_start + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff81678716 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff8969cc3b _pthread_cond_wait + 727
2   libc++.1.dylib                	0x00007fff89d58d43 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 47
3   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104fa9ca2 vscode::message_queue<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::pop() + 82
4   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104fa9bd3 vscode::handler_base<message_handler>::main_loop()::'lambda0'()::operator()() const + 67
5   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104fa9b50 void* std::__1::__thread_proxy<std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::'lambda0'()> >(void*) + 96
6   libsystem_pthread.dylib       	0x00007fff8969a899 _pthread_body + 138
7   libsystem_pthread.dylib       	0x00007fff8969a72a _pthread_start + 137
8   libsystem_pthread.dylib       	0x00007fff8969efc9 thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff81678716 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff8969cc3b _pthread_cond_wait + 727
2   libc++.1.dylib                	0x00007fff89d58d43 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 47
3   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104f80722 vscode::message_queue<vscode::vscode_client_message>::pop() + 82
4   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104fa9ec0 vscode::handler_base<message_handler>::main_loop()::'lambda1'()::operator()() const + 64
5   Microsoft.VSCode.CPP.Extension.darwin	0x0000000104fa9e40 void* std::__1::__thread_proxy<std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::'lambda1'()> >(void*) + 96
6   libsystem_pthread.dylib       	0x00007fff8969a899 _pthread_body + 138
7   libsystem_pthread.dylib       	0x00007fff8969a72a _pthread_start + 137
8   libsystem_pthread.dylib       	0x00007fff8969efc9 thread_start + 13

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000004  rbx: 0x00007fe440c04608  rcx: 0x0000000000000000  rdx: 0x00000001059b94c0
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x00000001059b9180  rsp: 0x00000001059b9180
   r8: 0x0000000000000004   r9: 0x00000001054836d0  r10: 0x0000000013db228b  r11: 0xffff801cc4ab93ba
  r12: 0x0000000000000000  r13: 0x00007fe440c04608  r14: 0x5d00bcc2cefefc10  r15: 0x00007fff5ac80d70
  rip: 0x0000000104fe4274  rfl: 0x0000000000010206  cr2: 0x000000000000042c
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x104f7d000 -        0x1054ebff7 +Microsoft.VSCode.CPP.Extension.darwin (0) <7442836F-C0DA-3D40-ADB7-98650DCA6656> /Users/USER/*/Microsoft.VSCode.CPP.Extension.darwin
    0x7fff6ecd6000 -     0x7fff6ed09887  dyld (239.5) <1D3130FE-FE7E-3C4C-8E74-EB51895B6BA5> /usr/lib/dyld
    0x7fff8113d000 -     0x7fff8113eff7  libSystem.B.dylib (1197.1.1) <72A98ACC-7606-3AD5-82AF-02D4EBBD4F02> /usr/lib/libSystem.B.dylib
    0x7fff81663000 -     0x7fff8167fff7  libsystem_kernel.dylib (2422.115.15) <34ABAF79-E147-3C34-B05D-46A566E689CC> /usr/lib/system/libsystem_kernel.dylib
    0x7fff816dc000 -     0x7fff81700fff  libxpc.dylib (300.90.2) <AB40CD57-F454-3FD4-B415-63B3C0D5C624> /usr/lib/system/libxpc.dylib
    0x7fff81a29000 -     0x7fff81a30ffb  libcopyfile.dylib (103.92.1) <CF29DFF6-0589-3590-834C-82E2316612E8> /usr/lib/system/libcopyfile.dylib
    0x7fff82a3f000 -     0x7fff82a68ff7  libc++abi.dylib (49.1) <21A807D3-6732-3455-B77F-743E9F916DF0> /usr/lib/libc++abi.dylib
    0x7fff82de7000 -     0x7fff82de7ff7  libkeymgr.dylib (28) <3AA8D85D-CF00-3BD3-A5A0-E28E1A32A6D8> /usr/lib/system/libkeymgr.dylib
    0x7fff83233000 -     0x7fff83234ff7  libDiagnosticMessagesClient.dylib (100) <4CDB0F7B-C0AF-3424-BC39-495696F0DB1E> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff8353c000 -     0x7fff83541fff  libmacho.dylib (845) <1D2910DF-C036-3A82-A3FD-44FF73B5FF9B> /usr/lib/system/libmacho.dylib
    0x7fff83542000 -     0x7fff83571fd2  libsystem_m.dylib (3047.16) <B7F0E2E4-2777-33FC-A787-D6430B630D54> /usr/lib/system/libsystem_m.dylib
    0x7fff84198000 -     0x7fff841e6fff  libcorecrypto.dylib (161.1) <F3973C28-14B6-3006-BB2B-00DD7F09ABC7> /usr/lib/system/libcorecrypto.dylib
    0x7fff84814000 -     0x7fff8481efff  libcommonCrypto.dylib (60049) <8C4F0CA0-389C-3EDC-B155-E62DD2187E1D> /usr/lib/system/libcommonCrypto.dylib
    0x7fff8513b000 -     0x7fff8513cff7  libsystem_blocks.dylib (63) <FB856CD1-2AEA-3907-8E9B-1E54B6827F82> /usr/lib/system/libsystem_blocks.dylib
    0x7fff85e49000 -     0x7fff85e4fff7  libsystem_platform.dylib (24.90.1) <3C3D3DA8-32B9-3243-98EC-D89B9A1670B3> /usr/lib/system/libsystem_platform.dylib
    0x7fff85e50000 -     0x7fff85e52ff3  libsystem_configuration.dylib (596.15) <4998CB6A-9D54-390A-9F57-5D1AC53C135C> /usr/lib/system/libsystem_configuration.dylib
    0x7fff85f6b000 -     0x7fff85f6fff7  libsystem_stats.dylib (93.90.3) <2304C7C2-BE45-35DE-BCC6-707D61B7AE7E> /usr/lib/system/libsystem_stats.dylib
    0x7fff86791000 -     0x7fff867abfff  libdispatch.dylib (339.92.1) <C4E4A18D-3C3B-3C9C-8709-A4270D998DE7> /usr/lib/system/libdispatch.dylib
    0x7fff86870000 -     0x7fff86897ff7  libsystem_network.dylib (241.4) <0D630D53-C772-3EC5-8257-EFB0ACCE3153> /usr/lib/system/libsystem_network.dylib
    0x7fff876f3000 -     0x7fff876fafff  libcompiler_rt.dylib (35) <4CD916B2-1B17-362A-B403-EF24A1DAC141> /usr/lib/system/libcompiler_rt.dylib
    0x7fff877b6000 -     0x7fff877b7fff  libunc.dylib (28) <62682455-1862-36FE-8A04-7A6B91256438> /usr/lib/system/libunc.dylib
    0x7fff88071000 -     0x7fff88073ff7  libquarantine.dylib (71) <7A1A2BCB-C03D-3A25-BFA4-3E569B2D2C38> /usr/lib/system/libquarantine.dylib
    0x7fff883a2000 -     0x7fff883bdff7  libsystem_malloc.dylib (23.10.1) <A695B4E4-38E9-332E-A772-29D31E3F1385> /usr/lib/system/libsystem_malloc.dylib
    0x7fff88619000 -     0x7fff886a2fef  libsystem_c.dylib (997.90.5) <889AA3F9-121C-3985-8B1D-5E908C5693BC> /usr/lib/system/libsystem_c.dylib
    0x7fff886bf000 -     0x7fff886c4ff7  libunwind.dylib (35.3) <78DCC358-2FC1-302E-B395-0155B47CB547> /usr/lib/system/libunwind.dylib
    0x7fff89699000 -     0x7fff896a0ff7  libsystem_pthread.dylib (53.1.4) <AB498556-B555-310E-9041-F67EC9E00E2C> /usr/lib/system/libsystem_pthread.dylib
    0x7fff89732000 -     0x7fff89743ff7  libsystem_asl.dylib (217.1.4) <655FB343-52CF-3E2F-B14D-BEBF5AAEF94D> /usr/lib/system/libsystem_asl.dylib
    0x7fff89787000 -     0x7fff8978ffff  libsystem_dnssd.dylib (522.92.3) <1418DF66-01BE-3A87-8553-09EAA945F4FE> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff89a53000 -     0x7fff89a95ff7  libauto.dylib (185.5) <F45C36E8-B606-3886-B5B1-B6745E757CA8> /usr/lib/libauto.dylib
    0x7fff89a96000 -     0x7fff89abdffb  libsystem_info.dylib (449.1.4) <12CD9E42-8CEE-3A8D-B006-F8A6EB98804D> /usr/lib/system/libsystem_info.dylib
    0x7fff89d52000 -     0x7fff89da4fff  libc++.1.dylib (120) <4F68DFC5-2077-39A8-A449-CAC5FDEE7BDE> /usr/lib/libc++.1.dylib
    0x7fff89dcb000 -     0x7fff89dccffb  libremovefile.dylib (33) <3543F917-928E-3DB2-A2F4-7AB73B4970EF> /usr/lib/system/libremovefile.dylib
    0x7fff8a109000 -     0x7fff8a110ff8  liblaunch.dylib (842.92.1) <A40A0C7B-3216-39B4-8AE0-B5D3BAF1DA8A> /usr/lib/system/liblaunch.dylib
    0x7fff8ad77000 -     0x7fff8ad78fff  libsystem_sandbox.dylib (278.11.2) <0C93EB23-7364-3670-B511-212A7A524695> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff8ba2d000 -     0x7fff8ba36ffb  libsystem_notify.dylib (121.20.1) <9B34B4FE-F5AD-3F09-A5F0-46AFF3571323> /usr/lib/system/libsystem_notify.dylib
    0x7fff8c48c000 -     0x7fff8c48fff7  libdyld.dylib (239.5) <CAE7A50D-F156-3D47-81C0-DC41EB975D38> /usr/lib/system/libdyld.dylib
    0x7fff8d96e000 -     0x7fff8db1bf27  libobjc.A.dylib (551.1) <AD7FD984-271E-30F4-A361-6B20319EC73B> /usr/lib/libobjc.A.dylib
    0x7fff8db1c000 -     0x7fff8db20ff7  libcache.dylib (62) <BDC1E65B-72A1-3DA3-A57C-B23159CAAD0B> /usr/lib/system/libcache.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 162716
    thread_create: 1
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=79.4M resident=65.7M(83%) swapped_out_or_unallocated=13.7M(17%)
Writable regions: Total=47.1M written=196K(0%) resident=304K(1%) swapped_out=0K(0%) unallocated=46.8M(99%)
 
REGION TYPE                      VIRTUAL
===========                      =======
Kernel Alloc Once                     4K
MALLOC                             36.2M
MALLOC (admin)                       16K
STACK GUARD                        56.0M
Stack                              9752K
VM_ALLOCATE                           8K
__DATA                             1992K
__LINKEDIT                         69.0M
__TEXT                             10.4M
shared memory                         4K
===========                      =======
TOTAL                             183.1M

```

**Comment by sridmad** [comment] 2016-09-01 21:38
Thanks for the detailed information! This should help us try and get to the bottom of the issue. I suspect that it is not specific to Mac as it seems like a timing issue that is probably getting masked due to OS differences.
