### ISSUE TITLE
Cpptool is preventing "editor.suggest.insertMode": "insert"

### ISSUE THREAD

**Issue by Adnn** [microsoft/vscode-cpptools#11353] opened 2023-08-22 12:42 UTC
Type: <b>Bug</b>

At some point during the past months, accepting a completion suggestion started deleting the word **right of** the inserted position.

I explicitly disabled this behaviour with this configuration in my user's settings.json (Please note that this initially worked):

    "[cpp]":  {
        "editor.suggest.insertMode": "insert"
    }

I just ran a "Start extension bisect" from VSCode, and it identified `cpptool` as the extension causing this problem.

Extension version: 1.17.4
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by Colengms** [comment] 2023-08-22 20:18
Hi @Adnn .  Thanks for letting us know about this.  It looks like this is a dupe of: https://github.com/microsoft/vscode-cpptools/issues/10613 , which I reopened.  Closing this as a duplicate.

**Closed as not planned by Colengms** 2023-08-22 20:18 UTC
