### ISSUE TITLE
Formatting error with C++ keyword on C source files

### ISSUE THREAD

**Issue by ZhUyU1997** [microsoft/vscode-cpptools#6711] opened 2020-12-25 18:26 UTC
**Type: LanguageService**

Formatting error with C++ keyword on C source files

**Describe the bug**
- OS and Version: Windows 10 20H2
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3

**Steps to reproduce**

1. Input below text:
```c
private->order = INVALID_ORDER;
````

**Expected behavior**
No newline

**Screenshots**
![image](https://user-images.githubusercontent.com/18410894/103140473-d51ef200-4721-11eb-936f-8966dfdcbefd.png)

**Comment by sean-mcmanus** [comment] 2020-12-29 00:17
This is a bug in clang-format 10.0. It's fixed in clang-format 11, which we plan to ship in our next release. You can workaround the bug via installing clang-format 11 https://releases.llvm.org/download.html and setting C_Cpp.clang_format_path to the path to the clang-format executable. You could also switch C_Cpp.formatting to "vcFormat" to use a different formatting implementation (but that has different configuration settings and behavior).

**Comment by bobbrow** [comment] 2021-01-05 21:13
We'll be updating to clang-format 11 in the next release.  I'll mark this as a duplicate of that work item.  #6326

**Closed as completed by bobbrow** 2021-01-05 21:13 UTC
Labels: bug, duplicate, external, Feature: Code Formatting

**Comment by sean-mcmanus** [comment] 2021-01-21 07:45
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
