### ISSUE TITLE
The template class cannot prompt correctly

### ISSUE THREAD

**Issue by stfujnkk** [microsoft/vscode-cpptools#8350] opened 2021-11-01 00:01 UTC
**Vscode Version : `September 2021 (version 1.61)`**
**operating system : `Windows 10`**
---
When I was writing `.val`, there was no code prompt.
```cpp
template <typename T>
struct Node {
  T val;
};
template <typename C>
class AAA {
  vector<Node<C>> a;
  AAA(){
    a[0].val;
  }
};
```
After I changed `C` to `string`, there was a code prompt.
![image](https://user-images.githubusercontent.com/52458236/139605639-be6c9715-4357-4e30-810b-edfed420275b.png)

**Comment by Colengms** [comment] 2021-11-03 20:57
Hi @stfujnkk .  Thanks for reporting this.  This appears to be a duplicate of: https://github.com/microsoft/vscode-cpptools/issues/4946   Closing this one as a duplicate.

**Closed as completed by Colengms** 2021-11-03 20:57 UTC
