### ISSUE TITLE
while compiling c++ file setting.json opens

### ISSUE THREAD

**Issue by max-keviv** [microsoft/vscode-cpptools#7697] opened 2021-06-15 05:51 UTC
After selecting C++ (GDB/LLDB) as environment 
setting.json prompts

```
{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.languageServer": "Microsoft",
    "workbench.colorTheme": "Hyper Term Black",
    "python.formatting.provider": "black",
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
    "workbench.iconTheme": "vscode-icons",
    "editor.formatOnPaste": true,
    "editor.defaultFormatter": "mgmcdermott.vscode-language-babel",
    // "editor.codeActionsOnSave": null,
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "C_Cpp.updateChannel": "Insiders",
    "window.zoomLevel": 1
}
```

**Comment by sean-mcmanus** [comment] 2021-06-15 18:14
Can you provide more info? Could this be a VS Code issue or caused by another extension?

**Comment by max-keviv** [comment] 2021-06-16 17:40
I have C/C++ extension installed in Visual Studio Code and also in system
while I am trying to compile my c++ code it shows option to select
- C++ (GDB/LLDB)
- C++ (Windows)
on select C++ (GDB/LLDB) setting.json opens
on select  C++ (Windows) noting happens
![Screenshot from 2021-06-16 23-06-51](https://user-images.githubusercontent.com/59287619/122266621-9bbc8780-cef7-11eb-87d1-be4e0d52948f.png)

**Comment by sean-mcmanus** [comment] 2021-06-16 17:59
Do you have gcc and gdb installed? https://code.visualstudio.com/docs/cpp/config-linux#_ensure-gcc-is-installed

**Comment by max-keviv** [comment] 2021-06-16 18:05
@sean-mcmanus yes

**Comment by sean-mcmanus** [comment] 2021-06-16 18:15
How are you invoking the debugger? F5? Do you have an existing launch.json?

**Comment by v-ericawu** [comment] 2021-06-17 07:37
@max-keviv When using the C++ (GDB/LLDB) debug file, the "settings.json" file is not opened
Notes: Install [gcc ](https://code.visualstudio.com/docs/cpp/config-linux#_ensure-gcc-is-installed)compilation tools
Repro steps:
1. Open HelloWorld project with VS Code.
2. Type the wrong information in the .cpp file, and click the light bulb to open the "settings.json" file.
3. Switch to the .cpp file.
4. Navigate to the top toolbar and click Run->Start Debugging.
![7697](https://user-images.githubusercontent.com/78774400/122352426-b3405280-cf81-11eb-8ce1-611b81f51df7.gif)

If the steps are not correct, can you share your specific steps and screenshots?

**Comment by max-keviv** [comment] 2021-06-22 08:06
thanks 
IT was solved by adding folder to WORKSPACE

**Comment by sean-mcmanus** [comment] 2021-06-25 20:15
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6545

**Closed as completed by sean-mcmanus** 2021-06-25 20:15 UTC
Labels: duplicate
