### ISSUE TITLE
Support for forced include

### ISSUE THREAD

**Issue by tksuoran** [microsoft/vscode-cpptools#1089] opened 2017-10-02 07:44 UTC
c_cpp_properties.json should allow user to provide forced includes. In MSVC compiler these are given with /FI option and in gcc using -include option. Without this option it is very difficult to get intellisense working on some projects.

**Comment by sean-mcmanus** [comment] 2017-10-02 14:54
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/852 .

**Closed as completed by sean-mcmanus** 2017-10-02 14:54 UTC
Labels: duplicate, Language Service

**Comment by sean-mcmanus** [comment] 2018-02-16 00:25
@tksuoran A workaround is to modify the bin/msvc.json file in same folder the Microsoft.VSCode.CPP.Extension process is in by appending code to the "defaults" array like:
`      "-D_USE_DECLSPECS_FOR_SAL=1",
      "--preinclude",
      "F:\\forcedInclude.h"
    ],`
We might be able to add a setting to c_cpp_properties.json in the next release, since that file gets overwritten on updates.
