### ISSUE TITLE
C/C++ Error Checking doesn't work for a missing '}' at the end of a file

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode-cpptools#6769] opened 2021-01-13 12:02 UTC
**Type: LanguageService**

Error checking is not working in VS Code. 

**Describe the bug**
- OS and Version: Windows 10 Pro
- VS Code Version:  1.52.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): Vs Intellicode
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is :-
   Errors in syntax and some other type of errors are not shown by editor.

_**I am using mingw gcc**_

**Steps to reproduce**

1. Create a new C file.
2. Copy Paste the following code. [https://pastebin.com/tB5bz7gi](https://pastebin.com/tB5bz7gi)
3. No errors are shown in this code.
4. Whereas it should have reported two errors namely:
(i) The bracket at the end of code is not closed.
(ii) In the printf function in Line 17,  the correct term should be %s instead of %c, so it should have reported that 
 _Format specifies type 'int' but the argument has type 'char *'_

**Expected behavior**
I want to report it the error.

Also other format specifier errors are not reported.

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![Screenshot (49)](https://user-images.githubusercontent.com/54276661/104449414-9663b580-55c4-11eb-9794-84e1a09d80c2.png)

**AND IN THE BELOW IMAGE IN LINE 17, it should have reported the format specifier error...but it's not reporting any  :(**
![Screenshot (50)](https://user-images.githubusercontent.com/54276661/104449762-1f7aec80-55c5-11eb-8109-d1ad79ab850b.png)

**Additional context**

**Comment by sean-mcmanus** [comment] 2021-01-13 19:46
IntelliSense errors are intentionally disabled in the Open File scenario. You need to open a folder to get error squiggles. Maybe we could change that...?

**Comment by lakshits11** [comment] 2021-01-13 20:20
I have tried opening folder also then also issue persists

**Comment by lakshits11** [comment] 2021-01-13 20:22
The image u see above, I have opened that file in folder actually.

**Comment by bobbrow** [comment] 2021-01-13 21:28
@sean-mcmanus, I was thinking we had a bug about missing squiggles on the last line of a file.

**Comment by sean-mcmanus** [comment] 2021-01-14 02:36
Yeah, I recall that.

**Comment by sean-mcmanus** [comment] 2021-01-14 02:48
@lakshits11 Can you confirm that you get squiggles for something like
```
int main()
{
    return 0;
&
```
i.e. if the last character ends with `&`?

No squiggles for a missing `{` would be a VS bug. I've filed an issue against our shared parser at https://developercommunity.visualstudio.com/content/problem/1309633/c-intellisense-gives-no-squiggles-for-missing-at-t.html .

@bobbrow You may have been thinking about the Find All References failing on the last line, which got fixed: https://github.com/microsoft/vscode-cpptools/issues/4150

**Comment by lakshits11** [comment] 2021-01-14 03:57
Yes, here it gives me an error under `&` keyword saying that _expected an expression_
It doesn't give any error for closing the bracket.

**Comment by lakshits11** [comment] 2021-01-14 04:03
What I also want that in the following  code, it should give me an warning in line 5 saying that
 _'%c' expects argument of type 'char *', but argument 2 has type 'int *' [-Wformat=]_

![image](https://user-images.githubusercontent.com/54276661/104543304-382de580-564b-11eb-8602-d4a4af8949b2.png)

Which it does not. i.e. 
**Warnings should also be reported in the editor.**

**Comment by lakshits11** [comment] 2021-01-14 04:06
One more thing I noticed regarding bracket closing bug that if I run build task the opened file (ofcourse in a folder) the if the file has any unclosed bracket, after running the run build task command, it wpuld show me the error saying that bracket is not closed.
But before the run build task, it doesn't give me any error.
But if I directly compile and run the file from command prompt or powershell, no errors are shown in editor .

**Comment by sean-mcmanus** [comment] 2021-01-14 04:18
The scanf issue is being tracked by https://github.com/microsoft/vscode-cpptools/issues/6457 -- we'd need to add support for VS's code analysis feature -- can you upvote that (it currently needs more votes).

The errors from the build task are from the compiler at compile time. This issue is tracking errors from IntelliSense during designtime.

**Comment by lakshits11** [comment] 2021-01-14 05:00
Yes I upvoted it. Thanks

**Comment by lakshits11** [comment] 2021-01-19 05:58
Hello, I have noted another bug (maybe) regarding error checking so I thought I would mention it here.
**Here I opened the file in a folder. There's no declaration of function. But still no error squiggle is shown.**

![image](https://user-images.githubusercontent.com/54276661/104993569-0d77ce80-5a49-11eb-9bef-5f0169105813.png)


**But after I run file without debugging, error squiggle is shown. Please look into this**

![image](https://user-images.githubusercontent.com/54276661/104993748-4dd74c80-5a49-11eb-85c8-779bfa195071.png)

**Comment by sean-mcmanus** [comment] 2021-01-20 23:18
That issue is "by design". You're using g++ which defaults to compiling for C++ so you get an error, but with a C compiler the code is valid and only results in a warning and we don't support showing warnings currently -- it's tracked by https://github.com/microsoft/vscode-cpptools/issues/828 . If you intend to compile C++ you could use a file ending with .C or .cpp instead of ".c".

**Comment by lakshits11** [comment] 2021-02-10 11:30
Hello, any update ?
Just asking.
Thanks.

**Comment by Colengms** [comment] 2021-02-10 21:40
Hi @lakshits11 .  The original issue repro's in VS, so is being tracked by the following, as we share IntelliSense code with VS: https://developercommunity.visualstudio.com/content/problem/1309633/c-intellisense-gives-no-squiggles-for-missing-at-t.html

It looks like it has not yet been addressed.  I'd suggest up-voting that issue.

**Comment by devumesh** [comment] 2021-09-26 04:50
Even after installing Microsoft C/C++ extension if the syntax error doesn't show up while you are typing/coding, try this....

Go to `.vscode` folder on the project folder you are working and open `settings.json`,

`project-folder -> .vscode -> settings.json`

and make `"C_Cpp.errorSquiggles": "Disabled"` to `"C_Cpp.errorSquiggles": "Enabled"`.

Now the error will show up before compilation.

**Comment by nicocossiom** [comment] 2022-05-04 16:59
Thank you so much I was having trouble finding the solution for this, I was getting tired of having to right click all the time and run "Run Code Analysis on Active File". I must have deactivated the option somehow without meaning too

**Comment by sean-mcmanus** [comment] 2022-05-04 19:50
@nicocossiom The "Run Code Analysis on Active File" is a different feature from C_Cpp.errorSquiggles. You can also set C_Cpp.codeAnalysis.clangTidy.Enabled to `true` (with C_Cpp.codeAnalysis.runAutomatically also set to the default of `true`) to avoid having to run the command explicitly all the time.

**Comment by nicocossiom** [comment] 2022-05-04 21:15
Ohh I see, well I will definitely try it out, thank you so much !

**Comment by bobbrow** [comment] 2024-07-11 23:39
The bug on the VS side was closed as "won't fix"

**Closed as not planned by bobbrow** 2024-07-11 23:39 UTC
Labels: bug, Language Service, Visual Studio
