### ISSUE TITLE
Intellisense Not Autocompleting C Code On M1 Mac

### ISSUE THREAD

**Issue by Ghostkwebb** [microsoft/vscode-cpptools#11315] opened 2023-08-12 08:33 UTC
### Environment

- OS and Version: macOS Sonoma beta 14.0 (23A5301h)
- VS Code Version: 1.81.1
- C/C++ Extension Version: v1.16.3
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
Intellisense doesn't show up when writing C code.

https://github.com/microsoft/vscode-cpptools/assets/61558762/036ad9d8-060e-46b8-8580-4d70fc8ca10c

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/opt/homebrew/bin/gcc",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-gcc-arm64"
        }
    ],
    "version": 4
}
```

### Other Extensions

<img width="317" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/61558762/5594ea37-a786-4deb-9f5e-e9ec897e26f5">

**Comment by Manishchauhan7** [comment] 2023-08-12 09:00
the same thing is happening in the window for C++ it's not auto-completing 
for loop, if while, and other kinds of stuff
can anybody help me

**Comment by sean-mcmanus** [comment] 2023-08-14 17:51
I'm not reproing the issue. What is the result of running `/opt/homebrew/bin/gcc --version`? Can you run C/C++: Log Diagnostics from the Command Palette and look for an incorrect configuration or provide the results from that?

**Comment by Ghostkwebb** [comment] 2023-08-15 04:37
<img width="682" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/61558762/0d177a6b-77d0-4091-a207-017efdb4e1a0">

-------- Diagnostics - 15/08/2023, 10:07:03
Version: 1.16.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "/Users/ghostkwebb/Desktop/C++ Prgrams/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "macos-clang-arm64",
    "compilerPathInCppPropertiesJson": "/usr/bin/clang",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.16.3.0
Translation Unit Mappings:
[ /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin1.cpp ]:
    /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin1.cpp
[ /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin2.cpp ]:
    /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin2.cpp
[ /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin3.cpp ]:
    /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin3.cpp
[ /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin4.cpp ]:
    /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin4.cpp
Translation Unit Configurations:
[ /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin1.cpp ]: not ready
    Process ID: 68495
    Memory Usage: 0 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/local/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/c++/v1
        /Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include
        /Library/Developer/CommandLineTools/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=150000
[ /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin2.cpp ]: not ready
    Process ID: 69755
    Memory Usage: 0 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/local/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/c++/v1
        /Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include
        /Library/Developer/CommandLineTools/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=150000
[ /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin3.cpp ]: not ready
    Process ID: 71513
    Memory Usage: 0 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/local/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/c++/v1
        /Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include
        /Library/Developer/CommandLineTools/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=150000
[ /Users/ghostkwebb/Desktop/C++ Prgrams/Learnin4.cpp ]: not ready
    Process ID: 74316
    Memory Usage: 0 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/local/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/c++/v1
        /Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include
        /Library/Developer/CommandLineTools/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=150000
Total Memory Usage: 0 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 9133

**Comment by Ghostkwebb** [comment] 2023-08-15 04:37
This is also happening for C++ as well

**Comment by sean-mcmanus** [comment] 2023-08-15 19:44
There appears to be some problem with the cpptools-srv process launching correctly, i.e. the logging "Total Memory Usage: 0 MB". Do you still repro this with 1.17.2 that was released yesterday?

I'll check with the team see if anyone else might have an idea what could be going wrong...

**Comment by sean-mcmanus** [comment] 2023-08-16 00:38
@Ghostkwebb What OS are you on?

Our current hypothesis is that it's an issue related to the OS version: macOS Sonoma beta 14.0, possibly a bug with that OS or the Mac build tools might have a bug in regards to the code generated for that OS. Is anyone able to repro the bug with a non-Beta OS?

**Comment by Ghostkwebb** [comment] 2023-08-16 01:25
> @Ghostkwebb What OS are you on?
> 
> Our current hypothesis is that it's an issue related to the OS version: macOS Sonoma beta 14.0, possibly a bug with that OS or the Mac build tools might have a bug in regards to the code generated for that OS. Is anyone able to repro the bug with a non-Beta OS?

I'm on macOS Sonoma beta 14.0 (23A5301h)

**Comment by sean-mcmanus** [comment] 2023-08-16 01:56
@Ghostkwebb Since the only 2 repros we've seen is with that OS, that re-enforces our belief that it's a bug or incompatibility with that OS. You may want to file a bug on Apple and mention the bug doesn't repro with the non-Beta OS? But we'll still try to look into it ourselves to see if it's possible for us to fix.

**Comment by Ghostkwebb** [comment] 2023-08-16 01:57
> @Ghostkwebb Since the only 2 repros we've seen is with that OS, that re-enforces our belief that it's a bug or incompatibility with that OS. You may want to file a bug on Apple and mention the bug doesn't repro with the non-Beta OS? But we'll still try to look into it ourselves to see if it's possible for us to fix.

Thank you very much for the help

**Comment by SimonKagstrom** [comment] 2023-08-19 05:25
Could it be related to #10789 ? In my case (with Ventura), I could workaround that with setting C_Cpp.intelliSenseCacheSize to 0 as per that bug.

**Comment by sean-mcmanus** [comment] 2023-08-23 21:41
Yes, if setting C_Cpp.intelliSenseCacheSize to 0 fixes the issue for anyone, then that should be done. We haven't figured out the cause or repro conditions of this failure with the cache yet. I'm guessing some issue with the memory mapping.

**Comment by Ghostkwebb** [comment] 2023-08-24 04:51
> Could it be related to #10789 ? In my case (with Ventura), I could workaround that with setting C_Cpp.intelliSenseCacheSize to 0 as per that bug.

How do I do this?

**Comment by SimonKagstrom** [comment] 2023-08-24 05:11
@Ghostkwebb Run "Preferences: Open User Settings (JSON)" and add

```    "C_Cpp.intelliSenseCacheSize": 0,```

somewhere in that file.

**Comment by Ghostkwebb** [comment] 2023-08-24 05:33
> @Ghostkwebb Run "Preferences: Open User Settings (JSON)" and add
> 
> ` "C_Cpp.intelliSenseCacheSize": 0,`
> 
> somewhere in that file.

ummmmmmmmm

![Uploading image.png…]()

**Comment by Ghostkwebb** [comment] 2023-08-24 05:37
> 

BRO WTF IT ACTUALLY STARTED WORKING!?!?!?! HUHHHHHHHHHHH

**Comment by Colengms** [comment] 2023-08-25 00:14
Closing this as a duplicate, as https://github.com/microsoft/vscode-cpptools/issues/10789 appears to be the same root cause.  It shouldn't technically be necessary to set `intelliSenseCacheSize` to 0, as arm64 does not support ASLR/PIE, so that feature _should_ be getting correctly disabled internally.  The root cause here appears to be that fallback internally failing.

**Closed as not planned by Colengms** 2023-08-25 00:14 UTC
Labels: Language Service, external, investigate: repro, Feature: Configuration
