### ISSUE TITLE
Inlay Hint settings not available in workspace folder settings.json

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#9782] opened 2022-08-24 07:20 UTC
### Feature Request

Why is that so? What about a single setting to enable all of them by default too?

![Screenshot 2022-08-24 at 10 20 07](https://user-images.githubusercontent.com/47526411/186355972-a6425dbe-a5f2-4ae3-a962-f211502a0561.png)

**Comment by michelleangela** [comment] 2022-08-25 17:43
@Colengms Assigning this to you since you're making changes to settings.

**Comment by sean-mcmanus** [comment] 2022-08-25 18:03
This is "by design". I don't think we want to enable the inlay settings to be changed per-workspace folder unless we have a reason to.

The multiple settings follows the approach taken by TypeScript, i.e. they do not have "a single setting to enable all of them by default".

**Comment by Colengms** [comment] 2022-08-26 18:30
TypeScript's inlayHint settings are all resource scope: [vscode/package.json at 662ba37e022f6339f372f810ee248dddfd6fcfd6 · microsoft/vscode (github.com)](https://github.com/microsoft/vscode/blob/662ba37e022f6339f372f810ee248dddfd6fcfd6/extensions/typescript-language-features/package.json#L271-L286)

The `editor.inlayHints.enabled` setting also appears to be resource scope (though, I can't find where it's declared. When I switch to folder-specific mode in VS Code's settings UI, that setting is still available.)

It seems like our settings should be consistent with those.

**Comment by sean-mcmanus** [comment] 2022-08-26 18:51
Yeah, but they may have a reason for doing that which isn't applicable to our C/C++ experience? I can't think of a reason why a user would want to inlay hints for only a subset of workspace folders.

**Closed as completed** 2022-12-07 18:45 UTC
Labels: Language Service, Feature Request, fixed, Feature: Configuration
