### ISSUE TITLE
"fstream" cannot be found while other headers work

### ISSUE THREAD

**Issue by t-troebst** [microsoft/vscode-cpptools#40] opened 2016-05-06 20:35 UTC
For some reason VS-Code always complains that it cannot find the fstream header even though all other C++ standard library headers work perfectly fine. For example, the following code reproduces the issue:

``` C++
#include <fstream>  // "Include file not found in include directory"
#include <iostream> // no errors...
```

This happens on both Windows (using Visual Studio includes) and OpenSuse even though the fstream header is present in the include directory.

**Comment by sridmad** [comment] 2016-05-06 21:04
Not sure why we are seeing the behavior. Thanks for the report. We will investigate.

**Comment by shensun** [comment] 2016-05-07 01:58
Following steps fixed Mac VSCode.

1: in cpp/cxx file, Press F8 to indicate where shows the Error.
2: Move your Mouse to that H file. a yellow light Icon will shows bellow H file.
3. Press that yellow icon.
3. VSCode lead you create a json File in /${workspaceRoot}/.vscode/c_cpp_properties.json

my configurations:
`{
    "configurations": [
        {
            "name": "Mac",
            "includePath": ["/usr/include","/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include"]
        },
        {
            "name": "Linux",
            "includePath": ["/usr/include"]
        },
        {
            "name": "Win32",
            "includePath": ["c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include"]
        }
    ]
}
`

**Comment by shensun** [comment] 2016-05-07 02:03
Following steps fixed Mac VSCode.

1: in cpp/cxx file, Press F8 to indicate & shows the Error location.
2: move your mouse to include fileName. a tooltip Icon will shows bellow.
3. press and config  c_cpp_properties.json.
3. VSCode lead you create a json file in /${workspaceRoot}/.vscode/c_cpp_properties.json

my configurations:
"name": "Mac",
 "includePath": ["/usr/include","/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include"]`

**Comment by choury** [comment] 2016-05-13 05:00
On my machine, it can't find any STL header
![image](https://cloud.githubusercontent.com/assets/4332542/15238433/8bf48efe-190a-11e6-94e4-b458028bd45c.png)
While the path is correct:
![image](https://cloud.githubusercontent.com/assets/4332542/15238449/aa707758-190a-11e6-94b2-1f1a13f89568.png)

**Comment by t-troebst** [comment] 2016-05-13 11:54
On Windows I had to change the slashes to backslashes and on Linux you have to add the include path for the STL headers (something like "/usr/include/c++/{version}") to get the headers (except for fstream) to work.

**Comment by mirao** [comment] 2016-06-07 18:32
I have the same issue with `#include <stdio.h>` on Ubuntu 16.04. I get the message "_Include file not found in include directory_". The path in config file is correct:

```
{
            "name": "Linux",
            "includePath": ["/usr/include"]
}
```

```
$ ls -l /usr/include/stdio.h
-rw-r--r-- 1 root root 31365 dub 15 00:09 /usr/include/stdio.h
```

I'm able to compile and run the program.

Used SW:
- Ubuntu 16.04
- VSC 1.2.0
- CPP extension 0.6.0

**Update:** The issue doesn't happen in CPP 0.6.1

**Comment by mirao** [comment] 2016-06-07 18:48
Well, I've just updated CPP extension to 0.6.1 and the issue has disappeared. So you can ignore my issue. Thanks.

**Comment by sridmad** [comment] 2016-06-25 00:38
@t-troebst do you still see the behavior with latest version of the extension?

**Comment by t-troebst** [comment] 2016-06-25 20:36
No, at least on Linux it appears to work fine now.

**Comment by sridmad** [comment] 2016-06-27 17:14
Closing the issue. If you seen it in other contexts please reopen the issue

**Closed as completed by sridmad** 2016-06-27 17:14 UTC
Labels: bug, Language Service

**Comment by rhoot** [comment] 2016-07-13 04:37
I'm seeing this on OSX with 0.7.1.
<img width="327" alt="screen shot 2016-07-12 at 21 33 39" src="https://cloud.githubusercontent.com/assets/1258798/16791938/60dc3be8-4878-11e6-8664-7990e4a28036.png">

As for everyone above me, the path is correct:

``` json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": ["/usr/include"]
        },
```

```
$ ls -l /usr/include/assert.h /usr/include/stdint.h
-r--r--r--  1 root  wheel  4197 Oct 28  2015 /usr/include/assert.h
-r--r--r--  1 root  wheel  5408 Oct 28  2015 /usr/include/stdint.h
```

**Comment by rhoot** [comment] 2016-07-13 04:44
Actually, I added a slash after `/usr/include` (to get `/usr/include/`) just for testing. It didn't make any difference, but once I removed the slash again and saved it magically started working. It is no longer telling me it can't find the headers.

**Comment by informatik01** [comment] 2016-07-14 23:50
I have Visual Studio Code **version 1.3.1** installed on Windows 10 and still see this issue despite the fact that the path to the include directory is correct:

```
{
    "name": "Win32",
    "includePath": ["c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include"]
}
```

**Comment by informatik01** [comment] 2016-07-16 00:45
### Solution (for Windows)

OK, I have managed to solve this issue on _Windows 10_. I found the answer on Microsoft's Visual Studio forum [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/0f580a73-6f11-4aa6-abbe-6bf1438734c2/standard-files-stddefh-stringh-missing-in-visual-studio-2015-rc?forum=vclanguage#answers).

The key was a quote from an article ["Introducing the Universal CRT"](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/):

> "The **headers**, sources, and libraries are **now distributed as part of a separate
> Universal CRT SDK**. This SDK is included with Visual Studio; it is installed by
> default to **C:\Program Files (x86)\Windows Kits\10**."

I needed to include an additional directory (besides the "c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include"). 

Look for the following directory on your computer:

> C:\Program Files (x86)\Windows Kits\10\Include

If you have it, you may find several folders there. I chose the one that had the latest "Modified date". In there you'll find a ton of C headers. I ended up adding the following include directory (in addition to the existing one):
**"C:/Program Files (x86)/Windows Kits/10/Include/10.0.10586.0/ucrt"**

---

Here is an excerpt from my final configuration in the _c_cpp_properties.json_ (NB! use forward slashes in the path even on Windows):

``` json
{
    "name": "Win32",
    "includePath": ["c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10586.0/ucrt"]
}
```

No more complaining about "_Include file not found in include directory_" from Visual Studio Code!

**Comment by albtdd** [comment] 2016-07-19 14:15
I have the same issue:
![main](https://cloud.githubusercontent.com/assets/12040245/16953055/ec82d03c-4dcb-11e6-9bf2-b973375b8957.png)

SDL is in the right direcory (usr/include/SDL):
![c_cpp_config](https://cloud.githubusercontent.com/assets/12040245/16953060/f2ed9b28-4dcb-11e6-9491-418fed23de52.png)

![usr_include](https://cloud.githubusercontent.com/assets/12040245/16953062/f63699d8-4dcb-11e6-9372-b395e43d2c0e.png)

**Comment by hamaney** [comment] 2016-09-20 10:43
I have the same issue on El Capitan(10.11.6) running VSC 1.5.2

**Comment by hak8or** [comment] 2016-09-21 01:03
I had a similar issue to this on linux. I noticed that when I were to save the generated `c_cpp_properties.json` and restarted vscode, it started to work. So for all of you with issues, try the following to generate the json file as per the getting started guide [here](https://code.visualstudio.com/docs/languages/cpp#_getting-started).

> To enable code completion and navigation, you will need to generate a c_cpp_properties.json file:
> 
> ```
> 1. Hover over any green squiggle in a source file (e.g. a #include statement).
> 2. Click the lightbulb that appears underneath the mouse cursor.
> 3. Click Add include path to settings.
> ```
> 
> This will generate a c_cpp_properties.json file that allows you to add additional include paths to properly enable code navigation and auto-completion.

Save the file via the ctrl-s shortcut, and then restart visual code. You should get the autocomplete to start working at this point.

**Comment by MeirionHughes** [comment] 2016-09-23 12:41
Same issue here; the problem would appear to be case differences in the file names. 

![example](https://cloud.githubusercontent.com/assets/3584509/18785951/4743e81c-8193-11e6-99f6-6aaaec81c0fc.png)

all the includes are lower-case, but the files themselves are a mix of cases. If you rename the files to all lower and restart vscode, they are found.

**Comment by sean-mcmanus** [comment] 2016-09-23 15:55
On Linux, the #include paths are case-sensitive. It looks like we treat #include paths as case-sensitive on Windows too, but they are not. This might be a different issue from what others are reporting.

**Comment by sean-mcmanus** [comment] 2016-09-23 16:48
Actually, I was hitting a different bug in which duplicate missing #include are not marked. The case detection on Windows appears to be correct, so I'm not able to repro any casing problem on Windows. However, I'm seeing a problem in which certain workspaces don't recognize #include <string> even when the includePaths are identical.

**Comment by hamaney** [comment] 2016-09-24 10:54
Update 👍
I found out that my issue was caused by opening my cpp files from the operation system file system, Finder for Mac as an example. The problem disappeared when I opened the project folder using "Open Folder" then I selected my .cpps from there.

I hope this will help :)

**Comment by rharriso** [comment] 2017-09-13 20:23
On osx I had to add `/usr/include/*` to the include path:

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                "/usr/local/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                "/usr/include",
                "/usr/include/*",
                "${workspaceRoot}"
            ],
/* more config */
}

```
