### ISSUE TITLE
Intellisense seems to be ignoring includePath configurations

### ISSUE THREAD

**Issue by mhhollomon** [microsoft/vscode-cpptools#11006] opened 2023-05-24 23:05 UTC
### Environment

- OS and Version:  Windows 11 Pro 10.0.22621 Build 22621
- VS Code Version: Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
- C/C++ Extension Version:  V1.15.4
- If using SSH remote, specify OS of remote machine:  N/a

### Bug Summary and Steps to Reproduce

Bug Summary:  Intellisense seems to be ignoring two recursive directory entries in the c_cpp_properties.json file.
It complains that headers can not be found. But cmake can certainly find them during the build.

![image](https://github.com/microsoft/vscode-cpptools/assets/43250483/3809d765-f0cc-4403-8659-ba20adacb487)

Steps to reproduce:
I cloned this following repo and see the error in the main.cpp file.

https://github.com/lszl84/wx_cmake_template

Expected behavior:
Intellisense should be able to find the wxWidget include files.

### Configuration and Logs

```shell
--- properties ---
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/src/**",
                "${workspaceFolder}/build/stage/include/**"
            ],
            "defines": [
                "__WXMSW__",
                "_UNICODE",
                "_DEBUG"
            ],
            "compilerPath": "cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x64",
            "configurationProvider": "ms-vscode.cmake-tools",
            "compilerArgs": []
        },

--- Diagnostics ---

-------- Diagnostics - 5/24/2023, 7:00:19 PM
Version: 1.15.4
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "c:\\Users\\<user>\\Documents\\GitHub\\wx_cmake_template/src/**",
        "c:\\Users\\<user>\\Documents\\GitHub\\wx_cmake_template/build/stage/include/**"
    ],
    "defines": [
        "__WXMSW__",
        "_UNICODE",
        "_DEBUG"
    ],
    "compilerPath": "cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerArgs": [],
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "cl.exe",
    "configurationProviderInCppPropertiesJson": "ms-vscode.cmake-tools",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/src/**",
            "${workspaceFolder}/build/stage/include/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "c:/users/<user>/documents/github/wx_cmake_template/build/cmakefiles",
        "c:/users/<user>/documents/github/wx_cmake_template/build/subprojects/stamp/wx_cmake_template_core"
    ],
    "compilerPath": "c:/program files/microsoft visual studio/2022/community/vc/tools/msvc/14.36.32532/bin/hostx64/x64/cl.exe",
    "compilerArgs": [],
    "compilerFragments": []
}
Translation Unit Mappings:
[ C:\Users\<user>\Documents\GitHub\wx_cmake_template\src\main.cpp ]:
    C:\Users\<user>\Documents\GitHub\wx_cmake_template\src\main.cpp
Translation Unit Configurations:
[ C:\Users\<user>\Documents\GitHub\wx_cmake_template\src\main.cpp ]:
    Process ID: 15924
    Memory Usage: 49 MB
    Compiler Path: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe
    Includes:
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\atlmfc\include
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include
        C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\Include\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
    Other Flags:
        --using_directory
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\lib\x64
        --using_directory
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\lib\x64
        --using_directory
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\lib\x86\store\references
        --using_directory
        C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0
        --using_directory
        C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0
        --using_directory
        C:\Windows\Microsoft.NET\Framework64\v4.0.30319
Total Memory Usage: 49 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 5222
Number of files parsed: 3
```

**Comment by browntarik** [comment] 2023-05-30 21:17
This is by design, includePath isn't used if configurationProvider is not set. Please set the mergeConfigurations setting in cpp_properties.json to true if you would like to add the includePath. Closing this issue as this is by design behavior.

**Closed as completed by browntarik** 2023-05-30 21:17 UTC
Labels: Language Service, by design
