### ISSUE TITLE
IntelliSense can`t recognize the #include MACRO(No definition found)

### ISSUE THREAD

**Issue by h2s0109** [microsoft/vscode-cpptools#6579] opened 2020-11-25 12:22 UTC
**Describe the bug**
- OS and Version: WIN10
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.1

**Steps to reproduce**
1. define the MCUCARD_TYPE_PATH "Test2.h" at Test1.h
![image](https://user-images.githubusercontent.com/21095801/100226531-3b69f680-2f63-11eb-84ef-962fc63bc002.png)
2. #include MCUCARD_TYPE_PATH at C file
![image](https://user-images.githubusercontent.com/21095801/100226666-648a8700-2f63-11eb-9692-b5eb0ae1bb7e.png)
3. **No definition found massage**
![image](https://user-images.githubusercontent.com/21095801/100226706-72400c80-2f63-11eb-9fc8-f6d7db37facb.png)
I attach the file for your analysis.
[test.zip](https://github.com/microsoft/vscode-cpptools/files/5596593/test.zip)
Thanks for your support!

**Comment by Colengms** [comment] 2020-11-25 22:04
Hi @h2s0109 .  Thanks for reporting this.  This appears to be a dupe of https://github.com/microsoft/vscode-cpptools/issues/5261 .    So, closing this as a dupe.  Let me know if I'm mistaken.

**Closed as completed by Colengms** 2020-11-25 22:04 UTC
Labels: duplicate, Language Service
