### ISSUE TITLE
the prelaunchtask c/c++: gcc build active file terminated with exit code -1

### ISSUE THREAD

**Issue by Y4M06** [microsoft/vscode-cpptools#11927] opened 2024-02-04 19:04 UTC
Type: <b>Bug</b>

1. Write code in a new file
2. press on run file on the top right.
3. Error: "the prelaunchtask c/c++: gcc build active file terminated with exit code -1"
4. run the file.

Expected result: compile the file and run it.

Not sure if it has to do with the flags, but apparently on linux it doesn't work, I tried another extension which used these flags and it worked like a charm  ["-g3", "-Wall", "-Wextra", "${file}", "-o", "\"${fileDirname}/${fileBasenameNoExtension}\""]

Here is an e.g. from the extension that worked "Executing task: g++ -Wall -Wextra -g3 /run/media/yamo/EDU/Extracurriculars/OSC/S&T/DS/wordOnThePaper.cpp -o /run/media/yamo/EDU/Extracurriculars/OSC/S&T/DS/output/wordOnThePaper 
"
Extension name: C/C++ Compile Run

Extension version: 1.18.5
VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:27:46.147Z)
OS version: Linux x64 6.6.10-1-MANJARO
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics (12 x 3984)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|15.00GB (6.24GB free)|
|Process Argv|--unity-launch --crash-reporter-id 7162d89c-d2bf-40c9-896e-a9a1c34f045e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
0bi6i642:30951795
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928
e3gdj431:30956216

```

</details>

**Comment by browntarik** [comment] 2024-02-06 19:19
Could you please provide more information about how you are getting this error? It is likely that you have not correctly configured your task.json with the appropriate arguments.

Example: 
![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/4f869671-1ec6-45d3-982d-a6ea698f0a40)

**Comment by Yamo406** [comment] 2024-02-07 11:07
I haven't modified the tasks.json I let the extension do it automatically for me. here is a screenshot of the tasks.json
![Screenshot_20240207_130246](https://github.com/microsoft/vscode-cpptools/assets/93231355/fb17d3da-f818-48a1-b9d3-c034e333cc85)

I am not sure, maybe it has something to do with me using Linux or the path of the file is not detected.

**Comment by browntarik** [comment] 2024-02-07 20:23
Can you provide the output from the error window including the command that is generated by the run and debug command?

Example:
![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/7ad7573a-9f80-4c4a-89a9-6667d9b0e7f7)

**Comment by Yamo406** [comment] 2024-02-11 14:28
@browntarik sorry for the late reply.
![image](https://github.com/microsoft/vscode-cpptools/assets/93231355/2f14e55c-3a09-461c-a3b2-0a8c8d52dec8)

**Comment by browntarik** [comment] 2024-02-12 19:01
It looks like there is an issue because of the '&' character in your path. Could you try renaming your directory to remove it and try the executable again? 

If you would like to keep the ampersand you may have to escape it in the file path, but it is generally not recommended practice to use special characters in file paths.

**Comment by Yamo406** [comment] 2024-02-12 19:20
@browntarik so it worked when I indeed changed the ampersand character, I have another question when I use the the GCC from the dropdown it doesn't work, that's on a different directory but the g++ works as intended, does that have to do with Linux?

Here are the errors:
![Screenshot_20240212_211748](https://github.com/microsoft/vscode-cpptools/assets/93231355/1a179f84-66d0-4626-a28f-5f9a2674f75d)
![Screenshot_20240212_211801](https://github.com/microsoft/vscode-cpptools/assets/93231355/29ec66f5-7117-422f-bd99-4e5e6324c9ad)

**Comment by Yamo406** [comment] 2024-02-12 19:40
The g++ compiler works just fine. 
If I understand correctly the gcc is for c projects and g++ for c++ projects?

**Comment by Yamo406** [comment] 2024-02-12 19:52
Awesome thanks for taking the time to solve the problem and answer my questions.

**Comment by browntarik** [comment] 2024-02-12 19:54
I am glad I was able to help, I will now close this issue but it will be available for future reference.

**Closed as completed by browntarik** 2024-02-12 19:54 UTC
Labels: Language Service, more info needed, Feature: Configuration

**Comment by dheerajparashar** [comment] 2024-03-27 13:18
Hello there, I am facing the same error but on my Windows laptop. 
![image](https://github.com/microsoft/vscode-cpptools/assets/63899076/094ec5f6-6e6c-4823-996b-1f91ff7af3ee)

**Comment by Yamo406** [comment] 2024-03-30 12:24
@dheerajparashar Hey there, it seems that in your case it's giving permission denied, I would have 2 solutions that I would try first.
1. change the location of the project.
2. change the permission of the file.

The easiest is to change the project's location as it can be tedious to change the permission of the folder especially since it's in the C: folder and I haven't been having that much look with permissions on Windows.

**Comment by dheerajparashar** [comment] 2024-03-30 21:37
Thanks mate I will try this and let you know what happens.
