### ISSUE TITLE
Watchpoints support

### ISSUE THREAD

**Issue by bojomojo** [microsoft/vscode-cpptools#6111] opened 2020-09-11 06:54 UTC
Type: Debugger

This is a feature request to support debug watchpoints

all debuggers support it, why not have vscode cppdbg interface with gdb/lldb to support it.

**Comment by WardenGnaw** [comment] 2020-09-12 01:23
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/1410

**Closed as completed by WardenGnaw** 2020-09-12 01:23 UTC
Labels: duplicate
