### ISSUE TITLE
Do not edit every workspace with files inside .vscode folder

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-cpptools#25] opened 2016-04-21 19:26 UTC
1. Install VSCode c++ extension
2. Any workspace I open in vscode will get modified, even if it does not have C++ -> files will be added inside the .vscode folder

Optimally the extension would not touch the content of any workspace.
If that is not possible the extension should only touch the content of C++ workspaces. I believe this could be achieved by being activated on the event `onDebug:cpp`. This event will be availble in the April release.

**Comment by sridmad** [comment] 2016-04-21 20:31
Duplicate of #6.

**Closed as completed by sridmad** 2016-04-21 20:31 UTC
