### ISSUE TITLE
Format on save takes way too long with cmake extension enabled.

### ISSUE THREAD

**Issue by christianbrugger** [microsoft/vscode-cpptools#12221] opened 2024-04-15 10:42 UTC
### Brief Issue Summary

When using format on save `"editor.formatOnSave": true` with `CMake Tools` extension enabled the save often takes 10 seconds or even longer. For the formatting itself I am using `clang-format-17`.

[Slow - CMake Extension Enabled.webm](https://github.com/microsoft/vscode-cmake-tools/assets/235346/8a075654-af39-4308-a879-48ccaae97544)

Running `clang-format-17` itself takes 20ms on this file when launched from the terminal.

```
$ time clang-format-17 -i src/component/simulation/history_calculation.h

real	0m0.023s
user	0m0.007s
sys	0m0.015s
```

**Comment by sean-mcmanus** [comment] 2024-04-18 21:38
@christianbrugger What is your "editor.formatOnSaveMode"?

**Comment by sean-mcmanus** [comment] 2024-04-19 21:36
@christianbrugger What version of the C/C++ extension are you using? Also, with `"C_Cpp.loggingLevel": "Debug"` set, what is the last "LSP (invoked)" line that in the C/C++ logging pane when it's stuck formatting? It should be `LSP: (invoked) cpptools/formatDocument` if it's stuck on a different operation.

**Comment by sean-mcmanus** [comment] 2024-04-19 22:47
@christianbrugger My guess is you're hitting a combination of https://github.com/microsoft/vscode-cpptools/issues/6156 and https://github.com/microsoft/vscode-cpptools/issues/12169 . You'd see logging like

```
Intellisense update pending for: 
LSP: (invoked) textDocument/didChange: 
LSP: (invoked) textDocument/completion (or some other IntelliSense operation): 
Populating file name cache...
...
Done populating filename cache. Elapsed time: 
sending compilation args for
...
LSP: (invoked) cpptools/formatDocument
```

**Comment by christianbrugger** [comment] 2024-04-20 07:00
@sean-mcmanus I am using C/C++ version `1.20.1 (pre-release)`.

When enabling `"C_Cpp.loggingLevel": "Debug"` it hangs at actually at several points:
```
LSP: (received) cpptools/didChangeTextEditorSelection
LSP: (received) textDocument/didChange: file:istory_calculation.h
LSP: (received) cpptools/didChangeTextEditorSelection
//                                  <============== hangs here 1.5 seconds
LSP: (received) textDocument/willSaveWaitUntil: file:istory_calculation.h (id: 366)
LSP: (invoked) textDocument/willSaveWaitUntil: file:istory_calculation.h (id: 366)
LSP: Sending response (id: 366)
willSaveWaitUntil: 0ms
LSP: (received) cpptools/getCodeActions: file://history_calculation.h (id: 367)
LSP: (received) cpptools/formatDocument: file://history_calculation.h (id: 368)
LSP: (received) cpptools/getDocumentSymbols: file://history_calculation.h (id: 369)
LSP: (invoked) cpptools/getDocumentSymbols: file://history_calculation.h (id: 369)
LSP: (received) cpptools/getDocumentSymbols: file://history_calculation.h (id: 370)
LSP: $/cancelRequest (cpptools/getDocumentSymbols, id: 365)
LSP: (invoked) cpptools/getDocumentSymbols: file://history_calculation.h (id: 370)
sending 2 changes to server
//                                  <============== hangs here 6 seconds
Database safe to open.
LSP: Sending response (id: 369)
LSP: Sending response (id: 370)
//                                  <============== hangs here 8 seconds
Update IntelliSense time (sec): 22.524
LSP: (invoked) cpptools/fileChanged: file://history_calculation.h
LSP: (invoked) cpptools/getCodeActions: file://history_calculation.h (id: 363)
LSP: (invoked) textDocument/didChange: file://history_calculation.h
LSP: (invoked) textDocument/didChange: file://history_calculation.h
LSP: (invoked) cpptools/didChangeTextEditorSelection
LSP: (invoked) cpptools/getCodeActions: file://history_calculation.h (id: 367)
//                                  <============== hangs here 1 seconds
LSP: Sending response (id: 367)
LSP: (invoked) cpptools/formatDocument: file://history_calculation.h (id: 368)
Formatting document: file://history_calculation.h
Formatting Engine: clangFormat
/usr/bin/clang-format-17 -style=file -fallback-style=LLVM --Wno-error=unknown -assume-filename=history_calculation.h
LSP: Sending response (id: 368)
```
[formatting-file-log.webm](https://github.com/microsoft/vscode-cpptools/assets/235346/45b3825d-9931-43a9-81d5-57a7d00ed6d3)

To me it looks like formatting is sometimes blocked until IntelliSense is done, leading to large delays. Formatting does not depend on IntelliSense so this could be resolved by better scheduling of those tasks.

Issue https://github.com/microsoft/vscode-cpptools/issues/6156 speaks about the same problem in a the context of on-type formatting, where similar delays are reported. One suggested fix was to make on-type formatting not depend on file formatting and use a simpler, e.g. Python based, method. Such a fix would not help here. Fixing the formatter issue should have a positive impact on issue https://github.com/microsoft/vscode-cpptools/issues/6156 at least for files where clang-format times are near instant.

Issue https://github.com/microsoft/vscode-cpptools/issues/12169 is about the time of IntelliSense being to large in general, not using multiple threads and lacking caching. I think it is only remotely related. While a speedup would make the lags less, the issue here seems to be related to both formatting and IntelliSense competing sometimes, not the time of IntelliSense itself.

**Comment by sean-mcmanus** [comment] 2024-04-22 19:26
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6156 -- I've updated the title to not mention "on type" formatting, since the root issue occurs for all formatting.

The formatting is stuck behind a 22 second IntelliSense update: `Update IntelliSense time (sec): 22.524`. The other logging is from getDocumentSymbol which is already in a separate thread. This could also be fixed by moving formatting into a separate thread from the main one that also handles potentially slow IntelliSense operations.

**Closed as not planned by sean-mcmanus** 2024-04-22 19:26 UTC
Labels: duplicate, Language Service, performance, Feature: Code Formatting
