### ISSUE TITLE
cpp.hint content is showed in help window

### ISSUE THREAD

**Issue by ihor-rud** [microsoft/vscode-cpptools#1894] opened 2018-04-27 16:38 UTC
Hi,
Sometimes cpp.hint content is showed when I want to check string data.
I use Visual Studio Code 1.22.2 and cpptool 0.16.1

![screenshot from 2018-04-27 18-14-09](https://user-images.githubusercontent.com/31574816/39373119-dd8e6360-4a46-11e8-9acb-6aeac3e67560.png)
[code_example.txt](https://github.com/Microsoft/vscode-cpptools/files/1955841/main.txt)

**Comment by bobbrow** [comment] 2018-04-27 17:08
This sounds like a duplicate of #1577

**Closed as completed by bobbrow** 2018-04-27 17:08 UTC
Labels: bug, duplicate, Language Service
