### ISSUE TITLE
Inline view of macros should contain its comment.

### ISSUE THREAD

**Issue by gtianw** [microsoft/vscode-cpptools#9584] opened 2022-07-15 12:23 UTC
### Feature Request

When I hover over a macro, I don't see its comment in the inline view, regardless of the location of the comment.
![image](https://user-images.githubusercontent.com/91190888/179221992-af145afa-9c40-450f-affd-e13b425740b8.png)
![image](https://user-images.githubusercontent.com/91190888/179222108-ad6b1cc3-aca6-4409-b705-d05a156846f1.png)

I'm not sure which type this issue belongs to. 'Feature Request', 'Bug', or 'My configuration'?

**Comment by sean-mcmanus** [comment] 2022-07-15 17:53
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/8320 . We have a fix pending.

**Closed as not planned by sean-mcmanus** 2022-07-15 17:53 UTC
Labels: bug, Language Service, Feature: Doc comments, verified

**Comment by sean-mcmanus** [comment] 2022-07-20 02:08
Fixed with 1.11.3 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.11.3
