### ISSUE TITLE
Crash when including QtCore

### ISSUE THREAD

**Issue by pe224** [microsoft/vscode-cpptools#1497] opened 2018-01-28 12:27 UTC
* Windows 10 Home, 1709, 16299.192
* MinGW 32bit toolchain (came bundled with standard Qt install)
*   VSCode
    Version 1.20.0-insider
    Commit 89264676133f25c4990706c889a48eab277544f7
    Date 2018-01-26T05:15:09.585Z
    Shell 1.7.9
    Renderer 58.0.3029.110
    Node 7.9.0
    Architecture x64
* cpptools 0.14.6
* issue persists after disabling all other extensions

I could reduce the crash to the following minimal configuration:
c_cpp_propterties.json
```json
{
    "configurations": [
        {
            "name": "Win32",
            "intelliSenseMode": "clang-x64",
            "includePath": [
                "${workspaceRoot}",
                "C:/Qt/5.10.0/mingw53_32/include/QtCore"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "__GNUC__=5",
                "__cdecl=__attribute__((__cdecl__))"
            ],
            "browse": {
                "path": [
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```
test.cpp
```c++
#include <QString>
```

the extension reports
```
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
  Folder: C:/PATH/ will be indexed
Checking for syntax errors: file:///c%3A/PATH/test.cpp
Discovering files...
  Processing folder (recursive): C:/PATH/
  Discovering files: 1 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Done parsing open files.
Failed to read response from server: 18
IntelliSense client has disconnected from the server - C:\PATH\TEST.CPP
```

Removing QtCore in includePath fixes it, but leaves "include path not found" for `<QString>`. Adding the QtCore back in reproduces crash.

**Comment by sean-mcmanus** [comment] 2018-01-29 09:01
Thanks for the repro details. We've fixed 3 crashes in our pending update, but I'll see if I can repro this.

**Comment by sean-mcmanus** [comment] 2018-01-29 21:52
On Linux with QT 5.6, I need to add the parent "include" folder in order to get the QtCore paths to resolve. Does adding that path fix your issue? (e.g. `"C:/Qt/5.10.0/mingw53_32/include"`).

**Comment by sean-mcmanus** [comment] 2018-01-30 01:07
I was able to repro the crash -- fortunately, in our pending 0.15.0-insiders release the crash is already fixed (i.e. duplicate of one of the other crashes we fixed). We'll try to make it available in the next few days.

**Comment by sean-mcmanus** [comment] 2018-02-06 02:18
The fix should be in our preview .vsix at https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.15.0-insiders (the final release is planned for next week).

**Comment by pe224** [comment] 2018-02-07 09:08
Cool. I'll re-check after release and let you know.

**Comment by sean-mcmanus** [comment] 2018-02-15 22:50
@pe224 We believe 0.15.0 has the fix (i.e. it stopped reproing for me). Let us know if the issue is still reproing for you.

**Closed as completed by sean-mcmanus** 2018-02-15 22:50 UTC
Labels: bug, duplicate, Language Service, fixed, reliability

**Comment by pe224** [comment] 2018-02-16 08:54
Can confirm. Thanks for the fix!
