### ISSUE TITLE
Find all Reference performance

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#4789] opened 2019-12-26 06:25 UTC
Hi Sean,
Currently cpptools parse related code symbols until we use "Find All Reference". It give reference results very slowly if your project is large. Cpptools can parse all code files and store them in some ways so that it can give results quickly ? Even though it will take long time to parse all files. I think it's worthy.

**Comment by sean-mcmanus** [comment] 2019-12-27 23:24
We need to know what the status UI is saying when the majority of the slowness is occurring. Is it saying "files confirmed"? We can only store "tag parse" results in our database (which gets us a small set of files with potential lexical references) and not IntelliSense parsing results (which is required to confirm the lexical references).

**Comment by Lennon925** [comment] 2019-12-28 06:22
> We need to know what the status UI is saying when the majority of the slowness is occurring. Is it saying "files confirmed"? We can only store "tag parse" results in our database (which gets us a small set of files with potential lexical references) and not IntelliSense parsing results (which is required to confirm the lexical references).

Yes, it's saying "files confirmed" when slowness is occurring. In a large project, usrs often use "find all references". If it's too slowly, it will influence reading code efficiency seriously.

**Comment by sean-mcmanus** [comment] 2019-12-30 20:31
There is no way for us to store the files confirmation results. If the number of files that need to be confirmed is large, then using a computer with more cores could help, i.e. a machine with 16 cores would be able to confirm references up to 4 times faster than a 4 core machine. The processing time during confirming is mostly spent on parsing the TU.

These 2 issues could help reduce the number of files that need to be confirmed.
https://github.com/microsoft/vscode-cpptools/issues/4708
https://github.com/microsoft/vscode-cpptools/issues/4617

https://github.com/microsoft/vscode-cpptools/issues/4038: This would only speed up cases where the 2nd Find All References needs to confirm in TUs that got created from the 1st Find All References. However, the manual workaround is to open the files you want "cached".

**Comment by yangshangde** [comment] 2019-12-31 07:04
@sean-mcmanus So no possible way to speed up the performance? Our project has thousands of files, the tool is fantastic only except for the finding reference performance...

**Comment by sean-mcmanus** [comment] 2019-12-31 19:49
@yangshangde The number of files in a project shouldn't affect Find All References performance in the "confirmation" stage -- you could have 100 files or a million and the time it takes to confirm references in 10 files should be around the same.

Our telemetry indicates that Find All References performance is not a major problem for most users and uses, although potentially some users might be hitting bugs or special cases (I'm not aware of any known issues though). What sort of timing are you seeing (i.e. number of files to search, time to search, number of files to confirm, time to confirm)?

ipch files are not getting used by the Find All References TUs if they exist already, so it might be possible to use those to speed up confirmation. UPDATE: Looks like our IntelliSense code doesn't have a read-only mode for ipch caches, so it would have to be added (which is unlikely to happen any time soon).

**Comment by sean-mcmanus** [comment] 2020-01-03 20:32
If your core count is too high compared to memory used/available, doing Find All References could cause memory thrashing and reduced performance. I've filed an issue tracking improving this at https://github.com/microsoft/vscode-cpptools/issues/4811.

**Comment by bobbrow** [comment] 2020-01-09 22:23
We're using #4051 to track performance issues with find all references. Closing this one as a duplicate.  If you have specific information about your workspace that we can use to tune our algorithms, please add it to that issue.

Thank you!

**Closed as completed by bobbrow** 2020-01-09 22:23 UTC
Labels: Language Service, Feature Request, performance, Feature: Find All References
