### ISSUE TITLE
The breakpoint does not work

### ISSUE THREAD

**Issue by benbenji** [microsoft/vscode-cpptools#4797] opened 2019-12-30 01:48 UTC
Type: Debugger

**Describe the bug**
- OS and Version:10.15.2  Catalina
- VS Code Version:1.41
- C/C++ Extension Version:0.26.3-insider2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
when I use the debug function of cmake tools, I find the breakpoint don't work
**To Reproduce**

![image](https://user-images.githubusercontent.com/2499988/71565334-9e9ba080-2ae8-11ea-87a7-c292a9913995.png)

It seems that the output of the debug is right as follow ,but it does not stop at breakpoint.

![image](https://user-images.githubusercontent.com/2499988/71565354-ef12fe00-2ae8-11ea-84eb-d951eff2eecf.png)
I clearly remember that this function works in preview version ,I don't know whether it is caused by the update of mac OS  or that of cpptools.
launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "clang++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/app/${fileBasenameNoExtension}",
            "args": [],
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "clang++ build active file",
            "stopAtEntry": true 
        }
    ]
}
setting.json:
"cmake.debugConfig": {
        "stopAtEntry": true,
        "MIMode": "lldb",
        "miDebuggerPath": "/Users/apple/.vscode/extensions/ms-vscode.cpptools-0.26.3-insiders2/debugAdapters/lldb/bin/lldb-mi",
        "logging": {
                "trace": true,
                "engineLogging": true,
                "traceResponse": true
        }
    }
Can anybody help me solve that problem? Thank you very much

**Comment by WardenGnaw** [comment] 2019-12-30 19:31
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/3829

**Closed as completed by WardenGnaw** 2019-12-30 19:31 UTC
Labels: duplicate, debugger
