### ISSUE TITLE
The version 0.23.0 can not find path, if path have Chinese.

### ISSUE THREAD

**Issue by LMissher** [microsoft/vscode-cpptools#3618] opened 2019-05-09 03:00 UTC
Type: Debugger
**If path have Chinese the debugger will wrong, and the version 0.22.1 do not have this error.**

**Describe the bug**
- OS and Version: Win10
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.23.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "preLaunchTask": "build",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe", //调试的.exe文件所在位置
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}", //调试将在此目录下进行
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "D:\\software\\CodeBlocks\\MinGW\\bin\\gdb32.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
        {
            "name": "LaunchDebug",
            "preLaunchTask": "build1",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe", //调试的.exe文件所在位置
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}", //调试将在此目录下进行
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "D:\\software\\CodeBlocks\\MinGW\\bin\\gdb32.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

.*

**Comment by pieandcakes** [comment] 2019-05-09 16:13
@LMissher Thank you for reporting your issue. The root of the problem is with `gdb`, which you can see in [this comment](https://github.com/microsoft/vscode-cpptools/issues/602#issuecomment-489342032). This is a duplicate of #602 and will need to wait for `gdb` to fix the problem.

**Comment by pieandcakes** [comment] 2019-05-09 16:13
Duplicate of #602

**Closed as completed by pieandcakes** 2019-05-09 16:13 UTC
Labels: duplicate, debugger, external
