### ISSUE TITLE
Intellisense broken when using Clang (GNU CLI)

### ISSUE THREAD

**Issue by NoMore201** [microsoft/vscode-cpptools#7529] opened 2021-05-16 12:44 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 2004
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.3.1
- Other extensions you installed (and if the issue persists after disabling them): Clang-Format, Cmake Tools, Cmake, Remote - WSL
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Problems happens when working on CMake based projects on VScode, using Clang 11 installed from visual studio installer (selected `Clang (GNU CLI)` as kit). Last time I opened my local project (nearly a month ago, I cannot tell exactly) everything was fine. Now IntelliSense is not working. When I open the project I get message `IntelliSenseMode changed from windows-msvc-x64 to windows-clang-x64 based on arguments and compilerPath "c:/program files (x86)/microsoft visual studio/2019/buildtools/vc/tools/llvm/x64/bin/clang-cl.exe"`. Sometimes I also get `IntelliSense process crash detected` when switching between kits, but I'm not able to reproduce this crash as it seems to happen sporadically.

If I use `Clang (MSVC CLI)` or MSVC compiler, intellisense seems to work correctly.

**Steps to reproduce**

1. Open CMake project
2. Select Clang (GNU CLI) kit
3. Do a clean build
4. Check if Intellisense is working

**Expected behavior**

Intellisense working and providing autocomplete.

**Code sample and logs**

- Code sample [vscpp-bug-reproducing.zip](https://github.com/microsoft/vscode-cpptools/files/6489189/vscpp-bug-reproducing.zip)

- Configurations in `c_cpp_properties.json` 
  - Even without this file Intellisense will not work using Clang (GNU CLI)
  - If I try to generate this file, plugin seems to use wrong compilerPath (using MSVC cl.exe rather than clang-cl.exe).
  - If I manually fix compilerPath to clang-cl.exe and IntelliSenseMode to windows-clang-x64, IntelliSense still doesn't work.
  - Nearly one month ago, everything was working fine without this file
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/Llvm/x64/bin/clang-cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-clang-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette [log-diagnostic.txt](https://github.com/microsoft/vscode-cpptools/files/6489203/log-diagnostic.txt)

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) [cpp-debug-log.txt](https://github.com/microsoft/vscode-cpptools/files/6489213/cpp-debug-log.txt)

**Screenshots**

![intellisense-not-working](https://user-images.githubusercontent.com/3220188/118396994-5421b200-b652-11eb-9edb-077bfddd807f.png)

**Additional context**

**Comment by sean-mcmanus** [comment] 2021-05-17 18:38
I believe you should be using the clang MSVC cli if you're trying to build for Windows with MSVC system headers. I don't get any errors when I do that. Log diagnostics should show it using
```
    IntelliSense Mode: windows-clang-x64
    Other Flags:
        --ms_compatibility
        --microsoft_version=1929
        --ms_extensions
        --clang
        --clang_version=110000
```

**Comment by NoMore201** [comment] 2021-05-17 19:53
With the current configuration, program is built and executed correctly even with Clang GNU CLI, as it was before. The only thing that changed is intellisense not working with Clang GNU CLI.

Maybe as you said something changed within Cmake plugin. For the moment I'll switch to MSVC CLI

**Comment by Colengms** [comment] 2021-05-18 01:14
@sean-mcmanus On Windows, Clang with GNU CLI should work.  (I've used it, a few versions ago).  I believe the only difference between clang (GNU CLI) and clang-cl (MSVC-CL) should be the command line argument handling.  However, I do see a few slightly different defines from either of them, but both appear to define: `_MSVC_LANG 201402L`.  This link refers to clang support on Windows, but does not appear to indicate that the support is only for clang-cl: https://clang.llvm.org/docs/MSVCCompatibility.html

Hi @NoMore201 .  Since you have a value specified for `configurationProvider`, most of the other fields of your `c_cpp_properties.json` would not be effective.  The configuration provided by the custom configuration provider would take precedence.  That might explain why changing those settings did not change the behavior.  Only if the config provider fails to provide a 'browse configuration' for some reason, would the C/C++ extension fall back to the values in your `c_cpp_properties.json`.

I'm able to repro the issue in which the IntelliSense is incorrect, and std::cout is not recognized.  I suspect there may have been a recent regression causing the IntelliSense parser to fail to properly parse something prior to the definitions of std::cin or std::endl.  Indeed, when I open `iosteam`, I see a number of other squiggles.

The repro example you provided does not include a `c_cpp_properties.json`.  It falls back to `cl.exe` for me, as that is my default compiler, until I run `CMake: Configure`.  Although that doesn't appear to be the main issue you are seeing, it looks like a bug. 
 I've open another issue to track it: https://github.com/microsoft/vscode-cpptools/issues/7542

**Comment by sean-mcmanus** [comment] 2021-05-18 01:31
So this issue is tracking the IntelliSense issue? It's regression from 1.3.1? I can investigate on Wednesday unless someone else wants to look at it on Tuesday.

**Comment by sean-mcmanus** [comment] 2021-05-26 00:55
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders3

**Closed as completed** 2021-05-28 00:14 UTC
Labels: bug, Language Service, fixed, regression
