### ISSUE TITLE
Template class error squiggles don't work

### ISSUE THREAD

**Issue by cclamb** [microsoft/vscode-cpptools#7684] opened 2021-06-12 15:24 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Ubuntu Linux, 20.04
- VS Code Version: 1.570
- C/C++ Extension Version: 1.4.1
- Other extensions you installed (and if the issue persists after disabling them):
gitlens, jupyter, python, pylance, prettier, VS Intellicode, vscode-icons; disabling makes no difference
- If using SSH remote, specify OS of remote machine: N/A
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Error squiggles don't appear in template classes.

**Steps to reproduce**

(1) Enable the plugin, create a project.
(2) Create this file in the project (I also create a main.cpp that references this, but I don't think it's needed):

```
#ifndef __TEST_H__
#define __TEST_H__

#include <iostream>

template<typename T>
struct printer
{
    void print(const T& t)
    {
        std::cout << t << std::endl;
        foo = 1;
    }
};

struct pp
{
    void print(const int& t)
    {
        std::cout << t << std::endl;
        foo = 1;
    }
};

#endif
```

(2) The second struct has error squiggles, the first doesn't

**Expected behavior**
I would expect error squiggles (and intellisense, for that matter) to work with template classes.

**Comment by sean-mcmanus** [comment] 2021-06-14 17:54
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/1946

**Closed as completed by sean-mcmanus** 2021-06-14 17:54 UTC
Labels: duplicate
