### ISSUE TITLE
F12 key aslo opens the peek definition view

### ISSUE THREAD

**Issue by suluvai** [microsoft/vscode-cpptools#391] opened 2016-12-08 03:24 UTC

**Comment by sean-mcmanus** [comment] 2016-12-08 21:17
Yeah, I'm seeing this bug. Did VS Code regress us?

**Comment by bobbrow** [comment] 2017-03-09 23:00
Are you still having this issue?  If the symbol is defined in multiple locations, the peek definition view opens up to help disambiguate.

**Comment by sean-mcmanus** [comment] 2017-03-09 23:04
Yeah, this is by design. I'm closing it. It doesn't repro if there's only 1 definition found.

**Closed as completed by sean-mcmanus** 2017-03-09 23:04 UTC
Labels: bug, Language Service, more info needed
