### ISSUE TITLE
IntelliSense engine views .C extension file as c file instead of cpp file

### ISSUE THREAD

**Issue by Yaphet-Chen** [microsoft/vscode-cpptools#2708] opened 2018-10-24 09:18 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Window 10 with  Ubuntu 16.04.5 LTS Linux Subsystem
- VS Code Version: 1.28.2
- C/C++ Extension Version: Version 0.19.0: September 27, 2018
- Other extensions you installed (and if the issue persists after disabling them): Only this cpptools
- A clear and concise description of what the bug is.

I working on OpenFOAM (Compiled successfully) and all its cpp source file with extension C. But it seems that cpptools IntelliSense engine view .C file as c file instead of cpp file.

![image](https://user-images.githubusercontent.com/16664001/47420090-33ea2900-d7b0-11e8-831b-1961ae44f12c.png)

But if I change .C extension of this file to .cpp 

![image](https://user-images.githubusercontent.com/16664001/47419171-292e9480-d7ae-11e8-844c-3426bd54eae1.png)

The problem "identifier "using" is undefined" disappears. However, other problems still exist since I don't change the extension of other thousands of source files from .C to .cpp.

Below is my c_cpp_properties.json
![image](https://user-images.githubusercontent.com/16664001/47419342-8fb3b280-d7ae-11e8-8739-b0d31abdb677.png)

**To Reproduce**

1. clone [OpenFOAM](https://github.com/OpenFOAM/OpenFOAM-6)
2. modify your c_cpp_properties.json file as
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/**",
                "/usr/include/openmpi"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```
3. open applications\test\Matrix\Test-Matrix.C

**Expected behavior**
You can see a red wavy underline in the keyword "using". If you change the file name to Test-Matrix.cpp, the red wavy underline disappear.

**Comment by Yaphet-Chen** [comment] 2018-10-24 16:09
This problem can be partially fixed by adding a workspace settings.json file as follow

```
{
	"settings": {
		"files.associations": {
			"*.H": "cpp",
			"*.C": "cpp"
		}
	}
}
```

Although the association of "*.C" to "cpp" works, the association of ".H" to "cpp" seems force the IntelliSense engine to view its as source file insteaded of header file. This can be verified by changing the file name from *.H to *.hpp, the IntelliSense engine behave different.

**Comment by bobbrow** [comment] 2018-10-24 16:31
Thank you for the bug report.  This is a duplicate of #2558

**Closed as completed by bobbrow** 2018-10-24 16:31 UTC

**Comment by Yaphet-Chen** [comment] 2018-10-25 06:49
I find another remedy. Using the older IntelliSense Engine can temporarily solve the problem. Both Go to and autocomplete function properly without annoying red squiggles appeared.
```
{
    "C_Cpp.intelliSenseEngine": "Tag Parser"
}
```

Set the engine as "Tag Parser" and add you relevant browse path.

```
{
    "configurations": [
        {
            "name": "WSL",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "browse.path":[
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```
