### ISSUE TITLE
When including a header file which is a link, some defines are not found (WSL)

### ISSUE THREAD

**Issue by sirbabyface** [microsoft/vscode-cpptools#2791] opened 2018-11-08 09:34 UTC
**Type: LanguageService**

- OS and Version: WIndows 10 - 1803 (Build 17134.345)
- VS Code Version: Version: 1.29.0-insider (system setup) x64
- C/C++ Extension Version: 0.20.1
- I'm using WSL system and bash to develop

**To Reproduce**

1. I've include <ncurses.h> in my file, but some of defines are not found.
2. But if I change to include <curses.h>, it works correctly.

It seems there is a problem with the symbolic links in linux, when using them in Windows.

**Comment by bobbrow** [comment] 2018-11-08 16:45
Thanks for the feedback.  This is a duplicate of #2140 and #2223 (same root cause).  Please go and "+1" those issues so we can track the priority of a fix for this better.

**Closed as completed by bobbrow** 2018-11-08 16:45 UTC
Labels: duplicate, Language Service
