### ISSUE TITLE
Use of conditional macros inside a macro invocation confuses the C/C++ Extension enhanced colouring

### ISSUE THREAD

**Issue by kevquinn** [microsoft/vscode-cpptools#6685] opened 2020-12-19 14:36 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 (Windows_NT x64 10.0.18363)
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them):
Others installed;
-- Auto Build Marlin 2.1.26
-- GitHub Pull Requests and Issues 0.22.0
-- GitLens 11.0.6
-- Jupyter 2020.12.414227025
-- Language Support for Ada 22.0.2
-- PlatformIO IDE 2.2.1
-- Python 2020.12.424452581
-- Remote - WSL 0.52.0
Issue occurs with all these extensions disabled.
- Does this issue involve using SSH remote to run the extension on a remote machine?:
No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
Macro parsing by the C/C++ extension gets confused with conditional macros placed inside another macro expansion. Impacts intelligent code navigation.
Workspace for the example is a single project - but happens in all workspaces.

**Steps to reproduce**

1. Place the following code in a .cpp file and save:

```
extern int returnvalue(int a, int b);

#define TEST(a,b) returnavalue(a,b)
#define CONFIG

void myfunction1() {
  int x =
    TEST(1,
    #ifdef CONFIG
      2
    #else
      3
    #endif
  );
}

void myfunction2() {
  int x =
    #ifdef CONFIG
    TEST(1,2);
    #else
    TEST(1,3);
    #endif
}
```
2. Notice a red squiggle on TEST in myfunction1 and a red squiggle at the end of the file, with the following in the problems tab:

- "improperly terminated macro invocation" on the first invocation of TEST
- "expected a )" at the end of the file.

The occurrence of the red squiggle in general means that things get out of step and colouring of active/inactive code controlled by macros gets confused, which in turn confuses the intelligent code navigation features.

The example provided is a dramatically simplified minimum so looks pathologically daft, but the (distasteful but I believe valid?) usage pattern that triggers the issue occurs liberally in the code base I'm using (Marlin 3D printer firmware - marlinfw.org), so I'm not in a position to suggest they rewrite all their code to satisfy a code syntax highlighter.

**Expected behavior**

No red squiggles or problems reported.

<details>
  <summary><strong>Logs</strong></summary>

*** C/C++: Log Diagnostics (I think?)
```
[19/12/2020, 14:05:34] For C source files, IntelliSenseMode was changed from "gcc-x64" to "gcc-arm" based on compiler args and probing compilerPath: "C:/Users/kevquinn/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc.exe"
[19/12/2020, 14:05:35] For C++ source files, IntelliSenseMode was changed from "gcc-x64" to "gcc-arm" based on compiler args and probing compilerPath: "C:/Users/kevquinn/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc.exe"
```
*** Language server log
```
cpptools/didChangeSettings
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
$/setTraceNotification
cpptools/getCodeActions: file:///d%3A/GitHub/BIGTREETECH-SKR-CR6/firmware/BTT-SKR-CR6/Marlin/src/module/test.cpp (id: 40)
cpptools/activeDocumentChange: file:///d%3A/GitHub/BIGTREETECH-SKR-CR6/firmware/BTT-SKR-CR6/Marlin/src/module/test.cpp
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///d%3A/GitHub/BIGTREETECH-SKR-CR6/firmware/BTT-SKR-CR6/Marlin/src/module/test.cpp (id: 41)
cpptools/getDocumentSymbols
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///d%3A/GitHub/BIGTREETECH-SKR-CR6/firmware/BTT-SKR-CR6/Marlin/src/module/test.cpp (id: 42)
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/GitHub/BIGTREETECH-SKR-CR6/firmware/BTT-SKR-CR6/Marlin/src/module/test.cpp
Queueing IntelliSense update for files in translation unit of: D:\GITHUB\BIGTREETECH-SKR-CR6\FIRMWARE\BTT-SKR-CR6\MARLIN\SRC\MODULE\TEST.CPP
cpptools/finishUpdateSquiggles
Error squiggle count: 2
Update IntelliSense time (sec): 0.257
cpptools/getSemanticTokens: file:///d%3A/GitHub/BIGTREETECH-SKR-CR6/firmware/BTT-SKR-CR6/Marlin/src/module/test.cpp (id: 43)
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment] 2020-12-21 18:28
Thanks for reporting this. I've filed an issue against our parser shared with VS at https://developercommunity.visualstudio.com/content/problem/1293412/c-intellisense-in-gcc-mode-doesnt-correctly-parse.html .

Also, with cl.exe, I get "warning C5101: use of preprocessor directive in function-like macro argument list is undefined behavior", so ideally code wouldn't be written that relies on undefined compiler behavior, since other compilers like cl.exe/EDG may not compile it.

**Comment by kevquinn** [comment] 2020-12-21 20:51
Thanks Sean, much appreciated. At the same time I'll follow up on the undefined language behaviour with the Marlin firmware folks; they may well be open to patches removing such occurrences as they may well be willing to support people using something other than gcc.

**Comment by kevquinn** [comment] 2021-01-01 14:48
Quick update - turns out use of `defined` in macro expressions is too deeply embedded in the way Marlin is built for changing that to be viable.

For reference, the rule that's broken according to the [SEI CERT C Coding Standard](https://wiki.sei.cmu.edu/confluence/display/c/PRE32-C.+Do+not+use+preprocessor+directives+in+invocations+of+function-like+macros) is section 6.10.3, paragraph 11 of ISO/IEC 9899:2011. The GNU folks describe it explicitly in their [not bugs list](https://gcc.gnu.org/bugs/#nonbugs_c) as something they support that's non-portable.

If I'm reading the comments on your upstream report properly, it sounds like it's already handled in more recent versions of the upstream intellisense, so maybe that will trickle down to Visual Studio Code at some point.

**Comment by sean-mcmanus** [comment] 2021-01-05 01:19
The issue is not fixed in VS -- the team just had some unknown issue that prevented the repro. I had replied to them internally.

**Closed as completed** 2021-02-03 00:41 UTC
Labels: bug, Language Service, fixed, Visual Studio
