### ISSUE TITLE
Cpptools consumes about 6GB memory on debian, and the system get no more response.

### ISSUE THREAD

**Issue by nuaalyy** [microsoft/vscode-cpptools#5227] opened 2020-03-30 09:29 UTC
I don't know why but it really confused me. Cpptools costs lots of **memory**, and the **debian** goes down, but on **win10**, cpptools works well. The only differece is that the boost libs is installed on debian but not installed on win10. Maybe large scale c++ projects are not supported well? The version of CPPTOOL is **0.27.0-insiders3**.

**Comment by sean-mcmanus** [comment] 2020-03-30 21:16
Have you tried 0.27.0-insiders5 (or the soon to be released 0.27.0)? What about 0.26.3 (i.e. is this a regression)?

Do you mean one cpptools process is using 6 GB or do you mean cpptools-srv? Does your system run out of memory after reaching 6 GB, i.e. does it appear like cpptools is requesting > 6 GB and is running out of memory?

Does this repro before you open any files?

**Comment by SantinoKeupp** [comment] 2020-03-31 12:10
I experience similar problems with version 0.27.0 on a gentoo machine. It looks like 0.26.3 is more stable.

**Comment by nuaalyy** [comment] 2020-03-31 13:41
The memory is cost by the C/C++ extension, not other applications or processes or services, which is for sure. And version 0.26.3 has been tried, which also has the problem. Once the extension is disabled, everything goes well.  I will try the version 0.27, and update a snapshot of the task manager later. If any log is helpful please let me know.

**Comment by sean-mcmanus** [comment] 2020-03-31 18:58
@nuaalyy cpptools-srv is part of our extension. Depending on how you're viewing C/C++ extension memory usage, cpptools and multiple cpptools-srv processes could be included in the memory usage count, so it's important for us to know what the per-process memory usage is. Most of our memory usage should be in those processes, but if you're seeing high memory usage in a Visual Studio Code process or "extension host", that would be important to know too.

@SantinoKeupp We are not yet aware of any instability regression in regards to memory usage with 0.27.0 (and we've been in Insider mode for a month). Can you provide more info on what you are seeing?

**Comment by nuaalyy** [comment] 2020-04-01 01:26
![memory_usage](https://user-images.githubusercontent.com/3361123/78089288-8e51d500-73f9-11ea-803a-ab989236d90c.png)
I tried the latest version, 0.27, same issue. When **Find All Reference** or **Go to Definition**, status of **cpptools-srv** switches to Running, and Memory grows up to even 8GB, and the system hangs. When the **cpptools-srv** process is killed, system goes back to normal. Wish to be helpful.

**Comment by sean-mcmanus** [comment] 2020-04-01 02:09
This is partly related to https://github.com/microsoft/vscode-cpptools/issues/4811 . We spawn up cpptools-srv processes based on the core count without checking the available memory. Both the 2.8 GB cpptools and the 6 GB cpptools-srv are unexpected. Are you aware of anything special about the TU you're compiling, such as using a large file or large libraries?

**Comment by nuaalyy** [comment] 2020-04-01 02:52
I was just reviewing the codes, not compiling anything. Indeed, some large libraries is included the project sucn as BOOST, which may be an impact factor.

**Comment by bobbrow** [comment] 2020-04-02 21:06
Is there an open source codebase we can clone to reproduce this error?  Unfortunately, there's not much we can do to solve this without some additional help.

**Comment by skramm** [comment] 2020-04-14 09:50
I think I got hit by this one too. VSCode is used only for editing purpose, no compiling.System becomes unresponsive, had to kill VS Code. 
Problem is: even after killing it, it seems that cpptools stays in the list of process (see attached screenshot from htop), each of these eating up lots of virtual memory.

![vscode_1](https://user-images.githubusercontent.com/6195178/79210477-31b4d800-7e45-11ea-8d5c-fd1582134c43.png)

OS: Ubuntu 16.04
"About" dialog:
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T11:22:13.689Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.4.0-177-generic

**Comment by Fla3inH0tCheet0s** [comment] 2020-04-14 19:34
I found that it helps to add exclusion folders. For example, add the following to .vscode/settings.json
```
"files.exclude": {
  "folder_with_generated_files": true,
  ...
}
```

**Comment by staleh1** [comment] 2020-06-09 14:15
Similar issue with 0.28.2 on Fedora, although not as extensive as OP. Seems to increase memory usage over time.

**Comment by skramm** [comment] 2020-06-09 17:02
I even had to stop using it, it became unusable after a couple of minutes (freezes), had to switch to another IDE.
@bobbrow asked for some relevant code base. I'd say: any, with more than 10-20 files. For a really large one, try https://github.com/opencv/opencv/ for example. On a standard Linux-Ubuntu flavor box, just fiddle around the source files, going from usage to definition/declaration of functions and you should experience that in a matter of minutes.

**Comment by sean-mcmanus** [comment] 2020-06-09 18:29
@skramm Does the issue repro if you disable our extension? The problem you're hitting may not be caused by our extension -- what process is using CPU or memory? The virtual memory usage shouldn't affect performance. If you kill the VS Code process, you'll need to do it in a way that also kills all the child process (cpptools, cpptools-srv, etc.).

**Comment by nuaalyy** [comment] 2020-06-15 06:49
> I even had to stop using it, it became unusable after a couple of minutes (freezes), had to switch to another IDE.
> @bobbrow asked for some relevant code base. I'd say: any, with more than 10-20 files. For a really large one, try https://github.com/opencv/opencv/ for example. On a standard Linux-Ubuntu flavor box, just fiddle around the source files, going from usage to definition/declaration of functions and you should experience that in a matter of minutes.

No doubt that large scale of projects will take lots of memory to parse the definitions and reference relationships. I will apply more memory for my desktop. Hope it will do. By the way, QT may consume less memory when parsing the projects.

**Comment by mgsteinkamp** [comment] 2020-07-06 02:32
Seem to be having the same issue here.  cpptools can easily run up 8GB of memory.
VSCode used only for editing, no compiling.
Also, I rarely use the Go-To-Definition feature and it hangs before I even hover over a variable.

Environment:
- Ubuntu 18.04, 
- 6 (12) core
- 16GB RAM
- v0.29.0-insiders


Some large, open source libraries used:

- OpenCV
- PCL

**Comment by OnkelDon** [comment] 2020-07-22 12:05
Same issue here. It seems as soon as linux kernel is in the search/intellisense path, the leak happens after some time, it eat up all the 32GB! Sometimes I replace the cpptools binary with a script which changes ulimit settings (ulimit -v 8000000), but it's gone after every update. Would be nice if this become a setting or so.

Environment:
- Ubuntu 18.04
- 8 (16) cores
- 32GB RAM
- v0.29.0

Linux kernel 5.6 and some litte binaries compiled against it.

**Comment by qfunq** [comment] 2020-08-09 18:24
To confirm and recap: out of the box, linux cpptools/vscode has two bugs, which combine to render the suite almost unusable:

1: A memory leak/over eager searching. cpptools consumes all cpu resources.
2: The cpptools service is slow to/never terminates after vscode has exited, and vscode server seems keen to respawn another cpptools service.


Workarounds:

1: Along with OnkelDons' suggestion of using a script wrapper and ulimit, subsequently launching with cpulimit -l 0 helps slow it's damage, with almost no(!) impact to the user. 
To expand on Onkels' suggestion, having UI limits for any extension is a nice general way to code it up, greatly expanding the range of usable extensions. For the moment, here is my cpptools script: (I'm running it on a cloud server, with 12G ram).

#!/bin/bash

ulimit -v 4000000

cpulimit -l 0 /home/qfunq/.vscode-server/extensions/ms-vscode.cpptools-0.29.0/bin/cpptools-raw $@



2: Now the persistence of instances of cpptools is much more general. One apparent cause of the bug is that vscode server is invoked using a shell script .... and scripts are not apps ... but by using dumb-init, they can be converted to have application like behaviour. Since the outer invocation uses sh, we can insert the following into .bashrc

alias sh='/bin/dumb-init /bin/bash'

with the side effect of upgrading every sh invocation to an app. This may be not what is required all the time ... so, in principle, by writing a more sophisticated script to replace sh, it's possible to trap the call to invoke cpptools (or other misbehaving extension/script), and inject it's complete resource configuration dynamically, allowing vscode to be updated without patching it, and fully localising the effect of the resource injection.

On testing, the dumb alias technique transforms vscode server from a script to an application, assuming a clean shutdown. In preliminary testing, there were no additional instances of cpptools created, they terminate as soon as the code server does (which may be after the app has exited), and as of yet, there are no side effects to report of locally aliasing sh (I tend to invoke bash with dumb-init anyway).

A remaining issue is that vscode still seems to want to spawn new cpptools after reloading the developers window. It appears reload is not signalling the child services? This might be patchable by using dumb-init at a higher level?

Edit: The entire workaround for 2) is not working, the alias is never being called because of path issues. When sh is patched globally, the dumb-init environment is not directly compatible with terminal control, requiring some additional wiring to be effective.

**Comment by jpan127** [comment] 2020-12-02 02:46
I've been noticing this for as long as I have used VScode.  Thankfully it often fixes itself for awhile when I `pkill -f cpptools`. Today, I just saw it ate up a good chunk of my 64GB RAM **and 90% of my 100GB swap space**.  There's either a memory leak or the logic is memory inefficient or there are no memory constraints or something about bazel symlinks 🤷 .

I promptly disabled following symlinks in the settings, and we'll see if it happens again.

**Comment by dkl** [comment] 2021-01-04 20:38
Here's a way to reproduce this issue (or at least it looks like it), using a very big C header file with tons of symbols (which obviously is going to cause lots of work for cpptools).

Use this python script to generate the main.h file (no worries, this generates only ~60 MB which isn't even that much for plain text editing):
```
#!/usr/bin/env python3
with open('main.h', 'w') as f:
	for i in range(1024 * 1024):
		f.write(f"int f{i}(int a, int *b, struct s *c, int (*C d)(int *a));\n")
```

Then put main.h into a new directory, and this main.c next to it:
```
#include "main.h"
```

Then open main.c in VSCode (or open the directory and then open main.c). Now cpptools starts up and quickly reaches 4-6 GiB memory usage. As far as I can tell the RAM usage varies a bit, but clearly depends on the amount of input source code, and can easily be high enough to trigger swapping. Obviously when swapping everything becomes painful, and I've seen cpptools remain busy for quite some time even after closing all vscode windows.

It's interesting that vscode itself refuses to deal with the big C file (saying "tokenization, wrapping and folding have been turned off..."), but I don't know whether cpptools has a limit like that. It certainly seems like it would be nice to have, and I guess, as a result, IntelliSense wouldn't work anymore for that project, but that's better than swapping.

**Comment by sean-mcmanus** [comment] 2021-01-05 02:53
@dkl Why do you say ~60 MB isn't a lot for plain text? sqlite3.c is only 8 MB and I see all the C++ system headers generating 4 MB and I don't get high memory usage with those. Is there some real world example that is > 8 MB in size?

Yeah, I repro large memory usage with a large file that is many MB in size, and we could add some sort of tag parsing limit for files, but I'm not sure if users are hitting the memory usage due to large files or not. Can someone confirm that is the case?

FYI, "IntelliSense" memory usage doesn't accumulate in cpptools, but in cpptools-srv.

**Comment by dkl** [comment] 2021-01-05 09:32
Yea, 60 MB is unusually large for C code in a single translation unit (it's not much for other file types, such as log files). I'm using such generated files to benchmark a C parser, and it was a bit surprising to see cpptools parsing them, since they're only temporary files, not even staged/committed in git, but luckily .gitignoring the files was enough to prevent cpptools from doing that, so it's fine.

**Comment by sean-mcmanus** [comment] 2021-01-05 19:20
@dkl Hmm, I don't know why adding it to .gitignore would change our parsing behavior. We only check the files.exclude setting, and I'm seeing .gitignore files being tag parsed.

**Comment by dkl** [comment] 2021-01-07 22:03
Sorry, I can't reproduce it anymore, must have been unrelated. But I did notice that it's enough to have any C file open for cpptools to start parsing the .h files, even if it doesn't #include them. So that must have been it.

**Comment by yusj** [comment] 2021-02-01 12:56
I can reproduce it stably:
1. Download chromium open source (Doc: https://chromium.googlesource.com/chromium/src.git/+/HEAD/docs/android_build_instructions.md). Need download all the sources, It takes about 42GB disk size. Two important steps:
   1.1 clone the main repo.
   1.2 use `gclient sync` to download third_party repos.
2. Add the chromium project into vs code.
3. Open any blink source file, such as `content/renderer/render_frame_impl.cc`.
4. Active cpptools: Go to some symbol's definition, and search some symbol globally.
5. The VmRSS of cpptools will grows up to 6GB very soon.

My computer's RAM is 32GB with Ubuntu 20.04, and stuck many times every day due to use out all of the memory. And I have to force shutdown my computer by cut off the power, because my mouse and keyboard are not responding.
I also used `ulimit -v 6144000` to limit cpptools's VM size, and I never got stuck any more, but the cpptools crashes frequently due to the limit.

**Comment by skramm** [comment] 2021-02-01 13:10
> I also used `ulimit -v 6144000` to limit cpptools's VM size, and I never got stuck any more, but the cpptools crashes frequently due to the limit.

Is it a "hard crash" (no error message at all), or some exception is being thrown, that you can see?

**Comment by sean-mcmanus** [comment] 2021-02-01 22:40
@yusj Thanks for the repro info.

**Comment by sean-mcmanus** [comment] 2021-02-03 01:04
@yusj I'm not reproing the issue with chromium (on Mac). It enumerates 1.1 million files, excluding 100k files, and parses 200k files. Any idea what the difference in my repro could be?

**Comment by sskorol** [comment] 2021-03-20 21:34
I'm using VSCode for remote development on resource-limited boards like [Respeaker Core v2](https://wiki.seeedstudio.com/ReSpeaker_Core_v2.0/#features). It has only 1Gb RAM. And when I open my C++ project, VSCode disconnects and the board just dies in several minutes. And I can't do anything with it. OS is not responsive.

![image](https://user-images.githubusercontent.com/6638780/111886046-05e68e80-89d4-11eb-808d-b772aea42a56.png)

**Comment by sean-mcmanus** [comment] 2021-03-22 15:35
@sskorol Setting C_Cpp.intelliSenseMemoryLimit to 256 might help, but if the TU require more memory then that won't be sufficient. Setting C_Cpp.intelliSenseEngine to "Tag Parser" would be another workaround. Our minimum spec for memory is probably around 4 GB.

**Comment by sskorol** [comment] 2021-03-24 15:24
@sean-mcmanus seems better, thanks. But do you have any plans to optimize cpptoops for remote development on resource-limited boards?

**Comment by sean-mcmanus** [comment] 2021-03-24 19:08
@sskorol  The cases where memory > 1 GB we may be able to fix/improve, but getting memory usage < 1 GB with cpptools-srv may not be possible given our parser's need for memory. If you have a Windows machine you could try using VS 2019's remote Linux support, which will run the IntelliSense on the host Windows machine with more memory: https://devblogs.microsoft.com/cppblog/linux-development-with-c-in-visual-studio/ .

**Comment by sskorol** [comment] 2021-03-24 20:43
@sean-mcmanus well, I have Windows as a second OS on PC. But primarily I use macOS and Linux. But thanks for the link.

**Comment by kefins** [comment] 2021-07-12 08:25
I have encountered the same problem, cpptools took  too much memory and trigger OOM.
```bash
[Mon Jul 12 15:51:56 2021] Out of memory: Kill process 1631 (cpptools) score 342 or sacrifice child
[Mon Jul 12 15:51:56 2021] Killed process 1631 (cpptools) total-vm:7280960kB, anon-rss:5549740kB, file-rss:0kB, shmem-rss:0kB
[Mon Jul 12 15:51:57 2021] oom_reaper: reaped process 1631 (cpptools), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

OS version info:
```bash
 cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
VSCODE version:
```
版本: 1.58.0 (system setup)
提交: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
日期: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

C/CPP version:
```bash
Version 1.5.1: July 9, 2021
Bug Fixes
cppvsdbg Debugging becomes no-op between 1.4.1 and 1.5.0 #7808
```

**Comment by sean-mcmanus** [comment] 2021-07-13 00:29
@kefins Running out of memory is a general symptom for which there could be many causes. We'd need more repro info to determine what the cause is in your case.

**Comment by kefins** [comment] 2021-07-13 02:03
> @kefins Running out of memory is a general symptom for which there could be many causes. We'd need more repro info to determine what the cause is in your case.

I know little about the cpptools process and I don't know how to fix it, if you need more info, you can tell me how to gather them. But I think it was caused by intelliSenseEngine, after making it to be disable, the OOM seems never take place again.

**Comment by sean-mcmanus** [comment] 2021-07-13 02:26
@kefins It's best to file a new issue: https://github.com/microsoft/vscode-cpptools/issues/new?assignees=&labels=&template=language-service.md&title= , and mention which process is using the memory and how much memory, what version of the C/C++ extension is being used, what OS is being used, what compiler is being used, and any repro project or file you can provide, and if there are any particular operations that trigger the issue.

**Comment by kefins** [comment] 2021-07-13 02:47
@sean-mcmanus OK, I will file a new issue later.

**Comment by riban-bw** [comment] 2021-10-02 16:50
There was mention earlier that the extension uses memory based on quantity of cores. I am running VSCode on a Windows laptop (i5 8GB) connecting remotely to a Raspberry Pi 4 with 2GB RAM and 4 cores. With larger projects the service on the Pi consumes all the available memory over a period of some minutes then it all locks up. There was also mention of disabling some features to make it less memory hungry or running parsers on the local rather than remote machine. Are any of these possible work-arounds for this issue?

**Comment by sean-mcmanus** [comment] 2021-10-04 23:27
The memory usage based on cores is just in regards to the number of IntelliSense processes kept alive. If you're hitting the memory issue with just 1 file then you'd be hitting a different issue. 2-4 GB of RAM may not be enough for using our extension (8+ GB would be recommended). We have some additional settings like C_Cpp.maxCachedProcesses in development (unreleased) that could be used to override that behavior (if you're hitting the issue when opening > 1 file).

**Comment by fwilmsh** [comment] 2021-11-24 14:17
I'm experiencing a similar issue with memory usage of cpptools process constantly increasing. over about an hour of usage now:
![Screenshot from 2021-11-24 15-14-58](https://user-images.githubusercontent.com/43751277/143255025-c6a6ddab-bfca-4a00-b83f-eba775a43895.png)
![Screenshot from 2021-11-24 15-15-59](https://user-images.githubusercontent.com/43751277/143255028-dd458257-52f0-495f-9452-7b42721b7b1d.png)

**Comment by sean-mcmanus** [comment] 2021-11-29 16:49
@fwilmsh We need more info. Are you able to set the C_Cpp.loggingLevel to "Debug" and check the C/C++ output to determine what is going on when the memory usage is increasing? Or attach a debugger to cpptools to provide a call stack? See https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

**Comment by moodboom** [comment] 2022-01-24 21:04
sean-mcmanus This problem seems pretty easily reproducible - if not the leak, then just the massive resource usage - have you tested with boost libraries?  With a small boost project, with just the editor open, right now I have 5 cpptools-srv processes each taking up 1.2GB of memory.  Completely unreasonable.

**Comment by sean-mcmanus** [comment] 2022-01-24 21:45
@moodboom 1.2 GB memory usage with a file that uses boost sounds "by design" (expected). The preprocessed TU for such a file could be hundreds of thousands of lines long. Implementation of https://github.com/microsoft/vscode-cpptools/issues/3628 might solve the issue.

**Closed as completed** 2022-03-26 11:16 UTC
Labels: bug, Language Service, more info needed
