### ISSUE TITLE
Formatting fails so bad.

### ISSUE THREAD

**Issue by elmelundsvej** [microsoft/vscode-cpptools#5938] opened 2020-08-08 12:53 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04 LTS
- VS Code Version: 1.47.3
- C/C++ Extension Version: 0.30.0-insiders
- Other extensions you installed (and if the issue persists after disabling them): CMake, CMake Tool, Python, SQL Server(mssql)
- Does this issue involve using SSH remote to run the extension on a remote machine?: No.

Text of code in C/C++ is missing and literals are separated by spaces all in a wrong way. Please refer to screenplay in below.

**Steps to reproduce**

1. Go to text editor.
2. Press "Ctrl+Shift+I" to trigger formatting.
3. Scroll down to the tail.
4. See error.

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![Bug Screenplay](https://user-images.githubusercontent.com/57971294/89710999-253b2900-d9ba-11ea-88c4-fbf4ee36ebe1.gif)

**Additional context**

**Comment by lucasmaziero** [comment] 2020-08-08 17:24
I have this problem too!!

**Comment by elmelundsvej** [comment] 2020-08-09 00:18
> I have this problem too!!

Now I'm not the only one. Let's wait for them to fix it.

**Comment by alanbueno** [comment] 2020-08-09 17:26
+1 here!

**Comment by alanbueno** [comment] 2020-08-09 17:39
apparently rolling back to the latest `0.29` and changing the `Update Channel` to default instead of insiders kinda sorts it out for now, until they actually fix it I guess!

- installing specific version:
<img src="https://user-images.githubusercontent.com/10865103/89738224-562d6380-da77-11ea-91b3-40a7704d20a5.png" alt="installing specific version" width="400">

- channel change:
<img src="https://user-images.githubusercontent.com/10865103/89738173-ed45eb80-da76-11ea-8d99-2fc7cf8d96e8.png" alt="channel change" width="400">

**Comment by lucasmaziero** [comment] 2020-08-09 22:41
Thanks @alanbueno here solved the problem using version 0.29 for now.

**Comment by github-yxb** [comment] 2020-08-10 07:26
Thanks @alanbueno !

**Comment by michelleangela** [comment] 2020-08-10 22:21
This is duplicate of https://github.com/microsoft/vscode-cpptools/issues/5914

**Closed as completed by michelleangela** 2020-08-10 22:21 UTC
Labels: duplicate, Language Service, Feature: Code Formatting

**Comment by sean-mcmanus** [comment] 2020-08-12 01:15
This is fixed with 0.30.0-insiders2: https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders2 .
