### ISSUE TITLE
Excludes sometimes aren't applied to dependent headers with recursive includes

### ISSUE THREAD

**Issue by JominL** [microsoft/vscode-cpptools#12042] opened 2024-03-01 16:38 UTC
### Environment

- OS and Version: WIN11 
- VS Code Version: 1.80.0
- C/C++ Extension Version: 1.19.4
- If using SSH remote, specify OS of remote machine: SSH remote ubuntu 20.04

### Bug Summary and Steps to Reproduce

Bug Summary:
cpptools alway parse those files and folders even they have been added to exclude.

From below log, you can cpptools still parse cpp under "distro/build".

I also try the vscode inside today, same behavior.

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
c_cpp_properties.json
============================
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c23",
            "intelliSenseMode": "gcc-arm",
            "cppStandard": "gnu++23"
            
        }
        
    ],
    "version": 4
}
======================
.vscode/settings.json
=======================
"C_Cpp.default.cStandard": "gnu23",
    "C_Cpp.default.cppStandard": "gnu++20",
    "ctags.languages": [
        "C",
        "C++",
        "DTS",
        "Kconfig",
        "Make"
    ],
    "C_Cpp.files.exclude": {
        "build":true,
        "tmp/work":true,
        "tmp/work/**":true,
        "**/build":true,
        "**/build/**":true,
        "**/.vscode": true,
        "**/.vs": true
    },
    "C_Cpp.default.intelliSenseMode": "linux-gcc-arm",
    "C_Cpp.default.compilerPath": "",
    "files.exclude": {
        "**/.DS_Store": true,
        "**/.git": true,
        "**/.hg": true,
        "**/.svn": true,
        "**/build": true,
        "**/CVS": true,
        "distro/build": true,
        "**/distro/build/**": true,
        "**/Thumbs.db": true
    },
    "C_Cpp.exclusionPolicy": "checkFilesAndFolders",
    "C_Cpp.loggingLevel": "Debug"
========================================================


loggingLevel: Debug
LSP: (received) cpptools/initialize (id: 1)
LSP: (invoked) cpptools/initialize (id: 1)
cpptools version (TypeScript): 1.19.4
cpptools version (native): 1.19.4.0
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
LSP: Sending response (id: 1)
LSP: (received) cpptools/queryCompilerDefaults (id: 2)
LSP: (invoked) cpptools/queryCompilerDefaults (id: 2)
LSP: (received) cpptools/didChangeCppProperties (id: 3)
LSP: (received) cpptools/queryCompilerDefaults (id: 4)
Querying compiler for default C++ language standard using command line: /usr/bin/clang -x c++ -E -dM /dev/null
Detected language standard version: c++14
Querying compiler's default target using command line: "/usr/bin/clang" -dumpmachine
Compiler returned default target value: x86_64-pc-linux-gnu
Compiler query command line: /usr/bin/clang -std=c17 -m64 -Wp,-v -fno-blocks -E -dM -x c /dev/null
Attempting to get defaults from C compiler in "compilerPath" property: '/usr/bin/clang'
Compiler query command line: /usr/bin/clang -std=c++14 -m64 -Wp,-v -fno-blocks -E -dM -x c++ /dev/null
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/clang'
LSP: Sending response (id: 2)
LSP: (invoked) cpptools/didChangeCppProperties (id: 3)
enabling full-text triggers
Code browsing service initialized
Compiler query command line: /usr/bin/clang -std=gnu++23 -m32 -Wp,-v -fno-blocks -E -dM -x c++ /dev/null
Compiler query command line: /usr/bin/clang -std=gnu++2b -m64 -Wp,-v -fno-blocks -E -dM -x c++ /dev/null
Compiler query command line: /usr/bin/clang -std=gnu++20 -m64 -Wp,-v -fno-blocks -E -dM -x c++ /dev/null
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/clang'
Compiler query command line: /usr/bin/clang -std=c23 -m32 -Wp,-v -fno-blocks -E -dM -x c /dev/null
Compiler query command line: /usr/bin/clang -std=c2x -m64 -Wp,-v -fno-blocks -E -dM -x c /dev/null
Attempting to get defaults from C compiler in "compilerPath" property: '/usr/bin/clang'
  Folder: /usr/include/ will be indexed
  Folder: /usr/lib/llvm-10/lib/clang/10.0.0/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /home/myuser/workspace/ will be indexed
LSP: Sending response (id: 3)
LSP: (invoked) cpptools/queryCompilerDefaults (id: 4)
Discovering files...
LSP: Sending response (id: 4)
LSP: (received) cpptools/didChangeCppProperties (id: 5)
LSP: (invoked) cpptools/didChangeCppProperties (id: 5)
LSP: Sending response (id: 5)

LSP: (invoked) cpptools/didChangeVisibleTextEditors
  Processing folder (recursive): /usr/include/
LSP: Sending response (id: 6)
  Processing folder (recursive): /usr/lib/llvm-10/lib/clang/10.0.0/include/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /home/myuser/workspace/
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
Database safe to open.
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
...

  Discovering files: 1335199 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populating include completion cache.
Parsing remaining files...
  tag parsing file: /usr/include/features.h
  tag parsing file: /usr/lib/llvm-10/lib/clang/10.0.0/include/stddef.h
  tag parsing file: /usr/include/time.h
  tag parsing file: /home/myuser/workspace/apps/src/power_control.hpp
  tag parsing file: /home/myuser/workspace/distro/build/target/tmp/work/armv7ahf/usr/include/cjson/cJSON.h
  tag parsing file: /usr/include/x86_64-linux-gnu/sys/sysinfo.h
  tag parsing file: /usr/lib/llvm-10/lib/clang/10.0.0/include/stdbool.h
  tag parsing file: /usr/lib/llvm-10/lib/clang/10.0.0/include/stdint.h
  tag parsing file: /home/myuser/workspace/distro/build/target/tmp/work/armv7ahf/usr/include/systemd/sd-journal.h
  tag parsing file: /home/myuser/workspace/apps/intel/crashdump/engine/logger.h
  tag parsing file: /usr/local/include/boost/asio/io_context.hpp
  tag parsing file: /home/myuser/workspace/distro/build/target/tmp/work/armv7ahf/usr/include/peci.h
  tag parsing file: /usr/local/include/boost/asio/posix/stream_descriptor.hpp
  tag parsing file: /usr/local/include/boost/asio/steady_timer.hpp
  tag parsing file: /usr/local/include/boost/container/flat_map.hpp
  tag parsing file: /usr/include/stdio.h
  tag parsing file: /usr/local/include/boost/container/flat_set.hpp
  tag parsing file: /usr/include/stdlib.h
  tag parsing file: /home/myuser/workspace/distro/build/target/tmp/work/armv7ahf/usr/include/gpiod.hpp
  tag parsing file: /usr/include/string.h
```

**Comment by sean-mcmanus** [comment] 2024-03-01 18:07
@JominL This is currently "by design" -- the folder is being excluded for symbol search workspace parsing and the parse file you're seeing is caused by the opening of a file that includes header that references an include in an excluded folder and the usage of "**" at the end of your includePath ${workspaceFolder} (recursive includes) -- if you remove the "** it should be "fixed". The recursive includes feature can't function currently unless it parses the file to get the headers used...this might change in an upcoming release though, so that tag parsing might go away as a result.

**Comment by sean-mcmanus** [comment] 2024-03-01 19:49
@JominL On further investigation, it seems like this is a bug.

**Comment by JominL** [comment] 2024-03-02 15:24
Hi Sean, thank you for your quick response. 
_the folder is being excluded for symbol search workspace parsing and the parse file you're seeing is caused by the opening of a file that includes header that references an include in an excluded folder and the usage of ** at the end of your includePath ${workspaceFolder} (recursive includes)_

As a user, I don't have a deep understanding of cpptools. Seems I can get below information.
1.  cpptools still forces to find the header files acorrding to includePath ${workspaceFolder}/** , although part of the foldrs may be in "C_Cpp.files.exclude", yes? 
2. The symbol parsing result will be save into .browse.VC.db, yes? Will the " includes headers" be saved to a db file? if yes, where is it?
3.  If remove ** to disable recursive includes, "Go to Definition" almost doesn't work.


My project is more like below topology. Actually hundreds of apps in my project. It's impossible for me to list the path to fill in includePath without recursive includes. Cpptools always find headers in build folders. It makes cpptools take a lot of cpu and space. Furthermore it provides me too many dup result. 
I thought if I added a path to C_Cpp.files.exclude, cpptools won't parse it, both symbols and headers. 

![image](https://github.com/microsoft/vscode-cpptools/assets/67772533/46be4428-df34-4004-a736-679597c8fd0e)

**Comment by JominL** [comment] 2024-03-02 15:31
As usual, include and exclude should be exist in pair. If there will be a excludepath in c_cpp_properties.json to force remove some folders/files from the header result? I expect the result would be: includePath(distinct include, means w/o ** ) +[ includePath(recursive includes, w/ **) - exclude]

To check if a path need to include, the order would be:
 includePath(distinct include, means w/o **)  > exclude > includePath(recursive includes)

**Comment by sean-mcmanus** [comment] 2024-03-05 00:00
@JominL Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.19.5

**Closed as completed by sean-mcmanus** 2024-03-05 00:00 UTC
Labels: bug, Language Service, fixed, quick fix
