### ISSUE TITLE
Nested function not recognized with cross-compiler

### ISSUE THREAD

**Issue by lcrocker** [microsoft/vscode-cpptools#7686] opened 2021-06-12 20:12 UTC
Issue Type: <b>Bug</b>

1. Set "compilerPath" in c_cpp_properties.json set to GCC cross-compiler, "cStandard" to "gnu17".
2. Enter nested function (A GCC extension that should be allowed by "gnu17")
3. Note that opening curly brace of inner function is red-squiggled, and hovering over it gives error indicating that it thinks the function definition is a declaration.

Note that when "compilerPath" is set to native compiler (e.g. /usr/bin/gcc), this doesn't happen.

Extension version: 1.4.1
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.8.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1379)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.57GB (6.91GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 7e7bcae0-2227-4333-a86b-b3c3f8b1dcce|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255:30319631
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by sean-mcmanus** [comment] 2021-06-14 18:29
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/1035. The VS issue was closed as low priority (https://developercommunity.visualstudio.com/t/intellisense-in-gcc-mode-does-not-recognize-nested/794903), but I re-activated it.

**Closed as completed by sean-mcmanus** 2021-06-14 18:29 UTC
Labels: duplicate
