### ISSUE TITLE
`Include file not found...` reported for files that don't belong to the project

### ISSUE THREAD

**Issue by martincohen** [microsoft/vscode-cpptools#453] opened 2017-01-18 00:14 UTC
I have opened a file from another project in Code and it keeps reporting `Include file not found in include directory`. Because it does this, the problem view is never empty and so the cursor for `F8` (next error) is not reset for a new build, therefore `F8` moves me to next of dozens of `Include file not found...` issues. That said, the cursor should reset when I'm making a new build (but that is probably an issue for Code itself).

![image](https://cloud.githubusercontent.com/assets/421916/22045574/5d8cde42-dd1b-11e6-8fca-c2c6be2b93ab.png)

**Comment by sean-mcmanus** [comment] 2017-01-18 00:28
If you want the "Include file not found" info message to go away you'll need to add the path to the headers to the IncludePath. Does doing that not work?

**Comment by martincohen** [comment] 2017-01-18 00:32
Well as I've said, the file `app.cpp` belongs to a different project of mine (and I opened it just for a reference), so I cannot really add include paths, as the file does not belong to the project I'm working on. Also the info doesn't go away if I close the file (and run build).

**Comment by sean-mcmanus** [comment] 2017-01-18 01:21
The publishing of the "Include file not found" for non-workspace files is "by design", but I suppose we could add a setting for that later. The fact that it doesn't go away on close can be considered a bug (the didClose updating was never implemented).

**Comment by martincohen** [comment] 2017-01-18 02:17
Can the cursor in *Problem* view be at least reset when I start a new build?

**Comment by sean-mcmanus** [comment] 2017-01-18 02:35
Our extensions doesn't control the cursor or the UI in the Problems view. You should report the issue on the Microsoft/vscode GitHub page. We just supply the string and Diagnostic info (see https://github.com/Microsoft/language-server-protocol/blob/b082a3bd761f7c50db0b538e954ac467e8aa5ba8/protocol.md#textDocument_publishDiagnostics ).

**Comment by martincohen** [comment] 2017-01-18 03:10
Okay, thanks for the info, I've added the issue about the cursor reset to `vscode`: https://github.com/Microsoft/vscode/issues/18695

**Comment by BillDenton** [comment] 2017-01-18 14:03
I think I have a similar problem. The file was in the project directory (but not included in normal builds so I hadn't set the include path). After opening and then closing the file, the info message 'Include file not found in include directory' stayed in in problems window. So the issue is that the messages aren't removed when the file is closed. I seen a similar issue for a spelling extension (https://github.com/Jason-Rev/vscode-spell-checker/issues/54 and python (https://github.com/DonJayamanne/pythonVSCode/issues/634).

**Comment by sean-mcmanus** [comment] 2017-01-18 15:20
The bug where the messages aren't removed onClose has been fixed (in the C++ extension). It should be in the next update.

**Comment by martincohen** [comment] 2017-01-18 15:54
Awesome! <3

**Comment by sean-mcmanus** [comment] 2017-01-26 03:59
In 0.10.0, the "Include files missing" message goes away after the file is closed.

**Closed as completed by sean-mcmanus** 2017-01-26 03:59 UTC
Labels: bug, Language Service
