### ISSUE TITLE
namespace "std" has no member intellisense errors with clang on Windows

### ISSUE THREAD

**Issue by Garph** [microsoft/vscode-cpptools#5031] opened 2020-02-29 16:18 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Pro 1909
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

All members of `std` namespace have `namespace "std" has no member foo` warning. See the screenshot below for the most clear reproduction

**To Reproduce**

CMake generates ninja build scripts which compile my project using clang 9.0. Here are my tool versions:

```
C:\>cmake --version
cmake version 3.17.0-rc1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

C:\>ninja --version
1.8.2

C:\>clang++ --version
clang version 9.0.0 (tags/RELEASE_900/final)
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\bin
```

_CMakeLists.txt_
```
cmake_minimum_required(VERSION 3.17)

project(MyProject VERSION 0.0.1)

set (CMAKE_CXX_COMPILER "clang++")
set (CMAKE_C_COMPILER "clang")

add_executable(hello-world
    src/hello-world.cpp
)
```

Configuring a build system with `cmake` from the command line:
```
C:\Users\mattp\source\testbed\build>cmake .. -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=DEBUG
-- The C compiler identification is Clang 9.0.0 with GNU-like command-line
-- The CXX compiler identification is Clang 9.0.0 with GNU-like command-line
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/clang.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/clang.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/clang++.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/clang++.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/mattp/source/testbed/build
```

Build & execute
```
C:\Users\mattp\source\testbed\build>ninja hello-world
[2/2] Linking CXX executable hello-world.exe

C:\Users\mattp\source\testbed\build>hello-world.exe
Hello C++ World from VS Code and the C++ extension!
```

**Expected behavior**

I expect Intellisense to examine the include paths in `c_cpp_properties.json` and properly provide members of `std`

**Screenshots**

![image](https://user-images.githubusercontent.com/11324256/75610920-46c6e900-5adb-11ea-8b38-7fa41db9b6e0.png)

**Additional context**

Attaching my compile_commands.json as well in hopes it can clear up any configuration issues

compile_commands.json
```
[
{
  "directory": "C:/Users/mattp/source/testbed/build",
  "command": "clang++    -g -Xclang -gcodeview -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd   -o CMakeFiles\\hello-world.dir\\src\\hello-world.cpp.obj -c C:\\Users\\mattp\\source\\testbed\\src\\hello-world.cpp",
  "file": "C:/Users/mattp/source/testbed/src/hello-world.cpp"
}
]
```

**Comment by Colengms** [comment] 2020-03-02 18:10
Hi @Garph .  Could you run the "C/C++: Log Diagnostics" command, while that file is open, and post the output?  It should indicate how IntelliSense is configured.

Also, consider using the CMake Tools extension.  It acts as a 'configuration provider' to the C/C++ extension.

**Comment by Garph** [comment] 2020-03-04 02:50
Log Diagnostics Output:
```
-------- Diagnostics - 3/3/2020, 8:49:31 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/lib/clang/9.0.0/include",
        "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/include",
        "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt",
        "C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/shared",
        "C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/um",
        "C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/winrt"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/clang.exe",
    "compileCommands": "${workspaceFolder}/build/compile_commands.json",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": [],
    "cStandard": "c11",
    "cppStandard": "c++17",
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/lib/clang/9.0.0/include",
            "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/include",
            "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt",
            "C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/shared",
            "C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/um",
            "C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/winrt"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\mattp\source\testbed\src\hello-world.cpp ]:
    C:\USERS\MATTP\SOURCE\TESTBED\SRC\HELLO-WORLD.CPP
Translation Unit Configurations:
[ C:\Users\mattp\source\testbed\src\hello-world.cpp ]:
    Process ID: 12380
    Memory Usage: 56 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/clang.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\LLVM\LIB\CLANG\9.0.0\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.24.28314\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
    Defines:
        _DEBUG
        _DLL
        _MT
    Standard Version: ms_c++17
    IntelliSense Mode: msvc-x64
Total Memory Usage: 56 MB
```

**Comment by Garph** [comment] 2020-03-04 02:56
I gave the Clang Tools extension a try and while it can configure/build my project the Intellisense errors remain unchanged while Cmake Tools is my configuration provider. As an aside, I had to change to compiler binaries to clang-cl to support Cmake Tools' use of windows compiler switches.

**Comment by Colengms** [comment] 2020-10-28 21:10
Hi @Garph .  We've recently addressed some issues with IntelliSense w/clang-cl.  Are you still seeing this issue with the latest insiders build of the extension?

**Comment by michelleangela** [comment] 2020-12-09 19:23
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide any new information.

**Closed as completed by michelleangela** 2020-12-09 19:23 UTC
Labels: Language Service, more info needed, Feature: Configuration
