### ISSUE TITLE
Browse.VC.db file being created out of nowhere

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-cpptools#14] opened 2016-04-17 12:44 UTC
_From @yoazmenda on April 15, 2016 15:7_
- VSCode Version: 1.0
- OS Version: Windows 10 x64

Every time I open a project (Java project) a 4mb "browse.VC.db" file is being created in my repository that can't be deleted.

Steps to Reproduce:
started happening after I tried editing C,C++ files.

_Copied from original issue: Microsoft/vscode#5350_

**Comment by egamma** [comment] 2016-04-17 12:44
_From @yoazmenda on April 16, 2016 11:15_

disapeared after uninstalling c/c++ extensions

**Comment by egamma** [comment] 2016-04-17 12:44
_From @BillyONeal on April 17, 2016 9:22_

Recent versions of the C++ extensions put this file into the .vscode folder.

**Comment by outcoldman** [comment] 2016-04-20 15:25
See https://github.com/Microsoft/vscode/issues/5510 - even when you just open simple file - this extension will create `.vscode` folder with `.browse.VC.db`

**Comment by sridmad** [comment] 2016-04-20 17:51
Duplicate of issue #6

**Closed as completed by sridmad** 2016-04-20 17:52 UTC
Labels: bug, Language Service
