### ISSUE TITLE
C++/CLI Reference assemblies

### ISSUE THREAD

**Issue by CordreSmith** [microsoft/vscode-cpptools#5819] opened 2020-07-22 08:43 UTC
I am currently unable to include the `System::Data` namespace to my project.

I have added the switch to my `c_cpp_properties.json` file:
``` json
"compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe /clr",
```

I have also added the path to my referenced assemblies to my include path, as specified in #1987:
```json
"C:/Program Files (x86)/Reference Assemblies/Microsoft/Framework/.NETFramework/v4.7.2"
```

However, I still get an error `name followed by '::' must be a class or namespace name`, if I do:
```c++
using namespace System::Data;
```

The current work around for me is:
```c++
// First #using teh dll
#using "System.Data.dll"
// Then using namespace
using namespace System::Data;
```

Currently, half my team is using VSCode and the other is using Visual Studio. Thus, if this project is opened in Visual Studio (by a team member) the extra `#using` might seem unnecessary/redundant and be removed.

Is this intended behaviour?

**Comment by sean-mcmanus** [comment] 2020-07-22 19:23
Using
```
            "compilerPath": "cl.exe",
            "compilerArgs": [
                "/ZW",
                "/AI \"C:/Program Files (x86)/Reference Assemblies/Microsoft/Framework/.NETFramework/v4.7.2\"",
                "/FU \"C:/Program Files (x86)/Reference Assemblies/Microsoft/Framework/.NETFramework/v4.7.2/System.Data.dll\""
            ]
```
works with 0.28.1, but there was a regression with 0.28.2 that broke the handling of the /FU flag (and others) -- looks like it's a quick/easy fix.

**Comment by sean-mcmanus** [comment] 2020-07-22 20:07
The fix should be in 0.30.0-insiders (processing of /FU and /FI). If you try 0.28.1 and hit other issues, let us know because those would be different bugs.

**Comment by CordreSmith** [comment] 2020-07-23 11:14
@sean-mcmanus thank you for the fast response. Will test this when new update releases.

**Comment by Colengms** [comment] 2020-07-23 21:04
Reopening for now.  We'll close this issue when the fix is released.

**Comment by sean-mcmanus** [comment] 2020-08-06 00:59
This should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders . Let us know if you're still hitting issues getting it to work.

**Closed as completed** 2020-09-14 21:42 UTC
Labels: bug, Language Service, fixed, quick fix, regression
