### ISSUE TITLE
No IntelliSense error squiggles without applying forward-declaration

### ISSUE THREAD

**Issue by rohanbari** [microsoft/vscode-cpptools#7287] opened 2021-04-03 06:04 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 20.04.2 LTS
- VS Code Version: 1.55.0 `c185983a683d14c396952dd432459097bc7f757f` x64
- C/C++ Extension Version: v1.3.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): IntelliJ IDEA Keybindings, Rust, Dart, Doxygen documentation generator, *some themes*
- Does this issue involve using SSH remotely to run the extension on a remote machine?: :x:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc.)
    - Workspace: A directory, not a project
    - Project size: :x:

Consider the following program:

```cpp
#include <iostream>
#include <map>
#include <string>

using std::string;
using Map = std::map<Person, int32_t>; // This line
// Person is declared later, neither forward-declaration is applied
// still - no warnings or errors from IntelliSense

// Test class
class Person {
    string name;
    int32_t id;

  public:
    Person() = default;
    ~Person() = default;
};

int main(void) {
    Map map;
}
```

C++ IntelliSense doesn't show any error squiggles or any kind of information to perform forward declaration for `Person` if it's used and defined somewhere beneath that line.

**Steps to reproduce**
Here's my **`c_cpp_properties.json`** file (it won't be required, though):
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "intelliSenseMode": "linux-gcc-x64",
            "cppStandard": "c++20",
            "cStandard": "c99"
        }
    ],
    "version": 4
}
```
1. Create a CPP extension file with a name given.
2. Write the code mentioned above.
3. See the erroneous (not showing information) output.

**Expected behavior**
It is expected to display an error message that the `Person` was not declared in the scope, or, a forward declaration should be performed to take the `Person` class in use. When it's compiled, the compiler shows the error messages correctly:

```
sortify.cpp:18:22: error: ‘Person’ was not declared in this scope
   18 | using Map = std::map<Person, int32_t>;
      |                      ^~~~~~
sortify.cpp:18:37: error: template argument 1 is invalid
   18 | using Map = std::map<Person, int32_t>;
      |                                     ^
sortify.cpp:18:37: error: template argument 3 is invalid
sortify.cpp:18:37: error: template argument 4 is invalid
sortify.cpp: In function ‘int main()’:
sortify.cpp:33:5: error: ‘Map’ was not declared in this scope
   33 |     Map map;
      |     ^~~
```

**Screenshots**
![intellisense_problem](https://user-images.githubusercontent.com/54104015/113469748-d02eb480-946d-11eb-9a2c-50a8d9ac0759.png)
<sup>No error squiggles invoked when introduced `Person` without a forward-class declaration.</sup>

**Comment by sean-mcmanus** [comment] 2021-04-05 17:24
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/3756 . It is unlikely to be fixed because it's a design limitation of our parser implementation shared with VS (see https://developercommunity.visualstudio.com/t/C-IntelliSense-does-not-detect-issue-w/910053).

**Closed as completed by sean-mcmanus** 2021-04-05 17:24 UTC
Labels: duplicate
