### ISSUE TITLE
Specify a path for .clang-format via VS Code settings.json

### ISSUE THREAD

**Issue by rongxin-liu** [microsoft/vscode-cpptools#10445] opened 2023-01-31 13:37 UTC
### Feature Request

Currently, per [this documentation](https://code.visualstudio.com/docs/cpp/cpp-ide#_code-formatting), VS Code would look for a .clang-format file in user's workspace and apply those settings. If .clang-format file is not found, it uses its default formatting style shipped with the C/C++ extension.

Would it be possible for users to specify the .clang-format file at a location other than the workspace, perhaps in settings.json, allowing more flexibility?

**Comment by rongxin-liu** [comment] 2023-01-31 13:47
The context is we want to ship our customized .clang-format file in a Docker image. Users launching a dev container using our image (with the accompanied .devcontainer.json) can automatically use our formatting styles without extra configuration.

**Comment by michelleangela** [comment] 2023-01-31 18:55
@rongxin-liu 
Thank you for submitting this request. It is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/10006. The current workaround is to add the clang-tidy arg `--config-file=<path>` to the setting `C_Cpp.codeAnalysis.clangTidy.args`.

**Closed as completed by michelleangela** 2023-01-31 18:55 UTC
Labels: question, Feature: Code Formatting

**Comment by rongxin-liu** [comment] 2023-02-01 00:07
@michelleangela Thanks! But I'm looking into specifying a file path for `.clang-format` file, not clang-tidy config file. Is there a workaround for that?

**Comment by rongxin-liu** [comment] 2023-02-01 00:11
@michelleangela Ah, just found out that this setting does exactly what we need:

`"C_Cpp.clang_format_style": "file:/home/ubuntu/.clang-format"`

**Comment by michelleangela** [comment] 2023-02-01 00:29
@rongxin-liu 
My apologies, I misread and thought of clang-tidy. Yes, the setting `C_Cpp.clang_format_style` can be set with a path to .clang-format file.
