### ISSUE TITLE
Intellisense not working on WSL after Windows & VSCode updates

### ISSUE THREAD

**Issue by galah92** [microsoft/vscode-cpptools#1799] opened 2018-04-07 20:11 UTC
* Windows 10.0.17133 build 17133
* VSCode 1.22.1
* C/C++ extension 0.16.1

I've been using VSCode & WSL for a bunch of C & C++ projects in the past weeks - it was a great success.
I has a Windows update today along with a VSCode update, and it broke my intellisense.

I followed [the following](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md), and my `c_cpp_properties.json` file looks like that:

    {
        "configurations": [
            {
                "name": "Linux",
                "includePath": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceFolder}"
                ],
                "defines": [],
                "intelliSenseMode": "clang-x64",
                "browse": {
                    "path": [
                        "/usr/include",
                        "/usr/local/include",
                        "${workspaceFolder}"
                    ],
                    "limitSymbolsToIncludedHeaders": true,
                    "databaseFilename": ""
                },
                "cStandard": "c11",
                "cppStandard": "c++17"
            },
            {
                "name": "WSL",
                "intelliSenseMode": "clang-x64",
                "includePath": [
                    "${workspaceRoot}",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/5",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu/c++/5",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/5/backward",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include"
                ],
                "defines": [
                    "__linux__",
                    "__x86_64__"
                ],
                "browse": {
                    "path": [
                        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/5",
                        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu/c++/5",
                        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
                        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include",
                        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu",
                        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/*"
                    ],
                    "limitSymbolsToIncludedHeaders": true,
                    "databaseFilename": ""
                },
                "cStandard": "c11",
                "cppStandard": "c++17"
            }
        ],
        "version": 3
    }

Open launching VSCode the log file outputs the following:

    IntelliSense Engine = Default.
    Autocomplete is enabled.
    Error squiggles are enabled.
    File exclude: **/.git
    File exclude: **/.svn
    File exclude: **/.hg
    File exclude: **/CVS
    File exclude: **/.DS_Store
    File exclude: **/.vscode
    Search exclude: **/node_modules
    Search exclude: **/bower_components
    Search exclude: **/.vscode
    Code browsing service initialized
    Unable to retrieve file system information for C:\Users\galah\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/5. error = -1
    Unable to retrieve file system information for C:\Users\galah\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu/c++/5. error = -1
    Unable to retrieve file system information for C:\Users\galah\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include. error = -1
    Unable to retrieve file system information for C:\Users\galah\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include. error = -1
    Unable to retrieve file system information for C:\Users\galah\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed. error = -1
    Unable to retrieve file system information for C:\Users\galah\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu. error = -1
    Unable to retrieve file system information for C:\Users\galah\AppData\Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/*. error = -1
    Discovering files...
    Discovering files: 0 file(s) processed
    0 file(s) removed from database
    Done discovering files.
    Parsing remaining files...
    Parsing: 0 files(s) processed
    Done parsing remaining files.

Main thing is, it's not only that includes are being ignored - there's also no linting at all. I'm writing and updating my `.cpp` files, ommitting `;` on purpose and getting nothing from intellisense - it's like nothing is being statically analyzed anymore.

**Comment by bobbrow** [comment] 2018-04-09 22:50
Looks like another duplicate of #1694.  I haven't installed this Windows Insider build yet, but it appears to be causing problems with the extension.

**Closed as completed** 2018-04-09 22:51 UTC
Labels: bug, duplicate, Language Service

**Comment by sean-mcmanus** [comment] 2018-05-04 06:41
This should be fixed with 0.17.0-insiders2 or later: https://github.com/Microsoft/vscode-cpptools/releases . The final release is planned for early next week.
