### ISSUE TITLE
still have “cannot open source file” after setting errorSquiggles to Disabled

### ISSUE THREAD

**Issue by chujinjin101** [microsoft/vscode-cpptools#2678] opened 2018-10-16 02:05 UTC
After I set errorSquiggles to disabled， there still have “cannot open source file” error， how can I disable 
all Squiggles and disable problems presentation in the problems window

**Comment by sean-mcmanus** [comment] 2018-10-16 02:40
Oh, yeah, I'm reproing this issue. I think it might be "by design". Setting intelliSenseEngine to "Disabled" and doing a Reload Window will get rid of it, but disable all our language service functionality.

**Comment by bobbrow** [comment] 2018-10-17 17:57
Error squiggles for missing include files cannot be disabled because missing includes could have a major impact on the IntelliSense experience.  Can you update your includePath so that the squiggles go away?  Use the `"C/Cpp: Edit Configurations..."` command to get to your folder's configuration file.

**Comment by Colengms** [comment] 2019-10-11 17:59
I believe this was addressed in 0.23.0.  From the change log:

* Change the `Disabled` value for `C_Cpp.errorSquiggles` to stop showing missing header squiggles. [#3361](https://github.com/Microsoft/vscode-cpptools/issues/3361)

* Add a new (default) value of `EnabledIfIncludesResolve` to `C_Cpp.errorSquiggles`, which only shows error squiggles if include headers are successfully resolved. [PR #3421](https://github.com/Microsoft/vscode-cpptools/pull/3421)

**Closed as completed by Colengms** 2019-10-11 17:59 UTC
Labels: bug, Language Service, investigate: repro
