### ISSUE TITLE
bug report - debug C++ then the process block

### ISSUE THREAD

**Issue by zhangliukun** [microsoft/vscode-cpptools#1836] opened 2018-04-15 04:39 UTC
Hello, there is a problem when I debug C++. 
- macos 10.12.5
- vscode 1.22.1 
- C/C++ 0.16.1 ,
- Code Runner 0.9.3 , C/C++ Clang  Command Adapter 0.2.2 , CMake

The code can run successfully, but when I debug it and set a breakpoint in the function maxSubArray, the debug process is blocked, and I can't abort it in the vscode. So I have to kill it in the shell because of the high usage of my CPU.
I have never met this problem before.If I only set one breakpoint in the main function, It can debug normally. As long as I set it In the function, then block.

- The code is as follows.

```C
/*Find the contiguous subarray within an array (containing at least one number) which has the largest sum.

For example, given the array [-2,1,-3,4,-1,2,1,-5,4],
the contiguous subarray [4,-1,2,1] has the largest sum = 6.*/
#include <iostream>
#include <limits>
#include <vector>
#include <string>
using namespace std;

class Solution {
public:
    int maxSubArray(vector<int>& nums) {
        
        if(nums.size()==0)return 0;
        if(nums.size()==1)return nums[0];

        int mid = nums.size()>>1;
        vector<int> left(nums.begin(),nums.begin()+mid);
        int l = maxSubArray(left);
        int l_mid_max=nums[mid-1],l_mid=l_mid_max;
        for(int i=mid-2;i>=0;i--){

            l_mid  += nums[i];
            if(l_mid>l_mid_max){
                l_mid_max = l_mid;
            }
        }

        vector<int> right(nums.begin()+mid,nums.begin()+nums.size());
        int r = maxSubArray(right);
        int r_mid_max=nums[mid], r_mid=r_mid_max;
        for(int i=mid+1;i<nums.size();i++){
            r_mid += nums[i];
            if(r_mid>r_mid_max){
                r_mid_max = r_mid;
            }
        }

        if(l>r && l>(l_mid_max+r_mid_max))return l;
        else if(r>l && r>(l_mid_max+r_mid_max))return r;
        else return l_mid_max+r_mid_max; 
        return 0;
    } 
};

int main()
{
    Solution s;
    //int num[] = {-2,1,-3,4,-1,2,1,-5,4};
    //int num[] = {1,2};
    int num[]={-1,-1,-2,-2};
    vector<int> vc(num,num+4);
    cout<<s.maxSubArray(vc);
    return 0;
}
```
- launch.json

```C
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/leetcode_53",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb"
        }
    ]
}
```

**Comment by WardenGnaw** [comment] 2018-04-16 19:52
@zhangliukun I could not reproduce your issue.  Can you disable all extensions besides the C/C++ extension and try debugging again? 

If it still happens, can you share your currently running processes? You can get this list via ```f1``` -> ```Help: Report Performance Issue``` -> Copy and paste the info in ```Currently Running Processes```

**Comment by zhangliukun** [comment] 2018-04-18 01:05
Strangely enough, I didn't change the code and It is all right now. I could not reproduce it too. Anyway, thank you.

**Comment by WardenGnaw** [comment] 2018-04-18 18:09
Closing for now. Please reopen if you encounter the same issue again.

**Closed as completed by WardenGnaw** 2018-04-18 18:09 UTC
Labels: debugger
