### ISSUE TITLE
Rename symbol (F2) not working properly with #define

### ISSUE THREAD

**Issue by Spaark84** [microsoft/vscode-cpptools#9717] opened 2022-08-11 09:20 UTC
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.70.1
- C/C++ Extension Version: 1.11.5

### Bug Summary and Steps to Reproduce

Renaming a symbol defined with the #define directive does not work properly. After I press Enter, all usages of the symbol are renamed except for the symbol next to the #define directive. This is the case whether I select the symbol next to the #define directive or any other usage of the symbol for renaming before I press F2.

### Code sample and Logs

```shell
#define THIS_IS_A_DEFINITION 123

int foo(void)
{
  return THIS_IS_A_DEFINITION;
}


// Renaming of symbol THIS_IS_A_DEFINITION results in the following

#define THIS_IS_A_DEFINITION 123

int foo(void)
{
  return THIS_IS_A_RENAMED_DEFINITION;
}
```

**Comment by michelleangela** [comment] 2022-08-11 17:30
@Spaark84 
Thank you for reporting this issue. It is a duplicate of the existing issue https://github.com/microsoft/vscode-cpptools/issues/6194, so I will close this issue..

**Closed as completed by michelleangela** 2022-08-11 17:30 UTC
Labels: bug, duplicate, Language Service, Works in VS, Feature: Find All References, Feature: Rename

**Comment by sean-mcmanus** [comment] 2025-12-04 00:53
@Spaark84 Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.29.2
