### ISSUE TITLE
Memory leak and crash

### ISSUE THREAD

**Issue by Ola1707** [microsoft/vscode-cpptools#6922] opened 2021-02-07 19:02 UTC
Type: General

**Describe the bug**
- OS and Version: The VS code is installed on Windows 10, and then connected through ssh to ubuntu 18
- VS Code Version: 1.53
- C/C++ Extension Version: 1.2.0

- While working there was a huge memory leak and the extension's memory was 58.7G 
- At this point the machine stopped working.

1. I am not sure what caused this behavior, I didn't use a debugger, or tried to run anything.
2. The only thing I used is a reference by click (on a class).

**Screenshots**
![image](https://user-images.githubusercontent.com/34832826/107156504-628f6c00-6987-11eb-8f3f-02fbcc92e6a8.png)

**Comment by michelleangela** [comment] 2021-02-08 22:57
@Ola1707 
Could you provide additional information and the following logs to help us further investigate?

1. Log output from enabling the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) and then reproduce the issue.
2. Log output from running the command `C/C++: Log Diagnostics`
3. What is the estimated size of your project?
4. Did you do a "find all reference" on a symbol while the extension is still tag parsing?
5. Have you run into this issue before with the same project and different version of the C++ extension or are you seeing this for the first time with version 1.2.0?

**Comment by sean-mcmanus** [comment] 2021-02-09 23:49
Also...
What exactly does "reference by click" mean? Find All References or Go to Definition? Does it not use high memory until that is done? If you're able to attach a debugger to cpptools when the memory is increasing the fastest that could show what is contributing to the memory usage (see https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv).

**Comment by ToppDev** [comment] 2021-03-01 15:00
As I have the same or a similar problem I will use this thread to share my information.

### Description

`cpp-tools-srv` Process starts increasing its memory usage (approx. 500MB/s) till the memory and swap are full and the whole system freezes. Also I noticed, that my hard drive has a lot of IOs when it happens.

### System Information

* C/C++ Extension: v1.2.2
* VSCode Version: 1.53.2 (OSS)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T21:13:58.622Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: ArchLinux Linux x64 5.11.2-arch1-1
* All Extensions except C/C++ disabled

### Steps to reproduce

Sadly I did not figure out what exactly causes the problem. Sometimes it happens straight away, sometimes it takes me 5 minutes to get the crash.

I am not sure if it is related to the project I am working with, but it happens in a fresh clone of this project https://github.com/thedmd/imgui-node-editor

I just have the files open in the screenshot. Switch between the files, scroll around and hover over the functions to see the Tooltips.

### Screenshots

![Bpytop](https://user-images.githubusercontent.com/17766093/109511281-2c836a80-7aa3-11eb-9aa7-19654f39984a.png)

Process Explorer:
![ProcessExplorer](https://user-images.githubusercontent.com/17766093/109511319-360cd280-7aa3-11eb-8034-f72bc6dfe7ad.png)

Language Server Log (notice the ToolTip Window in Line 739 is only saying "Loading...")
![LanguageServer](https://user-images.githubusercontent.com/17766093/109511329-386f2c80-7aa3-11eb-9a7d-d873ba79d56a.png)

**Comment by sean-mcmanus** [comment] 2021-03-19 20:23
@Ola1707 We fixed a memory leak crash with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders . Let us know if your issue still repros.

**Comment by berndporr** [comment] 2021-04-13 09:47
Version: 1.55.1
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T15:01:24.315Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-70-generic
![screenshot](https://user-images.githubusercontent.com/1679394/114532483-c9a9f500-9c44-11eb-8dc9-5d14bec841db.png)
I'm using it via an SSH remote session. Host is Ubuntu 20.04.2 LTS and I'm editing code on a Raspberry PI. The Raspberry PI runs out of memory very quickly. It started to go haywire after I've included boost headers which are quite extensive so I guess there is the problem roughly.

**Comment by AlexeyMoiseev** [comment] 2021-05-01 12:07
Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
C/C++ Extension: v1.3.1
Remote-SSH: 0.65.4

Same problem. The local host is windows 10, remote host is Ubuntu 18.04.5. The cpptools eat up all the memory in a few hours. This blocks the remote host and any connections until the system kills the process.

**Comment by sean-mcmanus** [comment] 2021-05-03 18:27
@AlexeyMoiseev Can you confirm that this with cpptools or cpptools-srv? During the "few hours" is the CPU usage idle if you don't make any edits? Do you know what action causes the memory to accumulate? A memory leak is a symptom for which there could be multiple different root causes, so it's preferred to file a separate issue with your particular repro details.

**Comment by AlexeyMoiseev** [comment] 2021-05-04 07:50
In my case, it looks like this:
- on start cpptools and cpptools-srv eat 600MB and node (bootstrap-fork --type = WatcherService) about 1.7gb;
- after a while, another cpptools-srv appears and eats up 600MB;
- if you work in already open tabs, memory after 30 minutes increases by another 200MB for each cpptools*;
- during the build task and launch task, the cpptools memory grows and is not reset after the task is completed;
- two more cpptools-srvs of 600MB are created;
- after several operations with git cpptools grew to 4.5gb;
- and after half an hour up to 8GB;
- if you kill cpptools, then the new running process immediately gains memory up to 4.4GB;
- so every few hours you need to restart the vscode completely.

> Can you confirm if this is with cpptools or cpptools-srv?
This is cpptools.

> During the "few hours" is the CPU usage idle if you don't make any edits?
In this case, all is Ok.

**Comment by sean-mcmanus** [comment] 2021-05-04 20:21
The 600 MB usage sounds normal. cpptools memory isn't expected to grow due to build/launch tasks since cpptools doesn't handle any build/launch processing -- this implies that your build is creating files that cpptools is processing (although that processing still shouldn't be causing excessive memory usage). You could try adding the build output folder to C_Cpp.files.exclude. The cpptools processing using 4 GB after being killed is unusual. We don't know yet what could be the cause of these memory issues (we haven't found a repro yet, except for with really large workspaces). Another known cause could be a symlink to a large folder, which could be fixed via adding that to your C_Cpp.files.exclude setting.

**Closed as completed** 2021-07-04 11:16 UTC
Labels: Language Service, more info needed, performance, remote
