### ISSUE TITLE
Command 'C/C++: Edit Configurations (UI)' resulted in an error (command 'C_Cpp.ConfigurationEditUI' not found)

### ISSUE THREAD

**Issue by iskettan** [microsoft/vscode-cpptools#6368] opened 2020-10-21 15:01 UTC
Hello,

I recently encountered a new issue with the C/C++ extension. (I am using the remote ssh tool).

All the C/C++ commands don't work. I tried to edit Configuration (UI) command, and the Reset Intellisense Database. All of them show me this error:

Command 'C/C++: Edit Configurations (UI)' resulted in an error (command 'C_Cpp.ConfigurationEditUI' not found)

Command 'C/C++: Reset IntelliSense Database' resulted in an error (command 'C_Cpp.ResetDatabase' not found)

It seems as if the extension is not properly installed on the remote machine. I tried uninstalling the extension, and reinstalling it. Moreover, I tried using another remote machine, but the issue is the same.

The issue started two days ago.

Thanks

**Comment by sean-mcmanus** [comment] 2020-10-21 23:29
What OS are you on (for the remote machine)? What version of the extension are you trying to install? What method of installation, from the marketplace or a .vsix?

**Comment by wgledbetter** [comment] 2020-10-30 18:44
I was having a similar issue on Fedora 32 with VSCode 1.50.1 and C/C++ 1.0.1

Cpptools was installed through vscode extension manager.

Errors:
Command 'C/C++: Reset IntelliSense Database' resulted in an error (command 'C_Cpp.ResetDatabase' not found)
Command 'C/C++: Rescan Workspace' resulted in an error (command 'C_Cpp.RescanWorkspace' not found)

A full re-install seems to have fixed it. Make sure you delete ~/.vscode and ~/.config/Code.

**Comment by michelleangela** [comment] 2020-12-09 19:34
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide any new information.

**Closed as completed by michelleangela** 2020-12-09 19:34 UTC
Labels: more info needed

**Comment by mjml** [comment] 2020-12-15 22:33
Not sure why this was closed since it was very recent and no fix was announced. I'm using the latest C/C++ extension and seeing the exact same thing. While I can open my c_cpp_properties.json file in text mode, I can't use the usual UI for editing intellisense parameters and none of the usual autocomplete / symbol indexing features are working. Basically this extension just stopped working.

**Comment by sean-mcmanus** [comment] 2020-12-15 22:38
Not enough info was given. Also, seeing the exact same symptom doesn't necessarily mean it's the same bug. Can you file a new issue with more repro info?

**Comment by mjml** [comment] 2020-12-15 22:40
Well, it just occurred randomly one day when I sat down to work. I was hovering a symbol to follow to its definition (something I currently do every session) and the option wasn't in the context menu. Curious, I went to check intellisense properties and the C/C++ UI just wouldn't open.

I just did an update to 1.52 and it seems to be fine now. <shrug>

**Comment by sean-mcmanus** [comment] 2020-12-15 22:44
It sounds like the extension got deactivated. I'm not familiar with what could cause that. Could be some VS Code issue.

The next time that happens, maybe look at Help->Toggle Developer Tools->Console to see if there are any error messages reported.

**Comment by mjml** [comment] 2020-12-15 22:45
I went to the extension page and it still offered the option to disable the extension. Is that what you mean? One fix that occurred to me was to disable the re-enable it.

**Comment by jparr721** [comment] 2021-01-05 03:47
Unfortunately, I am also encountering this issue recently on the m1 Mac. Not sure if there's something potentially up with that. I am, however, running vscode insiders so I'm not sure if that could cause a problem.

**Comment by sean-mcmanus** [comment] 2021-01-05 18:04
@jparr721 Does uninstalling/installing the extension fix the issue? Does installing the offline vsix (https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.3) fix the issue?

**Comment by jparr721** [comment] 2021-01-06 02:47
Oh boy do I feel stupid. I somehow downloaded the wrong insider build, which seems to have silently killed my editor's ability to run the C++ plugin. Problem was solved on a fresh reinstall the with the _proper_ version. Sorry for any confusion here.

**Comment by sean-mcmanus** [comment] 2021-01-06 02:52
@jparr721 Yeah, I've made that mistake before -- it's supposed to show a warning popup when your OS doesn't match. Let us know if you think there's something else we can do to warn users about this mistake.

![image](https://user-images.githubusercontent.com/19859882/103723511-1f586c80-4f87-11eb-941f-a2b1f78d6f27.png)

**Comment by jparr721** [comment] 2021-01-06 03:51
I _did_ see a warning for `architecture not supported`, but the cmake functions worked just fine as did the run button. I'm not sure how complex the detection would need to be to know outside of that since I assume it tries to use the wrong vsix file, leading to the silent failure?

**Comment by sean-mcmanus** [comment] 2021-01-06 22:34
Our extension doesn't output `architecture not supported`. We do output `"Architecture <arch> is not supported. "`, but that is only output in response to the host architecture and not the vsix or binary's architecture: https://github.com/microsoft/vscode-cpptools/blob/release/Extension/src/main.ts#L40 . Do you know what version of the vsix you installed?
