### ISSUE TITLE
Having two files with the same name will make the debugger break in each file

### ISSUE THREAD

**Issue by batortaller** [microsoft/vscode-cpptools#4721] opened 2019-12-09 20:24 UTC
Type: Debugger
The bug occurs when debuggin C++ code with VSCode. When a source files name is not unique (there are more than 1 files with the same name) putting a breakpoint in that file will put the breakpoint in each file.

Minimal repro: https://github.com/bator-prezi/vscode-debug-repro

**Describe the bug**
- OS and Version: macOS 10.14.6
- VS Code Version: 
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
See repro on: https://github.com/bator-prezi/vscode-debug-repro

**Additional context**

**Comment by pieandcakes** [comment] 2019-12-09 20:56
Duplicate of #977

**Closed as completed by pieandcakes** 2019-12-09 20:56 UTC
Labels: duplicate, debugger
