### ISSUE TITLE
Copy declaration / definition results are not formatted when pasted

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10956] opened 2023-05-15 22:46 UTC
It gives:

![image](https://github.com/microsoft/vscode-cpptools/assets/19859882/93aab0c3-ca5c-4a72-b756-255dd11f5936)

The issue doesn't repro with Create declaration / definition, in which case the formatting is applied after the creation is done.

I think the root cause of the bug is https://github.com/microsoft/vscode-cpptools/issues/10236 .

**Comment by sean-mcmanus** [comment] 2023-09-07 20:58
This issue is reproing with Extract Function too.

**Comment by sean-mcmanus** [comment] 2023-11-07 00:42
@bobbrow It feels to me like this issue isn't high enough priority for 1.19.0 compared to the other To Do stuff (unless we get more user feedback or reports of bugs caused by this), i.e. it's at the bottom of my list unless someone else wanted to investigate it.

**Comment by bobbrow** [comment] 2023-11-07 17:34
@sean-mcmanus, sure. Should we close as a dupe of https://github.com/microsoft/vscode-cpptools/issues/10236?  I think that maybe addressing that takes care of this one.

**Comment by sean-mcmanus** [comment] 2023-11-08 02:01
@bobbrow I'm not sure. But https://github.com/microsoft/vscode-cpptools/issues/10236 seems low priority too.

**Comment by sean-mcmanus** [comment] 2023-11-14 02:11
Fixing this issue could fix https://github.com/microsoft/vscode-cpptools/issues/11675 and https://github.com/microsoft/vscode-cpptools/issues/11673 .

**Closed as completed** 2024-03-26 22:42 UTC
Labels: bug, Language Service, fixed, Feature: Code Formatting, Feature: Refactoring, Feature: Create Declaration or Definition
