### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-cpptools#650] opened 2017-04-19 21:43 UTC
_From @tiamattia on April 19, 2017 21:24_

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.8.0-46-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-solarized|Braver|0.0.3|
|uncrustify|LaurentTreguier|1.5.1|
|cpptools|ms-vscode|0.10.5|
|sublime-keybindings|ms-vscode|2.0.1|;

I'm trying to configure a remote target debugging session. The target is an STM32 microcontroller and the debugging server is OpenOCD.
When launching the debug I get this error: "Cannot read property 'toLowerCase' of undefined"

---

Steps to Reproduce:

1. `{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "STM32 Attach",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/bin/discovery-radio.elf",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false,
            "setupCommands": [
                {
                    "text": "target remote localhost:3333"
                },
                {
                    "text": "file ${workspaceRoot}/bin/discovery-radio.elf"
                },
                {
                    "text": "monitor reset halt"
                }
            ],
            "customLaunchSetupCommands": [
                {
                    "text": "monitor reset halt"
                }
            ],
            "MIMode": "gdb",
            "launchCompleteCommand": "exec-continue",
            "miDebuggerPath": "/usr/bin/arm-miosix-eabi-gdb",
            "miDebuggerServerAddress": "localhost:3333",
            "debugServerPath": "/usr/bin/openocd",
            "debugServerArgs": "-f ${workspaceRoot}/somepath/stm32f4discovery.cfg",
            "serverStarted": "Info\\ :\\ [\\w\\d\\.]*:\\ hardware",
            "filterStderr": true
        }
    ]
}`

2. Launch debug

_Copied from original issue: Microsoft/vscode#25042_

**Comment by weinand** [comment] 2017-04-19 21:43
_From @mjbvz on April 19, 2017 21:42_

I've also seen this error. Here's the only trace I see:

```
Cannot read property 'toLowerCase' of undefined
e.doShow @ //Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
```

**Comment by sean-mcmanus** [comment] 2017-04-20 00:44
@tiamattia @mjbvz We should have a fix in our next update. In the mean time you can try working around this by changing the code that calls the toLower at `.vscode/extensions/ms-vscode.cpptools-0.10.5/out/src/Debugger/nativeAttach.js`
to 
`            processEntries.sort((a, b) => {
                if (a.name == undefined)
                    return 1;
                if (b.name == undefined)
                    return -1;
                return a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1;
            });`
and in attachToProcess.js: 
`.sort((a, b) => {
                        if (a.name == undefined)
                            return 1;
                        if (b.name == undefined)
                            return -1;
                        return a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1;
                    })`

**Comment by marcoconti83** [comment] 2017-04-20 16:44
Hi @sean-mcmanus , thanks for the tip, however just changing those files for me does not fix the issue. Is there anything I need to do after changing those files?

**Comment by sean-mcmanus** [comment] 2017-04-20 17:46
@marcoconti83 Hmm...that should be it. You have to restart your VS Code instance (and make sure you're changing the correct file, i.e. if you're on Insiders or not). What error are you getting now? When I change the < to > in the javascript, and then start an Attach, I see the list in reverse order. Do you see that? From your bug description, it's not clear that we are the cause of the toLowerCase error message, but it sounded like weinand debugged it and thought we were the cause.

**Comment by marcoconti83** [comment] 2017-04-20 22:02
@sean-mcmanus thanks for your reply. After further investigation I believe my issue to be unrelated to this. I ended up on the linked original issue (on the vscode repo) by searching for the exact error on a search engine, but I now believe this is caused for me by another, unrelated plugin and not cpptools. Sorry for the mix-up!

**Comment by pieandcakes** [comment] 2017-04-21 20:30
@marcoconti83 Closing this issue. If you need further help, please comment or file a new issue.

**Closed as completed** 2017-04-21 20:29 UTC
Labels: bug, debugger
