### ISSUE TITLE
"iostream" is not an importable headerC/C++(3270) on Macos Clang 16

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#10451] opened 2023-02-01 20:39 UTC
### Environment

- OS and Version: Macos 13.1
- VS Code Version: 1.75.0-insider
- C/C++ Extension Version:  1.14.0

### Bug Summary and Steps to Reproduce

Bug Summary:

Want to use the modules feature and try simply "import <iostream>;", then show the error "iostream" is not an importable headerC/C++(3270). It's a Intellisense error because it will pass the complie and output file as expected by adding -fmodules -std=c++2b options to clang.

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
-------- Diagnostics - 02/02/2023, 04:30:59
Version: 1.14.0
Current Configuration:
{
    "name": "Homebrew LLVM HEAD",
    "includePath": [
        "/Users/username/cpp/**"
    ],
    "defines": [
        "LDFLAGS=\"-L/opt/homebrew/opt/llvm/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++\""
    ],
    "macFrameworkPath": [
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/opt/homebrew/opt/llvm/bin/clang++",
    "compilerArgs": [
        "-std=c++2b",
        "-fmodules"
    ],
    "cStandard": "c17",
    "cppStandard": "c++23",
    "intelliSenseMode": "macos-clang-arm64",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    },
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true
}
Translation Unit Mappings:
[ /Users/username/cpp/main.cpp ]:
    /Users/username/cpp/main.cpp
Translation Unit Configurations:
[ /Users/username/cpp/main.cpp ]:
    Process ID: 4307
    Memory Usage: 115 MB
    Compiler Path: /opt/homebrew/opt/llvm/bin/clang++
    Includes:
        /opt/homebrew/Cellar/llvm/HEAD-d9e778d_1/include/c++/v1
        /opt/homebrew/Cellar/llvm/HEAD-d9e778d_1/lib/clang/16/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Frameworks
    Defines:
        LDFLAGS="-L/opt/homebrew/opt/llvm/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++"
    Standard Version: c++23
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=160000
Total Memory Usage: 115 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 9205
```

**Comment by Colengms** [comment] 2023-02-03 19:01
Hi @nilshiroqaq .  I believe this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6302 .  Support for modules is still under development.  Closing this as a duplicate.

**Closed as not planned by Colengms** 2023-02-03 19:01 UTC
