### ISSUE TITLE
Spurious 'exprected a ;' IntelliSense error in Linux kernel modules

### ISSUE THREAD

**Issue by kutukvpavel** [microsoft/vscode-cpptools#8616] opened 2021-12-31 23:41 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Win7x64 / Win10
- VS Code Version: 1.63.2
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Extension Pack, CMake etc; the issue down't seem to be related to any of them.
- If using SSH remote, specify OS of remote machine: RPi2 (arm), latest raspbian (bullseye, 5.10 kernel)
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

IntelliSense detects a spurious C/C++ error 65 ("expected a ;") in expansion of macro MODULE_LICENSE(...) - a standard part of Linux kernel module source file:

```
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>

MODULE_DESCRIPTION("My example module");
MODULE_AUTHOR("MDC");
MODULE_LICENSE("GPL");  // <-----

...
```

The macro is expanded into `#define MODULE_LICENSE(_license) MODULE_FILE MODULE_INFO(license, _license)`
Since all the other macros that involve MODULE_INFO() are fine, the problem must be somewhere in the MODULE_FILE macro. It is defined as `#define MODULE_FILE	MODULE_INFO(file, KBUILD_MODFILE);`.
And indeed, using `MODULE_FILE` directly produces the same error. However, I'm fairly new to Linux development, and I wasn't able to investigate much further.

**Steps to reproduce**

1. Set up VSCode for targeting Linux (arm, gcc v10, std=gnu89).
2. Set up include paths according to your distro/kernel (install kernel header packages if needed).
2. Create a barebones kernel module (+ your preferred build method, I use GNU make + kbuild). See code samples.
3. Observe the error on line №7.

**Expected behavior**
This code compiles fine. So, no error is expected.

**Code sample and logs**

- Code sample
```
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>

MODULE_DESCRIPTION("My example module");
MODULE_AUTHOR("MDC");
MODULE_LICENSE("GPL");

static int dummy_init(void)
{

    pr_debug("My Module is loaded!\n");
    return 0;
}

static void dummy_exit(void)
{
    pr_debug("My Module is unloaded!\n");
}

module_init(dummy_init);
module_exit(dummy_exit);
```

- Configurations in `c_cpp_properties.json`: see below

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 1/1/2022, 2:34:32 AM
Version: 1.7.1
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**",
        "/usr/include",
        "/usr/local/include",
        "/usr/src/linux-headers-5.10.63-v7l+/arch/arm/include/generated",
        "/usr/src/linux-headers-5.10.63-v7l+/arch/arm/include",
        "/usr/src/linux-headers-5.10.63-v7l+/include"
    ],
    "defines": [
        "__GNUC__",
        "__KERNEL__",
        "KBUILD_MODNAME=\"dummy_modname\""
    ],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu89",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "gcc-arm",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "/usr/include",
            "/usr/local/include",
            "/usr/src/linux-headers-5.10.63-v7l+/arch/arm/include/generated",
            "/usr/src/linux-headers-5.10.63-v7l+/arch/arm/include",
            "/usr/src/linux-headers-5.10.63-v7l+/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/pi/vscode/kernel_module/my_module.c ]:
    /home/pi/vscode/kernel_module/my_module.c
    /usr/src/linux-headers-5.10.63-v7l+/include/linux/module.h
Translation Unit Configurations:
[ /home/pi/vscode/kernel_module/my_module.c ]:
    Process ID: 10216
    Memory Usage: 32 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/src/linux-headers-5.10.63-v7l+/arch/arm/include/generated
        /usr/src/linux-headers-5.10.63-v7l+/arch/arm/include
        /usr/src/linux-headers-5.10.63-v7l+/include
        /usr/lib/gcc/arm-linux-gnueabihf/10/include
        /usr/local/include
        /usr/include/arm-linux-gnueabihf
        /usr/include
    Defines:
        __GNUC__
        __KERNEL__
        KBUILD_MODNAME="dummy_modname"
    Standard Version: c89
    IntelliSense Mode: linux-gcc-arm
    Other Flags:
        --gcc
        --gnu_version=100201
Total Memory Usage: 32 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 11709
```

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / armhf)' (10581 KB)  Done!
Downloading package 'ClangFormat (Linux / armhf)' (880 KB)  Done!
Downloading package 'OpenDebugAD7 (Linux ARM)' (30325 KB)  Done!

Installing package 'C/C++ language components (Linux / armhf)'
Installing package 'ClangFormat (Linux / armhf)'
Installing package 'OpenDebugAD7 (Linux ARM)'

Finished installing dependencies

loggingLevel has changed to: Debug
File exclude: **/.vscode
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/Thumbs.db
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/*.code-search
Discovering files...
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /usr/lib/gcc/arm-linux-gnueabihf/10/include/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /home/pi/vscode/kernel_module/
  Processing folder (recursive): /usr/src/linux-headers-5.10.63-v7l+/arch/arm/include/
  Processing folder (recursive): /usr/src/linux-headers-5.10.63-v7l+/include/
  Discovering files: 11709 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populate include completion cache.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Shutting down IntelliSense server: /home/pi/vscode/kernel_module/my_module.c
Discovering files...
  Processing folder (recursive): /usr/include/
Checking for syntax errors: file:///home/pi/vscode/kernel_module/my_module.c
  Processing folder (recursive): /usr/lib/gcc/arm-linux-gnueabihf/10/include/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /home/pi/vscode/kernel_module/
  Processing folder (recursive): /usr/src/linux-headers-5.10.63-v7l+/arch/arm/include/
  Processing folder (recursive): /usr/src/linux-headers-5.10.63-v7l+/include/
  Discovering files: 11709 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Populate include completion cache.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
  tag parsing file: /usr/include/linux/module.h
  tag parsing file: /usr/src/linux-headers-5.10.63-v7l+/include/uapi/linux/module.h
Done parsing open files.
sending compilation args for /home/pi/vscode/kernel_module/my_module.c
  include: /usr/src/linux-headers-5.10.63-v7l+/arch/arm/include/generated
  include: /usr/src/linux-headers-5.10.63-v7l+/arch/arm/include
  include: /usr/src/linux-headers-5.10.63-v7l+/include
  include: /usr/lib/gcc/arm-linux-gnueabihf/10/include
  include: /usr/local/include
  include: /usr/include/arm-linux-gnueabihf
  include: /usr/include
  define: __STDC__=1
  define: __STDC_HOSTED__=1
  define: __GNUC__=10
  define: __GNUC_MINOR__=2
  define: __GNUC_PATCHLEVEL__=1
  define: __VERSION__="10.2.1 20210110"
  define: __ATOMIC_RELAXED=0
  define: __ATOMIC_SEQ_CST=5
  define: __ATOMIC_ACQUIRE=2
  define: __ATOMIC_RELEASE=3
  define: __ATOMIC_ACQ_REL=4
  define: __ATOMIC_CONSUME=1
  define: __FINITE_MATH_ONLY__=0
  define: __SIZEOF_INT__=4
  define: __SIZEOF_LONG__=4
  define: __SIZEOF_LONG_LONG__=8
  define: __SIZEOF_SHORT__=2
  define: __SIZEOF_FLOAT__=4
  define: __SIZEOF_DOUBLE__=8
  define: __SIZEOF_LONG_DOUBLE__=8
  define: __SIZEOF_SIZE_T__=4
  define: __CHAR_BIT__=8
  define: __BIGGEST_ALIGNMENT__=8
  define: __ORDER_LITTLE_ENDIAN__=1234
  define: __ORDER_BIG_ENDIAN__=4321
  define: __ORDER_PDP_ENDIAN__=3412
  define: __BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __FLOAT_WORD_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __SIZEOF_POINTER__=4
  define: __SIZE_TYPE__=unsigned int
  define: __PTRDIFF_TYPE__=int
  define: __WCHAR_TYPE__=unsigned int
  define: __WINT_TYPE__=unsigned int
  define: __INTMAX_TYPE__=long long int
  define: __UINTMAX_TYPE__=long long unsigned int
  define: __CHAR16_TYPE__=short unsigned int
  define: __CHAR32_TYPE__=unsigned int
  define: __SIG_ATOMIC_TYPE__=int
  define: __INT8_TYPE__=signed char
  define: __INT16_TYPE__=short int
  define: __INT32_TYPE__=int
  define: __INT64_TYPE__=long long int
  define: __UINT8_TYPE__=unsigned char
  define: __UINT16_TYPE__=short unsigned int
  define: __UINT32_TYPE__=unsigned int
  define: __UINT64_TYPE__=long long unsigned int
  define: __INT_LEAST8_TYPE__=signed char
  define: __INT_LEAST16_TYPE__=short int
  define: __INT_LEAST32_TYPE__=int
  define: __INT_LEAST64_TYPE__=long long int
  define: __UINT_LEAST8_TYPE__=unsigned char
  define: __UINT_LEAST16_TYPE__=short unsigned int
  define: __UINT_LEAST32_TYPE__=unsigned int
  define: __UINT_LEAST64_TYPE__=long long unsigned int
  define: __INT_FAST8_TYPE__=signed char
  define: __INT_FAST16_TYPE__=int
  define: __INT_FAST32_TYPE__=int
  define: __INT_FAST64_TYPE__=long long int
  define: __UINT_FAST8_TYPE__=unsigned char
  define: __UINT_FAST16_TYPE__=unsigned int
  define: __UINT_FAST32_TYPE__=unsigned int
  define: __UINT_FAST64_TYPE__=long long unsigned int
  define: __INTPTR_TYPE__=int
  define: __UINTPTR_TYPE__=unsigned int
  define: __GXX_ABI_VERSION=1014
  define: __SCHAR_MAX__=0x7f
  define: __SHRT_MAX__=0x7fff
  define: __INT_MAX__=0x7fffffff
  define: __LONG_MAX__=0x7fffffffL
  define: __LONG_LONG_MAX__=0x7fffffffffffffffLL
  define: __WCHAR_MAX__=0xffffffffU
  define: __WCHAR_MIN__=0U
  define: __WINT_MAX__=0xffffffffU
  define: __WINT_MIN__=0U
  define: __PTRDIFF_MAX__=0x7fffffff
  define: __SIZE_MAX__=0xffffffffU
  define: __SCHAR_WIDTH__=8
  define: __SHRT_WIDTH__=16
  define: __INT_WIDTH__=32
  define: __LONG_WIDTH__=32
  define: __LONG_LONG_WIDTH__=64
  define: __WCHAR_WIDTH__=32
  define: __WINT_WIDTH__=32
  define: __PTRDIFF_WIDTH__=32
  define: __SIZE_WIDTH__=32
  define: __INTMAX_MAX__=0x7fffffffffffffffLL
  define: __INTMAX_C(c)=c ## LL
  define: __UINTMAX_MAX__=0xffffffffffffffffULL
  define: __UINTMAX_C(c)=c ## ULL
  define: __INTMAX_WIDTH__=64
  define: __SIG_ATOMIC_MAX__=0x7fffffff
  define: __SIG_ATOMIC_MIN__=(-__SIG_ATOMIC_MAX__ - 1)
  define: __SIG_ATOMIC_WIDTH__=32
  define: __INT8_MAX__=0x7f
  define: __INT16_MAX__=0x7fff
  define: __INT32_MAX__=0x7fffffff
  define: __INT64_MAX__=0x7fffffffffffffffLL
  define: __UINT8_MAX__=0xff
  define: __UINT16_MAX__=0xffff
  define: __UINT32_MAX__=0xffffffffU
  define: __UINT64_MAX__=0xffffffffffffffffULL
  define: __INT_LEAST8_MAX__=0x7f
  define: __INT8_C(c)=c
  define: __INT_LEAST8_WIDTH__=8
  define: __INT_LEAST16_MAX__=0x7fff
  define: __INT16_C(c)=c
  define: __INT_LEAST16_WIDTH__=16
  define: __INT_LEAST32_MAX__=0x7fffffff
  define: __INT32_C(c)=c
  define: __INT_LEAST32_WIDTH__=32
  define: __INT_LEAST64_MAX__=0x7fffffffffffffffLL
  define: __INT64_C(c)=c ## LL
  define: __INT_LEAST64_WIDTH__=64
  define: __UINT_LEAST8_MAX__=0xff
  define: __UINT8_C(c)=c
  define: __UINT_LEAST16_MAX__=0xffff
  define: __UINT16_C(c)=c
  define: __UINT_LEAST32_MAX__=0xffffffffU
  define: __UINT32_C(c)=c ## U
  define: __UINT_LEAST64_MAX__=0xffffffffffffffffULL
  define: __UINT64_C(c)=c ## ULL
  define: __INT_FAST8_MAX__=0x7f
  define: __INT_FAST8_WIDTH__=8
  define: __INT_FAST16_MAX__=0x7fffffff
  define: __INT_FAST16_WIDTH__=32
  define: __INT_FAST32_MAX__=0x7fffffff
  define: __INT_FAST32_WIDTH__=32
  define: __INT_FAST64_MAX__=0x7fffffffffffffffLL
  define: __INT_FAST64_WIDTH__=64
  define: __UINT_FAST8_MAX__=0xff
  define: __UINT_FAST16_MAX__=0xffffffffU
  define: __UINT_FAST32_MAX__=0xffffffffU
  define: __UINT_FAST64_MAX__=0xffffffffffffffffULL
  define: __INTPTR_MAX__=0x7fffffff
  define: __INTPTR_WIDTH__=32
  define: __UINTPTR_MAX__=0xffffffffU
  define: __GCC_IEC_559=2
  define: __GCC_IEC_559_COMPLEX=2
  define: __FLT_EVAL_METHOD__=0
  define: __FLT_EVAL_METHOD_TS_18661_3__=0
  define: __DEC_EVAL_METHOD__=2
  define: __FLT_RADIX__=2
  define: __FLT_MANT_DIG__=24
  define: __FLT_DIG__=6
  define: __FLT_MIN_EXP__=(-125)
  define: __FLT_MIN_10_EXP__=(-37)
  define: __FLT_MAX_EXP__=128
  define: __FLT_MAX_10_EXP__=38
  define: __FLT_DECIMAL_DIG__=9
  define: __FLT_MAX__=3.4028234663852886e+38F
  define: __FLT_NORM_MAX__=3.4028234663852886e+38F
  define: __FLT_MIN__=1.1754943508222875e-38F
  define: __FLT_EPSILON__=1.1920928955078125e-7F
  define: __FLT_DENORM_MIN__=1.4012984643248171e-45F
  define: __FLT_HAS_DENORM__=1
  define: __FLT_HAS_INFINITY__=1
  define: __FLT_HAS_QUIET_NAN__=1
  define: __DBL_MANT_DIG__=53
  define: __DBL_DIG__=15
  define: __DBL_MIN_EXP__=(-1021)
  define: __DBL_MIN_10_EXP__=(-307)
  define: __DBL_MAX_EXP__=1024
  define: __DBL_MAX_10_EXP__=308
  define: __DBL_DECIMAL_DIG__=17
  define: __DBL_MAX__=((double)1.7976931348623157e+308L)
  define: __DBL_NORM_MAX__=((double)1.7976931348623157e+308L)
  define: __DBL_MIN__=((double)2.2250738585072014e-308L)
  define: __DBL_EPSILON__=((double)2.2204460492503131e-16L)
  define: __DBL_DENORM_MIN__=((double)4.9406564584124654e-324L)
  define: __DBL_HAS_DENORM__=1
  define: __DBL_HAS_INFINITY__=1
  define: __DBL_HAS_QUIET_NAN__=1
  define: __LDBL_MANT_DIG__=53
  define: __LDBL_DIG__=15
  define: __LDBL_MIN_EXP__=(-1021)
  define: __LDBL_MIN_10_EXP__=(-307)
  define: __LDBL_MAX_EXP__=1024
  define: __LDBL_MAX_10_EXP__=308
  define: __DECIMAL_DIG__=17
  define: __LDBL_DECIMAL_DIG__=17
  define: __LDBL_MAX__=1.7976931348623157e+308L
  define: __LDBL_NORM_MAX__=1.7976931348623157e+308L
  define: __LDBL_MIN__=2.2250738585072014e-308L
  define: __LDBL_EPSILON__=2.2204460492503131e-16L
  define: __LDBL_DENORM_MIN__=4.9406564584124654e-324L
  define: __LDBL_HAS_DENORM__=1
  define: __LDBL_HAS_INFINITY__=1
  define: __LDBL_HAS_QUIET_NAN__=1
  define: __FLT32_MANT_DIG__=24
  define: __FLT32_DIG__=6
  define: __FLT32_MIN_EXP__=(-125)
  define: __FLT32_MIN_10_EXP__=(-37)
  define: __FLT32_MAX_EXP__=128
  define: __FLT32_MAX_10_EXP__=38
  define: __FLT32_DECIMAL_DIG__=9
  define: __FLT32_MAX__=3.4028234663852886e+38F32
  define: __FLT32_NORM_MAX__=3.4028234663852886e+38F32
  define: __FLT32_MIN__=1.1754943508222875e-38F32
  define: __FLT32_EPSILON__=1.1920928955078125e-7F32
  define: __FLT32_DENORM_MIN__=1.4012984643248171e-45F32
  define: __FLT32_HAS_DENORM__=1
  define: __FLT32_HAS_INFINITY__=1
  define: __FLT32_HAS_QUIET_NAN__=1
  define: __FLT64_MANT_DIG__=53
  define: __FLT64_DIG__=15
  define: __FLT64_MIN_EXP__=(-1021)
  define: __FLT64_MIN_10_EXP__=(-307)
  define: __FLT64_MAX_EXP__=1024
  define: __FLT64_MAX_10_EXP__=308
  define: __FLT64_DECIMAL_DIG__=17
  define: __FLT64_MAX__=1.7976931348623157e+308F64
  define: __FLT64_NORM_MAX__=1.7976931348623157e+308F64
  define: __FLT64_MIN__=2.2250738585072014e-308F64
  define: __FLT64_EPSILON__=2.2204460492503131e-16F64
  define: __FLT64_DENORM_MIN__=4.9406564584124654e-324F64
  define: __FLT64_HAS_DENORM__=1
  define: __FLT64_HAS_INFINITY__=1
  define: __FLT64_HAS_QUIET_NAN__=1
  define: __FLT32X_MANT_DIG__=53
  define: __FLT32X_DIG__=15
  define: __FLT32X_MIN_EXP__=(-1021)
  define: __FLT32X_MIN_10_EXP__=(-307)
  define: __FLT32X_MAX_EXP__=1024
  define: __FLT32X_MAX_10_EXP__=308
  define: __FLT32X_DECIMAL_DIG__=17
  define: __FLT32X_MAX__=1.7976931348623157e+308F32x
  define: __FLT32X_NORM_MAX__=1.7976931348623157e+308F32x
  define: __FLT32X_MIN__=2.2250738585072014e-308F32x
  define: __FLT32X_EPSILON__=2.2204460492503131e-16F32x
  define: __FLT32X_DENORM_MIN__=4.9406564584124654e-324F32x
  define: __FLT32X_HAS_DENORM__=1
  define: __FLT32X_HAS_INFINITY__=1
  define: __FLT32X_HAS_QUIET_NAN__=1
  define: __SFRACT_FBIT__=7
  define: __SFRACT_IBIT__=0
  define: __SFRACT_MIN__=(-0.5HR-0.5HR)
  define: __SFRACT_MAX__=0X7FP-7HR
  define: __SFRACT_EPSILON__=0x1P-7HR
  define: __USFRACT_FBIT__=8
  define: __USFRACT_IBIT__=0
  define: __USFRACT_MIN__=0.0UHR
  define: __USFRACT_MAX__=0XFFP-8UHR
  define: __USFRACT_EPSILON__=0x1P-8UHR
  define: __FRACT_FBIT__=15
  define: __FRACT_IBIT__=0
  define: __FRACT_MIN__=(-0.5R-0.5R)
  define: __FRACT_MAX__=0X7FFFP-15R
  define: __FRACT_EPSILON__=0x1P-15R
  define: __UFRACT_FBIT__=16
  define: __UFRACT_IBIT__=0
  define: __UFRACT_MIN__=0.0UR
  define: __UFRACT_MAX__=0XFFFFP-16UR
  define: __UFRACT_EPSILON__=0x1P-16UR
  define: __LFRACT_FBIT__=31
  define: __LFRACT_IBIT__=0
  define: __LFRACT_MIN__=(-0.5LR-0.5LR)
  define: __LFRACT_MAX__=0X7FFFFFFFP-31LR
  define: __LFRACT_EPSILON__=0x1P-31LR
  define: __ULFRACT_FBIT__=32
  define: __ULFRACT_IBIT__=0
  define: __ULFRACT_MIN__=0.0ULR
  define: __ULFRACT_MAX__=0XFFFFFFFFP-32ULR
  define: __ULFRACT_EPSILON__=0x1P-32ULR
  define: __LLFRACT_FBIT__=63
  define: __LLFRACT_IBIT__=0
  define: __LLFRACT_MIN__=(-0.5LLR-0.5LLR)
  define: __LLFRACT_MAX__=0X7FFFFFFFFFFFFFFFP-63LLR
  define: __LLFRACT_EPSILON__=0x1P-63LLR
  define: __ULLFRACT_FBIT__=64
  define: __ULLFRACT_IBIT__=0
  define: __ULLFRACT_MIN__=0.0ULLR
  define: __ULLFRACT_MAX__=0XFFFFFFFFFFFFFFFFP-64ULLR
  define: __ULLFRACT_EPSILON__=0x1P-64ULLR
  define: __SACCUM_FBIT__=7
  define: __SACCUM_IBIT__=8
  define: __SACCUM_MIN__=(-0X1P7HK-0X1P7HK)
  define: __SACCUM_MAX__=0X7FFFP-7HK
  define: __SACCUM_EPSILON__=0x1P-7HK
  define: __USACCUM_FBIT__=8
  define: __USACCUM_IBIT__=8
  define: __USACCUM_MIN__=0.0UHK
  define: __USACCUM_MAX__=0XFFFFP-8UHK
  define: __USACCUM_EPSILON__=0x1P-8UHK
  define: __ACCUM_FBIT__=15
  define: __ACCUM_IBIT__=16
  define: __ACCUM_MIN__=(-0X1P15K-0X1P15K)
  define: __ACCUM_MAX__=0X7FFFFFFFP-15K
  define: __ACCUM_EPSILON__=0x1P-15K
  define: __UACCUM_FBIT__=16
  define: __UACCUM_IBIT__=16
  define: __UACCUM_MIN__=0.0UK
  define: __UACCUM_MAX__=0XFFFFFFFFP-16UK
  define: __UACCUM_EPSILON__=0x1P-16UK
  define: __LACCUM_FBIT__=31
  define: __LACCUM_IBIT__=32
  define: __LACCUM_MIN__=(-0X1P31LK-0X1P31LK)
  define: __LACCUM_MAX__=0X7FFFFFFFFFFFFFFFP-31LK
  define: __LACCUM_EPSILON__=0x1P-31LK
  define: __ULACCUM_FBIT__=32
  define: __ULACCUM_IBIT__=32
  define: __ULACCUM_MIN__=0.0ULK
  define: __ULACCUM_MAX__=0XFFFFFFFFFFFFFFFFP-32ULK
  define: __ULACCUM_EPSILON__=0x1P-32ULK
  define: __LLACCUM_FBIT__=31
  define: __LLACCUM_IBIT__=32
  define: __LLACCUM_MIN__=(-0X1P31LLK-0X1P31LLK)
  define: __LLACCUM_MAX__=0X7FFFFFFFFFFFFFFFP-31LLK
  define: __LLACCUM_EPSILON__=0x1P-31LLK
  define: __ULLACCUM_FBIT__=32
  define: __ULLACCUM_IBIT__=32
  define: __ULLACCUM_MIN__=0.0ULLK
  define: __ULLACCUM_MAX__=0XFFFFFFFFFFFFFFFFP-32ULLK
  define: __ULLACCUM_EPSILON__=0x1P-32ULLK
  define: __QQ_FBIT__=7
  define: __QQ_IBIT__=0
  define: __HQ_FBIT__=15
  define: __HQ_IBIT__=0
  define: __SQ_FBIT__=31
  define: __SQ_IBIT__=0
  define: __DQ_FBIT__=63
  define: __DQ_IBIT__=0
  define: __TQ_FBIT__=127
  define: __TQ_IBIT__=0
  define: __UQQ_FBIT__=8
  define: __UQQ_IBIT__=0
  define: __UHQ_FBIT__=16
  define: __UHQ_IBIT__=0
  define: __USQ_FBIT__=32
  define: __USQ_IBIT__=0
  define: __UDQ_FBIT__=64
  define: __UDQ_IBIT__=0
  define: __UTQ_FBIT__=128
  define: __UTQ_IBIT__=0
  define: __HA_FBIT__=7
  define: __HA_IBIT__=8
  define: __SA_FBIT__=15
  define: __SA_IBIT__=16
  define: __DA_FBIT__=31
  define: __DA_IBIT__=32
  define: __TA_FBIT__=63
  define: __TA_IBIT__=64
  define: __UHA_FBIT__=8
  define: __UHA_IBIT__=8
  define: __USA_FBIT__=16
  define: __USA_IBIT__=16
  define: __UDA_FBIT__=32
  define: __UDA_IBIT__=32
  define: __UTA_FBIT__=64
  define: __UTA_IBIT__=64
  define: __REGISTER_PREFIX__=
  define: __USER_LABEL_PREFIX__=
  define: __GNUC_GNU_INLINE__=1
  define: __NO_INLINE__=1
  define: __CHAR_UNSIGNED__=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1
  define: __GCC_ATOMIC_BOOL_LOCK_FREE=1
  define: __GCC_ATOMIC_CHAR_LOCK_FREE=1
  define: __GCC_ATOMIC_CHAR16_T_LOCK_FREE=1
  define: __GCC_ATOMIC_CHAR32_T_LOCK_FREE=2
  define: __GCC_ATOMIC_WCHAR_T_LOCK_FREE=2
  define: __GCC_ATOMIC_SHORT_LOCK_FREE=1
  define: __GCC_ATOMIC_INT_LOCK_FREE=2
  define: __GCC_ATOMIC_LONG_LOCK_FREE=2
  define: __GCC_ATOMIC_LLONG_LOCK_FREE=1
  define: __GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1
  define: __GCC_ATOMIC_POINTER_LOCK_FREE=2
  define: __HAVE_SPECULATION_SAFE_VALUE=1
  define: __PRAGMA_REDEFINE_EXTNAME=1
  define: __SIZEOF_WCHAR_T__=4
  define: __SIZEOF_WINT_T__=4
  define: __SIZEOF_PTRDIFF_T__=4
  define: __ARM_FEATURE_DSP=1
  define: __ARM_FEATURE_QBIT=1
  define: __ARM_FEATURE_SAT=1
  define: __ARM_FEATURE_UNALIGNED=1
  define: __ARM_32BIT_STATE=1
  define: __ARM_FEATURE_LDREX=4
  define: __ARM_FEATURE_CLZ=1
  define: __ARM_FEATURE_SIMD32=1
  define: __ARM_SIZEOF_MINIMAL_ENUM=4
  define: __ARM_SIZEOF_WCHAR_T=4
  define: __arm__=1
  define: __ARM_ARCH=6
  define: __ARM_ARCH_ISA_ARM=1
  define: __APCS_32__=1
  define: __GCC_ASM_FLAG_OUTPUTS__=1
  define: __ARM_ARCH_ISA_THUMB=1
  define: __ARMEL__=1
  define: __VFP_FP__=1
  define: __ARM_FP=12
  define: __THUMB_INTERWORK__=1
  define: __ARM_ARCH_6__=1
  define: __ARM_PCS_VFP=1
  define: __ARM_EABI__=1
  define: __ARM_FEATURE_COPROC=15
  define: __GXX_TYPEINFO_EQUALITY_INLINE=0
  define: __gnu_linux__=1
  define: __linux=1
  define: __linux__=1
  define: linux=1
  define: __unix=1
  define: __unix__=1
  define: unix=1
  define: __ELF__=1
  define: _STDC_PREDEF_H=1
  define: __STDC_IEC_559__=1
  define: __STDC_IEC_559_COMPLEX__=1
  define: __STDC_ISO_10646__=201706L
  define: __GNUC__
  define: __KERNEL__
  define: KBUILD_MODNAME="dummy_modname"
  other: --gcc
  other: --gnu_version=100201
Checking for syntax errors: file:///home/pi/vscode/kernel_module/my_module.c
Queueing IntelliSense update for files in translation unit of: /home/pi/vscode/kernel_module/my_module.c
Error squiggle count: 1
Update IntelliSense time (sec): 8.047
```

**Comment by sean-mcmanus** [comment] 2022-01-05 01:30
This appears to be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/5588 . It's recommended that you install the Microsoft Makefile Tools extension and set it as the configurationProvider to fix this issue.

Another fix appears to be to add the define "MODULE", but there could be other similar misconfiguration issues you could encounter as well, which theoretically would be fixed by using the Makefile Tools configuration provider.

**Closed as completed** 2022-01-05 01:30 UTC
Labels: duplicate
