### ISSUE TITLE
Chunk of Thread header Inactive and can't be accessed

### ISSUE THREAD

**Issue by SuryanshVimlendra** [microsoft/vscode-cpptools#6120] opened 2020-09-12 05:34 UTC
**Type: LanguageService**

So I am trying to use thread header file. But the my vscode has problem accessing chunk of code inside the header file. And when I "GO TO DEFINITION" a large chunk of that header file is inactive.  

**Describe the bug**
- OS and Version: WINDOWS 10 Home
- VS Code Version: version 1.49
- C/C++ Extension Version: 0.30.0-insider5
- Other extensions you installed (and if the issue persists after disabling them):C/C++ intellisense 0.2.2
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Code inside Thread Header file is inactive and cant be accessed. 
This is my main CPP code
![image](https://user-images.githubusercontent.com/71164575/92988084-17f7e980-f4e6-11ea-9079-f1ca4854aea7.png)

and when I Go to definition it opens up the thread header file but in the inactive dim region
![image](https://user-images.githubusercontent.com/71164575/92988228-1e3a9580-f4e7-11ea-9e21-268bfd3ddb72.png)

as per some previous query i even tried changing the Intellisense mode to clang-x64 from ${default}
and the file containing the thread file is also been set in the includePath
![image](https://user-images.githubusercontent.com/71164575/92988277-a3be4580-f4e7-11ea-94d7-6ebf564292d1.png)

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment] 2020-09-14 18:15
You should remove the mingw path from your includePath, because it can interfere with the paths queried from your mingw compilerPath. After doing that, does it fix your issue? If not, can you run C/C++: Log Diagnostics after opening the source file and thread header?

**Comment by michelleangela** [comment] 2020-12-09 18:38
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 18:38 UTC
Labels: Language Service, more info needed
