### ISSUE TITLE
Intellisense on split panes returns information about the currently active project, not the currently moused-over pane.

### ISSUE THREAD

**Issue by JarrettR** [microsoft/vscode-cpptools#3452] opened 2019-04-11 17:55 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.33.0
- C/C++ Extension Version: 0.22.1
- A clear and concise description of what the bug is:

Intellisense on split panes returns information about the currently active project, not the currently moused-over pane.

**To Reproduce**

1.  Set up a c++ project, copy the entire folder and name the two `project_left` and `project_right`
2. Open a new, empty workspace in VSCode
3. Add both folders to the workspace
4. Open up `main.cpp` for both projects in the left and right panes respectively, using the `Open to the side` or `split right` or whatever your preferred method is.
5. In another file (eg. main.h), `#define VAR 1` in the left project, and `#define VAR 2` on the right.
6. Use it in main() / compile, etc. Anything to get Intellisense to start reading the define. Might need to close and open VSCode.
7.  While the left pane is active, mousing over the `VAR` define will display "1" on both sides.
8. When the right pane is active (ie. click somewhere in the right pane's code window), `VAR` will display "2" on both sides

**Expected behavior**

The mouseover info for `VAR` should always display "1" on the left, and "2" on the right

**Screenshots**

#defines in the .h file of left and right projects:

![image](https://user-images.githubusercontent.com/6027644/55979310-b6738180-5c46-11e9-916e-dcdc06966ddc.png)

Test function of left and right projects:
![image](https://user-images.githubusercontent.com/6027644/55979370-dacf5e00-5c46-11e9-9ba2-b4a0fa6c9778.png)

Left pane is active, mouseover of left #define (This is proper and expected:
![image](https://user-images.githubusercontent.com/6027644/55979437-018d9480-5c47-11e9-88bd-ca4fcee1b0d4.png)

Left pane active, mouseover on right (This is wrong):

![image](https://user-images.githubusercontent.com/6027644/55979465-136f3780-5c47-11e9-8c63-a02d9017f7f7.png)

For completion, right pane is active, and mouseover on right is correct:

![image](https://user-images.githubusercontent.com/6027644/55979689-a314e600-5c47-11e9-8cea-225909d6ca8b.png)

And left is incorrect:

![image](https://user-images.githubusercontent.com/6027644/55979626-7e207300-5c47-11e9-8be3-5dad687f1b9c.png)

**Additional context**

**Comment by sean-mcmanus** [comment] 2019-04-12 01:20
We have a fix at https://github.com/Microsoft/vscode-cpptools/pull/3455, but it requires that the workspace client of the hovered file be activated first, i.e. any file in the target workspace needs to be opened or given focus in the current session (the fact that all the clients don't activate on startup or on hover is a different issue, somewhat "by design").

FYI, your repro requires a `#include <>` and doesn't repro with a `#include ""`, because it was using the includePath for the active file (and the `""` version pulls in the current file's include path).

**Comment by sean-mcmanus** [comment] 2019-04-24 02:21
Fixed with 0.23.0-insiders.

**Closed as completed** 2019-05-08 01:29 UTC
Labels: bug, Language Service, fixed, quick fix, Feature: Multi-root
