### ISSUE TITLE
Replacing "(Windows) Launch" makes two run config copies

### ISSUE THREAD

**Issue by HydroPage** [microsoft/vscode-cpptools#11098] opened 2023-06-16 00:11 UTC
### Environment

- OS and version: Windows Version 10.0.22621 Build 22621
- VS Code: 1.79.2  695af097c7bd098fbf017ce3ac85e09bbc5dda06  x64
- C/C++ extension: v1.15.4

### Bug Summary and Steps to Reproduce

Bug Summary:
Whenever I make a run configuration for a C project by adding my own launch config to "launch.json"

Steps to reproduce:
1. Create a workspace for C in VS Code
2. click the "debug" icon next to the "run" icon on the top right to configure a run configuration for a file. It pops up with two options, "(gdp) Launch" and "(Windows) Launch". I click "(Windows) Launch" and it makes a launch.json file with the "(Windows) Launch" configuration in it. At this point, clicking the "run" icon shows two copies of "(Windows) Launch".
3. In launch.json, add a copy of "(Windows) Launch" with the details you want instead, and with a different name
4. when you click the "run" play button icon, both "(Windows) Launch" and the name of the new config you put will appear duplicated. Both of the copies of your new config should work but there are two of them.

### Debugger Configurations

This is launch.json
```json
{
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "enter program name, for example ${workspaceFolder}/a.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": "externalTerminal"
        },
        {
            "name": "Launch Program",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/CreditTest.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": "integratedTerminal"
        }
    ],
    "version": "2.0.0"
}
```

### Debugger Logs

I didn't actually run the program. The strange part is how the configs appear duplicated

### Other Extensions

I have many other extensions installed, but it's not worth listing them because this happened with all extensions except the ones in the C/C++ Extension Pack enabled

### Additional Information

<img width="399" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/31541490/134183b4-eed1-47a0-945a-24866da3e8cc">

**Comment by michelleangela** [comment] 2023-06-16 04:27
@HydroPage 
Thank you for reporting this issue. This turns out to be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/10878.

**Closed as completed by michelleangela** 2023-06-16 04:27 UTC
Labels: bug, duplicate, Language Service, tasks/build/debug
