### ISSUE TITLE
Terminal stays blank while debugging on macOS 12

### ISSUE THREAD

**Issue by n-hass** [microsoft/vscode-cpptools#8083] opened 2021-09-01 10:11 UTC
Bug type: Debugger

**Describe the bug**
- OS and Version: macOS 12 Monterey, build 21A5304g
- VS Code Version: 1.59.1
- C/C++ Extension Version: 1.6.0
- Other extensions you installed (and if the issue persists after disabling them): N/A, all disabled

With externalConsole enabled, window focus does not change to Terminal after starting a debug session. Terminal window remains blank for duration of debug session, no output is displayed and no input can be received.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Compile a C++ program that uses std::cin and cout.
2. Use a launch task with externalConsole=enabled to start a debug session
3. Verify that no output is displayed in the Terminal window and no input is received

Sample launch.json config:
`{
            "name": "Run C++ binary",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${input:binaryName}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb",
            "preLaunchTask": "",
            "postDebugTask": ""
        }`

Sample code:
`#include <iostream>
#include <string>
using namespace std;
int main() {
    string test;
    cin >> test;
    cout << test << endl;
}`

**Additional context**
No errors with logging flags enabled.
Debug console:
`Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=thread-selected,id="1"
=library-unloaded,id="/Volumes/GD/Uni/svnRepo/2021/s2/adds/assignment5/prog",target-name="/Volumes/GD/Uni/svnRepo/2021/s2/adds/assignment5/prog",host-name="/Volumes/GD/Uni/svnRepo/2021/s2/adds/assignment5/prog"
Loaded '/usr/lib/dyld'. Symbols loaded.
Loaded '/Volumes/GD/Uni/svnRepo/2021/s2/adds/assignment5/prog'. Symbols loaded.
Loaded '/usr/lib/libc++.1.dylib'. Symbols loaded.
Loaded '/usr/lib/libSystem.B.dylib'. Symbols loaded.
Loaded '/usr/lib/libc++abi.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcache.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcommonCrypto.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcompiler_rt.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcopyfile.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcorecrypto.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libdispatch.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libdyld.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libkeymgr.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libmacho.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libquarantine.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libremovefile.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_asl.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_blocks.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_c.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_collections.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_configuration.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_containermanager.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_coreservices.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_darwin.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_dnssd.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_featureflags.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_info.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_m.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_malloc.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_networkextension.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_notify.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_product_info_filter.dylib'. Cannot find or open the symbol file.
Loaded '/usr/lib/system/libsystem_sandbox.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_secinit.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_kernel.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_platform.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_pthread.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_symptoms.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_trace.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libunwind.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libxpc.dylib'. Symbols loaded.
Loaded '/usr/lib/libobjc.A.dylib'. Symbols loaded.
Loaded '/usr/lib/liboah.dylib'. Symbols loaded.`

**Comment by WardenGnaw** [comment] 2021-09-02 21:30
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/8075

**Closed as completed by WardenGnaw** 2021-09-02 21:30 UTC
Labels: duplicate, debugger

**Comment by Dayana1704** [comment] 2023-03-14 10:42
Hey, did you find solution because I am having the same problem
