### ISSUE TITLE
Pick the clang-format in PATH over the one bundled with the extension

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4618] opened 2019-11-15 22:18 UTC
The right thing to do is to pick the clang-format in PATH over the VSCode one.

_Originally posted by @ncihnegn in https://github.com/microsoft/vscode-cpptools/issues/2887#issuecomment-487843841_

**Comment by bobbrow** [comment] 2020-01-08 18:54
Duplicate of #3569

**Closed as completed by bobbrow** 2020-01-08 18:54 UTC
Labels: duplicate, Language Service, Feature Request, fixed, Feature: Code Formatting
