### ISSUE TITLE
Inaccurate messages raised by IntelliSense with Boost Geometry and SFML present

### ISSUE THREAD

**Issue by LitMSCTBB** [microsoft/vscode-cpptools#9657] opened 2022-07-28 05:36 UTC
### Environment

- OS and Version: Windows 10 
- VS Code Version: 1.69.2
- C/C++ Extension Version: 1.11.4
- Other extensions you installed (and if the issue persists after disabling them):  clangd (disabled), C/C++ Extension Pack, C/C++ Themes, Better C++ Syntax, Prettier, Intellicode
- If using SSH remote, specify OS of remote machine:  
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc). Single-project workspace, just one directory with 5 C++ files. IntelliSense keeps red-underlining certain boost namespaces, classes, etc. as well as marking some as error-types, even though all of the code functions properly. The `includePath` in c_cpp_properties.json is correct and exactly matches the paths used for includes for the cpp compilation

### Bug Summary and Steps to Reproduce

Bug Summary: IntelliSense seems to get very confused on various types in the boost library (specifically boost geometry) and also sometimes reports inaccurate type descriptions when custom structs or other libraries, such as SFML, coexist with boost.
- For example, `model` is not recognized as a subspace of `boost::geometry` (call it `bg`), and this leads to `bg::model::point<double, 2, bg::cs::cartesian>` to be considered as an `<error-type>` causing any instances of `point` to be considered undefined. This further invalidates `box` in a similar manner.
- `distance` is also not recognized as a function in the `bg` namespace.
- Classes/functions `rtree`, `quadratic`, `intersects`, `satisfies`, etc. are not recognized in the `bg::index` namespace and thus make my rtree instances undefined. 
- I have a custom struct called `Node`, but IntelliSense thinks that it falls under the `boost` namespace i.e. each instance of `Node` is actually an instance of `boost::Node`, which is not a real thing
- I am using the library SFML for graphics, and a similar issue to `Node` exists (`boost::sf`, or sometimes it's even `std::sf`???)
Also some errors necessarily related to `boost` but are still bugs nonetheless:
- I define `using NodeRef = std::reference_wrapper<Node>;`, but everywhere in the code IntelliSense thinks it's undefined.

Steps to reproduce:
1. Create new cpp file
2. Copy paste given code below as well as c_cpp_properties.json
3. See error

### Expected behavior

I don't expect any of these errors/bugs/inaccuracies to be showing up, as the code compiles successfully and performs as I expect it to.

### Code sample and Logs
boosttest.cpp
```cpp
Relevant snippets from cpp file:
#include <algorithm>
#include <iostream>
#include <cmath>
#include <stdlib.h>
#include <stdio.h>
#include <string>
#include <vector>
#include <deque>
#include <set>
#include <random>
#include <chrono>
#include <boost/geometry.hpp>
#include <boost/geometry/geometry.hpp>
#include <boost/geometry/geometries/point.hpp>
#include <boost/geometry/geometries/box.hpp>
#include <boost/geometry/geometries/register/point.hpp>
#include <boost/geometry/index/rtree.hpp>
#include <SFML/Graphics.hpp>
#include <SFML/Window.hpp>

#define cout std::cout
#define endl std::endl

namespace bg = boost::geometry;
namespace bgi = boost::geometry::index;

typedef bg::model::point<double, 2, bg::cs::cartesian> point;
typedef bg::model::box<point> box;

struct Node
{
  Node *parent = nullptr;
  point pos = {};
  int id = -1;
};

struct Result
{
  int numNodes;
  int iter;
  int pathNodes;
  double pathDistance;
  double time;
};

typedef std::pair<box, unsigned int> boxval;

BOOST_GEOMETRY_REGISTER_POINT_2D_GET_SET(Node, double, bg::cs::cartesian, pos.get<0>, pos.get<1>, pos.set<0>, pos.set<1>);

using NodeRef = std::reference_wrapper<Node>;
struct NodeIndexable
{
  using value_type = NodeRef;
  using result_type = Node &;

  result_type operator()(NodeRef r) const { return r; }
};

int main() {
  sf::RenderTexture renderTexture;
  renderTexture.create(200, 200);
  renderTexture.clear();

  point start(0, 0), end(200, 200);
  bgi::rtree<NodeRef, bgi::quadratic<16>, NodeIndexable> pts;
  bgi::rtree<boxval, bgi::quadratic<16>> boxes;
  
  // some of the stuff here is confidential, but the errors are described above, and every example of each type of issue that I've described above has an error (so viewer can try them out and see)

  return 0;
}
```

c_cpp_properties.json
```
{
  "configurations": [
    {
      "name": "Win32",
      "includePath": [
        "D:\\Program Files\\boost\\include\\boost-1_79",
        "D:\\Program Files\\SFML-2.5.1\\include",
        "C:\\Python310\\include",
        "C:\\Python310\\Lib\\site-packages\\numpy\\core\\include",
        "${workspaceFolder}/**"
      ],
      "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
      ],
      "compilerPath": "D:\\Program Files\\mingw64\\bin\\g++.exe",
      "cStandard": "gnu17",
      "cppStandard": "gnu++14",
      "intelliSenseMode": "windows-gcc-x64"
    }
  ],
  "version": 4
}
```

Log Diagnostics
```
-------- Diagnostics - 7/28/2022, 12:14:16 AM
Version: 1.11.4
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "D:\\Program Files\\boost\\include\\boost-1_79",
        "D:\\Program Files\\SFML-2.5.1\\include",
        "C:\\Python310\\include",
        "C:\\Python310\\Lib\\site-packages\\numpy\\core\\include",
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "D:\\Program Files\\mingw64\\bin\\g++.exe",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "windows-gcc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "D:\\Program Files\\boost\\include\\boost-1_79",
            "D:\\Program Files\\SFML-2.5.1\\include",
            "C:\\Python310\\include",
            "C:\\Python310\\Lib\\site-packages\\numpy\\core\\include",
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\Documents\Coding\bproj\boosttest.cpp ]:
    D:\Documents\Coding\bproj\boosttest.cpp
Translation Unit Configurations:
[ D:\Documents\Coding\bproj\boosttest.cpp ]:
    Process ID: 8172
    Memory Usage: 630 MB
    Compiler Path: D:\Program Files\mingw64\bin\g++.exe
    Includes:
        D:\PROGRAM FILES\BOOST\INCLUDE\BOOST-1_79
        D:\PROGRAM FILES\SFML-2.5.1\INCLUDE
        C:\PYTHON310\INCLUDE
        C:\PYTHON310\LIB\SITE-PACKAGES\NUMPY\CORE\INCLUDE
        D:\DOCUMENTS\CODING\RICE
        D:\PROGRAM FILES\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++
        D:\PROGRAM FILES\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\X86_64-W64-MINGW32
        D:\PROGRAM FILES\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\BACKWARD
        D:\PROGRAM FILES\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE
        D:\PROGRAM FILES\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE-FIXED
        D:\PROGRAM FILES\MINGW64\X86_64-W64-MINGW32\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++14
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=80100
Total Memory Usage: 1867 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 17784
Number of files parsed: 2826
```

### Screenshots

`model` not recognized
![image](https://user-images.githubusercontent.com/41565910/181426698-8c5c9546-ab96-468e-a736-b2459794430a.png)

`point` not defined
![image](https://user-images.githubusercontent.com/41565910/181426795-e20ac0c0-391d-49b9-a1b1-8ecec08a4906.png)
![image](https://user-images.githubusercontent.com/41565910/181426976-42fbac02-0490-42a7-af23-b3d35b9fca30.png)
![image](https://user-images.githubusercontent.com/41565910/181427596-4f1c48d9-ac2f-45ca-9ae9-811a9caff65d.png)

`box` not defined
![image](https://user-images.githubusercontent.com/41565910/181426907-ab618ef4-9b69-4e52-94dd-fb68de960095.png)

`NodeRef` not defined
![image](https://user-images.githubusercontent.com/41565910/181427018-12efceb1-a7c8-4c3c-a9c6-87acec670f17.png)

Same block of code with SFML RenderTexture
![image](https://user-images.githubusercontent.com/41565910/181427212-80e40009-05b6-416c-a3b2-1d7e3ab3ff20.png)
![image](https://user-images.githubusercontent.com/41565910/181427185-090f8baf-0c68-4f4c-80de-7cb3c5b2fd51.png)
![image](https://user-images.githubusercontent.com/41565910/181427246-df37e04f-f585-48c0-8e9c-3bc18cceecdf.png)

`rtree`, `quadratic` not members of `boost::geometry::index`
![image](https://user-images.githubusercontent.com/41565910/181427649-bab0b736-c79c-4cbc-9b3d-02dcbab6ea54.png)

**Comment by sean-mcmanus** [comment] 2022-08-05 03:28
We repro the issue. It repros with mingw/gcc but not with msvc/cl.exe. I'm looking into the root cause of the parser error...

**Comment by sean-mcmanus** [comment] 2022-08-05 23:33
This error is a cascading parse failure caused by our lack of support for __float128 on Windows: https://github.com/microsoft/vscode-cpptools/issues/9558 . The error doesn't occur if you avoid headers that have a dependency on the __float128 type, which may be difficult to do, i.e. if you can somehow force BOOST_MATH_USE_FLOAT128 to always be undefined.

**Comment by Colengms** [comment] 2022-08-16 22:16
Closing as duplicate.

**Closed as not planned by Colengms** 2022-08-16 22:16 UTC
Labels: bug, duplicate, Language Service, verified, Verified - Internal
