### ISSUE TITLE
IntelliSense squiggles gcc attribute constructor with priority

### ISSUE THREAD

**Issue by ltWolfik** [microsoft/vscode-cpptools#4847] opened 2020-01-14 11:16 UTC
Example:
```c
void func(void) __attribute__((constructor(1001))); // <-- squiggles here
```
Error message: `attribute "constructor" does not take arguments`

Extension Version: 0.26.2

**Comment by sean-mcmanus** [comment] 2020-01-14 20:35
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/4503 . You can upvote the VS bug if you have a Microsoft account: https://developercommunity.visualstudio.com/content/problem/796872/cc-intellisense-in-gccclang-mode-shows-attribute-c.html

**Closed as completed by sean-mcmanus** 2020-01-14 20:35 UTC
Labels: duplicate
