### ISSUE TITLE
[lldb] Unicode and special characters are not displayed correctly

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-cpptools#2854] opened 2018-11-22 12:15 UTC
Type: Debugger

**Describe the bug**
- OS and Version: macOS 10.14 (18A391)
- VS Code Version: 1.29.1 (1.29.1)
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): all other extensions disabled
- A clear and concise description of what the bug is:

I am not sure if it is (at least partially) intended behavior, but special characters are printed out literally when the internal console is chosen for debugging. Also, Unicode characters are printed out as their hex values. If it is intended behavior (to allow inspecting all characters written out, including non-visible ones) then it would be nice to have an option to turn it off.

My configuration:
```json
        {
            "name": "(lldb) Launch lz77",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/lz77.out",
            "args": ["-d"],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}/lz77/src/",
            "environment": [],
            "externalConsole": false,
            "preLaunchTask": "build LZ77",
            "MIMode": "lldb"
        }
```

My code:

```C
#include <stdio.h>
int main(int argc, char *argv[]){
    printf("\t →Hello \n\n");
}
```

Output: 

```
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=thread-selected,id="1"
Loaded '/usr/lib/dyld'. Symbols loaded.
Loaded '/usr/lib/libSystem.B.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcache.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcommonCrypto.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcompiler_rt.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcopyfile.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcorecrypto.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libdispatch.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libdyld.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libkeymgr.dylib'. Symbols loaded.
Loaded '/usr/lib/system/liblaunch.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libmacho.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libquarantine.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libremovefile.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_asl.dylib'. Symbols loaded. 
Loaded '/usr/lib/system/libsystem_c.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_configuration.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_coreservices.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_darwin.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_dnssd.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_info.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_m.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_malloc.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_networkextension.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_notify.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_sandbox.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_secinit.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_kernel.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_platform.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_pthread.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_symptoms.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_trace.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libunwind.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libxpc.dylib'. Symbols loaded.
Loaded '/usr/lib/libobjc.A.dylib'. Symbols loaded.
Loaded '/usr/lib/libc++abi.dylib'. Symbols loaded.
Loaded '/usr/lib/libc++.1.dylib'. Symbols loaded.
Loaded '/...<removed>.../prog.out'. Symbols loaded.
@"\t \xe2\x86\x92Hello \r\n"
@"\r\n"
The program '/...<removed>.../prog.out'  has exited with code 0 (0x00000000).
```

Please let me know if you need any extra information.

**Comment by pieandcakes** [comment] 2018-11-26 20:34
@ldorigo This seems like an issue with `lldb-mi` and not with the extension but we will need to investigate to make sure that is the case.

**Comment by ldorigo** [comment] 2018-11-26 22:42
It may be relevant to note that when using an external console (macOS terminal), the output is displayed correctly.

**Comment by gsittyz** [comment] 2019-09-22 13:19
@pieandcakes 
Is there any updates on this? I reproduced this issue on:
- mac OS Mojave 10.14.6 (18G95)
- VS Code Version: 1.38.1
- Other extensions you installed (and if the issue persists after disabling them): all other extensions disabled

**Comment by pieandcakes** [comment] 2019-09-23 17:34
@gsittyz I suspect this is similar to `gdb` where the issue is in the debugger. I haven't had time to investigate but I suspect it is something that is going to need to be fixed in `lldb`.

**Closed as completed** 2020-12-09 00:50 UTC
Labels: debugger, investigate: repro
