### ISSUE TITLE
"identifier is undefined" with version 0.29.0

### ISSUE THREAD

**Issue by olijaun** [microsoft/vscode-cpptools#5791] opened 2020-07-16 18:13 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux  4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- VS Code Version: 1.47.1
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): GitLens 10.2.2, No
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Suddenly I got "identifier is undefined" in my C++ project after the latest version (0.29.0) was installed. When I go back to 0.28.3 everything works fine. I found this bug here https://github.com/microsoft/vscode-cpptools/issues/3849 and tried to delete the "ipch"-directory (which is actually in .cache/vscode-cpptools/ on linux). It didn't help.

**Steps to reproduce**
0. Install Linux :-)
1. git clone --recursive https://github.com/clearly-broken-software/ninjas2.git   (it's not my project but you can reproduce it with this open source plugin)
2. File -> Open Folder -> select the directory you checked out: "ninjas2"
3. Open Ninjas2UI.cpp 
4. Wait for a while
5. Now check for example Line 35 (getPluginInstancePointer), you should see "identifier "getPluginInstancePointer" is undefined"
5.1 If it does not show up, close vscode and open again
6. Now downgrade to 0.28.3 of ms-vscode.cpptools
7. go back to Ninjas2UI.cpp --> the error has gone

**Expected behavior**
See above. The expectation is to NOT see the "identifier is undefined" error

1. Logs from the command `C/C++: Log Diagnostics`

-------- Diagnostics - 7/16/2020, 8:08:03 PM
Version: 0.29.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu11",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp ]:
    /home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp
Translation Unit Configurations:
[ /home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp ]:
    Process ID: 17377
    Memory Usage: 152 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
        /home/oliver/git/ninjas2/dpf/distrho
        /home/oliver/git/ninjas2/dpf/dgl
        /home/oliver/git/ninjas2/aubio/src
        /home/oliver/git/ninjas2/plugins/Ninjas2/Widgets
        /home/oliver/git/ninjas2/dpf/examples/CairoUI
        /home/oliver/git/ninjas2/plugins/Ninjas2/Structures
    Standard Version: c++14
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=70500
Total Memory Usage: 152 MB

2. Logs from [the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
 -->
<details>
  <summary><strong>Logs</strong></summary>

```
cpptools/didChangeCppProperties
Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/gcc'
terminating child process: 17778
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/gcc'
terminating child process: 17781
  Folder: /usr/lib/gcc/x86_64-linux-gnu/7/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/ will be indexed
  Folder: /usr/include/ will be indexed
  Folder: /home/oliver/git/ninjas2/ will be indexed
textDocument/didOpen: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp
Populate include completion cache.
Discovering files...
cpptools/activeDocumentChange: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp
cpptools/textEditorSelectionChange
  Processing folder (recursive): /usr/lib/gcc/x86_64-linux-gnu/7/include/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/
  Processing folder (recursive): /usr/include/
cpptools/getDocumentSymbols: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp (id: 2)
cpptools/getDocumentSymbols
cpptools/getCodeActions: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp (id: 3)
idle loop: reparsing the active document
Checking for syntax errors: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp
sending compilation args for /home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp
  include: /usr/include/c++/7
  include: /usr/include/x86_64-linux-gnu/c++/7
  include: /usr/include/c++/7/backward
  include: /usr/lib/gcc/x86_64-linux-gnu/7/include
  include: /usr/local/include
  include: /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
  include: /usr/include/x86_64-linux-gnu
  include: /usr/include
  include: /home/oliver/git/ninjas2/dpf/distrho
  include: /home/oliver/git/ninjas2/dpf/dgl
  include: /home/oliver/git/ninjas2/aubio/src
  include: /home/oliver/git/ninjas2/plugins/Ninjas2/Widgets
  include: /home/oliver/git/ninjas2/dpf/examples/CairoUI
  include: /home/oliver/git/ninjas2/plugins/Ninjas2/Structures
  define: __STDC__=1
  define: __cplusplus=201402L
  define: __STDC_UTF_16__=1
  define: __STDC_UTF_32__=1
  define: __STDC_HOSTED__=1
  define: __GNUC__=7
  define: __GNUC_MINOR__=5
  define: __GNUC_PATCHLEVEL__=0
  define: __VERSION__="7.5.0"
  define: __ATOMIC_RELAXED=0
  define: __ATOMIC_SEQ_CST=5
  define: __ATOMIC_ACQUIRE=2
  define: __ATOMIC_RELEASE=3
  define: __ATOMIC_ACQ_REL=4
  define: __ATOMIC_CONSUME=1
  define: __pic__=2
  define: __PIC__=2
  define: __pie__=2
  define: __PIE__=2
  define: __FINITE_MATH_ONLY__=0
  define: _LP64=1
  define: __LP64__=1
  define: __SIZEOF_INT__=4
  define: __SIZEOF_LONG__=8
  define: __SIZEOF_LONG_LONG__=8
  define: __SIZEOF_SHORT__=2
  define: __SIZEOF_FLOAT__=4
  define: __SIZEOF_DOUBLE__=8
  define: __SIZEOF_LONG_DOUBLE__=16
  define: __SIZEOF_SIZE_T__=8
  define: __CHAR_BIT__=8
  define: __BIGGEST_ALIGNMENT__=16
  define: __ORDER_LITTLE_ENDIAN__=1234
  define: __ORDER_BIG_ENDIAN__=4321
  define: __ORDER_PDP_ENDIAN__=3412
  define: __BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __FLOAT_WORD_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __SIZEOF_POINTER__=8
  define: __GNUG__=7
  define: __SIZE_TYPE__=long unsigned int
  define: __PTRDIFF_TYPE__=long int
  define: __WCHAR_TYPE__=int
  define: __WINT_TYPE__=unsigned int
  define: __INTMAX_TYPE__=long int
  define: __UINTMAX_TYPE__=long unsigned int
  define: __CHAR16_TYPE__=short unsigned int
  define: __CHAR32_TYPE__=unsigned int
  define: __SIG_ATOMIC_TYPE__=int
  define: __INT8_TYPE__=signed char
  define: __INT16_TYPE__=short int
  define: __INT32_TYPE__=int
  define: __INT64_TYPE__=long int
  define: __UINT8_TYPE__=unsigned char
  define: __UINT16_TYPE__=short unsigned int
  define: __UINT32_TYPE__=unsigned int
  define: __UINT64_TYPE__=long unsigned int
  define: __INT_LEAST8_TYPE__=signed char
  define: __INT_LEAST16_TYPE__=short int
  define: __INT_LEAST32_TYPE__=int
  define: __INT_LEAST64_TYPE__=long int
  define: __UINT_LEAST8_TYPE__=unsigned char
  define: __UINT_LEAST16_TYPE__=short unsigned int
  define: __UINT_LEAST32_TYPE__=unsigned int
  define: __UINT_LEAST64_TYPE__=long unsigned int
  define: __INT_FAST8_TYPE__=signed char
  define: __INT_FAST16_TYPE__=long int
  define: __INT_FAST32_TYPE__=long int
  define: __INT_FAST64_TYPE__=long int
  define: __UINT_FAST8_TYPE__=unsigned char
  define: __UINT_FAST16_TYPE__=long unsigned int
  define: __UINT_FAST32_TYPE__=long unsigned int
  define: __UINT_FAST64_TYPE__=long unsigned int
  define: __INTPTR_TYPE__=long int
  define: __UINTPTR_TYPE__=long unsigned int
  define: __GXX_WEAK__=1
  define: __DEPRECATED=1
  define: __GXX_RTTI=1
  define: __GXX_EXPERIMENTAL_CXX0X__=1
  define: __EXCEPTIONS=1
  define: __GXX_ABI_VERSION=1011
  define: __SCHAR_MAX__=0x7f
  define: __SHRT_MAX__=0x7fff
  define: __INT_MAX__=0x7fffffff
  define: __LONG_MAX__=0x7fffffffffffffffL
  define: __LONG_LONG_MAX__=0x7fffffffffffffffLL
  define: __WCHAR_MAX__=0x7fffffff
  define: __WCHAR_MIN__=(-__WCHAR_MAX__ - 1)
  define: __WINT_MAX__=0xffffffffU
  define: __WINT_MIN__=0U
  define: __PTRDIFF_MAX__=0x7fffffffffffffffL
  define: __SIZE_MAX__=0xffffffffffffffffUL
  define: __SCHAR_WIDTH__=8
  define: __SHRT_WIDTH__=16
  define: __INT_WIDTH__=32
  define: __LONG_WIDTH__=64
  define: __LONG_LONG_WIDTH__=64
  define: __WCHAR_WIDTH__=32
  define: __WINT_WIDTH__=32
  define: __PTRDIFF_WIDTH__=64
  define: __SIZE_WIDTH__=64
  define: __GLIBCXX_TYPE_INT_N_0=__int128
  define: __GLIBCXX_BITSIZE_INT_N_0=128
  define: __INTMAX_MAX__=0x7fffffffffffffffL
  define: __INTMAX_C(c)=c ## L
  define: __UINTMAX_MAX__=0xffffffffffffffffUL
  define: __UINTMAX_C(c)=c ## UL
  define: __INTMAX_WIDTH__=64
  define: __SIG_ATOMIC_MAX__=0x7fffffff
  define: __SIG_ATOMIC_MIN__=(-__SIG_ATOMIC_MAX__ - 1)
  define: __SIG_ATOMIC_WIDTH__=32
  define: __INT8_MAX__=0x7f
  define: __INT16_MAX__=0x7fff
  define: __INT32_MAX__=0x7fffffff
  define: __INT64_MAX__=0x7fffffffffffffffL
  define: __UINT8_MAX__=0xff
  define: __UINT16_MAX__=0xffff
  define: __UINT32_MAX__=0xffffffffU
  define: __UINT64_MAX__=0xffffffffffffffffUL
  define: __INT_LEAST8_MAX__=0x7f
  define: __INT8_C(c)=c
  define: __INT_LEAST8_WIDTH__=8
  define: __INT_LEAST16_MAX__=0x7fff
  define: __INT16_C(c)=c
  define: __INT_LEAST16_WIDTH__=16
  define: __INT_LEAST32_MAX__=0x7fffffff
  define: __INT32_C(c)=c
  define: __INT_LEAST32_WIDTH__=32
  define: __INT_LEAST64_MAX__=0x7fffffffffffffffL
  define: __INT64_C(c)=c ## L
  define: __INT_LEAST64_WIDTH__=64
  define: __UINT_LEAST8_MAX__=0xff
  define: __UINT8_C(c)=c
  define: __UINT_LEAST16_MAX__=0xffff
  define: __UINT16_C(c)=c
  define: __UINT_LEAST32_MAX__=0xffffffffU
  define: __UINT32_C(c)=c ## U
  define: __UINT_LEAST64_MAX__=0xffffffffffffffffUL
  define: __UINT64_C(c)=c ## UL
  define: __INT_FAST8_MAX__=0x7f
  define: __INT_FAST8_WIDTH__=8
  define: __INT_FAST16_MAX__=0x7fffffffffffffffL
  define: __INT_FAST16_WIDTH__=64
  define: __INT_FAST32_MAX__=0x7fffffffffffffffL
  define: __INT_FAST32_WIDTH__=64
  define: __INT_FAST64_MAX__=0x7fffffffffffffffL
  define: __INT_FAST64_WIDTH__=64
  define: __UINT_FAST8_MAX__=0xff
  define: __UINT_FAST16_MAX__=0xffffffffffffffffUL
  define: __UINT_FAST32_MAX__=0xffffffffffffffffUL
  define: __UINT_FAST64_MAX__=0xffffffffffffffffUL
  define: __INTPTR_MAX__=0x7fffffffffffffffL
  define: __INTPTR_WIDTH__=64
  define: __UINTPTR_MAX__=0xffffffffffffffffUL
  define: __GCC_IEC_559=2
  define: __GCC_IEC_559_COMPLEX=2
  define: __FLT_EVAL_METHOD__=0
  define: __FLT_EVAL_METHOD_TS_18661_3__=0
  define: __DEC_EVAL_METHOD__=2
  define: __FLT_RADIX__=2
  define: __FLT_MANT_DIG__=24
  define: __FLT_DIG__=6
  define: __FLT_MIN_EXP__=(-125)
  define: __FLT_MIN_10_EXP__=(-37)
  define: __FLT_MAX_EXP__=128
  define: __FLT_MAX_10_EXP__=38
  define: __FLT_DECIMAL_DIG__=9
  define: __FLT_MAX__=3.40282346638528859811704183484516925e+38F
  define: __FLT_MIN__=1.17549435082228750796873653722224568e-38F
  define: __FLT_EPSILON__=1.19209289550781250000000000000000000e-7F
  define: __FLT_DENORM_MIN__=1.40129846432481707092372958328991613e-45F
  define: __FLT_HAS_DENORM__=1
  define: __FLT_HAS_INFINITY__=1
  define: __FLT_HAS_QUIET_NAN__=1
  define: __DBL_MANT_DIG__=53
  define: __DBL_DIG__=15
  define: __DBL_MIN_EXP__=(-1021)
  define: __DBL_MIN_10_EXP__=(-307)
  define: __DBL_MAX_EXP__=1024
  define: __DBL_MAX_10_EXP__=308
  define: __DBL_DECIMAL_DIG__=17
  define: __DBL_MAX__=double(1.79769313486231570814527423731704357e+308L)
  define: __DBL_MIN__=double(2.22507385850720138309023271733240406e-308L)
  define: __DBL_EPSILON__=double(2.22044604925031308084726333618164062e-16L)
  define: __DBL_DENORM_MIN__=double(4.94065645841246544176568792868221372e-324L)
  define: __DBL_HAS_DENORM__=1
  define: __DBL_HAS_INFINITY__=1
  define: __DBL_HAS_QUIET_NAN__=1
  define: __LDBL_MANT_DIG__=64
  define: __LDBL_DIG__=18
  define: __LDBL_MIN_EXP__=(-16381)
  define: __LDBL_MIN_10_EXP__=(-4931)
  define: __LDBL_MAX_EXP__=16384
  define: __LDBL_MAX_10_EXP__=4932
  define: __DECIMAL_DIG__=21
  define: __LDBL_DECIMAL_DIG__=21
  define: __LDBL_MAX__=1.18973149535723176502126385303097021e+4932L
  define: __LDBL_MIN__=3.36210314311209350626267781732175260e-4932L
  define: __LDBL_EPSILON__=1.08420217248550443400745280086994171e-19L
  define: __LDBL_DENORM_MIN__=3.64519953188247460252840593361941982e-4951L
  define: __LDBL_HAS_DENORM__=1
  define: __LDBL_HAS_INFINITY__=1
  define: __LDBL_HAS_QUIET_NAN__=1
  define: __FLT32_MANT_DIG__=24
  define: __FLT32_DIG__=6
  define: __FLT32_MIN_EXP__=(-125)
  define: __FLT32_MIN_10_EXP__=(-37)
  define: __FLT32_MAX_EXP__=128
  define: __FLT32_MAX_10_EXP__=38
  define: __FLT32_DECIMAL_DIG__=9
  define: __FLT32_MAX__=3.40282346638528859811704183484516925e+38F32
  define: __FLT32_MIN__=1.17549435082228750796873653722224568e-38F32
  define: __FLT32_EPSILON__=1.19209289550781250000000000000000000e-7F32
  define: __FLT32_DENORM_MIN__=1.40129846432481707092372958328991613e-45F32
  define: __FLT32_HAS_DENORM__=1
  define: __FLT32_HAS_INFINITY__=1
  define: __FLT32_HAS_QUIET_NAN__=1
  define: __FLT64_MANT_DIG__=53
  define: __FLT64_DIG__=15
  define: __FLT64_MIN_EXP__=(-1021)
  define: __FLT64_MIN_10_EXP__=(-307)
  define: __FLT64_MAX_EXP__=1024
  define: __FLT64_MAX_10_EXP__=308
  define: __FLT64_DECIMAL_DIG__=17
  define: __FLT64_MAX__=1.79769313486231570814527423731704357e+308F64
  define: __FLT64_MIN__=2.22507385850720138309023271733240406e-308F64
  define: __FLT64_EPSILON__=2.22044604925031308084726333618164062e-16F64
  define: __FLT64_DENORM_MIN__=4.94065645841246544176568792868221372e-324F64
  define: __FLT64_HAS_DENORM__=1
  define: __FLT64_HAS_INFINITY__=1
  define: __FLT64_HAS_QUIET_NAN__=1
  define: __FLT128_MANT_DIG__=113
  define: __FLT128_DIG__=33
  define: __FLT128_MIN_EXP__=(-16381)
  define: __FLT128_MIN_10_EXP__=(-4931)
  define: __FLT128_MAX_EXP__=16384
  define: __FLT128_MAX_10_EXP__=4932
  define: __FLT128_DECIMAL_DIG__=36
  define: __FLT128_MAX__=1.18973149535723176508575932662800702e+4932F128
  define: __FLT128_MIN__=3.36210314311209350626267781732175260e-4932F128
  define: __FLT128_EPSILON__=1.92592994438723585305597794258492732e-34F128
  define: __FLT128_DENORM_MIN__=6.47517511943802511092443895822764655e-4966F128
  define: __FLT128_HAS_DENORM__=1
  define: __FLT128_HAS_INFINITY__=1
  define: __FLT128_HAS_QUIET_NAN__=1
  define: __FLT32X_MANT_DIG__=53
  define: __FLT32X_DIG__=15
  define: __FLT32X_MIN_EXP__=(-1021)
  define: __FLT32X_MIN_10_EXP__=(-307)
  define: __FLT32X_MAX_EXP__=1024
  define: __FLT32X_MAX_10_EXP__=308
  define: __FLT32X_DECIMAL_DIG__=17
  define: __FLT32X_MAX__=1.79769313486231570814527423731704357e+308F32x
  define: __FLT32X_MIN__=2.22507385850720138309023271733240406e-308F32x
  define: __FLT32X_EPSILON__=2.22044604925031308084726333618164062e-16F32x
  define: __FLT32X_DENORM_MIN__=4.94065645841246544176568792868221372e-324F32x
  define: __FLT32X_HAS_DENORM__=1
  define: __FLT32X_HAS_INFINITY__=1
  define: __FLT32X_HAS_QUIET_NAN__=1
  define: __FLT64X_MANT_DIG__=64
  define: __FLT64X_DIG__=18
  define: __FLT64X_MIN_EXP__=(-16381)
  define: __FLT64X_MIN_10_EXP__=(-4931)
  define: __FLT64X_MAX_EXP__=16384
  define: __FLT64X_MAX_10_EXP__=4932
  define: __FLT64X_DECIMAL_DIG__=21
  define: __FLT64X_MAX__=1.18973149535723176502126385303097021e+4932F64x
  define: __FLT64X_MIN__=3.36210314311209350626267781732175260e-4932F64x
  define: __FLT64X_EPSILON__=1.08420217248550443400745280086994171e-19F64x
  define: __FLT64X_DENORM_MIN__=3.64519953188247460252840593361941982e-4951F64x
  define: __FLT64X_HAS_DENORM__=1
  define: __FLT64X_HAS_INFINITY__=1
  define: __FLT64X_HAS_QUIET_NAN__=1
  define: __DEC32_MANT_DIG__=7
  define: __DEC32_MIN_EXP__=(-94)
  define: __DEC32_MAX_EXP__=97
  define: __DEC32_MIN__=1E-95DF
  define: __DEC32_MAX__=9.999999E96DF
  define: __DEC32_EPSILON__=1E-6DF
  define: __DEC32_SUBNORMAL_MIN__=0.000001E-95DF
  define: __DEC64_MANT_DIG__=16
  define: __DEC64_MIN_EXP__=(-382)
  define: __DEC64_MAX_EXP__=385
  define: __DEC64_MIN__=1E-383DD
  define: __DEC64_MAX__=9.999999999999999E384DD
  define: __DEC64_EPSILON__=1E-15DD
  define: __DEC64_SUBNORMAL_MIN__=0.000000000000001E-383DD
  define: __DEC128_MANT_DIG__=34
  define: __DEC128_MIN_EXP__=(-6142)
  define: __DEC128_MAX_EXP__=6145
  define: __DEC128_MIN__=1E-6143DL
  define: __DEC128_MAX__=9.999999999999999999999999999999999E6144DL
  define: __DEC128_EPSILON__=1E-33DL
  define: __DEC128_SUBNORMAL_MIN__=0.000000000000000000000000000000001E-6143DL
  define: __REGISTER_PREFIX__=
  define: __USER_LABEL_PREFIX__=
  define: __GNUC_STDC_INLINE__=1
  define: __NO_INLINE__=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1
  define: __GCC_ATOMIC_BOOL_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR16_T_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR32_T_LOCK_FREE=2
  define: __GCC_ATOMIC_WCHAR_T_LOCK_FREE=2
  define: __GCC_ATOMIC_SHORT_LOCK_FREE=2
  define: __GCC_ATOMIC_INT_LOCK_FREE=2
  define: __GCC_ATOMIC_LONG_LOCK_FREE=2
  define: __GCC_ATOMIC_LLONG_LOCK_FREE=2
  define: __GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1
  define: __GCC_ATOMIC_POINTER_LOCK_FREE=2
  define: __GCC_HAVE_DWARF2_CFI_ASM=1
  define: __PRAGMA_REDEFINE_EXTNAME=1
  define: __SSP_STRONG__=3
  define: __SIZEOF_INT128__=16
  define: __SIZEOF_WCHAR_T__=4
  define: __SIZEOF_WINT_T__=4
  define: __SIZEOF_PTRDIFF_T__=8
  define: __amd64=1
  define: __amd64__=1
  define: __x86_64=1
  define: __x86_64__=1
  define: __SIZEOF_FLOAT80__=16
  define: __SIZEOF_FLOAT128__=16
  define: __ATOMIC_HLE_ACQUIRE=65536
  define: __ATOMIC_HLE_RELEASE=131072
  define: __GCC_ASM_FLAG_OUTPUTS__=1
  define: __k8=1
  define: __k8__=1
  define: __code_model_small__=1
  define: __MMX__=1
  define: __SSE__=1
  define: __SSE2__=1
  define: __FXSR__=1
  define: __SSE_MATH__=1
  define: __SSE2_MATH__=1
  define: __SEG_FS=1
  define: __SEG_GS=1
  define: __gnu_linux__=1
  define: __linux=1
  define: __linux__=1
  define: linux=1
  define: __unix=1
  define: __unix__=1
  define: unix=1
  define: __ELF__=1
  define: __DECIMAL_BID_FORMAT__=1
  define: _GNU_SOURCE=1
  define: _STDC_PREDEF_H=1
  define: __STDC_IEC_559__=1
  define: __STDC_IEC_559_COMPLEX__=1
  define: __STDC_ISO_10646__=201706L
  define: __STDC_NO_THREADS__=1
  other: --g++
  other: --gnu_version=70500
  stdver: c++14
  intelliSenseMode: gcc-x64
Queueing IntelliSense update for files in translation unit of: /home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp
cpptools/getFoldingRanges: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp (id: 4)
cpptools/getSemanticTokens: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp (id: 5)
cpptools/finishUpdateSquiggles
Error squiggle count: 100
terminating child process: 17795
Update IntelliSense time (sec): 0.958
  Processing folder (recursive): /home/oliver/git/ninjas2/
cpptools/getCodeActions: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp (id: 6)
  Discovering files: 28895 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
cpptools/activeDocumentChange: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp
Queueing IntelliSense update for files in translation unit of: /home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 100
Update IntelliSense time (sec): 0.297
cpptools/getSemanticTokens: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp (id: 7)
cpptools/getCodeActions: file:///home/oliver/git/ninjas2/plugins/Ninjas2/Ninjas2UI.cpp (id: 8)

```
</details>

**Screenshots**
![image](https://user-images.githubusercontent.com/3141635/87707600-a9c2cf00-c7a1-11ea-8ff6-4540c45a0ff7.png)

**Additional context**
-
Thanks and Regards
Oliver

**Comment by sean-mcmanus** [comment] 2020-07-16 19:35
The error may not be appearing in 0.28.3 because the IntelliSense process may be crashing or otherwise erroring out.

Are you getting any missing includes?

What do you see when you do Go to Definition on getPluginInstancePointer? I'm seeing the variable not being defined, because the macros are not defined that are surrounding the definition.

**Comment by olijaun** [comment] 2020-07-20 17:28
Hi
Thanks for looking into this. "Go to Definition" works fine on getPluginInstancePointer(). But as you say, according to the "highlighting" it is not active. But the variable is set (see DistrhoPluginInfo.h):

```
#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS   1
```
"Go to definition" for DistroPluginInfo.h also works.

With Version 0.28.3 vscode recognizes the Variable as set to "1". So it really boils done to the question: "why does 0.29.0" ignore DistrhoPluginInfo.h? 

I cannot see any "Problems" that would mention a problem regarding this file.

Regards
Oliver

**Comment by ciwei100000** [comment] 2020-07-22 01:03
I am having the similar "identifier is undefined" issue. I can confirm mine are well defined in the header files and the code can be compiled successfully. Those errors sometimes will disappear if I open the header file containing the definitions of those identifiers in the vs code window. However, they usually occur again after I close the header files. And if the identifiers spread across different header files, only those in the active file can be properly found. 

Edit: It seems that it can be resolved by changing the "cppStandard" in the c_cpp_properties.json file from "gnu++14" to "c++14". I think, with the old version, it would be set to "c++14" if I chose c++14 in the configuration UI of the extension. But I didn't know now it's defaulted to "gnu++14".

**Comment by Colengms** [comment] 2020-07-22 02:42
Hi @olijaun .  It looks like the wrong version of `DistrhoPluginInfo.h` is being picked up by our intelliSense process.  Since it's been configured to consider your entire source tree as an include path, this may actually be valid behavior.  To ensure things work properly with multiple separate projects that contain headers of the same name, I'd suggest using a multiroot workspace, so you can provide separate configurations per sub-project which only include necessary include paths.  Alternatively, you could use compile_commands.json to configure each source file individually.  Custom configuration providers such as [CMake Tools](https://github.com/microsoft/vscode-cmake-tools) can also provide more granular configuration in single-folder mode.  A custom configuration provider for makefile build systems is currently under development.

**Comment by captainzonks** [comment] 2020-07-23 21:07
I'm having this issue as well. I'm on Manjaro and using a variety of libraries and includes.

Modifying the c_cpp_properties.json will suddenly fix everything for a moment (everything is found, squiggles disappear) but within a few minutes they're all lost again and the squiggles return. It doesn't matter what I modify or change in the json file (such as ciwei100000 suggesting switching from gnu++14 to c++14), it'll "find" everything for a moment, but then break again shortly after.

EDIT: just wanna add, everything builds just fine; this is only an intellisense problem

**Comment by sean-mcmanus** [comment] 2020-07-23 21:26
@captainzonks We need more repro info about your particular configuration (such as from C/C++: Log Diagnostics). Modifying the c_cpp_properties.json is probably triggering a reparse, and when that finishes the squiggles are appearing.

**Comment by captainzonks** [comment] 2020-07-23 21:49
@sean-mcmanus 

```
-------- Diagnostics - 7/23/2020, 3:45:01 PM
Version: 0.29.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/usr/include/SDL2"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/g++",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "cppStandard": "c++17",
    "browse": {
        "path": [
            "/usr/include/SDL2",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/******/repos/cpp/HandmadeHero/handmade/code/sdl_handmade.cpp ]:
    /home/******/repos/cpp/HandmadeHero/handmade/code/sdl_handmade.cpp
    /home/******/repos/cpp/HandmadeHero/handmade/code/handmade.h
Translation Unit Configurations:
[ /home/******/repos/cpp/HandmadeHero/handmade/code/sdl_handmade.cpp ]:
    Process ID: 374398
    Memory Usage: 86 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /usr/include/SDL2
        /usr/include/c++/10.1.0
        /usr/include/c++/10.1.0/x86_64-pc-linux-gnu
        /usr/include/c++/10.1.0/backward
        /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include
        /usr/local/include
        /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include-fixed
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100100
Total Memory Usage: 86 MB
```

---

I'm looking again at the squiggles. And I think it's primarily macros that IntelliSense is having an issue with. And oddly, upon hovering over the macros it'll pop out the definition (...expands to: ...) but then beneath the definition it'll have "identifier "PROT_WRITE" is undefined" (for example, from the mmap() function). Does that make sense?

Also, that Diagnostics spat out a slightly different configuration than what my c_cpp_properties.json has...which is:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${default}",
                "/usr/include/SDL2"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}

```

**Comment by sean-mcmanus** [comment] 2020-07-23 22:06
@captainzonks I've moved your issue to https://github.com/microsoft/vscode-cpptools/issues/5829

**Comment by Colengms** [comment] 2020-07-23 23:18
Closing this, as I believe olijaun's issue has been addressed.

**Comment by Colengms** [comment] 2020-07-23 23:19
Also, the following issue is tracking makefile support: https://github.com/microsoft/vscode-cpptools/issues/5791

**Closed as completed by Colengms** 2020-07-23 23:18 UTC
Labels: Language Service, by design, Feature: Configuration

**Comment by sean-mcmanus** [comment] 2021-03-19 20:10
A makefile configuration provider is available at https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools
