### ISSUE TITLE
large projects(symbolic link directory with a loop) , cpptools running heavily,never stop

### ISSUE THREAD

**Issue by liuyuxun** [microsoft/vscode-cpptools#600] opened 2017-03-29 10:02 UTC
```

**I've a big project about 60000 files

after about a few minutes browse my code ,i got cpptools running nearly 100%

goto definition do not work any more,only kill it ,and restart vscode

this is the sample from mac,

ps:i have got symbolic link directory with a loop in my project ,is it the issue?**





```

_sampling process 2737 for 3 seconds with 1 millisecond of run time between samples
Sampling completed, processing symbols...
Analysis of sampling Microsoft.VSCode.CPP.Extension.darwin (pid 2737) every 1 millisecond
Process:         Microsoft.VSCode.CPP.Extension.darwin [2737]
Path:            /Users/lyx/.vscode/extensions/ms-vscode.cpptools-0.10.5/bin/Microsoft.VSCode.CPP.Extension.darwin
Load Address:    0x103f3a000
Identifier:      Microsoft.VSCode.CPP.Extension.darwin
Version:         0
Code Type:       X86-64
Parent Process:  ??? [1]

Call graph:
    2580 Thread_130848   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2580 start  (in libdyld.dylib) + 1  [0x7fff8db9d235]
    +   2580 main  (in Microsoft.VSCode.CPP.Extension.darwin) + 215  [0x103f3c287]
    +     2580 vscode::handler_base<message_handler>::main_loop()  (in Microsoft.VSCode.CPP.Extension.darwin) + 867  [0x103f3c643]
    +       2580 std::__1::thread::join()  (in libc++.1.dylib) + 23  [0x7fff8c77b4b7]
    +         2580 pthread_join  (in libsystem_pthread.dylib) + 425  [0x7fff8ddb8759]
    +           2580 __semwait_signal  (in libsystem_kernel.dylib) + 10  [0x7fff8dccbf46]
    2580 Thread_130849
    + 2580 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8ddb6101]
    +   2580 _pthread_start  (in libsystem_pthread.dylib) + 286  [0x7fff8ddb68fb]
    +     2580 _pthread_body  (in libsystem_pthread.dylib) + 180  [0x7fff8ddb69af]
    +       2580 std::__1::__thread_proxy<std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::'lambda'()> >(void*, void*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 96  [0x10443b8f0]
    +         2580 microsoft::vc::thread_pool::thread_pool(int)::'lambda'()::operator()() const  (in Microsoft.VSCode.CPP.Extension.darwin) + 123  [0x10443b9ab]
    +           2580 microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int)  (in Microsoft.VSCode.CPP.Extension.darwin) + 309  [0x10443e5b5]
    +             2580 neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long long, int&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 1104  [0x10443f250]
    +               2580 _pthread_cond_wait  (in libsystem_pthread.dylib) + 712  [0x7fff8ddb786e]
    +                 2580 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff8dccbbf2]
    2580 Thread_130850
    + 2580 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8ddb6101]
    +   2580 _pthread_start  (in libsystem_pthread.dylib) + 286  [0x7fff8ddb68fb]
    +     2580 _pthread_body  (in libsystem_pthread.dylib) + 180  [0x7fff8ddb69af]
    +       2580 std::__1::__thread_proxy<std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::'lambda'()> >(void*, void*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 96  [0x10443b8f0]
    +         2580 microsoft::vc::thread_pool::thread_pool(int)::'lambda'()::operator()() const  (in Microsoft.VSCode.CPP.Extension.darwin) + 123  [0x10443b9ab]
    +           2580 microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int)  (in Microsoft.VSCode.CPP.Extension.darwin) + 309  [0x10443e5b5]
    +             2580 neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long long, int&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 1104  [0x10443f250]
    +               2580 _pthread_cond_wait  (in libsystem_pthread.dylib) + 712  [0x7fff8ddb786e]
    +                 2580 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff8dccbbf2]
    2580 Thread_130853
      2580 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8ddb6101]
        2580 _pthread_start  (in libsystem_pthread.dylib) + 286  [0x7fff8ddb68fb]
          2580 _pthread_body  (in libsystem_pthread.dylib) + 180  [0x7fff8ddb69af]
            2580 void* std::__1::__thread_proxy<std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::'lambda1'()> >(void*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 117  [0x103f69ee5]
              2580 message_handler::parse_root()  (in Microsoft.VSCode.CPP.Extension.darwin) + 848  [0x103f6a290]
                2580 browse_engine::generate_file_list(bool, bool)  (in Microsoft.VSCode.CPP.Extension.darwin) + 690  [0x103f85f52]
                  2580 parser::add_files(microsoft::vc::path_utf8&, browse_engine*, bool)  (in Microsoft.VSCode.CPP.Extension.darwin) + 352  [0x103f86380]
                    2580 microsoft::vc::result_t parser::process_path<microsoft::vc::recursive_directory_iterator_utf8>(microsoft::vc::path_utf8 const&, std::__1::function<microsoft::vc::result_t (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::function<microsoft::vc::result_t (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>)  (in Microsoft.VSCode.CPP.Extension.darwin) + 566  [0x103f90b06]
                      2580 std::__1::__function::__func<parser::add_files(microsoft::vc::path_utf8&, browse_engine*, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), std::__1::allocator<parser::add_files(microsoft::vc::path_utf8&, browse_engine*, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, microsoft::vc::result_t (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 13  [0x103f924dd]
                        2580 parser::add_files(microsoft::vc::path_utf8&, browse_engine*, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const  (in Microsoft.VSCode.CPP.Extension.darwin) + 42  [0x103f9254a]
                          2580 browse_engine::parse_file(char const*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 1314  [0x103f876c2]
                            2580 parser::update_file_if_needed(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, stat const*, bool, bool)  (in Microsoft.VSCode.CPP.Extension.darwin) + 1844  [0x103f92d04]
                              2580 code_store::a_store::finalize_full_file_update(code_store::a_record_id<code_store::a_file_tag>, code_store::a_store_event_listener*, code_store::lock_manager*, bool)  (in Microsoft.VSCode.CPP.Extension.darwin) + 415  [0x103fc423f]
                                2580 code_store::a_store_file_il::update_store(code_store::a_store*, code_store::a_store_event_listener*, code_store::lock_manager*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 270  [0x103fe118e]
                                  2580 code_store::a_store_file_il::impl::diff_changes(code_store::a_store*, code_store::an_il_scope*, std::__1::deque<std::__1::pair<code_store::a_record_id<code_store::an_item_tag>, code_store::a_code_item_kind>, std::__1::allocator<std::__1::pair<code_store::a_record_id<code_store::an_item_tag>, code_store::a_code_item_kind> > >&, code_store::a_store_event_listener&, std::__1::shared_ptr<std::__1::deque<std::__1::shared_ptr<code_store::CEncEdit>, std::__1::allocator<std::__1::shared_ptr<code_store::CEncEdit> > > >&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 492  [0x103fe19ec]
                                    2580 code_store::CEncRudeEditEngine::ComputeParseTreeEdits(std::__1::shared_ptr<code_store::CEncParseTree> const&, std::__1::shared_ptr<code_store::CEncParseTree> const&, std::__1::function<bool ()> const&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 271  [0x103ff26bf]
                                      2580 code_store::CEncEditScript::Execute()  (in Microsoft.VSCode.CPP.Extension.darwin) + 79  [0x103fecc7f]
                                        2580 code_store::CEncEditScript::ProcessTreePreOrder(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 92  [0x103feccfc]
                                          2580 code_store::CEncEditScript::ProcessTreePreOrder(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 33  [0x103feccc1]
                                            1513 code_store::CEncEditScript::ProcessNodeFromTree2(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 347  [0x103fecefb]
                                            ! 916 code_store::CEncEditScript::FindPos(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 184  [0x103fed028]
                                            ! : 916 code_store::CEncParseNode::CEnum::MoveNext()  (in Microsoft.VSCode.CPP.Extension.darwin) + 17,43,...  [0x103feedb1,0x103feedcb,...]
                                            ! 539 code_store::CEncEditScript::FindPos(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 93,188,...  [0x103fecfcd,0x103fed02c,...]
                                            ! 58 code_store::CEncEditScript::FindPos(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 106  [0x103fecfda]
                                            !   58 code_store::CEncParseNode::CEnum::MoveNext()  (in Microsoft.VSCode.CPP.Extension.darwin) + 17,0,...  [0x103feedb1,0x103feeda0,...]
                                            1056 code_store::CEncEditScript::ProcessNodeFromTree2(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 379  [0x103fecf1b]
                                            ! 1056 code_store::CEncParseNode::InsertInTree(code_store::CEncParseNode*, int)  (in Microsoft.VSCode.CPP.Extension.darwin) + 125,153,...  [0x103fef19d,0x103fef1b9,...]
                                            5 code_store::CEncEditScript::ProcessNodeFromTree2(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 362  [0x103fecf0a]
                                            ! 5 code_store::CEncParseTree::CreateParseNode(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 49  [0x103ff15e1]
                                            !   4 code_store::CEncParseTree::AllocateParseNode(code_store::CEncNodeLabel const&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 1713  [0x103ff1cc1]
                                            !   : 3 operator new(unsigned long)  (in libc++abi.dylib) + 30  [0x7fff8c7ade2e]
                                            !   : | 2 malloc  (in libsystem_malloc.dylib) + 24  [0x7fff8dd1e200]
                                            !   : | + 2 malloc_zone_malloc  (in libsystem_malloc.dylib) + 107  [0x7fff8dd1f282]
                                            !   : | +   1 default_zone_malloc  (in libsystem_malloc.dylib) + 41  [0x7fff8dd2e903]
                                            !   : | +   1 szone_malloc_should_clear  (in libsystem_malloc.dylib) + 1138  [0x7fff8dd1f754]
                                            !   : | +     1 madvise  (in libsystem_kernel.dylib) + 10  [0x7fff8dccce9e]
                                            !   : | 1 malloc  (in libsystem_malloc.dylib) + 0  [0x7fff8dd1e1e8]
                                            !   : 1 operator new(unsigned long)  (in libc++abi.dylib) + 0  [0x7fff8c7ade10]
                                            !   1 code_store::CEncParseTree::AllocateParseNode(code_store::CEncNodeLabel const&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 34  [0x103ff1632]
                                            4 code_store::CEncEditScript::ProcessNodeFromTree2(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 395  [0x103fecf2b]
                                            2 code_store::CEncEditScript::ProcessNodeFromTree2(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 400  [0x103fecf30]
                                              1 code_store::CEncEdits::AddInsert(code_store::CEncParseNode*, code_store::CEncParseNode*, int, code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 47  [0x103febadf]
                                              : 1 operator new(unsigned long)  (in libc++abi.dylib) + 30  [0x7fff8c7ade2e]
                                              :   1 malloc  (in libsystem_malloc.dylib) + 0  [0x7fff8dd1e1e8]
                                              1 code_store::CEncEdits::AddInsert(code_store::CEncParseNode*, code_store::CEncParseNode*, int, code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin) + 194  [0x103febb72]

Total number in stack (recursive counted multiple, when >=5):

Sort by top of stack, same collapsed (when >= 5):
        __psynch_cvwait  (in libsystem_kernel.dylib)        5160
        __semwait_signal  (in libsystem_kernel.dylib)        2580
        code_store::CEncParseNode::InsertInTree(code_store::CEncParseNode*, int)  (in Microsoft.VSCode.CPP.Extension.darwin)        1056
        code_store::CEncParseNode::CEnum::MoveNext()  (in Microsoft.VSCode.CPP.Extension.darwin)        974
        code_store::CEncEditScript::FindPos(code_store::CEncParseNode*)  (in Microsoft.VSCode.CPP.Extension.darwin)        539

Binary Images:
       0x103f3a000 -        0x1044feff7 +Microsoft.VSCode.CPP.Extension.darwin (0) <177E8378-0A35-3BE7-9C35-51968C3ACE5D> /Users/lyx/.vscode/extensions/ms-vscode.cpptools-0.10.5/bin/Microsoft.VSCode.CPP.Extension.darwin
       0x10b184000 -        0x10b1c1dc7  dyld (0.0 - ???) <8239D0D7-66F6-3C44-A77F-586F74525DA3> /usr/lib/dyld
    0x7fff8c580000 -     0x7fff8c581ffb  libSystem.B.dylib (1238.51.1) <D9B20A4F-87BC-36CB-9405-80E105666725> /usr/lib/libSystem.B.dylib
    0x7fff8c733000 -     0x7fff8c789ff7  libc++.1.dylib (307.5) <0B43BB5D-E6EB-3464-8DE9-B41AC8ED9D1C> /usr/lib/libc++.1.dylib
    0x7fff8c78a000 -     0x7fff8c7b4fff  libc++abi.dylib (307.3) <30199352-88BF-30BD-8CFF-2A4FBE247523> /usr/lib/libc++abi.dylib
    0x7fff8d2a7000 -     0x7fff8d67cbc7  libobjc.A.dylib (709) <54CD8D1A-5C98-3559-B13A-932B3D3DD338> /usr/lib/libobjc.A.dylib
    0x7fff8dac1000 -     0x7fff8dac5ff7  libcache.dylib (79) <093A4DAB-8385-3D47-A350-E20CB7CCF7BF> /usr/lib/system/libcache.dylib
    0x7fff8dac6000 -     0x7fff8dad0fff  libcommonCrypto.dylib (60092.50.5) <BE8380C5-C09D-3F48-A502-AEBB58231067> /usr/lib/system/libcommonCrypto.dylib
    0x7fff8dad1000 -     0x7fff8dad8fff  libcompiler_rt.dylib (62) <55D47421-772A-32AB-B529-1A46C2F43B4D> /usr/lib/system/libcompiler_rt.dylib
    0x7fff8dad9000 -     0x7fff8dae1fff  libcopyfile.dylib (138) <819BEA3C-DF11-3E3D-A1A1-5A51C5BF1961> /usr/lib/system/libcopyfile.dylib
    0x7fff8dae2000 -     0x7fff8db65fdf  libcorecrypto.dylib (442.50.19) <8A39EE06-121C-3731-A9E9-35847064B3EE> /usr/lib/system/libcorecrypto.dylib
    0x7fff8db66000 -     0x7fff8db97fff  libdispatch.dylib (703.50.37) <D122E712-9593-31CA-BAC4-4A54410BF4A0> /usr/lib/system/libdispatch.dylib
    0x7fff8db98000 -     0x7fff8db9dffb  libdyld.dylib (433.5) <129D3B44-FB21-3750-9A68-48B5C3DC632B> /usr/lib/system/libdyld.dylib
    0x7fff8db9e000 -     0x7fff8db9effb  libkeymgr.dylib (28) <7AA011A9-DC21-3488-BF73-3B5B14D1FDD6> /usr/lib/system/libkeymgr.dylib
    0x7fff8dbac000 -     0x7fff8dbacfff  liblaunch.dylib (972.50.27) <037D198D-9B02-3EF9-A8E9-6F43EA555A9E> /usr/lib/system/liblaunch.dylib
    0x7fff8dbad000 -     0x7fff8dbb2ff3  libmacho.dylib (898) <17D5D855-F6C3-3B04-B680-E9BF02EF8AED> /usr/lib/system/libmacho.dylib
    0x7fff8dbb3000 -     0x7fff8dbb5ff3  libquarantine.dylib (85.50.1) <7B32EA91-AB8B-32A4-8E52-9D3ED46CAC8E> /usr/lib/system/libquarantine.dylib
    0x7fff8dbb6000 -     0x7fff8dbb7ffb  libremovefile.dylib (45) <38D4CB9C-10CD-30D3-8B7B-A515EC75FE85> /usr/lib/system/libremovefile.dylib
    0x7fff8dbb8000 -     0x7fff8dbd0ff7  libsystem_asl.dylib (349.50.5) <096E4228-3B7C-30A6-8B13-EC909A64499A> /usr/lib/system/libsystem_asl.dylib
    0x7fff8dbd1000 -     0x7fff8dbd1ff7  libsystem_blocks.dylib (67) <10DC5404-73AB-35B3-A277-A8AFECB476EB> /usr/lib/system/libsystem_blocks.dylib
    0x7fff8dbd2000 -     0x7fff8dc5ffef  libsystem_c.dylib (1158.50.2) <B03F8915-1E9B-3C84-AED5-68E2E0031630> /usr/lib/system/libsystem_c.dylib
    0x7fff8dc60000 -     0x7fff8dc63ffb  libsystem_configuration.dylib (888.51.2) <872C8A42-0871-3424-830B-84E587A75D27> /usr/lib/system/libsystem_configuration.dylib
    0x7fff8dc64000 -     0x7fff8dc67fff  libsystem_coreservices.dylib (41.4) <FD0915E8-9C43-3FCB-94E0-33C45DF028CD> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff8dc68000 -     0x7fff8dc80fff  libsystem_coretls.dylib (121.50.4) <EC6FCF07-DCFB-3A03-9CC9-6DD3709974C6> /usr/lib/system/libsystem_coretls.dylib
    0x7fff8dc81000 -     0x7fff8dc87fff  libsystem_dnssd.dylib (765.50.9) <FF02A197-7CEF-3684-8155-E5E225051E44> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff8dc88000 -     0x7fff8dcb1ff7  libsystem_info.dylib (503.50.4) <611DB84C-BF70-3F92-8702-B9F28A900920> /usr/lib/system/libsystem_info.dylib
    0x7fff8dcb2000 -     0x7fff8dcd4ff7  libsystem_kernel.dylib (3789.51.2) <FC51D7B0-8292-3F6A-9231-64340B237EB7> /usr/lib/system/libsystem_kernel.dylib
    0x7fff8dcd5000 -     0x7fff8dd1cfe7  libsystem_m.dylib (3121.6) <A790C9A5-DD24-32F5-8FD7-33BFCE79AC87> /usr/lib/system/libsystem_m.dylib
    0x7fff8dd1d000 -     0x7fff8dd3bff7  libsystem_malloc.dylib (116.50.8) <48D1BBA3-914E-3C65-AF70-C33B4A1B5233> /usr/lib/system/libsystem_malloc.dylib
    0x7fff8dd3c000 -     0x7fff8dd95ffb  libsystem_network.dylib (856.50.56) <FDE14243-4328-3EFD-824C-C0D314D7B540> /usr/lib/system/libsystem_network.dylib
    0x7fff8dd96000 -     0x7fff8dd9fff3  libsystem_networkextension.dylib (563.50.32) <D5381DA9-529C-3588-BE16-A2245DE93423> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff8dda0000 -     0x7fff8dda9ff3  libsystem_notify.dylib (165.20.1) <B8160190-A069-3B3A-BDF6-2AA408221FAE> /usr/lib/system/libsystem_notify.dylib
    0x7fff8ddaa000 -     0x7fff8ddb2fe7  libsystem_platform.dylib (126.50.8) <5940EAB7-84D6-34DC-9B38-111648B2B589> /usr/lib/system/libsystem_platform.dylib
    0x7fff8ddb3000 -     0x7fff8ddbdff7  libsystem_pthread.dylib (218.51.1) <62A84A68-431D-3B54-A7B6-31367CCF2884> /usr/lib/system/libsystem_pthread.dylib
    0x7fff8ddbe000 -     0x7fff8ddc1ff7  libsystem_sandbox.dylib (592.50.47) <87A2327D-B7A1-3E4C-A85D-D3D9484003DB> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff8ddc2000 -     0x7fff8ddc3ff3  libsystem_secinit.dylib (24.50.4) <F78B847B-3565-3E4B-98A6-F7AD40392E2D> /usr/lib/system/libsystem_secinit.dylib
    0x7fff8ddc4000 -     0x7fff8ddcbffb  libsystem_symptoms.dylib (532.50.47) <9CF6A47C-8343-3E85-9C27-A8D98E726A8B> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff8ddcc000 -     0x7fff8dddfff7  libsystem_trace.dylib (518.51.1) <E1D540D8-CC88-3901-92BA-FC4B802FE0E8> /usr/lib/system/libsystem_trace.dylib
    0x7fff8dde0000 -     0x7fff8dde5ffb  libunwind.dylib (35.3) <3D50D8A8-C460-334D-A519-2DA841102C6B> /usr/lib/system/libunwind.dylib
    0x7fff8dde6000 -     0x7fff8de0fff7  libxpc.dylib (972.50.27) <ABC45890-DA23-3A4A-B50B-1384BD4CBBDF> /usr/lib/system/libxpc.dylib
Sample analysis of process 2737 written to file /dev/stdout_

**Comment by sean-mcmanus** [comment] 2017-03-29 12:24
This is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/463 . It's near the top of our list of issues to fix. It might not get fixed in the next update, but it's expected for the one after that.

**Closed as completed by sean-mcmanus** 2017-03-29 12:24 UTC
Labels: duplicate, Language Service, more info needed

**Comment by sean-mcmanus** [comment] 2017-05-15 23:18
I'm not able to repro any problem with a simple workspace with a sub folder with symbolic link to the parent folder on Linux and Mac. Is this still reproing? It seems like the repro might more complicated and we need more repro details of exactly how the cyclic link is constructed.
