### ISSUE TITLE
Intellisense thinks that 'new' accepts different arguments

### ISSUE THREAD

**Issue by lotusprey** [microsoft/vscode-cpptools#7081] opened 2021-03-01 14:49 UTC
**Type: LanguageService**

- OS and Version: Windows 10 Pro 20H2
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.2

**Steps to reproduce**
In the following code (or any other similar example):
```
#include <new>

int main()
{
    int *arr = new (std::nothrow) int[10];
    return 0;
}
```
intellisense marks `new` with 
`function "operator new[]" cannot be called with the given argument list -- argument types are: (unsigned long, const std::nothrow_t)C/C++(1767)`

**Expected behavior**
The program compiles fine, so I think this is a bug.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 3/1/2021, 4:02:15 PM
Version: 1.2.2
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": /*path*/,
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "windows-gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
/* ... */
Translation Unit Configurations:
[ /* ... */ ]:
    Process ID: 8968
    Memory Usage: 15 MB
    Compiler Path: /* ... */
    Includes:
        /* ... */
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++14
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=100200
Total Memory Usage: 15 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 2513
Number of files discovered (not excluded): 2456
```
</details>

**Screenshot**
![example](https://user-images.githubusercontent.com/35681808/109506430-48d4d680-7aa6-11eb-97e5-079d5e838324.png)

**Comment by sean-mcmanus** [comment] 2021-03-01 19:53
This appears to be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6246 , which is tracking https://developercommunity.visualstudio.com/content/problem/1207998/cc-intellisense-gives-errors-regarding-size-t-and.html .

**Closed as completed by sean-mcmanus** 2021-03-01 19:53 UTC
Labels: duplicate
