### ISSUE TITLE
The generated active file is shown in the root of workspace

### ISSUE THREAD

**Issue by BowenLi1994** [microsoft/vscode-cpptools#6386] opened 2020-10-24 23:31 UTC
Type: General

**Describe the bug**
- OS and Version:8.04.5 LTS (Bionic Beaver) 
- VS Code Version:1.50.1
- C/C++ Extension Version: v1.1.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them):C++ Intellisense,GitHub Pull Requests and Issues,GitLens
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*
1. I open the "issue" folder by remote SSH extension as the root path
2. In the "project" folder, there is a "folder1" subfolder.
3. In "folder1", there is a "helloworld.cpp"
4. When I try " run build task ..." by using "g++ build active file", the active file "helloworld" will appear in the root folder of the "issue" folder instead of the current directory "folder1".
5. In the task.json file, the environmental variable is "fileDirname".
6.This issue suddenly happens, everything is fine before.

**Expected behavior**
I hope the generated active file can be generated at the current folder instead of the root folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/33384921/97095591-5a592e00-162f-11eb-8342-4d0a293c84bf.png)

**Additional context**
Add any other context about the problem here including log messages from the Output window.
The task.joson is the default file without any modification:
![image](https://user-images.githubusercontent.com/33384921/97095600-74930c00-162f-11eb-840a-5939354cda33.png)

**Comment by WardenGnaw** [comment] 2020-10-26 20:17
This is by design. VS Code only looks a tasks/launch configurations in the ${workspaceRoot} which is the folder you have opened. 

Any configurations in subfolders are not looked at by VS Code so we do not generate in subfolders. If you wish to have it generated in the subfolder. Please open VS Code with that folder.

**Comment by timothylabounko** [comment] 2020-11-07 23:17
I ran into this issue as well, and I think there are several inconsistencies here, or I'm misunderstanding how to think about this.

${file} points to the active file using the full path, but ${fileDirname} in tasks.json ends up being evaluated to the root folder instead of the subfolder. This seems counter to the examples in https://code.visualstudio.com/docs/editor/variables-reference

Additionally, if I have a launch.json file with program specified as "program": "${fileDirname}\\${fileBasenameNoExtension}", it does evaluate to include the subfolder. This makes matching the build task with the run with debugger task difficult, since one includes the subfolder and one doesn't. This was the default configuration generated when following the instructions from
https://code.visualstudio.com/docs/cpp/config-mingw#_build-helloworldcpp and
https://code.visualstudio.com/docs/cpp/config-mingw#_debug-helloworldcpp

What should I be doing differently to get this to work? For now I've resorted to configuring the build task to output to ${file}.exe and the launch task to read from ${file}.exe, since those variable match.

**Comment by JohnnyLAmpAz** [comment] 2020-11-12 20:44
Same happening here. The var `${relativeFileDirname}` (and that part in `${fileDirname}`) is just null during the build task, therefore cannot handle either source files or build destination path in subdirectories of the root project dir.

Project tree:
```
.
├── .gitignore
├── notes.md
├── section0/
│   ├── .bin/
│   ├── ex1.cpp
│   ├── ex2.cpp
│   ├── ex3.cpp
│   ├── ex4.cpp
│   ├── ex5.cpp
│   └── ex6.cpp
└── .vscode/
    ├── launch.json
    └── tasks.json
```
Build task (relevant section):
```json
"command": "/usr/bin/g++",
"args": [
    "-g",
    "${file}",
    "-o",
    "${fileDirname}/.bin/${fileBasenameNoExtension}"
]
```
Output of build task:
```
> Executing task: C/C++: g++ build active file in .bin/ <

Starting build...
Build finished with error:

/usr/bin/ld: cannot open output file /home/lorenzo/Documents/UNI/EXE/INFO_PROGR/EXE-INFO_2020-11-12/.bin/ex4: No such file or directory
collect2: error: ld returned 1 exit status
```

**Comment by mak626** [comment] 2020-11-17 17:25
**Temporary fix** 

In `tasks.json` file

change `"type": "cppbuild"`  to  `"type": "shell"`

**Comment by sean-mcmanus** [comment] 2020-11-18 02:29
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.2

**Closed as completed by sean-mcmanus** 2020-11-18 02:29 UTC
Labels: bug, fixed, quick fix, regression, tasks/build/debug
