### ISSUE TITLE
Iunder Linux configuration of the c language, when I started writing # include always prompt the Add the include path to Settings. C_cpp_properties. Json configuration path is my c library paths. My English is not very good, I'm very sorry.

### ISSUE THREAD

**Issue by zhongmissu** [microsoft/vscode-cpptools#436] opened 2017-01-07 15:48 UTC

**Comment by sean-mcmanus** [comment] 2017-01-07 19:38
Can you locate and delete the .browse.vc.db or change the databaseFilename? What is the size of the database? Is the Linux configuration in the bottom right still red? If you can give a repro that would help. What Linux distribution/version are you using? What is your includePath setting? Can you get the #include to work under any circumstance?

**Comment by bobbrow** [comment] 2017-03-10 00:53
Are you still seeing this issue?  I cannot reproduce what you describe.  Please provide some more details, or let us know if the issue is fixed.

**Comment by bobbrow** [comment] 2017-03-14 16:47
I will close this for now.  If you are still seeing this issue, please reopen and share which version of the extension and VS Code you are using.  Thank you.

**Closed as completed by bobbrow** 2017-03-14 16:47 UTC
Labels: Language Service, more info needed
