### ISSUE TITLE
Automatic convertion '.' to '->' doesn't work

### ISSUE THREAD

**Issue by zhiyiYo** [microsoft/vscode-cpptools#9716] opened 2022-08-11 04:56 UTC
### Environment

- OS and Version: Windows11 22621.382
- VS Code Version: 1.70.1
- C/C++ Extension Version: 1.11.5
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
Automatic convertion '.' to '->' doesn't work in method.

### Bug Summary and Steps to Reproduce

As shown in the following figure:
![补全](https://user-images.githubusercontent.com/65096819/184066954-d3623934-bd10-4cf6-a0c9-9a62adb64c71.gif)

### Expected behavior

Automatic convertion '.' to '->' should work.

### Code sample and Logs

```cpp
struct Dog {
    int age;
    Dog(int a) : age(a) {}
};

class Owner {
public:
    void walkDog(Dog *dog) {
        
    }
};


void walkDog(Dog *dog) {

}
```

**Comment by sean-mcmanus** [comment] 2022-08-12 02:05
This is already fixed in https://github.com/microsoft/vscode-cpptools/releases/tag/v1.12.0, i.e. duplicate of https://github.com/microsoft/vscode-cpptools/issues/9599 .

**Closed as not planned by sean-mcmanus** 2022-08-12 02:05 UTC
Labels: bug, duplicate, Language Service, fixed, verified, Feature: Auto-complete, Works in VS
