### ISSUE TITLE
Show nested namespaces in breadcrumb w/o '...'

### ISSUE THREAD

**Issue by GertGrossmann** [microsoft/vscode-cpptools#6844] opened 2021-01-25 09:32 UTC
Issue Type: <b>Feature Request</b>

~~~
// A.cpp
namespace A {
namespace B {
// cursor is here
}}
~~~
Actual breadcrumb: A.cpp > {} A > {} B

~~~
// B.cpp
namespace A::B {
// cursor is here
}
~~~
Actual breadcrumb: A.cpp > ...
Expected : A.cpp > {} A > {} B

Extension version: 1.1.3
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.12.14-95.45-default

**Comment by michelleangela** [comment] 2021-01-25 19:06
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/4871

**Closed as completed by michelleangela** 2021-01-25 19:06 UTC
Labels: duplicate, Language Service, Feature: Document Symbol
