### ISSUE TITLE
IntelliSense doesn't update correctly after pasting of multi-line code

### ISSUE THREAD

**Issue by bshoshany** [microsoft/vscode-cpptools#6565] opened 2020-11-22 17:13 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: **Windows_NT x64 10.0.19042**
- VS Code Version: **1.51.1**
- C/C++ Extension Version: **1.1.2**
- Other extensions you installed (and if the issue persists after disabling them): **When disabling all extensions except the C/C++ extension (which is required to reproduce the issue), the issue still occurs.**
- Does this issue involve using SSH remote to run the extension on a remote machine?: **No.**
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc). **See title.**

**Steps to reproduce**

With the following code sample:

```cpp
#include <iostream>

/**
 * @brief Adds two numbers.
 *
 * @param a The first number to add.
 * @param b The second number to add.
 * @return The sum of the numbers.
 */
double add(const double &a, const double &b)
{
    return a + b;
}

int main()
{
    std::cout << add(1, 2);
}
```

I see a very nice tooltip when hovering with the mouse over `add`, as expected:

![image](https://user-images.githubusercontent.com/61846320/99910204-be1c5880-2cba-11eb-80cb-ceb248de5cf3.png)

However, if I add `using namespace std`:

```cpp
#include <iostream>

using namespace std;

/**
 * @brief Adds two numbers.
 *
 * @param a The first number to add.
 * @param b The second number to add.
 * @return The sum of the numbers.
 */
double add(const double &a, const double &b)
{
    return a + b;
}

int main()
{
    cout << add(1, 2);
}
```

Then the tooltip doesn't show anymore:

![image](https://user-images.githubusercontent.com/61846320/99910273-0e93b600-2cbb-11eb-95ca-95d924d9f33f.png)

Interestingly, this is fixed if I replace the Doxygen comments with `///` instead of `/**` format:

```cpp
#include <iostream>

using namespace std;

///
/// @brief Adds two numbers.
///
/// @param a The first number to add.
/// @param b The second number to add.
/// @return The sum of the numbers.
///
double add(const double &a, const double &b)
{
    return a + b;
}

int main()
{
    cout << add(1, 2);
}
```

![image](https://user-images.githubusercontent.com/61846320/99910322-47cc2600-2cbb-11eb-940c-ed4251c2668c.png)

So this seems to be a bug specific to Doxygen comments in the (very widely used) `/**` format.

This appears to happen with **any** `using` statement. For example, this will also not display the tooltip:

```cpp
#include <iostream>

using std::cin;

/**
 * @brief Adds two numbers.
 *
 * @param a The first number to add.
 * @param b The second number to add.
 * @return The sum of the numbers.
 */
double add(const double &a, const double &b)
{
    return a + b;
}

int main()
{
    std::cout << add(1, 2);
}
```

However, if I remove `#include <iostream>`, for example:

```cpp
using namespace std;

/**
 * @brief Adds two numbers.
 *
 * @param a The first number to add.
 * @param b The second number to add.
 * @return The sum of the numbers.
 */
double add(const double &a, const double &b)
{
    return a + b;
}

int main()
{
    add(1, 2);
}
```

Then the tooltip is displayed even though a `using` statement is invoked. So perhaps this has to do with `iostream` itself? However, this seems to be compiler-independent; I tested it with both `g++.exe` and `cl.exe` configured as the compiler (which means `iostream` is a different file in each case) and the issue occurred in both cases.

**Comment by sean-mcmanus** [comment] 2020-11-24 02:24
It becomes fixed after my cursor moves to a new line. Is that you're seeing?

![image](https://user-images.githubusercontent.com/19859882/100038004-12f1c900-2db8-11eb-96ec-c665e31882cb.png)

I think the issue is we need to invoke the cursor change update after a multiline paste.

**Comment by bshoshany** [comment] 2020-11-24 02:46
Weird, I checked now and it does indeed seem to work as intended after I simply move the cursor, but I could **swear** it didn't before 😮 Thanks for your quick response. At least it seems to be an easy bug to fix.

**Comment by sean-mcmanus** [comment] 2021-01-21 08:28
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2

**Closed as completed** 2021-02-03 00:45 UTC
Labels: bug, Language Service, fixed, quick fix, Feature: Doc comments, Works in VS
