### ISSUE TITLE
Comment lines without Doxygen tags is not parsed correctly

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5741] opened 2020-07-07 22:49 UTC
This is reported on Visual Studio at 
https://developercommunity.visualstudio.com/content/problem/1105383/comments-without-doxygen-tags-is-not-parsed-correc.html. Please upvote the Visual Studio feedback ticket to increase priority of issue as this feature is a shared API between Visual Studio C++ IntelliSense and the VS Code C++ extension.

**Sample code:**
```
/**
 * Hello there
 * blue sky.
 *
 * @return this is return note
 */
int test()
{
    return 0;
}
```
**Repro steps:**

- In a C++ source, use the sample code provided.
- Hover over the function `test()`.
- Tooltip display result: “Hello thereblue sky”
![image](https://user-images.githubusercontent.com/38734287/86852291-56e26c80-c069-11ea-9a51-cdaa9a0bb280.png)

**Expected result in tooltip display:**
“Hello there blue sky”

**Note:** 
This issue only occurs when the comment has Doxygen tags.

**Comment by cinderblock** [comment] 2021-04-03 00:14
When "Doxygen tags" are **not** used, is it also expected that single newlines get replaced with `<br />`?

![image](https://user-images.githubusercontent.com/419955/113069643-a9beff80-9175-11eb-8618-3845588a9f7a.png)

**Comment by michelleangela** [comment] 2021-04-07 03:39
@cinderblock 
The space after the function name in the tooltip is not a replacement of single newlines from the comment, but the space is there to format the function name and comments with a space between them.

Here's an example with a one line comment
![image](https://user-images.githubusercontent.com/38734287/113806891-01caa880-9718-11eb-9654-1ac656babb97.png)

**Comment by cinderblock** [comment] 2021-04-07 22:24
@michelleangela That's not what I'm referencing.

Do we not expect this to be displayed on one line?
```js
/**
 * one
 * line
 * or
 * not
 */
```

As in, do the HTML whitespace rules only apply when using `@` or `/` tags?

**Comment by Delgan** [comment] 2021-09-30 14:35
Hi!

Just another example: I'm often using `\brief` (or `@brief`, result is the same) then add a detailed description below (see [Doxygen manual](https://www.doxygen.nl/manual/docblocks.html)).

However, as soon as the `\brief` command is added, the newlines are removed from the tooltip which makes the documentation much less pleasant to read.


![Peek 2021-09-30 16-25](https://user-images.githubusercontent.com/4193924/135475249-6dd6121a-5555-424b-93e2-6192af5b5ed0.gif)

Without the `\brief` command Doxygen won't generate function summary in HTML.
Sadly, that means we can't have the best of both worlds.

**Comment by sean-mcmanus** [comment] 2021-11-30 18:44
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders (the missing newline becomes a space).

**Comment by austintraver** [comment] 2022-01-30 05:38
@sean-mcmanus : Confirmed 👏🏻  upgrading from `1.7.1` to the `1.8.0` insiders build fixed this issue for me.

**Closed as completed** 2022-02-01 20:39 UTC
Labels: Language Service, fixed, Visual Studio, Feature: Doc comments

**Comment by sean-mcmanus** [comment] 2022-10-21 01:12
Did/can anyone file a feature request on VS to turn the space into a newline? They resolved the reported "bug" as "not a bug": https://developercommunity.visualstudio.com/t/Tooltips-are-not-showing-doxygen-comment/10087897
