### ISSUE TITLE
The breakpoint is created at the same time when I click "Click to revert change" arrow button!

### ISSUE THREAD

**Issue by laplacedoge** [microsoft/vscode-cpptools#11127] opened 2023-06-24 08:32 UTC
### Environment

- OS and version: Windows 11 Pro 22H2
- VS Code: 1.78.2 (system setup)
- C/C++ extension: v1.16.3
- OS and version of remote machine (if applicable): Ubuntu Server 22.04.2 LTS

### Bug Summary and Steps to Reproduce

Bug Summary:
The breakpoint is created at the same time when I click "Click to revert change" arrow button!
Zoom the following GIF in to have a better viewing experience.

Steps to reproduce:
![bandicam 2023-06-24 16-12-05-190](https://github.com/microsoft/vscode-cpptools/assets/53377854/94b89c07-7324-4087-bc58-9357173f4452)

### Debugger Configurations

```shell
None
```

### Debugger Logs

```shell
None
```

**Comment by sean-mcmanus** [comment] 2023-06-24 09:10
This is a duplicate of https://github.com/microsoft/vscode/issues/114776. It sounds like it's fixed in VS Code Insiders.

**Closed as not planned by sean-mcmanus** 2023-06-24 09:10 UTC
Labels: duplicate, external
