### ISSUE TITLE
identifier "size_t" is undefined, with clang 18

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#12618] opened 2024-08-23 01:30 UTC
With clang 18(.1.3), I'm seeing an issue with size_t, which doesn't repro with earlier versions of clang. (15-17).

The issue likely has something to do with how the clang-18 headers decide whether or not to define size_t.  Some IntelliSense predefines may be confusing it, making it think size_t is already defined.

![image](https://github.com/user-attachments/assets/df8c38e7-d1ff-47ae-b3f2-dbaeccd5352d)

**Comment by sfan5** [comment] 2024-08-29 13:45
Can confirm this with Clang 18.1.8 and vscode-cpptools 1.22.0 on Linux x64.
I have the settings automatically detected from `compile_commands.json`, which always used to work fine.

**Comment by browntarik** [comment] 2024-09-16 19:23
I have file a bug with the internal VS (2253203) Team. As this is most likely the cause of https://github.com/microsoft/vscode-cpptools/issues/12319, that bug will be put on the back burner until this has been resolved.

**Comment by bobbrow** [comment] 2024-09-18 21:03
A workaround is to add this to your defines in `c_cpp_properties.json`:
```json
    "defines": [
        "__building_module(x)=0"
    ]
```
I don't know that we have an easy way to inject that in the `compile_commands.json` case, but someone else on the team may have an idea.

**Comment by sean-mcmanus** [comment] 2024-09-20 10:18
@sfan5 Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.22.4 .

**Closed as completed by sean-mcmanus** 2024-09-20 10:18 UTC
Labels: bug, Language Service, fixed, Visual Studio
