### ISSUE TITLE
F12  Go to Definition is not searching

### ISSUE THREAD

**Issue by thkrishn** [microsoft/vscode-cpptools#4756] opened 2019-12-17 18:30 UTC
![image](https://user-images.githubusercontent.com/7133450/71023192-0ef0fd80-20b7-11ea-8a77-5bcd5634970e.png)

I am not sure if its a Language service or the editor bug -- so here is the other bug I raised 
https://github.com/microsoft/vscode/issues/87112

Steps to Reproduce:
1. On the variables if I use F12, it does not go to definition; I have tried the `Go > Go To Definition` from the menu as well; it does not start a search I dont see a bar which indicates its searching)
2. I have re installed VS code twice; removed all extensions and tried it nothing seems to work
But on a similar setup I have I see no issues on Code Insiders

- VS Code Version:
Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 0.26.2
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them): I have tried disabling other extensions and tried it as well 

- A clear and concise description of what the bug is.
F12 should go to definition; I usually see a search in progress at the top of the editor; in this case I dont see a search being started as well 
 

**To Reproduce**
Start VS code
1. Go to a variable a chose  `Go > Go To Definition` 
2. it does not go to definition 

**Expected behavior**
`Go to Definition`  where the variable was defined or jump to where the class is defined 

**Screenshots**

**Comment by thkrishn** [comment] 2019-12-18 21:54
The Go to Definition is not preset when I do a mouse right click on the variable
![no_go_to](https://user-images.githubusercontent.com/7133450/71126436-d9730f80-219d-11ea-9c50-0d94b70d42bb.png)


here is a screen shot from another machine where F12 is working
![go_to](https://user-images.githubusercontent.com/7133450/71126445-ded05a00-219d-11ea-8f1b-b645d486b629.jpg)

**Comment by sean-mcmanus** [comment] 2019-12-19 00:36
It looks like our extension isn't activating. Can you check the Help->Toggle Developer Tools->Console for error messages?

**Comment by thkrishn** [comment] 2019-12-19 00:40
This is what it looks like 
![image](https://user-images.githubusercontent.com/7133450/71134995-22828e00-21b5-11ea-97e2-44f1eb8ea118.png)

**Comment by sean-mcmanus** [comment] 2019-12-19 00:42
From the comments in the VS Code issue, it looks like you're failing to download the OS binaries. You should follow the instructions and install the offline vsix manually as a workaround. After we release 0.26.3-insiders2, you could also set the C_Cpp.updateChannel to "Insiders" and it should work (until we release a non-Insiders update).

**Comment by sean-mcmanus** [comment] 2019-12-19 00:43
When VS Code marketplace allows us to publish per-OS vsix's then, this issue would also be fixed. My guess is that some http proxy settings are preventing you from downloading the OS binaries.

**Comment by thkrishn** [comment] 2019-12-19 01:18
> you could also set the C_Cpp.updateChannel to "Insiders"

do I do this in the settings.json?

**Comment by thkrishn** [comment] 2019-12-19 01:23
Should I remove the old cpp tools?

```
Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at /home/tejas.krishna/.vscode-server/extensions/ms-vscode.cpptools-0.26.2/bin/Microsoft.VSCode.CPP.Extension.linux
```

**Comment by sean-mcmanus** [comment] 2019-12-19 02:09
Yes, C_Cpp.updateChannel is in settings.json, but there is no insiders published yet.

I'm not sure if uninstalling the previous vsix is required or not, but it wouldn't hurt.

**Comment by thkrishn** [comment] 2019-12-19 06:23
```
Downloading package 'C/C++ language components (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'ClangFormat (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Mono Framework Assemblies'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Mono Runtime (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Installing package 'C/C++ language components (Linux / x86_64)'
Failed at stage: installPackages
Error: end of central directory record signature not found
```
1. in the Retry is it saying its done Retrying or done Download? 
2. and it says it failed to installPackage

**Comment by thkrishn** [comment] 2019-12-19 19:17
So I saw your `0.26.3-insiders2` release and  installed it after the install I got this message
```
Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at /home/thkrishn/.vscode-server/extensions/ms-vscode.cpptools-0.26.3-insiders2/bin/Microsoft.VSCode.CPP.Extension.linux
```
Which looks like this issue 
https://github.com/cdr/code-server/issues/1190

**Comment by thkrishn** [comment] 2019-12-19 23:18
So this is how I fixed this --  I connect from a Win 10 machine to a Ubuntu 16.04
I did an `Install from VSIX` but since my code is residing on a linux machine I had to install `cpptools-linux.vsix` 

Will it eventually be able to able to figure out the requirement?

**Comment by sean-mcmanus** [comment] 2019-12-21 00:56
@thkrishn We fixed this bug with 0.26.3-insiders2: https://github.com/microsoft/vscode-cpptools/issues/3874 . That bug would cause our auto-install of the insiders vsix to fall in the remote scenario, so the next insiders we release might also fix the issue you are seeing.

**Comment by bobbrow** [comment] 2020-01-10 19:09
@thkrishn I see you linked a code-server issue.  Are you using code-server or VS Code?  Our extension is not licensed to run in code-server.

**Comment by thkrishn** [comment] 2020-01-10 20:03
I am using VS-code; 
When i searched for the error message i found the "cdr/code-server#" issue 
I only made a comment because the Error message was a match

**Comment by bobbrow** [comment] 2020-01-15 17:54
Got it.  Thanks.  Are we able to add the "fixed (release pending)" tag to this issue @sean-mcmanus or is this a duplicate of the other "insiders won't install in remote" issue?

**Comment by sean-mcmanus** [comment] 2020-01-15 19:40
@bobbrow The issue morphed into the fixed issue. The originally issue is missing binaries, which doesn't have a resolution, other than it will be fixed when the have platform a specific marketplace.

**Comment by bobbrow** [comment] 2020-01-16 03:23
Then should we close this as a duplicate?

**Comment by sean-mcmanus** [comment] 2020-01-16 03:28
Yeah, I marked it as a duplicate a month ago, but left it open still.

**Closed as completed by sean-mcmanus** 2020-01-16 03:28 UTC
Labels: duplicate, Language Service
