### ISSUE TITLE
codeblock is gray even case is true

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#12664] opened 2024-08-30 06:27 UTC
### Environment

- C/C++ Extension Version: 1.22.2

![image](https://github.com/user-attachments/assets/ae83ab75-ab5a-47a9-a391-b3e92eb1f969)

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
1
```

**Comment by sean-mcmanus** [comment] 2024-08-30 10:58
@heartacker Is the 1st condition on the left of the `&&` also true?

**Comment by sean-mcmanus** [comment] 2024-08-30 16:58
@heartacker I've reproed the issue -- it repros with C and not C++. It's a duplicate of https://github.com/microsoft/vscode-cpptools/issues/11959, which is currently in a "Closed due to low priority" in the VS database, but we could potentially re-open it if it gets more upvotes or if our priorities change.

**Closed as not planned by sean-mcmanus** 2024-08-30 16:58 UTC
Labels: bug, duplicate, Language Service, more info needed
