### ISSUE TITLE
output tab steals focus from terminal tab, regression

### ISSUE THREAD

**Issue by rcsmith00** [microsoft/vscode-cpptools#6325] opened 2020-10-15 20:07 UTC
Issue Type: <b>Bug</b>

With the latest insiders version, I'm constantly getting this error when I open different files.

filename.c not found in "...  compile_commands.json" . 'includePath' from c_cpp_properties.json in folder '...' will be used for this file instead.

I typically use the terminal tab.  when these errors occurs it automatically switches to the output tab.   Have not seen this before this update.  Have tried disabling output tab, but it keeps returning.  

Extension version: 1.1.0-insiders
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042

**Comment by sean-mcmanus** [comment] 2020-10-15 20:18
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/6308

**Comment by Colengms** [comment] 2020-10-15 21:46
Closing as dupe.

**Comment by sean-mcmanus** [comment] 2020-10-16 03:00
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.0-insiders2 (the Configuration Warnings should only appear once per session).

**Closed as completed by sean-mcmanus** 2020-10-16 03:00 UTC
Labels: bug, Language Service, fixed
