### ISSUE TITLE
Go to definition not working

### ISSUE THREAD

**Issue by khou2020** [microsoft/vscode-cpptools#2368] opened 2018-08-07 19:20 UTC
Go to definition always shows "No definition found for ..." even when I click right on the variable declaration itself.

**Comment by sean-mcmanus** [comment] 2018-08-07 21:45
We need more info -- can you provide your c_cpp_properties.json and/or set your C_Cpp.loggingLevel to debug and provide the output in the C/C++ window after opening a workspace? You could also try our 0.17.8-insiders release which has many bug fixes: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.8-insiders .

Also, Go to Definition doesn't work on local variables and isn't powered by the "IntelliSense" engine, so its results are "fuzzy", see https://github.com/Microsoft/vscode-cpptools/issues/255 .

**Comment by powertomato** [comment] 2018-09-24 10:33
I ran into this issue about a week ago, after it was working previously. The log revealed thousands of 
`"Unable to add file to database, error = 0x8064000a: /usr/include/..."` errors.
Killing all extension processes and rebooting the machine didn't help.

I found #2296. The suggestion there is to add `"databaseFilename": "${workspaceFolder}/.vscode/vc.db"` to c_cpp_properties.json

I cannot confirm the cause beeing dangling processes, as there were none, and it also happened after a fresh reboot. I could check if something else is locking the file, as I can reliably reproduce the behavior, by removing `databaseFilename` from the config. However I don't know the default location for the files.

The explicit `databaseFilename` seemingly fixes it:
There are no errors in the C/C++ log output and now there is a database- and the red flame icon in the status bar. Tool-tips for those two are "Parsing Files 37/1737 2%" respectively "Updating Intellisense". This process is terribly slow, with one file being parsed in about 10 minutes. CPU load of the extension processes is at 0%, memory usage at 170MB for `Microsoft.VSCode.CPP.IntelliSense.Msvc.linux` and 90MB for `Microsoft.VSCode.CPP.Extension.linux`

I tried restarting several times, but the parsing was still slow. After I added `"C_Cpp.intelliSenseEngineFallback": "Enabled"` to settings.json, it finished in under a minute. 
That might have been a coincidence, however. IntelliSense now works as expected, even after I set it to `"Disabled"` and reboot the machine. 

The extension version is 0.18.1, VScode version 1.25.1
My current c_cpp_properties.json:

    {
        "configurations": [
            {
                "name": "Linux",
                "browse": {
                    "path": [
                        "${workspaceFolder}/src"
                    ],
                    "limitSymbolsToIncludedHeaders": true,
                    "databaseFilename": "${workspaceFolder}/.vscode/vc.db"
                },
                "includePath": [
                    "${workspaceFolder}/src",
                    "${workspaceFolder}/build/src",
                    "/usr/include",
                    "/usr/local/include"
                ],
                "defines": [],
                "compilerPath": "/usr/bin/g++",
                "cStandard": "c11",
                "cppStandard": "c++11",
                "intelliSenseMode": "gcc-x64"
            }
        ],
        "version": 4
    }

**Comment by bobbrow** [comment] 2018-09-26 22:59
@powertomato it sounds like the DB at the default location was corrupted.  If you remove `databaseFilename` and then run the `"C/Cpp: Reset IntelliSense Database"` command, it should delete the old, corrupted one and replace it with a new one.

For the slow parsing issue, you might want to open a new issue since this one is about goto definition.

**Comment by powertomato** [comment] 2018-09-27 09:04
@bobbrow I should have mentioned I tried executing `"C/Cpp: Reset IntelliSense Database"` but nothing changed. That's why I asked for the default db location, so I could check if something is preventing from writing to that location.

**Comment by sean-mcmanus** [comment] 2018-09-27 18:38
@powertomato Your c_cpp_properties.json has the datatabase location set to ${workspaceFolder}/.vscode/vc.db , so I don't know why you want the default db location . One other possibility is that there is a dangling Microsoft.VSCode.CPP.Extension process that has a lock on the database, so it needs to be killed. This could also be some new issue we're not aware of yet. A user at https://github.com/Microsoft/vscode-cpptools/issues/756#issuecomment-424982456 also had a database issue.

**Comment by powertomato** [comment] 2018-09-28 11:59
@sean-mcmanus As I wrote in my first comment I can only replicate this bug with the default db, if I change it, like in my c_cpp_properties.json, it works, as far as I'm concerned, I'm fine with that workaround.

However you have tagged this with "more info needed" and I'm just trying to provide as much info as I can.
With the default db even `"C/Cpp: Reset IntelliSense Database"` wont fix it, implying either that task doesn't work or something could locking the default db location. I could investigate that.

**Comment by sean-mcmanus** [comment] 2018-09-28 18:08
@powertomato Okay, I missed that detail -- the default db location is under a hashid folder in ~/.config/Code/User/workspaceStorage, so you can manually delete that entire folder (and VS Code will re-create it when we request a new default db). The Reset command is supposed to show a success/failure message...I assume it shows the success message, but still doesn't fix the issue.

**Comment by michelleangela** [comment] 2019-07-03 23:06
Closing this issue. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate your issue.

**Closed as completed by michelleangela** 2019-07-03 23:06 UTC
Labels: Language Service, more info needed, not reproing
