### ISSUE TITLE
Debug does not stop at the break points.

### ISSUE THREAD

**Issue by wangzhen11aaa** [microsoft/vscode-cpptools#4572] opened 2019-11-08 11:43 UTC
Type: Debugger
lldb

**Describe the bug**
- OS and Version: Mac Catalina
- VS Code Version: 1.40
- C/C++ Extension Version: clang 11
- Other extensions you installed (and if the issue persists after disabling them):

1. launch.json

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Hello world",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/test_cmake/helloworld/build/hello_world",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "setupCommands": [
            {
                "description": "Enable pretty-printing for gdb",
                "text": "-enable-pretty-printing",
                "ignoreFailures": true
            }
            ]
        }
    ]
}

2.  code:
#include <iostream>
using namespace std;

int main(int parameter_size, char ** parameter)
{
    int a = 1 + 3;
    int b = a + 3;
    cout << "hello word  " << parameter_size << "   " << endl;
    return 0;
}

3. CMakeLists.txt
project(hello_world)
    aux_source_directory(. DIR_TOOT_SRCS)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g")
    add_executable(hello_world ${DIR_TOOT_SRCS})

Debug does not stop.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by wangzhen11aaa** [comment] 2019-11-08 17:25
Use lldb command, we can debug this file and add breaking point.

The following is parts of my code.
  cout << "\n gquiz.size() : " << gquiz.size() << endl;
  cout << "\n gquiz.top() : " << gquiz.top() << endl;
  cout << "\n gquiz.pop() ";
  gquiz.pop();

setting mode 1:
In vscode, whith these configuration.
1.
            "name": "(lldb) Launch cunit",
			"type": "cppdbg",
			"request": "launch",
			"program": "${workspaceRoot}/test_priority_queue",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceRoot}",
			"environment": [],
			"externalConsole": true,
			//"preLaunchTask": "build cunit",
			"MIMode": "lldb"
The program '/Users/wangzhen/ClionProjects/cpp/test/test_priority_queue' has exited with code 0 (0x00000000). It does not print ant information.

setting mode 2:
            "type": "lldb-mi",
            "request": "launch",
            "name": "Launch Program",
            "target": "test_priority_queue",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText"
The program  print result without stopping at the breaking point.
 gquiz.size() : 4

 gquiz.top() : 30

 gquiz.pop() After pop()

**Comment by pieandcakes** [comment] 2019-11-09 00:09
This is a known issue.
Duplicate of: https://github.com/microsoft/vscode-cpptools/issues/3829

**Closed as completed by pieandcakes** 2019-11-09 00:09 UTC
Labels: duplicate, debugger
