### ISSUE TITLE
Support for clang-tidy

### ISSUE THREAD

**Issue by Bascy** [microsoft/vscode-cpptools#7936] opened 2021-08-07 13:43 UTC
Type: Feature Request

It would be really neat if this extension would also support the use of clang-tidy to include hints on improvements and code-smells.
From my experience in IntelliJ coding in Java, I know I learned a lot from all the suggestions it makes while writing the code (and the quick fix system is awsome in IntelliJ)

**Comment by Colengms** [comment] 2021-08-09 17:14
Hi @Bascy .  This looks like a duplicate of https://github.com/microsoft/vscode-cpptools/issues/2908 
Closing as a duplicate.

**Closed as completed by Colengms** 2021-08-09 17:14 UTC
