### ISSUE TITLE
Remote debugging with GDB: "An item with the same key has already been added."

### ISSUE THREAD

**Issue by michaelkourlas** [microsoft/vscode-cpptools#2099] opened 2018-06-07 20:54 UTC
Type: Debugger

When attempting to use remote debugging with GDB using the "miDebuggerServerAddress" option, the following error message is displayed:

"Unable to start debugging. An item with the same key has already been added."

- OS and Version: Fedora 28 (x64)
- VS Code Version: 1.23.1
- C/C++ Extension Version: 0.17.4
- Other extensions you installed (and if the issue persists after disabling them): Better TOML, Mustache, Python, Rust (rls), SVN, Trailing Spaces

**To Reproduce**

Attempt to start debugging using the following configuration:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/path/to/local/copy/of/binary",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerServerAddress": "1.2.3.4:5678",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

**Additional context**

The text "waiting for v8 protocol on stdin/stdout" appears in the Extensions log.

**Comment by pieandcakes** [comment] 2018-06-08 01:07
Can you check your local environment variables and see if you have a duplicate variable that has different casing? This is a problem inside Mono framework.

**Comment by pieandcakes** [comment] 2018-06-08 01:09
Duplicate of #2056

**Closed as completed** 2018-06-11 21:53 UTC
Labels: duplicate, debugger
