### ISSUE TITLE
Garbage 0 byte file gets created if vscode-cpptools are installed. 

### ISSUE THREAD

**Issue by sungb** [microsoft/vscode-cpptools#573] opened 2017-03-16 07:21 UTC
**Environment:** 
xubuntu 32bit 14.04 running under VMWare
stable release code, and vscode-cpptools

**Steps to reproduce**
1. run from the cli `code tst.c` 

**Result**
creates a empty garbage file in the directory it's opened.

**Expect**
do not leave any garbage files in the user's working directory.

**Reference**
Please refer to the issue below.
https://github.com/Microsoft/vscode/issues/15335

**Comment by sean-mcmanus** [comment] 2017-03-16 13:49
This is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/217 . We're still trying to find a repro. What locale or internationalization settings are you using? The language service part of our extension doesn't work on 32-bit Linux. Are you using the debugger?

**Closed as completed by sean-mcmanus** 2017-03-16 13:49 UTC
Labels: duplicate
