### ISSUE TITLE
Return type listed along with function name in Outline view

### ISSUE THREAD

**Issue by lijh8** [microsoft/vscode-cpptools#4440] opened 2019-10-16 05:09 UTC
![66886647-ab8d1580-f00a-11e9-90b9-2aa93ff0ea5d](https://user-images.githubusercontent.com/9011764/66889721-1001a200-f016-11e9-802c-41abe638419f.png)

- C/C++ Extension Version: 
Id: ms-vscode.cpptools
Version: 0.26.0

**Comment by sean-mcmanus** [comment] 2019-10-17 20:42
This appears to be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4383 .

**Comment by bobbrow** [comment] 2020-02-20 22:58
Closing duplicate issue.

**Closed as completed by bobbrow** 2020-02-20 22:58 UTC
Labels: duplicate, Language Service, Visual Studio
