### ISSUE TITLE
override keyword not highlighted if follwed by '= default'

### ISSUE THREAD

**Issue by EloCode** [microsoft/vscode-cpptools#9757] opened 2022-08-19 16:37 UTC
### Environment

Version: 1.70.2 (user setup)
OS: Windows_NT x64 10.0.19043
Extension: C/C++ v1.11.5

### Bug Summary and Steps to Reproduce

```
class Base {
    virtual ~Base() = default;
}

class Derived:Base {
    ~Derived() override = default;
}
```
override keyword remains white (not highlighted. If ```= default``` is removed, highlighting works again.

### Expected behavior

override keyword highlighted in even if followed by ```= default```

### Code sample and Logs

```shell
c_cpp_properties.json does not exist
```

### Screenshots

<img width="167" alt="tmp" src="https://user-images.githubusercontent.com/52861757/185666677-6c90613f-4873-4036-8b02-2345ba7ebc1f.PNG">

### Additional context

_No response

_

**Comment by michelleangela** [comment] 2022-08-19 18:20
@EloCode 
The C/C++ extension provides semantic tokens. Colorization of syntactic/lexical tokens come from VS Code itself and the TextMate grammar that it uses. The TextMate grammar for C/C++ is contributed to VS Code from this repo: https://github.com/jeff-hykin/better-cpp-syntax.

This issue reproduces without C/C++ extension. Also, when running the command `Developer: Inspect Editor Tokens and Scopes` and clicking on the "override" token, it has no info regarding "semantic tokens", so the issue is not caused by C/C++ extension.

![image](https://user-images.githubusercontent.com/38734287/185682459-9d90df71-5b96-4e53-8ec0-f6f6cfe1143a.png)

I suggest filing this issue at https://github.com/jeff-hykin/better-cpp-syntax.

**Comment by michelleangela** [comment] 2022-08-19 18:21
Closing this issue as external.

**Closed as completed by michelleangela** 2022-08-19 18:21 UTC
Labels: external, Feature: Colorization
