### ISSUE TITLE
Intellisense reports `cannot call non-constexpr function "round"`

### ISSUE THREAD

**Issue by RyanBerge** [microsoft/vscode-cpptools#10646] opened 2023-03-08 20:53 UTC
### Environment

- OS and Version: Windows 10 Pro 22H2
- VS Code Version: 1.76.0
- C/C++ Extension Version: 1.14.4
- If using SSH remote, specify OS of remote machine: WSL Ubuntu-18.04

### Bug Summary and Steps to Reproduce

Bug Summary: Intellisense reports `cannot call non-constexpr function "round"` on code that compiles fine.

Steps to reproduce:
1. Create a cpp file with the code:
``` #include <cmath>
#include <iostream>

int main()
{
    constexpr int a = std::round(15.17 * 57.93);
    std::cout << a << std::endl;
}
```
2. Compiling with g++ produces no warnings or errors and running the program gives the correct result (879) but Intellisense reports:

``` expression must have a constant value
main.cpp(6, 23): cannot call non-constexpr function "round" (declared at line 298 of "/usr/include/x86_64-linux-gnu/bits/mathcalls.h")
```

Expected behavior: No Intellisense error

### Configuration and Logs

```shell
-------- Diagnostics - 3/8/2023, 12:48:25 PM
Version: 1.14.4
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/ryan/Testing/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/g++",
    "cStandard": "gnu11",
    "cppStandard": "gnu++20",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/ryan/Testing/main.cpp ]:
    /home/ryan/Testing/main.cpp
Translation Unit Configurations:
[ /home/ryan/Testing/main.cpp ]:
    Process ID: 12023
    Memory Usage: 107 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=70500
Total Memory Usage: 107 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 2449
```

**Comment by Colengms** [comment] 2023-03-08 23:14
Hi @RyanBerge .  I believe this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4736 .  Because this is an issue in our IntelliSense engine that is shared with VS, it was also filed here: https://developercommunity.visualstudio.com/content/problem/854941/intellisense-shows-squiggle-for-use-of-gcc-compile.html . Unfortunately, few people were impacted and upvoted, and the issue was de-prioritized.  I'd suggest up-voting https://github.com/microsoft/vscode-cpptools/issues/4736 as well as commenting on the closed VS issue, asking for it to be revisited.  Customer responses to de-prioritized issues often get them revisited.

**Closed as not planned** 2023-03-08 23:15 UTC
