### ISSUE TITLE
Go to definition doesn't work for operators (e.g. <<).

### ISSUE THREAD

**Issue by yay** [microsoft/vscode-cpptools#979] opened 2017-08-18 21:39 UTC
- VSCode Version: 1.15.1
- OS Version: macOS 10.12.6 (16G29)
- Apple LLVM version 8.1.0 (clang-802.0.42)
- gcc-7 (Homebrew GCC 7.2.0) 7.2.0

<img width="579" alt="screen shot 2017-08-18 at 23 15 01" src="https://user-images.githubusercontent.com/1799756/29478674-55e8bbfc-846e-11e7-9070-e108ace91def.png">

On the above screenshot, if I ⌘-hover `endl`, it will get an underline and, upon clicking, open a file/line it is defined in. This is not the case when the `<<` operator is hovered. If won't get an underline, correctly suggesting that jumping to the definition is impossible, despite the fact the plugin knows the operator has been overloaded in several places.

Steps to Reproduce:

1. Use my code `¯\_(ツ)_/¯`:
```
#include <iostream>

using namespace std;

int main()
{
    cout << "Hello, World!" << endl;
    return 0;
}
```
2. ⌘-click `<<`.
3. Nothing happens.

Expected behavior:

Jump to the file/line where the particular instance of `<<` being used here is defined.
Or at least pop up a list that will allow the user to select the declaration to jump to, much like what is requested here: https://github.com/Microsoft/vscode/issues/31046

**Comment by bobbrow** [comment] 2017-08-18 22:18
While it is a bit non-intuitive, this is currently how we expect it to behave.  Goto definition is still implemented using the old IntelliSense engine which has no knowledge of this operator overload, while the hover tooltips are implemented with the new IntelliSense engine which does.

Migrating Goto Definition to the new IntelliSense engine is something we still plan to do.  We are tracking this feature with issue #255 which has the same root cause.

**Comment by sean-mcmanus** [comment] 2018-09-21 01:10
This will be fixed in the next release as long as the operators definition/declaration is the same TU (and IntelliSense is enabled), which is the case for iostream <<. If the definition is in a different source file, that is being tracked by https://github.com/Microsoft/vscode-cpptools/issues/2536 .

**Comment by sean-mcmanus** [comment] 2018-09-28 01:12
Go to Definition on overloaded operators works with the "Default" intelliSenseEngine with 0.19.0 -- but only if the definition exists in the current translation unit, which is the case for the iostream << operator in your example. We're tracking the "not in the TU" case with https://github.com/Microsoft/vscode-cpptools/issues/2536 .

Also, for cases like "int1+int2" (with no space surrounding the operator) you will need to select the "+" before using Go to Definition on +, which mimics the token selection behavior of Visual Studio 2017.

**Closed as completed by sean-mcmanus** 2018-09-28 01:12 UTC
Labels: Language Service, Feature Request, fixed
