### ISSUE TITLE
Unable to set a breakpoints in non .c/.cpp files

### ISSUE THREAD

**Issue by SvenJo** [microsoft/vscode-cpptools#440] opened 2017-01-10 19:12 UTC
The source code for my program is generated from .re file with the help of re2c and full of #line pragmas.
If I want to debug this program, I have to set the breakpoints for gdb in the .re file.
But Visual Studio Code don't allow me to set breakpoints that file. So the debugger simply don't stop!

1. Please let me set breakpoints in files with all extensions.
2. Please let me start the debugger in main(). (You can do the same in Visual Studio by starting the debugger with F10)

Example from the re2c source:
[calc_002.re.txt](https://github.com/Microsoft/vscode-cpptools/files/697089/calc_002.re.txt)
[calc_002.c.txt](https://github.com/Microsoft/vscode-cpptools/files/697093/calc_002.c.txt) generated with "re2c calc_002.re > calc_002.c"

Remove the .txt from the files.
gcc -g calc_002.c
gdb a.out
-> debugging calc_002.re

**Comment by KytoDragon** [comment] 2017-04-07 21:17
This feature is already in VS Code.
Got to File -> Preferences -> Settings -> Debug ->debug.allowBreakpointsEverywhere = true

**Comment by pieandcakes** [comment] 2020-03-03 17:37
Duplicate of #75

**Closed as completed** 2020-03-03 17:37 UTC
Labels: debugger, Feature Request
