### ISSUE TITLE
Intellisense Tooltip and C/C++ Warning showing Windows OS language instead of VSCode Display Language.

### ISSUE THREAD

**Issue by jasonyang-ee** [microsoft/vscode-cpptools#10632] opened 2023-03-04 08:58 UTC
### Environment

- OS and Version: Windows 10 x64 (Chinese Traditional)
- VS Code Version: 1.76.0
- C/C++ Extension Version: 1.14.4
- If using SSH remote, specify OS of remote machine: 

So here is the list of issue ever being reported:
https://github.com/microsoft/vscode/issues/82791
https://github.com/microsoft/vscode-cpptools/issues/4450
https://github.com/microsoft/vscode/issues/84883
https://github.com/microsoft/vscode-cpptools/issues/9929
https://github.com/microsoft/vscode-cpptools/issues/4442
.. Could be more, but, you get the idea.

Some was able to fix this by reloading `Display Language` in some magical sequence.
Some was able to fix it by editing `user\.vscode\argv.json` to have `"locale": "en"`
Some was able to fix it by adding a `locale.json` file in VS Code `\Code\User` folder with `"locale": "en"` [ref link](https://stackoverflow.com/questions/36868322/how-to-change-ui-language-in-visual-studio-code)

None of those worked for me.
It seems to be an issue with `VSCODE_NLS_CONFIG` being used
https://github.com/microsoft/vscode/issues/78392

The response from VS Code team is that `VSCODE_NLS_CONFIG` [should never be used](https://github.com/microsoft/vscode/issues/78392).

`vscode-nls-dev` should be used instead.

Even if we want to continue using `VSCODE_NLS_CONFIG`. We should parse it differently `nls.config(process.env.VSCODE_NLS_CONFIG)` as recommended here: https://github.com/microsoft/vscode/issues/23427

Currently I have tested on my local machine for those changes:
If I change display language pack into 3rd language (Japanese). VS Code UI and cpptool both be Japanese.
If I change display language pack into OS language (Chinese).  VS Code UI and cpptool both be Chinese.
If I change display language pack into English.  VS Code UI be English but cpptool be Chinese.
If I change `main.js` to use `nls.config(process.env.VSCODE_NLS_CONFIG)`. cpptool stays in English no matter of display language.
If I change options.language = 'ja' or 'en'. It will force the cpptool to stay in the 'ja' or 'en'. (code in below)

Line: 76474
```javascript
function initializeSettings() {
    options = { locale: undefined, language: undefined, languagePackSupport: false, cacheLanguageResolution: false, messageFormat: common_1.MessageFormat.bundle };
    if (isString(process.env.VSCODE_NLS_CONFIG)) {
        try {
            //var vscodeOptions_1 = nls.config(process.env.VSCODE_NLS_CONFIG);  // was var vscodeOptions_1 = JSON.parse(process.env.VSCODE_NLS_CONFIG);
			var vscodeOptions_1 = JSON.parse(process.env.VSCODE_NLS_CONFIG);
            var language = void 0;
            if (vscodeOptions_1.availableLanguages) {
                var value = vscodeOptions_1.availableLanguages['*'];
                if (isString(value)) {
                    language = value;
                }
            }
            if (isString(vscodeOptions_1.locale)) {
                options.locale = vscodeOptions_1.locale;
            }
            if (language === undefined) {
                options.language = 'en';
            }
            else if (language !== 'en') {
                options.language = language;
            }
```

Line: 47565
```javascript
exports.getLocalizedString = getLocalizedString;
function getLocaleId() {
    if (typeof process.env.VSCODE_NLS_CONFIG === 'string') {
        var vscodeOptions = JSON.parse(process.env.VSCODE_NLS_CONFIG);  // was const vscodeOptions = JSON.parse(process.env.VSCODE_NLS_CONFIG);
        if (vscodeOptions.availableLanguages) {
            const value = vscodeOptions.availableLanguages['*'];
            if (typeof value === 'string') {
                return value;
            }
        }
        if (typeof vscodeOptions.locale === 'string') {
            return 'en';
        }
    }
    return "en";
}
```

After all, I have concluded that it is a cpptool issue. Maybe it is some weird parsing causing this difficulty. But when I download and install a 3rd language pack, cpptool is well able to display this 3rd language.

I don't have sufficient knowledge on javascript to further debut this. I will need some help here.

Thank you.

![%23wy-025](https://user-images.githubusercontent.com/2824261/222886546-e11223aa-dcec-4b50-b1c8-3609e4bb699a.png)
![%23wy-026](https://user-images.githubusercontent.com/2824261/222886547-ccffd2df-3a71-4ed1-80de-1aa9be37c8b6.png)

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. Use an Windows OS that has language other than 'en'
2. Download VS Code from .com English website
3. Install and set display language to be English (this is actually default straight after installation).
4. cpptool warning and config UI both showing OS language only when argv.json has locale: "en" setting.

Expected behavior: cpptool should use argv.json setting

### Configuration and Logs

```shell
-------- Diagnostics - 3/4/2023, 12:57:05 AM
Version: 1.14.4
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.16299.0",
    "compilerPath": "cl.exe",
    "compileCommands": "${workspaceFolder}/build/Debug/compile_commands.json",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "intelliSenseModeIsExplicit": false
}
Custom browse configuration: 
{
    "browsePath": [
        "f:/devmcu/project/stm32-cli/core/inc",
        "f:/devmcu/project/stm32-cli/drivers/stm32l4xx_hal_driver/inc",
        "f:/devmcu/project/stm32-cli/drivers/stm32l4xx_hal_driver/inc/legacy",
        "f:/devmcu/project/stm32-cli/drivers/cmsis/device/st/stm32l4xx/include",
        "f:/devmcu/project/stm32-cli/drivers/cmsis/include",
        "f:/devmcu/project/stm32-cli/core/src",
        "f:/devmcu/project/stm32-cli/drivers/stm32l4xx_hal_driver/src",
        "f:/devmcu/project/stm32-cli/core"
    ],
    "compilerPath": "f:/devmcu/toolchain/arm-gnu-toolchain-12.2.mpacbti-bet1-mingw-w64-i686-arm-none-eabi/bin/arm-none-eabi-g++.exe",
    "compilerArgs": [],
    "compilerFragments": [
        "-g",
        "-mthumb",
        "-mcpu=cortex-m4",
        "-mfpu=fpv4-sp-d16",
        "-mfloat-abi=hard",
        "-Wall",
        "-Wpedantic",
        "-Wno-unused-parameter",
        "-Og",
        "-g3",
        "-ggdb",
        "-std=gnu++17"
    ]
}
Custom configurations:
[ F:\DevMCU\Project\STM32-CLI\Core\Src\main.cpp ]
{
    "includePath": [
        "f:/devmcu/project/stm32-cli/core/inc",
        "f:/devmcu/project/stm32-cli/drivers/stm32l4xx_hal_driver/inc",
        "f:/devmcu/project/stm32-cli/drivers/stm32l4xx_hal_driver/inc/legacy",
        "f:/devmcu/project/stm32-cli/drivers/cmsis/device/st/stm32l4xx/include",
        "f:/devmcu/project/stm32-cli/drivers/cmsis/include"
    ],
    "defines": [
        "DEBUG",
        "STM32L432xx",
        "USE_HAL_DRIVER"
    ],
    "compilerPath": "f:/devmcu/toolchain/arm-gnu-toolchain-12.2.mpacbti-bet1-mingw-w64-i686-arm-none-eabi/bin/arm-none-eabi-g++.exe",
    "compilerArgs": [],
    "compilerFragments": [
        "-g",
        "-mthumb",
        "-mcpu=cortex-m4",
        "-mfpu=fpv4-sp-d16",
        "-mfloat-abi=hard",
        "-Wall",
        "-Wpedantic",
        "-Wno-unused-parameter",
        "-Og",
        "-g3",
        "-ggdb",
        "-std=gnu++17"
    ]
}
Translation Unit Mappings:
[ F:\DevMCU\Project\STM32-CLI\Core\Src\main.cpp ]:
    F:\DevMCU\Project\STM32-CLI\Core\Src\main.cpp
Translation Unit Configurations:
[ F:\DevMCU\Project\STM32-CLI\Core\Src\main.cpp ]:
    Process ID: 21360
    Memory Usage: 72 MB
    Compiler Path: F:\DevMCU\ToolChain\arm-gnu-toolchain-12.2.mpacbti-bet1-mingw-w64-i686-arm-none-eabi\bin\arm-none-eabi-g++.exe
    Includes:
        F:\DevMCU\Project\STM32-CLI\Core\Inc
        F:\DevMCU\Project\STM32-CLI\Drivers\STM32L4xx_HAL_Driver\Inc
        F:\DevMCU\Project\STM32-CLI\Drivers\STM32L4xx_HAL_Driver\Inc\Legacy
        F:\DevMCU\Project\STM32-CLI\Drivers\CMSIS\Device\ST\STM32L4xx\Include
        F:\DevMCU\Project\STM32-CLI\Drivers\CMSIS\Include
        F:\DevMCU\ToolChain\arm-gnu-toolchain-12.2.mpacbti-bet1-mingw-w64-i686-arm-none-eabi\arm-none-eabi\include\c++\12.2.0
        F:\DevMCU\ToolChain\arm-gnu-toolchain-12.2.mpacbti-bet1-mingw-w64-i686-arm-none-eabi\arm-none-eabi\include\c++\12.2.0\arm-none-eabi\thumb\v7e-m+fp\hard
        F:\DevMCU\ToolChain\arm-gnu-toolchain-12.2.mpacbti-bet1-mingw-w64-i686-arm-none-eabi\arm-none-eabi\include\c++\12.2.0\backward
        F:\DevMCU\ToolChain\arm-gnu-toolchain-12.2.mpacbti-bet1-mingw-w64-i686-arm-none-eabi\lib\gcc\arm-none-eabi\12.2.0\include
        F:\DevMCU\ToolChain\arm-gnu-toolchain-12.2.mpacbti-bet1-mingw-w64-i686-arm-none-eabi\lib\gcc\arm-none-eabi\12.2.0\include-fixed
        F:\DevMCU\ToolChain\arm-gnu-toolchain-12.2.mpacbti-bet1-mingw-w64-i686-arm-none-eabi\arm-none-eabi\include
    Defines:
        DEBUG
        STM32L432xx
        USE_HAL_DRIVER
    Standard Version: c++17
    IntelliSense Mode: windows-gcc-arm
    Other Flags:
        --g++
        --gnu_version=120200
Total Memory Usage: 72 MB
Browse Paths from compile_commands.json, from workspace folder: F:\DevMCU\Project\STM32-CLI
    F:\DevMCU\Project\STM32-CLI\Core
    F:\DevMCU\Project\STM32-CLI\Core\Inc
    F:\DevMCU\Project\STM32-CLI\Core\Src
    F:\DevMCU\Project\STM32-CLI\Drivers\CMSIS\Device\ST\STM32L4xx\Include
    F:\DevMCU\Project\STM32-CLI\Drivers\CMSIS\Include
    F:\DevMCU\Project\STM32-CLI\Drivers\STM32L4xx_HAL_Driver\Inc
    F:\DevMCU\Project\STM32-CLI\Drivers\STM32L4xx_HAL_Driver\Inc\Legacy
    F:\DevMCU\Project\STM32-CLI\Drivers\STM32L4xx_HAL_Driver\Src

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 1919
```

**Comment by QrackEE** [comment] 2023-03-06 10:56
Hi, I am seeing the same problem as you do in VSCode 1.76.0, extension ms-vscode.cpptools v1.13.9 (I tried dowgrading hoping it would fix the issue). Thanks to your findings and workaround I fixed it for the time being. In addition to forceful language setting to `'en'` in extensions `main.js` I added display message that shows in OUTPUT->Window during startup:
```
function initializeSettings() {
    options = { locale: undefined, language: undefined, languagePackSupport: false, cacheLanguageResolution: true, messageFormat: common_1.MessageFormat.bundle };
    if (isString(process.env.VSCODE_NLS_CONFIG)) {
        try {
            var vscodeOptions_1 = JSON.parse(process.env.VSCODE_NLS_CONFIG);
            var language = void 0;
            if (vscodeOptions_1.availableLanguages) {
                var value = vscodeOptions_1.availableLanguages['*'];
                if (isString(value)) {
                    language = value;
                }
            }
            if (isString(vscodeOptions_1.locale)) {
                options.locale = vscodeOptions_1.locale.toLowerCase();
            }
            if (language === undefined) {
				console.error("Language undefined, using locale: " + options.locale + " based on " + process.env.VSCODE_NLS_CONFIG);
                options.language = 'en';
            }
```

the result, despite having `"locale": "en"` in `argv.json` is:

`2023-03-06 11:33:49.915 [error] [Extension Host] Language undefined, using locale: pl based on {"locale":"pl","availableLanguages":{},"_languagePackSupport":true}`

This proves @jasonyang-ee point that decision in cpptools is made based on bad input data (`process.env.VSCODE_NLS_CONFIG`). I wonder if this is not related to extension startup order in relation to NLS initialization; nevertherless, as was stated, this data structure should not be used directly as per https://github.com/microsoft/vscode/issues/23427 linked by @jasonyang-ee

**Comment by sean-mcmanus** [comment] 2023-03-10 22:42
Did someone want to create a PR to fix this? The code is at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/localization.ts#L45

**Comment by QrackEE** [comment] 2023-03-13 15:42
I tried to tackle that, but with no success. It seems I am not qualified enought to find solution at all or in fast manner.
From what I gathered though, it seems there are more than 1 individual issues:

1. the origin of OP (and mine) problem origins from `initializeSettings` of 
[vscode-nls](https://github.com/microsoft/vscode-nls) - the problem there would be in external dependency to microsoft/vscode-cpptools.
Details:
poor documentation there prevents me from understanding it in timely manner; short summary would be that for our installations Windows setting from _Settings / Time & Language / Region / Country or region_ is being used as dominant. Since we do not have any language packs installed, this `locale` is being used from OS settings; I could not determine where `process.env.VSCODE_NLS_CONFIG` comes from and why there is no user-provided configuration mechanism in it.

2. issue in function pointed by @sean-mcmanus [Extension/src/LanguageServer/localization.ts#L45](https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/localization.ts#L45) is that _microsoft/vscode-cpptools_ is recreating piece of _microsoft/vscode-nls_ `initializeSettings` function in order to have variable returned as `string`: I would say this is caused by lack of proper _microsoft/vscode-nls_ API (or documentation, so I could not find it)

3. the [microsoft/vscode-nls](https://github.com/microsoft/vscode-nls) is long time unsupported; maybe a solution from _microsoft/vscode-cpptools_ would be to search for alternatives or dedicate some effort toward that?

I tried force-run `nls.config({ locale:"<someother>"...` in localization.ts, but with no effect. 
It may be that there is nothing that can be done right now from _microsoft/vscode-cpptools_ perspective...

**Comment by Colengms** [comment] 2023-03-13 19:14
Note that the C/C++ Extension does use `vscode-nls-dev`/`vscode-nls`.  The use of `VSCODE_NLS_CONFIG` is restricted to scenarios in which we cannot use those to localize strings, such as in our `SchemaProvider` (using [an approach recommended by VS Code folks](https://github.com/microsoft/vscode/issues/78737)), and to provide our native code with the current language to use for localization in our native component.  It would seem that what we require a properly supported method for retrieving this value.  I've opened: https://github.com/microsoft/vscode/issues/176995

**Comment by Colengms** [comment] 2023-03-14 21:34
Hi @jasonyang-ee .  We're looking at switching to the officially supported method of detecting the language to localize for.  However, we had already been using the same logic that was in use in `vscode-nls` (though not officially supported).  So, this change will likely not alter the behavior in any way.  The isssue you are seeing likely will not be addressed.

There is one potential issue I'm aware of that could lead to the extension using a different language than VS Code.  If VS Code were to provide us with a language ID for a language that did not have a coresponding language pack in VS Code itself, we would use that language, despite the rest of VS Code falling back (presumably to English).  In this case, I believe it would be a VS Code issue, as they should not report to us a language that they are not themselves using in their UI.  Can you confirm if this might be the issue you're seeing?

**Comment by jasonyang-ee** [comment] 2023-03-15 03:23
@Colengms If I understand your 2nd part correctly, you are looking for VS Code Fallback condition testing.

I have recreated the situation
#### Condition:

- Latest version of cpptool and vscode.
- Chinese Transitional Windows 10 OS

#### Steps:

1. Clear VS Code display language setting.
2. Installed **BOTH** Chinese (OS Language) and Japanese (3rd Language) Language Pack.
3. Change VS Code display language setting to be Japaneses.
4. Reopened and find VS Code and cpptool UI showing Japanese correctly.
5. Manually deleted **ONLY** Japaneses Language Pack from `/user/.vscode` folder. (Chinese Pack is still there)
6. Reopened and find VS Code UI falling back to English correctly.
7. **But, cpptool UI is showing Chinese.**
8. Manually confirmed `` "locale" = "ja" `` is still untouched in `argv.json` file.

#### Additionally:
Step 5-2: I further deleted Chinese Language Pack and see that cpptool still incorrectly showing Chinese.

In short, cpptool did not have the same fall back behavior as VS Code.

I don't have sufficient knowledge in typescript language nor nls server to answer your first paragraph.

The only suspicious thing appeared to me is that nls.bundle.XX.json message key pair does not have one for 'en' . When a none English OS computer reports locale and trigger localization logic and continue to call for `localize(#, null, file_name)` function.

To tackle this suspicious universally applied `localize()` function, I think the following:
```javascript
var value = vscodeOptions_1.availableLanguages['*'];
                if (isString(value)) {
                    language = value;
                }
```
should check something like this (I only know C/C++, let me use C++ style):
```c++
std::string value = vscodeOptions_1.availableLanguages['*'];
                if ( value.find("en") > 0 ) {
                    language = "en";         // prioritize "en" when multiple language available.
                }
```

Again, I am not really sure of the usage of nls server at all. I will leave this issue to cpptool team to decide if there's value to fix or not.

For now, I spend 8 hours and has work around to force set "en", and that is good enough for my usage.

Thank you.

**Comment by jasonyang-ee** [comment] 2023-03-15 04:13
@Colengms @QrackEE @sean-mcmanus 
Fine... I was really frustrated about this issue. Here you go. Please merge this code for us. I am not sure on how do you guys maintain this repo.

## Solution:
add `if(!value.includes('en')){`

Line: 76474
```javascript
function initializeSettings() {
    options = { locale: undefined, language: undefined, languagePackSupport: false, cacheLanguageResolution: true, messageFormat: common_1.MessageFormat.bundle };
    if (isString(process.env.VSCODE_NLS_CONFIG)) {
        try {
            var vscodeOptions_1 = JSON.parse(process.env.VSCODE_NLS_CONFIG);
            var language = void 0;
            if (vscodeOptions_1.availableLanguages) {
                var value = vscodeOptions_1.availableLanguages['*'];
                if (isString(value)) {
			if(!value.includes('en')){
			    language = value;
			}
                }
            }
```

My guess was correct on the logic error of dealing 'en' as exception.

I have crippled my c_cpp_properties.json setting to quickly output the cpptool messages for debugging.

Case 1:
Set display language to English. All become English.

Case 2:
Set display language to Chinese. All become Chinese.

Case 3:
Set display language to Japanese. All become Japanese.

## Note....

Okay, I lied. I only fixed the tooltip and warning command output.

I didn't touch the code for the cpptool configuration UI (line: 47565). It is not behaving the same as. Maybe the var was made in `const`? I don't really want to debug javascript as I truly hate it... Please continue this effort for me.

I appreciate it.

![%23wy-040](https://user-images.githubusercontent.com/2824261/225204690-fdbacfc6-38fa-4212-a9d0-329be162bf0b.png)
![%23wy-042](https://user-images.githubusercontent.com/2824261/225204691-60e2511b-5a9e-4727-abac-027b7ba835b4.png)
![%23wy-043](https://user-images.githubusercontent.com/2824261/225204694-8c0a0adb-5797-4280-8393-3e21c85b28f9.png)

**Comment by Colengms** [comment] 2023-03-15 19:08
> Change VS Code display language setting to be Japaneses.
Reopened and find VS Code and cpptool UI showing Japanese correctly.
Manually deleted ONLY Japaneses Language Pack from /user/.vscode folder. (Chinese Pack is still there)
Reopened and find VS Code UI falling back to English correctly.
But, cpptool UI is showing Chinese.

>Okay, I lied. I only fixed the tooltip and warning command output.

Hi @jasonyang-ee .  You are seeing: https://github.com/microsoft/vscode/issues/82791
That is a scenario which reproduces the issue I referred to in my previous reply.  This is a VS Code bug.

The reason you saw cpptools use the correct language for only certain features after making your change, is that we are only using that code path for code that cannot use `vscode-nls`.  For all code that can, we are using `vscode-nls` (essentially part of VS Code itself), which would not be affected by your change.  Without your changes, we are using exactly the same code as `vscode-nls` (though will change this to an equivalent but supported approach, just to ensure this does not break in the future as `vscode-nls` is changed.

As the issue you are seeing is a VS Code issue, I'm going to close this as a duplicate.  If you're using the latest version of VS Code, which should have the fix for https://github.com/microsoft/vscode/issues/82791 , but are still seeing an issue with those repro steps, please follow up with an issue in [the VS Code repo](https://github.com/microsoft/vscode/issues).

**Closed as not planned by Colengms** 2023-03-15 19:08 UTC
Labels: bug, Language Service, world ready, Visual Studio Code

**Comment by Colengms** [comment] 2023-03-23 23:38
I just synced up with Tyler Leonhardt on the VS Code team.  This should be fixed by https://github.com/microsoft/vscode/pull/177426 , which should now be available in VS Code Insiders.  If you're still able to repro in VS Code Insiders (and subsequent VS Code versions), please let me know.

**Comment by jasonyang-ee** [comment] 2023-03-24 02:03
@Colengms  I have downloaded VS Code Insider just now and tested with cpptool pre-release version.
I can confirm the issue is 100% fixed.
Thank you very much!!
