### ISSUE TITLE
"There is no formatter for 'cpp' files installed', suggests the C/C++ plugin, which is listed as a formatter. It's already installed.

### ISSUE THREAD

**Issue by JonathanDotCel** [microsoft/vscode-cpptools#11713] opened 2023-11-18 20:48 UTC
### Environment

- OS and Version: Win 10 20H@, 19042
- VS Code Version: 1.84.2 user setup (see below)
- C/C++ Extension Version: v1.18.5
(+pre-release, last year's build in the 'install another version' dropdown, and a build from yesterday)

```
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19042
```

### Bug Summary and Steps to Reproduce

Bug Summary:
Fresh install of Win10 and VScode.

Literally no other plugins, no other setup.

Steps to reproduce:
1: open a project file via ctrl+p
2: alt+shift+p to format
3: "There is no formatter for 'cpp' files installed'
4: click "Install formatter"
5: It suggests the microsoft C/C++ plugin

It's already installed

Expected behavior:
Don't list it as a formatter if it isn't
Be detected as  formatter if it is

### Configuration and Logs

It's a stock, unmodified setup from today.
There is no `c_cpp_properties.json` in the `.vscode` directory or in `c:\users\me\.vscode\` or in `C:\Users\me\AppData\Roaming\Code`

`Logs from running C/C++: Log Diagnostics from the VS Code command palette`
VSCode didn't *have* this option until things were resolved (see following post)

### Other Extensions

None

### Additional context

None

**Comment by JonathanDotCel** [comment] 2023-11-18 21:35
Additional info:

The default formatter for both user and editor
`@id:editor.defaultFormatter format`
`@lang:cpp @id:editor.defaultFormatter format`
(Essentially all the user/workspace/folder  c++ user/c++ workspace/c++ folder options)

Have all been set, all been cleared, and all been re-set one by one
![image](https://github.com/microsoft/vscode-cpptools/assets/61208676/5162bcad-afe0-4256-b806-fac7b1ec805f)


Setting the default user formatter to "C/C++" as shown:

![image](https://github.com/microsoft/vscode-cpptools/assets/61208676/de2bc4d8-407f-49ee-a538-068793294a97)

Now produces the error:

Extension 'C/C++' is configured as a formatter but it cannot format 'C++'-files.

I don't want to be nasty, but this is a mess:
![image](https://github.com/microsoft/vscode-cpptools/assets/61208676/b149c194-64c2-486e-b6ae-f286d167b186)

Providing a path to clang-format (latest download), produces this issue:
https://github.com/microsoft/vscode-cpptools/issues/10102

Trying to change the default formatter for the Folder, doesn't work.
The value immediately resets. I.e. as soon as I click anywhere else, it's back to "None"
![image](https://github.com/microsoft/vscode-cpptools/assets/61208676/090f1545-cbf5-4036-aa61-959a302d32b5)

What are the out-of-the-box testing criteria as regards MS's own plugins, for new VSCode releases?
Honestly, it's not looking very stable. I've wasted an evening chasing basic formatting here on a fresh install.
Bouncing from one issue to another.

Using some of the other clang-format plugs is not an option as they don't support newer syntax.

Essentially, I have to ditch the entire MS C/C++ plugin, because it's decided it's no longer a formatter.

Thanks,
J

**Comment by sean-mcmanus** [comment] 2023-11-20 16:44
@JonathanDotCel Sorry, I'm having a hard time understanding. What is the bug? Your original issue sounds like you haven't run a command to activate our extension -- we don't register as a format handler until we activate, such as after opening a C/C++ file. FYI, 1.18.5 ships with clang-format 1.17 and 1.19.0 adds better error logging that might help. Is this a duplicate of https://github.com/microsoft/vscode-cpptools/issues/10102 ?

**Comment by bobbrow** [comment] 2023-11-20 17:05
I tried following your repro steps and wasn't able to see the issue. There may be other steps involved that we're not aware of. Are you doing this in WSL?
Video: https://github.com/microsoft/vscode-cpptools/assets/12818240/e42ccdd7-a492-44db-9e23-08e735b90cf8

If you open an Untitled file that has not been saved yet, you can get the cryptic error about no formatter installed even if you just barely formatted a saved file with the .cpp extension.
Video: https://github.com/microsoft/vscode-cpptools/assets/12818240/62ec7e1f-181a-47ef-adec-a6ef28781180

**Comment by JonathanDotCel** [comment] 2023-11-20 17:06
Hi Sean, and bobbrow, cheers for getting back.

This was nothing to do with WSL, separate issue.

"we don't register as a format handler until we activate, such as after opening a C/C++ file."
Out of curiosity, what do you assume I was trying to format then? Like a blank file or something? I don't  follow the logic there.

1st issue:
Fresh install of windows 20H2 (totally brand new), fresh install of VSCode.
The extension was active, installed etc.
I was loading .c, .cpp, .cc files from the disk. (It wasn't the "can't format unsaved files" issue)
I tried opening workspaces, folders, and individual files.
I tried multiple different versions of the plugin, as a package and not.
Multiple reboots, etc.
It just would not register as a formatter.

Once I was sure it wasn't working, only then did I try other formatters. (which worked)

In the end I had to trash my my VSCode installation.
(deleted `%userprofile%/.vscode`, and the one in `%appdata%/Code`)

At that point it registered properly as a formatter, but this happened:

2nd issue:

Essentially this:
https://github.com/microsoft/vscode-cpptools/issues/10102
But this is November 2023, not November 2022

Downgrading to plugin V1.17 fixed the issue.
(I assume the LLVM 1.19 binaries would've fared better, but that's not what came with the plugin)

Cheers.
J

**Comment by bobbrow** [comment] 2023-11-20 17:10
> "we don't register as a format handler until we activate, such as after opening a C/C++ file."
> Out of curiosity, what do you assume I was trying to format then? Like a blank file or something? I don't follow the logic there.

There could have been circumstances where VS Code didn't activate us or activation failed which is what @sean-mcmanus is referring to.  One other case is if you set the `C_Cpp.intelliSenseEngine` setting to "disabled." This turns off IntelliSense and formatting.  Some users do that if they want to use another extension for IntelliSense, but keep our extension active just for debugging.

**Comment by JonathanDotCel** [comment] 2023-11-20 17:11
> > "we don't register as a format handler until we activate, such as after opening a C/C++ file."
> > Out of curiosity, what do you assume I was trying to format then? Like a blank file or something? I don't follow the logic there.
> 
> There could have been circumstances where VS Code didn't activate us or activation failed which is what @sean-mcmanus is referring to. One other case is if you set the `C_Cpp.intelliSenseEngine` setting to "disabled." This turns off IntelliSense and formatting. Some users do that if they want to use another extension for IntelliSense, but keep our extension active just for debugging.

Aah thanks, this was fresh out the box though.
J

**Comment by bobbrow** [comment] 2023-11-20 17:15
> Aah thanks, this was fresh out the box though.
> (no changed settings)
> J

We've seen VS Code make mistakes unpacking extensions before and reinstalling the extension usually fixes those.  We've also seen people clone repositories with settings changes committed to the codebase that they've been unaware of.  So that's the context we're responding with. :)

So where does that put us in relation to your issue?  Are you saying that you're just hitting #10102 or is there another issue we need to follow up on?

**Comment by JonathanDotCel** [comment] 2023-11-20 17:18
So 1st issue:
yeah, possibly an unpacking issue.
eventually after a few reinstalls of the plugin, vscode, and deleting the settings dirs.

2nd issue:
https://github.com/microsoft/vscode-cpptools/issues/10102 Appears to be a problem again
I can check out 1.18.5 and clang-format breaks
Check out 1.17, it works
Back to 1.18.5, it's broken again
Check out 1.17, it works again

Etc,
J

**Comment by bobbrow** [comment] 2023-11-20 17:26
Would you be willing to try v1.19.0 which should log the errors that clang-format is generating?  We'd be curious to know why this flag is causing issues with clang-format again when it should have been fixed since version 12 or so.

In the Extensions panel, click the gear icon for the C++ extension and choose "Switch to Pre-Release Version" from the menu.

**Comment by JonathanDotCel** [comment] 2023-11-20 17:55
Prior to deleting my `%userprofile%/.vscode` and `%appdata%/Code` folders yesterday, no, v1.19 wasn't working.

Today, yes, 1.19 is working as intended.

Now, after installing a new version, and hitting reload, I'm getting a post-install notification in the stats menu (bottom right of the VS window) to configure intellisense, etc.
That wasn't happening yesterday.

I don't have any external LLVM repos/installs, no binaries/aliases going by 'clang-format', etc
There are no other SDKs providing a clang-format, and the path to LLVM before the hard reset was definitely:

Pre hard-reset (yesterday) I pasted the *exact* command line vscode used from the c++ output window into a terminal and got the `--Wno-error=unknown` issue.
The path was definitely of the form:
`C:\Users\me\.vscode\extensions\ms-vscode.cpptools-xyz`
(still in my cli history)

Today, post hard-reset, no error from clang-format. And I have no explanation.

My best guess is that prior to the vscode hard reset setup *something* got stuck, which prevented the plugin from fully installing and activating. 
I.e. the plugin never got as far as checking the LLVM version properly

Would that explain both the lack of formatter (issue 1) and then the subsequent clang-format error (issue2)?

**Comment by bobbrow** [comment] 2023-11-20 20:22
@sean-mcmanus do we ship the same version of clang-format in 1.18.5 and 1.19.0?  I'm at a loss to explain what @JonathanDotCel is seeing with clang-format failing on 1.18.5 and am a bit concerned that others might hit it too.

**Comment by sean-mcmanus** [comment] 2023-11-20 21:59
@bobbrow 1.18.5 and 1.19.0 have 17.0.4. You can pass "--version" to the binary to confirm that.

@JonathanDotCel I'm not sure what "clang-format breaks" means. The issues users have seen upgrading from 1.17.5 to 1.18.5 was due to duplicate entries in .clang-format causing and error (which is now logged in 1.19.0). We have not gotten any other bug reports yet of a bug in which our extension fails to register as a format provider, and we didn't explicitly fix that for 1.19.0.

So I'm also unsure what is going on.

**Closed as not planned** 2024-01-20 11:15 UTC
Labels: Language Service, more info needed, Feature: Code Formatting

**Comment by YSaxon** [comment] 2024-01-29 17:18
I'm having what I believe to be the same problem. When I try to format a .c file, it tells me `There is no formatter for 'c' files installed.`

The csvode-cpptools plugin is already installed and enabled, and I already have the correct path to clang-format specified in settings.



https://github.com/microsoft/vscode-cpptools/assets/11711101/5606f0ce-5b38-4fd4-87c2-79e46f6a6ef2



```
Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:11.430Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by YSaxon** [comment] 2024-01-29 17:19
Let me know if you'd rather me open a new issue than reopen this one.
