### ISSUE TITLE
Parse @files referenced in compile_commands.json, or give specific error message when encountered

### ISSUE THREAD

**Issue by ryan-feeley** [microsoft/vscode-cpptools#2357] opened 2018-08-05 22:11 UTC
Type: LanguageService

**Describe the bug**
- OS and Version: Windows 10, latest Msys2
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.7

If you configure your `c_cpp_properties.json` file to use a `compile_commands.json` file for include paths and defines, any referenced [compiler response](https://docs.microsoft.com/en-us/cpp/build/reference/at-specify-a-compiler-response-file) @files are not parsed and no informative error is given, even with `"C_Cpp.loggingLevel": "6"`.

**One way to Reproduce**
Use the MSYS2 Mingw x64 subsystem, and the mingw64/mingw-w64-x86_64-cmake executable to generate a compile_commands.json file with the "Unix Makefiles" generator.

Contents of a representative `compile_commands.json`:
```
[
{
  "directory": "D:/ergo-dev/build/clang/common/libraries/cstring-util",
  "command": "C:/apps/msys64/mingw64/bin/clang++.exe -DERGO_HAS_CPPSTDLIB @CMakeFiles/cstring-util.dir/includes_CXX.rsp  -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-covered-switch-default -g   -std=gnu++14 -o CMakeFiles/cstring-util.dir/cstring-util.cpp.obj -c D:/ergo-dev/common/libraries/cstring-util/cstring-util.cpp",
  "file": "D:/ergo-dev/common/libraries/cstring-util/cstring-util.cpp"
}
]
```

Contents of corresponding `@CMakeFiles/cstring-util.dir/includes_CXX.rsp` with path relative to the "directory" in the `compile_commands.json`:
```
-ID:/ergo-dev/common/libraries/cstring-util 
```

**Expected behavior**
`compile_commands.json` would be parsed, which includes simple text insertion of the contents of any referenced @files. Alternatively, a warning would be issued that the `compile_commands.json` file contains @files which are currently ignored by the extension. 

**Screenshots**
See this SO user's [question](https://stackoverflow.com/questions/49432379/vscode-not-using-compile-commands-json-for-library-paths).

**Comment by ryan-feeley** [comment] 2018-08-05 23:39
This might give a little more background. Ninja uses [compdb](https://github.com/Sarcasm/compdb) to generate compile_options.json files. They recently [merged a PR](https://github.com/ninja-build/ninja/pull/1223) that introduces a '-x' option to their invocation of '-t compdb' that will expand @rspfile style response file invocations inline.

This is to support tooling that expects all the command flags to be present in the 'command' field of compile_commands.json.

It looks like LLVM expects the "command:" to be free of response files in their [JSON Compilation Database Format Specification](http://clang.llvm.org/docs/JSONCompilationDatabase.html). However, it would seem that not all compile_commands.json generators adopt this format.

> command: The compile command executed. After JSON unescaping, this must be a valid command to rerun the exact compilation step for the translation unit in the environment the build system uses. Parameters use shell quoting and shell escaping of quotes, with ‘"’ and ‘\’ being the only special characters. Shell expansion is not supported.

It makes sense that there is some ambiguity here, and different tools might pick different approaches, since what is a "valid command", if the command required to run a compilation step is too long for the platform shell.

**Comment by ryan-feeley** [comment] 2018-08-05 23:47
Since it would appear that @rspfiles in `compile_commands.json` is probably a bit of an edge case (rarely needed since projects built on Windows tend to be smaller, and Linux supports much longer commands), giving the user an informative error message if a response file is referenced in `compile_commands.json` and a link to more info or possible workarounds is probably the best resolution of this issue.

**Comment by bobbrow** [comment] 2018-09-11 16:54
I believe this is a duplicate of #1718

**Closed as completed by bobbrow** 2018-09-11 16:54 UTC
Labels: bug, Language Service
