### ISSUE TITLE
Undeclared function in C not showing an error

### ISSUE THREAD

**Issue by coder-mike** [microsoft/vscode-cpptools#5721] opened 2020-07-03 05:09 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.46.1
- C/C++ Extension Version: 0.28.3

**Steps to reproduce**

Create a C source file with the following code:

```c
// main.c
int main() {
  thisFunctionIsNotDeclaredAnywhere();
}
```

**Expected behavior**

I would expect it to underline `thisFunctionIsNotDeclaredAnywhere` as an error, but instead, it seems to automatically declare it with a signature that returns an integer.

![image](https://user-images.githubusercontent.com/2261100/86433725-d9ec8580-bd3e-11ea-9f59-61bfe65e30b9.png)

If I change the file extension to `cpp`, I get the expected squigglies.

![image](https://user-images.githubusercontent.com/2261100/86433771-f25ca000-bd3e-11ea-861a-c06cee569bef.png)

The issue is that these do not seem to show up on C code, making refactoring difficult.

**Comment by sean-mcmanus** [comment] 2020-07-06 20:58
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/828 . You could upvote that issue.

The issue is that the C compiler doesn't generate an error, but a warning.

**Closed as completed by sean-mcmanus** 2020-07-06 20:58 UTC
Labels: duplicate
