### ISSUE TITLE
Support for custom C/C++ formatting

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode-cpptools#2754] opened 2018-11-01 00:28 UTC
Is it possible to support custom settings for C/C++ formatting (such as indentation, new lines, spacing wrapping), similar to Visual Studio? See https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-c-cpp-formatting?view=vs-2017

**Comment by sean-mcmanus** [comment] 2018-11-01 00:50
We use clang-format for formatting, so you can change our clang_format-related settings or add a `.clang-format` file to your project to modify the settings as well. Visual Studio's formatter is a custom implementation that we might port over later, but not in the near-term -- is that what you're asking for? We may also be able to update our default clang-format settings if you know a way to make them more similar to VS's default settings.

**Comment by bobbrow** [comment] 2018-11-01 05:29
Yes.  This is a duplicate of #657

**Closed as completed by bobbrow** 2018-11-01 05:29 UTC
Labels: duplicate, Language Service, Feature Request
