### ISSUE TITLE
Disabling autocomplete for C++ comment doesn't work

### ISSUE THREAD

**Issue by tinebp** [microsoft/vscode-cpptools#3958] opened 2019-07-22 20:33 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: ubuntu 16.04 x84_64
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1
- Other extensions you installed: C++ Intellisense (austin), Remote - SSH (Microsoft)
- A clear and concise description of what the bug is.

**To Reproduce**
- disable autocomplete in "the seetings.json" as below
{  
    "workbench.iconTheme": "vs-minimal",
    "C_Cpp.autocomplete": "Disabled" 
} 
- create a new c++ header file: HelloWorld.h
- type the beginning of a comment: /*

**Expected behavior**
- the two characters you type should show and nothing else: /*

**Actual behavior**
- VSCode auto-complete the comment: /* */

**Additional context**
I tried all the suggestions I found on google but none of them worked :-(

**Comment by michelleangela** [comment] 2019-07-22 20:39
Duplicate of https://github.com/microsoft/vscode/issues/77008

**Closed as completed by michelleangela** 2019-07-22 20:39 UTC
Labels: duplicate, Visual Studio Code
