### ISSUE TITLE
ErrorSquiggles only appears in open files

### ISSUE THREAD

**Issue by lh123** [microsoft/vscode-cpptools#3207] opened 2019-02-23 11:07 UTC
**ErrorSquiggles** disappears when the file is closed.

> I think **ErrorSquiggle** should be kept when the file is closed.

**Comment by bobbrow** [comment] 2019-02-25 18:14
This is how VSCode works with other languages too.  We could consider adding a setting to leave the squiggles around, but we'd need to see more upvotes before doing this work.

**Comment by sean-mcmanus** [comment] 2019-02-25 22:16
Is there a reason you would want error squiggles to still show for closed files? Are these closed files header files that belong to the currently open translation unit?

**Comment by lh123** [comment] 2019-02-26 03:00
> This is how VSCode works with other languages too. We could consider adding a setting to leave the squiggles around, but we'd need to see more upvotes before doing this work.
1. typescript lsp
ErrorSquiggles still shows after the file is closed.
![screenshot_20190226_105528](https://user-images.githubusercontent.com/10697249/53384282-47eba480-39b5-11e9-9098-d1d96e7bbaeb.png)
2. vscode-clangd
ErrorSquiggles still shows after the file is closed.
![image](https://user-images.githubusercontent.com/10697249/53384388-ae70c280-39b5-11e9-9ec1-9a69bcc55fb3.png)

![image](https://user-images.githubusercontent.com/10697249/53384988-d06b4480-39b7-11e9-8b52-b9b57f89c575.png)

**Comment by lh123** [comment] 2019-02-26 03:09
> Is there a reason you would want error squiggles to still show for closed files?

This will let me know if other files have errors.
Without this feature, I have to recompile the project to know the errors in other files.

> Are these closed files header files that belong to the currently open translation unit?

No. But even in the same translation unit, ErrorSquiggles will not be displayed in the closed file.

**Comment by sean-mcmanus** [comment] 2019-02-26 03:38
Okay, that's news to me -- VS Code's json squiggler stops showing the errors when the file is closed, so maybe that's what I was thinking of. Visual Studio also stops showing IntelliSense errors when the file is closed (I filed a bug on VS 2 years ago and they closed it as "By Design", not sure of the reasoning behind that design).

This looks like a 1 line change if we want to do this, plus any test case changes. Probably won't be till March/April though.

**Comment by lh123** [comment] 2019-02-26 03:52
I hope this feature is implemented because it is implemented in most "LSP".

**Comment by bobbrow** [comment] 2019-02-26 04:51
I'm fairly certain TypeScript used to clear the problems when the file closed.  This is news to me.  When we do this work, we would enable it behind a `C_Cpp.persistProblemsForClosedFiles` or some such setting.  It would default to false.

**Closed as completed** 2022-06-12 11:43 UTC
Labels: Language Service, Feature Request, quick fix, more votes needed, Works in VS
