### ISSUE TITLE
[Feature Request][cppvsdbg] Support Logpoints

### ISSUE THREAD

**Issue by guestieng** [microsoft/vscode-cpptools#5247] opened 2020-04-03 11:00 UTC
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10..0.16299
- VS Code Version: 1.43.1
- C/C++ Extension Version: 0.27.0
- Other extensions you installed (and if the issue persists after disabling them): CMake Tools 1.3.1, CMake 0.0.17
- Compiler: MSVC
- **ISSUE**: 
  Setting a Log Message for a breakpoint has no effect (logging is simply not happening) and hovering over the breakpoint (just after starting debugger with config. type "cppvsdbg") yields the tooltip "Breakpoints of this type are not supported by the debugger"

**To Reproduce**
* `launch.json` configuration:*
```
{
    "configurations": [
        {
            "name": "Attach to Process",
            "processId": "${command:pickProcess}",
            "request": "attach",
            "type": "cppvsdbg",
            "logging": {
                "exceptions": true,
                "programOutput": true,
                "trace": true, 
                "traceResponse": true,
                "engineLogging": true              
            }
        }
    ],
    "version": "0.2.0"
}
```

1. Set a breakpoint
2. Right click -> choose "Edit Logpoint..."
3. insert Log essage
4. Start debugging, attach to process
5. Hover over breakpoint and await tooltip "Breakpoints of this type are not supported by the debugger"

**Additional context**
Visual Studio 2019 (version 16.4.0) is installed.
A note: the value "launch" of "configurations" -> "request" yields the same issue.

**Comment by pieandcakes** [comment] 2020-04-03 19:31
@WardenGnaw Might be duplicate of #2591

**Comment by WardenGnaw** [comment] 2020-04-04 00:32
It is a duplicate.

**Closed as completed by WardenGnaw** 2020-04-04 00:32 UTC
Labels: duplicate

**Comment by guestieng** [comment] 2020-04-04 09:58
Can this be made clearer?
What is the current state of this issue (for this particular configuration!)?
It looks like unexpected behaviour by now.
