### ISSUE TITLE
error while loading libtinfo.so.5

### ISSUE THREAD

**Issue by billchenchina** [microsoft/vscode-cpptools#4664] opened 2019-11-26 16:15 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux x64 4.19.0-6-amd64
- VS Code Version: 1.40.1 8795a9889db74563ddd43eb0a897a2384129a619
- C/C++ Extension Version: 0.26.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
```
Formatting failed:
/home/billchenchina/.vscode/extensions/ms-vscode.cpptools-0.26.1/bin/../LLVM/bin/clang-format -style={ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 2, TabWidth: 2, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -2 } -fallback-style=LLVM -sort-includes=0 -assume-filename=/home/billchenchina/a.cpp
/home/billchenchina/.vscode/extensions/ms-vscode.cpptools-0.26.1/bin/../LLVM/bin/clang-format: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
**To Reproduce**

1. Open a file using `code a.cpp`
2. `Ctrl+Shift+I` to format the file
3. See error

**Expected behavior**
No error
**Screenshots**

**Additional context**

```
billchenchina@HP-Pavilion-14-bf048tx:~$ locate libtinfo.so
/home/billchenchina/android-studio/bin/lldb/lib/libtinfo.so.5
/usr/lib/i386-linux-gnu/libtinfo.so.6
/usr/lib/i386-linux-gnu/libtinfo.so.6.1
/usr/lib/x86_64-linux-gnu/libtinfo.so.6
/usr/lib/x86_64-linux-gnu/libtinfo.so.6.1
```

**Comment by sean-mcmanus** [comment] 2019-11-26 19:09
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/3174 , which has some workarounds described.

**Closed as completed by sean-mcmanus** 2019-11-26 19:09 UTC
Labels: duplicate

**Comment by billchenchina** [comment] 2019-11-27 01:34
> This is a duplicate of #3174 , which has some workarounds described.

Yeah, I tried linking the libtinfo.so.5 to libtinfo.so.6, and it works.

Why not changing the clang-format to the latest version? Is it for compatibility or something else?

**Comment by sean-mcmanus** [comment] 2019-11-27 01:52
We have another issue tracking that...we may also need to find a way to ship different versions on different Linux OS's (i.e. I think we ship clang-format 6 from Ubuntu 14).

**Comment by sean-mcmanus** [comment] 2020-03-04 03:01
Our Insiders release fixes the clang-format dependency problems: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders
