### ISSUE TITLE
Apostrophes auto-complete to single quotes when used in a comment

### ISSUE THREAD

**Issue by duncanhorn** [microsoft/vscode-cpptools#127] opened 2016-08-02 00:21 UTC
E.g. if I'm trying to type:

```
// ya'll
```

I'll end up with:

```
// ya'll'
```

and will manually need to delete the extra apostrophe

**Comment by devnoname120** [comment] 2017-03-05 00:16
Is there an update about this? It's rather annoying.

**Comment by bobbrow** [comment] 2017-03-06 16:52
You can disable it by adding `"editor.autoClosingBrackets": false,` to your settings.json file, but we'll need to talk to the VS Code folks and figure out why this might be happening.  We don't get a callback for it and I don't reproduce this problem in TypeScript files, so it could possibly be an issue with the atom grammar for C++.

**Comment by bobbrow** [comment] 2017-05-09 05:14
This is fixed in the latest version of VS Code (1.12.1)

**Closed as completed by bobbrow** 2017-05-09 05:14 UTC
Labels: Language Service, external

**Comment by taniarascia** [comment] 2017-06-07 16:16
This is still an issue for me in VS Code 1.12.2.

**Comment by bobbrow** [comment] 2017-06-07 18:34
Can you elaborate or give an example of what you're doing when you see this happen?  I don't repro in 1.12.2.

Other characters (paren, curly brace, double quote) still do auto-closing brackets inside comments because those almost universally need to be closed.  Single quotes should not insert an auto-closing char when inside a comment so the original issue reported is fixed.  If there is something else broken that we need to innvestigate, can you please reopen this issue or create a new one?

**Comment by taniarascia** [comment] 2017-06-07 19:02
Hi @bobbrow,

I'm currently using Visual Studio Code 1.12.2. If I leave the `editor.autoClosingBrackets` setting to default (`true`), apostrophes in comments are duplicated.

Here is an image both displaying my version number, and the issue that happened.

<img width="592" alt="screen shot 2017-06-07 at 1 58 00 pm" src="https://user-images.githubusercontent.com/11951801/26896227-a7c2ad52-4b89-11e7-91ab-ed3a887e9fc7.png">

From what I can tell, this GitHub issue is the exact one I'm having, which is why I didn't open a new issue. I'd be happy to reopen this issue if necessary. My issue is solved by changing the preferences (`"editor.autoClosingBrackets": false`) but I feel like that shouldn't be necessary.

Thanks for your response, have a great day.

**Comment by sean-mcmanus** [comment] 2017-06-07 19:12
Yeah, it doesn't repro on any of my machines either, including Mac.

**Comment by bobbrow** [comment] 2017-06-07 19:25
@taniarascia, do you also have version 0.11.4 of the C/C++ extension installed?

**Comment by bobbrow** [comment] 2017-06-07 19:29
Oh, and also, can you verify if the status bar in the lower right corner shows "C" or "C++" as the active language?  The text in your screenshot is not green, so I suspect that the editor has not detected you are in a comment block.

![status](https://user-images.githubusercontent.com/12818240/26897235-b4ee0470-4b7c-11e7-82b0-52cc6c528ab0.png)

**Comment by taniarascia** [comment] 2017-06-07 19:31
Ah, this is my fault, I didn't know this issue was C++ specific. I'm working in another language. I'm sorry for taking your time.

**Comment by bobbrow** [comment] 2017-06-07 19:34
Yeah, it is specific to whatever language you are working with and it not something that extensions handle.  You can log an issue with the VS Code team if it is a language that they have a grammar for already or you can request they add a grammar for your language.

**Comment by taniarascia** [comment] 2017-06-07 19:35
Thanks for letting me know. In my case, it's for PHP.
