### ISSUE TITLE
Enable breakpoints for nim language

### ISSUE THREAD

**Issue by rokups** [microsoft/vscode-cpptools#516] opened 2017-02-24 09:00 UTC
It is as easy as adding [this](https://github.com/WebFreak001/code-debug/blob/master/package.json#L57). Please enable it. Current workaround is installing my linked extension so we can add breakpoints in nim code, then we can use microsoft cpp extension debugger to debug nim code and it works.

**Comment by pieandcakes** [comment] 2017-02-24 22:13
@rokups You are welcome to add it to your local copy of the `package.json` file. I'll ask and see if this is something we would support but at this time we are focused on C and C++.

**Comment by pieandcakes** [comment] 2020-03-03 17:50
Duplicate of #75

**Closed as completed by pieandcakes** 2020-03-03 17:50 UTC
Labels: debugger, Feature Request, external
