### ISSUE TITLE
Intellisense 1.15.4 cannot locate vcruntime_exception.h when including C++ standard libraries

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#10940] opened 2023-05-11 20:06 UTC
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.78.1
- C/C++ Extension Version: 1.15.4

### Bug Summary and Steps to Reproduce

Bug Summary:
After updating the C/C++ extension to 1.15.4, Intellisense only gives the following errors on files that include certain (any?) standard library headers, such as memory, random, vector, iostream, and string:
* #include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (E:\Picross Solver\src\main.cpp).
* cannot open source file "vcruntime_exception.h" (dependency of "memory")

A simple .cpp file with `#include <memory>` is enough to get these errors.
However, clang++ can compile such programs without problems
This does not occur in extension versions 1.14.5 or 1.14.4.

Seems to boil down to this code in exception.h:
```
#if defined(_LIBCPP_ABI_VCRUNTIME)
#include <vcruntime_exception.h>
#endif```

In versions 1.14.4 and 1.14.5,_LIBCPP_ABI_VCRUNTIME is not defined for Intellisense; in version 1.15.4, it is.

### Configuration and Logs

```shell
c_cpp_properties.json

{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/Program Files/llvm-mingw-20220906-msvcrt-x86_64/bin/clang.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-clang-x64"
        }
    ],
    "version": 4
}
```

C/C++ Log Diagnostics:
```
-------- Diagnostics - 5/11/2023, 11:15:53 AM
Version: 1.15.4
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "e:\\Picross Solver/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "C:/Program Files/llvm-mingw-20220906-msvcrt-x86_64/bin/clang.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-clang-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "C:/Program Files/llvm-mingw-20220906-msvcrt-x86_64/bin/clang.exe",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ E:\Picross Solver\src\main.cpp ]:
    E:\Picross Solver\src\main.cpp
Translation Unit Configurations:
[ E:\Picross Solver\src\main.cpp ]:
    Process ID: 30296
    Memory Usage: 253 MB
    Compiler Path: C:\Program Files\llvm-mingw-20220906-msvcrt-x86_64\bin\clang.exe
    Includes:
        C:\Program Files\llvm-mingw-20220906-msvcrt-x86_64\include\c++\v1
        C:\Program Files\llvm-mingw-20220906-msvcrt-x86_64\lib\clang\15.0.0\include
        C:\Program Files\llvm-mingw-20220906-msvcrt-x86_64\include
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++17
    IntelliSense Mode: windows-clang-x64
    Other Flags:
        --clang
        --clang_version=150000
        --ms_extensions
Total Memory Usage: 253 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 2824
```

<details>
<summary>Language server logging</summary>
LSP: cpptools/textEditorSelectionChange<br/>
LSP: cpptools/activeDocumentChange: file:///e%3A/Picross%20Solver/src/test.cpp<br/>
LSP: cpptools/restartIntelliSenseForFile: file:///e%3A/Picross%20Solver/src/test.cpp<br/>
Checking for syntax errors: E:\Picross Solver\src	est.cpp<br/>
sending compilation args for E:\Picross Solver\src	est.cpp<br/>
  include: C:\PROGRAM FILES\LLVM-MINGW-20220906-MSVCRT-X86_64\INCLUDE\C++\V1<br/>
  include: C:\PROGRAM FILES\LLVM-MINGW-20220906-MSVCRT-X86_64\LIB\CLANG<br/>
.0.0\INCLUDE<br/>
  include: C:\PROGRAM FILES\LLVM-MINGW-20220906-MSVCRT-X86_64\INCLUDE<br/>
  define: _WIN32=1<br/>
  define: _WIN64=1<br/>
  define: __ATOMIC_ACQUIRE=2<br/>
  define: __ATOMIC_ACQ_REL=4<br/>
  define: __ATOMIC_CONSUME=1<br/>
  define: __ATOMIC_RELAXED=0<br/>
  define: __ATOMIC_RELEASE=3<br/>
  define: __ATOMIC_SEQ_CST=5<br/>
  define: __BIGGEST_ALIGNMENT__=16<br/>
  define: __BITINT_MAXWIDTH__=128<br/>
  define: __BOOL_WIDTH__=8<br/>
  define: __BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__<br/>
  define: __CHAR16_TYPE__=unsigned short<br/>
  define: __CHAR32_TYPE__=unsigned int<br/>
  define: __CHAR_BIT__=8<br/>
  define: __CLANG_ATOMIC_BOOL_LOCK_FREE=2<br/>
  define: __CLANG_ATOMIC_CHAR16_T_LOCK_FREE=2<br/>
  define: __CLANG_ATOMIC_CHAR32_T_LOCK_FREE=2<br/>
  define: __CLANG_ATOMIC_CHAR_LOCK_FREE=2<br/>
  define: __CLANG_ATOMIC_INT_LOCK_FREE=2<br/>
  define: __CLANG_ATOMIC_LLONG_LOCK_FREE=2<br/>
  define: __CLANG_ATOMIC_LONG_LOCK_FREE=2<br/>
  define: __CLANG_ATOMIC_POINTER_LOCK_FREE=2<br/>
  define: __CLANG_ATOMIC_SHORT_LOCK_FREE=2<br/>
  define: __CLANG_ATOMIC_WCHAR_T_LOCK_FREE=2<br/>
  define: __CONSTANT_CFSTRINGS__=1<br/>
  define: __DBL_DECIMAL_DIG__=17<br/>
  define: __DBL_DENORM_MIN__=4.9406564584124654e-324<br/>
  define: __DBL_DIG__=15<br/>
  define: __DBL_EPSILON__=2.2204460492503131e-16<br/>
  define: __DBL_HAS_DENORM__=1<br/>
  define: __DBL_HAS_INFINITY__=1<br/>
  define: __DBL_HAS_QUIET_NAN__=1<br/>
  define: __DBL_MANT_DIG__=53<br/>
  define: __DBL_MAX_10_EXP__=308<br/>
  define: __DBL_MAX_EXP__=1024<br/>
  define: __DBL_MAX__=1.7976931348623157e+308<br/>
  define: __DBL_MIN_10_EXP__=(-307)<br/>
  define: __DBL_MIN_EXP__=(-1021)<br/>
  define: __DBL_MIN__=2.2250738585072014e-308<br/>
  define: __DECIMAL_DIG__=__LDBL_DECIMAL_DIG__<br/>
  define: __DEPRECATED=1<br/>
  define: __EXCEPTIONS=1<br/>
  define: __FINITE_MATH_ONLY__=0<br/>
  define: __FLT16_DECIMAL_DIG__=5<br/>
  define: __FLT16_DENORM_MIN__=5.9604644775390625e-8F16<br/>
  define: __FLT16_DIG__=3<br/>
  define: __FLT16_EPSILON__=9.765625e-4F16<br/>
  define: __FLT16_HAS_DENORM__=1<br/>
  define: __FLT16_HAS_INFINITY__=1<br/>
  define: __FLT16_HAS_QUIET_NAN__=1<br/>
  define: __FLT16_MANT_DIG__=11<br/>
  define: __FLT16_MAX_10_EXP__=4<br/>
  define: __FLT16_MAX_EXP__=16<br/>
  define: __FLT16_MAX__=6.5504e+4F16<br/>
  define: __FLT16_MIN_10_EXP__=(-4)<br/>
  define: __FLT16_MIN_EXP__=(-13)<br/>
  define: __FLT16_MIN__=6.103515625e-5F16<br/>
  define: __FLT_DECIMAL_DIG__=9<br/>
  define: __FLT_DENORM_MIN__=1.40129846e-45F<br/>
  define: __FLT_DIG__=6<br/>
  define: __FLT_EPSILON__=1.19209290e-7F<br/>
  define: __FLT_HAS_DENORM__=1<br/>
  define: __FLT_HAS_INFINITY__=1<br/>
  define: __FLT_HAS_QUIET_NAN__=1<br/>
  define: __FLT_MANT_DIG__=24<br/>
  define: __FLT_MAX_10_EXP__=38<br/>
  define: __FLT_MAX_EXP__=128<br/>
  define: __FLT_MAX__=3.40282347e+38F<br/>
  define: __FLT_MIN_10_EXP__=(-37)<br/>
  define: __FLT_MIN_EXP__=(-125)<br/>
  define: __FLT_MIN__=1.17549435e-38F<br/>
  define: __FLT_RADIX__=2<br/>
  define: __FXSR__=1<br/>
  define: __GCC_ASM_FLAG_OUTPUTS__=1<br/>
  define: __GCC_ATOMIC_BOOL_LOCK_FREE=2<br/>
  define: __GCC_ATOMIC_CHAR16_T_LOCK_FREE=2<br/>
  define: __GCC_ATOMIC_CHAR32_T_LOCK_FREE=2<br/>
  define: __GCC_ATOMIC_CHAR_LOCK_FREE=2<br/>
  define: __GCC_ATOMIC_INT_LOCK_FREE=2<br/>
  define: __GCC_ATOMIC_LLONG_LOCK_FREE=2<br/>
  define: __GCC_ATOMIC_LONG_LOCK_FREE=2<br/>
  define: __GCC_ATOMIC_POINTER_LOCK_FREE=2<br/>
  define: __GCC_ATOMIC_SHORT_LOCK_FREE=2<br/>
  define: __GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1<br/>
  define: __GCC_ATOMIC_WCHAR_T_LOCK_FREE=2<br/>
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1<br/>
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1<br/>
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1<br/>
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1<br/>
  define: __GNUC_GNU_INLINE__=1<br/>
  define: __GNUC_MINOR__=2<br/>
  define: __GNUC_PATCHLEVEL__=1<br/>
  define: __GNUC__=4<br/>
  define: __GNUG__=4<br/>
  define: __GXX_ABI_VERSION=1002<br/>
  define: __GXX_EXPERIMENTAL_CXX0X__=1<br/>
  define: __GXX_RTTI=1<br/>
  define: __GXX_WEAK__=1<br/>
  define: __INT16_C_SUFFIX__=<br/>
  define: __INT16_FMTd__="hd"<br/>
  define: __INT16_FMTi__="hi"<br/>
  define: __INT16_MAX__=32767<br/>
  define: __INT16_TYPE__=short<br/>
  define: __INT32_C_SUFFIX__=<br/>
  define: __INT32_FMTd__="d"<br/>
  define: __INT32_FMTi__="i"<br/>
  define: __INT32_MAX__=2147483647<br/>
  define: __INT32_TYPE__=int<br/>
  define: __INT64_C_SUFFIX__=LL<br/>
  define: __INT64_FMTd__="lld"<br/>
  define: __INT64_FMTi__="lli"<br/>
  define: __INT64_MAX__=9223372036854775807LL<br/>
  define: __INT64_TYPE__=long long int<br/>
  define: __INT8_C_SUFFIX__=<br/>
  define: __INT8_FMTd__="hhd"<br/>
  define: __INT8_FMTi__="hhi"<br/>
  define: __INT8_MAX__=127<br/>
  define: __INT8_TYPE__=signed char<br/>
  define: __INTMAX_C_SUFFIX__=LL<br/>
  define: __INTMAX_FMTd__="lld"<br/>
  define: __INTMAX_FMTi__="lli"<br/>
  define: __INTMAX_MAX__=9223372036854775807LL<br/>
  define: __INTMAX_TYPE__=long long int<br/>
  define: __INTMAX_WIDTH__=64<br/>
  define: __INTPTR_FMTd__="lld"<br/>
  define: __INTPTR_FMTi__="lli"<br/>
  define: __INTPTR_MAX__=9223372036854775807LL<br/>
  define: __INTPTR_TYPE__=long long int<br/>
  define: __INTPTR_WIDTH__=64<br/>
  define: __INT_FAST16_FMTd__="hd"<br/>
  define: __INT_FAST16_FMTi__="hi"<br/>
  define: __INT_FAST16_MAX__=32767<br/>
  define: __INT_FAST16_TYPE__=short<br/>
  define: __INT_FAST16_WIDTH__=16<br/>
  define: __INT_FAST32_FMTd__="d"<br/>
  define: __INT_FAST32_FMTi__="i"<br/>
  define: __INT_FAST32_MAX__=2147483647<br/>
  define: __INT_FAST32_TYPE__=int<br/>
  define: __INT_FAST32_WIDTH__=32<br/>
  define: __INT_FAST64_FMTd__="lld"<br/>
  define: __INT_FAST64_FMTi__="lli"<br/>
  define: __INT_FAST64_MAX__=9223372036854775807LL<br/>
  define: __INT_FAST64_TYPE__=long long int<br/>
  define: __INT_FAST64_WIDTH__=64<br/>
  define: __INT_FAST8_FMTd__="hhd"<br/>
  define: __INT_FAST8_FMTi__="hhi"<br/>
  define: __INT_FAST8_MAX__=127<br/>
  define: __INT_FAST8_TYPE__=signed char<br/>
  define: __INT_FAST8_WIDTH__=8<br/>
  define: __INT_LEAST16_FMTd__="hd"<br/>
  define: __INT_LEAST16_FMTi__="hi"<br/>
  define: __INT_LEAST16_MAX__=32767<br/>
  define: __INT_LEAST16_TYPE__=short<br/>
  define: __INT_LEAST16_WIDTH__=16<br/>
  define: __INT_LEAST32_FMTd__="d"<br/>
  define: __INT_LEAST32_FMTi__="i"<br/>
  define: __INT_LEAST32_MAX__=2147483647<br/>
  define: __INT_LEAST32_TYPE__=int<br/>
  define: __INT_LEAST32_WIDTH__=32<br/>
  define: __INT_LEAST64_FMTd__="lld"<br/>
  define: __INT_LEAST64_FMTi__="lli"<br/>
  define: __INT_LEAST64_MAX__=9223372036854775807LL<br/>
  define: __INT_LEAST64_TYPE__=long long int<br/>
  define: __INT_LEAST64_WIDTH__=64<br/>
  define: __INT_LEAST8_FMTd__="hhd"<br/>
  define: __INT_LEAST8_FMTi__="hhi"<br/>
  define: __INT_LEAST8_MAX__=127<br/>
  define: __INT_LEAST8_TYPE__=signed char<br/>
  define: __INT_LEAST8_WIDTH__=8<br/>
  define: __INT_MAX__=2147483647<br/>
  define: __INT_WIDTH__=32<br/>
  define: __LDBL_DECIMAL_DIG__=21<br/>
  define: __LDBL_DENORM_MIN__=3.64519953188247460253e-4951L<br/>
  define: __LDBL_DIG__=18<br/>
  define: __LDBL_EPSILON__=1.08420217248550443401e-19L<br/>
  define: __LDBL_HAS_DENORM__=1<br/>
  define: __LDBL_HAS_INFINITY__=1<br/>
  define: __LDBL_HAS_QUIET_NAN__=1<br/>
  define: __LDBL_MANT_DIG__=64<br/>
  define: __LDBL_MAX_10_EXP__=4932<br/>
  define: __LDBL_MAX_EXP__=16384<br/>
  define: __LDBL_MAX__=1.18973149535723176502e+4932L<br/>
  define: __LDBL_MIN_10_EXP__=(-4931)<br/>
  define: __LDBL_MIN_EXP__=(-16381)<br/>
  define: __LDBL_MIN__=3.36210314311209350626e-4932L<br/>
  define: __LITTLE_ENDIAN__=1<br/>
  define: __LLONG_WIDTH__=64<br/>
  define: __LONG_LONG_MAX__=9223372036854775807LL<br/>
  define: __LONG_MAX__=2147483647L<br/>
  define: __LONG_WIDTH__=32<br/>
  define: __MINGW32__=1<br/>
  define: __MINGW64__=1<br/>
  define: __MMX__=1<br/>
  define: __MSVCRT__=1<br/>
  define: __NO_INLINE__=1<br/>
  define: __NO_MATH_INLINES=1<br/>
  define: __OBJC_BOOL_IS_BOOL=0<br/>
  define: __OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES=3<br/>
  define: __OPENCL_MEMORY_SCOPE_DEVICE=2<br/>
  define: __OPENCL_MEMORY_SCOPE_SUB_GROUP=4<br/>
  define: __OPENCL_MEMORY_SCOPE_WORK_GROUP=1<br/>
  define: __OPENCL_MEMORY_SCOPE_WORK_ITEM=0<br/>
  define: __ORDER_BIG_ENDIAN__=4321<br/>
  define: __ORDER_LITTLE_ENDIAN__=1234<br/>
  define: __ORDER_PDP_ENDIAN__=3412<br/>
  define: __PIC__=2<br/>
  define: __POINTER_WIDTH__=64<br/>
  define: __PRAGMA_REDEFINE_EXTNAME=1<br/>
  define: __PTRDIFF_FMTd__="lld"<br/>
  define: __PTRDIFF_FMTi__="lli"<br/>
  define: __PTRDIFF_MAX__=9223372036854775807LL<br/>
  define: __PTRDIFF_TYPE__=long long int<br/>
  define: __PTRDIFF_WIDTH__=64<br/>
  define: __REGISTER_PREFIX__=<br/>
  define: __SCHAR_MAX__=127<br/>
  define: __SEG_FS=1<br/>
  define: __SEG_GS=1<br/>
  define: __SEH__=1<br/>
  define: __SHRT_MAX__=32767<br/>
  define: __SHRT_WIDTH__=16<br/>
  define: __SIG_ATOMIC_MAX__=2147483647<br/>
  define: __SIG_ATOMIC_WIDTH__=32<br/>
  define: __SIZEOF_DOUBLE__=8<br/>
  define: __SIZEOF_FLOAT128__=16<br/>
  define: __SIZEOF_FLOAT__=4<br/>
  define: __SIZEOF_INT128__=16<br/>
  define: __SIZEOF_INT__=4<br/>
  define: __SIZEOF_LONG_DOUBLE__=16<br/>
  define: __SIZEOF_LONG_LONG__=8<br/>
  define: __SIZEOF_LONG__=4<br/>
  define: __SIZEOF_POINTER__=8<br/>
  define: __SIZEOF_PTRDIFF_T__=8<br/>
  define: __SIZEOF_SHORT__=2<br/>
  define: __SIZEOF_SIZE_T__=8<br/>
  define: __SIZEOF_WCHAR_T__=2<br/>
  define: __SIZEOF_WINT_T__=2<br/>
  define: __SIZE_FMTX__="llX"<br/>
  define: __SIZE_FMTo__="llo"<br/>
  define: __SIZE_FMTu__="llu"<br/>
  define: __SIZE_FMTx__="llx"<br/>
  define: __SIZE_MAX__=18446744073709551615ULL<br/>
  define: __SIZE_TYPE__=long long unsigned int<br/>
  define: __SIZE_WIDTH__=64<br/>
  define: __SSE2_MATH__=1<br/>
  define: __SSE2__=1<br/>
  define: __SSE_MATH__=1<br/>
  define: __SSE__=1<br/>
  define: __STDCPP_DEFAULT_NEW_ALIGNMENT__=16ULL<br/>
  define: __STDCPP_THREADS__=1<br/>
  define: __STDC_HOSTED__=1<br/>
  define: __STDC_UTF_16__=1<br/>
  define: __STDC_UTF_32__=1<br/>
  define: __STDC__=1<br/>
  define: __STRICT_ANSI__=1<br/>
  define: __UINT16_C_SUFFIX__=<br/>
  define: __UINT16_FMTX__="hX"<br/>
  define: __UINT16_FMTo__="ho"<br/>
  define: __UINT16_FMTu__="hu"<br/>
  define: __UINT16_FMTx__="hx"<br/>
  define: __UINT16_MAX__=65535<br/>
  define: __UINT16_TYPE__=unsigned short<br/>
  define: __UINT32_C_SUFFIX__=U<br/>
  define: __UINT32_FMTX__="X"<br/>
  define: __UINT32_FMTo__="o"<br/>
  define: __UINT32_FMTu__="u"<br/>
  define: __UINT32_FMTx__="x"<br/>
  define: __UINT32_MAX__=4294967295U<br/>
  define: __UINT32_TYPE__=unsigned int<br/>
  define: __UINT64_C_SUFFIX__=ULL<br/>
  define: __UINT64_FMTX__="llX"<br/>
  define: __UINT64_FMTo__="llo"<br/>
  define: __UINT64_FMTu__="llu"<br/>
  define: __UINT64_FMTx__="llx"<br/>
  define: __UINT64_MAX__=18446744073709551615ULL<br/>
  define: __UINT64_TYPE__=long long unsigned int<br/>
  define: __UINT8_C_SUFFIX__=<br/>
  define: __UINT8_FMTX__="hhX"<br/>
  define: __UINT8_FMTo__="hho"<br/>
  define: __UINT8_FMTu__="hhu"<br/>
  define: __UINT8_FMTx__="hhx"<br/>
  define: __UINT8_MAX__=255<br/>
  define: __UINT8_TYPE__=unsigned char<br/>
  define: __UINTMAX_C_SUFFIX__=ULL<br/>
  define: __UINTMAX_FMTX__="llX"<br/>
  define: __UINTMAX_FMTo__="llo"<br/>
  define: __UINTMAX_FMTu__="llu"<br/>
  define: __UINTMAX_FMTx__="llx"<br/>
  define: __UINTMAX_MAX__=18446744073709551615ULL<br/>
  define: __UINTMAX_TYPE__=long long unsigned int<br/>
  define: __UINTMAX_WIDTH__=64<br/>
  define: __UINTPTR_FMTX__="llX"<br/>
  define: __UINTPTR_FMTo__="llo"<br/>
  define: __UINTPTR_FMTu__="llu"<br/>
  define: __UINTPTR_FMTx__="llx"<br/>
  define: __UINTPTR_MAX__=18446744073709551615ULL<br/>
  define: __UINTPTR_TYPE__=long long unsigned int<br/>
  define: __UINTPTR_WIDTH__=64<br/>
  define: __UINT_FAST16_FMTX__="hX"<br/>
  define: __UINT_FAST16_FMTo__="ho"<br/>
  define: __UINT_FAST16_FMTu__="hu"<br/>
  define: __UINT_FAST16_FMTx__="hx"<br/>
  define: __UINT_FAST16_MAX__=65535<br/>
  define: __UINT_FAST16_TYPE__=unsigned short<br/>
  define: __UINT_FAST32_FMTX__="X"<br/>
  define: __UINT_FAST32_FMTo__="o"<br/>
  define: __UINT_FAST32_FMTu__="u"<br/>
  define: __UINT_FAST32_FMTx__="x"<br/>
  define: __UINT_FAST32_MAX__=4294967295U<br/>
  define: __UINT_FAST32_TYPE__=unsigned int<br/>
  define: __UINT_FAST64_FMTX__="llX"<br/>
  define: __UINT_FAST64_FMTo__="llo"<br/>
  define: __UINT_FAST64_FMTu__="llu"<br/>
  define: __UINT_FAST64_FMTx__="llx"<br/>
  define: __UINT_FAST64_MAX__=18446744073709551615ULL<br/>
  define: __UINT_FAST64_TYPE__=long long unsigned int<br/>
  define: __UINT_FAST8_FMTX__="hhX"<br/>
  define: __UINT_FAST8_FMTo__="hho"<br/>
  define: __UINT_FAST8_FMTu__="hhu"<br/>
  define: __UINT_FAST8_FMTx__="hhx"<br/>
  define: __UINT_FAST8_MAX__=255<br/>
  define: __UINT_FAST8_TYPE__=unsigned char<br/>
  define: __UINT_LEAST16_FMTX__="hX"<br/>
  define: __UINT_LEAST16_FMTo__="ho"<br/>
  define: __UINT_LEAST16_FMTu__="hu"<br/>
  define: __UINT_LEAST16_FMTx__="hx"<br/>
  define: __UINT_LEAST16_MAX__=65535<br/>
  define: __UINT_LEAST16_TYPE__=unsigned short<br/>
  define: __UINT_LEAST32_FMTX__="X"<br/>
  define: __UINT_LEAST32_FMTo__="o"<br/>
  define: __UINT_LEAST32_FMTu__="u"<br/>
  define: __UINT_LEAST32_FMTx__="x"<br/>
  define: __UINT_LEAST32_MAX__=4294967295U<br/>
  define: __UINT_LEAST32_TYPE__=unsigned int<br/>
  define: __UINT_LEAST64_FMTX__="llX"<br/>
  define: __UINT_LEAST64_FMTo__="llo"<br/>
  define: __UINT_LEAST64_FMTu__="llu"<br/>
  define: __UINT_LEAST64_FMTx__="llx"<br/>
  define: __UINT_LEAST64_MAX__=18446744073709551615ULL<br/>
  define: __UINT_LEAST64_TYPE__=long long unsigned int<br/>
  define: __UINT_LEAST8_FMTX__="hhX"<br/>
  define: __UINT_LEAST8_FMTo__="hho"<br/>
  define: __UINT_LEAST8_FMTu__="hhu"<br/>
  define: __UINT_LEAST8_FMTx__="hhx"<br/>
  define: __UINT_LEAST8_MAX__=255<br/>
  define: __UINT_LEAST8_TYPE__=unsigned char<br/>
  define: __USER_LABEL_PREFIX__=<br/>
  define: __VERSION__="Clang 15.0.0 (https://github.com/llvm/llvm-project.git 4ba6a9c9f65bbc8bd06e3652cb20fd4dfc846137)"<br/>
  define: __WCHAR_MAX__=65535<br/>
  define: __WCHAR_TYPE__=unsigned short<br/>
  define: __WCHAR_UNSIGNED__=1<br/>
  define: __WCHAR_WIDTH__=16<br/>
  define: __WIN32=1<br/>
  define: __WIN32__=1<br/>
  define: __WIN64=1<br/>
  define: __WIN64__=1<br/>
  define: __WINNT=1<br/>
  define: __WINNT__=1<br/>
  define: __WINT_MAX__=65535<br/>
  define: __WINT_TYPE__=unsigned short<br/>
  define: __WINT_UNSIGNED__=1<br/>
  define: __WINT_WIDTH__=16<br/>
  define: __amd64=1<br/>
  define: __amd64__=1<br/>
  define: __cdecl=__attribute__((__cdecl__))<br/>
  define: __clang__=1<br/>
  define: __clang_literal_encoding__="UTF-8"<br/>
  define: __clang_major__=15<br/>
  define: __clang_minor__=0<br/>
  define: __clang_patchlevel__=0<br/>
  define: __clang_version__="15.0.0 (https://github.com/llvm/llvm-project.git 4ba6a9c9f65bbc8bd06e3652cb20fd4dfc846137)"<br/>
  define: __clang_wide_literal_encoding__="UTF-16"<br/>
  define: __code_model_small__=1<br/>
  define: __cplusplus=201703L<br/>
  define: __declspec(a)=__attribute__((a))<br/>
  define: __fastcall=__attribute__((__fastcall__))<br/>
  define: __k8=1<br/>
  define: __k8__=1<br/>
  define: __llvm__=1<br/>
  define: __pascal=__attribute__((__pascal__))<br/>
  define: __pic__=2<br/>
  define: __private_extern__=extern<br/>
  define: __seg_fs=__attribute__((address_space(257)))<br/>
  define: __seg_gs=__attribute__((address_space(256)))<br/>
  define: __stdcall=__attribute__((__stdcall__))<br/>
  define: __thiscall=__attribute__((__thiscall__))<br/>
  define: __tune_k8__=1<br/>
  define: __x86_64=1<br/>
  define: __x86_64__=1<br/>
  define: _cdecl=__attribute__((__cdecl__))<br/>
  define: _fastcall=__attribute__((__fastcall__))<br/>
  define: _pascal=__attribute__((__pascal__))<br/>
  define: _stdcall=__attribute__((__stdcall__))<br/>
  define: _thiscall=__attribute__((__thiscall__))<br/>
  define: _DEBUG<br/>
  define: UNICODE<br/>
  define: _UNICODE<br/>
  other: --clang<br/>
  other: --clang_version=150000<br/>
  other: --ms_extensions<br/>
  stdver: c++17<br/>
  intelliSenseMode: windows-clang-x64<br/>
Queueing IntelliSense update for files in translation unit of: E:\Picross Solver\src	est.cpp<br/>
LSP: cpptools/getCodeActions: file:///e%3A/Picross%20Solver/src/test.cpp (id: 157)<br/>
0 include path suggestion(s) discovered.<br/>
Error squiggle count: 3<br/>
Error squiggles will be disabled in: file:///E%3A/Picross%20Solver/src/test.cpp<br/>
Update IntelliSense time (sec): 0.763<br/>
LSP: cpptools/getSemanticTokens: file:///e%3A/Picross%20Solver/src/test.cpp (id: 158)<br/>
LSP: cpptools/getFoldingRanges: file:///e%3A/Picross%20Solver/src/test.cpp (id: 159)<br/>
LSP: cpptools/getCodeActions: file:///e%3A/Picross%20Solver/src/test.cpp (id: 160)<br/>
0 include path suggestion(s) discovered.<br/>
</details>

**Comment by sean-mcmanus** [comment] 2023-05-11 22:23
This may be a regression due to https://github.com/microsoft/vscode-cpptools/issues/8353. Can you try adding "-fno-ms-extensions" to your compilerArgs property?

**Comment by Joekeen03** [comment] 2023-05-11 22:50
Added that, seems to be working now, based on a couple different test files.

**Comment by Colengms** [comment] 2023-05-11 23:15
This may be related to a define emitted for IntelliSense that is not emitted when building, related to use of the `--ms-extensions`.  Would it be possible to narrow down which define seems to differ between IntelliSense and real compilation?

Since I don't see that you're providing `--ms-extensions` in your configuration, the C/C++ extension could be incorrectly detecting that they should be used, perhaps due to a particular defined generated by your compiler (i.e. `_MSC_EXTENSIONS`) which is assumed to only be present when `--ms-extensions` are enabled.

(1727247)

**Comment by sean-mcmanus** [comment] 2023-05-11 23:18
@Colengms Yeah, as a result of https://github.com/microsoft/vscode-cpptools/issues/8353 we're adding -fms-extensions whenever `__MINGW32__` is defined.

**Comment by adalsteinnh** [comment] 2023-05-15 17:27
I noticed the same problem and i think it boils down to _MSC_VER definition being emitted for IntelliSense and not when building using clang.

Some C++ headers include `<exception>` which contains this:

```
#if defined(_LIBCPP_ABI_VCRUNTIME)
#  include <vcruntime_exception.h>
#endif
```

_LIBCPP_ABI_VCRUNTIME is defined in `<__config>` which exception includes. Therein you find the following:

```
#  if defined(_LIBCPP_ABI_FORCE_ITANIUM) && defined(_LIBCPP_ABI_FORCE_MICROSOFT)
#    error "Only one of _LIBCPP_ABI_FORCE_ITANIUM and _LIBCPP_ABI_FORCE_MICROSOFT can be defined"
#  elif defined(_LIBCPP_ABI_FORCE_ITANIUM)
#    define _LIBCPP_ABI_ITANIUM
#  elif defined(_LIBCPP_ABI_FORCE_MICROSOFT)
#    define _LIBCPP_ABI_MICROSOFT
#  else
#    if defined(_WIN32) && defined(_MSC_VER)
#      define _LIBCPP_ABI_MICROSOFT
#    else
#      define _LIBCPP_ABI_ITANIUM
#    endif
#  endif
```

All the parts are grayed out in the editor except for this one:

```
if defined(_WIN32) && defined(_MSC_VER)
#      define _LIBCPP_ABI_MICROSOFT
#    else
```

The following code demonstrates how it is actually defined in the build:

```
#include <cstdio>
#include <new>

int main(){
    #if defined(_LIBCPP_ABI_VCRUNTIME)
    printf("_LIBCPP_ABI_VCRUNTIME is defined\n");
    #else
    printf("_LIBCPP_ABI_VCRUNTIME is not defined\n");
    #endif
    #if defined(_LIBCPP_ABI_ITANIUM)
    printf("_LIBCPP_ABI_ITANIUM is defined\n");
    #else
    printf("_LIBCPP_ABI_ITANIUM is not defined\n");
    #endif
    #if defined(_MSC_VER)
    printf("_MSC_VER is defined\n");
    #else
    printf("_MSC_VER is not defined\n");
    #endif
    return 0;
}
```

This outputs:

> _LIBCPP_ABI_VCRUNTIME is not defined
> _LIBCPP_ABI_ITANIUM is defined
> _MSC_VER is not defined

**Comment by sean-mcmanus** [comment] 2023-05-15 17:43
Yeah, the _MSV_VER being defined is https://github.com/microsoft/vscode-cpptools/issues/10396 , so that's why -fms-extensions doesn't work (having -fms-extensions be the default may still be a regression bug though).

**Comment by michelleangela** [comment] 2023-05-23 00:37
This is resolved in https://github.com/microsoft/vscode-cpptools/releases/tag/1.16.0.

**Closed as completed** 2023-07-20 23:09 UTC
Labels: bug, Language Service, fixed, regression, Feature: Configuration
