### ISSUE TITLE
How to show class and function in top file status bar when cursor stay

### ISSUE THREAD

**Issue by daoluan** [microsoft/vscode-cpptools#11777] opened 2023-12-13 04:17 UTC
### Feature Request

![image](https://github.com/microsoft/vscode-cpptools/assets/2241128/74169cd8-ed43-469a-996c-7a64b9c1a1e8)

**Comment by sean-mcmanus** [comment] 2023-12-13 23:01
This is a known issue. Duplicate of https://github.com/microsoft/vscode-cpptools/issues/10944 .

**Closed as not planned by sean-mcmanus** 2023-12-13 23:01 UTC
Labels: duplicate
