### ISSUE TITLE
Press ctrl and mouse hover to key word will replace to the head file content.

### ISSUE THREAD

**Issue by TheBigFish** [microsoft/vscode-cpptools#4006] opened 2019-07-31 03:46 UTC
When open the c file, such as `test.c`, press ctrl key , and mouse hover to a key word, such as `uint16_t`, the c file content will be replaced by the head file, which include the definition of  `uint16_t`。

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10334759/62180777-c5ac4580-b383-11e9-8dbc-588f82785e61.gif)

**Comment by sean-mcmanus** [comment] 2019-07-31 23:51
I remember this being reported previously, but I can't find that issue now.

I'm not able to repro the bug. Do you have any additional details that might help identify what the repro requirements are?

**Comment by bobbrow** [comment] 2019-08-01 19:53
Is it actually writing the contents of the header into `test.c`, or is VS Code just closing `test.c` and opening the header in the same tab? (sorry, your GIF doesn't include the tab name so I can't tell)

This feature is controlled with the `workbench.editor.enablePreview` setting:
![image](https://user-images.githubusercontent.com/12818240/62322963-1642a200-b45b-11e9-8cc0-baf0b83441ed.png)

**Comment by TheBigFish** [comment] 2019-08-02 05:10
> Is it actually writing the contents of the header into `test.c`, or is VS Code just closing `test.c` and opening the header in the same tab? (sorry, your GIF doesn't include the tab name so I can't tell)
> 
> This feature is controlled with the `workbench.editor.enablePreview` setting:
> ![image](https://user-images.githubusercontent.com/12818240/62322963-1642a200-b45b-11e9-8cc0-baf0b83441ed.png)

**Comment by TheBigFish** [comment] 2019-08-02 05:13
It actually writing the  whole contents of the heade into test.c. It is not the preview future.

**Comment by bobbrow** [comment] 2020-03-19 21:25
We are unable to reproduce this bug.  If you can provide more information about how this happens, we can take a further look.

**Closed as completed by bobbrow** 2020-03-19 21:25 UTC
Labels: bug, Language Service, not reproing, Feature: Go to Definition

**Comment by sean-mcmanus** [comment] 2020-03-19 21:31
Or if you still repro it you should file a bug with VS Code itself: https://github.com/microsoft/vscode/issues
