### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by amrur** [microsoft/vscode-cpptools#3303] opened 2019-03-15 19:15 UTC
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.21.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\PC\ms-vscode.cpptools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bobbrow** [comment] 2019-03-15 19:47
Thank you for your issue report. This looks like a duplicate of #3213.

**Closed as completed by bobbrow** 2019-03-15 19:47 UTC
