### ISSUE TITLE
\u0000 in comment terminates the comment show in hover tip

### ISSUE THREAD

**Issue by kkkiio** [microsoft/vscode-cpptools#7950] opened 2021-08-10 15:52 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: windows 10
- VS Code Version: 1.59.0
- C/C++ Extension Version: v1.5.1
- Other extensions you installed (and if the issue persists after disabling them): wsl remote

**Steps to reproduce**

1. hover over the function name

**Expected behavior**
show the full comment, eg. `Make sure the given Mem is \u0000 terminated.`

**Code sample and logs**

- Code sample

```c
/*
** Make sure the given Mem is \u0000 terminated.
*/
int sqlite3VdbeMemNulTerminate(Mem *pMem){
  assert( pMem->db==0 || sqlite3_mutex_held(pMem->db->mutex) );
  testcase( (pMem->flags & (MEM_Term|MEM_Str))==(MEM_Term|MEM_Str) );
  testcase( (pMem->flags & (MEM_Term|MEM_Str))==0 );
  if( (pMem->flags & (MEM_Term|MEM_Str))!=MEM_Str ){
    return SQLITE_OK;   /* Nothing to do */
  }else{
    return vdbeMemAddTerminator(pMem);
  }
}
```

**Screenshots**
![hover_comment](https://user-images.githubusercontent.com/12840157/128894567-b01be1b1-caf1-474d-8bd2-40eec46a2f21.png)

**Comment by michelleangela** [comment] 2021-08-10 19:15
Closing as a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6084, which is related to the Visual Studio issue reported at https://developercommunity.visualstudio.com/t/%E6%B3%A8%E9%87%8A%E4%B8%AD%E5%A6%82%E6%9E%9C%E5%87%BA%E7%8E%B0%E4%BA%86%E5%AD%97%E7%AC%A6-0-%E4%BC%9A%E5%AF%BC%E8%87%B4%E5%AD%97%E7%AC%A6-0-%E4%B9%8B%E5%90%8E%E7%9A%84%E6%B3%A8%E9%87%8A%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA/1081005 

Please upvote the Visual Studio to increase its priority.

**Closed as completed by michelleangela** 2021-08-10 19:15 UTC
Labels: duplicate, Language Service, Feature: Doc comments
