### ISSUE TITLE
syntax hignlight may not work well in WSL2

### ISSUE THREAD

**Issue by jwf11** [microsoft/vscode-cpptools#8160] opened 2021-09-16 07:49 UTC
syntax hignlight may not work well in WSL2
![image](https://user-images.githubusercontent.com/49466253/133571967-ed14d827-9fae-44a0-a052-7dddc4368c32.png)

**Comment by michelleangela** [comment] 2021-09-16 21:13
@jwf11 
Could you try disabling the C++ extensions and see if the issue still reproduces? Does this issue also reproduce for all source code or to just certain files?

**Comment by jwf11** [comment] 2021-09-17 03:46
@michelleangela 
It reproduces for all source code and everything is fine if i disabled the C/C++ extension.  by the way, the problem will be fixed when I restart vscode and reconnect to WSL2, but it won't work for long(may be after changing several characters or adding some comments).

**Comment by Colengms** [comment] 2021-09-17 18:40
Hi @jwf11 .  Since this does not happen with the C/C++ extension (and semantic highlighting) disabled, this would seem to have something to do with semantic highlighting provided by the C/C++ extension.

Is it necessary to edit the file to cause the issue to occur?

Does the issue ever occur with the same file outside of WSL2?

Are you able to reproduce a similar issue with other languages that use VS Code's semantic highlighting API (such as TypeScript or Java) ?

If the ranges are correct without WSL2, and the issue can be reproduced with other languages, it is likely a VS Code issue.  If so, I'd suggest opening an issue in the [VS Code repo](https://github.com/microsoft/vscode/issues).  (They might assume the issue is with the C/C++ extension, so you might want to indicate you have contacted us about it, and it looks to us like a VS Code issue).

Even if an edit is involved in reproducing the issue, VS Code should be adjusting ranges to compensate for those edits.  The C/C++ extension will also discard/regenerate ranges whenever we detect a file has changed, instead of returning stale ranges.  If the issue does not happen for the same files outside of WSL2 (and same IntelliSense configuration), the problem may be with how VS Code is maintaining those ranges, not that the C/C++ extension is failing to generate them correctly.

**Comment by jwf11** [comment] 2021-09-18 03:40
Is it necessary to edit the file to cause the issue to occur?
A: yes. it won't be a problem if i don't edit it.
Does the issue ever occur with the same file outside of WSL2?
A: yes. just in WSL2.
Are you able to reproduce a similar issue with other languages that use VS Code's semantic highlighting API (such as TypeScript or Java) ?
A: no. the problem just occurs in C.
![image](https://user-images.githubusercontent.com/49466253/133871326-3b4a5828-241a-4183-84aa-804edd912905.png)
and it recognizes some incorrect information. such as recognize `struct a` to `int x`

**Comment by Colengms** [comment] 2021-09-20 18:14
Hi @jwf11 .  It is interesting that a hover operation is displaying info for a different line.  That would seem to imply the C/C++ extension is not tracking line positions correctly.  Did that repro after adding or removing multiple lines?  Are you editing files in another editor at the same time as the file is open in VS Code?  Are you modifying files that actually reside on the WSL2 file system, or the Windows file system via a mount point?  Perhaps you are mixing access to those files from WSL2 paths and Windows paths?  Does the same issue occur if the files are stored entirely on the WSL2 file system?

I'm not aware of other reports of this behavior, so there would seem to be something about your environment or scenario that we may need to better understand to determine what's happening.

**Comment by jwf11** [comment] 2021-09-27 01:55
I have changed several vscode versions and c/c++ plugin versions, and I also have re-installed ubuntu wsl from 18.04 to 20.04, however it did not work. Finally, I re-installed os, and the problem is solved. Anyway, thanks for answering.

**Comment by Colengms** [comment] 2021-09-27 18:35
Hi @jwf11.  Thanks for letting us know.  I'll go ahead and close this issue for now.

**Closed as completed by Colengms** 2021-09-27 18:35 UTC
Labels: Language Service, more info needed, Feature: Colorization
