### ISSUE TITLE
VSCode C++ cin/cout/endl was not declared

### ISSUE THREAD

**Issue by FayeeLee** [microsoft/vscode-cpptools#6082] opened 2020-09-04 05:47 UTC
properities.json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "D:\\vscode\\mingw64\\bin\\gcc.exe",
            "cStandard": "c11",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}

tasks.json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "task g++",
			"command": "D:\\vscode\\mingw64\\bin\\g++.exe",
			"args": [
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "${workspaceFolder}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"presentation": {
				"echo": true,
				"reveal": "always",
				"focus": false,
				"panel": "new", //这里shared表示共享，改成new之后每个进程创建新的端口
				"showReuseMessage": true,
				"clear": false
			},

			"group": "build"
		}
	]
}

launch.json
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe - 生成和调试活动文件",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "D:\\vscode\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "为 gdb 启用整齐打印",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "task g++"
        }
    ]
}

the complier path is right. when I add cin/cout/endl into my cpp code it shows these was not declared

**Comment by sean-mcmanus** [comment] 2020-09-04 17:16
Can you provide the exact error message? Is this error from compiling or IntelliSense? Information from running C/C++: Log Diagnostics may help as well.

**Comment by michelleangela** [comment] 2020-12-09 18:35
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Closed as completed by michelleangela** 2020-12-09 18:35 UTC
Labels: Language Service, more info needed, Feature: Configuration
