### ISSUE TITLE
I can't type

### ISSUE THREAD

**Issue by D-Chic** [microsoft/vscode-cpptools#6357] opened 2020-10-20 16:22 UTC
Issue Type: <b>Bug</b>

The editing page doesn't show the normal cursor blinker but a blinking rectangle and now I can't type my code

Extension version: 1.1.0-insiders2
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|32, 13, 5|
|Memory (System)|4.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id c5038f4f-3b8d-463c-a788-fc44ad3d5e09|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment] 2020-10-20 23:39
Hi @D-Chic  Does this repro with the C/C++ Extension disabled?  If not, are there any particular repro steps, or other clues you could share?  Or, if it does not repro when disabled, you might consider following up in: https://github.com/microsoft/vscode


A editor UI issue would seem to be a VS Code issue.  I'm not aware of how the extension should have this effect in the editor itself.

**Comment by michelleangela** [comment] 2020-12-09 18:31
Closing this issue because it has not had recent activity. Please installing the latest version of the C++ extension to see if the issue still reproduces or has been fixed.

**Closed as completed by michelleangela** 2020-12-09 18:31 UTC
Labels: Language Service, more info needed
