### ISSUE TITLE
IntelliSense false error `cannot call non-constexpr function "std::array<_Tp, _Nm>::array()"` 

### ISSUE THREAD

**Issue by discapes** [microsoft/vscode-cpptools#6395] opened 2020-10-26 20:26 UTC
**Type: LanguageService**

- OS and Version: Linux arch 5.9.1-arch1-1
- VS Code Version: 1.51.0-insider (f5d3ba4d61146b78f0c75c82f3f85232d3409bc1)
- C/C++ Extension Version: v1.1.0-insiders3

**Steps to reproduce**

1. Open a new folder and add a .cpp file
2. Add this code to the file
```
#include <array>
template <typename T> struct S {
	T x{};
};
template <int N> constexpr std::array<S<int>, N> func()
{
	std::array<S<int>, N> arr;
	return arr;
}
constexpr auto var = func<5>();
```
Compiling with g++ bug.cpp -c gives out no errors or warnings, but IntelliSense raises an error on the last line:
```
constexpr std::array<S<int>, 5UL> func<5>()
______________________________________________
expression must have a constant value
 -- cannot call non-constexpr function "std::array<_Tp, _Nm>::array() [with _Tp=S<int>, _Nm=5UL]" 
(declared implicitly)C/C++(28)
```
This shouldn't happen, since the code works fine.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 10/26/2020, 10:23:57 PM
Version: 1.1.0-insiders3
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/miika/code/cpp/bug.cpp ]:
    /home/miika/code/cpp/bug.cpp
Translation Unit Configurations:
[ /home/miika/code/cpp/bug.cpp ]:
    Process ID: 60839
    Memory Usage: 29 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/10.2.0
        /usr/include/c++/10.2.0/x86_64-pc-linux-gnu
        /usr/include/c++/10.2.0/backward
        /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include
        /usr/local/include
        /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100200
Total Memory Usage: 29 MB
```
</details>

**Comment by sean-mcmanus** [comment] 2020-10-26 20:49
I think this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/5833 (which is tracking https://developercommunity.visualstudio.com/content/problem/1127113/c-intellisense-gives-the-error-expression-must-hav.html ).

But we can keep this open to make sure it's fixed when the other issue is fixed.

**Comment by bobbrow** [comment] 2020-11-05 22:40
Closing as duplicate of #5833

**Closed as completed by bobbrow** 2020-11-05 22:40 UTC
Labels: bug, duplicate, Language Service, external, Visual Studio
