### ISSUE TITLE
Goto definition only goes to declaration in headers when using a compile_commands.json

### ISSUE THREAD

**Issue by smwikipedia** [microsoft/vscode-cpptools#4059] opened 2019-08-10 08:36 UTC
**Type: LanguageService**

My source tree is built with CMake/Ninja. I generated a "compile_commands.json" file from my Ninja build system and put it in the c_cpp_properties.json file. I did this in the hope that I can quickly configure the include search paths, defines, etc. 

The **c_cpp_properties.json**: (**Note that I am using the ARM toolchain. I choose gcc-X64 for intelliSenseMode because I have no better option.**)

```
{
    "configurations": 
    [
        {
            "name": "MyConfig", 
            "compilerPath": "c:\\gnuarmemb\\bin\\arm-none-eabi-gcc.exe", 
            "cStandard": "c99", 
            "cppStandard": "c++11", 
            "intelliSenseMode": "gcc-x64", 
            "compileCommands": "C:\\build\\helloworld.ARM\\compile_commands.json"}
    ], 
    "version": 4
}
```
The **settings.json**:

```
{
	"files.exclude":
	{
		"**/.github": true,
		"**/.known-issues": true,
		"**/.vscode": true,
		"**/.*": true,
		".vscode": false
	},
	"C_Cpp.exclusionPolicy": "checkFilesAndFolders",
	"cmake.configureOnOpen": false
}
```

**Describe the bug**
Then I open the source folder in VSCode. All symbols and include headers seem to be resolved successfully because there are no error squiggles. 

But when I press `F12` on a function call, if the function is **defined in some other c file**, it only jumps to the **declaration** of that function in some header rather than **definitions**. Such as below one. Note the **extern** keyword.

![image](https://user-images.githubusercontent.com/999318/62821658-e017c780-bbaa-11e9-8871-f910d599c6ce.png)

If the function is defined within the **same** c file, the goto definition works well.

**So it seems the CPP extension doesn't go looking for **extern** function definitions even that function is defined in a c file within the opened folder.** This behavior is different from Visual Studio, which will check all the files within current solution.

Is there any way to fix this?

- OS and Version:
`Windows 10 Version 1709 (Build 16299.1268)`

- VS Code Version:
```
Version: 1.37.0 (user setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299
```

- C/C++ Extension Version:
`0.25.0-insiders`

- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by smwikipedia** [comment] 2019-08-10 13:59
This issue seems similar: https://github.com/Microsoft/vscode-cpptools/issues/3157 but actually not. Because I don't have void arg list.

**Comment by smwikipedia** [comment] 2019-08-10 14:02
...but my scenario is not a void arg list.

**Comment by smwikipedia** [comment] 2019-08-11 04:21
I tried to reproduce the issue with below steps:

1. reconstruct the folder/file structure
2. reconstruct the file content
3. manually configure the include path

The goto definition works fine with above 3 steps.

The only difference is step 3. **I directly configure the include path instead of using a compile_commands.json file**

Below are the logs for good and bad scenarios:

### Good:

```
-------- Diagnostics - 8/11/2019, 12:31:48 PM
Version: 0.25.0-insiders
Current Configuration:
{
    "name": "Zephyr",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "compilerPath": "c:\\gnuarmemb\\bin\\arm-none-eabi-gcc.exe",
    "cStandard": "c99",
    "cppStandard": "c++11",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.

```

### Bad:

```
-------- Diagnostics - 8/11/2019, 12:32:41 PM
Version: 0.25.0-insiders
Current Configuration:
{
    "name": "Zephyr",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "compilerPath": "c:\\gnuarmemb\\bin\\arm-none-eabi-gcc.exe",
    "cStandard": "c99",
    "cppStandard": "c++11",
    "intelliSenseMode": "gcc-x64",
    "compileCommands": "C:\\build\\compile_commands.json"
}
No active translation units.

```

**Comment by smwikipedia** [comment] 2019-08-11 09:37
I guess I found the root cause.

I just noticed below icon:

![image](https://user-images.githubusercontent.com/999318/62832246-f16ddc00-bc5d-11e9-99c7-139343f4820c.png)

It seems the file parsing takes quite some time. Much longer than I expected.

I hovered my icon on it and see below progress:

![image](https://user-images.githubusercontent.com/999318/62832235-d307e080-bc5d-11e9-86e4-d468e2580292.png)

![image](https://user-images.githubusercontent.com/999318/62832316-d780c900-bc5e-11e9-92cc-0d2b12ff6dab.png)


I add below config to the c_cpp_properties.json:

```
            "browse": {
                "databaseFilename": "${workspaceFolder}/.vscode/browse.db"
            }
```

The I can see the browse.db file size is increasing.

After the parsing finished, **the database icon disappeared**, and the **goto definition** works well.

But the problem is, most of the time, the code parsing just keeps running forever and the database icon flashed and didn't show up, like below:

![image](https://user-images.githubusercontent.com/999318/62832778-a60bfb80-bc66-11e9-8228-160addaf0071.png)

And the **browse.db** file size freezes at 4KB after a 25 minutes wait. And there are 2 other files named **browse.db-shm** (32KB)  and **browse.db-wal** (1131KB) .  I tried many times, only for once I see the **browse.db** size reach more than 200M and the parsing icon says finished.

**Comment by smwikipedia** [comment] 2019-08-11 11:05
It seems I have to add below element to the c_cpp_properties.json file:

![image](https://user-images.githubusercontent.com/999318/62833034-b920ca80-bc6a-11e9-8664-bdfdb224e17c.png)

1. With above element, the database icon will show and it goes from "Discovering files..." -> "Parsing open files..."

2. Without above element, the data base icon will also show. But the "Discovering files" phase finished very quickly and found nothing. Then the "Parsing open files" phase just stay forever. And the browse.DB file freezes at 4KB.

And it seems I have to use the `"${workspaceFolder}"`. I tried to explicitly list the folders I want. But it failed as 2.

**Comment by smwikipedia** [comment] 2019-08-11 12:06
This issue is related to https://github.com/microsoft/vscode-cpptools/issues/4063.

**Comment by smwikipedia** [comment] 2019-08-11 12:07
I think this issue is caused by https://github.com/microsoft/vscode-cpptools/issues/4063.
This one can be closed.

**Comment by michelleangela** [comment] 2019-08-12 18:40
Closing this issue as duplicate of #4063

**Closed as completed by michelleangela** 2019-08-12 18:40 UTC
Labels: duplicate, Language Service
