### ISSUE TITLE
Enhanced colorization: less specific scopes override more specific ones

### ISSUE THREAD

**Issue by cengels** [microsoft/vscode-cpptools#6321] opened 2020-10-15 11:55 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Enterprise 10.0.18363
- VS Code Version: 1.50.1
- C/C++ Extension Version: issue occurs in at least v1.1.0-insiders and v1.0.1
- Other extensions you installed (and if the issue persists after disabling them): none that are relevant
- Does this issue involve using SSH remote to run the extension on a remote machine?: no

The issue is that the TextMate scopes supplied by the Enhanced Colorization seem to always take priority over any other scopes, *even* more specific ones.

For instance, here is the `entity.name.type` scope overriding the `entity.name.type.class` scope:
![image](https://user-images.githubusercontent.com/31248098/96117613-a77c2800-0eea-11eb-97dd-30f864fb8df6.png)

That should not happen. According to the official VS Code documentation, more specific scopes should always take precedence over less specific scopes.

Also (and I don't know if this is part of the issue or not), in the `inspect token` dialog, the foreground colour that takes precedence is displayed next to a separate `foreground` header in the section reserved for the semantic token highlighting. That doesn't really make sense to me, because the color in this case is being applied to a TextMate scope, not a semantic scope. For the screenshot above, no color for the semantic scope `type` is defined and, in fact, the issue still occurs even if semantic highlighting is completely disabled.

On a related note, most tokens seem to share the semantic scope `type`, which also doesn't seem right.

**Steps to reproduce**

1. Create a minimal C++ file, for instance containing a class:
```
class MyClass
{
    public:
        MyClass();
};
```
2. Make sure property `C_Cpp.enhancedColorization` is set to `Enabled` in `settings.json`
3. Create two new scoped token color customization rules for `entity.name.type` and `entity.name.type.class`, for instance:
```
"editor.tokenColorCustomizations": {
    "[Default Dark+]": {
        "textMateRules": [
            {
                "scope": "entity.name.type",
                "settings": {
                    "foreground": "#ff0000"
                }
            },
            {
                "scope": "entity.name.type.class",
                "settings": {
                    "foreground": "#0000ff"
                }
            }
        ]
    }
},
```
4. Use the `Inspect editor tokens and scopes` function and observe that the `entity.name.type` scope overrides the `entity.name.type.class` scope, which is struck out

**Expected behavior**
More specific scopes should override less specific scopes, not the other way around.

**Notes**
I'm filing this issue here instead of in the main VS Code repository because, so far, I've only had this issue occur in C++ when using the enhanced colorization. If this is a VS Code issue and not a cpptools issue, though, please let me know.

Also, let me know if more information is required.

**Comment by sean-mcmanus** [comment] 2020-10-15 19:16
@Colengms Do you have thoughts on this? This seems "by design" to me, since semantic scopes take precedence over syntactic scopes, and also in the types/class case, our IntelliSense parser gives us "types" and not class versus struct types. See https://code.visualstudio.com/docs/cpp/colorization-cpp and https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide .

**Comment by Colengms** [comment] 2020-10-15 20:06
@cengels 

It looks we need to update [this document](https://code.visualstudio.com/docs/cpp/colorization-cpp) to reflect the new approach for customizing semantic tokens, now that we've moved to VS Code's new Semantic Tokens API.  Those scopes will continue to be supported as a fallback, though colors associated directly with semantic tokens will lately take precedence.  The scopes in that document are still valid.

However, `entity.name.type.class` is not one of those scopes.  We do use some scopes more specific, such as `entity.name.type.class.templated`.  I don't believe you will be able to provide a separate color for regular classes vs types, as there is no distinction between these concepts in C++.  Our semantic token provider also does not distinguish between them.  The TextMate grammar for C/C++ in VS Code also does not return `entity.name.type.class` for classes.

**Comment by cengels** [comment] 2020-10-15 20:25
Ah, so in this case `entity.name.type` is a scope provided by the semantic token provider, but `entity.name.type.class` is provided by VS Code's "default" language engine and is therefore overwritten as a result?

I actually have no problem with not being able to style classes differently from other types. I suppose I'm just somewhat confused by the output of the "Inspect tokens and scopes" popup. Since it displays the `entity.name.type.class.cpp` scope at the top of the TextMate scopes, it seems reasonable to assume that `entity.name.type.class.cpp` would be the scope with the highest priority, not `entity.name.type`. Is there perhaps any way to make the "inspect tokens and scopes" popup more self-explanatory in this case?

Also, on a semi-related note, does the cpptools semantic token provider also not distinguish between normal member functions and constructors? Because the same problem arises with the `entity.name.function` scope, which always overrides the more specific scopes `entity.name.function.definition.special.constructor` and `entity.name.function.constructor`, making it impossible to style the constructor separately if the `entity.name.function` scope is defined. Is there a solution for this (aside from just not defining an `entity.name.function` scope)? The semantic token API itself does not seem to support a constructor scope right now.

**Comment by Colengms** [comment] 2020-10-15 20:57
> Since it displays the entity.name.type.class.cpp scope at the top of the TextMate scopes

Indeed.  I missed that.  It looks like the TextMate grammar is indeed returning `entity.name.type.class(.cpp)`.  I suspect it is the fact that a semantic token is associated which is preventing it from using the color you are associated with the TextMate scope.  

> Is there perhaps any way to make the "inspect tokens and scopes" popup more self-explanatory in this case?

The semantic token should be specified in the `Inspect Editor Tokens And Scopes` window.  As far as how to make it more self-explanatory, I'd have to defer to VS Code folks.

>Also, on a semi-related note, does the cpptools semantic token provider also not distinguish between normal member functions and constructors?

Indeed, that is the case.  The number of semantic tokens currently supported is much more limited than the number of TextMate scopes that are possible.  It is possible for us to add custom semantic tokens.  We share IntelliSense with VS, and semantic tokens are derived from an IntelliSense pass.  VS also does not distinguish between constructors and member functions.  So, new semantic tokens would likely start as feedback to VS to add additional semantic tokens to IntelliSense.

**Comment by cengels** [comment] 2020-10-15 21:11
Thanks again for taking the time to have a look at this issue with me. If there is no semantic scope for constructors, that doesn't bother me too much at the moment, especially since the same can still be achieved with TextMate scopes, even if it is a bit more convoluted to do so.

> > Since it displays the entity.name.type.class.cpp scope at the top of the TextMate scopes
> 
> Indeed. I missed that. It looks like the TextMate grammar is indeed returning `entity.name.type.class(.cpp)`. I suspect it is the fact that a semantic token is associated which is preventing it from using the color you are associated with the TextMate scope.

But unless I'm mistaken, the semantic scope in this case is just simply `type` while `entity.name.type` is a TextMate scope, correct? In my example, I made sure that there was no customization specified for any semantic scopes—in fact, I turned semantic highlighting off entirely for that screenshot, so no semantic tokens should be applied at all. Unless there is something else that I'm not understanding about the way semantic tokens and TextMate tokens play together, that can't be it, can it?

As mentioned, the same problem also arises with the `entity.name.function` scope. Constructors in C++ for instance are marked with the scope `entity.name.function.constructor` (among others), but if a customization for `entity.name.function` is already defined, the customization for `entity.name.function.constructor` is completely ignored.

I understand that semantic tokens should by design override syntactic tokens, but in this case (again: unless I'm misinterpreting something) it's actually a less specific syntactic token that is overriding a more specific syntactic token, which feels like a bug to me. Feel free to correct me though.

**Comment by Colengms** [comment] 2020-10-15 21:33
@cengels We provide semantic token scopes, and a mapping from those to the TextMate scopes we had used prior to switching to VS Code's new Semantic Tokens API (to hopefully ensure uses of our previous implementation were not broken).  Whether VS Code considers more or less specific TextMate scopes when matching against our 'fallback' scopes for semantic tokens, would seem to be VS Code behavior.

>In my example, I made sure that there was no customization specified for any semantic scopes—in fact, I turned semantic highlighting off entirely for that screenshot, so no semantic tokens should be applied at all.

That should take the C/C++ Extension out of the picture.  You might try disabling our support for semantic tokens using `"C_Cpp.enhancedColorization": "Disabled"`, and reloading the window (as VS Code currently doesn't remove existing semantic token colorization in response to setting changes.  https://github.com/microsoft/vscode/issues/97196 ).  Or, disabling the C/C++ Extension entirely.  Then you should be looking only at VS Code's behavior for matching color customizations with TextMate scopes based on VS Code's TextMate grammar.

If the issue is either of the what I mentioned above, I'd suggest following up by opening an issue in the VS Code repo.

**Comment by cengels** [comment] 2020-10-15 21:45
Ah, I see. I didn't realize linking a TextMate scope to a semantic scope was possible—my bad! That would probably explain it then. If I understand correctly now, several scopes that *look* like TextMate scopes (like `entity.name.type`) are actually mapped to semantic scopes and are therefore for all intents and purposes semantic highlighting. If that's the case, I'm not sure this would be an actionable issue in the main VS Code repo.

In that case, I would only offer the suggestion to perhaps implement a setting for the extension that allows a user to disable these syntactic-to-semantic token mappings (if that's even possible to conditionally configure). That way one could design a VS Code theme that explicitly uses the new Semantic Token API while still providing some color customizations for TextMate tokens without the fallbacks interfering in any way. But that's not a priority. If you think this is either to difficult to implement or just not worth the time investment, I would be okay with that.

By the way, I did try disabling the enhanced colorization, but as mentioned in the original issue, this issue only pops up with `C_Cpp.enhancedColorization` enabled, most likely because of those fallback scopes you mentioned. Why those fallback scopes seem to take precedence over any other "normal" TextMate scope even if semantic highlighting is completely turned off I don't know, but it also doesn't seem too important.

Thanks again for taking the time.

**Comment by Colengms** [comment] 2020-10-15 22:03
@cengels I'm not sure I follow.  The reason `MyClass` is colored as `entity.name.type` when semantic colorization is enabled, is because `MyClass` is identified as a semantic token of `type`, and it's falling back to the color associated with the TextMate scope `entity.name.type` because there is no color associated with the `type` semantic token.  This is because our semantic token provider does not differentiate between 'type' and 'class', so we don't have enough information to distinguish between the two concepts.  Arguably, there is no difference between the two concepts in C++.  If we were to map the token to `entity.name.type.class`, we would instead incorrectly color some types that were not explicitly declared using `class`.  Anything not identified as a semantic token should still be colored using TextMate scope settings, without semantic token fallback scopes interfering with them.  Let me know if there is something I'm missing.

**Comment by cengels** [comment] 2020-10-16 07:01
I'm not sure if there is something you are missing or something I am missing. First of all, though,

>  The reason `MyClass` is colored as `entity.name.type` when semantic colorization is enabled

But that's the thing—unless we're talking about a different thing here, in all of my tests I *explicitly disabled* semantic highlighting (`"editor.semanticHighlighting.enabled": false` in `settings.json`). The cpptools extension does not seem to honour that setting though. I don't know if that's a bug or if it's by design (maybe `"C_Cpp.enhancedColorization": "Enabled"` overrides it?).

> If we were to map the token to `entity.name.type.class`, we would instead incorrectly color some types that were not explicitly declared using `class`.

Yes, I'm not suggesting changing the mapping or anything. The thing I'm getting hung up on is that, in its current state, the *syntactic* token provider does actually apply an `entity.name.type.class(.cpp)` scope to all class declarations. Not to all class *usages*, of course, as that falls under the purview of the semantic token provider, and as you've stated, the semantic token provider cannot distinguish between classes and other types as C++ itself does not distinguish between them.

It just seems strange to me that the TextMate scope `entity.name.type.class` *appears* but essentially cannot be used unless there is no colour defined for the `entity.name.type` scope.

Now I don't particularly care about class colours, but it would be nice to be able to colourize a constructor. Even if the semantic token provider does not distinguish between normal member functions, the *syntactic* token provider *does* distinguish between normal member functions and constructor functions and provides the `entity.name.function.definition.special.constructor(.cpp)` scope for them. This scope, however, is overridden by colour customizations for `entity.name.function`, which I assume is the fallback scope defined for the semantic token provider's `member` scope.
![image](https://user-images.githubusercontent.com/31248098/96222448-9552c600-0f8c-11eb-9266-333f9b9ab77b.png)

As you can see, colour customizations for `entity.name.function` override colour customizations for `entity.name.function.definition.special.constructor`. It's just strange to me that a colour customization for a normal TextMate syntactic scope can always override any others, even if that scope does come from the semantic token provider.

That's why I suggested providing a configuration key in `settings.json` that allows you to disable those fallback TextMate scopes for the cpptools extension (maybe something like `"C_Cpp.provideFallbackScopes": false`). Without bothering the VS Code guys with something so minor, the configuration key seemed like the solution with the least amount of work attached to it, but I could be completely wrong since I don't know how the fallback scopes are implemented.

I hope that made my line of thinking clearer, but if not, don't worry about it. Again, this is only a minor annoyance to me as a theme creator, not the biggest deal. I really only aimed to understand why this was happening, and I definitely understand now, so if you think implementing a solution for this in the form of a configuration key is too much work, feel free to close this issue (or keep it open to track the aforementioned [docs update](https://code.visualstudio.com/docs/cpp/colorization-cpp)).

Sorry for taking up so much of your time with something so minor.

**Comment by Colengms** [comment] 2020-10-16 20:24
@cengels 

> "editor.semanticHighlighting.enabled": false in settings.json

Thanks for pointing this out.  It looks like this is currently being tracked by: https://github.com/microsoft/vscode/issues/101498  I'd suggest commenting on that issue, to let them know that being unable to disable semantic highlighting using this setting is confusing.  It looks like it's possible to work around the issue using:

```
    "[c]": {
        "editor.semanticHighlighting.enabled": false
    },
    "[cpp]": {
        "editor.semanticHighlighting.enabled": false
    }
```

>It just seems strange to me that the TextMate scope entity.name.type.class appears but essentially cannot be used unless there is no colour defined for the entity.name.type scope.

Correct, with semantic highlighting enabled, we actually apply the semantic colors on top of the syntactic colors.

> This scope, however, is overridden by colour customizations for entity.name.function, which I assume is the fallback scope defined for the semantic token provider's member scope.

I've updated the doc here, which includes semantic token names and fallback scopes: https://code.visualstudio.com/docs/cpp/colorization-cpp

I'm not sure whether disabling fallback scopes would result in VS Code falling back to the TextMate token and syntactic highlighting.  If semantic highlighting were enabled, and we returned a semantic token for it, it would still be a semantic token.  One way to test this might be to modify the package.json files in our extension directory to remove the `semanticTokenScopes` section.

If it would be useful to disable the fallback scopes, I'd suggest opening a feature request in the VS Code repo, for a setting, as it would likely be useful for other language service extensions as well.

**Comment by Colengms** [comment] 2020-11-10 00:34
Hi @cengels .  I think we got to the bottom of this, so am closing this issue.  If there is more to discuss, let me know.  :)

**Closed as completed by Colengms** 2020-11-10 00:34 UTC
Labels: bug, Language Service, more info needed, Feature: Colorization

**Comment by aenachescu** [comment] 2020-12-20 12:40
Hi @Colengms . I tried your workaround but it does not works properly. When i disabled semantic highlighting, some tokens are no longer recognized properly.
This is how it looks when semantic highlighting is disabled:
![image](https://user-images.githubusercontent.com/6330622/102713362-6fb9a400-42d0-11eb-8e69-935cbfd3a046.png)
And this is how it looks when semantic highlighting is enabled:
![image](https://user-images.githubusercontent.com/6330622/102713381-9081f980-42d0-11eb-857f-e1934a16cc45.png)
And this how a global variable is recognized when semantic highlighting is disabled:
![image](https://user-images.githubusercontent.com/6330622/102713459-0ede9b80-42d1-11eb-8e93-7771857f34e4.png)

VSCode details:
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.0.0-32-generic

Extension version: 1.1.3

**Comment by sean-mcmanus** [comment] 2020-12-21 22:08
@aenachescu It sounds like you're getting the expected behavior when semantic colorization is disabled. FYI, Colen probably won't be able to respond till January.
