### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jpl931** [microsoft/vscode-cpptools#3349] opened 2019-03-23 21:43 UTC
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/johnleboube/ms-vscode.cpptools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by michelleangela** [comment] 2019-03-25 18:00
Thank you for your issue report. This looks like a duplicate of [#3213](https://github.com/Microsoft/vscode-cpptools/issues/3213).

**Closed as completed** 2019-03-25 18:00 UTC
Labels: duplicate, Language Service
