### ISSUE TITLE
Version v1.20.5 does not find standard headers

### ISSUE THREAD

**Issue by funeetop** [microsoft/vscode-cpptools#12397] opened 2024-06-20 04:40 UTC
### Environment

- OS and version: WIN 11 10.0.22631
- VS Code:  1.90.2(user setup) 
- C/C++ extension: 1.20.5
- OS and version of remote machine (if applicable): 
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

Bug Summary:
the intellisense of new version v1.20.5 does not work properly, it complains about can not open file like type_traits functional (which comes from compiler include path). the issue does not exist in older version of cpptool like 1.18.5. I am using cmake 3.30 and msvc 2022 amd x64. 
the build process are fine.

### Debugger Configurations

```shell
produce by vscode cmake tool
```

### Debugger Logs

```shell
no applyable
```

**Comment by bobbrow** [comment] 2024-06-20 18:10
Hi @funeetop,

Can you share some logs with us?  To do this, please:
1. [Enable logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
2. Restart VS Code
3. Open the source file that is showing the problem
4. Copy the logging from the Output window into this issue (remove any personal information like file paths if they are not things you can share on the Internet)

Thank you!

**Comment by sean-mcmanus** [comment] 2024-06-20 19:04
@funeetop I believe this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/12293, which is fixed in 1.21.0 (pre-release) -- can you try that?

**Comment by P3tracore** [comment] 2024-06-30 06:43
Hello, I have the same issue as this and also https://github.com/microsoft/vscode-cpptools/issues/12293, but I have this error both in 1.20.5 and the pre-release version. Should I create a new issue for this or post my C++ Log Diagnostics/CMake Diagnostics/C++ output or whatever else is needed here?

**Closed as not planned** 2024-08-30 11:16 UTC
Labels: duplicate, Language Service, more info needed
