### ISSUE TITLE
The formatting tool is not working properly

### ISSUE THREAD

**Issue by langyo** [microsoft/vscode-cpptools#4099] opened 2019-08-16 16:34 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10.0.17763.678
- VS Code Version: 1.37.1
- C/C++ Extension Version: 0.24.1
- After formatting, the formatted text is not replaced but appended to the end of the text.

**To Reproduce**
1. Open a c++ file.
2. Copy some source code into it.
3. Right-click to format.
4. See error.

**Expected behavior**
Replace old text with new text instead of appending directly to the end of the file.

**Screenshots**
![1.gif](https://i.loli.net/2019/08/17/8ZbF4qMapAlwiCx.gif)

**Additional context**
The code I am going to format is that I copied it directly from the other place to the editing area.

**Comment by sean-mcmanus** [comment] 2019-08-16 18:52
I believe this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4091 (although your repro steps are slightly different). The document is becoming corrupted when it's saved and the formatting is revealing the corrupted document.

**Comment by michelleangela** [comment] 2019-08-21 17:25
Closing as duplicate.

**Closed as completed by michelleangela** 2019-08-21 17:25 UTC
Labels: bug, duplicate, Language Service, Feature: Code Formatting
