### ISSUE TITLE
VSCode.CPP.Extension crashes after some time of coding - no clear reason

### ISSUE THREAD

**Issue by thiagoh** [microsoft/vscode-cpptools#654] opened 2017-04-21 00:50 UTC
This has happened so many times but yet I can't understand why. I mean, sometimes I'm not even coding, it just happens.

<img width="1194" alt="screen shot 2017-04-20 at 4 39 17 pm" src="https://cloud.githubusercontent.com/assets/110336/25258069/be50bf90-260a-11e7-8d88-c276ac1d8c45.png">

@sean-mcmanus asked for the crash files, here they are:

[Microsoft.VSCode.CPP.Extension.darwin.crash.zip](https://github.com/Microsoft/vscode-cpptools/files/945800/Microsoft.VSCode.CPP.Extension.darwin.crash.zip)

**Comment by sean-mcmanus** [comment] 2017-04-21 16:59
Thanks a lot for the call stacks. One of the crashes was already fixed in our working branch (reported by another user), but one of them was new. Both bugs should be fixed in our pending update. The issues are caused by not handling unexpected UTF-8 data correctly. However, we don't actually have a repro for the bugs, so there might be other issues caused by the unexpected data. If you could provide a repro file that would be good or if it still crashes after the next update let us know the new call stack. I assume the file has some unusual data or is not a proper UTF-8 encoded file.

**Comment by bobbrow** [comment] 2017-04-25 17:44
We made some fixes in this area in v.0.11.0.  Can you let us know if you are still getting crashes in the latest version?

**Comment by thiagoh** [comment] 2017-04-25 21:59
@bobbrow thank you. Sure, I'm gonna work in a cpp project today, should anything wrong happen I tell you right away.

**Comment by zhushh** [comment] 2017-04-28 12:22
I also meet this problem when I am coding the cpp code, and autocomplete do not appear.

VSCode Version: 1.11.2
OS: 4.8.0-46-generic \# 49~16.04.1-Ubuntu x86_64

I think it is very bad if the autocomplete do not work.(ps: I has installed the extensions)

**Comment by sean-mcmanus** [comment] 2017-04-28 15:46
@zhushh What is your extension version? 0.11.0? Does autocomplete work when you use Ctrl+Space? What file encoding are you using? Can you provide any crash dumps or a small sample file the repros the problem? We fixed the crashes with the particular call stacks, but we were not able to obtain a repro.

**Comment by zhushh** [comment] 2017-04-29 17:08
@sean-mcmanus Sorry, I uninstalled the extensions and I do not know how to provide the file your need. However, I reinstalled the extensions and configured llvm+clang, then  the problem do not appear.
Here is the extension I reinstalled:

1. C/C++ 0.11.0
2. C/C++ Clang Command Adapter 0.2.2
3. C++ Intellisense 0.2.1
4. Include Autocomplete 0.0.3

![1](https://cloud.githubusercontent.com/assets/7234111/25557301/83f146e2-2d41-11e7-8d0f-1b4d38a8bd1d.png)

But now the problem is that the autocomplete do not appear and Ctrl+space do not work because I use it to switch input method.

**Comment by sean-mcmanus** [comment] 2017-04-30 04:48
@zhushh You can change the Ctrl+Space keybinding to something else for "Trigger Suggest" to trigger autocomplete. If you have multiple autocomplete providers, we can't tell which extension is causing the problem unless you disable the other autocomplete providers or disable the cpptools extension (or change the C_Cpp.autocomplete to "Disabled").

**Comment by zhushh** [comment] 2017-05-05 18:35
@sean-mcmanus OK,thx.

**Comment by bobbrow** [comment] 2017-05-09 16:52
Closing this issue.  If you are still experiencing crashes and can provide crash dumps for us, please open a new issue.

**Closed as completed by bobbrow** 2017-05-09 16:52 UTC
Labels: Language Service

**Comment by thiagoh** [comment] 2017-05-09 18:08
@bobbrow I've been using all week and the issue hasn't raised no longer.. thank you
