### ISSUE TITLE
Feature request: Output directly after compiling instead of doing ./test

### ISSUE THREAD

**Issue by GaaneshT** [microsoft/vscode-cpptools#7369] opened 2021-04-15 17:22 UTC
Type: Feature Request

Hey guys, great work on the extension so far. If I could suggest one feature, it would be to show the output directly into the terminal instead of compiling then going on my terminal and doing ./programme . The feature would directly show the output in the output box

**Comment by sean-mcmanus** [comment] 2021-04-15 20:04
I don't understand what you're describing exactly. Can you show a screenshot or provide more info?

**Comment by GaaneshT** [comment] 2021-04-17 18:30
Glady, after I compile the programme, the output appears like : 
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/61627677/115122541-0120f480-9feb-11eb-8e1a-5a2c1c1e57bb.png">

To run the program, I would have to run compiled file like so : 
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/61627677/115123051-cbc9d600-9fed-11eb-98ec-ad0399a58520.png">

Is it possible to run the code without doing the steps in the second screenshot?

**Comment by sean-mcmanus** [comment] 2021-04-19 17:36
This might be a duplicate of the run without debugging feature: https://github.com/microsoft/vscode-cpptools/issues/5680 .

The workaround would be to use F5 (run with debugging), but you need to have a debugger installed that works (the clang lldb-mi debugger is not installed by default on Linux, but you could try using the gdb debugger).

**Comment by sean-mcmanus** [comment] 2021-04-19 17:36
@WardenGnaw Is this a duplicate?

**Comment by WardenGnaw** [comment] 2021-04-21 17:40
It would be a duplicate if you want to launch your program without debugging.

**Closed as completed** 2021-04-21 21:37 UTC
Labels: duplicate, Feature Request
