### ISSUE TITLE
Undefined functions do not report errors

### ISSUE THREAD

**Issue by xren5321** [microsoft/vscode-cpptools#12405] opened 2024-06-22 09:35 UTC
### Environment

- OS and Version: win11 Professional Edition 23H2
- VS Code Version: 1.90.2
- C/C++ Extension Version: v1.21.0
- If using SSH remote, specify OS of remote machine: local

### Bug Summary and Steps to Reproduce

Bug Summary:
![image](https://github.com/microsoft/vscode-cpptools/assets/48077865/854ae1ec-ee85-4371-9885-3854bc1a0fba)
![image](https://github.com/microsoft/vscode-cpptools/assets/48077865/1a46271a-9d11-4463-9786-b1009b311aca)
![image](https://github.com/microsoft/vscode-cpptools/assets/48077865/3909f3f3-3b29-426f-aef6-c993caa7ea18)

### Configuration and Logs

```shell
c_cpp_properties.json

{
    "configurations": [
        {
            "name": "STM32F103",
            "includePath": [
                "E:/embedded/vscode/test1/Core/Inc",
                "E:/embedded/vscode/test1/Drivers/CMSIS/Device/ST/STM32F1xx/Include",
                "E:/embedded/vscode/test1/Drivers/CMSIS/Include",
                "E:/embedded/vscode/test1/Drivers/STM32F1xx_HAL_Driver/Inc",
                "E:/embedded/vscode/test1/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": false,
                "path": [
                    "E:/embedded/vscode/test1/Drivers/STM32F1xx_HAL_Driver/Src",
                    "E:/embedded/vscode/test1/Drivers/CMSIS/Device/ST/STM32F1xx/Source/Templates"
                ]
            },
            "cStandard": "c17",
            "cppStandard": "gnu++14",
            "defines": [
                "STM32F103xB",
                "USE_HAL_DRIVER",
                ""
            ],
            "compilerPath": "E:/software/VScode/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc.exe",
            "compilerArgs": [
                "-mthumb",
                "-mcpu=cortex-m3",
                ""
            ],
            "intelliSenseMode": "${default}"
        }
    ],
    "version": 4
}


settings.json 
{
    "files.associations": {
        "main.h": "c",
        "stm32f1xx_hal.h": "c",
        "stm32f1xx_hal_def.h": "c",
        "stddef.h": "c",
        "stm32f1xx.h": "c"
    }
}
```

### Additional context

This is a cubemx generated makefile format code, I write a random function in the main C/CPP does not give hints

**Comment by browntarik** [comment] 2024-06-24 13:24
Could you provide the codebase you are using to reproduce this error?

**Comment by browntarik** [comment] 2024-06-24 18:02
After further investigation, it looks like you are facing an existing issue due to by-design behavior from c-compilers. C-compilers process implicit functions as warnings and not errors. Thus, IntelliSense will not squiggle an undefined function with an error squiggle before compilation (see below). 

![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/8c2b7b0f-2043-4cce-95a0-0d72d9c0eeaa)

After compilation, you should see a warning flag generated using the -Wimplicit-function-declaration in the c compiler.

![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/d911e0e7-6db6-4a1b-8b94-2c45c07592ef)

More information can be found on another issue addressing this here: https://github.com/microsoft/vscode-cpptools/issues/828

This issue will now be closed as a duplicate. Please let us know if you have further concerns.

**Closed as completed by browntarik** 2024-06-24 18:02 UTC
Labels: Language Service, by design

**Comment by xren5321** [comment] 2024-06-26 02:24
thank you. So is Clang-Tidy supported now？

**Comment by sean-mcmanus** [comment] 2024-06-27 00:46
@xren5321 It is, via the Run Code Analysis commands (and C_Cpp.codeAnalysis.* settings).
