### ISSUE TITLE
Code completion does not work within Lambda expressions

### ISSUE THREAD

**Issue by lh123** [microsoft/vscode-cpptools#1943] opened 2018-05-06 05:35 UTC
* Operating System: Win10 64bit
 * VS Code version: 1.23.0
 * C/C++ extension version: 0.16.1
 * C/C++ Compiler: MinGW-W64

![image](https://user-images.githubusercontent.com/10697249/39670204-46d14dd2-5132-11e8-8470-66bb3e5a2727.png)

![image](https://user-images.githubusercontent.com/10697249/39670212-5a479d9e-5132-11e8-9ca8-a0d04cdb15a3.png)

**Comment by sean-mcmanus** [comment] 2018-05-07 08:08
There is a known issue in which lambda expression aren't given access to the private members when they should (inherited from Visual Studio...the bug has existed for 4 years, so I don't think they're fixing it soon). Public variables/methods autocomplete, right? That's what I'm seeing. If not, it's some other bug. We could work around this issue by skipping all the "is this accessible" checking (i.e. incorrectly showing inaccessible private data when we shouldn't) or find some way to implement a Show More Results completion option like VS has (I don't think VS Code has a UI mechanism for this yet though).

**Comment by lh123** [comment] 2018-05-07 08:29
Yes, public variables/methods autocomplete working properly，but private members doesn't work.

**Comment by lh123** [comment] 2018-05-07 10:44
I think we can use press `ctrl` + `space` twice or three times to trigger `Show More Results`.

**Comment by sean-mcmanus** [comment] 2018-05-07 10:47
Yeah, I think that would be doable. I think the fix should be pretty easy, but I'm not sure when it'll get on our schedule yet.

**Comment by sean-mcmanus** [comment] 2018-08-11 00:38
We've implemented the 2nd Ctrl+Space invoking "show more results" as a workaround for this (for our next release, https://github.com/Microsoft/vscode-cpptools/issues/2386 ), but the root bug hasn't been fixed.

**Comment by Colengms** [comment] 2020-05-01 02:19
I happened across this same issue and opened (another?) bug against VS, here: https://developercommunity.visualstudio.com/content/problem/1007155/intellisense-in-a-lambda-auto-complete-does-not-su.html

**Comment by stevenxi** [comment] 2020-06-02 21:52
I believe I'm experiencing similar problem, but with C#
Maybe it's a general VS 2019 problem?

![Capture2](https://user-images.githubusercontent.com/3340119/83573585-ac37d500-a523-11ea-88a7-767ee9832c7c.JPG)

**Comment by sean-mcmanus** [comment] 2020-06-02 21:57
@stevenxi Completion providing is language dependent with a different C# implementation, so the C# issue is unlikely to share the same root cause as the C++ issue (for VS or VS Code), i.e. you'd want to file a different bug for VS 2019 for C# (if it doesn't exist already).

**Comment by Colengms** [comment] 2024-11-15 22:08
This appears to have been addressed at some point, as it doesn't repro with the latest version (1.23.1):

![Image](https://github.com/user-attachments/assets/1389a052-bcd7-49f8-abbd-2560d028f957)

Closing as fixed.

**Closed as completed by Colengms** 2024-11-15 22:08 UTC
Labels: bug, Language Service, Visual Studio, more votes needed
