### ISSUE TITLE
With "C_Cpp.caseSensitiveFileSupport": "enabled" IntelliSense fails for every file in 1.22.0

### ISSUE THREAD

**Issue by avolden** [microsoft/vscode-cpptools#12648] opened 2024-08-28 12:44 UTC
### Environment

- OS and Version: W11 22631.3447
- VS Code Version: 1.92.2
- C/C++ Extension Version: 1.22.0

### Bug Summary and Steps to Reproduce

Bug Summary:
No IntelliSense is available, with update failing and quick info returning `operation failed: FE: 'Compiler exited with error - No IL available'` in logs.
The problem occurs independently of the workspace. A simple piece of code with errors isn't reported by the extension

Steps to reproduce:
Create a file containing errors, like
```cpp
int main(int argc, char** argv)
{
	drfdf
	return 0;
}
```
Notice no squiggles appearing on `drfdf` an any hover resulting on `Quick info operation failed: FE: 'Compiler exited with error - No IL available'` in the logs

Reverting to 1.21.6 fixes the issue.
Both log diagnostics for 1.22.0 and 1.21.6 are available below

### Configuration and Logs

```shell
Version: 1.22.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "d:/Documents/GitHub/mingen/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.22621.0",
    "cStandard": "c17",
    "intelliSenseMode": "windows-msvc-x64",
    "cppStandard": "c++17",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": true,
    "mergeConfigurations": false,
    "compilerPath": "cl.exe",
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "d:/Documents/GitHub/mingen/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Modified Settings:
{
    "C_Cpp.default.compilerPath": "cl.exe",
    "C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.formatting": "clangFormat",
    "C_Cpp.doxygen.generateOnType": false,
    "C_Cpp.intelliSenseMemoryLimit": 16384,
    "C_Cpp.loggingLevel": "Debug",
    "C_Cpp.experimentalFeatures": "enabled",
    "C_Cpp.caseSensitiveFileSupport": "enabled"
}
cpptools version (native): 1.22.0.0
Translation Unit Mappings:
[ D:\Documents\GitHub\mingen\src\main.cpp - source TU]:
Translation Unit Configurations:
[ D:\Documents\GitHub\mingen\src\main.cpp ]
    Process ID: 25880
    Memory Usage: 42 MB
    Compiler Path: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe
    Includes:
        D:\Documents\GitHub\mingen
        D:\Documents\GitHub\mingen\bin
        D:\Documents\GitHub\mingen\deps
        D:\Documents\GitHub\mingen\lib
        D:\Documents\GitHub\mingen\src
    System Includes:
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.40.33807\include
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.40.33807\atlmfc\include
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 42 MB
-----

-----
Version: 1.21.6
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "d:/Documents/GitHub/mingen/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.22621.0",
    "cStandard": "c17",
    "intelliSenseMode": "windows-msvc-x64",
    "cppStandard": "c++17",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": true,
    "mergeConfigurations": false,
    "compilerPath": "cl.exe",
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "d:/Documents/GitHub/mingen/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.21.6.0
Translation Unit Mappings:
[ D:\Documents\GitHub\mingen\src\main.cpp - source TU]:
Translation Unit Configurations:
[ D:\Documents\GitHub\mingen\src\main.cpp ]:
    Process ID: 8668
    Memory Usage: 51 MB
    Compiler Path: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe
    Includes:
    System Includes:
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.40.33807\include
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.40.33807\atlmfc\include
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 51 MB
```

**Comment by sean-mcmanus** [comment] 2024-08-28 15:14
@BluTree Thanks for reporting this. The failure appears to be caused by `"C_Cpp.caseSensitiveFileSupport": "enabled"`.

**Comment by sean-mcmanus** [comment] 2024-08-29 23:25
@BluTree Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.22.1

**Closed as completed** 2024-09-04 08:20 UTC
Labels: bug, Language Service, fixed, regression, insiders
