### ISSUE TITLE
Type coloration broken in WSL paths

### ISSUE THREAD

**Issue by aaxdev** [microsoft/vscode-cpptools#4954] opened 2020-02-11 18:22 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Pro (18363.628)
- VS Code Version: 1.42.0
- C/C++ Extension Version: 0.26.3
- Other extensions you installed: Remote - WSL (0.42.3)
- The coloration is broken when using VS code from WSL paths.

**Details**

Some coloration are not working correcty like class names, variable, defines and enums.
I noticed the color of type is working when making the declarations, inside any function parameter, but not inside the function itself or outside.
Intellisenses and code completion works fine, only the coloration seems broken.

**Screenshots**

Project on WSL paths:
![_Capture](https://user-images.githubusercontent.com/55292583/74262552-5f728900-4cfd-11ea-9766-7104e1c234a0.PNG)
Same project on C:/test/project/
![_Capture2](https://user-images.githubusercontent.com/55292583/74264667-55eb2000-4d01-11ea-865e-a6826e1cee0f.PNG)

**To reproduce**
- By opening the project on this path: \\\wsl$\Ubuntu\home\user\myproject
- By opening the project on this path: C:\Users\<username>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState
- By opening the project from ubuntu in bash by typing the following command in the project folder: code .

**Comment by sean-mcmanus** [comment] 2020-02-11 19:41
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/3942 .

**Closed as completed by sean-mcmanus** 2020-02-11 19:41 UTC
Labels: duplicate
