### ISSUE TITLE
Unable to resolve configuration with compilerPath "/usr/bin/g++"

### ISSUE THREAD

**Issue by bejota** [microsoft/vscode-cpptools#6837] opened 2021-01-22 22:41 UTC
I can no longer use VS Code for C++ development.

VS Code 1.52.1 & cpptools v1.2.0-insiders2. Using remote development from Win10 to CentOS 7.4. (Formatting doesn't work either - possibly related.)

`[1/22/2021, 4:01:22 PM] Unable to resolve configuration with compilerPath "/usr/bin/g++".  Using "/usr/bin/clang" instead.`

```
bejota@system: which g++
/usr/bin/g++

bejota@system: g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

_Originally posted by @bejota in https://github.com/microsoft/vscode-cpptools/issues/6792#issuecomment-765716347_

**Comment by Colengms** [comment] 2021-01-22 22:46
@bejota I don't believe we are seeing a general issue with failing to query g++, so we could use more info.  Could you set `"C_Cpp.loggingLevel": "Debug"`, reload the window, and provide your C/C++ output here?  That should indicate what failed, including the command line we attempted to use to invoke g++ which failed.

**Comment by Colengms** [comment] 2021-01-22 23:08
I suspect this is actually the same issue as https://github.com/microsoft/vscode-cpptools/issues/6792#issuecomment-765716347 , after all.  It looks like older version of gcc (<=4.8.x) may not provide the standard version define we are looking for.

**Comment by bejota** [comment] 2021-01-22 23:13
Well, I reverted to cpptools v1.1.3 and disabled auto-updates for extensions and the issue has disappeared. Formatting also worked on save, as expected.

**Comment by Colengms** [comment] 2021-01-22 23:24
Yeah, it looks like gcc 4.8.x defaults to c89, which doesn't define `__STDC_VERSION__`.  Closing this as a dupe of 6792.  We have a fix in progress.

**Closed as completed by Colengms** 2021-01-22 23:24 UTC
Labels: duplicate, Language Service, Feature: Configuration
