### ISSUE TITLE
gdb Attach: Why does launch.json need program name when it can be inferred from "processId": "${command:pickProcess}"?

### ISSUE THREAD

**Issue by bobinspace** [microsoft/vscode-cpptools#6134] opened 2020-09-14 05:53 UTC
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10.0.18362
- VS Code Version: 1.49.0
- C/C++ Extension Version: v0.30.0-insiders5
- Other extensions you installed (and if the issue persists after disabling them): Native Debug
- A clear and concise description of what the bug is:

**To Reproduce**
*`launch.json` configuration:
```
        {
            "name": "(gdb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/projects/foo/the_executable",
            "processId": "${command:pickProcess}",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
```
1. With the above `launch.json`, attaching to a PID will work only if "program" in the `launch.json` is set to the path of the process belonging to that PID. Why do we need to hardcode the "program" path if this can already be inferred from the picked PID?

**Comment by sean-mcmanus** [comment] 2020-09-14 18:00
I agree, it would be nice if code could be added to auto-fetch the name from the process id. The program name isn't needed for cppvsdbg, just cppdbg mode.

**Comment by WardenGnaw** [comment] 2020-09-14 20:35
The `pickProcess` data is [implemented in the extension code.](https://github.com/microsoft/vscode-cpptools/blob/0820b5ef5239e5e9667e001e87b0ed0a00858b24/Extension/src/Debugger/attachToProcess.ts#L33) 

However, if we can somehow provide the `program` field in the `launch.json` configuration, we can easily set `program` when `pickProcess` is used. At the moment, the `pickProcess` command only assigns to `processId`.

**Comment by WardenGnaw** [comment] 2020-11-12 04:54
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/909

**Closed as completed by WardenGnaw** 2020-11-12 04:54 UTC
Labels: debugger, Feature Request

**Comment by OliverHaag** [comment] 2021-02-02 17:39
This workaround fixed it for me until the issue is resolved:
```
"program": "/proc/${command:pickProcess}/exe",
"processId": "${command:pickProcess}",
```

**Comment by adriancostin6** [comment] 2023-10-05 09:53
Computing the program name based on the retrieved PID is trivial with Node JS. Already managed to do this for one of my extensions to overcome the limitations of 'cppdbg' and the implementation in this extension. Would love adding it to your code if it is of interest.

**Comment by adriancostin6** [comment] 2023-10-05 09:55
Program can easily be computed from the PID using Node JS. Would love adding a feature for this if anyone is interested.
