### ISSUE TITLE
#include errors detected. #1696.

### ISSUE THREAD

**Issue by acinine** [microsoft/vscode-cpptools#7740] opened 2021-06-23 10:36 UTC
I am starting to learn c++ with Microsoft Visual Studio Code.
I have written this:

#include <iostream>
int main(){
    std::cout << "Hello World!";
    std::cin.ignore;
    return 0;
}

For some reason, (#include) causes problems.
This was written when reviewing it:

include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\(my_username)\Desktop\C++\python.cpp).
C/C++(1696)
cannot open source file "iostream"C/C++(1696)

**Comment by LakeeSiv** [comment] 2021-06-23 15:58
Duplicate of #1863 

Have a look at the comments there. It should help you fix this

**Comment by michelleangela** [comment] 2021-06-23 18:07
@c0smo225,
"#include errors" usually means something needs to be set with IntelliSense configuration. If you run `C/C++: Log Diagnostics` from the VS Code command palette, it will show logs of your current IntelliSense configuration. 

Also, which OS are you on? We have some tutorials to help get you started with the C++ Extension. Here is one if you are on Windows machine and using an MSVC compiler https://code.visualstudio.com/docs/cpp/config-msvc

**Comment by c0smo225** [comment] 2021-06-23 18:14
I am on Windows, I'm pretty new to all this and also its 2 am where I live. So I won't be able to make any significant changes or any at all to my vscode at this time.

**Comment by michelleangela** [comment] 2021-06-23 18:19
@c0smo225 I suggest to follow the tutorial at https://code.visualstudio.com/docs/cpp/config-msvc. The tutorial has information to help users new to the C++ Extension get started with the C++ on VS Code.

**Comment by c0smo225** [comment] 2021-06-23 18:24
Thanks, will do once morning comes.

**Comment by juanjosegarciaripoll** [comment] 2022-02-07 13:31
I also seem to be getting includePath errors even though the configuration seems correct.
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${default}",
                "${workspaceFolder}/**",
                "${workspaceFolder}/include",
                "${workspaceFolder}/../cmake-msvc/include",
                "${workspaceFolder}/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```
As per the C++ log, there is no useful information but Intellisense is restarted without the information for includePath
```
cpptools/restartIntelliSenseForFile: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc
Comprobando si hay errores de sintaxis: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc
Enviando argumentos de compilación para C:\home\juanjo\src\mps\src\dmrg\minimizer.cc
  elementos include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2022\BUILDTOOLS\VC\TOOLS\MSVC\14.30.30705\INCLUDE
  elementos include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UM
  elementos include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UCRT
  elementos include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\SHARED
  elementos include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\WINRT
  elementos include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\CPPWINRT
  elementos define: _MT
  elementos define: _DLL
  otros: --rtti
  stdver: ms_c++14
  intelliSenseMode: windows-msvc-x64
cpptools/getCodeActions: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc (id: 227)
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc
Intentando obtener los valores predeterminados del compilador de C++ en la propiedad "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe"
cpptools/getCodeActions: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc (id: 228)
Se han detectado las siguientes sugerencias de ruta de acceso de inclusión: 1.
cpptools/formatDocument: C:\home\juanjo\src\mps\src\dmrg\minimizer.cc (id: 229)
```
(Apologies, but the language pack is in Spanish)

**Comment by sean-mcmanus** [comment] 2022-02-07 18:55
@juanjosegarciaripoll I moved your issue to https://github.com/microsoft/vscode-cpptools/issues/8797 -- it's better to create a new issue, because include errors are symptom for which there can be many causes, and most likely your configuration issue is not the same as for other users.

**Closed as completed** 2022-04-09 11:16 UTC
Labels: question, Language Service, more info needed, Feature: Configuration
