### ISSUE TITLE
Error with IntelliSense and Debugging when set to Unicode UTF-8  worldwide.

### ISSUE THREAD

**Issue by Stonepia** [microsoft/vscode-cpptools#2167] opened 2018-06-22 00:11 UTC
Type: LanguageService , Debug

- OS and Version: Windows 1803
- VS Code Version:  1.24.1
- C/C++ Extension Version: 0.17.4

**Describe the bug**
When the **Beta: Use Unicode UTF-8 for worldwide language support ** option is on, the Intellisense of msvc cannot use the "go to definition". It cannot find the correct path of headerfile. (with default generated c_cpp_properties.json)

When set the include path, it can  find correctly. 

However, the debugging with msvc or WSL is stuck. And cannot re-debugging without restarting the VSCode. Hope there is a fix to this.

**To Reproduce**
Click on 'Clock and Region -> Change date, time, or number formats -> Administrative -> Change system locale'

**Comment by pieandcakes** [comment] 2018-06-25 23:37
@Stonepia For debugging, this is a duplicate of #1527 . We are investigating options to fix it but the core issue is that when we convert to UTF-8, a BOM is sent which gdb doesn't know what to do with and then it hangs.

**Comment by pieandcakes** [comment] 2018-06-25 23:37
@sean-mcmanus or @bobbrow can help with whether the Intellisense issue is a known bug or not.

**Comment by michelleangela** [comment] 2019-08-19 18:43
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.

**Closed as completed by michelleangela** 2019-08-19 18:43 UTC
