### ISSUE TITLE
Step back in Debugging

### ISSUE THREAD

**Issue by tanmayck1201** [microsoft/vscode-cpptools#7898] opened 2021-07-30 11:02 UTC
Issue Type: Feature Request

There is no step back feature present for c/c++ debugger in vs code by the extension.
It'll be great if there could be this feature, will help to debug the programs more conviniently.
Thank you!

**Comment by WardenGnaw** [comment] 2021-08-09 18:14
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/2130

**Closed as completed by WardenGnaw** 2021-08-09 18:14 UTC
Labels: duplicate, debugger
