### ISSUE TITLE
If compile_commands.json contains @file notation content of file is not used by language service.

### ISSUE THREAD

**Issue by omicronns** [microsoft/vscode-cpptools#2507] opened 2018-09-11 16:50 UTC
**Type: LanguageService**

If command line inside `compile_commands.json` contains included file content using `@file` notation, content of the file is not parsed as a part of command. For example if command line looks like: 
```
g++ @includes_CXX.rsp -o lib.cxx.obj -c lib.cxx
```
and `includes_CXX.rsp` file content like:
```
-Iinclude
```
I get:
```
#include errors detected. Consider updating your compile_commands.json or includePath. IntelliSense 
features for this translation unit (lib.cxx) will be provided by the Tag Parser.
cannot open source file "lib.hxx"
```

If I copy and paste content of `includes_CXX.rsp` file into `compile_commands.json` in place of `@includes_CXX.rsp` error disappears.

- OS and Version: Windows 10
- VS Code Version: 1.28.0-insider
- C/C++ Extension Version: 0.18.1

**Comment by bobbrow** [comment] 2018-09-11 16:56
Thanks for the feedback. This is a duplicate of #1718.  Can you go upvote that issue?

**Closed as completed by bobbrow** 2018-09-11 16:56 UTC
