### ISSUE TITLE
Find symbols in file doesn't work in .cpp files when cpptools is installed

### ISSUE THREAD

**Issue by rrohrer** [microsoft/vscode-cpptools#1530] opened 2018-02-07 17:40 UTC
I'm using vscode 1.19.3 for windows 10 (1709) x64 and the cpptools 0.14.6.  I'm seeing an issue where when I press ctrl+shift+o to find symbols, it simply says "No Symbols Found" when in a cpp file (it works when a header, or other language file is open).  Sometimes for a new file it will have a little progress bar before saying "No Symbols Found", but after I've done it once in a file it's always instant.  What seems especially odd about this, is "goto symbol" (f12) or simply mousing over things works as intended, and is instant.  It's only the ctrl+shift+o fuzzy find that isn't working.  Intellisense autocomplete seems to work as intended also.

Sorry in advance for the "REDACTED" paths, its an unannounced work project where the paths most probably would give it away.  I have verified multiple times that they are correct (and since the other features are working, I'm pretty sure that's the case)

Here is my c_cpp_properties.json:

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.12.25827/include/*",
                "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.12.25827/atlmfc/include/*",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/um",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/ucrt",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/shared",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/winrt",
                "${workspaceRoot}",
                "${workspaceRoot}/src",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED",
                "${workspaceRoot}/REDACTED"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.12.25827/include/*",
                    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.12.25827/atlmfc/include/*",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/um",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/ucrt",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/shared",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/winrt",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}


```
Here is the output when logging is marked to "verbose":

```
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are disabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/ENTERPRISE/VC/TOOLS/MSVC/14.12.25827/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/ENTERPRISE/VC/TOOLS/MSVC/14.12.25827/ATLMFC/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.16299.0/UM/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.16299.0/UCRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.16299.0/SHARED/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.16299.0/WINRT/ will be indexed
  Folder: D:/C/REDACTED_SRC_DIR/ will be indexed
Discovering files...
Checking for syntax errors: file:///d%3A/c/REDACTEDFILE_PATH.cpp
  Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/ENTERPRISE/VC/TOOLS/MSVC/14.12.25827/INCLUDE
  Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/ENTERPRISE/VC/TOOLS/MSVC/14.12.25827/ATLMFC/INCLUDE
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.16299.0/UM/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.16299.0/UCRT/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.16299.0/SHARED/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.16299.0/WINRT/
  Processing folder (recursive): D:/REDACTED_SRC_DIR/
  Discovering files: 41924 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Done parsing open files.
```

**Comment by bobbrow** [comment] 2018-02-07 18:49
Just want to double check in case anything was lost in the redacting process:

I see the following lines in the log:
```
  Folder: D:/C/REDACTED_SRC_DIR/ will be indexed
  ...
  Processing folder (recursive): D:/REDACTED_SRC_DIR/
```
If we are actually processing D:/REDACTED_SRC_DIR/ instead of D:/C/REDACTED_SRC_DIR/ then that looks like it is our bug.  (i'm equating REDACTED_SRC_DIR to mean the same thing for both log lines).  What I'm trying to figure out is if the value of ${workspaceRoot} is wrong in the second case.  This line here indicates that the extension didn't think any of the 41924 files it discovered was in your ${workspaceRoot} folder:
```
  Parsing: 0 files(s) processed
```

**Comment by rrohrer** [comment] 2018-02-07 19:01
You suspicion was correct, that was heavy handed pasting on my part.  In both cases it is indeed `D:/C/[SAME PATH]`

It is strange it didn't think those files were in my ${workspaceRoot}, as there is a src folder that contains everything. (including lots of *.py and *.cs files, which I'd assume it ignores)

**Comment by sean-mcmanus** [comment] 2018-02-07 21:33
The 0 files processed probably means that the files were already all parsed from the previous time the workspace was opened. If you're getting "No symbols found" it means that our symbol parser failed to parse the global symbols in the file for some reason. Has the file been saved? We do a symbol parse of open files, even if they're part of the browse.path. It's possible macros are interfering with the parsing. Does Go To Definition work when the definition is in the same file? That would be very strange, because it would mean the symbol has been parsed in the file. Hover is from IntelliSense, which is a separate implementation from the symbols and go to definition results.

**Comment by rrohrer** [comment] 2018-02-07 21:39
Good catch on goto definition not working on symbols that are *within the same file*. It says "no definition found for [symbol name]" when i attempt to do that.

This project is pretty heavy on compile time templates and macros. Is there a way I could dump some sort of debug data that could help you figure out what's failing?

**Comment by sean-mcmanus** [comment] 2018-02-07 22:12
We don't have detailed logging of parsing failures. What I typically do is a binary search by deleting code until I get code that parses symbols. Macros in the signature of methods can break things as well macros that involve scopes like `for` loop macros. This can be fixed via adding a cpp.hint file to your workspace with contents like:
`#define MACRO_NAME1(arg1, arg2, arg3)`
`#define MACRO_NAME2(arg1, arg2, arg3, arg4)`
The macros only need a definition sufficient to make the code parse without having to expand the macro, so no definition is often fine (e.g. macros used as attributes), except when the definition has { that our parser needs to see.
Our next release ships with more macros defined: https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/cpp.hint . More info is at https://docs.microsoft.com/en-us/cpp/ide/hint-files .

This lack of macro expansion and cpp.hint file is inherited from VS 2017, which has the same issues, but it's not as noticeable because their Go to Definition is implemented via IntelliSense (their navigate and symbol search still uses it though).

Compile time templates are supposed to be expanded correctly unless there are bugs. If you're lucky, our insider release might give better results, since we upgraded the parser: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.15.0-insiders .

If macros aren't the cause, it's also possible you're hitting a parsing bug, in which case an isolated repro case would enable us to fix it.

**Comment by rrohrer** [comment] 2018-02-07 22:22
Ah that makes sense.  I'll try the insider release, and if that fails... I'll make a cpp.hint that has our major macros in it.  We have a bunch of macros in method signatures unfortunately. 

Thanks for the help!

**Comment by bobbrow** [comment] 2019-11-07 22:35
We're going to close this older issue that appears may have been resolved.  Please let us know if you need any further help with this issue.

**Closed as completed by bobbrow** 2019-11-07 22:35 UTC
Labels: Language Service
