### ISSUE TITLE
0.10.0 (linux) extension cannot parse workspaces with cyclical symlinks

### ISSUE THREAD

**Issue by yamcenutzer** [microsoft/vscode-cpptools#463] opened 2017-01-26 13:46 UTC
neither clang, nor any thing else,
Are the key bindings a well kept secret?

CTRL-K CTRL_F
CTRL_I
CTR-SHIFT I
alt-shift l
....

**Comment by sean-mcmanus** [comment] 2017-01-26 14:00
Hmm...text formatting works for me on Linux. Do you have other formatters installed? When you right-click in a cpp file it should show Format Document in the context menu.

**Comment by yamcenutzer** [comment] 2017-01-26 15:20
as it turns out,
starting a new 'folder' with only a few files in them works.
however, starting code on the top level dir of a real world non-trivial directory tree with not only cpp files in them.... nada
dunno what's going wrong here. In this 'big' diriectory tree none of the cpp file will format. It shows the 'format Document' in the context menu, but just doesn't do it.
The same works in the 'small' directory tree.

Is there anything that could disable this functionality depending on the recursive contents of the root folder, i.e. files with special meanings, starting with '.'?

That said, real world legacy style make file projects in linux have a lot of other issues in vscode, like
being able to build individual subdirs, or when run from top, being able to resolve relative filepaths in the gcc error messages...

**Comment by sean-mcmanus** [comment] 2017-01-26 16:11
Is the config text red in the bottom right when you do the format? We had bugs where the formatting would get blocked by the parser thread (which can take a long time for big workspaces) but we think it's fixed now. Does Go To Definition work? Are you using 0.10.0? .clang-format files in the directory will change how the formatter behaves.

**Comment by yamcenutzer** [comment] 2017-01-26 16:34
using 0.10.0
.clang-format is in the top dir
 just deleted .vscode folder and starting from scratch...
 it finds nothing, keeps complaining that it can't find include files (even those in /usr/include)
 I have added the appropriate folders to c_cpp_properties.json

if I go to the green squiggly lines beneath the 'missing' include files it just says 'Loading'.. for an hour now
It seems something broke either with the extension or with code in general

**Comment by sean-mcmanus** [comment] 2017-01-26 16:36
Okay, I'll investigate a repro.

**Comment by yamcenutzer** [comment] 2017-01-26 16:41
some more details:
I'm running this on a fedora 20 machine (i know... its old, but have no choice for this project)
- both code and the extension are up to date 
- the project in question is, as I said, a directory tree using recursive gcc make
- the directory tree contains quite a number of symlinks to directories, this recreating parts of the tree in various places.
I do assume, that on linux the inetllisense file parser knows this and can figure out which targets have actually already been parsed

the tree in total also contains binaries (quite a few)

right now, for example, it doesn't even seem to recognize the file as cpp (doesn't offer goto, format, peek)...

I also don't see any of vc.db files being created any more  (in ~/.config/Code...workspace

**Comment by bobbrow** [comment] 2017-01-26 17:23
For the vc.db issue, see https://github.com/Microsoft/vscode/issues/18808.  If you close and reopen the folder (or reload the window), the db will be created in the right place.  For the first time you open the folder, we have to choose a temp folder elsewhere (e.g. /tmp/loose)

**Comment by sean-mcmanus** [comment] 2017-01-26 17:23
fedora 20 seems new enough (if it were too old, our process wouldn't run at all). What is the file extension of the file that isn't recognized as cpp? The browsing functionality (go to def, etc.) currently uses hardcoded file extensions and doesn't read files.associations, so non-standard C++ files won't work well unless the file is #included (we plan to fix that). Is this a regression from 0.9.3?

**Comment by yamcenutzer** [comment] 2017-01-26 17:29
@ bobbrow: I have tried to reopen the offending folder multiple times. it gets stuck. Let me delete all files and try again...
OK did that, now it starts creating a a vc.db file, but never finds anything. I have to clode and reopen to see what it has found (on a simple folder). The big one never gets ready 

@ sean-mcmanus: the file that isn't recognized is .cpp or .h

I think it looks like a regression from 0.9.3.  Is there a way for me to test that? I.e can I get a 0.9.3?

**Comment by sean-mcmanus** [comment] 2017-01-26 17:43
If things like Go To Definition don't appear in the menu, it means our language server process Microsoft.VSCode.CPP.Extension.linux is not running and failed during initialization/launch. Unfortunately, the VS Code extension publishing system doesn't allow the publishing of multiple versions of an extension, so there isn't a good way to get an older version. One way would be to install VS Code 1.5, which would force our older 0.9.3 extension to be used, since 0.10.0 requires 1.6. We require a 64-bit OS too. And Fedora 19 isn't supported, but 20 should be.

**Comment by yamcenutzer** [comment] 2017-01-26 17:55
doesn't look like an option to me. Would I be able to update code to 1.8 without updating the extension?
I think I still have a machine with 0.9.3, I'll try there

Anything else I could try= turn on some debugging of the extension or something?

**Comment by bobbrow** [comment] 2017-01-26 17:59
@yamcenutzer, we have run the extension on large folders with lots of non-C/C++ code in them and the extension works ok.  I wonder if there is an issue with the db.  Have you tried deleting any previous db's and then reopening the folder?  `~/.config/Code/User/workspaceStorage/*` and `/tmp/loose/*`

**Comment by yamcenutzer** [comment] 2017-01-26 18:01
..workspace i deleted multiple times, /tmp/loose  is new , trying that...
..nope..  smal dirs yes,  big dir NO

big dir means ~14000 folders with ~51000 files worth ca. 9.4G
again, there are symlinks in subfolders to other subfolders...

it was working before I updated the extension this morning

**Comment by bobbrow** [comment] 2017-01-26 19:15
Do any of your symlinks point outside of the workspace root folder?  I think I might be seeing an issue with that.  That has not been tested very well in the past.  0.9.3 seems to work a little better, but there are other problems in that version as well.

**Comment by yamcenutzer** [comment] 2017-01-26 21:04
I don't think so, but I'm not sure, there are way too many to verify quickly.

BTW, this has nothing to do with formatting. The original issue just seems to be the result of the initial parsing to fail. Being blocked or whatever. Maybe change the title of the issue?
Also, it seems that the language service sometimes fails completely in this case, such that the file is then not recognized as cpp at all (e.g the context menu doesn't show anything of goto, format, etc. and then it also stops complaining about missing includes paths).

I think I need to take a closer look at what's inside the tree. The first time I opened it it was really only source code/ makefiles, but after building it it has obviously collected quite a number other files, intermediate, binaries and the like. I dunno how this influences the parser. Will look inti it tomorrow.

**Comment by yamcenutzer** [comment] 2017-01-27 14:52
OK I tried again with a clean checkout of the project. No joy.
It is simply either too big or contains a link pointing out somewhere.

I actually tried a smaller working tree and added a link to it pointing out, and I can confirm this breaks the language service. Not good

I am still wondering, why it seems that the previous version of the extension 0.9.3 did show something. Unfortunately I can't revert to check that.

**Comment by yamcenutzer** [comment] 2017-01-27 18:55
Thanks for changing the title.
Unfortunately it's not that simple .
I have been trying various things, and sometimes it works with links pointing outside, sometimes it doesn't.
The big project is the only one that is not working reproducably and causes the language service stop altogether. I also haven't yet found an outside link in that project, they are actually all 'within'.

It must be a combination of size and something else. I'm currently checking if the links don't recurse.

**Comment by bobbrow** [comment] 2017-01-27 22:11
I was unable to get the bug to repro when I tried to debug it so I don't have a solution just yet.

If you're blocked on this and want to go back to 0.9.3 for now, feel free to send me a mail (my user tag @ microsoft.com) and I can send you a copy of the old extension.

**Comment by yamcenutzer** [comment] 2017-01-30 14:43
The problem is that the directory tree in question has cyclic symlinks (symlink loops)!
This is unfortunately quite common it seems when using symlinks and therefore any file parser should detect it. (find does)

**Comment by bobbrow** [comment] 2017-01-30 16:27
Agreed.  I will update the title.

**Comment by yamcenutzer** [comment] 2017-01-30 17:18
thanks

**Comment by yamcenutzer** [comment] 2017-03-02 15:37
not fixed in 1.10.1 February 2017 update

**Comment by sean-mcmanus** [comment] 2017-03-02 15:52
Yes, it hasn't been fixed yet, but it's high on our list, after a bunch of general stability issues. Also, 1.10.1 is the VS Code version and is unrelated to the C++ extension version (0.10.2).

**Comment by yamcenutzer** [comment] 2017-03-02 18:06
Glad to hear that its 'high' on the todo list, even though everyone agrees that cyclical symlinks are bad, nevertheless the same 'everyone' tends to have them in deep legacy linux trees. 
And, there seems no chance whatsoever I can get rid of that legacy build system anytime soon :-(

Also, yes, I meant vscode 1.10.1 with 0.10.2 extension version.... Did both updates today

Thx for the update

**Comment by sean-mcmanus** [comment] 2017-03-02 18:08
Yes, both updated around the same time yesterday (coincidence).

**Comment by yamcenutzer** [comment] 2017-03-11 20:34
out of curiosity, 
where would I notice if this gets fixed, here or in the vscode repo?

**Comment by sean-mcmanus** [comment] 2017-03-11 21:50
When this gets fixed, it'll be in the ReadMe or Changes notes in the extension page, and we'll close this issue as fixed, and you'll get an update.

**Comment by sean-mcmanus** [comment] 2017-05-15 23:17
I'm not able to repro any problem with a simple workspace with a sub folder with symbolic link to the parent folder on Linux and Mac. Is this still reproing? It seems like the repro might more complicated and we need more repro details of exactly how the cyclic link is constructed.

**Comment by bobbrow** [comment] 2017-07-25 16:22
Please let us know if this is still an issue for you and if you can provide us additional information about the link structure you're dealing with.

**Closed as completed by bobbrow** 2017-07-25 16:22 UTC
Labels: bug, Language Service, more info needed

**Comment by yamcenutzer** [comment] 2017-07-25 17:00
seems to be working in 0.12.1
