### ISSUE TITLE
nested macro "Expands to"

### ISSUE THREAD

**Issue by loynoir** [microsoft/vscode-cpptools#10335] opened 2022-12-30 13:18 UTC
### Reproduce
Nested macro
```c
#define X(a) Y(a)
#define Y(a) "hello world"
```

### Current
- Hover on `Y(a)` shows
```
Expands to:

"hello world"
```

- Hover on `X(a)` shows
```
Expands to:

Y(a)
```

### Feature Request
- Hover on `Y(a)` shows
```
Expands to:

"hello world"
```

- Hover on `X(a)` shows
```
Expands to:

Y(a)
```

If hover on `X(a)` while the key `ctrl` (or key `shift`, or any else special key) is pressed, show final expansion

```
Final Expands to:

"hello world"
```

**Comment by sean-mcmanus** [comment] 2022-12-31 02:03
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/3579. You can upvote that issue, although it's already our 2nd most upvoted IntelliSense-related feature request.

**Closed as not planned by sean-mcmanus** 2022-12-31 02:03 UTC
Labels: duplicate

**Comment by sean-mcmanus** [comment] 2023-02-03 02:53
A fix is available with 1.14.1 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.1
