### ISSUE TITLE
IntelliSense Not working

### ISSUE THREAD

**Issue by rizwankhan13** [microsoft/vscode-cpptools#6470] opened 2020-11-08 12:44 UTC
Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at c:\Users\Rizwan\.vscode\extensions\ms-vscode.cpptools-1.1.0\bin\cpptools.exe

**Comment by HoangNhan105** [comment] 2020-11-09 00:08
I had same problem, can't fix yet.

**Comment by Biditmangal** [comment] 2020-11-09 07:27
I guess it is a recent problem

**Comment by Biditmangal** [comment] 2020-11-09 07:27
I am facing this too and can't proceed further

**Comment by michelleangela** [comment] 2020-11-09 18:40
This seems to be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6453

**Comment by Zhenghao-Liu** [comment] 2020-11-10 00:50
Rollback version 1.0.1 can solve this problem for a moment. Hope to fix this bug as soon as possible

**Comment by sean-mcmanus** [comment] 2020-11-10 01:09
It should be fixed now with 1.1.1: https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.1.

**Closed as completed by sean-mcmanus** 2020-11-10 01:09 UTC

**Comment by rizwankhan13** [comment] 2020-11-10 03:21
Yes , it is fixed now . 
Thanks !
