### ISSUE TITLE
C variable array length

### ISSUE THREAD

**Issue by Ak4n0** [microsoft/vscode-cpptools#8620] opened 2022-01-01 14:14 UTC
Since the C99 version, arrays can be declared with a dimension from a variable. For example:
int length = 12;
char myArray[length];

The plugin detects this C feature as an error:
the expression must have a constant value C / C ++ (28)

There are so many differences between C and C ++ that, possibly, different extensions should be created according to the peculiarities of each language.

**Comment by TheJoshuaTerry** [comment] 2022-01-02 01:58
I'm having the same issue, only my code won't compile.

**Comment by Ak4n0** [comment] 2022-01-02 02:36
@TheJoshuaTerry With GCC and the -std=c11 switch it compiles well, but VSCode marks it as an error.

**Comment by bobbrow** [comment] 2022-01-03 20:46
Is it related to the following issue? https://github.com/microsoft/vscode-cpptools/issues/8581

**Comment by sean-mcmanus** [comment] 2022-01-03 21:11
Yes, this is the same as https://github.com/microsoft/vscode-cpptools/issues/8581 and should be fixed in our next insiders and the root cause is being tracked by an internal bug (see https://github.com/microsoft/vscode-cpptools/issues/8353).

**Comment by sean-mcmanus** [comment] 2022-01-03 21:12
You should be able to work around it by adding a compilerArg of -fno-ms-extensions

**Closed as completed by sean-mcmanus** 2022-01-03 21:11 UTC
Labels: duplicate

**Comment by sean-mcmanus** [comment] 2022-01-03 21:15
@bobbrow We could ship 1.8.0-insiders3 this week instead of next week if we think a lot of users are hitting this (or related regressions).

**Comment by bobbrow** [comment] 2022-01-03 21:29
There's a lot of stuff in flight for insiders3 so I'd like to wait until @Colengms is back and do it next week.  There is a known work around for this issue (or folks can jump back to the stable release if it's severely impacting).  We'll be in a much better place to do quick insiders updates when we start using the Marketplace features next week.

**Comment by sean-mcmanus** [comment] 2022-01-19 19:36
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).

Unless you're explicitly adding -fms-extensions, in which case that bug fix is still pending (https://github.com/microsoft/vscode-cpptools/issues/8353 ).
