### ISSUE TITLE
Annoying notification and we need a 'Don't Show Again' button

### ISSUE THREAD

**Issue by github0null** [microsoft/vscode-cpptools#10849] opened 2023-04-21 07:33 UTC
### Environment

- OS and Version: Win 11
- VS Code Version: 1.77.3
- C/C++ Extension Version: 1.14.5
- If using SSH remote, specify OS of remote machine: no

### Bug Summary and Steps to Reproduce

Bug Summary:

I'm using custom configuration provider to provide intelliSense config

```
"C_Cpp.default.configurationProvider": "cl.eide",
```

My provider can provide all the configurations to cpptools,

![image](https://user-images.githubusercontent.com/43022536/233568072-a2c5c120-3ecd-40a6-bcba-0ee011414da6.png)

And cpptools works well.

But there's one thing that annoys me, after workspace launched, cpptools always show me a notification:

![image](https://user-images.githubusercontent.com/43022536/233567114-28578de8-9721-4e81-945e-9987a09e56ff.png)

The provider is already setuped the `compilerPath=C:\Users\admin\.eide\tools\gcc_arm_v7_3_1\bin\arm-none-eabi-gcc.exe`

Expected behavior:

We need a 'Don't Show Again' button to disable this notification !

Avoid it popping up after startup every time !

### Configuration and Logs

```shell
Version: 1.14.5
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "c:\\Users\\admin\\Desktop\\My_Workspace\\xxx\\xxx\\firmware/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "cl.eide",
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "${workspaceFolder}/**"
        ]
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/*",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/src/*",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/src/gateway/*",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/src/rf/cc11xL/*",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/src/rf/*",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/crc8/*",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/board_config/wrm450/Src/*",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/board_config/wrm450/*",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/board_config/wrm450/Drivers/STM32G0xx_HAL_Driver/Src/*"
    ],
    "compilerPath": "C:\\Users\\admin\\.eide\\tools\\gcc_arm_v7_3_1\\bin\\arm-none-eabi-gcc.exe",
    "compilerArgsLegacy": [
        "-std=c11",
        "-mthumb",
        "-mcpu=cortex-m0plus"
    ]
}
Custom configurations:
[ C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\source\port.h ]
{
    "standard": "c11",
    "includePath": [
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/.eide/deps",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/board_config/wrm450/Drivers/CMSIS/Device/ST/STM32G0xx/Include",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/board_config/wrm450/Drivers/CMSIS/Include",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/board_config/wrm450/Drivers/STM32G0xx_HAL_Driver/Inc",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/board_config/wrm450/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/board_config/wrm450/Inc",
        "c:/Users/admin/Desktop/My_Workspace/xxx/xxx/firmware/source/crc8"
    ],
    "defines": [
        "__VSCODE_CPPTOOL",
        "STM32G030xx",
        "USE_FULL_LL_DRIVER",
        "USE_HAL_DRIVER",
        "WRM_BOARD_TYPE=450"
    ],
    "forcedInclude": [
        "C:\\Users\\admin\\.eide\\bin\\include\\internal_headers\\gcc_intr.h"
    ],
    "compilerPath": "C:\\Users\\admin\\.eide\\tools\\gcc_arm_v7_3_1\\bin\\arm-none-eabi-gcc.exe",
    "compilerArgs": [
        "-std=c11",
        "-mthumb",
        "-mcpu=cortex-m0plus"
    ]
}
Translation Unit Mappings:
[ C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\source\port.h ]:
    C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\source\port.h
Translation Unit Configurations:
[ C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\source\port.h ]:
    Process ID: 10436
    Memory Usage: 59 MB
    Compiler Path: C:\Users\admin\.eide\tools\gcc_arm_v7_3_1\bin\arm-none-eabi-gcc.exe
    Includes:
        C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\.eide\deps
        C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\source
        C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\source\board_config\wrm450\Drivers\CMSIS\Device\ST\STM32G0xx\Include
        C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\source\board_config\wrm450\Drivers\CMSIS\Include
        C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\source\board_config\wrm450\Drivers\STM32G0xx_HAL_Driver\Inc
        C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\source\board_config\wrm450\Drivers\STM32G0xx_HAL_Driver\Inc\Legacy
        C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\source\board_config\wrm450\Inc
        C:\Users\admin\Desktop\My_Workspace\xxx\xxx\firmware\source\crc8
        C:\Users\admin\.eide\tools\gcc_arm_v7_3_1\lib\gcc\arm-none-eabi\7.3.1\include
        C:\Users\admin\.eide\tools\gcc_arm_v7_3_1\lib\gcc\arm-none-eabi\7.3.1\include-fixed
        C:\Users\admin\.eide\tools\gcc_arm_v7_3_1\arm-none-eabi\include
    Defines:
        __VSCODE_CPPTOOL
        STM32G030xx
        USE_FULL_LL_DRIVER
        USE_HAL_DRIVER
        WRM_BOARD_TYPE=450
    Forced Includes:
        C:\USERS\ADMIN\.EIDE\BIN\INCLUDE\INTERNAL_HEADERS\GCC_INTR.H
    Standard Version: c11
    IntelliSense Mode: windows-gcc-arm
    Other Flags:
        --gcc
        --gnu_version=70301
        --header_only_fallback
Total Memory Usage: 59 MB
```

**Comment by sean-mcmanus** [comment] 2023-04-21 17:52
@github0null This is fixed already in https://github.com/microsoft/vscode-cpptools/releases/tag/v1.15.2 . Duplicate of https://github.com/microsoft/vscode-cpptools/issues/10691 . Let us know if that is not fixed for you.

**Closed as not planned by sean-mcmanus** 2023-04-21 17:52 UTC
Labels: bug, duplicate, Language Service, fixed, Feature: Configuration

**Comment by sean-mcmanus** [comment] 2023-04-21 17:54
Also, another workaround (for 1.14.5) is to set `"C_Cpp.default.compilerPath": "C:\\Users\\admin\\.eide\\tools\\gcc_arm_v7_3_1\\bin\\arm-none-eabi-gcc.exe"`
