### ISSUE TITLE
Intellisense displays errors on boost::property_tree 1.77

### ISSUE THREAD

**Issue by alexolog** [microsoft/vscode-cpptools#8501] opened 2021-12-07 18:04 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: Ubuntu 20.04.3 LTS
- VS Code Version: 1.62.3 (OS: Linux x64 5.4.0-90-generic)
- C/C++ Extension Version: v1.7.1

Intellisense reports errors on boost::property_tree include file: 
"a template argument list is not allowed in a declaration of a primary template"

**Steps to reproduce**
1. Get Boost 1.77.0
2. Open include/boost/property_tree/detail/ptree_implementation.hpp in VSCode
3. Errors are displayed:
<details>
<summary>List of errors (click to expand)</summary>

```
[{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "840",
	"severity": 8,
	"message": "a template argument list is not allowed in a declaration of a primary template",
	"source": "C/C++",
	"startLineNumber": 30,
	"startColumn": 12,
	"endLineNumber": 30,
	"endColumn": 23
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "840",
	"severity": 8,
	"message": "a template argument list is not allowed in a declaration of a primary template",
	"source": "C/C++",
	"startLineNumber": 75,
	"startColumn": 11,
	"endLineNumber": 75,
	"endColumn": 22
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "840",
	"severity": 8,
	"message": "a template argument list is not allowed in a declaration of a primary template",
	"source": "C/C++",
	"startLineNumber": 98,
	"startColumn": 11,
	"endLineNumber": 98,
	"endColumn": 22
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "840",
	"severity": 8,
	"message": "a template argument list is not allowed in a declaration of a primary template",
	"source": "C/C++",
	"startLineNumber": 111,
	"startColumn": 11,
	"endLineNumber": 111,
	"endColumn": 22
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "840",
	"severity": 8,
	"message": "a template argument list is not allowed in a declaration of a primary template",
	"source": "C/C++",
	"startLineNumber": 121,
	"startColumn": 11,
	"endLineNumber": 121,
	"endColumn": 22
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "840",
	"severity": 8,
	"message": "a template argument list is not allowed in a declaration of a primary template",
	"source": "C/C++",
	"startLineNumber": 135,
	"startColumn": 11,
	"endLineNumber": 135,
	"endColumn": 22
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "840",
	"severity": 8,
	"message": "a template argument list is not allowed in a declaration of a primary template",
	"source": "C/C++",
	"startLineNumber": 157,
	"startColumn": 11,
	"endLineNumber": 157,
	"endColumn": 22
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "864",
	"severity": 8,
	"message": "basic_ptree is not a template",
	"source": "C/C++",
	"startLineNumber": 179,
	"startColumn": 5,
	"endLineNumber": 179,
	"endColumn": 16
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "864",
	"severity": 8,
	"message": "basic_ptree is not a template",
	"source": "C/C++",
	"startLineNumber": 185,
	"startColumn": 5,
	"endLineNumber": 185,
	"endColumn": 16
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "20",
	"severity": 8,
	"message": "identifier \"data_type\" is undefined",
	"source": "C/C++",
	"startLineNumber": 185,
	"startColumn": 45,
	"endLineNumber": 185,
	"endColumn": 54
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "864",
	"severity": 8,
	"message": "basic_ptree is not a template",
	"source": "C/C++",
	"startLineNumber": 191,
	"startColumn": 5,
	"endLineNumber": 191,
	"endColumn": 16
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "864",
	"severity": 8,
	"message": "basic_ptree is not a template",
	"source": "C/C++",
	"startLineNumber": 191,
	"startColumn": 45,
	"endLineNumber": 191,
	"endColumn": 56
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "864",
	"severity": 8,
	"message": "basic_ptree is not a template",
	"source": "C/C++",
	"startLineNumber": 198,
	"startColumn": 5,
	"endLineNumber": 198,
	"endColumn": 16
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "864",
	"severity": 8,
	"message": "basic_ptree is not a template",
	"source": "C/C++",
	"startLineNumber": 199,
	"startColumn": 9,
	"endLineNumber": 199,
	"endColumn": 20
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "864",
	"severity": 8,
	"message": "basic_ptree is not a template",
	"source": "C/C++",
	"startLineNumber": 199,
	"startColumn": 48,
	"endLineNumber": 199,
	"endColumn": 59
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "864",
	"severity": 8,
	"message": "basic_ptree is not a template",
	"source": "C/C++",
	"startLineNumber": 206,
	"startColumn": 5,
	"endLineNumber": 206,
	"endColumn": 16
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "864",
	"severity": 8,
	"message": "basic_ptree is not a template",
	"source": "C/C++",
	"startLineNumber": 212,
	"startColumn": 10,
	"endLineNumber": 212,
	"endColumn": 21
},{
	"resource": "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp",
	"owner": "C/C++",
	"code": "67",
	"severity": 8,
	"message": "expected a '}'",
	"source": "C/C++",
	"startLineNumber": 933,
	"startColumn": 8,
	"endLineNumber": 933,
	"endColumn": 8
}]
```
</details>

**Expected behavior**
No errors

**Code sample and logs**
<details>
<summary>Configurations in c_cpp_properties.json (click to expand)</summary>

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cppStandard": "gnu++17"
        }
    ],
    "version": 4
}
```
</details>

<details>
<summary>Logs from running C/C++: Log Diagnostics from the VS Code command palette (click to expand)</summary>

```
-------- Diagnostics - 2021-12-07, 12:58:26 p.m.
Version: 1.7.1
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cppStandard": "gnu++17",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "intelliSenseMode": "gcc-x64",
    "mergeConfigurations": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /work/project/src/config/ConfigLoader.cpp ]:
    /work/project/src/config/ConfigLoader.cpp
    /work/project/include/config/ConfigLoader.h
[ /work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp ]:
    /work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp
Translation Unit Configurations:
[ /work/project/src/config/ConfigLoader.cpp ]:
    Process ID: 98674
    Memory Usage: 323 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/11
        /usr/include/x86_64-linux-gnu/c++/11
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
        /work/project/include
        /work/project/.conan/data/boost/1.77.0/_/_/source/source_subfolder/boost/predef
        /work/project/.conan/data/librdkafka/1.7.0/_/_/build/da2dbbb3d20491c47ac497d2777a86f257d6f6b9/source_subfolder/generated
        /work/project/.conan/data/boost/1.77.0/_/_/source/source_subfolder/boost/predef/os
        /work/project/.conan/data/boost/1.77.0/_/_/source/source_subfolder/boost/predef/language
        /work/project/.conan/data/boost/1.77.0/_/_/source/source_subfolder/tools/build/src/engine
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110100
[ /work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/property_tree/detail/ptree_implementation.hpp ]:
    Process ID: 98931
    Memory Usage: 139 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/11
        /usr/include/x86_64-linux-gnu/c++/11
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
        /work/project/.conan/data/boost/1.77.0/_/_/source/source_subfolder/boost/predef
        /work/project/.conan/data/librdkafka/1.7.0/_/_/build/da2dbbb3d20491c47ac497d2777a86f257d6f6b9/source_subfolder/generated
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110100
        --header_only_fallback
Total Memory Usage: 462 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 130376
Number of files parsed: 97939

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: /usr/include/boost/assert.hpp
    Alternative: "/work/project/.conan/data/boost/1.77.0/_/_/source/source_subfolder"
    Alternative: "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include"
Using: /usr/include/c++/11/cctype
    Alternative: "/work/project/.conan/data/boost/1.77.0/_/_/source/source_subfolder/boost/compatibility/cpp_c_headers"
    Alternative: "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/compatibility/cpp_c_headers"
Using: /work/project/.conan/data/librdkafka/1.7.0/_/_/build/da2dbbb3d20491c47ac497d2777a86f257d6f6b9/source_subfolder/generated/config.h
    Alternative: "/work/project/.conan/data/libbacktrace/cci.20210118/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646"
    Alternative: "/work/project/.conan/data/boost/1.77.0/_/_/source/source_subfolder/tools/build/src/engine"
Using: /usr/include/ctype.h
    Alternative: "/work/project/.conan/data/openssl/3.0.0/_/_/source/source_subfolder/include/crypto"
    Alternative: "/work/project/.conan/data/openssl/3.0.0/_/_/build/b88c434d8110e892fcfb7bbb4f76234f590822f1/source_subfolder/include/crypto"
Using: /usr/include/endian.h
    Alternative: "/work/project/.conan/data/openssl/3.0.0/_/_/source/source_subfolder/include/internal"
    Alternative: "/work/project/.conan/data/openssl/3.0.0/_/_/build/b88c434d8110e892fcfb7bbb4f76234f590822f1/source_subfolder/include/internal"
    Alternative: "/work/project/.conan/data/boost/1.77.0/_/_/source/source_subfolder/boost/predef/other"
    Alternative: "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/predef/other"
Using: /usr/include/time.h
    Alternative: "/work/project/.conan/data/protobuf/3.17.1/_/_/source/source_subfolder/src/google/protobuf/stubs"
    Alternative: "/work/project/.conan/data/protobuf/3.17.1/_/_/build/64504d4b5743a18b5bb012ba0145fd09ce3bd5f2/source_subfolder/src/google/protobuf/stubs"
Using: /work/project/.conan/data/boost/1.77.0/_/_/source/source_subfolder/boost/predef/version.h
    Alternative: "/work/project/.conan/data/boost/1.77.0/_/_/package/dc8aedd23a0f0a773a5fcdcfe1ae3e89c4205978/include/boost/predef"
```
</details>

**Comment by sean-mcmanus** [comment] 2021-12-07 18:26
What is the TU? i.e. what source file is including that? It doesn't seem like that header compiles on it's own. If you run C/C++: Log Diagnostics you can see what source file we choose or if we're using a "header only fallback". If the source file doesn't compile on it's own, then the errors may be expected, i.e. I get compiler errors like "basic_ptree is not a template" when the header is compiled by itself in an empty source file.

**Comment by alexolog** [comment] 2021-12-08 03:05
It's not a compiler error, it's an intellisense error which pops up when I open the the file.
The C/C++: Log Diagnostics is included in a collapsible above (click on it)

**Comment by Colengms** [comment] 2021-12-08 21:10
Hi @alexolog .  The IntellISense parser is a compiler front end, internally.  If code does not compile, it will not be processed properly by IntelliSense.  IntelliSense will squiggle code it does not understand, based on prior code it has parsed/compiled successfully in the same Translations Unit (TU).

Sean is referring to the fact that `ptree_implementation.hpp` does not appear to parse/compile properly all by itself.  If you copy the contents of this header into a `.cpp` file, that source file would not compile.  As such, I believe this issue is "by design".

Because header files are interpreted in the context of where they are included in source files, the C/C++ extension will choose a source file (TU) to interpret the header file in.  If there is a source file in your project that includes this header (likely indirectly, as this header does not appear intended to include directly), it would be chosen, and may provide sufficient context (code from other, prior/parent headers) for IntelliSense to interpret it.  If you run `C/C++: Log Diagnostics`, as Sean suggests, it should provide sufficient information to determine what source file was used to interpret the header. I suspect there is no source file available, and the header is being interpreted in `header only` mode, in which case the reported errors would be expected.

**Comment by alexolog** [comment] 2021-12-08 22:32
I did run the `C/C++: Log Diagnostics`.  It it included as a collapsible in the original post.  Click on the last line ("Logs from running C/C++: Log Diagnostics from the VS Code command palette (click to expand)") to expand it

**Comment by Colengms** [comment] 2021-12-09 00:00
Hi @alexolog .  That output indicates the file was opened with `--header_only_fallback` because no source file was found that included it.  So, this appears to be working as expected (as I explained in my last comment).  Closing this as 'by design'.

**Closed as completed by Colengms** 2021-12-09 00:00 UTC
Labels: Language Service, by design
