### ISSUE TITLE
The process of debugger locked in the line of vector or map where define when debug code of C/C++ using STL In MAC .

### ISSUE THREAD

**Issue by rigel2015** [microsoft/vscode-cpptools#9080] opened 2022-03-24 08:08 UTC
Bug type: Debugger

**Describe the bug**
- OS and Version:  macOS Monterey  version 12.2.1
- VS Code Version: 1.65.2 (Universal)
- C/C++ Extension Version: v1.9.7
- Other extensions you installed (and if the issue persists after disabling them): 
code-runner | for | 0.11.7
better-cpp-syntax | jef | 1.15.13
vscode-language-pack-zh-hans | MS- | 1.65.3
cpptools | ms- | 1.9.7
cpptools-extension-pack | ms- | 1.1.0
hexeditor | ms- | 1.9.5
vsliveshare | ms- | 1.0.5449
code-spell-checker | str | 2.1.7
vscodeintellicode | Vis | 1.2.17

- A clear and concise description of what the bug is : In MAC, When debug code of C/C++ using STL. set break point at the line of vector or map where define. The VS code jam in it. The process of debugger can not been quit. The process go on waste the CPU and memory untill the OS crash. 

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

launch.json:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "clang++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: clang++ build active file",
        }
    ]
}

<img width="711" alt="Screen Shot 2022-03-24 at 2 58 37 PM" src="https://user-images.githubusercontent.com/26108569/159870413-92668aca-68ba-4747-ac6d-7e201d855523.png">
IN debug C/C++ code using STL. When set break point in the line "vector> grid = {{0, 0, 0, 0}," the variable view in left_top go on turning.

<img width="422" alt="Screen Shot 2022-03-24 at 2 59 47 PM" src="https://user-images.githubusercontent.com/26108569/159870456-72130675-00cb-4693-91b7-d38c74556994.png">
After quit debug in VS code. The process of test64 go on running. can not be quit in "monitor".

<img width="533" alt="Screen Shot 2022-03-24 at 2 59 59 PM" src="https://user-images.githubusercontent.com/26108569/159870579-ff571f8d-372a-4605-aa26-aa23fe9eef49.png">
<img width="489" alt="Screen Shot 2022-03-24 at 3 00 38 PM" src="https://user-images.githubusercontent.com/26108569/159870591-43142195-a968-44a5-8934-c430230bfc9f.png">
The only way to stop test64 is to stop its parent process "debugserver". or it would go on waste more memory until the OS can not work.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment] 2022-03-24 18:53
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/5805

**Closed as completed by WardenGnaw** 2022-03-24 18:53 UTC
Labels: duplicate
