### ISSUE TITLE
semantic analysis error 

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#5891] opened 2020-08-04 11:32 UTC
```cpp
    static void *operator new(size_t size);
```

``` json
{
	"resource": "/E:/Home/atc6194/Code/mcu/ucosii/COMMON/triggertask.h",
	"owner": "C/C++",
	"severity": 8,
	"message": "分配函数的第一个参数必须是“size_t”类型",
	"startLineNumber": 54,
	"startColumn": 18,
	"endLineNumber": 54,
	"endColumn": 26
}
```

![image](https://user-images.githubusercontent.com/1876302/89289041-30741900-d689-11ea-8b1d-aa794183094d.png)

**Comment by heartacker** [comment] 2020-08-04 11:33
![image](https://user-images.githubusercontent.com/1876302/89289182-61544e00-d689-11ea-930b-a053af34224c.png)

**Comment by sean-mcmanus** [comment] 2020-08-05 18:39
Can you give the output of the C/C++: Log Diagnostics command?

Your intelliSenseMode may be incorrect. It looks like it's expecting a different size_t value than the configured architecture expects.

**Comment by heartacker** [comment] 2020-08-10 13:45
THE intelliSenseMode is `&{default}`，and my pc os is win7 x64.
btw, there is ok when i change the mode to any_x86(32bit) mode. there will be a error shown as above while i change mode to any_x64 mode
![image](https://user-images.githubusercontent.com/1876302/89788808-4a629f80-db52-11ea-95e4-41dfe1930c4c.png)

**Comment by Colengms** [comment] 2020-08-10 22:47
This may be a dupe of: https://github.com/microsoft/vscode-cpptools/issues/5457 .  I think it has to do with some versions of x64 gcc/g++ on Windows following the Windows convention of using 32-bit longs, and while others are following the Linux convention of using 64-bit longs.  We need to find a way to distinguish between these diverging implementations in order to pass the correct size to the IntelliSense process.

**Comment by sean-mcmanus** [comment] 2020-08-12 21:05
Yeah, sounds like the same issue.

**Closed as completed** 2020-10-12 11:23 UTC
Labels: duplicate, Language Service, more info needed
