### ISSUE TITLE
Include path settings does not parse correctly second and further ${workspaceFolder}

### ISSUE THREAD

**Issue by xkubrt0** [microsoft/vscode-cpptools#5564] opened 2020-05-26 09:11 UTC
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

C/C++ extension Version 0.28.1

I cannot open most of my include files by clicking on them. It was working correctly some days/weeks ago. After some analyzation I found that the setting of include files does not work, if I use ${workspaceFolder} variable.

example c_cpp_properties:
"env": {
        "myDefaultIncludePath": ["${workspaceFolder}/Libraries", "${workspaceFolder}/internal"],
},
..
"configurations": [
{
...
            "includePath": [
                "${myDefaultIncludePath}"
            ],
...
}
]

When I look to UI settings, I can see following error:
Include path
An include path is a folder that contains header files (such as #include "myHeaderFile.h") that are included in a source file. Specify a list paths for the IntelliSense engine to use while searching for included header files. If a path ends with /** the IntelliSense engine will do a recursive search for header files starting from that directory. If on Windows with Visual Studio installed, or if a compiler is specified in the compilerPath setting, it is not necessary to list the system include paths in this list.

One include path per line.
${myDefaultIncludePath}
 **Cannot find: /home/jke/Dvlp/Riedel/BitBucket/Tango/Libraries;${workspaceFolder}/internal**

Note that the second ${workspaceFolder} is not evaluated....

**Comment by Nounnours** [comment] 2020-05-26 11:12
Similar issue here (I think?) since the latest 0.28.1 update
It broke my includes and some files are parsed wrong by intellisense now (greyed out whe it shouldn't)
Compiler/right click find declaration and all function perfectly fine still :/

Temporary fix for me was simply to revert IntelliSense to 0.28

**Comment by xkubrt0** [comment] 2020-05-26 11:32
Thanks for tip. I tried to revert C++ extension to 0.28, but the problem still exists. Then I reverted to 0.27 and the problem does not appear any more!

**Comment by bryceschober** [comment] 2020-05-26 17:04
I think I'm having the issue too, also using user-defined include path variable:
```json
    "env": {
        "shared_includes": [
            "${workspaceFolder}",
            "${workspaceFolder}/source",
            "${workspaceFolder}/source/control/include",
            ...
        ]
    },
    "configurations": [
        {
            "includePath": [
                "${env:shared_includes}"
            ],
            ...
```

The error given from the C/C++ Configurations GUI is:
```
Cannot find: /home/bschober/git/D3;${workspaceFolder}/source;${workspaceFolder}/source/control/include;...
```
Note that its listing is expanding only the first instance of `${workspaceFolder}`. Is that the actual problem, or just a GUI-only artifact?
 
When I copy-paste the exact list from the `shared_includes` value into the `includePath` value, everything works as expected.

Out of curiosity, I tested placing only one of the necessary include paths in the `env:shared_includes`, putting the rest in the configuration, and it did successfully use the single path from `env:shared_includes`:
```json
    "env": {
        "shared_includes": [
            "${workspaceFolder}/source/control/include"
        ]
    },
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${env:shared_includes}",
                "${workspaceFolder}",
                "${workspaceFolder}/source",
                ...
```

**Comment by bryceschober** [comment] 2020-05-26 17:11
FYI, I'm pretty sure this is a duplicate of #5509, but I'll let the maintainer(s) resolve it as such.

**Comment by Colengms** [comment] 2020-05-27 01:57
Hi @xkubrt0 .  Thanks for letting us know.  I've confirmed that, as @bryceschober suspected, the fix for https://github.com/microsoft/vscode-cpptools/issues/5509 currently in [PR](https://github.com/microsoft/vscode-cpptools/pull/5510) appears to fix the issue you are reporting.

Closing this as a dupe of https://github.com/microsoft/vscode-cpptools/issues/5509 .

**Closed as completed by Colengms** 2020-05-27 01:57 UTC
Labels: duplicate, Language Service, Feature: Configuration
