### ISSUE TITLE
Highlighting of % in a format string

### ISSUE THREAD

**Issue by aahaselgrove** [microsoft/vscode-cpptools#1149] opened 2017-10-20 06:16 UTC
Windows 10 version 1703
VSCode version 1.17.0
cpptools version 0.14.0

% is highlighting red in a format string (I understand this to indicate an invalid format specifier) when it is followed by '[', which is valid. For example: `fscanf(file, "%[^','],%s", word1, word2)`

**Comment by sean-mcmanus** [comment] 2017-10-20 18:21
This appears to be a duplicate of https://github.com/atom/language-c/pull/234 . Once the fix gets into there, then VS Code can port the fix over.

**Closed as completed by sean-mcmanus** 2017-10-20 18:21 UTC
Labels: duplicate, external
