### ISSUE TITLE
Support automatically folding inactive regions

### ISSUE THREAD

**Issue by HunterZ** [microsoft/vscode-cpptools#5020] opened 2020-02-27 20:31 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: RHEL 7.5 64-bit
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them): twxs.cmake, ms-vscode.cmake-tools, slevesque.vscode-hexdump
- A clear and concise description of what the bug is.

Would like a way to fold/collapse all inactive code regions. There doesn't seem to currently be a way to do this, even though this plugin supports folding and can dim inactive regions.

**To Reproduce**

1. Create a file with some code that is inactive due to an `#ifdef`.
2. Observe that the region is dimmed out when that setting is active.
3. Observe that folding of that region is supported.
4. Observe that there are no settings or commands for folding the region based on the fact that it is inactive.

**Expected behavior**

One or more of the following:
1. Setting to auto-fold inactive regions by default (I understand that this may be difficult due to parsing data not being present immediately on file open).
2. Command to fold inactive regions on user trigger.

**Screenshots**

**Additional context**

**Comment by michelleangela** [comment] 2020-02-27 20:43
This is a duplicate of #407. Please up-vote #407.

**Closed as completed by michelleangela** 2020-02-27 20:43 UTC
Labels: duplicate, Language Service, Feature Request
