### ISSUE TITLE
struct sigaction (from signal.h) not recognized by vs code

### ISSUE THREAD

**Issue by CrackedOnTiti** [microsoft/vscode-cpptools#11894] opened 2024-01-24 08:41 UTC
### Environment

- OS and Version: Windows 10
- VS Code Version: v1.85.1
- C/C++ Extension Version: v1.18.5
- If using SSH remote, specify OS of remote machine: NaN

### Bug Summary and Steps to Reproduce

Bug Summary:

Issue Type: Bug

struct sigaction is not recognized by vs code and it doesn't seem to be any setting or extension that i can tweak

Steps to reproduce:
simply include signal.h and try to use "sigaction", or "siginfo_t". VS Code doesn't seem to recognise it.

Expected behavior:
VS Code should be able to interact with their respective structures

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-clang-x64"
        }
    ],
    "version": 4
}
```

**Comment by bobbrow** [comment] 2024-01-24 16:43
I'm not reproducing the problem.  You listed Windows as your OS, can I assume you're using WSL?  If so, which distro?  I tried with Ubuntu 22.04.

<img width="495" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/12818240/52da112b-4504-4d17-ab46-0fcb9f450646">

Are there any red underlines under the `#include <signal.h>` line?  If not, can you move the cursor to `<signal.h>`, press F12 (goto definition), and let me know if there are any red underlines in signal.h?

**Comment by servettonga** [comment] 2024-04-13 19:56
I just started learning about `sigaction` and I thought I was doing something wrong.
The issue is with Ubuntu 22.04. It works as expected on macOS.

**Comment by Colengms** [comment] 2024-04-15 18:56
Hi @CrackedOnTiti , @meltmeltix , @servettonga .  I believe this issue is not specific to the C/C++ Extension for VS Code.  If you attempt to build a C (not C++) file containing:

```
#include <signal.h>
#include <stdio.h>

int main() {
    struct sigaction sa;
    return 0;
}
```

Using the command line: `gcc test.c -std=c17`, the issue repro's on the command line as well. 

```
colen@COLENSPC:~/repos/test$ gcc test.c -std=c17
test.c: In function ‘main’:
test.c:8:22: error: storage size of ‘sa’ isn’t known
    8 |     struct sigaction sa;
      |     
```

Searching the internet, there are various articles with people reporting similar issues.

Changing the standard version to any of the `gnu` standard versions (i.e. `gnu17` instead of `c17`) appears to address it:

```
colen@COLENPC:~/repos/test$ gcc test.c -std=gnu17
colen@COLENPC:~/repos/test$ 
```

Closing this issue, as it's not an issue with the C/C++ Extension itself.

**Closed as not planned by Colengms** 2024-04-15 18:56 UTC
Labels: Language Service, more info needed, not reproing, Feature: Configuration
