### ISSUE TITLE
Outline incorrectly parses C Enum Outline

### ISSUE THREAD

**Issue by DeveloperGY** [microsoft/vscode-cpptools#9567] opened 2022-07-10 23:55 UTC
Issue Type: <b>Bug</b>

create  an enum in a c header file with one of the values called "operator" (without the quotations of course). 

![image](https://user-images.githubusercontent.com/79323075/178166917-422a8b61-f451-4770-96f4-e16a3cc8c3f5.png)

Extension version: 1.10.8
VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T08:29:47.439Z)
OS version: Linux x64 5.15.0-40-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.58GB (9.21GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 0712a7ef-442e-4d86-9f00-8d1c243eeef1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by DeveloperGY** [comment] 2022-07-10 23:57
Please note that while it says that i used --disable-extensions, i had re-enabled them to do the extension bisect in vscode

**Comment by DeveloperGY** [comment] 2022-07-11 00:05
The problem in fact also gives some error squiggles

![image](https://user-images.githubusercontent.com/79323075/178167434-354bd49a-c1c4-4bcb-8a99-322c5eb9465b.png)

**Comment by sean-mcmanus** [comment] 2022-07-11 19:50
The header is being interpreted as a C++ file instead of C by IntelliSense. Make sure the header is included by a .c or C associated file and/or add the header to the files.associations setting as a C file. Let us know if that's still not working for you. Also, you can run the C/C++: Log Diagnostics command to check if the TU associated with the header is being treated as C or C++ (the Standard Version should be a C version if C is being used) and you may want to confirm the header is associated with a C file, unless it's supposed to be a standalone header.

**Comment by sean-mcmanus** [comment] 2022-07-11 19:53
My previous comment was in regards to the error squiggle, but the Outline is another "by design" or Won't Fix issue, see https://developercommunity.visualstudio.com/t/C-language-c-file-IntelliSense-tag-p/10081769 (our Outline parser always run in C++ mode, so uses of C++ keywords doesn't work correctly for C files).

**Closed as completed** 2022-07-11 22:04 UTC
Labels: more info needed, by design, Feature: Configuration

**Comment by sean-mcmanus** [comment] 2022-07-11 22:38
@DeveloperGY I've filed issue https://github.com/microsoft/vscode-cpptools/issues/9570 to track a potential fix.
