### ISSUE TITLE
sentence begins with ”#“

### ISSUE THREAD

**Issue by kermanx** [microsoft/vscode-cpptools#7454] opened 2021-05-02 02:03 UTC
Type: Feature Request

Why there isn‘t any syntax about sentences begin with ”#“？

Hope someone to add its highlight.

Thanks!

**Comment by KermanX** [comment] 2021-05-02 05:22
I mean, like this
![image](https://user-images.githubusercontent.com/63178754/116803361-60354c00-ab49-11eb-9838-29d82457f726.png)

**Comment by Colengms** [comment] 2021-05-03 18:10
Hi @KermanX .  This looks to be a dupe of: https://github.com/microsoft/vscode-cpptools/issues/3927 .  Could you upvote that issue?  Closing this one.

**Closed as completed by Colengms** 2021-05-03 18:10 UTC
Labels: duplicate

**Comment by KermanX** [comment] 2021-05-04 05:52
OK
thank you
