### ISSUE TITLE
"Unable to open cygwin.S" when stepping into strcpy using GDB debugger

### ISSUE THREAD

**Issue by TheBicPen** [microsoft/vscode-cpptools#3306] opened 2019-03-18 15:43 UTC
Issue Type: <b>Bug</b>

It seems like the latest update broke the GDB debugger. 

Steps to reproduce:
1. Have MinGW installed.
2. Have the official C/C++ plugin installed.
3. Update to 1.32.3.
4. Create a c file with the following code:
```
#include<string.h>

int main()
{
    char str1[1024] = "asfhk\0";
    int len = strlen(str1);
	char str[len];
	strcpy(str, str1);
    return 0;
}
```
5. Place a breakpoint on the line ```char str[len];```
6. Debug with GDB using the following vscode files:

launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "gcc compile debug current file"
        }
    ]
}
```

Tasks.json:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "gcc compile current file",
            "type": "shell",
            "command": "gcc",
            "args": [
                "${fileBasename}", "-o", "${fileBasenameNoExtension}", "-Wall", "-Werror"
            ],
            
            
        },
        {
            "label": "gcc compile debug current file",
            "type": "shell",
            "command": "gcc",
            "args": [
                "${fileBasename}", "-o", "${fileBasenameNoExtension}", "-g", "-Wall", "-Werror"
            ],
            
            
        },
        {
            "label": "run current file",
            "type": "shell",
            "command": ".\\${fileBasenameNoExtension}",
            "dependsOn": ["gcc compile current file"],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": false
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        
        },
        /*{
            "label": "print filename",
            "type": "shell",
            "command": "echo ${fileBasenameNoExtension}",
            "dependsOn": ["gcc compile current file"]
        }*/
    ]
}
```

c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:\\MinGW\\bin",
            "cStandard": "c11",
            "intelliSenseMode": "gcc-x64",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 4
}

```
7. Step into the line with strcpy.
8. The following error appears:

Unable to open 'cygwin.S': File not found (file:///home/keith/src/mingw/gcc-build/gcc-8.2.0-mingw32-cross-native-sandbox/mingw32/libgcc/../../../src/gcc-8.2.0/libgcc/config/i386/cygwin.S).

I don't have cygwin installed, only minGW. Debugging worked just fine before the update.

Extension version: 0.21.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

**Comment by WardenGnaw** [comment] 2019-03-18 19:24
GDB is sending the source for strcopy to VSCode. Unless you built the libraries for strcpy, it is sending the source file line of where it was built. 

Duplicate of:
https://github.com/Microsoft/vscode-cpptools/issues/811

**Closed as completed by WardenGnaw** 2019-03-18 19:25 UTC
Labels: debugger, external

**Comment by EricJeffrey** [comment] 2019-10-31 15:55
Say I meet the problem and you know what I found?
My Code is ****!
I just have a 
`buffer[1024 * 4 * 1024];`
inside my code and that's all I got after spending all night trying to figure out what happened.


Say it, I am foolish.
