### ISSUE TITLE
#if/#define syntax not parsing for some reason

### ISSUE THREAD

**Issue by wjk** [microsoft/vscode-cpptools#11499] opened 2023-10-03 17:20 UTC
### Environment

- OS and Version: macOS 14.0
- VS Code Version: 1.82.3
- C/C++ Extension Version: 1.17.5
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:

I have a file full of code. When I load it into VSCode, I have three problems:

1. VSCode thinks the opening `#ifndef` has no `#endif` (but it really does)
2. The below preprocessor syntax is not accepted. It says “expected an expression” on hover.
3. The `#define` in the below snippet is not recognized, such as the `#if CC_UNIT_SIZE == 8` block right below it is still considered preprocessor’d-out. This causes further errors going down the file.

```c
#if defined(__x86_64__) || defined(__arm64__)
#define CCN_UNIT_SIZE 8
#endif
```

Steps to reproduce:
1. Open the file attached to this issue
2. See error

Expected behavior:

There should be no errors here, and the `#define` statement should influence the parsing of the below `#if` block.

### Configuration and Logs

```shell
c_cpp_properties.json: not in use
C/C++: Log Diagnostics: attached below
Language server logging: attached below
```

### Additional context

[The offending header file](https://github.com/microsoft/vscode-cpptools/files/12795189/ccn.h.txt).  
[C/C++ Log Diagnostics output](https://github.com/microsoft/vscode-cpptools/files/12795194/diagnostics.log.txt).  
[Language server debug output](https://github.com/microsoft/vscode-cpptools/files/12795213/output.log.txt).

**Comment by wjk** [comment] 2023-10-03 17:21
And restarting VSCode just fixed all these problems. 🤦 Sorry to bother you again.

**Comment by michelleangela** [comment] 2023-10-04 18:57
@wjk 
Could you try adding the macro `CCN_UNIT_SIZE ` in a cpp.hint file and save that file in the root of the workspace folder? The extension's symbol parser has a limitation that is by design (see https://learn.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-170).

Example in a cpp.hint file:
```
#define CCN_UNIT_SIZE 8
```

**Comment by wjk** [comment] 2023-10-04 19:17
No good. I am now getting “cannot open source file” errors on every `#include` statement in my project as well.

**Comment by sean-mcmanus** [comment] 2023-10-04 23:21
Your CMake Tools configuration provider is sending args that indicate targeting x64 Mac and not arm Mac but our IntelliSense mode is somehow changing to target arm. You're trying to target x64, right? Your C_Cpp.loggingLevel needs to be set to "Debug" to get more info from the "C/C++" output.

If your includes are not resolving, can you look at your Include paths that are logged with C/C++: Log Diagnostics to see if those look correct?

Also, cpp.hint is only required for correctly parsing workspace symbols (such as in the Outline view) and won't have any affect on IntelliSense squiggles.

**Comment by wjk** [comment] 2023-10-04 23:58
I am indeed trying to target x64 Mac.

And now the symptoms change again: no missing headers, no preprocessor problems. The only issue remaining now is that the architecture builtin pseudo-defines (e.g. `__x86_64__`) are not honored. Neither `__x86_64__` or `__arm64__` is considered defined, while one or the other should always be defined by the compiler. I am not surprised at this last behavior, as these are GCC/clang constructs, and the VSCode C++ tools are probably based on MSVC.

A few other weird things are happening elsewhere in the project. For some reason, VSCode thinks that one type defined elsewhere in the project, `typedef int kern_return_t`, is actually a function type due to the declaration `extern kern_return_t (*mig_impl_routine_t)(void)`. Furthermore, some of the C type definitions are not being parsed properly, but that is due to preprocessor abuse in the code and not something VSCode can deal with directly.

All in all, this project now works more than it did when I first filed this issue. This project is a mess overall due to how many different coding styles interact over the various parts of the project.

**Comment by michelleangela** [comment] 2023-10-05 23:46
@wjk, could you provide another set of 
logs from the language server (see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) with a source file open? The logs will show what configs/include paths/IntelliSense mode is sent to the IntelliSense engine.

**Comment by wjk** [comment] 2023-10-06 15:18
[Please find attached](https://github.com/microsoft/vscode-cpptools/files/12832717/log.txt).

**Comment by michelleangela** [comment] 2023-10-06 18:29
@wjk 
Sorry to ask for the logs again, but it is missing some logging data due to the `C_Cpp.loggingLevel` being set to "Information" (as printed in the first line of the log) instead of "Debug". Could you set your `C_Cpp.loggingLevel` to "Debug" and send the logs again? If the logging level is get to "Debug", the logs should have data such as "sending compilation args for ...." where it prints how the list of configs sent to the IntelliSense engine.

**Comment by wjk** [comment] 2023-10-06 18:59
[Please find attached](https://github.com/microsoft/vscode-cpptools/files/12834612/log.txt). I thought I had done this the first time. 😕

**Comment by michelleangela** [comment] 2023-10-09 19:02
@wjk 
Thank you for the logs. The extension is not generating the "-arch" arg correctly which results in the incorrectly IntelliSenseMode. The logs show it is falling back to arm64, though if it is, then `__arm64__` should be defined.

**Comment by bobbrow** [comment] 2024-12-31 22:14
This might be fixed in the latest version of the extension. I just tested the failing command line from the latest logs by pasting into a `compile_commands.json` file since I didn't have a CMake repro.  I see that `__x86_64__` is defined for the source file with a configuration and `__arm64__` is defined for the source file without a configuration.

If you continue to see this issue, please let us know and we can reopen it.

**Closed as completed by bobbrow** 2024-12-31 22:14 UTC
Labels: bug, Language Service, Feature: Configuration
