### ISSUE TITLE
Newlines in Auto Completion is not working in later Versions

### ISSUE THREAD

**Issue by mhummels** [microsoft/vscode-cpptools#6908] opened 2021-02-04 19:20 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.52.1
- C/C++ Extension Version: 0.29.0 up to 1.2.0
- Other extensions you installed (and if the issue persists after disabling them): disabled all for testing, problem persists
- Does this issue involve using SSH remote to run the extension on a remote machine?: no

In Issue #2937 the problem with multiple lines in the code preview was fixed with version 0.23.0. In my current setup it does not work, so I tried downgrading to 0.23.0 and tada it worked. Then I upgraded versionwise to 0.29.0 where it stopped working. So it seems like every version 0.29.0 and above do have the same Issue again. 

**Steps to reproduce**
1. Install current Version of cpptools
2. Write Function with Doxygenconform header over multiple lines. For example:
```
/**
 * @brief test function
 * 
 * Some
 * 
 * Test
 */
int test()
{
    return 0;
}

int main() {
    test();
}
```
3. Open the Preview of test():
![grafik](https://user-images.githubusercontent.com/39949284/106943366-a5520980-6725-11eb-9dc3-893c9d01111f.png)
4. All comment lines are on one line

**Expected behavior**
On cpptools Version 0.28.3 it looks as expected:
![grafik](https://user-images.githubusercontent.com/39949284/106943562-df231000-6725-11eb-84ca-4fe22a1c0eb8.png)
With exception of the missing parsing of the doxygen commands.

**Comment by sean-mcmanus** [comment] 2021-02-05 19:50
@michelleangela Do you know about this? It repros with VS too and with simplifyStructuredComments set to true or false.

**Comment by michelleangela** [comment] 2021-02-05 22:47
This a duplicate of https://github.com/microsoft/vscode-cpptools/issues/5741 and https://github.com/microsoft/vscode-cpptools/issues/5903

**Closed as completed by michelleangela** 2021-02-05 22:47 UTC
Labels: duplicate, Language Service, Feature: Doc comments
