### ISSUE TITLE
Unable to add file to database. error = -2147467259

### ISSUE THREAD

**Issue by Iwan-Zotow** [microsoft/vscode-cpptools#1164] opened 2017-10-24 19:33 UTC
Windows 7 Pro SP1, 64bit, VSCode 1.17.2 64bit, updating C/C++ to 0.14.0, loading files, debugger support, updating, then lots of message
Unable to add file to database. error = -2147467259

**Comment by jophippe** [comment] 2017-10-24 20:15
Duplicate of #1158, you can safely ignore those errors. Reload VS Code and everything should work

**Closed as completed** 2017-11-02 15:39 UTC
Labels: duplicate, Language Service

**Comment by g4r37h** [comment] 2017-11-15 23:23
By "everything should work", if you mean the app starts again then yes it does. But it then re-downloads all the updates it just downloaded and applies them again. The updates work 2nd time round but it would be nice if the app didn't have to download everything twice in order to update.  :)

**Comment by sean-mcmanus** [comment] 2017-11-15 23:45
@g4r37h The extension should only re-download the files again if the extension was uninstalled or an update occurred. Are you saying with 0.14.2 when you install the extension it is downloading the dependencies twice? We haven't heard any other reports of this occurring.

**Comment by g4r37h** [comment] 2017-11-15 23:57
Hmm. It's too late to check now as everything is installed. But I last updated the app 3 days ago, then tonight I checked for updates and it downloaded the full set of updates before giving me the "Unable to add file to database. error = -2147467259" error. I closed the app and re-opened it, and it downloaded all the updates again. I can't guarantee that the files were all identical, but I am assuming that if I was 2 versions behind then the app would only download the very latest files and not every version incrementally until I was at the latest - correct?

**Comment by sean-mcmanus** [comment] 2017-11-16 00:07
Yeah, if you updated 3 days ago, you should've had our latest 0.14.2 and there should not have been a need to trigger a newer update, and if you see the database error, then the code has been successfully installed so it shouldn't prompt to re-download again. The only way it could upgrade to an intermediate version would be if you were on an older VS Code like 1.16, then the max version for our extension would be 0.14, so then upgrading VS Code to 1.18 would cause a "re-download" when 0.14.2 installe. (Or the install.lock file being deleted in the extension folder could cause a redownload as well).

**Comment by g4r37h** [comment] 2017-11-16 00:13
OK. I'll keep a closer eye on it next time and keep track of versions and file sizes. Thanks.
