### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fiastus** [microsoft/vscode-cpptools#3414] opened 2019-04-05 07:01 UTC
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.1`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/user/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment] 2019-04-05 20:06
Thank you for the feedback. This appears to be a duplicate of #3213.

**Closed as completed by sean-mcmanus** 2019-04-05 20:06 UTC
Labels: duplicate
