### ISSUE TITLE
False positive: a value of type 'volatile struct *' cannot be assigned to an entity of type 'volatile struct *'

### ISSUE THREAD

**Issue by alexisfrjp** [microsoft/vscode-cpptools#6329] opened 2020-10-16 00:15 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: CentOS Linux release 7.8.2003 
- VS Code Version: 1.50.0 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3 x64
- C/C++ Extension Version: v1.0.1

**Steps to reproduce**

**c_cpp_properties.json**:
```json
{
    "configurations": [
        {
            "defines": [
                "__GNUC__",
                "_GNU_SOURCE"
            ],
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/../driver/include",
                "${workspaceFolder}/../extlibs/include"
            ],
            "compilerPath": "/opt/rh/devtoolset-7/root/usr/bin/gcc",
            "cStandard": "gnu11",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```
```c++
class Session {
  public:
    Session(int phys, int sess);
    ~Session();

  private:
    /* HW representations */
    struct PioArrayDma {
      uint64_t buffer;
      uint64_t monitoring;
    };

    /* Hardware base addresses */
    volatile void *mmap_pioSpace;
    volatile PioArrayDma *pPioArrayDMA;
};

void Session::Session(){
  // mmap_pioSpace = mmap() ...
  pPioArrayDMA = static_cast<volatile PioArrayDma*>(mmap_pioSpace);
};
```

At `pPioArrayDMA = static_cast...`, I get : 
>a value of type "volatile Session::PioArrayDma *" cannot be assigned to an entity of type "volatile Session::PioArrayDma *"C/C++

It compiles without any warnings, and **clang-tidy** on **CLion** doesn't complain about it.

**Comment by Colengms** [comment] 2020-10-16 01:16
Hi @alexisfrjp I'm not able to easily repro, on Linux w/gcc.  However, I did need to change the constructor definition to remove 'void' and add the 2 int params.

I have seen issues like this in the past, where IntelliSense reports that a type cannot be assigned to itself.  In those cases, the bug has arisen only as certain edits are made and has not repro'ed after freshly opening the file.  Does the error disappear after reloading VS Code?  If so, could you help us identify what edits lead to the issue?  Or, if not, could you post a zip contain a self-contained repro that we might investigate?  Thanks!

**Comment by alexisfrjp** [comment] 2020-10-16 01:59
Yes, me neither that's why I couldn't give an reproducible example. It's really random.

If I have several structures like that and following such as:
```
void Session::Session(){
  /* ... */
  pPioArrayDMA0 = static_cast<volatile PioArrayDma0*>(mmap_pioSpace0);
  pPioArrayDMA1 = static_cast<volatile PioArrayDma1*>(mmap_pioSpace1);
  pPioArrayDMA2 = static_cast<volatile PioArrayDma2*>(mmap_pioSpace2);
};
```
The error come from the last or two last assignments and the first one disappears.

**Ctrl+Shift+P : Developer: Reload Window** : A single error is shown at the first assignment.

I'll try to give you more info when I have time! Thanks!

Similar issue: https://github.com/microsoft/vscode-cpptools/issues/4092

**Comment by Colengms** [comment] 2020-10-16 22:09
I suspect this is a duplicate of: https://github.com/microsoft/vscode-cpptools/issues/3883
Also tracked in VS: https://developercommunity.visualstudio.com/content/problem/714374/intellisense-error-unable-to-assign-type-to-own-ty.html

I'm following up with devs in this area internally to get some traction on the VS bug.

I'm going to close this as a dupe of https://github.com/microsoft/vscode-cpptools/issues/3883 for now.

**Closed as completed by Colengms** 2020-10-16 22:09 UTC
Labels: duplicate, Language Service, more info needed
