### ISSUE TITLE
[lldb] input redirection not working

### ISSUE THREAD

**Issue by MichaelBrazeau** [microsoft/vscode-cpptools#2512] opened 2018-09-13 03:45 UTC
I've tried serval other posts suggestions and none seem to work.
I have a simple program that uses cin/cout and I want to use a .txt to test my code.

i've tried putting "<inputfile.txt" in args but when the debugger reaches any line that uses cin it crashes. Honestly  i'm not sure if that is what happens but it doesn't really work.

heres my launch.json file
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/letter_debug",
            "args": ["<spec-simple.txt"],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "make"
        }
    ]
}

**Comment by pieandcakes** [comment] 2018-09-26 18:42
@MichaelBrazeau lldb-mi does not respect input redirection. You can reference #1219 for more information.

**Comment by pieandcakes** [comment] 2018-09-26 18:43
Marking as a duplicate of #1219 and closing. Please comment there

**Closed as completed by pieandcakes** 2018-09-26 18:43 UTC
Labels: duplicate, debugger
