### ISSUE TITLE
GDB crashing when debugging and checking VARIABLES

### ISSUE THREAD

**Issue by p3root** [microsoft/vscode-cpptools#7299] opened 2021-04-06 17:26 UTC
Type: Debugger
GDB

**Describe the bug**
- Windows 10 - WSL 2
- VS Code Version: 1.55.0
- C/C++ Extension Version: v1.3.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): Remote - WSL
- A clear and concise description of what the bug is.

When I want to display the content of some variables, the GDB crashes and hangs up after that. I need to kill the application and restart a new debugging session.

The issue can relate to the Remote WSL extension, I start my vscode inside a WSL and run the code inside the WSL.

![image](https://user-images.githubusercontent.com/4295914/113752854-b90df200-970d-11eb-9548-005fcee556c9.png)

GDB log output

`--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (40439) 1193: elapsed time 0\n"},"seq":2361}
1: (40439) 1193: elapsed time 0
--> R (variables-23): {"type":"response","request_seq":23,"success":true,"command":"variables","body":{"variables":[{"name":"balances","value":"{...}","type":"TAmounts","evaluateName":"(sum).balances","variablesReference":1007}]},"seq":2363}
<--   C (variables-24): {"command":"variables","arguments":{"variablesReference":1004},"type":"request","seq":24}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (41592) <-1194-var-list-children --simple-values \"var62\" 0 1000\n"},"seq":2366}
1: (41592) <-1194-var-list-children --simple-values "var62" 0 1000
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (41593) ->1194^done,numchild=\"2\",displayhint=\"map\",children=[child={name=\"var62.[0]\",exp=\"[0]\",numchild=\"1\",type=\"const CScript\",thread-id=\"20\"},child={name=\"var62.[1]\",exp=\"[1]\",numchild=\"1\",type=\"CBalances\",thread-id=\"20\"}],has_more=\"0\"\n"},"seq":2368}
1: (41593) ->1194^done,numchild="2",displayhint="map",children=[child={name="var62.[0]",exp="[0]",numchild="1",type="const CScript",thread-id="20"},child={name="var62.[1]",exp="[1]",numchild="1",type="CBalances",thread-id="20"}],has_more="0"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (41593) ->(gdb)\n"},"seq":2370}
1: (41593) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (41593) 1194: elapsed time 1\n"},"seq":2372}
1: (41593) 1194: elapsed time 1
Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object`

launch.json

`{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/src/defid",
            "args": [
                "-printtoconsole",
                "-rpcuser=test",
                "-rpcpassword=test",
                "-rpcbind=0.0.0.0",
                "-rpcallowip=0.0.0.0/0",
                "-testnet",
                "-txindex",
                "-logips",
                
            ],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "logging": { "engineLogging": true, "trace": true, "traceResponse": true }
        }
    ]
}`

**Comment by WardenGnaw** [comment] 2021-04-06 17:51
Which version of GDB are you using?

Is is possible for you to share the definition of the class that it is causing it to crash? It seems to be your class `CScript`.

**Comment by p3root** [comment] 2021-04-06 18:17
You can find the code here https://github.com/DeFiCh/ain

GDB Version
`GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.`

**Comment by p3root** [comment] 2021-04-06 18:19
But in general, gdb crashes for every type of class

**Comment by p3root** [comment] 2021-04-06 18:25
> But in general, gdb crashes for every type of class

nope. sorry, you're right. only for the cscript class!

**Comment by lixin-wei** [comment] 2021-04-09 06:26
I think this is the same bug as mine, and I provide a reproduction sample in my issue. Please check it.
https://github.com/microsoft/vscode-cpptools/issues/7324

**Comment by WardenGnaw** [comment] 2021-04-12 20:48
This is due to not handling nulls in memoryContext's. 

Fixed in https://github.com/microsoft/MIEngine/commit/b774ad486dc0e8a07d956df3a6bb51813971104a#diff-ac0f039773063f8f8697d4ab9f9d6158d2e9069366abdf9f8b86e991b8fd255b

**Comment by Colengms** [comment] 2021-05-28 00:29
This fix should be in 1.4.0.

**Closed as completed by Colengms** 2021-05-28 00:29 UTC
Labels: bug, debugger, fixed
