### ISSUE TITLE
Doxygen: `\tparam` argument is not properly highlighted

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#10069] opened 2022-10-26 16:57 UTC
Type: <b>Bug</b>

Doxygen: `\tparam` argument is not properly highlighted as the other paramters. `Args` should be grayed out too.

```C++
/*!
 * \brief
 * Log a single line to the logfile
 *
 * \tparam Args A formatting argument type
 * \param lineLevel Log verbosity associated with this line
 * \param fmt Format specifier for this line
 * \param args ... Arguments to be formatted
 *
 * \return int
 *  0 No action taken
 * -1 Invalid log file name or no longer openable
 * >0 # of bytes written to log file
 */
template <class... Args>
int Log::LogLineFmt(int lineLevel, fmt::format_string<Args...> fmt, Args &&...args)
```

Extension version: 1.13.2
VS Code version: Code 1.72.2 (Universal) (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:30.254Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id a7eaff19-94ae-4653-b917-d9aaab19da5d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30566497
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30596373

```

</details>

![Screenshot 2022-10-26 at 19 58 37](https://user-images.githubusercontent.com/47526411/198088721-ae7aa651-aae8-4a61-926f-7d720dabf5b0.png)

**Comment by browntarik** [comment] 2022-10-26 17:32
This is currently an existing bug within VSCode, not our extension. If you disable our extension, this bug will still be present. The code highlighting implementation that VSCode uses is obtained from the Better C++ Syntax extension. There is already an existing bug for this issue which would be more useful for you to track https://github.com/jeff-hykin/better-cpp-syntax/issues/559

**Comment by browntarik** [comment] 2022-10-26 17:46
If there are no other concerns, I will be closing this issue.

**Closed as completed by browntarik** 2022-10-26 17:46 UTC

**Comment by H-G-Hristov** [comment] 2022-10-26 17:55
@browntarik  Better C++ Syntax extension is disabled.

**Comment by sean-mcmanus** [comment] 2022-10-26 18:04
@H-G-Hristov As Tarik mentioned, VS Code gets its implementation of the lexical colorization from the Better C++ Syntax extension. You can also confirm it's not a bug with our extension via disabling our extension and seeing that it still repros.
