### ISSUE TITLE
Incorrect syntax highliting for C/C++

### ISSUE THREAD

**Issue by Rn86** [microsoft/vscode-cpptools#434] opened 2017-01-06 10:21 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-57-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|output-colorizer|IBM|0.0.9|
|tortoise-svn|fantasytyx|0.1.1|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.3.0|

Color theme: Dark(Visual Studio)

---

Visual Studio Code does not generate .browse.VS.db in .vscode

Steps to Reproduce:

1. Open directory with Visual Studio Code
2. Open C or C++ file
3. Everything is in blue.

**Comment by sean-mcmanus** [comment] 2017-01-06 13:03
We changed it to generate the .browse.VS.db in the workspaceStorage location, such as ~/.config/Code/User/workspaceStorage. Our extensions should have no impact on colorization. It's either another extension or VS Code itself.

**Comment by bobbrow** [comment] 2017-03-14 16:52
Are you still seeing this issue?  If so, where does the blue color start in your code?  Usually these are issues with the colorization grammar, but we need to know what that last good line of code looks like so we can identify the pattern that is not being matched properly.

**Comment by bobbrow** [comment] 2017-03-14 16:53
Just looked at the linked issue.  It is resolved as a duplicate of atom/language-c#160

**Closed as completed by bobbrow** 2017-03-14 16:53 UTC
Labels: duplicate, Language Service, external
