### ISSUE TITLE
Macro: Go to definition, inconsistent behavior

### ISSUE THREAD

**Issue by sstudi** [microsoft/vscode-cpptools#8914] opened 2022-02-23 10:01 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version:  Windows 10, Version 10.0.19042 Build 19042
- VS Code Version: 1.64.2 (user)
- C/C++ Extension Version: 1.8.4
- Other extensions you installed (and if the issue persists after disabling them): all deactivated, issue persists

Using F12 or CTRL+Click I want to go to the definition of a macro which is used somewhere in code. 
This works as long as it's not a nested macro.  
If it's a nested macro, it jumps to the fully resolved definition.   

This behavior changed recently, before it always correctly jumped to the definition and did not fully resolve the macro.

The bug appears in a big single project workspace with different CPP configurations.

But I can reproduce the issue with a small demo project as well.

The problem seems to be affected by the setting `incudePath` & `compilerPath`.   
If either I don't provide an include path, or an invalid compiler path, it always jumps to the real definition and not the fully resolved definition.

**Steps to reproduce**
1. Adapt `c_cpp_properties.json` to provide a valid compiler path
1. Go to 'test.cpp'
2. CTRL+Click on `CONCRETE_ADDRESS`
3. Error: Jumps to `base_defs.h` instead of `defs.h`

**Code sample and logs**

[macro_test.zip](https://github.com/microsoft/vscode-cpptools/files/8123332/macro_test.zip)

**Comment by xxthunder** [comment] 2022-02-24 15:58
Indeed, I can confirm this bug. Search for it and came to this ticket.

**Comment by Colengms** [comment] 2022-02-25 03:14
Hi @estudm @xxthunder .  Thanks for reporting this.  I'm able to repro to repro this issue in VS as well, so have opened an issue against VS internally.  (We share the same IntelliSense implementation as VS)

**Comment by tenggui** [comment] 2022-03-29 03:24
I also reproduced it in the lastest VSCode and C/C++ extension version. When will this bug be fixed? Do you have any plans?

**Comment by sean-mcmanus** [comment] 2022-03-29 03:41
I'm not sure.

@Colengms Do you know what internal bug number is tracking this?

**Comment by sean-mcmanus** [comment] 2022-03-29 18:05
@tenggui I found the issue -- it should be fixed in our next pre-release.

**Comment by ziki77** [comment] 2022-04-22 07:43
The milestone associated is at only 5%...when you plan to release this fix? You already released the 1.9.8 in the meanwhile...
I do not know if you are really use VSCode for programming...but this bug wastes a lot of a C programmer's time.

**Comment by Colengms** [comment] 2022-04-22 17:17
Hi @ziki77 .  We have released 1.10.0, which looks like it should include this fix.  1.10.0 is a 'pre-release', so you will need to select `Switch To Pre-Release` for this extension in the VS Code marketplace UI.

**Closed as completed** 2022-04-27 01:01 UTC
Labels: bug, Language Service, fixed, Visual Studio, Feature: Go to Definition
