### ISSUE TITLE
Hundreds of rg.exe instances take up 100% CPU and gigs of memory

### ISSUE THREAD

**Issue by rkg96** [microsoft/vscode-cpptools#10625] opened 2023-03-03 01:43 UTC
Type: <b>Bug</b>

After a while, I see instances of rg.exe start accumulating and slowly taking up more CPU and multiple GBs of RAM. I've seen from ~200 to over 1000 instances. Reloading vscode ends up getting rid of them. 

Extension version: 1.14.4
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.25310
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.57GB (11.40GB free)|
|Process Argv|--crash-reporter-id c85acfd1-02e1-4a8a-8342-5591367042b2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
vsctsb:30662444
vscodedisable:30660115
funwalk2cf:30676044

```

</details>

**Comment by sean-mcmanus** [comment] 2023-03-03 01:48
This is a VS Code issue unrelated to our extension.

Duplicate of https://github.com/microsoft/vscode-cpptools/issues/7160 .

See also https://github.com/microsoft/vscode/issues/113378 and https://github.com/microsoft/vscode/issues/64984 .

**Closed as not planned by sean-mcmanus** 2023-03-03 01:48 UTC
Labels: duplicate, external, Visual Studio Code
