### ISSUE TITLE
command 'C_Cpp.ConfigurationEditJSON' not found

### ISSUE THREAD

**Issue by misha-antonenko** [microsoft/vscode-cpptools#9064] opened 2022-03-22 08:05 UTC
Issue Type: <b>Bug</b>

Removing the extension from `~/.vscode` with `rm -rf` and installing it again does not help

Extension version: 1.8.4
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id de7537ee-b7ff-4aa6-9ac1-40d3f0a20bb2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrc:30451274
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvidc:30447482
dockersurvey3cf:30453610
pynewfile477:30450038

```

</details>

**Comment by sean-mcmanus** [comment] 2022-03-22 17:26
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/8785 . It's fixed in 1.9.6 (pre-release), which should be identical to 1.9.7 which we plan to release tomorrow or so.

**Closed as completed by sean-mcmanus** 2022-03-22 17:26 UTC
Labels: duplicate
