### ISSUE TITLE
Support for standard importable headers

### ISSUE THREAD

**Issue by TerensTare** [microsoft/vscode-cpptools#7664] opened 2021-06-08 21:12 UTC
Type: Feature Request

I am aware that there are other issues tracking support for C++20 modules, but I wanted to propose a small "workaround". The standard mandates that standard headers are importable. (See [draft](http://eel.is/c%2B%2Bdraft/module.import#5))
> An importable header is a member of an implementation-defined set of headers that includes all importable C++ library headers ([headers]). H shall identify an importable header.

Thus, I believe that these headers should be `import`ed in C++20 instead of `#include`d. However, the C/C++ extension currently doesn't have  support for `import`ing headers of any kind, which totally breaks intellisense and such. What I propose is to have `import` support only for standard headers for the time being, and then expand to other compiler-dependent headers. I believe this will greatly improve the development experience with modules and set foundations for further improvements. Thank you.

**Comment by sean-mcmanus** [comment] 2021-06-08 22:54
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/6302 -- there is no difference between the standard header scenario versus other headers.

**Closed as completed by sean-mcmanus** 2021-06-08 22:54 UTC
Labels: duplicate
