### ISSUE TITLE
C++ IntelliSense memory leak

### ISSUE THREAD

**Issue by RARain** [microsoft/vscode-cpptools#3220] opened 2019-02-26 08:08 UTC
**Type: LanguageService**

**Describe the bug**
- OS and Version: ubuntu16.04
- VS Code Version: 1.31
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

1. Go to 'https://www.hikvision.com/cn/download_more_403.html'
2. Click on download  'SDK_V6.0.2.2(for Linux64)'
3. Extract and Open, click ./incCn/HCNetSDK.h in VsCode
4. Open SystemMonitor, watch the intellisense memory a moment
5. See error

**Expected behavior**

**Screenshots**

![selection_003](https://user-images.githubusercontent.com/15813725/53396880-919db480-39e0-11e9-9c55-48f9b9798395.png)

**Additional context**

**Comment by ben-the-hedgehog** [comment] 2019-03-01 14:50
Seeing this as well with Ubuntu 14.04, code-insiders 1.32.0, and C/C++ ext 0.21.0

**Comment by sean-mcmanus** [comment] 2019-03-02 04:14
Can you try the latest Insiders release? We improved the memory usage: https://github.com/Microsoft/vscode-cpptools/releases , although we didn't intentionally fix any "leak".

**Comment by ben-the-hedgehog** [comment] 2019-03-05 15:14
Still seeing the same issues with the pre-release version. Not sure if the issue is a "memory leak", but Intellisense uses up all of the available memory on startup.

**Comment by sean-mcmanus** [comment] 2019-03-05 23:57
@ben-the-hedgehog Are you on 32-bit Linux? The memory improvement we made doesn't work on 32-bit Linux.

**Comment by ben-the-hedgehog** [comment] 2019-03-06 14:52
I'm on 64 bit Ubuntu 14.04 
`4.4.0-131-generic #157~14.04.1-Ubuntu SMP Fri Jul 13 08:53:17 UTC 2018 x86_64 GNU/Linux`

**Comment by sean-mcmanus** [comment] 2019-03-06 19:17
This only repros for you when opening certain files, right? Do you have a lot of red or green squiggles from missing includes -- in that case it can cause our parser to accumulate an unusually large size. I think we will need some sort of repro in order to investigate/fix this, but I seem to recall on chromium I got 2 GB of usage and it was "by design", but I can re-check if that case got worse or not.

**Comment by nerdmaennchen** [comment] 2020-01-01 14:59
I think I'm experiencing the same thing.
I'm working tao::pegtl in a project and Intellisense eats all my RAM and swap (24GB total until it runs out of memory and crashes).

I love vscode but this behavior is really painfull for me as it renders vscode hardly usable for big (template heavy) C++ projects.

FYI: I'm on ARCH
Linux Urmel 5.4.6-arch3-1 #1 SMP PREEMPT Tue, 24 Dec 2019 04:36:53 +0000 x86_64 GNU/Linux

**Comment by sean-mcmanus** [comment] 2020-01-02 19:28
@nerdmaennchen Can you confirm you're using the C/C++ extension version 0.26.2 (and not 0.26.3-insiders2) and that the process using memory is Microsoft.VSCode.CPP.IntelliSense.Msvc.linux and not Microsoft.VSCode.CPP.Extension.linux (want to make sure it's not a different issue).

**Comment by nerdmaennchen** [comment] 2020-01-03 03:05
I was using 0.26.3-insiders2, indeed. 
However, after installing 0.26.2 I get the same thing :/
Also it is Microsoft.VSCode.CPP.IntelliSense.Msvc.linux eating all the memory.
![memory_usage_intellisense](https://user-images.githubusercontent.com/2685755/71705109-d708ea80-2e18-11ea-8f23-819b075fa530.jpg)

**Comment by nerdmaennchen** [comment] 2020-01-03 03:15
What helps in my case is to switch the "Intelli Sense Engine" from "default" to "Tag Parser".
The completion suggestions are not even remotely as good as with the default engine but it makes my system a lot more stable.

I really love VSCode for a multitude of reasons and would like my complaining here to not sound like I complain about your software.
On the contrary: You're building something awesome! Thank you so much for that!
The only thing I wish is that the memory usage of that awesome parser of yours would be less

Happy new year

**Comment by sean-mcmanus** [comment] 2020-01-03 20:26
@nerdmaennchen Your screenshot shows around 600 MB memory usage per IntelliSense process? That is actually normal/expected for many scenarios. It is odd (not normal) that the processes are so similar in size though. We intend to fix a bug that can cause the memory to increase to an unbounded amount after certain actions (I believe another bug is tracking that). We also do not query the OS for available memory, which can cause problems if your core count is too high compared to your available memory (i.e. too many IntelliSense processes could put a strain on memory after opening too many files), which we're also tracking with another issue (a potential workaround is to not keep as many files open, but Find All References can spawn a lot of temporary IntelliSense processes). I filed an issue to track IntelliSense process limitting in low memory scenarios at https://github.com/microsoft/vscode-cpptools/issues/4811 .

Tag Parser mode is not recommended unless as a last resort due to reduced functionality.

There's nothing wrong with complaining about our software -- it helps us prioritize what to fix or improve. Our C/C++ extension works well for most code bases, but some projects/users/machines hit issues that we're still working on fixing or finding repros for.

**Comment by nerdmaennchen** [comment] 2020-01-04 00:32
My screenshot shows 6387MB per process. Most of it is shared (due to forking and copy on write, I guess) amongst the processes. However, it uses 83% of memory ressources. And still... 16GB of virtual memory seems a little bit too plenty for parsing text files. I truly believe there is something fishy.

Also, I see the effect even when I have only a single file open with includes to template heavy headers.

Thanks for looking into this and for all your good work!

**Comment by sean-mcmanus** [comment] 2020-01-04 00:49
Ooops, sorry -- I saw it wrong -- yeah, ~6 GB is abnormally large. Is it that large soon after the process starts or does it accumulate memory after navigation/edits/etc.?

**Comment by nerdmaennchen** [comment] 2020-01-04 02:57
No worries, the font, colors and compression make it hard to read, indeed.
The effect starts as soon as I do anything that triggers the indexer e.g., hitting F12 when having selected a symbol.
The memory consumption grows steadily even if I don't touch the IDE after triggering the indexer.
After one or two minutes my system starts swapping and the memory consumption grows until the indexer crashes due to an out of memory situation.

**Comment by dakersnar** [comment] 2020-01-13 01:30
Has a fix for this been found? I'm having a similar issue, also while working with pegtl.

**Comment by sean-mcmanus** [comment] 2020-01-13 22:25
@dakersnar Not yet. You're getting an IntelliSense process using how much memory? Is the pegtl a project we can try out? Is it https://github.com/taocpp/PEGTL or some other one? Can you provide any other repro info?

**Comment by nerdmaennchen** [comment] 2020-01-14 02:34
As it happens, my project involving pegtl is now in a usable state and is on GH

To reproduce the memory issue, please check out the "demo" branch of https://github.com/nerdmaennchen/qrqma and then try F12 when the corsor is on any symbol from the pegtl namespace and then watch the memory consumption.

Thanks again for looking into this!

**Comment by sean-mcmanus** [comment] 2020-01-14 03:13
@nerdmaennchen I'm not reproing the bug. How are you configuring that project? Our extension doesn't currently support auto-configuration of Makefile projects. What compilerPath are you using with any defines? I tried with g++-8. If you can do a C/C++: Log diagnostics with the file that causes the memory issue that could help determine what configuration info is being used.

**Comment by nerdmaennchen** [comment] 2020-01-14 03:28
To compile/index the demo you should not need to specify any fancy compiler flags apart from C++17 and -Isrc/.
The actual compile call (for src/main.cpp) would be the following:
~~~bash
g++   -O0 -Isrc/ -Wextra -Wredundant-decls -Wall -Wundef -std=c++17 -I -gsplit-dwarf -o obj/src/main.cpp.o -c src/main.cpp
~~~

Within a new vscode window I simply do the following:
- open die folder that contains the repository
- navigate to src/qrqma/grammar/atom.h
- in line 12 mark the ``one`` part of ``pegtl::one``
- hit F12

If you'd like to build the project (which should no be necessary for this issue); simply call "make" from within the projects root directory.

Or create a build task in your tasks.json to build it from within vscode:
~~~json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "make",
            "args": [
                "-j5"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "problemMatcher": "$gcc"
        }
    ]
}
~~~

**Comment by Colengms** [comment] 2020-02-14 21:13
The issue this was originally created to track has been addressed.  Memory usage of the IntelliSense process is monitored and is reset if unaccounted for growth is detected.  Though, 3G is not unreasonable for the intelliSense process to use with a sufficiently complex codebase.

There may still be issues related to memory.  If you are seeing a similar problem, please open a new issue with specific repro information, rather than adding a potentially new scenario to an existing memory related issue.

**Closed as completed by Colengms** 2020-02-14 21:13 UTC
Labels: bug, Language Service, performance, investigate: repro
