### ISSUE TITLE
When start c++ gdb debug, not launch externalConsole

### ISSUE THREAD

**Issue by rjifu** [microsoft/vscode-cpptools#7969] opened 2021-08-13 08:23 UTC
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 10 Home
- VS Code Version: 1.59.0
- C/C++ Extension Version: v1.6.0-insiders
- Other extensions you installed (and if the issue persists after disabling them):
      Japanese Language Pack for Visual Studio Code - v1.59.3
      Remote - WSL - v0.58.2 (invalid)
      Tabnine (invalid)
      WSL workspaceFolder - v1.1.2 (invalid)
- A clear and concise description of what the bug is. When I run debug, console don't launch. And same time, not stop at breakpoint.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
[my settings]
launch.json
{
"version": "0.2.0",
"configurations": [
{
"name": "(gdb) 起動",
"type": "cppdbg",
"request": "launch",
"program": "${fileDirname}/${fileBasenameNoExtension}.exe",
"args": [],
"stopAtEntry": false,
"cwd": "${workspaceFolder}",
"environment": [],
"externalConsole": true,
"MIMode": "gdb",
"miDebuggerPath": "C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/gdb.exe",
"setupCommands": [
{
"description": "gdb の再フォーマットを有効にする",
"text": "-enable-pretty-printing",
"ignoreFailures": true
}
],
"preLaunchTask": "g++.exe build active file"
}
]
}

1. run debug ( press F5 key)
2. nothing happen.
 This issue have appeared since today. yesterday, there was no problem. I did't touch setting.
I would appreciate it if you help this issue.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.
-> I include logging, But there are no output.

**Comment by rjifu** [comment] 2021-08-13 10:50
additional information.
When I Installed C/C++ Extension Version v1.5.1, it became that console launch when debugging.

**Comment by gokunik** [comment] 2021-08-13 14:24
I don't know what might be the cause or what might be the solution but just want to provide information related to this issue.

Even if the externalConsole set to false it is shows the same behavior, Nothing happens!. When I try to debug it just builds the program and that's it. seems like the debugger is not getting triggered or something.

This issue came in the recent insiders update( Version 1.6.0-insiders: August 12, 2021 ). Till yesterday everything was fine and when I opened up my vs code today, show this update and right after the update, this issue came. initially, I thought something is wrong with my config files but everything is untouched, I also tried to change a few configs in the hope that it might work but nothing happens.

Then I remembered that I have updated the extension so to check if the update was the reason, I re-installed the c/c++ extension without the insiders update ( Version 1.6.0-insiders: August 12, 2021 ) and it worked. But right after installing the extension it updates the extension automatically and if you do not reload the window it will work fine but the moment you reload and new update's changes are applied this problem arises again.

When I start debugging this is what happens 👇. The file builds successfully but after that nothing happens. The debugging control also show up for few split seconds and then gone. 
![image](https://user-images.githubusercontent.com/57342034/129370094-905289e0-9f8c-4d13-9fd2-6f7f493f553d.png)

**Comment by fucker-cracker** [comment] 2021-08-13 14:39
Fxxk the insiders update

**Comment by gsh1150** [comment] 2021-08-13 15:07
Me too. The problem of updating.

**Comment by gokunik** [comment] 2021-08-13 15:14
A temporary solution can be is to disable the automatic extension updates and then re-install the extension. it will still install the previous version of the extension which works fine and not the recent update which causes this problem.

**Comment by WardenGnaw** [comment] 2021-08-13 18:21
Duplicate of: https://github.com/microsoft/vscode-cpptools/issues/7971

**Closed as completed by WardenGnaw** 2021-08-13 18:21 UTC
Labels: duplicate, debugger, regression

**Comment by rjifu** [comment] 2021-08-14 03:01
@gokunik 
I appreciate your comments. it's helped solving the problem I have.
And, I'll watch over #7971.
