### ISSUE TITLE
The language server crashed 5 times in the last 3 minutes. It will not be restarted. WHEN Update v1.6.0 TO v1.7.0-insiders

### ISSUE THREAD

**Issue by EdgarRSSA** [microsoft/vscode-cpptools#8201] opened 2021-09-29 03:11 UTC
Bug type: General

**Describe the bug**
- OS and Version:  
**Debian 10 buster | Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220)  #1 SMP Fri Apr 2 22:23:49 UTC 2021**
- VS Code Version: 
**1.60.2 7f6ab5485bbc008386c4386d08766667e155244e x64**
- C/C++ Extension Version: **v1.7.0-insiders**
- Other extensions you installed: **REQUIRED -> Remote-Containers v0.194.3**

**To Reproduce**
1.Open vscode from **WSL/Debian `user@host /home/user/code/cdlinux/$ code .`**.
2. Using **Remote-Containers** RUN **Reopen in container.**
3. Reopen Container **SUCCESS**
4. **NOTIFICATIONS "The C/C++ Extension has been updated to version 1.7.0-insiders. Please reload the window for the changes to take effect."**
5. Click on: **RELOAD**
6. **REOPEN SUCCESS**
7. Open **any file with extension .c .cpp .h**
8. Error: **"The language server crashed 5 times in the last 3 minutes. It will not be restarted."**

**After this error, Im back to v1.6.0 and all works fine. ¿Someone knows why the error does in v1.7.0-insiders?**

**Expected behavior**
NORMAL UPDATE AND START EXTENSION 

**ADITIONAL INFO**
**Docker-info**
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 2.918GiB
 Name: docker-desktop
 ID: MQ22:NE7B:GLBD:4A2J:NTT3:S3R4:TMN4:GQH5:FZ7C:6OEE:QZDK:ILNT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**REMOTE EXTENSION HOST LOG**
[2021-09-29 02:26:03.559] [exthost] [info] extension host started
[2021-09-29 02:26:03.608] [exthost] [info] Lock '/home/coder/.vscode-server/data/User/workspaceStorage/821376919bcfd6edb9d1e52fab1f5320/vscode.lock': Lock acquired.
[2021-09-29 02:26:04.019] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-09-29 02:26:04.021] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/extensions/debug-auto-launch/dist/extension
[2021-09-29 02:26:04.066] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-09-29 02:26:04.068] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/extensions/git/dist/main
[2021-09-29 02:26:04.756] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools {"startup":true,"extensionId":{"value":"ms-vscode.cpptools","_lower":"ms-vscode.cpptools"},"activationEvent":"workspaceContains:/.vscode/c_cpp_properties.json"}
[2021-09-29 02:26:04.757] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main
[2021-09-29 02:26:06.076] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-09-29 02:26:06.076] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/extensions/github/dist/extension.js
[2021-09-29 02:26:06.459] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-09-29 02:26:06.459] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/extensions/ms-vscode.js-debug/src/extension.js
[2021-09-29 02:26:08.980] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:json"}
[2021-09-29 02:26:08.991] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/extensions/configuration-editing/dist/configurationEditingMain
[2021-09-29 02:26:09.058] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"extensionId":{"value":"vscode.extension-editing","_lower":"vscode.extension-editing"},"activationEvent":"onLanguage:json"}
[2021-09-29 02:26:09.058] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/extensions/extension-editing/dist/extensionEditingMain
[2021-09-29 02:26:09.232] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:json"}
[2021-09-29 02:26:09.233] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/extensions/json-language-features/client/dist/node/jsonClientMain
[2021-09-29 02:26:09.827] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":false,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"onLanguage:json"}
[2021-09-29 02:26:09.828] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/extensions/npm/dist/npmMain
[2021-09-29 02:26:10.053] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:jsonc"}
[2021-09-29 02:26:10.053] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/extensions/typescript-language-features/dist/extension
[2021-09-29 02:26:10.881] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-09-29 02:26:10.882] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/extensions/emmet/dist/node/emmetNodeMain
[2021-09-29 02:26:10.994] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-09-29 02:26:10.994] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/coder/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/extensions/merge-conflict/dist/mergeConflictMain
**[2021-09-29 02:26:11.028] [exthost] [info] eager extensions activated**
**[2021-09-29 02:27:26.014] [exthost] [error] [ms-vscode.cpptools] provider FAILED**
**[2021-09-29 02:27:26.014] [exthost] [error] Error: Connection got disposed.
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58625:25)
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:59545:35)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:61627:42)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:62817:15)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:61614:18)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57401:36)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57975:26)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57401:36)
	at StreamMessageReader.fireClose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58791:27)
	at Socket.<anonymous> (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58831:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)**
[2021-09-29 02:27:26.015] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-09-29 02:27:26.015] [exthost] [error] Error: Connection got disposed.
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58625:25)
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:59545:35)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:61627:42)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:62817:15)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:61614:18)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57401:36)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57975:26)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57401:36)
	at StreamMessageReader.fireClose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58791:27)
	at Socket.<anonymous> (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58831:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[2021-09-29 02:27:29.138] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-09-29 02:27:29.139] [exthost] [error] Error: Connection got disposed.
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58625:25)
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:59545:35)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:61627:42)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:62817:15)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:61614:18)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57401:36)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57975:26)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57401:36)
	at StreamMessageReader.fireClose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58791:27)
	at Socket.<anonymous> (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58831:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[2021-09-29 02:27:30.675] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-09-29 02:27:30.675] [exthost] [error] Error: Connection got disposed.
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58625:25)
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:59545:35)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:61627:42)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:62817:15)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:61614:18)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57401:36)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57975:26)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57401:36)
	at StreamMessageReader.fireClose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58791:27)
	at Socket.<anonymous> (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58831:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[2021-09-29 02:27:32.271] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-09-29 02:27:32.272] [exthost] [error] Error: Connection got disposed.
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58625:25)
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:59545:35)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:61627:42)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:62817:15)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:61614:18)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57401:36)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57975:26)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:57401:36)
	at StreamMessageReader.fireClose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58791:27)
	at Socket.<anonymous> (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/dist/main.js:58831:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)

**Comment by EdgarRSSA** [comment] 2021-09-29 04:18
Sorry, Yes, The Distro is "Debian 10 (buster)". Ill set that -> "The workaround is to downgrade to 1.6.0 (set C_Cpp.updateChannel to "Default"). 👍🏼

**Comment by Colengms** [comment] 2021-09-29 23:04
Hi @EdgarRSSA .  I tried installing Debian 10.2.0 in a VM, but could not repro any obvious issue.  I've also tried install Debian as a WSL distro, but only Debian 11 was available in the Microsoft Store (and did not repro an issue).

Could you try deleting the contents of the extension directory (`/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders`) and re-installing the extension?

**Comment by chengxxf** [comment] 2021-09-30 09:09
[Error - 4:47:04 PM] Connection to server got closed. Server will not be restarted.
/home/chengxianfu.cxf/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/bin/cpptools: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/chengxianfu.cxf/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders/bin/cpptools)

vscode connect the remote server error, everytime open a new folder on remote, need reinstall cpp plugin

**Comment by Colengms** [comment] 2021-10-01 00:34
Closing as a dupe of #8192 .

**Closed as completed by Colengms** 2021-10-01 00:34 UTC

**Comment by michelleangela** [comment] 2021-10-01 00:54
1.7.0-insiders2 is now available with a fix for this issue. https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2

**Comment by EdgarRSSA** [comment] 2021-10-01 01:39
@michelleangela Succesfully installed BUT :( The IntelliSense not works! 

OUPUT C/C++ LOG
  loggingLevel: Warning 
  uv_pipe_bind failed with ret = -98
  Failed to spawn IntelliSense process:
  uv_pipe_bind failed with ret = -98
  ...

REMOTE SERVER LOG
[2021-10-01 01:18:31.114] [remoteagent] [info] Installing extension: ms-vscode.cpptools
[2021-10-01 01:18:40.926] [remoteagent] [info] Extracted extension to /home/coder/.vscode-server/extensions/.bdb263c9-088d-4682-b405-20d928178a38: ms-vscode.cpptools
[2021-10-01 01:18:41.291] [remoteagent] [info] Renamed to /home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2
[2021-10-01 01:18:41.313] [remoteagent] [info] Extracting completed. ms-vscode.cpptools
[2021-10-01 01:18:41.495] [remoteagent] [info] Extension installed successfully: ms-vscode.cpptools
[2021-10-01 01:18:48.455] [remoteagent] [info] [::ffff:127.0.0.1][4e1e5d5d][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2021-10-01 01:18:49.793] [remoteagent] [info] [::ffff:127.0.0.1][bd8459bc][ExtensionHostConnection] <688> Extension Host Process exited with code: 0, signal: null.
[2021-10-01 01:19:19.304] [remoteagent] [info] [::ffff:127.0.0.1][3d49ef36][ManagementConnection] New connection established.
[2021-10-01 01:19:21.713] [remoteagent] [info] [::ffff:127.0.0.1][5ee8013f][ExtensionHostConnection] New connection established.
[2021-10-01 01:19:21.759] [remoteagent] [info] [::ffff:127.0.0.1][5ee8013f][ExtensionHostConnection] <6350> Launched Extension Host Process.
[2021-10-01 01:23:37.705] [remoteagent] [info] [::ffff:127.0.0.1][3d49ef36][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2021-10-01 01:23:38.972] [remoteagent] [info] [::ffff:127.0.0.1][5ee8013f][ExtensionHostConnection] <6350> Extension Host Process exited with code: 0, signal: null.
[2021-10-01 01:24:09.686] [remoteagent] [info] [::ffff:127.0.0.1][571de748][ManagementConnection] New connection established.
[2021-10-01 01:24:13.488] [remoteagent] [info] [::ffff:127.0.0.1][ba3fc349][ExtensionHostConnection] New connection established.
[2021-10-01 01:24:13.518] [remoteagent] [info] [::ffff:127.0.0.1][ba3fc349][ExtensionHostConnection] <6951> Launched Extension Host Process.
