### ISSUE TITLE
@warning / \warning sections from doxygen comments are not displayed in simplified view

### ISSUE THREAD

**Issue by kisielk** [microsoft/vscode-cpptools#7705] opened 2021-06-16 18:06 UTC
Bug type: Language Service

**Describe the bug**
- OS and Version: macOS 11.4
- VS Code Version: 1.57.0
- C/C++ Extension Version: 1.5.0-insiders

**Steps to reproduce**

1. Document a function and use the `@warning` or `\warning` doxgen command.
2. Hover over the function name or any usage of the function to display the documentation popup. 

**Expected behavior**
The popup should include the `@warning` paragraph but it does not.

**Screenshots**
Code example:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/58618/122269968-aee93c00-ce92-11eb-8f11-a8b82b16a448.png">

Result when hovering over `ApplyIn`:
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/58618/122270089-cd4f3780-ce92-11eb-8e9e-904e32d8c8e7.png">

**Comment by michelleangela** [comment] 2021-06-16 18:29
@kisielk 
You can set the setting `C_Cpp.simplifyStructuredComments` to false to display all Doxygen tags. 
![image](https://user-images.githubusercontent.com/38734287/122273279-1ce33280-ce96-11eb-8309-c8c4fd71111f.png)

**Comment by kisielk** [comment] 2021-06-16 18:35
Yes but that also removes all the nice formatting of the other parameters. Also something that's labelled "warning" is usually pretty important so should be shown in the simplified view.

**Comment by Kaleb-JCI** [comment] 2021-09-16 22:58
I agree that `@warning` is important and should be shown in the simplified view! I think this also applies to `@attention`.

For example, I'm working on an existing codebase, and I sometimes run across functions where the caller is responsible for freeing up memory allocated within the function. This is information that _should_ be visible on hover (and since newlines don't stick around, the only way I can currently add this to a tooltip and still have it visually stand out [without telling people to adjust their default extension settings] is to add an `@exception` tag and mention it in there even though it's not throwing an exception).

**Comment by bobbrow** [comment] 2022-08-31 18:22
I'm going to close this as a duplicate of #8525.  What we are planning to do with that issue is allow you to customize the tooltip to include the tags that are important to you.

**Closed as not planned by bobbrow** 2022-08-31 18:22 UTC
Labels: duplicate, Language Service, Feature Request, Feature: Doc comments

**Comment by Kaleb-JCI** [comment] 2022-09-13 20:28
> I'm going to close this as a duplicate of #8525. What we are planning to do with that issue is allow you to customize the tooltip to include the tags that are important to you.

I understand that there are a lot of people with a lot of different wants/needs for the tooltip, so a more general solution makes sense. Maybe just turn on the `warning` tag by default? It definitely feels like a _WARNING_ should be visible by default; That's the point of a warning. That's why they put up signs warning about dangerous road conditions instead of having people call a phone number or flip through a book every time they're about to turn down a new road to see if there's anything dangerous to worry about.

If not, I'm assuming that this would be something that could be saved as a workspace setting and checked in with the codebase (so new and existing users don't have to be instructed to make configuration changes before working on the code to ensure that they see warnings)?

That's just my two cents; Hopefully it doesn't come across as ungrateful because I am a big fan of this extension, use it daily, and am very grateful to everyone who puts effort into maintaining it. ❤️

**Comment by sean-mcmanus** [comment] 2022-09-14 04:29
@Kaleb-JCI Showing warnings by default seems good to me.
