### ISSUE TITLE
C/C++ extensions, remote development: all C++ features suddenly inhibited for any project on a single remote host

### ISSUE THREAD

**Issue by vectraCpc** [microsoft/vscode-cpptools#12174] opened 2024-04-08 09:55 UTC
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.88.0 and before
- C/C++ Extension Version: 1.3.0 (extension pack); 1.19.9 (c/c++)
- If using SSH remote, specify OS of remote machine: Oracle Linux Server 8.5

### Bug Summary and Steps to Reproduce

Bug Summary: all C++ extension features ceased working one day, on a given remote host, and continue working onto other hosts.

Steps to reproduce:
1. Be inside my corporate network
2. Open any remote project on a given host server; they all used to work flawlessly 
3. F1; C-C++:Edit Configurations UI, or any other function that shows up
4. "Activating Extensions" message shows up in the lower tray on the outer-right and disappears, then nothing happens

Expected behavior: a menu shows up.
Please notice that this erratic behavior stands for any C-C++ command. C-C++ Log diagnostic is no longer proposed to me!
When I right-click into a C++ code file, the menu is incomplete, and the few functions proposed don't even work (switch header/source).

The right-click menu on the 'broken' remote host, any project:
![nope](https://github.com/microsoft/vscode-cpptools/assets/159932080/cd64dde7-959f-433f-a4c5-fbb675e5e44d)
The same menu on the 'still working' remote:
![yesh](https://github.com/microsoft/vscode-cpptools/assets/159932080/0e791f85-4ea6-4542-bb3b-120a1bbb9ce5)

I tried reinstalling vscode-server on the remote host: it worked, but no extension accepted to download itself. I tried to install some extensions manually: some installed, some not. In any case, the c++ extension refused to work.

At the very same time, my other projects continue working on another remote host, that fortunately kept all its extensions. I can still add an extension from the network, no problem to report.
I suspect a configuration issue in my over-protected corporate network, but how can I figure it out given the diagnostic methods I have left?

Thanks for your answer or any hint.

### Configuration and Logs

```shell
The file is not present, not even settings.json. I copied such files from same project on a remote that works, but it did not help.
The 2 latter are not available, because the extension is so completely neutralized that options don't even show up.
```

### Other Extensions

Issue still present on the remote server even after a remote server reinstall. Extensions refuse to install through networks, and I managed to install only the c-c++ core extension by hand.
No change.

**Comment by sean-mcmanus** [comment] 2024-04-08 18:30
@vectraCpc It sounds like our extension is not activating. Are you able to repro the issue with any other extensions? Can you try filing a bug against the VS Code remote extensions at https://github.com/microsoft/vscode-remote-release/issues  ?

**Comment by vectraCpc** [comment] 2024-04-08 18:50
Hello Sean!

Yes, I should have opened a ticket in that remote section, had I found it before! 

I took time to notice the C++ extension was not working any longer because I was mostly busy with other tasks. The git extension, among others, is working perfectly. I will check tomorrow if functions from other language plugins work on this cursed server, or if it only affects the C++ plugin.

Please don't forget that I can't download any extension in the cursed server while absolutely evereything works fine on the other server. Also, since I can't ownload extensions or even install some of these using vsix packages, I transfered a copy of my ~/.vscode-server from the working server to the cursed one. Git worked on the cursed server before and after the copy.

**Comment by vectraCpc** [comment] 2024-04-09 08:06
Ctd:

The Python plugin seems to run fine in both servers. The right-click menu is the same, I can peek definitions & references, unlike in C++. 

It looks like the problem mostly occurs with the C++ extension inside the 'cursed' remote only, but please keep in mind the other problems arising in this same server (can't download any extension at all, manual install not working for some).

I will shortly publish a ticket in the remote board though.

**Comment by WinCPP** [comment] 2024-04-09 10:09
@vectraCpc, although I "struck out" my earlier comment, I am back to the same issue today once again. None of the extensions seems to have got activated. VSCode is taking inordinately long time to startup. Looks like I am hitting another manifestation of some same root cause. Any pointers to what data you are gathering, so that I can help give proper diagnostics? Not sure if there i some VSCode log which will dump everything.

**Comment by vectraCpc** [comment] 2024-04-09 14:52
Hi,

I reverted to 1.85.2, but it did not improve much in my case. 
The C++ is still not working in the 'cursed' server, and I can't install new plugins. I still can find & use previous plugins though.

As a matter of  fact, the 'cursed' remote is Oracle Linux 8.5 and the 'spared' remote is running Centos 7: I had the same banner issue but everything works fine though.

I am not sure of the use I could make of your logs, just because I'm not skilled enough and not used to read them. But if the people in charge may need them, it would be very helpful.

Anyway, thank you for your time, it's much appreciated!

**Comment by vectraCpc** [comment] 2024-04-17 12:21
Hello @sean-mcmanus ,

Please let me know if you need more information, I'll do the best I can.
So far, I feel like I provided everything I was expected to, but don't hesitate to ask if I forgot anything.

I did not make any progress from my side since last week, though. The VScode update that  occured since I opened the ticket did not change anything, unfortunately.

Best regards,
J.B

**Comment by sean-mcmanus** [comment] 2024-04-17 22:40
@vectraCpc I'm closing this issue because I don't think our extension is the cause.

**Closed as not planned by sean-mcmanus** 2024-04-17 22:40 UTC
Labels: external

**Comment by vectraCpc** [comment] 2024-04-18 13:34
@sean-mcmanus 
Before I posted, I was actually thinking a local network issue should cause the problem, considering the same codebase runs simultaneously on a second remote host but not on the first.
Honestly, I was expecting some help or troubleshoot checklist in order to find out the specific network restriction that impedes one remote and not the other. But maybe this topic is not the best fit for this?

Best regards,

**Comment by sean-mcmanus** [comment] 2024-04-18 21:45
@vectraCpc Sorry, I'm not familiar with what trouble shooting steps to try.
