### ISSUE TITLE
Chinese appears in the path, the resulting bug.

### ISSUE THREAD

**Issue by j-xzy** [microsoft/vscode-cpptools#959] opened 2017-08-08 14:51 UTC
![image](https://user-images.githubusercontent.com/22634735/29077928-ba0096d6-7c8b-11e7-9632-b58e08e82661.png)

After press F5....

![image](https://user-images.githubusercontent.com/22634735/29080473-6b6eed68-7c92-11e7-9b03-4088296f8188.png)

error: can't open "main.cpp",no found  ...

This is a duplicate of #602.

OS: ubuntu 16.04 .
vscode: 1.14.2.

``` json
// task.json
{
    "version": "0.1.0",
    "command": "g++",
    "isShellCommand": true,
    "showOutput": "always",
    "args": ["-g", "main.cpp"]
}
```
``` json
// launch.json
{
{
  "version": "0.2.0",
  "configurations": [
{
  "name": "(gdb) Launch",
  "type": "cppdbg",
  "request": "launch",
  "program": "${workspaceRoot}/a.out",
  "args": [],
  "stopAtEntry": false,
  "cwd": "${workspaceRoot}",
  "environment": [],
  "externalConsole": true,
  "MIMode": "gdb",
  "preLaunchTask": "g++",
  "setupCommands": [
      {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
      }
  ]
}
  ]
}
}
```

**Comment by pieandcakes** [comment] 2017-08-17 20:56
@wu38607 If this is a duplicate of #602, we will track with that one.

**Closed as completed by pieandcakes** 2017-08-17 20:56 UTC
Labels: debugger
