### ISSUE TITLE
Bug Summary: cannot index all the files in includepath

### ISSUE THREAD

**Issue by Nononoa-Zoro** [microsoft/vscode-cpptools#10166] opened 2022-11-18 04:20 UTC
### Environment

- OS and version: ubuntu 16.04.1
- VS Code: 1.69.2
- C/C++ extension: 1.12.0
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

Steps to reproduce:
1. when i use ssh-remote in vscode , i had config the includepath like /dir/headers/** but when i open my .c file in vscode, there is red squirrel that tell me includepath error. In fact, not all the .h file in includepath cannot be finded, only a part of them cannot be finded. But when i print F12 to index these file, the red squirrel will be cleared.

**Comment by sean-mcmanus** [comment] 2022-11-18 18:44
Version 1.12.0 is old. Can you upgrade to 1.12.4 or 1.13.4? When you use the C/C++: Log Diagnostics command from the Command Palette is the include path shown in the Includes section? What do you mean by "print F12 to index these files"? What headers can't be found? Are they under "/dir/headers" or are they system headers?

**Comment by Hansformer** [comment] 2022-11-25 13:38
I have a similar problem. IncludePath doesn't seem to be able to parse header files in the working directory.
I chose the inside version to see if this bug would've been fixed in the insiders edition already but alas.

OS and Version: Windows 10 Pro 21H2
VS Code: 1.74.0-insider
C/C++ Extension: 1.13.4
OS and version of remote machine (if applicable):
GDB / LLDB version:

Steps to reproduce:
1. Create a C source file test.c and a header file testheader.h
2. Write a function in testheader.h and then include testheader.h in your C source file and try to invoke the function from the header file.
3. IntelliSense then compains that cannot open source file "testheader.h"

**Comment by sean-mcmanus** [comment] 2022-11-28 21:43
@Hansformer I'm not able to repro the issue. Are you using `<>` or `""` style `#include`? Either should work, but if you run the C/C++: Log Diagnostics command from the Command Palette you should see the include path add a workspace folder for the `<>` case, while the `""` case should automatically add the file's directory (internally). Does it work if you remove the "**" from the workspace folder path? That might indicate some issue with the recursive includes feature.

**Comment by Hansformer** [comment] 2022-12-01 12:53
This is a strange issue for me. I tried reproducing the issue in another directory and it worked as it should.
It seems that it works in some directories but not others.
I've tried resetting the .vscode settings and deleting the vscode specific directories.
I've tried using both `${workspaceFolder}/**` and `${workspaceFolder}` when the header files are in the root directory.

The `<>` style includes don't work either, but I assume that is because I haven't specified a compiler for this project. I'm compiling the code under a virtual machine, but editing the code from Windows side.

Anyways, since it sometimes works, I'm pretty sure the problem is on my end and not the intellisense addon.

**Comment by sean-mcmanus** [comment] 2022-12-08 01:59
You may want to try doing a Reset IntelliSense Database in case it's in some bad state where it thinks some folder doesn't exist.

Can this be closed?

**Comment by Hansformer** [comment] 2022-12-08 16:14
I sort of hijacked @Nononoa-Zoro 's issue,  so I guess they should comment on that, but from my perspective, sure.

**Comment by sean-mcmanus** [comment] 2022-12-09 02:27
Also, if this is still an issue it may be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/10224

**Closed as not planned** 2022-12-09 02:26 UTC
Labels: Language Service, more info needed, Feature: Configuration
